/**
 * H1 문형 사전 — HSK 1급 핵심 구문·표현 전수 커버 레이어 (SCHEMA.md 참고)
 * 챕터(grammar/h1.js)가 '이해'라면 이 사전은 '전수 검색'.
 */
export default {
  level: "H1",
  title: "1급 문형 사전",
  desc: "是·有·在 기본 술어부터 不・没 부정, 吗・의문사 의문, 양사·시간·了까지 — HSK 1급 핵심 문형을 기능별로 모두 모은 전수 검색 사전.",
  themes: [
    {
      name: "기본 술어문",
      items: [
        {
          pattern: "A 是 B",
          pinyin: "shì",
          ch: "h1-01-shi",
          conn: "주어 + 是 + 명사",
          ko: "A는 B이다 (명사 술어)",
          ex: { zh: "我是学生。", pinyin: "wǒ shì xuésheng", ko: "저는 학생이에요." },
          ex2: { zh: "他是中国人。", pinyin: "tā shì Zhōngguó rén", ko: "그는 중국인이에요." },
          note: "是는 명사를 잇는 '~이다'. 형용사 앞에는 是를 쓰지 않아요 (×我是高).",
        },
        {
          pattern: "주어 + 很 + 형용사",
          pinyin: "hěn",
          ch: "h1-01-shi",
          conn: "주어 + (很) + 형용사 (是 없음)",
          ko: "A는 ~하다 (형용사 술어, 是 없이 很으로)",
          ex: { zh: "今天很热。", pinyin: "jīntiān hěn rè", ko: "오늘은 더워요." },
          ex2: { zh: "她很漂亮。", pinyin: "tā hěn piàoliang", ko: "그녀는 예뻐요." },
          note: "형용사 술어 앞엔 보통 很을 붙여요. 여기서 很은 '매우'보다 어조를 고르는 역할.",
        },
        {
          pattern: "주어 + 동사 + 목적어",
          pinyin: "—",
          ch: "ot-04-word-order",
          conn: "주어 + 동사 + 목적어 (SVO 어순)",
          ko: "A가 B를 ~하다",
          ex: { zh: "我喝茶。", pinyin: "wǒ hē chá", ko: "저는 차를 마셔요." },
          ex2: { zh: "他看书。", pinyin: "tā kàn shū", ko: "그는 책을 봐요." },
          note: "중국어 어순은 SVO. 한국어 SOV와 달라 목적어가 동사 뒤에 와요.",
        },
        {
          pattern: "A 有 B",
          pinyin: "yǒu",
          ch: "h1-02-you",
          conn: "주어 + 有 + 목적어",
          ko: "A는 B가 있다 / B를 가지고 있다 (소유)",
          ex: { zh: "我有一个妹妹。", pinyin: "wǒ yǒu yí ge mèimei", ko: "저는 여동생이 한 명 있어요." },
          ex2: { zh: "他没有钱。", pinyin: "tā méiyǒu qián", ko: "그는 돈이 없어요." },
          note: "有의 부정은 不有가 아니라 반드시 没有예요.",
        },
        {
          pattern: "장소 + 有 + 명사",
          pinyin: "yǒu",
          ch: "h1-02-you",
          conn: "장소 + 有 + 명사 (존재)",
          ko: "(어떤 장소)에 ~이 있다",
          ex: { zh: "桌子上有书。", pinyin: "zhuōzi shang yǒu shū", ko: "책상 위에 책이 있어요." },
          ex2: { zh: "家里没有人。", pinyin: "jiā li méiyǒu rén", ko: "집에 사람이 없어요." },
          note: "'장소+有+사물'은 막연한 존재를 나타내요 (영어 there is).",
        },
        {
          pattern: "A 在 + 장소",
          pinyin: "zài",
          ch: "h1-09-time-place",
          conn: "주어 + 在 + 장소",
          ko: "A는 (어떤 장소)에 있다 (소재)",
          ex: { zh: "我在学校。", pinyin: "wǒ zài xuéxiào", ko: "저는 학교에 있어요." },
          ex2: { zh: "妈妈不在家。", pinyin: "māma bú zài jiā", ko: "엄마는 집에 안 계세요." },
          note: "在의 부정은 不在. '특정한 것이 어디 있다'는 在, '어디에 무엇이 있다'는 有.",
        },
        {
          pattern: "주어 + 在 + 동사",
          pinyin: "zài",
          ch: "h2-03-zai-progressive",
          conn: "주어 + 在 + 동사 — ~하는 중",
          ko: "~하고 있다",
          ex: { zh: "我在吃饭。", pinyin: "wǒ zài chī fàn", ko: "저는 밥 먹고 있어요." },
          ex2: { zh: "他在看书。", pinyin: "tā zài kàn shū", ko: "그는 책을 보고 있어요." },
          note: "在 + 동사는 동작의 진행을 나타내요.",
        },
        {
          pattern: "A 叫 + 이름",
          pinyin: "jiào",
          conn: "주어 + 叫 + 이름",
          ko: "A의 이름은 ~이다",
          ex: { zh: "我叫李明。", pinyin: "wǒ jiào Lǐ Míng", ko: "제 이름은 리밍이에요." },
          ex2: { zh: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi", ko: "이름이 뭐예요?" },
        },
        {
          pattern: "주어 + 是…的",
          pinyin: "shì…de",
          ch: "h1-07-de-possessive",
          conn: "주어 + 是 + 명사 + 的 (소유·소속)",
          ko: "~의 것이다 / ~에 속하다",
          ex: { zh: "这是我的书。", pinyin: "zhè shì wǒ de shū", ko: "이건 제 책이에요." },
          ex2: { zh: "那不是他的。", pinyin: "nà bú shì tā de", ko: "그건 그의 것이 아니에요." },
          note: "的는 '~의'. 명사를 생략하고 '~의 것'으로도 써요 (我的 = 내 것).",
        },
        {
          pattern: "주어 + 동사 + 대상 + 사물",
          pinyin: "—",
          ch: "h2-07-prepositions",
          conn: "给/教 등 + 대상(사람) + 사물 (이중목적어)",
          ko: "~에게 ~을 …하다",
          ex: { zh: "老师教我们汉语。", pinyin: "lǎoshī jiāo wǒmen Hànyǔ", ko: "선생님이 우리에게 중국어를 가르쳐요." },
          ex2: { zh: "他给我一本书。", pinyin: "tā gěi wǒ yì běn shū", ko: "그가 저에게 책 한 권을 줘요." },
          note: "给·教 같은 동사는 '사람+사물' 두 목적어를 나란히 받아요.",
        },
        {
          pattern: "주어 + 喜欢 + 명사/동사",
          pinyin: "xǐhuan",
          ch: "h1-12-modal-wishes",
          conn: "喜欢 + 명사/동사구 (좋아함)",
          ko: "~을 좋아하다 / ~하기를 좋아하다",
          ex: { zh: "我喜欢中国菜。", pinyin: "wǒ xǐhuan Zhōngguó cài", ko: "저는 중국 요리를 좋아해요." },
          ex2: { zh: "他喜欢看书。", pinyin: "tā xǐhuan kàn shū", ko: "그는 책 읽는 걸 좋아해요." },
          note: "喜欢 뒤엔 명사도 동사구도 올 수 있어요.",
        },
        {
          pattern: "주어 + 去/来 + 동사",
          pinyin: "qù/lái",
          ch: "h1-08-serial-verbs",
          conn: "去/来 + 동작 — 잇따른 두 동작 (연동문)",
          ko: "~하러 가다/오다",
          ex: { zh: "我去商店买东西。", pinyin: "wǒ qù shāngdiàn mǎi dōngxi", ko: "저는 가게에 물건 사러 가요." },
          ex2: { zh: "他来看我。", pinyin: "tā lái kàn wǒ", ko: "그가 저를 보러 와요." },
          note: "동작이 일어난 순서대로 동사를 나열해요 (去 + 목적 동작).",
        },
      ],
    },
    {
      name: "부정",
      items: [
        {
          pattern: "不 + 동사/형용사",
          pinyin: "bù",
          ch: "h1-06-negation",
          conn: "不 + 동사/형용사",
          ko: "~하지 않다 (현재·습관·의지의 부정)",
          ex: { zh: "我不吃肉。", pinyin: "wǒ bù chī ròu", ko: "저는 고기를 안 먹어요." },
          ex2: { zh: "今天不冷。", pinyin: "jīntiān bù lěng", ko: "오늘은 안 추워요." },
          note: "不은 4성 앞에서 bú로 변조해요 (不是 bú shì).",
        },
        {
          pattern: "没・没有 + 동사",
          pinyin: "méi・méiyǒu",
          ch: "h1-06-negation",
          conn: "没(有) + 동사",
          ko: "~하지 않았다 (과거·완료의 부정)",
          ex: { zh: "我没吃饭。", pinyin: "wǒ méi chī fàn", ko: "저는 밥을 안 먹었어요." },
          ex2: { zh: "他没来。", pinyin: "tā méi lái", ko: "그는 안 왔어요." },
          note: "이미 일어난 일의 부정은 不이 아니라 没. 没 뒤엔 了를 안 써요 (×没吃了).",
        },
        {
          pattern: "不是…",
          pinyin: "bú shì",
          ch: "h1-01-shi",
          conn: "주어 + 不是 + 명사",
          ko: "~이 아니다",
          ex: { zh: "我不是老师。", pinyin: "wǒ bú shì lǎoshī", ko: "저는 선생님이 아니에요." },
          ex2: { zh: "这不是茶，是水。", pinyin: "zhè bú shì chá, shì shuǐ", ko: "이건 차가 아니라 물이에요." },
        },
        {
          pattern: "没有 + 명사",
          pinyin: "méiyǒu",
          ch: "h1-02-you",
          conn: "주어 + 没有 + 명사",
          ko: "~이 없다 / 가지고 있지 않다",
          ex: { zh: "我没有钱。", pinyin: "wǒ méiyǒu qián", ko: "저는 돈이 없어요." },
          ex2: { zh: "这里没有人。", pinyin: "zhèlǐ méiyǒu rén", ko: "여기엔 사람이 없어요." },
          note: "有의 부정은 언제나 没有 — 不有는 틀려요.",
        },
        {
          pattern: "别 + 동사",
          pinyin: "bié",
          ch: "h1-06-negation",
          conn: "别 + 동사 (금지 명령)",
          ko: "~하지 마",
          ex: { zh: "别去！", pinyin: "bié qù", ko: "가지 마!" },
          ex2: { zh: "别说话。", pinyin: "bié shuōhuà", ko: "말하지 마." },
          note: "别은 '不要'의 줄임 같은 금지 표현. 1급에선 别 형태만 익혀도 충분해요.",
        },
        {
          pattern: "不太 + 형용사",
          pinyin: "bú tài",
          ch: "h1-06-negation",
          conn: "不太 + 형용사 — 완곡한 부정",
          ko: "그다지 ~하지 않다",
          ex: { zh: "我不太喜欢。", pinyin: "wǒ bú tài xǐhuan", ko: "저는 별로 안 좋아해요." },
          ex2: { zh: "今天不太冷。", pinyin: "jīntiān bú tài lěng", ko: "오늘은 그다지 안 추워요." },
          note: "不太는 '아주 ~인 건 아니다'라는 부드러운 부정이에요.",
        },
        {
          pattern: "还没…呢",
          pinyin: "hái méi…ne",
          ch: "h1-06-negation",
          conn: "还 + 没(有) + 동사 (+ 呢) — 아직 안 함",
          ko: "아직 ~하지 않았다",
          ex: { zh: "他还没来。", pinyin: "tā hái méi lái", ko: "그는 아직 안 왔어요." },
          ex2: { zh: "我还没吃饭呢。", pinyin: "wǒ hái méi chī fàn ne", ko: "저는 아직 밥 안 먹었어요." },
        },
        {
          pattern: "不用 + 동사",
          pinyin: "búyòng",
          ch: "h1-12-modal-wishes",
          conn: "不用 + 동사 — ~할 필요 없다",
          ko: "~할 필요 없다",
          ex: { zh: "不用谢。", pinyin: "búyòng xiè", ko: "고마워할 필요 없어요 (천만에요)." },
          ex2: { zh: "你不用来。", pinyin: "nǐ búyòng lái", ko: "당신은 안 와도 돼요." },
        },
      ],
    },
    {
      name: "의문문",
      items: [
        {
          pattern: "…吗？",
          pinyin: "ma",
          ch: "h1-05-ma-questions",
          conn: "평서문 + 吗 (예/아니오 의문)",
          ko: "~입니까? / ~해요?",
          ex: { zh: "你是学生吗？", pinyin: "nǐ shì xuésheng ma", ko: "당신은 학생이에요?" },
          ex2: { zh: "他不来吗？", pinyin: "tā bù lái ma", ko: "그는 안 와요?" },
          note: "문장 끝에 吗만 붙이면 의문문. 어순은 그대로예요.",
        },
        {
          pattern: "…呢？",
          pinyin: "ne",
          ch: "h1-05-ma-questions",
          conn: "명사/대명사 + 呢 (되묻기·생략 의문)",
          ko: "~는요?",
          ex: { zh: "我很好，你呢？", pinyin: "wǒ hěn hǎo, nǐ ne", ko: "저는 잘 지내요, 당신은요?" },
          ex2: { zh: "我的书呢？", pinyin: "wǒ de shū ne", ko: "제 책은요? (어디 있어요?)" },
        },
        {
          pattern: "什么",
          pinyin: "shénme",
          ch: "h1-05-ma-questions",
          conn: "什么 (+ 명사) — 무엇/무슨",
          ko: "무엇 / 무슨",
          ex: { zh: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi", ko: "이름이 뭐예요?" },
          ex2: { zh: "你吃什么？", pinyin: "nǐ chī shénme", ko: "뭐 먹어요?" },
          note: "의문사 의문문엔 吗를 안 붙여요 (×你吃什么吗).",
        },
        {
          pattern: "谁",
          pinyin: "shéi",
          ch: "h1-05-ma-questions",
          conn: "谁 — 누구 (주어/목적어 자리 그대로)",
          ko: "누구",
          ex: { zh: "他是谁？", pinyin: "tā shì shéi", ko: "그는 누구예요?" },
          ex2: { zh: "谁是你的老师？", pinyin: "shéi shì nǐ de lǎoshī", ko: "누가 당신의 선생님이에요?" },
          note: "谁는 shéi 또는 shuí. 의문사는 묻는 자리에 그대로 둬요 (어순 바꿈 없음).",
        },
        {
          pattern: "哪・哪儿",
          pinyin: "nǎ・nǎr",
          ch: "h1-05-ma-questions",
          conn: "哪 + 양사 (어느) / 哪儿 (어디)",
          ko: "어느 / 어디",
          ex: { zh: "你去哪儿？", pinyin: "nǐ qù nǎr", ko: "어디 가요?" },
          ex2: { zh: "你是哪国人？", pinyin: "nǐ shì nǎ guó rén", ko: "어느 나라 사람이에요?" },
        },
        {
          pattern: "几・多少",
          pinyin: "jǐ・duōshao",
          ch: "h1-10-numbers",
          conn: "几 + 양사 (10 미만) / 多少 (수 제한 없음)",
          ko: "몇 / 얼마",
          ex: { zh: "现在几点？", pinyin: "xiànzài jǐ diǎn", ko: "지금 몇 시예요?" },
          ex2: { zh: "这个多少钱？", pinyin: "zhège duōshao qián", ko: "이거 얼마예요?" },
          note: "几는 보통 10 미만의 적은 수, 多少는 큰 수나 가격에 써요. 几 뒤엔 양사 필요.",
        },
        {
          pattern: "怎么样",
          pinyin: "zěnmeyàng",
          ch: "h1-05-ma-questions",
          conn: "주어 + 怎么样 (상태·의향 묻기)",
          ko: "어때(요)?",
          ex: { zh: "你身体怎么样？", pinyin: "nǐ shēntǐ zěnmeyàng", ko: "몸은 좀 어때요?" },
          ex2: { zh: "明天去，怎么样？", pinyin: "míngtiān qù, zěnmeyàng", ko: "내일 가는 거 어때요?" },
        },
        {
          pattern: "为什么",
          pinyin: "wèishénme",
          ch: "h1-05-ma-questions",
          conn: "为什么 + 절 — 이유 묻기",
          ko: "왜 ~해요?",
          ex: { zh: "你为什么不来？", pinyin: "nǐ wèishénme bù lái", ko: "왜 안 와요?" },
          ex2: { zh: "他为什么这么高兴？", pinyin: "tā wèishénme zhème gāoxìng", ko: "그는 왜 이렇게 기뻐해요?" },
        },
        {
          pattern: "동사 + 不 + 동사",
          pinyin: "bù",
          ch: "h1-05-ma-questions",
          conn: "동사/형용사 + 不 + 동사/형용사 (정반의문)",
          ko: "~해요, 안 해요? (정반의문)",
          ex: { zh: "你去不去？", pinyin: "nǐ qù bu qù", ko: "갈 거예요, 안 갈 거예요?" },
          ex2: { zh: "这个菜好不好吃？", pinyin: "zhège cài hǎo bu hǎo chī", ko: "이 요리 맛있어요, 없어요?" },
          note: "긍정형과 부정형을 나란히 — 吗 의문문과 같은 뜻이지만 더 또렷하게 물어요.",
        },
        {
          pattern: "有没有…？",
          pinyin: "yǒu méiyǒu",
          ch: "h1-02-you",
          conn: "有没有 + 명사 — 有의 정반의문",
          ko: "~이 있어요, 없어요?",
          ex: { zh: "你有没有时间？", pinyin: "nǐ yǒu méiyǒu shíjiān", ko: "시간 있으세요?" },
          ex2: { zh: "这儿有没有人？", pinyin: "zhèr yǒu méiyǒu rén", ko: "여기 사람 있어요?" },
        },
        {
          pattern: "好吗・好不好",
          pinyin: "hǎo ma・hǎo bu hǎo",
          ch: "h1-05-ma-questions",
          conn: "제안 + 好吗?/好不好? — 동의 구하기",
          ko: "~할래요? / ~하는 거 어때요?",
          ex: { zh: "我们一起去，好吗？", pinyin: "wǒmen yìqǐ qù, hǎo ma", ko: "우리 같이 가요, 괜찮죠?" },
          ex2: { zh: "明天来，好不好？", pinyin: "míngtiān lái, hǎo bu hǎo", ko: "내일 오는 거 어때요?" },
        },
        {
          pattern: "怎么 + 동사",
          pinyin: "zěnme",
          ch: "h1-05-ma-questions",
          conn: "怎么 + 동사 — 방식·이유 묻기",
          ko: "어떻게 / 왜 ~해요?",
          ex: { zh: "这个字怎么读？", pinyin: "zhège zì zěnme dú", ko: "이 글자 어떻게 읽어요?" },
          ex2: { zh: "你怎么不吃？", pinyin: "nǐ zěnme bù chī", ko: "왜 안 먹어요?" },
          note: "怎么 + 동사는 방법을, 怎么 + 안 함은 이유(왜 안 ~)를 물어요.",
        },
      ],
    },
    {
      name: "양사·지시",
      items: [
        {
          pattern: "수량 + 양사 + 명사",
          pinyin: "—",
          ch: "h1-04-measure-words",
          conn: "수사 + 양사 + 명사",
          ko: "~ 몇 개의 …",
          ex: { zh: "三个人", pinyin: "sān ge rén", ko: "세 사람" },
          ex2: { zh: "我有两本书。", pinyin: "wǒ yǒu liǎng běn shū", ko: "저는 책이 두 권 있어요." },
          note: "명사 셀 땐 반드시 양사가 필요해요 (×三人). '2개'는 二이 아니라 两个.",
        },
        {
          pattern: "一个 + 명사",
          pinyin: "yí ge",
          ch: "h1-04-measure-words",
          conn: "수사 + 个 + 명사",
          ko: "~ 개/명 (가장 흔한 양사)",
          ex: { zh: "一个苹果", pinyin: "yí ge píngguǒ", ko: "사과 한 개" },
          ex2: { zh: "我吃了一个。", pinyin: "wǒ chī le yí ge", ko: "저는 한 개 먹었어요." },
          note: "양사를 모를 땐 일단 个를 쓰면 대개 통해요. 个는 경성.",
        },
        {
          pattern: "这・那 + 양사 + 명사",
          pinyin: "zhè・nà",
          ch: "h1-03-zhe-na",
          conn: "这/那 (+ 양사) + 명사",
          ko: "이/그(저) ~",
          ex: { zh: "这本书很好。", pinyin: "zhè běn shū hěn hǎo", ko: "이 책 정말 좋아요." },
          ex2: { zh: "那个人是谁？", pinyin: "nàge rén shì shéi", ko: "저 사람은 누구예요?" },
          note: "这/那 뒤에도 양사가 들어가요 (这本, 那个).",
        },
        {
          pattern: "这儿・那儿",
          pinyin: "zhèr・nàr",
          ch: "h1-03-zhe-na",
          conn: "这儿(여기) / 那儿(거기·저기)",
          ko: "여기 / 거기·저기",
          ex: { zh: "我在这儿。", pinyin: "wǒ zài zhèr", ko: "저는 여기 있어요." },
          ex2: { zh: "你的书在那儿。", pinyin: "nǐ de shū zài nàr", ko: "당신 책은 저기 있어요." },
        },
        {
          pattern: "这些・那些",
          pinyin: "zhèxiē・nàxiē",
          ch: "h1-03-zhe-na",
          conn: "这些/那些 + 명사 — 이것들/저것들",
          ko: "이 ~들 / 저 ~들",
          ex: { zh: "这些书都是我的。", pinyin: "zhèxiē shū dōu shì wǒ de", ko: "이 책들은 다 제 거예요." },
          ex2: { zh: "那些人是谁？", pinyin: "nàxiē rén shì shéi", ko: "저 사람들은 누구예요?" },
        },
        {
          pattern: "几点・几岁",
          pinyin: "jǐ diǎn・jǐ suì",
          ch: "h1-10-numbers",
          conn: "几 + 点/岁 (시각·나이 묻기)",
          ko: "몇 시 / 몇 살",
          ex: { zh: "你几岁？", pinyin: "nǐ jǐ suì", ko: "몇 살이에요? (어린이에게)" },
          ex2: { zh: "现在几点了？", pinyin: "xiànzài jǐ diǎn le", ko: "지금 몇 시예요?" },
        },
        {
          pattern: "每 + 양사 + 명사",
          pinyin: "měi",
          ch: "h1-04-measure-words",
          conn: "每 + 양사 + 명사 — 매~",
          ko: "~마다, 모든 ~",
          ex: { zh: "每个人都有名字。", pinyin: "měi ge rén dōu yǒu míngzi", ko: "사람마다 이름이 있어요." },
          ex2: { zh: "我每天都看书。", pinyin: "wǒ měi tiān dōu kàn shū", ko: "저는 매일 책을 봐요." },
          note: "每는 흔히 都와 짝을 이뤄요 (每…都…).",
        },
      ],
    },
    {
      name: "시간·때",
      items: [
        {
          pattern: "시간 + 동사",
          pinyin: "—",
          ch: "h1-09-time-place",
          conn: "시간 표현 + 주어/동사 (시간은 동사 앞)",
          ko: "(언제) ~하다",
          ex: { zh: "我今天去。", pinyin: "wǒ jīntiān qù", ko: "저는 오늘 가요." },
          ex2: { zh: "他明天来。", pinyin: "tā míngtiān lái", ko: "그는 내일 와요." },
          note: "시간 표현은 동사 앞에 와요. 我去今天은 틀려요.",
        },
        {
          pattern: "수량 + 点",
          pinyin: "diǎn",
          ch: "h1-10-numbers",
          conn: "숫자 + 点 (+ 分)",
          ko: "~시 (~분)",
          ex: { zh: "现在八点。", pinyin: "xiànzài bā diǎn", ko: "지금 8시예요." },
          ex2: { zh: "我七点起床。", pinyin: "wǒ qī diǎn qǐchuáng", ko: "저는 7시에 일어나요." },
        },
        {
          pattern: "今天・明天・昨天",
          pinyin: "jīntiān・míngtiān・zuótiān",
          ch: "h1-10-numbers",
          conn: "날 표현 (今天/明天/昨天)",
          ko: "오늘 / 내일 / 어제",
          ex: { zh: "昨天我没上班。", pinyin: "zuótiān wǒ méi shàngbān", ko: "어제 저는 출근 안 했어요." },
          ex2: { zh: "明天是星期几？", pinyin: "míngtiān shì xīngqī jǐ", ko: "내일은 무슨 요일이에요?" },
        },
        {
          pattern: "星期 + 수량",
          pinyin: "xīngqī",
          ch: "h1-10-numbers",
          conn: "星期 + 一~六 / 星期天 (요일)",
          ko: "~요일",
          ex: { zh: "今天星期三。", pinyin: "jīntiān xīngqīsān", ko: "오늘은 수요일이에요." },
          ex2: { zh: "我星期天不工作。", pinyin: "wǒ xīngqītiān bù gōngzuò", ko: "저는 일요일에 일 안 해요." },
          note: "요일을 말할 땐 是를 생략하기도 해요 (今天星期三).",
        },
        {
          pattern: "수량 月 수량 号",
          pinyin: "yuè … hào",
          ch: "h1-10-numbers",
          conn: "숫자 + 月 + 숫자 + 号",
          ko: "~월 ~일",
          ex: { zh: "今天五月一号。", pinyin: "jīntiān wǔ yuè yī hào", ko: "오늘은 5월 1일이에요." },
          ex2: { zh: "你的生日是几月几号？", pinyin: "nǐ de shēngrì shì jǐ yuè jǐ hào", ko: "생일이 몇 월 며칠이에요?" },
          note: "구어에선 日 대신 号를 흔히 써요.",
        },
        {
          pattern: "现在 + 술어",
          pinyin: "xiànzài",
          ch: "h1-09-time-place",
          conn: "现在 + 술어 (지금)",
          ko: "지금 ~하다",
          ex: { zh: "我现在很忙。", pinyin: "wǒ xiànzài hěn máng", ko: "저는 지금 바빠요." },
          ex2: { zh: "现在下雨。", pinyin: "xiànzài xiàyǔ", ko: "지금 비가 와요." },
        },
        {
          pattern: "上午・中午・下午・晚上",
          pinyin: "shàngwǔ・zhōngwǔ・xiàwǔ・wǎnshang",
          ch: "h1-10-numbers",
          conn: "하루 시간대 + 동사",
          ko: "오전/점심/오후/저녁에 ~하다",
          ex: { zh: "我上午有课。", pinyin: "wǒ shàngwǔ yǒu kè", ko: "저는 오전에 수업이 있어요." },
          ex2: { zh: "晚上我们一起吃饭。", pinyin: "wǎnshang wǒmen yìqǐ chī fàn", ko: "저녁에 우리 같이 밥 먹어요." },
        },
        {
          pattern: "什么时候",
          pinyin: "shénme shíhou",
          ch: "h1-05-ma-questions",
          conn: "什么时候 + 동사 — 언제",
          ko: "언제 ~해요?",
          ex: { zh: "你什么时候来？", pinyin: "nǐ shénme shíhou lái", ko: "언제 와요?" },
          ex2: { zh: "我们什么时候吃饭？", pinyin: "wǒmen shénme shíhou chī fàn", ko: "우리 언제 밥 먹어요?" },
        },
        {
          pattern: "수량 点 수량 分",
          pinyin: "diǎn … fēn",
          ch: "h1-10-numbers",
          conn: "숫자 + 点 + 숫자 + 分 — 시각의 분",
          ko: "~시 ~분",
          ex: { zh: "现在八点十分。", pinyin: "xiànzài bā diǎn shí fēn", ko: "지금 8시 10분이에요." },
          ex2: { zh: "差五分九点。", pinyin: "chà wǔ fēn jiǔ diǎn", ko: "9시 5분 전이에요." },
        },
        {
          pattern: "半・刻",
          pinyin: "bàn・kè",
          ch: "h1-10-numbers",
          conn: "点 + 半(30분) / 一刻(15분)",
          ko: "~시 반 / ~시 15분",
          ex: { zh: "现在七点半。", pinyin: "xiànzài qī diǎn bàn", ko: "지금 7시 반이에요." },
          ex2: { zh: "我三点一刻到。", pinyin: "wǒ sān diǎn yí kè dào", ko: "저는 3시 15분에 도착해요." },
        },
      ],
    },
    {
      name: "了·완료",
      items: [
        {
          pattern: "동사 + 了",
          pinyin: "le",
          ch: "h2-01-le-completion",
          conn: "동사 + 了 (동작의 완료·실현)",
          ko: "~했다",
          ex: { zh: "我吃了。", pinyin: "wǒ chī le", ko: "저는 먹었어요." },
          ex2: { zh: "他买了一本书。", pinyin: "tā mǎi le yì běn shū", ko: "그는 책을 한 권 샀어요." },
          note: "부정은 没 + 동사이고 了를 빼요 (我没吃, ×我没吃了).",
        },
        {
          pattern: "…了",
          pinyin: "le",
          ch: "h2-04-le-change",
          conn: "문장 끝 了 (상황의 변화)",
          ko: "~하게 되었다 / 이제 ~다",
          ex: { zh: "下雨了。", pinyin: "xiàyǔ le", ko: "비가 오기 시작했어요." },
          ex2: { zh: "我饿了。", pinyin: "wǒ è le", ko: "배고파졌어요." },
          note: "문말 了는 '예전과 달라진 새 상황'을 알려줘요.",
        },
        {
          pattern: "太…了",
          pinyin: "tài…le",
          ch: "h2-04-le-change",
          conn: "太 + 형용사 + 了 (감탄·강조)",
          ko: "너무 ~하다",
          ex: { zh: "太好了！", pinyin: "tài hǎo le", ko: "정말 잘됐다!" },
          ex2: { zh: "今天太热了。", pinyin: "jīntiān tài rè le", ko: "오늘 너무 더워요." },
          note: "太 … 了는 한 세트로 외우면 편해요.",
        },
        {
          pattern: "동사 + 了 + 没有？",
          pinyin: "le … méiyǒu",
          ch: "h2-01-le-completion",
          conn: "동사 + 了 + 没有? — 완료 여부 묻기",
          ko: "~했어요, 안 했어요?",
          ex: { zh: "你吃了没有？", pinyin: "nǐ chī le méiyǒu", ko: "밥 먹었어요?" },
          ex2: { zh: "他来了没有？", pinyin: "tā lái le méiyǒu", ko: "그 사람 왔어요?" },
          note: "완료를 묻는 정반의문. 没有가 부정 쪽을 대신해요.",
        },
      ],
    },
    {
      name: "능원동사·바람",
      items: [
        {
          pattern: "想 + 동사",
          pinyin: "xiǎng",
          ch: "h2-06-modal-verbs",
          conn: "想 + 동사 (바람·의향)",
          ko: "~하고 싶다",
          ex: { zh: "我想喝水。", pinyin: "wǒ xiǎng hē shuǐ", ko: "물 마시고 싶어요." },
          ex2: { zh: "我不想去。", pinyin: "wǒ bù xiǎng qù", ko: "가고 싶지 않아요." },
          note: "想은 '생각하다'이자 '~하고 싶다'. 부정은 不想.",
        },
        {
          pattern: "会 + 동사",
          pinyin: "huì",
          ch: "h2-06-modal-verbs",
          conn: "会 + 동사 (학습으로 익힌 능력)",
          ko: "~할 줄 안다",
          ex: { zh: "我会说汉语。", pinyin: "wǒ huì shuō Hànyǔ", ko: "저는 중국어를 할 줄 알아요." },
          ex2: { zh: "他不会做菜。", pinyin: "tā bú huì zuò cài", ko: "그는 요리를 할 줄 몰라요." },
          note: "배워서 할 수 있는 것은 会. 부정은 不会.",
        },
        {
          pattern: "能 + 동사",
          pinyin: "néng",
          ch: "h2-06-modal-verbs",
          conn: "能 + 동사 (가능·여건상 할 수 있음)",
          ko: "~할 수 있다",
          ex: { zh: "我今天能来。", pinyin: "wǒ jīntiān néng lái", ko: "저는 오늘 올 수 있어요." },
          ex2: { zh: "我不能喝酒。", pinyin: "wǒ bù néng hē jiǔ", ko: "저는 술을 마시면 안 돼요/못 마셔요." },
          note: "여건·허락상 가능은 能, 학습된 기능은 会로 구별해요.",
        },
        {
          pattern: "请 + 동사",
          pinyin: "qǐng",
          ch: "h1-12-modal-wishes",
          conn: "请 + 동사 (공손한 청유)",
          ko: "~해 주세요",
          ex: { zh: "请坐。", pinyin: "qǐng zuò", ko: "앉으세요." },
          ex2: { zh: "请喝茶。", pinyin: "qǐng hē chá", ko: "차 드세요." },
        },
        {
          pattern: "想 + 명사",
          pinyin: "xiǎng",
          ch: "h1-12-modal-wishes",
          conn: "想 + 사람/장소 — 그리움",
          ko: "~을 그리워하다/보고 싶다",
          ex: { zh: "我想家。", pinyin: "wǒ xiǎng jiā", ko: "저는 집이 그리워요." },
          ex2: { zh: "妈妈很想你。", pinyin: "māma hěn xiǎng nǐ", ko: "엄마가 너를 많이 보고 싶어 해." },
          note: "想은 뒤에 동사면 '~하고 싶다', 사람·장소면 '그립다'예요.",
        },
        {
          pattern: "会…的",
          pinyin: "huì…de",
          ch: "h2-06-modal-verbs",
          conn: "会 + 동사 (+ 的) — 미래 가능성",
          ko: "~할 것이다 (그럴 것이다)",
          ex: { zh: "他明天会来。", pinyin: "tā míngtiān huì lái", ko: "그는 내일 올 거예요." },
          ex2: { zh: "明天不会下雨。", pinyin: "míngtiān bú huì xiàyǔ", ko: "내일은 비가 안 올 거예요." },
          note: "会는 '할 줄 안다'뿐 아니라 '~일 것이다'라는 추측도 나타내요.",
        },
      ],
    },
    {
      name: "부사·정도",
      items: [
        {
          pattern: "很 + 형용사",
          pinyin: "hěn",
          ch: "h1-01-shi",
          conn: "很 + 형용사 (정도 부사 + 형용사 술어)",
          ko: "(매우) ~하다",
          ex: { zh: "我很高兴。", pinyin: "wǒ hěn gāoxìng", ko: "저는 기뻐요." },
          ex2: { zh: "这个很贵。", pinyin: "zhège hěn guì", ko: "이거 비싸요." },
          note: "형용사 술어엔 흔히 很이 붙어요. 강하게 '정말'은 真을 써요.",
        },
        {
          pattern: "都 + 동사/형용사",
          pinyin: "dōu",
          ch: "h1-11-adverbs-dou-ye",
          conn: "주어(복수) + 都 + 술어 (모두)",
          ko: "모두 ~하다",
          ex: { zh: "我们都是学生。", pinyin: "wǒmen dōu shì xuésheng", ko: "우리는 모두 학생이에요." },
          ex2: { zh: "他们都不来。", pinyin: "tāmen dōu bù lái", ko: "그들은 모두 안 와요." },
          note: "都는 주어 뒤·동사 앞. 가리키는 대상이 都 앞에 와야 해요.",
        },
        {
          pattern: "也 + 동사/형용사",
          pinyin: "yě",
          ch: "h1-11-adverbs-dou-ye",
          conn: "주어 + 也 + 술어 (~도)",
          ko: "~도 (역시) ~하다",
          ex: { zh: "我也是中国人。", pinyin: "wǒ yě shì Zhōngguó rén", ko: "저도 중국인이에요." },
          ex2: { zh: "他也不去。", pinyin: "tā yě bú qù", ko: "그도 안 가요." },
          note: "也도 주어 뒤·동사 앞 자리예요.",
        },
        {
          pattern: "很多・一点儿",
          pinyin: "hěn duō・yìdiǎnr",
          conn: "很多 + 명사 / 一点儿 (양 표현)",
          ko: "많은 ~ / 조금",
          ex: { zh: "他有很多朋友。", pinyin: "tā yǒu hěn duō péngyou", ko: "그는 친구가 많아요." },
          ex2: { zh: "我会说一点儿汉语。", pinyin: "wǒ huì shuō yìdiǎnr Hànyǔ", ko: "저는 중국어를 조금 할 줄 알아요." },
        },
        {
          pattern: "真 + 형용사",
          pinyin: "zhēn",
          ch: "h1-11-adverbs-dou-ye",
          conn: "真 + 형용사 — 감탄 강조",
          ko: "정말 ~하다",
          ex: { zh: "你真好！", pinyin: "nǐ zhēn hǎo", ko: "당신 정말 좋은 사람이에요!" },
          ex2: { zh: "这个真贵。", pinyin: "zhège zhēn guì", ko: "이거 정말 비싸요." },
        },
        {
          pattern: "一起 + 동사",
          pinyin: "yìqǐ",
          ch: "h1-11-adverbs-dou-ye",
          conn: "(和 …) 一起 + 동사 — 함께",
          ko: "함께 ~하다",
          ex: { zh: "我们一起去吧。", pinyin: "wǒmen yìqǐ qù ba", ko: "우리 같이 가요." },
          ex2: { zh: "你和我一起学习。", pinyin: "nǐ hé wǒ yìqǐ xuéxí", ko: "너랑 나랑 같이 공부해." },
        },
      ],
    },
    {
      name: "개사·대상",
      items: [
        {
          pattern: "在 + 장소 + 동사",
          pinyin: "zài",
          ch: "h1-09-time-place",
          conn: "在 + 장소 + 동사 (장소는 동사 앞)",
          ko: "(어디)에서 ~하다",
          ex: { zh: "我在家看电视。", pinyin: "wǒ zài jiā kàn diànshì", ko: "저는 집에서 TV를 봐요." },
          ex2: { zh: "他在学校学习。", pinyin: "tā zài xuéxiào xuéxí", ko: "그는 학교에서 공부해요." },
          note: "'~에서'의 在구는 동사 앞에 와요. 한국어 어순(장소+동작)과 같아 편해요.",
        },
        {
          pattern: "和…一起",
          pinyin: "hé…yìqǐ",
          ch: "h2-07-prepositions",
          conn: "和 + 대상 + (一起) + 동사",
          ko: "~와 (함께) …하다",
          ex: { zh: "我和朋友一起去。", pinyin: "wǒ hé péngyou yìqǐ qù", ko: "저는 친구와 함께 가요." },
          ex2: { zh: "我想和你说话。", pinyin: "wǒ xiǎng hé nǐ shuōhuà", ko: "당신과 이야기하고 싶어요." },
          note: "和는 '~와/과'. 명사를 잇는 접속사로도 써요 (我和你 = 나와 너).",
        },
        {
          pattern: "给 + 대상 + 동사",
          pinyin: "gěi",
          ch: "h2-07-prepositions",
          conn: "给 + 대상 + 동사 (~에게)",
          ko: "~에게 …하다/주다",
          ex: { zh: "我给你打电话。", pinyin: "wǒ gěi nǐ dǎ diànhuà", ko: "제가 전화 드릴게요." },
          ex2: { zh: "请给我一杯水。", pinyin: "qǐng gěi wǒ yì bēi shuǐ", ko: "물 한 잔 주세요." },
        },
        {
          pattern: "从 + 장소/시간",
          pinyin: "cóng",
          ch: "h2-07-prepositions",
          conn: "从 + 출발점 + 동사",
          ko: "~에서(부터) …하다",
          ex: { zh: "我从韩国来。", pinyin: "wǒ cóng Hánguó lái", ko: "저는 한국에서 왔어요." },
          ex2: { zh: "他从家里出来。", pinyin: "tā cóng jiā li chūlái", ko: "그는 집에서 나와요." },
        },
        {
          pattern: "对 + 대상 + 술어",
          pinyin: "duì",
          ch: "h2-07-prepositions",
          conn: "对 + 대상 + 술어 — ~에게",
          ko: "~에게 (대하여) …하다",
          ex: { zh: "他对我很好。", pinyin: "tā duì wǒ hěn hǎo", ko: "그는 저에게 잘해 줘요." },
          ex2: { zh: "请对我说。", pinyin: "qǐng duì wǒ shuō", ko: "저에게 말씀해 주세요." },
        },
      ],
    },
    {
      name: "관용·인사",
      items: [
        {
          pattern: "谢谢・不客气",
          pinyin: "xièxie・bú kèqi",
          ch: "h1-13-greetings",
          conn: "감사와 응답 (고정 표현)",
          ko: "고맙습니다 / 천만에요",
          ex: { zh: "谢谢你！", pinyin: "xièxie nǐ", ko: "고마워요!" },
          ex2: { zh: "不客气。", pinyin: "bú kèqi", ko: "천만에요." },
        },
        {
          pattern: "对不起・没关系",
          pinyin: "duìbuqǐ・méi guānxi",
          ch: "h1-13-greetings",
          conn: "사과와 응답 (고정 표현)",
          ko: "미안합니다 / 괜찮아요",
          ex: { zh: "对不起，我来晚了。", pinyin: "duìbuqǐ, wǒ lái wǎn le", ko: "죄송해요, 늦었어요." },
          ex2: { zh: "没关系。", pinyin: "méi guānxi", ko: "괜찮아요." },
        },
        {
          pattern: "请问…",
          pinyin: "qǐngwèn",
          ch: "h1-13-greetings",
          conn: "请问 + 질문 (말 걸기)",
          ko: "실례지만 ~",
          ex: { zh: "请问，火车站在哪儿？", pinyin: "qǐngwèn, huǒchēzhàn zài nǎr", ko: "실례지만 기차역이 어디예요?" },
          ex2: { zh: "请问，你叫什么名字？", pinyin: "qǐngwèn, nǐ jiào shénme míngzi", ko: "실례지만 이름이 뭐예요?" },
        },
        {
          pattern: "再见・明天见",
          pinyin: "zàijiàn・míngtiān jiàn",
          ch: "h1-13-greetings",
          conn: "헤어질 때 인사 (见 = 보다)",
          ko: "안녕히 가세요 / 내일 봐요",
          ex: { zh: "老师，再见！", pinyin: "lǎoshī, zàijiàn", ko: "선생님, 안녕히 계세요!" },
          ex2: { zh: "明天见！", pinyin: "míngtiān jiàn", ko: "내일 봐요!" },
        },
        {
          pattern: "你好吗？",
          pinyin: "nǐ hǎo ma",
          ch: "h1-13-greetings",
          conn: "안부 묻기 (고정 표현)",
          ko: "잘 지내요?",
          ex: { zh: "你好吗？", pinyin: "nǐ hǎo ma", ko: "잘 지내요?" },
          ex2: { zh: "我很好，你呢？", pinyin: "wǒ hěn hǎo, nǐ ne", ko: "저는 잘 지내요, 당신은요?" },
        },
        {
          pattern: "认识你很高兴",
          pinyin: "rènshi nǐ hěn gāoxìng",
          ch: "h1-13-greetings",
          conn: "처음 만났을 때 인사 (고정 표현)",
          ko: "만나서 반가워요",
          ex: { zh: "认识你很高兴。", pinyin: "rènshi nǐ hěn gāoxìng", ko: "만나서 반가워요." },
          ex2: { zh: "我也很高兴。", pinyin: "wǒ yě hěn gāoxìng", ko: "저도 반가워요." },
        },
      ],
    },
    {
      name: "숫자·돈·나이",
      items: [
        {
          pattern: "수량 块・수량 元",
          pinyin: "kuài・yuán",
          ch: "h1-10-numbers",
          conn: "숫자 + 块/元 (+ 钱) — 위안 단위",
          ko: "~위안",
          ex: { zh: "这个十块钱。", pinyin: "zhège shí kuài qián", ko: "이거 10위안이에요." },
          ex2: { zh: "一共多少钱？", pinyin: "yígòng duōshao qián", ko: "모두 얼마예요?" },
          note: "구어에선 元보다 块를 더 많이 써요.",
        },
        {
          pattern: "주어 + 수량 + 岁",
          pinyin: "suì",
          ch: "h1-10-numbers",
          conn: "주어 + 숫자 + 岁 — 나이",
          ko: "~살이다",
          ex: { zh: "我二十岁。", pinyin: "wǒ èrshí suì", ko: "저는 스무 살이에요." },
          ex2: { zh: "你多大？", pinyin: "nǐ duō dà", ko: "나이가 어떻게 되세요?" },
          note: "나이엔 是를 안 써요 (×我是二十岁). 어른에겐 你多大?로 물어요.",
        },
        {
          pattern: "两 + 양사",
          pinyin: "liǎng",
          ch: "h1-10-numbers",
          conn: "两 + 양사 (수량으로서의 2)",
          ko: "두 ~",
          ex: { zh: "我要两个。", pinyin: "wǒ yào liǎng ge", ko: "두 개 주세요." },
          ex2: { zh: "他有两个孩子。", pinyin: "tā yǒu liǎng ge háizi", ko: "그는 아이가 둘 있어요." },
          note: "양사 앞에서 '2'는 二이 아니라 两을 써요.",
        },
        {
          pattern: "第 + 수량",
          pinyin: "dì",
          ch: "h1-10-numbers",
          conn: "第 + 숫자 (+ 양사) — 순서",
          ko: "~번째",
          ex: { zh: "我是第一个。", pinyin: "wǒ shì dì-yī ge", ko: "제가 첫 번째예요." },
          ex2: { zh: "今天是第三天。", pinyin: "jīntiān shì dì-sān tiān", ko: "오늘이 셋째 날이에요." },
        },
      ],
    },
  ],
};
