/**
 * H2 문형 사전 — HSK 2급 핵심 구문·표현 전수 커버 레이어 (SCHEMA.md 참고)
 * 챕터(grammar/h2.js)가 '이해'라면 이 사전은 '전수 검색'.
 */
export default {
  level: "H2",
  title: "2급 문형 사전",
  desc: "在 진행·过 경험·정도보어부터 比 비교, 因为·所以 연결, 개사틀(从·离·对·给), 가능보어 입문까지 — HSK 2급 핵심 문형을 기능별로 모두 모은 전수 검색 사전.",
  themes: [
    {
      name: "진행·경험·완료",
      items: [
        {
          pattern: "正在・在 + 동사 (+ 呢)",
          conn: "(正)在 + 동사 (+ 呢) — 동작의 진행",
          ko: "~하고 있다 (진행)",
          ex: { zh: "我在看电视呢。", pinyin: "wǒ zài kàn diànshì ne", ko: "저는 TV를 보고 있어요." },
          ex2: { zh: "他没在睡觉。", pinyin: "tā méi zài shuìjiào", ko: "그는 자고 있지 않아요." },
          note: "在는 진행, 着는 상태 지속. 문말 呢가 진행 어감을 더해요.",
        },
        {
          pattern: "동사 + 过",
          conn: "동사 + 过 — 경험",
          ko: "~한 적이 있다 (경험)",
          ex: { zh: "我去过北京。", pinyin: "wǒ qù guo Běijīng", ko: "저는 베이징에 가 본 적 있어요." },
          ex2: { zh: "我没吃过羊肉。", pinyin: "wǒ méi chī guo yángròu", ko: "저는 양고기를 먹어 본 적 없어요." },
          note: "了는 완료, 过는 '겪어본 경험'. 부정은 没 + V + 过 (过를 남겨요).",
        },
        {
          pattern: "동사 + 了 + 수량 + 목적어",
          conn: "동사 + 了 + 수량사 + 목적어 — 완료된 분량",
          ko: "~을 (얼마만큼) 했다",
          ex: { zh: "我买了三本书。", pinyin: "wǒ mǎi le sān běn shū", ko: "저는 책을 세 권 샀어요." },
          ex2: { zh: "他喝了两杯咖啡。", pinyin: "tā hē le liǎng bēi kāfēi", ko: "그는 커피를 두 잔 마셨어요." },
        },
        {
          pattern: "동사 + 着",
          conn: "동사 + 着 — 상태의 지속",
          ko: "~한 채로 있다 / ~해 있다",
          ex: { zh: "门开着。", pinyin: "mén kāi zhe", ko: "문이 열려 있어요." },
          ex2: { zh: "他穿着一件红衣服。", pinyin: "tā chuān zhe yí jiàn hóng yīfu", ko: "그는 빨간 옷을 입고 있어요." },
          note: "着는 동작이 끝난 뒤의 '상태 지속'. 진행의 在와 구별해요.",
        },
        {
          pattern: "快 … 了",
          conn: "快(要) + 동사/형용사 + 了 — 임박",
          ko: "곧 ~하려 한다",
          ex: { zh: "火车快到了。", pinyin: "huǒchē kuài dào le", ko: "기차가 곧 도착해요." },
          ex2: { zh: "快下雨了。", pinyin: "kuài xiàyǔ le", ko: "곧 비가 올 것 같아요." },
        },
        {
          pattern: "要 … 了",
          conn: "要 + 동사 + 了 — 곧 일어남",
          ko: "곧 ~할 것이다",
          ex: { zh: "我要去上海了。", pinyin: "wǒ yào qù Shànghǎi le", ko: "저는 곧 상하이에 가요." },
          ex2: { zh: "电影要开始了。", pinyin: "diànyǐng yào kāishǐ le", ko: "영화가 곧 시작해요." },
        },
        {
          pattern: "正在 … 呢",
          conn: "正在 + 동사 + 呢 — 바로 그때 진행 중",
          ko: "마침 ~하고 있다",
          ex: { zh: "我正在做饭呢。", pinyin: "wǒ zhèngzài zuò fàn ne", ko: "저는 마침 밥하고 있어요." },
          ex2: { zh: "他们正在开会。", pinyin: "tāmen zhèngzài kāihuì", ko: "그들은 지금 회의 중이에요." },
          note: "正在은 '바로 그 순간'을 강조하는 진행이에요.",
        },
        {
          pattern: "동사 + 过 + 几次",
          conn: "동사 + 过 + 횟수 — 경험의 빈도",
          ko: "~한 적이 몇 번 있다",
          ex: { zh: "我去过两次中国。", pinyin: "wǒ qù guo liǎng cì Zhōngguó", ko: "저는 중국에 두 번 가 봤어요." },
          ex2: { zh: "这部电影我看过一次。", pinyin: "zhè bù diànyǐng wǒ kàn guo yí cì", ko: "이 영화 저는 한 번 본 적 있어요." },
        },
        {
          pattern: "没 + 동사 (과거 부정)",
          conn: "没(有) + 동사 — 안 했음",
          ko: "~하지 않았다",
          ex: { zh: "昨天我没上班。", pinyin: "zuótiān wǒ méi shàngbān", ko: "어제 저는 출근 안 했어요." },
          ex2: { zh: "他没告诉我。", pinyin: "tā méi gàosu wǒ", ko: "그는 저에게 안 알려 줬어요." },
          note: "완료 了의 부정은 没 + 동사. 了를 빼요.",
        },
      ],
    },
    {
      name: "보어 (결과·정도·시량)",
      items: [
        {
          pattern: "동사 + 完",
          conn: "동사 + 完 — 완료 결과보어",
          ko: "다 ~하다",
          ex: { zh: "我吃完了。", pinyin: "wǒ chī wán le", ko: "저는 다 먹었어요." },
          ex2: { zh: "作业还没做完。", pinyin: "zuòyè hái méi zuò wán", ko: "숙제를 아직 다 못 했어요." },
          note: "完은 '동작이 끝남'을 보충하는 결과보어. 부정은 没.",
        },
        {
          pattern: "동사 + 到・见",
          conn: "동사 + 到/见 — 도달·지각 결과보어",
          ko: "~해내다 / ~하게 되다",
          ex: { zh: "我看到他了。", pinyin: "wǒ kàn dào tā le", ko: "저는 그를 봤어요." },
          ex2: { zh: "我没听见。", pinyin: "wǒ méi tīng jiàn", ko: "저는 못 들었어요." },
          note: "看到·听见처럼 동작이 결과까지 이어졌음을 나타내요.",
        },
        {
          pattern: "동사 + 错・对",
          conn: "동사 + 错(틀림)/对(맞음) — 결과보어",
          ko: "잘못 ~하다 / 제대로 ~하다",
          ex: { zh: "我说错了。", pinyin: "wǒ shuō cuò le", ko: "제가 잘못 말했어요." },
          ex2: { zh: "你写对了。", pinyin: "nǐ xiě duì le", ko: "당신은 맞게 썼어요." },
        },
        {
          pattern: "동사 + 得 + 정도보어",
          conn: "동사 + 得 + 형용사 — 정도·평가",
          ko: "~하는 정도가 …하다 (잘/빨리 등)",
          ex: { zh: "他说得很好。", pinyin: "tā shuō de hěn hǎo", ko: "그는 말을 잘해요." },
          ex2: { zh: "我起得不早。", pinyin: "wǒ qǐ de bù zǎo", ko: "저는 일찍 안 일어나요." },
          note: "목적어가 있으면 동사를 반복해요 (他说汉语说得很好).",
        },
        {
          pattern: "동사 + 시량보어",
          conn: "동사 + 시간량 (얼마 동안)",
          ko: "(얼마 동안) ~하다",
          ex: { zh: "我学了两年汉语。", pinyin: "wǒ xué le liǎng nián Hànyǔ", ko: "저는 중국어를 2년 배웠어요." },
          ex2: { zh: "他睡了八个小时。", pinyin: "tā shuì le bā ge xiǎoshí", ko: "그는 8시간 잤어요." },
          note: "시간의 '길이'는 동사 뒤, 시점은 동사 앞. 목적어가 있으면 동사 반복도 가능.",
        },
        {
          pattern: "동사 + 一下",
          conn: "동사 + 一下 — 가볍게 잠깐",
          ko: "좀 ~하다",
          ex: { zh: "请等一下。", pinyin: "qǐng děng yíxià", ko: "잠깐만 기다려 주세요." },
          ex2: { zh: "我看一下。", pinyin: "wǒ kàn yíxià", ko: "제가 한번 볼게요." },
          note: "동작을 부드럽게 만드는 표현. 동사 중첩(看看)과 비슷한 어감.",
        },
        {
          pattern: "동사 + 开・住・好",
          conn: "동사 + 开(열림)/住(고정)/好(완성) — 결과보어",
          ko: "~해 열다/붙잡다/완성하다",
          ex: { zh: "请打开门。", pinyin: "qǐng dǎkāi mén", ko: "문을 열어 주세요." },
          ex2: { zh: "饭做好了。", pinyin: "fàn zuò hǎo le", ko: "밥이 다 됐어요." },
          note: "好는 '잘 마무리됨'을 보충해요 (做好 = 다 만들다).",
        },
        {
          pattern: "동사 + 得 + 不 + 보어",
          conn: "동사 + 得 + 부정 정도보어",
          ko: "~하는 정도가 …하지 않다",
          ex: { zh: "他来得不晚。", pinyin: "tā lái de bù wǎn", ko: "그는 늦게 안 와요." },
          ex2: { zh: "我跑得不快。", pinyin: "wǒ pǎo de bú kuài", ko: "저는 빨리 못 달려요." },
          note: "정도보어의 부정은 보어 부분에 不을 넣어요 (得不 + 형용사).",
        },
        {
          pattern: "동사 + 多/少了",
          conn: "동사 + 형용사 + 了 — 결과 상태",
          ko: "~이 많아/적어졌다",
          ex: { zh: "今天人多了。", pinyin: "jīntiān rén duō le", ko: "오늘은 사람이 많아졌어요." },
          ex2: { zh: "天气暖和了。", pinyin: "tiānqì nuǎnhuo le", ko: "날씨가 따뜻해졌어요." },
        },
      ],
    },
    {
      name: "비교",
      items: [
        {
          pattern: "A 比 B + 형용사",
          conn: "A + 比 + B + 형용사 — 차등 비교",
          ko: "A는 B보다 ~하다",
          ex: { zh: "今天比昨天热。", pinyin: "jīntiān bǐ zuótiān rè", ko: "오늘이 어제보다 더워요." },
          ex2: { zh: "他比我高。", pinyin: "tā bǐ wǒ gāo", ko: "그는 저보다 키가 커요." },
          note: "比 비교문엔 很·非常을 안 써요 (×他比我很高). 정도는 一点儿·得多로.",
        },
        {
          pattern: "A 比 B + 형용사 + 一点儿・得多",
          conn: "A 比 B + 형용사 + 一点儿/得多 — 차이의 양",
          ko: "A가 B보다 조금/훨씬 ~하다",
          ex: { zh: "这个比那个贵一点儿。", pinyin: "zhège bǐ nàge guì yìdiǎnr", ko: "이게 저것보다 조금 비싸요." },
          ex2: { zh: "他比我大得多。", pinyin: "tā bǐ wǒ dà de duō", ko: "그는 저보다 훨씬 나이가 많아요." },
        },
        {
          pattern: "A 没有 B + 형용사",
          conn: "A + 没有 + B + 형용사 — 비교의 부정",
          ko: "A는 B만큼 ~하지 않다",
          ex: { zh: "我没有他高。", pinyin: "wǒ méiyǒu tā gāo", ko: "저는 그만큼 키가 크지 않아요." },
          ex2: { zh: "今天没有昨天冷。", pinyin: "jīntiān méiyǒu zuótiān lěng", ko: "오늘은 어제만큼 춥지 않아요." },
          note: "比의 부정은 不比보다 没有 … 를 더 흔히 써요.",
        },
        {
          pattern: "A 跟 B 一样",
          conn: "A + 跟 + B + 一样 (+ 형용사) — 동등 비교",
          ko: "A는 B와 같다 / 똑같이 ~하다",
          ex: { zh: "我的手机跟你的一样。", pinyin: "wǒ de shǒujī gēn nǐ de yíyàng", ko: "제 휴대폰은 당신 것과 같아요." },
          ex2: { zh: "他跟我一样高。", pinyin: "tā gēn wǒ yíyàng gāo", ko: "그는 저와 키가 같아요." },
        },
        {
          pattern: "最 + 형용사",
          conn: "最 + 형용사 — 최상급",
          ko: "가장 ~하다",
          ex: { zh: "这个最好。", pinyin: "zhège zuì hǎo", ko: "이게 제일 좋아요." },
          ex2: { zh: "我最喜欢这个。", pinyin: "wǒ zuì xǐhuan zhège", ko: "저는 이걸 가장 좋아해요." },
        },
        {
          pattern: "更 + 형용사",
          conn: "更 + 형용사 — 한층 더",
          ko: "더욱 ~하다",
          ex: { zh: "这个更好。", pinyin: "zhège gèng hǎo", ko: "이게 더 좋아요." },
          ex2: { zh: "明天会更冷。", pinyin: "míngtiān huì gèng lěng", ko: "내일은 더 추울 거예요." },
        },
        {
          pattern: "A 不如 B",
          conn: "A + 不如 + B (+ 형용사) — ~만 못함",
          ko: "A는 B만 못하다",
          ex: { zh: "我的汉语不如他。", pinyin: "wǒ de Hànyǔ bùrú tā", ko: "제 중국어는 그만 못해요." },
          ex2: { zh: "坐车不如走路快。", pinyin: "zuò chē bùrú zǒulù kuài", ko: "차 타는 게 걷는 것보다 빠르지 않아요." },
        },
        {
          pattern: "和 … 差不多",
          conn: "A + 和 + B + 差不多 — 거의 비슷",
          ko: "A는 B와 비슷하다",
          ex: { zh: "他和我差不多高。", pinyin: "tā hé wǒ chàbuduō gāo", ko: "그는 저와 키가 비슷해요." },
          ex2: { zh: "价格差不多。", pinyin: "jiàgé chàbuduō", ko: "가격이 비슷해요." },
        },
      ],
    },
    {
      name: "개사틀",
      items: [
        {
          pattern: "从 + 장소/시간",
          conn: "从 + 출발점 (+ 到) + 동사",
          ko: "~에서(부터) …하다",
          ex: { zh: "我从北京来。", pinyin: "wǒ cóng Běijīng lái", ko: "저는 베이징에서 왔어요." },
          ex2: { zh: "从这儿到那儿很近。", pinyin: "cóng zhèr dào nàr hěn jìn", ko: "여기서 저기까지 가까워요." },
          note: "从 … 到 …는 '~에서 ~까지'. 출발점·시작점을 나타내요.",
        },
        {
          pattern: "离 + 기준점",
          conn: "A + 离 + B + 远/近 — 거리",
          ko: "A는 B에서 멀다/가깝다",
          ex: { zh: "我家离公司很近。", pinyin: "wǒ jiā lí gōngsī hěn jìn", ko: "저희 집은 회사에서 가까워요." },
          ex2: { zh: "学校离这儿不远。", pinyin: "xuéxiào lí zhèr bù yuǎn", ko: "학교는 여기서 멀지 않아요." },
          note: "거리·간격의 기준점은 离, 출발점은 从으로 구별해요.",
        },
        {
          pattern: "对 + 대상",
          conn: "对 + 대상 + 술어 — ~에 대해/에게",
          ko: "~에 대해 / ~에게",
          ex: { zh: "他对我很好。", pinyin: "tā duì wǒ hěn hǎo", ko: "그는 저에게 잘해 줘요." },
          ex2: { zh: "我对中国文化很感兴趣。", pinyin: "wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù", ko: "저는 중국 문화에 관심이 많아요." },
        },
        {
          pattern: "给 + 사람 + 동사",
          conn: "给 + 대상 + 동사 — ~에게/위해",
          ko: "~에게 …해 주다",
          ex: { zh: "我给妈妈打电话。", pinyin: "wǒ gěi māma dǎ diànhuà", ko: "저는 엄마에게 전화해요." },
          ex2: { zh: "他给我买了礼物。", pinyin: "tā gěi wǒ mǎi le lǐwù", ko: "그는 저에게 선물을 사 줬어요." },
        },
        {
          pattern: "为了 + 목적",
          conn: "为了 + 목적 + 주절",
          ko: "~을 위해 …하다",
          ex: { zh: "为了考试，我每天学习。", pinyin: "wèile kǎoshì, wǒ měi tiān xuéxí", ko: "시험을 위해 저는 매일 공부해요." },
          ex2: { zh: "为了身体，他每天跑步。", pinyin: "wèile shēntǐ, tā měi tiān pǎobù", ko: "건강을 위해 그는 매일 달리기를 해요." },
        },
        {
          pattern: "向・往 + 방향",
          conn: "向/往 + 방향 + 동사",
          ko: "~쪽으로 …하다",
          ex: { zh: "一直往前走。", pinyin: "yìzhí wǎng qián zǒu", ko: "쭉 앞으로 가세요." },
          ex2: { zh: "请向左转。", pinyin: "qǐng xiàng zuǒ zhuǎn", ko: "왼쪽으로 도세요." },
        },
        {
          pattern: "在 + 시간/장소 + 동사",
          conn: "在 + 시점/장소 + 동사",
          ko: "(언제·어디서) ~하다",
          ex: { zh: "我在家工作。", pinyin: "wǒ zài jiā gōngzuò", ko: "저는 집에서 일해요." },
          ex2: { zh: "我们在七点见面。", pinyin: "wǒmen zài qī diǎn jiànmiàn", ko: "우리는 7시에 만나요." },
        },
        {
          pattern: "跟・和 + 사람 + 동사",
          conn: "跟/和 + 대상 + 동사 — ~와",
          ko: "~와 함께/에게 …하다",
          ex: { zh: "我跟朋友去看电影。", pinyin: "wǒ gēn péngyou qù kàn diànyǐng", ko: "저는 친구와 영화 보러 가요." },
          ex2: { zh: "请跟我来。", pinyin: "qǐng gēn wǒ lái", ko: "저를 따라오세요." },
        },
        {
          pattern: "用 + 도구 + 동사",
          conn: "用 + 수단/도구 + 동사 — ~으로",
          ko: "~을 써서/~으로 …하다",
          ex: { zh: "我用筷子吃饭。", pinyin: "wǒ yòng kuàizi chī fàn", ko: "저는 젓가락으로 밥을 먹어요." },
          ex2: { zh: "请用汉语说。", pinyin: "qǐng yòng Hànyǔ shuō", ko: "중국어로 말해 주세요." },
        },
        {
          pattern: "到 + 장소 + 동사",
          conn: "到 + 도착지 + 동사 — ~에 가서",
          ko: "~에 가서/도착해서 …하다",
          ex: { zh: "我到北京去旅行。", pinyin: "wǒ dào Běijīng qù lǚxíng", ko: "저는 베이징에 여행 가요." },
          ex2: { zh: "到家给我打电话。", pinyin: "dào jiā gěi wǒ dǎ diànhuà", ko: "집에 도착하면 전화해." },
        },
      ],
    },
    {
      name: "연결·접속",
      items: [
        {
          pattern: "因为 … 所以 …",
          conn: "因为 + 원인, 所以 + 결과",
          ko: "~ 때문에, 그래서 ~",
          ex: { zh: "因为下雨，所以我没去。", pinyin: "yīnwèi xiàyǔ, suǒyǐ wǒ méi qù", ko: "비가 와서 저는 안 갔어요." },
          ex2: { zh: "因为他病了，所以没来。", pinyin: "yīnwèi tā bìng le, suǒyǐ méi lái", ko: "그는 아파서 안 왔어요." },
          note: "한국어와 달리 因为·所以를 둘 다 쓰는 게 자연스러워요.",
        },
        {
          pattern: "虽然 … 但是 …",
          conn: "虽然 + 사실, 但是 + 반전",
          ko: "비록 ~지만, 그러나 ~",
          ex: { zh: "虽然很累，但是很高兴。", pinyin: "suīrán hěn lèi, dànshì hěn gāoxìng", ko: "비록 피곤하지만 기뻐요." },
          ex2: { zh: "虽然贵，但是很好。", pinyin: "suīrán guì, dànshì hěn hǎo", ko: "비싸지만 좋아요." },
        },
        {
          pattern: "如果 … (就) …",
          conn: "如果 + 가정, (就) + 결과",
          ko: "만약 ~라면, (그러면) ~",
          ex: { zh: "如果有时间，我就去。", pinyin: "rúguǒ yǒu shíjiān, wǒ jiù qù", ko: "시간이 있으면 갈게요." },
          ex2: { zh: "如果下雨，我们就不去。", pinyin: "rúguǒ xiàyǔ, wǒmen jiù bú qù", ko: "비가 오면 우리는 안 가요." },
        },
        {
          pattern: "一边 … 一边 …",
          conn: "一边 + 동사 + 一边 + 동사 — 동시 동작",
          ko: "~하면서 ~하다",
          ex: { zh: "他一边吃饭一边看电视。", pinyin: "tā yìbiān chī fàn yìbiān kàn diànshì", ko: "그는 밥을 먹으면서 TV를 봐요." },
          ex2: { zh: "我一边走一边唱歌。", pinyin: "wǒ yìbiān zǒu yìbiān chàng gē", ko: "저는 걸으면서 노래를 불러요." },
        },
        {
          pattern: "先 … 然后 …",
          conn: "先 + 동작1, 然后 + 동작2 — 순서",
          ko: "먼저 ~하고, 그다음 ~",
          ex: { zh: "我先吃饭，然后做作业。", pinyin: "wǒ xiān chī fàn, ránhòu zuò zuòyè", ko: "저는 먼저 밥을 먹고 나서 숙제를 해요." },
          ex2: { zh: "先洗手，然后吃饭。", pinyin: "xiān xǐshǒu, ránhòu chī fàn", ko: "먼저 손을 씻고 나서 밥을 먹어요." },
        },
        {
          pattern: "一 … 就 …",
          conn: "一 + 동작1 + 就 + 동작2 — 즉시",
          ko: "~하자마자 ~하다",
          ex: { zh: "我一回家就睡觉。", pinyin: "wǒ yì huí jiā jiù shuìjiào", ko: "저는 집에 오자마자 자요." },
          ex2: { zh: "他一看就懂了。", pinyin: "tā yí kàn jiù dǒng le", ko: "그는 보자마자 이해했어요." },
        },
        {
          pattern: "还是・或者",
          conn: "A 还是 B (의문) / A 或者 B (평서) — 선택",
          ko: "A 아니면 B / A 또는 B",
          ex: { zh: "你喝茶还是咖啡？", pinyin: "nǐ hē chá háishi kāfēi", ko: "차 마실래요, 커피 마실래요?" },
          ex2: { zh: "你或者我去都行。", pinyin: "nǐ huòzhě wǒ qù dōu xíng", ko: "당신이나 제가 가도 다 괜찮아요." },
          note: "선택의문문엔 还是, 평서문의 '또는'엔 或者를 써요.",
        },
      ],
    },
    {
      name: "능원·당위",
      items: [
        {
          pattern: "可以 + 동사",
          conn: "可以 + 동사 — 허락·가능",
          ko: "~해도 된다 / ~할 수 있다",
          ex: { zh: "这里可以拍照吗？", pinyin: "zhèlǐ kěyǐ pāizhào ma", ko: "여기서 사진 찍어도 되나요?" },
          ex2: { zh: "你可以坐这儿。", pinyin: "nǐ kěyǐ zuò zhèr", ko: "여기 앉으셔도 돼요." },
          note: "허락 거절은 不能·不可以. 不可以는 '안 돼요'에 가까워요.",
        },
        {
          pattern: "要 + 동사",
          conn: "要 + 동사 — 의지·필요",
          ko: "~하려 한다 / ~해야 한다",
          ex: { zh: "我要学汉语。", pinyin: "wǒ yào xué Hànyǔ", ko: "저는 중국어를 배우려고 해요." },
          ex2: { zh: "我不想去。", pinyin: "wǒ bù xiǎng qù", ko: "저는 가고 싶지 않아요." },
          note: "要의 부정은 의미에 따라 不想(의향) 또는 不用(불필요)으로 갈려요.",
        },
        {
          pattern: "应该 + 동사",
          conn: "应该 + 동사 — 마땅함",
          ko: "~해야 한다 / ~하는 게 맞다",
          ex: { zh: "你应该多休息。", pinyin: "nǐ yīnggāi duō xiūxi", ko: "당신은 좀 더 쉬어야 해요." },
          ex2: { zh: "我们不应该迟到。", pinyin: "wǒmen bù yīnggāi chídào", ko: "우리는 지각하면 안 돼요." },
        },
        {
          pattern: "得 + 동사",
          conn: "得(děi) + 동사 — 필요·당위 (구어)",
          ko: "~해야 한다",
          ex: { zh: "我得走了。", pinyin: "wǒ děi zǒu le", ko: "저 이제 가야 해요." },
          ex2: { zh: "你得早点儿来。", pinyin: "nǐ děi zǎodiǎnr lái", ko: "당신은 좀 일찍 와야 해요." },
          note: "이때 得는 děi로 읽어요. 정도보어의 得(de)와 다르니 주의.",
        },
        {
          pattern: "别 + 동사 + 了",
          conn: "别 + 동사 + 了 — 그만하라는 금지",
          ko: "그만 ~해 / ~하지 마",
          ex: { zh: "别说了。", pinyin: "bié shuō le", ko: "그만 말해." },
          ex2: { zh: "别担心。", pinyin: "bié dānxīn", ko: "걱정하지 마." },
        },
      ],
    },
    {
      name: "강조·어기",
      items: [
        {
          pattern: "是 … 的",
          conn: "是 + 시간/장소/방식 + 的 — 이미 일어난 일의 강조",
          ko: "~한 것이다 (언제·어디서·어떻게를 강조)",
          ex: { zh: "我是昨天来的。", pinyin: "wǒ shì zuótiān lái de", ko: "저는 어제 왔어요." },
          ex2: { zh: "他是坐飞机来的。", pinyin: "tā shì zuò fēijī lái de", ko: "그는 비행기를 타고 왔어요." },
          note: "이미 끝난 일에서 '언제·어떻게'를 부각할 때 是 … 的로 감싸요.",
        },
        {
          pattern: "还・还没",
          conn: "还 + 동사 (아직·여전히) / 还没 (아직 안)",
          ko: "아직 / 여전히 ~",
          ex: { zh: "他还在睡觉。", pinyin: "tā hái zài shuìjiào", ko: "그는 아직 자고 있어요." },
          ex2: { zh: "我还没吃饭。", pinyin: "wǒ hái méi chī fàn", ko: "저는 아직 밥을 안 먹었어요." },
        },
        {
          pattern: "已经 … 了",
          conn: "已经 + 술어 + 了 — 이미",
          ko: "이미 ~했다",
          ex: { zh: "我已经到了。", pinyin: "wǒ yǐjīng dào le", ko: "저는 이미 도착했어요." },
          ex2: { zh: "他已经走了。", pinyin: "tā yǐjīng zǒu le", ko: "그는 이미 갔어요." },
        },
        {
          pattern: "真 + 형용사",
          conn: "真 + 형용사 — 진심 어린 감탄",
          ko: "정말 ~하다",
          ex: { zh: "今天真冷！", pinyin: "jīntiān zhēn lěng", ko: "오늘 정말 춥다!" },
          ex2: { zh: "这个菜真好吃。", pinyin: "zhège cài zhēn hǎochī", ko: "이 요리 정말 맛있어요." },
          note: "真은 감탄·주관적, 很은 무난한 술어 표시로 어감이 달라요.",
        },
        {
          pattern: "有点儿 + 형용사",
          conn: "有点儿 + 형용사 — 살짝 부정적 어감",
          ko: "좀 ~하다 (불만·아쉬움)",
          ex: { zh: "今天有点儿累。", pinyin: "jīntiān yǒudiǎnr lèi", ko: "오늘은 좀 피곤해요." },
          ex2: { zh: "这个有点儿贵。", pinyin: "zhège yǒudiǎnr guì", ko: "이건 좀 비싸요." },
          note: "有点儿은 술어 앞(부정적), 一点儿은 형용사 뒤 비교에 써요 (便宜一点儿).",
        },
      ],
    },
  ],
};
