/**
 * H2 문형 사전 — HSK 2급 핵심 구문·표현 전수 커버 레이어 (SCHEMA.md 참고)
 * 챕터(grammar/h2.js)가 '이해'라면 이 사전은 '전수 검색'.
 */
export default {
  level: "H2",
  title: "2급 문형 사전",
  desc: "在 진행·过 경험·정도보어부터 比 비교, 因为·所以 연결, 개사틀(从·离·对·给), 가능보어 입문까지 — HSK 2급 핵심 문형을 기능별로 모두 모은 전수 검색 사전.",
  themes: [
    {
      name: "진행·경험·완료",
      items: [
        {
          pattern: "正在・在 + 동사 (+ 呢)",
          ch: "h2-03-zai-progressive",
          conn: "(正)在 + 동사 (+ 呢) — 동작의 진행",
          ko: "~하고 있다 (진행)",
          ex: { zh: "我在看电视呢。", pinyin: "wǒ zài kàn diànshì ne", ko: "저는 TV를 보고 있어요." },
          ex2: { zh: "他没在睡觉。", pinyin: "tā méi zài shuìjiào", ko: "그는 자고 있지 않아요." },
          note: "在는 진행, 着는 상태 지속. 문말 呢가 진행 어감을 더해요.",
        },
        {
          pattern: "동사 + 过",
          ch: "h2-02-guo-experience",
          conn: "동사 + 过 — 경험",
          ko: "~한 적이 있다 (경험)",
          ex: { zh: "我去过北京。", pinyin: "wǒ qù guo Běijīng", ko: "저는 베이징에 가 본 적 있어요." },
          ex2: { zh: "我没吃过羊肉。", pinyin: "wǒ méi chī guo yángròu", ko: "저는 양고기를 먹어 본 적 없어요." },
          note: "了는 완료, 过는 '겪어본 경험'. 부정은 没 + V + 过 (过를 남겨요).",
        },
        {
          pattern: "동사 + 了 + 수량 + 목적어",
          ch: "h2-01-le-completion",
          conn: "동사 + 了 + 수량사 + 목적어 — 완료된 분량",
          ko: "~을 (얼마만큼) 했다",
          ex: { zh: "我买了三本书。", pinyin: "wǒ mǎi le sān běn shū", ko: "저는 책을 세 권 샀어요." },
          ex2: { zh: "他喝了两杯咖啡。", pinyin: "tā hē le liǎng bēi kāfēi", ko: "그는 커피를 두 잔 마셨어요." },
        },
        {
          pattern: "동사 + 着",
          ch: "h3-10-existential",
          conn: "동사 + 着 — 상태의 지속",
          ko: "~한 채로 있다 / ~해 있다",
          ex: { zh: "门开着。", pinyin: "mén kāi zhe", ko: "문이 열려 있어요." },
          ex2: { zh: "他穿着一件红衣服。", pinyin: "tā chuān zhe yí jiàn hóng yīfu", ko: "그는 빨간 옷을 입고 있어요." },
          note: "着는 동작이 끝난 뒤의 '상태 지속'. 진행의 在와 구별해요.",
        },
        {
          pattern: "동사1 + 着 + 동사2",
          ch: "h3-10-existential",
          conn: "동사1 + 着 + 동사2 — 부수 동작",
          ko: "~한 채로 …하다",
          ex: { zh: "他笑着说。", pinyin: "tā xiào zhe shuō", ko: "그는 웃으면서 말했어요." },
          ex2: { zh: "我站着吃饭。", pinyin: "wǒ zhàn zhe chī fàn", ko: "저는 선 채로 밥을 먹어요." },
          note: "앞 동작이 뒤 동작의 '방식·자세'가 돼요 (V1着 + V2).",
        },
        {
          pattern: "快 … 了",
          ch: "h2-04-le-change",
          conn: "快(要) + 동사/형용사 + 了 — 임박",
          ko: "곧 ~하려 한다",
          ex: { zh: "火车快到了。", pinyin: "huǒchē kuài dào le", ko: "기차가 곧 도착해요." },
          ex2: { zh: "快下雨了。", pinyin: "kuài xiàyǔ le", ko: "곧 비가 올 것 같아요." },
        },
        {
          pattern: "就要 … 了",
          ch: "h2-04-le-change",
          conn: "(시간) + 就要 + 동사 + 了 — 임박 (시점 명시 가능)",
          ko: "곧 ~한다",
          ex: { zh: "我们就要放假了。", pinyin: "wǒmen jiùyào fàngjià le", ko: "우리는 곧 방학이에요." },
          ex2: { zh: "明天就要考试了。", pinyin: "míngtiān jiùyào kǎoshì le", ko: "내일이면 곧 시험이에요." },
          note: "快要 … 了와 달리 就要 … 了는 앞에 구체적 시점을 둘 수 있어요.",
        },
        {
          pattern: "要 … 了",
          ch: "h2-04-le-change",
          conn: "要 + 동사 + 了 — 곧 일어남",
          ko: "곧 ~할 것이다",
          ex: { zh: "我要去上海了。", pinyin: "wǒ yào qù Shànghǎi le", ko: "저는 곧 상하이에 가요." },
          ex2: { zh: "电影要开始了。", pinyin: "diànyǐng yào kāishǐ le", ko: "영화가 곧 시작해요." },
        },
        {
          pattern: "正在 … 呢",
          ch: "h2-03-zai-progressive",
          conn: "正在 + 동사 + 呢 — 바로 그때 진행 중",
          ko: "마침 ~하고 있다",
          ex: { zh: "我正在做饭呢。", pinyin: "wǒ zhèngzài zuò fàn ne", ko: "저는 마침 밥하고 있어요." },
          ex2: { zh: "他们正在开会。", pinyin: "tāmen zhèngzài kāihuì", ko: "그들은 지금 회의 중이에요." },
          note: "正在은 '바로 그 순간'을 강조하는 진행이에요.",
        },
        {
          pattern: "동사 + 过 + 几次",
          ch: "h2-02-guo-experience",
          conn: "동사 + 过 + 횟수 — 경험의 빈도",
          ko: "~한 적이 몇 번 있다",
          ex: { zh: "我去过两次中国。", pinyin: "wǒ qù guo liǎng cì Zhōngguó", ko: "저는 중국에 두 번 가 봤어요." },
          ex2: { zh: "这部电影我看过一次。", pinyin: "zhè bù diànyǐng wǒ kàn guo yí cì", ko: "이 영화 저는 한 번 본 적 있어요." },
        },
        {
          pattern: "没 + 동사",
          ch: "h1-06-negation",
          conn: "没(有) + 동사 — 안 했음",
          ko: "~하지 않았다",
          ex: { zh: "昨天我没上班。", pinyin: "zuótiān wǒ méi shàngbān", ko: "어제 저는 출근 안 했어요." },
          ex2: { zh: "他没告诉我。", pinyin: "tā méi gàosu wǒ", ko: "그는 저에게 안 알려 줬어요." },
          note: "완료 了의 부정은 没 + 동사. 了를 빼요.",
        },
      ],
    },
    {
      name: "보어 (결과·정도·시량)",
      items: [
        {
          pattern: "동사 + 完",
          ch: "h3-03-result-complement",
          conn: "동사 + 完 — 완료 결과보어",
          ko: "다 ~하다",
          ex: { zh: "我吃完了。", pinyin: "wǒ chī wán le", ko: "저는 다 먹었어요." },
          ex2: { zh: "作业还没做完。", pinyin: "zuòyè hái méi zuò wán", ko: "숙제를 아직 다 못 했어요." },
          note: "完은 '동작이 끝남'을 보충하는 결과보어. 부정은 没.",
        },
        {
          pattern: "동사 + 到・见",
          ch: "h3-03-result-complement",
          conn: "동사 + 到/见 — 도달·지각 결과보어",
          ko: "~해내다 / ~하게 되다",
          ex: { zh: "我看到他了。", pinyin: "wǒ kàn dào tā le", ko: "저는 그를 봤어요." },
          ex2: { zh: "我没听见。", pinyin: "wǒ méi tīng jiàn", ko: "저는 못 들었어요." },
          note: "看到·听见처럼 동작이 결과까지 이어졌음을 나타내요.",
        },
        {
          pattern: "동사 + 错・对",
          ch: "h3-03-result-complement",
          conn: "동사 + 错(틀림)/对(맞음) — 결과보어",
          ko: "잘못 ~하다 / 제대로 ~하다",
          ex: { zh: "我说错了。", pinyin: "wǒ shuō cuò le", ko: "제가 잘못 말했어요." },
          ex2: { zh: "你写对了。", pinyin: "nǐ xiě duì le", ko: "당신은 맞게 썼어요." },
        },
        {
          pattern: "동사 + 得 + 정도보어",
          ch: "h3-05-degree-complement",
          conn: "동사 + 得 + 형용사 — 정도·평가",
          ko: "~하는 정도가 …하다 (잘/빨리 등)",
          ex: { zh: "他说得很好。", pinyin: "tā shuō de hěn hǎo", ko: "그는 말을 잘해요." },
          ex2: { zh: "我起得不早。", pinyin: "wǒ qǐ de bù zǎo", ko: "저는 일찍 안 일어나요." },
          note: "목적어가 있으면 동사를 반복해요 (他说汉语说得很好).",
        },
        {
          pattern: "동사 + 시량보어",
          ch: "h2-08-complement-duration",
          conn: "동사 + 시간량 (얼마 동안)",
          ko: "(얼마 동안) ~하다",
          ex: { zh: "我学了两年汉语。", pinyin: "wǒ xué le liǎng nián Hànyǔ", ko: "저는 중국어를 2년 배웠어요." },
          ex2: { zh: "他睡了八个小时。", pinyin: "tā shuì le bā ge xiǎoshí", ko: "그는 8시간 잤어요." },
          note: "시간의 '길이'는 동사 뒤, 시점은 동사 앞. 목적어가 있으면 동사 반복도 가능.",
        },
        {
          pattern: "동사 + 一下",
          ch: "h2-10-complement-frequency",
          conn: "동사 + 一下 — 가볍게 잠깐",
          ko: "좀 ~하다",
          ex: { zh: "请等一下。", pinyin: "qǐng děng yíxià", ko: "잠깐만 기다려 주세요." },
          ex2: { zh: "我看一下。", pinyin: "wǒ kàn yíxià", ko: "제가 한번 볼게요." },
          note: "동작을 부드럽게 만드는 표현. 동사 중첩(看看)과 비슷한 어감.",
        },
        {
          pattern: "동사 + 开・住・好",
          ch: "h3-03-result-complement",
          conn: "동사 + 开(열림)/住(고정)/好(완성) — 결과보어",
          ko: "~해 열다/붙잡다/완성하다",
          ex: { zh: "请打开门。", pinyin: "qǐng dǎkāi mén", ko: "문을 열어 주세요." },
          ex2: { zh: "饭做好了。", pinyin: "fàn zuò hǎo le", ko: "밥이 다 됐어요." },
          note: "好는 '잘 마무리됨'을 보충해요 (做好 = 다 만들다).",
        },
        {
          pattern: "동사 + 得 + 不 + 보어",
          ch: "h3-05-degree-complement",
          conn: "동사 + 得 + 부정 정도보어",
          ko: "~하는 정도가 …하지 않다",
          ex: { zh: "他来得不晚。", pinyin: "tā lái de bù wǎn", ko: "그는 늦게 안 와요." },
          ex2: { zh: "我跑得不快。", pinyin: "wǒ pǎo de bú kuài", ko: "저는 빨리 못 달려요." },
          note: "정도보어의 부정은 보어 부분에 不을 넣어요 (得不 + 형용사).",
        },
        {
          pattern: "동사 + 多/少了",
          conn: "동사 + 형용사 + 了 — 결과 상태",
          ko: "~이 많아/적어졌다",
          ex: { zh: "今天人多了。", pinyin: "jīntiān rén duō le", ko: "오늘은 사람이 많아졌어요." },
          ex2: { zh: "天气暖和了。", pinyin: "tiānqì nuǎnhuo le", ko: "날씨가 따뜻해졌어요." },
        },
        {
          pattern: "동사 + 在 + 장소",
          ch: "h3-03-result-complement",
          conn: "동사 + 在 + 장소 — 동작 결과의 위치",
          ko: "~해서 (어디에) 있게 되다",
          ex: { zh: "他坐在前面。", pinyin: "tā zuò zài qiánmiàn", ko: "그는 앞쪽에 앉아 있어요." },
          ex2: { zh: "书放在桌子上。", pinyin: "shū fàng zài zhuōzi shang", ko: "책은 책상 위에 놓여 있어요." },
          note: "동작 뒤 결과로 머무는 장소는 동사 + 在 + 장소로 표현해요.",
        },
      ],
    },
    {
      name: "비교",
      items: [
        {
          pattern: "A 比 B + 형용사",
          ch: "h2-05-comparison-bi",
          conn: "A + 比 + B + 형용사 — 차등 비교",
          ko: "A는 B보다 ~하다",
          ex: { zh: "今天比昨天热。", pinyin: "jīntiān bǐ zuótiān rè", ko: "오늘이 어제보다 더워요." },
          ex2: { zh: "他比我高。", pinyin: "tā bǐ wǒ gāo", ko: "그는 저보다 키가 커요." },
          note: "比 비교문엔 很·非常을 안 써요 (×他比我很高). 정도는 一点儿·得多로.",
        },
        {
          pattern: "A 比 B + 형용사 + 一点儿・得多",
          ch: "h2-05-comparison-bi",
          conn: "A 比 B + 형용사 + 一点儿/得多 — 차이의 양",
          ko: "A가 B보다 조금/훨씬 ~하다",
          ex: { zh: "这个比那个贵一点儿。", pinyin: "zhège bǐ nàge guì yìdiǎnr", ko: "이게 저것보다 조금 비싸요." },
          ex2: { zh: "他比我大得多。", pinyin: "tā bǐ wǒ dà de duō", ko: "그는 저보다 훨씬 나이가 많아요." },
        },
        {
          pattern: "A 没有 B + 형용사",
          ch: "h2-05-comparison-bi",
          conn: "A + 没有 + B + 형용사 — 비교의 부정",
          ko: "A는 B만큼 ~하지 않다",
          ex: { zh: "我没有他高。", pinyin: "wǒ méiyǒu tā gāo", ko: "저는 그만큼 키가 크지 않아요." },
          ex2: { zh: "今天没有昨天冷。", pinyin: "jīntiān méiyǒu zuótiān lěng", ko: "오늘은 어제만큼 춥지 않아요." },
          note: "比의 부정은 不比보다 没有 … 를 더 흔히 써요.",
        },
        {
          pattern: "A 跟 B 一样",
          ch: "h2-05-comparison-bi",
          conn: "A + 跟 + B + 一样 (+ 형용사) — 동등 비교",
          ko: "A는 B와 같다 / 똑같이 ~하다",
          ex: { zh: "我的手机跟你的一样。", pinyin: "wǒ de shǒujī gēn nǐ de yíyàng", ko: "제 휴대폰은 당신 것과 같아요." },
          ex2: { zh: "他跟我一样高。", pinyin: "tā gēn wǒ yíyàng gāo", ko: "그는 저와 키가 같아요." },
        },
        {
          pattern: "最 + 형용사",
          ch: "h2-05-comparison-bi",
          conn: "最 + 형용사 — 최상급",
          ko: "가장 ~하다",
          ex: { zh: "这个最好。", pinyin: "zhège zuì hǎo", ko: "이게 제일 좋아요." },
          ex2: { zh: "我最喜欢这个。", pinyin: "wǒ zuì xǐhuan zhège", ko: "저는 이걸 가장 좋아해요." },
        },
        {
          pattern: "A 有 B 这么/那么 + 형용사",
          ch: "h2-05-comparison-bi",
          conn: "A + 有 + B + 这么/那么 + 형용사 — 동급 비교",
          ko: "A는 B만큼 그렇게 ~하다",
          ex: { zh: "他有你这么高吗？", pinyin: "tā yǒu nǐ zhème gāo ma", ko: "그가 너만큼 키가 커?" },
          ex2: { zh: "今天没有昨天那么冷。", pinyin: "jīntiān méiyǒu zuótiān nàme lěng", ko: "오늘은 어제만큼 그렇게 춥지 않아요." },
        },
        {
          pattern: "更 + 형용사",
          ch: "h2-05-comparison-bi",
          conn: "更 + 형용사 — 한층 더",
          ko: "더욱 ~하다",
          ex: { zh: "这个更好。", pinyin: "zhège gèng hǎo", ko: "이게 더 좋아요." },
          ex2: { zh: "明天会更冷。", pinyin: "míngtiān huì gèng lěng", ko: "내일은 더 추울 거예요." },
        },
        {
          pattern: "A 不如 B",
          ch: "h2-05-comparison-bi",
          conn: "A + 不如 + B (+ 형용사) — ~만 못함",
          ko: "A는 B만 못하다",
          ex: { zh: "我的汉语不如他。", pinyin: "wǒ de Hànyǔ bùrú tā", ko: "제 중국어는 그만 못해요." },
          ex2: { zh: "坐车不如走路快。", pinyin: "zuò chē bùrú zǒulù kuài", ko: "차 타는 게 걷는 것보다 빠르지 않아요." },
        },
        {
          pattern: "和 … 差不多",
          ch: "h2-05-comparison-bi",
          conn: "A + 和 + B + 差不多 — 거의 비슷",
          ko: "A는 B와 비슷하다",
          ex: { zh: "他和我差不多高。", pinyin: "tā hé wǒ chàbuduō gāo", ko: "그는 저와 키가 비슷해요." },
          ex2: { zh: "价格差不多。", pinyin: "jiàgé chàbuduō", ko: "가격이 비슷해요." },
        },
      ],
    },
    {
      name: "개사틀",
      items: [
        {
          pattern: "从 + 장소/시간",
          ch: "h2-07-prepositions",
          conn: "从 + 출발점 (+ 到) + 동사",
          ko: "~에서(부터) …하다",
          ex: { zh: "我从北京来。", pinyin: "wǒ cóng Běijīng lái", ko: "저는 베이징에서 왔어요." },
          ex2: { zh: "从这儿到那儿很近。", pinyin: "cóng zhèr dào nàr hěn jìn", ko: "여기서 저기까지 가까워요." },
          note: "从 … 到 …는 '~에서 ~까지'. 출발점·시작점을 나타내요.",
        },
        {
          pattern: "离 + 기준점",
          ch: "h2-07-prepositions",
          conn: "A + 离 + B + 远/近 — 거리",
          ko: "A는 B에서 멀다/가깝다",
          ex: { zh: "我家离公司很近。", pinyin: "wǒ jiā lí gōngsī hěn jìn", ko: "저희 집은 회사에서 가까워요." },
          ex2: { zh: "学校离这儿不远。", pinyin: "xuéxiào lí zhèr bù yuǎn", ko: "학교는 여기서 멀지 않아요." },
          note: "거리·간격의 기준점은 离, 출발점은 从으로 구별해요.",
        },
        {
          pattern: "对 + 대상",
          ch: "h2-07-prepositions",
          conn: "对 + 대상 + 술어 — ~에 대해/에게",
          ko: "~에 대해 / ~에게",
          ex: { zh: "他对我很好。", pinyin: "tā duì wǒ hěn hǎo", ko: "그는 저에게 잘해 줘요." },
          ex2: { zh: "我对中国文化很感兴趣。", pinyin: "wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù", ko: "저는 중국 문화에 관심이 많아요." },
        },
        {
          pattern: "给 + 사람 + 동사",
          ch: "h2-07-prepositions",
          conn: "给 + 대상 + 동사 — ~에게/위해",
          ko: "~에게 …해 주다",
          ex: { zh: "我给妈妈打电话。", pinyin: "wǒ gěi māma dǎ diànhuà", ko: "저는 엄마에게 전화해요." },
          ex2: { zh: "他给我买了礼物。", pinyin: "tā gěi wǒ mǎi le lǐwù", ko: "그는 저에게 선물을 사 줬어요." },
        },
        {
          pattern: "为了 + 목적",
          ch: "h3-08-complex-sentence",
          conn: "为了 + 목적 + 주절",
          ko: "~을 위해 …하다",
          ex: { zh: "为了考试，我每天学习。", pinyin: "wèile kǎoshì, wǒ měi tiān xuéxí", ko: "시험을 위해 저는 매일 공부해요." },
          ex2: { zh: "为了身体，他每天跑步。", pinyin: "wèile shēntǐ, tā měi tiān pǎobù", ko: "건강을 위해 그는 매일 달리기를 해요." },
        },
        {
          pattern: "关于 …",
          ch: "h2-07-prepositions",
          conn: "关于 + 화제 + 절",
          ko: "~에 관하여",
          ex: { zh: "关于这件事，我不太清楚。", pinyin: "guānyú zhè jiàn shì, wǒ bú tài qīngchu", ko: "이 일에 관해서는 잘 몰라요." },
          ex2: { zh: "我有一个关于工作的问题。", pinyin: "wǒ yǒu yí ge guānyú gōngzuò de wèntí", ko: "일에 관한 질문이 하나 있어요." },
        },
        {
          pattern: "向・往 + 방향",
          ch: "h2-07-prepositions",
          conn: "向/往 + 방향 + 동사",
          ko: "~쪽으로 …하다",
          ex: { zh: "一直往前走。", pinyin: "yìzhí wǎng qián zǒu", ko: "쭉 앞으로 가세요." },
          ex2: { zh: "请向左转。", pinyin: "qǐng xiàng zuǒ zhuǎn", ko: "왼쪽으로 도세요." },
        },
        {
          pattern: "把 + 사물 + 给 + 사람",
          ch: "h3-01-ba",
          conn: "把 + 사물 + 给 + 사람 — ~을 ~에게 주다",
          ko: "~을 ~에게 건네다/주다",
          ex: { zh: "请把书给我。", pinyin: "qǐng bǎ shū gěi wǒ", ko: "그 책 저에게 주세요." },
          ex2: { zh: "他把礼物给了妈妈。", pinyin: "tā bǎ lǐwù gěi le māma", ko: "그는 선물을 엄마에게 줬어요." },
          note: "2급에서 만나는 把의 가장 쉬운 형태예요 (3급에서 본격적으로 다뤄요).",
        },
        {
          pattern: "比 + 시간/장소",
          ch: "h2-05-comparison-bi",
          conn: "A + 比 + B — 비교 개사",
          ko: "A는 B보다 ~",
          ex: { zh: "弟弟比我矮。", pinyin: "dìdi bǐ wǒ ǎi", ko: "남동생은 저보다 키가 작아요." },
          ex2: { zh: "坐地铁比坐公交快。", pinyin: "zuò dìtiě bǐ zuò gōngjiāo kuài", ko: "지하철 타는 게 버스보다 빨라요." },
        },
        {
          pattern: "在 + 시간/장소 + 동사",
          ch: "h1-09-time-place",
          conn: "在 + 시점/장소 + 동사",
          ko: "(언제·어디서) ~하다",
          ex: { zh: "我在家工作。", pinyin: "wǒ zài jiā gōngzuò", ko: "저는 집에서 일해요." },
          ex2: { zh: "我们在七点见面。", pinyin: "wǒmen zài qī diǎn jiànmiàn", ko: "우리는 7시에 만나요." },
        },
        {
          pattern: "跟・和 + 사람 + 동사",
          ch: "h2-07-prepositions",
          conn: "跟/和 + 대상 + 동사 — ~와",
          ko: "~와 함께/에게 …하다",
          ex: { zh: "我跟朋友去看电影。", pinyin: "wǒ gēn péngyou qù kàn diànyǐng", ko: "저는 친구와 영화 보러 가요." },
          ex2: { zh: "请跟我来。", pinyin: "qǐng gēn wǒ lái", ko: "저를 따라오세요." },
        },
        {
          pattern: "用 + 도구 + 동사",
          ch: "h2-07-prepositions",
          conn: "用 + 수단/도구 + 동사 — ~으로",
          ko: "~을 써서/~으로 …하다",
          ex: { zh: "我用筷子吃饭。", pinyin: "wǒ yòng kuàizi chī fàn", ko: "저는 젓가락으로 밥을 먹어요." },
          ex2: { zh: "请用汉语说。", pinyin: "qǐng yòng Hànyǔ shuō", ko: "중국어로 말해 주세요." },
        },
        {
          pattern: "到 + 장소 + 동사",
          ch: "h2-07-prepositions",
          conn: "到 + 도착지 + 동사 — ~에 가서",
          ko: "~에 가서/도착해서 …하다",
          ex: { zh: "我到北京去旅行。", pinyin: "wǒ dào Běijīng qù lǚxíng", ko: "저는 베이징에 여행 가요." },
          ex2: { zh: "到家给我打电话。", pinyin: "dào jiā gěi wǒ dǎ diànhuà", ko: "집에 도착하면 전화해." },
        },
      ],
    },
    {
      name: "연결·접속",
      items: [
        {
          pattern: "因为 … 所以 …",
          ch: "h3-08-complex-sentence",
          conn: "因为 + 원인, 所以 + 결과",
          ko: "~ 때문에, 그래서 ~",
          ex: { zh: "因为下雨，所以我没去。", pinyin: "yīnwèi xiàyǔ, suǒyǐ wǒ méi qù", ko: "비가 와서 저는 안 갔어요." },
          ex2: { zh: "因为他病了，所以没来。", pinyin: "yīnwèi tā bìng le, suǒyǐ méi lái", ko: "그는 아파서 안 왔어요." },
          note: "한국어와 달리 因为·所以를 둘 다 쓰는 게 자연스러워요.",
        },
        {
          pattern: "虽然 … 但是 …",
          ch: "h3-08-complex-sentence",
          conn: "虽然 + 사실, 但是 + 반전",
          ko: "비록 ~지만, 그러나 ~",
          ex: { zh: "虽然很累，但是很高兴。", pinyin: "suīrán hěn lèi, dànshì hěn gāoxìng", ko: "비록 피곤하지만 기뻐요." },
          ex2: { zh: "虽然贵，但是很好。", pinyin: "suīrán guì, dànshì hěn hǎo", ko: "비싸지만 좋아요." },
        },
        {
          pattern: "如果 … (就) …",
          ch: "h3-08-complex-sentence",
          conn: "如果 + 가정, (就) + 결과",
          ko: "만약 ~라면, (그러면) ~",
          ex: { zh: "如果有时间，我就去。", pinyin: "rúguǒ yǒu shíjiān, wǒ jiù qù", ko: "시간이 있으면 갈게요." },
          ex2: { zh: "如果下雨，我们就不去。", pinyin: "rúguǒ xiàyǔ, wǒmen jiù bú qù", ko: "비가 오면 우리는 안 가요." },
        },
        {
          pattern: "一边 … 一边 …",
          ch: "h3-08-complex-sentence",
          conn: "一边 + 동사 + 一边 + 동사 — 동시 동작",
          ko: "~하면서 ~하다",
          ex: { zh: "他一边吃饭一边看电视。", pinyin: "tā yìbiān chī fàn yìbiān kàn diànshì", ko: "그는 밥을 먹으면서 TV를 봐요." },
          ex2: { zh: "我一边走一边唱歌。", pinyin: "wǒ yìbiān zǒu yìbiān chàng gē", ko: "저는 걸으면서 노래를 불러요." },
        },
        {
          pattern: "先 … 然后 …",
          ch: "h3-08-complex-sentence",
          conn: "先 + 동작1, 然后 + 동작2 — 순서",
          ko: "먼저 ~하고, 그다음 ~",
          ex: { zh: "我先吃饭，然后做作业。", pinyin: "wǒ xiān chī fàn, ránhòu zuò zuòyè", ko: "저는 먼저 밥을 먹고 나서 숙제를 해요." },
          ex2: { zh: "先洗手，然后吃饭。", pinyin: "xiān xǐshǒu, ránhòu chī fàn", ko: "먼저 손을 씻고 나서 밥을 먹어요." },
        },
        {
          pattern: "一 … 就 …",
          ch: "h3-08-complex-sentence",
          conn: "一 + 동작1 + 就 + 동작2 — 즉시",
          ko: "~하자마자 ~하다",
          ex: { zh: "我一回家就睡觉。", pinyin: "wǒ yì huí jiā jiù shuìjiào", ko: "저는 집에 오자마자 자요." },
          ex2: { zh: "他一看就懂了。", pinyin: "tā yí kàn jiù dǒng le", ko: "그는 보자마자 이해했어요." },
        },
        {
          pattern: "还是・或者",
          ch: "h2-09-haishi",
          conn: "A 还是 B (의문) / A 或者 B (평서) — 선택",
          ko: "A 아니면 B / A 또는 B",
          ex: { zh: "你喝茶还是咖啡？", pinyin: "nǐ hē chá háishi kāfēi", ko: "차 마실래요, 커피 마실래요?" },
          ex2: { zh: "你或者我去都行。", pinyin: "nǐ huòzhě wǒ qù dōu xíng", ko: "당신이나 제가 가도 다 괜찮아요." },
          note: "선택의문문엔 还是, 평서문의 '또는'엔 或者를 써요.",
        },
        {
          pattern: "不是 … 就是 …",
          ch: "h3-08-complex-sentence",
          conn: "不是 + A + 就是 + B — 둘 중 하나",
          ko: "A 아니면 B다",
          ex: { zh: "他不是在家就是在公司。", pinyin: "tā búshì zài jiā jiùshì zài gōngsī", ko: "그는 집 아니면 회사에 있어요." },
          ex2: { zh: "我每天不是学习就是工作。", pinyin: "wǒ měi tiān búshì xuéxí jiùshì gōngzuò", ko: "저는 매일 공부 아니면 일이에요." },
        },
        {
          pattern: "一边 … 一边 …의 연속 / 然后",
          ch: "h3-08-complex-sentence",
          conn: "동작1, 然后 + 동작2 — 그다음",
          ko: "~하고, 그러고 나서 ~",
          ex: { zh: "我先回家，然后去买东西。", pinyin: "wǒ xiān huí jiā, ránhòu qù mǎi dōngxi", ko: "저는 먼저 집에 가고 그다음 장 보러 가요." },
          ex2: { zh: "我们吃完饭，然后散步。", pinyin: "wǒmen chī wán fàn, ránhòu sànbù", ko: "우리는 밥 다 먹고 그다음 산책해요." },
        },
        {
          pattern: "因为 …",
          ch: "h3-08-complex-sentence",
          conn: "因为 + 원인 (단독)",
          ko: "~ 때문에",
          ex: { zh: "我没去，因为下雨了。", pinyin: "wǒ méi qù, yīnwèi xiàyǔ le", ko: "비가 와서 안 갔어요." },
          ex2: { zh: "因为太贵，我没买。", pinyin: "yīnwèi tài guì, wǒ méi mǎi", ko: "너무 비싸서 안 샀어요." },
          note: "구어에선 因为만 쓰고 所以를 생략하기도 해요.",
        },
      ],
    },
    {
      name: "능원·당위",
      items: [
        {
          pattern: "可以 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "可以 + 동사 — 허락·가능",
          ko: "~해도 된다 / ~할 수 있다",
          ex: { zh: "这里可以拍照吗？", pinyin: "zhèlǐ kěyǐ pāizhào ma", ko: "여기서 사진 찍어도 되나요?" },
          ex2: { zh: "你可以坐这儿。", pinyin: "nǐ kěyǐ zuò zhèr", ko: "여기 앉으셔도 돼요." },
          note: "허락 거절은 不能·不可以. 不可以는 '안 돼요'에 가까워요.",
        },
        {
          pattern: "会 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "会 + 동사 (+ 的) — ~일 것이다",
          ko: "~할 것이다 (가능성)",
          ex: { zh: "他明天会来的。", pinyin: "tā míngtiān huì lái de", ko: "그는 내일 올 거예요." },
          ex2: { zh: "不会有问题的。", pinyin: "bú huì yǒu wèntí de", ko: "문제없을 거예요." },
          note: "会 … 的는 '분명 그럴 것'이라는 확신 어린 추측이에요.",
        },
        {
          pattern: "要 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "要 + 동사 — 의지·필요",
          ko: "~하려 한다 / ~해야 한다",
          ex: { zh: "我要学汉语。", pinyin: "wǒ yào xué Hànyǔ", ko: "저는 중국어를 배우려고 해요." },
          ex2: { zh: "我不想去。", pinyin: "wǒ bù xiǎng qù", ko: "저는 가고 싶지 않아요." },
          note: "要의 부정은 의미에 따라 不想(의향) 또는 不用(불필요)으로 갈려요.",
        },
        {
          pattern: "应该 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "应该 + 동사 — 마땅함",
          ko: "~해야 한다 / ~하는 게 맞다",
          ex: { zh: "你应该多休息。", pinyin: "nǐ yīnggāi duō xiūxi", ko: "당신은 좀 더 쉬어야 해요." },
          ex2: { zh: "我们不应该迟到。", pinyin: "wǒmen bù yīnggāi chídào", ko: "우리는 지각하면 안 돼요." },
        },
        {
          pattern: "得 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "得(děi) + 동사 — 필요·당위 (구어)",
          ko: "~해야 한다",
          ex: { zh: "我得走了。", pinyin: "wǒ děi zǒu le", ko: "저 이제 가야 해요." },
          ex2: { zh: "你得早点儿来。", pinyin: "nǐ děi zǎodiǎnr lái", ko: "당신은 좀 일찍 와야 해요." },
          note: "이때 得는 děi로 읽어요. 정도보어의 得(de)와 다르니 주의.",
        },
        {
          pattern: "别 + 동사 + 了",
          ch: "h1-06-negation",
          conn: "别 + 동사 + 了 — 그만하라는 금지",
          ko: "그만 ~해 / ~하지 마",
          ex: { zh: "别说了。", pinyin: "bié shuō le", ko: "그만 말해." },
          ex2: { zh: "别担心。", pinyin: "bié dānxīn", ko: "걱정하지 마." },
        },
        {
          pattern: "愿意 + 동사",
          conn: "愿意 + 동사 — 기꺼이 ~하다",
          ko: "기꺼이 ~하려 하다",
          ex: { zh: "我愿意帮助你。", pinyin: "wǒ yuànyì bāngzhù nǐ", ko: "기꺼이 당신을 도울게요." },
          ex2: { zh: "他不愿意去。", pinyin: "tā bú yuànyì qù", ko: "그는 가고 싶어 하지 않아요." },
        },
        {
          pattern: "需要 + 명사/동사",
          conn: "需要 + 명사/동사 — 필요",
          ko: "~이 필요하다 / ~할 필요가 있다",
          ex: { zh: "我需要休息。", pinyin: "wǒ xūyào xiūxi", ko: "저는 쉬어야 해요." },
          ex2: { zh: "不需要这么多。", pinyin: "bù xūyào zhème duō", ko: "이렇게 많이는 필요 없어요." },
        },
        {
          pattern: "可能 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "可能 + 술어 — 가능성 추측",
          ko: "아마 ~일 것이다",
          ex: { zh: "他可能不来了。", pinyin: "tā kěnéng bù lái le", ko: "그는 아마 안 올 거예요." },
          ex2: { zh: "明天可能下雨。", pinyin: "míngtiān kěnéng xiàyǔ", ko: "내일 비가 올 수도 있어요." },
        },
      ],
    },
    {
      name: "강조·어기",
      items: [
        {
          pattern: "是 … 的",
          ch: "h4-03-shi-de",
          conn: "是 + 시간/장소/방식 + 的 — 이미 일어난 일의 강조",
          ko: "~한 것이다 (언제·어디서·어떻게를 강조)",
          ex: { zh: "我是昨天来的。", pinyin: "wǒ shì zuótiān lái de", ko: "저는 어제 왔어요." },
          ex2: { zh: "他是坐飞机来的。", pinyin: "tā shì zuò fēijī lái de", ko: "그는 비행기를 타고 왔어요." },
          note: "이미 끝난 일에서 '언제·어떻게'를 부각할 때 是 … 的로 감싸요.",
        },
        {
          pattern: "还・还没",
          conn: "还 + 동사 (아직·여전히) / 还没 (아직 안)",
          ko: "아직 / 여전히 ~",
          ex: { zh: "他还在睡觉。", pinyin: "tā hái zài shuìjiào", ko: "그는 아직 자고 있어요." },
          ex2: { zh: "我还没吃饭。", pinyin: "wǒ hái méi chī fàn", ko: "저는 아직 밥을 안 먹었어요." },
        },
        {
          pattern: "已经 … 了",
          ch: "h2-04-le-change",
          conn: "已经 + 술어 + 了 — 이미",
          ko: "이미 ~했다",
          ex: { zh: "我已经到了。", pinyin: "wǒ yǐjīng dào le", ko: "저는 이미 도착했어요." },
          ex2: { zh: "他已经走了。", pinyin: "tā yǐjīng zǒu le", ko: "그는 이미 갔어요." },
        },
        {
          pattern: "真 + 형용사",
          conn: "真 + 형용사 — 진심 어린 감탄",
          ko: "정말 ~하다",
          ex: { zh: "今天真冷！", pinyin: "jīntiān zhēn lěng", ko: "오늘 정말 춥다!" },
          ex2: { zh: "这个菜真好吃。", pinyin: "zhège cài zhēn hǎochī", ko: "이 요리 정말 맛있어요." },
          note: "真은 감탄·주관적, 很은 무난한 술어 표시로 어감이 달라요.",
        },
        {
          pattern: "当然 …",
          conn: "当然 + 절 — 당연히",
          ko: "당연히 ~",
          ex: { zh: "我当然愿意。", pinyin: "wǒ dāngrán yuànyì", ko: "당연히 좋아요." },
          ex2: { zh: "这件事他当然知道。", pinyin: "zhè jiàn shì tā dāngrán zhīdào", ko: "이 일은 그가 당연히 알아요." },
        },
        {
          pattern: "终于 … 了",
          conn: "终于 + 술어 + 了 — 마침내",
          ko: "마침내 ~했다",
          ex: { zh: "我终于到了。", pinyin: "wǒ zhōngyú dào le", ko: "드디어 도착했어요." },
          ex2: { zh: "他终于来了。", pinyin: "tā zhōngyú lái le", ko: "그가 마침내 왔어요." },
        },
        {
          pattern: "又 … 又 …",
          conn: "又 + A + 又 + B — 두 속성 병렬",
          ko: "~하기도 하고 ~하기도 하다",
          ex: { zh: "这个又便宜又好。", pinyin: "zhège yòu piányi yòu hǎo", ko: "이건 싸기도 하고 좋기도 해요." },
          ex2: { zh: "他又累又饿。", pinyin: "tā yòu lèi yòu è", ko: "그는 피곤하기도 하고 배고프기도 해요." },
        },
        {
          pattern: "有点儿 + 형용사",
          conn: "有点儿 + 형용사 — 살짝 부정적 어감",
          ko: "좀 ~하다 (불만·아쉬움)",
          ex: { zh: "今天有点儿累。", pinyin: "jīntiān yǒudiǎnr lèi", ko: "오늘은 좀 피곤해요." },
          ex2: { zh: "这个有点儿贵。", pinyin: "zhège yǒudiǎnr guì", ko: "이건 좀 비싸요." },
          note: "有点儿은 술어 앞(부정적), 一点儿은 형용사 뒤 비교에 써요 (便宜一点儿).",
        },
        {
          pattern: "多 + 동사 / 少 + 동사",
          conn: "多/少 + 동사 — 더/덜 ~하다",
          ko: "많이/적게 ~하다",
          ex: { zh: "你应该多休息。", pinyin: "nǐ yīnggāi duō xiūxi", ko: "좀 더 쉬어야 해요." },
          ex2: { zh: "请少放盐。", pinyin: "qǐng shǎo fàng yán", ko: "소금을 적게 넣어 주세요." },
          note: "多·少가 동사 앞에 오면 '더·덜'이라는 양 조절이 돼요.",
        },
        {
          pattern: "一点儿也不・都不",
          conn: "一点儿 + 也/都 + 不/没 — 조금도",
          ko: "조금도 ~하지 않다",
          ex: { zh: "我一点儿也不累。", pinyin: "wǒ yìdiǎnr yě bú lèi", ko: "저는 조금도 안 피곤해요." },
          ex2: { zh: "他一点儿都没吃。", pinyin: "tā yìdiǎnr dōu méi chī", ko: "그는 조금도 안 먹었어요." },
        },
      ],
    },
    {
      name: "시간량·빈도",
      items: [
        {
          pattern: "동사 + 횟수",
          ch: "h2-10-complement-frequency",
          conn: "동사 + 수사 + 次/遍 — 몇 번",
          ko: "~을 몇 번 …하다",
          ex: { zh: "我去过两次。", pinyin: "wǒ qù guo liǎng cì", ko: "저는 두 번 가 봤어요." },
          ex2: { zh: "请再说一遍。", pinyin: "qǐng zài shuō yí biàn", ko: "한 번 더 말해 주세요." },
          note: "次는 동작 횟수, 遍은 처음부터 끝까지 한 번을 셀 때 써요.",
        },
        {
          pattern: "每 + 시간 + 都",
          ch: "h1-09-time-place",
          conn: "每天/每年 + 都 + 동사 — 매번",
          ko: "매일/매년 ~하다",
          ex: { zh: "我每天都跑步。", pinyin: "wǒ měi tiān dōu pǎobù", ko: "저는 매일 달리기를 해요." },
          ex2: { zh: "他每年都回国。", pinyin: "tā měi nián dōu huíguó", ko: "그는 매년 귀국해요." },
        },
        {
          pattern: "… 的时候",
          conn: "동사구 + 的时候 — ~할 때",
          ko: "~할 때",
          ex: { zh: "我小的时候很瘦。", pinyin: "wǒ xiǎo de shíhou hěn shòu", ko: "저는 어렸을 때 말랐어요." },
          ex2: { zh: "走的时候请关灯。", pinyin: "zǒu de shíhou qǐng guān dēng", ko: "나갈 때 불을 꺼 주세요." },
        },
        {
          pattern: "以前・以后",
          conn: "동사구 + 以前/以后 — ~전/후에",
          ko: "~하기 전에 / 한 후에",
          ex: { zh: "来中国以前我学过汉语。", pinyin: "lái Zhōngguó yǐqián wǒ xué guo Hànyǔ", ko: "중국에 오기 전에 중국어를 배운 적 있어요." },
          ex2: { zh: "下班以后我去运动。", pinyin: "xiàbān yǐhòu wǒ qù yùndòng", ko: "퇴근 후에 저는 운동하러 가요." },
        },
        {
          pattern: "从 … 到 …",
          ch: "h2-07-prepositions",
          conn: "从 + 시작 + 到 + 끝 — ~부터 ~까지",
          ko: "~에서 ~까지",
          ex: { zh: "我从九点到五点上班。", pinyin: "wǒ cóng jiǔ diǎn dào wǔ diǎn shàngbān", ko: "저는 9시부터 5시까지 일해요." },
          ex2: { zh: "从这儿到学校很近。", pinyin: "cóng zhèr dào xuéxiào hěn jìn", ko: "여기서 학교까지 가까워요." },
        },
        {
          pattern: "동사 + 了 + 시간 + 了",
          ch: "h2-08-complement-duration",
          conn: "동사 + 了 + 기간 + 了 — 지금까지 ~해 온",
          ko: "~한 지 (얼마)가 되다",
          ex: { zh: "我学汉语学了一年了。", pinyin: "wǒ xué Hànyǔ xué le yì nián le", ko: "저는 중국어를 배운 지 1년 됐어요." },
          ex2: { zh: "他来中国半年了。", pinyin: "tā lái Zhōngguó bàn nián le", ko: "그가 중국에 온 지 반년 됐어요." },
          note: "문말 了까지 붙으면 '지금도 이어지고 있다'는 뜻이 더해져요.",
        },
      ],
    },
    {
      name: "의문 심화",
      items: [
        {
          pattern: "多 + 형용사？",
          conn: "多 + 大/高/长 — 정도를 묻는 의문",
          ko: "얼마나 ~해요?",
          ex: { zh: "你今年多大？", pinyin: "nǐ jīnnián duō dà", ko: "올해 나이가 어떻게 되세요?" },
          ex2: { zh: "这条路多长？", pinyin: "zhè tiáo lù duō cháng", ko: "이 길은 얼마나 길어요?" },
        },
        {
          pattern: "是不是 …？",
          ch: "h1-05-ma-questions",
          conn: "是不是 + 절 — 추측 확인",
          ko: "~인 거 아니에요? / 맞죠?",
          ex: { zh: "你是不是累了？", pinyin: "nǐ shì bu shì lèi le", ko: "당신 피곤한 거 아니에요?" },
          ex2: { zh: "他是不是不来了？", pinyin: "tā shì bu shì bù lái le", ko: "그 사람 안 오는 거 맞죠?" },
        },
        {
          pattern: "怎么了？",
          ch: "h1-05-ma-questions",
          conn: "怎么了 — 무슨 일 묻기 (고정)",
          ko: "무슨 일이에요? / 왜 그래요?",
          ex: { zh: "你怎么了？", pinyin: "nǐ zěnme le", ko: "무슨 일 있어요?" },
          ex2: { zh: "他怎么了？是不是生病了？", pinyin: "tā zěnme le? shì bu shì shēngbìng le", ko: "그 사람 왜 그래요? 아픈 거 아니에요?" },
        },
        {
          pattern: "好不好・行不行・对不对",
          ch: "h1-05-ma-questions",
          conn: "형용사 정반의문 — 동의·확인",
          ko: "괜찮죠? / 되죠? / 맞죠?",
          ex: { zh: "我们坐这儿，好不好？", pinyin: "wǒmen zuò zhèr, hǎo bu hǎo", ko: "우리 여기 앉아요, 괜찮죠?" },
          ex2: { zh: "明天去，行不行？", pinyin: "míngtiān qù, xíng bu xíng", ko: "내일 가는 거 괜찮아요?" },
        },
      ],
    },
    {
      name: "감정·상태 표현",
      items: [
        {
          pattern: "觉得 …",
          conn: "주어 + 觉得 + 절 — ~라고 느끼다/생각하다",
          ko: "~인 것 같다 / ~라고 생각하다",
          ex: { zh: "我觉得这个很好。", pinyin: "wǒ juéde zhège hěn hǎo", ko: "저는 이게 좋은 것 같아요." },
          ex2: { zh: "你觉得怎么样？", pinyin: "nǐ juéde zěnmeyàng", ko: "당신 생각엔 어때요?" },
        },
        {
          pattern: "希望 …",
          conn: "希望 + 절 — 바람",
          ko: "~하길 바라다",
          ex: { zh: "我希望你快点儿好。", pinyin: "wǒ xīwàng nǐ kuàidiǎnr hǎo", ko: "빨리 낫길 바라요." },
          ex2: { zh: "希望明天天气好。", pinyin: "xīwàng míngtiān tiānqì hǎo", ko: "내일 날씨가 좋길 바라요." },
        },
        {
          pattern: "知道・不知道 …",
          conn: "知道 + 절/의문절 — 알다/모르다",
          ko: "~을 알다 / 모르다",
          ex: { zh: "我知道他在哪儿。", pinyin: "wǒ zhīdào tā zài nǎr", ko: "저는 그가 어디 있는지 알아요." },
          ex2: { zh: "我不知道怎么去。", pinyin: "wǒ bù zhīdào zěnme qù", ko: "어떻게 가는지 모르겠어요." },
        },
        {
          pattern: "好像・像 …",
          conn: "好像/像 + 명사/절 — ~같다",
          ko: "~인 것 같다 / ~을 닮다",
          ex: { zh: "他好像很忙。", pinyin: "tā hǎoxiàng hěn máng", ko: "그는 바쁜 것 같아요." },
          ex2: { zh: "你像你妈妈。", pinyin: "nǐ xiàng nǐ māma", ko: "당신은 어머니를 닮았어요." },
        },
        {
          pattern: "怕・担心 …",
          conn: "怕/担心 + 절 — 걱정·우려",
          ko: "~할까 봐 걱정하다",
          ex: { zh: "我担心他迟到。", pinyin: "wǒ dānxīn tā chídào", ko: "그가 늦을까 봐 걱정돼요." },
          ex2: { zh: "我怕你不来。", pinyin: "wǒ pà nǐ bù lái", ko: "당신이 안 올까 봐 걱정했어요." },
        },
        {
          pattern: "喜欢・爱 + 동사",
          conn: "喜欢/爱 + 동사 — 즐겨 하다",
          ko: "~하기를 좋아하다",
          ex: { zh: "我喜欢旅游。", pinyin: "wǒ xǐhuan lǚyóu", ko: "저는 여행을 좋아해요." },
          ex2: { zh: "她爱笑。", pinyin: "tā ài xiào", ko: "그녀는 잘 웃어요." },
        },
        {
          pattern: "决定 + 동사",
          conn: "决定 + 동사 — 결정하다",
          ko: "~하기로 하다",
          ex: { zh: "我决定去留学。", pinyin: "wǒ juédìng qù liúxué", ko: "저는 유학 가기로 했어요." },
          ex2: { zh: "他决定不去了。", pinyin: "tā juédìng bú qù le", ko: "그는 안 가기로 했어요." },
        },
        {
          pattern: "准备 + 동사",
          conn: "准备 + 동사 — ~할 준비/예정",
          ko: "~할 작정이다 / 준비하다",
          ex: { zh: "我准备明天回家。", pinyin: "wǒ zhǔnbèi míngtiān huí jiā", ko: "저는 내일 집에 갈 예정이에요." },
          ex2: { zh: "你准备好了吗？", pinyin: "nǐ zhǔnbèi hǎo le ma", ko: "준비됐어요?" },
        },
      ],
    },
  ],
};
