/**
 * H3 문형 사전 — HSK 3급 핵심 구문·표현 전수 커버 레이어 (SCHEMA.md 참고)
 * 챕터(grammar/h3.js)가 '이해'라면 이 사전은 '전수 검색'.
 */
export default {
  level: "H3",
  title: "3급 문형 사전",
  desc: "把·被 처치/피동, 방향·가능보어, 复句 접속(不但·只要·无论)부터 정도·범위·시태 부사, 동사 중첩까지 — HSK 3급 핵심 문형을 기능별로 모두 모은 전수 검색 사전.",
  themes: [
    {
      name: "把구문·처치",
      items: [
        {
          pattern: "把 + 목적어 + 동사 + 기타성분",
          conn: "주어 + 把 + 목적어 + 동사 + 결과/방향/了 등",
          ko: "~을 (어떻게) 처리하다",
          ex: { zh: "我把作业做完了。", pinyin: "wǒ bǎ zuòyè zuò wán le", ko: "저는 숙제를 다 했어요." },
          ex2: { zh: "他没把门关上。", pinyin: "tā méi bǎ mén guān shang", ko: "그는 문을 닫지 않았어요." },
          note: "把구문 동사 뒤엔 반드시 기타성분(了·결과보어 등)이 와요. 부정 没·别은 把 앞.",
        },
        {
          pattern: "把 + 목적어 + 동사 + 방향보어",
          conn: "把 + 목적어 + 동사 + 来/去/上/下 등",
          ko: "~을 (어디로) …하다",
          ex: { zh: "请把书拿来。", pinyin: "qǐng bǎ shū ná lái", ko: "책을 가져와 주세요." },
          ex2: { zh: "我把椅子搬过去了。", pinyin: "wǒ bǎ yǐzi bān guòqù le", ko: "저는 의자를 저쪽으로 옮겼어요." },
        },
        {
          pattern: "把 + 목적어 + 동사 + 给/在/到 + …",
          conn: "把 + 목적어 + 동사 + 在/到/给 + 장소·대상",
          ko: "~을 (어디·누구)에 …하다",
          ex: { zh: "请把车停在这儿。", pinyin: "qǐng bǎ chē tíng zài zhèr", ko: "차를 여기에 세워 주세요." },
          ex2: { zh: "我把礼物送给他了。", pinyin: "wǒ bǎ lǐwù sòng gěi tā le", ko: "저는 선물을 그에게 줬어요." },
          note: "'~을 어디에 두다/누구에게 주다'류 동사는 把구문이 자연스러워요.",
        },
      ],
    },
    {
      name: "被구문·피동",
      items: [
        {
          pattern: "A 被 (B) + 동사 + 기타성분",
          conn: "주어 + 被 (+ 행위자) + 동사 + 결과/了",
          ko: "A가 (B에게) ~당하다 (피동)",
          ex: { zh: "我的手机被人偷了。", pinyin: "wǒ de shǒujī bèi rén tōu le", ko: "제 휴대폰을 누가 훔쳐 갔어요." },
          ex2: { zh: "蛋糕没被吃完。", pinyin: "dàngāo méi bèi chī wán", ko: "케이크는 다 먹히지 않았어요." },
          note: "被 동사 뒤에도 기타성분이 필요해요. 행위자는 생략 가능. 부정 没은 被 앞.",
        },
        {
          pattern: "A 让・叫 + B + 동사",
          conn: "A + 让/叫 + B + 동사 — 구어 피동·사역",
          ko: "A가 B에게 ~당하다/시키다",
          ex: { zh: "杯子让妹妹打破了。", pinyin: "bēizi ràng mèimei dǎ pò le", ko: "컵이 여동생한테 깨졌어요." },
          ex2: { zh: "妈妈叫我打扫房间。", pinyin: "māma jiào wǒ dǎsǎo fángjiān", ko: "엄마가 저에게 방을 청소하라고 했어요." },
          note: "让·叫는 구어 피동(被 대용)이자 사역. 문맥으로 구별해요.",
        },
      ],
    },
    {
      name: "방향보어",
      items: [
        {
          pattern: "동사 + 来・去",
          conn: "동사 + 来(이쪽)/去(저쪽) — 단순방향보어",
          ko: "~해 오다 / ~해 가다",
          ex: { zh: "他跑过来了。", pinyin: "tā pǎo guòlái le", ko: "그가 뛰어왔어요." },
          ex2: { zh: "请进来。", pinyin: "qǐng jìnlái", ko: "들어오세요." },
          note: "화자 쪽으로 오면 来, 멀어지면 去로 방향이 정해져요.",
        },
        {
          pattern: "동사 + 上・下・进・出 + 来/去",
          conn: "동사 + 上/下/进/出/回/过 (+ 来/去) — 복합방향보어",
          ko: "~해 올라/내려/들어/나오다 등",
          ex: { zh: "他走进来了。", pinyin: "tā zǒu jìnlái le", ko: "그가 걸어 들어왔어요." },
          ex2: { zh: "请站起来。", pinyin: "qǐng zhàn qǐlái", ko: "일어서 주세요." },
        },
        {
          pattern: "동사 + 起来 (시작·평가)",
          conn: "동사/형용사 + 起来 — 시작·관점 도입",
          ko: "~하기 시작하다 / ~해 보니",
          ex: { zh: "他突然唱起来了。", pinyin: "tā tūrán chàng qǐlái le", ko: "그가 갑자기 노래하기 시작했어요." },
          ex2: { zh: "这个菜看起来很好吃。", pinyin: "zhège cài kàn qǐlái hěn hǎochī", ko: "이 요리는 맛있어 보여요." },
          note: "看起来·听起来처럼 '~해 보니/보이니'의 추상적 용법도 자주 써요.",
        },
        {
          pattern: "동사 + 下去 (지속)",
          conn: "동사 + 下去 — 계속 이어감",
          ko: "계속 ~해 나가다",
          ex: { zh: "请说下去。", pinyin: "qǐng shuō xiàqù", ko: "계속 말씀하세요." },
          ex2: { zh: "我不想再等下去了。", pinyin: "wǒ bù xiǎng zài děng xiàqù le", ko: "더 이상 계속 기다리고 싶지 않아요." },
        },
      ],
    },
    {
      name: "가능보어",
      items: [
        {
          pattern: "동사 + 得/不 + 결과/방향",
          conn: "동사 + 得(가능)/不(불가능) + 보어",
          ko: "~할 수 있다/없다 (가능보어)",
          ex: { zh: "这个字我看得懂。", pinyin: "zhège zì wǒ kàn de dǒng", ko: "이 글자는 제가 읽어서 이해할 수 있어요." },
          ex2: { zh: "太远了，我走不到。", pinyin: "tài yuǎn le, wǒ zǒu bu dào", ko: "너무 멀어서 걸어서 못 가요." },
          note: "能/不能과 달리 '여건상 결과에 도달 가능한가'를 동사에 붙여 표현해요.",
        },
        {
          pattern: "동사 + 得了・不了",
          conn: "동사 + 得了/不了(liǎo) — 가능·완수",
          ko: "~할 수 있다/없다 (해낼 수 있는가)",
          ex: { zh: "这么多菜，我吃得了。", pinyin: "zhème duō cài, wǒ chī de liǎo", ko: "이렇게 많은 음식, 다 먹을 수 있어요." },
          ex2: { zh: "今天我去不了。", pinyin: "jīntiān wǒ qù bu liǎo", ko: "오늘 저는 못 가요." },
          note: "이때 了는 liǎo. 양·능력상 '해낼 수 있는지'를 나타내요.",
        },
        {
          pattern: "听得懂・看得见 류",
          conn: "동사 + 得/不 + 懂/见/到/清楚",
          ko: "알아듣다/보이다 등 가능 여부",
          ex: { zh: "老师说的话我听得懂。", pinyin: "lǎoshī shuō de huà wǒ tīng de dǒng", ko: "선생님 말씀을 알아들을 수 있어요." },
          ex2: { zh: "声音太小，我听不清楚。", pinyin: "shēngyīn tài xiǎo, wǒ tīng bu qīngchu", ko: "소리가 너무 작아서 잘 안 들려요." },
        },
      ],
    },
    {
      name: "복문 접속",
      items: [
        {
          pattern: "不但 … 而且 …",
          conn: "不但 + A, 而且 + B — 점층",
          ko: "~할 뿐만 아니라 게다가 ~",
          ex: { zh: "他不但会说汉语，而且说得很好。", pinyin: "tā búdàn huì shuō Hànyǔ, érqiě shuō de hěn hǎo", ko: "그는 중국어를 할 줄 알 뿐 아니라 잘하기까지 해요." },
          ex2: { zh: "这儿不但便宜，而且很好吃。", pinyin: "zhèr búdàn piányi, érqiě hěn hǎochī", ko: "여기는 쌀 뿐만 아니라 맛도 좋아요." },
        },
        {
          pattern: "只要 … 就 …",
          conn: "只要 + 조건, 就 + 결과 — 충분조건",
          ko: "~하기만 하면 ~",
          ex: { zh: "只要努力，就一定能成功。", pinyin: "zhǐyào nǔlì, jiù yídìng néng chénggōng", ko: "노력하기만 하면 반드시 성공할 수 있어요." },
          ex2: { zh: "只要你来，我就高兴。", pinyin: "zhǐyào nǐ lái, wǒ jiù gāoxìng", ko: "당신이 오기만 하면 저는 기뻐요." },
        },
        {
          pattern: "只有 … 才 …",
          conn: "只有 + 유일조건, 才 + 결과 — 필요조건",
          ko: "~해야만 비로소 ~",
          ex: { zh: "只有多练习，才能学好。", pinyin: "zhǐyǒu duō liànxí, cái néng xué hǎo", ko: "많이 연습해야만 잘 배울 수 있어요." },
          ex2: { zh: "只有他才知道答案。", pinyin: "zhǐyǒu tā cái zhīdào dá'àn", ko: "그만이 정답을 알아요." },
          note: "只要(충분조건)는 就, 只有(필요조건)는 才와 짝을 이뤄요.",
        },
        {
          pattern: "无论・不管 … 都 …",
          conn: "无论/不管 + 의문구 + 都/也 — 조건 무관",
          ko: "~에 상관없이 모두 ~",
          ex: { zh: "无论多忙，他都会来。", pinyin: "wúlùn duō máng, tā dōu huì lái", ko: "아무리 바빠도 그는 올 거예요." },
          ex2: { zh: "不管你去不去，我都去。", pinyin: "bùguǎn nǐ qù bu qù, wǒ dōu qù", ko: "당신이 가든 안 가든 저는 가요." },
          note: "无论/不管 뒤엔 의문사·정반형 같은 '여러 경우'가 와야 해요.",
        },
        {
          pattern: "因为 … 才・所以 …",
          conn: "因为 + 원인, 才/所以 + 결과",
          ko: "~ 때문에 (그래서/비로소) ~",
          ex: { zh: "因为努力，所以成功了。", pinyin: "yīnwèi nǔlì, suǒyǐ chénggōng le", ko: "노력했기 때문에 성공했어요." },
          ex2: { zh: "因为有事，他才没来。", pinyin: "yīnwèi yǒu shì, tā cái méi lái", ko: "일이 있어서 그가 못 온 거예요." },
        },
        {
          pattern: "越 … 越 …",
          conn: "越 + A + 越 + B — 정비례",
          ko: "~할수록 ~하다",
          ex: { zh: "雨越下越大。", pinyin: "yǔ yuè xià yuè dà", ko: "비가 올수록 더 거세져요." },
          ex2: { zh: "我越想越担心。", pinyin: "wǒ yuè xiǎng yuè dānxīn", ko: "생각할수록 더 걱정돼요." },
          note: "越来越 + 형용사는 '점점 ~해지다'로 자주 써요 (越来越冷).",
        },
        {
          pattern: "一 … 也/都 + 不/没 …",
          conn: "一 + 양사 + 명사 + 也/都 + 부정 — 전면 부정",
          ko: "하나도 ~하지 않다",
          ex: { zh: "我一个人也不认识。", pinyin: "wǒ yí ge rén yě bú rènshi", ko: "저는 한 사람도 몰라요." },
          ex2: { zh: "他一句话都没说。", pinyin: "tā yí jù huà dōu méi shuō", ko: "그는 한 마디도 안 했어요." },
        },
        {
          pattern: "既 … 又 …",
          conn: "既 + A + 又 + B — 두 속성 병렬",
          ko: "~하기도 하고 ~하기도 하다",
          ex: { zh: "这个房间既大又干净。", pinyin: "zhège fángjiān jì dà yòu gānjìng", ko: "이 방은 크기도 하고 깨끗하기도 해요." },
          ex2: { zh: "他既聪明又努力。", pinyin: "tā jì cōngming yòu nǔlì", ko: "그는 똑똑하기도 하고 노력하기도 해요." },
        },
      ],
    },
    {
      name: "정도·범위 부사",
      items: [
        {
          pattern: "比较 + 형용사",
          conn: "比较 + 형용사 — 비교적",
          ko: "비교적 ~하다",
          ex: { zh: "今天比较冷。", pinyin: "jīntiān bǐjiào lěng", ko: "오늘은 비교적 추워요." },
          ex2: { zh: "这个比较便宜。", pinyin: "zhège bǐjiào piányi", ko: "이게 비교적 싸요." },
        },
        {
          pattern: "非常・特别 + 형용사",
          conn: "非常/特别 + 형용사 — 매우",
          ko: "대단히/특히 ~하다",
          ex: { zh: "这个菜非常好吃。", pinyin: "zhège cài fēicháng hǎochī", ko: "이 요리는 대단히 맛있어요." },
          ex2: { zh: "今天特别热。", pinyin: "jīntiān tèbié rè", ko: "오늘은 유난히 더워요." },
        },
        {
          pattern: "形 + 极了・死了",
          conn: "형용사 + 极了/死了 — 극단 강조",
          ko: "엄청 ~하다",
          ex: { zh: "我饿死了。", pinyin: "wǒ è sǐ le", ko: "배고파 죽겠어요." },
          ex2: { zh: "这个好吃极了。", pinyin: "zhège hǎochī jí le", ko: "이거 엄청 맛있어요." },
          note: "死了는 과장된 구어 표현. 文어체에선 极了가 무난해요.",
        },
        {
          pattern: "几乎 + 술어",
          conn: "几乎 + 술어 — 거의",
          ko: "거의 ~하다",
          ex: { zh: "我几乎每天都运动。", pinyin: "wǒ jīhū měi tiān dōu yùndòng", ko: "저는 거의 매일 운동해요." },
          ex2: { zh: "他几乎没说话。", pinyin: "tā jīhū méi shuōhuà", ko: "그는 거의 말을 안 했어요." },
        },
        {
          pattern: "只 + 동사 / 只有 + 명사",
          conn: "只 + 동사 / 只有 + 명사 — 한정",
          ko: "~만 / ~밖에 없다",
          ex: { zh: "我只喝了一杯。", pinyin: "wǒ zhǐ hē le yì bēi", ko: "저는 한 잔만 마셨어요." },
          ex2: { zh: "现在只有他一个人。", pinyin: "xiànzài zhǐyǒu tā yí ge rén", ko: "지금은 그 한 사람밖에 없어요." },
        },
        {
          pattern: "一共・总共",
          conn: "一共/总共 + 수량 — 합계",
          ko: "모두 합쳐서 ~",
          ex: { zh: "一共多少钱？", pinyin: "yígòng duōshao qián", ko: "모두 얼마예요?" },
          ex2: { zh: "我们一共五个人。", pinyin: "wǒmen yígòng wǔ ge rén", ko: "우리는 모두 다섯 명이에요." },
        },
      ],
    },
    {
      name: "시태·빈도 부사",
      items: [
        {
          pattern: "一直 + 동사",
          conn: "一直 + 동사 — 줄곧",
          ko: "계속/줄곧 ~하다",
          ex: { zh: "我一直在等你。", pinyin: "wǒ yìzhí zài děng nǐ", ko: "저는 계속 당신을 기다리고 있었어요." },
          ex2: { zh: "他一直没回来。", pinyin: "tā yìzhí méi huílái", ko: "그는 줄곧 돌아오지 않았어요." },
        },
        {
          pattern: "经常・常常 + 동사",
          conn: "经常/常常 + 동사 — 자주",
          ko: "자주 ~하다",
          ex: { zh: "我经常去图书馆。", pinyin: "wǒ jīngcháng qù túshūguǎn", ko: "저는 자주 도서관에 가요." },
          ex2: { zh: "他不常运动。", pinyin: "tā bù cháng yùndòng", ko: "그는 운동을 자주 안 해요." },
        },
        {
          pattern: "又 … 了 / 再 + 동사",
          conn: "又(이미 반복) … 了 / 再(앞으로 반복) + 동사",
          ko: "또 ~했다 / 다시 ~하다",
          ex: { zh: "他又迟到了。", pinyin: "tā yòu chídào le", ko: "그는 또 지각했어요." },
          ex2: { zh: "请再说一遍。", pinyin: "qǐng zài shuō yí biàn", ko: "다시 한번 말해 주세요." },
          note: "이미 일어난 반복은 又, 아직 안 한 반복은 再로 나눠요.",
        },
        {
          pattern: "终于 + 동사 + 了",
          conn: "终于 + 술어 + 了 — 마침내",
          ko: "마침내 ~했다",
          ex: { zh: "我终于找到工作了。", pinyin: "wǒ zhōngyú zhǎo dào gōngzuò le", ko: "저는 마침내 일자리를 찾았어요." },
          ex2: { zh: "雨终于停了。", pinyin: "yǔ zhōngyú tíng le", ko: "비가 드디어 그쳤어요." },
        },
        {
          pattern: "马上・立刻 + 동사",
          conn: "马上/立刻 + 동사 — 즉시",
          ko: "곧/즉시 ~하다",
          ex: { zh: "我马上就来。", pinyin: "wǒ mǎshàng jiù lái", ko: "제가 곧 갈게요." },
          ex2: { zh: "请立刻出发。", pinyin: "qǐng lìkè chūfā", ko: "즉시 출발하세요." },
        },
        {
          pattern: "刚・刚才",
          conn: "刚 + 동사(방금, 부사) / 刚才(방금 전, 시간명사)",
          ko: "막/방금 ~",
          ex: { zh: "我刚到家。", pinyin: "wǒ gāng dào jiā", ko: "저는 방금 집에 도착했어요." },
          ex2: { zh: "刚才他给我打电话了。", pinyin: "gāngcái tā gěi wǒ dǎ diànhuà le", ko: "방금 전에 그가 저에게 전화했어요." },
          note: "刚은 동사 앞 부사, 刚才는 문장 앞 시간명사로 위치가 달라요.",
        },
      ],
    },
    {
      name: "동작 표현 심화",
      items: [
        {
          pattern: "동사 중첩 (V V / V 一 V)",
          conn: "동사 + 동사 / 동사 + 一 + 동사 — 가볍게·시도",
          ko: "좀 ~해 보다",
          ex: { zh: "你看看这个。", pinyin: "nǐ kànkan zhège", ko: "이거 좀 봐 봐." },
          ex2: { zh: "我想休息一下。", pinyin: "wǒ xiǎng xiūxi yíxià", ko: "좀 쉬고 싶어요." },
          note: "동작을 부드럽게·짧게. 2음절 동사는 ABAB로 중첩해요 (休息休息).",
        },
        {
          pattern: "形 + 형용사 중첩",
          conn: "형용사 + 형용사 (AABB) — 생생한 묘사",
          ko: "아주 ~하게",
          ex: { zh: "她高高兴兴地走了。", pinyin: "tā gāogāoxìngxìng de zǒu le", ko: "그녀는 기쁘게 떠났어요." },
          ex2: { zh: "房间干干净净的。", pinyin: "fángjiān gānganjìngjìng de", ko: "방이 아주 깨끗해요." },
        },
        {
          pattern: "형용사/부사 + 地 + 동사",
          conn: "수식어 + 地 + 동사 — 양태 부사어",
          ko: "~하게 …하다",
          ex: { zh: "他认真地学习。", pinyin: "tā rènzhēn de xuéxí", ko: "그는 열심히 공부해요." },
          ex2: { zh: "请慢慢地说。", pinyin: "qǐng mànmàn de shuō", ko: "천천히 말씀해 주세요." },
          note: "동작을 꾸미면 地(de), 정도를 보충하면 得(de). 둘 다 de지만 위치가 달라요.",
        },
        {
          pattern: "동사 + 了 + 동사 (연동·완료 연쇄)",
          conn: "동사1 + 了 + 동사2 — 잇따른 동작",
          ko: "~하고 나서 ~하다",
          ex: { zh: "我吃了饭就去。", pinyin: "wǒ chī le fàn jiù qù", ko: "저는 밥을 먹고 바로 가요." },
          ex2: { zh: "下了课我们一起走。", pinyin: "xià le kè wǒmen yìqǐ zǒu", ko: "수업 끝나면 우리 같이 가요." },
        },
        {
          pattern: "连 … 都/也 …",
          conn: "连 + 강조 대상 + 都/也 + 술어 — ~조차",
          ko: "~조차 …하다",
          ex: { zh: "他连一句话也没说。", pinyin: "tā lián yí jù huà yě méi shuō", ko: "그는 한 마디조차 안 했어요." },
          ex2: { zh: "我连他的名字都不知道。", pinyin: "wǒ lián tā de míngzi dōu bù zhīdào", ko: "저는 그의 이름조차 몰라요." },
        },
      ],
    },
    {
      name: "어기·완곡·확인",
      items: [
        {
          pattern: "… 吧 (제안·추측)",
          conn: "문말 吧 — 권유·추측·동의",
          ko: "~하자 / ~하죠 / ~겠죠?",
          ex: { zh: "我们走吧。", pinyin: "wǒmen zǒu ba", ko: "우리 가요." },
          ex2: { zh: "他应该到了吧？", pinyin: "tā yīnggāi dào le ba", ko: "그는 도착했겠죠?" },
          note: "吗은 순수 질문, 吧는 '제안·추측'이라 어감이 달라요.",
        },
        {
          pattern: "… 了吧・… 是吧",
          conn: "문말 了吧/是吧 — 확인",
          ko: "~했죠? / ~맞죠?",
          ex: { zh: "你是韩国人吧？", pinyin: "nǐ shì Hánguó rén ba", ko: "한국 분이시죠?" },
          ex2: { zh: "你已经吃过了吧？", pinyin: "nǐ yǐjīng chī guo le ba", ko: "이미 드셨죠?" },
        },
        {
          pattern: "好像 …",
          conn: "好像 + 술어 — 추측·완곡",
          ko: "~인 것 같다",
          ex: { zh: "他好像生病了。", pinyin: "tā hǎoxiàng shēngbìng le", ko: "그는 아픈 것 같아요." },
          ex2: { zh: "好像要下雨。", pinyin: "hǎoxiàng yào xiàyǔ", ko: "비가 올 것 같아요." },
        },
        {
          pattern: "可能・也许 + 술어",
          conn: "可能/也许 + 술어 — 가능성",
          ko: "아마 ~일 것이다",
          ex: { zh: "他可能不来了。", pinyin: "tā kěnéng bù lái le", ko: "그는 아마 안 올 거예요." },
          ex2: { zh: "也许明天会更好。", pinyin: "yěxǔ míngtiān huì gèng hǎo", ko: "어쩌면 내일은 더 나을 거예요." },
        },
        {
          pattern: "当然・一定",
          conn: "当然(당연) / 一定(반드시) + 술어",
          ko: "당연히 / 반드시 ~",
          ex: { zh: "我当然知道。", pinyin: "wǒ dāngrán zhīdào", ko: "당연히 알죠." },
          ex2: { zh: "我一定会去。", pinyin: "wǒ yídìng huì qù", ko: "저는 꼭 갈게요." },
        },
        {
          pattern: "其实 …",
          conn: "其实 + 절 — 사실은",
          ko: "사실은 ~",
          ex: { zh: "其实我不太喜欢。", pinyin: "qíshí wǒ bú tài xǐhuan", ko: "사실 저는 별로 안 좋아해요." },
          ex2: { zh: "其实这件事很简单。", pinyin: "qíshí zhè jiàn shì hěn jiǎndān", ko: "사실 이 일은 간단해요." },
        },
      ],
    },
    {
      name: "주제·존재·근거",
      items: [
        {
          pattern: "对于・关于 …",
          conn: "对于/关于 + 화제 + 절",
          ko: "~에 대해서는 / ~에 관하여",
          ex: { zh: "对于这个问题，我有不同的看法。", pinyin: "duìyú zhège wèntí, wǒ yǒu bùtóng de kànfǎ", ko: "이 문제에 대해 저는 다른 견해가 있어요." },
          ex2: { zh: "关于他的事，我不太清楚。", pinyin: "guānyú tā de shì, wǒ bú tài qīngchu", ko: "그의 일에 관해서는 잘 몰라요." },
        },
        {
          pattern: "除了 … 以外, 都/还 …",
          conn: "除了 + A + 以外, 都(제외)/还(추가) …",
          ko: "~을 제외하고는 모두 / ~말고도 또",
          ex: { zh: "除了他以外，大家都来了。", pinyin: "chúle tā yǐwài, dàjiā dōu lái le", ko: "그를 빼고는 모두 왔어요." },
          ex2: { zh: "除了汉语，我还会说英语。", pinyin: "chúle Hànyǔ, wǒ hái huì shuō Yīngyǔ", ko: "중국어 말고도 저는 영어도 할 줄 알아요." },
          note: "都와 짝이면 '제외', 还와 짝이면 '추가'로 의미가 갈려요.",
        },
        {
          pattern: "A 是 B 的 + 명사 (분류)",
          conn: "A + 是 + 수식 + 的 + 명사 — 속성 규정",
          ko: "A는 ~한 …이다",
          ex: { zh: "这是去年买的衣服。", pinyin: "zhè shì qùnián mǎi de yīfu", ko: "이건 작년에 산 옷이에요." },
          ex2: { zh: "他是教汉语的老师。", pinyin: "tā shì jiāo Hànyǔ de lǎoshī", ko: "그는 중국어를 가르치는 선생님이에요." },
          note: "동사구 + 的 + 명사는 관계절처럼 명사를 꾸며요.",
        },
        {
          pattern: "동사 + 的时候",
          conn: "동사구 + 的时候 — ~할 때",
          ko: "~할 때",
          ex: { zh: "吃饭的时候别看手机。", pinyin: "chī fàn de shíhou bié kàn shǒujī", ko: "밥 먹을 때 휴대폰 보지 마." },
          ex2: { zh: "我小的时候住在北京。", pinyin: "wǒ xiǎo de shíhou zhù zài Běijīng", ko: "저는 어렸을 때 베이징에 살았어요." },
        },
        {
          pattern: "一 … 的时候 / 以前·以后",
          conn: "동사구 + 以前/以后 — ~하기 전/후에",
          ko: "~하기 전에 / 한 후에",
          ex: { zh: "睡觉以前我喜欢看书。", pinyin: "shuìjiào yǐqián wǒ xǐhuan kàn shū", ko: "자기 전에 저는 책 읽는 걸 좋아해요." },
          ex2: { zh: "下课以后我们去吃饭。", pinyin: "xiàkè yǐhòu wǒmen qù chī fàn", ko: "수업 후에 우리 밥 먹으러 가요." },
        },
      ],
    },
  ],
};
