/**
 * H3 문형 사전 — HSK 3급 핵심 구문·표현 전수 커버 레이어 (SCHEMA.md 참고)
 * 챕터(grammar/h3.js)가 '이해'라면 이 사전은 '전수 검색'.
 */
export default {
  level: "H3",
  title: "3급 문형 사전",
  desc: "把·被 처치/피동, 방향·가능보어, 复句 접속(不但·只要·无论)부터 정도·범위·시태 부사, 동사 중첩까지 — HSK 3급 핵심 문형을 기능별로 모두 모은 전수 검색 사전.",
  themes: [
    {
      name: "把구문·처치",
      items: [
        {
          pattern: "把 + 목적어 + 동사 + 기타성분",
          pinyin: "bǎ",
          ch: "h3-01-ba",
          conn: "주어 + 把 + 목적어 + 동사 + 결과/방향/了 등",
          ko: "~을 (어떻게) 처리하다",
          ex: { zh: "我把作业做完了。", pinyin: "wǒ bǎ zuòyè zuò wán le", ko: "저는 숙제를 다 했어요." },
          ex2: { zh: "他没把门关上。", pinyin: "tā méi bǎ mén guān shang", ko: "그는 문을 닫지 않았어요." },
          note: "把구문 동사 뒤엔 반드시 기타성분(了·결과보어 등)이 와요. 부정 没·别은 把 앞.",
        },
        {
          pattern: "把 + 목적어 + 동사 + 방향보어",
          ch: "h3-01-ba",
          conn: "把 + 목적어 + 동사 + 来/去/上/下 등",
          ko: "~을 (어디로) …하다",
          ex: { zh: "请把书拿来。", pinyin: "qǐng bǎ shū ná lái", ko: "책을 가져와 주세요." },
          ex2: { zh: "我把椅子搬过去了。", pinyin: "wǒ bǎ yǐzi bān guòqù le", ko: "저는 의자를 저쪽으로 옮겼어요." },
        },
        {
          pattern: "把 + 목적어 + 동사 + 给/在/到 + …",
          ch: "h3-01-ba",
          conn: "把 + 목적어 + 동사 + 在/到/给 + 장소·대상",
          ko: "~을 (어디·누구)에 …하다",
          ex: { zh: "请把车停在这儿。", pinyin: "qǐng bǎ chē tíng zài zhèr", ko: "차를 여기에 세워 주세요." },
          ex2: { zh: "我把礼物送给他了。", pinyin: "wǒ bǎ lǐwù sòng gěi tā le", ko: "저는 선물을 그에게 줬어요." },
          note: "'~을 어디에 두다/누구에게 주다'류 동사는 把구문이 자연스러워요.",
        },
        {
          pattern: "把 + 목적어 + 동사 + 成/作",
          ch: "h3-01-ba",
          conn: "把 + A + 동사 + 成 + B — A를 B로 바꾸다",
          ko: "~을 ~로 …하다",
          ex: { zh: "请把这句话翻译成中文。", pinyin: "qǐng bǎ zhè jù huà fānyì chéng Zhōngwén", ko: "이 문장을 중국어로 번역해 주세요." },
          ex2: { zh: "他把钱换成了人民币。", pinyin: "tā bǎ qián huàn chéng le rénmínbì", ko: "그는 돈을 인민폐로 바꿨어요." },
        },
        {
          pattern: "把 + 목적어 + 동사 + 一下/동사중첩",
          ch: "h3-01-ba",
          conn: "把 + 목적어 + 동사 + 一下 — 가볍게 처치",
          ko: "~을 좀 …하다",
          ex: { zh: "请把窗户开一下。", pinyin: "qǐng bǎ chuānghu kāi yíxià", ko: "창문 좀 열어 주세요." },
          ex2: { zh: "你把房间打扫打扫。", pinyin: "nǐ bǎ fángjiān dǎsǎo dǎsǎo", ko: "방 좀 청소해." },
          note: "동사 중첩·一下도 把구문 동사 뒤의 '기타성분'이 될 수 있어요.",
        },
      ],
    },
    {
      name: "被구문·피동",
      items: [
        {
          pattern: "A 被 (B) + 동사 + 기타성분",
          ch: "h3-02-bei",
          conn: "주어 + 被 (+ 행위자) + 동사 + 결과/了",
          ko: "A가 (B에게) ~당하다 (피동)",
          ex: { zh: "我的手机被人偷了。", pinyin: "wǒ de shǒujī bèi rén tōu le", ko: "제 휴대폰을 누가 훔쳐 갔어요." },
          ex2: { zh: "蛋糕没被吃完。", pinyin: "dàngāo méi bèi chī wán", ko: "케이크는 다 먹히지 않았어요." },
          note: "被 동사 뒤에도 기타성분이 필요해요. 행위자는 생략 가능. 부정 没은 被 앞.",
        },
        {
          pattern: "A 让・叫 + B + 동사",
          ch: "h3-02-bei",
          conn: "A + 让/叫 + B + 동사 — 구어 피동·사역",
          ko: "A가 B에게 ~당하다/시키다",
          ex: { zh: "杯子让妹妹打破了。", pinyin: "bēizi ràng mèimei dǎ pò le", ko: "컵이 여동생한테 깨졌어요." },
          ex2: { zh: "妈妈叫我打扫房间。", pinyin: "māma jiào wǒ dǎsǎo fángjiān", ko: "엄마가 저에게 방을 청소하라고 했어요." },
          note: "让·叫는 구어 피동(被 대용)이자 사역. 문맥으로 구별해요.",
        },
        {
          pattern: "让 + 사람 + 동사",
          ch: "h5-04-causative",
          conn: "주어 + 让 + 대상 + 동사 — ~하게 하다",
          ko: "~에게 …하게 하다/시키다",
          ex: { zh: "老师让我们回答问题。", pinyin: "lǎoshī ràng wǒmen huídá wèntí", ko: "선생님이 우리에게 질문에 답하게 했어요." },
          ex2: { zh: "别让他等太久。", pinyin: "bié ràng tā děng tài jiǔ", ko: "그를 너무 오래 기다리게 하지 마." },
        },
        {
          pattern: "被 + 동사",
          ch: "h3-02-bei",
          conn: "주어 + 被 + 동사 + 기타성분 (행위자 없음)",
          ko: "~당하다 (누가 했는지는 생략)",
          ex: { zh: "我的自行车被偷了。", pinyin: "wǒ de zìxíngchē bèi tōu le", ko: "제 자전거를 도둑맞았어요." },
          ex2: { zh: "问题被解决了。", pinyin: "wèntí bèi jiějué le", ko: "문제가 해결됐어요." },
          note: "행위자가 불분명하거나 중요치 않으면 被 뒤를 비워요.",
        },
      ],
    },
    {
      name: "방향보어",
      items: [
        {
          pattern: "동사 + 来・去",
          ch: "h3-04-direction-complement",
          conn: "동사 + 来(이쪽)/去(저쪽) — 단순방향보어",
          ko: "~해 오다 / ~해 가다",
          ex: { zh: "他跑过来了。", pinyin: "tā pǎo guòlái le", ko: "그가 뛰어왔어요." },
          ex2: { zh: "请进来。", pinyin: "qǐng jìnlái", ko: "들어오세요." },
          note: "화자 쪽으로 오면 来, 멀어지면 去로 방향이 정해져요.",
        },
        {
          pattern: "동사 + 上・下・进・出 + 来/去",
          ch: "h3-04-direction-complement",
          conn: "동사 + 上/下/进/出/回/过 (+ 来/去) — 복합방향보어",
          ko: "~해 올라/내려/들어/나오다 등",
          ex: { zh: "他走进来了。", pinyin: "tā zǒu jìnlái le", ko: "그가 걸어 들어왔어요." },
          ex2: { zh: "请站起来。", pinyin: "qǐng zhàn qǐlái", ko: "일어서 주세요." },
        },
        {
          pattern: "동사 + 起来",
          ch: "h3-04-direction-complement",
          conn: "동사/형용사 + 起来 — 시작·관점 도입",
          ko: "~하기 시작하다 / ~해 보니",
          ex: { zh: "他突然唱起来了。", pinyin: "tā tūrán chàng qǐlái le", ko: "그가 갑자기 노래하기 시작했어요." },
          ex2: { zh: "这个菜看起来很好吃。", pinyin: "zhège cài kàn qǐlái hěn hǎochī", ko: "이 요리는 맛있어 보여요." },
          note: "看起来·听起来처럼 '~해 보니/보이니'의 추상적 용법도 자주 써요.",
        },
        {
          pattern: "동사 + 上",
          ch: "h3-04-direction-complement",
          conn: "동사 + 上 — 닿다·이루다",
          ko: "~해 붙이다/이루다",
          ex: { zh: "请关上门。", pinyin: "qǐng guān shang mén", ko: "문을 닫아 주세요." },
          ex2: { zh: "他考上了大学。", pinyin: "tā kǎo shang le dàxué", ko: "그는 대학에 합격했어요." },
          note: "考上(합격하다)처럼 上은 '목표 달성'도 나타내요.",
        },
        {
          pattern: "동사 + 下",
          ch: "h3-04-direction-complement",
          conn: "동사 + 下 — 떼다·남기다",
          ko: "~해 내려놓다/남기다",
          ex: { zh: "请坐下。", pinyin: "qǐng zuò xià", ko: "앉으세요." },
          ex2: { zh: "他留下了一封信。", pinyin: "tā liú xià le yì fēng xìn", ko: "그는 편지 한 통을 남겼어요." },
        },
        {
          pattern: "동사 + 下去",
          ch: "h3-04-direction-complement",
          conn: "동사 + 下去 — 계속 이어감",
          ko: "계속 ~해 나가다",
          ex: { zh: "请说下去。", pinyin: "qǐng shuō xiàqù", ko: "계속 말씀하세요." },
          ex2: { zh: "我不想再等下去了。", pinyin: "wǒ bù xiǎng zài děng xiàqù le", ko: "더 이상 계속 기다리고 싶지 않아요." },
        },
        {
          pattern: "동사 + 出来",
          ch: "h3-04-direction-complement",
          conn: "동사 + 出来 — 알아내다·만들어내다",
          ko: "~해 내다 (알아보다·생겨나다)",
          ex: { zh: "我听出来是他的声音。", pinyin: "wǒ tīng chūlái shì tā de shēngyīn", ko: "그의 목소리인 걸 알아들었어요." },
          ex2: { zh: "我看不出来他多大。", pinyin: "wǒ kàn bu chūlái tā duō dà", ko: "그가 몇 살인지 가늠이 안 돼요." },
          note: "看出来·听出来는 '식별해 내다'라는 추상 용법이 자주 쓰여요.",
        },
        {
          pattern: "동사 + 过来・过去",
          ch: "h3-04-direction-complement",
          conn: "동사 + 过来(이쪽으로)/过去(저쪽으로)",
          ko: "~해 오다/가다 (방향·전환)",
          ex: { zh: "他跑过来。", pinyin: "tā pǎo guòlái", ko: "그가 이쪽으로 뛰어와요." },
          ex2: { zh: "请把书递过来。", pinyin: "qǐng bǎ shū dì guòlái", ko: "책을 이쪽으로 건네주세요." },
        },
        {
          pattern: "동사 + 回来・回去",
          ch: "h3-04-direction-complement",
          conn: "동사 + 回来/回去 — 돌아오다/가다",
          ko: "~해서 돌아오다/가다",
          ex: { zh: "他买回来很多东西。", pinyin: "tā mǎi huílái hěn duō dōngxi", ko: "그는 물건을 잔뜩 사 왔어요." },
          ex2: { zh: "请把椅子搬回去。", pinyin: "qǐng bǎ yǐzi bān huíqù", ko: "의자를 제자리로 옮겨 놓으세요." },
        },
      ],
    },
    {
      name: "가능보어",
      items: [
        {
          pattern: "동사 + 得/不 + 결과/방향",
          ch: "h3-06-potential-complement",
          conn: "동사 + 得(가능)/不(불가능) + 보어",
          ko: "~할 수 있다/없다 (가능보어)",
          ex: { zh: "这个字我看得懂。", pinyin: "zhège zì wǒ kàn de dǒng", ko: "이 글자는 제가 읽어서 이해할 수 있어요." },
          ex2: { zh: "太远了，我走不到。", pinyin: "tài yuǎn le, wǒ zǒu bu dào", ko: "너무 멀어서 걸어서 못 가요." },
          note: "能/不能과 달리 '여건상 결과에 도달 가능한가'를 동사에 붙여 표현해요.",
        },
        {
          pattern: "동사 + 得了・不了",
          ch: "h3-06-potential-complement",
          conn: "동사 + 得了/不了(liǎo) — 가능·완수",
          ko: "~할 수 있다/없다 (해낼 수 있는가)",
          ex: { zh: "这么多菜，我吃得了。", pinyin: "zhème duō cài, wǒ chī de liǎo", ko: "이렇게 많은 음식, 다 먹을 수 있어요." },
          ex2: { zh: "今天我去不了。", pinyin: "jīntiān wǒ qù bu liǎo", ko: "오늘 저는 못 가요." },
          note: "이때 了는 liǎo. 양·능력상 '해낼 수 있는지'를 나타내요.",
        },
        {
          pattern: "听得懂・看得见 류",
          ch: "h3-06-potential-complement",
          conn: "동사 + 得/不 + 懂/见/到/清楚",
          ko: "알아듣다/보이다 등 가능 여부",
          ex: { zh: "老师说的话我听得懂。", pinyin: "lǎoshī shuō de huà wǒ tīng de dǒng", ko: "선생님 말씀을 알아들을 수 있어요." },
          ex2: { zh: "声音太小，我听不清楚。", pinyin: "shēngyīn tài xiǎo, wǒ tīng bu qīngchu", ko: "소리가 너무 작아서 잘 안 들려요." },
        },
        {
          pattern: "동사 + 得/不 + 下・动・起",
          ch: "h3-06-potential-complement",
          conn: "동사 + 得/不 + 下(수용)/动(움직임)/起(감당)",
          ko: "담을/움직일/감당할 수 있다/없다",
          ex: { zh: "这个箱子我拿不动。", pinyin: "zhège xiāngzi wǒ ná bu dòng", ko: "이 상자는 제가 못 들어요." },
          ex2: { zh: "这个房间坐得下二十个人。", pinyin: "zhège fángjiān zuò de xià èrshí ge rén", ko: "이 방은 스무 명이 앉을 수 있어요." },
          note: "买不起(살 형편이 안 됨)처럼 起는 '감당'을 나타내요.",
        },
        {
          pattern: "来得及・来不及",
          ch: "h3-06-potential-complement",
          conn: "来得及/来不及 (+ 동사) — 시간이 됨/안 됨",
          ko: "(시간상) 제때 할 수 있다/없다",
          ex: { zh: "现在出发还来得及。", pinyin: "xiànzài chūfā hái láidejí", ko: "지금 출발하면 아직 늦지 않아요." },
          ex2: { zh: "太晚了，来不及了。", pinyin: "tài wǎn le, láibují le", ko: "너무 늦어서 시간이 안 돼요." },
        },
      ],
    },
    {
      name: "복문 접속",
      items: [
        {
          pattern: "不但 … 而且 …",
          ch: "h4-09-budan-erqie",
          conn: "不但 + A, 而且 + B — 점층",
          ko: "~할 뿐만 아니라 게다가 ~",
          ex: { zh: "他不但会说汉语，而且说得很好。", pinyin: "tā búdàn huì shuō Hànyǔ, érqiě shuō de hěn hǎo", ko: "그는 중국어를 할 줄 알 뿐 아니라 잘하기까지 해요." },
          ex2: { zh: "这儿不但便宜，而且很好吃。", pinyin: "zhèr búdàn piányi, érqiě hěn hǎochī", ko: "여기는 쌀 뿐만 아니라 맛도 좋아요." },
        },
        {
          pattern: "只要 … 就 …",
          ch: "h3-08-complex-sentence",
          conn: "只要 + 조건, 就 + 결과 — 충분조건",
          ko: "~하기만 하면 ~",
          ex: { zh: "只要努力，就一定能成功。", pinyin: "zhǐyào nǔlì, jiù yídìng néng chénggōng", ko: "노력하기만 하면 반드시 성공할 수 있어요." },
          ex2: { zh: "只要你来，我就高兴。", pinyin: "zhǐyào nǐ lái, wǒ jiù gāoxìng", ko: "당신이 오기만 하면 저는 기뻐요." },
        },
        {
          pattern: "只有 … 才 …",
          ch: "h3-08-complex-sentence",
          conn: "只有 + 유일조건, 才 + 결과 — 필요조건",
          ko: "~해야만 비로소 ~",
          ex: { zh: "只有多练习，才能学好。", pinyin: "zhǐyǒu duō liànxí, cái néng xué hǎo", ko: "많이 연습해야만 잘 배울 수 있어요." },
          ex2: { zh: "只有他才知道答案。", pinyin: "zhǐyǒu tā cái zhīdào dá'àn", ko: "그만이 정답을 알아요." },
          note: "只要(충분조건)는 就, 只有(필요조건)는 才와 짝을 이뤄요.",
        },
        {
          pattern: "无论・不管 … 都 …",
          ch: "h3-08-complex-sentence",
          conn: "无论/不管 + 의문구 + 都/也 — 조건 무관",
          ko: "~에 상관없이 모두 ~",
          ex: { zh: "无论多忙，他都会来。", pinyin: "wúlùn duō máng, tā dōu huì lái", ko: "아무리 바빠도 그는 올 거예요." },
          ex2: { zh: "不管你去不去，我都去。", pinyin: "bùguǎn nǐ qù bu qù, wǒ dōu qù", ko: "당신이 가든 안 가든 저는 가요." },
          note: "无论/不管 뒤엔 의문사·정반형 같은 '여러 경우'가 와야 해요.",
        },
        {
          pattern: "因为 … 才・所以 …",
          ch: "h3-08-complex-sentence",
          conn: "因为 + 원인, 才/所以 + 결과",
          ko: "~ 때문에 (그래서/비로소) ~",
          ex: { zh: "因为努力，所以成功了。", pinyin: "yīnwèi nǔlì, suǒyǐ chénggōng le", ko: "노력했기 때문에 성공했어요." },
          ex2: { zh: "因为有事，他才没来。", pinyin: "yīnwèi yǒu shì, tā cái méi lái", ko: "일이 있어서 그가 못 온 거예요." },
        },
        {
          pattern: "越 … 越 …",
          ch: "h4-06-yue-yue",
          conn: "越 + A + 越 + B — 정비례",
          ko: "~할수록 ~하다",
          ex: { zh: "雨越下越大。", pinyin: "yǔ yuè xià yuè dà", ko: "비가 올수록 더 거세져요." },
          ex2: { zh: "我越想越担心。", pinyin: "wǒ yuè xiǎng yuè dānxīn", ko: "생각할수록 더 걱정돼요." },
          note: "越来越 + 형용사는 '점점 ~해지다'로 자주 써요 (越来越冷).",
        },
        {
          pattern: "一 … 也/都 + 不/没 …",
          ch: "h3-08-complex-sentence",
          conn: "一 + 양사 + 명사 + 也/都 + 부정 — 전면 부정",
          ko: "하나도 ~하지 않다",
          ex: { zh: "我一个人也不认识。", pinyin: "wǒ yí ge rén yě bú rènshi", ko: "저는 한 사람도 몰라요." },
          ex2: { zh: "他一句话都没说。", pinyin: "tā yí jù huà dōu méi shuō", ko: "그는 한 마디도 안 했어요." },
        },
        {
          pattern: "既 … 又 …",
          ch: "h3-08-complex-sentence",
          conn: "既 + A + 又 + B — 두 속성 병렬",
          ko: "~하기도 하고 ~하기도 하다",
          ex: { zh: "这个房间既大又干净。", pinyin: "zhège fángjiān jì dà yòu gānjìng", ko: "이 방은 크기도 하고 깨끗하기도 해요." },
          ex2: { zh: "他既聪明又努力。", pinyin: "tā jì cōngming yòu nǔlì", ko: "그는 똑똑하기도 하고 노력하기도 해요." },
        },
        {
          pattern: "不是 … 而是 …",
          ch: "h3-08-complex-sentence",
          conn: "不是 + A + 而是 + B — A가 아니라 B",
          ko: "~이 아니라 ~이다",
          ex: { zh: "他不是老师，而是学生。", pinyin: "tā bú shì lǎoshī, érshì xuésheng", ko: "그는 선생님이 아니라 학생이에요." },
          ex2: { zh: "问题不是钱，而是时间。", pinyin: "wèntí bú shì qián, érshì shíjiān", ko: "문제는 돈이 아니라 시간이에요." },
        },
        {
          pattern: "要是 … 就 …",
          ch: "h4-02-hypothesis",
          conn: "要是 + 가정, 就 + 결과 (구어)",
          ko: "만약 ~라면 ~",
          ex: { zh: "要是你有空，就来吧。", pinyin: "yàoshi nǐ yǒu kòng, jiù lái ba", ko: "시간 있으면 와요." },
          ex2: { zh: "要是下雨，我就不去了。", pinyin: "yàoshi xiàyǔ, wǒ jiù bú qù le", ko: "비 오면 저는 안 갈게요." },
          note: "如果보다 더 구어적인 가정 표현이에요.",
        },
        {
          pattern: "虽然 … 可是 …",
          ch: "h3-08-complex-sentence",
          conn: "虽然 + 사실, 可是/不过 + 반전",
          ko: "비록 ~지만 그래도 ~",
          ex: { zh: "虽然很忙，可是我很开心。", pinyin: "suīrán hěn máng, kěshì wǒ hěn kāixīn", ko: "바쁘지만 저는 즐거워요." },
          ex2: { zh: "他虽然年轻，不过很有经验。", pinyin: "tā suīrán niánqīng, búguò hěn yǒu jīngyàn", ko: "그는 젊지만 경험이 많아요." },
        },
        {
          pattern: "为了 … 而 …",
          ch: "h3-08-complex-sentence",
          conn: "为了 + 목적, (而) + 동작 — ~을 위해",
          ko: "~을 위하여 ~하다",
          ex: { zh: "为了学好汉语，他去了中国。", pinyin: "wèile xué hǎo Hànyǔ, tā qù le Zhōngguó", ko: "중국어를 잘 배우려고 그는 중국에 갔어요." },
          ex2: { zh: "我为了健康开始运动。", pinyin: "wǒ wèile jiànkāng kāishǐ yùndòng", ko: "건강을 위해 운동을 시작했어요." },
        },
      ],
    },
    {
      name: "정도·범위 부사",
      items: [
        {
          pattern: "比较 + 형용사",
          conn: "比较 + 형용사 — 비교적",
          ko: "비교적 ~하다",
          ex: { zh: "今天比较冷。", pinyin: "jīntiān bǐjiào lěng", ko: "오늘은 비교적 추워요." },
          ex2: { zh: "这个比较便宜。", pinyin: "zhège bǐjiào piányi", ko: "이게 비교적 싸요." },
        },
        {
          pattern: "非常・特别 + 형용사",
          conn: "非常/特别 + 형용사 — 매우",
          ko: "대단히/특히 ~하다",
          ex: { zh: "这个菜非常好吃。", pinyin: "zhège cài fēicháng hǎochī", ko: "이 요리는 대단히 맛있어요." },
          ex2: { zh: "今天特别热。", pinyin: "jīntiān tèbié rè", ko: "오늘은 유난히 더워요." },
        },
        {
          pattern: "形 + 极了・死了",
          ch: "h3-05-degree-complement",
          conn: "형용사 + 极了/死了 — 극단 강조",
          ko: "엄청 ~하다",
          ex: { zh: "我饿死了。", pinyin: "wǒ è sǐ le", ko: "배고파 죽겠어요." },
          ex2: { zh: "这个好吃极了。", pinyin: "zhège hǎochī jí le", ko: "이거 엄청 맛있어요." },
          note: "死了는 과장된 구어 표현. 文어체에선 极了가 무난해요.",
        },
        {
          pattern: "几乎 + 술어",
          conn: "几乎 + 술어 — 거의",
          ko: "거의 ~하다",
          ex: { zh: "我几乎每天都运动。", pinyin: "wǒ jīhū měi tiān dōu yùndòng", ko: "저는 거의 매일 운동해요." },
          ex2: { zh: "他几乎没说话。", pinyin: "tā jīhū méi shuōhuà", ko: "그는 거의 말을 안 했어요." },
        },
        {
          pattern: "只 + 동사 / 只有 + 명사",
          conn: "只 + 동사 / 只有 + 명사 — 한정",
          ko: "~만 / ~밖에 없다",
          ex: { zh: "我只喝了一杯。", pinyin: "wǒ zhǐ hē le yì bēi", ko: "저는 한 잔만 마셨어요." },
          ex2: { zh: "现在只有他一个人。", pinyin: "xiànzài zhǐyǒu tā yí ge rén", ko: "지금은 그 한 사람밖에 없어요." },
        },
        {
          pattern: "一共・总共",
          conn: "一共/总共 + 수량 — 합계",
          ko: "모두 합쳐서 ~",
          ex: { zh: "一共多少钱？", pinyin: "yígòng duōshao qián", ko: "모두 얼마예요?" },
          ex2: { zh: "我们一共五个人。", pinyin: "wǒmen yígòng wǔ ge rén", ko: "우리는 모두 다섯 명이에요." },
        },
        {
          pattern: "越来越 + 형용사",
          ch: "h3-09-comparison",
          conn: "越来越 + 형용사/동사 — 점점 더",
          ko: "점점 ~해지다",
          ex: { zh: "天气越来越冷了。", pinyin: "tiānqì yuèláiyuè lěng le", ko: "날씨가 점점 추워져요." },
          ex2: { zh: "他的汉语越来越好。", pinyin: "tā de Hànyǔ yuèláiyuè hǎo", ko: "그의 중국어가 점점 좋아져요." },
        },
        {
          pattern: "有点儿 vs 一点儿",
          conn: "有点儿 + 형용사(불만) / 형용사 + 一点儿(비교)",
          ko: "좀 ~하다 / 조금 더 ~",
          ex: { zh: "这个有点儿贵，便宜一点儿吧。", pinyin: "zhège yǒudiǎnr guì, piányi yìdiǎnr ba", ko: "이거 좀 비싸요, 좀 깎아 주세요." },
          ex2: { zh: "今天有点儿冷，多穿一点儿。", pinyin: "jīntiān yǒudiǎnr lěng, duō chuān yìdiǎnr", ko: "오늘 좀 추우니 좀 더 껴입어." },
          note: "有点儿은 술어 앞(부정적 어감), 一点儿은 형용사 뒤(비교)예요.",
        },
        {
          pattern: "差不多 + 술어",
          conn: "差不多 + 술어/수량 — 거의·대략",
          ko: "거의/대략 ~",
          ex: { zh: "差不多十点了。", pinyin: "chàbuduō shí diǎn le", ko: "거의 10시가 됐어요." },
          ex2: { zh: "我们差不多准备好了。", pinyin: "wǒmen chàbuduō zhǔnbèi hǎo le", ko: "우리는 거의 다 준비됐어요." },
        },
        {
          pattern: "至少・最多",
          conn: "至少/最多 + 수량 — 최소·최대",
          ko: "적어도 / 많아야 ~",
          ex: { zh: "至少要一个小时。", pinyin: "zhìshǎo yào yí ge xiǎoshí", ko: "적어도 한 시간은 걸려요." },
          ex2: { zh: "最多只能等十分钟。", pinyin: "zuìduō zhǐ néng děng shí fēnzhōng", ko: "많아야 10분밖에 못 기다려요." },
        },
        {
          pattern: "多 + 수량",
          conn: "수량 + 多 — ~ 남짓·여",
          ko: "~ 남짓, ~여",
          ex: { zh: "他来了一个多小时了。", pinyin: "tā lái le yí ge duō xiǎoshí le", ko: "그가 온 지 한 시간 남짓 됐어요." },
          ex2: { zh: "这本书三十多块。", pinyin: "zhè běn shū sānshí duō kuài", ko: "이 책은 30위안 남짓이에요." },
        },
        {
          pattern: "左右・前后",
          conn: "수량 + 左右/前后 — 쯤·가량",
          ko: "~쯤, ~가량",
          ex: { zh: "我五点左右到。", pinyin: "wǒ wǔ diǎn zuǒyòu dào", ko: "저는 5시쯤 도착해요." },
          ex2: { zh: "这件事一个星期左右能办好。", pinyin: "zhè jiàn shì yí ge xīngqī zuǒyòu néng bàn hǎo", ko: "이 일은 일주일 정도면 처리할 수 있어요." },
        },
      ],
    },
    {
      name: "시태·빈도 부사",
      items: [
        {
          pattern: "一直 + 동사",
          conn: "一直 + 동사 — 줄곧",
          ko: "계속/줄곧 ~하다",
          ex: { zh: "我一直在等你。", pinyin: "wǒ yìzhí zài děng nǐ", ko: "저는 계속 당신을 기다리고 있었어요." },
          ex2: { zh: "他一直没回来。", pinyin: "tā yìzhí méi huílái", ko: "그는 줄곧 돌아오지 않았어요." },
        },
        {
          pattern: "经常・常常 + 동사",
          conn: "经常/常常 + 동사 — 자주",
          ko: "자주 ~하다",
          ex: { zh: "我经常去图书馆。", pinyin: "wǒ jīngcháng qù túshūguǎn", ko: "저는 자주 도서관에 가요." },
          ex2: { zh: "他不常运动。", pinyin: "tā bù cháng yùndòng", ko: "그는 운동을 자주 안 해요." },
        },
        {
          pattern: "又 … 了 / 再 + 동사",
          ch: "h2-04-le-change",
          conn: "又(이미 반복) … 了 / 再(앞으로 반복) + 동사",
          ko: "또 ~했다 / 다시 ~하다",
          ex: { zh: "他又迟到了。", pinyin: "tā yòu chídào le", ko: "그는 또 지각했어요." },
          ex2: { zh: "请再说一遍。", pinyin: "qǐng zài shuō yí biàn", ko: "다시 한번 말해 주세요." },
          note: "이미 일어난 반복은 又, 아직 안 한 반복은 再로 나눠요.",
        },
        {
          pattern: "终于 + 동사 + 了",
          ch: "h2-04-le-change",
          conn: "终于 + 술어 + 了 — 마침내",
          ko: "마침내 ~했다",
          ex: { zh: "我终于找到工作了。", pinyin: "wǒ zhōngyú zhǎo dào gōngzuò le", ko: "저는 마침내 일자리를 찾았어요." },
          ex2: { zh: "雨终于停了。", pinyin: "yǔ zhōngyú tíng le", ko: "비가 드디어 그쳤어요." },
        },
        {
          pattern: "马上・立刻 + 동사",
          conn: "马上/立刻 + 동사 — 즉시",
          ko: "곧/즉시 ~하다",
          ex: { zh: "我马上就来。", pinyin: "wǒ mǎshàng jiù lái", ko: "제가 곧 갈게요." },
          ex2: { zh: "请立刻出发。", pinyin: "qǐng lìkè chūfā", ko: "즉시 출발하세요." },
        },
        {
          pattern: "刚・刚才",
          conn: "刚 + 동사(방금, 부사) / 刚才(방금 전, 시간명사)",
          ko: "막/방금 ~",
          ex: { zh: "我刚到家。", pinyin: "wǒ gāng dào jiā", ko: "저는 방금 집에 도착했어요." },
          ex2: { zh: "刚才他给我打电话了。", pinyin: "gāngcái tā gěi wǒ dǎ diànhuà le", ko: "방금 전에 그가 저에게 전화했어요." },
          note: "刚은 동사 앞 부사, 刚才는 문장 앞 시간명사로 위치가 달라요.",
        },
        {
          pattern: "正好・刚好",
          conn: "正好/刚好 + 술어 — 마침",
          ko: "마침/딱 ~",
          ex: { zh: "你来得正好。", pinyin: "nǐ lái de zhènghǎo", ko: "마침 잘 왔어요." },
          ex2: { zh: "我正好有时间。", pinyin: "wǒ zhènghǎo yǒu shíjiān", ko: "저 마침 시간 있어요." },
        },
        {
          pattern: "一直・总是",
          conn: "一直(줄곧)/总是(늘) + 술어",
          ko: "줄곧 / 늘 ~하다",
          ex: { zh: "他总是迟到。", pinyin: "tā zǒngshì chídào", ko: "그는 늘 지각해요." },
          ex2: { zh: "我一直在想这件事。", pinyin: "wǒ yìzhí zài xiǎng zhè jiàn shì", ko: "저는 줄곧 이 일을 생각하고 있어요." },
        },
        {
          pattern: "突然 + 동사",
          conn: "突然 + 동사 — 갑자기",
          ko: "갑자기 ~하다",
          ex: { zh: "他突然不说话了。", pinyin: "tā tūrán bù shuōhuà le", ko: "그가 갑자기 말을 안 했어요." },
          ex2: { zh: "天突然下起雨来。", pinyin: "tiān tūrán xià qǐ yǔ lái", ko: "갑자기 비가 내리기 시작했어요." },
        },
        {
          pattern: "差点儿 + 동사",
          conn: "差点儿 + 동사 — 하마터면",
          ko: "하마터면 ~할 뻔하다",
          ex: { zh: "我差点儿迟到了。", pinyin: "wǒ chàdiǎnr chídào le", ko: "하마터면 지각할 뻔했어요." },
          ex2: { zh: "他差点儿忘了。", pinyin: "tā chàdiǎnr wàng le", ko: "그는 하마터면 잊을 뻔했어요." },
        },
        {
          pattern: "原来 …",
          conn: "原来 + 절 — 알고 보니",
          ko: "알고 보니 ~ / 원래 ~",
          ex: { zh: "原来是你啊！", pinyin: "yuánlái shì nǐ a", ko: "알고 보니 너였구나!" },
          ex2: { zh: "他原来住在上海。", pinyin: "tā yuánlái zhù zài Shànghǎi", ko: "그는 원래 상하이에 살았어요." },
        },
        {
          pattern: "重新・再 + 동사",
          conn: "重新/再 + 동사 — 다시·새로",
          ko: "다시 ~하다",
          ex: { zh: "请重新写一遍。", pinyin: "qǐng chóngxīn xiě yí biàn", ko: "다시 한번 써 주세요." },
          ex2: { zh: "我们再试一次。", pinyin: "wǒmen zài shì yí cì", ko: "우리 한 번 더 해 봐요." },
        },
      ],
    },
    {
      name: "동작 표현 심화",
      items: [
        {
          pattern: "동사 중첩 (V V / V 一 V)",
          ch: "h3-05-degree-complement",
          conn: "동사 + 동사 / 동사 + 一 + 동사 — 가볍게·시도",
          ko: "좀 ~해 보다",
          ex: { zh: "你看看这个。", pinyin: "nǐ kànkan zhège", ko: "이거 좀 봐 봐." },
          ex2: { zh: "我想休息一下。", pinyin: "wǒ xiǎng xiūxi yíxià", ko: "좀 쉬고 싶어요." },
          note: "동작을 부드럽게·짧게. 2음절 동사는 ABAB로 중첩해요 (休息休息).",
        },
        {
          pattern: "形 + 형용사 중첩",
          ch: "h3-05-degree-complement",
          conn: "형용사 + 형용사 (AABB) — 생생한 묘사",
          ko: "아주 ~하게",
          ex: { zh: "她高高兴兴地走了。", pinyin: "tā gāogāoxìngxìng de zǒu le", ko: "그녀는 기쁘게 떠났어요." },
          ex2: { zh: "房间干干净净的。", pinyin: "fángjiān gānganjìngjìng de", ko: "방이 아주 깨끗해요." },
        },
        {
          pattern: "형용사/부사 + 地 + 동사",
          ch: "h5-08-de-summary",
          conn: "수식어 + 地 + 동사 — 양태 부사어",
          ko: "~하게 …하다",
          ex: { zh: "他认真地学习。", pinyin: "tā rènzhēn de xuéxí", ko: "그는 열심히 공부해요." },
          ex2: { zh: "请慢慢地说。", pinyin: "qǐng mànmàn de shuō", ko: "천천히 말씀해 주세요." },
          note: "동작을 꾸미면 地(de), 정도를 보충하면 得(de). 둘 다 de지만 위치가 달라요.",
        },
        {
          pattern: "동사 + 了 + 동사",
          ch: "h3-08-complex-sentence",
          conn: "동사1 + 了 + 동사2 — 잇따른 동작",
          ko: "~하고 나서 ~하다",
          ex: { zh: "我吃了饭就去。", pinyin: "wǒ chī le fàn jiù qù", ko: "저는 밥을 먹고 바로 가요." },
          ex2: { zh: "下了课我们一起走。", pinyin: "xià le kè wǒmen yìqǐ zǒu", ko: "수업 끝나면 우리 같이 가요." },
        },
        {
          pattern: "连 … 都/也 …",
          ch: "h4-04-lian-dou",
          conn: "连 + 강조 대상 + 都/也 + 술어 — ~조차",
          ko: "~조차 …하다",
          ex: { zh: "他连一句话也没说。", pinyin: "tā lián yí jù huà yě méi shuō", ko: "그는 한 마디조차 안 했어요." },
          ex2: { zh: "我连他的名字都不知道。", pinyin: "wǒ lián tā de míngzi dōu bù zhīdào", ko: "저는 그의 이름조차 몰라요." },
        },
        {
          pattern: "把 + … + 동사 + 결과",
          ch: "h3-01-ba",
          conn: "把 + 목적어 + 동사 + 完/好/干净 — 정돈 처치",
          ko: "~을 다/깔끔히 …해 놓다",
          ex: { zh: "我把房间打扫干净了。", pinyin: "wǒ bǎ fángjiān dǎsǎo gānjìng le", ko: "방을 깨끗이 청소했어요." },
          ex2: { zh: "请把作业写完。", pinyin: "qǐng bǎ zuòyè xiě wán", ko: "숙제를 다 끝내세요." },
        },
        {
          pattern: "동사 + 着 + 동사",
          ch: "h3-04-direction-complement",
          conn: "동사1 + 着 + 동사2 — ~한 채 …하다",
          ko: "~하면서 …하다",
          ex: { zh: "她听着音乐做饭。", pinyin: "tā tīng zhe yīnyuè zuò fàn", ko: "그녀는 음악을 들으면서 요리해요." },
          ex2: { zh: "他拿着手机走路。", pinyin: "tā ná zhe shǒujī zǒulù", ko: "그는 휴대폰을 든 채로 걸어요." },
        },
        {
          pattern: "동사 + 来 + 동사 + 去",
          conn: "동사 + 来 + 동사 + 去 — 반복",
          ko: "이리저리 ~하다 (반복)",
          ex: { zh: "他想来想去，还是不去了。", pinyin: "tā xiǎng lái xiǎng qù, háishi bú qù le", ko: "그는 이리저리 생각하다가 결국 안 가기로 했어요." },
          ex2: { zh: "我找来找去也没找到。", pinyin: "wǒ zhǎo lái zhǎo qù yě méi zhǎo dào", ko: "이리저리 찾아도 못 찾았어요." },
        },
      ],
    },
    {
      name: "어기·완곡·확인",
      items: [
        {
          pattern: "… 吧",
          conn: "문말 吧 — 권유·추측·동의",
          ko: "~하자 / ~하죠 / ~겠죠?",
          ex: { zh: "我们走吧。", pinyin: "wǒmen zǒu ba", ko: "우리 가요." },
          ex2: { zh: "他应该到了吧？", pinyin: "tā yīnggāi dào le ba", ko: "그는 도착했겠죠?" },
          note: "吗은 순수 질문, 吧는 '제안·추측'이라 어감이 달라요.",
        },
        {
          pattern: "… 了吧・… 是吧",
          conn: "문말 了吧/是吧 — 확인",
          ko: "~했죠? / ~맞죠?",
          ex: { zh: "你是韩国人吧？", pinyin: "nǐ shì Hánguó rén ba", ko: "한국 분이시죠?" },
          ex2: { zh: "你已经吃过了吧？", pinyin: "nǐ yǐjīng chī guo le ba", ko: "이미 드셨죠?" },
        },
        {
          pattern: "好像 …",
          conn: "好像 + 술어 — 추측·완곡",
          ko: "~인 것 같다",
          ex: { zh: "他好像生病了。", pinyin: "tā hǎoxiàng shēngbìng le", ko: "그는 아픈 것 같아요." },
          ex2: { zh: "好像要下雨。", pinyin: "hǎoxiàng yào xiàyǔ", ko: "비가 올 것 같아요." },
        },
        {
          pattern: "可能・也许 + 술어",
          ch: "h2-06-modal-verbs",
          conn: "可能/也许 + 술어 — 가능성",
          ko: "아마 ~일 것이다",
          ex: { zh: "他可能不来了。", pinyin: "tā kěnéng bù lái le", ko: "그는 아마 안 올 거예요." },
          ex2: { zh: "也许明天会更好。", pinyin: "yěxǔ míngtiān huì gèng hǎo", ko: "어쩌면 내일은 더 나을 거예요." },
        },
        {
          pattern: "当然・一定",
          conn: "当然(당연) / 一定(반드시) + 술어",
          ko: "당연히 / 반드시 ~",
          ex: { zh: "我当然知道。", pinyin: "wǒ dāngrán zhīdào", ko: "당연히 알죠." },
          ex2: { zh: "我一定会去。", pinyin: "wǒ yídìng huì qù", ko: "저는 꼭 갈게요." },
        },
        {
          pattern: "其实 …",
          conn: "其实 + 절 — 사실은",
          ko: "사실은 ~",
          ex: { zh: "其实我不太喜欢。", pinyin: "qíshí wǒ bú tài xǐhuan", ko: "사실 저는 별로 안 좋아해요." },
          ex2: { zh: "其实这件事很简单。", pinyin: "qíshí zhè jiàn shì hěn jiǎndān", ko: "사실 이 일은 간단해요." },
        },
        {
          pattern: "… 是吗？・… 对吗？",
          conn: "평서문 + 是吗/对吗 — 확인 부가의문",
          ko: "~죠? / 맞죠?",
          ex: { zh: "你是新来的，对吗？", pinyin: "nǐ shì xīn lái de, duì ma", ko: "새로 오신 분이죠, 맞죠?" },
          ex2: { zh: "他已经走了，是吗？", pinyin: "tā yǐjīng zǒu le, shì ma", ko: "그는 이미 갔죠?" },
        },
        {
          pattern: "难道 … 吗？",
          ch: "h4-07-rhetorical",
          conn: "难道 + 절 + 吗 — 반어",
          ko: "설마 ~란 말이에요?",
          ex: { zh: "难道你不知道吗？", pinyin: "nándào nǐ bù zhīdào ma", ko: "설마 모른단 말이에요?" },
          ex2: { zh: "难道他还没来？", pinyin: "nándào tā hái méi lái", ko: "설마 아직 안 왔어요?" },
          note: "难道는 '믿기 힘들다'는 반어의 어기를 더해요.",
        },
        {
          pattern: "恐怕 …",
          conn: "恐怕 + 절 — 우려 섞인 추측",
          ko: "아마 ~일 것 같다 (걱정)",
          ex: { zh: "恐怕来不及了。", pinyin: "kǒngpà láibují le", ko: "아마 시간이 안 될 것 같아요." },
          ex2: { zh: "他恐怕不会同意。", pinyin: "tā kǒngpà bú huì tóngyì", ko: "그는 아마 동의하지 않을 거예요." },
        },
        {
          pattern: "看来・听说 …",
          conn: "看来(보아하니)/听说(들으니) + 절",
          ko: "보아하니 / 듣자 하니 ~",
          ex: { zh: "看来今天会下雨。", pinyin: "kànlái jīntiān huì xiàyǔ", ko: "보아하니 오늘 비가 올 것 같아요." },
          ex2: { zh: "听说他要结婚了。", pinyin: "tīngshuō tā yào jiéhūn le", ko: "그가 곧 결혼한다고 들었어요." },
        },
      ],
    },
    {
      name: "주제·존재·근거",
      items: [
        {
          pattern: "对于・关于 …",
          ch: "h4-08-prepositional-frames",
          conn: "对于/关于 + 화제 + 절",
          ko: "~에 대해서는 / ~에 관하여",
          ex: { zh: "对于这个问题，我有不同的看法。", pinyin: "duìyú zhège wèntí, wǒ yǒu bùtóng de kànfǎ", ko: "이 문제에 대해 저는 다른 견해가 있어요." },
          ex2: { zh: "关于他的事，我不太清楚。", pinyin: "guānyú tā de shì, wǒ bú tài qīngchu", ko: "그의 일에 관해서는 잘 몰라요." },
        },
        {
          pattern: "除了 … 以外, 都/还 …",
          ch: "h4-05-chule",
          conn: "除了 + A + 以外, 都(제외)/还(추가) …",
          ko: "~을 제외하고는 모두 / ~말고도 또",
          ex: { zh: "除了他以外，大家都来了。", pinyin: "chúle tā yǐwài, dàjiā dōu lái le", ko: "그를 빼고는 모두 왔어요." },
          ex2: { zh: "除了汉语，我还会说英语。", pinyin: "chúle Hànyǔ, wǒ hái huì shuō Yīngyǔ", ko: "중국어 말고도 저는 영어도 할 줄 알아요." },
          note: "都와 짝이면 '제외', 还와 짝이면 '추가'로 의미가 갈려요.",
        },
        {
          pattern: "A 是 B 的 + 명사",
          ch: "h4-03-shi-de",
          conn: "A + 是 + 수식 + 的 + 명사 — 속성 규정",
          ko: "A는 ~한 …이다",
          ex: { zh: "这是去年买的衣服。", pinyin: "zhè shì qùnián mǎi de yīfu", ko: "이건 작년에 산 옷이에요." },
          ex2: { zh: "他是教汉语的老师。", pinyin: "tā shì jiāo Hànyǔ de lǎoshī", ko: "그는 중국어를 가르치는 선생님이에요." },
          note: "동사구 + 的 + 명사는 관계절처럼 명사를 꾸며요.",
        },
        {
          pattern: "동사 + 的时候",
          ch: "h3-08-complex-sentence",
          conn: "동사구 + 的时候 — ~할 때",
          ko: "~할 때",
          ex: { zh: "吃饭的时候别看手机。", pinyin: "chī fàn de shíhou bié kàn shǒujī", ko: "밥 먹을 때 휴대폰 보지 마." },
          ex2: { zh: "我小的时候住在北京。", pinyin: "wǒ xiǎo de shíhou zhù zài Běijīng", ko: "저는 어렸을 때 베이징에 살았어요." },
        },
        {
          pattern: "一 … 的时候 / 以前·以后",
          ch: "h3-08-complex-sentence",
          conn: "동사구 + 以前/以后 — ~하기 전/후에",
          ko: "~하기 전에 / 한 후에",
          ex: { zh: "睡觉以前我喜欢看书。", pinyin: "shuìjiào yǐqián wǒ xǐhuan kàn shū", ko: "자기 전에 저는 책 읽는 걸 좋아해요." },
          ex2: { zh: "下课以后我们去吃饭。", pinyin: "xiàkè yǐhòu wǒmen qù chī fàn", ko: "수업 후에 우리 밥 먹으러 가요." },
        },
        {
          pattern: "장소 + 동사 + 着 + 명사",
          ch: "h3-10-existential",
          conn: "장소 + 동사 + 着 + 명사 — ~에 ~이 …해 있다",
          ko: "(어디)에 ~이 …해 있다",
          ex: { zh: "墙上挂着一幅画。", pinyin: "qiáng shang guà zhe yì fú huà", ko: "벽에 그림 한 폭이 걸려 있어요." },
          ex2: { zh: "门口站着很多人。", pinyin: "ménkǒu zhàn zhe hěn duō rén", ko: "입구에 많은 사람이 서 있어요." },
          note: "장소가 주어 자리에 오는 존현문. 사물이 동사 뒤에 와요.",
        },
        {
          pattern: "장소 + 来/去了 + 명사",
          ch: "h3-10-existential",
          conn: "장소/시점 + 동사 + 了 + 명사 — 새로 나타남",
          ko: "~에 ~이 생기다/오다",
          ex: { zh: "前面来了一辆车。", pinyin: "qiánmiàn lái le yí liàng chē", ko: "앞쪽에서 차 한 대가 왔어요." },
          ex2: { zh: "我们公司来了一个新同事。", pinyin: "wǒmen gōngsī lái le yí ge xīn tóngshì", ko: "우리 회사에 새 동료가 왔어요." },
        },
        {
          pattern: "随着 …",
          ch: "h5-01-shumianyu",
          conn: "随着 + 변화 + 주절 — ~에 따라",
          ko: "~함에 따라 ~",
          ex: { zh: "随着时间的变化，城市越来越大。", pinyin: "suí zhe shíjiān de biànhuà, chéngshì yuèláiyuè dà", ko: "시간이 지남에 따라 도시가 점점 커져요." },
          ex2: { zh: "随着年龄增长，他变得更成熟。", pinyin: "suí zhe niánlíng zēngzhǎng, tā biàn de gèng chéngshú", ko: "나이가 들면서 그는 더 성숙해졌어요." },
        },
      ],
    },
    {
      name: "정도보어·결과 심화",
      items: [
        {
          pattern: "형용사 + 得 + 정도 묘사",
          ch: "h3-05-degree-complement",
          conn: "형용사 + 得 + 결과·정도절",
          ko: "~해서 …할 정도다",
          ex: { zh: "他高兴得跳了起来。", pinyin: "tā gāoxìng de tiào le qǐlái", ko: "그는 기뻐서 펄쩍 뛰었어요." },
          ex2: { zh: "我累得走不动了。", pinyin: "wǒ lèi de zǒu bu dòng le", ko: "저는 지쳐서 걸을 수가 없어요." },
          note: "得 뒤에 결과를 묘사하는 절을 붙여 정도를 생생하게 나타내요.",
        },
        {
          pattern: "동사 + 得 + 多/少了",
          ch: "h3-05-degree-complement",
          conn: "동사/형용사 + 得多 / 得多了 — 차이가 큼",
          ko: "훨씬 ~하다",
          ex: { zh: "今天比昨天好得多。", pinyin: "jīntiān bǐ zuótiān hǎo de duō", ko: "오늘이 어제보다 훨씬 좋아요." },
          ex2: { zh: "他跑得快多了。", pinyin: "tā pǎo de kuài duō le", ko: "그는 훨씬 빨리 달려요." },
        },
        {
          pattern: "동사 + 成・为",
          ch: "h3-03-result-complement",
          conn: "동사 + 成/为 — ~이 되다",
          ko: "~로 되다/변하다",
          ex: { zh: "雪化成了水。", pinyin: "xuě huà chéng le shuǐ", ko: "눈이 녹아 물이 됐어요." },
          ex2: { zh: "他成为了一名医生。", pinyin: "tā chéngwéi le yì míng yīshēng", ko: "그는 의사가 되었어요." },
        },
        {
          pattern: "동사 + 在・到",
          ch: "h3-03-result-complement",
          conn: "동사 + 在/到 + 장소·시간 — 결과의 위치·시점",
          ko: "~한 결과 (어디·언제)에 이르다",
          ex: { zh: "我昨天学到很晚。", pinyin: "wǒ zuótiān xué dào hěn wǎn", ko: "저는 어제 늦게까지 공부했어요." },
          ex2: { zh: "他住在学校附近。", pinyin: "tā zhù zài xuéxiào fùjìn", ko: "그는 학교 근처에 살아요." },
        },
      ],
    },
    {
      name: "능원·의지 심화",
      items: [
        {
          pattern: "应该 …",
          ch: "h2-06-modal-verbs",
          conn: "应该 + 술어 — 마땅함·추측",
          ko: "~해야 한다 / ~일 것이다",
          ex: { zh: "你应该早点儿睡觉。", pinyin: "nǐ yīnggāi zǎodiǎnr shuìjiào", ko: "당신은 좀 일찍 자야 해요." },
          ex2: { zh: "他应该已经到了。", pinyin: "tā yīnggāi yǐjīng dào le", ko: "그는 이미 도착했을 거예요." },
          note: "应该는 당위뿐 아니라 '~일 것이다'라는 합리적 추측도 나타내요.",
        },
        {
          pattern: "可能 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "可能 + 동사 — 일어날 수 있음",
          ko: "~일지도 모른다",
          ex: { zh: "他可能会迟到。", pinyin: "tā kěnéng huì chídào", ko: "그는 지각할지도 몰라요." },
          ex2: { zh: "这件事不太可能。", pinyin: "zhè jiàn shì bú tài kěnéng", ko: "이 일은 그럴 가능성이 별로 없어요." },
        },
        {
          pattern: "舍得・舍不得",
          ch: "h2-06-modal-verbs",
          conn: "舍得/舍不得 + 동사 — 아까워하다",
          ko: "기꺼이 ~하다 / 차마 ~하지 못하다",
          ex: { zh: "我舍不得离开这儿。", pinyin: "wǒ shěbude líkāi zhèr", ko: "저는 여기를 떠나기가 아쉬워요." },
          ex2: { zh: "他舍不得花钱。", pinyin: "tā shěbude huā qián", ko: "그는 돈 쓰는 걸 아까워해요." },
        },
        {
          pattern: "敢 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "敢 + 동사 — 감히 ~하다",
          ko: "감히 ~하다 / ~할 엄두를 내다",
          ex: { zh: "我不敢一个人去。", pinyin: "wǒ bù gǎn yí ge rén qù", ko: "저는 혼자 갈 엄두가 안 나요." },
          ex2: { zh: "你敢不敢试试？", pinyin: "nǐ gǎn bu gǎn shìshi", ko: "한번 해 볼 용기 있어?" },
        },
        {
          pattern: "值得 + 동사",
          ch: "h2-06-modal-verbs",
          conn: "值得 + 동사 — ~할 만하다",
          ko: "~할 가치가 있다",
          ex: { zh: "这部电影值得看。", pinyin: "zhè bù diànyǐng zhídé kàn", ko: "이 영화는 볼 만해요." },
          ex2: { zh: "这个地方值得去。", pinyin: "zhège dìfang zhídé qù", ko: "이곳은 가 볼 만해요." },
        },
      ],
    },
    {
      name: "화제·관계절",
      items: [
        {
          pattern: "동사구 + 的 + 명사",
          ch: "h1-07-de-possessive",
          conn: "수식절 + 的 + 명사 — ~한 …",
          ko: "~하는 …",
          ex: { zh: "这是我昨天买的衣服。", pinyin: "zhè shì wǒ zuótiān mǎi de yīfu", ko: "이건 제가 어제 산 옷이에요." },
          ex2: { zh: "说汉语的那个人是谁？", pinyin: "shuō Hànyǔ de nàge rén shì shéi", ko: "중국어를 하는 저 사람은 누구예요?" },
          note: "동사구 전체가 的로 명사를 꾸며요 (한국어 관형절과 비슷).",
        },
        {
          pattern: "的 + 명사 생략 (… 的)",
          ch: "h1-07-de-possessive",
          conn: "수식어 + 的 (명사 생략) — ~한 것/사람",
          ko: "~한 것 / ~하는 사람",
          ex: { zh: "红的是我的。", pinyin: "hóng de shì wǒ de", ko: "빨간 것이 제 거예요." },
          ex2: { zh: "卖水果的在那儿。", pinyin: "mài shuǐguǒ de zài nàr", ko: "과일 파는 사람은 저기 있어요." },
        },
        {
          pattern: "주제 + 술어",
          conn: "주제 + (주어) + 술어 — ~로 말하면",
          ko: "~은 (말이죠) …",
          ex: { zh: "这件事我知道。", pinyin: "zhè jiàn shì wǒ zhīdào", ko: "이 일은 제가 알아요." },
          ex2: { zh: "汉语，我学了三年。", pinyin: "Hànyǔ, wǒ xué le sān nián", ko: "중국어는 3년 배웠어요." },
          note: "강조하고 싶은 화제를 문장 맨 앞에 내세우는 어순이에요.",
        },
        {
          pattern: "对 … 来说",
          ch: "h4-08-prepositional-frames",
          conn: "对 + 사람 + 来说 — ~에게는",
          ko: "~에게 있어서는",
          ex: { zh: "对我来说，健康最重要。", pinyin: "duì wǒ lái shuō, jiànkāng zuì zhòngyào", ko: "저에게는 건강이 가장 중요해요." },
          ex2: { zh: "这对他来说很难。", pinyin: "zhè duì tā lái shuō hěn nán", ko: "이건 그에게는 어려워요." },
        },
        {
          pattern: "把 … 当作 …",
          ch: "h3-01-ba",
          conn: "把 + A + 当作/看成 + B — A를 B로 여기다",
          ko: "~을 ~로 여기다/삼다",
          ex: { zh: "他把这儿当作自己的家。", pinyin: "tā bǎ zhèr dàngzuò zìjǐ de jiā", ko: "그는 여기를 자기 집처럼 여겨요." },
          ex2: { zh: "别把我当成小孩子。", pinyin: "bié bǎ wǒ dàngchéng xiǎoháizi", ko: "저를 어린애 취급하지 마세요." },
        },
        {
          pattern: "除了 … 以外",
          ch: "h4-05-chule",
          conn: "除了 + A + 以外, 都/还 + 절",
          ko: "~을 제외하고는 / ~말고도",
          ex: { zh: "除了周末以外，我每天都上班。", pinyin: "chúle zhōumò yǐwài, wǒ měi tiān dōu shàngbān", ko: "주말 빼고는 매일 출근해요." },
          ex2: { zh: "除了汉语，他还会日语。", pinyin: "chúle Hànyǔ, tā hái huì Rìyǔ", ko: "중국어 말고도 그는 일본어도 할 줄 알아요." },
        },
        {
          pattern: "由 …",
          ch: "h5-05-passive",
          conn: "由 + 사람 + 동사 — ~이 (책임지고) 하다",
          ko: "~이/가 (맡아서) ~하다",
          ex: { zh: "这件事由我来办。", pinyin: "zhè jiàn shì yóu wǒ lái bàn", ko: "이 일은 제가 맡아서 처리할게요." },
          ex2: { zh: "会议由他主持。", pinyin: "huìyì yóu tā zhǔchí", ko: "회의는 그가 진행해요." },
        },
      ],
    },
  ],
};
