/**
 * H4 문형 사전 — HSK 4급 핵심 구문·표현 전수 레이어 (SCHEMA.md 참고)
 * 챕터가 '이해'라면 이 사전은 '전수 검색'. 모든 예문에 병음 병기.
 */
export default {
  level: "H4",
  title: "4급 문형 사전",
  desc: "把구문·被수동·강조 是…的·연동/겸어부터 가정·양보·점층·비교 심화까지 — HSK 4급 핵심 문형 112개를 기능별 14개 테마로 전수 수록한 중급 문형 사전. 모든 예문에 병음 병기.",
  themes: [
    {
      name: "把구문 — 처치문",
      items: [
        {
          pattern: "把 + 목적어 + V + 기타성분",
          conn: "주어 + 把 + 명사 + 동사 + 결과/방향/了 등",
          ko: "~을 …하다 (목적어를 어떻게 처리했는지)",
          ex: { zh: "我把作业做完了。", pinyin: "wǒ bǎ zuòyè zuòwán le", ko: "저는 숙제를 다 했어요." },
          ex2: { zh: "请把窗户关上。", pinyin: "qǐng bǎ chuānghu guānshàng", ko: "창문 좀 닫아 주세요." },
          note: "把 뒤 동사는 단독으로 끝낼 수 없다 — 了·결과보어·방향보어 등 기타성분이 꼭 붙는다",
        },
        {
          pattern: "把 + 목적어 + V + 在/到/给",
          conn: "把 + 명사 + 동사 + 在/到/给 + 장소·대상",
          ko: "~을 …에 (놓다/보내다/주다)",
          ex: { zh: "他把书放在桌子上了。", pinyin: "tā bǎ shū fàngzài zhuōzi shàng le", ko: "그는 책을 책상 위에 놓았어요." },
          ex2: { zh: "请把这封信寄给他。", pinyin: "qǐng bǎ zhè fēng xìn jìgěi tā", ko: "이 편지를 그에게 부쳐 주세요." },
          note: "위치 이동·전달 결과를 분명히 할 때 把구문이 자연스럽다",
        },
        {
          pattern: "没把 + 목적어 + V",
          conn: "주어 + 没把 + 명사 + 동사 + 기타성분",
          ko: "~을 …하지 못했다/안 했다",
          ex: { zh: "我没把钥匙带来。", pinyin: "wǒ méi bǎ yàoshi dàilái", ko: "저는 열쇠를 안 가져왔어요." },
          ex2: { zh: "他没把这件事告诉我。", pinyin: "tā méi bǎ zhè jiàn shì gàosu wǒ", ko: "그는 이 일을 저에게 말하지 않았어요." },
          note: "把구문의 부정은 把 앞에 没(过거)·别(금지)·不要를 둔다 — 把 뒤가 아니다",
        },
        {
          pattern: "把 + 목적어 + V成/V作",
          conn: "把 + A + 동사 + 成 + B",
          ko: "A를 B로 (바꾸다/번역하다)",
          ex: { zh: "请把这句话翻译成中文。", pinyin: "qǐng bǎ zhè jù huà fānyì chéng zhōngwén", ko: "이 문장을 중국어로 번역해 주세요." },
          ex2: { zh: "她把卧室改成了书房。", pinyin: "tā bǎ wòshì gǎichéng le shūfáng", ko: "그녀는 침실을 서재로 바꿨어요." },
          note: "把…翻译成 / 把…改成 — '~로 바꾸다'는 把구문이 거의 필수",
        },
        {
          pattern: "把 + 목적어 + V + 一下/一遍",
          conn: "把 + 명사 + 동사 + 동량보어",
          ko: "~을 한 번/한 차례 …하다",
          ex: { zh: "请把这段话再读一遍。", pinyin: "qǐng bǎ zhè duàn huà zài dú yí biàn", ko: "이 단락을 한 번 더 읽어 주세요." },
          ex2: { zh: "你把桌子擦一下吧。", pinyin: "nǐ bǎ zhuōzi cā yíxià ba", ko: "책상 좀 한번 닦아 줘요." },
          note: "把 뒤 동사에 동량보어(一下·一遍)를 붙이면 가벼운 부탁이 된다",
        },
        {
          pattern: "把 + 목적어 + 给 + V了",
          conn: "把 + 명사 + 给 + 동사 + 了 (구어 강조)",
          ko: "~을 …해 버렸다 (구어)",
          ex: { zh: "我不小心把杯子给打破了。", pinyin: "wǒ bù xiǎoxīn bǎ bēizi gěi dǎpò le", ko: "저도 모르게 컵을 깨뜨려 버렸어요." },
          ex2: { zh: "他把我的话给忘了。", pinyin: "tā bǎ wǒ de huà gěi wàng le", ko: "그는 제 말을 까먹어 버렸어요." },
          note: "把…给…了는 把구문에 给를 더해 어기를 강조하는 구어 표현",
        },
        {
          pattern: "别/不要把 + 목적어 + V",
          conn: "别/不要 + 把 + 명사 + 동사 + 기타성분",
          ko: "~을 …하지 마라 (금지)",
          ex: { zh: "别把这件事告诉别人。", pinyin: "bié bǎ zhè jiàn shì gàosu biérén", ko: "이 일을 남한테 말하지 마세요." },
          ex2: { zh: "请不要把垃圾扔在这里。", pinyin: "qǐng bú yào bǎ lājī rēng zài zhèlǐ", ko: "쓰레기를 여기에 버리지 마세요." },
          note: "把구문의 금지는 把 앞에 别·不要 — 把 뒤가 아니다",
        },
      ],
    },
    {
      name: "被·让·叫 — 피동",
      items: [
        {
          pattern: "被 + 행위자 + V",
          conn: "주어 + 被 (+ 행위자) + 동사 + 기타성분",
          ko: "~에게 …당하다/되다",
          ex: { zh: "我的自行车被偷了。", pinyin: "wǒ de zìxíngchē bèi tōu le", ko: "제 자전거를 도둑맞았어요." },
          ex2: { zh: "他被老板批评了一顿。", pinyin: "tā bèi lǎobǎn pīpíng le yí dùn", ko: "그는 사장에게 한바탕 혼났어요." },
          note: "행위자는 생략 가능 — 被偷了. 중국어 피동은 보통 안 좋은 일에 쓴다",
        },
        {
          pattern: "让/叫 + 행위자 + V",
          conn: "주어 + 让/叫 + 행위자 + 동사",
          ko: "~에게 …당하다 (구어 피동)",
          ex: { zh: "蛋糕让弟弟吃光了。", pinyin: "dàngāo ràng dìdi chīguāng le", ko: "케이크를 동생이 다 먹어 버렸어요." },
          ex2: { zh: "我的手机叫人拿走了。", pinyin: "wǒ de shǒujī jiào rén názǒu le", ko: "제 휴대폰을 누가 가져가 버렸어요." },
          note: "구어에서는 被보다 让·叫가 흔하다. 단 让·叫는 행위자를 생략할 수 없다",
        },
        {
          pattern: "被 + 행위자 + V + 得 + 보어",
          conn: "주어 + 被 + 행위자 + 동사 + 得 + 정도보어",
          ko: "~에게 …해져서 (어떤 상태가) 되다",
          ex: { zh: "他被这个问题难住了。", pinyin: "tā bèi zhège wèntí nánzhù le", ko: "그는 이 문제에 막혀 버렸어요." },
          ex2: { zh: "我被吓得说不出话来。", pinyin: "wǒ bèi xià de shuō bu chū huà lái", ko: "저는 놀라서 말이 안 나왔어요." },
        },
        {
          pattern: "被 + 행위자 + V + 走/掉/坏",
          conn: "주어 + 被 + 행위자 + 동사 + 결과보어",
          ko: "~에게 …되어 버리다 (소실·손상)",
          ex: { zh: "我的雨伞被别人拿走了。", pinyin: "wǒ de yǔsǎn bèi biérén názǒu le", ko: "제 우산을 누가 가져가 버렸어요." },
          ex2: { zh: "蛋糕被孩子吃掉了一半。", pinyin: "dàngāo bèi háizi chīdiào le yíbàn", ko: "케이크를 아이가 절반 먹어 버렸어요." },
          note: "被구문도 동사 뒤에 결과·방향보어를 붙여 결과를 분명히 한다",
        },
        {
          pattern: "没被 + 행위자 + V",
          conn: "주어 + 没(有)被 + 행위자 + 동사",
          ko: "~에게 …당하지 않았다",
          ex: { zh: "幸好钱包没被偷。", pinyin: "xìnghǎo qiánbāo méi bèi tōu", ko: "다행히 지갑은 도둑맞지 않았어요." },
          ex2: { zh: "他的秘密一直没被发现。", pinyin: "tā de mìmì yìzhí méi bèi fāxiàn", ko: "그의 비밀은 줄곧 들키지 않았어요." },
          note: "被구문의 부정은 被 앞에 没·没有 — 不被는 거의 안 쓴다",
        },
      ],
    },
    {
      name: "강조 是…的",
      items: [
        {
          pattern: "是 + 강조성분 + 的",
          conn: "주어 + 是 + 시간/장소/방식/대상 + 동사 + 的",
          ko: "~한 것이다 (이미 일어난 일의 시간·장소·방식 강조)",
          ex: { zh: "我是昨天到的。", pinyin: "wǒ shì zuótiān dào de", ko: "저는 어제 도착한 거예요." },
          ex2: { zh: "他是坐飞机来的。", pinyin: "tā shì zuò fēijī lái de", ko: "그는 비행기를 타고 온 거예요." },
          note: "이미 일어난 일에서 '언제·어디서·어떻게'를 강조 — 了가 아니라 是…的를 쓴다",
        },
        {
          pattern: "不是 + 강조성분 + 的",
          conn: "주어 + 不是 + 강조성분 + 동사 + 的",
          ko: "~한 게 아니다 (강조의 부정)",
          ex: { zh: "我不是故意的。", pinyin: "wǒ bú shì gùyì de", ko: "일부러 그런 게 아니에요." },
          ex2: { zh: "这件事不是我做的。", pinyin: "zhè jiàn shì bú shì wǒ zuò de", ko: "이 일은 제가 한 게 아니에요." },
          note: "是…的의 부정은 是를 不是로 — 不是…的 전체가 한 덩어리",
        },
        {
          pattern: "是 + 대상 + 的",
          conn: "명사 + 是 + 명사 + 的",
          ko: "~의 것이다",
          ex: { zh: "这本词典是图书馆的。", pinyin: "zhè běn cídiǎn shì túshūguǎn de", ko: "이 사전은 도서관 것이에요." },
          ex2: { zh: "这个主意是大家一起想的。", pinyin: "zhège zhǔyi shì dàjiā yìqǐ xiǎng de", ko: "이 아이디어는 다 같이 생각해 낸 거예요." },
        },
        {
          pattern: "是 + 강조 + 동사 + 的 + 목적어",
          conn: "주어 + 是 + 강조성분 + 동사 + 的 + 목적어",
          ko: "~한 것이다 (목적어가 있을 때)",
          ex: { zh: "我是去年开始学汉语的。", pinyin: "wǒ shì qùnián kāishǐ xué hànyǔ de", ko: "저는 작년에 중국어를 배우기 시작한 거예요." },
          ex2: { zh: "他是在网上买的票。", pinyin: "tā shì zài wǎngshàng mǎi de piào", ko: "그는 인터넷에서 표를 산 거예요." },
          note: "목적어가 있으면 的를 목적어 앞(买的票)에 둘 수도 있다",
        },
        {
          pattern: "是 + 형용사 + 的",
          conn: "주어 + 是 + 형용사 + 的 (성질의 단정)",
          ko: "~하기 마련이다, ~한 법이다 (단정·확신)",
          ex: { zh: "努力总是有用的。", pinyin: "nǔlì zǒngshì yǒuyòng de", ko: "노력은 늘 도움이 되는 법이에요." },
          ex2: { zh: "他不会骗你的。", pinyin: "tā bú huì piàn nǐ de", ko: "그가 당신을 속일 리 없어요." },
          note: "문장 끝 …的는 화자의 단정·확신을 더한다 — 会…的(분명 ~할 거예요)",
        },
      ],
    },
    {
      name: "연동·겸어",
      items: [
        {
          pattern: "V1 + V2",
          conn: "주어 + 동사1 + (목적어) + 동사2 + (목적어)",
          ko: "~해서 …하다 (한 주어의 연속·목적 동작)",
          ex: { zh: "我去超市买东西。", pinyin: "wǒ qù chāoshì mǎi dōngxi", ko: "저는 마트에 물건 사러 가요." },
          ex2: { zh: "他坐地铁上班。", pinyin: "tā zuò dìtiě shàngbān", ko: "그는 지하철을 타고 출근해요." },
          note: "동작 순서대로 동사를 늘어놓는다 — 去买(가서 사다), 坐…上班(타고 출근하다)",
        },
        {
          pattern: "请/让/叫 + 사람 + V",
          conn: "동사1 + 사람 + 동사2 — 사람이 V1의 목적어이자 V2의 주어",
          ko: "~에게 …하게 하다/시키다/청하다",
          ex: { zh: "妈妈让我早点儿回家。", pinyin: "māma ràng wǒ zǎodiǎnr huíjiā", ko: "엄마가 저에게 일찍 집에 오라고 했어요." },
          ex2: { zh: "老师请同学们安静一下。", pinyin: "lǎoshī qǐng tóngxuémen ānjìng yíxià", ko: "선생님이 학생들에게 좀 조용히 해 달라고 했어요." },
          note: "让(시키다)·叫(시키다)·请(청하다)·使(~하게 만들다)가 대표 겸어 동사",
        },
        {
          pattern: "使 + 사람 + 형용사/동사",
          conn: "주어 + 使 + 대상 + 변화·심리",
          ko: "~로 하여금 …하게 하다 (서면)",
          ex: { zh: "这个消息使大家很高兴。", pinyin: "zhège xiāoxi shǐ dàjiā hěn gāoxìng", ko: "이 소식은 모두를 기쁘게 했어요." },
          ex2: { zh: "运动使人健康。", pinyin: "yùndòng shǐ rén jiànkāng", ko: "운동은 사람을 건강하게 합니다." },
          note: "使는 让보다 서면적·추상적 — 사물·일이 사람에게 심리 변화를 일으킬 때",
        },
        {
          pattern: "有 + 명사 + V",
          conn: "有 + 명사 + 동사 (존재+묘사 겸어)",
          ko: "~할 …이 있다",
          ex: { zh: "有件事想跟你商量。", pinyin: "yǒu jiàn shì xiǎng gēn nǐ shāngliang", ko: "당신과 상의하고 싶은 일이 있어요." },
          ex2: { zh: "有很多人来参加这个活动。", pinyin: "yǒu hěn duō rén lái cānjiā zhège huódòng", ko: "많은 사람이 이 행사에 참가하러 왔어요." },
        },
        {
          pattern: "帮 + 사람 + V",
          conn: "帮 + 사람 + 동사 (겸어 — ~를 도와 …하다)",
          ko: "~를 도와 …해 주다, ~ 대신 …하다",
          ex: { zh: "请帮我看一下行李。", pinyin: "qǐng bāng wǒ kān yíxià xíngli", ko: "제 짐 좀 봐 주세요." },
          ex2: { zh: "他帮我把箱子搬上来了。", pinyin: "tā bāng wǒ bǎ xiāngzi bān shànglái le", ko: "그가 저 대신 상자를 올려다 줬어요." },
          note: "帮…(忙)은 부탁·도움의 겸어 — 帮我 + 동사가 통째로 자주 쓰인다",
        },
        {
          pattern: "请 + 사람 + V",
          conn: "请 + 사람 + 동사 (~를 …하도록 청하다)",
          ko: "~에게 …해 주십사 청하다, ~를 대접하다",
          ex: { zh: "今天我请你们吃饭。", pinyin: "jīntiān wǒ qǐng nǐmen chīfàn", ko: "오늘은 제가 여러분께 식사를 대접할게요." },
          ex2: { zh: "我们请了一位专家来讲座。", pinyin: "wǒmen qǐng le yí wèi zhuānjiā lái jiǎngzuò", ko: "우리는 전문가 한 분을 강연에 모셨어요." },
          note: "请客(한턱내다)·请…吃饭처럼 请은 '대접·초청'의 겸어 동사",
        },
        {
          pattern: "V1 + 是为了 + V2",
          conn: "동사1 + 是为了 + 동사2 (목적 연동)",
          ko: "~하는 것은 …하기 위해서이다",
          ex: { zh: "我学汉语是为了去中国工作。", pinyin: "wǒ xué hànyǔ shì wèile qù zhōngguó gōngzuò", ko: "제가 중국어를 배우는 건 중국에 가서 일하기 위해서예요." },
          ex2: { zh: "他这么做是为了帮助大家。", pinyin: "tā zhème zuò shì wèile bāngzhù dàjiā", ko: "그가 이렇게 하는 건 모두를 돕기 위해서예요." },
        },
      ],
    },
    {
      name: "결과·방향·가능 보어",
      items: [
        {
          pattern: "V + 完/好/到/懂",
          conn: "동사 + 결과보어 + (了)",
          ko: "~해 내다/마치다 (동작의 결과)",
          ex: { zh: "我听懂了老师的话。", pinyin: "wǒ tīngdǒng le lǎoshī de huà", ko: "선생님의 말을 알아들었어요." },
          ex2: { zh: "作业还没写完。", pinyin: "zuòyè hái méi xiěwán", ko: "숙제를 아직 다 못 썼어요." },
          note: "부정은 没 — 听懂의 부정은 没听懂. 不은 거의 안 쓴다",
        },
        {
          pattern: "V + 上/下/出/起来",
          conn: "동사 + 방향보어 — 동작의 방향·결과 의미 확장",
          ko: "~해 오르다/내리다/나오다 등",
          ex: { zh: "他站起来回答问题。", pinyin: "tā zhàn qǐlái huídá wèntí", ko: "그는 일어나서 질문에 답했어요." },
          ex2: { zh: "我想起来一件重要的事。", pinyin: "wǒ xiǎng qǐlái yí jiàn zhòngyào de shì", ko: "중요한 일이 하나 생각났어요." },
          note: "想起来(생각나다)·看出来(알아보다)처럼 방향보어가 비유적 뜻으로도 쓰인다",
        },
        {
          pattern: "V + 得/不 + 결과보어",
          conn: "동사 + 得(가능)/不(불가능) + 결과·방향보어",
          ko: "~할 수 있다/없다 (능력·여건상)",
          ex: { zh: "这些菜我一个人吃不完。", pinyin: "zhèxiē cài wǒ yí ge rén chī bu wán", ko: "이 음식들은 저 혼자 다 못 먹어요." },
          ex2: { zh: "声音太小，我听不见。", pinyin: "shēngyīn tài xiǎo, wǒ tīng bu jiàn", ko: "소리가 너무 작아서 안 들려요." },
          note: "听不见(안 들린다)·看得见(보인다) — 能…보다 '여건상 가능/불가능'을 직접 표현. 가능보어는 把구문과 함께 못 쓴다",
        },
        {
          pattern: "V + 得 + 정도보어",
          conn: "동사 (+ 목적어 + 동사) + 得 + 형용사구",
          ko: "~하는 정도가 …하다 (정도·평가)",
          ex: { zh: "他汉语说得很流利。", pinyin: "tā hànyǔ shuō de hěn liúlì", ko: "그는 중국어를 아주 유창하게 해요." },
          ex2: { zh: "今天我起得太晚了。", pinyin: "jīntiān wǒ qǐ de tài wǎn le", ko: "오늘 저는 너무 늦게 일어났어요." },
          note: "목적어가 있으면 동사를 한 번 더 반복 — 说汉语 → 汉语说得很流利",
        },
        {
          pattern: "V + 过",
          conn: "동사 + 过 (~해 본 적 있다)",
          ko: "~한 적이 있다 (경험)",
          ex: { zh: "我去过两次中国。", pinyin: "wǒ qù guo liǎng cì zhōngguó", ko: "저는 중국에 두 번 가 본 적이 있어요." },
          ex2: { zh: "他从来没听过这首歌。", pinyin: "tā cónglái méi tīng guo zhè shǒu gē", ko: "그는 이 노래를 한 번도 들어 본 적이 없어요." },
          note: "过는 경험을 나타낸다 — 부정은 没…过, '한 번도'는 从来没…过",
        },
        {
          pattern: "V + 得/不 + 下",
          conn: "동사 + 得下/不下 (공간상 ~할 수 있다/없다)",
          ko: "~을 다 담을/넣을 수 있다/없다",
          ex: { zh: "这个房间坐得下二十个人。", pinyin: "zhège fángjiān zuò de xià èrshí ge rén", ko: "이 방은 스무 명이 앉을 수 있어요." },
          ex2: { zh: "箱子太小，放不下这么多衣服。", pinyin: "xiāngzi tài xiǎo, fàng bu xià zhème duō yīfu", ko: "상자가 너무 작아서 이렇게 많은 옷을 못 넣어요." },
          note: "V得下/V不下는 '공간이 수용 가능한가'를 나타내는 가능보어",
        },
        {
          pattern: "V + 得了/不了",
          conn: "동사 + 得了/不了 (~할 수 있다/없다)",
          ko: "~할 수 있다/없다 (실현 가능성)",
          ex: { zh: "今天的事一天做得了吗？", pinyin: "jīntiān de shì yì tiān zuò de liǎo ma", ko: "오늘 일을 하루에 끝낼 수 있어요?" },
          ex2: { zh: "下这么大雨，我们去不了了。", pinyin: "xià zhème dà yǔ, wǒmen qù bu liǎo le", ko: "비가 이렇게 많이 와서 우리 못 가게 됐어요." },
          note: "V得了/V不了(liǎo)는 '실현 가능성' — 完了(le)와 발음·뜻이 다르다",
        },
      ],
    },
    {
      name: "가정·조건",
      items: [
        {
          pattern: "如果…(的话)，就…",
          conn: "如果 + 조건 (+ 的话)，주어 + 就 + 결과",
          ko: "만약 ~라면, …하다",
          ex: { zh: "如果明天下雨，我们就不去了。", pinyin: "rúguǒ míngtiān xiàyǔ, wǒmen jiù bú qù le", ko: "만약 내일 비가 오면 우리는 안 갈 거예요." },
          ex2: { zh: "如果你有问题的话，可以问我。", pinyin: "rúguǒ nǐ yǒu wèntí de huà, kěyǐ wèn wǒ", ko: "만약 질문이 있으면 저에게 물어보세요." },
          note: "如果…就… 짝꿍 — 끝에 的话를 붙이면 더 구어적. 要是…就…도 같은 뜻",
        },
        {
          pattern: "要是…，就…",
          conn: "要是 + 조건，주어 + 就 + 결과",
          ko: "~라면, …할 텐데 (구어)",
          ex: { zh: "要是我有时间，就去旅游。", pinyin: "yàoshi wǒ yǒu shíjiān, jiù qù lǚyóu", ko: "시간이 있으면 여행 갈 텐데요." },
          ex2: { zh: "要是早知道，我就不来了。", pinyin: "yàoshi zǎo zhīdào, wǒ jiù bù lái le", ko: "진작 알았으면 안 왔을 텐데." },
          note: "要是는 如果보다 구어적. 글말에서는 如果가 무난",
        },
        {
          pattern: "只要…，就…",
          conn: "只要 + 조건，주어 + 就 + 결과",
          ko: "~하기만 하면, …하다 (충분조건)",
          ex: { zh: "只要努力，就一定能成功。", pinyin: "zhǐyào nǔlì, jiù yídìng néng chénggōng", ko: "노력하기만 하면 반드시 성공할 수 있어요." },
          ex2: { zh: "只要你愿意，随时都可以来。", pinyin: "zhǐyào nǐ yuànyì, suíshí dōu kěyǐ lái", ko: "당신이 원하기만 하면 언제든 와도 돼요." },
          note: "只要…就(하나만 만족하면 충분)와 只有…才(그것만이 유일 조건)를 구별",
        },
        {
          pattern: "只有…，才…",
          conn: "只有 + 유일조건，주어 + 才 + 결과",
          ko: "~해야만, 비로소 …하다 (필요조건)",
          ex: { zh: "只有多练习，才能学好。", pinyin: "zhǐyǒu duō liànxí, cái néng xuéhǎo", ko: "많이 연습해야만 잘 배울 수 있어요." },
          ex2: { zh: "只有他才知道密码。", pinyin: "zhǐyǒu tā cái zhīdào mìmǎ", ko: "그 사람만이 비밀번호를 알아요." },
          note: "只有 뒤에는 就가 아니라 才 — '그것만이 유일한 조건'을 강조",
        },
        {
          pattern: "无论/不管…，都…",
          conn: "无论/不管 + 의문구·선택지，주어 + 都/也 + 결과",
          ko: "~하든 (상관없이), 다 …하다",
          ex: { zh: "无论多忙，他都坚持锻炼。", pinyin: "wúlùn duō máng, tā dōu jiānchí duànliàn", ko: "아무리 바빠도 그는 운동을 꾸준히 해요." },
          ex2: { zh: "不管你同不同意，我都要去。", pinyin: "bùguǎn nǐ tóng bu tóngyì, wǒ dōu yào qù", ko: "당신이 동의하든 말든 저는 갈 거예요." },
          note: "无论/不管 뒤에는 의문사·정반의문·선택지가 와야 한다. 不管은 구어, 无论은 글말",
        },
        {
          pattern: "要不・要不然",
          conn: "문장，要不(然) + 대안·결과",
          ko: "안 그러면, ~하든가",
          ex: { zh: "快点儿走，要不然就迟到了。", pinyin: "kuài diǎnr zǒu, yàoburán jiù chídào le", ko: "빨리 가, 안 그러면 늦어." },
          ex2: { zh: "要不我们改天再去吧。", pinyin: "yàobu wǒmen gǎitiān zài qù ba", ko: "아니면 우리 다음에 다시 가요." },
          note: "要不然(안 그러면)·要不(아니면 ~하자) — 둘 다 구어 제안·경고",
        },
        {
          pattern: "万一",
          conn: "万一 + 만일의 상황，주어 + 대비",
          ko: "만일 ~하면 (혹시 몰라)",
          ex: { zh: "多带点儿钱，万一不够呢。", pinyin: "duō dài diǎnr qián, wànyī bú gòu ne", ko: "돈을 좀 더 챙겨, 혹시 모자랄지 모르니." },
          ex2: { zh: "万一他不同意怎么办？", pinyin: "wànyī tā bù tóngyì zěnme bàn", ko: "만일 그가 동의하지 않으면 어쩌죠?" },
          note: "万一은 확률이 낮은 불상사 대비 — '만에 하나'",
        },
        {
          pattern: "的话",
          conn: "조건절 + 的话，주절",
          ko: "~한다면 (조건의 마무리)",
          ex: { zh: "有时间的话，一起去看电影吧。", pinyin: "yǒu shíjiān de huà, yìqǐ qù kàn diànyǐng ba", ko: "시간이 있으면 같이 영화 보러 가요." },
          ex2: { zh: "不舒服的话，就早点儿休息。", pinyin: "bù shūfu de huà, jiù zǎodiǎnr xiūxi", ko: "몸이 안 좋으면 일찍 쉬어요." },
          note: "的话는 조건절 끝에 붙는 구어 표지 — 如果·要是와 함께 또는 단독으로",
        },
      ],
    },
    {
      name: "양보·전환",
      items: [
        {
          pattern: "虽然…，但是/可是…",
          conn: "虽然 + 사실，但是/可是 + 상반 결과",
          ko: "비록 ~지만, …하다",
          ex: { zh: "虽然天气很冷，但是他还去跑步。", pinyin: "suīrán tiānqì hěn lěng, dànshì tā hái qù pǎobù", ko: "날씨가 추운데도 그는 달리기를 하러 가요." },
          ex2: { zh: "这家店虽然小，可是东西很全。", pinyin: "zhè jiā diàn suīrán xiǎo, kěshì dōngxi hěn quán", ko: "이 가게는 작지만 물건은 다 갖춰져 있어요." },
          note: "虽然…但是… 둘 다 써야 자연스럽다 — 한국어처럼 '하지만'을 생략하지 않는다",
        },
        {
          pattern: "即使/就算…，也…",
          conn: "即使/就算 + 가정·극단，주어 + 也 + 결과",
          ko: "설령 ~하더라도, …하다",
          ex: { zh: "即使下大雨，比赛也不会取消。", pinyin: "jíshǐ xià dàyǔ, bǐsài yě bú huì qǔxiāo", ko: "설령 비가 많이 와도 경기는 취소되지 않을 거예요." },
          ex2: { zh: "就算再难，我也不会放弃。", pinyin: "jiùsuàn zài nán, wǒ yě bú huì fàngqì", ko: "아무리 어려워도 저는 포기하지 않을 거예요." },
          note: "即使는 아직 일어나지 않은 가정 — 虽然(이미 사실)과 구별. 就算은 구어",
        },
        {
          pattern: "其实",
          conn: "주어 + 其实 + 사실 (예상과 다른 진실)",
          ko: "사실은, 실은",
          ex: { zh: "看起来很难，其实很简单。", pinyin: "kàn qǐlái hěn nán, qíshí hěn jiǎndān", ko: "어려워 보이지만 사실은 아주 쉬워요." },
          ex2: { zh: "其实我也不太清楚。", pinyin: "qíshí wǒ yě bú tài qīngchu", ko: "사실 저도 잘 몰라요." },
        },
        {
          pattern: "不过",
          conn: "문장，不过 + 가벼운 전환",
          ko: "그런데, 다만",
          ex: { zh: "这件衣服很好看，不过有点儿贵。", pinyin: "zhè jiàn yīfu hěn hǎokàn, búguò yǒudiǎnr guì", ko: "이 옷은 예쁜데 다만 좀 비싸요." },
          ex2: { zh: "我想去，不过没时间。", pinyin: "wǒ xiǎng qù, búguò méi shíjiān", ko: "가고 싶은데 시간이 없어요." },
          note: "不过는 但是보다 가벼운 전환 — '그런데·다만'에 가깝다",
        },
        {
          pattern: "倒",
          conn: "주어 + 倒 + 의외·완곡한 전환",
          ko: "오히려, 그런데 (의외·완곡)",
          ex: { zh: "这个办法倒不错。", pinyin: "zhège bànfǎ dào búcuò", ko: "이 방법 의외로 괜찮네요." },
          ex2: { zh: "他人倒挺好，就是太忙了。", pinyin: "tā rén dào tǐng hǎo, jiùshì tài máng le", ko: "그 사람 사람은 좋은데 너무 바빠요." },
          note: "倒는 예상과 다른 가벼운 전환·완곡 — '의외로·그런데'의 어감을 더한다",
        },
        {
          pattern: "再…也…",
          conn: "再 + 형용사/동사 + 也 + 결과",
          ko: "아무리 ~해도 …하다",
          ex: { zh: "再忙也要吃早饭。", pinyin: "zài máng yě yào chī zǎofàn", ko: "아무리 바빠도 아침은 먹어야 해요." },
          ex2: { zh: "这个道理再简单也有人不懂。", pinyin: "zhège dàolǐ zài jiǎndān yě yǒu rén bù dǒng", ko: "이 이치는 아무리 쉬워도 모르는 사람이 있어요." },
          note: "再…也…는 '아무리 ~해도' — 무론(無論)식 양보의 구어 표현",
        },
      ],
    },
    {
      name: "점층·추가",
      items: [
        {
          pattern: "越来越 + 형용사",
          conn: "주어 + 越来越 + 형용사/동사",
          ko: "점점 더 ~해지다",
          ex: { zh: "天气越来越暖和了。", pinyin: "tiānqì yuè lái yuè nuǎnhuo le", ko: "날씨가 점점 따뜻해지고 있어요." },
          ex2: { zh: "他的汉语越来越好了。", pinyin: "tā de hànyǔ yuè lái yuè hǎo le", ko: "그의 중국어가 점점 좋아지고 있어요." },
          note: "끝에 了가 붙어 변화를 나타낸다",
        },
        {
          pattern: "越 A 越 B",
          conn: "주어 + 越 + 동사/형용사 + 越 + 형용사",
          ko: "~할수록 …하다",
          ex: { zh: "雨越下越大。", pinyin: "yǔ yuè xià yuè dà", ko: "비가 내릴수록 더 거세져요." },
          ex2: { zh: "这本书越看越有意思。", pinyin: "zhè běn shū yuè kàn yuè yǒu yìsi", ko: "이 책은 볼수록 재미있어요." },
          note: "越来越(절대적 변화)와 越A越B(상관 변화)를 구별",
        },
        {
          pattern: "不但…，而且…",
          conn: "不但 + A，而且 + 더 나아간 B",
          ko: "~할 뿐만 아니라, 게다가 …하다",
          ex: { zh: "他不但会说英语，而且会说法语。", pinyin: "tā búdàn huì shuō yīngyǔ, érqiě huì shuō fǎyǔ", ko: "그는 영어를 할 뿐만 아니라 프랑스어도 해요." },
          ex2: { zh: "这里不但风景美，而且空气好。", pinyin: "zhèlǐ búdàn fēngjǐng měi, érqiě kōngqì hǎo", ko: "여기는 경치가 아름다울 뿐 아니라 공기도 좋아요." },
          note: "不但…而且… 짝꿍. 주어가 같으면 不但은 주어 뒤, 다르면 주어 앞",
        },
        {
          pattern: "除了…以外，还/都…",
          conn: "除了 + A 以外，주어 + 还(추가)/都(예외) + B",
          ko: "~외에도 …하다 / ~을 빼고는 다 …하다",
          ex: { zh: "除了汉语以外，我还会说日语。", pinyin: "chúle hànyǔ yǐwài, wǒ hái huì shuō rìyǔ", ko: "중국어 외에 일본어도 할 수 있어요." },
          ex2: { zh: "除了他以外，大家都来了。", pinyin: "chúle tā yǐwài, dàjiā dōu lái le", ko: "그를 빼고는 다들 왔어요." },
          note: "뒤에 还/也면 '포함·추가', 都면 '예외' — 같은 除了가 정반대로 갈린다",
        },
        {
          pattern: "连…都/也…",
          conn: "连 + 극단적 예 + 都/也 + 술어",
          ko: "~조차도 …하다 (강조)",
          ex: { zh: "他连饭都不吃了。", pinyin: "tā lián fàn dōu bù chī le", ko: "그는 밥조차 안 먹어요." },
          ex2: { zh: "这么简单的问题，连孩子都会。", pinyin: "zhème jiǎndān de wèntí, lián háizi dōu huì", ko: "이렇게 쉬운 문제는 아이조차도 풀 수 있어요." },
          note: "连…都/也…는 '~조차도' — 극단적인 예를 들어 강조. 都·也를 꼭 동반",
        },
        {
          pattern: "又…又…",
          conn: "又 + A + 又 + B (두 성질·동작 병렬)",
          ko: "~하기도 하고 …하기도 하다",
          ex: { zh: "这家店的菜又便宜又好吃。", pinyin: "zhè jiā diàn de cài yòu piányi yòu hǎochī", ko: "이 가게 음식은 싸고도 맛있어요." },
          ex2: { zh: "他又会唱歌，又会跳舞。", pinyin: "tā yòu huì chànggē, yòu huì tiàowǔ", ko: "그는 노래도 부르고 춤도 출 줄 알아요." },
          note: "又…又…는 이미 실현된 두 성질, 既…又…는 더 서면적",
        },
        {
          pattern: "不是…，而是…",
          conn: "不是 + A，而是 + B (정정·대조)",
          ko: "~이 아니라 …이다",
          ex: { zh: "我要的不是这个，而是那个。", pinyin: "wǒ yào de bú shì zhège, ér shì nàge", ko: "제가 원하는 건 이게 아니라 저거예요." },
          ex2: { zh: "他不是不想去，而是没时间。", pinyin: "tā bú shì bù xiǎng qù, ér shì méi shíjiān", ko: "그는 가기 싫은 게 아니라 시간이 없는 거예요." },
          note: "不是…而是…는 'A가 아니라 B'라고 바로잡는 구문",
        },
        {
          pattern: "既…又/也…",
          conn: "既 + A + 又/也 + B (병렬 강조)",
          ko: "~할 뿐 아니라 …하기도 하다",
          ex: { zh: "这样做既省钱又环保。", pinyin: "zhèyàng zuò jì shěngqián yòu huánbǎo", ko: "이렇게 하면 돈도 아끼고 친환경적이기도 해요." },
          ex2: { zh: "他既聪明，也很努力。", pinyin: "tā jì cōngming, yě hěn nǔlì", ko: "그는 똑똑하기도 하고 노력도 많이 해요." },
          note: "既…又…는 又…又…의 서면형 — 既 뒤엔 보통 2음절어",
        },
        {
          pattern: "不是…，就是…",
          conn: "不是 + A，就是 + B (둘 중 하나)",
          ko: "~ 아니면 …이다 (양자 중 하나)",
          ex: { zh: "他每天不是看书，就是上网。", pinyin: "tā měi tiān bú shì kàn shū, jiùshì shàngwǎng", ko: "그는 매일 책을 보지 않으면 인터넷을 해요." },
          ex2: { zh: "周末不是下雨，就是刮风。", pinyin: "zhōumò bú shì xiàyǔ, jiùshì guāfēng", ko: "주말이면 비가 오거나 아니면 바람이 불어요." },
          note: "不是…就是…는 '둘 중 하나'(추측·범위) — 不是…而是…(정정)와 구별",
        },
      ],
    },
    {
      name: "비교 심화",
      items: [
        {
          pattern: "A 比 B + 형용사 + 수량보어",
          conn: "A + 比 + B + 형용사 + 一点儿/多了/구체적 차이",
          ko: "A가 B보다 (얼마만큼) 더 ~하다",
          ex: { zh: "今天比昨天热多了。", pinyin: "jīntiān bǐ zuótiān rè duō le", ko: "오늘이 어제보다 훨씬 더워요." },
          ex2: { zh: "他比我大三岁。", pinyin: "tā bǐ wǒ dà sān suì", ko: "그는 저보다 세 살 많아요." },
          note: "차이를 형용사 뒤에 둔다 — 大三岁(세 살 많다), 热多了(훨씬 덥다). 很·非常은 못 쓴다",
        },
        {
          pattern: "A 比 B 更/还 + 형용사",
          conn: "A + 比 + B + 更/还 + 형용사",
          ko: "A가 B보다 더욱 ~하다",
          ex: { zh: "这个办法比那个更好。", pinyin: "zhège bànfǎ bǐ nàge gèng hǎo", ko: "이 방법이 저것보다 더 좋아요." },
          ex2: { zh: "他跑得比我还快。", pinyin: "tā pǎo de bǐ wǒ hái kuài", ko: "그는 저보다도 더 빨리 달려요." },
          note: "比 비교문 강조에는 更·还만 — 很·太·非常은 쓸 수 없다",
        },
        {
          pattern: "A 没有 B (那么) + 형용사",
          conn: "A + 没有 + B + (这么/那么) + 형용사",
          ko: "A는 B만큼 ~하지 않다",
          ex: { zh: "我没有他那么高。", pinyin: "wǒ méiyǒu tā nàme gāo", ko: "저는 그만큼 키가 크지 않아요." },
          ex2: { zh: "这家餐厅没有那家好吃。", pinyin: "zhè jiā cāntīng méiyǒu nà jiā hǎochī", ko: "이 식당은 저 식당만큼 맛있지 않아요." },
          note: "比의 부정은 不比가 아니라 보통 没有 — '~만큼 못하다'",
        },
        {
          pattern: "A 跟/和 B 一样",
          conn: "A + 跟/和 + B + 一样 + (형용사)",
          ko: "A는 B와 똑같다/마찬가지로 ~하다",
          ex: { zh: "我的手机跟你的一样。", pinyin: "wǒ de shǒujī gēn nǐ de yíyàng", ko: "제 휴대폰은 당신 것과 똑같아요." },
          ex2: { zh: "他的想法和我的一样。", pinyin: "tā de xiǎngfǎ hé wǒ de yíyàng", ko: "그의 생각은 제 생각과 같아요." },
          note: "부정은 不一样. 跟…一样 뒤에 형용사를 붙이면 '~만큼 …하다'",
        },
        {
          pattern: "A 是 B 的 + 수량 + 倍",
          conn: "A + 是 + B + 的 + 수 + 倍",
          ko: "A는 B의 ~배이다",
          ex: { zh: "这个城市的人口是那个的两倍。", pinyin: "zhège chéngshì de rénkǒu shì nàge de liǎng bèi", ko: "이 도시 인구는 저 도시의 두 배예요." },
          ex2: { zh: "今年的收入是去年的三倍。", pinyin: "jīnnián de shōurù shì qùnián de sān bèi", ko: "올해 수입은 작년의 세 배예요." },
        },
        {
          pattern: "A 比 B + 형용사 + 得多/一点儿",
          conn: "A + 比 + B + 형용사 + 得多 / 一点儿",
          ko: "A가 B보다 훨씬/조금 더 ~하다",
          ex: { zh: "这条路比那条近得多。", pinyin: "zhè tiáo lù bǐ nà tiáo jìn de duō", ko: "이 길이 저 길보다 훨씬 가까워요." },
          ex2: { zh: "今天比昨天暖和一点儿。", pinyin: "jīntiān bǐ zuótiān nuǎnhuo yìdiǎnr", ko: "오늘이 어제보다 조금 따뜻해요." },
          note: "차이 정도는 형용사 뒤 — 得多(훨씬), 一点儿(조금), 一些(다소)",
        },
        {
          pattern: "不如",
          conn: "A + 不如 + B + (형용사)",
          ko: "A는 B만 못하다",
          ex: { zh: "坐车不如走路快。", pinyin: "zuòchē bùrú zǒulù kuài", ko: "차를 타는 것이 걷는 것만 못해요." },
          ex2: { zh: "今年的天气不如去年好。", pinyin: "jīnnián de tiānqì bùrú qùnián hǎo", ko: "올해 날씨는 작년만 못해요." },
          note: "A不如B는 '비교해서 A가 떨어진다' — 没有만큼이나 자주 쓰인다",
        },
        {
          pattern: "A 像 B 一样",
          conn: "A + 像 + B + 一样 + (형용사)",
          ko: "A는 B와 같이/마치 ~처럼 …하다",
          ex: { zh: "他像哥哥一样照顾我。", pinyin: "tā xiàng gēge yíyàng zhàogù wǒ", ko: "그는 형처럼 저를 돌봐 줘요." },
          ex2: { zh: "今天热得像夏天一样。", pinyin: "jīntiān rè de xiàng xiàtiān yíyàng", ko: "오늘은 여름처럼 더워요." },
          note: "像…一样은 '~처럼·~와 같이'의 비유 — 跟…一样(똑같다)과 어감이 다르다",
        },
      ],
    },
    {
      name: "시간·동작 상태",
      items: [
        {
          pattern: "V + 着",
          conn: "동사 + 着 — 동작·상태의 지속",
          ko: "~하고 있다, ~한 채로 있다",
          ex: { zh: "门开着，你进来吧。", pinyin: "mén kāizhe, nǐ jìnlái ba", ko: "문이 열려 있으니 들어오세요." },
          ex2: { zh: "他笑着对我说。", pinyin: "tā xiàozhe duì wǒ shuō", ko: "그는 웃으면서 저에게 말했어요." },
          note: "着는 상태의 지속 — V着 V 형태로 '~하면서 …하다'(부수 동작)도 된다",
        },
        {
          pattern: "一边…，一边…",
          conn: "주어 + 一边 + V1，一边 + V2",
          ko: "~하면서 …하다 (동시 동작)",
          ex: { zh: "他一边吃饭，一边看电视。", pinyin: "tā yìbiān chīfàn, yìbiān kàn diànshì", ko: "그는 밥을 먹으면서 텔레비전을 봐요." },
          ex2: { zh: "我们一边走，一边聊天。", pinyin: "wǒmen yìbiān zǒu, yìbiān liáotiān", ko: "우리는 걸으면서 이야기를 나눠요." },
        },
        {
          pattern: "一…就…",
          conn: "주어 + 一 + V1，(주어) + 就 + V2",
          ko: "~하자마자 …하다",
          ex: { zh: "他一回家就睡觉了。", pinyin: "tā yì huíjiā jiù shuìjiào le", ko: "그는 집에 오자마자 잤어요." },
          ex2: { zh: "我一看就明白了。", pinyin: "wǒ yí kàn jiù míngbai le", ko: "저는 보자마자 이해했어요." },
          note: "一…就…는 '~하자마자' 또는 '~하기만 하면 늘'(습관) 두 뜻",
        },
        {
          pattern: "V + 了 + 수량 + 了",
          conn: "동사 + 了 + 기간 + (목적어) + 了",
          ko: "~한 지 (얼마)가 되었다 (지금도 계속)",
          ex: { zh: "我学汉语学了三年了。", pinyin: "wǒ xué hànyǔ xué le sān nián le", ko: "저는 중국어를 배운 지 3년이 되었어요." },
          ex2: { zh: "他在北京住了五年了。", pinyin: "tā zài běijīng zhù le wǔ nián le", ko: "그는 베이징에 산 지 5년이 되었어요." },
          note: "문장 끝의 了가 '지금까지도 계속'을 나타낸다 — 끝의 了를 빼면 이미 끝난 일",
        },
        {
          pattern: "先…，然后…，最后…",
          conn: "先 + V1，然后 + V2，最后 + V3",
          ko: "먼저 ~하고, 그다음에 …하고, 마지막에 ~하다",
          ex: { zh: "你先洗手，然后吃饭。", pinyin: "nǐ xiān xǐshǒu, ránhòu chīfàn", ko: "먼저 손을 씻고 그다음에 밥을 먹어요." },
          ex2: { zh: "我们先开会，最后一起吃饭。", pinyin: "wǒmen xiān kāihuì, zuìhòu yìqǐ chīfàn", ko: "우리는 먼저 회의를 하고 마지막에 같이 식사해요." },
        },
        {
          pattern: "正在 + V + 呢",
          conn: "주어 + 正在/在 + 동사 + 呢 (진행)",
          ko: "~하고 있는 중이다",
          ex: { zh: "他正在打电话呢。", pinyin: "tā zhèngzài dǎ diànhuà ne", ko: "그는 지금 전화하는 중이에요." },
          ex2: { zh: "我来的时候，他们在开会呢。", pinyin: "wǒ lái de shíhou, tāmen zài kāihuì ne", ko: "제가 왔을 때 그들은 회의 중이었어요." },
          note: "正在·在(진행) + 呢 — 셋 다 같이 쓰거나 일부만 써도 된다",
        },
        {
          pattern: "V + 着 V + 着，就…",
          conn: "동사 + 着 + 동사 + 着，就 + 변화",
          ko: "~하다 보니 …하게 되다",
          ex: { zh: "说着说着，他就哭了。", pinyin: "shuōzhe shuōzhe, tā jiù kū le", ko: "말하다 보니 그는 울어 버렸어요." },
          ex2: { zh: "走着走着，天就黑了。", pinyin: "zǒuzhe zǒuzhe, tiān jiù hēi le", ko: "걷다 보니 날이 어두워졌어요." },
          note: "V着V着는 '그 동작이 이어지던 중에 변화가 생김'을 나타낸다",
        },
        {
          pattern: "刚…，就…",
          conn: "주어 + 刚 + V1，就 + V2",
          ko: "막 ~했는데 곧 …하다",
          ex: { zh: "我刚到家，就下起雨来了。", pinyin: "wǒ gāng dào jiā, jiù xià qǐ yǔ lái le", ko: "막 집에 도착했는데 비가 내리기 시작했어요." },
          ex2: { zh: "他刚坐下，电话就响了。", pinyin: "tā gāng zuòxià, diànhuà jiù xiǎng le", ko: "그가 막 앉자마자 전화가 울렸어요." },
          note: "刚(막 ~한)은 시간보어 — 刚才(방금)와 구별. 刚…就…는 '~하자마자'",
        },
        {
          pattern: "V + 了 + 再 + V",
          conn: "동사1 + 了 + 再 + 동사2 (~하고 나서 …하다)",
          ko: "~한 다음에 …하다",
          ex: { zh: "你吃了饭再走吧。", pinyin: "nǐ chī le fàn zài zǒu ba", ko: "밥 먹고 나서 가요." },
          ex2: { zh: "想清楚了再做决定。", pinyin: "xiǎng qīngchu le zài zuò juédìng", ko: "잘 생각하고 나서 결정해요." },
          note: "V了再V는 '앞 동작을 끝낸 뒤에' — 미래·권유에서 자주 쓰인다",
        },
      ],
    },
    {
      name: "원인·결과·목적",
      items: [
        {
          pattern: "因为…，所以…",
          conn: "因为 + 원인，所以 + 결과",
          ko: "~하기 때문에, 그래서 …하다",
          ex: { zh: "因为堵车，所以我迟到了。", pinyin: "yīnwèi dǔchē, suǒyǐ wǒ chídào le", ko: "차가 막혀서 늦었어요." },
          ex2: { zh: "因为太累了，所以他早早睡了。", pinyin: "yīnwèi tài lèi le, suǒyǐ tā zǎozǎo shuì le", ko: "너무 피곤해서 그는 일찍 잤어요." },
          note: "因为…所以… 둘 다 쓰는 게 자연스럽다 — 하나만 써도 된다",
        },
        {
          pattern: "既然…，就…",
          conn: "既然 + 기정 사실，주어 + 就 + 결론",
          ko: "이미 ~한 이상, …하다",
          ex: { zh: "既然你来了，就一起吃饭吧。", pinyin: "jìrán nǐ lái le, jiù yìqǐ chīfàn ba", ko: "이미 왔으니 같이 밥 먹어요." },
          ex2: { zh: "既然决定了，就别后悔。", pinyin: "jìrán juédìng le, jiù bié hòuhuǐ", ko: "이미 결정했으니 후회하지 마세요." },
          note: "既然은 '이미 그러한 이상'(이미 알려진 사실)을 전제로 결론을 낸다 — 因为(객관적 원인)와 구별",
        },
        {
          pattern: "为了 + 목적",
          conn: "为了 + 목적，주어 + 동작",
          ko: "~을 위해서 …하다",
          ex: { zh: "为了考好成绩，他每天都复习。", pinyin: "wèile kǎo hǎo chéngjì, tā měi tiān dōu fùxí", ko: "좋은 성적을 위해 그는 매일 복습해요." },
          ex2: { zh: "为了健康，我开始锻炼了。", pinyin: "wèile jiànkāng, wǒ kāishǐ duànliàn le", ko: "건강을 위해 운동을 시작했어요." },
          note: "为了(목적, 앞)와 因为(원인)를 구별. 为了는 보통 문장 맨 앞",
        },
        {
          pattern: "由于…，因此…",
          conn: "由于 + 원인，因此/所以 + 결과",
          ko: "~로 인해, 따라서 …하다 (서면)",
          ex: { zh: "由于天气原因，航班取消了。", pinyin: "yóuyú tiānqì yuányīn, hángbān qǔxiāo le", ko: "날씨 때문에 항공편이 취소되었습니다." },
          ex2: { zh: "由于准备充分，比赛很顺利。", pinyin: "yóuyú zhǔnbèi chōngfèn, bǐsài hěn shùnlì", ko: "준비가 충분해서 경기가 순조로웠습니다." },
          note: "由于…因此…는 서면체 — 因为…所以…의 격식 버전",
        },
        {
          pattern: "之所以…，是因为…",
          conn: "주어 + 之所以 + 결과，是因为 + 원인",
          ko: "~한 까닭은 …하기 때문이다",
          ex: { zh: "他之所以成功，是因为很努力。", pinyin: "tā zhī suǒyǐ chénggōng, shì yīnwèi hěn nǔlì", ko: "그가 성공한 까닭은 열심히 했기 때문이에요." },
          ex2: { zh: "我之所以没去，是因为身体不舒服。", pinyin: "wǒ zhī suǒyǐ méi qù, shì yīnwèi shēntǐ bù shūfu", ko: "제가 안 간 까닭은 몸이 안 좋았기 때문이에요." },
          note: "결과를 먼저 말하고 원인을 뒤에 강조 — 因果를 뒤집는 구문",
        },
        {
          pattern: "为了不 + V",
          conn: "为了不 + 동사，주어 + 동작",
          ko: "~하지 않기 위해 …하다",
          ex: { zh: "为了不打扰别人，他小声说话。", pinyin: "wèile bù dǎrǎo biérén, tā xiǎoshēng shuōhuà", ko: "남을 방해하지 않으려고 그는 작은 소리로 말했어요." },
          ex2: { zh: "为了不迟到，我提前出门了。", pinyin: "wèile bù chídào, wǒ tíqián chūmén le", ko: "늦지 않으려고 저는 일찍 나섰어요." },
        },
        {
          pattern: "是…造成的・是…的结果",
          conn: "결과 + 是 + 원인 + 造成的 / 的结果",
          ko: "~은 …때문에 생긴 것이다",
          ex: { zh: "这次失败是粗心造成的。", pinyin: "zhè cì shībài shì cūxīn zàochéng de", ko: "이번 실패는 부주의 때문에 생긴 거예요." },
          ex2: { zh: "他的进步是努力的结果。", pinyin: "tā de jìnbù shì nǔlì de jiéguǒ", ko: "그의 발전은 노력의 결과예요." },
          note: "是…造成的 / 是…的结果 — 원인·결과를 是…的로 잇는 구문",
        },
      ],
    },
    {
      name: "어림·정도·범위",
      items: [
        {
          pattern: "差不多",
          conn: "差不多 + 수량/형용사 / 동사 + 得差不多了",
          ko: "거의, 대략",
          ex: { zh: "我们差不多到了。", pinyin: "wǒmen chàbuduō dào le", ko: "우리 거의 다 왔어요." },
          ex2: { zh: "这两个差不多一样大。", pinyin: "zhè liǎng ge chàbuduō yíyàng dà", ko: "이 둘은 거의 같은 크기예요." },
        },
        {
          pattern: "左右・大概・大约",
          conn: "수량 + 左右 / 大概·大约 + 수량",
          ko: "~쯤, 대략",
          ex: { zh: "他三十岁左右。", pinyin: "tā sānshí suì zuǒyòu", ko: "그는 서른 살쯤 돼요." },
          ex2: { zh: "从这儿到机场大概要一个小时。", pinyin: "cóng zhèr dào jīchǎng dàgài yào yí ge xiǎoshí", ko: "여기서 공항까지 대략 한 시간 걸려요." },
          note: "左右는 수량 뒤, 大概·大约는 수량 앞",
        },
        {
          pattern: "几乎",
          conn: "几乎 + 동사/형용사 (긍정·부정)",
          ko: "거의 (~할 뻔하다/~하지 않다)",
          ex: { zh: "我几乎每天都喝咖啡。", pinyin: "wǒ jīhū měi tiān dōu hē kāfēi", ko: "저는 거의 매일 커피를 마셔요." },
          ex2: { zh: "他激动得几乎说不出话来。", pinyin: "tā jīdòng de jīhū shuō bu chū huà lái", ko: "그는 감격해서 거의 말을 못 할 뻔했어요." },
        },
        {
          pattern: "至少・最多",
          conn: "至少/最多 + 수량",
          ko: "적어도 / 많아야",
          ex: { zh: "你至少要休息一天。", pinyin: "nǐ zhìshǎo yào xiūxi yì tiān", ko: "당신은 적어도 하루는 쉬어야 해요." },
          ex2: { zh: "这件事最多需要两个小时。", pinyin: "zhè jiàn shì zuìduō xūyào liǎng ge xiǎoshí", ko: "이 일은 많아야 두 시간 걸려요." },
        },
        {
          pattern: "对…来说",
          conn: "对 + 사람/대상 + 来说",
          ko: "~에게 있어서, ~로서는",
          ex: { zh: "对我来说，健康最重要。", pinyin: "duì wǒ lái shuō, jiànkāng zuì zhòngyào", ko: "저에게는 건강이 가장 중요해요." },
          ex2: { zh: "对学生来说，这个价格有点儿贵。", pinyin: "duì xuésheng lái shuō, zhège jiàgé yǒudiǎnr guì", ko: "학생에게는 이 가격이 좀 비싸요." },
        },
        {
          pattern: "差点儿 + V",
          conn: "差点儿(+没) + 동사",
          ko: "하마터면 ~할 뻔하다",
          ex: { zh: "我差点儿迟到了。", pinyin: "wǒ chàdiǎnr chídào le", ko: "저는 하마터면 늦을 뻔했어요." },
          ex2: { zh: "他差点儿没赶上火车。", pinyin: "tā chàdiǎnr méi gǎnshàng huǒchē", ko: "그는 하마터면 기차를 놓칠 뻔했어요." },
          note: "差点儿(안 바라던 일)은 没가 있어도 같은 뜻 — 差点儿没赶上 = 가까스로 탔다",
        },
        {
          pattern: "至于・关于",
          conn: "关于/至于 + 화제，+ 진술",
          ko: "~에 관해서 / ~으로 말하자면",
          ex: { zh: "关于这个问题，我们下次再讨论。", pinyin: "guānyú zhège wèntí, wǒmen xiàcì zài tǎolùn", ko: "이 문제에 관해서는 다음에 다시 논의해요." },
          ex2: { zh: "至于结果如何，现在还不清楚。", pinyin: "zhìyú jiéguǒ rúhé, xiànzài hái bù qīngchu", ko: "결과가 어떨지로 말하자면 아직 잘 몰라요." },
          note: "关于(~에 관하여, 화제 제시)·至于(~으로 말하자면, 화제 전환)",
        },
        {
          pattern: "比如・例如",
          conn: "比如/例如 + 예시 + 等",
          ko: "예를 들면",
          ex: { zh: "我喜欢运动，比如跑步、游泳。", pinyin: "wǒ xǐhuan yùndòng, bǐrú pǎobù, yóuyǒng", ko: "저는 운동을 좋아해요, 예를 들면 달리기, 수영이요." },
          ex2: { zh: "很多水果都很有营养，例如苹果。", pinyin: "hěn duō shuǐguǒ dōu hěn yǒu yíngyǎng, lìrú píngguǒ", ko: "많은 과일이 영양가가 높아요, 예를 들면 사과요." },
          note: "比如는 구어, 例如는 서면 — 끝에 等(등)을 붙이기도 한다",
        },
        {
          pattern: "尤其・特别是",
          conn: "주절，尤其/特别是 + 두드러진 예",
          ko: "특히, 그중에서도",
          ex: { zh: "我喜欢中国菜，尤其是川菜。", pinyin: "wǒ xǐhuan zhōngguó cài, yóuqí shì chuāncài", ko: "저는 중국 음식을 좋아하는데, 특히 쓰촨 요리를 좋아해요." },
          ex2: { zh: "这里风景很美，特别是秋天。", pinyin: "zhèlǐ fēngjǐng hěn měi, tèbié shì qiūtiān", ko: "여기는 경치가 아름다워요, 특히 가을에요." },
          note: "尤其·特别是는 '여럿 중에서도 유독' — 뒤에 是를 붙이는 경우가 많다",
        },
      ],
    },
    {
      name: "어기·태도",
      items: [
        {
          pattern: "V + 不了",
          conn: "동사 + 不了 (가능보어, ~할 수 없다)",
          ko: "~할 수 없다, 다 ~하지 못하다",
          ex: { zh: "今天的菜太多了，吃不了。", pinyin: "jīntiān de cài tài duō le, chī bu liǎo", ko: "오늘 음식이 너무 많아서 다 못 먹어요." },
          ex2: { zh: "下大雨，我们去不了了。", pinyin: "xià dàyǔ, wǒmen qù bu liǎo le", ko: "비가 많이 와서 우리 못 가게 됐어요." },
          note: "여기서 了는 liǎo로 읽는다 — 完了(le)와 발음·뜻이 다르다",
        },
        {
          pattern: "看起来・听起来",
          conn: "看/听/说 + 起来 + 형용사·평가",
          ko: "~해 보이다/들리다",
          ex: { zh: "这道菜看起来很好吃。", pinyin: "zhè dào cài kàn qǐlái hěn hǎochī", ko: "이 요리는 맛있어 보여요." },
          ex2: { zh: "这个办法听起来不错。", pinyin: "zhège bànfǎ tīng qǐlái búcuò", ko: "이 방법 괜찮게 들리네요." },
        },
        {
          pattern: "恐怕",
          conn: "恐怕 + 추측 (부정적·우려)",
          ko: "아마 ~일 것 같다 (걱정·우려)",
          ex: { zh: "恐怕今天来不及了。", pinyin: "kǒngpà jīntiān láibují le", ko: "아마 오늘은 시간이 안 될 것 같아요." },
          ex2: { zh: "他恐怕不会同意。", pinyin: "tā kǒngpà bú huì tóngyì", ko: "그는 아마 동의하지 않을 거예요." },
          note: "恐怕는 안 좋은 일에 대한 추측 — 단순 추측 也许·可能과 뉘앙스가 다르다",
        },
        {
          pattern: "幸亏・还好",
          conn: "幸亏/还好 + 다행스러운 사실",
          ko: "다행히, 그나마",
          ex: { zh: "幸亏我带了伞，要不然就淋湿了。", pinyin: "xìngkuī wǒ dài le sǎn, yàoburán jiù línshī le", ko: "다행히 우산을 가져와서 망정이지, 안 그랬으면 비 맞을 뻔했어요." },
          ex2: { zh: "还好你提醒我，我差点儿忘了。", pinyin: "háihǎo nǐ tíxǐng wǒ, wǒ chàdiǎnr wàng le", ko: "그나마 네가 알려 줘서 다행이지, 하마터면 잊을 뻔했어." },
        },
        {
          pattern: "难道…吗",
          conn: "难道 + 문장 + 吗 (반어)",
          ko: "설마 ~란 말인가",
          ex: { zh: "难道你不知道吗？", pinyin: "nándào nǐ bù zhīdào ma", ko: "설마 너 모르는 거야?" },
          ex2: { zh: "难道这就是答案吗？", pinyin: "nándào zhè jiùshì dá'àn ma", ko: "설마 이게 정답이란 말이야?" },
          note: "难道…吗는 반어 — 형식은 의문이지만 강한 단정·놀람을 나타낸다",
        },
        {
          pattern: "V + 来 V + 去",
          conn: "동사 + 来 + 동사 + 去 (반복)",
          ko: "이리저리 ~하다, ~하고 또 ~하다",
          ex: { zh: "他想来想去，还是决定不去了。", pinyin: "tā xiǎng lái xiǎng qù, háishi juédìng bú qù le", ko: "그는 이리저리 생각하다가 결국 안 가기로 했어요." },
          ex2: { zh: "我找来找去也没找到。", pinyin: "wǒ zhǎo lái zhǎo qù yě méi zhǎodào", ko: "이리저리 찾아봤지만 못 찾았어요." },
        },
        {
          pattern: "到底",
          conn: "到底 + 의문 (도대체) / 주어 + 到底 + 결과 (마침내)",
          ko: "①도대체 ②마침내, 결국",
          ex: { zh: "你到底想说什么？", pinyin: "nǐ dàodǐ xiǎng shuō shénme", ko: "너 도대체 무슨 말을 하려는 거야?" },
          ex2: { zh: "经过努力，他到底成功了。", pinyin: "jīngguò nǔlì, tā dàodǐ chénggōng le", ko: "노력 끝에 그는 마침내 성공했어요." },
          note: "의문문 속 到底는 '도대체', 평서문 속 到底는 '결국·마침내'",
        },
        {
          pattern: "尽量",
          conn: "주어 + 尽量 + 동사 (되도록)",
          ko: "되도록, 가능한 한 ~하다",
          ex: { zh: "请尽量早点儿来。", pinyin: "qǐng jǐnliàng zǎodiǎnr lái", ko: "되도록 일찍 와 주세요." },
          ex2: { zh: "我会尽量帮你的。", pinyin: "wǒ huì jǐnliàng bāng nǐ de", ko: "최대한 도와드릴게요." },
        },
        {
          pattern: "V + 起来",
          conn: "동사 + 起来 + 평가",
          ko: "막상 ~해 보니 (평가)",
          ex: { zh: "这件事说起来容易，做起来难。", pinyin: "zhè jiàn shì shuō qǐlái róngyì, zuò qǐlái nán", ko: "이 일은 말하기는 쉬워도 막상 하기는 어려워요." },
          ex2: { zh: "用起来很方便。", pinyin: "yòng qǐlái hěn fāngbiàn", ko: "써 보니 아주 편리해요." },
          note: "V起来는 '막상 ~해 보니'의 평가 — 看起来(보기에)와 함께 자주 쓰인다",
        },
        {
          pattern: "好像",
          conn: "주어 + 好像 + 술어 (+ 似的)",
          ko: "마치 ~인 것 같다",
          ex: { zh: "他好像生病了。", pinyin: "tā hǎoxiàng shēngbìng le", ko: "그는 아픈 것 같아요." },
          ex2: { zh: "天好像要下雨了。", pinyin: "tiān hǎoxiàng yào xiàyǔ le", ko: "비가 오려는 것 같아요." },
          note: "好像은 불확실한 추측·비유 — 끝에 似的를 붙이면 비유가 강해진다",
        },
        {
          pattern: "千万",
          conn: "千万 + 别/不要/要 + 동사 (당부)",
          ko: "부디, 절대 ~해라/하지 마라",
          ex: { zh: "你千万别迟到。", pinyin: "nǐ qiānwàn bié chídào", ko: "절대 늦지 마세요." },
          ex2: { zh: "过马路千万要小心。", pinyin: "guò mǎlù qiānwàn yào xiǎoxīn", ko: "길 건널 때 부디 조심하세요." },
          note: "千万은 간곡한 당부 — 别·要와 호응해 '절대·부디'를 강조",
        },
        {
          pattern: "竟然・居然",
          conn: "주어 + 竟然/居然 + 의외의 사실",
          ko: "뜻밖에도, 의외로 (놀람)",
          ex: { zh: "他竟然忘了今天的会议。", pinyin: "tā jìngrán wàng le jīntiān de huìyì", ko: "그가 뜻밖에도 오늘 회의를 잊어버렸어요." },
          ex2: { zh: "这么简单的题，他居然做错了。", pinyin: "zhème jiǎndān de tí, tā jūrán zuòcuò le", ko: "이렇게 쉬운 문제를 의외로 그가 틀렸어요." },
          note: "竟然·居然은 '예상 밖이라 놀랍다'는 어기 — 의외성 강조",
        },
        {
          pattern: "终于",
          conn: "주어 + 终于 + 결과 (오랜 끝에 마침내)",
          ko: "마침내, 드디어",
          ex: { zh: "等了很久，他终于来了。", pinyin: "děng le hěn jiǔ, tā zhōngyú lái le", ko: "한참 기다려서 그가 드디어 왔어요." },
          ex2: { zh: "经过努力，我终于通过了考试。", pinyin: "jīngguò nǔlì, wǒ zhōngyú tōngguò le kǎoshì", ko: "노력 끝에 저는 마침내 시험에 합격했어요." },
          note: "终于는 오랜 기다림·노력 끝의 결과 — 긍정적 결말에 주로 쓴다",
        },
      ],
    },
  ],
};
