/**
 * H4 문형 사전 — HSK 4급 핵심 구문·표현 전수 레이어 (SCHEMA.md 참고)
 * 챕터가 '이해'라면 이 사전은 '전수 검색'. 모든 예문에 병음 병기.
 */
export default {
  level: "H4",
  title: "4급 문형 사전",
  desc: "把구문·被수동·강조 是…的·연동/겸어부터 가정·양보·점층·비교 심화까지 — HSK 4급 핵심 문형 112개를 기능별 14개 테마로 전수 수록한 중급 문형 사전. 모든 예문에 병음 병기.",
  themes: [
    {
      name: "把구문 — 처치문",
      items: [
        {
          pattern: "把 + 목적어 + V + 기타성분",
          conn: "주어 + 把 + 명사 + 동사 + 결과/방향/了 등",
          ko: "~을 …하다 (목적어를 어떻게 처리했는지)",
          ex: { zh: "我把作业做完了。", pinyin: "wǒ bǎ zuòyè zuòwán le", ko: "저는 숙제를 다 했어요." },
          ex2: { zh: "请把窗户关上。", pinyin: "qǐng bǎ chuānghu guānshàng", ko: "창문 좀 닫아 주세요." },
          note: "把 뒤 동사는 단독으로 끝낼 수 없다 — 了·결과보어·방향보어 등 기타성분이 꼭 붙는다",
        },
        {
          pattern: "把 + 목적어 + V + 在/到/给",
          conn: "把 + 명사 + 동사 + 在/到/给 + 장소·대상",
          ko: "~을 …에 (놓다/보내다/주다)",
          ex: { zh: "他把书放在桌子上了。", pinyin: "tā bǎ shū fàngzài zhuōzi shàng le", ko: "그는 책을 책상 위에 놓았어요." },
          ex2: { zh: "请把这封信寄给他。", pinyin: "qǐng bǎ zhè fēng xìn jìgěi tā", ko: "이 편지를 그에게 부쳐 주세요." },
          note: "위치 이동·전달 결과를 분명히 할 때 把구문이 자연스럽다",
        },
        {
          pattern: "没把 + 목적어 + V",
          conn: "주어 + 没把 + 명사 + 동사 + 기타성분",
          ko: "~을 …하지 못했다/안 했다",
          ex: { zh: "我没把钥匙带来。", pinyin: "wǒ méi bǎ yàoshi dàilái", ko: "저는 열쇠를 안 가져왔어요." },
          ex2: { zh: "他没把这件事告诉我。", pinyin: "tā méi bǎ zhè jiàn shì gàosu wǒ", ko: "그는 이 일을 저에게 말하지 않았어요." },
          note: "把구문의 부정은 把 앞에 没(过거)·别(금지)·不要를 둔다 — 把 뒤가 아니다",
        },
        {
          pattern: "把 + 목적어 + V成/V作",
          conn: "把 + A + 동사 + 成 + B",
          ko: "A를 B로 (바꾸다/번역하다)",
          ex: { zh: "请把这句话翻译成中文。", pinyin: "qǐng bǎ zhè jù huà fānyì chéng zhōngwén", ko: "이 문장을 중국어로 번역해 주세요." },
          ex2: { zh: "她把卧室改成了书房。", pinyin: "tā bǎ wòshì gǎichéng le shūfáng", ko: "그녀는 침실을 서재로 바꿨어요." },
          note: "把…翻译成 / 把…改成 — '~로 바꾸다'는 把구문이 거의 필수",
        },
      ],
    },
    {
      name: "被·让·叫 — 피동",
      items: [
        {
          pattern: "被 + 행위자 + V",
          conn: "주어 + 被 (+ 행위자) + 동사 + 기타성분",
          ko: "~에게 …당하다/되다",
          ex: { zh: "我的自行车被偷了。", pinyin: "wǒ de zìxíngchē bèi tōu le", ko: "제 자전거를 도둑맞았어요." },
          ex2: { zh: "他被老板批评了一顿。", pinyin: "tā bèi lǎobǎn pīpíng le yí dùn", ko: "그는 사장에게 한바탕 혼났어요." },
          note: "행위자는 생략 가능 — 被偷了. 중국어 피동은 보통 안 좋은 일에 쓴다",
        },
        {
          pattern: "让/叫 + 행위자 + V",
          conn: "주어 + 让/叫 + 행위자 + 동사",
          ko: "~에게 …당하다 (구어 피동)",
          ex: { zh: "蛋糕让弟弟吃光了。", pinyin: "dàngāo ràng dìdi chīguāng le", ko: "케이크를 동생이 다 먹어 버렸어요." },
          ex2: { zh: "我的手机叫人拿走了。", pinyin: "wǒ de shǒujī jiào rén názǒu le", ko: "제 휴대폰을 누가 가져가 버렸어요." },
          note: "구어에서는 被보다 让·叫가 흔하다. 단 让·叫는 행위자를 생략할 수 없다",
        },
        {
          pattern: "被 + 행위자 + V + 得 + 보어",
          conn: "주어 + 被 + 행위자 + 동사 + 得 + 정도보어",
          ko: "~에게 …해져서 (어떤 상태가) 되다",
          ex: { zh: "他被这个问题难住了。", pinyin: "tā bèi zhège wèntí nánzhù le", ko: "그는 이 문제에 막혀 버렸어요." },
          ex2: { zh: "我被吓得说不出话来。", pinyin: "wǒ bèi xià de shuō bu chū huà lái", ko: "저는 놀라서 말이 안 나왔어요." },
        },
      ],
    },
    {
      name: "강조 是…的",
      items: [
        {
          pattern: "是 + 강조성분 + 的",
          conn: "주어 + 是 + 시간/장소/방식/대상 + 동사 + 的",
          ko: "~한 것이다 (이미 일어난 일의 시간·장소·방식 강조)",
          ex: { zh: "我是昨天到的。", pinyin: "wǒ shì zuótiān dào de", ko: "저는 어제 도착한 거예요." },
          ex2: { zh: "他是坐飞机来的。", pinyin: "tā shì zuò fēijī lái de", ko: "그는 비행기를 타고 온 거예요." },
          note: "이미 일어난 일에서 '언제·어디서·어떻게'를 강조 — 了가 아니라 是…的를 쓴다",
        },
        {
          pattern: "不是 + 강조성분 + 的",
          conn: "주어 + 不是 + 강조성분 + 동사 + 的",
          ko: "~한 게 아니다 (강조의 부정)",
          ex: { zh: "我不是故意的。", pinyin: "wǒ bú shì gùyì de", ko: "일부러 그런 게 아니에요." },
          ex2: { zh: "这件事不是我做的。", pinyin: "zhè jiàn shì bú shì wǒ zuò de", ko: "이 일은 제가 한 게 아니에요." },
          note: "是…的의 부정은 是를 不是로 — 不是…的 전체가 한 덩어리",
        },
        {
          pattern: "是 + 대상 + 的 (소속·소유)",
          conn: "명사 + 是 + 명사 + 的",
          ko: "~의 것이다",
          ex: { zh: "这本词典是图书馆的。", pinyin: "zhè běn cídiǎn shì túshūguǎn de", ko: "이 사전은 도서관 것이에요." },
          ex2: { zh: "这个主意是大家一起想的。", pinyin: "zhège zhǔyi shì dàjiā yìqǐ xiǎng de", ko: "이 아이디어는 다 같이 생각해 낸 거예요." },
        },
      ],
    },
    {
      name: "연동·겸어",
      items: [
        {
          pattern: "V1 + V2 (연동문)",
          conn: "주어 + 동사1 + (목적어) + 동사2 + (목적어)",
          ko: "~해서 …하다 (한 주어의 연속·목적 동작)",
          ex: { zh: "我去超市买东西。", pinyin: "wǒ qù chāoshì mǎi dōngxi", ko: "저는 마트에 물건 사러 가요." },
          ex2: { zh: "他坐地铁上班。", pinyin: "tā zuò dìtiě shàngbān", ko: "그는 지하철을 타고 출근해요." },
          note: "동작 순서대로 동사를 늘어놓는다 — 去买(가서 사다), 坐…上班(타고 출근하다)",
        },
        {
          pattern: "请/让/叫 + 사람 + V (겸어문)",
          conn: "동사1 + 사람 + 동사2 — 사람이 V1의 목적어이자 V2의 주어",
          ko: "~에게 …하게 하다/시키다/청하다",
          ex: { zh: "妈妈让我早点儿回家。", pinyin: "māma ràng wǒ zǎodiǎnr huíjiā", ko: "엄마가 저에게 일찍 집에 오라고 했어요." },
          ex2: { zh: "老师请同学们安静一下。", pinyin: "lǎoshī qǐng tóngxuémen ānjìng yíxià", ko: "선생님이 학생들에게 좀 조용히 해 달라고 했어요." },
          note: "让(시키다)·叫(시키다)·请(청하다)·使(~하게 만들다)가 대표 겸어 동사",
        },
        {
          pattern: "使 + 사람 + 형용사/동사",
          conn: "주어 + 使 + 대상 + 변화·심리",
          ko: "~로 하여금 …하게 하다 (서면)",
          ex: { zh: "这个消息使大家很高兴。", pinyin: "zhège xiāoxi shǐ dàjiā hěn gāoxìng", ko: "이 소식은 모두를 기쁘게 했어요." },
          ex2: { zh: "运动使人健康。", pinyin: "yùndòng shǐ rén jiànkāng", ko: "운동은 사람을 건강하게 합니다." },
          note: "使는 让보다 서면적·추상적 — 사물·일이 사람에게 심리 변화를 일으킬 때",
        },
        {
          pattern: "有 + 명사 + V",
          conn: "有 + 명사 + 동사 (존재+묘사 겸어)",
          ko: "~할 …이 있다",
          ex: { zh: "有件事想跟你商量。", pinyin: "yǒu jiàn shì xiǎng gēn nǐ shāngliang", ko: "당신과 상의하고 싶은 일이 있어요." },
          ex2: { zh: "有很多人来参加这个活动。", pinyin: "yǒu hěn duō rén lái cānjiā zhège huódòng", ko: "많은 사람이 이 행사에 참가하러 왔어요." },
        },
      ],
    },
    {
      name: "결과·방향·가능 보어",
      items: [
        {
          pattern: "V + 完/好/到/懂 (결과보어)",
          conn: "동사 + 결과보어 + (了)",
          ko: "~해 내다/마치다 (동작의 결과)",
          ex: { zh: "我听懂了老师的话。", pinyin: "wǒ tīngdǒng le lǎoshī de huà", ko: "선생님의 말을 알아들었어요." },
          ex2: { zh: "作业还没写完。", pinyin: "zuòyè hái méi xiěwán", ko: "숙제를 아직 다 못 썼어요." },
          note: "부정은 没 — 听懂의 부정은 没听懂. 不은 거의 안 쓴다",
        },
        {
          pattern: "V + 上/下/出/起来 (방향보어)",
          conn: "동사 + 방향보어 — 동작의 방향·결과 의미 확장",
          ko: "~해 오르다/내리다/나오다 등",
          ex: { zh: "他站起来回答问题。", pinyin: "tā zhàn qǐlái huídá wèntí", ko: "그는 일어나서 질문에 답했어요." },
          ex2: { zh: "我想起来一件重要的事。", pinyin: "wǒ xiǎng qǐlái yí jiàn zhòngyào de shì", ko: "중요한 일이 하나 생각났어요." },
          note: "想起来(생각나다)·看出来(알아보다)처럼 방향보어가 비유적 뜻으로도 쓰인다",
        },
        {
          pattern: "V + 得/不 + 보어 (가능보어)",
          conn: "동사 + 得(가능)/不(불가능) + 결과·방향보어",
          ko: "~할 수 있다/없다 (능력·여건상)",
          ex: { zh: "这些菜我一个人吃不完。", pinyin: "zhèxiē cài wǒ yí ge rén chī bu wán", ko: "이 음식들은 저 혼자 다 못 먹어요." },
          ex2: { zh: "声音太小，我听不见。", pinyin: "shēngyīn tài xiǎo, wǒ tīng bu jiàn", ko: "소리가 너무 작아서 안 들려요." },
          note: "听不见(안 들린다)·看得见(보인다) — 能…보다 '여건상 가능/불가능'을 직접 표현. 가능보어는 把구문과 함께 못 쓴다",
        },
        {
          pattern: "V + 得 + 정도보어",
          conn: "동사 (+ 목적어 + 동사) + 得 + 형용사구",
          ko: "~하는 정도가 …하다 (정도·평가)",
          ex: { zh: "他汉语说得很流利。", pinyin: "tā hànyǔ shuō de hěn liúlì", ko: "그는 중국어를 아주 유창하게 해요." },
          ex2: { zh: "今天我起得太晚了。", pinyin: "jīntiān wǒ qǐ de tài wǎn le", ko: "오늘 저는 너무 늦게 일어났어요." },
          note: "목적어가 있으면 동사를 한 번 더 반복 — 说汉语 → 汉语说得很流利",
        },
      ],
    },
    {
      name: "가정·조건",
      items: [
        {
          pattern: "如果…(的话)，就…",
          conn: "如果 + 조건 (+ 的话)，주어 + 就 + 결과",
          ko: "만약 ~라면, …하다",
          ex: { zh: "如果明天下雨，我们就不去了。", pinyin: "rúguǒ míngtiān xiàyǔ, wǒmen jiù bú qù le", ko: "만약 내일 비가 오면 우리는 안 갈 거예요." },
          ex2: { zh: "如果你有问题的话，可以问我。", pinyin: "rúguǒ nǐ yǒu wèntí de huà, kěyǐ wèn wǒ", ko: "만약 질문이 있으면 저에게 물어보세요." },
          note: "如果…就… 짝꿍 — 끝에 的话를 붙이면 더 구어적. 要是…就…도 같은 뜻",
        },
        {
          pattern: "要是…，就…",
          conn: "要是 + 조건，주어 + 就 + 결과",
          ko: "~라면, …할 텐데 (구어)",
          ex: { zh: "要是我有时间，就去旅游。", pinyin: "yàoshi wǒ yǒu shíjiān, jiù qù lǚyóu", ko: "시간이 있으면 여행 갈 텐데요." },
          ex2: { zh: "要是早知道，我就不来了。", pinyin: "yàoshi zǎo zhīdào, wǒ jiù bù lái le", ko: "진작 알았으면 안 왔을 텐데." },
          note: "要是는 如果보다 구어적. 글말에서는 如果가 무난",
        },
        {
          pattern: "只要…，就…",
          conn: "只要 + 조건，주어 + 就 + 결과",
          ko: "~하기만 하면, …하다 (충분조건)",
          ex: { zh: "只要努力，就一定能成功。", pinyin: "zhǐyào nǔlì, jiù yídìng néng chénggōng", ko: "노력하기만 하면 반드시 성공할 수 있어요." },
          ex2: { zh: "只要你愿意，随时都可以来。", pinyin: "zhǐyào nǐ yuànyì, suíshí dōu kěyǐ lái", ko: "당신이 원하기만 하면 언제든 와도 돼요." },
          note: "只要…就(하나만 만족하면 충분)와 只有…才(그것만이 유일 조건)를 구별",
        },
        {
          pattern: "只有…，才…",
          conn: "只有 + 유일조건，주어 + 才 + 결과",
          ko: "~해야만, 비로소 …하다 (필요조건)",
          ex: { zh: "只有多练习，才能学好。", pinyin: "zhǐyǒu duō liànxí, cái néng xuéhǎo", ko: "많이 연습해야만 잘 배울 수 있어요." },
          ex2: { zh: "只有他才知道密码。", pinyin: "zhǐyǒu tā cái zhīdào mìmǎ", ko: "그 사람만이 비밀번호를 알아요." },
          note: "只有 뒤에는 就가 아니라 才 — '그것만이 유일한 조건'을 강조",
        },
        {
          pattern: "无论/不管…，都…",
          conn: "无论/不管 + 의문구·선택지，주어 + 都/也 + 결과",
          ko: "~하든 (상관없이), 다 …하다",
          ex: { zh: "无论多忙，他都坚持锻炼。", pinyin: "wúlùn duō máng, tā dōu jiānchí duànliàn", ko: "아무리 바빠도 그는 운동을 꾸준히 해요." },
          ex2: { zh: "不管你同不同意，我都要去。", pinyin: "bùguǎn nǐ tóng bu tóngyì, wǒ dōu yào qù", ko: "당신이 동의하든 말든 저는 갈 거예요." },
          note: "无论/不管 뒤에는 의문사·정반의문·선택지가 와야 한다. 不管은 구어, 无论은 글말",
        },
      ],
    },
    {
      name: "양보·전환",
      items: [
        {
          pattern: "虽然…，但是/可是…",
          conn: "虽然 + 사실，但是/可是 + 상반 결과",
          ko: "비록 ~지만, …하다",
          ex: { zh: "虽然天气很冷，但是他还去跑步。", pinyin: "suīrán tiānqì hěn lěng, dànshì tā hái qù pǎobù", ko: "날씨가 추운데도 그는 달리기를 하러 가요." },
          ex2: { zh: "这家店虽然小，可是东西很全。", pinyin: "zhè jiā diàn suīrán xiǎo, kěshì dōngxi hěn quán", ko: "이 가게는 작지만 물건은 다 갖춰져 있어요." },
          note: "虽然…但是… 둘 다 써야 자연스럽다 — 한국어처럼 '하지만'을 생략하지 않는다",
        },
        {
          pattern: "即使/就算…，也…",
          conn: "即使/就算 + 가정·극단，주어 + 也 + 결과",
          ko: "설령 ~하더라도, …하다",
          ex: { zh: "即使下大雨，比赛也不会取消。", pinyin: "jíshǐ xià dàyǔ, bǐsài yě bú huì qǔxiāo", ko: "설령 비가 많이 와도 경기는 취소되지 않을 거예요." },
          ex2: { zh: "就算再难，我也不会放弃。", pinyin: "jiùsuàn zài nán, wǒ yě bú huì fàngqì", ko: "아무리 어려워도 저는 포기하지 않을 거예요." },
          note: "即使는 아직 일어나지 않은 가정 — 虽然(이미 사실)과 구별. 就算은 구어",
        },
        {
          pattern: "其实",
          conn: "주어 + 其实 + 사실 (예상과 다른 진실)",
          ko: "사실은, 실은",
          ex: { zh: "看起来很难，其实很简单。", pinyin: "kàn qǐlái hěn nán, qíshí hěn jiǎndān", ko: "어려워 보이지만 사실은 아주 쉬워요." },
          ex2: { zh: "其实我也不太清楚。", pinyin: "qíshí wǒ yě bú tài qīngchu", ko: "사실 저도 잘 몰라요." },
        },
        {
          pattern: "不过",
          conn: "문장，不过 + 가벼운 전환",
          ko: "그런데, 다만",
          ex: { zh: "这件衣服很好看，不过有点儿贵。", pinyin: "zhè jiàn yīfu hěn hǎokàn, búguò yǒudiǎnr guì", ko: "이 옷은 예쁜데 다만 좀 비싸요." },
          ex2: { zh: "我想去，不过没时间。", pinyin: "wǒ xiǎng qù, búguò méi shíjiān", ko: "가고 싶은데 시간이 없어요." },
          note: "不过는 但是보다 가벼운 전환 — '그런데·다만'에 가깝다",
        },
      ],
    },
    {
      name: "점층·추가",
      items: [
        {
          pattern: "越来越 + 형용사",
          conn: "주어 + 越来越 + 형용사/동사",
          ko: "점점 더 ~해지다",
          ex: { zh: "天气越来越暖和了。", pinyin: "tiānqì yuè lái yuè nuǎnhuo le", ko: "날씨가 점점 따뜻해지고 있어요." },
          ex2: { zh: "他的汉语越来越好了。", pinyin: "tā de hànyǔ yuè lái yuè hǎo le", ko: "그의 중국어가 점점 좋아지고 있어요." },
          note: "끝에 了가 붙어 변화를 나타낸다",
        },
        {
          pattern: "越 A 越 B",
          conn: "주어 + 越 + 동사/형용사 + 越 + 형용사",
          ko: "~할수록 …하다",
          ex: { zh: "雨越下越大。", pinyin: "yǔ yuè xià yuè dà", ko: "비가 내릴수록 더 거세져요." },
          ex2: { zh: "这本书越看越有意思。", pinyin: "zhè běn shū yuè kàn yuè yǒu yìsi", ko: "이 책은 볼수록 재미있어요." },
          note: "越来越(절대적 변화)와 越A越B(상관 변화)를 구별",
        },
        {
          pattern: "不但…，而且…",
          conn: "不但 + A，而且 + 더 나아간 B",
          ko: "~할 뿐만 아니라, 게다가 …하다",
          ex: { zh: "他不但会说英语，而且会说法语。", pinyin: "tā búdàn huì shuō yīngyǔ, érqiě huì shuō fǎyǔ", ko: "그는 영어를 할 뿐만 아니라 프랑스어도 해요." },
          ex2: { zh: "这里不但风景美，而且空气好。", pinyin: "zhèlǐ búdàn fēngjǐng měi, érqiě kōngqì hǎo", ko: "여기는 경치가 아름다울 뿐 아니라 공기도 좋아요." },
          note: "不但…而且… 짝꿍. 주어가 같으면 不但은 주어 뒤, 다르면 주어 앞",
        },
        {
          pattern: "除了…以外，还/都…",
          conn: "除了 + A 以外，주어 + 还(추가)/都(예외) + B",
          ko: "~외에도 …하다 / ~을 빼고는 다 …하다",
          ex: { zh: "除了汉语以外，我还会说日语。", pinyin: "chúle hànyǔ yǐwài, wǒ hái huì shuō rìyǔ", ko: "중국어 외에 일본어도 할 수 있어요." },
          ex2: { zh: "除了他以外，大家都来了。", pinyin: "chúle tā yǐwài, dàjiā dōu lái le", ko: "그를 빼고는 다들 왔어요." },
          note: "뒤에 还/也면 '포함·추가', 都면 '예외' — 같은 除了가 정반대로 갈린다",
        },
        {
          pattern: "连…都/也…",
          conn: "连 + 극단적 예 + 都/也 + 술어",
          ko: "~조차도 …하다 (강조)",
          ex: { zh: "他连饭都不吃了。", pinyin: "tā lián fàn dōu bù chī le", ko: "그는 밥조차 안 먹어요." },
          ex2: { zh: "这么简单的问题，连孩子都会。", pinyin: "zhème jiǎndān de wèntí, lián háizi dōu huì", ko: "이렇게 쉬운 문제는 아이조차도 풀 수 있어요." },
          note: "连…都/也…는 '~조차도' — 극단적인 예를 들어 강조. 都·也를 꼭 동반",
        },
      ],
    },
    {
      name: "비교 심화",
      items: [
        {
          pattern: "A 比 B + 형용사 + 수량보어",
          conn: "A + 比 + B + 형용사 + 一点儿/多了/구체적 차이",
          ko: "A가 B보다 (얼마만큼) 더 ~하다",
          ex: { zh: "今天比昨天热多了。", pinyin: "jīntiān bǐ zuótiān rè duō le", ko: "오늘이 어제보다 훨씬 더워요." },
          ex2: { zh: "他比我大三岁。", pinyin: "tā bǐ wǒ dà sān suì", ko: "그는 저보다 세 살 많아요." },
          note: "차이를 형용사 뒤에 둔다 — 大三岁(세 살 많다), 热多了(훨씬 덥다). 很·非常은 못 쓴다",
        },
        {
          pattern: "A 比 B 更/还 + 형용사",
          conn: "A + 比 + B + 更/还 + 형용사",
          ko: "A가 B보다 더욱 ~하다",
          ex: { zh: "这个办法比那个更好。", pinyin: "zhège bànfǎ bǐ nàge gèng hǎo", ko: "이 방법이 저것보다 더 좋아요." },
          ex2: { zh: "他跑得比我还快。", pinyin: "tā pǎo de bǐ wǒ hái kuài", ko: "그는 저보다도 더 빨리 달려요." },
          note: "比 비교문 강조에는 更·还만 — 很·太·非常은 쓸 수 없다",
        },
        {
          pattern: "A 没有 B (那么) + 형용사",
          conn: "A + 没有 + B + (这么/那么) + 형용사",
          ko: "A는 B만큼 ~하지 않다",
          ex: { zh: "我没有他那么高。", pinyin: "wǒ méiyǒu tā nàme gāo", ko: "저는 그만큼 키가 크지 않아요." },
          ex2: { zh: "这家餐厅没有那家好吃。", pinyin: "zhè jiā cāntīng méiyǒu nà jiā hǎochī", ko: "이 식당은 저 식당만큼 맛있지 않아요." },
          note: "比의 부정은 不比가 아니라 보통 没有 — '~만큼 못하다'",
        },
        {
          pattern: "A 跟/和 B 一样",
          conn: "A + 跟/和 + B + 一样 + (형용사)",
          ko: "A는 B와 똑같다/마찬가지로 ~하다",
          ex: { zh: "我的手机跟你的一样。", pinyin: "wǒ de shǒujī gēn nǐ de yíyàng", ko: "제 휴대폰은 당신 것과 똑같아요." },
          ex2: { zh: "他的想法和我的一样。", pinyin: "tā de xiǎngfǎ hé wǒ de yíyàng", ko: "그의 생각은 제 생각과 같아요." },
          note: "부정은 不一样. 跟…一样 뒤에 형용사를 붙이면 '~만큼 …하다'",
        },
        {
          pattern: "A 是 B 的 + 수량 + 倍",
          conn: "A + 是 + B + 的 + 수 + 倍",
          ko: "A는 B의 ~배이다",
          ex: { zh: "这个城市的人口是那个的两倍。", pinyin: "zhège chéngshì de rénkǒu shì nàge de liǎng bèi", ko: "이 도시 인구는 저 도시의 두 배예요." },
          ex2: { zh: "今年的收入是去年的三倍。", pinyin: "jīnnián de shōurù shì qùnián de sān bèi", ko: "올해 수입은 작년의 세 배예요." },
        },
      ],
    },
    {
      name: "시간·동작 상태",
      items: [
        {
          pattern: "V + 着 (지속)",
          conn: "동사 + 着 — 동작·상태의 지속",
          ko: "~하고 있다, ~한 채로 있다",
          ex: { zh: "门开着，你进来吧。", pinyin: "mén kāizhe, nǐ jìnlái ba", ko: "문이 열려 있으니 들어오세요." },
          ex2: { zh: "他笑着对我说。", pinyin: "tā xiàozhe duì wǒ shuō", ko: "그는 웃으면서 저에게 말했어요." },
          note: "着는 상태의 지속 — V着 V 형태로 '~하면서 …하다'(부수 동작)도 된다",
        },
        {
          pattern: "一边…，一边…",
          conn: "주어 + 一边 + V1，一边 + V2",
          ko: "~하면서 …하다 (동시 동작)",
          ex: { zh: "他一边吃饭，一边看电视。", pinyin: "tā yìbiān chīfàn, yìbiān kàn diànshì", ko: "그는 밥을 먹으면서 텔레비전을 봐요." },
          ex2: { zh: "我们一边走，一边聊天。", pinyin: "wǒmen yìbiān zǒu, yìbiān liáotiān", ko: "우리는 걸으면서 이야기를 나눠요." },
        },
        {
          pattern: "一…就…",
          conn: "주어 + 一 + V1，(주어) + 就 + V2",
          ko: "~하자마자 …하다",
          ex: { zh: "他一回家就睡觉了。", pinyin: "tā yì huíjiā jiù shuìjiào le", ko: "그는 집에 오자마자 잤어요." },
          ex2: { zh: "我一看就明白了。", pinyin: "wǒ yí kàn jiù míngbai le", ko: "저는 보자마자 이해했어요." },
          note: "一…就…는 '~하자마자' 또는 '~하기만 하면 늘'(습관) 두 뜻",
        },
        {
          pattern: "V + 了 + 수량 + 了 (지속 진행)",
          conn: "동사 + 了 + 기간 + (목적어) + 了",
          ko: "~한 지 (얼마)가 되었다 (지금도 계속)",
          ex: { zh: "我学汉语学了三年了。", pinyin: "wǒ xué hànyǔ xué le sān nián le", ko: "저는 중국어를 배운 지 3년이 되었어요." },
          ex2: { zh: "他在北京住了五年了。", pinyin: "tā zài běijīng zhù le wǔ nián le", ko: "그는 베이징에 산 지 5년이 되었어요." },
          note: "문장 끝의 了가 '지금까지도 계속'을 나타낸다 — 끝의 了를 빼면 이미 끝난 일",
        },
        {
          pattern: "先…，然后…，最后…",
          conn: "先 + V1，然后 + V2，最后 + V3",
          ko: "먼저 ~하고, 그다음에 …하고, 마지막에 ~하다",
          ex: { zh: "你先洗手，然后吃饭。", pinyin: "nǐ xiān xǐshǒu, ránhòu chīfàn", ko: "먼저 손을 씻고 그다음에 밥을 먹어요." },
          ex2: { zh: "我们先开会，最后一起吃饭。", pinyin: "wǒmen xiān kāihuì, zuìhòu yìqǐ chīfàn", ko: "우리는 먼저 회의를 하고 마지막에 같이 식사해요." },
        },
      ],
    },
    {
      name: "원인·결과·목적",
      items: [
        {
          pattern: "因为…，所以…",
          conn: "因为 + 원인，所以 + 결과",
          ko: "~하기 때문에, 그래서 …하다",
          ex: { zh: "因为堵车，所以我迟到了。", pinyin: "yīnwèi dǔchē, suǒyǐ wǒ chídào le", ko: "차가 막혀서 늦었어요." },
          ex2: { zh: "因为太累了，所以他早早睡了。", pinyin: "yīnwèi tài lèi le, suǒyǐ tā zǎozǎo shuì le", ko: "너무 피곤해서 그는 일찍 잤어요." },
          note: "因为…所以… 둘 다 쓰는 게 자연스럽다 — 하나만 써도 된다",
        },
        {
          pattern: "既然…，就…",
          conn: "既然 + 기정 사실，주어 + 就 + 결론",
          ko: "이미 ~한 이상, …하다",
          ex: { zh: "既然你来了，就一起吃饭吧。", pinyin: "jìrán nǐ lái le, jiù yìqǐ chīfàn ba", ko: "이미 왔으니 같이 밥 먹어요." },
          ex2: { zh: "既然决定了，就别后悔。", pinyin: "jìrán juédìng le, jiù bié hòuhuǐ", ko: "이미 결정했으니 후회하지 마세요." },
          note: "既然은 '이미 그러한 이상'(이미 알려진 사실)을 전제로 결론을 낸다 — 因为(객관적 원인)와 구별",
        },
        {
          pattern: "为了 + 목적",
          conn: "为了 + 목적，주어 + 동작",
          ko: "~을 위해서 …하다",
          ex: { zh: "为了考好成绩，他每天都复习。", pinyin: "wèile kǎo hǎo chéngjì, tā měi tiān dōu fùxí", ko: "좋은 성적을 위해 그는 매일 복습해요." },
          ex2: { zh: "为了健康，我开始锻炼了。", pinyin: "wèile jiànkāng, wǒ kāishǐ duànliàn le", ko: "건강을 위해 운동을 시작했어요." },
          note: "为了(목적, 앞)와 因为(원인)를 구별. 为了는 보통 문장 맨 앞",
        },
        {
          pattern: "由于…，因此…",
          conn: "由于 + 원인，因此/所以 + 결과",
          ko: "~로 인해, 따라서 …하다 (서면)",
          ex: { zh: "由于天气原因，航班取消了。", pinyin: "yóuyú tiānqì yuányīn, hángbān qǔxiāo le", ko: "날씨 때문에 항공편이 취소되었습니다." },
          ex2: { zh: "由于准备充分，比赛很顺利。", pinyin: "yóuyú zhǔnbèi chōngfèn, bǐsài hěn shùnlì", ko: "준비가 충분해서 경기가 순조로웠습니다." },
          note: "由于…因此…는 서면체 — 因为…所以…의 격식 버전",
        },
        {
          pattern: "之所以…，是因为…",
          conn: "주어 + 之所以 + 결과，是因为 + 원인",
          ko: "~한 까닭은 …하기 때문이다",
          ex: { zh: "他之所以成功，是因为很努力。", pinyin: "tā zhī suǒyǐ chénggōng, shì yīnwèi hěn nǔlì", ko: "그가 성공한 까닭은 열심히 했기 때문이에요." },
          ex2: { zh: "我之所以没去，是因为身体不舒服。", pinyin: "wǒ zhī suǒyǐ méi qù, shì yīnwèi shēntǐ bù shūfu", ko: "제가 안 간 까닭은 몸이 안 좋았기 때문이에요." },
          note: "결과를 먼저 말하고 원인을 뒤에 강조 — 因果를 뒤집는 구문",
        },
      ],
    },
    {
      name: "어림·정도·범위",
      items: [
        {
          pattern: "差不多",
          conn: "差不多 + 수량/형용사 / 동사 + 得差不多了",
          ko: "거의, 대략",
          ex: { zh: "我们差不多到了。", pinyin: "wǒmen chàbuduō dào le", ko: "우리 거의 다 왔어요." },
          ex2: { zh: "这两个差不多一样大。", pinyin: "zhè liǎng ge chàbuduō yíyàng dà", ko: "이 둘은 거의 같은 크기예요." },
        },
        {
          pattern: "左右・大概・大约",
          conn: "수량 + 左右 / 大概·大约 + 수량",
          ko: "~쯤, 대략",
          ex: { zh: "他三十岁左右。", pinyin: "tā sānshí suì zuǒyòu", ko: "그는 서른 살쯤 돼요." },
          ex2: { zh: "从这儿到机场大概要一个小时。", pinyin: "cóng zhèr dào jīchǎng dàgài yào yí ge xiǎoshí", ko: "여기서 공항까지 대략 한 시간 걸려요." },
          note: "左右는 수량 뒤, 大概·大约는 수량 앞",
        },
        {
          pattern: "几乎",
          conn: "几乎 + 동사/형용사 (긍정·부정)",
          ko: "거의 (~할 뻔하다/~하지 않다)",
          ex: { zh: "我几乎每天都喝咖啡。", pinyin: "wǒ jīhū měi tiān dōu hē kāfēi", ko: "저는 거의 매일 커피를 마셔요." },
          ex2: { zh: "他激动得几乎说不出话来。", pinyin: "tā jīdòng de jīhū shuō bu chū huà lái", ko: "그는 감격해서 거의 말을 못 할 뻔했어요." },
        },
        {
          pattern: "至少・最多",
          conn: "至少/最多 + 수량",
          ko: "적어도 / 많아야",
          ex: { zh: "你至少要休息一天。", pinyin: "nǐ zhìshǎo yào xiūxi yì tiān", ko: "당신은 적어도 하루는 쉬어야 해요." },
          ex2: { zh: "这件事最多需要两个小时。", pinyin: "zhè jiàn shì zuìduō xūyào liǎng ge xiǎoshí", ko: "이 일은 많아야 두 시간 걸려요." },
        },
        {
          pattern: "对…来说",
          conn: "对 + 사람/대상 + 来说",
          ko: "~에게 있어서, ~로서는",
          ex: { zh: "对我来说，健康最重要。", pinyin: "duì wǒ lái shuō, jiànkāng zuì zhòngyào", ko: "저에게는 건강이 가장 중요해요." },
          ex2: { zh: "对学生来说，这个价格有点儿贵。", pinyin: "duì xuésheng lái shuō, zhège jiàgé yǒudiǎnr guì", ko: "학생에게는 이 가격이 좀 비싸요." },
        },
      ],
    },
    {
      name: "어기·태도",
      items: [
        {
          pattern: "V + 不了",
          conn: "동사 + 不了 (가능보어, ~할 수 없다)",
          ko: "~할 수 없다, 다 ~하지 못하다",
          ex: { zh: "今天的菜太多了，吃不了。", pinyin: "jīntiān de cài tài duō le, chī bu liǎo", ko: "오늘 음식이 너무 많아서 다 못 먹어요." },
          ex2: { zh: "下大雨，我们去不了了。", pinyin: "xià dàyǔ, wǒmen qù bu liǎo le", ko: "비가 많이 와서 우리 못 가게 됐어요." },
          note: "여기서 了는 liǎo로 읽는다 — 完了(le)와 발음·뜻이 다르다",
        },
        {
          pattern: "看起来・听起来",
          conn: "看/听/说 + 起来 + 형용사·평가",
          ko: "~해 보이다/들리다",
          ex: { zh: "这道菜看起来很好吃。", pinyin: "zhè dào cài kàn qǐlái hěn hǎochī", ko: "이 요리는 맛있어 보여요." },
          ex2: { zh: "这个办法听起来不错。", pinyin: "zhège bànfǎ tīng qǐlái búcuò", ko: "이 방법 괜찮게 들리네요." },
        },
        {
          pattern: "恐怕",
          conn: "恐怕 + 추측 (부정적·우려)",
          ko: "아마 ~일 것 같다 (걱정·우려)",
          ex: { zh: "恐怕今天来不及了。", pinyin: "kǒngpà jīntiān láibují le", ko: "아마 오늘은 시간이 안 될 것 같아요." },
          ex2: { zh: "他恐怕不会同意。", pinyin: "tā kǒngpà bú huì tóngyì", ko: "그는 아마 동의하지 않을 거예요." },
          note: "恐怕는 안 좋은 일에 대한 추측 — 단순 추측 也许·可能과 뉘앙스가 다르다",
        },
        {
          pattern: "幸亏・还好",
          conn: "幸亏/还好 + 다행스러운 사실",
          ko: "다행히, 그나마",
          ex: { zh: "幸亏我带了伞，要不然就淋湿了。", pinyin: "xìngkuī wǒ dài le sǎn, yàoburán jiù línshī le", ko: "다행히 우산을 가져와서 망정이지, 안 그랬으면 비 맞을 뻔했어요." },
          ex2: { zh: "还好你提醒我，我差点儿忘了。", pinyin: "háihǎo nǐ tíxǐng wǒ, wǒ chàdiǎnr wàng le", ko: "그나마 네가 알려 줘서 다행이지, 하마터면 잊을 뻔했어." },
        },
        {
          pattern: "难道…吗",
          conn: "难道 + 문장 + 吗 (반어)",
          ko: "설마 ~란 말인가",
          ex: { zh: "难道你不知道吗？", pinyin: "nándào nǐ bù zhīdào ma", ko: "설마 너 모르는 거야?" },
          ex2: { zh: "难道这就是答案吗？", pinyin: "nándào zhè jiùshì dá'àn ma", ko: "설마 이게 정답이란 말이야?" },
          note: "难道…吗는 반어 — 형식은 의문이지만 강한 단정·놀람을 나타낸다",
        },
        {
          pattern: "V + 来 V + 去",
          conn: "동사 + 来 + 동사 + 去 (반복)",
          ko: "이리저리 ~하다, ~하고 또 ~하다",
          ex: { zh: "他想来想去，还是决定不去了。", pinyin: "tā xiǎng lái xiǎng qù, háishi juédìng bú qù le", ko: "그는 이리저리 생각하다가 결국 안 가기로 했어요." },
          ex2: { zh: "我找来找去也没找到。", pinyin: "wǒ zhǎo lái zhǎo qù yě méi zhǎodào", ko: "이리저리 찾아봤지만 못 찾았어요." },
        },
      ],
    },
  ],
};
