/**
 * H5 문형 사전 — HSK 5급 핵심 구문·표현 전수 레이어 (SCHEMA.md 참고)
 * 챕터가 '이해'라면 이 사전은 '전수 검색'. 모든 예문에 병음 병기.
 */
export default {
  level: "H5",
  title: "5급 문형 사전",
  desc: "관련사 짝꿍·복문 심화부터 강조·도치·서면 연결·관용 격식 표현까지 — HSK 5급 핵심 문형 92개를 기능별 13개 테마로 전수 수록한 중상급 문형 사전. 구어·서면 레지스터를 구별해 모든 예문에 병음 병기.",
  themes: [
    {
      name: "조건·가정 심화",
      items: [
        {
          pattern: "万一…，就…",
          conn: "万一 + 만일의 사태，주어 + 就 + 대비",
          ko: "만일 ~하면, …하다 (낮은 확률·불상사 대비)",
          ex: { zh: "万一他不来，我们怎么办？", pinyin: "wànyī tā bù lái, wǒmen zěnme bàn", ko: "만일 그가 안 오면 우리 어떡하죠?" },
          ex2: { zh: "带上雨伞，万一下雨呢。", pinyin: "dàishàng yǔsǎn, wànyī xiàyǔ ne", ko: "혹시 비 올지 모르니 우산 챙겨." },
          note: "万一는 如果보다 확률이 낮고 부정적인 사태 — '만에 하나'에 가깝다",
        },
        {
          pattern: "哪怕…，也…",
          conn: "哪怕 + 극단적 가정，주어 + 也 + 결과",
          ko: "설령 ~하더라도, …하다 (구어 양보)",
          ex: { zh: "哪怕只有一点儿希望，我也要试试。", pinyin: "nǎpà zhǐyǒu yìdiǎnr xīwàng, wǒ yě yào shìshi", ko: "설령 희망이 조금밖에 없더라도 시도해 볼 거예요." },
          ex2: { zh: "哪怕走着去，我也要去。", pinyin: "nǎpà zǒuzhe qù, wǒ yě yào qù", ko: "걸어서라도 저는 갈 거예요." },
          note: "哪怕는 即使의 구어형 — 也와 짝을 이룬다",
        },
        {
          pattern: "除非…，否则/不然…",
          conn: "除非 + 유일조건，否则/不然 + 부정적 결과",
          ko: "~하지 않는 한, 그렇지 않으면 …하다",
          ex: { zh: "除非你亲自去，否则解决不了。", pinyin: "chúfēi nǐ qīnzì qù, fǒuzé jiějué bu liǎo", ko: "당신이 직접 가지 않는 한 해결할 수 없어요." },
          ex2: { zh: "除非下雨，我们一定去爬山。", pinyin: "chúfēi xiàyǔ, wǒmen yídìng qù páshān", ko: "비가 오지 않는 한 우리는 꼭 등산 갈 거예요." },
          note: "除非는 '오직 그 조건이라야' — 只有와 통하되, 否则·才와 자주 호응",
        },
        {
          pattern: "一旦…，就…",
          conn: "一旦 + 일이 일어나면，주어 + 就 + 결과",
          ko: "일단 ~하면, …하다",
          ex: { zh: "一旦做出决定，就不要轻易改变。", pinyin: "yídàn zuòchū juédìng, jiù bú yào qīngyì gǎibiàn", ko: "일단 결정을 내리면 쉽게 바꾸지 마세요." },
          ex2: { zh: "机会一旦失去，就很难再来。", pinyin: "jīhuì yídàn shīqù, jiù hěn nán zài lái", ko: "기회는 일단 놓치면 다시 오기 어려워요." },
          note: "一旦은 '일단 ~하기만 하면'의 가정 — 시간 一(곧)과 구별",
        },
      ],
    },
    {
      name: "양보·전환 심화",
      items: [
        {
          pattern: "尽管…，但/还是…",
          conn: "尽管 + 사실，但是/还是 + 상반 결과",
          ko: "비록 ~지만, 그래도 …하다 (서면 양보)",
          ex: { zh: "尽管困难重重，他还是坚持了下来。", pinyin: "jǐnguǎn kùnnan chóngchóng, tā háishi jiānchí le xiàlái", ko: "어려움이 거듭됐지만 그는 끝까지 버텼어요." },
          ex2: { zh: "尽管下着大雨，活动仍然照常进行。", pinyin: "jǐnguǎn xiàzhe dàyǔ, huódòng réngrán zhàocháng jìnxíng", ko: "큰비가 내렸지만 행사는 예정대로 진행됐어요." },
          note: "尽管은 虽然의 서면형 — 仍然·还是와 잘 어울린다",
        },
        {
          pattern: "反而",
          conn: "예상과 달리，주어 + 反而 + 상반 결과",
          ko: "오히려, 도리어",
          ex: { zh: "吃了药，病反而更重了。", pinyin: "chī le yào, bìng fǎn'ér gèng zhòng le", ko: "약을 먹었는데 병이 오히려 더 심해졌어요." },
          ex2: { zh: "他不但不感谢，反而怪起我来。", pinyin: "tā búdàn bù gǎnxiè, fǎn'ér guài qǐ wǒ lái", ko: "그는 고마워하기는커녕 오히려 저를 탓했어요." },
          note: "反而는 기대와 정반대 결과를 강조 — 不但不…反而…(은커녕 오히려) 짝꿍이 자주 쓰인다",
        },
        {
          pattern: "并 + 不/没",
          conn: "주어 + 并 + 不/没 + 술어",
          ko: "결코 ~하지 않다 (예상·통념의 반박)",
          ex: { zh: "事情并不像你想的那么简单。", pinyin: "shìqing bìng bú xiàng nǐ xiǎng de nàme jiǎndān", ko: "일은 결코 네가 생각하는 만큼 간단하지 않아." },
          ex2: { zh: "我并没有责怪你的意思。", pinyin: "wǒ bìng méiyǒu zéguài nǐ de yìsi", ko: "당신을 탓할 생각은 결코 없어요." },
          note: "并은 不·没 앞에서 '상대의 예상을 반박' — 단순 부정에 어기를 더한다",
        },
        {
          pattern: "却",
          conn: "주어 + 却 + 상반 결과",
          ko: "그런데도, 오히려 (전환 부사)",
          ex: { zh: "大家都同意了，他却反对。", pinyin: "dàjiā dōu tóngyì le, tā què fǎnduì", ko: "다들 동의했는데 그는 반대했어요." },
          ex2: { zh: "说起来容易，做起来却很难。", pinyin: "shuō qǐlái róngyì, zuò qǐlái què hěn nán", ko: "말하기는 쉬운데 막상 하기는 어려워요." },
          note: "却는 주어 뒤·동사 앞에 오는 전환 부사 — 문장 앞에 못 온다",
        },
      ],
    },
    {
      name: "강조·도치",
      items: [
        {
          pattern: "之所以…，是因为…",
          conn: "주어 + 之所以 + 결과，是因为 + 원인",
          ko: "~한 까닭은 …하기 때문이다",
          ex: { zh: "他之所以失败，是因为太骄傲了。", pinyin: "tā zhī suǒyǐ shībài, shì yīnwèi tài jiāo'ào le", ko: "그가 실패한 까닭은 너무 자만했기 때문이에요." },
          ex2: { zh: "我之所以告诉你，是希望你能理解。", pinyin: "wǒ zhī suǒyǐ gàosu nǐ, shì xīwàng nǐ néng lǐjiě", ko: "제가 말씀드리는 까닭은 이해해 주셨으면 해서예요." },
        },
        {
          pattern: "正是・就是",
          conn: "正是/就是 + 강조 대상",
          ko: "바로 ~이다",
          ex: { zh: "这正是我想说的。", pinyin: "zhè zhèng shì wǒ xiǎng shuō de", ko: "이게 바로 제가 하고 싶었던 말이에요." },
          ex2: { zh: "就是他帮了我的忙。", pinyin: "jiùshì tā bāng le wǒ de máng", ko: "바로 그가 저를 도와줬어요." },
          note: "正是는 서면적, 就是는 구어적인 '바로 ~이다'",
        },
        {
          pattern: "连…带…",
          conn: "连 + A + 带 + B (A와 B를 한꺼번에)",
          ko: "~까지 (해서), ~와 …를 통째로",
          ex: { zh: "他连说带笑地讲了一个故事。", pinyin: "tā lián shuō dài xiào de jiǎng le yí ge gùshi", ko: "그는 말하면서 웃으며 이야기를 하나 들려줬어요." },
          ex2: { zh: "连本带利一共还了五万。", pinyin: "lián běn dài lì yígòng huán le wǔ wàn", ko: "원금에 이자까지 합쳐 모두 5만을 갚았어요." },
          note: "连…带…는 두 동작·요소를 한 덩어리로 묶는 관용 — 连…都/也(조차도)와 다르다",
        },
        {
          pattern: "再…不过了",
          conn: "再 + 형용사 + 不过了",
          ko: "더할 나위 없이 ~하다",
          ex: { zh: "这个主意再好不过了。", pinyin: "zhège zhǔyi zài hǎo bú guò le", ko: "이 아이디어는 더할 나위 없이 좋아요." },
          ex2: { zh: "能见到你，我再高兴不过了。", pinyin: "néng jiàndào nǐ, wǒ zài gāoxìng bú guò le", ko: "당신을 만나서 더없이 기뻐요." },
          note: "再…不过了는 형용사의 최상급 강조 — '이보다 더 ~할 수 없다'",
        },
        {
          pattern: "A 是 A，但…",
          conn: "형용사1 + 是 + 형용사1，但 + 유보",
          ko: "~하긴 한데, 다만 …하다",
          ex: { zh: "贵是贵，但质量真的好。", pinyin: "guì shì guì, dàn zhìliàng zhēn de hǎo", ko: "비싸긴 비싼데 품질이 정말 좋아요." },
          ex2: { zh: "累是累，可是很开心。", pinyin: "lèi shì lèi, kěshì hěn kāixīn", ko: "피곤하긴 한데 즐거워요." },
          note: "형용사를 是로 반복해 일단 인정하고 뒤에 유보를 단다 — 구어에서 자주",
        },
      ],
    },
    {
      name: "범위·예외·포괄",
      items: [
        {
          pattern: "凡是…，都…",
          conn: "凡是 + 부류，주어 + 都 + 술어",
          ko: "무릇 ~한 것은 다 …하다",
          ex: { zh: "凡是来过的人都说好。", pinyin: "fánshì lái guo de rén dōu shuō hǎo", ko: "와 본 사람은 다들 좋다고 해요." },
          ex2: { zh: "凡是他答应的事，一定会做到。", pinyin: "fánshì tā dāying de shì, yídìng huì zuòdào", ko: "그가 약속한 일은 무엇이든 반드시 해내요." },
          note: "凡是는 '예외 없이 그 부류 전부' — 都와 호응. 서면적",
        },
        {
          pattern: "无论如何",
          conn: "无论如何 + 주어 + 都/也 + 술어",
          ko: "어떻게 해서든, 무슨 일이 있어도",
          ex: { zh: "无论如何我都要完成这个任务。", pinyin: "wúlùn rúhé wǒ dōu yào wánchéng zhège rènwù", ko: "무슨 일이 있어도 이 임무를 완수하겠어요." },
          ex2: { zh: "无论如何也要试一次。", pinyin: "wúlùn rúhé yě yào shì yí cì", ko: "어떻게 해서든 한 번은 해 봐야 해요." },
        },
        {
          pattern: "除了…，其余/其他…",
          conn: "除了 + A 以外，其余/其他 + 나머지",
          ko: "~을 제외한 나머지는 …하다",
          ex: { zh: "除了周末，其他时间他都在公司。", pinyin: "chúle zhōumò, qítā shíjiān tā dōu zài gōngsī", ko: "주말을 빼고는 그는 늘 회사에 있어요." },
          ex2: { zh: "除了这一点，其余都没问题。", pinyin: "chúle zhè yìdiǎn, qíyú dōu méi wèntí", ko: "이 점만 빼면 나머지는 다 문제없어요." },
        },
        {
          pattern: "以…为…",
          conn: "以 + A + 为 + B (A를 B로 삼다/하다)",
          ko: "~을 …으로 삼다/하다 (서면)",
          ex: { zh: "我们应该以诚信为本。", pinyin: "wǒmen yīnggāi yǐ chéngxìn wéi běn", ko: "우리는 신의를 근본으로 삼아야 해요." },
          ex2: { zh: "这家公司以质量为重。", pinyin: "zhè jiā gōngsī yǐ zhìliàng wéi zhòng", ko: "이 회사는 품질을 중시해요." },
          note: "以…为…는 격식 서면 구문 — 以…为主(주로 하다)·以…为例(예로 들다)로 자주 활용",
        },
      ],
    },
    {
      name: "관련사 — 점층·선택",
      items: [
        {
          pattern: "不仅…，而且/还…",
          conn: "不仅 + A，而且/还 + 더 나아간 B",
          ko: "~할 뿐만 아니라, 게다가 …하다 (서면)",
          ex: { zh: "他不仅成绩好，而且很有礼貌。", pinyin: "tā bùjǐn chéngjì hǎo, érqiě hěn yǒu lǐmào", ko: "그는 성적이 좋을 뿐만 아니라 예의도 발라요." },
          ex2: { zh: "这本书不仅内容丰富，还很实用。", pinyin: "zhè běn shū bùjǐn nèiróng fēngfù, hái hěn shíyòng", ko: "이 책은 내용이 풍부할 뿐 아니라 실용적이에요." },
          note: "不仅은 不但의 서면형 — 而且·还·也와 짝을 이룬다",
        },
        {
          pattern: "甚至",
          conn: "주어 + 甚至 + 극단적 예",
          ko: "심지어, ~까지도",
          ex: { zh: "他忙得甚至忘了吃饭。", pinyin: "tā máng de shènzhì wàng le chīfàn", ko: "그는 바빠서 심지어 밥 먹는 것도 잊었어요." },
          ex2: { zh: "很多人，甚至连专家都不知道。", pinyin: "hěn duō rén, shènzhì lián zhuānjiā dōu bù zhīdào", ko: "많은 사람, 심지어 전문가조차도 몰라요." },
          note: "甚至는 점층의 마지막 극단을 끌어온다 — 连…都와 자주 결합",
        },
        {
          pattern: "与其…，不如…",
          conn: "与其 + A，不如 + 더 나은 B",
          ko: "~하느니 차라리 …하는 게 낫다",
          ex: { zh: "与其等他，不如我们自己去。", pinyin: "yǔqí děng tā, bùrú wǒmen zìjǐ qù", ko: "그를 기다리느니 우리가 직접 가는 게 나아요." },
          ex2: { zh: "与其抱怨，不如想办法解决。", pinyin: "yǔqí bàoyuàn, bùrú xiǎng bànfǎ jiějué", ko: "불평하느니 해결 방법을 찾는 게 나아요." },
          note: "与其…不如…는 두 선택지를 비교해 후자를 택하는 구문",
        },
        {
          pattern: "宁可…，也…",
          conn: "宁可 + 감수하는 선택，也 + 양보 / 也不 + 거부",
          ko: "차라리 ~할지언정, …하다/하지 않다",
          ex: { zh: "他宁可自己吃亏，也不让别人为难。", pinyin: "tā nìngkě zìjǐ chīkuī, yě bú ràng biérén wéinán", ko: "그는 차라리 자기가 손해를 볼지언정 남을 곤란하게 하지 않아요." },
          ex2: { zh: "我宁可走路，也不坐他的车。", pinyin: "wǒ nìngkě zǒulù, yě bú zuò tā de chē", ko: "차라리 걸을지언정 그의 차는 안 타겠어요." },
          note: "宁可…也不…는 '한쪽을 감수하더라도 다른 쪽은 거부' — 강한 의지",
        },
        {
          pattern: "要么…，要么…",
          conn: "要么 + A，要么 + B (양자택일)",
          ko: "~하든가, 아니면 …하든가",
          ex: { zh: "要么你来，要么我去。", pinyin: "yàome nǐ lái, yàome wǒ qù", ko: "네가 오든가 내가 가든가 하자." },
          ex2: { zh: "周末要么爬山，要么游泳。", pinyin: "zhōumò yàome páshān, yàome yóuyǒng", ko: "주말에 등산을 하든가 수영을 하든가 해요." },
          note: "要么…要么…는 둘 중 하나를 고르는 구어 선택 구문",
        },
      ],
    },
    {
      name: "정도·결과 보어 심화",
      items: [
        {
          pattern: "形 + 得 + 결과절",
          conn: "형용사/동사 + 得 + 정도가 어떠한지 묘사하는 절",
          ko: "~해서 (그 결과) …할 정도다",
          ex: { zh: "他高兴得跳了起来。", pinyin: "tā gāoxìng de tiào le qǐlái", ko: "그는 기뻐서 펄쩍 뛰었어요." },
          ex2: { zh: "我累得连话都不想说。", pinyin: "wǒ lèi de lián huà dōu bù xiǎng shuō", ko: "저는 너무 피곤해서 말조차 하기 싫었어요." },
          note: "得 뒤에 절이 와서 정도가 어느 정도인지 구체적으로 보여 준다",
        },
        {
          pattern: "V + 个 + 보어",
          conn: "동사 + 个 + 형용사/명사 (실컷·시원하게)",
          ko: "실컷 ~하다, ~을 …하게",
          ex: { zh: "今天我们玩个痛快。", pinyin: "jīntiān wǒmen wán ge tòngkuài", ko: "오늘 우리 신나게 놀자." },
          ex2: { zh: "雨下个不停。", pinyin: "yǔ xià ge bù tíng", ko: "비가 그치지 않고 계속 내려요." },
          note: "동사 + 个는 구어에서 '시원하게·끊임없이'의 어감을 더한다",
        },
        {
          pattern: "好/难 + V",
          conn: "好/难 + 동사 (쉽게/어렵게 ~하다)",
          ko: "~하기 좋다/어렵다",
          ex: { zh: "这种字很好记。", pinyin: "zhè zhǒng zì hěn hǎo jì", ko: "이런 글자는 외우기 쉬워요." },
          ex2: { zh: "这个问题很难回答。", pinyin: "zhège wèntí hěn nán huídá", ko: "이 질문은 대답하기 어려워요." },
          note: "好+동사(쉽다)·难+동사(어렵다) — 好吃·好看처럼 굳어진 표현도 많다",
        },
        {
          pattern: "V + 来 V + 去",
          conn: "동사 + 来 + 동사 + 去 (반복·번복)",
          ko: "이리저리·여러 번 ~하다",
          ex: { zh: "他们讨论来讨论去也没有结果。", pinyin: "tāmen tǎolùn lái tǎolùn qù yě méiyǒu jiéguǒ", ko: "그들은 이리저리 토론했지만 결론이 안 났어요." },
          ex2: { zh: "这件事说来话长。", pinyin: "zhè jiàn shì shuō lái huà cháng", ko: "이 일은 말하자면 길어요." },
        },
      ],
    },
    {
      name: "시간·순서 서면",
      items: [
        {
          pattern: "随着…",
          conn: "随着 + 변화·발전，주어 + 결과",
          ko: "~함에 따라, ~에 따라",
          ex: { zh: "随着年龄的增长，他变得更成熟了。", pinyin: "suízhe niánlíng de zēngzhǎng, tā biàn de gèng chéngshú le", ko: "나이가 들면서 그는 더 성숙해졌어요." },
          ex2: { zh: "随着科技的发展，生活越来越方便。", pinyin: "suízhe kējì de fāzhǎn, shēnghuó yuè lái yuè fāngbiàn", ko: "기술이 발전함에 따라 생활이 점점 편리해져요." },
          note: "随着는 서면체 — 뒤에 명사구가 오고, 동반·인과적 변화를 나타낸다",
        },
        {
          pattern: "在…的过程中",
          conn: "在 + 동작/사건 + 的过程中",
          ko: "~하는 과정에서",
          ex: { zh: "在学习的过程中，遇到困难是正常的。", pinyin: "zài xuéxí de guòchéng zhōng, yùdào kùnnan shì zhèngcháng de", ko: "공부하는 과정에서 어려움을 만나는 건 정상이에요." },
          ex2: { zh: "在交流的过程中，我们成了朋友。", pinyin: "zài jiāoliú de guòchéng zhōng, wǒmen chéng le péngyou", ko: "교류하는 과정에서 우리는 친구가 됐어요." },
        },
        {
          pattern: "从…起・自…以来",
          conn: "从 + 기점 + 起 / 自(从) + 시점 + 以来",
          ko: "~부터 / ~이래로",
          ex: { zh: "从今天起，我要早睡早起。", pinyin: "cóng jīntiān qǐ, wǒ yào zǎo shuì zǎo qǐ", ko: "오늘부터 저는 일찍 자고 일찍 일어날 거예요." },
          ex2: { zh: "自从开学以来，他每天都很忙。", pinyin: "zìcóng kāixué yǐlái, tā měi tiān dōu hěn máng", ko: "개학한 이래로 그는 매일 바빠요." },
          note: "自…以来는 서면적, 从…起는 구어·서면 모두 — '~부터 지금까지'",
        },
        {
          pattern: "一…，便…",
          conn: "주어 + 一 + V1，便 + V2 (서면)",
          ko: "~하자마자 곧 …하다 (서면)",
          ex: { zh: "他一听便明白了。", pinyin: "tā yì tīng biàn míngbai le", ko: "그는 듣자마자 곧 이해했어요." },
          ex2: { zh: "天一亮，他便出发了。", pinyin: "tiān yí liàng, tā biàn chūfā le", ko: "날이 밝자마자 그는 곧 출발했어요." },
          note: "便은 就의 서면형 — 一…便…은 一…就…의 문어체",
        },
      ],
    },
    {
      name: "추측·판단·전언",
      items: [
        {
          pattern: "看来・看样子",
          conn: "看来/看样子 + 판단",
          ko: "보아하니, ~인 것 같다",
          ex: { zh: "看来今天会下雨。", pinyin: "kànlái jīntiān huì xiàyǔ", ko: "보아하니 오늘 비가 올 것 같아요." },
          ex2: { zh: "看样子他不太愿意。", pinyin: "kàn yàngzi tā bú tài yuànyì", ko: "보아하니 그는 별로 내키지 않는 것 같아요." },
        },
        {
          pattern: "据说・据…说",
          conn: "据说 / 据 + 출처 + 说，+ 전언 내용",
          ko: "~라고 한다, ~에 따르면",
          ex: { zh: "据说那家餐厅很有名。", pinyin: "jùshuō nà jiā cāntīng hěn yǒumíng", ko: "그 식당이 유명하다고 해요." },
          ex2: { zh: "据天气预报说，明天会变冷。", pinyin: "jù tiānqì yùbào shuō, míngtiān huì biàn lěng", ko: "일기 예보에 따르면 내일 추워진대요." },
          note: "据说(소문·전언)와 据…说(출처 명시) — 서면·뉴스체에서 흔하다",
        },
        {
          pattern: "难免",
          conn: "주어 + 难免 + (会) + 일",
          ko: "~하기 마련이다, ~을 면하기 어렵다",
          ex: { zh: "工作中难免会出错。", pinyin: "gōngzuò zhōng nánmiǎn huì chūcuò", ko: "일하다 보면 실수하기 마련이에요." },
          ex2: { zh: "刚开始难免有些紧张。", pinyin: "gāng kāishǐ nánmiǎn yǒuxiē jǐnzhāng", ko: "처음엔 다소 긴장하기 마련이죠." },
        },
        {
          pattern: "怪不得・原来",
          conn: "怪不得 + 결과，原来 + 알게 된 원인",
          ko: "어쩐지, 알고 보니",
          ex: { zh: "怪不得他没来，原来病了。", pinyin: "guàibude tā méi lái, yuánlái bìng le", ko: "어쩐지 그가 안 오더라니, 알고 보니 아팠군요." },
          ex2: { zh: "原来是这样，我终于明白了。", pinyin: "yuánlái shì zhèyàng, wǒ zhōngyú míngbai le", ko: "알고 보니 그랬군요, 드디어 이해했어요." },
          note: "怪不得(어쩐지)와 原来(알고 보니)는 '뜻밖의 진상을 깨달음'을 함께 표현",
        },
      ],
    },
    {
      name: "관용 격식 표현",
      items: [
        {
          pattern: "不得不",
          conn: "주어 + 不得不 + 동사",
          ko: "~하지 않을 수 없다, 어쩔 수 없이 ~하다",
          ex: { zh: "因为下雨，我们不得不取消了活动。", pinyin: "yīnwèi xiàyǔ, wǒmen bùdébù qǔxiāo le huódòng", ko: "비가 와서 우리는 어쩔 수 없이 행사를 취소했어요." },
          ex2: { zh: "为了生活，他不得不打两份工。", pinyin: "wèile shēnghuó, tā bùdébù dǎ liǎng fèn gōng", ko: "먹고살기 위해 그는 어쩔 수 없이 일을 두 개 해요." },
          note: "不得不는 이중부정으로 '~할 수밖에 없다'를 강조",
        },
        {
          pattern: "舍不得",
          conn: "주어 + 舍不得 + 동사/명사",
          ko: "차마 ~하지 못하다, 아까워하다",
          ex: { zh: "她舍不得离开家乡。", pinyin: "tā shěbude líkāi jiāxiāng", ko: "그녀는 차마 고향을 떠나지 못해요." },
          ex2: { zh: "这件衣服我舍不得扔。", pinyin: "zhè jiàn yīfu wǒ shěbude rēng", ko: "이 옷은 아까워서 못 버리겠어요." },
          note: "舍得(기꺼이 ~하다)의 부정 — '아까워서/정이 들어서 못 하다'",
        },
        {
          pattern: "恨不得",
          conn: "恨不得 + 실현 불가능한 강한 바람",
          ko: "당장이라도 ~하고 싶다 (간절함)",
          ex: { zh: "听到这个消息，我恨不得马上飞回去。", pinyin: "tīngdào zhège xiāoxi, wǒ hènbude mǎshàng fēi huíqù", ko: "이 소식을 듣고 당장이라도 날아가고 싶었어요." },
          ex2: { zh: "他恨不得一天就把书读完。", pinyin: "tā hènbude yì tiān jiù bǎ shū dúwán", ko: "그는 하루 만에 책을 다 읽어 버리고 싶을 정도예요." },
          note: "恨不得는 현실적으로 불가능한 일을 간절히 바람 — 巴不得(실현 가능한 강한 바람)와 구별",
        },
        {
          pattern: "免得・以免",
          conn: "주절，免得/以免 + 피하고 싶은 일",
          ko: "~하지 않도록, ~을 면하기 위해",
          ex: { zh: "早点儿出发，免得迟到。", pinyin: "zǎodiǎnr chūfā, miǎnde chídào", ko: "늦지 않도록 좀 일찍 출발해요." },
          ex2: { zh: "请提前通知，以免造成误会。", pinyin: "qǐng tíqián tōngzhī, yǐmiǎn zàochéng wùhuì", ko: "오해가 생기지 않도록 미리 알려 주세요." },
          note: "免得는 구어, 以免은 서면 — 둘 다 '~하는 걸 피하기 위해'",
        },
        {
          pattern: "省得",
          conn: "주절，省得 + 덜고 싶은 수고·번거로움",
          ko: "~하는 수고를 덜도록, ~하지 않게",
          ex: { zh: "我帮你带过来，省得你跑一趟。", pinyin: "wǒ bāng nǐ dài guòlái, shěngde nǐ pǎo yí tàng", ko: "제가 가져다드릴게요, 한 번 오시는 수고 덜게요." },
          ex2: { zh: "把地址写下来，省得忘了。", pinyin: "bǎ dìzhǐ xiě xiàlái, shěngde wàng le", ko: "주소를 적어 둬요, 잊지 않게요." },
          note: "省得는 免得와 비슷하나 '수고·번거로움을 덜다'에 초점 — 구어",
        },
        {
          pattern: "巴不得",
          conn: "주어 + 巴不得 + 간절히 바라는 일",
          ko: "~하기를 간절히 바라다, ~하면 더없이 좋다",
          ex: { zh: "他巴不得马上放假。", pinyin: "tā bābude mǎshàng fàngjià", ko: "그는 당장 방학하기를 간절히 바라요." },
          ex2: { zh: "我巴不得你能留下来。", pinyin: "wǒ bābude nǐ néng liú xiàlái", ko: "당신이 남아 줬으면 정말 좋겠어요." },
          note: "巴不得는 실현 가능한 강한 바람 — 恨不得(불가능한 바람)와 구별",
        },
      ],
    },
    {
      name: "동작·처치 심화",
      items: [
        {
          pattern: "把…当作/看成",
          conn: "把 + A + 当作/看成 + B",
          ko: "A를 B로 여기다/간주하다",
          ex: { zh: "他把我当作自己的家人。", pinyin: "tā bǎ wǒ dàngzuò zìjǐ de jiārén", ko: "그는 저를 자기 가족처럼 여겨요." },
          ex2: { zh: "别把困难看成是坏事。", pinyin: "bié bǎ kùnnan kànchéng shì huàishì", ko: "어려움을 나쁜 일로만 보지 마세요." },
        },
        {
          pattern: "对…负责・对…感兴趣",
          conn: "对 + 대상 + 동사·형용사 (관련 대상 표시)",
          ko: "~에 대해 …하다",
          ex: { zh: "每个人都要对自己的决定负责。", pinyin: "měi ge rén dōu yào duì zìjǐ de juédìng fùzé", ko: "누구나 자기 결정에 책임을 져야 해요." },
          ex2: { zh: "我对中国文化很感兴趣。", pinyin: "wǒ duì zhōngguó wénhuà hěn gǎn xìngqù", ko: "저는 중국 문화에 관심이 많아요." },
          note: "对…负责·对…感兴趣·对…有帮助 등 对 + 대상 짝꿍을 통째로 외우면 편하다",
        },
        {
          pattern: "拿…来说",
          conn: "拿 + 예 + 来说",
          ko: "~을 예로 들면, ~로 말하자면",
          ex: { zh: "拿这件事来说，他做得很好。", pinyin: "ná zhè jiàn shì lái shuō, tā zuò de hěn hǎo", ko: "이 일로 말하자면 그는 아주 잘했어요." },
          ex2: { zh: "拿我自己来说，我更喜欢安静的地方。", pinyin: "ná wǒ zìjǐ lái shuō, wǒ gèng xǐhuan ānjìng de dìfang", ko: "저로 말하자면 조용한 곳을 더 좋아해요." },
        },
        {
          pattern: "给…带来/造成",
          conn: "给 + 대상 + 带来/造成 + 영향·결과",
          ko: "~에게 (영향·결과)를 가져오다/끼치다",
          ex: { zh: "这件事给他带来了很大的麻烦。", pinyin: "zhè jiàn shì gěi tā dàilái le hěn dà de máfan", ko: "이 일은 그에게 큰 골칫거리를 가져왔어요." },
          ex2: { zh: "暴雨给交通造成了影响。", pinyin: "bàoyǔ gěi jiāotōng zàochéng le yǐngxiǎng", ko: "폭우가 교통에 영향을 끼쳤어요." },
          note: "给…带来(좋은·중립)·给…造成(주로 나쁜 결과) — 뉴스·보고서체에 흔하다",
        },
      ],
    },
    {
      name: "수량·빈도·정도 부사",
      items: [
        {
          pattern: "并不・并非",
          conn: "并不 + 형용사·동사 / 并非 + 명사·판단",
          ko: "결코 ~한 것이 아니다",
          ex: { zh: "成功并不容易。", pinyin: "chénggōng bìng bù róngyì", ko: "성공은 결코 쉽지 않아요." },
          ex2: { zh: "这并非他的本意。", pinyin: "zhè bìngfēi tā de běnyì", ko: "이건 결코 그의 본심이 아니에요." },
          note: "并非는 不是의 서면형 — 并不(형용사·동사 앞), 并非(명사·판단 앞)",
        },
        {
          pattern: "再三・一再",
          conn: "주어 + 再三/一再 + 동사",
          ko: "거듭, 여러 번 (반복 강조)",
          ex: { zh: "他再三向我表示感谢。", pinyin: "tā zàisān xiàng wǒ biǎoshì gǎnxiè", ko: "그는 거듭 저에게 감사를 표했어요." },
          ex2: { zh: "我一再提醒他注意安全。", pinyin: "wǒ yízài tíxǐng tā zhùyì ānquán", ko: "저는 그에게 안전에 주의하라고 거듭 일렀어요." },
          note: "再三·一再는 서면적인 '여러 차례' — 동작의 반복을 강조",
        },
        {
          pattern: "格外",
          conn: "格外 + 형용사 (유난히)",
          ko: "유난히, 각별히",
          ex: { zh: "今天的月亮格外明亮。", pinyin: "jīntiān de yuèliang géwài míngliàng", ko: "오늘 달이 유난히 밝아요." },
          ex2: { zh: "见到老朋友，他格外高兴。", pinyin: "jiàndào lǎo péngyou, tā géwài gāoxìng", ko: "오랜 친구를 만나서 그는 유난히 기뻐했어요." },
        },
        {
          pattern: "未必",
          conn: "주어 + 未必 + 판단 (꼭 ~한 건 아니다)",
          ko: "반드시 ~한 것은 아니다",
          ex: { zh: "贵的未必就是好的。", pinyin: "guì de wèibì jiùshì hǎo de", ko: "비싸다고 꼭 좋은 건 아니에요." },
          ex2: { zh: "他说的未必都对。", pinyin: "tā shuō de wèibì dōu duì", ko: "그가 한 말이 다 맞는 건 아니에요." },
          note: "未必는 '반드시 ~인 것은 아니다'(부분 부정) — 一定不(반드시 아니다)와 다르다",
        },
      ],
    },
  ],
};
