/**
 * H6 문형 사전 — HSK 6급 고급 구문·성어·관용·서면 표현 전수 레이어 (SCHEMA.md 참고)
 * 챕터가 '이해'라면 이 사전은 '전수 검색'. 모든 예문에 병음 병기.
 */
export default {
  level: "H6",
  title: "6급 문형 사전",
  desc: "서면 허사·고급 관련사·격식 구문부터 성어·관용구·사자성어 활용까지 — HSK 6급 고급 문형 72개를 기능별 11개 테마로 전수 수록한 최상급 문형 사전. 구어·서면 레지스터를 구별해 모든 예문에 병음 병기.",
  themes: [
    {
      name: "서면 허사·격식 부사",
      items: [
        {
          pattern: "予以・加以",
          ch: "h5-05-passive",
          conn: "予以/加以 + 2음절 동사 (서면 형식동사)",
          ko: "~을 가하다, ~하다 (격식)",
          ex: { zh: "对违规行为将予以处罚。", pinyin: "duì wéiguī xíngwéi jiāng yǔyǐ chǔfá", ko: "규정 위반 행위에 대해서는 처벌을 가할 것입니다." },
          ex2: { zh: "这个问题需要加以重视。", pinyin: "zhège wèntí xūyào jiāyǐ zhòngshì", ko: "이 문제는 중시할 필요가 있습니다." },
          note: "予以·加以 뒤에는 2음절 동사가 목적어로 온다 — 공문·보고서체 형식동사",
        },
        {
          pattern: "给予",
          ch: "h5-05-passive",
          conn: "给予 + 추상 명사 (서면)",
          ko: "~을 주다/베풀다 (격식)",
          ex: { zh: "学校给予了他很大的支持。", pinyin: "xuéxiào jǐyǔ le tā hěn dà de zhīchí", ko: "학교는 그에게 큰 지원을 베풀었습니다." },
          ex2: { zh: "希望大家给予理解。", pinyin: "xīwàng dàjiā jǐyǔ lǐjiě", ko: "여러분의 이해를 부탁드립니다." },
          note: "给予(jǐyǔ)는 给(gěi)의 서면형 — 给予支持·给予帮助처럼 추상 명사와 결합",
        },
        {
          pattern: "将",
          ch: "h5-01-shumianyu",
          conn: "주어 + 将 + 동사 (미래·서면)",
          ko: "~할 것이다 (서면 미래)",
          ex: { zh: "会议将于下周举行。", pinyin: "huìyì jiāng yú xià zhōu jǔxíng", ko: "회의는 다음 주에 개최될 예정입니다." },
          ex2: { zh: "本次活动将持续一个月。", pinyin: "běn cì huódòng jiāng chíxù yí ge yuè", ko: "이번 행사는 한 달간 지속됩니다." },
          note: "将은 要·会의 서면형 — 于(=在)와 함께 공고·뉴스체에서 흔하다",
        },
        {
          pattern: "于",
          ch: "h5-01-shumianyu",
          conn: "동사 + 于 + 시간/장소/대상 (서면)",
          ko: "~에(서) (서면 개사)",
          ex: { zh: "他出生于一九九零年。", pinyin: "tā chūshēng yú yī jiǔ jiǔ líng nián", ko: "그는 1990년에 태어났습니다." },
          ex2: { zh: "成功源于不断的努力。", pinyin: "chénggōng yuán yú búduàn de nǔlì", ko: "성공은 끊임없는 노력에서 비롯됩니다." },
          note: "于는 在·从·对 등을 대신하는 서면 개사 — 出生于·源于·位于·善于처럼 동사에 붙는다",
        },
        {
          pattern: "皆・均",
          ch: "h5-01-shumianyu",
          conn: "주어 + 皆/均 + 술어 (모두, 서면)",
          ko: "모두, 다 (서면)",
          ex: { zh: "在场的人均表示赞同。", pinyin: "zàichǎng de rén jūn biǎoshì zàntóng", ko: "참석한 사람들은 모두 찬성을 표했습니다." },
          ex2: { zh: "各项准备工作皆已完成。", pinyin: "gè xiàng zhǔnbèi gōngzuò jiē yǐ wánchéng", ko: "각종 준비 작업이 모두 완료되었습니다." },
          note: "皆·均은 都의 서면형 — 공문·격식체. 구어에서는 都",
        },
        {
          pattern: "此・该・本",
          ch: "h5-01-shumianyu",
          conn: "此/该/本 + 명사 (이, 해당, 본)",
          ko: "이, 해당, 본 (서면 지시)",
          ex: { zh: "此事尚未得到证实。", pinyin: "cǐ shì shàngwèi dédào zhèngshí", ko: "이 일은 아직 확인되지 않았습니다." },
          ex2: { zh: "该公司将于近期上市。", pinyin: "gāi gōngsī jiāng yú jìnqī shàngshì", ko: "해당 회사는 곧 상장할 예정입니다." },
          note: "此(=这)·该(=那个, 앞서 언급한)·本(우리)는 서면 지시어 — 此外·该校·本公司",
        },
        {
          pattern: "乃至・以及",
          ch: "h5-01-shumianyu",
          conn: "A、B 乃至/以及 C (열거·확장)",
          ko: "내지, 그리고, ~까지도 (서면 열거)",
          ex: { zh: "这项政策影响到企业乃至整个社会。", pinyin: "zhè xiàng zhèngcè yǐngxiǎng dào qǐyè nǎizhì zhěnggè shèhuì", ko: "이 정책은 기업 내지 사회 전체에 영향을 미칩니다." },
          ex2: { zh: "他精通英语、法语以及德语。", pinyin: "tā jīngtōng yīngyǔ、fǎyǔ yǐjí déyǔ", ko: "그는 영어, 프랑스어 그리고 독일어에 능통합니다." },
          note: "以及는 격식 열거의 마지막 항목 연결, 乃至는 '~에 이르기까지'의 확장",
        },
        {
          pattern: "之・其",
          ch: "h5-06-zhi-qi",
          conn: "之(=的/그것) / 其(=그의·그것) — 문어 대사",
          ko: "그것의, 그 (문어 대사)",
          ex: { zh: "对此，我深以为然。", pinyin: "duì cǐ, wǒ shēn yǐwéi rán", ko: "이에 대해 저는 깊이 공감합니다." },
          ex2: { zh: "尽其所能，方能无悔。", pinyin: "jìn qí suǒ néng, fāng néng wú huǐ", ko: "자기가 할 수 있는 바를 다해야 비로소 후회가 없습니다." },
          note: "之·其는 문언 잔재 대사 — 尽其所能·取而代之처럼 성어·격식구에 박혀 있다",
        },
      ],
    },
    {
      name: "고급 양보·전환",
      items: [
        {
          pattern: "固然…，但…",
          ch: "h6-06-advanced-conjunctions",
          conn: "固然 + 인정하는 사실，但/可 + 더 중요한 점",
          ko: "물론 ~하기는 하지만, …하다",
          ex: { zh: "理论固然重要，但实践更不可少。", pinyin: "lǐlùn gùrán zhòngyào, dàn shíjiàn gèng bùkě shǎo", ko: "이론도 물론 중요하지만 실천이 더욱 빠질 수 없습니다." },
          ex2: { zh: "天分固然有用，努力却更关键。", pinyin: "tiānfèn gùrán yǒuyòng, nǔlì què gèng guānjiàn", ko: "재능도 물론 쓸모 있지만 노력이 더 관건이에요." },
          note: "固然은 '먼저 한쪽을 인정하고 뒤에 더 중요한 점을 강조' — 서면 양보",
        },
        {
          pattern: "尽管如此",
          ch: "h6-06-advanced-conjunctions",
          conn: "앞 문장。尽管如此，주어 + 결과",
          ko: "그럼에도 불구하고",
          ex: { zh: "条件很差，尽管如此，他们还是坚持了下来。", pinyin: "tiáojiàn hěn chà, jǐnguǎn rúcǐ, tāmen háishi jiānchí le xiàlái", ko: "여건이 나빴지만, 그럼에도 그들은 끝까지 버텼습니다." },
          ex2: { zh: "他知道很危险，尽管如此也没有退缩。", pinyin: "tā zhīdào hěn wēixiǎn, jǐnguǎn rúcǐ yě méiyǒu tuìsuō", ko: "그는 위험한 줄 알았지만 그럼에도 물러서지 않았어요." },
        },
        {
          pattern: "话虽如此",
          conn: "话虽如此，但/可 + 유보·반전",
          ko: "말은 그렇지만",
          ex: { zh: "话虽如此，实际操作起来并不容易。", pinyin: "huà suī rúcǐ, shíjì cāozuò qǐlái bìng bù róngyì", ko: "말은 그렇지만 실제로 해 보면 결코 쉽지 않아요." },
          ex2: { zh: "话虽如此，我还是有点儿担心。", pinyin: "huà suī rúcǐ, wǒ háishi yǒudiǎnr dānxīn", ko: "말은 그렇지만 그래도 좀 걱정돼요." },
        },
        {
          pattern: "与此同时・相反",
          ch: "h5-02-connectors",
          conn: "与此同时 / 相反 + 대조·병행 진술",
          ko: "이와 동시에 / 반대로 (서면 접속)",
          ex: { zh: "经济在增长，与此同时，环境压力也在加大。", pinyin: "jīngjì zài zēngzhǎng, yǔ cǐ tóngshí, huánjìng yālì yě zài jiādà", ko: "경제가 성장하는 한편, 동시에 환경 부담도 커지고 있습니다." },
          ex2: { zh: "有人支持，相反，也有人坚决反对。", pinyin: "yǒu rén zhīchí, xiāngfǎn, yě yǒu rén jiānjué fǎnduì", ko: "지지하는 사람도 있고, 반대로 단호히 반대하는 사람도 있습니다." },
          note: "与此同时·相反·因此·然而 등은 단락 첫머리에 오는 서면 접속어",
        },
        {
          pattern: "退一步说",
          conn: "退一步说，即使 + 양보，也…",
          ko: "한 걸음 양보해서 말하면",
          ex: { zh: "退一步说，即使失败了，也是宝贵的经验。", pinyin: "tuì yí bù shuō, jíshǐ shībài le, yě shì bǎoguì de jīngyàn", ko: "한 걸음 양보해서 말하면, 설령 실패하더라도 귀중한 경험이에요." },
          ex2: { zh: "退一步说，这件事也不全是他的错。", pinyin: "tuì yí bù shuō, zhè jiàn shì yě bù quán shì tā de cuò", ko: "한 걸음 물러서서 봐도 이 일이 전부 그의 잘못은 아니에요." },
        },
        {
          pattern: "倒不如说",
          conn: "与其说 + A，倒不如说 + B",
          ko: "~라기보다 차라리 …라고 하는 편이 낫다",
          ex: { zh: "与其说他是老师，倒不如说他是朋友。", pinyin: "yǔqí shuō tā shì lǎoshī, dào bùrú shuō tā shì péngyou", ko: "그를 선생님이라기보다 차라리 친구라고 하는 편이 맞아요." },
          ex2: { zh: "这与其说是巧合，倒不如说是必然。", pinyin: "zhè yǔqí shuō shì qiǎohé, dào bùrú shuō shì bìrán", ko: "이건 우연이라기보다 차라리 필연이라 해야겠죠." },
          note: "与其说…倒不如说…은 더 정확한 표현으로 바꿔 말하는 서면 구문",
        },
      ],
    },
    {
      name: "강조·점층 고급",
      items: [
        {
          pattern: "不但不/没…，反而…",
          ch: "h5-07-rhetorical-emphasis",
          conn: "不但不/没 + A，反而 + 상반된 B",
          ko: "~하기는커녕 오히려 …하다",
          ex: { zh: "他不但不道歉，反而怪起别人来。", pinyin: "tā búdàn bù dàoqiàn, fǎn'ér guài qǐ biérén lái", ko: "그는 사과하기는커녕 오히려 남을 탓하기 시작했어요." },
          ex2: { zh: "批评之后，他不但没改，反而变本加厉。", pinyin: "pīpíng zhīhòu, tā búdàn méi gǎi, fǎn'ér biàn běn jiā lì", ko: "지적을 받고도 그는 고치기는커녕 오히려 더 심해졌어요." },
          note: "不但不…反而…는 '예상과 정반대' 강조 — 变本加厉(더 심해지다) 같은 성어와 잘 어울린다",
        },
        {
          pattern: "非…不可",
          ch: "h5-07-rhetorical-emphasis",
          conn: "非 + 동사/명사 + 不可",
          ko: "반드시 ~해야 한다, ~하지 않으면 안 된다",
          ex: { zh: "这件事非他不可。", pinyin: "zhè jiàn shì fēi tā bùkě", ko: "이 일은 그가 아니면 안 돼요." },
          ex2: { zh: "想成功，非下苦功不可。", pinyin: "xiǎng chénggōng, fēi xià kǔgōng bùkě", ko: "성공하려면 반드시 각고의 노력을 해야 해요." },
          note: "非…不可는 이중부정으로 강한 필연 — 不可를 不行·不成으로도 바꿀 수 있다",
        },
        {
          pattern: "何况・更不用说",
          ch: "h6-06-advanced-conjunctions",
          conn: "앞 사실，何况/更不用说 + 더 분명한 경우",
          ko: "하물며, ~은 말할 것도 없고",
          ex: { zh: "大人都搬不动，何况孩子呢？", pinyin: "dàrén dōu bān bu dòng, hékuàng háizi ne", ko: "어른도 못 옮기는데 하물며 아이가요?" },
          ex2: { zh: "他连母语都说不好，更不用说外语了。", pinyin: "tā lián mǔyǔ dōu shuō bu hǎo, gèng búyòng shuō wàiyǔ le", ko: "그는 모국어도 잘 못하는데 외국어는 말할 것도 없죠." },
          note: "何况·更不用说은 점층 — 약한 예에서 강한 예로 끌어올린다",
        },
        {
          pattern: "莫过于",
          conn: "최상급 평가 + 莫过于 + 대상",
          ko: "~만 한 것이 없다, 가장 ~한 것은 …이다",
          ex: { zh: "人生最大的幸福莫过于身体健康。", pinyin: "rénshēng zuì dà de xìngfú mòguòyú shēntǐ jiànkāng", ko: "인생 최대의 행복은 건강만 한 것이 없습니다." },
          ex2: { zh: "最令人感动的莫过于他的坚持。", pinyin: "zuì lìng rén gǎndòng de mòguòyú tā de jiānchí", ko: "가장 감동적인 것은 그의 끈기였습니다." },
          note: "莫过于는 '~을 능가하는 것이 없다'는 서면 최상급 표현",
        },
        {
          pattern: "无非是・不外乎",
          conn: "无非是/不外乎 + 한정된 범위",
          ko: "결국 ~에 불과하다, ~을 벗어나지 않는다",
          ex: { zh: "他的要求无非是希望得到尊重。", pinyin: "tā de yāoqiú wúfēi shì xīwàng dédào zūnzhòng", ko: "그의 요구는 결국 존중받고 싶다는 것에 불과해요." },
          ex2: { zh: "成功的秘诀不外乎勤奋和坚持。", pinyin: "chénggōng de mìjué bùwàihū qínfèn hé jiānchí", ko: "성공의 비결은 결국 근면과 끈기를 벗어나지 않아요." },
          note: "不外乎는 '결국 ~의 범위를 넘지 않는다'는 서면 한정",
        },
        {
          pattern: "何尝・岂",
          ch: "h4-07-rhetorical",
          conn: "何尝/岂 + 不 + 술어 (반어)",
          ko: "어찌 ~하지 않겠는가 (반어 강조)",
          ex: { zh: "我何尝不知道其中的危险？", pinyin: "wǒ hécháng bù zhīdào qízhōng de wēixiǎn", ko: "제가 그 위험을 어찌 모르겠어요?" },
          ex2: { zh: "这岂是一朝一夕能做到的？", pinyin: "zhè qǐ shì yì zhāo yì xī néng zuòdào de", ko: "이게 어찌 하루아침에 이룰 수 있는 일이겠어요?" },
          note: "何尝·岂는 반어로 강한 단정 — 一朝一夕(하루아침) 같은 성어와 잘 어울린다",
        },
      ],
    },
    {
      name: "원인·결과·논리 서면",
      items: [
        {
          pattern: "鉴于",
          ch: "h6-06-advanced-conjunctions",
          conn: "鉴于 + 상황·사실，주어 + 결정·조치",
          ko: "~을 감안하여, ~에 비추어",
          ex: { zh: "鉴于天气原因，活动延期举行。", pinyin: "jiànyú tiānqì yuányīn, huódòng yánqī jǔxíng", ko: "날씨를 감안하여 행사를 연기합니다." },
          ex2: { zh: "鉴于他的出色表现，公司决定提拔他。", pinyin: "jiànyú tā de chūsè biǎoxiàn, gōngsī juédìng tíbá tā", ko: "그의 뛰어난 성과를 감안해 회사는 그를 승진시키기로 했습니다." },
          note: "鉴于는 공문·보고서에서 결정의 근거를 제시하는 격식 개사",
        },
        {
          pattern: "从而",
          ch: "h5-02-connectors",
          conn: "앞 동작·조건，从而 + 그로 인한 결과",
          ko: "그리하여, 그로써 (서면 결과)",
          ex: { zh: "他改进了方法，从而提高了效率。", pinyin: "tā gǎijìn le fāngfǎ, cóng'ér tígāo le xiàolǜ", ko: "그는 방법을 개선하여 효율을 높였습니다." },
          ex2: { zh: "技术的发展从而改变了人们的生活。", pinyin: "jìshù de fāzhǎn cóng'ér gǎibiàn le rénmen de shēnghuó", ko: "기술 발전은 그로써 사람들의 생활을 바꿔 놓았습니다." },
          note: "从而는 앞의 수단·조건에서 결과로 이어지는 서면 연결 — 因此와 달리 인과를 한 호흡에 잇는다",
        },
        {
          pattern: "以至于・以致",
          ch: "h5-02-connectors",
          conn: "앞 정도·원인，以至于/以致 + 결과",
          ko: "~한 나머지, 그 결과 …하다",
          ex: { zh: "他太投入了，以至于忘了时间。", pinyin: "tā tài tóurù le, yǐzhìyú wàng le shíjiān", ko: "그는 너무 몰입한 나머지 시간 가는 줄 몰랐어요." },
          ex2: { zh: "准备不足，以致比赛失利。", pinyin: "zhǔnbèi bùzú, yǐzhì bǐsài shīlì", ko: "준비가 부족하여 그 결과 경기에서 패했습니다." },
          note: "以至于(정도가 심해 자연히 그 결과로)·以致(주로 안 좋은 결과)를 구별",
        },
        {
          pattern: "总而言之・综上所述",
          ch: "h5-02-connectors",
          conn: "총괄어 + 결론",
          ko: "요컨대, 이상을 종합하면",
          ex: { zh: "总而言之，我们应该尽快行动。", pinyin: "zǒng'ér yán zhī, wǒmen yīnggāi jǐnkuài xíngdòng", ko: "요컨대 우리는 되도록 빨리 행동해야 합니다." },
          ex2: { zh: "综上所述，这个方案是可行的。", pinyin: "zōng shàng suǒ shù, zhège fāng'àn shì kěxíng de", ko: "이상을 종합하면 이 방안은 실현 가능합니다." },
          note: "总而言之(구어·서면 모두)·综上所述(논설문 결론)는 마무리 신호어",
        },
        {
          pattern: "可见",
          conn: "앞 근거。可见 + 도출된 결론",
          ko: "~을 보면 알 수 있다, 이로써 ~임을 알 수 있다",
          ex: { zh: "他每次都准时，可见是个守信的人。", pinyin: "tā měi cì dōu zhǔnshí, kějiàn shì ge shǒuxìn de rén", ko: "그는 매번 시간을 지키니 신의 있는 사람임을 알 수 있어요." },
          ex2: { zh: "由此可见，努力比天赋更重要。", pinyin: "yóu cǐ kějiàn, nǔlì bǐ tiānfù gèng zhòngyào", ko: "이로써 노력이 재능보다 중요함을 알 수 있습니다." },
          note: "可见·由此可见은 앞의 근거에서 결론을 끌어내는 논설 표현",
        },
        {
          pattern: "之所以…，关键在于…",
          ch: "h6-06-advanced-conjunctions",
          conn: "주어 + 之所以 + 결과，关键在于 + 핵심 원인",
          ko: "~한 까닭은 …에 달려 있다",
          ex: { zh: "他之所以成功，关键在于持之以恒。", pinyin: "tā zhī suǒyǐ chénggōng, guānjiàn zàiyú chí zhī yǐ héng", ko: "그가 성공한 비결은 꾸준함에 있어요." },
          ex2: { zh: "问题之所以难，关键在于缺乏经验。", pinyin: "wèntí zhī suǒyǐ nán, guānjiàn zàiyú quēfá jīngyàn", ko: "문제가 어려운 까닭은 경험 부족에 있어요." },
          note: "关键在于·问题在于·原因在于 — 핵심을 짚는 서면 구문",
        },
      ],
    },
    {
      name: "비교·기준 서면",
      items: [
        {
          pattern: "相比之下・相对而言",
          conn: "相比之下 / 相对而言 + 비교 결과",
          ko: "그에 비하면 / 상대적으로",
          ex: { zh: "相比之下，这个方案更合理。", pinyin: "xiāngbǐ zhī xià, zhège fāng'àn gèng hélǐ", ko: "그에 비하면 이 방안이 더 합리적입니다." },
          ex2: { zh: "相对而言，南方的冬天比较温暖。", pinyin: "xiāngduì ér yán, nánfāng de dōngtiān bǐjiào wēnnuǎn", ko: "상대적으로 남쪽의 겨울은 비교적 따뜻해요." },
        },
        {
          pattern: "与…相比",
          conn: "与 + 대상 + 相比，주어 + 차이",
          ko: "~와 비교하면",
          ex: { zh: "与去年相比，今年的销量大幅增长。", pinyin: "yǔ qùnián xiāngbǐ, jīnnián de xiāoliàng dàfú zēngzhǎng", ko: "작년과 비교하면 올해 판매량이 크게 늘었습니다." },
          ex2: { zh: "与其他城市相比，这里的房价更高。", pinyin: "yǔ qítā chéngshì xiāngbǐ, zhèlǐ de fángjià gèng gāo", ko: "다른 도시와 비교하면 이곳의 집값이 더 높아요." },
          note: "与…相比는 跟…比较的 서면형 — 통계·보고서에서 흔하다",
        },
        {
          pattern: "不亚于",
          conn: "A + 不亚于 + B",
          ko: "A는 B에 못지않다",
          ex: { zh: "他的能力不亚于任何人。", pinyin: "tā de nénglì bú yà yú rènhé rén", ko: "그의 능력은 누구에게도 못지않아요." },
          ex2: { zh: "这部电影的水准不亚于好莱坞大片。", pinyin: "zhè bù diànyǐng de shuǐzhǔn bú yà yú hǎoláiwù dàpiàn", ko: "이 영화의 수준은 할리우드 대작에 못지않습니다." },
        },
        {
          pattern: "宁愿…，也不…",
          ch: "h6-06-advanced-conjunctions",
          conn: "宁愿 + A，也不 + B (감수 vs 거부)",
          ko: "차라리 ~할지언정 …하지 않다",
          ex: { zh: "我宁愿失败，也不愿放弃尝试。", pinyin: "wǒ nìngyuàn shībài, yě bú yuàn fàngqì chángshì", ko: "차라리 실패할지언정 시도를 포기하지 않겠어요." },
          ex2: { zh: "他宁愿吃苦，也不向困难低头。", pinyin: "tā nìngyuàn chīkǔ, yě bú xiàng kùnnan dītóu", ko: "그는 고생할지언정 어려움에 굴복하지 않아요." },
          note: "宁愿…也不…는 宁可…也不…와 같은 뜻 — 의지적 선택의 강조",
        },
        {
          pattern: "在…看来",
          conn: "在 + 사람 + 看来 (~이 보기에)",
          ko: "~이 보기에는, ~의 견해로는",
          ex: { zh: "在我看来，这种做法并不可取。", pinyin: "zài wǒ kànlái, zhè zhǒng zuòfǎ bìng bù kěqǔ", ko: "제가 보기에 이런 방식은 결코 바람직하지 않아요." },
          ex2: { zh: "在专家看来，这个结论还需要验证。", pinyin: "zài zhuānjiā kànlái, zhège jiélùn hái xūyào yànzhèng", ko: "전문가가 보기에 이 결론은 아직 검증이 필요합니다." },
          note: "在…看来는 관점·견해의 주체를 명시하는 서면 표현",
        },
        {
          pattern: "就…来看",
          conn: "就 + 근거 + 来看 (~으로 볼 때)",
          ko: "~으로 볼 때, ~에 비추어 보면",
          ex: { zh: "就目前的情况来看，进展比较顺利。", pinyin: "jiù mùqián de qíngkuàng lái kàn, jìnzhǎn bǐjiào shùnlì", ko: "현재 상황으로 볼 때 진행이 비교적 순조로워요." },
          ex2: { zh: "就数据来看，这个趋势还会持续。", pinyin: "jiù shùjù lái kàn, zhège qūshì hái huì chíxù", ko: "데이터로 볼 때 이 추세는 계속될 거예요." },
          note: "就…来看은 판단의 근거를 제시 — 从…来看과 통한다",
        },
      ],
    },
    {
      name: "성어 — 정도·상태",
      items: [
        {
          pattern: "一举两得",
          ch: "h6-01-advanced-chengyu",
          conn: "사자성어 (술어·평어)",
          ko: "일거양득, 한 번에 두 가지를 얻다",
          ex: { zh: "骑车上班既环保又锻炼身体，真是一举两得。", pinyin: "qí chē shàngbān jì huánbǎo yòu duànliàn shēntǐ, zhēn shì yìjǔ liǎngdé", ko: "자전거로 출근하면 친환경적이면서 운동도 되니 정말 일거양득이에요." },
          ex2: { zh: "这个办法一举两得，何乐而不为？", pinyin: "zhège bànfǎ yìjǔ liǎngdé, hé lè ér bù wéi", ko: "이 방법은 일거양득인데 왜 안 하겠어요?" },
          note: "한국어 '일거양득'과 한자가 같다 — 一舉兩得",
        },
        {
          pattern: "千方百计",
          ch: "h6-01-advanced-chengyu",
          conn: "千方百计 + 동사 (온갖 방법으로)",
          ko: "온갖 방법을 다 동원하여",
          ex: { zh: "他千方百计地想要解决这个问题。", pinyin: "tā qiānfāng bǎijì de xiǎng yào jiějué zhège wèntí", ko: "그는 온갖 방법을 다 동원해 이 문제를 풀려고 했어요." },
          ex2: { zh: "为了帮助灾民，大家千方百计筹集物资。", pinyin: "wèile bāngzhù zāimín, dàjiā qiānfāng bǎijì chóují wùzī", ko: "이재민을 돕기 위해 모두가 온갖 방법으로 물자를 모았어요." },
        },
        {
          pattern: "理所当然",
          ch: "h6-01-advanced-chengyu",
          conn: "理所当然 (당연하다) — 술어·관형어",
          ko: "지극히 당연하다",
          ex: { zh: "努力就有回报，这是理所当然的。", pinyin: "nǔlì jiù yǒu huíbào, zhè shì lǐsuǒ dāngrán de", ko: "노력하면 보답이 따르는 건 지극히 당연한 일이에요." },
          ex2: { zh: "他把别人的帮助当成理所当然。", pinyin: "tā bǎ biérén de bāngzhù dàngchéng lǐsuǒ dāngrán", ko: "그는 남의 도움을 당연하게 여겨요." },
        },
        {
          pattern: "迫不及待",
          ch: "h6-01-advanced-chengyu",
          conn: "迫不及待地 + 동사",
          ko: "한시도 지체할 수 없을 만큼 조급하다",
          ex: { zh: "收到礼物，孩子迫不及待地打开了。", pinyin: "shōudào lǐwù, háizi pòbùjídài de dǎkāi le", ko: "선물을 받자 아이는 한시도 못 기다리고 뜯어 봤어요." },
          ex2: { zh: "他迫不及待地想分享这个好消息。", pinyin: "tā pòbùjídài de xiǎng fēnxiǎng zhège hǎo xiāoxi", ko: "그는 한시바삐 이 좋은 소식을 알리고 싶어 했어요." },
        },
        {
          pattern: "名副其实",
          ch: "h6-01-advanced-chengyu",
          conn: "名副其实 (이름값을 하다) — 술어·관형어",
          ko: "명실상부하다, 명성에 걸맞다",
          ex: { zh: "他是一位名副其实的专家。", pinyin: "tā shì yí wèi míngfù qíshí de zhuānjiā", ko: "그는 명실상부한 전문가예요." },
          ex2: { zh: "这座城市名副其实，处处是美景。", pinyin: "zhè zuò chéngshì míngfù qíshí, chùchù shì měijǐng", ko: "이 도시는 명성 그대로 곳곳이 절경이에요." },
          note: "名副其实 ↔ 名不副实(이름값을 못 하다) — 한국어 '명실상부'",
        },
        {
          pattern: "层出不穷",
          ch: "h6-01-advanced-chengyu",
          conn: "주어 + 层出不穷 (끊임없이 나타나다)",
          ko: "끊임없이 쏟아져 나오다",
          ex: { zh: "新技术层出不穷，让人眼花缭乱。", pinyin: "xīn jìshù céngchū bùqióng, ràng rén yǎnhuā liáoluàn", ko: "신기술이 끊임없이 쏟아져 나와 눈이 어지러울 정도예요." },
          ex2: { zh: "类似的问题层出不穷，必须从根本上解决。", pinyin: "lèisì de wèntí céngchū bùqióng, bìxū cóng gēnběn shàng jiějué", ko: "비슷한 문제가 끊이지 않으니 근본적으로 해결해야 합니다." },
        },
        {
          pattern: "数一数二",
          ch: "h6-01-advanced-chengyu",
          conn: "주어 + 数一数二 (손꼽히다)",
          ko: "손에 꼽히다, 으뜸가다",
          ex: { zh: "他是公司里数一数二的人才。", pinyin: "tā shì gōngsī lǐ shǔyī shǔ'èr de réncái", ko: "그는 회사에서 손꼽히는 인재예요." },
          ex2: { zh: "这家餐厅在本地数一数二。", pinyin: "zhè jiā cāntīng zài běndì shǔyī shǔ'èr", ko: "이 식당은 이 지역에서 으뜸으로 꼽혀요." },
        },
        {
          pattern: "微不足道",
          ch: "h6-01-advanced-chengyu",
          conn: "주어 + 微不足道 (보잘것없다)",
          ko: "하찮다, 보잘것없다",
          ex: { zh: "和他的贡献相比，我做的微不足道。", pinyin: "hé tā de gòngxiàn xiāngbǐ, wǒ zuò de wēi bù zú dào", ko: "그의 기여에 비하면 제가 한 일은 보잘것없어요." },
          ex2: { zh: "这点损失微不足道，不必在意。", pinyin: "zhè diǎn sǔnshī wēi bù zú dào, búbì zàiyì", ko: "이 정도 손실은 하찮으니 신경 쓸 필요 없어요." },
        },
      ],
    },
    {
      name: "성어 — 태도·처세",
      items: [
        {
          pattern: "全力以赴",
          ch: "h6-01-advanced-chengyu",
          conn: "全力以赴 + (동사) (전력을 다하다)",
          ko: "전력을 다하다",
          ex: { zh: "无论结果如何，我都会全力以赴。", pinyin: "wúlùn jiéguǒ rúhé, wǒ dōu huì quánlì yǐfù", ko: "결과가 어떻든 저는 전력을 다할 거예요." },
          ex2: { zh: "为了这次比赛，全队全力以赴。", pinyin: "wèile zhè cì bǐsài, quán duì quánlì yǐfù", ko: "이번 경기를 위해 팀 전체가 전력을 쏟았어요." },
        },
        {
          pattern: "脚踏实地",
          ch: "h6-01-advanced-chengyu",
          conn: "脚踏实地 (착실하다) — 술어·부사어",
          ko: "발을 땅에 딛고 착실히 하다",
          ex: { zh: "成功没有捷径，只能脚踏实地。", pinyin: "chénggōng méiyǒu jiéjìng, zhǐ néng jiǎotà shídì", ko: "성공에 지름길은 없으니 착실히 하는 수밖에 없어요." },
          ex2: { zh: "他做事脚踏实地，深受大家信任。", pinyin: "tā zuòshì jiǎotà shídì, shēn shòu dàjiā xìnrèn", ko: "그는 일을 착실하게 해 모두의 신뢰를 깊이 받아요." },
        },
        {
          pattern: "三心二意・全神贯注",
          ch: "h6-01-advanced-chengyu",
          conn: "三心二意 (산만) ↔ 全神贯注 (몰두)",
          ko: "마음이 산만하다 / 온 정신을 집중하다",
          ex: { zh: "做事不能三心二意，要专心。", pinyin: "zuòshì bùnéng sānxīn èryì, yào zhuānxīn", ko: "일을 할 때 딴마음 먹지 말고 집중해야 해요." },
          ex2: { zh: "他全神贯注地听老师讲课。", pinyin: "tā quánshén guànzhù de tīng lǎoshī jiǎngkè", ko: "그는 온 정신을 집중해 선생님의 강의를 들었어요." },
          note: "三心二意(딴생각)와 全神贯注(전념)는 대조 성어 — 짝지어 외우면 좋다",
        },
        {
          pattern: "实事求是",
          ch: "h6-01-advanced-chengyu",
          conn: "实事求是 (사실에 입각하다) — 술어·부사어",
          ko: "사실에 근거해 진실을 추구하다",
          ex: { zh: "我们应该实事求是地看待这个问题。", pinyin: "wǒmen yīnggāi shíshì qiúshì de kàndài zhège wèntí", ko: "우리는 사실에 입각해 이 문제를 봐야 해요." },
          ex2: { zh: "做研究必须实事求是，不能弄虚作假。", pinyin: "zuò yánjiū bìxū shíshì qiúshì, bùnéng nòngxū zuòjiǎ", ko: "연구는 반드시 사실에 근거해야지 거짓을 꾸며선 안 돼요." },
        },
        {
          pattern: "半途而废",
          ch: "h6-01-advanced-chengyu",
          conn: "주어 + 半途而废 (중도에 포기하다)",
          ko: "하던 일을 중도에 그만두다",
          ex: { zh: "既然开始了，就不要半途而废。", pinyin: "jìrán kāishǐ le, jiù bú yào bàntú ér fèi", ko: "이미 시작했으니 중도에 그만두지 마세요." },
          ex2: { zh: "他做事常常半途而废，很难成功。", pinyin: "tā zuòshì chángcháng bàntú ér fèi, hěn nán chénggōng", ko: "그는 일을 자주 중도에 포기해서 성공하기 어려워요." },
        },
        {
          pattern: "一举一动",
          ch: "h6-01-advanced-chengyu",
          conn: "一 + 명사1 + 一 + 명사2 (ABAC 성어)",
          ko: "일거수일투족, 하나하나의 행동",
          ex: { zh: "他的一举一动都受到大家的关注。", pinyin: "tā de yìjǔ yídòng dōu shòudào dàjiā de guānzhù", ko: "그의 일거수일투족이 모두의 주목을 받아요." },
          ex2: { zh: "做老师的，一言一行都要谨慎。", pinyin: "zuò lǎoshī de, yì yán yì xíng dōu yào jǐnshèn", ko: "선생님이라면 말 한마디 행동 하나까지 신중해야 해요." },
          note: "一举一动·一言一行처럼 一…一… ABAC형 성어는 '하나하나·낱낱이'를 뜻한다",
        },
        {
          pattern: "千载难逢",
          ch: "h6-01-advanced-chengyu",
          conn: "千载难逢的 + 명사 (좀처럼 만나기 힘든)",
          ko: "천재일우의, 좀처럼 오지 않는",
          ex: { zh: "这是一个千载难逢的好机会。", pinyin: "zhè shì yí ge qiānzǎi nánféng de hǎo jīhuì", ko: "이건 천재일우의 좋은 기회예요." },
          ex2: { zh: "能亲眼见到他，真是千载难逢。", pinyin: "néng qīnyǎn jiàndào tā, zhēn shì qiānzǎi nánféng", ko: "그를 직접 볼 수 있다니 정말 좀처럼 없는 일이에요." },
        },
      ],
    },
    {
      name: "관용구·구어 표현",
      items: [
        {
          pattern: "说不定",
          ch: "h6-02-idioms-xiehouyu",
          conn: "说不定 + 추측",
          ko: "어쩌면 ~일지도 모른다",
          ex: { zh: "说不定他已经到了。", pinyin: "shuōbudìng tā yǐjīng dào le", ko: "어쩌면 그가 벌써 도착했을지도 몰라요." },
          ex2: { zh: "多准备一些，说不定用得上。", pinyin: "duō zhǔnbèi yìxiē, shuōbudìng yòng de shàng", ko: "좀 더 준비해 둬요, 어쩌면 쓸지도 모르니까." },
          note: "说不定은 也许·可能보다 구어적인 '혹시·어쩌면'",
        },
        {
          pattern: "难怪",
          ch: "h6-02-idioms-xiehouyu",
          conn: "难怪/怪不得 + 결과 (+ 原来 + 원인)",
          ko: "어쩐지, 그럴 만도 하다",
          ex: { zh: "难怪他这么累，原来昨晚没睡。", pinyin: "nánguài tā zhème lèi, yuánlái zuó wǎn méi shuì", ko: "어쩐지 그가 이렇게 피곤하더라니, 알고 보니 어젯밤에 못 잤군요." },
          ex2: { zh: "难怪找不到，钥匙在你口袋里。", pinyin: "nánguài zhǎo bu dào, yàoshi zài nǐ kǒudai lǐ", ko: "못 찾을 만하네, 열쇠가 네 주머니에 있잖아." },
        },
        {
          pattern: "归根结底",
          ch: "h6-02-idioms-xiehouyu",
          conn: "归根结底 + 본질적 결론",
          ko: "결국, 따지고 보면",
          ex: { zh: "归根结底，还是要靠自己努力。", pinyin: "guīgēn jiédǐ, háishi yào kào zìjǐ nǔlì", ko: "결국 따지고 보면 스스로 노력하는 수밖에 없어요." },
          ex2: { zh: "这些问题归根结底是观念的问题。", pinyin: "zhèxiē wèntí guīgēn jiédǐ shì guānniàn de wèntí", ko: "이 문제들은 따지고 보면 관념의 문제예요." },
        },
        {
          pattern: "一来…，二来…",
          conn: "一来 + 이유1，二来 + 이유2",
          ko: "첫째는 ~하고, 둘째는 …하고 (이유 나열)",
          ex: { zh: "我不去，一来太远，二来没时间。", pinyin: "wǒ bú qù, yìlái tài yuǎn, èrlái méi shíjiān", ko: "저는 안 가요, 하나는 너무 멀고 또 하나는 시간이 없어서요." },
          ex2: { zh: "学外语，一来开阔视野，二来增加机会。", pinyin: "xué wàiyǔ, yìlái kāikuò shìyě, èrlái zēngjiā jīhuì", ko: "외국어를 배우면 하나는 시야가 넓어지고 둘은 기회가 늘어요." },
        },
        {
          pattern: "再说",
          conn: "주장，再说 + 보충 이유",
          ko: "게다가, 더구나",
          ex: { zh: "今天太累了，再说也下雨了，就别出去了。", pinyin: "jīntiān tài lèi le, zàishuō yě xiàyǔ le, jiù bié chūqù le", ko: "오늘 너무 피곤하고, 게다가 비도 오니 나가지 맙시다." },
          ex2: { zh: "这件衣服很贵，再说也不太适合我。", pinyin: "zhè jiàn yīfu hěn guì, zàishuō yě bú tài shìhé wǒ", ko: "이 옷은 비싸고, 게다가 저한테 별로 안 어울려요." },
          note: "再说은 이미 충분한 이유에 하나 더 보태는 구어 — 동사 再说(나중에 다시 보다)와 구별",
        },
      ],
    },
    {
      name: "범위·한정 서면",
      items: [
        {
          pattern: "无不・莫不",
          conn: "주어 + 无不/莫不 + 술어 (~하지 않는 것이 없다)",
          ko: "모두 다 ~하다 (이중부정 강조)",
          ex: { zh: "听到这个消息，大家无不感到兴奋。", pinyin: "tīngdào zhège xiāoxi, dàjiā wúbù gǎndào xīngfèn", ko: "이 소식을 듣고 모두가 흥분하지 않을 수 없었어요." },
          ex2: { zh: "在场的人莫不为他的勇气所感动。", pinyin: "zàichǎng de rén mòbù wèi tā de yǒngqì suǒ gǎndòng", ko: "그 자리의 사람들 모두 그의 용기에 감동했습니다." },
          note: "无不·莫不은 이중부정으로 '예외 없이 다' — 都보다 강한 서면 강조",
        },
        {
          pattern: "唯有・唯独",
          conn: "唯有/唯独 + 대상 (오직 ~만)",
          ko: "오직 ~만, 유독 ~만",
          ex: { zh: "唯有努力，才能改变命运。", pinyin: "wéiyǒu nǔlì, cái néng gǎibiàn mìngyùn", ko: "오직 노력만이 운명을 바꿀 수 있어요." },
          ex2: { zh: "大家都同意，唯独他持反对意见。", pinyin: "dàjiā dōu tóngyì, wéidú tā chí fǎnduì yìjiàn", ko: "다들 동의했는데 유독 그만 반대 의견이었어요." },
          note: "唯有는 只有의 서면형(才와 호응), 唯独은 '유독 ~만'의 예외 강조",
        },
        {
          pattern: "未尝不・未必不",
          conn: "未尝/未必 + 不 + 술어 (꼭 ~ 아닌 것은 아니다)",
          ko: "꼭 ~한 것은 아니다, ~ 못 할 것도 없다",
          ex: { zh: "失败未尝不是一件好事。", pinyin: "shībài wèicháng bú shì yí jiàn hǎoshì", ko: "실패가 꼭 나쁜 일인 것만은 아니에요." },
          ex2: { zh: "这个办法未必行不通。", pinyin: "zhège bànfǎ wèibì xíng bu tōng", ko: "이 방법이 꼭 안 통하리란 법은 없어요." },
          note: "未尝不·未必不은 완곡한 이중부정 — '~할 수도 있다'를 에둘러 표현",
        },
        {
          pattern: "仅仅・无非",
          conn: "仅仅 / 无非 + 한정 (단지 ~에 불과하다)",
          ko: "단지 ~에 지나지 않다, 결국 ~일 뿐이다",
          ex: { zh: "这仅仅是一个开始。", pinyin: "zhè jǐnjǐn shì yí ge kāishǐ", ko: "이건 단지 시작일 뿐이에요." },
          ex2: { zh: "他说的无非是些客套话。", pinyin: "tā shuō de wúfēi shì xiē kètàohuà", ko: "그가 한 말은 결국 인사치레에 불과해요." },
          note: "无非(결국 ~에 불과)는 '대수롭지 않게 한정'하는 서면 표현",
        },
      ],
    },
    {
      name: "피동·처치 서면",
      items: [
        {
          pattern: "为…所…",
          ch: "h5-05-passive",
          conn: "주어 + 为 + 행위자 + 所 + 동사 (서면 피동)",
          ko: "~에 의해 …되다 (서면 피동)",
          ex: { zh: "他的精神为大家所敬佩。", pinyin: "tā de jīngshén wèi dàjiā suǒ jìngpèi", ko: "그의 정신은 모두에게 존경받습니다." },
          ex2: { zh: "这种现象逐渐为人们所接受。", pinyin: "zhè zhǒng xiànxiàng zhújiàn wèi rénmen suǒ jiēshòu", ko: "이런 현상은 점차 사람들에게 받아들여지고 있어요." },
          note: "为…所…는 被…의 서면형 — 为众人所知(널리 알려지다)처럼 굳어진 표현이 많다",
        },
        {
          pattern: "受到・遭到",
          ch: "h5-05-passive",
          conn: "주어 + 受到/遭到 + 추상 명사",
          ko: "~을 받다 / ~을 당하다 (서면 피동)",
          ex: { zh: "他的提议受到了广泛的支持。", pinyin: "tā de tíyì shòudào le guǎngfàn de zhīchí", ko: "그의 제안은 폭넓은 지지를 받았습니다." },
          ex2: { zh: "该计划遭到了不少人的反对。", pinyin: "gāi jìhuà zāodào le bùshǎo rén de fǎnduì", ko: "그 계획은 적지 않은 사람들의 반대에 부딪혔습니다." },
          note: "受到(긍정·중립)·遭到(부정적) — 뒤에 2음절 추상 명사가 온다",
        },
        {
          pattern: "对…进行…",
          ch: "h5-05-passive",
          conn: "对 + 대상 + 进行 + 2음절 동사명사",
          ko: "~에 대해 …을 진행하다/하다 (격식)",
          ex: { zh: "专家对这个方案进行了详细的分析。", pinyin: "zhuānjiā duì zhège fāng'àn jìnxíng le xiángxì de fēnxī", ko: "전문가가 이 방안에 대해 상세한 분석을 진행했습니다." },
          ex2: { zh: "公司将对设备进行全面检查。", pinyin: "gōngsī jiāng duì shèbèi jìnxíng quánmiàn jiǎnchá", ko: "회사는 설비에 대해 전면 점검을 실시할 예정입니다." },
          note: "对…进行…은 동작을 격식 있게 표현하는 서면 구문 — 进行 뒤엔 2음절 동사",
        },
        {
          pattern: "把…加以/予以…",
          ch: "h6-01-advanced-chengyu",
          conn: "把/对 + 대상 + 加以/予以 + 2음절 동사",
          ko: "~을 …하다 (서면 처치)",
          ex: { zh: "我们必须把这些意见加以总结。", pinyin: "wǒmen bìxū bǎ zhèxiē yìjiàn jiāyǐ zǒngjié", ko: "우리는 이 의견들을 종합해야 합니다." },
          ex2: { zh: "对存在的问题要予以纠正。", pinyin: "duì cúnzài de wèntí yào yǔyǐ jiūzhèng", ko: "존재하는 문제는 바로잡아야 합니다." },
          note: "加以·予以는 把구문·对구문과 결합하는 서면 형식동사",
        },
      ],
    },
  ],
};
