/**
 * 프랑스어 연습문항 미배선 초안.
 *
 * Claude 콘텐츠 검수 전까지 src/content/french/index.js 또는 런타임 소비자에서
 * import하지 않는다. 모든 문항은 원본 문법·어휘 팩의 표현만 사용한 DRAFT이며,
 * 정답 허용 범위와 문항 유형은 배선 전에 별도 확정해야 한다.
 */

export const FRENCH_EXERCISE_DRAFT_SCHEMA_VERSION = 1;
export const FRENCH_EXERCISE_DRAFT_STATUS = "DRAFT_UNWIRED";

const grammarDraftPacks = [
  {
    sourcePath: "src/content/french/grammar/a0.js",
    kind: "grammar",
    level: "A0",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-a0-01",
        type: "short-answer",
        sourceRef: "a0-02-alphabet",
        promptKo: "프랑스어 알파벳 g의 이름 발음을 IPA로 쓰세요.",
        answer: "[ʒe]",
      },
      {
        id: "fr-g-a0-02",
        type: "short-answer",
        sourceRef: "a0-03-vowels",
        promptKo: "프랑스어 u와 ou 중 [y]로 발음하는 철자를 쓰세요.",
        answer: "u",
      },
      {
        id: "fr-g-a0-03",
        type: "short-answer",
        sourceRef: "a0-04-consonants",
        promptKo: "단어 끝에서도 발음될 수 있는 CaReFuL 자음 네 개를 순서대로 쓰세요.",
        answer: "c, r, f, l",
      },
    ],
  },
  {
    sourcePath: "src/content/french/grammar/a1.js",
    kind: "grammar",
    level: "A1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-a1-01",
        type: "short-answer",
        sourceRef: "a1-01-pronouns-etre",
        promptKo: "être 현재형에서 ‘우리는’에 해당하는 형태를 완성하세요: nous ____.",
        answer: "sommes",
      },
      {
        id: "fr-g-a1-02",
        type: "short-answer",
        sourceRef: "a1-02-avoir",
        promptKo: "‘배가 고프다’를 avoir를 사용해 쓰세요.",
        answer: "avoir faim",
      },
      {
        id: "fr-g-a1-03",
        type: "short-answer",
        sourceRef: "a1-03-er-verbs",
        promptKo: "규칙 -er 동사의 nous 현재형 어미를 쓰세요.",
        answer: "-ons",
      },
    ],
  },
  {
    sourcePath: "src/content/french/grammar/a2.js",
    kind: "grammar",
    level: "A2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-a2-01",
        type: "short-answer",
        sourceRef: "a2-01-passe-compose-avoir",
        promptKo: "avoir를 쓰는 복합과거의 기본 공식을 쓰세요.",
        answer: "avoir 현재형 + 과거분사",
      },
      {
        id: "fr-g-a2-02",
        type: "short-answer",
        sourceRef: "a2-02-passe-compose-etre",
        promptKo: "être를 쓰는 복합과거에서 과거분사가 주어와 일치해야 하는 두 범주는 무엇인가요?",
        answer: "성·수",
      },
      {
        id: "fr-g-a2-03",
        type: "short-answer",
        sourceRef: "a2-03-imparfait",
        promptKo: "반과거 어간은 현재형 어떤 인칭에서 -ons를 뺀 형태인가요?",
        answer: "nous",
      },
    ],
  },
  {
    sourcePath: "src/content/french/grammar/b1.js",
    kind: "grammar",
    level: "B1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-b1-01",
        type: "short-answer",
        sourceRef: "b1-01-conditionnel-present",
        promptKo: "정중하게 ‘저는 ~을 원합니다’라고 말할 때 쓰는 조건법 표현을 쓰세요.",
        answer: "Je voudrais...",
      },
      {
        id: "fr-g-b1-02",
        type: "short-answer",
        sourceRef: "b1-02-subjonctif-intro",
        promptKo: "바람·필요·감정·의심 뒤에서 사용하는 법(mood)의 프랑스어 이름을 쓰세요.",
        answer: "subjonctif",
      },
      {
        id: "fr-g-b1-03",
        type: "short-answer",
        sourceRef: "b1-03-plus-que-parfait",
        promptKo: "대과거의 기본 공식을 쓰세요.",
        answer: "avoir/être 반과거 + 과거분사",
      },
    ],
  },
  {
    sourcePath: "src/content/french/grammar/b2.js",
    kind: "grammar",
    level: "B2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-b2-01",
        type: "short-answer",
        sourceRef: "b2-01-subjonctif-advanced",
        promptKo: "bien que 뒤에 사용하는 법(mood)의 프랑스어 이름을 쓰세요.",
        answer: "subjonctif",
      },
      {
        id: "fr-g-b2-02",
        type: "short-answer",
        sourceRef: "b2-02-hypothese-si",
        promptKo: "현재 사실과 반대되는 가정의 공식을 완성하세요: si + ____, conditionnel présent.",
        answer: "imparfait",
      },
      {
        id: "fr-g-b2-03",
        type: "short-answer",
        sourceRef: "b2-03-participe-present",
        promptKo: "제롱디프를 만드는 기본 형태를 쓰세요.",
        answer: "en + -ant",
      },
    ],
  },
  {
    sourcePath: "src/content/french/grammar/c1.js",
    kind: "grammar",
    level: "C1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-c1-01",
        type: "short-answer",
        sourceRef: "c1-01-passe-simple",
        promptKo: "단순과거 passé simple이 주로 쓰이는 레지스터를 쓰세요.",
        answer: "문어",
      },
      {
        id: "fr-g-c1-02",
        type: "short-answer",
        sourceRef: "c1-02-registres",
        promptKo: "표준(courant) 의문문에서 도치 대신 쓰는 대표 구조를 쓰세요.",
        answer: "est-ce que",
      },
      {
        id: "fr-g-c1-03",
        type: "short-answer",
        sourceRef: "c1-03-argumentation",
        promptKo: "프랑스식 논증의 정·반·합 세 단계를 프랑스어로 순서대로 쓰세요.",
        answer: "thèse → antithèse → synthèse",
      },
    ],
  },
  {
    sourcePath: "src/content/french/grammar/c2.js",
    kind: "grammar",
    level: "C2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-g-c2-01",
        type: "short-answer",
        sourceRef: "c2-01-subjonctif-litteraire",
        promptKo: "être의 접속법 반과거 3인칭 단수 형태를 쓰세요.",
        answer: "fût",
      },
      {
        id: "fr-g-c2-02",
        type: "short-answer",
        sourceRef: "c2-02-style",
        promptKo: "litote 예문 « Je ne te hais point. »가 실제로 강하게 전달하는 뜻을 한국어로 쓰세요.",
        answer: "당신을 사랑해요.",
      },
      {
        id: "fr-g-c2-03",
        type: "short-answer",
        sourceRef: "c2-03-francophonie",
        promptKo: "벨기에·스위스권에서 70을 가리키는 표현을 쓰세요.",
        answer: "septante",
      },
    ],
  },
];

const vocabDraftPacks = [
  {
    sourcePath: "src/content/french/vocab/a0.js",
    kind: "vocab",
    level: "A0",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-a0-01",
        type: "short-answer",
        sourceRef: "인사와 예의 표현: bonjour",
        promptKo: "‘안녕하세요(아침~낮)’에 해당하는 프랑스어를 쓰세요.",
        answer: "bonjour",
      },
      {
        id: "fr-v-a0-02",
        type: "short-answer",
        sourceRef: "카페에서 살아남기: la carte",
        promptKo: "카페에서 ‘메뉴판’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la carte",
      },
      {
        id: "fr-v-a0-03",
        type: "short-answer",
        sourceRef: "기초 형용사·부사: lentement",
        promptKo: "‘천천히’를 뜻하는 프랑스어 부사를 쓰세요.",
        answer: "lentement",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/a1.js",
    kind: "vocab",
    level: "A1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-a1-01",
        type: "short-answer",
        sourceRef: "가족과 사람: la famille",
        promptKo: "‘가족’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la famille",
      },
      {
        id: "fr-v-a1-02",
        type: "short-answer",
        sourceRef: "기초 형용사: mauvais",
        promptKo: "‘나쁜’을 뜻하는 프랑스어 형용사 남성형을 쓰세요.",
        answer: "mauvais",
      },
      {
        id: "fr-v-a1-03",
        type: "short-answer",
        sourceRef: "달력의 달: juin",
        promptKo: "‘6월’을 뜻하는 프랑스어를 쓰세요.",
        answer: "juin",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/a1_flelex.js",
    kind: "vocab",
    level: "A1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-a1-flelex-01",
        type: "short-answer",
        sourceRef: "사람과 일상: le nom",
        promptKo: "‘이름, 성(姓)’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le nom",
      },
      {
        id: "fr-v-a1-flelex-02",
        type: "short-answer",
        sourceRef: "도시와 장소: la campagne",
        promptKo: "‘시골’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la campagne",
      },
      {
        id: "fr-v-a1-flelex-03",
        type: "short-answer",
        sourceRef: "달력의 달: mai",
        promptKo: "‘5월’을 뜻하는 프랑스어를 쓰세요.",
        answer: "mai",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/a2.js",
    kind: "vocab",
    level: "A2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-a2-01",
        type: "short-answer",
        sourceRef: "여행과 교통: le voyage",
        promptKo: "‘여행’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le voyage",
      },
      {
        id: "fr-v-a2-02",
        type: "short-answer",
        sourceRef: "하루 일과 동사 (대명동사 포함): se reposer",
        promptKo: "‘쉬다, 휴식하다’를 뜻하는 프랑스어 대명동사를 쓰세요.",
        answer: "se reposer",
      },
      {
        id: "fr-v-a2-03",
        type: "short-answer",
        sourceRef: "부사와 전치사: jusqu'à",
        promptKo: "‘~까지’를 뜻하는 프랑스어 전치사 표현을 쓰세요.",
        answer: "jusqu'à",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/a2_flelex.js",
    kind: "vocab",
    level: "A2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-a2-flelex-01",
        type: "short-answer",
        sourceRef: "사회와 생활: le public",
        promptKo: "‘대중, 관객’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le public",
      },
      {
        id: "fr-v-a2-flelex-02",
        type: "short-answer",
        sourceRef: "동사 확장: valoir",
        promptKo: "‘~의 가치가 있다’를 뜻하는 프랑스어 동사를 쓰세요.",
        answer: "valoir",
      },
      {
        id: "fr-v-a2-flelex-03",
        type: "short-answer",
        sourceRef: "부사·기타: tantôt",
        promptKo: "‘때로는 ~, 때로는 ~’ 구조에 반복해 쓰는 프랑스어 부사를 쓰세요.",
        answer: "tantôt",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/b1.js",
    kind: "vocab",
    level: "B1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-b1-01",
        type: "short-answer",
        sourceRef: "일과 직장: le métier",
        promptKo: "‘직업(기술·전문성이 있는 일)’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le métier",
      },
      {
        id: "fr-v-b1-02",
        type: "short-answer",
        sourceRef: "자주 쓰는 동사구·표현: faire la queue",
        promptKo: "‘줄을 서다’를 뜻하는 프랑스어 표현을 쓰세요.",
        answer: "faire la queue",
      },
      {
        id: "fr-v-b1-03",
        type: "short-answer",
        sourceRef: "형용사와 연결 표현: dès que",
        promptKo: "‘~하자마자’를 뜻하는 프랑스어 연결 표현을 쓰세요.",
        answer: "dès que",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/b1_flelex.js",
    kind: "vocab",
    level: "B1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-b1-flelex-01",
        type: "short-answer",
        sourceRef: "사회와 제도: le crime",
        promptKo: "‘범죄, 중범죄’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le crime",
      },
      {
        id: "fr-v-b1-flelex-02",
        type: "short-answer",
        sourceRef: "추상·개념 명사: l'écho (m.)",
        promptKo: "‘메아리, 반향’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "l'écho (m.)",
      },
      {
        id: "fr-v-b1-flelex-03",
        type: "short-answer",
        sourceRef: "그 밖의 어휘: le sida",
        promptKo: "‘에이즈’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le sida",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/b1_flelex2.js",
    kind: "vocab",
    level: "B1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-b1-flelex2-01",
        type: "short-answer",
        sourceRef: "사회와 제도: l'alerte (f.)",
        promptKo: "‘경보, 경고’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "l'alerte (f.)",
      },
      {
        id: "fr-v-b1-flelex2-02",
        type: "short-answer",
        sourceRef: "형용사: clinique",
        promptKo: "‘임상의, 진료의’를 뜻하는 프랑스어 형용사를 쓰세요.",
        answer: "clinique",
      },
      {
        id: "fr-v-b1-flelex2-03",
        type: "short-answer",
        sourceRef: "부사와 연결어: environ",
        promptKo: "‘약, 대략’을 뜻하는 프랑스어 부사를 쓰세요.",
        answer: "environ",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/b2.js",
    kind: "vocab",
    level: "B2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-b2-01",
        type: "short-answer",
        sourceRef: "정치와 경제: le pouvoir",
        promptKo: "‘권력, 힘’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le pouvoir",
      },
      {
        id: "fr-v-b2-02",
        type: "short-answer",
        sourceRef: "핵심 동사 II: organiser",
        promptKo: "‘준비하다, 조직하다’를 뜻하는 프랑스어 동사를 쓰세요.",
        answer: "organiser",
      },
      {
        id: "fr-v-b2-03",
        type: "short-answer",
        sourceRef: "부사와 담화 연결어: bas / basse",
        promptKo: "‘낮은’을 뜻하는 프랑스어 형용사의 남성형과 여성형을 함께 쓰세요.",
        answer: "bas / basse",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/b2_flelex.js",
    kind: "vocab",
    level: "B2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-b2-flelex-01",
        type: "short-answer",
        sourceRef: "정치·사회·시사: la minorité",
        promptKo: "‘소수, 소수자’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la minorité",
      },
      {
        id: "fr-v-b2-flelex-02",
        type: "short-answer",
        sourceRef: "핵심 동사: élargir",
        promptKo: "‘넓히다, 확대하다’를 뜻하는 프랑스어 동사를 쓰세요.",
        answer: "élargir",
      },
      {
        id: "fr-v-b2-flelex-03",
        type: "short-answer",
        sourceRef: "그 밖의 어휘: la cuillère",
        promptKo: "‘숟가락’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la cuillère",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/b2_flelex2.js",
    kind: "vocab",
    level: "B2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-b2-flelex2-01",
        type: "short-answer",
        sourceRef: "정치·사회·시사: l'asile (m.)",
        promptKo: "‘망명, 피난처’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "l'asile (m.)",
      },
      {
        id: "fr-v-b2-flelex2-02",
        type: "short-answer",
        sourceRef: "추상·논증 명사: la cheville",
        promptKo: "‘발목’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la cheville",
      },
      {
        id: "fr-v-b2-flelex2-03",
        type: "short-answer",
        sourceRef: "그 밖의 어휘: le câlin",
        promptKo: "‘포옹, 껴안기’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le câlin",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/c1.js",
    kind: "vocab",
    level: "C1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-c1-01",
        type: "short-answer",
        sourceRef: "학술·지성 어휘: l'enjeu (m.)",
        promptKo: "‘쟁점, 관건’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "l'enjeu (m.)",
      },
      {
        id: "fr-v-c1-02",
        type: "short-answer",
        sourceRef: "문어와 논증의 동사: évoluer",
        promptKo: "‘변화하다, 발전하다’를 뜻하는 프랑스어 동사를 쓰세요.",
        answer: "évoluer",
      },
      {
        id: "fr-v-c1-03",
        type: "short-answer",
        sourceRef: "정밀한 형용사와 부사: le cas échéant",
        promptKo: "‘필요한 경우, 경우에 따라’를 뜻하는 프랑스어 표현을 쓰세요.",
        answer: "le cas échéant",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/c1_flelex.js",
    kind: "vocab",
    level: "C1",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-c1-flelex-01",
        type: "short-answer",
        sourceRef: "학술·지성 어휘: la synthèse",
        promptKo: "‘종합, 통합’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "la synthèse",
      },
      {
        id: "fr-v-c1-flelex-02",
        type: "short-answer",
        sourceRef: "이야기와 구어의 명사: le stupéfiant",
        promptKo: "‘마약, 마취제’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le stupéfiant",
      },
      {
        id: "fr-v-c1-flelex-03",
        type: "short-answer",
        sourceRef: "그 밖의 어휘: le fournisseur",
        promptKo: "‘공급업체, 납품업자’를 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le fournisseur",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/c2.js",
    kind: "vocab",
    level: "C2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-c2-01",
        type: "short-answer",
        sourceRef: "문체와 수사의 어휘: l'éloquence (f.)",
        promptKo: "‘웅변, 능변’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "l'éloquence (f.)",
      },
      {
        id: "fr-v-c2-02",
        type: "short-answer",
        sourceRef: "라틴어 직수입 표현 — 영어와 공유하는 자산: le statu quo",
        promptKo: "‘현상 유지’를 뜻하는 프랑스어 표현을 관사와 함께 쓰세요.",
        answer: "le statu quo",
      },
      {
        id: "fr-v-c2-03",
        type: "short-answer",
        sourceRef: "뉘앙스의 형용사와 부사: bof",
        promptKo: "시큰둥하게 ‘글쎄, 별로’라고 답할 때 쓰는 프랑스어 감탄사를 쓰세요.",
        answer: "bof",
      },
    ],
  },
  {
    sourcePath: "src/content/french/vocab/c2_flelex.js",
    kind: "vocab",
    level: "C2",
    status: FRENCH_EXERCISE_DRAFT_STATUS,
    questions: [
      {
        id: "fr-v-c2-flelex-01",
        type: "short-answer",
        sourceRef: "시사와 수사의 명사: le prolongement",
        promptKo: "‘연장, 연속, 연장선’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le prolongement",
      },
      {
        id: "fr-v-c2-flelex-02",
        type: "short-answer",
        sourceRef: "문어와 격식의 동사: croquer",
        promptKo: "‘와삭 깨물다, 스케치로 그려 내다’를 뜻하는 프랑스어 동사를 쓰세요.",
        answer: "croquer",
      },
      {
        id: "fr-v-c2-flelex-03",
        type: "short-answer",
        sourceRef: "그 밖의 어휘: le séquençage",
        promptKo: "‘염기서열 분석, 시퀀싱’을 뜻하는 프랑스어를 관사와 함께 쓰세요.",
        answer: "le séquençage",
      },
    ],
  },
];

export const frenchExerciseDraftPacks = [
  ...grammarDraftPacks,
  ...vocabDraftPacks,
];

export default frenchExerciseDraftPacks;
