// 일본어 핵심 어휘 시드 — JLPT N5~N4 중 빈도 최상위
// 조사/조동사는 분석 대부분 줄에 등장하므로 이 시드만으로 캐시 히트율 대폭 향상
// { base_form, pos, reading } 구조 — /api/admin/seed-dictionary가 이걸 Gemini에 배치로 의미 요청

export const SEED_JP_CORE = [
  // ── 조사 (빈도 가장 높음) ──────────────────
  { base_form: 'は', pos: '조사', reading: 'は' },
  { base_form: 'が', pos: '조사', reading: 'が' },
  { base_form: 'を', pos: '조사', reading: 'を' },
  { base_form: 'に', pos: '조사', reading: 'に' },
  { base_form: 'で', pos: '조사', reading: 'で' },
  { base_form: 'と', pos: '조사', reading: 'と' },
  { base_form: 'も', pos: '조사', reading: 'も' },
  { base_form: 'の', pos: '조사', reading: 'の' },
  { base_form: 'へ', pos: '조사', reading: 'へ' },
  { base_form: 'から', pos: '조사', reading: 'から' },
  { base_form: 'まで', pos: '조사', reading: 'まで' },
  { base_form: 'より', pos: '조사', reading: 'より' },
  { base_form: 'や', pos: '조사', reading: 'や' },
  { base_form: 'か', pos: '조사', reading: 'か' },
  { base_form: 'ね', pos: '조사', reading: 'ね' },
  { base_form: 'よ', pos: '조사', reading: 'よ' },
  { base_form: 'な', pos: '조사', reading: 'な' },
  { base_form: 'ぞ', pos: '조사', reading: 'ぞ' },
  { base_form: 'ばかり', pos: '조사', reading: 'ばかり' },
  { base_form: 'だけ', pos: '조사', reading: 'だけ' },
  { base_form: 'しか', pos: '조사', reading: 'しか' },
  { base_form: 'など', pos: '조사', reading: 'など' },
  { base_form: 'ので', pos: '조사', reading: 'ので' },
  { base_form: 'のに', pos: '조사', reading: 'のに' },
  { base_form: 'けれど', pos: '조사', reading: 'けれど' },
  { base_form: 'が', pos: '접속조사', reading: 'が' },

  // ── 조동사 / 보조동사 ─────────────────────
  { base_form: 'だ', pos: '조동사', reading: 'だ' },
  { base_form: 'です', pos: '조동사', reading: 'です' },
  { base_form: 'である', pos: '조동사', reading: 'である' },
  { base_form: 'ます', pos: '조동사', reading: 'ます' },
  { base_form: 'ない', pos: '조동사', reading: 'ない' },
  { base_form: 'た', pos: '조동사', reading: 'た' },
  { base_form: 'て', pos: '조동사', reading: 'て' },
  { base_form: 'れる', pos: '조동사', reading: 'れる' },
  { base_form: 'られる', pos: '조동사', reading: 'られる' },
  { base_form: 'せる', pos: '조동사', reading: 'せる' },
  { base_form: 'させる', pos: '조동사', reading: 'させる' },
  { base_form: 'たい', pos: '조동사', reading: 'たい' },
  { base_form: 'そうだ', pos: '조동사', reading: 'そうだ' },
  { base_form: 'らしい', pos: '조동사', reading: 'らしい' },
  { base_form: 'ようだ', pos: '조동사', reading: 'ようだ' },
  { base_form: 'べき', pos: '조동사', reading: 'べき' },
  { base_form: 'まい', pos: '조동사', reading: 'まい' },
  { base_form: 'う', pos: '조동사', reading: 'う' },
  { base_form: 'よう', pos: '조동사', reading: 'よう' },
  { base_form: 'いる', pos: '보조동사', reading: 'いる' },
  { base_form: 'ある', pos: '동사', reading: 'ある' },
  { base_form: 'おく', pos: '보조동사', reading: 'おく' },
  { base_form: 'しまう', pos: '보조동사', reading: 'しまう' },
  { base_form: 'くれる', pos: '보조동사', reading: 'くれる' },
  { base_form: 'あげる', pos: '보조동사', reading: 'あげる' },
  { base_form: 'もらう', pos: '보조동사', reading: 'もらう' },
  { base_form: 'みる', pos: '보조동사', reading: 'みる' },
  { base_form: 'いく', pos: '보조동사', reading: 'いく' },
  { base_form: 'くる', pos: '보조동사', reading: 'くる' },

  // ── 지시어 ────────────────────────────────
  { base_form: 'これ', pos: '대명사', reading: 'これ' },
  { base_form: 'それ', pos: '대명사', reading: 'それ' },
  { base_form: 'あれ', pos: '대명사', reading: 'あれ' },
  { base_form: 'どれ', pos: '대명사', reading: 'どれ' },
  { base_form: 'この', pos: '연체사', reading: 'この' },
  { base_form: 'その', pos: '연체사', reading: 'その' },
  { base_form: 'あの', pos: '연체사', reading: 'あの' },
  { base_form: 'どの', pos: '연체사', reading: 'どの' },
  { base_form: 'ここ', pos: '대명사', reading: 'ここ' },
  { base_form: 'そこ', pos: '대명사', reading: 'そこ' },
  { base_form: 'あそこ', pos: '대명사', reading: 'あそこ' },
  { base_form: 'どこ', pos: '대명사', reading: 'どこ' },
  { base_form: 'こう', pos: '부사', reading: 'こう' },
  { base_form: 'そう', pos: '부사', reading: 'そう' },
  { base_form: 'ああ', pos: '부사', reading: 'ああ' },
  { base_form: 'どう', pos: '부사', reading: 'どう' },

  // ── 인칭대명사 ────────────────────────────
  { base_form: '私', pos: '대명사', reading: 'わたし' },
  { base_form: '僕', pos: '대명사', reading: 'ぼく' },
  { base_form: '俺', pos: '대명사', reading: 'おれ' },
  { base_form: 'あなた', pos: '대명사', reading: 'あなた' },
  { base_form: '君', pos: '대명사', reading: 'きみ' },
  { base_form: '彼', pos: '대명사', reading: 'かれ' },
  { base_form: '彼女', pos: '대명사', reading: 'かのじょ' },

  // ── 의문사 ────────────────────────────────
  { base_form: '何', pos: '대명사', reading: 'なに' },
  { base_form: '誰', pos: '대명사', reading: 'だれ' },
  { base_form: 'いつ', pos: '부사', reading: 'いつ' },
  { base_form: 'なぜ', pos: '부사', reading: 'なぜ' },
  { base_form: 'どうして', pos: '부사', reading: 'どうして' },
  { base_form: 'いくつ', pos: '대명사', reading: 'いくつ' },
  { base_form: 'いくら', pos: '부사', reading: 'いくら' },

  // ── 최다 빈도 동사 ────────────────────────
  { base_form: 'する', pos: '동사', reading: 'する' },
  { base_form: 'なる', pos: '동사', reading: 'なる' },
  { base_form: '行く', pos: '동사', reading: 'いく' },
  { base_form: '来る', pos: '동사', reading: 'くる' },
  { base_form: '見る', pos: '동사', reading: 'みる' },
  { base_form: '聞く', pos: '동사', reading: 'きく' },
  { base_form: '話す', pos: '동사', reading: 'はなす' },
  { base_form: '言う', pos: '동사', reading: 'いう' },
  { base_form: '食べる', pos: '동사', reading: 'たべる' },
  { base_form: '飲む', pos: '동사', reading: 'のむ' },
  { base_form: '読む', pos: '동사', reading: 'よむ' },
  { base_form: '書く', pos: '동사', reading: 'かく' },
  { base_form: '買う', pos: '동사', reading: 'かう' },
  { base_form: '売る', pos: '동사', reading: 'うる' },
  { base_form: '会う', pos: '동사', reading: 'あう' },
  { base_form: '思う', pos: '동사', reading: 'おもう' },
  { base_form: '知る', pos: '동사', reading: 'しる' },
  { base_form: '分かる', pos: '동사', reading: 'わかる' },
  { base_form: '出る', pos: '동사', reading: 'でる' },
  { base_form: '入る', pos: '동사', reading: 'はいる' },
  { base_form: '出す', pos: '동사', reading: 'だす' },
  { base_form: '入れる', pos: '동사', reading: 'いれる' },
  { base_form: '立つ', pos: '동사', reading: 'たつ' },
  { base_form: '座る', pos: '동사', reading: 'すわる' },
  { base_form: '起きる', pos: '동사', reading: 'おきる' },
  { base_form: '寝る', pos: '동사', reading: 'ねる' },
  { base_form: '働く', pos: '동사', reading: 'はたらく' },
  { base_form: '休む', pos: '동사', reading: 'やすむ' },
  { base_form: '遊ぶ', pos: '동사', reading: 'あそぶ' },
  { base_form: '勉強する', pos: '동사', reading: 'べんきょうする' },
  { base_form: '使う', pos: '동사', reading: 'つかう' },
  { base_form: '作る', pos: '동사', reading: 'つくる' },
  { base_form: '持つ', pos: '동사', reading: 'もつ' },
  { base_form: '取る', pos: '동사', reading: 'とる' },
  { base_form: '待つ', pos: '동사', reading: 'まつ' },
  { base_form: '送る', pos: '동사', reading: 'おくる' },
  { base_form: '考える', pos: '동사', reading: 'かんがえる' },
  { base_form: '感じる', pos: '동사', reading: 'かんじる' },
  { base_form: '始める', pos: '동사', reading: 'はじめる' },
  { base_form: '終わる', pos: '동사', reading: 'おわる' },
  { base_form: '続ける', pos: '동사', reading: 'つづける' },
  { base_form: '戻る', pos: '동사', reading: 'もどる' },
  { base_form: '帰る', pos: '동사', reading: 'かえる' },
  { base_form: '歩く', pos: '동사', reading: 'あるく' },
  { base_form: '走る', pos: '동사', reading: 'はしる' },
  { base_form: '乗る', pos: '동사', reading: 'のる' },
  { base_form: '降りる', pos: '동사', reading: 'おりる' },

  // ── 최다 빈도 형용사 ──────────────────────
  { base_form: '良い', pos: '형용사', reading: 'よい' },
  { base_form: '悪い', pos: '형용사', reading: 'わるい' },
  { base_form: '大きい', pos: '형용사', reading: 'おおきい' },
  { base_form: '小さい', pos: '형용사', reading: 'ちいさい' },
  { base_form: '高い', pos: '형용사', reading: 'たかい' },
  { base_form: '低い', pos: '형용사', reading: 'ひくい' },
  { base_form: '新しい', pos: '형용사', reading: 'あたらしい' },
  { base_form: '古い', pos: '형용사', reading: 'ふるい' },
  { base_form: '多い', pos: '형용사', reading: 'おおい' },
  { base_form: '少ない', pos: '형용사', reading: 'すくない' },
  { base_form: '早い', pos: '형용사', reading: 'はやい' },
  { base_form: '遅い', pos: '형용사', reading: 'おそい' },
  { base_form: '長い', pos: '형용사', reading: 'ながい' },
  { base_form: '短い', pos: '형용사', reading: 'みじかい' },
  { base_form: '強い', pos: '형용사', reading: 'つよい' },
  { base_form: '弱い', pos: '형용사', reading: 'よわい' },
  { base_form: '熱い', pos: '형용사', reading: 'あつい' },
  { base_form: '寒い', pos: '형용사', reading: 'さむい' },
  { base_form: '暑い', pos: '형용사', reading: 'あつい' },
  { base_form: '冷たい', pos: '형용사', reading: 'つめたい' },
  { base_form: '美しい', pos: '형용사', reading: 'うつくしい' },
  { base_form: '面白い', pos: '형용사', reading: 'おもしろい' },
  { base_form: '楽しい', pos: '형용사', reading: 'たのしい' },
  { base_form: '難しい', pos: '형용사', reading: 'むずかしい' },
  { base_form: '易しい', pos: '형용사', reading: 'やさしい' },
  { base_form: '忙しい', pos: '형용사', reading: 'いそがしい' },
  { base_form: '欲しい', pos: '형용사', reading: 'ほしい' },
  { base_form: '好き', pos: '형용동사', reading: 'すき' },
  { base_form: '嫌い', pos: '형용동사', reading: 'きらい' },
  { base_form: '上手', pos: '형용동사', reading: 'じょうず' },
  { base_form: '下手', pos: '형용동사', reading: 'へた' },
  { base_form: '大事', pos: '형용동사', reading: 'だいじ' },
  { base_form: '大切', pos: '형용동사', reading: 'たいせつ' },
  { base_form: '大変', pos: '형용동사', reading: 'たいへん' },
  { base_form: '元気', pos: '형용동사', reading: 'げんき' },

  // ── 기본 명사 (시간) ──────────────────────
  { base_form: '今日', pos: '명사', reading: 'きょう' },
  { base_form: '明日', pos: '명사', reading: 'あした' },
  { base_form: '昨日', pos: '명사', reading: 'きのう' },
  { base_form: '今', pos: '명사', reading: 'いま' },
  { base_form: '朝', pos: '명사', reading: 'あさ' },
  { base_form: '昼', pos: '명사', reading: 'ひる' },
  { base_form: '夜', pos: '명사', reading: 'よる' },
  { base_form: '年', pos: '명사', reading: 'とし' },
  { base_form: '月', pos: '명사', reading: 'つき' },
  { base_form: '日', pos: '명사', reading: 'ひ' },
  { base_form: '週', pos: '명사', reading: 'しゅう' },
  { base_form: '時間', pos: '명사', reading: 'じかん' },
  { base_form: '時', pos: '명사', reading: 'とき' },
  { base_form: '分', pos: '명사', reading: 'ふん' },
  { base_form: '秒', pos: '명사', reading: 'びょう' },

  // ── 기본 명사 (일반) ──────────────────────
  { base_form: '人', pos: '명사', reading: 'ひと' },
  { base_form: '物', pos: '명사', reading: 'もの' },
  { base_form: '事', pos: '명사', reading: 'こと' },
  { base_form: '所', pos: '명사', reading: 'ところ' },
  { base_form: '国', pos: '명사', reading: 'くに' },
  { base_form: '家', pos: '명사', reading: 'いえ' },
  { base_form: '学校', pos: '명사', reading: 'がっこう' },
  { base_form: '会社', pos: '명사', reading: 'かいしゃ' },
  { base_form: '友達', pos: '명사', reading: 'ともだち' },
  { base_form: '名前', pos: '명사', reading: 'なまえ' },
  { base_form: '仕事', pos: '명사', reading: 'しごと' },
  { base_form: '手', pos: '명사', reading: 'て' },
  { base_form: '目', pos: '명사', reading: 'め' },
  { base_form: '耳', pos: '명사', reading: 'みみ' },
  { base_form: '口', pos: '명사', reading: 'くち' },
  { base_form: '頭', pos: '명사', reading: 'あたま' },
  { base_form: '顔', pos: '명사', reading: 'かお' },
  { base_form: '心', pos: '명사', reading: 'こころ' },
  { base_form: '水', pos: '명사', reading: 'みず' },
  { base_form: '火', pos: '명사', reading: 'ひ' },
  { base_form: '空', pos: '명사', reading: 'そら' },
  { base_form: '山', pos: '명사', reading: 'やま' },
  { base_form: '川', pos: '명사', reading: 'かわ' },
  { base_form: '海', pos: '명사', reading: 'うみ' },
  { base_form: '道', pos: '명사', reading: 'みち' },
  { base_form: '駅', pos: '명사', reading: 'えき' },

  // ── 숫자 ──────────────────────────────────
  { base_form: '一', pos: '명사', reading: 'いち' },
  { base_form: '二', pos: '명사', reading: 'に' },
  { base_form: '三', pos: '명사', reading: 'さん' },
  { base_form: '四', pos: '명사', reading: 'よん' },
  { base_form: '五', pos: '명사', reading: 'ご' },
  { base_form: '六', pos: '명사', reading: 'ろく' },
  { base_form: '七', pos: '명사', reading: 'なな' },
  { base_form: '八', pos: '명사', reading: 'はち' },
  { base_form: '九', pos: '명사', reading: 'きゅう' },
  { base_form: '十', pos: '명사', reading: 'じゅう' },
  { base_form: '百', pos: '명사', reading: 'ひゃく' },
  { base_form: '千', pos: '명사', reading: 'せん' },
  { base_form: '万', pos: '명사', reading: 'まん' },

  // ── 접속사 / 부사 ─────────────────────────
  { base_form: 'そして', pos: '접속사', reading: 'そして' },
  { base_form: 'しかし', pos: '접속사', reading: 'しかし' },
  { base_form: 'でも', pos: '접속사', reading: 'でも' },
  { base_form: 'また', pos: '접속사', reading: 'また' },
  { base_form: 'だから', pos: '접속사', reading: 'だから' },
  { base_form: 'それで', pos: '접속사', reading: 'それで' },
  { base_form: 'ところで', pos: '접속사', reading: 'ところで' },
  { base_form: 'とても', pos: '부사', reading: 'とても' },
  { base_form: '少し', pos: '부사', reading: 'すこし' },
  { base_form: 'たくさん', pos: '부사', reading: 'たくさん' },
  { base_form: 'もう', pos: '부사', reading: 'もう' },
  { base_form: 'まだ', pos: '부사', reading: 'まだ' },
  { base_form: 'いつも', pos: '부사', reading: 'いつも' },
  { base_form: 'よく', pos: '부사', reading: 'よく' },
  { base_form: 'ちょっと', pos: '부사', reading: 'ちょっと' },
  { base_form: '全部', pos: '부사', reading: 'ぜんぶ' },
  { base_form: '一緒', pos: '명사', reading: 'いっしょ' },
  { base_form: '本当', pos: '부사', reading: 'ほんとう' },
];
