// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium,webkit} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:3102',out=process.env.QA_OUT||'/private/tmp/manabi-unified-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,lesson_explanation_ko text,conversation_script text,direction text NOT NULL DEFAULT 'read',source_pdf_id uuid,page_start integer,page_end integer,document_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE,SELECT,UPDATE ON SEQUENCE reading_materials_id_seq TO authenticated;GRANT ALL ON reading_materials TO service_role;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql','20260910024120_classroom_study_flow.sql','20260910070535_textbook_teaching_annotations.sql','20260911051522_classroom_source_anchors.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Chinese',team:{key:'fixture-class',root:true,name:'목요일의 중국어',lang:'Chinese',bookKey:'fixture-book',chapterId:10,pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.query('INSERT INTO auth.users VALUES($1)',[uid]);await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const words=['图书馆','学生','老师','学校','学习','明天','今天','谢谢','朋友','中文','工作','欢迎','这里','那里'];
const book={sequence:[],dictionary:{},status:'completed',failed_indices:[],metadata:{language:'Chinese',book:{key:'fixture-book',order:1}}};
words.forEach((text,i)=>{const id=`id_${i}_word`,br=`br_${i}_end_fixture`;book.sequence.push(id,br);book.dictionary[id]={text,meaning:`뜻 ${i+1}`,furigana:i===0?'tú shū guǎn':'',pos:'명사',base:text};book.dictionary[br]={text:'\n',pos:'개행'};});
for(const [i,text]of ['我们','明天','见','。'].entries()){const id=`id_14_${i}`;book.sequence.push(id);book.dictionary[id]={text,meaning:['우리','내일','보다',''][i],pos:i===3?'기호':'표현'};}
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(10,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 함께 공부하는 하루',words.join('\n')+'\n我们明天见。','private',book]);
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(11,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 다음 과',words.join('\n'),'private',{...book,metadata:{...book.metadata,book:{key:'fixture-book',order:2}}}]);
await db.exec("select setval('reading_materials_id_seq',20)");
const engine=process.env.QA_BROWSER||'chromium',touch=process.env.QA_TOUCH==='1',activate=touch?'tap':'click';
assert(['chromium','webkit'].includes(engine),'QA_BROWSER must be chromium or webkit');
const browser=await (engine==='webkit'?webkit:chromium).launch({...(engine==='chromium'?{executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{}),headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:touch,serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const tabletState={dictionaryDelay:0,lookups:0};
const report={engine,touch,checks:[],errors:[],screens:[]},writes=[];
await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
// Synthetic auth belongs to the intercepted client/API fixtures. Strip it from
// server page requests without a second fetch/fulfill lifecycle for prefetches.
await context.route(base+'/**',route=>route.continue(new URL(route.request().url()).pathname.startsWith('/_next/static/')?{}:{headers:{...route.request().headers(),cookie:''}}));
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:uid,display_name:'수업 검수',role:'teacher',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(['classroom_append_entry','classroom_append_study'].includes(table)){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query(table==='classroom_append_study'?'select classroom_append_study($1,$2,$3,$4,$5) result':'select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation,...(table==='classroom_append_study'?[body.p_seed]:[])])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  const bookKey=url.searchParams.get('processed_json->metadata->book->>key');if(bookKey?.startsWith('eq.'))rows=rows.filter(row=>row.processed_json.metadata.book?.key===bookKey.slice(3));
  const select=url.searchParams.get('select')||'';
  if(select.includes('processed_json->status'))rows=rows.map(row=>({...row,status:row.processed_json.status,book:row.processed_json.metadata.book}));
  if(select&&select!=='*'&&!select.includes('->'))rows=rows.map(row=>Object.fromEntries(select.split(',').map(key=>key.trim()).map(key=>[key,row[key]])));
  return send(object?(rows[0]||null):rows);
 }
 if(table==='morpheme_dictionary'){tabletState.lookups++;if(tabletState.dictionaryDelay)await new Promise(resolve=>setTimeout(resolve,tabletState.dictionaryDelay));return send(object?{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}:[{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}]);}
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){
 await page.waitForTimeout(2600);await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'로그인',exact:true}).last()[activate]();await page.waitForURL('**/home');
 // Complete the fixture login landing before a hard navigation. WebKit can
 // report requests interrupted during the document swap as access-control errors.
 await page.getByRole('heading',{name:/첫 표현을 담아/}).waitFor();
 await page.getByRole('heading',{name:/말이 태어나는 곳을/}).waitFor();
}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}

let annotationLost=false;
await context.route('**/api/materials/*/annotations*',async r=>{
 try{await db.exec('RESET ROLE;SET ROLE service_role');
 if(r.request().method()==='POST'){
  const b=r.request().postDataJSON();
  const result=(await db.query('select save_textbook_annotation($1,10,$2,$3,$4) result',[uid,b.operation,b.annotation,{sequence:book.sequence,dictionary:book.dictionary}])).rows[0].result;
  if(annotationLost){annotationLost=false;return r.abort('failed');}
  return r.fulfill({json:{annotation:result}});
 }
 const materialId=Number(new URL(r.request().url()).pathname.split('/')[3]);
 const rows=(await db.query('select * from textbook_annotations where material_id=$1 order by created_at',[materialId])).rows;
 const history=(await db.query('select * from textbook_annotation_revisions order by created_at desc')).rows;
 return r.fulfill({json:{materialId:'10',canEdit:true,annotations:rows,history}});
 }catch(e){return r.fulfill({status:409,json:{error:e.message,conflict:true}});}finally{await db.exec('RESET ROLE;SET ROLE authenticated');}
});
try {
 if(process.env.QA_TABLET==='1'){await (await import('./classroom-tablet.scenario.mjs')).runTabletScenario({page,context,base,out,day,db,check,waitFor,current,report,writes,activate,tabletState});}
 else {
 await page.goto(base+'/class/fixture-class');
 await page.getByRole('heading',{name:'목요일의 중국어',exact:true}).waitFor();
 assert.equal(await page.locator('a.classroom-back[href="/class"]').count(),0);
 assert.equal(await page.getByRole('link',{name:'웹앱 홈'}).getAttribute('href'),'/home');
 await page.getByRole('button',{name:'설정',exact:true})[activate]();
 const settings=page.getByRole('region',{name:'이 수업 설정'});await settings.waitFor();
 await settings.getByRole('textbox',{name:'팀 이름'}).fill('목요일의 중국어 · 함께 읽는 수업');
 await settings.getByRole('button',{name:'설정 저장'})[activate]();
 await settings.getByText('설정을 저장했어요.',{exact:true}).waitFor();
 assert.equal((await db.query('select processed_json from reading_materials where id=1')).rows[0].processed_json.metadata.team.name,'목요일의 중국어 · 함께 읽는 수업');
 await settings.getByRole('button',{name:'닫기',exact:true})[activate]();
 check('independent team home, explicit app home and in-team teacher settings');
 const start=page.getByRole('link',{name:'수업 이어하기',exact:true});assert((await start.getAttribute('href')).includes('class=fixture-class'));
 await start[activate]();await page.waitForURL('**/viewer/10?**');
 const dock=page.getByRole('complementary',{name:'교재 안 수업 도구'});await dock.waitFor();
 check('one start action opens the actual textbook and teacher tools');
 await page.goto(base+`/class/fixture-class/live?day=${day}`);
 await page.waitForURL('**/viewer/10?**');await dock.waitFor();
 assert.equal(new URL(page.url()).searchParams.get('day'),day);
 check('existing live link directly opens textbook without an input-page detour');
 const baseline=(await db.query('select raw_text,processed_json from reading_materials where id=10')).rows[0];
 await page.locator('[data-tid="id_0_word"]')[activate]();
 await dock.getByRole('button',{name:'수업용 뜻 수정',exact:true})[activate]();
 await dock.getByRole('textbox',{name:'수업용 뜻',exact:true}).fill('책을 읽고 빌리는 곳');
 await dock.getByRole('button',{name:'크게 보기',exact:true})[activate]();
 let dialog=page.getByRole('dialog',{name:'학생에게 보여주는 설명'});await dialog.waitFor();
 await dialog.getByText('책을 읽고 빌리는 곳',{exact:true}).waitFor();
 const before=(await current()).raw_text;
 await dialog.getByRole('button',{name:'교재로 돌아가기 ×'})[activate]();
 assert.equal((await current()).raw_text,before);
 await dock.getByRole('button',{name:'오늘 표현에 추가',exact:true})[activate]();
 await waitFor(async()=>(await current()).raw_text.includes('图书馆'));
 check('inline classroom meaning, display without saving, explicit add without navigation');
 await page.getByRole('navigation',{name:'수업 도구'}).getByRole('button',{name:/오늘 표현/})[activate]();
 await dock.getByRole('button',{name:'图书馆 뜻 수정'})[activate]();
 await dock.getByRole('textbox',{name:'수업용 뜻',exact:true}).fill('도서관 · 책을 빌리는 곳');
 await dock.getByRole('button',{name:'뜻 저장',exact:true})[activate]();
 await dock.getByText('도서관 · 책을 빌리는 곳',{exact:true}).waitFor();
 check('teacher edits a recorded expression in the same panel');
 await page.getByRole('navigation',{name:'수업 도구'}).getByRole('button',{name:'표현 찾기',exact:true})[activate]();
 const search=dock.getByRole('textbox',{name:'단어·표현 찾기'});await search.fill('你好');await search.press('Enter');
 await waitFor(async()=>await dock.getByRole('textbox',{name:'핵심 뜻',exact:true}).inputValue()==='안녕하세요');
 await dock.getByRole('button',{name:'오늘 표현에 추가',exact:true})[activate]();
 await waitFor(async()=>(await current()).raw_text.includes('你好'));
 assert.equal(await page.getByRole('dialog').count(),0);
 check('manual expressions use the same add action, without opening an unwanted presentation');
 await page.locator('[data-tid="id_1_word"]')[activate]();
 await dock.getByRole('button',{name:'설명 추가',exact:true})[activate]();
 await dock.getByRole('textbox',{name:'교재 설명 입력'}).fill('이 부분은 다음 수업에도 함께 확인합니다.');
 await dock.getByRole('button',{name:'교재에 저장',exact:true})[activate]();
 await dock.getByText('교재에 저장했어요.',{exact:false}).waitFor();
 await db.exec('RESET ROLE');assert.equal((await db.query('select count(*)::int n from textbook_annotations')).rows[0].n,1);await db.exec('SET ROLE authenticated');
 check('shared explanation added beside textbook without changing the dated class note');
 for(const viewport of [{width:1440,height:1000},{width:1024,height:768},{width:768,height:1024},{width:390,height:844}]){
  await page.setViewportSize(viewport);await page.locator('[data-tid="id_2_word"]')[activate]();
  await page.waitForTimeout(250);
  if(viewport.width<1100){const bounds=await page.evaluate(()=>({word:document.querySelector('[data-tid="id_2_word"]').getBoundingClientRect().toJSON(),panel:document.querySelector('.class-reader-dock').getBoundingClientRect().toJSON(),nav:document.querySelector('.class-workspace-topbar').getBoundingClientRect().toJSON()}));assert(bounds.word.bottom<=bounds.panel.top-4&&bounds.word.top>=bounds.nav.bottom,`selected word remains visible at ${viewport.width}`);}
  const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+1||r.left< -1)}).slice(0,30).map(e=>({tag:e.tagName,cls:e.className,left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right,text:e.textContent?.slice(0,100)}))}));if(overflow.scroll>overflow.width+1)console.log(JSON.stringify(overflow));
  assert.equal(overflow.scroll>overflow.width+1,false,`overflow ${viewport.width}`);
  await dock.getByRole('button',{name:'크게 보기',exact:true})[activate]();await dialog.waitFor();
  await dialog.getByRole('button',{name:'뜻 가리기'})[activate]();
  await page.screenshot({path:out+`/presentation-${viewport.width}.png`});
  await dialog.getByRole('button',{name:'교재로 돌아가기 ×'})[activate]();
  await page.screenshot({path:out+`/reader-${viewport.width}.png`});
  check(`teacher reading and presentation at ${viewport.width}x${viewport.height}`);
 }
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('navigation',{name:'수업 도구'}).getByRole('button',{name:'마무리',exact:true})[activate]();
 await dock.getByRole('heading',{name:'오늘 수업을 확인하세요'}).waitFor();
 await dock.getByRole('link',{name:'팀 홈으로',exact:true})[activate]();
 await page.waitForURL('**/class/fixture-class');
 await page.getByRole('heading',{name:'목요일의 중국어 · 함께 읽는 수업',exact:true}).waitFor();
 await page.screenshot({path:out+'/team-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/team-mobile.png'});
 check('summary returns to independent team home without requiring publication');
 assert.deepEqual((await db.query('select raw_text,processed_json from reading_materials where id=10')).rows[0],baseline);
 assert.equal(writes.filter(w=>['user_vocabulary','persist_vocab_grade','review_events'].includes(w.table)).length,0);
 check('teacher class operations preserve original textbook and personal review');
 await page.getByRole('button',{name:'설정',exact:true})[activate]();
 await settings.getByRole('combobox',{name:'수업 교재',exact:true}).selectOption('');
 await settings.getByRole('button',{name:'설정 저장'})[activate]();
 await settings.getByText('설정을 저장했어요.',{exact:true}).waitFor();
 await page.goto(base+`/class/fixture-class/live?day=${day}`);await dock.waitFor();
 await dock.getByRole('textbox',{name:'단어·표현 찾기'}).fill('欢迎');
 await dock.getByRole('textbox',{name:'단어·표현 찾기'}).press('Enter');
 await waitFor(async()=>await dock.getByRole('textbox',{name:'핵심 뜻',exact:true}).inputValue()==='안녕하세요');
 await dock.getByRole('button',{name:'오늘 표현에 추가',exact:true})[activate]();
 await waitFor(async()=>(await current()).raw_text.includes('欢迎'));
 assert.equal(await page.getByRole('link',{name:'웹앱 홈'}).getAttribute('href'),'/home');
 check('class without a linked textbook uses the same lookup and recording tools');
 assert.deepEqual(report.errors,[]);
 }
} catch(error){report.failure=error.stack;await page.screenshot({path:out+'/failure.png'}).catch(()=>{});throw error;}
finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await db.close();}
