// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {build} from 'vite';
import path from 'node:path';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:8910',out=process.env.QA_OUT||'/private/tmp/manabi-class-copy-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,lesson_explanation_ko text,conversation_script text,direction text NOT NULL DEFAULT 'read',source_pdf_id uuid,page_start integer,page_end integer,document_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE,SELECT,UPDATE ON SEQUENCE reading_materials_id_seq TO authenticated;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql','20260910024120_classroom_study_flow.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Chinese',team:{key:'fixture-class',root:true,name:'목요일의 중국어',lang:'Chinese',bookKey:'fixture-book',chapterId:10,pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.query('INSERT INTO auth.users VALUES($1)',[uid]);await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const words=['图书馆','学生','老师','学校','学习','明天','今天','谢谢','朋友','中文','工作','欢迎','这里','那里'];
const book={sequence:[],dictionary:{},status:'completed',failed_indices:[],metadata:{language:'Chinese',book:{key:'fixture-book',order:1}}};
words.forEach((text,i)=>{const id=`id_${i}_word`,br=`br_${i}_end_fixture`;book.sequence.push(id,br);book.dictionary[id]={text,meaning:`뜻 ${i+1}`,furigana:i===0?'tú shū guǎn':'',pos:'명사',base:text};book.dictionary[br]={text:'\n',pos:'개행'};});
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(10,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 함께 공부하는 하루',words.join('\n'),'private',book]);
await db.exec("select setval('reading_materials_id_seq',20)");
const student='00000000-0000-4000-8000-000000000088';
await db.exec('RESET ROLE');await db.query('INSERT INTO auth.users VALUES($1)',[student]);
const browser=await chromium.launch({executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:student,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:student,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const report={checks:[],errors:[],screens:[]},writes=[];
await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
await context.route(base+'/**',async route=>{if(new URL(route.request().url()).pathname.startsWith('/_next/static/'))return route.continue();const response=await route.fetch({headers:{...route.request().headers(),cookie:''},timeout:180000});await route.fulfill({response});});
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:student,display_name:'수업 검수',role:'admin',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(['classroom_append_entry','classroom_append_study'].includes(table)){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query(table==='classroom_append_study'?'select classroom_append_study($1,$2,$3,$4,$5) result':'select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation,...(table==='classroom_append_study'?[body.p_seed]:[])])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  const bookKey=url.searchParams.get('processed_json->metadata->book->>key');if(bookKey?.startsWith('eq.'))rows=rows.filter(row=>row.processed_json.metadata.book?.key===bookKey.slice(3));
  const select=url.searchParams.get('select')||'';
  if(select.includes('processed_json->status'))rows=rows.map(row=>({...row,status:row.processed_json.status,book:row.processed_json.metadata.book}));
  if(select.includes('source_ref'))rows=rows.filter(row=>row.processed_json.metadata.source_ref).map(row=>({...row,source_ref:row.processed_json.metadata.source_ref}));
  return send(object?(rows[0]||null):rows);
 }
 if(table==='morpheme_dictionary')return send(object?{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}:[{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}]);
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});

const status={failCopy:false,failContext:false},contexts=[],vocab=[];
const admin={rpc:async(name,a)=>{try{
 if(status.failCopy)return {error:{code:'offline'}};
 const args=[a.p_owner,a.p_root,a.p_generation,a.p_source];
 const sql=name==='classroom_copy_state'?'select classroom_copy_state($1,$2,$3,$4,$5,$6) result':'select classroom_update_copy($1,$2,$3,$4,$5,$6,$7) result';
 args.push(...(name==='classroom_copy_state'?[a.p_create,a.p_preferred]:[a.p_expected,a.p_source_revision,a.p_next]));
 return {data:(await db.query(sql,args)).rows[0].result};
 }catch(error){return {error:{code:error.code,message:error.message}};}},from:()=>{const q={select:()=>q,eq:()=>q,order:()=>q,range:async()=>({data:[]})};return q;}};
globalThis.__classQA={user,access:{admin,root:{id:1},team:{pwGen:1}}};
await build({configFile:false,resolve:{alias:{'@':path.resolve('src')}},build:{ssr:'src/app/api/class/[team]/copy/route.js',minify:false,outDir:out,emptyOutDir:false,rollupOptions:{output:{entryFileNames:'copy-route.mjs'}}},plugins:[{name:'fixture-auth-only',transform(code,id){
 if(id.endsWith('/src/lib/server/auth.js'))return 'export async function requireUser(){return {user:globalThis.__classQA.user}}';
 if(id.endsWith('/src/app/api/class/[team]/route.js'))return 'export async function authorizeTeamRequest(request){return request.headers.get("x-class-token")==="fixture-class-token"?globalThis.__classQA.access:{error:Response.json({error:"expired"},{status:401})}}';
}}]});
const {POST}=await import(out+'/copy-route.mjs');
await context.route('**/api/class/fixture-class',r=>r.fulfill({json:{team:{key:'fixture-class',name:'목요일의 중국어',lang:'Chinese',bookKey:'fixture-book',bookTitle:'실전 중국어',bookTotal:1},notes:[],chapters:[{id:10,title:'실전 중국어 — 함께 공부하는 하루',order:1,status:'completed'}]}}));
await context.route('**/api/class/fixture-class/copy',async r=>{const response=await POST(new Request(r.request().url(),{method:'POST',headers:r.request().headers(),body:r.request().postData()}),{params:Promise.resolve({team:'fixture-class'})});await r.fulfill({status:response.status,json:await response.json()});});
await context.route('**/rest/v1/user_vocabulary**',async r=>{
 if(r.request().method()==='POST'){const row=r.request().postDataJSON();if(!vocab.some(v=>v.word_text===row.word_text&&v.user_id===row.user_id))vocab.push(row);assert(r.request().headers().prefer?.includes('ignore-duplicates'));return r.fulfill({headers:cors,json:[]});}
 return r.fulfill({headers:cors,json:vocab});
});
await context.route('**/api/learning/vocabulary',async r=>{
 if(r.request().method()!=='POST')return r.fulfill({json:{contexts:[]}});
 const body=r.request().postDataJSON();if(status.failContext)return r.fulfill({status:503,json:{error:'검수 연결 실패'}});
 assert.equal(body.word.user_id,student);assert.equal(body.source.kind,'reading');assert.notEqual(body.source.materialId,'10');contexts.push(body);return r.fulfill({json:{contextAdded:true}});
});
await context.addInitScript(()=>{localStorage.setItem('class_unlock:fixture-class',JSON.stringify({token:'fixture-class-token',exp:Date.now()+86400000,pwGen:1,name:'목요일의 중국어'}));});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'로그인',exact:true}).last().click();await page.waitForURL('**/home');}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}


try {
await page.goto(base+'/class/fixture-class');await page.getByRole('button',{name:/읽기 시작 →/}).waitFor();
await page.getByRole('button',{name:/읽기 시작 →/}).click();await page.waitForURL(/\/viewer\/\d+/);await page.locator('[data-tid="id_0_word"]').waitFor();
const copyId=/viewer\/(\d+)/.exec(page.url())[1];assert.notEqual(copyId,'10');assert.equal(await page.getByRole('complementary',{name:'교재 안 수업 도구'}).count(),0);check('student opens one private canonical copy with no teacher controls');
await page.getByRole('link',{name:'← 수업으로',exact:true}).click();await page.getByRole('button',{name:/읽기 시작 →/}).click();await page.waitForURL(new RegExp('/viewer/'+copyId));
assert.equal((await db.query("select count(*)::int n from reading_materials where owner_id=$1 and processed_json#>>'{metadata,source_ref}'='10'",[student])).rows[0].n,1);check('return and reopen uses same copy ID');
const copyBefore=(await db.query('select * from reading_materials where id=$1',[copyId])).rows[0];
const personal=structuredClone(copyBefore.processed_json);personal.dictionary.id_0_word.meaning='학생이 직접 적은 뜻';await db.query('update reading_materials set processed_json=$1 where id=$2',[personal,copyId]);
const source=structuredClone(book);source.dictionary.id_0_word.meaning='선생님의 새 뜻';source.dictionary.id_1_word.meaning='학생이라는 새 설명';await db.query('update reading_materials set processed_json=$1 where id=10',[source]);
await page.reload();await page.getByRole('button',{name:'변경 내용 보기',exact:true}).waitFor();assert.equal((await db.query('select processed_json from reading_materials where id=$1',[copyId])).rows[0].processed_json.dictionary.id_1_word.meaning,'뜻 2');check('new source stays unapplied until explicitly reviewed');
await page.getByRole('button',{name:'변경 내용 보기',exact:true}).click();const dialog=page.getByRole('dialog',{name:'수업의 새 내용'});await dialog.waitFor();await page.screenshot({path:out+'/update-desktop.png'});report.screens.push('update-desktop.png');
await dialog.getByRole('button',{name:'변경 내용 반영',exact:true}).click();await dialog.waitFor({state:'hidden'});
const updated=(await db.query('select * from reading_materials where id=$1',[copyId])).rows[0];assert.equal(updated.processed_json.dictionary.id_0_word.meaning,'학생이 직접 적은 뜻');assert.equal(updated.processed_json.dictionary.id_1_word.meaning,'학생이라는 새 설명');assert.deepEqual(updated.processed_json.sequence,copyBefore.processed_json.sequence);check('explicit update preserves student correction and original token IDs');
await page.getByRole('link',{name:'← 수업으로',exact:true}).click();status.failCopy=true;await page.getByRole('button',{name:/읽기 시작 →/}).click();await page.getByText('자료를 처리하지 못했어요. 기존 자료는 유지됩니다.',{exact:true}).waitFor();assert(page.url().includes('/class/fixture-class'));status.failCopy=false;check('copy lookup failure never silently creates a duplicate');
for(const width of [1440,390,320]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${out}/student-${width}.png`});report.screens.push(`student-${width}.png`);}check('student class home has no overflow on desktop and mobile');
await page.setViewportSize({width:1440,height:1000});
const intent=await page.evaluate(async()=>{
 const id=crypto.randomUUID();const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('manabi-class-save-intents',1);r.onupgradeneeded=()=>r.result.createObjectStore('intents',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 await new Promise((resolve,reject)=>{const tx=db.transaction('intents','readwrite');tx.objectStore('intents').put({id,at:Date.now(),ownerId:null,team:'fixture-class',materialId:10,tokenId:'id_0_word',grade:3,word:{text:'图书馆',meaning:'학생이 직접 적은 뜻',reading:'tú shū guǎn',pos:'명사',language:'Chinese',sourceSentence:'图书馆'}});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();sessionStorage.setItem(`class-save-login:${id}`,'requested');return id;
});
status.failContext=true;await page.goto(base+'/class/fixture-class?classSave='+intent);await page.getByText('단어는 저장됐지만 문맥 연결을 마치지 못했어요. 다시 시도해 주세요.',{exact:true}).waitFor();assert.equal(vocab.length,1);const savedStats=JSON.stringify(vocab[0]);check('login intent records partial success and retains retry after context failure');
status.failContext=false;await page.getByRole('button',{name:'저장 재시도',exact:true}).click();await page.waitForURL(/classSaved=1/);await page.locator('[data-tid="id_0_word"][data-selected="true"]').waitFor();assert.equal(vocab.length,1);assert.equal(JSON.stringify(vocab[0]),savedStats);assert.equal(contexts.length,1);assert.equal(contexts[0].source.materialId,copyId);assert(page.url().includes('sourceToken=id_0_word'));check('resumed explicit save returns to exact word in canonical copy without resetting FSRS');
assert.equal(await page.evaluate(id=>sessionStorage.getItem(`class-save-login:${id}`),intent),null);check('completed request is consumed only after vocabulary and context success');
assert.equal(report.errors.length,0,report.errors.join('\n'));check('no page runtime errors');
} catch(error){console.error(error);report.failure=error.message;await page.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/failure.html',await page.content());process.exitCode=1;}
fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();await db.close();
