import {boardMenus} from './teaching-board-menu-checks.mjs';
// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium,webkit} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:3108',out=process.env.QA_OUT||'/private/tmp/manabi-classroom-ink-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,lesson_explanation_ko text,conversation_script text,direction text NOT NULL DEFAULT 'read',source_pdf_id uuid,page_start integer,page_end integer,document_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE,SELECT,UPDATE ON SEQUENCE reading_materials_id_seq TO authenticated;GRANT ALL ON reading_materials TO service_role;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql','20260910024120_classroom_study_flow.sql','20260910070535_textbook_teaching_annotations.sql','20260911072945_classroom_source_anchors.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Japanese',team:{key:'fixture-class',root:true,name:'목요일의 일본어',lang:'Japanese',bookKey:'fixture-book',chapterId:10,pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.query('INSERT INTO auth.users VALUES($1)',[uid]);await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const words=['图书馆','学生','老师','学校','学习','明天','今天','谢谢','朋友','中文','工作','欢迎','这里','那里'];
const book={sequence:[],dictionary:{},status:'completed',failed_indices:[],metadata:{language:'Chinese',book:{key:'fixture-book',order:1}}};
words.forEach((text,i)=>{const id=`id_${i}_word`,br=`br_${i}_end_fixture`;book.sequence.push(id,br);book.dictionary[id]={text,meaning:`뜻 ${i+1}`,furigana:i===0?'tú shū guǎn':'',pos:'명사',base:text};book.dictionary[br]={text:'\n',pos:'개행'};});
for(const [i,text]of ['我们','明天','见','。'].entries()){const id=`id_14_${i}`;book.sequence.push(id);book.dictionary[id]={text,meaning:['우리','내일','보다',''][i],pos:i===3?'기호':'표현'};}
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(10,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 함께 공부하는 하루',words.join('\n')+'\n我们明天见。','private',book]);
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(11,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 다음 과',words.join('\n'),'private',{...book,metadata:{...book.metadata,book:{key:'fixture-book',order:2}}}]);
await db.exec("select setval('reading_materials_id_seq',20)");
const engine=process.env.QA_BROWSER||'chromium',touch=process.env.QA_TOUCH==='1',activate=touch?'tap':'click';
assert(['chromium','webkit'].includes(engine),'QA_BROWSER must be chromium or webkit');
const browser=await (engine==='webkit'?webkit:chromium).launch({...(engine==='chromium'?{executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{}),headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:touch,serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const tabletState={dictionaryDelay:0,lookups:0};
const report={engine,touch,checks:[],errors:[],screens:[],failedRequests:[],expectedTransport:[]},writes=[];
let replacingDocument=false,cancelledHomePrefetch=false,revisionConflicts=0;
await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
// Vercel's injected review toolbar is hosting chrome, outside the app flow.
// Stub only that script; application console failures still fail verification.
await context.route('https://vercel.live/_next-live/feedback/feedback.js',r=>r.fulfill({contentType:'application/javascript',body:''}));
// Synthetic auth belongs to the intercepted client/API fixtures. Strip it from
// server page requests without a second fetch/fulfill lifecycle for prefetches.
await context.route(base+'/**',route=>route.continue(new URL(route.request().url()).pathname.startsWith('/_next/static/')?{}:{headers:{...route.request().headers(),cookie:''}}));
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:uid,display_name:'수업 검수',role:'teacher',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(['classroom_append_entry','classroom_append_study'].includes(table)){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query(table==='classroom_append_study'?'select classroom_append_study($1,$2,$3,$4,$5) result':'select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation,...(table==='classroom_append_study'?[body.p_seed]:[])])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){if(error.code==='40001'&&table==='viewer_replace_analysis'){revisionConflicts++;report.expectedTransport.push('stale background analysis rejected by SQL revision check');}return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  const bookKey=url.searchParams.get('processed_json->metadata->book->>key');if(bookKey?.startsWith('eq.'))rows=rows.filter(row=>row.processed_json.metadata.book?.key===bookKey.slice(3));
  const select=url.searchParams.get('select')||'';
  if(select.includes('processed_json->status'))rows=rows.map(row=>({...row,status:row.processed_json.status,book:row.processed_json.metadata.book}));
  if(select&&select!=='*'&&!select.includes('->'))rows=rows.map(row=>Object.fromEntries(select.split(',').map(key=>key.trim()).map(key=>[key,row[key]])));
  return send(object?(rows[0]||null):rows);
 }
 if(table==='morpheme_dictionary'){tabletState.lookups++;if(tabletState.dictionaryDelay)await new Promise(resolve=>setTimeout(resolve,tabletState.dictionaryDelay));return send(object?{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}:[{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}]);}
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{
 if(m.type()!=='error'||m.text().startsWith('WebSocket connection')||(lookupError&&m.text().includes('503')))return;
 if(cancelledHomePrefetch&&m.text().startsWith('Failed to fetch RSC payload for '+base+'/home')){cancelledHomePrefetch=false;report.expectedTransport.push('home link prefetch cancelled while replacing the test document');return;}
 if(revisionConflicts>0&&m.text().includes('409 (Conflict)')){revisionConflicts--;return;}
 report.errors.push(m.text());console.log('browser-console',m.text());
});
page.on('requestfailed',request=>{const url=new URL(request.url());report.failedRequests.push(url.origin+url.pathname);if(replacingDocument&&url.pathname==='/home'&&request.failure()?.errorText==='cancelled')cancelledHomePrefetch=true;});
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){
 await page.waitForTimeout(2600);await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'로그인',exact:true}).last()[activate]();await page.waitForURL('**/home');
 // Complete the fixture login landing before a hard navigation. WebKit can
 // report requests interrupted during the document swap as access-control errors.
 await page.getByRole('heading',{name:/첫 표현을 담아/}).waitFor();
 await page.getByRole('heading',{name:/말이 태어나는 곳을/}).waitFor();
 await page.waitForLoadState('networkidle');
}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}

let annotationLost=false;
await context.route('**/api/materials/*/annotations*',async r=>{
 try{await db.exec('RESET ROLE;SET ROLE service_role');
 if(r.request().method()==='POST'){
  const b=r.request().postDataJSON();
  const result=(await db.query('select save_textbook_annotation($1,10,$2,$3,$4) result',[uid,b.operation,b.annotation,{sequence:book.sequence,dictionary:book.dictionary}])).rows[0].result;
  if(annotationLost){annotationLost=false;return r.abort('failed');}
  return r.fulfill({json:{annotation:result}});
 }
 const materialId=Number(new URL(r.request().url()).pathname.split('/')[3]);
 const rows=(await db.query('select * from textbook_annotations where material_id=$1 order by created_at',[materialId])).rows;
 const history=(await db.query('select * from textbook_annotation_revisions order by created_at desc')).rows;
 return r.fulfill({json:{materialId:'10',canEdit:true,annotations:rows,history}});
 }catch(e){return r.fulfill({status:409,json:{error:e.message,conflict:true}});}finally{await db.exec('RESET ROLE;SET ROLE authenticated');}
});
const readBoards=()=>page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const q=indexedDB.open('manabi-teaching-boards');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});return new Promise((resolve,reject)=>{const q=db.transaction('boards').objectStore('boards').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});});
const head=async()=> (await readBoards()).find(row=>row.id===row.scope);
const scene=async()=>{const row=await head();return row?.document.pages.find(p=>p.id===row.document.activePage)?.elements.filter(el=>!el.isDeleted)||[];};
const saveScreen=async name=>{await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name+'.png');};
let lookupDelay=0,lookupError=false;
await context.route('**/api/classroom/lookup',async route=>{
 const {text,language}=route.request().postDataJSON();if(lookupDelay)await new Promise(r=>setTimeout(r,lookupDelay));
 if(lookupError)return route.fulfill({status:503,json:{error:'뜻을 불러오지 못했어요.'}});
 return route.fulfill({json:{text,language,reading:text==='复习'?'fù xí':'liàn xí',source:'ai',senses:[{meaning:text==='复习'?'복습하다':'연습하다',pos:'동사'},{meaning:'연습',pos:'명사'}]}});
});
let mode='ok',calls=[];
await context.route('**/api/classroom/recognize',async r=>{
 const body=r.request().postDataJSON();calls.push(body);
 if(mode==='slow')await new Promise(resolve=>setTimeout(resolve,1800));
 if(mode==='fail')return r.fulfill({status:503,json:{error:'검수 인식 실패'}});
 try{await r.fulfill({json:{source:'gemini',fingerprint:body.fingerprint,expressions:mode==='empty'?[]:[
  {original:'はし',reading:'はし',uncertain:true,choices:[{text:'箸',reading:'はし',meaning:'젓가락'},{text:'橋',reading:'はし',meaning:'다리'}]},
  {original:'がっこう',reading:'がっこう',uncertain:false,choices:[{text:'学校',reading:'がっこう',meaning:'학교'}]},
 ]}});}catch{/* A cancelled request must not affect the canvas. */}
});
try{
 await page.goto(base+`/viewer/10?class=fixture-class&day=${day}&board=1`);
 const board=page.getByRole('region',{name:'선생님 설명판'});await board.locator('.excalidraw canvas').first().waitFor();
 const menus=boardMenus(page,activate),hud=menus.hud,surface=board.locator('canvas.interactive');
 const originalNote=(await current()).raw_text;
 await menus.action('tools','펜');
 let rect=await surface.boundingBox();
 await page.mouse.move(rect.x+220,rect.y+210);await page.mouse.down();await page.mouse.move(rect.x+390,rect.y+260,{steps:18});await page.mouse.up();
 await waitFor(async()=>(await scene()).some(el=>el.type==='freedraw'));
 const originalInk=(await scene()).filter(el=>el.type==='freedraw').map(el=>({id:el.id,x:el.x,y:el.y,points:el.points}));
 const capture=async()=>{await menus.action('tools','선택');await surface.click({position:{x:150,y:600}});await page.keyboard.press('Meta+a');await menus.open('selection');await hud.getByRole('button',{name:'선택한 필기 인식',exact:true}).click();};
 await capture();const panel=page.getByRole('dialog',{name:'필기에서 표현 가져오기'});await panel.waitFor();
 await saveScreen('01-selected-ink-desktop');assert.equal(calls.length,0);
 await panel.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();assert.equal(calls.length,0);
 await capture();lookupError=true;mode='fail';await panel.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await panel.getByText('검수 인식 실패',{exact:true}).waitFor();
 mode='ok';await panel.getByRole('button',{name:'다시 인식',exact:true}).click();await panel.getByRole('button',{name:'箸 젓가락',exact:true}).waitFor();
 assert(!await panel.getByRole('button',{name:'선택한 0개 판에 놓기'}).isEnabled());
 await panel.getByRole('button',{name:'箸 젓가락',exact:true}).click();await panel.getByRole('button',{name:'学校 학교',exact:true}).click();
 await saveScreen('02-candidates-desktop');
 await panel.getByRole('button',{name:'선택한 2개 판에 놓기'}).click();
 await waitFor(async()=>(await scene()).filter(el=>el.customData?.manabiExpression).length===2);
 const cards=(await scene()).filter(el=>el.customData?.manabiExpression);
 assert.deepEqual(cards.map(el=>el.customData.manabiExpression.text),['箸','学校']);
 for(const card of cards){assert.equal(card.backgroundColor,'transparent');assert.equal(card.customData.manabiExpression.source.kind,'manual');assert(card.customData.manabiInk);}
 assert.equal((await current()).raw_text,originalNote,'placement must not publish student records');
 assert.deepEqual((await scene()).filter(el=>el.type==='freedraw').map(el=>({id:el.id,x:el.x,y:el.y,points:el.points})),originalInk);
 for(const body of calls)assert.deepEqual(Object.keys(body).sort(),['rootId','teamKey','image','fingerprint','consent'].sort());
 assert.equal(calls[0].rootId,1);assert.equal(calls[0].teamKey,'fixture-class');assert(calls[0].image.startsWith('data:image/png;base64,'));
 check('selected raster only; no request before consent; provider retry; explicit kana/meaning choice; multiple words with preserved ink and no auto class record');
 await panel.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();
 // Reload and re-select the original stroke only to check stable result keys.
 await page.reload();await surface.waitFor();await menus.action('tools','선택');rect=await surface.boundingBox();
 await page.mouse.move(rect.x+190,rect.y+180);await page.mouse.down();await page.mouse.move(rect.x+415,rect.y+280,{steps:12});await page.mouse.up();
 await menus.open('selection');await hud.getByRole('button',{name:'선택한 필기 인식',exact:true}).click();await panel.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await panel.getByRole('button',{name:'箸 젓가락',exact:true}).click();await panel.getByRole('button',{name:'선택한 1개 판에 놓기'}).click();
 await panel.getByRole('button',{name:'인식 결과 다시 열기',exact:true}).waitFor();assert.equal((await scene()).filter(el=>el.customData?.manabiExpression).length,2);
 check('reopening and recognizing the same selected ink focuses an existing word rather than adding duplicates');
 await panel.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();
 // Explicit student record remains available through existing element menu.
 await menus.open('selection');await hud.getByRole('button',{name:'수업에 남기기',exact:true}).click();await waitFor(async()=>(await current()).raw_text.includes('箸'));
 check('only the existing explicit class-record action publishes the reviewed expression');
 await menus.close();await menus.action('pages','새 판');await surface.waitFor();
 await menus.action('tools','펜');rect=await surface.boundingBox();
 await page.mouse.move(rect.x+200,rect.y+190);await page.mouse.down();await page.mouse.move(rect.x+350,rect.y+240,{steps:12});await page.mouse.up();
 await capture();mode='slow';await panel.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await waitFor(()=>calls.length===4);
 // While the request runs, a new stroke outside the captured region is allowed.
 await hud.getByRole('button',{name:'펜',exact:true}).click();await page.mouse.move(rect.x+240,rect.y+440);await page.mouse.down();await page.mouse.move(rect.x+420,rect.y+480,{steps:12});await page.mouse.up();
 await panel.getByRole('button',{name:'箸 젓가락',exact:true}).waitFor();assert.equal((await scene()).filter(el=>el.type==='freedraw').length,2);
 await panel.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();
 check('the teacher can continue writing outside the selected region while recognition runs');
 await capture();mode='slow';await panel.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await waitFor(()=>calls.length===5);await panel.getByRole('button',{name:'필기 인식 취소',exact:true}).click();await page.waitForTimeout(2200);assert.equal(await page.locator('.board-ink-panel').count(),0);assert.equal((await scene()).filter(el=>el.customData?.manabiExpression).length,0);
 await capture();mode='empty';await panel.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await panel.getByText('읽을 수 있는 표현이 없어요. 영역을 줄이거나 ＋에서 직접 입력해 주세요.',{exact:true}).waitFor();await panel.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();
 check('cancelled late responses do not change the board; empty results keep the handwriting and allow retry');
 await page.setViewportSize({width:390,height:844});await menus.action('tools','펜');rect=await surface.boundingBox();await page.mouse.move(rect.x+20,rect.y+110);await page.mouse.down();await page.mouse.move(rect.x+rect.width-20,rect.y+rect.height-80,{steps:20});await page.mouse.up();await waitFor(async()=>(await scene()).filter(el=>el.type==='freedraw').length===3);await capture();mode='ok';await panel.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await panel.getByRole('button',{name:'箸 젓가락',exact:true}).click();await panel.getByRole('button',{name:'学校 학교',exact:true}).click();await saveScreen('03-candidates-mobile');
 const box=await panel.boundingBox();assert(box.x>=0&&box.y>=70&&box.width<=390&&box.y+box.height<=844);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await panel.getByRole('button',{name:'선택한 2개 판에 놓기'}).click();
 await panel.getByRole('button',{name:'새 판에 2개 놓기'}).click();await waitFor(async()=>(await scene()).filter(el=>el.customData?.manabiExpression).length===2);
 await saveScreen('04-new-page-mobile');
 await panel.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();
 check('mobile sheet fits the viewport and offers explicit new-page placement when paper space runs out');
 const rows=await readBoards(),currentBoard=rows.find(row=>row.id===row.scope);assert.equal(currentBoard.document.pages.length,3);
 assert.equal(currentBoard.document.pages[1].elements.filter(el=>el.type==='freedraw'&&!el.isDeleted).length,3);
 assert.equal(report.errors.length,0,JSON.stringify(report.errors));
}finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await db.close();}
