// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:8900',out=process.env.QA_OUT||'/private/tmp/manabi-classroom-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE ON SEQUENCE reading_materials_id_seq TO authenticated;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Japanese',team:{key:'fixture-class',root:true,name:'화요일의 일본어',lang:'Japanese',pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const browser=await chromium.launch({executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const report={checks:[],errors:[],screens:[]},writes=[];
await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
await context.route(base+'/**',async route=>{if(new URL(route.request().url()).pathname.startsWith('/_next/static/'))return route.continue();const response=await route.fetch({headers:{...route.request().headers(),cookie:''},timeout:180000});await route.fulfill({response});});
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:uid,display_name:'수업 검수',role:'admin',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(table==='classroom_append_entry'){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query('select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  return send(object?(rows[0]||null):rows);
 }
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'로그인',exact:true}).last().click();await page.waitForURL('**/home');}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}
await page.goto(base+'/class');await page.getByRole('link',{name:'수업 열기 →'}).waitFor();check('teacher hub real class destination');
await page.screenshot({path:out+'/hub-desktop.png'});report.screens.push('hub-desktop.png');
await page.getByRole('link',{name:'수업 열기 →'}).click();await page.getByRole('link',{name:'수업 진행 →'}).waitFor();check('class home shows notes first');
await page.getByRole('link',{name:'수업 진행 →'}).click();await page.waitForURL('**/live');await page.goto(base+`/class/fixture-class/live?day=${day}`);
const input=page.getByLabel('지금 함께 공부할 표현');await input.waitFor();await page.getByRole('button',{name:'また来週',exact:true}).waitFor();
if(process.env.QA_LAYOUT_ONLY==='1'){
 await input.fill('keyboard draft');await input.press('Tab');assert.equal((await page.evaluate(()=>document.activeElement.textContent)).trim(),'추가 ↑');await page.keyboard.press('Shift+Tab');assert(await input.evaluate(el=>el===document.activeElement));await input.fill('');check('keyboard reaches submit and returns to composer');
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:950});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.evaluate(()=>document.fonts.ready);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const ink=await page.locator('.classroom-composer label').evaluate(el=>getComputedStyle(el).color);assert.equal(ink,'rgb(128, 87, 106)');await page.screenshot({path:`${out}/verified-live-${width}-${theme}.png`});}}
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:950});for(const selector of ['.gnb__logo','.gnb__profile-btn','.manabi-search-link']){const box=await page.locator(selector).boundingBox();assert(box&&box.x>=0&&box.x+box.width<=width+1,`${selector} clipped at ${width}`);}}
 check('fonts, 320/390/1440 layout and inherited dark preference keep readable ink');check('header logo, search and profile stay fully visible');await browser.close();await db.close();process.exit(0);
}
await input.fill('IME途中');await input.dispatchEvent('compositionstart');await input.press('Enter');assert.equal((await input.inputValue()).trim(),'IME途中');assert(!(await current()).raw_text.includes('IME途中')); await input.dispatchEvent('compositionend');await input.fill('');check('IME confirmation does not submit');
await input.fill('途中の下書き');await page.reload();await input.waitFor();await waitFor(async()=>await input.inputValue()==='途中の下書き');await input.fill('');check('unfinished composer draft restored after reload');
analysisDelay=2000;await input.fill('保存が先');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await waitFor(async()=>(await current()).raw_text.includes('保存が先'));check('raw stored while analysis still pending');
await input.fill('次の表現');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await waitFor(async()=>(await current()).raw_text.includes('次の表現'));check('new input independent of slow analysis');
await waitFor(async()=>(await current()).processed_json.status==='completed');analysisDelay=0;
const word=page.locator('.classroom-entry').filter({has:page.getByRole('button',{name:'保存が先',exact:true})});await word.locator('.classroom-meaning-edit').click();await page.getByLabel('대표 뜻',{exact:true}).fill('선생님이 직접 적은 핵심 뜻');await page.getByRole('button',{name:'뜻 저장',exact:true}).click();await word.getByRole('button',{name:/선생님이 직접 적은 핵심 뜻/}).waitFor();check('manual primary meaning saved');
failure=true;await input.fill('消えない入力');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await page.getByRole('button',{name:'저장 재시도'}).waitFor();await page.reload();await page.getByText('消えない入力',{exact:true}).waitFor();check('failed input restored after reload');failure=false;await page.getByRole('button',{name:'저장 재시도'}).click();await waitFor(async()=>(await current()).raw_text.includes('消えない入力'));check('explicit retry saves preserved original');
lostResponse=true;await input.fill('応答が消えた');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await page.getByRole('button',{name:'저장 재시도'}).waitFor();await page.getByRole('button',{name:'저장 재시도'}).click();await waitFor(async()=>await page.locator('.classroom-pending').count()===0);assert.equal((await current()).raw_text.split('応答が消えた').length-1,1);check('lost response retry has no duplicate');
await context.setOffline(true);await input.fill('オフライン');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await page.getByText('オフライン',{exact:true}).waitFor();assert(!(await current()).raw_text.includes('オフライン'));await input.fill('取り消した入力');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await page.locator('.classroom-pending').filter({hasText:'取り消した入力'}).getByRole('button',{name:'입력 취소'}).click();await context.setOffline(false);await waitFor(async()=>(await current()).raw_text.includes('オフライン'));assert(!(await current()).raw_text.includes('取り消した入力'));check('cancelled offline entry is never sent');check('offline queue resumes online');
await input.fill('二行目\n三行目');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();await waitFor(async()=>(await current()).raw_text.includes('二行目\n三行目'));check('multiline input preserves source and both analysis indices');
await waitFor(async()=>(await current()).processed_json.status==='completed');
assert(Object.values((await current()).processed_json.metadata.classMeanings).some(v=>v.meaning==='선생님이 직접 적은 핵심 뜻'));check('subsequent analysis preserves manual meaning');
emptyMeaning=true;await input.fill('図書館');await page.getByRole('button',{name:'추가 ↑',exact:true}).click();
const gap=page.locator('.classroom-entry').filter({has:page.getByRole('button',{name:'図書館',exact:true})});
await gap.getByRole('button',{name:'뜻 다시 찾기',exact:true}).waitFor();
const callsBefore=analyzedLines.length;await page.waitForTimeout(1500);assert.equal(analyzedLines.length,callsBefore);check('completed empty meaning exposes retry without automatic loop');
await gap.locator('.classroom-meaning-edit').click();await page.getByLabel('대표 뜻',{exact:true}).fill('도서관 · 직접 입력');await page.getByRole('button',{name:'뜻 저장',exact:true}).click();await gap.getByRole('button',{name:/도서관 · 직접 입력/}).waitFor();
await gap.getByRole('button',{name:'뜻 다시 찾기',exact:true}).click();await waitFor(async()=>analyzedLines.length===callsBefore+1);await gap.getByRole('button',{name:'뜻 다시 찾기',exact:true}).waitFor();await page.waitForTimeout(1500);assert.equal(analyzedLines.length,callsBefore+1);check('empty retry remains recoverable without repeated API calls');
const unchanged=(await current()).processed_json;emptyMeaning=false;await gap.getByRole('button',{name:'뜻 다시 찾기',exact:true}).click();await waitFor(async()=>await gap.getByRole('button',{name:'뜻 다시 찾기',exact:true}).count()===0);await waitFor(async()=>Object.values((await current()).processed_json.dictionary).some(t=>t.text==='図書館'&&t.meaning==='검수 표현의 뜻'));
assert.deepEqual(analyzedLines.at(-1),['図書館']);assert.equal(await gap.locator('.classroom-meaning-edit').innerText(),'도서관 · 직접 입력 ↗');
const recovered=(await current()).processed_json;for(const id of unchanged.sequence){if(unchanged.dictionary[id].text!=='図書館'&&unchanged.dictionary[id].pos!=='개행')assert.deepEqual(recovered.dictionary[id],unchanged.dictionary[id]);}check('retry fills only missing gloss and preserves normal tokens and teacher meaning');
await page.getByRole('link',{name:'수업 노트 읽기 →',exact:true}).click();await page.getByRole('link',{name:'← 수업 진행',exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'← 수업 진행',exact:true}).getAttribute('href'),`/class/fixture-class/live?day=${day}`);await page.getByRole('link',{name:'← 수업 진행',exact:true}).click();await input.waitFor();check('saved note viewer returns to the same classroom and date');
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:950});await page.evaluate(()=>document.fonts.ready);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`live overflow ${width}`);await page.screenshot({path:`${out}/live-${width}.png`});report.screens.push(`live-${width}.png`);}check('live 320/390/768/1440 no horizontal overflow');
for(let i=0;i<10;i++){await input.fill(`連続入力${i}`);await page.getByRole('button',{name:'추가 ↑',exact:true}).click();}
await waitFor(async()=>(await current()).raw_text.includes('連続入力9'));const ten=(await current()).raw_text.match(/連続入力\d/g);assert.deepEqual(ten,Array.from({length:10},(_,i)=>`連続入力${i}`));check('ten successive inputs retain exact order once');
await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await page.screenshot({path:out+'/live-dark.png'});report.screens.push('live-dark.png');await page.evaluate(()=>document.documentElement.setAttribute('data-theme','light'));
const failedStore=await context.newPage();await failedStore.addInitScript(()=>Object.defineProperty(window,'indexedDB',{get(){throw new Error('fixture storage unavailable');}}));await failedStore.goto(base+`/class/fixture-class/live?day=${day}`);const failedInput=failedStore.getByLabel('지금 함께 공부할 표현');await failedInput.fill('消さないで');await failedStore.getByRole('button',{name:'추가 ↑',exact:true}).click();assert.equal(await failedInput.inputValue(),'消さないで');assert(!(await current()).raw_text.includes('消さないで'));await failedStore.close();check('unavailable device storage keeps composer original');
const board=await context.newPage();board.on('pageerror',e=>report.errors.push(e.message));await board.goto(base+`/class/fixture-class/board?day=${day}`);await board.getByRole('button',{name:'뜻 가리기',exact:true}).waitFor();await board.getByRole('button',{name:'뜻 가리기',exact:true}).click();assert(await board.getByText('뜻을 떠올려 보세요',{exact:true}).isVisible());await board.getByRole('button',{name:'뜻 보기',exact:true}).click();check('board meaning reveal');
await board.getByRole('button',{name:'이전 표현',exact:true}).click();const previous=await board.locator('.classroom-word').innerText();await callAppend('新しい表現');await board.reload(); // Reload resets only local follow state; now select older and wait for a new poll.
await board.getByRole('button',{name:'이전 표현',exact:true}).click();const held=await board.locator('.classroom-word').innerText();await callAppend('さらに新しい');await board.waitForTimeout(16000);assert.equal(await board.locator('.classroom-word').innerText(),held);check('older board selection held across polling');
await board.getByRole('button',{name:'최신 따라가기',exact:true}).click();await board.getByText('さらに新しい',{exact:true}).waitFor();check('board resumes newest');
for(const width of [1024,768,390,320]){await board.setViewportSize({width,height:1000});await board.getByLabel('글자 크기').selectOption('largest');assert(await board.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`board overflow ${width}`);await board.screenshot({path:`${out}/board-${width}.png`});report.screens.push(`board-${width}.png`);}check('board portrait/landscape and largest text no overflow');
const twins=await Promise.all([context.newPage(),context.newPage()]);for(const p of twins)await p.goto(base+'/class/fixture-class/live?day=2026-09-11');await Promise.all(twins.map(async(p,i)=>{await p.getByLabel('지금 함께 공부할 표현').fill(`二つの窓${i}`);await p.getByRole('button',{name:'추가 ↑',exact:true}).click();}));await waitFor(async()=>{const rows=(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'='2026-09-11'")).rows;return rows.length===1&&rows[0].raw_text.includes('二つの窓0')&&rows[0].raw_text.includes('二つの窓1');});for(const p of twins)await p.close();check('two tabs create one day note and retain both entries');
assert.equal(report.errors.length,0,report.errors.join('\n'));check('no page runtime errors');
await context.storageState({path:out+'/fixture-state.json'});fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();await db.close();
