import {createServer} from 'vite';
import {launchQaBrowser,traceQa,finishQa} from './qa-runtime.mjs';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const out=process.env.QA_OUT||'/private/tmp/manabi-reference-scope',engine=process.env.QA_BROWSER||'chromium';fs.mkdirSync(out,{recursive:true});
const server=await createServer({configFile:false,root:process.cwd(),server:{host:'127.0.0.1',port:0},oxc:{jsx:{runtime:'automatic'}},optimizeDeps:{include:['react','react-dom/client','react/jsx-dev-runtime','react/jsx-runtime']},logLevel:'error'});await server.listen();
const browser=await launchQaBrowser(engine);
const page=await browser.newPage(),errors=[],requests=[],aborted=[];let delayed=null,response={form:'研究',warn:null};
page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>{if(r.url().endsWith('/api/gemini'))aborted.push(r.failure()?.errorText);});
await page.route('**/api/gemini',async route=>{
 const input=JSON.parse(route.request().postDataJSON().contents[0].parts[0].text.split('\n')[1]);requests.push(input);
 const payload=response;const finish=()=>route.fulfill({json:{candidates:[{content:{parts:[{text:JSON.stringify(payload)}]}}]}}).catch(()=>{});
 if(delayed===true)delayed=finish;else await finish();
});
const waitFor=async f=>{for(let i=0;i<100;i++){if(await f())return;await page.waitForTimeout(30);}throw new Error('condition timeout');};
const select=patch=>page.evaluate(patch=>window.selectReference(patch),patch);
const lookup=()=>page.getByRole('button',{name:'일본어 대응 찾기',exact:true});
const section=page.getByRole('region',{name:'일본어 대조'});
const checks=[];const check=label=>{checks.push(label);console.log(label);};
const report={engine,groups:[],checks,requests,aborted,errors};await traceQa(page.context());
try{
 await page.goto(server.resolvedUrls.local[0]+'e2e/reference-scope-fixture.html');await lookup().waitFor();assert.equal(requests.length,0);
 delayed=true;await lookup().click();await waitFor(()=>typeof delayed==='function');
 assert.equal(requests[0].partOfSpeech,'명사');
 await select({pos:'동사'});await lookup().waitFor();await waitFor(()=>aborted.length===1);
 await delayed();delayed=null;await page.waitForTimeout(100);assert.equal(requests.length,1);assert.equal(await section.getByText('AI',{exact:true}).count(),0);
 check('changing only POS aborts the pending request; late result cannot appear or automatically request again');
 response={form:'研究する',warn:null};await lookup().click();await section.getByText('研究する',{exact:true}).waitFor();assert.equal(requests[1].partOfSpeech,'동사');
 await select({meaning:'조사하다'});await lookup().waitFor();await page.waitForTimeout(100);assert.equal(requests.length,2);
 await select({meaning:'연구',pos:'명사'});await lookup().waitFor();response={form:'研究',warn:null};await lookup().click();await section.getByText('AI',{exact:true}).waitFor();assert.equal(requests.length,3);
 await select({pos:'동사'});await section.getByText('研究する',{exact:true}).waitFor();await page.waitForTimeout(100);assert.equal(requests.length,3);
 check('noun and verb use separate caches; changed meaning requires consent; returning to an exact cached scope does not refetch');
 await select({userId:'student'});await lookup().waitFor();assert.equal(await section.getByText('研究する',{exact:true}).count(),0);assert.equal(requests.length,3);
 await select({userId:null});await section.getByText('로그인하면 일본어 대응어를 찾을 수 있어요.',{exact:true}).waitFor();assert.equal(await lookup().count(),0);
 check('another account cannot see the previous account result; signed-out state never requests');
 await select({userId:'student',word:'学习',meaning:'공부하다',pos:'동사',jaTable:{学:'学',习:'習'}});await lookup().waitFor();response={form:null};await lookup().click();await page.getByRole('button',{name:'일본어 다시 찾기',exact:true}).waitFor();
 response={form:'勉強する',warn:null};await page.getByRole('button',{name:'일본어 다시 찾기',exact:true}).click();await section.getByText('勉強する',{exact:true}).waitFor();
 check('uncertain response stays empty and a manual retry can recover');
 await select({word:'东道主',meaning:'손님을 맞이하는 주인',pos:'명사',jaTable:{东:'東',道:'道',主:'主'}});await lookup().waitFor();
 response={form:'주최자',warn:'東道主는 현대 일본어에서 거의 사용되지 않는 고어 표현입니다.'};
 await lookup().click();await page.getByRole('button',{name:'일본어 다시 찾기',exact:true}).waitFor();
 assert.equal(await section.getByText('주최자',{exact:true}).count(),0);assert.equal(await section.getByText('AI',{exact:true}).count(),0);
 const rejectedRequestCount=requests.length;await page.waitForTimeout(100);assert.equal(requests.length,rejectedRequestCount);
 response={form:'もてなす人',warn:'현대 일본어에서는 드문 표기'};
 await page.getByRole('button',{name:'일본어 다시 찾기',exact:true}).click();await section.getByText('もてなす人',{exact:true}).waitFor();
 await section.getByText('일본어 참고: 현대 일본어에서는 드문 표기',{exact:true}).waitFor();
 check('Korean model output is never shown as Japanese; retry is manual and usage notes are not presented as definitions');
 assert.deepEqual(Object.keys(requests.at(-1)).sort(),['chinese','japaneseCharacterForm','koreanMeaning','partOfSpeech'].sort());assert.deepEqual(errors,[]);
 await page.screenshot({path:out+'/reference.png'});report.groups.push('reader.reference');
}catch(error){report.failure=error.stack;throw error;}finally{await finishQa({browser,server,context:page.context(),report,out});}
