// Actual React UI with synthetic auth/HTTP data and the existing PostgreSQL
// vocabulary RPC. No real account, personal note, or external AI is contacted.
import {chromium,webkit} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:3115',out=process.env.QA_OUT||'/private/tmp/manabi-personal-note-qa';
fs.mkdirSync(out,{recursive:true});
const uid='00000000-0000-4000-8000-000000000077',oldVocab='00000000-0000-4000-8000-000000000088';
const db=new PGlite();
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql AS $$ SELECT false $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,direction text DEFAULT 'read');
CREATE UNIQUE INDEX note_attempt ON reading_materials(owner_id,(processed_json#>>'{metadata,importAttempt}'));
CREATE TABLE uploaded_pdfs(id uuid primary key,owner_id uuid);
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,word_text text,base_form text,meaning text,furigana text,pos text,language text,source_sentence text,source_material_id bigint,next_review_at timestamptz,stability real default 0,difficulty real default 0,reps integer default 0,unique(user_id,word_text));
GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());
ALTER TABLE user_vocabulary ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON user_vocabulary TO authenticated USING(user_id=auth.uid()) WITH CHECK(user_id=auth.uid());
GRANT SELECT,INSERT,UPDATE ON reading_materials,user_vocabulary TO authenticated;GRANT SELECT ON uploaded_pdfs TO authenticated;GRANT USAGE,SELECT ON SEQUENCE reading_materials_id_seq TO authenticated;`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260905065205_textbook_material_contexts.sql',import.meta.url),'utf8'));
await db.query('insert into auth.users values($1)',[uid]);
await db.query("insert into user_vocabulary(id,user_id,word_text,base_form,meaning,language,next_review_at,stability,difficulty,reps) values($1,$2,'橋','橋','다리, 교량','Japanese','2030-01-01',12,3,8)",[oldVocab,uid]);
await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const collectionSummary=rows=>({pending:rows.filter(r=>!r.vocabularyId&&!r.excluded).length});
const originalVocab=(await db.query('select * from user_vocabulary where id=$1',[oldVocab])).rows[0];
const engine=process.env.QA_BROWSER||'chromium';
const browser=await(engine==='webkit'?webkit:chromium).launch({...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{}),headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
context.setDefaultTimeout(30000);context.setDefaultNavigationTimeout(180000);
const enc=value=>Buffer.from(JSON.stringify(value)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'note-fixture@example.com',app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'};
const report={engine,checks:[],errors:[],screens:[],externalAI:[],expectedTransport:[]},intentionalAborts=new Set();
let failSave=false,loseSave=false,failWord=true,lookupDelay=0;
let recognitionMode="ok",recognitionCalls=[];
await context.route('**/*',route=>{
 if(/generativelanguage|openai\.com|api\/analyze|api\/classroom\/lookup/.test(route.request().url()))report.externalAI.push(route.request().url());
 return route.request().url().startsWith(base)?route.continue():route.abort();
});
await context.route(base+'/**',route=>route.continue(new URL(route.request().url()).pathname.startsWith('/_next/static/')?{}:{headers:{...route.request().headers(),cookie:''}}));
await context.route('**/api/**',route=>route.fulfill({json:{}}));
await context.route('**/auth/v1/**',route=>route.fulfill({headers:cors,json:route.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async route=>{
 const request=route.request(),url=new URL(request.url()),table=url.pathname.split('/').pop(),single=request.headers().accept?.includes('vnd.pgrst.object');
 if(request.method()==='OPTIONS')return route.fulfill({status:204,headers:cors});
 if(request.method()==='HEAD')return route.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 let data=[];
 if(table==='profiles')data={id:uid,display_name:'개인 노트 검수',role:'student',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']};
 else if(table==='user_vocabulary')data=(await db.query('select * from user_vocabulary')).rows;
 else if(table==='personal_library_page'){const rows=(await db.query('select * from reading_materials')).rows;return route.fulfill({headers:cors,json:{items:rows.map(row=>({target_kind:'material',target_id:String(row.id),material_id:String(row.id),title:row.title,is_note:true,owned:true,language:'Japanese',child_count:0,assets:[],excerpt:'',created_at:new Date().toISOString()})),total:rows.length,unavailable:0}});}
 else if(table==='reading_materials'){data=(await db.query('select * from reading_materials')).rows;const id=url.searchParams.get('id');if(id?.startsWith('eq.'))data=data.filter(row=>String(row.id)===id.slice(3));if(url.searchParams.get('select')?.includes('note_summary:'))data=data.map(row=>({id:row.id,note_summary:row.processed_json.metadata.studyNote.summary}));if(single)data=data[0]||null;}
 else if(single)data=null;
 return route.fulfill({headers:cors,json:data});
});
const noteResponse=row=>({id:String(row.id),title:row.title,revision:row.processed_json.metadata.studyNote.revision,document:row.processed_json.metadata.studyNote.document});
const noteRow=async id=>(await db.query('select * from reading_materials where id=$1',[id])).rows[0];
await context.route('**/api/notes**',async route=>{
 const req=route.request(),url=new URL(req.url()),path=url.pathname;
 const send=(json,status=200)=>route.fulfill({json,status});
 if(path.endsWith('/recognize')){
  const body=req.postDataJSON();recognitionCalls.push(body);
  if(recognitionMode==='fail')return send({error:'검수용 인식 실패'},503);
  if(recognitionMode==='slow')await new Promise(resolve=>setTimeout(resolve,1500));
  return send({source:'gemini',revision:body.revision,fingerprint:body.fingerprint,expressions:recognitionMode==='empty'?[]:[{original:'はし',reading:'はし',uncertain:true,choices:[{text:'橋',reading:'はし',meaning:'다리'},{text:'箸',reading:'はし',meaning:'젓가락'}]}]});
 }
 if(path.endsWith('/dictionary')){
  if(lookupDelay)await new Promise(resolve=>setTimeout(resolve,lookupDelay));
  return send({text:url.searchParams.get('q'),reading:'はし',senses:[],source:'내 사전',candidates:[{text:'橋',reading:'はし',meaning:'다리'},{text:'箸',reading:'はし',meaning:'젓가락'}]});
 }
 const id=path.split('/')[3];
 if(req.method()==='GET'){const row=await noteRow(id);return row?send(noteResponse(row)):send({error:'내 계정의 개인 노트만 열 수 있어요.'},404);}
 const body=req.postDataJSON();
 if(req.method()==='POST'){
  const old=(await db.query("select * from reading_materials where processed_json#>>'{metadata,importAttempt}'=$1",[body.document.key])).rows[0];if(old)return send(noteResponse(old));
  const json={sequence:[],dictionary:{},last_idx:-1,status:'note',metadata:{language:body.document.language,importAttempt:body.document.key,studyNote:{version:1,revision:crypto.randomUUID(),document:body.document,summary:collectionSummary(body.document.candidates)}}};
  const row=(await db.query("insert into reading_materials(owner_id,title,visibility,direction,raw_text,processed_json) values($1,$2,'private','write','',$3) returning *",[uid,body.title,json])).rows[0];return send(noteResponse(row),201);
 }
 if(failSave)return send({error:'검수용 연결 실패'},503);
 const row=await noteRow(id);if(row.processed_json.metadata.studyNote.revision!==body.revision)return send({error:'다른 기기의 수정과 겹쳤어요.'},409);
 const json={...row.processed_json,metadata:{...row.processed_json.metadata,studyNote:{version:1,revision:crypto.randomUUID(),document:body.document,summary:collectionSummary(body.document.candidates)}}};
 const result=(await db.query("update reading_materials set title=$1,processed_json=$2 where id=$3 and processed_json#>>'{metadata,studyNote,revision}'=$4 returning *",[body.title,json,id,body.revision])).rows[0];
 if(loseSave){loseSave=false;intentionalAborts.add(url.host+url.pathname);return route.abort('failed');}return result?send(noteResponse(result)):send({error:'다른 기기의 수정과 겹쳤어요.'},409);
});
await context.route('**/api/learning/vocabulary',async route=>{
 const body=route.request().postDataJSON(),row=await noteRow(body.source.materialId),candidate=row.processed_json.metadata.studyNote.document.candidates.find(item=>item.id===body.source.noteCandidateId);
 assert(candidate?.reviewed&&!candidate.excluded,'client saved its review to the note before requesting vocabulary');
 if(candidate.text==='復習'&&failWord){failWord=false;return route.fulfill({status:503,json:{error:'검수용 단어 저장 실패'}});}
 const word={word_text:candidate.base||candidate.text,language:candidate.language,meaning:candidate.meaning,furigana:candidate.reading};
 const source={kind:'reading',materialId:String(row.id),quote:candidate.original,translation:candidate.meaning,locator:{notePage:candidate.pageId,noteCandidate:candidate.id,surface:candidate.text}};
 try {const result=(await db.query('select save_vocabulary_context($1,$2,$3,$4) result',[word,source,body.confirmId||null,body.confirmMeaning??null])).rows[0].result;return route.fulfill({json:result});}
 catch(error){if(error.message.includes('vocabulary_meaning_conflict'))return route.fulfill({status:409,json:{error:'같은 뜻인지 확인해 주세요.',code:'meaning_conflict',existing:{id:oldVocab,meaning:originalVocab.meaning}}});throw error;}
});
if(process.env.QA_LOGIN!=='1')await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);
const page=await context.newPage();
page.on('pageerror',error=>report.errors.push(error.message));
page.on('console',message=>{
 if(message.type()!=='error')return;
 if(message.text().includes('due to access control checks')&&[...intentionalAborts].some(path=>message.text().includes(path))){report.expectedTransport.push('WebKit reported the deliberately lost note-save response');return;}
 if(!/503|409|ERR_FAILED|Failed to fetch RSC|WebSocket connection/.test(message.text()))report.errors.push(message.text());
});
const check=label=>{report.checks.push(label);console.log(label);};
const screen=async name=>{await page.screenshot({path:`${out}/${name}.png`});report.screens.push(name+'.png');};
const waitFor=async fn=>{for(let i=0;i<150;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const readLocal=()=>page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('manabi-teaching-boards');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return new Promise(resolve=>{const req=db.transaction('boards').objectStore('boards').getAll();req.onsuccess=()=>resolve(req.result);});});
try{
 if(process.env.QA_LOGIN==='1'){
  await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'로그인',exact:true}).last().click();await page.waitForURL('**/home');await page.waitForLoadState('networkidle');
 }
 await page.goto(base+'/notes/new');await page.getByLabel('노트 제목',{exact:true}).fill('수업을 들으며 — 오늘의 일본어');await screen('01-create');
 await page.getByRole('button',{name:'노트 펼치기 ↗',exact:true}).click();await page.waitForURL(/\/notes\/\d+$/);const id=page.url().split('/').pop();
 const board=page.getByRole('region',{name:'개인 학습 노트'}),hud=page.locator('.board-hud');await board.locator('canvas.interactive').waitFor();
 const close=async()=>{const popup=hud.locator('.board-popover:not([hidden])');if(await popup.count())await popup.getByRole('button',{name:'메뉴 닫기',exact:true}).click();};
 const entry=async(text,reading,meaning)=>{
  await hud.getByRole('button',{name:'표현 입력',exact:true}).click();const form=hud.locator('#board-menu-entry form');await form.getByLabel('단어·표현',{exact:true}).fill(text);
  const details=form.getByRole('button',{name:'읽기와 뜻 입력',exact:true});if(await details.getAttribute('aria-expanded')!=='true')await details.click();
  await form.getByLabel('읽기',{exact:true}).fill(reading);await form.getByLabel('뜻',{exact:true}).fill(meaning);await form.getByRole('button',{name:'바로 놓기',exact:true}).click();await close();
 };
 const remote=async()=>noteResponse(await noteRow(id));
 await entry('はし','はし','다리');await entry('復習','ふくしゅう','복습');
 await hud.locator('.board-quick-tools').getByRole('button',{name:'펜',exact:true}).click();const surface=board.locator('canvas.interactive');await page.mouse.move(220,570);await page.mouse.down();await page.mouse.move(560,600,{steps:25});await page.mouse.up();
 await hud.getByRole('button',{name:'단어 정리',exact:true}).filter({visible:true}).first().click();
 const review=page.locator('.note-review');await review.waitFor();assert.equal(await review.locator('.note-candidate').count(),2);await review.getByRole('button',{name:'전체 2',exact:true}).click();
 await waitFor(async()=>!(await page.locator('.board-hud-status').getAttribute('data-saving'))||await page.locator('.board-hud-status').getAttribute('data-saving')==='false');
 const beforeInk=JSON.stringify((await remote()).document.board.pages[0].elements.find(el=>el.type==='freedraw').points);
 const first=review.locator('.note-candidate').first();await first.getByRole('button',{name:'한자·사전',exact:true}).click();await first.getByRole('button',{name:'橋 다리',exact:true}).click();
 await review.getByRole('button',{name:'뜻 있는 항목 모두 선택',exact:true}).click();await screen('02-desktop-review');
 await review.getByRole('button',{name:'선택한 2개 담기',exact:true}).click();await review.getByText('검수용 단어 저장 실패',{exact:true}).waitFor();await first.getByRole('button',{name:'같은 뜻이에요 · 문맥만 연결',exact:true}).click();
 await first.getByText('기존 단어에 문맥 연결',{exact:true}).waitFor();await review.getByRole('button',{name:'선택한 1개 담기',exact:true}).click();await review.getByText('새로 담음',{exact:true}).waitFor();
 assert.deepEqual((await db.query('select * from user_vocabulary where id=$1',[oldVocab])).rows[0],originalVocab);
 assert.equal((await db.query('select count(*)::int n from user_vocabulary')).rows[0].n,2);assert.equal((await db.query('select count(*)::int n from vocabulary_contexts')).rows[0].n,2);
 assert.equal(JSON.stringify((await remote()).document.board.pages[0].elements.find(el=>el.type==='freedraw').points),beforeInk);
 check('student account creates private notebook; kanji review, conflict confirmation and failed-item retry preserve original ink and existing SRS');
 await review.getByRole('button',{name:'단어 정리 닫기',exact:true}).click();await hud.getByRole('button',{name:'단어 정리',exact:true}).filter({visible:true}).first().click();assert.equal(await review.locator('.note-candidate').count(),0);await review.getByRole('button',{name:'담음 2',exact:true}).click();assert.equal(await review.locator('.note-candidate').count(),2);
 await page.reload();await board.locator('canvas.interactive').waitFor();await hud.getByRole('button',{name:'단어 정리',exact:true}).filter({visible:true}).first().click();await review.getByRole('button',{name:'담음 2',exact:true}).click();assert.equal(await review.getByText('저장됨',{exact:true}).count(),2);
 check('reload and repeated organization keep saved corrections without duplicate words or contexts');
 await page.setViewportSize({width:390,height:844});await screen('03-mobile-review');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 const rect=await review.boundingBox();assert(rect.x>=0&&rect.y>=0&&rect.width<=390&&rect.height<=844);
 assert.equal(await page.locator('.personal-note-canvas').evaluate(el=>el.inert),true,'mobile review does not leave hidden canvas controls focusable');
 await review.locator('.note-candidate').first().getByRole('button',{name:'원래 필기 ↗',exact:true}).click();await review.waitFor({state:'hidden'});await screen('04-mobile-note');
 const full=await board.boundingBox();assert(full.y<=1&&full.height>=843&&full.width>=389);
 await hud.getByRole('button',{name:'전체 메뉴',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'선택');
 check('mobile review fits the viewport; original-note action restores the full canvas; rail supports keyboard navigation');
 await page.setViewportSize({width:1440,height:1000});
 // A successful cloud write with a lost response is reconciled, not duplicated.
 loseSave=true;await entry('予習','よしゅう','예습');await waitFor(async()=>!loseSave);await waitFor(async()=>await page.locator('.board-hud-status').getAttribute('aria-label')==='계정에 저장됨');
 check('lost cloud save response is reconciled by reading the current revision');
 failSave=true;await entry('授業','じゅぎょう','수업');await waitFor(async()=>await page.locator('.board-hud-status').getAttribute('data-error')==='true');
 await waitFor(async()=>(await readLocal()).some(row=>row.document.personalNote?.dirty));
 const old=await noteRow(id);old.processed_json.metadata.studyNote.revision=crypto.randomUUID();await db.query('update reading_materials set processed_json=$1,title=$2 where id=$3',[old.processed_json,'다른 기기의 수정',id]);failSave=false;
 page.on('dialog',dialog=>dialog.accept());await page.reload();await board.locator('canvas.interactive').waitFor();await waitFor(async()=>await page.locator('.board-hud-status').getAttribute('data-error')==='true');
 await hud.getByRole('button',{name:'노트 정보',exact:true}).click();await page.getByRole('button',{name:'내 초안을 새 노트로 보관',exact:true}).waitFor();await screen('05-conflict-recovery');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'노트와 정리 목록 백업',exact:true}).click();const file=await download;const backup=JSON.parse(fs.readFileSync(await file.path(),'utf8'));assert.equal(backup.document.candidates.length,2);assert(backup.document.board.pages[0].elements.some(el=>el.customData?.manabiExpression?.text==='授業'));
 await page.getByRole('button',{name:'내 초안을 새 노트로 보관',exact:true}).click();await page.waitForURL(url=>url.pathname.startsWith('/notes/')&&!url.pathname.endsWith('/'+id));await board.locator('canvas.interactive').waitFor();
 assert.equal((await noteRow(id)).title,'다른 기기의 수정');check('offline draft survives reload, cloud conflict never overwrites the other writer, complete backup and private fork recover the local work');
 await hud.getByRole('button',{name:'전체 메뉴',exact:true}).click();await hud.getByRole('button',{name:'필기 도구 메뉴',exact:true}).click();await hud.getByRole('button',{name:'글자',exact:true}).click();
 await board.locator('canvas.interactive').click({position:{x:650,y:300}});await page.locator('textarea.excalidraw-wysiwyg').fill('お疲れさま → 수고했어요\n確認 → 확인');await page.keyboard.press('Escape');
 await hud.getByRole('button',{name:'단어 정리',exact:true}).filter({visible:true}).first().click();
 await review.getByRole('textbox',{name:'お疲れさま 뜻',exact:true}).waitFor();await review.getByRole('textbox',{name:'確認 뜻',exact:true}).waitFor();
 const typed=review.getByRole('textbox',{name:'お疲れさま 뜻',exact:true});await typed.fill('수고 ');assert.equal(await typed.inputValue(),'수고 ');
 check('native text notes split into individual expressions, keep their original lines, and preserve spaces while editing');
 // A separate note exercises real raster export and selection with a fake
 // recognition response. No production handwriting or AI service is used.
 await page.goto(base+'/notes/new');await page.getByLabel('노트 제목',{exact:true}).fill('필기 인식 검수');await page.getByRole('button',{name:'노트 펼치기 ↗',exact:true}).click();await page.waitForURL(/\/notes\/\d+$/);const inkId=page.url().split('/').pop();await board.locator('canvas.interactive').waitFor();
 await entry('送信しない','そうしんしない','선택하지 않은 문장');
 await hud.locator('.board-quick-tools').getByRole('button',{name:'펜',exact:true}).click();
 await page.mouse.move(220,570);await page.mouse.down();await page.mouse.move(280,590,{steps:10});await page.mouse.move(300,560,{steps:6});await page.mouse.up();
 await hud.locator('.board-quick-tools').getByRole('button',{name:'선택',exact:true}).click();
 await page.mouse.move(200,530);await page.mouse.down();await page.mouse.move(325,625,{steps:15});await page.mouse.up();
 const capture=async()=>{await hud.getByRole('button',{name:'선택한 요소 편집',exact:true}).click();await hud.getByRole('button',{name:'선택한 필기 인식',exact:true}).click();await page.getByRole('dialog',{name:'선택한 필기 읽기.'}).waitFor();};
 await capture();const recognition=page.locator('.note-recognition');await screen('06-selected-ink-desktop');
 assert.equal(recognitionCalls.length,0,'opening the crop preview must not send anything');
 await page.keyboard.press('Escape');await recognition.waitFor({state:'hidden'});assert.equal(recognitionCalls.length,0);
 await capture();await page.setViewportSize({width:390,height:844});await screen('07-selected-ink-mobile');
 const box=await recognition.boundingBox();assert(box.width<=390&&box.height<=844&&box.x>=0&&box.y>=0);assert(Math.abs(box.x-(390-box.width)/2)<2,'crop preview is centered');
 await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('.note-recognition')),'native modal keeps focus inside preview');
 recognitionMode='fail';await recognition.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await recognition.getByText('검수용 인식 실패',{exact:true}).waitFor();
 recognitionMode='ok';await recognition.getByRole('button',{name:'다시 인식',exact:true}).click();await recognition.waitFor({state:'hidden'});assert.equal(await review.isVisible(),false,'recognition leaves the canvas available');await page.getByRole('button',{name:'지금 정리',exact:true}).click();await review.waitFor();
 const inkNote=noteResponse(await noteRow(inkId));const originalStrokes=JSON.stringify(inkNote.document.board.pages[0].elements.filter(el=>el.type==='freedraw'));
 assert.equal(recognitionCalls.length,2);for(const body of recognitionCalls){assert.deepEqual(Object.keys(body).sort(),['consent','elementIds','fingerprint','image','pageId','revision'].sort());assert.equal(body.consent,'selected-ink-to-gemini');assert(body.image.startsWith('data:image/png;base64,'));assert.equal(body.elementIds.length,1);const selected=inkNote.document.board.pages[0].elements.find(el=>el.id===body.elementIds[0]);assert.equal(selected.type,'freedraw');}
 assert.equal(await review.locator('.note-candidate').count(),1);const recognized=review.locator('.note-candidate').first();assert.equal(await recognized.getByRole('textbox',{name:'표현 표기',exact:true}).inputValue(),'はし');assert.equal(await recognized.getByRole('textbox',{name:'はし 뜻',exact:true}).inputValue(),'');
 await recognized.getByRole('button',{name:'箸 젓가락',exact:true}).click();await recognized.getByRole('textbox',{name:'箸 뜻',exact:true}).fill('젓가락 · 수업 메모');await screen('08-kana-choice-mobile');
 assert.equal((await db.query('select count(*)::int n from user_vocabulary')).rows[0].n,2,'recognition does not save vocabulary automatically');
 await review.getByRole('button',{name:'단어 정리 닫기',exact:true}).click();await page.setViewportSize({width:1440,height:1000});await capture();await recognition.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await recognition.waitFor({state:'hidden'});await page.getByRole('button',{name:'지금 정리',exact:true}).click();await review.waitFor();
 assert.equal(await review.locator('.note-candidate').count(),1);assert.equal(await review.getByRole('textbox',{name:'箸 뜻',exact:true}).inputValue(),'젓가락 · 수업 메모');
 await review.getByRole('button',{name:'뜻 있는 항목 모두 선택',exact:true}).click();await review.getByRole('button',{name:'선택한 1개 담기',exact:true}).click();await review.getByText('새 단어 1개 · 기존 단어 0개 연결',{exact:true}).waitFor();assert.equal(await review.locator('.note-candidate').count(),0);
 assert.equal(JSON.stringify(noteResponse(await noteRow(inkId)).document.board.pages[0].elements.filter(el=>el.type==='freedraw')),originalStrokes);
 check('explicit crop preview sends only selected ink; cancel sends nothing; failed recognition retries, kana alternatives preserve edits, deduplicate and save with unchanged strokes');
 await review.getByRole('button',{name:'단어 정리 닫기',exact:true}).click();await capture();recognitionMode='slow';await recognition.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await waitFor(()=>recognitionCalls.length===4);await recognition.getByRole('button',{name:'필기 인식 취소',exact:true}).click();await page.waitForTimeout(1800);
 assert.equal(noteResponse(await noteRow(inkId)).document.candidates.length,1,'cancelled late response is not applied');
 await capture();recognitionMode='empty';await recognition.getByRole('button',{name:'이 부분 인식하기',exact:true}).click();await recognition.getByText('읽을 수 있는 표현을 찾지 못했어요. 글자 몇 개씩 선택하거나 직접 입력해 주세요.',{exact:true}).waitFor();await recognition.getByRole('button',{name:'필기 인식 닫기',exact:true}).click();
 check('late cancelled responses and unreadable handwriting preserve the note and prior candidate');

 // A learner can keep writing, then return to the unfinished queue without
 // rescanning the notebook or losing a reviewed choice.
 await page.setViewportSize({width:1440,height:1000});
 await entry('確認','かくにん','확인');await entry('質問','しつもん','질문');
 await hud.getByRole('button',{name:'단어 정리',exact:true}).filter({visible:true}).first().click();
 const confirm=review.locator('.note-candidate').filter({has:page.getByRole('textbox',{name:'確認 뜻',exact:true})});
 const question=review.locator('.note-candidate').filter({has:page.getByRole('textbox',{name:'質問 뜻',exact:true})});
 await confirm.getByRole('checkbox',{name:'確認 선택',exact:true}).check();
 await question.getByRole('button',{name:'제외',exact:true}).click();
 await review.getByRole('button',{name:'제외 1',exact:true}).click();assert.equal(await review.locator('.note-candidate').count(),1);
 await review.getByRole('button',{name:'미완료 2',exact:true}).click();
 assert.equal(await confirm.getByRole('checkbox',{name:'確認 선택',exact:true}).isChecked(),true);
 await review.getByRole('button',{name:'계속 필기 · 나중에 정리',exact:true}).click();
 assert.equal(await review.isVisible(),false);assert.equal(await page.locator('.personal-note-canvas').evaluate(el=>el.inert),false);
 await waitFor(async()=>await page.locator('.board-hud-status').getAttribute('aria-label')==='계정에 저장됨');
 await page.goto(base+'/notes/'+inkId+'?review=1');await review.waitFor();
 assert.equal(await confirm.getByRole('checkbox',{name:'確認 선택',exact:true}).isChecked(),true);
 assert.equal(await review.getByRole('button',{name:'미완료 2',exact:true}).getAttribute('aria-pressed'),'true');
 await review.getByRole('button',{name:'선택한 1개 담기',exact:true}).click();
 await review.getByText('새 단어 1개 · 기존 단어 0개 연결',{exact:true}).waitFor();
 assert.equal(await review.locator('.note-candidate').count(),1);
 await review.getByRole('button',{name:'제외 1',exact:true}).click();await question.getByRole('button',{name:'다시 포함',exact:true}).click();
 assert.equal(await review.locator('.note-candidate').count(),0);
 await review.getByRole('button',{name:'미완료 2',exact:true}).click();assert.equal(await question.getByRole('checkbox',{name:'質問 선택',exact:true}).isChecked(),false);
 await page.setViewportSize({width:320,height:740});await screen('09-collection-mobile');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 check('unfinished/saved/excluded queues preserve choices across reload; only reviewed rows save, and excluded words can be restored');
 await review.getByRole('button',{name:'계속 필기 · 나중에 정리',exact:true}).click();
 await hud.getByRole('button',{name:'전체 메뉴',exact:true}).click();await hud.getByRole('button',{name:'내 서재',exact:true}).click();
 await page.waitForURL(url=>url.pathname==='/materials');
 const resume=page.getByRole('link',{name:'미완료 2개 · 이어 정리 ↗',exact:true});await resume.waitFor();await resume.scrollIntoViewIfNeeded();await screen('10-library-resume');
 await resume.click();await review.waitFor();assert.equal(await review.locator('.note-candidate').count(),2);
 check('library shows the saved unfinished count and opens the review queue directly');
 assert.equal(report.externalAI.length,0);assert.equal(report.errors.length,0,report.errors.join('\n'));check('no actual external AI request or uncaught UI error');
}catch(error){report.failure=error.stack;await screen('failure');throw error;}
finally{fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await db.close();}
