import {installBoardCloudFixture,verifyBoardCloud} from './teaching-board-cloud-fixture.mjs';
import {boardMenus,verifyBoardMenus} from './teaching-board-menu-checks.mjs';
// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium,webkit} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:3108',out=process.env.QA_OUT||'/private/tmp/manabi-board-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,lesson_explanation_ko text,conversation_script text,direction text NOT NULL DEFAULT 'read',source_pdf_id uuid,page_start integer,page_end integer,document_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE,SELECT,UPDATE ON SEQUENCE reading_materials_id_seq TO authenticated;GRANT ALL ON reading_materials TO service_role;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql','20260910024120_classroom_study_flow.sql','20260910070535_textbook_teaching_annotations.sql','20260911072945_classroom_source_anchors.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Chinese',team:{key:'fixture-class',root:true,name:'목요일의 중국어',lang:'Chinese',bookKey:'fixture-book',chapterId:10,pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.query('INSERT INTO auth.users VALUES($1)',[uid]);await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const words=['图书馆','学生','老师','学校','学习','明天','今天','谢谢','朋友','中文','工作','欢迎','这里','那里'];
const book={sequence:[],dictionary:{},status:'completed',failed_indices:[],metadata:{language:'Chinese',book:{key:'fixture-book',order:1}}};
words.forEach((text,i)=>{const id=`id_${i}_word`,br=`br_${i}_end_fixture`;book.sequence.push(id,br);book.dictionary[id]={text,meaning:`뜻 ${i+1}`,furigana:i===0?'tú shū guǎn':'',pos:'명사',base:text};book.dictionary[br]={text:'\n',pos:'개행'};});
for(const [i,text]of ['我们','明天','见','。'].entries()){const id=`id_14_${i}`;book.sequence.push(id);book.dictionary[id]={text,meaning:['우리','내일','보다',''][i],pos:i===3?'기호':'표현'};}
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(10,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 함께 공부하는 하루',words.join('\n')+'\n我们明天见。','private',book]);
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(11,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 다음 과',words.join('\n'),'private',{...book,metadata:{...book.metadata,book:{key:'fixture-book',order:2}}}]);
await db.exec("select setval('reading_materials_id_seq',20)");
const engine=process.env.QA_BROWSER||'chromium',touch=process.env.QA_TOUCH==='1',activate=touch?'tap':'click';
assert(['chromium','webkit'].includes(engine),'QA_BROWSER must be chromium or webkit');
const browser=await (engine==='webkit'?webkit:chromium).launch({...(engine==='chromium'?{executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{}),headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:touch,serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const tabletState={dictionaryDelay:0,lookups:0};
const report={engine,touch,checks:[],errors:[],screens:[],failedRequests:[],expectedTransport:[],readingPrefetch:[]},writes=[];
let revisionConflicts=0;
// WebKit routes local Blob images too; allow this app's generated thumbnails.
await context.route('**/*',r=>{const url=r.request().url();return url.startsWith(base)||url.startsWith(`blob:${base}/`)?r.continue():r.abort();});
// Vercel's injected review toolbar is hosting chrome, outside the app flow.
// Stub only that script; application console failures still fail verification.
await context.route('https://vercel.live/_next-live/feedback/feedback.js',r=>r.fulfill({contentType:'application/javascript',body:''}));
// Synthetic auth belongs to the intercepted client/API fixtures. Strip it from
// server page requests without a second fetch/fulfill lifecycle for prefetches.
await context.route(base+'/**',route=>route.continue(new URL(route.request().url()).pathname.startsWith('/_next/static/')?{}:{headers:{...route.request().headers(),cookie:''}}));
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:uid,display_name:'수업 검수',role:'teacher',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(['classroom_append_entry','classroom_append_study'].includes(table)){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query(table==='classroom_append_study'?'select classroom_append_study($1,$2,$3,$4,$5) result':'select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation,...(table==='classroom_append_study'?[body.p_seed]:[])])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){if(error.code==='40001'&&table==='viewer_replace_analysis'){revisionConflicts++;report.expectedTransport.push('stale background analysis rejected by SQL revision check');}return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  const bookKey=url.searchParams.get('processed_json->metadata->book->>key');if(bookKey?.startsWith('eq.'))rows=rows.filter(row=>row.processed_json.metadata.book?.key===bookKey.slice(3));
  const select=url.searchParams.get('select')||'';
  if(select.includes('processed_json->status'))rows=rows.map(row=>({...row,status:row.processed_json.status,book:row.processed_json.metadata.book}));
  if(select&&select!=='*'&&!select.includes('->'))rows=rows.map(row=>Object.fromEntries(select.split(',').map(key=>key.trim()).map(key=>[key,row[key]])));
  return send(object?(rows[0]||null):rows);
 }
 if(table==='morpheme_dictionary'){tabletState.lookups++;if(tabletState.dictionaryDelay)await new Promise(resolve=>setTimeout(resolve,tabletState.dictionaryDelay));return send(object?{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}:[{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}]);}
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});
const cloud=await installBoardCloudFixture({context,db,uid,cors,report});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{
 if(cloud.state.expectedErrors>0&&/503|409|400|ERR_FAILED|Load failed/.test(m.text())){cloud.state.expectedErrors--;return;}
 if(m.type()!=='error'||m.text().startsWith('WebSocket connection')||(lookupError&&m.text().includes('503')))return;
 if(revisionConflicts>0&&m.text().includes('409 (Conflict)')){revisionConflicts--;return;}
 report.errors.push(m.text());console.log('browser-console',m.text());
});
// Leaving links should not fetch account/team/session pages during reading.
// Keep real navigation requests and every console error visible to the verifier.
page.on('request',request=>{
 const url=new URL(request.url()),headers=request.headers();
 if(page.url().startsWith(base+'/viewer/')&&headers['next-router-prefetch']==='1'&&headers.rsc==='1'&&['/home','/class/fixture-class','/study'].includes(url.pathname))report.readingPrefetch.push(url.pathname);
});
page.on('requestfailed',request=>{const url=new URL(request.url());report.failedRequests.push(url.origin+url.pathname);});
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){
 await page.waitForTimeout(2600);await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'로그인',exact:true}).last()[activate]();await page.waitForURL('**/home');
 // Complete the fixture login landing before a hard navigation. WebKit can
 // report requests interrupted during the document swap as access-control errors.
 await page.getByRole('heading',{name:/첫 표현을 담아/}).waitFor();
 await page.getByRole('heading',{name:/말이 태어나는 곳을/}).waitFor();
 await page.waitForLoadState('networkidle');
}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}

let annotationLost=false;
await context.route('**/api/materials/*/annotations*',async r=>{
 try{await db.exec('RESET ROLE;SET ROLE service_role');
 if(r.request().method()==='POST'){
  const b=r.request().postDataJSON();
  const result=(await db.query('select save_textbook_annotation($1,10,$2,$3,$4) result',[uid,b.operation,b.annotation,{sequence:book.sequence,dictionary:book.dictionary}])).rows[0].result;
  if(annotationLost){annotationLost=false;return r.abort('failed');}
  return r.fulfill({json:{annotation:result}});
 }
 const materialId=Number(new URL(r.request().url()).pathname.split('/')[3]);
 const rows=(await db.query('select * from textbook_annotations where material_id=$1 order by created_at',[materialId])).rows;
 const history=(await db.query('select * from textbook_annotation_revisions order by created_at desc')).rows;
 return r.fulfill({json:{materialId:'10',canEdit:true,annotations:rows,history}});
 }catch(e){return r.fulfill({status:409,json:{error:e.message,conflict:true}});}finally{await db.exec('RESET ROLE;SET ROLE authenticated');}
});
const readBoards=()=>page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const q=indexedDB.open('manabi-teaching-boards');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});return new Promise((resolve,reject)=>{const q=db.transaction('boards').objectStore('boards').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});});
const head=async()=> (await readBoards()).find(row=>row.id===row.scope);
const scene=async()=>{const row=await head();return row?.document.pages.find(p=>p.id===row.document.activePage)?.elements.filter(el=>!el.isDeleted)||[];};
const saveScreen=async name=>{await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name+'.png');};
let lookupDelay=0,lookupError=false;
await context.route('**/api/classroom/lookup',async route=>{
 const {text,language}=route.request().postDataJSON();if(lookupDelay)await new Promise(r=>setTimeout(r,lookupDelay));
 if(lookupError)return route.fulfill({status:503,json:{error:'뜻을 불러오지 못했어요.'}});
 return route.fulfill({json:{text,language,reading:text==='复习'?'fù xí':'liàn xí',source:'ai',senses:[{meaning:text==='复习'?'복습하다':'연습하다',pos:'동사'},{meaning:'연습',pos:'명사'}]}});
});
try {
 await page.goto(base+`/viewer/10?class=fixture-class&day=${day}&board=1`);
 const board=page.getByRole('region',{name:'선생님 설명판'});await board.locator('.excalidraw canvas').first().waitFor();
 const menus=boardMenus(page,activate),hud=menus.hud;
 await menus.layout('함께');
 const originalNote=(await current()).raw_text;
 await page.locator('[data-tid="id_0_word"]')[activate]();
 const inspector=page.locator('.viewer-inspector');
 await inspector.locator('.teaching-word').waitFor();
 const graphic=inspector.locator('.teaching-word-graphic');
 assert(await graphic.locator('.teaching-word-part--hun').count()>0);
 // WebKit's remote SVG boundingBox can include the SVG root. DOM client rects
 // measure the actual rendered glyphs consistently in both engines.
 await waitFor(()=>graphic.evaluate(el=>{const words=[...el.querySelectorAll('.teaching-word-part--text')].map(t=>t.getBoundingClientRect()),meaning=el.querySelector('.teaching-word-part--meaning').getBoundingClientRect();return words.every(r=>r.width>0)&&meaning.left>Math.max(...words.map(r=>r.right));}));
 await saveScreen('word-in-textbook');
 await inspector.getByRole('button',{name:'판에 놓기',exact:true})[activate]();
 await waitFor(async()=> (await scene()).some(el=>el.customData?.manabiExpression));
 const first=(await scene()).find(el=>el.customData?.manabiExpression);
 assert.equal(first.customData.manabiExpression.source.materialId,'10');assert.equal(first.customData.manabiExpression.appearance,'plain');assert.equal(first.backgroundColor,'transparent');
 check('textbook source, upper reading, lower hanja and right meaning are retained in a borderless native group');
 await menus.layout('설명판');
 const add=async(text,reading,meaning)=>{
  await menus.open('entry');const form=hud.locator('#board-menu-entry form');
  await form.getByLabel('단어·표현',{exact:true}).fill(text);
  const details=form.getByRole('button',{name:'읽기와 뜻 입력',exact:true});if(await details.getAttribute('aria-expanded')!=='true')await details[activate]();
  await form.getByLabel('읽기',{exact:true}).fill(reading);await form.getByLabel('뜻',{exact:true}).fill(meaning);
  await form.getByRole('button',{name:'바로 놓기',exact:true})[activate]();
  await waitFor(async()=> (await scene()).some(el=>el.customData?.manabiExpression?.text===text));
 };
 await add('学习','xué xí','배우다, 공부하다');await add('复习','fù xí','복습하다');await add('练习','liàn xí','연습하다');
 assert.equal((await scene()).filter(el=>el.customData?.manabiExpression).length,4);assert.equal((await current()).raw_text,originalNote);
 check('four expressions coexist and do not publish themselves to student records');
 await menus.close();
 await menus.action('tools','펜');
 const surface=board.locator('canvas.interactive'),rect=await surface.boundingBox();
 await page.mouse.move(rect.x+280,rect.y+450);await page.mouse.down();await page.mouse.move(rect.x+640,rect.y+510,{steps:24});await page.mouse.up();
 // IndexedDB can contain an intermediate pointer-move save while the completed
 // stroke is still queued. Compare the finished stroke, including Excalidraw's
 // repeated pointer-up endpoint, rather than a partial line.
 await waitFor(async()=>{const stroke=(await scene()).find(el=>el.type==='freedraw');const points=stroke?.points;return points?.length>2&&JSON.stringify(points.at(-1))===JSON.stringify(points.at(-2));});
 const ink=(await scene()).find(el=>el.type==='freedraw');const beforeInk=JSON.stringify(ink.points);
 await saveScreen('four-words-and-ink');
 await menus.action('tools','선택');await surface.click({position:{x:900,y:600}});await page.keyboard.press('Meta+a');
 await menus.open('selection');const selection=hud.locator('#board-menu-selection');
 const originalExpressions=(await scene()).filter(el=>el.customData?.manabiExpression).map(el=>({text:el.customData.manabiExpression.text,meaning:el.customData.manabiExpression.meaning,source:el.customData.manabiExpression.source}));
 await selection.getByRole('button',{name:'글자만',exact:true})[activate]();
 await waitFor(async()=> (await scene()).filter(el=>el.customData?.manabiExpression).every(el=>el.customData.manabiExpression.appearance==='card'));
 await selection.getByRole('button',{name:'카드',exact:true})[activate]();
 await waitFor(async()=> (await scene()).filter(el=>el.customData?.manabiExpression).every(el=>el.backgroundColor==='transparent'));
 const geometry=()=>scene().then(rows=>rows.map(({id,x,y,width,height})=>({id,x,y,width,height})));
 const before=await geometry();await selection.getByRole('button',{name:'병음',exact:true})[activate]();await selection.getByRole('button',{name:'한자 훈음',exact:true})[activate]();await selection.getByRole('button',{name:'뜻',exact:true})[activate]();
 await waitFor(async()=> (await scene()).filter(el=>['reading','hun','meaning'].includes(el.customData?.manabiField)).every(el=>el.opacity===0));assert.deepEqual(await geometry(),before);
 for(const name of ['병음','한자 훈음','뜻'])await selection.getByRole('button',{name,exact:true})[activate]();
 await selection.getByRole('button',{name:'나란히 정렬',exact:true})[activate]();
 await waitFor(async()=>new Set((await scene()).filter(el=>el.customData?.manabiExpression).map(el=>el.y)).size===1);
 assert.equal(JSON.stringify((await scene()).find(el=>el.id===ink.id).points),beforeInk);
 assert.equal((await scene()).find(el=>el.id===ink.id).x,ink.x);
 assert.deepEqual((await scene()).filter(el=>el.customData?.manabiExpression).map(el=>({text:el.customData.manabiExpression.text,meaning:el.customData.manabiExpression.meaning,source:el.customData.manabiExpression.source})),originalExpressions);
 check('multi-select frame/annotation controls preserve geometry; arranging words does not move ink');
 await selection.getByRole('button',{name:'여백 줄이기',exact:true})[activate]();await page.waitForTimeout(450);
 await menus.action('main','전체 보기');await saveScreen('arranged-words');
 const snapshot=(await scene()).map(({id,type,x,y,customData,points,text})=>({id,type,x,y,customData,points,text}));
 await page.reload();await board.waitFor();await waitFor(async()=> (await scene()).length===snapshot.length);
 assert.deepEqual((await scene()).map(({id,type,x,y,customData,points,text})=>({id,type,x,y,customData,points,text})),snapshot);
 check('annotated groups and handwriting survive reload without reflow');
 await menus.action('main','보여주기');const presentation=page.locator('dialog.board-presentation');await presentation.waitFor();
 await presentation.getByRole('button',{name:'한자 훈음',exact:true})[activate]();await saveScreen('presentation');
 await page.keyboard.press('Escape');await presentation.waitFor({state:'detached'});
 assert.deepEqual((await scene()).map(({id,type,x,y,customData,points,text})=>({id,type,x,y,customData,points,text})),snapshot);
 check('temporary presentation toggles leave every saved expression and ink stroke unchanged');
 await menus.open('book');await hud.getByLabel('수업 교재 과 선택').selectOption('11');
 await page.waitForURL('**/viewer/11?**');await board.locator('.excalidraw canvas').first().waitFor();
 await waitFor(async()=> (await scene()).some(el=>el.customData?.manabiExpression?.source.materialId==='10'));
 check('switching chapters preserves words and source anchors from the previous chapter');
 await menus.open('entry');const form=hud.locator('#board-menu-entry form');
 await form.getByLabel('단어·표현',{exact:true}).fill('复习');
 await form.getByRole('button',{name:'사전 찾기',exact:true})[activate]();await form.getByRole('group',{name:'수업에서 쓸 뜻 선택'}).waitFor();
 await form.getByRole('button',{name:'연습 명사'}).click();
 assert.equal(await form.getByLabel('뜻',{exact:true}).inputValue(),'연습');check('lookup shows AI provenance and lets the teacher select a sense');
 await form.getByLabel('계속 추가',{exact:true}).check();await form.getByRole('button',{name:'바로 놓기',exact:true})[activate]();
 assert(await form.isVisible());assert.equal(await form.getByLabel('단어·표현',{exact:true}).inputValue(),'');
 await form.getByLabel('단어·표현',{exact:true}).fill('새 표현');lookupDelay=800;
 await form.getByRole('button',{name:'사전 찾기',exact:true})[activate]();await form.getByLabel('뜻',{exact:true}).fill('선생이 입력한 뜻');await page.waitForTimeout(1000);
 assert.equal(await form.getByLabel('뜻',{exact:true}).inputValue(),'선생이 입력한 뜻');lookupDelay=0;
 check('continue adding keeps the board in place, and late results cannot overwrite teacher edits');
 lookupError=true;await form.getByLabel('단어·표현',{exact:true}).fill('조회 실패 확인');
 await form.getByRole('button',{name:'사전 찾기',exact:true})[activate]();await page.getByText('뜻을 불러오지 못했어요.',{exact:true}).waitFor();
 await form.getByLabel('뜻',{exact:true}).fill('직접 입력한 뜻');assert.equal(await form.getByLabel('단어·표현',{exact:true}).inputValue(),'조회 실패 확인');
 await saveScreen('lookup-failure');lookupError=false;
 check('a lookup failure preserves the input and allows manual explanation');
 await menus.close();
 await surface.click({position:{x:900,y:650}});await page.keyboard.press('Meta+a');await menus.open('selection');
 await selection.getByRole('button',{name:/선택한 \d+개 수업에 남기기/})[activate]();
 await waitFor(async()=> (await current()).raw_text.includes('图书馆')&&(await current()).raw_text.includes('学习'));
 await waitFor(async()=> (await current()).raw_text.split('\n').filter(text=>text==='复习').length===2);
 const saved=await current(),meanings=Object.values(saved.processed_json.metadata.classMeanings).filter(row=>row.text==='复习').map(row=>row.meaning);
 assert(meanings.includes('복습하다')&&meanings.includes('연습'));
 await menus.close();await hud.getByRole('button',{name:/오늘 표현 \d+개/})[activate]();
 await hud.locator('#board-menu-session').getByRole('heading',{name:'오늘 배운 표현'}).waitFor();
 check('explicit multi-save writes the existing classroom record and the visible list opens in place');
 await menus.close();
 for(const [w,h,label]of [[1024,768,'tablet-landscape'],[768,1024,'tablet-portrait'],[390,844,'phone']]){
  await page.setViewportSize({width:w,height:h});await page.waitForTimeout(400);await menus.action('main','전체 보기');await saveScreen(label);
  assert(await page.locator('.viewer-layout').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await menus.open('entry');await waitFor(()=>form.getByLabel('단어·표현',{exact:true}).evaluate(el=>el===document.activeElement));await form.getByLabel('단어·표현',{exact:true}).fill('换位思考');
  const details=form.getByRole('button',{name:'읽기와 뜻 입력',exact:true});if(await details.getAttribute('aria-expanded')!=='true')await details[activate]();
  await form.getByLabel('읽기',{exact:true}).fill('huàn wèi sī kǎo');await form.getByLabel('뜻',{exact:true}).fill('상대방의 입장에서 생각하다');
  await waitFor(()=>form.locator('.teaching-word-graphic').evaluate(el=>new Set([...el.querySelectorAll('.teaching-word-part--text')].map(t=>t.getAttribute('y'))).size===1));
  await saveScreen(label+'-lookup');
  const action=await form.getByRole('button',{name:'바로 놓기',exact:true}).boundingBox();
  assert(action.y>=0&&action.y+action.height<=h,'placement action stays visible without scrolling the whole menu');
  await menus.close();
 }
 check('tablet landscape/portrait and phone menus stay inside the viewport; four-character words stay together');
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+`/viewer/10?class=fixture-class&day=${day}`);
 const dock=page.getByRole('complementary',{name:'교재 안 수업 도구'});await dock.waitFor();
 await page.locator('[data-tid="id_14_0"]').scrollIntoViewIfNeeded();await page.evaluate(()=>document.fonts.ready);
 const firstToken=await page.locator('[data-tid="id_14_0"] .surface').boundingBox(),lastToken=await page.locator('[data-tid="id_14_2"] .surface').boundingBox();
 await page.mouse.move(firstToken.x+firstToken.width/2,firstToken.y+firstToken.height/2);await page.mouse.down();await page.mouse.move(lastToken.x+lastToken.width/2,lastToken.y+lastToken.height/2,{steps:8});await page.mouse.up();
 await dock.locator('.class-reader-picked strong').filter({hasText:'我们明天见'}).waitFor();
 await dock.getByRole('button',{name:'수업용 뜻 수정',exact:true})[activate]();await dock.getByLabel('수업용 뜻',{exact:true}).fill('우리 내일 만나요');
 await saveScreen('selected-expression');await dock.getByRole('button',{name:'오늘 표현에 추가',exact:true})[activate]();
 await waitFor(async()=> (await current()).raw_text.includes('我们明天见'));
 await waitFor(()=>dock.getByText('서버 저장 확인됨',{exact:true}).isVisible());
 check('the original teacher inspector still edits and records a dragged multiword expression');
 if(process.env.QA_BOARD_CLOUD==='1')await verifyBoardCloud({page,base,day,cloud,check,waitFor,saveScreen,menus,readBoards,uid});
 const returnUrl=page.url(),savedPages=(await head()).document.pages.map(p=>p.id);
 for(const [label,path] of [['팀 홈','/class/fixture-class'],['웹앱 홈','/home']]){
  await menus.open('main');await hud.getByRole('link',{name:label,exact:true})[activate]();await page.waitForURL(base+path);
  if(path==='/home')await page.getByRole('heading',{name:/말이 태어나는 곳을/}).waitFor();
  else await page.getByRole('heading',{name:'목요일의 중국어',exact:true}).waitFor();
  await page.goBack();await page.waitForURL(returnUrl);await board.locator('canvas').first().waitFor();
  assert.deepEqual((await head()).document.pages.map(p=>p.id),savedPages);
 }
 check('home and team links navigate on click and browser back restores every board page');
 assert.deepEqual(report.readingPrefetch,[],'reading and board menus do not prefetch home, team or study pages');check('reading links request destinations only when used');
 assert.equal(report.errors.length,0,report.errors.join('\n'));check('no browser runtime errors');if(cloud?.state.historyMetrics)report.historyMetrics=cloud.state.historyMetrics;
} catch(error){report.failure=error.stack;await saveScreen('failure');console.error(await page.locator('body').innerText());throw error;}
finally{await fs.promises.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await db.close();}
