// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium,webkit} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:3108',out=process.env.QA_OUT||'/private/tmp/manabi-board-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,lesson_explanation_ko text,conversation_script text,direction text NOT NULL DEFAULT 'read',source_pdf_id uuid,page_start integer,page_end integer,document_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE,SELECT,UPDATE ON SEQUENCE reading_materials_id_seq TO authenticated;GRANT ALL ON reading_materials TO service_role;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql','20260910024120_classroom_study_flow.sql','20260910070535_textbook_teaching_annotations.sql','20260911072945_classroom_source_anchors.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Chinese',team:{key:'fixture-class',root:true,name:'목요일의 중국어',lang:'Chinese',bookKey:'fixture-book',chapterId:10,pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.query('INSERT INTO auth.users VALUES($1)',[uid]);await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const words=['图书馆','学生','老师','学校','学习','明天','今天','谢谢','朋友','中文','工作','欢迎','这里','那里'];
const book={sequence:[],dictionary:{},status:'completed',failed_indices:[],metadata:{language:'Chinese',book:{key:'fixture-book',order:1}}};
words.forEach((text,i)=>{const id=`id_${i}_word`,br=`br_${i}_end_fixture`;book.sequence.push(id,br);book.dictionary[id]={text,meaning:`뜻 ${i+1}`,furigana:i===0?'tú shū guǎn':'',pos:'명사',base:text};book.dictionary[br]={text:'\n',pos:'개행'};});
for(const [i,text]of ['我们','明天','见','。'].entries()){const id=`id_14_${i}`;book.sequence.push(id);book.dictionary[id]={text,meaning:['우리','내일','보다',''][i],pos:i===3?'기호':'표현'};}
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(10,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 함께 공부하는 하루',words.join('\n')+'\n我们明天见。','private',book]);
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(11,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 다음 과',words.join('\n'),'private',{...book,metadata:{...book.metadata,book:{key:'fixture-book',order:2}}}]);
await db.exec("select setval('reading_materials_id_seq',20)");
const engine=process.env.QA_BROWSER||'chromium',touch=process.env.QA_TOUCH==='1',activate=touch?'tap':'click';
assert(['chromium','webkit'].includes(engine),'QA_BROWSER must be chromium or webkit');
const browser=await (engine==='webkit'?webkit:chromium).launch({...(engine==='chromium'?{executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{}),headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:touch,serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const tabletState={dictionaryDelay:0,lookups:0};
const report={engine,touch,checks:[],errors:[],screens:[]},writes=[];
await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
// Synthetic auth belongs to the intercepted client/API fixtures. Strip it from
// server page requests without a second fetch/fulfill lifecycle for prefetches.
await context.route(base+'/**',route=>route.continue(new URL(route.request().url()).pathname.startsWith('/_next/static/')?{}:{headers:{...route.request().headers(),cookie:''}}));
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:uid,display_name:'수업 검수',role:'teacher',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(['classroom_append_entry','classroom_append_study'].includes(table)){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query(table==='classroom_append_study'?'select classroom_append_study($1,$2,$3,$4,$5) result':'select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation,...(table==='classroom_append_study'?[body.p_seed]:[])])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  const bookKey=url.searchParams.get('processed_json->metadata->book->>key');if(bookKey?.startsWith('eq.'))rows=rows.filter(row=>row.processed_json.metadata.book?.key===bookKey.slice(3));
  const select=url.searchParams.get('select')||'';
  if(select.includes('processed_json->status'))rows=rows.map(row=>({...row,status:row.processed_json.status,book:row.processed_json.metadata.book}));
  if(select&&select!=='*'&&!select.includes('->'))rows=rows.map(row=>Object.fromEntries(select.split(',').map(key=>key.trim()).map(key=>[key,row[key]])));
  return send(object?(rows[0]||null):rows);
 }
 if(table==='morpheme_dictionary'){tabletState.lookups++;if(tabletState.dictionaryDelay)await new Promise(resolve=>setTimeout(resolve,tabletState.dictionaryDelay));return send(object?{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}:[{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}]);}
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error' && !m.text().startsWith('WebSocket connection')){report.errors.push(m.text());console.log('browser-console',m.text());}});
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){
 await page.waitForTimeout(2600);await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'로그인',exact:true}).last()[activate]();await page.waitForURL('**/home');
 // Complete the fixture login landing before a hard navigation. WebKit can
 // report requests interrupted during the document swap as access-control errors.
 await page.getByRole('heading',{name:/첫 표현을 담아/}).waitFor();
 await page.getByRole('heading',{name:/말이 태어나는 곳을/}).waitFor();
}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}

let annotationLost=false;
await context.route('**/api/materials/*/annotations*',async r=>{
 try{await db.exec('RESET ROLE;SET ROLE service_role');
 if(r.request().method()==='POST'){
  const b=r.request().postDataJSON();
  const result=(await db.query('select save_textbook_annotation($1,10,$2,$3,$4) result',[uid,b.operation,b.annotation,{sequence:book.sequence,dictionary:book.dictionary}])).rows[0].result;
  if(annotationLost){annotationLost=false;return r.abort('failed');}
  return r.fulfill({json:{annotation:result}});
 }
 const materialId=Number(new URL(r.request().url()).pathname.split('/')[3]);
 const rows=(await db.query('select * from textbook_annotations where material_id=$1 order by created_at',[materialId])).rows;
 const history=(await db.query('select * from textbook_annotation_revisions order by created_at desc')).rows;
 return r.fulfill({json:{materialId:'10',canEdit:true,annotations:rows,history}});
 }catch(e){return r.fulfill({status:409,json:{error:e.message,conflict:true}});}finally{await db.exec('RESET ROLE;SET ROLE authenticated');}
});
const readBoards=()=>page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const q=indexedDB.open('manabi-teaching-boards');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});return new Promise((resolve,reject)=>{const q=db.transaction('boards').objectStore('boards').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});});
const head=async()=> (await readBoards()).find(row=>row.id===row.scope);
const scene=async()=>{const row=await head();return row?.document.pages.find(p=>p.id===row.document.activePage)?.elements.filter(el=>!el.isDeleted)||[];};
const saveScreen=async name=>{await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name+'.png');};
try {
 await page.goto(base+`/viewer/10?class=fixture-class&day=${day}&board=1`);
 const board=page.getByRole('region',{name:'선생님 설명판'});await board.waitFor();
 await board.locator('.excalidraw canvas').first().waitFor();
 const originalBook=(await db.query('select raw_text,processed_json from reading_materials where id=10')).rows[0];
 const originalNote=(await current()).raw_text;
 await page.locator('[data-tid="id_0_word"]')[activate]();
 await board.getByRole('button',{name:'판에 놓기',exact:true})[activate]();
 await waitFor(async()=> (await scene()).length===4);
 assert.equal((await scene()).find(el=>el.customData?.manabiExpression).customData.manabiExpression.source.materialId,'10');
 await saveScreen('board-textbook');check('selected textbook expression imports with reading, meaning and exact source');
 const originalBoard=JSON.stringify(await head());
 await board.getByRole('button',{name:'선택한 내용 보여주기',exact:true})[activate]();
 const presentation=page.getByRole('dialog',{name:'학생에게 보여주기'});await presentation.waitFor();
 const displayed=await presentation.locator('canvas.static').evaluate(el=>el.toDataURL());
 await presentation.getByRole('button',{name:'뜻 가리기',exact:true})[activate]();
 await waitFor(async()=>await presentation.locator('canvas.static').evaluate(el=>el.toDataURL())!==displayed);
 await presentation.getByRole('button',{name:'뜻 보이기',exact:true})[activate]();
 await presentation.getByRole('button',{name:'레이저',exact:true})[activate]();
 await saveScreen('board-presentation');
 await presentation.getByRole('button',{name:'← 설명판으로',exact:true})[activate]();
 assert.equal(JSON.stringify(await head()),originalBoard,'presentation must not write the original board');
 await board.getByRole('button',{name:'선택한 내용 보여주기',exact:true})[activate]();await presentation.waitFor();
 await page.keyboard.press('Escape');await presentation.waitFor({state:'detached'});
 assert(await board.getByRole('button',{name:'선택한 내용 보여주기',exact:true}).evaluate(el=>el===document.activeElement),'Escape returns keyboard focus to the original trigger');
 check('presentation enlarges selected content; temporary hiding and laser never rewrite original scene');
 const paper=await board.locator('canvas.interactive').boundingBox();
 const rectangle=(await scene()).find(el=>el.type==='rectangle');
 const sx=paper.x+rectangle.x+10,sy=paper.y+rectangle.y+18,ex=paper.x+rectangle.x+rectangle.width-10;
 const pixelAt=()=>board.locator('canvas.static').evaluate((canvas,{x,y})=>Array.from(canvas.getContext('2d').getImageData(x*devicePixelRatio,y*devicePixelRatio,1,1).data),{x:rectangle.x+80,y:rectangle.y+18});
 const beforePixel=await pixelAt();
 await board.getByRole('button',{name:'펜',exact:true})[activate]();
 await page.mouse.move(sx,sy);await page.mouse.down();await page.mouse.move(ex,sy,{steps:30});await page.mouse.up();
 await waitFor(async()=> (await scene()).some(el=>el.type==='freedraw'));
 assert.notDeepEqual(await pixelAt(),beforePixel,'ink must render ON TOP of the card');
 await saveScreen('board-ink');check('real pointer ink remains visible over semantic expression');
 await board.getByTestId('button-undo')[activate]();await waitFor(async()=> !(await scene()).some(el=>el.type==='freedraw'));
 await board.getByTestId('button-redo')[activate]();await waitFor(async()=> (await scene()).some(el=>el.type==='freedraw'));
 check('native undo and redo restore the stroke without reader grading');
 await board.getByRole('button',{name:'선택',exact:true})[activate]();
 await board.locator('canvas.interactive').click({position:{x:500,y:400}});await page.keyboard.press('Meta+a');
 await board.getByRole('button',{name:'함께 묶기',exact:true})[activate]();
 await waitFor(async()=> (await scene()).every(el=>el.groupIds.length>0));
 const beforeMove=await scene();
 await page.mouse.move(paper.x+rectangle.x+rectangle.width-20,paper.y+rectangle.y+rectangle.height-16);await page.mouse.down();await page.mouse.move(paper.x+rectangle.x+rectangle.width+50,paper.y+rectangle.y+rectangle.height+34,{steps:12});await page.mouse.up();
 await waitFor(async()=>Math.abs((await scene()).find(el=>el.id===rectangle.id).x-rectangle.x)>20);
 const moved=await scene();const delta=moved.find(el=>el.id===rectangle.id).x-rectangle.x;
 for(const el of moved)assert(Math.abs(el.x-beforeMove.find(old=>old.id===el.id).x-delta)<1,'grouped expression and ink move together');
 const saved=JSON.stringify(moved.map(({id,type,x,y,text,points,customData,groupIds})=>({id,type,x,y,text,points,customData,groupIds})));
 await page.reload();await board.waitFor();await waitFor(async()=> (await scene()).length===5);
 assert.equal(JSON.stringify((await scene()).map(({id,type,x,y,text,points,customData,groupIds})=>({id,type,x,y,text,points,customData,groupIds}))),saved);
 check('group moves as one explanation, then survives reload with ink, source and positions');
 await page.getByRole('button',{name:'표현 입력',exact:true})[activate]();
 const form=board.getByRole('form',{name:'표현 불러오기'});
 await form.getByLabel('단어·표현',{exact:true}).fill('你好');await form.getByRole('button',{name:'읽기와 뜻 입력',exact:true})[activate]();await form.getByLabel('뜻',{exact:true}).fill('안녕하세요');
 await form.getByRole('button',{name:'바로 놓기',exact:true})[activate]();
 await waitFor(async()=> (await scene()).filter(el=>el.customData?.manabiExpression).length===2);
 assert.equal((await current()).raw_text,originalNote,'displaying a manual expression does not publish it');
 await board.getByRole('button',{name:'오늘 표현에 추가',exact:true})[activate]();
 await waitFor(async()=> (await current()).raw_text.includes('你好'));
 check('manual expression displays immediately; only explicit add writes the existing classroom record');
 await board.getByRole('button',{name:'뜻 가리기',exact:true})[activate]();
 await waitFor(async()=> (await scene()).find(el=>el.customData?.manabiExpression?.text==='你好').customData.manabiExpression.showMeaning===false);
 assert.equal((await scene()).filter(el=>el.customData?.manabiField==='meaning').at(-1).opacity,0);
 await board.getByRole('button',{name:'뜻 보이기',exact:true})[activate]();
 await board.getByRole('button',{name:'새 판',exact:true})[activate]();await waitFor(async()=> (await head()).document.pages.length===2);
 await board.getByRole('navigation',{name:'설명판 페이지'}).getByRole('button',{name:'1',exact:true})[activate]();
 await waitFor(async()=> (await scene()).length===9);
 await page.getByLabel('수업 교재 과 선택').selectOption('11');await page.waitForURL('**/viewer/11?**');await board.waitFor();
 assert.equal(new URL(page.url()).searchParams.get('board'),'1');await waitFor(async()=> (await scene()).length===9);
 check('reading/meaning toggles and pages persist; changing textbooks keeps the same lesson board');
 const quick=board.getByRole('form',{name:'표현 불러오기'}).getByLabel('단어·표현',{exact:true});
 await quick.fill('준비 중인 표현');
 const divider=board.getByRole('separator',{name:'설명판 너비'});await divider.focus();await divider.press('ArrowLeft');
 const ratio=await divider.getAttribute('aria-valuenow');
 await page.getByRole('link',{name:'이전 과',exact:true})[activate]();await page.waitForURL('**/viewer/10?**');await board.waitFor();
 assert.equal(await quick.inputValue(),'준비 중인 표현');assert.equal(await divider.getAttribute('aria-valuenow'),ratio);
 await page.getByRole('link',{name:'다음 과',exact:true})[activate]();await page.waitForURL('**/viewer/11?**');await board.waitFor();
 assert.equal(new URL(page.url()).searchParams.get('board'),'1');assert.equal(await quick.inputValue(),'준비 중인 표현');
 await quick.fill('');
 check('both chapter arrows preserve the board, unfinished input and keyboard-adjusted split ratio');
 assert.deepEqual((await db.query('select raw_text,processed_json from reading_materials where id=10')).rows[0],originalBook);
 await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(500);await saveScreen('board-tablet-landscape');
 assert(await page.locator('.viewer-center').isVisible());
 assert(await page.locator('canvas.interactive').evaluate(el=>el.getBoundingClientRect().height>100));
 await page.setViewportSize({width:768,height:1024});await page.waitForTimeout(500);await saveScreen('board-tablet-portrait');
 assert(await page.locator('.viewer-center').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth+1;}));
 assert(await page.locator('.viewer-layout').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);await saveScreen('board-phone');
 assert(await board.getByTestId('button-undo').isVisible(),'phone keeps native undo available');
 assert(await board.getByTestId('button-redo').isVisible(),'phone keeps native redo available');
 const mobileScene=await head(),mobilePage=mobileScene.document.pages.find(p=>p.id===mobileScene.document.activePage);
 assert(await board.locator('.teaching-board-surface').evaluate((surface,{elements,camera})=>elements.filter(el=>!el.isDeleted&&el.type==='text'&&el.opacity!==0).every(el=>{
   const x=(el.x+el.width/2+camera.scrollX)*camera.zoom.value,y=(el.y+el.height/2+camera.scrollY)*camera.zoom.value;
   return x>=0&&x<=surface.clientWidth&&y>=0&&y<=surface.clientHeight;
 }),mobilePage),'resizing an unselected board keeps its text on screen');
 const stacked=await page.locator('.viewer-layout').evaluate(root=>{const b=root.querySelector('.teaching-board-host').getBoundingClientRect(),r=root.querySelector('.viewer-center').getBoundingClientRect();return {boardBottom:b.bottom,readerTop:r.top,boardWidth:b.width,readerWidth:r.width,width:root.clientWidth};});
 assert(stacked.boardBottom<=stacked.readerTop+1,'phone board and textbook must never overlap');
 assert(stacked.boardWidth>=stacked.width-2&&stacked.readerWidth>=stacked.width-2,'each stacked pane must have the full phone width');
 assert(await page.locator('.viewer-layout').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 // Model the visual viewport shrinking without shrinking the layout viewport,
 // as a software keyboard does. This does not claim physical iOS IME coverage.
 await quick.focus();
 await page.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,get:()=>innerHeight-310});visualViewport.dispatchEvent(new Event('resize'));});
 await page.waitForTimeout(500);
 assert.equal(await page.locator('.viewer-layout').getAttribute('data-keyboard-open'),'true');
 assert(await form.getByRole('button',{name:'바로 놓기',exact:true}).evaluate(el=>el.getBoundingClientRect().bottom<=visualViewport.height+1),'quick insertion stays above the software keyboard');
 await saveScreen('board-phone-keyboard');
 await page.evaluate(()=>{delete visualViewport.height;visualViewport.dispatchEvent(new Event('resize'));});
 await page.waitForTimeout(500);
 assert(await page.locator('.viewer-center').isVisible(),'closing the keyboard restores the textbook pane');
 check('visual viewport keyboard resize keeps expression input visible and restores the textbook after closing');
 await page.setViewportSize({width:1440,height:1000});
 check('desktop/tablet/phone layouts retain textbook access without horizontal overflow');
 // Local search retains the exact chapter source. Editing an existing card
 // must leave an unfinished new-expression draft available after cancel/save.
 await quick.fill('老师');
 await board.locator('.board-search-results').getByRole('button',{name:/老师/})[activate]();
 await waitFor(async()=>(await scene()).some(el=>el.customData?.manabiExpression?.text==='老师'));
 const localCard=(await scene()).find(el=>el.customData?.manabiExpression?.text==='老师');
 assert.equal(localCard.customData.manabiExpression.source.materialId,'11');
 await quick.fill('다음 설명 초안');
 await board.getByRole('button',{name:'내용 수정',exact:true})[activate]();
 await form.getByLabel('뜻',{exact:true}).fill('취소할 설명');
 await form.getByRole('button',{name:'수정 취소',exact:true})[activate]();
 assert.equal(await quick.inputValue(),'다음 설명 초안');
 assert.equal((await scene()).find(el=>el.id===localCard.id).customData.manabiExpression.meaning,localCard.customData.manabiExpression.meaning);
 await board.getByRole('button',{name:'내용 수정',exact:true})[activate]();
 await form.getByLabel('뜻',{exact:true}).fill('선생님');
 await form.getByRole('button',{name:'수정',exact:true})[activate]();
 await waitFor(async()=>(await scene()).find(el=>el.id===localCard.id).customData.manabiExpression.meaning==='선생님');
 assert.equal(await quick.inputValue(),'다음 설명 초안');
 await quick.fill('');
 check('local textbook search keeps its chapter source; editing and cancelling preserve the separate input draft');
 // Two tabs share the same real IndexedDB. A stale tab must preserve a recovery copy.
 const other=await context.newPage();await other.goto(page.url());await other.getByRole('region',{name:'선생님 설명판'}).waitFor();await other.waitForTimeout(800);
 await board.getByRole('button',{name:'새 판',exact:true})[activate]();await waitFor(async()=> (await head()).document.pages.length===3);
 await other.getByRole('button',{name:'새 판',exact:true})[activate]();
 await other.getByText('다른 창에서 이 판을 수정했어요.',{exact:false}).first().waitFor();
 await waitFor(async()=> (await readBoards()).some(row=>row.id!==row.scope));
 assert.equal((await head()).document.pages.length,3);
 await other.close();await page.reload();await board.waitFor();await board.getByText('보관',{exact:true})[activate]();
 await board.getByRole('button',{name:'충돌본 1 불러오기',exact:true})[activate]();
 await waitFor(async()=> (await head()).document.pages.length===6);
 check('cross-tab save conflict never overwrites the latest board; recovery copy can be reopened');
 // Japanese kana candidates remain a teacher choice; browser IME confirmation is not submission.
 const rootJson=(await db.query('select processed_json from reading_materials where id=1')).rows[0].processed_json;
 rootJson.metadata.team.lang='Japanese';
 await db.query('update reading_materials set processed_json=$1 where id=1',[rootJson]);
 const kanaIndex=JSON.parse(fs.readFileSync(new URL('../src/lib/data/jaYomiIndex.json',import.meta.url)));
 await context.route('**/api/classroom/kana?**',r=>r.fulfill({json:{candidates:(kanaIndex['はし']||[]).map(([text,level])=>({text,level,reading:'はし'}))}}));
 await page.reload();await board.waitFor();
 await page.getByRole('button',{name:'표현 입력',exact:true})[activate]();
 const japaneseForm=board.getByRole('form',{name:'표현 불러오기'}), query=japaneseForm.getByLabel('단어·표현',{exact:true});
 await query.fill('はし');
 await query.dispatchEvent('compositionstart');await query.press('Enter');
 assert(await japaneseForm.isVisible());await query.dispatchEvent('compositionend');
 await japaneseForm.getByRole('button',{name:'사전 찾기',exact:true})[activate]();
 await board.getByRole('button',{name:/橋/}).waitFor();
 await board.getByRole('button',{name:/箸/}).waitFor();
 assert.equal(await query.inputValue(),'はし');
 await board.getByRole('button',{name:/箸/})[activate]();assert.equal(await query.inputValue(),'箸');await japaneseForm.getByRole('button',{name:'사전 찾기',exact:true}).waitFor();
 await japaneseForm.getByLabel('읽기',{exact:true}).fill('はし');await japaneseForm.getByLabel('뜻',{exact:true}).fill('젓가락');
 await japaneseForm.getByRole('button',{name:'바로 놓기',exact:true})[activate]();
 await waitFor(async()=> (await scene()).some(el=>el.customData?.manabiExpression?.text==='箸'));
 await saveScreen('board-japanese');check('kana input offers separate kanji choices; IME confirmation never inserts prematurely');
 // A 1024×768 browser at 121% zoom exposes about 846×634 CSS pixels.
 // Native mobile tools must not cover the selected card's meaning in that space.
 await page.setViewportSize({width:846,height:634});
 const unobstructed=async()=>{
  const row=await head(),active=row.document.pages.find(p=>p.id===row.document.activePage),card=active.elements.find(el=>!el.isDeleted&&el.customData?.manabiExpression?.text==='箸');
  const result=await board.locator('.teaching-board-surface').evaluate((surface,{card,camera})=>{
   const canvas=surface.getBoundingClientRect(),toolbar=surface.querySelector('.App-toolbar:not(.App-bottom-bar .App-toolbar)')?.getBoundingClientRect(),footer=surface.querySelector('.App-bottom-bar .Island')?.getBoundingClientRect();
   const y=canvas.top+(card.y+camera.scrollY)*camera.zoom.value,bottom=y+card.height*camera.zoom.value;
   return {fits:y>=(toolbar?.height?toolbar.bottom:canvas.top)+15 && bottom<=(footer?.top || canvas.bottom)-15,y,bottom,top:toolbar?.bottom,footer:footer?.top,card,camera};
  },{card,camera:active.camera});
  return result.fits;
 };
 await waitFor(unobstructed);await saveScreen('board-browser-zoom');
 await board.getByRole('button',{name:'전체 보기',exact:true})[activate]();await waitFor(unobstructed);
 check('selected expression and fit-all stay clear of mobile toolbars at 121-percent browser zoom');
 await page.setViewportSize({width:1440,height:1000});
 // No debounce wait: a just-added expression must survive immediate chapter navigation.
 const quickBeforeMove=board.getByRole('form',{name:'표현 불러오기'}).getByLabel('단어·표현',{exact:true});
 await quickBeforeMove.fill('即座に');await quickBeforeMove.press('Enter');
 await page.getByRole('link',{name:'이전 과',exact:true})[activate]();await page.waitForURL('**/viewer/10?**');await board.waitFor();
 await waitFor(async()=>(await scene()).some(el=>el.customData?.manabiExpression?.text==='即座に'));
 check('text-only immediate insertion survives a chapter change without waiting for autosave');
 // Backup round-trip appends a new page, leaving the current board and original textbook intact.
 const backupMenu=board.locator('.teaching-board-footer details');if(!await backupMenu.getAttribute('open'))await backupMenu.locator('summary')[activate]();
 const downloaded=page.waitForEvent('download');await backupMenu.getByRole('button',{name:'내려받기',exact:true})[activate]();
 const download=await downloaded, file=out+'/backup.json';await download.saveAs(file);
 const restored=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(restored.format,'manabi-teaching-board');
 const count=restored.document.pages.length;
 await backupMenu.locator('input[type=file]').setInputFiles(file);await waitFor(async()=> (await head()).document.pages.length===count*2);
 const revisionBefore=(await head()).revision;
 await backupMenu.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"other"}')});
 await board.getByText('manabi 설명판 백업 파일을 골라 주세요.',{exact:true}).waitFor();assert.equal((await head()).revision,revisionBefore);
 await page.getByRole('navigation',{name:'설명판 보기'}).getByRole('button',{name:'설명판',exact:true})[activate]();assert.equal(await page.locator('.viewer-center').isVisible(),false);
 await page.getByRole('navigation',{name:'설명판 보기'}).getByRole('button',{name:'함께',exact:true})[activate]();assert(await page.locator('.viewer-center').isVisible());
 await page.getByRole('navigation',{name:'설명판 보기'}).getByRole('button',{name:'교재',exact:true})[activate]();assert.equal(await board.locator('canvas.interactive').isVisible(),false);
 await page.getByRole('navigation',{name:'설명판 보기'}).getByRole('button',{name:'함께',exact:true})[activate]();await board.locator('canvas.interactive').waitFor({state:'visible'});
 check('backup round-trip, invalid-file protection and board/textbook view switching');
 await page.goto(base+'/viewer/10');await page.locator('[data-tid="id_0_word"]').waitFor();assert.equal(await page.getByRole('region',{name:'선생님 설명판'}).count(),0);
 check('personal viewer stays unchanged outside a teacher classroom');
 assert.equal(report.errors.length,0,report.errors.join('\n'));
 check('no browser runtime errors');
} catch(error) {await saveScreen('failure');console.error(await page.locator('body').innerText());throw error;}
finally {await fs.promises.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await db.close();}
