// Real React pages + HTTP fixtures + actual disposable PostgreSQL RPCs. No production writes.
import {chromium} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');
const base=process.env.QA_BASE||'http://127.0.0.1:8912',out=process.env.QA_OUT||'/private/tmp/manabi-teaching-qa';fs.mkdirSync(out,{recursive:true});
const db=new PGlite();const uid='00000000-0000-4000-8000-000000000077',day='2026-09-10';
await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE TABLE reading_materials(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner_id uuid,title text,raw_text text,visibility text,processed_json jsonb,lesson_explanation_ko text,conversation_script text,direction text NOT NULL DEFAULT 'read',source_pdf_id uuid,page_start integer,page_end integer,document_json jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE user_vocabulary(id uuid PRIMARY KEY,user_id uuid);CREATE TABLE vocabulary_contexts(id uuid PRIMARY KEY,user_id uuid,vocabulary_id uuid REFERENCES user_vocabulary(id));
GRANT USAGE ON SCHEMA auth TO authenticated,anon;GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER TABLE reading_materials ENABLE ROW LEVEL SECURITY;CREATE POLICY mine ON reading_materials TO authenticated USING(owner_id=auth.uid()) WITH CHECK(owner_id=auth.uid());GRANT SELECT,INSERT,UPDATE ON reading_materials TO authenticated;GRANT USAGE,SELECT,UPDATE ON SEQUENCE reading_materials_id_seq TO authenticated;GRANT ALL ON reading_materials TO service_role;`);
for(const f of ['20260908234552_viewer_reliability_atomic_operations.sql','20260909165823_classroom_atomic_entries.sql','20260910024120_classroom_study_flow.sql','20260910070535_textbook_teaching_annotations.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const meta={language:'Chinese',team:{key:'fixture-class',root:true,name:'목요일의 중국어',lang:'Chinese',bookKey:'fixture-book',chapterId:10,pwGen:1,pwSalt:'fixture',pwHash:'fixture'}};
await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5)',[uid,'수업 설정','수업 설정','private',{sequence:[],dictionary:{},metadata:meta}]);
await db.query('INSERT INTO auth.users VALUES($1)',[uid]);await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
const callAppend=async text=>(await db.query('select classroom_append_entry(1,$1,$2,$3) result',[day,text,crypto.randomUUID()])).rows[0].result.material;
let note;for(const text of ['いかがですか','お先に失礼します','また来週'])note=await callAppend(text);
const json=note.processed_json;json.sequence=[];json.dictionary={};json.failed_indices=[];json.status='completed';json.metadata.classMeanings={};
for(const [i,e]of json.metadata.classEntries.entries()){const id=`id_${e.idx}_seed`;json.sequence.push(id);json.dictionary[id]={text:e.text,meaning:['어떠세요?','먼저 실례하겠습니다.','다음 주에 또 만나요.'][i],pos:'표현',furigana:''};json.metadata.classMeanings[e.id]={text:e.text,meaning:json.dictionary[id].meaning};}
await db.query('update reading_materials set processed_json=$1 where id=$2',[json,note.id]);
const words=['图书馆','学生','老师','学校','学习','明天','今天','谢谢','朋友','中文','工作','欢迎','这里','那里'];
const book={sequence:[],dictionary:{},status:'completed',failed_indices:[],metadata:{language:'Chinese',book:{key:'fixture-book',order:1}}};
words.forEach((text,i)=>{const id=`id_${i}_word`,br=`br_${i}_end_fixture`;book.sequence.push(id,br);book.dictionary[id]={text,meaning:`뜻 ${i+1}`,furigana:i===0?'tú shū guǎn':'',pos:'명사',base:text};book.dictionary[br]={text:'\n',pos:'개행'};});
for(const [i,text]of ['我们','明天','见','。'].entries()){const id=`id_14_${i}`;book.sequence.push(id);book.dictionary[id]={text,meaning:['우리','내일','보다',''][i],pos:i===3?'기호':'표현'};}
await db.query('insert into reading_materials(id,owner_id,title,raw_text,visibility,processed_json) values(10,$1,$2,$3,$4,$5)',[uid,'실전 중국어 — 함께 공부하는 하루',words.join('\n')+'\n我们明天见。','private',book]);
await db.exec("select setval('reading_materials_id_seq',20)");
const browser=await chromium.launch({executablePath:process.env.QA_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});context.setDefaultTimeout(25000);context.setDefaultNavigationTimeout(180000);
const enc=v=>Buffer.from(JSON.stringify(v)).toString('base64url'),now=Math.floor(Date.now()/1000);
const user={id:uid,aud:'authenticated',role:'authenticated',email:'classroom-fixture@example.com',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{},identities:[]};
const session={user,access_token:`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,aud:'authenticated',role:'authenticated',exp:now+3600,iat:now})}.fixture`,refresh_token:'fixture',expires_at:now+3600,expires_in:3600,token_type:'bearer'};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*','access-control-expose-headers':'content-range'};
let failure=false,lostResponse=false,analysisDelay=0,analysisFail=false,emptyMeaning=false;
const analyzedLines=[];
const report={checks:[],errors:[],screens:[]},writes=[];
await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());
await context.route(base+'/**',async route=>{if(new URL(route.request().url()).pathname.startsWith('/_next/static/'))return route.continue();const response=await route.fetch({headers:{...route.request().headers(),cookie:''},timeout:180000});await route.fulfill({response});});
await context.route('**/api/**',r=>r.fulfill({json:{}}));
await context.route('**/auth/v1/**',r=>r.fulfill({headers:cors,json:r.request().url().includes('/user')?user:session}));
await context.route('**/rest/v1/**',async r=>{
 const req=r.request(),url=new URL(req.url()),table=url.pathname.split('/').pop(),method=req.method(),object=req.headers().accept?.includes('vnd.pgrst.object');
 const send=(data,status=200)=>r.fulfill({headers:cors,status,json:data});
 if(method==='OPTIONS')return r.fulfill({status:204,headers:cors});if(method==='HEAD')return r.fulfill({headers:{...cors,'content-range':'*/0'},body:''});
 if(table==='profiles')return send({id:uid,display_name:'수업 검수',role:'admin',onboarded:true,last_login_at:new Date().toISOString(),learning_language:['Japanese']});
 if(['POST','PATCH','DELETE'].includes(method)){
  const body=req.postDataJSON();writes.push({table,body});
  try{
   if(['classroom_append_entry','classroom_append_study'].includes(table)){
    if(failure)return send({code:'503',message:'검수용 연결 실패'},503);
    const result=(await db.query(table==='classroom_append_study'?'select classroom_append_study($1,$2,$3,$4,$5) result':'select classroom_append_entry($1,$2,$3,$4) result',[body.p_root,body.p_day,body.p_text,body.p_operation,...(table==='classroom_append_study'?[body.p_seed]:[])])).rows[0].result;
    if(lostResponse){lostResponse=false;return r.abort('failed');}return send(result);
   }
   if(table==='viewer_replace_analysis')return send((await db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',[body.p_id,body.p_expected_raw,body.p_expected_json,body.p_raw,body.p_json,body.p_attempt])).rows[0].result);
   if(table==='reading_materials'&&method==='POST'){const result=await db.query('insert into reading_materials(owner_id,title,raw_text,visibility,processed_json) values($1,$2,$3,$4,$5) returning *',[body.owner_id,body.title,body.raw_text,body.visibility,body.processed_json]);return send(result.rows,201);}
   return send([]);
  }catch(error){return send({code:error.code,message:error.message},409);}
 }
 if(table==='reading_materials'){
  let rows=(await db.query('select * from reading_materials')).rows;
  for(const key of ['id','owner_id','visibility']){const v=url.searchParams.get(key);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row[key])===v.slice(3));}
  for(const key of ['key','day','root']){const v=url.searchParams.get(`processed_json->metadata->team->>${key}`);if(v?.startsWith('eq.'))rows=rows.filter(row=>String(row.processed_json.metadata.team?.[key])===v.slice(3));if(v==='is.null')rows=rows.filter(row=>row.processed_json.metadata.team?.[key]==null);}
  if(url.searchParams.has('processed_json->metadata->book'))rows=rows.filter(row=>row.processed_json.metadata.book);
  const bookKey=url.searchParams.get('processed_json->metadata->book->>key');if(bookKey?.startsWith('eq.'))rows=rows.filter(row=>row.processed_json.metadata.book?.key===bookKey.slice(3));
  const select=url.searchParams.get('select')||'';
  if(select.includes('processed_json->status'))rows=rows.map(row=>({...row,status:row.processed_json.status,book:row.processed_json.metadata.book}));
  return send(object?(rows[0]||null):rows);
 }
 if(table==='morpheme_dictionary')return send(object?{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}:[{reading:'nǐ hǎo',meanings:['안녕하세요'],pos:'표현'}]);
 return send(object?null:[]);
});
await context.route('**/api/suggestions/today',r=>r.fulfill({json:[]}));
await context.route('**/api/analyze',async r=>{if(analysisDelay)await new Promise(resolve=>setTimeout(resolve,analysisDelay));if(analysisFail)return r.fulfill({status:503,json:{error:'검수 분석 실패'}});const {lines}=r.request().postDataJSON();analyzedLines.push(lines);try{await r.fulfill({json:{results:lines.map(line=>({sequence:['word'],dictionary:{word:{text:line,meaning:emptyMeaning?'':'검수 표현의 뜻',pos:'명사',furigana:'よみ'}}}))}});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const check=label=>{report.checks.push(label);console.log(label);};
const waitFor=async fn=>{for(let i=0;i<100;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error('condition timeout');};
const current=async()=>(await db.query("select * from reading_materials where processed_json#>>'{metadata,team,day}'=$1",[day])).rows[0];
if(process.env.QA_LOGIN==='1'){await page.goto(base+'/auth');await page.getByLabel('이메일',{exact:true}).fill(user.email);await page.getByLabel('비밀번호',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'로그인',exact:true}).last().click();await page.waitForURL('**/home');}
else {await context.addCookies([{name:'sb-e2e-auth-token',value:'base64-'+enc(session),url:base,httpOnly:false,sameSite:'Lax'}]);}

let annotationLost=false;
await context.route('**/api/materials/*/annotations*',async r=>{
 try{await db.exec('RESET ROLE;SET ROLE service_role');
 if(r.request().method()==='POST'){
  const b=r.request().postDataJSON();
  const result=(await db.query('select save_textbook_annotation($1,10,$2,$3,$4) result',[uid,b.operation,b.annotation,{sequence:book.sequence,dictionary:book.dictionary}])).rows[0].result;
  if(annotationLost){annotationLost=false;return r.abort('failed');}
  return r.fulfill({json:{annotation:result}});
 }
 const rows=(await db.query('select * from textbook_annotations where material_id=10 order by created_at')).rows;
 const history=(await db.query('select * from textbook_annotation_revisions order by created_at desc')).rows;
 return r.fulfill({json:{materialId:'10',canEdit:true,annotations:rows,history}});
 }catch(e){return r.fulfill({status:409,json:{error:e.message,conflict:true}});}finally{await db.exec('RESET ROLE;SET ROLE authenticated');}
});
try {
const url=base+`/viewer/10?class=fixture-class&day=${day}&returnTo=${encodeURIComponent('/class/fixture-class/live?day='+day)}`;
await page.goto(url);
const dock=page.getByRole('complementary',{name:'교재 안 수업 도구'});await dock.waitFor();
await page.locator('[data-tid="id_0_word"]').click();
const original=await current();
await dock.getByRole('button',{name:'주의점 추가 +',exact:true}).click();
await dock.getByRole('textbox',{name:'교재 주의점 입력'}).fill('图书馆은 책을 읽거나 빌리는 곳입니다. 서점 书店과 구별해요.');
await dock.getByRole('button',{name:'교재에 저장',exact:true}).click();
await dock.getByText('교재에 저장했어요.',{exact:false}).waitFor();
assert.equal((await current()).raw_text,original.raw_text);assert.deepEqual((await current()).processed_json,original.processed_json);check('annotation saves without touching dated notes or textbook');
await dock.getByRole('button',{name:'주의점 추가 +',exact:true}).click();await dock.getByRole('textbox',{name:'교재 주의점 입력'}).fill('图书馆里很安静。');annotationLost=true;await dock.getByRole('button',{name:'교재에 저장',exact:true}).click();
await dock.getByRole('button',{name:'저장 재시도',exact:true}).waitFor();await page.reload();await dock.waitFor();await dock.getByRole('button',{name:'저장 재시도',exact:true}).click();await waitFor(async()=>await dock.getByRole('button',{name:'저장 재시도',exact:true}).count()===0);check('response loss retries exact operation and preserves appended explanation');
await db.exec('RESET ROLE');assert.equal((await db.query('select count(*)::int n from textbook_annotations')).rows[0].n,2);await db.exec('SET ROLE authenticated');
await page.reload();await dock.waitFor();await dock.getByText('图书馆里很安静。',{exact:true}).waitFor();check('annotation automatically returns on next visit at its anchored passage');
await dock.getByRole('button',{name:'접기',exact:true}).last().click();await page.evaluate(()=>scrollTo(0,1000));await page.evaluate(()=>scrollTo(0,0));assert.equal(await dock.getByText('图书馆里很安静。',{exact:true}).count(),0);check('scrolling back does not repeatedly reopen a dismissed annotation');
for(const viewport of [{width:1024,height:768},{width:768,height:1024},{width:390,height:844}]){
 await page.setViewportSize(viewport);await page.locator('[data-tid="id_3_word"]').click();
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const origin=await page.evaluate(()=>scrollY);
 for(let i=0;i<10;i++){
  await dock.getByRole('button',{name:'크게 보여주기',exact:true}).last().click();
  const dialog=page.getByRole('dialog',{name:'학생에게 보여주는 설명'});await dialog.waitFor();
  await dialog.getByRole('button',{name:'뜻 가리기',exact:true}).click();await dialog.getByText('뜻을 떠올려 보세요.',{exact:true}).waitFor();
  if(i===0){const shot=`presentation-${viewport.width}.png`;await page.screenshot({path:out+'/'+shot});report.screens.push(shot);}
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false);
  await dialog.getByRole('button',{name:'교재로 돌아가기 ×',exact:true}).click();await waitFor(async()=>await dialog.count()===0);assert.equal(page.url(),url);
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const restored=await page.evaluate(()=>scrollY);assert(Math.abs(restored-origin)<3,`viewport ${viewport.width} cycle ${i}: before ${origin}, after ${restored}`);
 }
 check(`presentation restores textbook position ten times at ${viewport.width}x${viewport.height}`);
}
await page.setViewportSize({width:1440,height:1000});await page.locator('[data-tid="id_0_word"]').click();
await page.screenshot({path:out+'/textbook-notes-desktop.png'});report.screens.push('textbook-notes-desktop.png');
assert.equal((await current()).raw_text,original.raw_text);check('showing words and annotations never records a class expression');
await dock.getByRole('button',{name:'찾기',exact:true}).first().click();
const search=dock.getByRole('textbox',{name:'단어·표현 찾기'});await search.fill('你好');await search.press('Enter');await waitFor(async()=>await dock.getByRole('textbox',{name:'핵심 뜻',exact:true}).inputValue()==='안녕하세요');
await dock.getByRole('button',{name:'보여주고 기록',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('dialog').getByRole('button',{name:'수업에 기록됨 ✓',exact:true}).waitFor();assert((await current()).raw_text.endsWith('你好'));check('manual expression displays and records with one action');
await page.keyboard.press('Escape');await waitFor(async()=>await page.getByRole('dialog').count()===0);
await page.locator('[data-tid="id_0_word"]').click();
await dock.getByRole('button',{name:'수정',exact:true}).first().click();await dock.getByRole('button',{name:'보관',exact:true}).click();await waitFor(async()=>await dock.getByRole('button',{name:'보관',exact:true}).count()===0);
await dock.getByText('보관한 주의점',{exact:true}).click();await dock.getByRole('button',{name:'다시 표시',exact:true}).click();await waitFor(async()=>await dock.getByRole('button',{name:'다시 표시',exact:true}).count()===0);check('teacher can archive and restore explanations without deleting history');
assert.equal(writes.filter(w=>w.table==='user_vocabulary').length,0);assert.equal(report.errors.length,0,report.errors.join('\n'));check('no personal vocabulary mutations or runtime errors');
} catch(error) {console.error(error);report.failure=error.message;await page.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/failure.html',await page.content());process.exitCode=1;}
fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();await db.close();
