// Run with QA_PGLITE_MODULE pointing to an installed @electric-sql/pglite module. No live DB connection.
const { PGlite } = await import(process.env.QA_PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role authenticated; create role anon; create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
grant usage on schema auth to authenticated, anon; grant execute on function auth.uid() to authenticated,anon;
create table reading_materials(id bigint primary key,owner_id uuid,raw_text text,processed_json jsonb);
create table user_vocabulary(id uuid primary key,user_id uuid,meaning text,last_reviewed_at timestamptz);
create table vocabulary_contexts(id uuid primary key,user_id uuid,vocabulary_id uuid references user_vocabulary(id) on delete cascade);
alter table reading_materials enable row level security; alter table user_vocabulary enable row level security; alter table vocabulary_contexts enable row level security;
create policy mine on reading_materials to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy mine on user_vocabulary to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy mine on vocabulary_contexts to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,update on reading_materials to authenticated; grant select,update,delete on user_vocabulary to authenticated; grant select,delete on vocabulary_contexts to authenticated;`);
await db.exec(fs.readFileSync(new URL('../docs/manabi-viewer-reliability.sql', import.meta.url),'utf8'));
const owner='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',attempt='00000000-0000-4000-8000-000000000003',word='00000000-0000-4000-8000-000000000004',context='00000000-0000-4000-8000-000000000005';
const before={sequence:['id_0_old'],dictionary:{id_0_old:{text:'你好'}},metadata:{language:'Chinese'},status:'completed'};
const after={...before,metadata:{...before.metadata,viewerRevision:attempt}};
await db.query('insert into reading_materials values(1,$1,$2,$3)',[owner,'你好',before]);
await db.query('insert into user_vocabulary values($1,$2,$3,null)',[word,owner,'안녕']);
await db.query('insert into vocabulary_contexts values($1,$2,$3)',[context,owner,word]);
await db.exec('set role authenticated');
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
const args=[1,'你好',before,'你好',after,attempt];
const apply=()=>db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6) result',args);
assert.equal((await apply()).rows[0].result.material.processed_json.metadata.viewerRevision,attempt);
assert.equal((await apply()).rows[0].result.material.id,1);
await assert.rejects(db.query('select viewer_replace_analysis($1,$2,$3,$4,$5,$6)',[1,'你好',before,'你好',{...after,metadata:{...after.metadata,viewerRevision:other}},other]),/다른 창/);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
await assert.rejects(apply(),/수정 권한/);
await db.exec('set role anon'); await assert.rejects(apply(),/permission denied/);
await db.exec('set role authenticated'); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
const snapshot=(await db.query('select to_jsonb(v) v from user_vocabulary v where id=$1',[word])).rows[0].v;
await assert.rejects(db.query('select viewer_undo_vocabulary_save($1,$2,$3)',[word,{...snapshot,meaning:'wrong'},[context]]),/이후 학습/);
await assert.rejects(db.query('select viewer_undo_vocabulary_save($1,$2,$3)',[word,snapshot,[]]),/다른 문맥/);
// A newly hidden source context must block cascade deletion even though SELECT cannot see it.
const hidden='00000000-0000-4000-8000-000000000009';
await db.exec('reset role');
await db.query('insert into vocabulary_contexts values($1,$2,$3)',[hidden,owner,word]);
await db.exec(`drop policy mine on vocabulary_contexts; create policy mine on vocabulary_contexts to authenticated using(user_id=auth.uid() and id <> '${hidden}'::uuid) with check(user_id=auth.uid());`);
await db.exec('set role authenticated');
assert.equal((await db.query('select count(*)::int n from vocabulary_contexts')).rows[0].n,1);
await assert.rejects(db.query('select viewer_undo_vocabulary_save($1,$2,$3)',[word,snapshot,[context]]),/다른 문맥/);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[other]);
assert.equal((await db.query('select viewer_undo_vocabulary_save($1,$2,$3) undone',[word,snapshot,[context,hidden]])).rows[0].undone,false);
await db.exec('reset role');await db.query('delete from vocabulary_contexts where id=$1',[hidden]);
await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
assert.equal((await db.query('select viewer_undo_vocabulary_save($1,$2,$3) undone',[word,snapshot,[context]])).rows[0].undone,true);
assert.equal((await db.query('select count(*)::int n from vocabulary_contexts')).rows[0].n,0);
const routines=(await db.query("select proname,prosecdef from pg_proc where proname in ('viewer_replace_analysis','viewer_undo_vocabulary_save')")).rows;
assert.equal(routines.find(r=>r.proname==='viewer_replace_analysis').prosecdef,false);
assert.equal(routines.find(r=>r.proname==='viewer_undo_vocabulary_save').prosecdef,true);
console.log(JSON.stringify({passed:13,checks:['atomic source+analysis','same attempt retry','stale snapshot conflict','non-owner rejected','anonymous rejected','changed vocabulary rejected','extra context rejected','exact undo','own context cascade','scoped function privileges','hidden context invisible to caller','hidden context blocks cascade','definer rejects non-owner']}));
await db.close();
