import { beforeEach, describe, expect, it, vi } from 'vitest';
const { authenticate, base, overrides } = vi.hoisted(()=>({authenticate:vi.fn(),overrides:vi.fn(),base:{slug:'first',level:'A1',title:'원래 제목',sections:[{heading:'읽어요',examples:[{en:'I read a book.',ko:'책을 읽어요.'}]},{type:'vocabPreview',vocabs:[{word:'book',meanings:['책'],exampleSentence:'Read this book.'}]}]}}));
vi.mock('@/lib/supabaseServer',()=>({requireUser:authenticate}));
vi.mock('@/content/refGrammarLoaders',()=>({getGrammarManifest:()=>({levels:[{key:'A1',chapters:[base]}]}),loadChapter:async()=>({registry:{base:'/english',getChapter:()=>({chapter:base})},data:{chapter:base}})}));
vi.mock('@/lib/contentOverrides',async load=>({...await load(),getOverridesForLang:overrides}));
import * as vocabulary from '../vocabulary/route';
import * as links from '../material-links/route';
const user='10000000-0000-0000-0000-000000000001',id='20000000-0000-0000-0000-000000000001';
const token={text:'books',base_form:'book',meaning:'책',pos:'명사'};
const word={word_text:'book',meaning:'책',language:'English'};
let db;
function database(){
 const state={material:{id:1,title:'내 자료',owner_id:user,visibility:'private',raw_text:'I read books.',processed_json:{metadata:{language:'English'},sequence:['a','b','c'],dictionary:{a:{text:'I'},b:{text:'read'},c:token}}},pdf:{id,owner_id:user,page_count:15},error:null,rpcResult:{data:{vocabularyId:id,contextAdded:true}},existing:{id,meaning:'책'},contexts:[],links:[]};
 const calls=[];
 const supabase={rpc:vi.fn(async()=>state.rpcResult),from:vi.fn(table=>{
  const call={table,filters:[],op:'read'};calls.push(call);
  const result=()=>({error:state.error,data:table==='reading_materials'?state.material:table==='uploaded_pdfs'?state.pdf:table==='user_vocabulary'?state.existing:table==='vocabulary_contexts'?state.contexts:state.links});
  const q={select:()=>q,eq:(k,v)=>{call.filters.push([k,v]);return q;},order:()=>q,limit:()=>q,maybeSingle:async()=>result(),delete:()=>{call.op='delete';return q;},upsert:(value,options)=>{call.op='upsert';call.value=value;call.options=options;return q;},then:resolve=>Promise.resolve(result()).then(resolve)};return q;
 })};return{state,supabase,calls};
}
const request=(body,method='POST',path='vocabulary')=>new Request(`https://fixture.test/api/learning/${path}`,{method,body:JSON.stringify(body),headers:{'Content-Type':'application/json'}});
const save=(body={word,source:{kind:'reading',materialId:'1',tokenId:'c'}})=>vocabulary.POST(request(body));
beforeEach(()=>{db=database();authenticate.mockResolvedValue({user:{id:user},supabase:db.supabase});overrides.mockResolvedValue(new Map());});
describe('학습 연결 API 권한과 검증',()=>{
 it('로그인 없이는 모든 조회·쓰기·삭제를 DB 호출 전에 거부한다',async()=>{authenticate.mockResolvedValue({error:'로그인 필요',status:401});for(const route of [vocabulary,links])for(const method of ['GET','POST','DELETE'])expect((await route[method](new Request('https://fixture.test/'))).status).toBe(401);expect(db.supabase.from).not.toHaveBeenCalled();});
 it('읽기 자료의 저장값은 서버 토큰에서 얻고 클라이언트 조작을 버린다',async()=>{const response=await save({word:{...word,word_text:'forged'},source:{kind:'reading',materialId:1,tokenId:'c',quote:'forged'}});expect(response.status).toBe(200);expect(db.supabase.rpc.mock.calls[0][1]).toMatchObject({p_word:{word_text:'book',meaning:'책'},p_source:{quote:'I read books',locator:{tokenId:'c',surface:'books'}}});expect(response.headers.get('Cache-Control')).toBe('private, no-store');});
 it('이합사는 뷰어와 같은 결합 기본형에 문맥을 붙인다',async()=>{db.state.material.processed_json.dictionary.c={...token,sep_link:'read a book'};expect((await save()).status).toBe(200);expect(db.supabase.rpc.mock.calls[0][1].p_word.word_text).toBe('read a book');});
 it('이전 DB 정책이 허용해도 타인 비공개 읽기 자료는 반환하지 않는다',async()=>{db.state.material.owner_id='someone-else';expect((await save()).status).toBe(404);expect(db.supabase.rpc).not.toHaveBeenCalled();});
 it('공개 읽기 자료는 문맥 등록이 가능하다',async()=>{db.state.material.owner_id='someone-else';db.state.material.visibility='public';expect((await save()).status).toBe(200);});
 it('소유하지 않은 PDF와 범위를 벗어난 쪽수는 거부한다',async()=>{const body={word,source:{kind:'pdf',pdfId:id,page:16,quote:'A book.'}};expect((await save(body)).status).toBe(400);body.source.page=12;db.state.pdf.owner_id='someone-else';expect((await save(body)).status).toBe(404);});
 it('PDF 쪽수는 사용자 선택으로 표시하고 파일 주소는 저장하지 않는다',async()=>{await save({word,source:{kind:'pdf',pdfId:id,page:'12',quote:'A book.',url:'https://secret/signed'}});expect(db.supabase.rpc.mock.calls[0][1].p_source).toEqual({kind:'pdf',pdfId:id,quote:'A book.',translation:'',locator:{page:12,userSelected:true}});});
 it('자료에 없는 발췌와 다른 언어는 거부한다',async()=>{expect((await save({word,source:{kind:'reading',materialId:1,quote:'A forged book.',surface:'book'}})).status).toBe(400);expect((await save({word:{...word,language:'French'},source:{kind:'reading',materialId:1,tokenId:'c'}})).status).toBe(400);});
 it('드래그한 문장은 원문 포함 여부를 검사한 후 연결한다',async()=>{expect((await save({word,source:{kind:'reading',materialId:1,quote:'I read books.',surface:'books'}})).status).toBe(200);expect(db.supabase.rpc.mock.calls[0][1].p_source.locator).toEqual({surface:'books'});});
 it('교재 저장은 현재 발행 원고에서 발췌와 위치를 얻는다',async()=>{overrides.mockResolvedValue(new Map([['first',{sections:[{heading:'새 예문',examples:[{en:'I buy a book.',ko:'책을 사요.'}]}]}]]));const response=await save({word,source:{kind:'textbook',chapterSlug:'first',sectionIndex:0,exampleIndex:0}});expect(response.status).toBe(200);expect(db.supabase.rpc.mock.calls[0][1].p_source).toMatchObject({quote:'I buy a book.',translation:'책을 사요.',locator:{blockId:expect.stringMatching(/^tb-/),revision:expect.any(String)}});});
 it('교재 어휘는 조작된 클라이언트 뜻 대신 원고의 값을 저장한다',async()=>{await save({word:{...word,meaning:'조작'},source:{kind:'textbook',chapterSlug:'first',sectionIndex:1,vocabIndex:0}});expect(db.supabase.rpc.mock.calls[0][1].p_word.meaning).toBe('책');});
 it('없는 교재 위치와 예문 밖 표현은 거부한다',async()=>{expect((await save({word,source:{kind:'textbook',chapterSlug:'missing',sectionIndex:0,exampleIndex:0}})).status).toBe(404);expect((await save({word:{...word,word_text:'unrelated'},source:{kind:'textbook',chapterSlug:'first',sectionIndex:0,exampleIndex:0}})).status).toBe(400);});
 it('뜻 충돌은 비교할 값만 반환하며 확인은 ID와 현재 뜻을 함께 보낸다',async()=>{db.state.rpcResult={error:{message:'vocabulary_meaning_conflict'}};let response=await save();expect(response.status).toBe(409);expect(await response.json()).toMatchObject({code:'meaning_conflict',existing:{id,meaning:'책'}});db.state.rpcResult={data:{contextAdded:true}};await save({word,source:{kind:'reading',materialId:1,tokenId:'c'},confirmId:id,confirmMeaning:'책'});expect(db.supabase.rpc.mock.calls[1][1]).toMatchObject({p_confirm_id:id,p_confirm_meaning:'책'});});
 it('언어 충돌과 DB 실패를 성공으로 표시하지 않는다',async()=>{db.state.rpcResult={error:{message:'vocabulary_language_conflict'}};expect((await save()).status).toBe(409);db.state.rpcResult={error:{message:'internal connection details'}};const response=await save();expect(response.status).toBe(503);expect(JSON.stringify(await response.json())).not.toContain('internal connection');});
 it('활용형으로 저장했던 카드의 뜻 충돌도 실제 카드 ID로 확인한다',async()=>{db.state.rpcResult={error:{message:'vocabulary_meaning_conflict',details:id}};expect((await save()).status).toBe(409);expect(db.calls.find(c=>c.table==='user_vocabulary').filters).toContainEqual(['id',id]);});
 it('기존 활용형 카드가 여러 개면 새 카드 생성 없이 안내한다',async()=>{db.state.rpcResult={error:{message:'vocabulary_ambiguous_match'}};const response=await save();expect(response.status).toBe(409);expect((await response.json()).code).toBe('ambiguous_match');});
 it('문맥 조회와 삭제는 사용자별 필터를 강제하고 안전한 출처 주소만 반환한다',async()=>{db.state.contexts=[{id,kind:'reading',material_id:1,locator:{tokenId:'c',surface:'books'}},{kind:'textbook',lang:'English',chapter_slug:'../../secret'}];const response=await vocabulary.GET(new Request(`https://fixture.test/?id=${id}`));expect((await response.json()).contexts).toHaveLength(1);await vocabulary.DELETE(request({id},'DELETE'));expect(db.calls.every(call=>call.filters.some(([k,v])=>k==='user_id'&&v===user))).toBe(true);expect(db.calls.at(-1).table).toBe('vocabulary_contexts');});
 it('잘못된 JSON·null·배열 요청은 400으로 끝난다',async()=>{for(const route of [vocabulary,links]){for(const body of ['{','null','[]'])expect((await route.POST(new Request('https://fixture.test',{method:'POST',body}))).status).toBe(400);expect((await route.DELETE(new Request('https://fixture.test',{method:'DELETE',body:'null'}))).status).toBe(400);}expect((await save({word:null,source:null})).status).toBe(400);});
 it('자료 연결은 자기 ID로 쓰고 중복 연결은 무시한다',async()=>{expect((await links.POST(request({lang:'English',slug:'first',kind:'reading',materialId:'1',user_id:'forged'}))).status).toBe(200);expect(db.calls.at(-1)).toMatchObject({table:'textbook_material_links',op:'upsert',value:{user_id:user,material_id:'1'},options:{ignoreDuplicates:true}});});
 it('연결 목록은 공개 수정 제목을 사용하고 개인 소유 연결만 조회한다',async()=>{overrides.mockResolvedValue(new Map([['first',{title:'수정한 제목'}]]));db.state.links=[{id,chapter_slug:'first',material_id:1,reading_materials:{id:1,title:'내 자료'}}];const response=await links.GET(new Request('https://fixture.test/?lang=English&kind=reading&id=1'));expect(response.status).toBe(200);expect((await response.json()).links[0].title).toBe('수정한 제목');expect(db.calls.find(c=>c.table==='textbook_material_links').filters).toContainEqual(['user_id',user]);});
 it('자료 연결 삭제는 자료 원본과 단어장 테이블을 건드리지 않는다',async()=>{expect((await links.DELETE(request({id},'DELETE'))).status).toBe(200);expect(db.calls).toHaveLength(1);expect(db.calls[0]).toMatchObject({table:'textbook_material_links',op:'delete'});});
});
