/**
 * H1 (HSK 1급) 기초 어휘 — 자기소개·숫자·시간·음식·일상 동작의 뼈대.
 * 인사와 사람·숫자와 시간·음식과 음료·일상 동사·형용사·장소와 교통 여섯 테마.
 */
export default {
  level: "H1",
  title: "1급 기초 어휘",
  desc: "你好부터 시작하는 HSK 1급 — 자기소개와 하루 일상에 가장 많이 쓰는 핵심 어휘 100여 개예요.",
  themes: [
    {
      name: "인사와 사람",
      words: [
        { zh: "你好", pinyin: "nǐ hǎo", ko: "안녕하세요", pos: "표현", ex: { zh: "你好！", pinyin: "nǐ hǎo", ko: "안녕하세요!" } },
        { zh: "谢谢", pinyin: "xièxie", ko: "고맙습니다", pos: "표현", ex: { zh: "谢谢你。", pinyin: "xièxie nǐ", ko: "고마워요." } },
        { zh: "不客气", pinyin: "bú kèqi", ko: "천만에요", pos: "표현", hanja: "객기(客氣)에서 — '손님처럼 사양하지 마세요'라는 뜻이에요.", ex: { zh: "不客气。", pinyin: "bú kèqi", ko: "천만에요." } },
        { zh: "再见", pinyin: "zàijiàn", ko: "안녕히 가세요", pos: "표현", hanja: "재견(再見) — '다시 보다', 즉 또 만나요.", ex: { zh: "老师，再见！", pinyin: "lǎoshī, zàijiàn", ko: "선생님, 안녕히 계세요!" } },
        { zh: "对不起", pinyin: "duìbuqǐ", ko: "미안합니다", pos: "표현", ex: { zh: "对不起，我来晚了。", pinyin: "duìbuqǐ, wǒ lái wǎn le", ko: "늦어서 미안해요." } },
        { zh: "我", pinyin: "wǒ", ko: "나, 저", pos: "대사", ex: { zh: "我是学生。", pinyin: "wǒ shì xuésheng", ko: "저는 학생이에요." } },
        { zh: "你", pinyin: "nǐ", ko: "너, 당신", pos: "대사", ex: { zh: "你好吗？", pinyin: "nǐ hǎo ma", ko: "잘 지내요?" } },
        { zh: "他", pinyin: "tā", ko: "그", pos: "대사", ex: { zh: "他是我朋友。", pinyin: "tā shì wǒ péngyou", ko: "그는 제 친구예요." } },
        { zh: "她", pinyin: "tā", ko: "그녀", pos: "대사", ex: { zh: "她是老师。", pinyin: "tā shì lǎoshī", ko: "그녀는 선생님이에요." } },
        { zh: "我们", pinyin: "wǒmen", ko: "우리", pos: "대사", ex: { zh: "我们是中国人。", pinyin: "wǒmen shì Zhōngguó rén", ko: "우리는 중국인이에요." } },
        { zh: "老师", pinyin: "lǎoshī", ko: "선생님", pos: "명사", hanja: "노사(老師) — '師'가 스승. 한국 한자음 '사'를 떠올리면 쉬워요.", ex: { zh: "她是我的老师。", pinyin: "tā shì wǒ de lǎoshī", ko: "그녀는 제 선생님이에요." } },
        { zh: "学生", pinyin: "xuésheng", ko: "학생", pos: "명사", hanja: "학생(學生) — 한자가 그대로예요.", ex: { zh: "我是学生。", pinyin: "wǒ shì xuésheng", ko: "저는 학생이에요." } },
        { zh: "同学", pinyin: "tóngxué", ko: "급우, 학우", pos: "명사", hanja: "동학(同學) — 같이 배우는 사람.", ex: { zh: "他是我同学。", pinyin: "tā shì wǒ tóngxué", ko: "그는 제 학교 친구예요." } },
        { zh: "朋友", pinyin: "péngyou", ko: "친구", pos: "명사", hanja: "붕우(朋友) — '붕우유신'의 그 붕우예요.", ex: { zh: "我有很多朋友。", pinyin: "wǒ yǒu hěn duō péngyou", ko: "저는 친구가 많아요." } },
        { zh: "先生", pinyin: "xiānsheng", ko: "~씨, 남편", pos: "명사", hanja: "선생(先生) — 한국과 달리 남성에 대한 '~씨' 호칭이에요. 주의!", ex: { zh: "王先生是医生。", pinyin: "Wáng xiānsheng shì yīshēng", ko: "왕 선생님(왕 씨)은 의사예요." } },
        { zh: "人", pinyin: "rén", ko: "사람", pos: "명사", hanja: "인(人) — 한자 그대로.", ex: { zh: "他是好人。", pinyin: "tā shì hǎo rén", ko: "그는 좋은 사람이에요." } },
        { zh: "名字", pinyin: "míngzi", ko: "이름", pos: "명사", hanja: "명자(名字) — '名'이 이름 명.", ex: { zh: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi", ko: "이름이 뭐예요?" } },
        { zh: "老婆", pinyin: "lǎopo", ko: "아내 (구어)", pos: "명사", hanja: "노파(老婆) — 한국어 '노파'가 아니라 구어로 '아내'를 뜻해요. 주의!", ex: { zh: "这是我老婆。", pinyin: "zhè shì wǒ lǎopo", ko: "이쪽은 제 아내예요." } },
        { zh: "马", pinyin: "mǎ", ko: "말", pos: "명사", hanja: "마(馬) — '말 마'.", ex: { zh: "妈妈骑马。", pinyin: "māma qí mǎ", ko: "엄마가 말을 타요." } },
      ],
    },
    {
      name: "숫자와 시간",
      words: [
        { zh: "一", pinyin: "yī", ko: "하나, 1", pos: "수사", hanja: "일(一).", ex: { zh: "我有一个哥哥。", pinyin: "wǒ yǒu yí ge gēge", ko: "저는 형이 한 명 있어요." } },
        { zh: "二", pinyin: "èr", ko: "둘, 2", pos: "수사", hanja: "이(二).", ex: { zh: "二加二是四。", pinyin: "èr jiā èr shì sì", ko: "2 더하기 2는 4예요." } },
        { zh: "三", pinyin: "sān", ko: "셋, 3", pos: "수사", hanja: "삼(三).", ex: { zh: "我们三个人。", pinyin: "wǒmen sān ge rén", ko: "우리 세 사람이에요." } },
        { zh: "五", pinyin: "wǔ", ko: "다섯, 5", pos: "수사", hanja: "오(五).", ex: { zh: "现在五点。", pinyin: "xiànzài wǔ diǎn", ko: "지금 5시예요." } },
        { zh: "十", pinyin: "shí", ko: "열, 10", pos: "수사", hanja: "십(十).", ex: { zh: "十块钱。", pinyin: "shí kuài qián", ko: "10위안이에요." } },
        { zh: "百", pinyin: "bǎi", ko: "백, 100", pos: "수사", hanja: "백(百).", ex: { zh: "这本书一百块。", pinyin: "zhè běn shū yìbǎi kuài", ko: "이 책은 100위안이에요." } },
        { zh: "个", pinyin: "ge", ko: "개, 명 (가장 흔한 양사)", pos: "양사", hanja: "개(個) — 한국어 '개'와 통해요. 양사는 셀 때 명사 앞에 붙여요.", ex: { zh: "三个苹果。", pinyin: "sān ge píngguǒ", ko: "사과 세 개." } },
        { zh: "岁", pinyin: "suì", ko: "살, 세 (나이)", pos: "양사", hanja: "세(歲) — 나이의 '세'.", ex: { zh: "我二十岁。", pinyin: "wǒ èrshí suì", ko: "저는 스무 살이에요." } },
        { zh: "今天", pinyin: "jīntiān", ko: "오늘", pos: "명사", hanja: "금천(今天) — '今'은 지금 금, '天'은 날.", ex: { zh: "今天星期一。", pinyin: "jīntiān xīngqīyī", ko: "오늘은 월요일이에요." } },
        { zh: "明天", pinyin: "míngtiān", ko: "내일", pos: "명사", hanja: "명천(明天) — '明'은 밝을 명, 다음 날.", ex: { zh: "明天见。", pinyin: "míngtiān jiàn", ko: "내일 봐요." } },
        { zh: "昨天", pinyin: "zuótiān", ko: "어제", pos: "명사", hanja: "작천(昨天) — '昨'은 어제 작.", ex: { zh: "昨天我没去学校。", pinyin: "zuótiān wǒ méi qù xuéxiào", ko: "어제 저는 학교에 안 갔어요." } },
        { zh: "年", pinyin: "nián", ko: "해, 년", pos: "명사", hanja: "년(年).", ex: { zh: "今年我二十岁。", pinyin: "jīnnián wǒ èrshí suì", ko: "올해 저는 스무 살이에요." } },
        { zh: "月", pinyin: "yuè", ko: "달, 월", pos: "명사", hanja: "월(月).", ex: { zh: "现在五月。", pinyin: "xiànzài wǔ yuè", ko: "지금은 5월이에요." } },
        { zh: "星期", pinyin: "xīngqī", ko: "주, 요일", pos: "명사", hanja: "성기(星期) — '星'은 별 성. 요일은 星期 뒤에 숫자를 붙여요.", ex: { zh: "这个星期我很忙。", pinyin: "zhège xīngqī wǒ hěn máng", ko: "이번 주에 저는 바빠요." } },
        { zh: "时候", pinyin: "shíhou", ko: "때, 무렵", pos: "명사", hanja: "시후(時候) — '時'는 때 시.", ex: { zh: "你什么时候来？", pinyin: "nǐ shénme shíhou lái", ko: "언제 와요?" } },
        { zh: "点", pinyin: "diǎn", ko: "시 (시각)", pos: "양사", hanja: "점(點) — 시각을 셀 때 써요.", ex: { zh: "现在几点？", pinyin: "xiànzài jǐ diǎn", ko: "지금 몇 시예요?" } },
        { zh: "分钟", pinyin: "fēnzhōng", ko: "분 (시간 길이)", pos: "명사", hanja: "분종(分鐘) — '分'은 나눌 분.", ex: { zh: "我等了十分钟。", pinyin: "wǒ děng le shí fēnzhōng", ko: "저는 10분 기다렸어요." } },
        { zh: "现在", pinyin: "xiànzài", ko: "지금, 현재", pos: "명사", hanja: "현재(現在) — 한자 그대로.", ex: { zh: "现在几点了？", pinyin: "xiànzài jǐ diǎn le", ko: "지금 몇 시예요?" } },
      ],
    },
    {
      name: "음식과 음료",
      words: [
        { zh: "吃", pinyin: "chī", ko: "먹다", pos: "동사", ex: { zh: "我想吃饭。", pinyin: "wǒ xiǎng chī fàn", ko: "저는 밥을 먹고 싶어요." } },
        { zh: "喝", pinyin: "hē", ko: "마시다", pos: "동사", ex: { zh: "我喝水。", pinyin: "wǒ hē shuǐ", ko: "저는 물을 마셔요." } },
        { zh: "米饭", pinyin: "mǐfàn", ko: "쌀밥", pos: "명사", hanja: "미반(米飯) — '米'는 쌀 미, '飯'은 밥 반.", ex: { zh: "我喜欢吃米饭。", pinyin: "wǒ xǐhuan chī mǐfàn", ko: "저는 쌀밥을 좋아해요." } },
        { zh: "菜", pinyin: "cài", ko: "요리, 채소", pos: "명사", hanja: "채(菜) — 채소의 '채'.", ex: { zh: "这个菜很好吃。", pinyin: "zhège cài hěn hǎochī", ko: "이 요리는 맛있어요." } },
        { zh: "水果", pinyin: "shuǐguǒ", ko: "과일", pos: "명사", hanja: "수과(水果) — '水'는 물 수, '果'는 열매 과.", ex: { zh: "我喜欢吃水果。", pinyin: "wǒ xǐhuan chī shuǐguǒ", ko: "저는 과일을 좋아해요." } },
        { zh: "苹果", pinyin: "píngguǒ", ko: "사과", pos: "명사", ex: { zh: "我买了三个苹果。", pinyin: "wǒ mǎi le sān ge píngguǒ", ko: "저는 사과 세 개를 샀어요." } },
        { zh: "水", pinyin: "shuǐ", ko: "물", pos: "명사", hanja: "수(水).", ex: { zh: "请给我一杯水。", pinyin: "qǐng gěi wǒ yì bēi shuǐ", ko: "물 한 잔 주세요." } },
        { zh: "茶", pinyin: "chá", ko: "차", pos: "명사", hanja: "차(茶) — 한국어 '차'가 바로 이 글자.", ex: { zh: "我喜欢喝茶。", pinyin: "wǒ xǐhuan hē chá", ko: "저는 차를 즐겨 마셔요." } },
        { zh: "咖啡", pinyin: "kāfēi", ko: "커피", pos: "명사", ex: { zh: "我每天喝咖啡。", pinyin: "wǒ měi tiān hē kāfēi", ko: "저는 매일 커피를 마셔요." } },
        { zh: "饭店", pinyin: "fàndiàn", ko: "식당, 호텔", pos: "명사", hanja: "반점(飯店) — '店'은 가게 점. 중국에선 호텔도 가리켜요.", ex: { zh: "我们去饭店吃饭。", pinyin: "wǒmen qù fàndiàn chī fàn", ko: "우리 식당에 가서 밥 먹어요." } },
        { zh: "杯子", pinyin: "bēizi", ko: "컵, 잔", pos: "명사", hanja: "배자(杯子) — '杯'는 잔 배.", ex: { zh: "桌子上有一个杯子。", pinyin: "zhuōzi shàng yǒu yí ge bēizi", ko: "탁자 위에 컵이 하나 있어요." } },
      ],
    },
    {
      name: "일상 동사",
      words: [
        { zh: "是", pinyin: "shì", ko: "~이다", pos: "동사", hanja: "시(是) — '옳을 시'. 'A是B' = 'A는 B다'.", ex: { zh: "我是韩国人。", pinyin: "wǒ shì Hánguó rén", ko: "저는 한국인이에요." } },
        { zh: "有", pinyin: "yǒu", ko: "있다, 가지다", pos: "동사", hanja: "유(有) — '있을 유'.", ex: { zh: "我有一个妹妹。", pinyin: "wǒ yǒu yí ge mèimei", ko: "저는 여동생이 한 명 있어요." } },
        { zh: "去", pinyin: "qù", ko: "가다", pos: "동사", ex: { zh: "我去学校。", pinyin: "wǒ qù xuéxiào", ko: "저는 학교에 가요." } },
        { zh: "来", pinyin: "lái", ko: "오다", pos: "동사", hanja: "래(來) — '올 래'.", ex: { zh: "他明天来。", pinyin: "tā míngtiān lái", ko: "그는 내일 와요." } },
        { zh: "看", pinyin: "kàn", ko: "보다", pos: "동사", ex: { zh: "我看书。", pinyin: "wǒ kàn shū", ko: "저는 책을 봐요." } },
        { zh: "听", pinyin: "tīng", ko: "듣다", pos: "동사", ex: { zh: "我听音乐。", pinyin: "wǒ tīng yīnyuè", ko: "저는 음악을 들어요." } },
        { zh: "说", pinyin: "shuō", ko: "말하다", pos: "동사", hanja: "설(說) — '말씀 설'.", ex: { zh: "请说慢一点。", pinyin: "qǐng shuō màn yìdiǎn", ko: "천천히 말해 주세요." } },
        { zh: "说话", pinyin: "shuōhuà", ko: "말을 하다", pos: "동사", hanja: "설화(說話) — '話'는 말씀 화.", ex: { zh: "老师在说话。", pinyin: "lǎoshī zài shuōhuà", ko: "선생님이 말하고 계세요." } },
        { zh: "读", pinyin: "dú", ko: "읽다", pos: "동사", hanja: "독(讀) — '읽을 독'.", ex: { zh: "我读汉语书。", pinyin: "wǒ dú Hànyǔ shū", ko: "저는 중국어 책을 읽어요." } },
        { zh: "写", pinyin: "xiě", ko: "쓰다", pos: "동사", ex: { zh: "他在写字。", pinyin: "tā zài xiě zì", ko: "그는 글씨를 쓰고 있어요." } },
        { zh: "学习", pinyin: "xuéxí", ko: "공부하다", pos: "동사", hanja: "학습(學習) — 한자 그대로.", ex: { zh: "我学习汉语。", pinyin: "wǒ xuéxí Hànyǔ", ko: "저는 중국어를 공부해요." } },
        { zh: "工作", pinyin: "gōngzuò", ko: "일하다, 일", pos: "동사", hanja: "공작(工作) — '工'은 장인 공.", ex: { zh: "我爸爸在医院工作。", pinyin: "wǒ bàba zài yīyuàn gōngzuò", ko: "우리 아빠는 병원에서 일하세요." } },
        { zh: "想", pinyin: "xiǎng", ko: "~하고 싶다, 생각하다", pos: "동사", hanja: "상(想) — '생각 상'.", ex: { zh: "我想去中国。", pinyin: "wǒ xiǎng qù Zhōngguó", ko: "저는 중국에 가고 싶어요." } },
        { zh: "喜欢", pinyin: "xǐhuan", ko: "좋아하다", pos: "동사", ex: { zh: "我喜欢看电影。", pinyin: "wǒ xǐhuan kàn diànyǐng", ko: "저는 영화 보는 걸 좋아해요." } },
        { zh: "爱", pinyin: "ài", ko: "사랑하다", pos: "동사", hanja: "애(愛) — '사랑 애'.", ex: { zh: "我爱我的家。", pinyin: "wǒ ài wǒ de jiā", ko: "저는 우리 집을 사랑해요." } },
        { zh: "买", pinyin: "mǎi", ko: "사다", pos: "동사", ex: { zh: "我买了一本书。", pinyin: "wǒ mǎi le yì běn shū", ko: "저는 책 한 권을 샀어요." } },
        { zh: "做", pinyin: "zuò", ko: "하다, 만들다", pos: "동사", ex: { zh: "你在做什么？", pinyin: "nǐ zài zuò shénme", ko: "뭐 하고 있어요?" } },
        { zh: "叫", pinyin: "jiào", ko: "부르다, (이름이) ~이다", pos: "동사", ex: { zh: "我叫小明。", pinyin: "wǒ jiào Xiǎomíng", ko: "제 이름은 샤오밍이에요." } },
        { zh: "睡觉", pinyin: "shuìjiào", ko: "잠을 자다", pos: "동사", ex: { zh: "我十点睡觉。", pinyin: "wǒ shí diǎn shuìjiào", ko: "저는 10시에 자요." } },
        { zh: "回", pinyin: "huí", ko: "돌아가다, 돌아오다", pos: "동사", hanja: "회(回) — '돌아올 회'.", ex: { zh: "我回家。", pinyin: "wǒ huí jiā", ko: "저는 집에 가요." } },
        { zh: "骑", pinyin: "qí", ko: "(말·자전거를) 타다", pos: "동사", hanja: "기(騎) — '말 탈 기'. 다리를 벌려 올라타는 것에 써요.", ex: { zh: "妈妈骑马。", pinyin: "māma qí mǎ", ko: "엄마가 말을 타요." } },
        { zh: "走路", pinyin: "zǒulù", ko: "걷다, 길을 걷다", pos: "동사", hanja: "주로(走路) — '走'는 걸을 주, '路'는 길 로.", ex: { zh: "我们走路去。", pinyin: "wǒmen zǒulù qù", ko: "우리는 걸어서 가요." } },
        { zh: "书", pinyin: "shū", ko: "책", pos: "명사", hanja: "서(書) — '글 서'. '도서(圖書)'의 서.", ex: { zh: "这是我的书。", pinyin: "zhè shì wǒ de shū", ko: "이것은 제 책이에요." } },
        { zh: "字", pinyin: "zì", ko: "글자", pos: "명사", hanja: "자(字) — '글자 자'. '한자(漢字)'의 자.", ex: { zh: "他在写字。", pinyin: "tā zài xiě zì", ko: "그는 글씨를 쓰고 있어요." } },
        { zh: "工夫", pinyin: "gōngfu", ko: "(들인) 노력·시간, 무술", pos: "명사", hanja: "공부(工夫) — 한국어 '공부'가 아니라 들인 '노력·시간', 또는 무술(쿵푸)을 뜻해요.", ex: { zh: "这件事要花工夫。", pinyin: "zhè jiàn shì yào huā gōngfu", ko: "이 일은 공이 들어요." } },
      ],
    },
    {
      name: "형용사와 부사",
      words: [
        { zh: "好", pinyin: "hǎo", ko: "좋다", pos: "형용사", ex: { zh: "今天天气很好。", pinyin: "jīntiān tiānqì hěn hǎo", ko: "오늘 날씨가 좋아요." } },
        { zh: "大", pinyin: "dà", ko: "크다", pos: "형용사", hanja: "대(大).", ex: { zh: "这个房子很大。", pinyin: "zhège fángzi hěn dà", ko: "이 집은 커요." } },
        { zh: "小", pinyin: "xiǎo", ko: "작다", pos: "형용사", hanja: "소(小).", ex: { zh: "我的房间很小。", pinyin: "wǒ de fángjiān hěn xiǎo", ko: "제 방은 작아요." } },
        { zh: "多", pinyin: "duō", ko: "많다", pos: "형용사", hanja: "다(多).", ex: { zh: "今天人很多。", pinyin: "jīntiān rén hěn duō", ko: "오늘 사람이 많아요." } },
        { zh: "少", pinyin: "shǎo", ko: "적다", pos: "형용사", hanja: "소(少).", ex: { zh: "钱太少了。", pinyin: "qián tài shǎo le", ko: "돈이 너무 적어요." } },
        { zh: "热", pinyin: "rè", ko: "덥다, 뜨겁다", pos: "형용사", hanja: "열(熱) — '더울 열'.", ex: { zh: "今天很热。", pinyin: "jīntiān hěn rè", ko: "오늘 더워요." } },
        { zh: "冷", pinyin: "lěng", ko: "춥다, 차다", pos: "형용사", hanja: "랭(冷) — '찰 랭'.", ex: { zh: "冬天很冷。", pinyin: "dōngtiān hěn lěng", ko: "겨울은 추워요." } },
        { zh: "高兴", pinyin: "gāoxìng", ko: "기쁘다", pos: "형용사", hanja: "고흥(高興) — '興'은 흥할 흥. 기분이 들뜬 상태.", ex: { zh: "我很高兴。", pinyin: "wǒ hěn gāoxìng", ko: "저는 기뻐요." } },
        { zh: "漂亮", pinyin: "piàoliang", ko: "예쁘다", pos: "형용사", ex: { zh: "她很漂亮。", pinyin: "tā hěn piàoliang", ko: "그녀는 예뻐요." } },
        { zh: "好吃", pinyin: "hǎochī", ko: "맛있다", pos: "형용사", ex: { zh: "这个菜很好吃。", pinyin: "zhège cài hěn hǎochī", ko: "이 요리는 맛있어요." } },
        { zh: "很", pinyin: "hěn", ko: "매우, 아주", pos: "부사", ex: { zh: "我很忙。", pinyin: "wǒ hěn máng", ko: "저는 바빠요." } },
        { zh: "太", pinyin: "tài", ko: "너무, 지나치게", pos: "부사", hanja: "태(太) — '클 태'. 보통 '太…了' 형태로 써요.", ex: { zh: "太好了！", pinyin: "tài hǎo le", ko: "정말 잘됐어요!" } },
        { zh: "都", pinyin: "dōu", ko: "모두, 다", pos: "부사", hanja: "도(都).", ex: { zh: "我们都是学生。", pinyin: "wǒmen dōu shì xuésheng", ko: "우리는 모두 학생이에요." } },
        { zh: "不", pinyin: "bù", ko: "안, ~지 않다", pos: "부사", hanja: "불(不) — 동사·형용사 앞에서 부정.", ex: { zh: "我不喝咖啡。", pinyin: "wǒ bù hē kāfēi", ko: "저는 커피를 안 마셔요." } },
        { zh: "没", pinyin: "méi", ko: "없다, ~지 않았다", pos: "부사", ex: { zh: "我没有钱。", pinyin: "wǒ méiyǒu qián", ko: "저는 돈이 없어요." } },
        { zh: "也", pinyin: "yě", ko: "~도, 또한", pos: "부사", ex: { zh: "我也是学生。", pinyin: "wǒ yě shì xuésheng", ko: "저도 학생이에요." } },
      ],
    },
    {
      name: "장소와 교통",
      words: [
        { zh: "家", pinyin: "jiā", ko: "집", pos: "명사", hanja: "가(家) — '집 가'.", ex: { zh: "我在家。", pinyin: "wǒ zài jiā", ko: "저는 집에 있어요." } },
        { zh: "学校", pinyin: "xuéxiào", ko: "학교", pos: "명사", hanja: "학교(學校) — 한자 그대로.", ex: { zh: "我去学校。", pinyin: "wǒ qù xuéxiào", ko: "저는 학교에 가요." } },
        { zh: "医院", pinyin: "yīyuàn", ko: "병원", pos: "명사", hanja: "의원(醫院) — '院'은 집 원. 한국 '의원'보다 큰 병원이에요.", ex: { zh: "妈妈在医院工作。", pinyin: "māma zài yīyuàn gōngzuò", ko: "엄마는 병원에서 일하세요." } },
        { zh: "医生", pinyin: "yīshēng", ko: "의사", pos: "명사", hanja: "의생(醫生) — 한자는 '의생'이지만 뜻은 '의사'! 주의하세요.", ex: { zh: "他是医生。", pinyin: "tā shì yīshēng", ko: "그는 의사예요." } },
        { zh: "商店", pinyin: "shāngdiàn", ko: "상점, 가게", pos: "명사", hanja: "상점(商店) — 한자 그대로.", ex: { zh: "我去商店买东西。", pinyin: "wǒ qù shāngdiàn mǎi dōngxi", ko: "저는 가게에 물건을 사러 가요." } },
        { zh: "中国", pinyin: "Zhōngguó", ko: "중국", pos: "명사", hanja: "중국(中國) — 한자 그대로.", ex: { zh: "我想去中国。", pinyin: "wǒ xiǎng qù Zhōngguó", ko: "저는 중국에 가고 싶어요." } },
        { zh: "北京", pinyin: "Běijīng", ko: "베이징", pos: "명사", hanja: "북경(北京) — 한국 한자음으로 '북경'.", ex: { zh: "北京很大。", pinyin: "Běijīng hěn dà", ko: "베이징은 커요." } },
        { zh: "里", pinyin: "lǐ", ko: "안, 속", pos: "명사", hanja: "리(裏) — '속 리'. 위치를 나타내요.", ex: { zh: "包里有书。", pinyin: "bāo lǐ yǒu shū", ko: "가방 안에 책이 있어요." } },
        { zh: "上", pinyin: "shàng", ko: "위, 위에", pos: "명사", hanja: "상(上).", ex: { zh: "桌子上有杯子。", pinyin: "zhuōzi shàng yǒu bēizi", ko: "탁자 위에 컵이 있어요." } },
        { zh: "下", pinyin: "xià", ko: "아래, 아래에", pos: "명사", hanja: "하(下).", ex: { zh: "椅子下有猫。", pinyin: "yǐzi xià yǒu māo", ko: "의자 아래에 고양이가 있어요." } },
        { zh: "飞机", pinyin: "fēijī", ko: "비행기", pos: "명사", hanja: "비기(飛機) — '飛'는 날 비. 한국 '비행기'와 통해요.", ex: { zh: "我坐飞机去北京。", pinyin: "wǒ zuò fēijī qù Běijīng", ko: "저는 비행기를 타고 베이징에 가요." } },
        { zh: "出租车", pinyin: "chūzūchē", ko: "택시", pos: "명사", hanja: "출조차(出租車) — '租'는 빌릴 조, '車'는 수레 차. '빌려 타는 차'.", ex: { zh: "我们坐出租车去。", pinyin: "wǒmen zuò chūzūchē qù", ko: "우리 택시 타고 가요." } },
        { zh: "坐", pinyin: "zuò", ko: "앉다, (교통수단을) 타다", pos: "동사", hanja: "좌(坐) — '앉을 좌'. 타는 것도 '앉아 가는' 셈이에요.", ex: { zh: "我坐火车去。", pinyin: "wǒ zuò huǒchē qù", ko: "저는 기차를 타고 가요." } },
        { zh: "在", pinyin: "zài", ko: "~에 있다, ~에서", pos: "동사", hanja: "재(在) — '있을 재'. 위치를 말할 때 핵심이에요.", ex: { zh: "他在家。", pinyin: "tā zài jiā", ko: "그는 집에 있어요." } },
        { zh: "车", pinyin: "chē", ko: "차, 자동차", pos: "명사", hanja: "차(車) — '수레 차'.", ex: { zh: "我坐车去。", pinyin: "wǒ zuò chē qù", ko: "저는 차를 타고 가요." } },
        { zh: "这儿", pinyin: "zhèr", ko: "여기", pos: "대사", hanja: "'這(이 저)'에 兒이 붙은 장소 지시. = 这里.", ex: { zh: "我在这儿。", pinyin: "wǒ zài zhèr", ko: "저 여기 있어요." } },
        { zh: "那儿", pinyin: "nàr", ko: "저기, 거기", pos: "대사", hanja: "'那(저 나)'에 兒이 붙은 장소 지시. = 那里.", ex: { zh: "他在那儿。", pinyin: "tā zài nàr", ko: "그는 저기 있어요." } },
        { zh: "哪儿", pinyin: "nǎr", ko: "어디", pos: "대사", hanja: "'哪(어느 나)'에 兒이 붙은 의문. 장소를 물어요.", ex: { zh: "你在哪儿？", pinyin: "nǐ zài nǎr", ko: "너 어디 있어?" } },
      ],
    },
  ],
}
