/**
 * H1 (HSK 1급) HSK 3.0 표준 보강 어휘 — 공식 어휘표(drkameleon/complete-hsk-vocabulary, MIT)에서
 * 기존에 없던 191개를 채웠어요. 한자·병음·품사는 표준 데이터, 뜻·예문은 학습용으로 작성.
 */
const themes = {
  themes: [
    {
      name: "HSK1 3.0 보강",
      icon: "🟩",
      words: [
        { zh: "爸", pinyin: "bà", ko: "아빠, 아버지", pos: "명사", ex: { zh: "我爸是老师。", pinyin: "Wǒ bà shì lǎoshī.", ko: "우리 아빠는 선생님이다." } },
        { zh: "白天", pinyin: "bái tiān", ko: "낮, 대낮", pos: "명사", ex: { zh: "白天我在学校上课。", pinyin: "Bái tiān wǒ zài xuéxiào shàng kè.", ko: "낮에는 나는 학교에서 수업을 듣는다." } },
        { zh: "半年", pinyin: "bàn nián", ko: "반년", pos: "", ex: { zh: "我学中文半年了。", pinyin: "Wǒ xué Zhōngwén bàn nián le.", ko: "나는 중국어를 배운 지 반년이 되었다." } },
        { zh: "帮", pinyin: "bāng", ko: "돕다", pos: "동사", ex: { zh: "我帮你拿东西。", pinyin: "Wǒ bāng nǐ ná dōngxi.", ko: "내가 네 짐 드는 것을 도와줄게." } },
        { zh: "杯", pinyin: "bēi", ko: "잔, 컵(양사)", pos: "양사", ex: { zh: "我喝了一杯水。", pinyin: "Wǒ hēle yì bēi shuǐ.", ko: "나는 물 한 잔을 마셨다." } },
        { zh: "北", pinyin: "běi", ko: "북, 북쪽", pos: "명사", ex: { zh: "我们往北走。", pinyin: "Wǒmen wǎng běi zǒu.", ko: "우리는 북쪽으로 간다." } },
        { zh: "北边", pinyin: "běi biān", ko: "북쪽, 북편", pos: "명사", ex: { zh: "学校在公园的北边。", pinyin: "Xuéxiào zài gōngyuán de běi biān.", ko: "학교는 공원의 북쪽에 있다." } },
        { zh: "本子", pinyin: "běn zi", ko: "공책, 노트", pos: "명사", ex: { zh: "我买了一个新本子。", pinyin: "Wǒ mǎile yí gè xīn běnzi.", ko: "나는 새 공책을 하나 샀다." } },
        { zh: "别的", pinyin: "bié de", ko: "다른 것, 다른", pos: "대명사", ex: { zh: "你还有别的问题吗?", pinyin: "Nǐ hái yǒu bié de wèntí ma?", ko: "다른 질문 있으세요?" } },
        { zh: "病", pinyin: "bìng", ko: "병, 질병", pos: "명사", ex: { zh: "他生病了,不能来上课。", pinyin: "Tā shēng bìng le, bù néng lái shàng kè.", ko: "그는 병이 나서 수업에 올 수 없다." } },
        { zh: "病人", pinyin: "bìng rén", ko: "환자", pos: "명사", ex: { zh: "医生正在给病人看病。", pinyin: "Yīshēng zhèngzài gěi bìngrén kànbìng.", ko: "의사가 환자를 진료하고 있다." } },
        { zh: "不大", pinyin: "bù dà", ko: "그다지 ~않다, 별로 ~않다", pos: "부사", ex: { zh: "这件衣服不大好看。", pinyin: "Zhè jiàn yīfu bú dà hǎokàn.", ko: "이 옷은 그다지 예쁘지 않다." } },
        { zh: "不对", pinyin: "bù duì", ko: "틀리다, 맞지 않다", pos: "형용사", ex: { zh: "你说的不对。", pinyin: "Nǐ shuō de bú duì.", ko: "네가 말한 것은 틀리다." } },
        { zh: "不用", pinyin: "bù yòng", ko: "~할 필요 없다", pos: "부사", ex: { zh: "不用谢。", pinyin: "Bú yòng xiè.", ko: "감사할 필요 없어요(천만에요)." } },
        { zh: "常", pinyin: "cháng", ko: "자주, 늘", pos: "부사", ex: { zh: "他常来我家玩。", pinyin: "Tā cháng lái wǒ jiā wán.", ko: "그는 자주 우리 집에 놀러 온다." } },
        { zh: "常常", pinyin: "cháng cháng", ko: "자주, 항상", pos: "부사", ex: { zh: "我常常去图书馆。", pinyin: "Wǒ chángcháng qù túshūguǎn.", ko: "나는 자주 도서관에 간다." } },
        { zh: "唱", pinyin: "chàng", ko: "노래하다, 부르다", pos: "동사", ex: { zh: "她唱歌唱得很好。", pinyin: "Tā chàng gē chàng de hěn hǎo.", ko: "그녀는 노래를 매우 잘 부른다." } },
        { zh: "车票", pinyin: "chē piào", ko: "차표, 승차권", pos: "명사", ex: { zh: "我买了两张车票。", pinyin: "Wǒ mǎile liǎng zhāng chēpiào.", ko: "나는 차표 두 장을 샀다." } },
        { zh: "车上", pinyin: "chē shàng", ko: "차 안, 차 위", pos: "", ex: { zh: "车上人很多。", pinyin: "Chē shàng rén hěn duō.", ko: "차 안에 사람이 많다." } },
        { zh: "车站", pinyin: "chē zhàn", ko: "정류장, 역", pos: "명사", ex: { zh: "车站离这儿不远。", pinyin: "Chēzhàn lí zhèr bù yuǎn.", ko: "정류장은 여기서 멀지 않다." } },
        { zh: "吃饭", pinyin: "chī fàn", ko: "밥을 먹다, 식사하다", pos: "동사", ex: { zh: "我们一起吃饭吧。", pinyin: "Wǒmen yìqǐ chī fàn ba.", ko: "우리 같이 밥 먹자." } },
        { zh: "出来", pinyin: "chū lái", ko: "나오다", pos: "동사", ex: { zh: "他从房间里出来了。", pinyin: "Tā cóng fángjiān lǐ chūlái le.", ko: "그는 방에서 나왔다." } },
        { zh: "出去", pinyin: "chū qù", ko: "나가다", pos: "동사", ex: { zh: "我想出去走走。", pinyin: "Wǒ xiǎng chūqù zǒuzou.", ko: "나는 나가서 좀 걷고 싶다." } },
        { zh: "床", pinyin: "chuáng", ko: "침대", pos: "명사", ex: { zh: "房间里有一张床。", pinyin: "Fángjiān lǐ yǒu yì zhāng chuáng.", ko: "방 안에 침대가 하나 있다." } },
        { zh: "打", pinyin: "dá", ko: "다스(12개)", pos: "동사", ex: { zh: "我买了一打鸡蛋。", pinyin: "Wǒ mǎile yì dá jīdàn.", ko: "나는 계란 한 다스를 샀다." } },
        { zh: "打车", pinyin: "dǎ chē", ko: "택시를 타다", pos: "동사", ex: { zh: "我打车去机场。", pinyin: "Wǒ dǎchē qù jīchǎng.", ko: "나는 택시를 타고 공항에 간다." } },
        { zh: "打开", pinyin: "dǎ kāi", ko: "열다, 켜다", pos: "동사", ex: { zh: "请打开窗户。", pinyin: "Qǐng dǎkāi chuānghu.", ko: "창문을 좀 열어 주세요." } },
        { zh: "打球", pinyin: "dǎ qiú", ko: "공놀이하다, 구기 종목을 하다", pos: "동사", ex: { zh: "他们在操场上打球。", pinyin: "Tāmen zài cāochǎng shàng dǎqiú.", ko: "그들은 운동장에서 공놀이를 한다." } },
        { zh: "大学", pinyin: "dàxué", ko: "대학교", pos: "명사", ex: { zh: "我在大学学习中文。", pinyin: "Wǒ zài dàxué xuéxí Zhōngwén.", ko: "나는 대학교에서 중국어를 공부한다." } },
        { zh: "大学生", pinyin: "dà xué shēng", ko: "대학생", pos: "명사", ex: { zh: "我姐姐是大学生。", pinyin: "Wǒ jiějie shì dàxuéshēng.", ko: "우리 언니는 대학생이다." } },
        { zh: "地点", pinyin: "dì diǎn", ko: "장소, 지점", pos: "명사", ex: { zh: "请告诉我地点。", pinyin: "Qǐng gàosu wǒ dìdiǎn.", ko: "장소를 저에게 알려주세요." } },
        { zh: "地上", pinyin: "dì shang", ko: "땅 위, 바닥에", pos: "", ex: { zh: "书掉在地上了。", pinyin: "Shū diào zài dìshang le.", ko: "책이 바닥에 떨어졌다." } },
        { zh: "得到", pinyin: "dé dào", ko: "얻다, 획득하다", pos: "동사", ex: { zh: "他得到了很多帮助。", pinyin: "Tā dédàole hěn duō bāngzhù.", ko: "그는 많은 도움을 얻었다." } },
        { zh: "弟", pinyin: "dì", ko: "남동생", pos: "명사", ex: { zh: "我弟今年十岁。", pinyin: "Wǒ dì jīnnián shí suì.", ko: "내 남동생은 올해 열 살이다." } },
        { zh: "第", pinyin: "dì", ko: "제~(차례를 나타내는 접두어)", pos: "수사", ex: { zh: "这是我第一次来中国。", pinyin: "Zhè shì wǒ dì yī cì lái Zhōngguó.", ko: "이번이 내가 처음 중국에 온 것이다." } },
        { zh: "第二", pinyin: "dì èr", ko: "두 번째, 제2", pos: "수사", ex: { zh: "他排第二。", pinyin: "Tā pái dì èr.", ko: "그는 두 번째다." } },
        { zh: "电", pinyin: "diàn", ko: "전기", pos: "명사", ex: { zh: "家里停电了。", pinyin: "Jiā lǐ tíng diàn le.", ko: "집에 정전이 됐다." } },
        { zh: "电视机", pinyin: "diàn shì jī", ko: "텔레비전, TV 수상기", pos: "명사", ex: { zh: "客厅里有一台电视机。", pinyin: "Kètīng lǐ yǒu yì tái diànshìjī.", ko: "거실에 텔레비전이 한 대 있다." } },
        { zh: "电影院", pinyin: "diàn yǐng yuàn", ko: "영화관", pos: "명사", ex: { zh: "我们周末去电影院看电影。", pinyin: "Wǒmen zhōumò qù diànyǐngyuàn kàn diànyǐng.", ko: "우리는 주말에 영화관에 가서 영화를 본다." } },
        { zh: "东边", pinyin: "dōng bian", ko: "동쪽, 동편", pos: "명사", ex: { zh: "太阳从东边升起。", pinyin: "Tàiyáng cóng dōngbian shēngqǐ.", ko: "해는 동쪽에서 뜬다." } },
        { zh: "动", pinyin: "dòng", ko: "움직이다", pos: "동사", ex: { zh: "你别动。", pinyin: "Nǐ bié dòng.", ko: "움직이지 마." } },
        { zh: "饭", pinyin: "fàn", ko: "밥, 식사", pos: "명사", ex: { zh: "我们一起吃饭吧。", pinyin: "Wǒmen yìqǐ chī fàn ba.", ko: "우리 같이 밥 먹자." } },
        { zh: "房子", pinyin: "fáng zi", ko: "집, 건물", pos: "명사", ex: { zh: "这是一栋新房子。", pinyin: "Zhè shì yí dòng xīn fángzi.", ko: "이것은 새 집이다." } },
        { zh: "放假", pinyin: "fàng jià", ko: "방학하다, 휴가를 얻다", pos: "동사", ex: { zh: "我们下周放假。", pinyin: "Wǒmen xià zhōu fàng jià.", ko: "우리는 다음 주에 방학한다." } },
        { zh: "放学", pinyin: "fàng xué", ko: "하교하다, 수업이 끝나다", pos: "동사", ex: { zh: "我们三点放学。", pinyin: "Wǒmen sān diǎn fàng xué.", ko: "우리는 3시에 수업이 끝난다." } },
        { zh: "飞", pinyin: "fēi", ko: "날다", pos: "동사", ex: { zh: "小鸟在天上飞。", pinyin: "Xiǎo niǎo zài tiānshàng fēi.", ko: "작은 새가 하늘에서 날고 있다." } },
        { zh: "风", pinyin: "fēng", ko: "바람", pos: "명사", ex: { zh: "今天风很大。", pinyin: "Jīntiān fēng hěn dà.", ko: "오늘은 바람이 많이 분다." } },
        { zh: "干什么", pinyin: "gàn shén me", ko: "뭐 하다, 뭐 하는 거야", pos: "동사", ex: { zh: "你在干什么?", pinyin: "Nǐ zài gàn shénme?", ko: "너 뭐 하고 있어?" } },
        { zh: "哥", pinyin: "gē", ko: "형, 오빠", pos: "명사", ex: { zh: "我哥比我大三岁。", pinyin: "Wǒ gē bǐ wǒ dà sān suì.", ko: "우리 형은 나보다 세 살 많다." } },
        { zh: "歌", pinyin: "gē", ko: "노래", pos: "명사", ex: { zh: "她唱歌唱得很好。", pinyin: "Tā chàng gē chàng de hěn hǎo.", ko: "그녀는 노래를 매우 잘 부른다." } },
        { zh: "关上", pinyin: "guān shàng", ko: "닫다, 끄다", pos: "동사", ex: { zh: "请关上门。", pinyin: "Qǐng guān shàng mén.", ko: "문을 닫아 주세요." } },
        { zh: "国", pinyin: "guó", ko: "나라, 국가", pos: "명사", ex: { zh: "中国是一个大国。", pinyin: "Zhōngguó shì yí gè dà guó.", ko: "중국은 큰 나라이다." } },
        { zh: "国外", pinyin: "guó wài", ko: "국외, 해외", pos: "", ex: { zh: "他在国外工作。", pinyin: "Tā zài guó wài gōngzuò.", ko: "그는 해외에서 일한다." } },
        { zh: "还有", pinyin: "hái yǒu", ko: "그리고 또, 게다가, 아직 있다", pos: "동사", ex: { zh: "还有一个问题。", pinyin: "Hái yǒu yí gè wèntí.", ko: "질문이 하나 더 있다." } },
        { zh: "好看", pinyin: "hǎo kàn", ko: "예쁘다, 보기 좋다", pos: "형용사", ex: { zh: "这件衣服很好看。", pinyin: "Zhè jiàn yīfu hěn hǎokàn.", ko: "이 옷은 예쁘다." } },
        { zh: "好听", pinyin: "hǎo tīng", ko: "듣기 좋다", pos: "형용사", ex: { zh: "这首歌很好听。", pinyin: "Zhè shǒu gē hěn hǎotīng.", ko: "이 노래는 듣기 좋다." } },
        { zh: "好玩儿", pinyin: "hǎo wánr", ko: "재미있다", pos: "형용사", ex: { zh: "这个游戏很好玩儿。", pinyin: "Zhège yóuxì hěn hǎowánr.", ko: "이 게임은 재미있다." } },
        { zh: "后", pinyin: "hòu", ko: "뒤, 후", pos: "명사", ex: { zh: "他坐在我后面。", pinyin: "Tā zuò zài wǒ hòumiàn.", ko: "그는 내 뒤에 앉아 있다." } },
        { zh: "后边", pinyin: "hòu bian", ko: "뒤, 뒤쪽", pos: "명사", ex: { zh: "他站在我后边。", pinyin: "Tā zhàn zài wǒ hòubian.", ko: "그는 내 뒤에 서 있다." } },
        { zh: "后天", pinyin: "hòu tiān", ko: "모레", pos: "명사", ex: { zh: "我们后天见。", pinyin: "Wǒmen hòutiān jiàn.", ko: "우리 모레 만나자." } },
        { zh: "话", pinyin: "huà", ko: "말, 이야기", pos: "명사", ex: { zh: "他说的话很有道理。", pinyin: "Tā shuō de huà hěn yǒu dàolǐ.", ko: "그가 한 말은 일리가 있다." } },
        { zh: "回到", pinyin: "huí dào", ko: "~로 돌아가다/돌아오다", pos: "동사", ex: { zh: "他回到了自己的房间。", pinyin: "Tā huídào le zìjǐ de fángjiān.", ko: "그는 자기 방으로 돌아갔다." } },
        { zh: "回来", pinyin: "huí lai", ko: "돌아오다", pos: "동사", ex: { zh: "你什么时候回来?", pinyin: "Nǐ shénme shíhou huílai?", ko: "너 언제 돌아와?" } },
        { zh: "回去", pinyin: "huí qu", ko: "돌아가다", pos: "동사", ex: { zh: "我该回去了。", pinyin: "Wǒ gāi huíqu le.", ko: "나 이제 돌아가야 해." } },
        { zh: "火车", pinyin: "huǒ chē", ko: "기차", pos: "명사", ex: { zh: "我们坐火车去北京。", pinyin: "Wǒmen zuò huǒchē qù Běijīng.", ko: "우리는 기차를 타고 베이징에 간다." } },
        { zh: "机票", pinyin: "jī piào", ko: "비행기표, 항공권", pos: "명사", ex: { zh: "我买了两张机票。", pinyin: "Wǒ mǎi le liǎng zhāng jīpiào.", ko: "나는 비행기표 두 장을 샀다." } },
        { zh: "记", pinyin: "jì", ko: "기록하다, 기억하다, 외우다", pos: "동사", ex: { zh: "请把这个记下来。", pinyin: "Qǐng bǎ zhège jì xiàlai.", ko: "이것을 좀 적어 두세요." } },
        { zh: "记住", pinyin: "jì zhu", ko: "기억하다, 명심하다", pos: "동사", ex: { zh: "请记住我的电话号码。", pinyin: "Qǐng jì zhu wǒ de diànhuà hàomǎ.", ko: "제 전화번호를 기억해 주세요." } },
        { zh: "家里", pinyin: "jiā lǐ", ko: "집, 집안", pos: "명사", ex: { zh: "我家里有四口人。", pinyin: "Wǒ jiā lǐ yǒu sì kǒu rén.", ko: "우리 집에는 네 식구가 있다." } },
        { zh: "家人", pinyin: "jiā rén", ko: "가족", pos: "명사", ex: { zh: "我很爱我的家人。", pinyin: "Wǒ hěn ài wǒ de jiārén.", ko: "나는 우리 가족을 매우 사랑한다." } },
        { zh: "间", pinyin: "jiān", ko: "칸(방을 세는 단위), 사이", pos: "양사", ex: { zh: "这间房间很大。", pinyin: "Zhè jiān fángjiān hěn dà.", ko: "이 방은 매우 크다." } },
        { zh: "见", pinyin: "jiàn", ko: "보다, 만나다", pos: "동사", ex: { zh: "我们明天见。", pinyin: "Wǒmen míngtiān jiàn.", ko: "우리 내일 만나자." } },
        { zh: "教学楼", pinyin: "jiào xué lóu", ko: "강의동, 교육관", pos: "명사", ex: { zh: "教室在教学楼三楼。", pinyin: "Jiàoshì zài jiàoxué lóu sān lóu.", ko: "교실은 강의동 3층에 있다." } },
        { zh: "姐", pinyin: "jiě", ko: "누나, 언니", pos: "명사", ex: { zh: "我姐结婚了。", pinyin: "Wǒ jiě jié hūn le.", ko: "우리 언니는 결혼했다." } },
        { zh: "今年", pinyin: "jīn nián", ko: "올해, 금년", pos: "명사", ex: { zh: "今年我二十岁。", pinyin: "Jīnnián wǒ èrshí suì.", ko: "올해 나는 스무 살이다." } },
        { zh: "进来", pinyin: "jìn lái", ko: "들어오다", pos: "동사", ex: { zh: "请进来。", pinyin: "Qǐng jìnlái.", ko: "들어오세요." } },
        { zh: "进去", pinyin: "jìn qù", ko: "들어가다", pos: "동사", ex: { zh: "你先进去吧。", pinyin: "Nǐ xiān jìnqù ba.", ko: "너 먼저 들어가." } },
        { zh: "开车", pinyin: "kāi chē", ko: "운전하다", pos: "동사", ex: { zh: "他每天开车上班。", pinyin: "Tā měitiān kāichē shàngbān.", ko: "그는 매일 차를 몰고 출근한다." } },
        { zh: "开会", pinyin: "kāi huì", ko: "회의하다", pos: "동사", ex: { zh: "明天上午开会。", pinyin: "Míngtiān shàngwǔ kāihuì.", ko: "내일 오전에 회의가 있다." } },
        { zh: "看病", pinyin: "kàn bìng", ko: "진찰받다, 병원에 가다", pos: "동사", ex: { zh: "我要去医院看病。", pinyin: "Wǒ yào qù yīyuàn kàn bìng.", ko: "나는 병원에 진찰받으러 간다." } },
        { zh: "看到", pinyin: "kàn dào", ko: "보다, 보이다", pos: "동사", ex: { zh: "我看到他了。", pinyin: "wǒ kàn dào tā le.", ko: "나는 그를 보았다." } },
        { zh: "考", pinyin: "kǎo", ko: "시험 보다, 검사하다", pos: "동사", ex: { zh: "他考了一百分。", pinyin: "tā kǎo le yì bǎi fēn.", ko: "그는 시험에서 백 점을 받았다." } },
        { zh: "课本", pinyin: "kè běn", ko: "교과서", pos: "명사", ex: { zh: "这是我的课本。", pinyin: "zhè shì wǒ de kè běn.", ko: "이것은 내 교과서이다." } },
        { zh: "课文", pinyin: "kè wén", ko: "본문", pos: "명사", ex: { zh: "请打开课文读一读。", pinyin: "qǐng dǎ kāi kè wén dú yi dú.", ko: "본문을 펴서 읽어 보세요." } },
        { zh: "来到", pinyin: "lái dào", ko: "도착하다, 오다", pos: "동사", ex: { zh: "我们来到了北京。", pinyin: "wǒ men lái dào le Běi jīng.", ko: "우리는 베이징에 도착했다." } },
        { zh: "老人", pinyin: "lǎo rén", ko: "노인", pos: "명사", ex: { zh: "那个老人很健康。", pinyin: "nà ge lǎo rén hěn jiàn kāng.", ko: "그 노인은 매우 건강하다." } },
        { zh: "里边", pinyin: "lǐ bian", ko: "안, 안쪽", pos: "명사", ex: { zh: "房间里边很干净。", pinyin: "fáng jiān lǐ bian hěn gān jìng.", ko: "방 안은 매우 깨끗하다." } },
        { zh: "楼上", pinyin: "lóu shàng", ko: "위층", pos: "명사", ex: { zh: "我家在楼上。", pinyin: "wǒ jiā zài lóu shàng.", ko: "우리 집은 위층에 있다." } },
        { zh: "楼下", pinyin: "lóu xià", ko: "아래층", pos: "", ex: { zh: "他住在楼下。", pinyin: "tā zhù zài lóu xià.", ko: "그는 아래층에 산다." } },
        { zh: "路口", pinyin: "lù kǒu", ko: "교차로", pos: "명사", ex: { zh: "请在路口右转。", pinyin: "qǐng zài lù kǒu yòu zhuǎn.", ko: "교차로에서 우회전하세요." } },
        { zh: "路上", pinyin: "lù shang", ko: "길에서, 도중에", pos: "", ex: { zh: "我在路上看见了他。", pinyin: "wǒ zài lù shang kàn jiàn le tā.", ko: "나는 길에서 그를 보았다." } },
        { zh: "妈", pinyin: "mā", ko: "엄마", pos: "명사", ex: { zh: "妈,我回来了。", pinyin: "mā, wǒ huí lái le.", ko: "엄마, 저 왔어요." } },
        { zh: "马路", pinyin: "mǎ lù", ko: "대로, 큰길", pos: "명사", ex: { zh: "过马路要小心。", pinyin: "guò mǎ lù yào xiǎo xīn.", ko: "길을 건널 때는 조심해야 한다." } },
        { zh: "没什么", pinyin: "méi shén me", ko: "별거 아니다, 괜찮다", pos: "동사", ex: { zh: "没什么,别担心。", pinyin: "méi shén me, bié dān xīn.", ko: "별거 아니야, 걱정하지 마." } },
        { zh: "没事儿", pinyin: "méi shìr", ko: "괜찮다, 별일 없다", pos: "동사", ex: { zh: "你没事儿吧?", pinyin: "nǐ méi shìr ba?", ko: "너 괜찮아?" } },
        { zh: "没有", pinyin: "méi yǒu", ko: "없다, ~하지 않았다", pos: "동사", ex: { zh: "我没有钱。", pinyin: "wǒ méi yǒu qián.", ko: "나는 돈이 없다." } },
        { zh: "妹", pinyin: "mèi", ko: "여동생", pos: "명사", ex: { zh: "这是我妹。", pinyin: "zhè shì wǒ mèi.", ko: "이 애는 내 여동생이다." } },
        { zh: "门口", pinyin: "mén kǒu", ko: "입구, 문 앞", pos: "", ex: { zh: "他在门口等我。", pinyin: "tā zài mén kǒu děng wǒ.", ko: "그는 입구에서 나를 기다린다." } },
        { zh: "门票", pinyin: "mén piào", ko: "입장권", pos: "명사", ex: { zh: "门票多少钱?", pinyin: "mén piào duō shao qián?", ko: "입장권은 얼마예요?" } },
        { zh: "们", pinyin: "men", ko: "~들 (복수 접미사)", pos: "", ex: { zh: "老师们都很忙。", pinyin: "lǎo shī men dōu hěn máng.", ko: "선생님들은 모두 바쁘다." } },
        { zh: "面条儿", pinyin: "miàn tiáor", ko: "국수", pos: "", ex: { zh: "我喜欢吃面条儿。", pinyin: "wǒ xǐ huan chī miàn tiáor.", ko: "나는 국수 먹는 것을 좋아한다." } },
        { zh: "明年", pinyin: "míng nián", ko: "내년", pos: "명사", ex: { zh: "明年我要去中国。", pinyin: "míng nián wǒ yào qù Zhōng guó.", ko: "내년에 나는 중국에 갈 것이다." } },
        { zh: "哪里", pinyin: "nǎ lǐ", ko: "어디", pos: "대명사", ex: { zh: "你家在哪里?", pinyin: "nǐ jiā zài nǎ lǐ?", ko: "너희 집은 어디니?" } },
        { zh: "哪些", pinyin: "nǎ xiē", ko: "어느 것들", pos: "대명사", ex: { zh: "你喜欢哪些颜色?", pinyin: "nǐ xǐ huan nǎ xiē yán sè?", ko: "너는 어떤 색깔들을 좋아하니?" } },
        { zh: "那边", pinyin: "nà bian", ko: "저쪽", pos: "대명사", ex: { zh: "那边有一个公园。", pinyin: "nà bian yǒu yí ge gōng yuán.", ko: "저쪽에 공원이 하나 있다." } },
        { zh: "那里", pinyin: "nà li", ko: "저기, 그곳", pos: "대명사", ex: { zh: "他住在那里。", pinyin: "tā zhù zài nà li.", ko: "그는 저기에 산다." } },
        { zh: "那些", pinyin: "nà xiē", ko: "저것들, 그것들", pos: "대명사", ex: { zh: "那些书是我的。", pinyin: "nà xiē shū shì wǒ de.", ko: "저 책들은 내 것이다." } },
        { zh: "奶", pinyin: "nǎi", ko: "우유, 젖", pos: "명사", ex: { zh: "宝宝在喝奶。", pinyin: "bǎo bao zài hē nǎi.", ko: "아기가 우유를 마시고 있다." } },
        { zh: "男孩儿", pinyin: "nán háir", ko: "남자아이", pos: "", ex: { zh: "那个男孩儿很聪明。", pinyin: "nà ge nán háir hěn cōng ming.", ko: "그 남자아이는 매우 똑똑하다." } },
        { zh: "男朋友", pinyin: "nán péng you", ko: "남자친구", pos: "명사", ex: { zh: "她有男朋友了。", pinyin: "tā yǒu nán péng you le.", ko: "그녀는 남자친구가 생겼다." } },
        { zh: "男生", pinyin: "nán shēng", ko: "남학생", pos: "명사", ex: { zh: "班里的男生很多。", pinyin: "bān lǐ de nán shēng hěn duō.", ko: "반에 남학생이 많다." } },
        { zh: "南边", pinyin: "nán bian", ko: "남쪽", pos: "명사", ex: { zh: "学校在城市的南边。", pinyin: "xué xiào zài chéng shì de nán bian.", ko: "학교는 도시의 남쪽에 있다." } },
        { zh: "你们", pinyin: "nǐ men", ko: "너희들, 여러분", pos: "대명사", ex: { zh: "你们好!", pinyin: "nǐ men hǎo!", ko: "여러분 안녕하세요!" } },
        { zh: "女孩儿", pinyin: "nǚ háir", ko: "여자아이", pos: "", ex: { zh: "那个女孩儿在唱歌。", pinyin: "nà ge nǚ háir zài chàng gē.", ko: "그 여자아이는 노래를 부르고 있다." } },
        { zh: "女朋友", pinyin: "nǚ péng you", ko: "여자친구", pos: "명사", ex: { zh: "他和女朋友一起看电影。", pinyin: "tā hé nǚ péng you yì qǐ kàn diàn yǐng.", ko: "그는 여자친구와 함께 영화를 본다." } },
        { zh: "女生", pinyin: "nǚ shēng", ko: "여학생", pos: "명사", ex: { zh: "那位女生学习很努力。", pinyin: "nà wèi nǚ shēng xué xí hěn nǔ lì.", ko: "그 여학생은 공부를 매우 열심히 한다." } },
        { zh: "起", pinyin: "qǐ", ko: "일어나다", pos: "동사", ex: { zh: "他七点就起了。", pinyin: "tā qī diǎn jiù qǐ le.", ko: "그는 7시에 일어났다." } },
        { zh: "汽车", pinyin: "qì chē", ko: "자동차", pos: "명사", ex: { zh: "他买了一辆新汽车。", pinyin: "tā mǎi le yí liàng xīn qì chē.", ko: "그는 새 자동차를 한 대 샀다." } },
        { zh: "前", pinyin: "qián", ko: "앞, 이전", pos: "명사", ex: { zh: "往前走就是学校。", pinyin: "wǎng qián zǒu jiù shì xué xiào.", ko: "앞으로 걸어가면 바로 학교이다." } },
        { zh: "前边", pinyin: "qián bian", ko: "앞, 앞쪽", pos: "명사", ex: { zh: "前边有一家商店。", pinyin: "qián bian yǒu yì jiā shāng diàn.", ko: "앞쪽에 가게가 하나 있다." } },
        { zh: "前天", pinyin: "qián tiān", ko: "그저께", pos: "명사", ex: { zh: "前天我去了图书馆。", pinyin: "qián tiān wǒ qù le tú shū guǎn。", ko: "그저께 나는 도서관에 갔다." } },
        { zh: "请进", pinyin: "qǐng jìn", ko: "들어오세요", pos: "", ex: { zh: "请进，请坐。", pinyin: "qǐng jìn, qǐng zuò。", ko: "들어오세요, 앉으세요." } },
        { zh: "请问", pinyin: "qǐng wèn", ko: "말씀 좀 여쭙겠습니다, 실례합니다", pos: "동사", ex: { zh: "请问，洗手间在哪儿？", pinyin: "qǐng wèn, xǐ shǒu jiān zài nǎr?", ko: "실례합니다, 화장실이 어디예요?" } },
        { zh: "请坐", pinyin: "qǐng zuò", ko: "앉으세요", pos: "", ex: { zh: "大家请坐。", pinyin: "dà jiā qǐng zuò。", ko: "여러분 앉으세요." } },
        { zh: "球", pinyin: "qiú", ko: "공", pos: "명사", ex: { zh: "他喜欢踢球。", pinyin: "tā xǐ huan tī qiú。", ko: "그는 공 차는 것을 좋아한다." } },
        { zh: "肉", pinyin: "ròu", ko: "고기", pos: "명사", ex: { zh: "我不吃肉。", pinyin: "wǒ bù chī ròu。", ko: "나는 고기를 먹지 않는다." } },
        { zh: "山", pinyin: "shān", ko: "산", pos: "명사", ex: { zh: "这座山很高。", pinyin: "Zhè zuò shān hěn gāo.", ko: "이 산은 매우 높다." } },
        { zh: "商场", pinyin: "shāng chǎng", ko: "쇼핑몰, 백화점", pos: "명사", ex: { zh: "我们周末去商场买衣服。", pinyin: "wǒ men zhōu mò qù shāng chǎng mǎi yī fu。", ko: "우리는 주말에 쇼핑몰에 옷을 사러 간다." } },
        { zh: "上边", pinyin: "shàng bian", ko: "위, 위쪽", pos: "명사", ex: { zh: "书放在桌子上边。", pinyin: "shū fàng zài zhuō zi shàng bian。", ko: "책은 책상 위에 놓여 있다." } },
        { zh: "上车", pinyin: "shàng chē", ko: "차에 타다", pos: "동사", ex: { zh: "我们快上车吧。", pinyin: "wǒ men kuài shàng chē ba。", ko: "우리 빨리 차에 타자." } },
        { zh: "上次", pinyin: "shàng cì", ko: "지난번", pos: "명사", ex: { zh: "上次谢谢你的帮助。", pinyin: "shàng cì xiè xie nǐ de bāng zhù。", ko: "지난번 도와줘서 고마워요." } },
        { zh: "上课", pinyin: "shàng kè", ko: "수업하다, 수업을 듣다", pos: "동사", ex: { zh: "我们八点上课。", pinyin: "wǒ men bā diǎn shàng kè。", ko: "우리는 8시에 수업을 한다." } },
        { zh: "上学", pinyin: "shàng xué", ko: "학교에 가다, 등교하다", pos: "동사", ex: { zh: "弟弟明年上学。", pinyin: "dì di míng nián shàng xué。", ko: "남동생은 내년에 학교에 간다." } },
        { zh: "身上", pinyin: "shēn shang", ko: "몸에, 몸에 지님", pos: "", ex: { zh: "他身上没有钱。", pinyin: "tā shēn shang méi yǒu qián。", ko: "그는 몸에 돈이 없다." } },
        { zh: "事", pinyin: "shì", ko: "일", pos: "명사", ex: { zh: "我有点儿事要跟你说。", pinyin: "wǒ yǒu diǎnr shì yào gēn nǐ shuō。", ko: "너에게 말할 일이 좀 있어." } },
        { zh: "是不是", pinyin: "shì bù shì", ko: "~인지 아닌지, ~이지요?", pos: "동사", ex: { zh: "你是不是学生？", pinyin: "nǐ shì bú shì xué sheng?", ko: "너는 학생이니 아니니?" } },
        { zh: "手", pinyin: "shǒu", ko: "손", pos: "명사", ex: { zh: "请举手。", pinyin: "qǐng jǔ shǒu。", ko: "손을 들어 주세요." } },
        { zh: "书包", pinyin: "shū bāo", ko: "책가방", pos: "명사", ex: { zh: "她背着书包上学。", pinyin: "tā bēi zhe shū bāo shàng xué。", ko: "그녀는 책가방을 메고 학교에 간다." } },
        { zh: "书店", pinyin: "shū diàn", ko: "서점", pos: "명사", ex: { zh: "附近有一家书店。", pinyin: "fù jìn yǒu yì jiā shū diàn。", ko: "근처에 서점이 하나 있다." } },
        { zh: "睡", pinyin: "shuì", ko: "자다", pos: "동사", ex: { zh: "我昨晚睡得很晚。", pinyin: "wǒ zuó wǎn shuì de hěn wǎn。", ko: "나는 어젯밤 늦게 잤다." } },
        { zh: "他们", pinyin: "tā men", ko: "그들", pos: "대명사", ex: { zh: "他们是我的同学。", pinyin: "tā men shì wǒ de tóng xué。", ko: "그들은 나의 학교 친구이다." } },
        { zh: "她们", pinyin: "tā men", ko: "그녀들", pos: "대명사", ex: { zh: "她们都是老师。", pinyin: "tā men dōu shì lǎo shī。", ko: "그녀들은 모두 선생님이다." } },
        { zh: "天", pinyin: "tiān", ko: "하늘, 날", pos: "명사", ex: { zh: "今天天气很好。", pinyin: "jīn tiān tiān qì hěn hǎo。", ko: "오늘 날씨가 좋다." } },
        { zh: "听到", pinyin: "tīng dào", ko: "듣다, 들리다", pos: "동사", ex: { zh: "我听到了他的声音。", pinyin: "wǒ tīng dào le tā de shēng yīn。", ko: "나는 그의 목소리를 들었다." } },
        { zh: "听写", pinyin: "tīng xiě", ko: "받아쓰기", pos: "동사", ex: { zh: "老师让我们听写生词。", pinyin: "lǎo shī ràng wǒ men tīng xiě shēng cí。", ko: "선생님은 우리에게 단어 받아쓰기를 시켰다." } },
        { zh: "外边", pinyin: "wài bian", ko: "밖, 바깥", pos: "명사", ex: { zh: "外边下雨了。", pinyin: "wài bian xià yǔ le。", ko: "밖에 비가 온다." } },
        { zh: "外国", pinyin: "wài guó", ko: "외국", pos: "명사", ex: { zh: "她想去外国留学。", pinyin: "tā xiǎng qù wài guó liú xué。", ko: "그녀는 외국에 유학 가고 싶어한다." } },
        { zh: "外语", pinyin: "wài yǔ", ko: "외국어", pos: "명사", ex: { zh: "他会说三种外语。", pinyin: "tā huì shuō sān zhǒng wài yǔ。", ko: "그는 세 가지 외국어를 할 줄 안다." } },
        { zh: "玩儿", pinyin: "wánr", ko: "놀다", pos: "동사", ex: { zh: "孩子们在公园玩儿。", pinyin: "hái zi men zài gōng yuán wánr。", ko: "아이들이 공원에서 논다." } },
        { zh: "晚", pinyin: "wǎn", ko: "늦다, 저녁", pos: "형용사", ex: { zh: "今天我起得很晚。", pinyin: "jīn tiān wǒ qǐ de hěn wǎn。", ko: "오늘 나는 늦게 일어났다." } },
        { zh: "晚饭", pinyin: "wǎn fàn", ko: "저녁밥", pos: "명사", ex: { zh: "我们六点吃晚饭。", pinyin: "wǒ men liù diǎn chī wǎn fàn。", ko: "우리는 6시에 저녁을 먹는다." } },
        { zh: "网友", pinyin: "wǎng yǒu", ko: "인터넷 친구", pos: "명사", ex: { zh: "我在网上认识了一个网友。", pinyin: "wǒ zài wǎng shàng rèn shi le yí gè wǎng yǒu。", ko: "나는 인터넷에서 한 인터넷 친구를 알게 되었다." } },
        { zh: "午饭", pinyin: "wǔ fàn", ko: "점심밥", pos: "명사", ex: { zh: "我们一起吃午饭吧。", pinyin: "wǒ men yì qǐ chī wǔ fàn ba。", ko: "우리 같이 점심 먹자." } },
        { zh: "西边", pinyin: "xī biān", ko: "서쪽", pos: "명사", ex: { zh: "太阳从西边落下。", pinyin: "tài yáng cóng xī biān luò xià。", ko: "해는 서쪽으로 진다." } },
        { zh: "下边", pinyin: "xià bian", ko: "아래, 아래쪽", pos: "명사", ex: { zh: "猫在桌子下边。", pinyin: "māo zài zhuō zi xià bian。", ko: "고양이가 책상 아래에 있다." } },
        { zh: "下车", pinyin: "xià chē", ko: "차에서 내리다", pos: "동사", ex: { zh: "请在下一站下车。", pinyin: "qǐng zài xià yí zhàn xià chē。", ko: "다음 정거장에서 내려 주세요." } },
        { zh: "下次", pinyin: "xià cì", ko: "다음번", pos: "명사", ex: { zh: "下次我们再见面吧。", pinyin: "xià cì wǒ men zài jiàn miàn ba。", ko: "다음번에 우리 또 만나자." } },
        { zh: "下课", pinyin: "xià kè", ko: "수업이 끝나다", pos: "동사", ex: { zh: "我们十点下课。", pinyin: "wǒ men shí diǎn xià kè。", ko: "우리는 10시에 수업이 끝난다." } },
        { zh: "小孩儿", pinyin: "xiǎo háir", ko: "아이, 어린이", pos: "", ex: { zh: "这个小孩儿真可爱。", pinyin: "zhè ge xiǎo háir zhēn kě ài。", ko: "이 아이는 정말 귀엽다." } },
        { zh: "小朋友", pinyin: "xiǎo péng yǒu", ko: "어린이, 꼬마", pos: "명사", ex: { zh: "小朋友们都喜欢这个游戏。", pinyin: "xiǎo péng yǒu men dōu xǐ huan zhè ge yóu xì。", ko: "어린이들은 모두 이 게임을 좋아한다." } },
        { zh: "小学", pinyin: "xiǎo xué", ko: "초등학교", pos: "명사", ex: { zh: "我妹妹在小学读三年级。", pinyin: "Wǒ mèi mei zài xiǎo xué dú sān nián jí.", ko: "내 여동생은 초등학교 3학년이다." } },
        { zh: "小学生", pinyin: "xiǎo xué shēng", ko: "초등학생", pos: "명사", ex: { zh: "小学生们放学后在操场玩耍。", pinyin: "Xiǎo xué shēng men fàng xué hòu zài cāo chǎng wán shuǎ.", ko: "초등학생들은 방과 후 운동장에서 논다." } },
        { zh: "新年", pinyin: "xīn nián", ko: "새해", pos: "명사", ex: { zh: "祝你新年快乐!", pinyin: "Zhù nǐ xīn nián kuài lè!", ko: "새해 복 많이 받으세요!" } },
        { zh: "星期日", pinyin: "Xīng qī rì", ko: "일요일", pos: "명사", ex: { zh: "星期日我们全家去公园。", pinyin: "Xīng qī rì wǒ men quán jiā qù gōng yuán.", ko: "일요일에 우리 가족은 공원에 간다." } },
        { zh: "星期天", pinyin: "Xīng qī tiān", ko: "일요일", pos: "명사", ex: { zh: "星期天商店不开门。", pinyin: "Xīng qī tiān shāng diàn bù kāi mén.", ko: "일요일에는 가게가 문을 열지 않는다." } },
        { zh: "学", pinyin: "xué", ko: "배우다, 공부하다", pos: "동사", ex: { zh: "他每天学两个小时汉语。", pinyin: "Tā měi tiān xué liǎng gè xiǎo shí Hàn yǔ.", ko: "그는 매일 두 시간씩 중국어를 공부한다." } },
        { zh: "学院", pinyin: "xué yuàn", ko: "학원, 단과대학", pos: "명사", ex: { zh: "她在艺术学院学习绘画。", pinyin: "Tā zài yì shù xué yuàn xué xí huì huà.", ko: "그녀는 예술대학에서 그림을 공부한다." } },
        { zh: "一半", pinyin: "yī bàn", ko: "절반", pos: "수사", ex: { zh: "这个苹果我吃了一半。", pinyin: "Zhè ge píng guǒ wǒ chī le yī bàn.", ko: "나는 이 사과를 절반 먹었다." } },
        { zh: "一点儿", pinyin: "yī diǎnr", ko: "조금, 약간", pos: "", ex: { zh: "请给我一点儿水。", pinyin: "Qǐng gěi wǒ yī diǎnr shuǐ.", ko: "물을 조금만 주세요." } },
        { zh: "一块儿", pinyin: "yī kuàir", ko: "함께, 같이", pos: "부사", ex: { zh: "我们一块儿去看电影吧。", pinyin: "Wǒ men yī kuàir qù kàn diàn yǐng ba.", ko: "우리 같이 영화 보러 가자." } },
        { zh: "一下儿", pinyin: "yī xiàr", ko: "한번, 잠깐", pos: "", ex: { zh: "你等一下儿,我马上回来。", pinyin: "Nǐ děng yī xiàr, wǒ mǎ shàng huí lái.", ko: "잠깐만 기다려, 곧 돌아올게." } },
        { zh: "一些", pinyin: "yī xiē", ko: "약간, 몇몇", pos: "", ex: { zh: "桌子上有一些书。", pinyin: "Zhuō zi shàng yǒu yī xiē shū.", ko: "책상 위에 책이 몇 권 있다." } },
        { zh: "有的", pinyin: "yǒu de", ko: "어떤 것(사람)은", pos: "대명사", ex: { zh: "有的人喜欢喝茶,有的人喜欢喝咖啡。", pinyin: "Yǒu de rén xǐ huan hē chá, yǒu de rén xǐ huan hē kā fēi.", ko: "어떤 사람은 차를 좋아하고 어떤 사람은 커피를 좋아한다." } },
        { zh: "有时", pinyin: "yǒu shí", ko: "때때로, 가끔", pos: "부사", ex: { zh: "他有时晚上加班。", pinyin: "Tā yǒu shí wǎn shang jiā bān.", ko: "그는 가끔 밤에 야근한다." } },
        { zh: "有时候", pinyin: "yǒu shí hou", ko: "가끔, 어떤 때는", pos: "부사", ex: { zh: "有时候我一个人去旅行。", pinyin: "Yǒu shí hou wǒ yí gè rén qù lǚ xíng.", ko: "가끔 나는 혼자 여행을 간다." } },
        { zh: "有些", pinyin: "yǒu xiē", ko: "일부, 어느 정도", pos: "대명사", ex: { zh: "有些问题我还不明白。", pinyin: "Yǒu xiē wèn tí wǒ hái bù míng bai.", ko: "어떤 문제들은 아직 이해가 안 된다." } },
        { zh: "有一些", pinyin: "yǒu yī xiē", ko: "약간, 다소", pos: "", ex: { zh: "今天天气有一些冷。", pinyin: "Jīn tiān tiān qì yǒu yī xiē lěng.", ko: "오늘 날씨가 좀 춥다." } },
        { zh: "有用", pinyin: "yǒu yòng", ko: "유용하다", pos: "형용사", ex: { zh: "这本词典很有用。", pinyin: "Zhè běn cí diǎn hěn yǒu yòng.", ko: "이 사전은 매우 유용하다." } },
        { zh: "右", pinyin: "yòu", ko: "오른쪽, 우측", pos: "명사", ex: { zh: "邮局在银行的右边。", pinyin: "Yóu jú zài yín háng de yòu bian.", ko: "우체국은 은행 오른쪽에 있다." } },
        { zh: "在家", pinyin: "zài jiā", ko: "집에 있다", pos: "동사", ex: { zh: "周末我一般在家休息。", pinyin: "Zhōu mò wǒ yì bān zài jiā xiū xi.", ko: "주말에 나는 보통 집에서 쉰다." } },
        { zh: "早", pinyin: "zǎo", ko: "이르다, 안녕하세요(아침 인사)", pos: "형용사", ex: { zh: "他每天很早起床。", pinyin: "Tā měi tiān hěn zǎo qǐ chuáng.", ko: "그는 매일 아주 일찍 일어난다." } },
        { zh: "这边", pinyin: "zhè biān", ko: "이쪽", pos: "대명사", ex: { zh: "请往这边走。", pinyin: "Qǐng wǎng zhè biān zǒu.", ko: "이쪽으로 가세요." } },
        { zh: "这里", pinyin: "zhè lǐ", ko: "여기, 이곳", pos: "대명사", ex: { zh: "这里的风景很美。", pinyin: "Zhè lǐ de fēng jǐng hěn měi.", ko: "이곳의 풍경은 매우 아름답다." } },
        { zh: "这些", pinyin: "zhè xiē", ko: "이것들, 이런 것들", pos: "대명사", ex: { zh: "这些照片是我去年拍的。", pinyin: "Zhè xiē zhào piàn shì wǒ qù nián pāi de.", ko: "이 사진들은 내가 작년에 찍은 것이다." } },
        { zh: "真的", pinyin: "zhēn de", ko: "정말로, 진짜로", pos: "부사", ex: { zh: "这件事是真的吗?", pinyin: "Zhè jiàn shì shì zhēn de ma?", ko: "이 일이 정말이야?" } },
        { zh: "中", pinyin: "zhōng", ko: "중국(의 약칭), 가운데", pos: "명사", ex: { zh: "中日两国是邻居。", pinyin: "Zhōng Rì liǎng guó shì lín jū.", ko: "중국과 일본 두 나라는 이웃이다." } },
        { zh: "中学", pinyin: "zhōng xué", ko: "중고등학교", pos: "명사", ex: { zh: "他在这所中学教数学。", pinyin: "Tā zài zhè suǒ zhōng xué jiāo shù xué.", ko: "그는 이 중학교에서 수학을 가르친다." } },
        { zh: "中学生", pinyin: "zhōng xué shēng", ko: "중고등학생", pos: "명사", ex: { zh: "中学生的作业很多。", pinyin: "Zhōng xué shēng de zuò yè hěn duō.", ko: "중고등학생은 숙제가 많다." } },
        { zh: "子", pinyin: "zǐ", ko: "자식, 아들; 씨앗", pos: "양사", ex: { zh: "他有一个儿子和一个女儿。", pinyin: "Tā yǒu yí gè ér zi hé yí gè nǚ ér.", ko: "그는 아들 하나와 딸 하나가 있다." } },
        { zh: "左", pinyin: "zuǒ", ko: "왼쪽; 성씨 좌", pos: "명사", ex: { zh: "图书馆在教室的左边。", pinyin: "Tú shū guǎn zài jiào shì de zuǒ bian.", ko: "도서관은 교실 왼쪽에 있다." } },
        { zh: "坐下", pinyin: "zuò xia", ko: "앉다", pos: "동사", ex: { zh: "请大家坐下。", pinyin: "Qǐng dà jiā zuò xia.", ko: "모두 앉아 주세요." } },
      ],
    },
  ],
}

export default themes;
