/**
 * H2 (HSK 2급) 어휘 — 일상 화제를 더 풍부하게.
 * 사람과 가족·시간과 날씨·음식과 쇼핑·동작과 표현·형용사와 부사·장소와 교통 여섯 테마.
 */
const themes = {
  level: "H2",
  title: "H2 어휘",
  desc: "1급에서 한 걸음 더 — 가족·날씨·쇼핑·감정까지 일상 대화를 넓혀 주는 HSK 2급 핵심 어휘 100여 개예요.",
  themes: [
    {
      name: "사람과 가족",
      words: [
        { zh: "爸爸", pinyin: "bàba", ko: "아빠", pos: "명사", ex: { zh: "我爸爸是老师。", pinyin: "wǒ bàba shì lǎoshī", ko: "우리 아빠는 선생님이에요." } },
        { zh: "妈妈", pinyin: "māma", ko: "엄마", pos: "명사", ex: { zh: "妈妈做的菜很好吃。", pinyin: "māma zuò de cài hěn hǎochī", ko: "엄마가 만든 요리는 맛있어요." } },
        { zh: "哥哥", pinyin: "gēge", ko: "형, 오빠", pos: "명사", ex: { zh: "我有一个哥哥。", pinyin: "wǒ yǒu yí ge gēge", ko: "저는 형이 한 명 있어요." } },
        { zh: "姐姐", pinyin: "jiějie", ko: "누나, 언니", pos: "명사", ex: { zh: "姐姐在北京工作。", pinyin: "jiějie zài Běijīng gōngzuò", ko: "언니는 베이징에서 일해요." } },
        { zh: "弟弟", pinyin: "dìdi", ko: "남동생", pos: "명사", hanja: "제(弟) — '아우 제'.", ex: { zh: "我弟弟是学生。", pinyin: "wǒ dìdi shì xuésheng", ko: "제 남동생은 학생이에요." } },
        { zh: "妹妹", pinyin: "mèimei", ko: "여동생", pos: "명사", hanja: "매(妹) — '누이 매'.", ex: { zh: "妹妹很漂亮。", pinyin: "mèimei hěn piàoliang", ko: "여동생은 예뻐요." } },
        { zh: "儿子", pinyin: "érzi", ko: "아들", pos: "명사", hanja: "아자(兒子) — '兒'는 아이 아.", ex: { zh: "他的儿子十岁了。", pinyin: "tā de érzi shí suì le", ko: "그의 아들은 열 살이에요." } },
        { zh: "女儿", pinyin: "nǚ'ér", ko: "딸", pos: "명사", hanja: "여아(女兒) — '女'는 여자 여.", ex: { zh: "我女儿在上学。", pinyin: "wǒ nǚ'ér zài shàngxué", ko: "제 딸은 학교에 다녀요." } },
        { zh: "孩子", pinyin: "háizi", ko: "아이, 자녀", pos: "명사", ex: { zh: "他们有两个孩子。", pinyin: "tāmen yǒu liǎng ge háizi", ko: "그들은 아이가 둘 있어요." } },
        { zh: "丈夫", pinyin: "zhàngfu", ko: "남편", pos: "명사", hanja: "장부(丈夫) — 한국 '대장부'의 그 장부지만 뜻은 '남편'.", ex: { zh: "她的丈夫是医生。", pinyin: "tā de zhàngfu shì yīshēng", ko: "그녀의 남편은 의사예요." } },
        { zh: "妻子", pinyin: "qīzi", ko: "아내", pos: "명사", hanja: "처자(妻子) — '妻'는 아내 처. 한국 '처자(아가씨)'와 뜻이 달라요!", ex: { zh: "这是我妻子。", pinyin: "zhè shì wǒ qīzi", ko: "이쪽은 제 아내예요." } },
        { zh: "男", pinyin: "nán", ko: "남자의, 남성", pos: "명사", hanja: "남(男).", ex: { zh: "他是男老师。", pinyin: "tā shì nán lǎoshī", ko: "그는 남자 선생님이에요." } },
        { zh: "女", pinyin: "nǚ", ko: "여자의, 여성", pos: "명사", hanja: "여(女).", ex: { zh: "她是女医生。", pinyin: "tā shì nǚ yīshēng", ko: "그녀는 여의사예요." } },
        { zh: "大家", pinyin: "dàjiā", ko: "여러분, 모두", pos: "대사", hanja: "대가(大家) — 직역하면 '큰 집', 즉 '모두'.", ex: { zh: "大家好！", pinyin: "dàjiā hǎo", ko: "여러분 안녕하세요!" } },
      ],
    },
    {
      name: "시간과 날씨",
      words: [
        { zh: "早上", pinyin: "zǎoshang", ko: "아침", pos: "명사", hanja: "조상(早上) — '早'는 이를 조.", ex: { zh: "我早上六点起床。", pinyin: "wǒ zǎoshang liù diǎn qǐchuáng", ko: "저는 아침 6시에 일어나요." } },
        { zh: "中午", pinyin: "zhōngwǔ", ko: "정오, 점심때", pos: "명사", hanja: "중오(中午) — '午'는 낮 오.", ex: { zh: "中午我们一起吃饭。", pinyin: "zhōngwǔ wǒmen yìqǐ chī fàn", ko: "점심에 우리 같이 밥 먹어요." } },
        { zh: "晚上", pinyin: "wǎnshang", ko: "저녁, 밤", pos: "명사", hanja: "만상(晚上) — '晚'은 늦을 만.", ex: { zh: "晚上我在家看电视。", pinyin: "wǎnshang wǒ zài jiā kàn diànshì", ko: "저녁에 저는 집에서 텔레비전을 봐요." } },
        { zh: "小时", pinyin: "xiǎoshí", ko: "시간 (단위)", pos: "명사", hanja: "소시(小時) — 한 '시간'을 가리켜요.", ex: { zh: "我学了两个小时。", pinyin: "wǒ xué le liǎng ge xiǎoshí", ko: "저는 두 시간 공부했어요." } },
        { zh: "号", pinyin: "hào", ko: "일 (날짜), 번호", pos: "명사", hanja: "호(號) — 날짜와 번호를 가리켜요.", ex: { zh: "今天五月十号。", pinyin: "jīntiān wǔ yuè shí hào", ko: "오늘은 5월 10일이에요." } },
        { zh: "去年", pinyin: "qùnián", ko: "작년", pos: "명사", hanja: "거년(去年) — '去'는 갈 거, 지나간 해.", ex: { zh: "去年我去了中国。", pinyin: "qùnián wǒ qù le Zhōngguó", ko: "작년에 저는 중국에 갔어요." } },
        { zh: "天气", pinyin: "tiānqì", ko: "날씨", pos: "명사", hanja: "천기(天氣) — '天'은 하늘 천, '氣'는 기운 기.", ex: { zh: "今天天气怎么样？", pinyin: "jīntiān tiānqì zěnmeyàng", ko: "오늘 날씨 어때요?" } },
        { zh: "晴", pinyin: "qíng", ko: "맑다", pos: "형용사", hanja: "청(晴) — '갤 청'.", ex: { zh: "今天天晴。", pinyin: "jīntiān tiān qíng", ko: "오늘은 날이 맑아요." } },
        { zh: "阴", pinyin: "yīn", ko: "흐리다", pos: "형용사", hanja: "음(陰) — '그늘 음'.", ex: { zh: "今天天阴。", pinyin: "jīntiān tiān yīn", ko: "오늘은 날이 흐려요." } },
        { zh: "下雨", pinyin: "xià yǔ", ko: "비가 오다", pos: "동사", hanja: "하우(下雨) — '雨'는 비 우. 비가 '내리다'.", ex: { zh: "外面下雨了。", pinyin: "wàimiàn xià yǔ le", ko: "밖에 비가 와요." } },
        { zh: "雪", pinyin: "xuě", ko: "눈", pos: "명사", hanja: "설(雪).", ex: { zh: "冬天下雪。", pinyin: "dōngtiān xià xuě", ko: "겨울에 눈이 와요." } },
        { zh: "分钟", pinyin: "fēnzhōng", ko: "분 (시간 길이)", pos: "명사", hanja: "분종(分鐘) — '分'은 나눌 분.", ex: { zh: "请等我五分钟。", pinyin: "qǐng děng wǒ wǔ fēnzhōng", ko: "5분만 기다려 주세요." } },
        { zh: "生日", pinyin: "shēngrì", ko: "생일", pos: "명사", hanja: "생일(生日) — 한자 그대로.", ex: { zh: "祝你生日快乐！", pinyin: "zhù nǐ shēngrì kuàilè", ko: "생일 축하해요!" } },
      ],
    },
    {
      name: "음식과 쇼핑",
      words: [
        { zh: "鸡蛋", pinyin: "jīdàn", ko: "달걀", pos: "명사", hanja: "계단(鷄蛋) — '鷄'는 닭 계, '蛋'은 알. '닭의 알'.", ex: { zh: "我早上吃鸡蛋。", pinyin: "wǒ zǎoshang chī jīdàn", ko: "저는 아침에 달걀을 먹어요." } },
        { zh: "羊肉", pinyin: "yángròu", ko: "양고기", pos: "명사", hanja: "양육(羊肉) — '羊'은 양 양, '肉'은 고기 육.", ex: { zh: "我喜欢吃羊肉。", pinyin: "wǒ xǐhuan chī yángròu", ko: "저는 양고기를 좋아해요." } },
        { zh: "鱼", pinyin: "yú", ko: "물고기, 생선", pos: "명사", hanja: "어(魚).", ex: { zh: "这条鱼很大。", pinyin: "zhè tiáo yú hěn dà", ko: "이 물고기는 커요." } },
        { zh: "牛奶", pinyin: "niúnǎi", ko: "우유", pos: "명사", hanja: "우내(牛奶) — '牛'는 소 우. '소의 젖'.", ex: { zh: "我每天喝牛奶。", pinyin: "wǒ měi tiān hē niúnǎi", ko: "저는 매일 우유를 마셔요." } },
        { zh: "西瓜", pinyin: "xīguā", ko: "수박", pos: "명사", hanja: "서과(西瓜) — '서쪽 오이', 즉 수박.", ex: { zh: "夏天我喜欢吃西瓜。", pinyin: "xiàtiān wǒ xǐhuan chī xīguā", ko: "여름에 저는 수박을 좋아해요." } },
        { zh: "早饭", pinyin: "zǎofàn", ko: "아침밥", pos: "명사", hanja: "조반(早飯) — '早'는 이를 조, '飯'은 밥 반.", ex: { zh: "我吃了早饭。", pinyin: "wǒ chī le zǎofàn", ko: "저는 아침을 먹었어요." } },
        { zh: "咖啡", pinyin: "kāfēi", ko: "커피", pos: "명사", ex: { zh: "再来一杯咖啡。", pinyin: "zài lái yì bēi kāfēi", ko: "커피 한 잔 더 주세요." } },
        { zh: "钱", pinyin: "qián", ko: "돈", pos: "명사", hanja: "전(錢) — '돈 전'. 한국 화폐 단위 '전'과 같은 글자.", ex: { zh: "这个多少钱？", pinyin: "zhège duōshao qián", ko: "이거 얼마예요?" } },
        { zh: "块", pinyin: "kuài", ko: "위안 (화폐 단위), 덩어리", pos: "양사", ex: { zh: "这个十块钱。", pinyin: "zhège shí kuài qián", ko: "이건 10위안이에요." } },
        { zh: "次", pinyin: "cì", ko: "번, 회 (횟수)", pos: "양사", hanja: "차(次) — '버금 차'. 동작의 횟수를 세는 동량사.", ex: { zh: "我去过两次中国。", pinyin: "wǒ qù guo liǎng cì Zhōngguó", ko: "저는 중국에 두 번 가 봤어요." } },
        { zh: "卖", pinyin: "mài", ko: "팔다", pos: "동사", hanja: "매(賣) — '팔 매'. 사다(买 mǎi)와 헷갈리지 마세요.", ex: { zh: "他们卖水果。", pinyin: "tāmen mài shuǐguǒ", ko: "그들은 과일을 팔아요." } },
        { zh: "贵", pinyin: "guì", ko: "비싸다", pos: "형용사", hanja: "귀(貴) — '귀할 귀'. 귀하니까 비싸요.", ex: { zh: "这个太贵了。", pinyin: "zhège tài guì le", ko: "이건 너무 비싸요." } },
        { zh: "便宜", pinyin: "piányi", ko: "싸다", pos: "형용사", ex: { zh: "这件衣服很便宜。", pinyin: "zhè jiàn yīfu hěn piányi", ko: "이 옷은 싸요." } },
        { zh: "衣服", pinyin: "yīfu", ko: "옷", pos: "명사", hanja: "의복(衣服) — 한자 그대로.", ex: { zh: "我想买衣服。", pinyin: "wǒ xiǎng mǎi yīfu", ko: "저는 옷을 사고 싶어요." } },
        { zh: "东西", pinyin: "dōngxi", ko: "물건", pos: "명사", hanja: "동서(東西) — 직역하면 '동쪽 서쪽'이지만 뜻은 '물건'!", ex: { zh: "我去商店买东西。", pinyin: "wǒ qù shāngdiàn mǎi dōngxi", ko: "저는 가게에 물건을 사러 가요." } },
      ],
    },
    {
      name: "동작과 표현",
      words: [
        { zh: "起床", pinyin: "qǐchuáng", ko: "일어나다, 기상하다", pos: "동사", hanja: "기상(起床) — '起'는 일어날 기, '床'은 침상.", ex: { zh: "我七点起床。", pinyin: "wǒ qī diǎn qǐchuáng", ko: "저는 7시에 일어나요." } },
        { zh: "运动", pinyin: "yùndòng", ko: "운동하다", pos: "동사", hanja: "운동(運動) — 한자 그대로.", ex: { zh: "我每天运动。", pinyin: "wǒ měi tiān yùndòng", ko: "저는 매일 운동해요." } },
        { zh: "跑步", pinyin: "pǎobù", ko: "달리다, 조깅하다", pos: "동사", hanja: "포보(跑步) — '步'는 걸음 보.", ex: { zh: "我早上去跑步。", pinyin: "wǒ zǎoshang qù pǎobù", ko: "저는 아침에 달리기 하러 가요." } },
        { zh: "踢足球", pinyin: "tī zúqiú", ko: "축구를 하다", pos: "동사", hanja: "족구(足球) — '足'은 발 족, '球'는 공 구. 발로 차는 공.", ex: { zh: "他喜欢踢足球。", pinyin: "tā xǐhuan tī zúqiú", ko: "그는 축구를 좋아해요." } },
        { zh: "游泳", pinyin: "yóuyǒng", ko: "수영하다", pos: "동사", hanja: "유영(游泳) — '游'는 헤엄칠 유, '泳'은 헤엄칠 영.", ex: { zh: "他会游泳。", pinyin: "tā huì yóuyǒng", ko: "그는 수영할 줄 알아요." } },
        { zh: "打电话", pinyin: "dǎ diànhuà", ko: "전화를 걸다", pos: "동사", hanja: "전화(電話) — '打'는 칠 타. '전화를 걸다'를 打电话라고 해요.", ex: { zh: "我给你打电话。", pinyin: "wǒ gěi nǐ dǎ diànhuà", ko: "제가 전화할게요." } },
        { zh: "玩", pinyin: "wán", ko: "놀다", pos: "동사", ex: { zh: "孩子们在玩。", pinyin: "háizimen zài wán", ko: "아이들이 놀고 있어요." } },
        { zh: "唱歌", pinyin: "chànggē", ko: "노래하다", pos: "동사", hanja: "창가(唱歌) — '唱'은 부를 창, '歌'는 노래 가.", ex: { zh: "她唱歌很好。", pinyin: "tā chànggē hěn hǎo", ko: "그녀는 노래를 잘해요." } },
        { zh: "旅游", pinyin: "lǚyóu", ko: "여행하다", pos: "동사", hanja: "여유(旅遊) — '旅'는 나그네 려, '遊'는 놀 유.", ex: { zh: "我想去中国旅游。", pinyin: "wǒ xiǎng qù Zhōngguó lǚyóu", ko: "저는 중국에 여행 가고 싶어요." } },
        { zh: "送", pinyin: "sòng", ko: "보내다, 선물하다, 배웅하다", pos: "동사", hanja: "송(送) — '보낼 송'.", ex: { zh: "我送你回家。", pinyin: "wǒ sòng nǐ huí jiā", ko: "제가 집까지 데려다줄게요." } },
        { zh: "找", pinyin: "zhǎo", ko: "찾다", pos: "동사", ex: { zh: "我在找我的手机。", pinyin: "wǒ zài zhǎo wǒ de shǒujī", ko: "저는 제 휴대폰을 찾고 있어요." } },
        { zh: "帮助", pinyin: "bāngzhù", ko: "돕다, 도움", pos: "동사", hanja: "방조(幫助) — '助'는 도울 조.", ex: { zh: "谢谢你的帮助。", pinyin: "xièxie nǐ de bāngzhù", ko: "도와줘서 고마워요." } },
        { zh: "知道", pinyin: "zhīdào", ko: "알다", pos: "동사", hanja: "지도(知道) — '知'는 알 지, '道'는 길 도(이치).", ex: { zh: "我不知道。", pinyin: "wǒ bù zhīdào", ko: "저는 몰라요." } },
        { zh: "觉得", pinyin: "juéde", ko: "~라고 생각하다, 느끼다", pos: "동사", ex: { zh: "我觉得很好。", pinyin: "wǒ juéde hěn hǎo", ko: "저는 좋다고 생각해요." } },
        { zh: "希望", pinyin: "xīwàng", ko: "바라다, 희망하다", pos: "동사", hanja: "희망(希望) — 한자 그대로.", ex: { zh: "希望你来。", pinyin: "xīwàng nǐ lái", ko: "당신이 오기를 바라요." } },
        { zh: "介绍", pinyin: "jièshào", ko: "소개하다", pos: "동사", hanja: "개소(介紹) — '介'는 끼일 개, '紹'는 이을 소.", ex: { zh: "我来介绍一下。", pinyin: "wǒ lái jièshào yíxià", ko: "제가 소개할게요." } },
        { zh: "欢迎", pinyin: "huānyíng", ko: "환영하다", pos: "동사", hanja: "환영(歡迎) — 한자 그대로.", ex: { zh: "欢迎你来我家。", pinyin: "huānyíng nǐ lái wǒ jiā", ko: "우리 집에 온 것을 환영해요." } },
        { zh: "等", pinyin: "děng", ko: "기다리다", pos: "동사", hanja: "등(等) — '무리 등'이지만 중국어에선 '기다리다'.", ex: { zh: "我在门口等你。", pinyin: "wǒ zài ménkǒu děng nǐ", ko: "제가 입구에서 기다릴게요." } },
        { zh: "准备", pinyin: "zhǔnbèi", ko: "준비하다", pos: "동사", hanja: "준비(準備) — 한자 그대로.", ex: { zh: "我在准备考试。", pinyin: "wǒ zài zhǔnbèi kǎoshì", ko: "저는 시험을 준비하고 있어요." } },
        { zh: "开始", pinyin: "kāishǐ", ko: "시작하다", pos: "동사", hanja: "개시(開始) — 한자 그대로.", ex: { zh: "电影开始了。", pinyin: "diànyǐng kāishǐ le", ko: "영화가 시작했어요." } },
        { zh: "电影", pinyin: "diànyǐng", ko: "영화", pos: "명사", hanja: "전영(電影) — '電'은 번개 전, '影'은 그림자 영. '전기로 비추는 그림자'.", ex: { zh: "你看过这个电影吗？", pinyin: "nǐ kàn guo zhège diànyǐng ma", ko: "이 영화 본 적 있어요?" } },
        { zh: "电话", pinyin: "diànhuà", ko: "전화", pos: "명사", hanja: "전화(電話) — 한자 그대로.", ex: { zh: "他给我打电话。", pinyin: "tā gěi wǒ dǎ diànhuà", ko: "그가 저에게 전화했어요." } },
        { zh: "礼物", pinyin: "lǐwù", ko: "선물", pos: "명사", hanja: "예물(禮物) — 한자는 '예물'이지만 뜻은 '선물'. 한국어 '예물'보다 넓어요.", ex: { zh: "他给我买了礼物。", pinyin: "tā gěi wǒ mǎi le lǐwù", ko: "그가 저에게 선물을 사 줬어요." } },
        { zh: "兴趣", pinyin: "xìngqù", ko: "흥미, 관심", pos: "명사", hanja: "흥취(興趣) — '興'은 흥할 흥, '趣'는 뜻 취. '感兴趣'로 '관심이 있다'를 표현해요.", ex: { zh: "我对中国文化很感兴趣。", pinyin: "wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù", ko: "저는 중국 문화에 관심이 많아요." } },
        { zh: "回答", pinyin: "huídá", ko: "대답하다", pos: "동사", hanja: "회답(回答) — 한자 그대로.", ex: { zh: "请回答这个问题。", pinyin: "qǐng huídá zhège wèntí", ko: "이 질문에 답해 주세요." } },
      ],
    },
    {
      name: "형용사와 부사",
      words: [
        { zh: "新", pinyin: "xīn", ko: "새롭다", pos: "형용사", hanja: "신(新).", ex: { zh: "这是我的新手机。", pinyin: "zhè shì wǒ de xīn shǒujī", ko: "이건 제 새 휴대폰이에요." } },
        { zh: "快", pinyin: "kuài", ko: "빠르다", pos: "형용사", hanja: "쾌(快) — '쾌속'의 쾌.", ex: { zh: "他跑得很快。", pinyin: "tā pǎo de hěn kuài", ko: "그는 빨리 달려요." } },
        { zh: "慢", pinyin: "màn", ko: "느리다", pos: "형용사", hanja: "만(慢) — '거만'의 만, '느리다'.", ex: { zh: "请慢一点。", pinyin: "qǐng màn yìdiǎn", ko: "천천히 하세요." } },
        { zh: "忙", pinyin: "máng", ko: "바쁘다", pos: "형용사", hanja: "망(忙) — '바쁠 망'.", ex: { zh: "我今天很忙。", pinyin: "wǒ jīntiān hěn máng", ko: "저는 오늘 바빠요." } },
        { zh: "累", pinyin: "lèi", ko: "피곤하다", pos: "형용사", ex: { zh: "我很累。", pinyin: "wǒ hěn lèi", ko: "저는 피곤해요." } },
        { zh: "久", pinyin: "jiǔ", ko: "(시간이) 오래다", pos: "형용사", hanja: "구(久) — '오랠 구'.", ex: { zh: "我等了很久。", pinyin: "wǒ děng le hěn jiǔ", ko: "저는 오래 기다렸어요." } },
        { zh: "高", pinyin: "gāo", ko: "높다, 키가 크다", pos: "형용사", hanja: "고(高).", ex: { zh: "他个子很高。", pinyin: "tā gèzi hěn gāo", ko: "그는 키가 커요." } },
        { zh: "长", pinyin: "cháng", ko: "길다", pos: "형용사", hanja: "장(長).", ex: { zh: "她的头发很长。", pinyin: "tā de tóufa hěn cháng", ko: "그녀의 머리는 길어요." } },
        { zh: "白", pinyin: "bái", ko: "희다", pos: "형용사", hanja: "백(白).", ex: { zh: "她穿白衣服。", pinyin: "tā chuān bái yīfu", ko: "그녀는 흰 옷을 입어요." } },
        { zh: "黑", pinyin: "hēi", ko: "검다", pos: "형용사", hanja: "흑(黑).", ex: { zh: "外面很黑。", pinyin: "wàimiàn hěn hēi", ko: "밖이 어두워요." } },
        { zh: "红", pinyin: "hóng", ko: "붉다", pos: "형용사", hanja: "홍(紅) — '홍색'의 홍.", ex: { zh: "我喜欢红色。", pinyin: "wǒ xǐhuan hóngsè", ko: "저는 빨간색을 좋아해요." } },
        { zh: "对", pinyin: "duì", ko: "맞다, 옳다", pos: "형용사", hanja: "대(對) — '대답'의 대. '맞다'.", ex: { zh: "你说得对。", pinyin: "nǐ shuō de duì", ko: "당신 말이 맞아요." } },
        { zh: "真", pinyin: "zhēn", ko: "정말, 진짜", pos: "부사", hanja: "진(眞) — '참 진'.", ex: { zh: "这个菜真好吃。", pinyin: "zhège cài zhēn hǎochī", ko: "이 요리 정말 맛있어요." } },
        { zh: "最", pinyin: "zuì", ko: "가장, 제일", pos: "부사", hanja: "최(最) — '최고'의 최.", ex: { zh: "我最喜欢看电影。", pinyin: "wǒ zuì xǐhuan kàn diànyǐng", ko: "저는 영화 보는 걸 제일 좋아해요." } },
        { zh: "还", pinyin: "hái", ko: "아직, 더, 또", pos: "부사", ex: { zh: "他还没来。", pinyin: "tā hái méi lái", ko: "그는 아직 안 왔어요." } },
        { zh: "已经", pinyin: "yǐjīng", ko: "이미, 벌써", pos: "부사", hanja: "이경(已經) — '已'는 이미 이.", ex: { zh: "我已经吃了。", pinyin: "wǒ yǐjīng chī le", ko: "저는 이미 먹었어요." } },
        { zh: "一起", pinyin: "yìqǐ", ko: "함께, 같이", pos: "부사", hanja: "일기(一起) — '한데 일어나다', 즉 함께.", ex: { zh: "我们一起去吧。", pinyin: "wǒmen yìqǐ qù ba", ko: "우리 같이 가요." } },
      ],
    },
    {
      name: "장소와 교통",
      words: [
        { zh: "公司", pinyin: "gōngsī", ko: "회사", pos: "명사", hanja: "공사(公司) — '公'은 공평할 공. 한국 '공사(公社)'와 비슷하나 뜻은 '회사'.", ex: { zh: "我在公司工作。", pinyin: "wǒ zài gōngsī gōngzuò", ko: "저는 회사에서 일해요." } },
        { zh: "教室", pinyin: "jiàoshì", ko: "교실", pos: "명사", hanja: "교실(敎室) — 한자 그대로.", ex: { zh: "教室里有很多学生。", pinyin: "jiàoshì lǐ yǒu hěn duō xuésheng", ko: "교실에 학생이 많아요." } },
        { zh: "房间", pinyin: "fángjiān", ko: "방", pos: "명사", hanja: "방간(房間) — '房'은 방 방, '間'은 사이 간.", ex: { zh: "我的房间很干净。", pinyin: "wǒ de fángjiān hěn gānjìng", ko: "제 방은 깨끗해요." } },
        { zh: "机场", pinyin: "jīchǎng", ko: "공항", pos: "명사", hanja: "기장(機場) — '機'는 기계 기(비행기), '場'은 마당 장.", ex: { zh: "我去机场接朋友。", pinyin: "wǒ qù jīchǎng jiē péngyou", ko: "저는 친구를 마중하러 공항에 가요." } },
        { zh: "火车站", pinyin: "huǒchēzhàn", ko: "기차역", pos: "명사", hanja: "화차참(火車站) — '火車'는 기차, '站'은 역.", ex: { zh: "火车站离这儿很近。", pinyin: "huǒchēzhàn lí zhèr hěn jìn", ko: "기차역은 여기서 가까워요." } },
        { zh: "路", pinyin: "lù", ko: "길", pos: "명사", hanja: "로(路) — '길 로'.", ex: { zh: "这条路很长。", pinyin: "zhè tiáo lù hěn cháng", ko: "이 길은 길어요." } },
        { zh: "公共汽车", pinyin: "gōnggòng qìchē", ko: "버스", pos: "명사", hanja: "공공기차(公共汽車) — '公共'은 공공, '汽車'는 차. '공공의 차'.", ex: { zh: "我坐公共汽车去学校。", pinyin: "wǒ zuò gōnggòng qìchē qù xuéxiào", ko: "저는 버스를 타고 학교에 가요." } },
        { zh: "船", pinyin: "chuán", ko: "배", pos: "명사", hanja: "선(船) — '배 선'.", ex: { zh: "我们坐船去。", pinyin: "wǒmen zuò chuán qù", ko: "우리 배를 타고 가요." } },
        { zh: "走", pinyin: "zǒu", ko: "걷다, 가다", pos: "동사", hanja: "주(走) — '달릴 주'지만 중국어에선 '걷다·가다'.", ex: { zh: "我们走着去吧。", pinyin: "wǒmen zǒuzhe qù ba", ko: "우리 걸어서 가요." } },
        { zh: "到", pinyin: "dào", ko: "도착하다, ~까지", pos: "동사", hanja: "도(到) — '이를 도'.", ex: { zh: "火车到了。", pinyin: "huǒchē dào le", ko: "기차가 도착했어요." } },
        { zh: "进", pinyin: "jìn", ko: "들어가다", pos: "동사", hanja: "진(進) — '나아갈 진'.", ex: { zh: "请进。", pinyin: "qǐng jìn", ko: "들어오세요." } },
        { zh: "出", pinyin: "chū", ko: "나가다, 나오다", pos: "동사", hanja: "출(出) — '날 출'.", ex: { zh: "他出去了。", pinyin: "tā chūqu le", ko: "그는 나갔어요." } },
        { zh: "离", pinyin: "lí", ko: "~에서, ~로부터 (거리)", pos: "개사", hanja: "리(離) — '떠날 리'. 두 지점 사이 거리를 말해요.", ex: { zh: "我家离公司很近。", pinyin: "wǒ jiā lí gōngsī hěn jìn", ko: "우리 집은 회사에서 가까워요." } },
        { zh: "从", pinyin: "cóng", ko: "~부터, ~에서", pos: "개사", hanja: "종(從) — '좇을 종'. 출발점을 말해요.", ex: { zh: "我从北京来。", pinyin: "wǒ cóng Běijīng lái", ko: "저는 베이징에서 왔어요." } },
        { zh: "近", pinyin: "jìn", ko: "가깝다", pos: "형용사", hanja: "근(近) — '가까울 근'.", ex: { zh: "学校离我家很近。", pinyin: "xuéxiào lí wǒ jiā hěn jìn", ko: "학교는 우리 집에서 가까워요." } },
        { zh: "远", pinyin: "yuǎn", ko: "멀다", pos: "형용사", hanja: "원(遠) — '멀 원'.", ex: { zh: "机场离这儿很远。", pinyin: "jīchǎng lí zhèr hěn yuǎn", ko: "공항은 여기서 멀어요." } },
      ],
    },
  ],
}

export default themes;
