/**
 * H2 (HSK 2급) HSK 3.0 표준 보강 어휘 — 공식 어휘표(drkameleon/complete-hsk-vocabulary, MIT)에서
 * 기존에 없던 333개를 채웠어요. 한자·병음·품사는 표준 데이터, 뜻·예문은 학습용으로 작성.
 */
const themes = {
  themes: [
    {
      name: "HSK2 3.0 보강",
      icon: "🟩",
      words: [
        { zh: "爱人", pinyin: "àiren", ko: "애인, 배우자", pos: "명사", ex: { zh: "他的爱人是医生。", pinyin: "Tā de àiren shì yīshēng.", ko: "그의 배우자는 의사예요." } },
        { zh: "白色", pinyin: "báisè", ko: "흰색", pos: "명사", ex: { zh: "她喜欢穿白色的衣服。", pinyin: "Tā xǐhuan chuān báisè de yīfu.", ko: "그녀는 흰색 옷을 입는 것을 좋아해요." } },
        { zh: "班长", pinyin: "bānzhǎng", ko: "반장", pos: "명사", ex: { zh: "他是我们班的班长。", pinyin: "Tā shì wǒmen bān de bānzhǎng.", ko: "그는 우리 반의 반장이에요." } },
        { zh: "办", pinyin: "bàn", ko: "처리하다, 하다", pos: "동사", ex: { zh: "这件事我来办。", pinyin: "Zhè jiàn shì wǒ lái bàn.", ko: "이 일은 내가 처리하겠어요." } },
        { zh: "半夜", pinyin: "bànyè", ko: "한밤중", pos: "명사", ex: { zh: "他半夜才回家。", pinyin: "Tā bànyè cái huí jiā.", ko: "그는 한밤중이 되어서야 집에 돌아왔어요." } },
        { zh: "比如说", pinyin: "bǐrúshuō", ko: "예를 들면", pos: "동사", ex: { zh: "比如说,你可以先学中文。", pinyin: "Bǐrúshuō, nǐ kěyǐ xiān xué Zhōngwén.", ko: "예를 들면, 너는 먼저 중국어를 배울 수 있어요." } },
        { zh: "笔", pinyin: "bǐ", ko: "펜, 붓", pos: "양사", ex: { zh: "我买了一支笔。", pinyin: "Wǒ mǎi le yī zhī bǐ.", ko: "나는 펜 한 자루를 샀어요." } },
        { zh: "笔记", pinyin: "bǐjì", ko: "필기, 노트", pos: "명사", ex: { zh: "我在课堂上做笔记。", pinyin: "Wǒ zài kètáng shàng zuò bǐjì.", ko: "나는 수업 시간에 필기를 해요." } },
        { zh: "边", pinyin: "biān", ko: "가장자리, 옆", pos: "부사", ex: { zh: "他站在河边。", pinyin: "Tā zhàn zài hé biān.", ko: "그는 강가에 서 있어요." } },
        { zh: "变", pinyin: "biàn", ko: "변하다, 바뀌다", pos: "동사", ex: { zh: "天气突然变冷了。", pinyin: "Tiānqì tūrán biàn lěng le.", ko: "날씨가 갑자기 추워졌어요." } },
        { zh: "变成", pinyin: "biànchéng", ko: "~로 변하다, ~이 되다", pos: "동사", ex: { zh: "蝌蚪会变成青蛙。", pinyin: "Kēdǒu huì biànchéng qīngwā.", ko: "올챙이는 개구리로 변해요." } },
        { zh: "表", pinyin: "biǎo", ko: "겉면, 표(양식)", pos: "명사", ex: { zh: "请填写这张表。", pinyin: "Qǐng tiánxiě zhè zhāng biǎo.", ko: "이 표를 작성해 주세요." } },
        { zh: "不错", pinyin: "bùcuò", ko: "괜찮다, 좋다", pos: "형용사", ex: { zh: "这部电影很不错。", pinyin: "Zhè bù diànyǐng hěn bùcuò.", ko: "이 영화는 꽤 괜찮아요." } },
        { zh: "不够", pinyin: "bùgòu", ko: "부족하다, 모자라다", pos: "형용사", ex: { zh: "时间不够了。", pinyin: "Shíjiān bùgòu le.", ko: "시간이 부족해요." } },
        { zh: "不久", pinyin: "bùjiǔ", ko: "머지않아, 곧", pos: "수사", ex: { zh: "他不久就会回来。", pinyin: "Tā bùjiǔ jiù huì huílái.", ko: "그는 머지않아 돌아올 거예요." } },
        { zh: "不满", pinyin: "bùmǎn", ko: "불만스럽다, 불만족하다", pos: "형용사", ex: { zh: "大家对这个结果很不满。", pinyin: "Dàjiā duì zhège jiéguǒ hěn bùmǎn.", ko: "모두가 이 결과에 불만이 많아요." } },
        { zh: "不少", pinyin: "bùshǎo", ko: "적지 않다, 많다", pos: "수사", ex: { zh: "公园里有不少游客。", pinyin: "Gōngyuán lǐ yǒu bùshǎo yóukè.", ko: "공원에는 적지 않은 관광객이 있어요." } },
        { zh: "不太", pinyin: "bùtài", ko: "그다지 ~하지 않다, 별로", pos: "부사", ex: { zh: "我不太喜欢辣的食物。", pinyin: "Wǒ bù tài xǐhuan là de shíwù.", ko: "나는 매운 음식을 그다지 좋아하지 않아요." } },
        { zh: "不同", pinyin: "bùtóng", ko: "다르다, 같지 않다", pos: "형용사", ex: { zh: "每个人的想法都不同。", pinyin: "Měi gè rén de xiǎngfǎ dōu bùtóng.", ko: "사람마다 생각이 달라요." } },
        { zh: "不行", pinyin: "bùxíng", ko: "안 된다", pos: "형용사", ex: { zh: "你现在走不行。", pinyin: "Nǐ xiànzài zǒu bùxíng.", ko: "너는 지금 가면 안 돼요." } },
        { zh: "不要", pinyin: "bùyào", ko: "~하지 마라", pos: "부사", ex: { zh: "不要在这里抽烟。", pinyin: "Bùyào zài zhèlǐ chōuyān.", ko: "여기서 담배 피우지 마라." } },
        { zh: "不一定", pinyin: "bùyīdìng", ko: "반드시 ~한 것은 아니다", pos: "부사", ex: { zh: "他不一定会来。", pinyin: "Tā bù yīdìng huì lái.", ko: "그가 꼭 온다고는 할 수 없어요." } },
        { zh: "不一会儿", pinyin: "bù yīhuǐr", ko: "얼마 지나지 않아, 곧", pos: "부사", ex: { zh: "不一会儿,雨就停了。", pinyin: "Bù yīhuǐr, yǔ jiù tíng le.", ko: "얼마 지나지 않아 비가 멈췄어요." } },
        { zh: "草地", pinyin: "cǎodì", ko: "잔디밭, 초원", pos: "명사", ex: { zh: "孩子们在草地上玩耍。", pinyin: "Háizimen zài cǎodì shàng wánshuǎ.", ko: "아이들이 잔디밭에서 놀아요." } },
        { zh: "查", pinyin: "chá", ko: "조사하다, 찾다", pos: "동사", ex: { zh: "我要查一下这个词的意思。", pinyin: "Wǒ yào chá yíxià zhège cí de yìsi.", ko: "나는 이 단어의 뜻을 좀 찾아봐야 해요." } },
        { zh: "常见", pinyin: "chángjiàn", ko: "흔하다, 자주 보이는", pos: "형용사", ex: { zh: "这是一种常见的病。", pinyin: "Zhè shì yī zhǒng chángjiàn de bìng.", ko: "이것은 흔한 병이에요." } },
        { zh: "常用", pinyin: "chángyòng", ko: "자주 쓰이는, 상용의", pos: "형용사", ex: { zh: "这是一个常用的词语。", pinyin: "Zhè shì yī gè chángyòng de cíyǔ.", ko: "이것은 자주 쓰이는 단어예요." } },
        { zh: "车辆", pinyin: "chēliàng", ko: "차량", pos: "명사", ex: { zh: "路上车辆很多。", pinyin: "Lù shàng chēliàng hěn duō.", ko: "길에 차량이 많아요." } },
        { zh: "称", pinyin: "chèn", ko: "어울리다, 맞다", pos: "동사", ex: { zh: "这件衣服很称身。", pinyin: "Zhè jiàn yīfu hěn chènshēn.", ko: "이 옷은 몸에 잘 맞아요." } },
        { zh: "成", pinyin: "chéng", ko: "이루다, ~이 되다", pos: "동사", ex: { zh: "他的梦想终于成真了。", pinyin: "Tā de mèngxiǎng zhōngyú chéng zhēn le.", ko: "그의 꿈이 마침내 이루어졌어요." } },
        { zh: "出国", pinyin: "chūguó", ko: "출국하다", pos: "동사", ex: { zh: "他打算明年出国留学。", pinyin: "Tā dǎsuàn míngnián chūguó liúxué.", ko: "그는 내년에 유학을 위해 출국할 계획이에요." } },
        { zh: "出门", pinyin: "chūmén", ko: "외출하다", pos: "동사", ex: { zh: "出门前记得关灯。", pinyin: "Chūmén qián jìde guān dēng.", ko: "외출하기 전에 불 끄는 것을 잊지 마라." } },
        { zh: "出院", pinyin: "chūyuàn", ko: "퇴원하다", pos: "동사", ex: { zh: "他明天就可以出院了。", pinyin: "Tā míngtiān jiù kěyǐ chūyuàn le.", ko: "그는 내일이면 퇴원할 수 있어요." } },
        { zh: "出租", pinyin: "chūzū", ko: "임대하다, 세놓다", pos: "동사", ex: { zh: "这套房子正在出租。", pinyin: "Zhè tào fángzi zhèngzài chūzū.", ko: "이 집은 지금 세를 놓고 있어요." } },
        { zh: "春节", pinyin: "Chūnjié", ko: "춘절, 음력설", pos: "명사", ex: { zh: "春节是中国最重要的节日。", pinyin: "Chūnjié shì Zhōngguó zuì zhòngyào de jiérì.", ko: "춘절은 중국에서 가장 중요한 명절이에요." } },
        { zh: "春天", pinyin: "chūntiān", ko: "봄", pos: "명사", ex: { zh: "春天来了,花都开了。", pinyin: "Chūntiān lái le, huā dōu kāi le.", ko: "봄이 오니 꽃이 다 피었어요." } },
        { zh: "词", pinyin: "cí", ko: "단어, 말", pos: "명사", ex: { zh: "这个词是什么意思?", pinyin: "Zhège cí shì shénme yìsi?", ko: "이 단어는 무슨 뜻이야?" } },
        { zh: "从小", pinyin: "cóngxiǎo", ko: "어릴 때부터", pos: "부사", ex: { zh: "他从小就喜欢音乐。", pinyin: "Tā cóngxiǎo jiù xǐhuan yīnyuè.", ko: "그는 어릴 때부터 음악을 좋아했어요." } },
        { zh: "大部分", pinyin: "dàbùfen", ko: "대부분", pos: "수사", ex: { zh: "大部分学生都同意这个计划。", pinyin: "Dàbùfen xuésheng dōu tóngyì zhège jìhuà.", ko: "대부분의 학생들이 이 계획에 동의해요." } },
        { zh: "大大", pinyin: "dàdà", ko: "크게, 대대적으로", pos: "부사", ex: { zh: "这项技术大大提高了效率。", pinyin: "Zhè xiàng jìshù dàdà tígāo le xiàolǜ.", ko: "이 기술은 효율을 크게 향상시켰어요." } },
        { zh: "大多数", pinyin: "dàduōshù", ko: "대다수, 대부분", pos: "수사", ex: { zh: "大多数人都同意这个计划。", pinyin: "Dà duō shù rén dōu tóng yì zhè ge jì huà.", ko: "대다수의 사람들이 이 계획에 동의해요." } },
        { zh: "大海", pinyin: "dàhǎi", ko: "바다, 대해", pos: "명사", ex: { zh: "他喜欢站在大海边看日出。", pinyin: "Tā xǐ huan zhàn zài dà hǎi biān kàn rì chū.", ko: "그는 바닷가에 서서 일출 보는 것을 좋아해요." } },
        { zh: "大量", pinyin: "dàliàng", ko: "대량, 다량", pos: "수사", ex: { zh: "工厂每天生产大量产品。", pinyin: "Gōng chǎng měi tiān shēng chǎn dà liàng chǎn pǐn.", ko: "공장은 매일 대량의 제품을 생산해요." } },
        { zh: "大门", pinyin: "Dàmén", ko: "대문, 정문", pos: "명사", ex: { zh: "请从大门进来。", pinyin: "Qǐng cóng dà mén jìn lái.", ko: "정문으로 들어오세요." } },
        { zh: "大人", pinyin: "dàren", ko: "어른, 성인", pos: "명사", ex: { zh: "大人应该给孩子做榜样。", pinyin: "Dà ren yīng gāi gěi hái zi zuò bǎng yàng.", ko: "어른은 아이에게 모범을 보여야 해요." } },
        { zh: "大声", pinyin: "dàshēng", ko: "큰 소리로, 큰소리", pos: "부사", ex: { zh: "请不要大声说话。", pinyin: "Qǐng bú yào dà shēng shuō huà.", ko: "큰 소리로 말하지 마세요." } },
        { zh: "大小", pinyin: "dàxiǎo", ko: "크기, 대소", pos: "명사", ex: { zh: "这双鞋的大小正合适。", pinyin: "Zhè shuāng xié de dà xiǎo zhèng hé shì.", ko: "이 신발의 크기가 딱 맞아요." } },
        { zh: "大衣", pinyin: "dàyī", ko: "외투, 코트", pos: "명사", ex: { zh: "冬天她穿着一件红色大衣。", pinyin: "Dōng tiān tā chuān zhe yí jiàn hóng sè dà yī.", ko: "겨울에 그녀는 빨간 외투를 입고 있어요." } },
        { zh: "大自然", pinyin: "dàzìrán", ko: "대자연", pos: "명사", ex: { zh: "我们应该保护大自然。", pinyin: "Wǒ men yīng gāi bǎo hù dà zì rán.", ko: "우리는 대자연을 보호해야 해요." } },
        { zh: "但", pinyin: "dàn", ko: "그러나, 하지만", pos: "접속사", ex: { zh: "他很聪明,但不努力。", pinyin: "Tā hěn cōng ming, dàn bù nǔ lì.", ko: "그는 똑똑하지만 노력하지 않아요." } },
        { zh: "蛋", pinyin: "dàn", ko: "달걀, 알", pos: "명사", ex: { zh: "妈妈煮了两个鸡蛋。", pinyin: "Mā ma zhǔ le liǎng gè jī dàn.", ko: "엄마가 계란 두 개를 삶았어요." } },
        { zh: "道", pinyin: "dào", ko: "길, 도리, 이치", pos: "명사", ex: { zh: "这条道很窄。", pinyin: "Zhè tiáo dào hěn zhǎi.", ko: "이 길은 좁아요." } },
        { zh: "道路", pinyin: "dàolù", ko: "도로, 길", pos: "명사", ex: { zh: "这条道路正在维修。", pinyin: "Zhè tiáo dào lù zhèng zài wéi xiū.", ko: "이 도로는 보수 공사 중이에요." } },
        { zh: "地铁站", pinyin: "dìtiězhàn", ko: "지하철역", pos: "명사", ex: { zh: "地铁站就在前面。", pinyin: "Dì tiě zhàn jiù zài qián miàn.", ko: "지하철역이 바로 앞에 있어요." } },
        { zh: "的话", pinyin: "dehuà", ko: "~라면, ~한다면", pos: "조사", ex: { zh: "如果明天下雨的话,我们就不去了。", pinyin: "Rú guǒ míng tiān xià yǔ de huà, wǒ men jiù bú qù le.", ko: "만약 내일 비가 온다면 우리는 가지 않을 거예요." } },
        { zh: "得出", pinyin: "déchū", ko: "얻어내다, 도출하다", pos: "동사", ex: { zh: "我们得出了一个重要的结论。", pinyin: "Wǒ men dé chū le yí gè zhòng yào de jié lùn.", ko: "우리는 중요한 결론을 도출했어요." } },
        { zh: "等到", pinyin: "děngdào", ko: "~할 때까지 기다리다", pos: "동사", ex: { zh: "等到雨停了我们再出发。", pinyin: "Děng dào yǔ tíng le wǒ men zài chū fā.", ko: "비가 그칠 때까지 기다렸다가 다시 출발하자." } },
        { zh: "店", pinyin: "diàn", ko: "가게, 상점", pos: "명사", ex: { zh: "这家店的东西很便宜。", pinyin: "Zhè jiā diàn de dōng xi hěn pián yi.", ko: "이 가게 물건은 매우 싸요." } },
        { zh: "东北", pinyin: "Dōngběi", ko: "동북, 중국 동북 지방(만주)", pos: "명사", ex: { zh: "他的老家在东北。", pinyin: "Tā de lǎo jiā zài dōng běi.", ko: "그의 고향은 동북 지방(만주)이에요." } },
        { zh: "东方", pinyin: "Dōngfāng", ko: "동방, 동양", pos: "명사", ex: { zh: "太阳从东方升起。", pinyin: "Tài yáng cóng dōng fāng shēng qǐ.", ko: "태양은 동쪽에서 떠올라요." } },
        { zh: "东南", pinyin: "dōngnán", ko: "동남쪽", pos: "명사", ex: { zh: "这个城市在中国的东南部。", pinyin: "Zhè ge chéng shì zài Zhōng guó de dōng nán bù.", ko: "이 도시는 중국의 동남부에 있어요." } },
        { zh: "冬天", pinyin: "dōngtiān", ko: "겨울", pos: "명사", ex: { zh: "冬天这里很冷。", pinyin: "Dōng tiān zhè lǐ hěn lěng.", ko: "겨울에 이곳은 매우 추워요." } },
        { zh: "懂得", pinyin: "dǒngde", ko: "이해하다, 알다", pos: "동사", ex: { zh: "他懂得如何照顾自己。", pinyin: "Tā dǒng de rú hé zhào gù zì jǐ.", ko: "그는 자신을 돌보는 법을 알아요." } },
        { zh: "动物园", pinyin: "dòngwùyuán", ko: "동물원", pos: "명사", ex: { zh: "周末我们去动物园吧。", pinyin: "Zhōu mò wǒ men qù dòng wù yuán ba.", ko: "주말에 우리 동물원에 가자." } },
        { zh: "读音", pinyin: "dúyīn", ko: "발음, 독음", pos: "명사", ex: { zh: "这个字的读音是什么?", pinyin: "Zhè ge zì de dú yīn shì shén me?", ko: "이 글자의 발음은 무엇입니까?" } },
        { zh: "度", pinyin: "dù", ko: "(시간을) 보내다, 지내다", pos: "동사", ex: { zh: "我们在海边度过了假期。", pinyin: "Wǒ men zài hǎi biān dù guò le jià qī.", ko: "우리는 바닷가에서 휴가를 보냈어요." } },
        { zh: "队", pinyin: "duì", ko: "팀, 대열", pos: "명사", ex: { zh: "我们队赢了比赛。", pinyin: "Wǒ men duì yíng le bǐ sài.", ko: "우리 팀이 경기에서 이겼어요." } },
        { zh: "队长", pinyin: "duìzhǎng", ko: "팀장, 대장", pos: "명사", ex: { zh: "他是我们班的队长。", pinyin: "Tā shì wǒ men bān de duì zhǎng.", ko: "그는 우리 반의 팀장이에요." } },
        { zh: "多久", pinyin: "duōjiǔ", ko: "얼마나 오래", pos: "대명사", ex: { zh: "你在北京住了多久?", pinyin: "Nǐ zài Běi jīng zhù le duō jiǔ?", ko: "당신은 베이징에서 얼마나 오래 살았습니까?" } },
        { zh: "多数", pinyin: "duōshù", ko: "다수, 대부분", pos: "수사", ex: { zh: "多数学生都喜欢这门课。", pinyin: "Duō shù xué sheng dōu xǐ huan zhè mén kè.", ko: "대부분의 학생들이 이 수업을 좋아해요." } },
        { zh: "多云", pinyin: "duōyún", ko: "구름 많음, 흐림", pos: "명사", ex: { zh: "今天多云,没有太阳。", pinyin: "Jīn tiān duō yún, méi yǒu tài yáng.", ko: "오늘은 구름이 많고 해가 없어요." } },
        { zh: "方便面", pinyin: "fāngbiànmiàn", ko: "라면, 인스턴트 라면", pos: "명사", ex: { zh: "我晚上煮了一包方便面。", pinyin: "Wǒ wǎn shang zhǔ le yì bāo fāng biàn miàn.", ko: "나는 저녁에 라면 한 봉지를 끓였어요." } },
        { zh: "放下", pinyin: "fàngxià", ko: "내려놓다, 놓다", pos: "동사", ex: { zh: "请把包放下休息一会儿。", pinyin: "Qǐng bǎ bāo fàng xià xiū xi yí huìr.", ko: "가방을 내려놓고 잠시 쉬세요." } },
        { zh: "分开", pinyin: "fēnkāi", ko: "헤어지다, 분리하다", pos: "동사", ex: { zh: "他们两个人分开已经很久了。", pinyin: "Tā men liǎng gè rén fēn kāi yǐ jīng hěn jiǔ le.", ko: "그 두 사람은 헤어진 지 이미 오래되었어요." } },
        { zh: "分数", pinyin: "fēnshù", ko: "점수, 성적", pos: "명사", ex: { zh: "这次考试他的分数很高。", pinyin: "Zhè cì kǎo shì tā de fēn shù hěn gāo.", ko: "이번 시험에서 그의 점수는 매우 높아요." } },
        { zh: "封", pinyin: "fēng", ko: "통(편지를 세는 단위)", pos: "양사", ex: { zh: "我收到了一封信。", pinyin: "Wǒ shōu dào le yì fēng xìn.", ko: "나는 편지 한 통을 받았어요." } },
        { zh: "服务", pinyin: "fúwù", ko: "서비스하다, 봉사하다", pos: "동사", ex: { zh: "他在银行工作,为顾客服务。", pinyin: "Tā zài yín háng gōng zuò, wèi gù kè fú wù.", ko: "그는 은행에서 일하며 고객을 위해 서비스해요." } },
        { zh: "该", pinyin: "gāi", ko: "~해야 한다, ~일 것이다", pos: "동사", ex: { zh: "我们该出发了。", pinyin: "Wǒ men gāi chū fā le.", ko: "우리는 출발해야 해요." } },
        { zh: "改", pinyin: "gǎi", ko: "고치다, 바꾸다", pos: "동사", ex: { zh: "他改了一下计划。", pinyin: "Tā gǎi le yí xià jì huà.", ko: "그는 계획을 조금 수정했어요." } },
        { zh: "感到", pinyin: "gǎndào", ko: "느끼다", pos: "동사", ex: { zh: "听到这个消息,我感到很高兴。", pinyin: "Tīng dào zhè ge xiāo xi, wǒ gǎn dào hěn gāo xìng.", ko: "이 소식을 듣고 나는 매우 기뻤어요." } },
        { zh: "刚", pinyin: "gāng", ko: "방금, 막", pos: "부사", ex: { zh: "我刚到家。", pinyin: "Wǒ gāng dào jiā.", ko: "나는 방금 집에 도착했어요." } },
        { zh: "高中", pinyin: "gāozhōng", ko: "고등학교", pos: "명사", ex: { zh: "他在高中学习很努力。", pinyin: "Tā zài gāo zhōng xué xí hěn nǔ lì.", ko: "그는 고등학교에서 열심히 공부해요." } },
        { zh: "公交车", pinyin: "gōngjiāochē", ko: "버스, 대중교통버스", pos: "명사", ex: { zh: "我每天坐公交车上班。", pinyin: "Wǒ měi tiān zuò gōng jiāo chē shàng bān.", ko: "나는 매일 버스를 타고 출근해요." } },
        { zh: "公路", pinyin: "gōnglù", ko: "도로, 고속도로", pos: "명사", ex: { zh: "这条公路很长。", pinyin: "Zhè tiáo gōng lù hěn cháng.", ko: "이 도로는 매우 길어요." } },
        { zh: "关机", pinyin: "guānjī", ko: "(기계를) 끄다", pos: "동사", ex: { zh: "请把手机关机。", pinyin: "Qǐng bǎ shǒu jī guān jī.", ko: "휴대폰을 꺼 주세요." } },
        { zh: "过来", pinyin: "guòlái", ko: "건너오다, 다가오다", pos: "동사", ex: { zh: "你快过来看看。", pinyin: "Nǐ kuài guò lái kàn kan.", ko: "빨리 이리 와서 봐봐." } },
        { zh: "过年", pinyin: "guònián", ko: "새해를 맞다, 설을 쇠다", pos: "동사", ex: { zh: "我们全家一起过年。", pinyin: "Wǒ men quán jiā yì qǐ guò nián.", ko: "우리 가족은 함께 설을 쇠어요." } },
        { zh: "海", pinyin: "hǎi", ko: "바다", pos: "명사", ex: { zh: "海很蓝。", pinyin: "Hǎi hěn lán.", ko: "바다가 파래요." } },
        { zh: "海边", pinyin: "hǎibiān", ko: "바닷가, 해변", pos: "명사", ex: { zh: "我们去海边玩。", pinyin: "Wǒ men qù hǎi biān wán.", ko: "우리는 해변으로 놀러 가요." } },
        { zh: "好多", pinyin: "hǎoduō", ko: "많은, 매우 많이", pos: "수사", ex: { zh: "他买了好多书。", pinyin: "Tā mǎi le hǎo duō shū.", ko: "그는 많은 책을 샀어요." } },
        { zh: "好久", pinyin: "hǎojiǔ", ko: "오랫동안", pos: "수사", ex: { zh: "好久不见。", pinyin: "Hǎo jiǔ bú jiàn.", ko: "오랜만이에요." } },
        { zh: "好人", pinyin: "hǎorén", ko: "좋은 사람", pos: "명사", ex: { zh: "他是个好人。", pinyin: "Tā shì gè hǎo rén.", ko: "그는 좋은 사람이에요." } },
        { zh: "好事", pinyin: "hǎoshì", ko: "좋은 일", pos: "명사", ex: { zh: "帮助别人是好事。", pinyin: "Bāng zhù bié rén shì hǎo shì.", ko: "남을 돕는 것은 좋은 일이에요." } },
        { zh: "黑色", pinyin: "hēisè", ko: "검은색", pos: "명사", ex: { zh: "她穿着黑色的衣服。", pinyin: "Tā chuān zhe hēi sè de yī fu.", ko: "그녀는 검은색 옷을 입고 있어요." } },
        { zh: "红色", pinyin: "hóngsè", ko: "빨간색", pos: "명사", ex: { zh: "我喜欢红色。", pinyin: "Wǒ xǐ huan hóng sè.", ko: "나는 빨간색을 좋아해요." } },
        { zh: "湖", pinyin: "hú", ko: "호수", pos: "명사", ex: { zh: "这个湖很美。", pinyin: "Zhè ge hú hěn měi.", ko: "이 호수는 매우 아름다워요." } },
        { zh: "画儿", pinyin: "huàr", ko: "그림", pos: "명사", ex: { zh: "墙上挂着一幅画儿。", pinyin: "Qiáng shang guà zhe yì fú huàr.", ko: "벽에 그림 한 폭이 걸려 있어요." } },
        { zh: "画家", pinyin: "huàjiā", ko: "화가", pos: "명사", ex: { zh: "他想成为画家。", pinyin: "Tā xiǎng chéng wéi huà jiā.", ko: "그는 화가가 되고 싶어 해요." } },
        { zh: "坏处", pinyin: "huàichu", ko: "나쁜 점, 해로움", pos: "명사", ex: { zh: "抽烟对身体有坏处。", pinyin: "Chōu yān duì shēn tǐ yǒu huài chu.", ko: "흡연은 몸에 해로워요." } },
        { zh: "坏人", pinyin: "huàirén", ko: "나쁜 사람", pos: "명사", ex: { zh: "电影里的坏人被抓住了。", pinyin: "Diàn yǐng lǐ de huài rén bèi zhuā zhù le.", ko: "영화 속 나쁜 사람이 붙잡혔어요." } },
        { zh: "黄色", pinyin: "huángsè", ko: "노란색", pos: "명사", ex: { zh: "秋天的树叶是黄色的。", pinyin: "Qiū tiān de shù yè shì huáng sè de.", ko: "가을의 나뭇잎은 노란색이에요." } },
        { zh: "回国", pinyin: "huíguó", ko: "귀국하다", pos: "동사", ex: { zh: "他明年回国。", pinyin: "Tā míng nián huí guó.", ko: "그는 내년에 귀국해요." } },
        { zh: "或", pinyin: "huò", ko: "혹은, 또는", pos: "접속사", ex: { zh: "你可以坐火车或飞机去。", pinyin: "Nǐ kě yǐ zuò huǒ chē huò fēi jī qù.", ko: "너는 기차나 비행기로 갈 수 있어요." } },
        { zh: "鸡", pinyin: "jī", ko: "닭", pos: "명사", ex: { zh: "妈妈做了一只鸡。", pinyin: "Mā ma zuò le yì zhī jī.", ko: "엄마가 닭 한 마리를 요리했어요." } },
        { zh: "级", pinyin: "jí", ko: "급, 등급, 학년", pos: "양사", ex: { zh: "他是三年级学生。", pinyin: "Tā shì sān nián jí xué sheng.", ko: "그는 3학년 학생이에요." } },
        { zh: "急", pinyin: "jí", ko: "급하다, 조급하다", pos: "동사", ex: { zh: "他很急，一直看表。", pinyin: "Tā hěn jí, yì zhí kàn biǎo.", ko: "그는 조급해서 계속 시계를 봐요." } },
        { zh: "计算机", pinyin: "jìsuànjī", ko: "컴퓨터", pos: "명사", ex: { zh: "我用计算机工作。", pinyin: "Wǒ yòng jì suàn jī gōng zuò.", ko: "나는 컴퓨터로 일해요." } },
        { zh: "加", pinyin: "jiā", ko: "더하다, 추가하다", pos: "동사", ex: { zh: "三加二等于五。", pinyin: "Sān jiā èr děng yú wǔ.", ko: "3더하기 2는 5예요." } },
        { zh: "加油", pinyin: "jiāyóu", ko: "힘내다, 기름을 넣다", pos: "동사", ex: { zh: "大家一起加油！", pinyin: "Dà jiā yì qǐ jiā yóu!", ko: "다같이 힘내자!" } },
        { zh: "家长", pinyin: "jiāzhǎng", ko: "학부모, 가장", pos: "명사", ex: { zh: "家长们都很关心孩子的教育。", pinyin: "Jiā zhǎng men dōu hěn guān xīn hái zi de jiào yù.", ko: "학부모들은 모두 아이의 교육에 관심이 많아요." } },
        { zh: "假期", pinyin: "jiàqī", ko: "방학, 휴가 기간", pos: "명사", ex: { zh: "假期我要去旅行。", pinyin: "Jià qī wǒ yào qù lǚ xíng.", ko: "방학에 나는 여행을 갈 거예요." } },
        { zh: "见到", pinyin: "jiàndào", ko: "만나다, 보다", pos: "동사", ex: { zh: "很高兴见到你。", pinyin: "Hěn gāo xìng jiàn dào nǐ.", ko: "당신을 만나서 반갑습니다." } },
        { zh: "见过", pinyin: "jiànguò", ko: "~을 만난 적 있다, 본 적 있다", pos: "동사", ex: { zh: "我见过他一次。", pinyin: "Wǒ jiàn guò tā yí cì.", ko: "나는 그를 한 번 만난 적이 있어요." } },
        { zh: "讲话", pinyin: "jiǎnghuà", ko: "연설, 이야기하다", pos: "명사", ex: { zh: "校长正在讲话。", pinyin: "Xiào zhǎng zhèng zài jiǎng huà.", ko: "교장 선생님이 연설하고 계세요." } },
        { zh: "交给", pinyin: "jiāogěi", ko: "넘겨주다, 건네주다", pos: "동사", ex: { zh: "请把作业交给老师。", pinyin: "Qǐng bǎ zuò yè jiāo gěi lǎo shī.", ko: "숙제를 선생님께 제출해 주세요." } },
        { zh: "交朋友", pinyin: "jiāopéngyou", ko: "친구를 사귀다", pos: "동사", ex: { zh: "我喜欢交朋友。", pinyin: "Wǒ xǐ huan jiāo péng you.", ko: "나는 친구 사귀는 것을 좋아해요." } },
        { zh: "叫作", pinyin: "jiàozuò", ko: "~라고 부르다", pos: "동사", ex: { zh: "这种花叫作玫瑰。", pinyin: "Zhè zhǒng huā jiào zuò méi gui.", ko: "이 꽃은 장미라고 불려요." } },
        { zh: "教师", pinyin: "jiàoshī", ko: "교사", pos: "명사", ex: { zh: "我妈妈是教师。", pinyin: "Wǒ mā ma shì jiào shī.", ko: "우리 엄마는 교사예요." } },
        { zh: "教学", pinyin: "jiàoxué", ko: "교육, 수업", pos: "명사", ex: { zh: "他从事教学工作。", pinyin: "Tā cóng shì jiào xué gōng zuò.", ko: "그는 교육 업무에 종사해요." } },
        { zh: "接到", pinyin: "jiēdào", ko: "(전화, 편지 등을) 받다", pos: "동사", ex: { zh: "我接到了一个电话。", pinyin: "Wǒ jiē dào le yí gè diàn huà.", ko: "나는 전화 한 통을 받았어요." } },
        { zh: "接下来", pinyin: "jiēxiàlái", ko: "다음으로, 이어서", pos: "동사", ex: { zh: "接下来我们开始上课。", pinyin: "Jiē xià lái wǒmen kāishǐ shàng kè.", ko: "다음으로 우리는 수업을 시작해요." } },
        { zh: "街", pinyin: "jiē", ko: "거리", pos: "명사", ex: { zh: "这条街很热闹。", pinyin: "Zhè tiáo jiē hěn rènao.", ko: "이 거리는 매우 활기차요." } },
        { zh: "今后", pinyin: "jīnhòu", ko: "앞으로, 이후", pos: "명사", ex: { zh: "今后我会更努力。", pinyin: "Jīnhòu wǒ huì gèng nǔlì.", ko: "앞으로 나는 더 노력할 거예요." } },
        { zh: "斤", pinyin: "jīn", ko: "근(무게 단위, 500g)", pos: "양사", ex: { zh: "我买了两斤苹果。", pinyin: "Wǒ mǎi le liǎng jīn píngguǒ.", ko: "나는 사과 두 근을 샀어요." } },
        { zh: "进入", pinyin: "jìnrù", ko: "들어가다, 진입하다", pos: "동사", ex: { zh: "我们进入了教室。", pinyin: "Wǒmen jìnrù le jiàoshì.", ko: "우리는 교실에 들어갔어요." } },
        { zh: "酒", pinyin: "jiǔ", ko: "술", pos: "명사", ex: { zh: "他不喝酒。", pinyin: "Tā bù hē jiǔ.", ko: "그는 술을 마시지 않아요." } },
        { zh: "酒店", pinyin: "jiǔdiàn", ko: "호텔", pos: "명사", ex: { zh: "我们住在这家酒店。", pinyin: "Wǒmen zhù zài zhè jiā jiǔdiàn.", ko: "우리는 이 호텔에 머물러요." } },
        { zh: "就要", pinyin: "jiùyào", ko: "곧 ~하려 하다", pos: "부사", ex: { zh: "火车就要开了。", pinyin: "Huǒchē jiù yào kāi le.", ko: "기차가 곧 출발하려 해요." } },
        { zh: "举手", pinyin: "jǔshǒu", ko: "손을 들다", pos: "동사", ex: { zh: "有问题请举手。", pinyin: "Yǒu wèntí qǐng jǔshǒu.", ko: "질문이 있으면 손을 드세요." } },
        { zh: "句", pinyin: "jù", ko: "문장, 구절, 마디", pos: "양사", ex: { zh: "他说了一句话。", pinyin: "Tā shuō le yí jù huà.", ko: "그는 한 마디 말을 했어요." } },
        { zh: "卡", pinyin: "kǎ", ko: "막히다, 걸리다; (전산) 느리다", pos: "명사", ex: { zh: "手机突然卡住了。", pinyin: "Shǒujī tūrán kǎ zhù le.", ko: "휴대폰이 갑자기 멈췄다(버벅거렸다)." } },
        { zh: "开机", pinyin: "kāijī", ko: "(컴퓨터를) 켜다, 부팅하다", pos: "동사", ex: { zh: "电脑开机需要一分钟。", pinyin: "Diànnǎo kāijī xūyào yì fēnzhōng.", ko: "컴퓨터가 부팅하는 데 1분 걸려요." } },
        { zh: "开学", pinyin: "kāixué", ko: "개학하다", pos: "동사", ex: { zh: "下周一学校开学。", pinyin: "Xià zhōu yī xuéxiào kāixué.", ko: "다음 주 월요일에 학교가 개학해요." } },
        { zh: "考生", pinyin: "kǎoshēng", ko: "수험생", pos: "명사", ex: { zh: "考生们都很紧张。", pinyin: "Kǎoshēngmen dōu hěn jǐnzhāng.", ko: "수험생들은 모두 긴장하고 있어요." } },
        { zh: "靠", pinyin: "kào", ko: "기대다, 의지하다", pos: "동사", ex: { zh: "他靠在墙上。", pinyin: "Tā kào zài qiáng shàng.", ko: "그는 벽에 기대어 있어요." } },
        { zh: "科", pinyin: "kē", ko: "과, 학과, 분야", pos: "명사", ex: { zh: "他是外科医生。", pinyin: "Tā shì wàikē yīshēng.", ko: "그는 외과 의사예요." } },
        { zh: "课堂", pinyin: "kètáng", ko: "교실, 수업 시간", pos: "명사", ex: { zh: "课堂上很安静。", pinyin: "Kètáng shàng hěn ānjìng.", ko: "교실은 매우 조용해요." } },
        { zh: "快餐", pinyin: "kuàicān", ko: "패스트푸드", pos: "명사", ex: { zh: "我们中午吃快餐。", pinyin: "Wǒmen zhōngwǔ chī kuàicān.", ko: "우리는 점심에 패스트푸드를 먹어요." } },
        { zh: "快点儿", pinyin: "kuài diǎnr", ko: "빨리, 서둘러", pos: "부사", ex: { zh: "快点儿走吧！", pinyin: "Kuài diǎnr zǒu ba!", ko: "빨리 가자!" } },
        { zh: "快要", pinyin: "kuàiyào", ko: "곧 ~하려 하다", pos: "부사", ex: { zh: "天快要黑了。", pinyin: "Tiān kuài yào hēi le.", ko: "곧 날이 어두워지려 해요." } },
        { zh: "蓝色", pinyin: "lánsè", ko: "파란색", pos: "명사", ex: { zh: "我喜欢蓝色的天空。", pinyin: "Wǒ xǐhuan lánsè de tiānkōng.", ko: "나는 파란 하늘을 좋아해요." } },
        { zh: "老年", pinyin: "lǎonián", ko: "노년", pos: "명사", ex: { zh: "老年人要注意身体。", pinyin: "Lǎonián rén yào zhùyì shēntǐ.", ko: "노인들은 건강에 유의해야 해요." } },
        { zh: "老朋友", pinyin: "lǎopéngyou", ko: "오랜 친구", pos: "명사", ex: { zh: "他是我的老朋友。", pinyin: "Tā shì wǒ de lǎo péngyou.", ko: "그는 나의 오랜 친구예요." } },
        { zh: "老是", pinyin: "lǎoshi", ko: "늘, 항상", pos: "부사", ex: { zh: "他老是迟到。", pinyin: "Tā lǎoshi chídào.", ko: "그는 늘 지각해요." } },
        { zh: "里头", pinyin: "lǐtou", ko: "안, 안쪽", pos: "명사", ex: { zh: "房子里头很干净。", pinyin: "Fángzi lǐtou hěn gānjìng.", ko: "집 안은 매우 깨끗해요." } },
        { zh: "例子", pinyin: "lìzi", ko: "예, 예시", pos: "명사", ex: { zh: "请举一个例子。", pinyin: "Qǐng jǔ yí gè lìzi.", ko: "예를 하나 들어 주세요." } },
        { zh: "练", pinyin: "liàn", ko: "연습하다", pos: "동사", ex: { zh: "他每天练太极拳。", pinyin: "Tā měitiān liàn tàijíquán.", ko: "그는 매일 태극권을 연습해요." } },
        { zh: "凉", pinyin: "liáng", ko: "서늘하다, 차갑다", pos: "형용사", ex: { zh: "今天天气很凉。", pinyin: "Jīntiān tiānqì hěn liáng.", ko: "오늘 날씨가 서늘해요." } },
        { zh: "零下", pinyin: "língxià", ko: "영하", pos: "명사", ex: { zh: "今天零下五度。", pinyin: "Jīntiān líng xià wǔ dù.", ko: "오늘은 영하 5도예요." } },
        { zh: "流", pinyin: "liú", ko: "흐르다", pos: "동사", ex: { zh: "河水慢慢地流。", pinyin: "Héshuǐ mànmàn de liú.", ko: "강물이 천천히 흘러요." } },
        { zh: "留下", pinyin: "liúxià", ko: "남기다, 남다", pos: "동사", ex: { zh: "他留下了一封信。", pinyin: "Tā liú xià le yì fēng xìn.", ko: "그는 편지 한 통을 남겼어요." } },
        { zh: "留学生", pinyin: "liúxuéshēng", ko: "유학생", pos: "명사", ex: { zh: "她是中国的留学生。", pinyin: "Tā shì Zhōngguó de liúxuéshēng.", ko: "그녀는 중국의 유학생이에요." } },
        { zh: "路边", pinyin: "lùbiān", ko: "길가", pos: "명사", ex: { zh: "路边有很多花。", pinyin: "Lù biān yǒu hěn duō huā.", ko: "길가에 꽃이 많아요." } },
        { zh: "旅客", pinyin: "lǚkè", ko: "여행객, 승객", pos: "명사", ex: { zh: "车站里有很多旅客。", pinyin: "Chēzhàn lǐ yǒu hěn duō lǚkè.", ko: "역에는 많은 여행객이 있어요." } },
        { zh: "旅行", pinyin: "lǚxíng", ko: "여행하다", pos: "동사", ex: { zh: "我们打算去旅行。", pinyin: "Wǒmen dǎsuàn qù lǚxíng.", ko: "우리는 여행을 갈 계획이에요." } },
        { zh: "绿色", pinyin: "lǜsè", ko: "녹색", pos: "명사", ex: { zh: "树叶是绿色的。", pinyin: "Shùyè shì lǜsè de.", ko: "나뭇잎은 녹색이에요." } },
        { zh: "面", pinyin: "miàn", ko: "얼굴, 면, 표면", pos: "명사", ex: { zh: "这个盒子的表面很光滑。", pinyin: "Zhège hézi de biǎomiàn hěn guānghuá.", ko: "이 상자의 표면은 매끄러워요." } },
        { zh: "面前", pinyin: "miànqián", ko: "눈앞, 앞", pos: "명사", ex: { zh: "他站在我面前。", pinyin: "Tā zhàn zài wǒ miànqián.", ko: "그는 내 앞에 서 있어요." } },
        { zh: "名", pinyin: "míng", ko: "명(사람을 세는 단위); 이름", pos: "양사", ex: { zh: "班里有三十名学生。", pinyin: "Bān lǐ yǒu sānshí míng xuésheng.", ko: "반에는 30명의 학생이 있어요." } },
        { zh: "名称", pinyin: "míngchēng", ko: "명칭", pos: "명사", ex: { zh: "这个公司的名称是什么？", pinyin: "Zhège gōngsī de míngchēng shì shénme?", ko: "이 회사의 명칭은 무엇입니까?" } },
        { zh: "名单", pinyin: "míngdān", ko: "명단", pos: "명사", ex: { zh: "请把名单发给我。", pinyin: "Qǐng bǎ míngdān fā gěi wǒ.", ko: "명단을 저에게 보내 주세요." } },
        { zh: "拿出", pinyin: "náchū", ko: "꺼내다", pos: "동사", ex: { zh: "他从包里拿出一本书。", pinyin: "Tā cóng bāo lǐ náchū yì běn shū.", ko: "그는 가방에서 책 한 권을 꺼냈어요." } },
        { zh: "拿到", pinyin: "nádào", ko: "받다, 손에 넣다", pos: "동사", ex: { zh: "我拿到了录取通知书。", pinyin: "Wǒ nádàole lùqǔ tōngzhīshū.", ko: "나는 합격 통지서를 받았어요." } },
        { zh: "那会儿", pinyin: "nà huìr", ko: "그때", pos: "대명사", ex: { zh: "那会儿我还很小。", pinyin: "Nà huìr wǒ hái hěn xiǎo.", ko: "그때 나는 아직 어렸어요." } },
        { zh: "那时", pinyin: "nàshí", ko: "그때, 그 당시", pos: "대명사", ex: { zh: "那时我还不认识他。", pinyin: "Nà shí wǒ hái bú rènshi tā.", ko: "그때 나는 아직 그를 몰랐어요." } },
        { zh: "那时候", pinyin: "nàshíhou", ko: "그때, 그 무렵", pos: "명사", ex: { zh: "那时候我们都很年轻。", pinyin: "Nà shíhou wǒmen dōu hěn niánqīng.", ko: "그때 우리는 모두 젊었어요." } },
        { zh: "那样", pinyin: "nàyàng", ko: "그렇게, 그런 식으로", pos: "대명사", ex: { zh: "别那样说话。", pinyin: "Bié nàyàng shuōhuà.", ko: "그렇게 말하지 마." } },
        { zh: "南方", pinyin: "nánfāng", ko: "남방, 남쪽 지방", pos: "명사", ex: { zh: "他是南方人。", pinyin: "Tā shì nánfāng rén.", ko: "그는 남방 사람이에요." } },
        { zh: "难题", pinyin: "nántí", ko: "난제, 어려운 문제", pos: "명사", ex: { zh: "这道难题我解不出来。", pinyin: "Zhè dào nántí wǒ jiě bù chūlái.", ko: "이 어려운 문제를 나는 못 풀겠어요." } },
        { zh: "难听", pinyin: "nántīng", ko: "듣기 싫다, 거슬리다", pos: "형용사", ex: { zh: "别说那种难听的话。", pinyin: "Bié shuō nà zhǒng nántīng de huà.", ko: "그렇게 듣기 싫은 말은 하지 마." } },
        { zh: "能够", pinyin: "nénggòu", ko: "~할 수 있다", pos: "동사", ex: { zh: "我们能够按时完成任务。", pinyin: "Wǒmen nénggòu ànshí wánchéng rènwù.", ko: "우리는 제때에 임무를 완수할 수 있어요." } },
        { zh: "爬", pinyin: "pá", ko: "기어오르다, 오르다", pos: "동사", ex: { zh: "孩子在地上爬。", pinyin: "Háizi zài dìshang pá.", ko: "아이가 바닥에서 기어요." } },
        { zh: "怕", pinyin: "pà", ko: "무서워하다, 두려워하다", pos: "동사", ex: { zh: "我很怕黑。", pinyin: "Wǒ hěn pà hēi.", ko: "나는 어둠을 매우 무서워해요." } },
        { zh: "排", pinyin: "pái", ko: "줄을 서다, 배열하다", pos: "동사", ex: { zh: "大家在门口排队。", pinyin: "Dàjiā zài ménkǒu pái duì.", ko: "모두 입구에서 줄을 서요." } },
        { zh: "碰", pinyin: "pèng", ko: "부딪치다, 만나다", pos: "동사", ex: { zh: "别碰我的东西。", pinyin: "Bié pèng wǒ de dōngxi.", ko: "내 물건 건드리지 마." } },
        { zh: "碰到", pinyin: "pèngdào", ko: "우연히 만나다, 마주치다", pos: "동사", ex: { zh: "我在路上碰到了老朋友。", pinyin: "Wǒ zài lùshang pèngdàole lǎo péngyou.", ko: "나는 길에서 옛 친구를 우연히 만났어요." } },
        { zh: "平安", pinyin: "píngān", ko: "평안하다, 무사하다", pos: "형용사", ex: { zh: "祝你一路平安。", pinyin: "Zhù nǐ yílù píng'ān.", ko: "가시는 길 평안하시길 바랍니다." } },
        { zh: "瓶", pinyin: "píng", ko: "병(양사)", pos: "양사", ex: { zh: "我买了一瓶水。", pinyin: "Wǒ mǎile yì píng shuǐ.", ko: "나는 물 한 병을 샀어요." } },
        { zh: "普通", pinyin: "pǔtōng", ko: "보통이다, 평범하다", pos: "형용사", ex: { zh: "他是一个普通人。", pinyin: "Tā shì yí gè pǔtōng rén.", ko: "그는 평범한 사람이에요." } },
        { zh: "骑车", pinyin: "qíchē", ko: "자전거를 타다", pos: "동사", ex: { zh: "我每天骑车上班。", pinyin: "Wǒ měitiān qí chē shàngbān.", ko: "나는 매일 자전거를 타고 출근해요." } },
        { zh: "气", pinyin: "qì", ko: "기체, 공기, 냄새", pos: "명사", ex: { zh: "轮胎没气了。", pinyin: "Lúntāi méi qì le.", ko: "타이어에 바람이 빠졌어요." } },
        { zh: "气温", pinyin: "qìwēn", ko: "기온", pos: "명사", ex: { zh: "今天的气温很低。", pinyin: "Jīntiān de qìwēn hěn dī.", ko: "오늘 기온이 매우 낮아요." } },
        { zh: "千克", pinyin: "qiānkè", ko: "킬로그램(kg)", pos: "양사", ex: { zh: "这个西瓜重五千克。", pinyin: "Zhège xīguā zhòng wǔ qiānkè.", ko: "이 수박은 무게가 5킬로그램이에요." } },
        { zh: "前年", pinyin: "qiánnián", ko: "재작년", pos: "명사", ex: { zh: "我前年去过北京。", pinyin: "Wǒ qiánnián qùguo Běijīng.", ko: "나는 재작년에 베이징에 간 적이 있어요." } },
        { zh: "青年", pinyin: "qīngnián", ko: "청년", pos: "명사", ex: { zh: "他是一位有理想的青年。", pinyin: "Tā shì yí wèi yǒu lǐxiǎng de qīngnián.", ko: "그는 이상을 가진 청년이에요." } },
        { zh: "晴天", pinyin: "qíngtiān", ko: "맑은 날", pos: "명사", ex: { zh: "今天是晴天,适合出去玩。", pinyin: "Jīntiān shì qíngtiān, shìhé chūqù wán.", ko: "오늘은 맑은 날이라 놀러 나가기 좋아요." } },
        { zh: "秋天", pinyin: "qiūtiān", ko: "가을", pos: "명사", ex: { zh: "秋天的树叶是黄色的。", pinyin: "Qiūtiān de shùyè shì huángsè de.", ko: "가을 나뭇잎은 노래요." } },
        { zh: "求", pinyin: "qiú", ko: "부탁하다, 구하다, 청하다", pos: "동사", ex: { zh: "我求你帮我一次。", pinyin: "Wǒ qiú nǐ bāng wǒ yí cì.", ko: "한 번만 도와달라고 부탁드려요." } },
        { zh: "球场", pinyin: "qiúchǎng", ko: "구장, 경기장", pos: "명사", ex: { zh: "我们在球场上打篮球。", pinyin: "Wǒmen zài qiúchǎng shàng dǎ lánqiú.", ko: "우리는 구장에서 농구를 해요." } },
        { zh: "球队", pinyin: "qiúduì", ko: "구기 팀, 선수단", pos: "명사", ex: { zh: "这支球队赢了比赛。", pinyin: "Zhè zhī qiúduì yíngle bǐsài.", ko: "이 팀은 경기에서 이겼어요." } },
        { zh: "球鞋", pinyin: "qiúxié", ko: "운동화", pos: "명사", ex: { zh: "我想买一双新球鞋。", pinyin: "Wǒ xiǎng mǎi yì shuāng xīn qiúxié.", ko: "나는 새 운동화 한 켤레를 사고 싶어요." } },
        { zh: "取得", pinyin: "qǔdé", ko: "얻다, 취득하다", pos: "동사", ex: { zh: "他取得了很大的成绩。", pinyin: "Tā qǔdéle hěn dà de chéngjì.", ko: "그는 큰 성과를 거두었어요." } },
        { zh: "全", pinyin: "quán", ko: "전부, 모두, 온전히", pos: "부사", ex: { zh: "全班同学都来了。", pinyin: "Quán bān tóngxué dōu lái le.", ko: "반 학생 전부가 왔어요." } },
        { zh: "全国", pinyin: "quánguó", ko: "전국", pos: "명사", ex: { zh: "这个节目全国都能看到。", pinyin: "Zhège jiémù quánguó dōu néng kàndào.", ko: "이 프로그램은 전국에서 볼 수 있어요." } },
        { zh: "全家", pinyin: "quánjiā", ko: "온 가족", pos: "명사", ex: { zh: "全家人一起吃年夜饭。", pinyin: "Quánjiā rén yìqǐ chī niányèfàn.", ko: "온 가족이 함께 섣달 그믐날 저녁을 먹어요." } },
        { zh: "全年", pinyin: "quánnián", ko: "일 년 내내, 연중", pos: "명사", ex: { zh: "这家商店全年营业。", pinyin: "Zhè jiā shāngdiàn quánnián yíngyè.", ko: "이 가게는 일 년 내내 영업해요." } },
        { zh: "全身", pinyin: "quánshēn", ko: "온몸, 전신", pos: "명사", ex: { zh: "运动后我全身都疼。", pinyin: "Yùndòng hòu wǒ quánshēn dōu téng.", ko: "운동 후에 나는 온몸이 아파요." } },
        { zh: "全体", pinyin: "quántǐ", ko: "전체, 전원", pos: "명사", ex: { zh: "全体同学请注意。", pinyin: "Quántǐ tóngxué qǐng zhùyì.", ko: "전체 학생들은 주목해 주세요." } },
        { zh: "人们", pinyin: "rénmen", ko: "사람들", pos: "명사", ex: { zh: "人们都喜欢春天。", pinyin: "Rénmen dōu xǐhuan chūntiān.", ko: "사람들은 모두 봄을 좋아해요." } },
        { zh: "人数", pinyin: "rénshù", ko: "인원수", pos: "명사", ex: { zh: "教室里的人数不多。", pinyin: "Jiàoshì lǐ de rénshù bù duō.", ko: "교실 안의 인원수는 많지 않아요." } },
        { zh: "日报", pinyin: "rìbào", ko: "일간신문, 일보", pos: "명사", ex: { zh: "他每天早上看日报。", pinyin: "tā měitiān zǎoshang kàn rìbào.", ko: "그는 매일 아침 일간신문을 봐요." } },
        { zh: "日子", pinyin: "rìzi", ko: "날, 날짜; 생활, 세월", pos: "명사", ex: { zh: "这些日子他一直很忙。", pinyin: "zhè xiē rìzi tā yìzhí hěn máng.", ko: "요즘 그는 계속 바빠요." } },
        { zh: "商人", pinyin: "shāngrén", ko: "상인, 사업가", pos: "명사", ex: { zh: "他的父亲是一位商人。", pinyin: "tā de fùqīn shì yí wèi shāngrén.", ko: "그의 아버지는 상인이에요." } },
        { zh: "上周", pinyin: "shàngzhōu", ko: "지난주", pos: "명사", ex: { zh: "上周我去了北京。", pinyin: "shàngzhōu wǒ qùle Běijīng.", ko: "지난주에 나는 베이징에 갔어요." } },
        { zh: "少年", pinyin: "shàonián", ko: "소년", pos: "명사", ex: { zh: "他是一个爱读书的少年。", pinyin: "tā shì yí gè ài dúshū de shàonián.", ko: "그는 책 읽기를 좋아하는 소년이에요." } },
        { zh: "少数", pinyin: "shǎoshù", ko: "소수, 극소수", pos: "수사", ex: { zh: "只有少数人同意这个计划。", pinyin: "zhǐyǒu shǎoshù rén tóngyì zhège jìhuà.", ko: "소수의 사람만이 이 계획에 동의해요." } },
        { zh: "身边", pinyin: "shēnbiān", ko: "곁, 신변, 주변", pos: "명사", ex: { zh: "她一直在我身边。", pinyin: "tā yìzhí zài wǒ shēnbiān.", ko: "그녀는 늘 내 곁에 있어요." } },
        { zh: "什么样", pinyin: "shénmeyàng", ko: "어떤, 어떤 모습", pos: "대명사", ex: { zh: "你想找什么样的工作?", pinyin: "nǐ xiǎng zhǎo shénme yàng de gōngzuò?", ko: "당신은 어떤 일을 찾고 싶습니까?" } },
        { zh: "生", pinyin: "shēng", ko: "낳다, 태어나다; 생(生)", pos: "동사", ex: { zh: "她去年生了一个女儿。", pinyin: "tā qùnián shēngle yí gè nǚ'ér.", ko: "그녀는 작년에 딸을 낳았어요." } },
        { zh: "生词", pinyin: "shēngcí", ko: "새 단어, 생소한 단어", pos: "명사", ex: { zh: "这篇课文有很多生词。", pinyin: "zhè piān kèwén yǒu hěn duō shēngcí.", ko: "이 본문에는 새 단어가 많아요." } },
        { zh: "市", pinyin: "shì", ko: "시(市), 도시; 시장", pos: "명사", ex: { zh: "上海市有很多外国人。", pinyin: "shànghǎi shì yǒu hěn duō wàiguó rén.", ko: "상하이시에는 외국인이 많아요." } },
        { zh: "市长", pinyin: "shìzhǎng", ko: "시장(市長)", pos: "명사", ex: { zh: "市长在会议上讲话。", pinyin: "shìzhǎng zài huìyì shàng jiǎnghuà.", ko: "시장은 회의에서 연설했어요." } },
        { zh: "收到", pinyin: "shōudào", ko: "받다, 수령하다", pos: "동사", ex: { zh: "我收到了你的信。", pinyin: "wǒ shōudàole nǐ de xìn.", ko: "나는 당신의 편지를 받았어요." } },
        { zh: "熟", pinyin: "shú", ko: "익다; 익숙하다, 잘 알다", pos: "형용사", ex: { zh: "这个西瓜已经熟了。", pinyin: "zhège xīguā yǐjīng shú le.", ko: "이 수박은 이미 익었어요." } },
        { zh: "数", pinyin: "shǔ", ko: "세다, 헤아리다", pos: "수사", ex: { zh: "他正在数钱。", pinyin: "tā zhèngzài shǔ qián.", ko: "그는 지금 돈을 세고 있어요." } },
        { zh: "送到", pinyin: "sòngdào", ko: "보내다, 배달하다", pos: "동사", ex: { zh: "快递已经送到了。", pinyin: "kuàidì yǐjīng sòngdào le.", ko: "택배가 이미 도착했어요." } },
        { zh: "送给", pinyin: "sònggěi", ko: "선물하다, ~에게 주다", pos: "동사", ex: { zh: "我把这本书送给他了。", pinyin: "wǒ bǎ zhè běn shū sònggěi tā le.", ko: "나는 이 책을 그에게 선물했어요." } },
        { zh: "它们", pinyin: "tāmen", ko: "그것들", pos: "대명사", ex: { zh: "这些猫很可爱,我喜欢它们。", pinyin: "zhè xiē māo hěn kě'ài, wǒ xǐhuan tāmen.", ko: "이 고양이들은 귀엽다, 나는 그것들을 좋아해요." } },
        { zh: "提出", pinyin: "tíchū", ko: "제기하다, 제안하다", pos: "동사", ex: { zh: "他提出了一个新想法。", pinyin: "tā tíchūle yí gè xīn xiǎngfǎ.", ko: "그는 새로운 생각을 제안했어요." } },
        { zh: "提到", pinyin: "tídào", ko: "언급하다", pos: "동사", ex: { zh: "他在信中提到了这件事。", pinyin: "tā zài xìn zhōng tídàole zhè jiàn shì.", ko: "그는 편지에서 이 일을 언급했어요." } },
        { zh: "体育场", pinyin: "tǐyùchǎng", ko: "경기장, 스타디움", pos: "명사", ex: { zh: "比赛在体育场举行。", pinyin: "bǐsài zài tǐyùchǎng jǔxíng.", ko: "경기는 경기장에서 열려요." } },
        { zh: "体育馆", pinyin: "tǐyùguǎn", ko: "체육관", pos: "명사", ex: { zh: "我们在体育馆打篮球。", pinyin: "wǒmen zài tǐyùguǎn dǎ lánqiú.", ko: "우리는 체육관에서 농구를 해요." } },
        { zh: "天上", pinyin: "tiānshàng", ko: "하늘, 하늘 위", pos: "명사", ex: { zh: "天上有很多星星。", pinyin: "tiānshàng yǒu hěn duō xīngxing.", ko: "하늘에는 별이 많아요." } },
        { zh: "听讲", pinyin: "tīngjiǎng", ko: "강의를 듣다", pos: "동사", ex: { zh: "学生们认真听讲。", pinyin: "xuéshengmen rènzhēn tīngjiǎng.", ko: "학생들은 열심히 강의를 들어요." } },
        { zh: "听说", pinyin: "tīngshuō", ko: "듣자 하니, ~라고 들었다", pos: "동사", ex: { zh: "听说他明天要回国。", pinyin: "tīngshuō tā míngtiān yào huíguó.", ko: "듣자 하니 그는 내일 귀국한다고 해요." } },
        { zh: "停", pinyin: "tíng", ko: "멈추다, 세우다, 주차하다", pos: "동사", ex: { zh: "车停在门口。", pinyin: "chē tíng zài ménkǒu.", ko: "차가 입구에 멈춰 있어요." } },
        { zh: "停车", pinyin: "tíngchē", ko: "주차하다, 차를 세우다", pos: "동사", ex: { zh: "这里不能停车。", pinyin: "zhèlǐ bùnéng tíngchē.", ko: "여기는 주차할 수 없어요." } },
        { zh: "停车场", pinyin: "tíngchēchǎng", ko: "주차장", pos: "명사", ex: { zh: "停车场里没有空位了。", pinyin: "tíngchēchǎng lǐ méiyǒu kòngwèi le.", ko: "주차장에 빈 자리가 없어요." } },
        { zh: "挺好", pinyin: "tǐnghǎo", ko: "아주 좋다, 꽤 괜찮다", pos: "형용사", ex: { zh: "这个主意挺好的。", pinyin: "zhège zhǔyi tǐng hǎo de.", ko: "이 생각은 아주 좋아요." } },
        { zh: "通", pinyin: "tōng", ko: "통하다, 잘 알다", pos: "동사", ex: { zh: "这条路通往城里。", pinyin: "zhè tiáo lù tōng wǎng chéng lǐ.", ko: "이 길은 시내로 통해요." } },
        { zh: "同样", pinyin: "tóngyàng", ko: "같은, 동일한", pos: "형용사", ex: { zh: "我们有同样的想法。", pinyin: "wǒmen yǒu tóngyàng de xiǎngfǎ.", ko: "우리는 같은 생각을 가지고 있어요." } },
        { zh: "头", pinyin: "tóu", ko: "머리", pos: "명사", ex: { zh: "他的头有点疼。", pinyin: "tā de tóu yǒudiǎn téng.", ko: "그는 머리가 좀 아파요." } },
        { zh: "图片", pinyin: "túpiàn", ko: "그림, 사진", pos: "명사", ex: { zh: "这张图片很漂亮。", pinyin: "zhè zhāng túpiàn hěn piàoliang.", ko: "이 사진은 매우 아름다워요." } },
        { zh: "外地", pinyin: "wàidì", ko: "타지, 다른 지역", pos: "명사", ex: { zh: "他是从外地来的。", pinyin: "tā shì cóng wàidì lái de.", ko: "그는 다른 지역에서 왔어요." } },
        { zh: "外卖", pinyin: "wàimài", ko: "배달 음식, 테이크아웃", pos: "명사", ex: { zh: "我今天点了外卖。", pinyin: "wǒ jīntiān diǎnle wàimài.", ko: "나는 오늘 배달 음식을 시켰어요." } },
        { zh: "晚安", pinyin: "wǎnān", ko: "안녕히 주무세요, 잘 자요", pos: "동사", ex: { zh: "晚安,做个好梦。", pinyin: "wǎn'ān, zuò gè hǎomèng.", ko: "안녕히 주무세요, 좋은 꿈 꾸세요." } },
        { zh: "晚报", pinyin: "wǎnbào", ko: "석간신문", pos: "명사", ex: { zh: "爷爷每天看晚报。", pinyin: "yéye měitiān kàn wǎnbào.", ko: "할아버지는 매일 석간신문을 봐요." } },
        { zh: "晚餐", pinyin: "wǎncān", ko: "저녁 식사, 만찬", pos: "명사", ex: { zh: "我们一起吃晚餐吧。", pinyin: "wǒmen yìqǐ chī wǎncān ba.", ko: "우리 같이 저녁 먹자." } },
        { zh: "晚会", pinyin: "wǎnhuì", ko: "저녁 파티, 이브닝 파티", pos: "명사", ex: { zh: "学校举办了新年晚会。", pinyin: "xuéxiào jǔbànle xīnnián wǎnhuì.", ko: "학교에서 신년 이브닝 파티를 열었어요." } },
        { zh: "网", pinyin: "wǎng", ko: "그물, 망, 인터넷", pos: "명사", ex: { zh: "他在网上买了一本书。", pinyin: "tā zài wǎng shàng mǎile yì běn shū.", ko: "그는 인터넷에서 책 한 권을 샀어요." } },
        { zh: "问路", pinyin: "wènlù", ko: "길을 묻다", pos: "동사", ex: { zh: "他在北京问路,找到了地铁站。", pinyin: "Tā zài Běijīng wèn lù, zhǎo dào le dìtiě zhàn.", ko: "그는 베이징에서 길을 물어 지하철역을 찾았어요." } },
        { zh: "午餐", pinyin: "wǔcān", ko: "점심, 점심 식사", pos: "명사", ex: { zh: "我们中午一起吃午餐吧。", pinyin: "Wǒmen zhōngwǔ yìqǐ chī wǔcān ba.", ko: "우리 점심에 같이 점심 식사 하자." } },
        { zh: "午睡", pinyin: "wǔshuì", ko: "낮잠 자다", pos: "동사", ex: { zh: "我每天中午都午睡半个小时。", pinyin: "Wǒ měitiān zhōngwǔ dōu wǔshuì bàn gè xiǎoshí.", ko: "나는 매일 점심에 30분씩 낮잠을 자요." } },
        { zh: "西北", pinyin: "Xīběi", ko: "서북, 중국 서북 지역", pos: "명사", ex: { zh: "西北地区的天气很干燥。", pinyin: "Xīběi dìqū de tiānqì hěn gānzào.", ko: "서북 지역의 날씨는 매우 건조해요." } },
        { zh: "西餐", pinyin: "xīcān", ko: "서양 음식, 양식", pos: "명사", ex: { zh: "周末我们去吃西餐吧。", pinyin: "Zhōumò wǒmen qù chī xīcān ba.", ko: "주말에 우리 양식 먹으러 가자." } },
        { zh: "西方", pinyin: "Xīfāng", ko: "서양, 서방", pos: "명사", ex: { zh: "很多西方国家的文化不太一样。", pinyin: "Hěn duō Xīfāng guójiā de wénhuà bú tài yíyàng.", ko: "많은 서양 국가들의 문화는 서로 많이 달라요." } },
        { zh: "西南", pinyin: "xīnán", ko: "서남, 남서", pos: "명사", ex: { zh: "云南在中国的西南方向。", pinyin: "Yúnnán zài Zhōngguó de xīnán fāngxiàng.", ko: "윈난은 중국의 서남쪽에 있어요." } },
        { zh: "西医", pinyin: "xīyī", ko: "서양 의학, 양의사", pos: "명사", ex: { zh: "他不相信中医,只相信西医。", pinyin: "Tā bù xiāngxìn zhōngyī, zhǐ xiāngxìn xīyī.", ko: "그는 한의학을 믿지 않고 서양 의학만 믿어요." } },
        { zh: "下雪", pinyin: "xiàxuě", ko: "눈이 내리다", pos: "동사", ex: { zh: "冬天北京经常下雪。", pinyin: "Dōngtiān Běijīng jīngcháng xià xuě.", ko: "겨울에 베이징은 자주 눈이 내려요." } },
        { zh: "下周", pinyin: "xiàzhōu", ko: "다음 주", pos: "명사", ex: { zh: "下周我要去上海出差。", pinyin: "Xià zhōu wǒ yào qù Shànghǎi chūchāi.", ko: "다음 주에 나는 상하이로 출장을 가요." } },
        { zh: "夏天", pinyin: "xiàtiān", ko: "여름", pos: "명사", ex: { zh: "夏天的时候天气非常热。", pinyin: "Xiàtiān de shíhou tiānqì fēicháng rè.", ko: "여름에는 날씨가 매우 더워요." } },
        { zh: "相机", pinyin: "xiàngjī", ko: "카메라, 사진기", pos: "명사", ex: { zh: "我买了一个新相机。", pinyin: "Wǒ mǎi le yí gè xīn xiàngjī.", ko: "나는 새 카메라를 샀어요." } },
        { zh: "想到", pinyin: "xiǎngdào", ko: "생각이 나다, 떠올리다", pos: "동사", ex: { zh: "我突然想到一个好办法。", pinyin: "Wǒ tūrán xiǎngdào yí gè hǎo bànfǎ.", ko: "나는 갑자기 좋은 방법이 떠올랐어요." } },
        { zh: "想法", pinyin: "xiǎngfǎ", ko: "생각, 의견", pos: "명사", ex: { zh: "你对这件事有什么想法?", pinyin: "Nǐ duì zhè jiàn shì yǒu shénme xiǎngfǎ?", ko: "너는 이 일에 대해 어떤 생각이 있니?" } },
        { zh: "小声", pinyin: "xiǎoshēng", ko: "작은 소리로 말하다, 소곤소곤", pos: "동사", ex: { zh: "请你小声说话,孩子在睡觉。", pinyin: "Qǐng nǐ xiǎoshēng shuōhuà, háizi zài shuìjiào.", ko: "아이가 자고 있으니 작은 소리로 말씀해 주세요." } },
        { zh: "小时候", pinyin: "xiǎoshíhou", ko: "어릴 때, 어린 시절", pos: "명사", ex: { zh: "小时候我很喜欢吃糖。", pinyin: "Xiǎo shíhou wǒ hěn xǐhuan chī táng.", ko: "어릴 때 나는 사탕 먹는 것을 아주 좋아했어요." } },
        { zh: "小组", pinyin: "xiǎozǔ", ko: "소그룹, 조", pos: "명사", ex: { zh: "老师把学生分成几个小组。", pinyin: "Lǎoshī bǎ xuésheng fēnchéng jǐ gè xiǎozǔ.", ko: "선생님은 학생들을 몇 개의 조로 나누었어요." } },
        { zh: "校园", pinyin: "xiàoyuán", ko: "캠퍼스, 교정", pos: "명사", ex: { zh: "校园里的樱花开了。", pinyin: "Xiàoyuán li de yīnghuā kāi le.", ko: "캠퍼스의 벚꽃이 피었어요." } },
        { zh: "笑话儿", pinyin: "xiàohuar", ko: "농담, 우스갯소리", pos: "명사", ex: { zh: "他喜欢讲笑话儿逗大家开心。", pinyin: "Tā xǐhuan jiǎng xiàohuar dòu dàjiā kāixīn.", ko: "그는 농담을 해서 모두를 즐겁게 하는 것을 좋아해요." } },
        { zh: "心里", pinyin: "xīnli", ko: "마음속, 속마음", pos: "명사", ex: { zh: "我心里很难过。", pinyin: "Wǒ xīnli hěn nánguò.", ko: "나는 마음속으로 매우 슬퍼요." } },
        { zh: "心中", pinyin: "xīnzhōng", ko: "마음속, 가슴속", pos: "명사", ex: { zh: "妈妈永远在我心中。", pinyin: "Māma yǒngyuǎn zài wǒ xīnzhōng.", ko: "엄마는 영원히 내 마음속에 있어요." } },
        { zh: "星星", pinyin: "xīngxing", ko: "별", pos: "명사", ex: { zh: "晚上天上有很多星星。", pinyin: "Wǎnshang tiān shàng yǒu hěn duō xīngxing.", ko: "밤에는 하늘에 별이 많이 있어요." } },
        { zh: "姓名", pinyin: "xìngmíng", ko: "성명, 이름", pos: "명사", ex: { zh: "请写下你的姓名和电话号码。", pinyin: "Qǐng xiěxià nǐ de xìngmíng hé diànhuà hàomǎ.", ko: "당신의 성명과 전화번호를 적어 주세요." } },
        { zh: "休假", pinyin: "xiūjià", ko: "휴가를 보내다, 휴가 가다", pos: "동사", ex: { zh: "下个月我要去休假。", pinyin: "Xià gè yuè wǒ yào qù xiūjià.", ko: "다음 달에 나는 휴가를 갈 거예요." } },
        { zh: "选", pinyin: "xuǎn", ko: "고르다, 선택하다", pos: "동사", ex: { zh: "你想选哪个颜色?", pinyin: "Nǐ xiǎng xuǎn nǎge yánsè?", ko: "너는 어떤 색깔을 고르고 싶니?" } },
        { zh: "眼", pinyin: "yǎn", ko: "눈", pos: "명사", ex: { zh: "她的眼很大很漂亮。", pinyin: "Tā de yǎn hěn dà hěn piàoliang.", ko: "그녀의 눈은 크고 예뻐요." } },
        { zh: "养", pinyin: "yǎng", ko: "기르다, 키우다", pos: "동사", ex: { zh: "我家养了一只小猫。", pinyin: "Wǒ jiā yǎng le yì zhī xiǎo māo.", ko: "우리 집은 고양이 한 마리를 길러요." } },
        { zh: "药店", pinyin: "yàodiàn", ko: "약국", pos: "명사", ex: { zh: "附近有一家药店。", pinyin: "Fùjìn yǒu yì jiā yàodiàn.", ko: "근처에 약국이 하나 있어요." } },
        { zh: "药片", pinyin: "yàopiàn", ko: "알약, 정제", pos: "명사", ex: { zh: "每天吃两片药片。", pinyin: "Měitiān chī liǎng piàn yàopiàn.", ko: "매일 알약 두 알을 먹어요." } },
        { zh: "药水", pinyin: "Yàoshuǐ", ko: "물약, 약물(액체)", pos: "명사", ex: { zh: "妈妈给我买了止咳药水。", pinyin: "Māma gěi wǒ mǎi le zhǐké yàoshuǐ.", ko: "엄마가 나에게 기침약(물약)을 사 주셨어요." } },
        { zh: "夜里", pinyin: "yèli", ko: "밤에, 밤중", pos: "명사", ex: { zh: "夜里下起了大雨。", pinyin: "Yèli xià qǐ le dàyǔ.", ko: "밤에 큰 비가 내리기 시작했어요." } },
        { zh: "一部分", pinyin: "yībùfen", ko: "일부분, 일부", pos: "수사", ex: { zh: "这只是问题的一部分。", pinyin: "Zhè zhǐ shì wèntí de yí bùfen.", ko: "이것은 단지 문제의 일부일 뿐이에요." } },
        { zh: "一点点", pinyin: "yīdiǎndiǎn", ko: "조금, 아주 조금", pos: "명사", ex: { zh: "我只吃了一点点。", pinyin: "Wǒ zhǐ chī le yìdiǎndiǎn.", ko: "나는 아주 조금만 먹었어요." } },
        { zh: "一路平安", pinyin: "yīlù píngān", ko: "가시는 길 평안하시길, 안전한 여행 되세요", pos: "표현", ex: { zh: "祝你一路平安!", pinyin: "Zhù nǐ yílù píng'ān!", ko: "가시는 길 평안하시길 빕니다!" } },
        { zh: "一路顺风", pinyin: "yīlù shùnfēng", ko: "가시는 길 순조롭길, 잘 다녀오세요", pos: "동사", ex: { zh: "明天你要出发了,一路顺风!", pinyin: "Míngtiān nǐ yào chūfā le, yílù shùnfēng!", ko: "내일 출발하시는군요, 잘 다녀오세요!" } },
        { zh: "一生", pinyin: "yīshēng", ko: "일생, 평생", pos: "명사", ex: { zh: "他把一生都献给了教育事业。", pinyin: "Tā bǎ yìshēng dōu xiàn gěi le jiàoyù shìyè.", ko: "그는 일생을 교육 사업에 바쳤어요." } },
        { zh: "以上", pinyin: "yǐshàng", ko: "이상", pos: "명사", ex: { zh: "十八岁以上才能进去。", pinyin: "Shíbā suì yǐshàng cái néng jìnqù.", ko: "18세 이상이어야만 들어갈 수 있어요." } },
        { zh: "以外", pinyin: "yǐwài", ko: "이외, 그 밖에", pos: "명사", ex: { zh: "除了他以外,大家都同意。", pinyin: "Chúle tā yǐwài, dàjiā dōu tóngyì.", ko: "그를 제외하고는 모두 동의했어요." } },
        { zh: "以下", pinyin: "yǐxià", ko: "이하", pos: "명사", ex: { zh: "五岁以下的孩子可以免费入场。", pinyin: "Wǔ suì yǐxià de háizi kěyǐ miǎnfèi rùchǎng.", ko: "5세 이하의 어린이는 무료로 입장할 수 있어요." } },
        { zh: "阴天", pinyin: "yīntiān", ko: "흐린 날씨, 흐린 날", pos: "명사", ex: { zh: "今天是阴天,没有太阳。", pinyin: "Jīntiān shì yīntiān, méiyǒu tàiyáng.", ko: "오늘은 흐린 날이라 해가 없어요." } },
        { zh: "音节", pinyin: "yīnjié", ko: "음절", pos: "명사", ex: { zh: "“汉语”有两个音节。", pinyin: "“hàn yǔ” yǒu liǎng gè yīn jié。", ko: "“汉语”는 두 개의 음절이 있어요." } },
        { zh: "音乐会", pinyin: "yīnyuèhuì", ko: "음악회, 콘서트", pos: "명사", ex: { zh: "我们明天去听音乐会。", pinyin: "wǒ men míng tiān qù tīng yīn yuè huì。", ko: "우리는 내일 음악회를 들으러 가요." } },
        { zh: "银行卡", pinyin: "yínhángkǎ", ko: "은행 카드", pos: "명사", ex: { zh: "我用银行卡付款。", pinyin: "wǒ yòng yín háng kǎ fù kuǎn。", ko: "나는 은행 카드로 결제해요." } },
        { zh: "英文", pinyin: "Yīngwén", ko: "영어", pos: "명사", ex: { zh: "他的英文很好。", pinyin: "tā de Yīng wén hěn hǎo。", ko: "그의 영어 실력은 좋아요." } },
        { zh: "英语", pinyin: "Yīngyǔ", ko: "영어", pos: "명사", ex: { zh: "我在学英语。", pinyin: "wǒ zài xué Yīng yǔ。", ko: "나는 영어를 배우고 있어요." } },
        { zh: "影片", pinyin: "yǐngpiàn", ko: "영화, 필름", pos: "명사", ex: { zh: "这部影片很感人。", pinyin: "zhè bù yǐng piàn hěn gǎn rén。", ko: "이 영화는 매우 감동적이에요." } },
        { zh: "油", pinyin: "yóu", ko: "기름", pos: "명사", ex: { zh: "这道菜放了很多油。", pinyin: "zhè dào cài fàng le hěn duō yóu。", ko: "이 요리에는 기름이 많이 들어갔어요." } },
        { zh: "游客", pinyin: "yóukè", ko: "관광객, 여행객", pos: "명사", ex: { zh: "这里每天有很多游客。", pinyin: "zhè lǐ měi tiān yǒu hěn duō yóu kè。", ko: "이곳에는 매일 많은 관광객이 있어요." } },
        { zh: "有点儿", pinyin: "yǒu diǎnr", ko: "조금, 약간", pos: "부사", ex: { zh: "我今天有点儿累。", pinyin: "wǒ jīn tiān yǒu diǎnr lèi。", ko: "나는 오늘 조금 피곤해요." } },
        { zh: "有空儿", pinyin: "yǒukòngr", ko: "시간이 있다, 짬이 나다", pos: "동사", ex: { zh: "你明天有空儿吗？", pinyin: "nǐ míng tiān yǒu kòngr ma?", ko: "너 내일 시간 있니?" } },
        { zh: "有人", pinyin: "yǒurén", ko: "어떤 사람, 누군가", pos: "대명사", ex: { zh: "门外有人在等你。", pinyin: "mén wài yǒu rén zài děng nǐ。", ko: "문밖에 누군가 너를 기다리고 있어요." } },
        { zh: "有一点儿", pinyin: "yǒu yī diǎnr", ko: "조금, 약간", pos: "부사", ex: { zh: "这件衣服有一点儿贵。", pinyin: "zhè jiàn yī fu yǒu yì diǎnr guì。", ko: "이 옷은 조금 비싸요." } },
        { zh: "有意思", pinyin: "yǒuyìsi", ko: "재미있다", pos: "형용사", ex: { zh: "这本书很有意思。", pinyin: "zhè běn shū hěn yǒu yì si。", ko: "이 책은 매우 재미있어요." } },
        { zh: "院", pinyin: "yuàn", ko: "마당, 기관", pos: "명사", ex: { zh: "这个院很安静。", pinyin: "zhè ge yuàn hěn ān jìng。", ko: "이 마당은 조용해요." } },
        { zh: "院长", pinyin: "yuànzhǎng", ko: "원장, 학장", pos: "명사", ex: { zh: "王教授是医学院院长。", pinyin: "wáng jiào shòu shì yī xué yuàn yuàn zhǎng。", ko: "왕 교수는 의과대학 학장이에요." } },
        { zh: "院子", pinyin: "yuànzi", ko: "마당, 뜰", pos: "명사", ex: { zh: "院子里种了很多花。", pinyin: "yuàn zi lǐ zhòng le hěn duō huā。", ko: "마당에는 많은 꽃이 심어져 있어요." } },
        { zh: "月份", pinyin: "yuèfèn", ko: "월, 달", pos: "명사", ex: { zh: "这个月份天气很热。", pinyin: "zhè ge yuè fèn tiān qì hěn rè。", ko: "이 달은 날씨가 더워요." } },
        { zh: "越来越", pinyin: "yuèláiyuè", ko: "점점 더", pos: "부사", ex: { zh: "天气越来越冷了。", pinyin: "tiān qì yuè lái yuè lěng le。", ko: "날씨가 점점 더 추워져요." } },
        { zh: "咱", pinyin: "zán", ko: "우리(구어체)", pos: "대명사", ex: { zh: "咱走吧。", pinyin: "zán zǒu ba。", ko: "우리 가자." } },
        { zh: "早餐", pinyin: "zǎocān", ko: "아침밥", pos: "명사", ex: { zh: "我每天七点吃早餐。", pinyin: "wǒ měi tiān qī diǎn chī zǎo cān。", ko: "나는 매일 7시에 아침을 먹어요." } },
        { zh: "早晨", pinyin: "zǎochén", ko: "아침, 새벽", pos: "명사", ex: { zh: "早晨的空气很新鲜。", pinyin: "zǎo chén de kōng qì hěn xīn xiān。", ko: "아침 공기는 매우 신선해요." } },
        { zh: "早就", pinyin: "zǎojiù", ko: "벌써, 진작", pos: "부사", ex: { zh: "他早就知道这件事了。", pinyin: "tā zǎo jiù zhī dào zhè jiàn shì le。", ko: "그는 이 일을 진작 알고 있었어요." } },
        { zh: "怎么办", pinyin: "zěnmebàn", ko: "어떻게 하지, 어떡하지", pos: "대명사", ex: { zh: "这件事怎么办？", pinyin: "zhè jiàn shì zěn me bàn?", ko: "이 일을 어떻게 하지?" } },
        { zh: "怎样", pinyin: "zěnyàng", ko: "어떻게, 어떤", pos: "대명사", ex: { zh: "你觉得这个方法怎样？", pinyin: "nǐ jué de zhè ge fāng fǎ zěn yàng?", ko: "너는 이 방법이 어떤 것 같니?" } },
        { zh: "占", pinyin: "zhàn", ko: "차지하다, 점하다", pos: "동사", ex: { zh: "这张桌子占了很大地方。", pinyin: "zhè zhāng zhuō zi zhàn le hěn dà dì fang。", ko: "이 책상은 많은 자리를 차지해요." } },
        { zh: "站住", pinyin: "zhànzhù", ko: "멈춰 서다", pos: "동사", ex: { zh: "他大喊一声：“站住！”", pinyin: "tā dà hǎn yì shēng: “zhàn zhù!”", ko: "그는 크게 외쳤다. “멈춰 서!”" } },
        { zh: "长大", pinyin: "zhǎngdà", ko: "자라다, 성장하다", pos: "동사", ex: { zh: "孩子们很快就长大了。", pinyin: "hái zi men hěn kuài jiù zhǎng dà le。", ko: "아이들은 금세 자라요." } },
        { zh: "找出", pinyin: "zhǎochū", ko: "찾아내다", pos: "동사", ex: { zh: "他终于找出了问题的原因。", pinyin: "tā zhōng yú zhǎo chū le wèn tí de yuán yīn。", ko: "그는 마침내 문제의 원인을 찾아냈어요." } },
        { zh: "照相", pinyin: "zhàoxiàng", ko: "사진을 찍다", pos: "동사", ex: { zh: "我们在公园照相。", pinyin: "wǒ men zài gōng yuán zhào xiàng。", ko: "우리는 공원에서 사진을 찍어요." } },
        { zh: "这么", pinyin: "zhème", ko: "이렇게, 이만큼", pos: "대명사", ex: { zh: "天气怎么这么冷？", pinyin: "tiān qì zěn me zhè me lěng?", ko: "날씨가 왜 이렇게 춥지?" } },
        { zh: "这时", pinyin: "zhèshí", ko: "이때", pos: "대명사", ex: { zh: "这时门开了。", pinyin: "zhè shí mén kāi le。", ko: "이때 문이 열렸어요." } },
        { zh: "这时候", pinyin: "zhè shíhòu", ko: "이때, 이 무렵", pos: "대명사", ex: { zh: "这时候他才想起来。", pinyin: "zhè shí hòu tā cái xiǎng qǐ lái。", ko: "이때가 되어서야 그는 생각이 났어요." } },
        { zh: "这样", pinyin: "zhèyàng", ko: "이렇게, 이런", pos: "대명사", ex: { zh: "你不应该这样做。", pinyin: "nǐ bù yīng gāi zhè yàng zuò。", ko: "너는 이렇게 해서는 안 돼요." } },
        { zh: "正是", pinyin: "zhèngshì", ko: "바로 ~이다", pos: "동사", ex: { zh: "这正是我想要的答案。", pinyin: "zhè zhèng shì wǒ xiǎng yào de dá àn。", ko: "이것이 바로 내가 원하는 답이에요." } },
        { zh: "只能", pinyin: "zhǐnéng", ko: "~할 수밖에 없다", pos: "동사", ex: { zh: "下雨了，我们只能在家。", pinyin: "xià yǔ le, wǒ men zhǐ néng zài jiā。", ko: "비가 와서 우리는 집에 있을 수밖에 없어요." } },
        { zh: "纸", pinyin: "zhǐ", ko: "종이", pos: "명사", ex: { zh: "请给我一张纸。", pinyin: "qǐng gěi wǒ yì zhāng zhǐ。", ko: "저에게 종이 한 장 주세요." } },
        { zh: "中餐", pinyin: "zhōngcān", ko: "중식, 중국 요리", pos: "명사", ex: { zh: "我喜欢吃中餐。", pinyin: "wǒ xǐ huan chī zhōng cān。", ko: "나는 중식 먹는 것을 좋아해요." } },
        { zh: "中级", pinyin: "zhōngjí", ko: "중급", pos: "형용사", ex: { zh: "他通过了中级考试。", pinyin: "tā tōng guò le zhōng jí kǎo shì。", ko: "그는 중급 시험에 합격했어요." } },
        { zh: "中年", pinyin: "zhōngnián", ko: "중년", pos: "명사", ex: { zh: "他已经是中年人了。", pinyin: "tā yǐ jīng shì zhōng nián rén le。", ko: "그는 이미 중년이 되었어요." } },
        { zh: "中小学", pinyin: "zhōngxiǎoxué", ko: "초중고, 초중등학교", pos: "명사", ex: { zh: "政府重视中小学教育。", pinyin: "zhèng fǔ zhòng shì zhōng xiǎo xué jiào yù。", ko: "정부는 초중등 교육을 중시해요." } },
        { zh: "中医", pinyin: "Zhōngyī", ko: "중의학, 한의사", pos: "명사", ex: { zh: "他去看中医治疗感冒。", pinyin: "Tā qù kàn Zhōng yī zhì liáo gǎn mào.", ko: "그는 감기를 치료하러 한의사에게 갔어요." } },
        { zh: "周", pinyin: "zhōu", ko: "주(성씨); 주(주간)", pos: "명사", ex: { zh: "这周他很忙。", pinyin: "Zhè zhōu tā hěn máng.", ko: "이번 주 그는 매우 바빠요." } },
        { zh: "周年", pinyin: "zhōunián", ko: "주년", pos: "양사", ex: { zh: "今年是他们结婚十周年。", pinyin: "Jīn nián shì tā men jié hūn shí zhōu nián.", ko: "올해는 그들의 결혼 10주년이에요." } },
        { zh: "住房", pinyin: "zhùfáng", ko: "주택", pos: "명사", ex: { zh: "政府正在解决住房问题。", pinyin: "Zhèng fǔ zhèng zài jiě jué zhù fáng wèn tí.", ko: "정부는 주택 문제를 해결하고 있어요." } },
        { zh: "住院", pinyin: "zhùyuàn", ko: "입원하다", pos: "동사", ex: { zh: "他因为生病住院了。", pinyin: "Tā yīn wèi shēng bìng zhù yuàn le.", ko: "그는 병이 나서 입원했어요." } },
        { zh: "走过", pinyin: "zǒuguò", ko: "지나가다", pos: "동사", ex: { zh: "他从我身边走过。", pinyin: "Tā cóng wǒ shēn biān zǒu guò.", ko: "그는 내 옆을 지나갔어요." } },
        { zh: "走进", pinyin: "zǒujìn", ko: "걸어 들어가다", pos: "동사", ex: { zh: "她走进教室坐下了。", pinyin: "Tā zǒu jìn jiào shì zuò xià le.", ko: "그녀는 교실로 걸어 들어가 앉았어요." } },
        { zh: "走开", pinyin: "zǒukāi", ko: "떠나다, 비키다", pos: "동사", ex: { zh: "请你走开,别挡路。", pinyin: "Qǐng nǐ zǒu kāi, bié dǎng lù.", ko: "좀 비켜 주세요, 길을 막지 마세요." } },
        { zh: "组", pinyin: "zǔ", ko: "조, 그룹; 성씨 조", pos: "명사", ex: { zh: "我们分成三个组讨论。", pinyin: "Wǒ men fēn chéng sān gè zǔ tǎo lùn.", ko: "우리는 세 개의 조로 나누어 토론해요." } },
        { zh: "组长", pinyin: "zǔzhǎng", ko: "조장, 그룹장", pos: "명사", ex: { zh: "他被选为小组的组长。", pinyin: "Tā bèi xuǎn wéi xiǎo zǔ de zǔ zhǎng.", ko: "그는 조의 조장으로 뽑혔어요." } },
        { zh: "作家", pinyin: "zuòjiā", ko: "작가", pos: "명사", ex: { zh: "她是一位有名的作家。", pinyin: "Tā shì yí wèi yǒu míng de zuò jiā.", ko: "그녀는 유명한 작가예요." } },
        { zh: "做到", pinyin: "zuòdào", ko: "해내다, 달성하다", pos: "동사", ex: { zh: "只要努力就能做到。", pinyin: "Zhǐ yào nǔ lì jiù néng zuò dào.", ko: "노력만 하면 해낼 수 있어요." } },
        { zh: "做饭", pinyin: "zuòfàn", ko: "밥을 짓다, 요리하다", pos: "동사", ex: { zh: "妈妈每天在家做饭。", pinyin: "Mā ma měi tiān zài jiā zuò fàn.", ko: "엄마는 매일 집에서 밥을 지어요." } },
      ],
    },
  ],
}

export default themes;
