/**
 * H2 (HSK 2급) 보강 어휘 — 표준 HSK2 어휘표 대비 누락분 53개를 채워요.
 * 동사·기능어(대명사·개사·접속사·조사)·명사와 기타 세 갈래로 묶었어요.
 */
const themes = {
  themes: [
    {
      name: "HSK2 보강 — 동사",
      icon: "🟪",
      words: [
        { zh: "穿", pinyin: "chuān", ko: "(옷을) 입다, 신다", pos: "동사", hanja: "천(穿) — '뚫을 천'이지만 중국어에선 '입다·신다'.", ex: { zh: "她穿着红色的衣服。", pinyin: "tā chuānzhe hóngsè de yīfu", ko: "그녀는 빨간 옷을 입고 있어요." } },
        { zh: "踢", pinyin: "tī", ko: "(발로) 차다", pos: "동사", ex: { zh: "孩子们在踢足球。", pinyin: "háizimen zài tī zúqiú", ko: "아이들이 축구를 하고 있어요." } },
        { zh: "跳舞", pinyin: "tiàowǔ", ko: "춤을 추다", pos: "동사", hanja: "도무(跳舞) — '跳'는 뛸 도, '舞'는 춤출 무.", ex: { zh: "我们一起跳舞吧。", pinyin: "wǒmen yìqǐ tiào wǔ ba", ko: "우리 같이 춤춰요." } },
        { zh: "打篮球", pinyin: "dǎlánqiú", ko: "농구를 하다", pos: "동사", hanja: "남구(籃球) — '籃'은 바구니 람, '球'는 공 구. 바구니에 넣는 공.", ex: { zh: "他喜欢打篮球。", pinyin: "tā xǐhuan dǎ lán qiú", ko: "그는 농구를 좋아해요." } },
        { zh: "洗", pinyin: "xǐ", ko: "씻다, 빨다", pos: "동사", hanja: "세(洗) — '씻을 세'.", ex: { zh: "我要洗手。", pinyin: "wǒ yào xǐ shǒu", ko: "저는 손을 씻으려고 해요." } },
        { zh: "问", pinyin: "wèn", ko: "묻다, 질문하다", pos: "동사", hanja: "문(問) — '물을 문'.", ex: { zh: "我想问你一个问题。", pinyin: "wǒ xiǎng wèn nǐ yí ge wèntí", ko: "한 가지 물어보고 싶어요." } },
        { zh: "姓", pinyin: "xìng", ko: "성이 ~이다, 성씨", pos: "동사", hanja: "성(姓) — '성씨 성'. 동사로 '성이 ~이다'.", ex: { zh: "我姓王。", pinyin: "wǒ xìng Wáng", ko: "제 성은 왕이에요." } },
        { zh: "让", pinyin: "ràng", ko: "~하게 하다, 시키다, 양보하다", pos: "동사", hanja: "양(讓) — '사양할 양'. 사역의 '시키다·하게 하다'.", ex: { zh: "妈妈让我早点回家。", pinyin: "māma ràng wǒ zǎodiǎn huí jiā", ko: "엄마가 저에게 일찍 집에 오라고 했어요." } },
        { zh: "生病", pinyin: "shēngbìng", ko: "병이 나다, 아프다", pos: "동사", hanja: "생병(生病) — '生'은 날 생, '病'은 병 병. 병이 '생기다'.", ex: { zh: "他生病了，没来上课。", pinyin: "tā shēng bìng le, méi lái shàngkè", ko: "그는 아파서 수업에 안 왔어요." } },
        { zh: "可能", pinyin: "kěnéng", ko: "~일지도 모른다, 아마, 가능성", pos: "동사", hanja: "가능(可能) — 한자 그대로. '~할 수도 있다'.", ex: { zh: "他可能不来了。", pinyin: "tā kěnéng bù lái le", ko: "그는 아마 안 올 거예요." } },
        { zh: "可以", pinyin: "kěyǐ", ko: "~해도 된다, ~할 수 있다", pos: "동사", hanja: "가이(可以) — '可'는 옳을 가. 허락·가능을 나타내요.", ex: { zh: "我可以进来吗？", pinyin: "wǒ kěyǐ jìnlái ma", ko: "들어가도 될까요?" } },
        { zh: "得", pinyin: "dé", ko: "얻다, 받다", pos: "동사", hanja: "득(得) — '얻을 득'.", ex: { zh: "他得了第一名。", pinyin: "tā dé le dì yī míng", ko: "그는 1등을 했어요." } },
      ],
    },
    {
      name: "HSK2 보강 — 대명사·기능어",
      icon: "🟪",
      words: [
        { zh: "您", pinyin: "nín", ko: "당신 (높임말)", pos: "대명사", ex: { zh: "您好！请坐。", pinyin: "nín hǎo! qǐng zuò", ko: "안녕하세요! 앉으세요." } },
        { zh: "它", pinyin: "tā", ko: "그것 (사물·동물)", pos: "대명사", ex: { zh: "这是我的狗，它很可爱。", pinyin: "zhè shì wǒ de gǒu, tā hěn kě'ài", ko: "이건 제 강아지인데, 정말 귀여워요." } },
        { zh: "每", pinyin: "měi", ko: "매, 각, ~마다", pos: "대명사", hanja: "매(每) — '매양 매'.", ex: { zh: "我每天都喝牛奶。", pinyin: "wǒ měi tiān dōu hē niúnǎi", ko: "저는 매일 우유를 마셔요." } },
        { zh: "比", pinyin: "bǐ", ko: "~보다 (비교)", pos: "개사", hanja: "비(比) — '견줄 비'. 'A 比 B + 형용사'로 비교해요.", ex: { zh: "今天比昨天热。", pinyin: "jīntiān bǐ zuótiān rè", ko: "오늘이 어제보다 더워요." } },
        { zh: "给", pinyin: "gěi", ko: "~에게 (주다)", pos: "개사", ex: { zh: "我给你打电话。", pinyin: "wǒ gěi nǐ dǎ diànhuà", ko: "제가 당신에게 전화할게요." } },
        { zh: "为", pinyin: "wèi", ko: "~을 위하여, ~때문에", pos: "개사", hanja: "위(爲) — '할 위'. '为了'로 '~을 위해서'.", ex: { zh: "我为你高兴。", pinyin: "wǒ wèi nǐ gāoxìng", ko: "당신 일이 잘돼서 기뻐요." } },
        { zh: "向", pinyin: "xiàng", ko: "~을 향하여, ~에게", pos: "개사", hanja: "향(向) — '향할 향'. 방향·대상을 가리켜요.", ex: { zh: "请向前走。", pinyin: "qǐng xiàng qián zǒu", ko: "앞으로 가세요." } },
        { zh: "因为", pinyin: "yīnwèi", ko: "~때문에, 왜냐하면", pos: "접속사", hanja: "인위(因爲) — '因'은 인할 인. '因为…所以…' 구문으로 자주 써요.", ex: { zh: "因为下雨，我没去。", pinyin: "yīnwèi xià yǔ, wǒ méi qù", ko: "비가 와서 저는 안 갔어요." } },
        { zh: "所以", pinyin: "suǒyǐ", ko: "그래서, 그러므로", pos: "접속사", hanja: "소이(所以) — 한국어 '소이(까닭)'와 글자는 같아요. '因为…所以…'로 짝을 이뤄요.", ex: { zh: "他病了，所以没来。", pinyin: "tā bìng le, suǒyǐ méi lái", ko: "그는 아파서 안 왔어요." } },
        { zh: "但是", pinyin: "dànshì", ko: "그러나, 하지만", pos: "접속사", hanja: "단시(但是) — '但'은 다만 단. '다만 ~이다', 즉 '하지만'.", ex: { zh: "他很累，但是很高兴。", pinyin: "tā hěn lèi, dànshì hěn gāoxìng", ko: "그는 피곤하지만 기뻐요." } },
        { zh: "吧", pinyin: "ba", ko: "~하자, ~겠지 (권유·추측의 어기조사)", pos: "조사", ex: { zh: "我们走吧。", pinyin: "wǒmen zǒu ba", ko: "우리 가요." } },
        { zh: "着", pinyin: "zhe", ko: "~하고 있다, ~한 채로 (지속의 조사)", pos: "조사", ex: { zh: "门开着。", pinyin: "mén kāizhe", ko: "문이 열려 있어요." } },
        { zh: "别", pinyin: "bié", ko: "~하지 마라", pos: "부사", hanja: "별(別) — '다를 별'이지만 여기선 금지의 '~하지 마'.", ex: { zh: "别说话！", pinyin: "bié shuōhuà", ko: "말하지 마세요!" } },
        { zh: "就", pinyin: "jiù", ko: "곧, 바로, 즉시", pos: "부사", hanja: "취(就) — '나아갈 취'. '바로·곧'의 어감.", ex: { zh: "我马上就来。", pinyin: "wǒ mǎshàng jiù lái", ko: "제가 바로 올게요." } },
        { zh: "再", pinyin: "zài", ko: "다시, 또, 더", pos: "부사", hanja: "재(再) — '두 재'. '재차'의 그 재.", ex: { zh: "请再说一遍。", pinyin: "qǐng zài shuō yí biàn", ko: "다시 한 번 말해 주세요." } },
        { zh: "非常", pinyin: "fēicháng", ko: "매우, 대단히", pos: "부사", hanja: "비상(非常) — '常'은 항상 상. '보통이 아닌', 즉 '매우'.", ex: { zh: "这个菜非常好吃。", pinyin: "zhège cài fēicháng hǎochī", ko: "이 요리는 정말 맛있어요." } },
        { zh: "正在", pinyin: "zhèngzài", ko: "~하고 있다, 한창 ~중이다", pos: "부사", hanja: "정재(正在) — '正'은 바를 정. 진행을 나타내요.", ex: { zh: "他正在睡觉。", pinyin: "tā zhèngzài shuìjiào", ko: "그는 지금 자고 있어요." } },
        { zh: "要", pinyin: "yào", ko: "~하려고 하다, 원하다, 필요하다", pos: "동사", hanja: "요(要) — '요긴할 요'. 의지·필요를 나타내요.", ex: { zh: "我要喝水。", pinyin: "wǒ yào hē shuǐ", ko: "저는 물을 마시고 싶어요." } },
        { zh: "第一", pinyin: "dìyī", ko: "첫째, 제일, 1위", pos: "수사", hanja: "제일(第一) — 한자 그대로. 서수 '첫 번째'.", ex: { zh: "他是第一名。", pinyin: "tā shì dì yī míng", ko: "그는 1등이에요." } },
        { zh: "两", pinyin: "liǎng", ko: "둘, 2 (양사 앞에서)", pos: "수사", hanja: "량(兩) — '두 량'. 양사 앞에서는 二 대신 两을 써요.", ex: { zh: "我有两个哥哥。", pinyin: "wǒ yǒu liǎng ge gēge", ko: "저는 형이 두 명 있어요." } },
        { zh: "千", pinyin: "qiān", ko: "천, 1000", pos: "수사", hanja: "천(千) — '일천 천'.", ex: { zh: "这本书一千块。", pinyin: "zhè běn shū yìqiān kuài", ko: "이 책은 천 위안이에요." } },
        { zh: "件", pinyin: "jiàn", ko: "벌, 건 (옷·일을 세는 양사)", pos: "양사", hanja: "건(件) — '물건 건'. 옷·일·사건 등을 세요.", ex: { zh: "我买了一件衣服。", pinyin: "wǒ mǎi le yí jiàn yīfu", ko: "저는 옷을 한 벌 샀어요." } },
        { zh: "张", pinyin: "zhāng", ko: "장 (종이·평면을 세는 양사)", pos: "양사", hanja: "장(張) — '베풀 장'. 종이·표·침대 등 평평한 것을 세요.", ex: { zh: "给我一张纸。", pinyin: "gěi wǒ yì zhāng zhǐ", ko: "종이 한 장 주세요." } },
        { zh: "公斤", pinyin: "gōngjīn", ko: "킬로그램", pos: "양사", hanja: "공근(公斤) — '斤'은 무게 단위 근. '공식 근', 즉 킬로그램.", ex: { zh: "我买了两公斤苹果。", pinyin: "wǒ mǎi le liǎng gōngjīn píngguǒ", ko: "저는 사과를 2킬로그램 샀어요." } },
        { zh: "元", pinyin: "yuán", ko: "위안 (화폐 단위)", pos: "양사", hanja: "원(元) — '으뜸 원'. 块의 공식 표기예요.", ex: { zh: "这个十元。", pinyin: "zhège shí yuán", ko: "이건 10위안이에요." } },
      ],
    },
    {
      name: "HSK2 보강 — 명사·기타",
      icon: "🟪",
      words: [
        { zh: "报纸", pinyin: "bàozhǐ", ko: "신문", pos: "명사", hanja: "보지(報紙) — '報'는 알릴 보, '紙'는 종이 지. '알리는 종이'.", ex: { zh: "爸爸每天看报纸。", pinyin: "bàba měi tiān kàn bàozhǐ", ko: "아빠는 매일 신문을 봐요." } },
        { zh: "服务员", pinyin: "fúwùyuán", ko: "종업원, 점원", pos: "명사", hanja: "복무원(服務員) — '服務'는 복무·서비스, '員'은 인원 원.", ex: { zh: "服务员，买单！", pinyin: "fúwùyuán, mǎidān", ko: "저기요, 계산해 주세요!" } },
        { zh: "男人", pinyin: "nánrén", ko: "남자", pos: "명사", hanja: "남인(男人) — '男'은 사내 남, '人'은 사람 인.", ex: { zh: "那个男人是我哥哥。", pinyin: "nàge nánrén shì wǒ gēge", ko: "저 남자는 제 형이에요." } },
        { zh: "女人", pinyin: "nǚrén", ko: "여자", pos: "명사", hanja: "여인(女人) — 한국어 '여인'과 같은 글자.", ex: { zh: "那个女人是医生。", pinyin: "nàge nǚrén shì yīshēng", ko: "저 여자는 의사예요." } },
        { zh: "课", pinyin: "kè", ko: "수업, 과목, 과", pos: "명사", hanja: "과(課) — '공부할 과'. 한국어 '과목·1과'의 그 과.", ex: { zh: "我今天有三节课。", pinyin: "wǒ jīntiān yǒu sān jié kè", ko: "저는 오늘 수업이 세 개 있어요." } },
        { zh: "题", pinyin: "tí", ko: "문제, 제목", pos: "명사", hanja: "제(題) — '제목 제'. '문제·시험 문제'.", ex: { zh: "这个题太难了。", pinyin: "zhège tí tài nán le", ko: "이 문제는 너무 어려워요." } },
        { zh: "时间", pinyin: "shíjiān", ko: "시간", pos: "명사", hanja: "시간(時間) — 한자 그대로.", ex: { zh: "我没有时间。", pinyin: "wǒ méiyǒu shíjiān", ko: "저는 시간이 없어요." } },
        { zh: "事情", pinyin: "shìqing", ko: "일, 사건", pos: "명사", hanja: "사정(事情) — '事'는 일 사, '情'은 뜻 정. '일·용무'.", ex: { zh: "我有事情要做。", pinyin: "wǒ yǒu shìqing yào zuò", ko: "저는 할 일이 있어요." } },
        { zh: "手表", pinyin: "shǒubiǎo", ko: "손목시계", pos: "명사", hanja: "수표(手錶) — '手'는 손 수, '錶'는 시계. 손에 차는 시계.", ex: { zh: "这块手表很贵。", pinyin: "zhè kuài shǒubiǎo hěn guì", ko: "이 손목시계는 비싸요." } },
        { zh: "颜色", pinyin: "yánsè", ko: "색, 색깔", pos: "명사", hanja: "안색(顏色) — '顏'은 얼굴 안, '色'은 빛 색. 한국어 '안색(낯빛)'과 달리 '색깔'이에요.", ex: { zh: "你喜欢什么颜色？", pinyin: "nǐ xǐhuan shénme yánsè", ko: "무슨 색을 좋아해요?" } },
        { zh: "药", pinyin: "yào", ko: "약", pos: "명사", hanja: "약(藥) — '약 약'.", ex: { zh: "你要吃药。", pinyin: "nǐ yào chī yào", ko: "약을 먹어야 해요." } },
        { zh: "快乐", pinyin: "kuàilè", ko: "즐겁다, 행복하다", pos: "형용사", hanja: "쾌락(快樂) — '快'는 쾌할 쾌, '樂'는 즐거울 락.", ex: { zh: "祝你生日快乐！", pinyin: "zhù nǐ shēngrì kuàilè", ko: "생일 축하해요!" } },
        { zh: "旁边", pinyin: "pángbiān", ko: "옆, 곁", pos: "명사", hanja: "방변(旁邊) — '旁'은 곁 방, '邊'은 가 변.", ex: { zh: "银行在学校旁边。", pinyin: "yínháng zài xuéxiào pángbiān", ko: "은행은 학교 옆에 있어요." } },
        { zh: "左边", pinyin: "zuǒbian", ko: "왼쪽", pos: "명사", hanja: "좌변(左邊) — '左'는 왼 좌, '邊'은 가 변.", ex: { zh: "商店在左边。", pinyin: "shāngdiàn zài zuǒbian", ko: "가게는 왼쪽에 있어요." } },
        { zh: "右边", pinyin: "yòubian", ko: "오른쪽", pos: "명사", hanja: "우변(右邊) — '右'는 오른 우, '邊'은 가 변.", ex: { zh: "医院在右边。", pinyin: "yīyuàn zài yòubian", ko: "병원은 오른쪽에 있어요." } },
        { zh: "外", pinyin: "wài", ko: "밖, 바깥", pos: "명사", hanja: "외(外) — '바깥 외'.", ex: { zh: "他在外面等你。", pinyin: "tā zài wàimiàn děng nǐ", ko: "그가 밖에서 기다리고 있어요." } },
      ],
    },
  ],
};

export default themes;
