/**
 * H3 (HSK 3급) 어휘 — 의견·계획·감정을 말하는 중급 진입 단계.
 * 사람과 사회·시간과 계획·학습과 일·동작과 소통·감정과 형용사·장소와 생활 여섯 테마.
 */
export default {
  level: "H3",
  title: "3급 어휘",
  desc: "의견을 말하고 계획을 세우는 단계로 — 학습·직장·감정·여행까지 다루는 HSK 3급 핵심 어휘 90여 개예요.",
  themes: [
    {
      name: "사람과 사회",
      words: [
        { zh: "邻居", pinyin: "línjū", ko: "이웃", pos: "명사", hanja: "인거(隣居) — '隣'은 이웃 린, '居'는 살 거.", ex: { zh: "我的邻居很热情。", pinyin: "wǒ de línjū hěn rèqíng", ko: "제 이웃은 친절해요." } },
        { zh: "校长", pinyin: "xiàozhǎng", ko: "교장", pos: "명사", hanja: "교장(校長) — 한자 그대로.", ex: { zh: "校长在办公室。", pinyin: "xiàozhǎng zài bàngōngshì", ko: "교장 선생님은 사무실에 계세요." } },
        { zh: "经理", pinyin: "jīnglǐ", ko: "매니저, 부장", pos: "명사", hanja: "경리(經理) — '經'은 다스릴 경, '理'는 다스릴 리. 한국 '경리'와 뜻이 달라요!", ex: { zh: "他是我们的经理。", pinyin: "tā shì wǒmen de jīnglǐ", ko: "그는 우리 매니저예요." } },
        { zh: "客人", pinyin: "kèrén", ko: "손님", pos: "명사", hanja: "객인(客人) — '客'은 손 객.", ex: { zh: "今天家里有客人。", pinyin: "jīntiān jiā lǐ yǒu kèrén", ko: "오늘 집에 손님이 와요." } },
        { zh: "关系", pinyin: "guānxi", ko: "관계", pos: "명사", hanja: "관계(關係) — 한자 그대로. '没关系'는 '괜찮다'.", ex: { zh: "他们的关系很好。", pinyin: "tāmen de guānxi hěn hǎo", ko: "그들의 사이는 좋아요." } },
        { zh: "习惯", pinyin: "xíguàn", ko: "습관, 익숙하다", pos: "명사", hanja: "습관(習慣) — 한자 그대로.", ex: { zh: "早起是好习惯。", pinyin: "zǎo qǐ shì hǎo xíguàn", ko: "일찍 일어나는 건 좋은 습관이에요." } },
        { zh: "文化", pinyin: "wénhuà", ko: "문화", pos: "명사", hanja: "문화(文化) — 한자 그대로.", ex: { zh: "我对中国文化很感兴趣。", pinyin: "wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù", ko: "저는 중국 문화에 관심이 많아요." } },
        { zh: "历史", pinyin: "lìshǐ", ko: "역사", pos: "명사", hanja: "역사(歷史) — 한자 그대로.", ex: { zh: "我喜欢学历史。", pinyin: "wǒ xǐhuan xué lìshǐ", ko: "저는 역사 배우는 걸 좋아해요." } },
        { zh: "国家", pinyin: "guójiā", ko: "국가, 나라", pos: "명사", hanja: "국가(國家) — 한자 그대로.", ex: { zh: "中国是一个大国家。", pinyin: "Zhōngguó shì yí ge dà guójiā", ko: "중국은 큰 나라예요." } },
        { zh: "世界", pinyin: "shìjiè", ko: "세계", pos: "명사", hanja: "세계(世界) — 한자 그대로.", ex: { zh: "我想看看世界。", pinyin: "wǒ xiǎng kànkan shìjiè", ko: "저는 세계를 둘러보고 싶어요." } },
        { zh: "意思", pinyin: "yìsi", ko: "뜻, 의미", pos: "명사", hanja: "의사(意思) — '意'는 뜻 의. '뜻'을 가리켜요.", ex: { zh: "这个词是什么意思？", pinyin: "zhège cí shì shénme yìsi", ko: "이 단어는 무슨 뜻이에요?" } },
        { zh: "故事", pinyin: "gùshi", ko: "이야기", pos: "명사", hanja: "고사(故事) — '故'는 옛 고. 한국 '고사성어'의 고사.", ex: { zh: "奶奶给我讲故事。", pinyin: "nǎinai gěi wǒ jiǎng gùshi", ko: "할머니가 저에게 이야기를 들려주세요." } },
      ],
    },
    {
      name: "시간과 계획",
      words: [
        { zh: "周末", pinyin: "zhōumò", ko: "주말", pos: "명사", hanja: "주말(週末) — 한자 그대로.", ex: { zh: "周末我们去爬山。", pinyin: "zhōumò wǒmen qù páshān", ko: "주말에 우리 등산 가요." } },
        { zh: "季节", pinyin: "jìjié", ko: "계절", pos: "명사", hanja: "계절(季節) — 한자 그대로.", ex: { zh: "我最喜欢的季节是秋天。", pinyin: "wǒ zuì xǐhuan de jìjié shì qiūtiān", ko: "제가 가장 좋아하는 계절은 가을이에요." } },
        { zh: "春", pinyin: "chūn", ko: "봄", pos: "명사", hanja: "춘(春) — '봄 춘'.", ex: { zh: "春天天气很好。", pinyin: "chūntiān tiānqì hěn hǎo", ko: "봄은 날씨가 좋아요." } },
        { zh: "夏", pinyin: "xià", ko: "여름", pos: "명사", hanja: "하(夏) — '여름 하'.", ex: { zh: "夏天很热。", pinyin: "xiàtiān hěn rè", ko: "여름은 더워요." } },
        { zh: "秋", pinyin: "qiū", ko: "가을", pos: "명사", hanja: "추(秋) — '가을 추'.", ex: { zh: "秋天不冷不热。", pinyin: "qiūtiān bù lěng bú rè", ko: "가을은 춥지도 덥지도 않아요." } },
        { zh: "冬", pinyin: "dōng", ko: "겨울", pos: "명사", hanja: "동(冬) — '겨울 동'.", ex: { zh: "冬天会下雪。", pinyin: "dōngtiān huì xià xuě", ko: "겨울에는 눈이 와요." } },
        { zh: "以前", pinyin: "yǐqián", ko: "이전, 예전", pos: "명사", hanja: "이전(以前) — 한자 그대로.", ex: { zh: "以前我不会说汉语。", pinyin: "yǐqián wǒ bú huì shuō Hànyǔ", ko: "예전엔 중국어를 할 줄 몰랐어요." } },
        { zh: "以后", pinyin: "yǐhòu", ko: "이후, 나중", pos: "명사", hanja: "이후(以後) — 한자 그대로.", ex: { zh: "下课以后我们去吃饭。", pinyin: "xiàkè yǐhòu wǒmen qù chī fàn", ko: "수업 후에 우리 밥 먹으러 가요." } },
        { zh: "刚才", pinyin: "gāngcái", ko: "방금, 막", pos: "명사", ex: { zh: "他刚才还在这儿。", pinyin: "tā gāngcái hái zài zhèr", ko: "그는 방금까지 여기 있었어요." } },
        { zh: "一直", pinyin: "yìzhí", ko: "줄곧, 계속", pos: "부사", hanja: "일직(一直) — '直'은 곧을 직. '한결같이'.", ex: { zh: "我一直在等你。", pinyin: "wǒ yìzhí zài děng nǐ", ko: "저는 계속 당신을 기다리고 있었어요." } },
        { zh: "总是", pinyin: "zǒngshì", ko: "늘, 항상", pos: "부사", hanja: "총시(總是) — '總'은 거느릴 총.", ex: { zh: "他总是很忙。", pinyin: "tā zǒngshì hěn máng", ko: "그는 늘 바빠요." } },
        { zh: "终于", pinyin: "zhōngyú", ko: "드디어, 마침내", pos: "부사", hanja: "종어(終於) — '終'은 마칠 종.", ex: { zh: "我终于到了。", pinyin: "wǒ zhōngyú dào le", ko: "저는 드디어 도착했어요." } },
      ],
    },
    {
      name: "학습과 일",
      words: [
        { zh: "复习", pinyin: "fùxí", ko: "복습하다", pos: "동사", hanja: "복습(復習) — 한자 그대로.", ex: { zh: "考试以前要复习。", pinyin: "kǎoshì yǐqián yào fùxí", ko: "시험 전에는 복습해야 해요." } },
        { zh: "练习", pinyin: "liànxí", ko: "연습하다", pos: "동사", hanja: "연습(練習) — 한자 그대로.", ex: { zh: "我每天练习说汉语。", pinyin: "wǒ měi tiān liànxí shuō Hànyǔ", ko: "저는 매일 중국어 말하기를 연습해요." } },
        { zh: "教", pinyin: "jiāo", ko: "가르치다", pos: "동사", hanja: "교(敎) — '가르칠 교'.", ex: { zh: "老师教我们汉语。", pinyin: "lǎoshī jiāo wǒmen Hànyǔ", ko: "선생님이 우리에게 중국어를 가르쳐요." } },
        { zh: "成绩", pinyin: "chéngjì", ko: "성적", pos: "명사", hanja: "성적(成績) — 한자 그대로.", ex: { zh: "她的成绩很好。", pinyin: "tā de chéngjì hěn hǎo", ko: "그녀의 성적은 좋아요." } },
        { zh: "考试", pinyin: "kǎoshì", ko: "시험", pos: "명사", hanja: "고시(考試) — '考'는 상고할 고, '試'는 시험할 시.", ex: { zh: "明天有考试。", pinyin: "míngtiān yǒu kǎoshì", ko: "내일 시험이 있어요." } },
        { zh: "问题", pinyin: "wèntí", ko: "문제, 질문", pos: "명사", hanja: "문제(問題) — 한자 그대로.", ex: { zh: "我有一个问题。", pinyin: "wǒ yǒu yí ge wèntí", ko: "저 질문이 하나 있어요." } },
        { zh: "回答", pinyin: "huídá", ko: "대답하다", pos: "동사", hanja: "회답(回答) — 한자 그대로.", ex: { zh: "请回答我的问题。", pinyin: "qǐng huídá wǒ de wèntí", ko: "제 질문에 답해 주세요." } },
        { zh: "解决", pinyin: "jiějué", ko: "해결하다", pos: "동사", hanja: "해결(解決) — 한자 그대로.", ex: { zh: "这个问题很难解决。", pinyin: "zhège wèntí hěn nán jiějué", ko: "이 문제는 해결하기 어려워요." } },
        { zh: "努力", pinyin: "nǔlì", ko: "노력하다, 열심히", pos: "동사", hanja: "노력(努力) — 한자 그대로.", ex: { zh: "他学习很努力。", pinyin: "tā xuéxí hěn nǔlì", ko: "그는 공부를 열심히 해요." } },
        { zh: "完成", pinyin: "wánchéng", ko: "완성하다, 끝내다", pos: "동사", hanja: "완성(完成) — 한자 그대로.", ex: { zh: "我已经完成作业了。", pinyin: "wǒ yǐjīng wánchéng zuòyè le", ko: "저는 이미 숙제를 끝냈어요." } },
        { zh: "办公室", pinyin: "bàngōngshì", ko: "사무실", pos: "명사", hanja: "판공실(辦公室) — '辦'은 힘쓸 판, '公'은 공무.", ex: { zh: "经理在办公室。", pinyin: "jīnglǐ zài bàngōngshì", ko: "매니저는 사무실에 있어요." } },
        { zh: "会议", pinyin: "huìyì", ko: "회의", pos: "명사", hanja: "회의(會議) — 한자 그대로.", ex: { zh: "下午有一个会议。", pinyin: "xiàwǔ yǒu yí ge huìyì", ko: "오후에 회의가 하나 있어요." } },
      ],
    },
    {
      name: "동작과 소통",
      words: [
        { zh: "用", pinyin: "yòng", ko: "쓰다, 사용하다", pos: "동사", hanja: "용(用) — '쓸 용'.", ex: { zh: "我用手机看新闻。", pinyin: "wǒ yòng shǒujī kàn xīnwén", ko: "저는 휴대폰으로 뉴스를 봐요." } },
        { zh: "带", pinyin: "dài", ko: "지니다, 데리고 가다", pos: "동사", ex: { zh: "别忘了带护照。", pinyin: "bié wàng le dài hùzhào", ko: "여권 챙기는 걸 잊지 마세요." } },
        { zh: "拿", pinyin: "ná", ko: "(손으로) 들다, 가지다", pos: "동사", ex: { zh: "请拿一下这个包。", pinyin: "qǐng ná yíxià zhège bāo", ko: "이 가방 좀 들어 주세요." } },
        { zh: "放", pinyin: "fàng", ko: "놓다, 두다", pos: "동사", hanja: "방(放) — '놓을 방'.", ex: { zh: "把书放在桌子上。", pinyin: "bǎ shū fàng zài zhuōzi shàng", ko: "책을 탁자 위에 놓으세요." } },
        { zh: "搬", pinyin: "bān", ko: "옮기다, 이사하다", pos: "동사", ex: { zh: "我下个月搬家。", pinyin: "wǒ xià ge yuè bānjiā", ko: "저는 다음 달에 이사해요." } },
        { zh: "选择", pinyin: "xuǎnzé", ko: "선택하다", pos: "동사", hanja: "선택(選擇) — 한자 그대로.", ex: { zh: "你可以自己选择。", pinyin: "nǐ kěyǐ zìjǐ xuǎnzé", ko: "당신이 직접 선택할 수 있어요." } },
        { zh: "决定", pinyin: "juédìng", ko: "결정하다", pos: "동사", hanja: "결정(決定) — 한자 그대로.", ex: { zh: "我决定去中国留学。", pinyin: "wǒ juédìng qù Zhōngguó liúxué", ko: "저는 중국 유학을 가기로 결정했어요." } },
        { zh: "同意", pinyin: "tóngyì", ko: "동의하다", pos: "동사", hanja: "동의(同意) — 한자 그대로.", ex: { zh: "我同意你的意见。", pinyin: "wǒ tóngyì nǐ de yìjiàn", ko: "저는 당신 의견에 동의해요." } },
        { zh: "告诉", pinyin: "gàosu", ko: "알리다, 말하다", pos: "동사", hanja: "고소(告訴) — '告'는 알릴 고. 한국 '고소(소송)'와 뜻이 달라요!", ex: { zh: "请告诉我你的电话号码。", pinyin: "qǐng gàosu wǒ nǐ de diànhuà hàomǎ", ko: "전화번호를 알려 주세요." } },
        { zh: "认为", pinyin: "rènwéi", ko: "여기다, ~라고 생각하다", pos: "동사", hanja: "인위(認爲) — '認'은 알 인, '爲'는 할 위.", ex: { zh: "我认为这样很好。", pinyin: "wǒ rènwéi zhèyàng hěn hǎo", ko: "저는 이게 좋다고 생각해요." } },
        { zh: "相信", pinyin: "xiāngxìn", ko: "믿다", pos: "동사", hanja: "상신(相信) — '信'은 믿을 신.", ex: { zh: "我相信你。", pinyin: "wǒ xiāngxìn nǐ", ko: "저는 당신을 믿어요." } },
        { zh: "记得", pinyin: "jìde", ko: "기억하다", pos: "동사", hanja: "기득(記得) — '記'는 기록할 기.", ex: { zh: "你还记得他吗？", pinyin: "nǐ hái jìde tā ma", ko: "그를 아직 기억해요?" } },
        { zh: "担心", pinyin: "dānxīn", ko: "걱정하다", pos: "동사", hanja: "담심(擔心) — '擔'은 멜 담, '心'은 마음. '마음을 짊어지다'.", ex: { zh: "别担心，没问题。", pinyin: "bié dānxīn, méi wèntí", ko: "걱정 마세요, 괜찮아요." } },
        { zh: "需要", pinyin: "xūyào", ko: "필요하다", pos: "동사", hanja: "수요(需要) — '需'는 구할 수, '要'는 요긴할 요.", ex: { zh: "你需要帮助吗？", pinyin: "nǐ xūyào bāngzhù ma", ko: "도움이 필요해요?" } },
      ],
    },
    {
      name: "감정과 형용사",
      words: [
        { zh: "重要", pinyin: "zhòngyào", ko: "중요하다", pos: "형용사", hanja: "중요(重要) — 한자 그대로.", ex: { zh: "这件事很重要。", pinyin: "zhè jiàn shì hěn zhòngyào", ko: "이 일은 중요해요." } },
        { zh: "简单", pinyin: "jiǎndān", ko: "간단하다", pos: "형용사", hanja: "간단(簡單) — 한자 그대로.", ex: { zh: "这个问题很简单。", pinyin: "zhège wèntí hěn jiǎndān", ko: "이 문제는 간단해요." } },
        { zh: "容易", pinyin: "róngyì", ko: "쉽다", pos: "형용사", hanja: "용이(容易) — '容'은 얼굴 용, '易'는 쉬울 이.", ex: { zh: "汉语不太容易。", pinyin: "Hànyǔ bú tài róngyì", ko: "중국어는 그리 쉽지 않아요." } },
        { zh: "难", pinyin: "nán", ko: "어렵다", pos: "형용사", hanja: "난(難) — '어려울 난'.", ex: { zh: "这个字很难写。", pinyin: "zhège zì hěn nán xiě", ko: "이 글자는 쓰기 어려워요." } },
        { zh: "清楚", pinyin: "qīngchu", ko: "분명하다, 뚜렷하다", pos: "형용사", hanja: "청초(淸楚) — '淸'은 맑을 청.", ex: { zh: "我没听清楚。", pinyin: "wǒ méi tīng qīngchu", ko: "저는 잘 못 들었어요." } },
        { zh: "安静", pinyin: "ānjìng", ko: "조용하다", pos: "형용사", hanja: "안정(安靜) — '安'은 편안 안, '靜'은 고요할 정.", ex: { zh: "图书馆里很安静。", pinyin: "túshūguǎn lǐ hěn ānjìng", ko: "도서관 안은 조용해요." } },
        { zh: "热情", pinyin: "rèqíng", ko: "친절하다, 열정적이다", pos: "형용사", hanja: "열정(熱情) — 한자 그대로. 사람한테 쓰면 '다정하다'.", ex: { zh: "服务员很热情。", pinyin: "fúwùyuán hěn rèqíng", ko: "종업원이 친절해요." } },
        { zh: "健康", pinyin: "jiànkāng", ko: "건강하다, 건강", pos: "형용사", hanja: "건강(健康) — 한자 그대로.", ex: { zh: "运动让我们更健康。", pinyin: "yùndòng ràng wǒmen gèng jiànkāng", ko: "운동은 우리를 더 건강하게 해요." } },
        { zh: "奇怪", pinyin: "qíguài", ko: "이상하다", pos: "형용사", hanja: "기괴(奇怪) — '奇'는 기이할 기.", ex: { zh: "这件事很奇怪。", pinyin: "zhè jiàn shì hěn qíguài", ko: "이 일은 이상해요." } },
        { zh: "满意", pinyin: "mǎnyì", ko: "만족하다", pos: "형용사", hanja: "만의(滿意) — '滿'은 찰 만, '意'는 뜻 의. '마음에 차다'.", ex: { zh: "我对结果很满意。", pinyin: "wǒ duì jiéguǒ hěn mǎnyì", ko: "저는 결과에 만족해요." } },
        { zh: "着急", pinyin: "zháojí", ko: "초조하다, 조급하다", pos: "형용사", hanja: "착급(着急) — '急'은 급할 급.", ex: { zh: "别着急，慢慢来。", pinyin: "bié zháojí, mànmàn lái", ko: "조급해하지 말고 천천히 하세요." } },
        { zh: "害怕", pinyin: "hàipà", ko: "무서워하다, 두렵다", pos: "동사", ex: { zh: "我有点害怕。", pinyin: "wǒ yǒudiǎn hàipà", ko: "저는 좀 무서워요." } },
        { zh: "生气", pinyin: "shēngqì", ko: "화나다", pos: "형용사", hanja: "생기(生氣) — '화가 생기다'. 한국 '생기(활력)'와 뜻이 달라요!", ex: { zh: "他生气了。", pinyin: "tā shēngqì le", ko: "그는 화났어요." } },
      ],
    },
    {
      name: "장소와 생활",
      words: [
        { zh: "银行", pinyin: "yínháng", ko: "은행", pos: "명사", hanja: "은행(銀行) — 한자 그대로. '行'은 여기서 'háng'으로 읽어요.", ex: { zh: "我去银行取钱。", pinyin: "wǒ qù yínháng qǔ qián", ko: "저는 돈을 찾으러 은행에 가요." } },
        { zh: "图书馆", pinyin: "túshūguǎn", ko: "도서관", pos: "명사", hanja: "도서관(圖書館) — 한자 그대로.", ex: { zh: "我在图书馆学习。", pinyin: "wǒ zài túshūguǎn xuéxí", ko: "저는 도서관에서 공부해요." } },
        { zh: "公园", pinyin: "gōngyuán", ko: "공원", pos: "명사", hanja: "공원(公園) — 한자 그대로.", ex: { zh: "我们去公园散步吧。", pinyin: "wǒmen qù gōngyuán sànbù ba", ko: "우리 공원에 산책하러 가요." } },
        { zh: "宾馆", pinyin: "bīnguǎn", ko: "호텔", pos: "명사", hanja: "빈관(賓館) — '賓'은 손 빈, '館'은 집 관. '손님 묵는 집'.", ex: { zh: "我们住在宾馆。", pinyin: "wǒmen zhù zài bīnguǎn", ko: "우리는 호텔에 묵어요." } },
        { zh: "厨房", pinyin: "chúfáng", ko: "주방, 부엌", pos: "명사", hanja: "주방(廚房) — 한자 그대로.", ex: { zh: "妈妈在厨房做饭。", pinyin: "māma zài chúfáng zuò fàn", ko: "엄마는 부엌에서 밥을 해요." } },
        { zh: "环境", pinyin: "huánjìng", ko: "환경", pos: "명사", hanja: "환경(環境) — 한자 그대로.", ex: { zh: "这里的环境很好。", pinyin: "zhèlǐ de huánjìng hěn hǎo", ko: "여기 환경이 좋아요." } },
        { zh: "城市", pinyin: "chéngshì", ko: "도시", pos: "명사", hanja: "성시(城市) — '城'은 재 성, '市'는 저자 시.", ex: { zh: "上海是一个大城市。", pinyin: "Shànghǎi shì yí ge dà chéngshì", ko: "상하이는 큰 도시예요." } },
        { zh: "地方", pinyin: "dìfang", ko: "곳, 장소, 지방", pos: "명사", hanja: "지방(地方) — 한자 그대로지만 '곳·장소'로 더 많이 써요.", ex: { zh: "这是一个安静的地方。", pinyin: "zhè shì yí ge ānjìng de dìfang", ko: "여기는 조용한 곳이에요." } },
        { zh: "地图", pinyin: "dìtú", ko: "지도", pos: "명사", hanja: "지도(地圖) — 한자 그대로.", ex: { zh: "请看一下地图。", pinyin: "qǐng kàn yíxià dìtú", ko: "지도를 한번 보세요." } },
        { zh: "护照", pinyin: "hùzhào", ko: "여권", pos: "명사", hanja: "호조(護照) — '護'는 도울 호, '照'는 비칠 조.", ex: { zh: "出国要带护照。", pinyin: "chūguó yào dài hùzhào", ko: "출국할 때는 여권을 챙겨야 해요." } },
        { zh: "行李箱", pinyin: "xínglixiāng", ko: "여행 가방, 캐리어", pos: "명사", hanja: "행리상(行李箱) — '行李'는 짐, '箱'은 상자.", ex: { zh: "我的行李箱很重。", pinyin: "wǒ de xínglixiāng hěn zhòng", ko: "제 캐리어는 무거워요." } },
        { zh: "搬家", pinyin: "bānjiā", ko: "이사하다", pos: "동사", hanja: "반가(搬家) — '집을 옮기다'.", ex: { zh: "他们上个月搬家了。", pinyin: "tāmen shàng ge yuè bānjiā le", ko: "그들은 지난달에 이사했어요." } },
        { zh: "刮风", pinyin: "guāfēng", ko: "바람이 불다", pos: "동사", hanja: "괄풍(颳風) — '風'은 바람 풍.", ex: { zh: "今天刮风了。", pinyin: "jīntiān guāfēng le", ko: "오늘 바람이 불어요." } },
        { zh: "锻炼", pinyin: "duànliàn", ko: "단련하다, (몸을) 운동하다", pos: "동사", hanja: "단련(鍛鍊) — 한자 그대로.", ex: { zh: "他每天早上锻炼身体。", pinyin: "tā měi tiān zǎoshang duànliàn shēntǐ", ko: "그는 매일 아침 몸을 단련해요." } },
      ],
    },
  ],
}
