/**
 * H3 (HSK 3급) 보강 어휘 — 표준 HSK3 단어 목록 중 본편(h3.js)에 없던 200개를 보충.
 * 품사·의미별 6개 테마. pinyin은 원본 표기를 그대로 보존했어요.
 */
export default {
  themes: [
    {
      name: "HSK3 보강 — 동사",
      icon: "🟣",
      words: [
        { zh: "爱好", pinyin: "ài hào", ko: "취미; 좋아하다", pos: "명사", hanja: "애호(愛好) — '愛'는 사랑 애, '好'는 좋을 호.", ex: { zh: "我的爱好是看书。", pinyin: "wǒ de àihào shì kàn shū", ko: "제 취미는 독서예요." } },
        { zh: "帮忙", pinyin: "bāng máng", ko: "돕다, 거들다", pos: "동사", ex: { zh: "你能帮我一个忙吗？", pinyin: "nǐ néng bāng wǒ yí ge máng ma", ko: "저를 좀 도와줄 수 있어요?" } },
        { zh: "参加", pinyin: "cān jiā", ko: "참가하다, 참석하다", pos: "동사", hanja: "참가(參加) — 한자 그대로.", ex: { zh: "我想参加这个活动。", pinyin: "wǒ xiǎng cānjiā zhège huódòng", ko: "저는 이 행사에 참가하고 싶어요." } },
        { zh: "出现", pinyin: "chū xiàn", ko: "나타나다, 출현하다", pos: "동사", hanja: "출현(出現) — 한자 그대로.", ex: { zh: "问题又出现了。", pinyin: "wèntí yòu chūxiàn le", ko: "문제가 또 생겼어요." } },
        { zh: "打扫", pinyin: "dǎ sǎo", ko: "청소하다", pos: "동사", hanja: "타소(打掃) — '掃'는 쓸 소.", ex: { zh: "我每天打扫房间。", pinyin: "wǒ měi tiān dǎsǎo fángjiān", ko: "저는 매일 방을 청소해요." } },
        { zh: "打算", pinyin: "dǎ suàn", ko: "~할 계획이다; 계획", pos: "동사", hanja: "타산(打算) — '算'은 셈할 산.", ex: { zh: "你周末打算做什么？", pinyin: "nǐ zhōumò dǎsuàn zuò shénme", ko: "주말에 뭐 할 계획이에요?" } },
        { zh: "发烧", pinyin: "fā shāo", ko: "열이 나다", pos: "동사", hanja: "발소(發燒) — '燒'는 사를 소. '열이 오르다'.", ex: { zh: "我有点发烧。", pinyin: "wǒ yǒudiǎn fāshāo", ko: "저 좀 열이 나요." } },
        { zh: "发现", pinyin: "fā xiàn", ko: "발견하다, 알아차리다", pos: "동사", hanja: "발현(發現) — '現'은 나타날 현.", ex: { zh: "我发现了一个问题。", pinyin: "wǒ fāxiàn le yí ge wèntí", ko: "저는 문제 하나를 발견했어요." } },
        { zh: "放心", pinyin: "fàng xīn", ko: "안심하다, 마음을 놓다", pos: "동사", hanja: "방심(放心) — 한자는 '방심'이지만 '마음을 놓다=안심하다'예요. 가짜동족어 주의!", ex: { zh: "你放心吧，没问题。", pinyin: "nǐ fàngxīn ba, méi wèntí", ko: "안심하세요, 괜찮아요." } },
        { zh: "感冒", pinyin: "gǎn mào", ko: "감기에 걸리다; 감기", pos: "동사", hanja: "감모(感冒) — '冒'는 무릅쓸 모.", ex: { zh: "我感冒了，很难受。", pinyin: "wǒ gǎnmào le, hěn nánshòu", ko: "감기에 걸려서 힘들어요." } },
        { zh: "敢", pinyin: "gǎn", ko: "감히 ~하다, ~할 용기가 있다", pos: "동사", hanja: "감(敢) — '감히 감'.", ex: { zh: "我不敢一个人去。", pinyin: "wǒ bù gǎn yí ge rén qù", ko: "저는 혼자 갈 엄두가 안 나요." } },
        { zh: "关心", pinyin: "guān xīn", ko: "관심을 가지다, 마음 쓰다", pos: "동사", hanja: "관심(關心) — 한자 그대로.", ex: { zh: "妈妈很关心我。", pinyin: "māma hěn guānxīn wǒ", ko: "엄마는 저를 많이 챙겨요." } },
        { zh: "换", pinyin: "huàn", ko: "바꾸다, 교환하다", pos: "동사", hanja: "환(換) — '바꿀 환'. '교환(交換)'의 환.", ex: { zh: "我想换一个手机。", pinyin: "wǒ xiǎng huàn yí ge shǒujī", ko: "저는 휴대폰을 바꾸고 싶어요." } },
        { zh: "见面", pinyin: "jiàn miàn", ko: "만나다, 대면하다", pos: "동사", hanja: "견면(見面) — '見'은 볼 견, '面'은 낯 면.", ex: { zh: "我们明天见面吧。", pinyin: "wǒmen míngtiān jiànmiàn ba", ko: "우리 내일 만나요." } },
        { zh: "讲", pinyin: "jiǎng", ko: "말하다, 설명하다, 이야기하다", pos: "동사", hanja: "강(講) — '강의(講義)'의 강.", ex: { zh: "老师讲得很清楚。", pinyin: "lǎoshī jiǎng de hěn qīngchu", ko: "선생님은 설명을 분명하게 해요." } },
        { zh: "接", pinyin: "jiē", ko: "받다, 마중하다, (전화를) 받다", pos: "동사", hanja: "접(接) — '접할 접'.", ex: { zh: "我去机场接朋友。", pinyin: "wǒ qù jīchǎng jiē péngyou", ko: "저는 공항에 친구를 마중하러 가요." } },
        { zh: "结婚", pinyin: "jié hūn", ko: "결혼하다", pos: "동사", hanja: "결혼(結婚) — 한자 그대로.", ex: { zh: "他们去年结婚了。", pinyin: "tāmen qùnián jiéhūn le", ko: "그들은 작년에 결혼했어요." } },
        { zh: "结束", pinyin: "jié shù", ko: "끝나다, 마치다", pos: "동사", hanja: "결속(結束) — 한자는 '결속'이지만 '끝나다·종료'를 뜻해요. 가짜동족어 주의!", ex: { zh: "会议已经结束了。", pinyin: "huìyì yǐjīng jiéshù le", ko: "회의는 이미 끝났어요." } },
        { zh: "借", pinyin: "jiè", ko: "빌리다, 빌려주다", pos: "동사", hanja: "차(借) — '빌릴 차'.", ex: { zh: "我想借你的书。", pinyin: "wǒ xiǎng jiè nǐ de shū", ko: "당신 책을 빌리고 싶어요." } },
        { zh: "举行", pinyin: "jǔ xíng", ko: "거행하다, 개최하다", pos: "동사", hanja: "거행(舉行) — '舉'는 들 거.", ex: { zh: "学校举行了运动会。", pinyin: "xuéxiào jǔxíng le yùndònghuì", ko: "학교에서 운동회를 열었어요." } },
        { zh: "离开", pinyin: "lí kāi", ko: "떠나다, 벗어나다", pos: "동사", hanja: "이개(離開) — '離'는 떠날 리, '開'는 열 개.", ex: { zh: "他已经离开公司了。", pinyin: "tā yǐjīng líkāi gōngsī le", ko: "그는 이미 회사를 떠났어요." } },
        { zh: "上网", pinyin: "shàng wǎng", ko: "인터넷을 하다, 접속하다", pos: "동사", hanja: "상망(上網) — '網'은 그물 망. '인터넷에 올라가다'.", ex: { zh: "我每天上网看新闻。", pinyin: "wǒ měi tiān shàngwǎng kàn xīnwén", ko: "저는 매일 인터넷으로 뉴스를 봐요." } },
        { zh: "使", pinyin: "shǐ", ko: "~하게 하다, ~시키다", pos: "동사", hanja: "사(使) — '하여금 사'.", ex: { zh: "这件事使我很高兴。", pinyin: "zhè jiàn shì shǐ wǒ hěn gāoxìng", ko: "이 일이 저를 기쁘게 했어요." } },
        { zh: "刷", pinyin: "shuā", ko: "닦다, (카드를) 긁다, 칠하다", pos: "동사", hanja: "쇄(刷) — '인쇄(印刷)'의 쇄.", ex: { zh: "我每天早上刷牙。", pinyin: "wǒ měi tiān zǎoshang shuā yá", ko: "저는 매일 아침 이를 닦아요." } },
        { zh: "忘记", pinyin: "wàng jì", ko: "잊다, 잊어버리다", pos: "동사", hanja: "망기(忘記) — '忘'은 잊을 망, '記'는 기록할 기.", ex: { zh: "我忘记带钱包了。", pinyin: "wǒ wàngjì dài qiánbāo le", ko: "지갑 챙기는 걸 잊어버렸어요." } },
        { zh: "洗澡", pinyin: "xǐ zǎo", ko: "목욕하다, 샤워하다", pos: "동사", hanja: "세조(洗澡) — '洗'는 씻을 세, '澡'는 씻을 조.", ex: { zh: "我每天晚上洗澡。", pinyin: "wǒ měi tiān wǎnshang xǐzǎo", ko: "저는 매일 저녁 샤워해요." } },
        { zh: "要求", pinyin: "yāo qiú", ko: "요구하다; 요구", pos: "동사", hanja: "요구(要求) — 한자 그대로.", ex: { zh: "老师要求我们准时到。", pinyin: "lǎoshī yāoqiú wǒmen zhǔnshí dào", ko: "선생님은 우리에게 제시간에 오라고 요구해요." } },
        { zh: "以为", pinyin: "yǐ wéi", ko: "(잘못) ~인 줄 알다, 여기다", pos: "동사", hanja: "이위(以爲) — '~라고 여기다'. 대개 사실과 다를 때 써요.", ex: { zh: "我以为今天是星期天。", pinyin: "wǒ yǐwéi jīntiān shì xīngqītiān", ko: "저는 오늘이 일요일인 줄 알았어요." } },
        { zh: "应该", pinyin: "yīng gāi", ko: "~해야 한다, 마땅히", pos: "동사", hanja: "응해(應該) — '應'은 응할 응, '該'는 마땅 해.", ex: { zh: "你应该多休息。", pinyin: "nǐ yīnggāi duō xiūxi", ko: "당신은 더 쉬어야 해요." } },
        { zh: "影响", pinyin: "yǐng xiǎng", ko: "영향을 주다; 영향", pos: "동사", hanja: "영향(影響) — '影'은 그림자 영, '響'은 울릴 향.", ex: { zh: "天气会影响心情。", pinyin: "tiānqì huì yǐngxiǎng xīnqíng", ko: "날씨는 기분에 영향을 줘요." } },
        { zh: "愿意", pinyin: "yuàn yì", ko: "~하기를 원하다, 기꺼이 ~하다", pos: "동사", hanja: "원의(願意) — '願'은 원할 원.", ex: { zh: "我愿意帮助你。", pinyin: "wǒ yuànyì bāngzhù nǐ", ko: "저는 기꺼이 당신을 도울게요." } },
        { zh: "照顾", pinyin: "zhào gu", ko: "돌보다, 보살피다", pos: "동사", hanja: "조고(照顧) — '顧'는 돌아볼 고.", ex: { zh: "她在家照顾孩子。", pinyin: "tā zài jiā zhàogu háizi", ko: "그녀는 집에서 아이를 돌봐요." } },
        { zh: "注意", pinyin: "zhù yì", ko: "주의하다, 신경 쓰다", pos: "동사", hanja: "주의(注意) — 한자 그대로.", ex: { zh: "过马路要注意安全。", pinyin: "guò mǎlù yào zhùyì ānquán", ko: "길을 건널 때는 안전에 주의하세요." } },
        { zh: "祝", pinyin: "zhù", ko: "기원하다, 빌다, 축하하다", pos: "동사", hanja: "축(祝) — '빌 축'. '축하(祝賀)'의 축.", ex: { zh: "祝你生日快乐！", pinyin: "zhù nǐ shēngrì kuàilè", ko: "생일 축하해요!" } },
        { zh: "变化", pinyin: "biàn huà", ko: "변화하다; 변화", pos: "동사", hanja: "변화(變化) — 한자 그대로.", ex: { zh: "天气变化很大。", pinyin: "tiānqì biànhuà hěn dà", ko: "날씨 변화가 커요." } },
        { zh: "表示", pinyin: "biǎo shì", ko: "나타내다, 표시하다", pos: "동사", hanja: "표시(表示) — 한자 그대로.", ex: { zh: "他点头表示同意。", pinyin: "tā diǎntóu biǎoshì tóngyì", ko: "그는 고개를 끄덕여 동의를 표했어요." } },
        { zh: "表演", pinyin: "biǎo yǎn", ko: "공연하다; 공연", pos: "동사", hanja: "표연(表演) — '演'은 펼 연. '연기·공연'.", ex: { zh: "孩子们在台上表演。", pinyin: "háizimen zài tái shang biǎoyǎn", ko: "아이들이 무대에서 공연해요." } },
        { zh: "刮", pinyin: "guā", ko: "(바람이) 불다, 긁다", pos: "동사", ex: { zh: "外面刮大风了。", pinyin: "wàimiàn guā dà fēng le", ko: "밖에 바람이 세게 불어요." } },
        { zh: "画", pinyin: "huà", ko: "그리다; 그림", pos: "동사", hanja: "화(畫) — '그림 화'.", ex: { zh: "她很会画画。", pinyin: "tā hěn huì huà huà", ko: "그녀는 그림을 잘 그려요." } },
        { zh: "刻", pinyin: "kè", ko: "새기다; 15분(시간 단위)", pos: "동사", hanja: "각(刻) — '새길 각'. 시간으로는 '一刻=15분'.", ex: { zh: "现在三点一刻。", pinyin: "xiànzài sān diǎn yí kè", ko: "지금은 3시 15분이에요." } },
        { zh: "哭", pinyin: "kū", ko: "울다", pos: "동사", hanja: "곡(哭) — '울 곡'.", ex: { zh: "孩子哭了起来。", pinyin: "háizi kū le qǐlái", ko: "아이가 울기 시작했어요." } },
        { zh: "爬山", pinyin: "pá shān", ko: "등산하다, 산을 오르다", pos: "동사", hanja: "파산(爬山) — '爬'는 길 파(기다), '山'은 산.", ex: { zh: "周末我们去爬山。", pinyin: "zhōumò wǒmen qù páshān", ko: "주말에 우리 등산 가요." } },
        { zh: "经过", pinyin: "jīng guò", ko: "지나가다, 거치다; 경과", pos: "동사", hanja: "경과(經過) — 한자 그대로.", ex: { zh: "我每天经过这家店。", pinyin: "wǒ měi tiān jīngguò zhè jiā diàn", ko: "저는 매일 이 가게를 지나가요." } },
        { zh: "根据", pinyin: "gēn jù", ko: "~에 근거하다; ~에 따라", pos: "개사", hanja: "근거(根據) — 한자 그대로.", ex: { zh: "根据天气预报，明天下雨。", pinyin: "gēnjù tiānqì yùbào, míngtiān xià yǔ", ko: "일기예보에 따르면 내일 비가 와요." } },
        { zh: "作用", pinyin: "zuò yòng", ko: "작용; 역할, 영향", pos: "명사", hanja: "작용(作用) — 한자 그대로.", ex: { zh: "运动对身体有好作用。", pinyin: "yùndòng duì shēntǐ yǒu hǎo zuòyòng", ko: "운동은 몸에 좋은 작용을 해요." } },
        { zh: "过去", pinyin: "guò qù", ko: "지나가다; 과거, 이전", pos: "동사", hanja: "과거(過去) — 한자 그대로.", ex: { zh: "过去的事就别想了。", pinyin: "guòqù de shì jiù bié xiǎng le", ko: "지난 일은 더 생각하지 마세요." } },
      ],
    },
    {
      name: "HSK3 보강 — 사람·신체·동물",
      icon: "🟣",
      words: [
        { zh: "阿姨", pinyin: "ā yí", ko: "이모, 아주머니", pos: "명사", hanja: "아이(阿姨) — '아주머니'를 부르는 호칭이에요.", ex: { zh: "阿姨，请问洗手间在哪儿？", pinyin: "āyí, qǐngwèn xǐshǒujiān zài nǎr", ko: "아주머니, 화장실이 어디예요?" } },
        { zh: "叔叔", pinyin: "shū shu", ko: "삼촌, 아저씨", pos: "명사", hanja: "숙숙(叔叔) — '叔'은 아저씨 숙.", ex: { zh: "这是我叔叔。", pinyin: "zhè shì wǒ shūshu", ko: "이쪽은 제 삼촌이에요." } },
        { zh: "奶奶", pinyin: "nǎi nai", ko: "할머니(친할머니)", pos: "명사", ex: { zh: "奶奶今年八十岁了。", pinyin: "nǎinai jīnnián bāshí suì le", ko: "할머니는 올해 여든이세요." } },
        { zh: "爷爷", pinyin: "yé ye", ko: "할아버지(친할아버지)", pos: "명사", ex: { zh: "爷爷喜欢喝茶。", pinyin: "yéye xǐhuan hē chá", ko: "할아버지는 차 마시는 걸 좋아하세요." } },
        { zh: "同事", pinyin: "tóng shì", ko: "동료, 직장 동료", pos: "명사", hanja: "동사(同事) — '同'은 같을 동, '事'는 일 사. '같은 일을 하는 사람'.", ex: { zh: "他是我的同事。", pinyin: "tā shì wǒ de tóngshì", ko: "그는 제 직장 동료예요." } },
        { zh: "司机", pinyin: "sī jī", ko: "운전사, 기사", pos: "명사", hanja: "사기(司機) — '司'는 맡을 사, '機'는 기계 기.", ex: { zh: "司机开车很小心。", pinyin: "sījī kāichē hěn xiǎoxīn", ko: "기사님은 운전을 조심스럽게 해요." } },
        { zh: "别人", pinyin: "bié ren", ko: "다른 사람, 남", pos: "대명사", hanja: "별인(別人) — '別'은 다를 별.", ex: { zh: "别管别人怎么说。", pinyin: "bié guǎn biéren zěnme shuō", ko: "남이 뭐라 하든 신경 쓰지 마세요." } },
        { zh: "自己", pinyin: "zì jǐ", ko: "자기, 자신, 스스로", pos: "대명사", hanja: "자기(自己) — 한자 그대로.", ex: { zh: "这是我自己做的。", pinyin: "zhè shì wǒ zìjǐ zuò de", ko: "이건 제가 직접 만든 거예요." } },
        { zh: "鼻子", pinyin: "bí zi", ko: "코", pos: "명사", hanja: "비자(鼻子) — '鼻'는 코 비.", ex: { zh: "他的鼻子很高。", pinyin: "tā de bízi hěn gāo", ko: "그는 코가 오똑해요." } },
        { zh: "耳朵", pinyin: "ěr duo", ko: "귀", pos: "명사", hanja: "이타(耳朵) — '耳'는 귀 이.", ex: { zh: "兔子的耳朵很长。", pinyin: "tùzi de ěrduo hěn cháng", ko: "토끼는 귀가 길어요." } },
        { zh: "脸", pinyin: "liǎn", ko: "얼굴", pos: "명사", ex: { zh: "她的脸有点红。", pinyin: "tā de liǎn yǒudiǎn hóng", ko: "그녀의 얼굴이 좀 빨개요." } },
        { zh: "脚", pinyin: "jiǎo", ko: "발", pos: "명사", hanja: "각(腳) — '다리 각'. 중국어에서는 '발'을 가리켜요.", ex: { zh: "我的脚很疼。", pinyin: "wǒ de jiǎo hěn téng", ko: "제 발이 너무 아파요." } },
        { zh: "腿", pinyin: "tuǐ", ko: "다리", pos: "명사", ex: { zh: "他的腿很长。", pinyin: "tā de tuǐ hěn cháng", ko: "그는 다리가 길어요." } },
        { zh: "头发", pinyin: "tóu fa", ko: "머리카락", pos: "명사", hanja: "두발(頭髮) — '頭'는 머리 두, '髮'은 터럭 발.", ex: { zh: "她的头发又黑又长。", pinyin: "tā de tóufa yòu hēi yòu cháng", ko: "그녀의 머리카락은 검고 길어요." } },
        { zh: "动物", pinyin: "dòng wù", ko: "동물", pos: "명사", hanja: "동물(動物) — 한자 그대로.", ex: { zh: "我喜欢看动物。", pinyin: "wǒ xǐhuan kàn dòngwù", ko: "저는 동물 보는 걸 좋아해요." } },
        { zh: "熊猫", pinyin: "xióng māo", ko: "판다", pos: "명사", hanja: "웅묘(熊貓) — '熊'은 곰 웅, '貓'는 고양이 묘.", ex: { zh: "熊猫很可爱。", pinyin: "xióngmāo hěn kě'ài", ko: "판다는 귀여워요." } },
        { zh: "鸟", pinyin: "diǎo", ko: "새", pos: "명사", hanja: "조(鳥) — '새 조'.", ex: { zh: "树上有一只鸟。", pinyin: "shù shang yǒu yì zhī niǎo", ko: "나무 위에 새 한 마리가 있어요." } },
        { zh: "树", pinyin: "shù", ko: "나무", pos: "명사", hanja: "수(樹) — '나무 수'.", ex: { zh: "门前有一棵大树。", pinyin: "mén qián yǒu yì kē dà shù", ko: "문 앞에 큰 나무 한 그루가 있어요." } },
        { zh: "草", pinyin: "cǎo", ko: "풀", pos: "명사", hanja: "초(草) — '풀 초'.", ex: { zh: "草地上有很多花。", pinyin: "cǎodì shang yǒu hěn duō huā", ko: "잔디밭에 꽃이 많아요." } },
        { zh: "花", pinyin: "huā", ko: "꽃; (돈·시간을) 쓰다", pos: "명사", hanja: "화(花) — '꽃 화'.", ex: { zh: "这些花真漂亮。", pinyin: "zhèxiē huā zhēn piàoliang", ko: "이 꽃들 정말 예뻐요." } },
      ],
    },
    {
      name: "HSK3 보강 — 사물·음식·장소",
      icon: "🟣",
      words: [
        { zh: "办法", pinyin: "bàn fǎ", ko: "방법, 수단", pos: "명사", hanja: "판법(辦法) — '辦'은 힘쓸 판, '法'은 법 법.", ex: { zh: "这是个好办法。", pinyin: "zhè shì ge hǎo bànfǎ", ko: "이건 좋은 방법이에요." } },
        { zh: "冰箱", pinyin: "bīng xiāng", ko: "냉장고", pos: "명사", hanja: "빙상(冰箱) — '冰'은 얼음 빙, '箱'은 상자 상.", ex: { zh: "牛奶在冰箱里。", pinyin: "niúnǎi zài bīngxiāng lǐ", ko: "우유는 냉장고 안에 있어요." } },
        { zh: "菜单", pinyin: "cài dān", ko: "메뉴, 메뉴판", pos: "명사", hanja: "채단(菜單) — '菜'는 나물 채, '單'은 홑 단(목록).", ex: { zh: "请给我看一下菜单。", pinyin: "qǐng gěi wǒ kàn yíxià càidān", ko: "메뉴 좀 보여 주세요." } },
        { zh: "超市", pinyin: "chāo shì", ko: "슈퍼마켓, 마트", pos: "명사", hanja: "초시(超市) — '超級市場(슈퍼마켓)'의 줄임말.", ex: { zh: "我去超市买东西。", pinyin: "wǒ qù chāoshì mǎi dōngxi", ko: "저는 마트에 물건을 사러 가요." } },
        { zh: "衬衫", pinyin: "chèn shān", ko: "셔츠, 와이셔츠", pos: "명사", hanja: "친삼(襯衫) — '衫'은 적삼 삼.", ex: { zh: "他穿了一件白衬衫。", pinyin: "tā chuān le yí jiàn bái chènshān", ko: "그는 흰 셔츠를 입었어요." } },
        { zh: "裤子", pinyin: "kù zi", ko: "바지", pos: "명사", hanja: "고자(褲子) — '褲'는 바지 고.", ex: { zh: "这条裤子有点长。", pinyin: "zhè tiáo kùzi yǒudiǎn cháng", ko: "이 바지는 좀 길어요." } },
        { zh: "裙子", pinyin: "qún zi", ko: "치마, 스커트", pos: "명사", hanja: "군자(裙子) — '裙'은 치마 군.", ex: { zh: "她穿了一条红裙子。", pinyin: "tā chuān le yì tiáo hóng qúnzi", ko: "그녀는 빨간 치마를 입었어요." } },
        { zh: "帽子", pinyin: "mào zi", ko: "모자", pos: "명사", hanja: "모자(帽子) — '帽'는 모자 모.", ex: { zh: "天冷，戴上帽子吧。", pinyin: "tiān lěng, dàishang màozi ba", ko: "날이 추우니 모자를 쓰세요." } },
        { zh: "鞋", pinyin: "xié", ko: "신발", pos: "명사", hanja: "혜(鞋) — '신 혜'.", ex: { zh: "这双鞋很舒服。", pinyin: "zhè shuāng xié hěn shūfu", ko: "이 신발은 편해요." } },
        { zh: "眼镜", pinyin: "yǎn jìng", ko: "안경", pos: "명사", hanja: "안경(眼鏡) — '眼'은 눈 안, '鏡'은 거울 경.", ex: { zh: "我的眼镜找不到了。", pinyin: "wǒ de yǎnjìng zhǎo bu dào le", ko: "제 안경을 못 찾겠어요." } },
        { zh: "伞", pinyin: "sǎn", ko: "우산", pos: "명사", hanja: "산(傘) — '우산 산'.", ex: { zh: "下雨了，带伞吧。", pinyin: "xià yǔ le, dài sǎn ba", ko: "비가 오니 우산을 챙기세요." } },
        { zh: "铅笔", pinyin: "qiān bǐ", ko: "연필", pos: "명사", hanja: "연필(鉛筆) — '鉛'은 납 연, '筆'은 붓 필.", ex: { zh: "请借我一支铅笔。", pinyin: "qǐng jiè wǒ yì zhī qiānbǐ", ko: "연필 한 자루 빌려주세요." } },
        { zh: "黑板", pinyin: "hēi bǎn", ko: "칠판", pos: "명사", hanja: "흑판(黑板) — '黑'은 검을 흑, '板'은 널 판.", ex: { zh: "老师在黑板上写字。", pinyin: "lǎoshī zài hēibǎn shang xiě zì", ko: "선생님이 칠판에 글씨를 써요." } },
        { zh: "字典", pinyin: "zì diǎn", ko: "(한자)사전", pos: "명사", hanja: "자전(字典) — '字'는 글자 자, '典'은 법 전.", ex: { zh: "我查了字典。", pinyin: "wǒ chá le zìdiǎn", ko: "저는 사전을 찾아봤어요." } },
        { zh: "盘子", pinyin: "pán zi", ko: "접시, 쟁반", pos: "명사", hanja: "반자(盤子) — '盤'은 소반 반.", ex: { zh: "桌子上有几个盘子。", pinyin: "zhuōzi shang yǒu jǐ ge pánzi", ko: "탁자 위에 접시가 몇 개 있어요." } },
        { zh: "碗", pinyin: "wǎn", ko: "그릇, 공기; ~그릇(양사)", pos: "명사", ex: { zh: "我吃了一碗面。", pinyin: "wǒ chī le yì wǎn miàn", ko: "저는 국수 한 그릇을 먹었어요." } },
        { zh: "筷子", pinyin: "kuài zi", ko: "젓가락", pos: "명사", ex: { zh: "我会用筷子。", pinyin: "wǒ huì yòng kuàizi", ko: "저는 젓가락을 쓸 줄 알아요." } },
        { zh: "面包", pinyin: "miàn bāo", ko: "빵", pos: "명사", hanja: "면포(麵包) — '麵'은 밀가루 면, '包'는 쌀 포.", ex: { zh: "早上我吃面包。", pinyin: "zǎoshang wǒ chī miànbāo", ko: "아침에 저는 빵을 먹어요." } },
        { zh: "面条", pinyin: "miàn tiáo", ko: "국수, 면", pos: "명사", hanja: "면조(麵條) — '條'는 가지 조(가늘고 긴 것).", ex: { zh: "我喜欢吃面条。", pinyin: "wǒ xǐhuan chī miàntiáo", ko: "저는 국수 먹는 걸 좋아해요." } },
        { zh: "果汁", pinyin: "guǒ zhī", ko: "주스, 과즙", pos: "명사", hanja: "과즙(果汁) — '果'는 과실 과, '汁'은 즙 즙.", ex: { zh: "我想喝果汁。", pinyin: "wǒ xiǎng hē guǒzhī", ko: "저는 주스를 마시고 싶어요." } },
        { zh: "啤酒", pinyin: "pí jiǔ", ko: "맥주", pos: "명사", hanja: "비주(啤酒) — '酒'는 술 주. '啤'는 beer의 음역.", ex: { zh: "他喜欢喝啤酒。", pinyin: "tā xǐhuan hē píjiǔ", ko: "그는 맥주 마시는 걸 좋아해요." } },
        { zh: "葡萄", pinyin: "pú tao", ko: "포도", pos: "명사", hanja: "포도(葡萄) — 한자 그대로.", ex: { zh: "这种葡萄很甜。", pinyin: "zhè zhǒng pútao hěn tián", ko: "이 포도는 달아요." } },
        { zh: "香蕉", pinyin: "xiāng jiāo", ko: "바나나", pos: "명사", hanja: "향초(香蕉) — '香'은 향기 향, '蕉'는 파초 초.", ex: { zh: "我每天吃一根香蕉。", pinyin: "wǒ měi tiān chī yì gēn xiāngjiāo", ko: "저는 매일 바나나 하나를 먹어요." } },
        { zh: "糖", pinyin: "táng", ko: "설탕, 사탕", pos: "명사", hanja: "당(糖) — '엿 당'. '설탕(雪糖)'의 당.", ex: { zh: "咖啡里别放糖。", pinyin: "kāfēi lǐ bié fàng táng", ko: "커피에 설탕 넣지 마세요." } },
        { zh: "地铁", pinyin: "dì tiě", ko: "지하철", pos: "명사", hanja: "지철(地鐵) — '地'는 땅 지, '鐵'은 쇠 철. '地下鐵'의 줄임.", ex: { zh: "我坐地铁上班。", pinyin: "wǒ zuò dìtiě shàngbān", ko: "저는 지하철을 타고 출근해요." } },
        { zh: "电梯", pinyin: "diàn tī", ko: "엘리베이터, 에스컬레이터", pos: "명사", hanja: "전제(電梯) — '電'은 번개 전, '梯'는 사다리 제.", ex: { zh: "我们坐电梯上去吧。", pinyin: "wǒmen zuò diàntī shàngqù ba", ko: "우리 엘리베이터 타고 올라가요." } },
        { zh: "灯", pinyin: "dēng", ko: "등, 불, 램프", pos: "명사", hanja: "등(燈) — '등 등'.", ex: { zh: "请把灯关上。", pinyin: "qǐng bǎ dēng guānshang", ko: "불 좀 꺼 주세요." } },
        { zh: "照相机", pinyin: "zhào xiàng jī", ko: "카메라", pos: "명사", hanja: "조상기(照相機) — '照相'은 사진 찍기, '機'는 기계.", ex: { zh: "这台照相机很贵。", pinyin: "zhè tái zhàoxiàngjī hěn guì", ko: "이 카메라는 비싸요." } },
        { zh: "信", pinyin: "xìn", ko: "편지; 믿다", pos: "명사", hanja: "신(信) — '믿을 신'. 명사로는 '편지'.", ex: { zh: "我给妈妈写了一封信。", pinyin: "wǒ gěi māma xiě le yì fēng xìn", ko: "저는 엄마에게 편지를 한 통 썼어요." } },
        { zh: "河", pinyin: "hé", ko: "강, 하천", pos: "명사", hanja: "하(河) — '물 하'. '운하(運河)'의 하.", ex: { zh: "河里有很多鱼。", pinyin: "hé lǐ yǒu hěn duō yú", ko: "강에 물고기가 많아요." } },
        { zh: "花园", pinyin: "huā yuán", ko: "정원, 화원", pos: "명사", hanja: "화원(花園) — '花'는 꽃 화, '園'은 동산 원.", ex: { zh: "我家有一个小花园。", pinyin: "wǒ jiā yǒu yí ge xiǎo huāyuán", ko: "우리 집에는 작은 정원이 있어요." } },
        { zh: "街道", pinyin: "jiē dào", ko: "거리, 길거리", pos: "명사", hanja: "가도(街道) — '街'는 거리 가, '道'는 길 도.", ex: { zh: "这条街道很干净。", pinyin: "zhè tiáo jiēdào hěn gānjìng", ko: "이 거리는 깨끗해요." } },
        { zh: "洗手间", pinyin: "xǐ shǒu jiān", ko: "화장실", pos: "명사", hanja: "세수간(洗手間) — '손 씻는 칸'.", ex: { zh: "请问，洗手间在哪儿？", pinyin: "qǐngwèn, xǐshǒujiān zài nǎr", ko: "실례지만 화장실이 어디예요?" } },
        { zh: "节目", pinyin: "jié mù", ko: "프로그램, 공연 순서", pos: "명사", hanja: "절목(節目) — '節'은 마디 절, '目'은 눈 목.", ex: { zh: "这个节目很有意思。", pinyin: "zhège jiémù hěn yǒu yìsi", ko: "이 프로그램은 재미있어요." } },
        { zh: "节日", pinyin: "jié rì", ko: "명절, 기념일", pos: "명사", hanja: "절일(節日) — '節'은 마디 절, '日'은 날 일.", ex: { zh: "春节是重要的节日。", pinyin: "chūnjié shì zhòngyào de jiérì", ko: "춘절은 중요한 명절이에요." } },
        { zh: "新闻", pinyin: "xīn wén", ko: "뉴스, 소식", pos: "명사", hanja: "신문(新聞) — 한자는 '신문'이지만 '뉴스'를 뜻해요. 종이 신문은 报纸!", ex: { zh: "我每天看新闻。", pinyin: "wǒ měi tiān kàn xīnwén", ko: "저는 매일 뉴스를 봐요." } },
        { zh: "音乐", pinyin: "yīn yuè", ko: "음악", pos: "명사", hanja: "음악(音樂) — 한자 그대로. '樂'을 'yuè'로 읽어요.", ex: { zh: "我喜欢听音乐。", pinyin: "wǒ xǐhuan tīng yīnyuè", ko: "저는 음악 듣는 걸 좋아해요." } },
        { zh: "游戏", pinyin: "yóu xì", ko: "게임, 놀이", pos: "명사", hanja: "유희(遊戲) — '遊'는 놀 유, '戲'는 놀이 희.", ex: { zh: "孩子们在玩游戏。", pinyin: "háizimen zài wán yóuxì", ko: "아이들이 게임을 하고 있어요." } },
        { zh: "数学", pinyin: "shù xué", ko: "수학", pos: "명사", hanja: "수학(數學) — '數'는 셈 수, '學'은 배울 학.", ex: { zh: "我数学不太好。", pinyin: "wǒ shùxué bú tài hǎo", ko: "저는 수학을 잘 못해요." } },
        { zh: "体育", pinyin: "tǐ yù", ko: "체육, 스포츠", pos: "명사", hanja: "체육(體育) — '體'는 몸 체, '育'은 기를 육.", ex: { zh: "我喜欢上体育课。", pinyin: "wǒ xǐhuan shàng tǐyù kè", ko: "저는 체육 수업을 좋아해요." } },
        { zh: "词语", pinyin: "cí yǔ", ko: "단어, 어휘", pos: "명사", hanja: "사어(詞語) — '詞'는 말 사, '語'는 말씀 어.", ex: { zh: "这个词语我不懂。", pinyin: "zhège cíyǔ wǒ bù dǒng", ko: "이 단어를 모르겠어요." } },
        { zh: "句子", pinyin: "jù zi", ko: "문장", pos: "명사", hanja: "구자(句子) — '句'는 글귀 구.", ex: { zh: "请用这个词造句子。", pinyin: "qǐng yòng zhège cí zào jùzi", ko: "이 단어로 문장을 만들어 보세요." } },
        { zh: "普通话", pinyin: "pǔ tōng huà", ko: "표준 중국어, 보통화", pos: "명사", hanja: "보통화(普通話) — '普通'은 보통, '話'는 말.", ex: { zh: "他的普通话很标准。", pinyin: "tā de pǔtōnghuà hěn biāozhǔn", ko: "그의 표준어는 매우 정확해요." } },
        { zh: "电子", pinyin: "diàn zǐ", ko: "전자", pos: "명사", hanja: "전자(電子) — '電'은 번개 전, '子'는 아들 자.", ex: { zh: "我给你发电子邮件。", pinyin: "wǒ gěi nǐ fā diànzǐ yóujiàn", ko: "제가 당신에게 이메일을 보낼게요." } },
        { zh: "水平", pinyin: "shuǐ píng", ko: "수준, 실력", pos: "명사", hanja: "수평(水平) — 한자는 '수평'이지만 '수준·실력'을 뜻해요.", ex: { zh: "他的汉语水平很高。", pinyin: "tā de Hànyǔ shuǐpíng hěn gāo", ko: "그의 중국어 실력은 높아요." } },
        { zh: "年级", pinyin: "nián jí", ko: "학년", pos: "명사", hanja: "연급(年級) — '年'은 해 년, '級'은 등급 급.", ex: { zh: "你上几年级？", pinyin: "nǐ shàng jǐ niánjí", ko: "몇 학년이에요?" } },
        { zh: "太阳", pinyin: "tài yang", ko: "태양, 해", pos: "명사", hanja: "태양(太陽) — 한자 그대로.", ex: { zh: "今天太阳很大。", pinyin: "jīntiān tàiyang hěn dà", ko: "오늘 햇볕이 강해요." } },
        { zh: "月亮", pinyin: "yuè liang", ko: "달", pos: "명사", hanja: "월량(月亮) — '月'은 달 월, '亮'은 밝을 량.", ex: { zh: "今晚的月亮很圆。", pinyin: "jīnwǎn de yuèliang hěn yuán", ko: "오늘 밤 달이 둥글어요." } },
        { zh: "云", pinyin: "yún", ko: "구름", pos: "명사", hanja: "운(雲) — '구름 운'.", ex: { zh: "天上有很多云。", pinyin: "tiān shàng yǒu hěn duō yún", ko: "하늘에 구름이 많아요." } },
      ],
    },
    {
      name: "HSK3 보강 — 형용사·상태",
      icon: "🟣",
      words: [
        { zh: "矮", pinyin: "ǎi", ko: "(키가) 작다, 낮다", pos: "형용사", ex: { zh: "他比我矮一点。", pinyin: "tā bǐ wǒ ǎi yìdiǎn", ko: "그는 저보다 키가 조금 작아요." } },
        { zh: "饱", pinyin: "bǎo", ko: "배부르다", pos: "형용사", hanja: "포(飽) — '배부를 포'.", ex: { zh: "我吃饱了。", pinyin: "wǒ chībǎo le", ko: "저는 배불러요." } },
        { zh: "饿", pinyin: "è", ko: "배고프다", pos: "형용사", hanja: "아(餓) — '주릴 아'.", ex: { zh: "我有点饿了。", pinyin: "wǒ yǒudiǎn è le", ko: "저 좀 배고파요." } },
        { zh: "渴", pinyin: "kě", ko: "목마르다", pos: "형용사", hanja: "갈(渴) — '목마를 갈'. '갈증(渴症)'의 갈.", ex: { zh: "我很渴，想喝水。", pinyin: "wǒ hěn kě, xiǎng hē shuǐ", ko: "목말라서 물을 마시고 싶어요." } },
        { zh: "短", pinyin: "duǎn", ko: "짧다", pos: "형용사", hanja: "단(短) — '짧을 단'.", ex: { zh: "这条路很短。", pinyin: "zhè tiáo lù hěn duǎn", ko: "이 길은 짧아요." } },
        { zh: "低", pinyin: "dī", ko: "낮다, (소리를) 낮추다", pos: "형용사", hanja: "저(低) — '낮을 저'.", ex: { zh: "这里的温度很低。", pinyin: "zhèlǐ de wēndù hěn dī", ko: "여기 온도가 낮아요." } },
        { zh: "干净", pinyin: "gān jìng", ko: "깨끗하다", pos: "형용사", hanja: "건정(乾淨) — '乾'은 마를 건, '淨'은 깨끗할 정.", ex: { zh: "房间很干净。", pinyin: "fángjiān hěn gānjìng", ko: "방이 깨끗해요." } },
        { zh: "坏", pinyin: "huài", ko: "나쁘다, 고장 나다, 상하다", pos: "형용사", hanja: "괴(壞) — '무너질 괴'.", ex: { zh: "电脑坏了。", pinyin: "diànnǎo huài le", ko: "컴퓨터가 고장 났어요." } },
        { zh: "旧", pinyin: "jiù", ko: "낡다, 오래되다, 헌", pos: "형용사", hanja: "구(舊) — '예 구'. 新(새것)의 반대.", ex: { zh: "这件衣服太旧了。", pinyin: "zhè jiàn yīfu tài jiù le", ko: "이 옷은 너무 낡았어요." } },
        { zh: "可爱", pinyin: "kě ài", ko: "귀엽다, 사랑스럽다", pos: "형용사", hanja: "가애(可愛) — '可'는 옳을 가, '愛'는 사랑 애.", ex: { zh: "这只小猫很可爱。", pinyin: "zhè zhī xiǎo māo hěn kě'ài", ko: "이 새끼 고양이는 귀여워요." } },
        { zh: "胖", pinyin: "pàng", ko: "뚱뚱하다, 살찌다", pos: "형용사", ex: { zh: "他最近有点胖了。", pinyin: "tā zuìjìn yǒudiǎn pàng le", ko: "그는 요즘 좀 살이 쪘어요." } },
        { zh: "瘦", pinyin: "shòu", ko: "마르다, 날씬하다, (옷이) 끼다", pos: "형용사", ex: { zh: "她很瘦。", pinyin: "tā hěn shòu", ko: "그녀는 말랐어요." } },
        { zh: "难过", pinyin: "nán guò", ko: "슬프다, 괴롭다", pos: "형용사", hanja: "난과(難過) — '難'은 어려울 난, '過'는 지날 과. '지내기 힘들다'.", ex: { zh: "听到这个消息，我很难过。", pinyin: "tīngdào zhège xiāoxi, wǒ hěn nánguò", ko: "이 소식을 듣고 저는 슬펐어요." } },
        { zh: "年轻", pinyin: "nián qīng", ko: "젊다", pos: "형용사", hanja: "연경(年輕) — '年'은 해 년, '輕'은 가벼울 경.", ex: { zh: "他看起来很年轻。", pinyin: "tā kàn qǐlái hěn niánqīng", ko: "그는 젊어 보여요." } },
        { zh: "新鲜", pinyin: "xīn xiān", ko: "신선하다, 싱싱하다", pos: "형용사", hanja: "신선(新鮮) — '新'은 새 신, '鮮'은 고울 선.", ex: { zh: "这些蔬菜很新鲜。", pinyin: "zhèxiē shūcài hěn xīnxiān", ko: "이 채소들은 싱싱해요." } },
        { zh: "甜", pinyin: "tián", ko: "달다", pos: "형용사", ex: { zh: "这个西瓜很甜。", pinyin: "zhège xīguā hěn tián", ko: "이 수박은 달아요." } },
        { zh: "相同", pinyin: "xiāng tóng", ko: "같다, 동일하다", pos: "형용사", hanja: "상동(相同) — '相'은 서로 상, '同'은 같을 동.", ex: { zh: "我们的想法相同。", pinyin: "wǒmen de xiǎngfǎ xiāngtóng", ko: "우리 생각은 같아요." } },
        { zh: "一样", pinyin: "yī yàng", ko: "같다, 똑같다", pos: "형용사", hanja: "일양(一樣) — '一'은 한 일, '樣'은 모양 양.", ex: { zh: "这两个一样吗？", pinyin: "zhè liǎng ge yíyàng ma", ko: "이 둘은 똑같아요?" } },
        { zh: "一般", pinyin: "yī bān", ko: "보통이다, 일반적이다, 그저 그렇다", pos: "형용사", hanja: "일반(一般) — 한자 그대로.", ex: { zh: "这家店的菜一般。", pinyin: "zhè jiā diàn de cài yìbān", ko: "이 가게 음식은 그저 그래요." } },
        { zh: "有名", pinyin: "yǒu míng", ko: "유명하다", pos: "형용사", hanja: "유명(有名) — '有'는 있을 유, '名'은 이름 명.", ex: { zh: "这是一家很有名的饭馆。", pinyin: "zhè shì yì jiā hěn yǒumíng de fànguǎn", ko: "여기는 아주 유명한 식당이에요." } },
        { zh: "主要", pinyin: "zhǔ yào", ko: "주요하다, 주된", pos: "형용사", hanja: "주요(主要) — '主'는 주인 주, '要'는 요긴할 요.", ex: { zh: "这是主要原因。", pinyin: "zhè shì zhǔyào yuányīn", ko: "이게 주된 이유예요." } },
        { zh: "小心", pinyin: "xiǎo xīn", ko: "조심하다, 조심스럽다", pos: "동사", hanja: "소심(小心) — 한자는 '소심'이지만 '조심하다'를 뜻해요. 가짜동족어 주의!", ex: { zh: "路上小心！", pinyin: "lù shàng xiǎoxīn", ko: "길 조심하세요!" } },
        { zh: "方便", pinyin: "fāng biàn", ko: "편리하다, 편하다", pos: "형용사", hanja: "방편(方便) — 한자는 '방편'이지만 '편리하다'를 뜻해요.", ex: { zh: "坐地铁很方便。", pinyin: "zuò dìtiě hěn fāngbiàn", ko: "지하철 타는 게 편리해요." } },
        { zh: "蓝", pinyin: "lán", ko: "파랗다, 남색의", pos: "형용사", hanja: "남(藍) — '쪽 람'.", ex: { zh: "天空很蓝。", pinyin: "tiānkōng hěn lán", ko: "하늘이 파래요." } },
        { zh: "绿", pinyin: "lǜ", ko: "초록색의, 푸르다", pos: "형용사", hanja: "록(綠) — '푸를 록'.", ex: { zh: "春天树叶变绿了。", pinyin: "chūntiān shùyè biàn lǜ le", ko: "봄에는 나뭇잎이 초록색으로 변해요." } },
        { zh: "黄", pinyin: "huáng", ko: "노랗다, 황색의", pos: "형용사", hanja: "황(黃) — '누를 황'.", ex: { zh: "秋天树叶变黄了。", pinyin: "qiūtiān shùyè biàn huáng le", ko: "가을에는 나뭇잎이 노랗게 변해요." } },
        { zh: "老", pinyin: "lǎo", ko: "늙다, 오래되다; 자주", pos: "형용사", hanja: "로(老) — '늙을 로'.", ex: { zh: "我的爷爷老了。", pinyin: "wǒ de yéye lǎo le", ko: "우리 할아버지는 늙으셨어요." } },
        { zh: "疼", pinyin: "téng", ko: "아프다; 몹시 아끼다", pos: "형용사", ex: { zh: "我头有点疼。", pinyin: "wǒ tóu yǒudiǎn téng", ko: "저는 머리가 좀 아파요." } },
        { zh: "差", pinyin: "chà", ko: "나쁘다, 모자라다, 차이 나다", pos: "형용사", hanja: "차(差) — '어긋날 차'. '差別(차별)'의 차.", ex: { zh: "他的成绩很差。", pinyin: "tā de chéngjì hěn chà", ko: "그의 성적은 나빠요." } },
      ],
    },
    {
      name: "HSK3 보강 — 부사·접속사·개사",
      icon: "🟣",
      words: [
        { zh: "比较", pinyin: "bǐ jiào", ko: "비교적, 상대적으로; 비교하다", pos: "부사", hanja: "비교(比較) — '比'는 견줄 비, '較'는 견줄 교.", ex: { zh: "今天比较冷。", pinyin: "jīntiān bǐjiào lěng", ko: "오늘은 비교적 추워요." } },
        { zh: "才", pinyin: "cái", ko: "비로소, 이제야, 겨우", pos: "부사", ex: { zh: "他现在才来。", pinyin: "tā xiànzài cái lái", ko: "그는 이제야 왔어요." } },
        { zh: "更", pinyin: "gèng", ko: "더, 더욱", pos: "부사", hanja: "경(更) — '고칠 경/다시 갱'. 비교에서 '더'를 나타내요.", ex: { zh: "今天比昨天更热。", pinyin: "jīntiān bǐ zuótiān gèng rè", ko: "오늘은 어제보다 더 더워요." } },
        { zh: "极", pinyin: "jí", ko: "극히, 몹시 (~极了)", pos: "부사", hanja: "극(極) — '다할 극'. '极了'는 '엄청'.", ex: { zh: "这个菜好吃极了。", pinyin: "zhège cài hǎochī jí le", ko: "이 요리는 엄청 맛있어요." } },
        { zh: "经常", pinyin: "jīng cháng", ko: "자주, 늘", pos: "부사", hanja: "경상(經常) — '經'은 지날 경, '常'은 떳떳할 상.", ex: { zh: "我经常去那家店。", pinyin: "wǒ jīngcháng qù nà jiā diàn", ko: "저는 그 가게에 자주 가요." } },
        { zh: "马上", pinyin: "mǎ shàng", ko: "곧, 즉시, 바로", pos: "부사", hanja: "마상(馬上) — '말 위에서'라는 뜻에서 '즉시'로 굳어졌어요.", ex: { zh: "我马上就来。", pinyin: "wǒ mǎshàng jiù lái", ko: "곧 갈게요." } },
        { zh: "特别", pinyin: "tè bié", ko: "특히, 특별히; 특별하다", pos: "부사", hanja: "특별(特別) — 한자 그대로.", ex: { zh: "我特别喜欢这首歌。", pinyin: "wǒ tèbié xǐhuan zhè shǒu gē", ko: "저는 이 노래를 특히 좋아해요." } },
        { zh: "先", pinyin: "xiān", ko: "먼저, 우선", pos: "부사", hanja: "선(先) — '먼저 선'.", ex: { zh: "你先走吧。", pinyin: "nǐ xiān zǒu ba", ko: "당신 먼저 가세요." } },
        { zh: "一定", pinyin: "yī dìng", ko: "반드시, 꼭", pos: "부사", hanja: "일정(一定) — 한자는 '일정'이지만 '반드시'를 뜻해요.", ex: { zh: "我一定会去。", pinyin: "wǒ yídìng huì qù", ko: "저는 꼭 갈 거예요." } },
        { zh: "一共", pinyin: "yī gòng", ko: "모두, 전부, 합쳐서", pos: "부사", hanja: "일공(一共) — '共'은 함께 공.", ex: { zh: "一共多少钱？", pinyin: "yígòng duōshao qián", ko: "전부 얼마예요?" } },
        { zh: "又", pinyin: "yòu", ko: "또, 다시; ~하면서 ~하다", pos: "부사", hanja: "우(又) — '또 우'.", ex: { zh: "他又迟到了。", pinyin: "tā yòu chídào le", ko: "그는 또 지각했어요." } },
        { zh: "只", pinyin: "zhǐ", ko: "단지, 오직, ~만", pos: "부사", hanja: "지(只) — '다만 지'.", ex: { zh: "我只想喝水。", pinyin: "wǒ zhǐ xiǎng hē shuǐ", ko: "저는 물만 마시고 싶어요." } },
        { zh: "而且", pinyin: "ér qiě", ko: "게다가, 뿐만 아니라", pos: "접속사", hanja: "이차(而且) — '而'는 말 이을 이, '且'는 또 차.", ex: { zh: "她很聪明，而且很努力。", pinyin: "tā hěn cōngming, érqiě hěn nǔlì", ko: "그녀는 똑똑하고 게다가 열심히 해요." } },
        { zh: "或者", pinyin: "huò zhě", ko: "혹은, 또는, ~이거나", pos: "접속사", hanja: "혹자(或者) — '或'은 혹 혹, '者'는 놈 자.", ex: { zh: "你喝茶或者咖啡？", pinyin: "nǐ hē chá huòzhě kāfēi", ko: "차나 커피 드실래요?" } },
        { zh: "还是", pinyin: "hái shi", ko: "아니면 (의문); 여전히, ~하는 게 낫다", pos: "접속사", hanja: "환시(還是) — '還'은 돌아올 환, '是'는 옳을 시.", ex: { zh: "你喝茶还是咖啡？", pinyin: "nǐ hē chá háishi kāfēi", ko: "차 드실래요, 아니면 커피 드실래요?" } },
        { zh: "然后", pinyin: "rán hòu", ko: "그런 다음, 그러고 나서", pos: "접속사", hanja: "연후(然後) — '然'은 그럴 연, '後'는 뒤 후.", ex: { zh: "先吃饭，然后看电影。", pinyin: "xiān chī fàn, ránhòu kàn diànyǐng", ko: "먼저 밥 먹고, 그다음에 영화 봐요." } },
        { zh: "如果", pinyin: "rú guǒ", ko: "만약, 만일", pos: "접속사", hanja: "여과(如果) — '如'는 같을 여, '果'는 열매 과.", ex: { zh: "如果下雨，我就不去了。", pinyin: "rúguǒ xià yǔ, wǒ jiù bú qù le", ko: "비가 오면 저는 안 갈게요." } },
        { zh: "虽然", pinyin: "suī rán", ko: "비록 ~이지만", pos: "접속사", hanja: "수연(雖然) — '雖'는 비록 수, '然'은 그럴 연. 흔히 '但是'와 호응.", ex: { zh: "虽然很累，但是很开心。", pinyin: "suīrán hěn lèi, dànshì hěn kāixīn", ko: "비록 피곤하지만 즐거워요." } },
        { zh: "为了", pinyin: "wèi le", ko: "~을 위하여", pos: "개사", hanja: "위료(爲了) — '爲'는 할 위.", ex: { zh: "为了健康，我每天运动。", pinyin: "wèile jiànkāng, wǒ měi tiān yùndòng", ko: "건강을 위해 저는 매일 운동해요." } },
        { zh: "除了", pinyin: "chú le", ko: "~을 제외하고, ~외에", pos: "개사", hanja: "제료(除了) — '除'는 덜 제. '除了…以外' 형태로 자주 써요.", ex: { zh: "除了他，大家都来了。", pinyin: "chúle tā, dàjiā dōu lái le", ko: "그를 제외하고 모두 왔어요." } },
        { zh: "关于", pinyin: "guān yú", ko: "~에 관하여, ~에 대해", pos: "개사", hanja: "관어(關於) — '關'은 빗장 관, '於'는 어조사 어.", ex: { zh: "这是关于历史的书。", pinyin: "zhè shì guānyú lìshǐ de shū", ko: "이건 역사에 관한 책이에요." } },
        { zh: "跟", pinyin: "gēn", ko: "~와/과; 따라가다", pos: "개사", ex: { zh: "我跟朋友一起去。", pinyin: "wǒ gēn péngyou yìqǐ qù", ko: "저는 친구와 함께 가요." } },
        { zh: "被", pinyin: "bèi", ko: "~당하다, ~에게 (피동)", pos: "개사", hanja: "피(被) — '입을 피'. 피동을 나타내는 개사예요.", ex: { zh: "我的自行车被偷了。", pinyin: "wǒ de zìxíngchē bèi tōu le", ko: "제 자전거를 도둑맞았어요." } },
        { zh: "把", pinyin: "bǎ", ko: "~을/를 (처치문); ~자루(양사)", pos: "개사", ex: { zh: "请把窗户打开。", pinyin: "qǐng bǎ chuānghu dǎkāi", ko: "창문을 열어 주세요." } },
        { zh: "像", pinyin: "xiàng", ko: "~와 같다, 닮다; 마치", pos: "동사", hanja: "상(像) — '모양 상'. '~처럼 보이다·닮다'.", ex: { zh: "她长得很像妈妈。", pinyin: "tā zhǎng de hěn xiàng māma", ko: "그녀는 엄마를 많이 닮았어요." } },
        { zh: "多么", pinyin: "duō me", ko: "얼마나, 정말 (감탄)", pos: "부사", hanja: "다마(多麼) — '多'는 많을 다.", ex: { zh: "这里的风景多么美啊！", pinyin: "zhèlǐ de fēngjǐng duōme měi a", ko: "여기 풍경이 정말 아름다워요!" } },
        { zh: "为什么", pinyin: "wèi shén me", ko: "왜, 어째서", pos: "대명사", hanja: "위십마(爲什麼) — '무엇을 위하여=왜'.", ex: { zh: "你为什么不来？", pinyin: "nǐ wèishénme bù lái", ko: "왜 안 와요?" } },
        { zh: "其他", pinyin: "qí tā", ko: "기타, 다른 것", pos: "대명사", hanja: "기타(其他) — '其'는 그 기, '他'는 다를 타.", ex: { zh: "其他人呢？", pinyin: "qítā rén ne", ko: "다른 사람들은요?" } },
        { zh: "啊", pinyin: "ā", ko: "아! (놀람·감탄)", pos: "감탄사", ex: { zh: "啊，原来是你！", pinyin: "ā, yuánlái shì nǐ", ko: "아, 너였구나!" } },
        { zh: "地", pinyin: "de", ko: "~하게, ~히 (부사어 표지)", pos: "조사", hanja: "지(地) — 형용사를 부사어로 만드는 구조조사예요('땅 지'와 같은 글자).", ex: { zh: "他高兴地笑了。", pinyin: "tā gāoxìng de xiào le", ko: "그는 기쁘게 웃었어요." } },
        { zh: "一边", pinyin: "yī biān", ko: "한쪽; ~하면서 ~하다 (一边…一边)", pos: "부사", hanja: "일변(一邊) — '一'은 한 일, '邊'은 가 변.", ex: { zh: "他一边走一边唱歌。", pinyin: "tā yìbiān zǒu yìbiān chàng gē", ko: "그는 걸으면서 노래를 불러요." } },
        { zh: "中间", pinyin: "zhōng jiān", ko: "가운데, 중간, 사이", pos: "명사", hanja: "중간(中間) — 한자 그대로.", ex: { zh: "他坐在我们中间。", pinyin: "tā zuò zài wǒmen zhōngjiān", ko: "그는 우리 사이에 앉았어요." } },
        { zh: "附近", pinyin: "fù jìn", ko: "부근, 근처", pos: "명사", hanja: "부근(附近) — '附'는 붙을 부, '近'은 가까울 근.", ex: { zh: "附近有一家医院。", pinyin: "fùjìn yǒu yì jiā yīyuàn", ko: "근처에 병원이 하나 있어요." } },
        { zh: "北方", pinyin: "běi fāng", ko: "북쪽, 북방", pos: "명사", hanja: "북방(北方) — '北'은 북녘 북, '方'은 모 방.", ex: { zh: "北方的冬天很冷。", pinyin: "běifāng de dōngtiān hěn lěng", ko: "북쪽 지방의 겨울은 추워요." } },
        { zh: "东", pinyin: "dōng", ko: "동쪽, 동", pos: "명사", hanja: "동(東) — '동녘 동'.", ex: { zh: "太阳从东边升起。", pinyin: "tàiyáng cóng dōngbiān shēngqǐ", ko: "해는 동쪽에서 떠요." } },
        { zh: "西", pinyin: "xī", ko: "서쪽, 서", pos: "명사", hanja: "서(西) — '서녘 서'.", ex: { zh: "我家在城市的西边。", pinyin: "wǒ jiā zài chéngshì de xībiān", ko: "우리 집은 도시 서쪽에 있어요." } },
        { zh: "南", pinyin: "nán", ko: "남쪽, 남", pos: "명사", hanja: "남(南) — '남녘 남'.", ex: { zh: "南边的天气比较暖和。", pinyin: "nánbiān de tiānqì bǐjiào nuǎnhuo", ko: "남쪽 날씨가 비교적 따뜻해요." } },
        { zh: "最近", pinyin: "zuì jìn", ko: "최근, 요즘", pos: "명사", hanja: "최근(最近) — '最'는 가장 최, '近'은 가까울 근.", ex: { zh: "你最近怎么样？", pinyin: "nǐ zuìjìn zěnmeyàng", ko: "요즘 어떻게 지내요?" } },
        { zh: "越", pinyin: "yuè", ko: "더욱 (越…越… ~할수록 ~하다)", pos: "부사", hanja: "월(越) — '넘을 월'. '越来越=점점 더'.", ex: { zh: "天气越来越冷了。", pinyin: "tiānqì yuè lái yuè lěng le", ko: "날씨가 점점 추워져요." } },
        { zh: "种", pinyin: "zhǒng", ko: "종류, 가지 (양사); 씨앗", pos: "양사", hanja: "종(種) — '씨 종'. '~종류'를 셀 때 써요.", ex: { zh: "这种水果很甜。", pinyin: "zhè zhǒng shuǐguǒ hěn tián", ko: "이 종류의 과일은 달아요." } },
        { zh: "条", pinyin: "tiáo", ko: "(가늘고 긴 것을 세는) ~줄, ~마리", pos: "양사", hanja: "조(條) — '가지 조'. 길·강·물고기·바지 등에 써요.", ex: { zh: "我买了一条鱼。", pinyin: "wǒ mǎi le yì tiáo yú", ko: "저는 물고기 한 마리를 샀어요." } },
        { zh: "辆", pinyin: "liàng", ko: "~대 (차량을 세는 양사)", pos: "양사", hanja: "량(輛) — '수레 량'.", ex: { zh: "门口停着一辆车。", pinyin: "ménkǒu tíng zhe yí liàng chē", ko: "입구에 차 한 대가 서 있어요." } },
        { zh: "双", pinyin: "shuāng", ko: "쌍, 켤레 (양사)", pos: "양사", hanja: "쌍(雙) — '쌍 쌍'. 신발·젓가락 등에 써요.", ex: { zh: "我买了一双鞋。", pinyin: "wǒ mǎi le yì shuāng xié", ko: "저는 신발 한 켤레를 샀어요." } },
        { zh: "层", pinyin: "céng", ko: "층 (양사)", pos: "양사", hanja: "층(層) — '층 층'.", ex: { zh: "我家在三层。", pinyin: "wǒ jiā zài sān céng", ko: "우리 집은 3층에 있어요." } },
        { zh: "段", pinyin: "duàn", ko: "(시간·거리·글의) 토막, 구간 (양사)", pos: "양사", hanja: "단(段) — '구분 단'.", ex: { zh: "这段时间我很忙。", pinyin: "zhè duàn shíjiān wǒ hěn máng", ko: "요즘 한동안 저는 바빠요." } },
        { zh: "位", pinyin: "wèi", ko: "분 (사람을 높여 세는 양사)", pos: "양사", hanja: "위(位) — '자리 위'. 사람을 정중히 셀 때 써요.", ex: { zh: "请问您几位？", pinyin: "qǐngwèn nín jǐ wèi", ko: "실례지만 몇 분이세요?" } },
        { zh: "口", pinyin: "kǒu", ko: "입; (식구·한 입을 세는) 양사", pos: "양사", hanja: "구(口) — '입 구'.", ex: { zh: "我家有四口人。", pinyin: "wǒ jiā yǒu sì kǒu rén", ko: "우리 집은 네 식구예요." } },
        { zh: "楼", pinyin: "lóu", ko: "건물, 층, 빌딩", pos: "명사", hanja: "루(樓) — '다락 루'.", ex: { zh: "他住在这栋楼。", pinyin: "tā zhù zài zhè dòng lóu", ko: "그는 이 건물에 살아요." } },
        { zh: "角", pinyin: "jiǎo", ko: "뿔, 모서리; 자오(화폐 단위)", pos: "명사", hanja: "각(角) — '뿔 각'.", ex: { zh: "桌子的角很尖。", pinyin: "zhuōzi de jiǎo hěn jiān", ko: "탁자 모서리가 뾰족해요." } },
        { zh: "半", pinyin: "bàn", ko: "절반, 반", pos: "수사", hanja: "반(半) — '반 반'.", ex: { zh: "现在是两点半。", pinyin: "xiànzài shì liǎng diǎn bàn", ko: "지금은 2시 반이에요." } },
        { zh: "分", pinyin: "fēn", ko: "나누다; 분(시간·점수·화폐 단위)", pos: "동사", hanja: "분(分) — '나눌 분'.", ex: { zh: "请把蛋糕分一下。", pinyin: "qǐng bǎ dàngāo fēn yíxià", ko: "케이크를 좀 나눠 주세요." } },
        { zh: "包", pinyin: "bāo", ko: "가방; 싸다, 포장하다; (만두 등) ~봉지", pos: "명사", hanja: "포(包) — '쌀 포'.", ex: { zh: "这个包很好看。", pinyin: "zhège bāo hěn hǎokàn", ko: "이 가방 예뻐요." } },
        { zh: "班", pinyin: "bān", ko: "반, 학급; 근무 (조)", pos: "명사", hanja: "반(班) — '나눌 반'. '班级(반)'의 반.", ex: { zh: "我们班有三十个学生。", pinyin: "wǒmen bān yǒu sānshí ge xuésheng", ko: "우리 반에는 학생이 서른 명 있어요." } },
        { zh: "米", pinyin: "mǐ", ko: "쌀; 미터(m)", pos: "명사", hanja: "미(米) — '쌀 미'. 길이 단위 '미터'로도 써요.", ex: { zh: "这条路有一百米长。", pinyin: "zhè tiáo lù yǒu yìbǎi mǐ cháng", ko: "이 길은 100미터 길이예요." } },
        { zh: "万", pinyin: "wàn", ko: "만(10,000)", pos: "수사", hanja: "만(萬) — '일만 만'.", ex: { zh: "这台电脑一万块。", pinyin: "zhè tái diànnǎo yí wàn kuài", ko: "이 컴퓨터는 만 위안이에요." } },
        { zh: "一会儿", pinyin: "yī huì r", ko: "잠깐, 잠시", pos: "명사", hanja: "일회아(一會兒) — '一'은 한 일, '會'는 모일 회.", ex: { zh: "请等我一会儿。", pinyin: "qǐng děng wǒ yíhuìr", ko: "잠깐만 기다려 주세요." } },
      ],
    },
  ],
};
