/**
 * H3 (HSK 3급) HSK 3.0 표준 보강 어휘 — 공식 어휘표(drkameleon/complete-hsk-vocabulary, MIT)에서
 * 기존에 없던 370개를 채웠어요. 한자·병음·품사는 표준 데이터, 뜻·예문은 학습용으로 작성.
 */
const themes = {
  themes: [
    {
      name: "HSK3 3.0 보강",
      icon: "🟩",
      words: [
        { zh: "按", pinyin: "àn", ko: "~에 따라, 누르다", pos: "전치사", ex: { zh: "请按规定办事。", pinyin: "Qǐng àn guīdìng bànshì.", ko: "규정에 따라 일을 처리해 주세요." } },
        { zh: "白菜", pinyin: "bái cài", ko: "배추", pos: "명사", ex: { zh: "妈妈买了两棵白菜。", pinyin: "Māma mǎi le liǎng kē báicài.", ko: "엄마는 배추 두 포기를 샀다." } },
        { zh: "班级", pinyin: "bān jí", ko: "학급, 반", pos: "명사", ex: { zh: "每个班级都有自己的教室。", pinyin: "Měi gè bānjí dōu yǒu zìjǐ de jiàoshì.", ko: "각 학급마다 자기 교실이 있다." } },
        { zh: "板", pinyin: "bǎn", ko: "판, 널빤지", pos: "명사", ex: { zh: "工人正在钉木板。", pinyin: "Gōngrén zhèngzài dīng mùbǎn.", ko: "인부가 나무판을 못질하고 있다." } },
        { zh: "保", pinyin: "bǎo", ko: "보호하다, 지키다", pos: "동사", ex: { zh: "我们要保护环境。", pinyin: "Wǒmen yào bǎohù huánjìng.", ko: "우리는 환경을 보호해야 한다." } },
        { zh: "保安", pinyin: "bǎo ān", ko: "경비원, 보안", pos: "형용사", ex: { zh: "保安在门口检查证件。", pinyin: "Bǎoān zài ménkǒu jiǎnchá zhèngjiàn.", ko: "경비원이 입구에서 신분증을 확인한다." } },
        { zh: "报", pinyin: "bào", ko: "신문, 알리다, 보고", pos: "명사", ex: { zh: "他每天看报。", pinyin: "Tā měitiān kàn bào.", ko: "그는 매일 신문을 본다." } },
        { zh: "报到", pinyin: "bào dào", ko: "등록하다, 체크인하다", pos: "동사", ex: { zh: "新生今天来学校报到。", pinyin: "Xīnshēng jīntiān lái xuéxiào bàodào.", ko: "신입생이 오늘 학교에 등록하러 왔다." } },
        { zh: "北部", pinyin: "běi bù", ko: "북부", pos: "명사", ex: { zh: "他住在城市的北部。", pinyin: "Tā zhù zài chéngshì de běibù.", ko: "그는 도시의 북부에 산다." } },
        { zh: "背后", pinyin: "bèi hòu", ko: "뒤, 배후", pos: "명사", ex: { zh: "有人在他背后说他坏话。", pinyin: "Yǒu rén zài tā bèihòu shuō tā huàihuà.", ko: "누군가 그의 뒤에서 그를 험담한다." } },
        { zh: "本事", pinyin: "běn shì", ko: "원작, 본래 이야기", pos: "명사", ex: { zh: "这部电影的本事来自一部小说。", pinyin: "Zhè bù diànyǐng de běnshì láizì yī bù xiǎoshuō.", ko: "이 영화의 원작 이야기는 한 소설에서 비롯되었다." } },
        { zh: "变为", pinyin: "biàn wéi", ko: "~로 변하다, ~이 되다", pos: "동사", ex: { zh: "沙漠逐渐变为绿洲。", pinyin: "Shāmò zhújiàn biànwéi lǜzhōu.", ko: "사막이 점차 오아시스로 변했다." } },
        { zh: "标题", pinyin: "biāo tí", ko: "제목, 표제", pos: "명사", ex: { zh: "这篇文章的标题很吸引人。", pinyin: "Zhè piān wénzhāng de biāotí hěn xīyǐn rén.", ko: "이 글의 제목은 매우 흥미롭다." } },
        { zh: "并", pinyin: "bìng", ko: "그리고, 또한", pos: "부사", ex: { zh: "他学习努力,并取得了好成绩。", pinyin: "Tā xuéxí nǔlì, bìng qǔdé le hǎo chéngjì.", ko: "그는 열심히 공부했고, 또한 좋은 성적을 얻었다." } },
        { zh: "播出", pinyin: "bō chū", ko: "방송하다", pos: "동사", ex: { zh: "这部电视剧将在下周播出。", pinyin: "Zhè bù diànshìjù jiāng zài xià zhōu bōchū.", ko: "이 드라마는 다음 주에 방송될 것이다." } },
        { zh: "播放", pinyin: "bō fàng", ko: "방영하다, 재생하다", pos: "동사", ex: { zh: "电视台正在播放新闻。", pinyin: "Diànshìtái zhèngzài bōfàng xīnwén.", ko: "방송국이 뉴스를 방영하고 있다." } },
        { zh: "补", pinyin: "bǔ", ko: "보충하다, 기우다, 메우다", pos: "동사", ex: { zh: "妈妈在补衣服。", pinyin: "Māma zài bǔ yīfu.", ko: "엄마가 옷을 기우고 있다." } },
        { zh: "不光", pinyin: "bù guāng", ko: "~뿐만 아니라", pos: "접속사", ex: { zh: "他不光会说英语,还会说法语。", pinyin: "Tā bùguāng huì shuō Yīngyǔ, hái huì shuō Fǎyǔ.", ko: "그는 영어뿐만 아니라 프랑스어도 할 줄 안다." } },
        { zh: "不论", pinyin: "bù lùn", ko: "~을 막론하고, ~든지", pos: "접속사", ex: { zh: "不论天气怎样,我们都要出发。", pinyin: "Bùlùn tiānqì zěnyàng, wǒmen dōu yào chūfā.", ko: "날씨가 어떻든 우리는 출발해야 한다." } },
        { zh: "步", pinyin: "bù", ko: "걸음, 보", pos: "명사", ex: { zh: "他向前走了几步。", pinyin: "Tā xiàng qián zǒu le jǐ bù.", ko: "그는 앞으로 몇 걸음 걸었다." } },
        { zh: "部", pinyin: "bù", ko: "부, 부서; (영화·서적 단위)", pos: "양사", ex: { zh: "这部电影很感人。", pinyin: "Zhè bù diànyǐng hěn gǎnrén.", ko: "이 영화는 매우 감동적이다." } },
        { zh: "部长", pinyin: "bù zhǎng", ko: "부장, 장관", pos: "명사", ex: { zh: "教育部长今天发表了讲话。", pinyin: "Jiàoyù bùzhǎng jīntiān fābiǎo le jiǎnghuà.", ko: "교육부 장관이 오늘 연설을 발표했다." } },
        { zh: "才能", pinyin: "cái néng", ko: "재능", pos: "명사", ex: { zh: "他有很高的音乐才能。", pinyin: "Tā yǒu hěn gāo de yīnyuè cáinéng.", ko: "그는 뛰어난 음악적 재능을 가지고 있다." } },
        { zh: "采用", pinyin: "cǎi yòng", ko: "채택하다, 채용하다", pos: "동사", ex: { zh: "学校决定采用新的教学方法。", pinyin: "Xuéxiào juédìng cǎiyòng xīn de jiàoxué fāngfǎ.", ko: "학교는 새로운 교육 방법을 채택하기로 결정했다." } },
        { zh: "彩色", pinyin: "cǎi sè", ko: "컬러의, 다채로운", pos: "형용사", ex: { zh: "这是一台彩色打印机。", pinyin: "Zhè shì yī tái cǎisè dǎyìnjī.", ko: "이것은 컬러 프린터이다." } },
        { zh: "厂", pinyin: "chǎng", ko: "공장", pos: "명사", ex: { zh: "他在一家工厂工作。", pinyin: "Tā zài yì jiā gōngchǎng gōngzuò.", ko: "그는 한 공장에서 일한다." } },
        { zh: "场合", pinyin: "chǎng hé", ko: "상황, 자리, 경우", pos: "명사", ex: { zh: "在正式场合要注意礼仪。", pinyin: "Zài zhèngshì chǎnghé yào zhùyì lǐyí.", ko: "공식적인 자리에서는 예의를 지켜야 한다." } },
        { zh: "场所", pinyin: "chǎng suǒ", ko: "장소", pos: "명사", ex: { zh: "图书馆是学习的好场所。", pinyin: "Túshūguǎn shì xuéxí de hǎo chǎngsuǒ.", ko: "도서관은 공부하기 좋은 장소이다." } },
        { zh: "超级", pinyin: "chāo jí", ko: "슈퍼, 초(超)~", pos: "형용사", ex: { zh: "这是一家超级市场。", pinyin: "Zhè shì yī jiā chāojí shìchǎng.", ko: "이곳은 슈퍼마켓이다." } },
        { zh: "衬衣", pinyin: "chèn yī", ko: "셔츠", pos: "명사", ex: { zh: "他穿着一件白衬衣。", pinyin: "Tā chuānzhe yī jiàn bái chènyī.", ko: "그는 흰 셔츠를 입고 있다." } },
        { zh: "称为", pinyin: "chēng wéi", ko: "~라고 불리다, ~라고 일컫다", pos: "동사", ex: { zh: "他被称为天才。", pinyin: "Tā bèi chēngwéi tiāncái.", ko: "그는 천재라고 불린다." } },
        { zh: "成员", pinyin: "chéng yuán", ko: "구성원, 멤버", pos: "명사", ex: { zh: "每个家庭成员都很重要。", pinyin: "Měi gè jiātíng chéngyuán dōu hěn zhòngyào.", ko: "모든 가족 구성원이 다 중요하다." } },
        { zh: "城", pinyin: "chéng", ko: "성, 도시", pos: "명사", ex: { zh: "这座古城有很长的历史。", pinyin: "Zhè zuò gǔchéng yǒu hěn cháng de lìshǐ.", ko: "이 고대 도시는 오랜 역사를 가지고 있다." } },
        { zh: "初", pinyin: "chū", ko: "처음, 초", pos: "명사", ex: { zh: "我们初次见面。", pinyin: "Wǒmen chū cì jiànmiàn.", ko: "우리는 처음 만났다." } },
        { zh: "初步", pinyin: "chū bù", ko: "초보의, 예비의", pos: "부사", ex: { zh: "我们已经有了初步的计划。", pinyin: "Wǒmen yǐjīng yǒu le chūbù de jìhuà.", ko: "우리는 이미 초보적인 계획을 세웠다." } },
        { zh: "初一", pinyin: "chū yī", ko: "초하루; 중학교 1학년", pos: "명사", ex: { zh: "弟弟今年上初一。", pinyin: "Dìdi jīnnián shàng chūyī.", ko: "남동생은 올해 중학교 1학년이다." } },
        { zh: "初中", pinyin: "chū zhōng", ko: "중학교", pos: "명사", ex: { zh: "她在附近的初中上学。", pinyin: "Tā zài fùjìn de chūzhōng shàngxué.", ko: "그녀는 근처 중학교에 다닌다." } },
        { zh: "传", pinyin: "chuán", ko: "전하다, 전달하다", pos: "동사", ex: { zh: "这个消息很快就传开了。", pinyin: "Zhège xiāoxi hěn kuài jiù chuánkāi le.", ko: "이 소식은 빠르게 퍼졌다." } },
        { zh: "传来", pinyin: "chuán lái", ko: "(소리·소식이) 들려오다", pos: "동사", ex: { zh: "远处传来阵阵歌声。", pinyin: "Yuǎnchù chuánlái zhènzhèn gēshēng.", ko: "멀리서 노랫소리가 들려온다." } },
        { zh: "创新", pinyin: "chuàng xīn", ko: "혁신하다, 창의적이다", pos: "동사", ex: { zh: "这家公司非常注重创新。", pinyin: "Zhè jiā gōngsī fēicháng zhùzhòng chuàngxīn.", ko: "이 회사는 혁신을 매우 중시한다." } },
        { zh: "创业", pinyin: "chuàng yè", ko: "창업하다", pos: "동사", ex: { zh: "他辞职去创业了。", pinyin: "Tā cí zhí qù chuàng yè le.", ko: "그는 사직하고 창업했다." } },
        { zh: "创作", pinyin: "chuàng zuò", ko: "창작하다", pos: "동사", ex: { zh: "她正在创作一部小说。", pinyin: "Tā zhèng zài chuàng zuò yí bù xiǎo shuō.", ko: "그녀는 소설을 창작하고 있다." } },
        { zh: "村", pinyin: "cūn", ko: "마을, 촌", pos: "명사", ex: { zh: "这个村有一百多户人家。", pinyin: "Zhè ge cūn yǒu yì bǎi duō hù rén jiā.", ko: "이 마을에는 백여 가구가 있다." } },
        { zh: "打破", pinyin: "dǎ pò", ko: "깨다, 타파하다", pos: "동사", ex: { zh: "他打破了世界纪录。", pinyin: "Tā dǎ pò le shì jiè jì lù.", ko: "그는 세계 기록을 깼다." } },
        { zh: "代", pinyin: "dài", ko: "대신하다, 대체하다", pos: "동사", ex: { zh: "他今天生病了,我来代他上课。", pinyin: "Tā jīn tiān shēng bìng le, wǒ lái dài tā shàng kè.", ko: "그가 오늘 아파서 내가 그를 대신해 수업한다." } },
        { zh: "代表团", pinyin: "dài biǎo tuán", ko: "대표단", pos: "명사", ex: { zh: "中国代表团访问了这个国家。", pinyin: "Zhōng guó dài biǎo tuán fǎng wèn le zhè ge guó jiā.", ko: "중국 대표단이 이 나라를 방문했다." } },
        { zh: "带动", pinyin: "dài dòng", ko: "이끌다, 촉진하다", pos: "동사", ex: { zh: "旅游业带动了当地经济发展。", pinyin: "Lǚ yóu yè dài dòng le dāng dì jīng jì fā zhǎn.", ko: "관광업이 현지 경제 발전을 이끌었다." } },
        { zh: "带领", pinyin: "dài lǐng", ko: "인솔하다, 이끌다", pos: "동사", ex: { zh: "老师带领学生们参观博物馆。", pinyin: "Lǎo shī dài lǐng xué sheng men cān guān bó wù guǎn.", ko: "선생님이 학생들을 인솔하여 박물관을 참관했다." } },
        { zh: "当初", pinyin: "dāng chū", ko: "당초, 애초", pos: "명사", ex: { zh: "当初我们没想到会这么难。", pinyin: "Dāng chū wǒ men méi xiǎng dào huì zhè me nán.", ko: "당초 우리는 이렇게 어려울 줄 몰랐다." } },
        { zh: "当中", pinyin: "dāng zhōng", ko: "그 중, 가운데", pos: "명사", ex: { zh: "在这些学生当中,他最聪明。", pinyin: "Zài zhè xiē xué sheng dāng zhōng, tā zuì cōng ming.", ko: "이 학생들 중에서 그가 가장 똑똑하다." } },
        { zh: "得分", pinyin: "dé fēn", ko: "득점하다", pos: "동사", ex: { zh: "他在比赛中得分很高。", pinyin: "Tā zài bǐ sài zhōng dé fēn hěn gāo.", ko: "그는 경기에서 높은 점수를 얻었다." } },
        { zh: "底下", pinyin: "dǐ xia", ko: "아래, 밑", pos: "명사", ex: { zh: "猫躲在桌子底下。", pinyin: "Māo duǒ zài zhuō zi dǐ xia.", ko: "고양이가 책상 밑에 숨어 있다." } },
        { zh: "电视剧", pinyin: "diàn shì jù", ko: "TV 드라마", pos: "명사", ex: { zh: "她喜欢看韩国电视剧。", pinyin: "Tā xǐ huan kàn Hán guó diàn shì jù.", ko: "그녀는 한국 드라마 보는 것을 좋아한다." } },
        { zh: "电视台", pinyin: "diàn shì tái", ko: "TV 방송국", pos: "명사", ex: { zh: "他在电视台工作。", pinyin: "Tā zài diàn shì tái gōng zuò.", ko: "그는 방송국에서 일한다." } },
        { zh: "电子邮件", pinyin: "diàn zǐ yóu jiàn", ko: "이메일, 전자우편", pos: "", ex: { zh: "请把文件用电子邮件发给我。", pinyin: "Qǐng bǎ wén jiàn yòng diàn zǐ yóu jiàn fā gěi wǒ.", ko: "파일을 이메일로 보내주세요." } },
        { zh: "调", pinyin: "diào", ko: "옮기다, 전근시키다", pos: "동사", ex: { zh: "他被调到北京工作了。", pinyin: "Tā bèi diào dào Běi jīng gōng zuò le.", ko: "그는 베이징으로 전근되어 일하게 되었다." } },
        { zh: "订", pinyin: "dìng", ko: "예약하다, 정하다", pos: "동사", ex: { zh: "我们已经订好了机票。", pinyin: "Wǒ men yǐ jīng dìng hǎo le jī piào.", ko: "우리는 이미 비행기표를 예약했다." } },
        { zh: "定期", pinyin: "dìng qī", ko: "정기적으로", pos: "부사", ex: { zh: "他定期去医院检查身体。", pinyin: "Tā dìng qī qù yī yuàn jiǎn chá shēn tǐ.", ko: "그는 정기적으로 병원에 가서 건강검진을 받는다." } },
        { zh: "东部", pinyin: "dōng bù", ko: "동부", pos: "명사", ex: { zh: "这家公司在中国东部设有分公司。", pinyin: "Zhè jiā gōng sī zài Zhōng guó dōng bù shè yǒu fēn gōng sī.", ko: "이 회사는 중국 동부에 지사를 두고 있다." } },
        { zh: "动力", pinyin: "dòng lì", ko: "동력, 원동력", pos: "명사", ex: { zh: "兴趣是学习的动力。", pinyin: "Xìng qù shì xué xí de dòng lì.", ko: "흥미는 학습의 원동력이다." } },
        { zh: "动人", pinyin: "dòng rén", ko: "감동적이다", pos: "형용사", ex: { zh: "这是一个非常动人的故事。", pinyin: "Zhè shì yí gè fēi cháng dòng rén de gù shi.", ko: "이것은 매우 감동적인 이야기이다." } },
        { zh: "读者", pinyin: "dú zhě", ko: "독자", pos: "명사", ex: { zh: "这本书受到了读者的欢迎。", pinyin: "Zhè běn shū shòu dào le dú zhě de huān yíng.", ko: "이 책은 독자들의 환영을 받았다." } },
        { zh: "短处", pinyin: "duǎn chù", ko: "단점, 결점", pos: "명사", ex: { zh: "每个人都有自己的短处。", pinyin: "Měi gè rén dōu yǒu zì jǐ de duǎn chù.", ko: "모든 사람은 자신만의 단점이 있다." } },
        { zh: "短裤", pinyin: "duǎn kù", ko: "반바지", pos: "명사", ex: { zh: "夏天他常穿短裤。", pinyin: "Xià tiān tā cháng chuān duǎn kù.", ko: "여름에 그는 자주 반바지를 입는다." } },
        { zh: "短期", pinyin: "duǎn qī", ko: "단기의", pos: "형용사", ex: { zh: "他参加了一个短期培训班。", pinyin: "Tā cān jiā le yí gè duǎn qī péi xùn bān.", ko: "그는 단기 훈련반에 참가했다." } },
        { zh: "队员", pinyin: "duì yuán", ko: "팀원, 대원", pos: "명사", ex: { zh: "每个队员都很努力。", pinyin: "Měi gè duì yuán dōu hěn nǔ lì.", ko: "모든 팀원이 열심히 한다." } },
        { zh: "发出", pinyin: "fā chū", ko: "내다, 발송하다", pos: "동사", ex: { zh: "公司发出了一份通知。", pinyin: "Gōng sī fā chū le yí fèn tōng zhī.", ko: "회사가 통지문을 발송했다." } },
        { zh: "发动", pinyin: "fā dòng", ko: "시동 걸다, 일으키다", pos: "동사", ex: { zh: "他发动了汽车的引擎。", pinyin: "Tā fā dòng le qì chē de yǐn qíng.", ko: "그는 자동차 엔진을 시동 걸었다." } },
        { zh: "发送", pinyin: "fā sòng", ko: "발송하다, 전송하다", pos: "동사", ex: { zh: "请把邮件发送给我。", pinyin: "Qǐng bǎ yóu jiàn fā sòng gěi wǒ.", ko: "메일을 저에게 발송해주세요." } },
        { zh: "防", pinyin: "fáng", ko: "막다, 방지하다", pos: "동사", ex: { zh: "出门要防感冒。", pinyin: "Chū mén yào fáng gǎn mào.", ko: "외출할 때 감기를 조심해야 한다." } },
        { zh: "防止", pinyin: "fáng zhǐ", ko: "방지하다", pos: "동사", ex: { zh: "我们要防止事故的发生。", pinyin: "Wǒ men yào fáng zhǐ shì gù de fā shēng.", ko: "우리는 사고 발생을 방지해야 한다." } },
        { zh: "房屋", pinyin: "fáng wū", ko: "가옥, 집", pos: "명사", ex: { zh: "这栋房屋已经有一百年历史了。", pinyin: "Zhè dòng fáng wū yǐ jīng yǒu yì bǎi nián lì shǐ le.", ko: "이 집은 이미 백 년의 역사를 가지고 있다." } },
        { zh: "房租", pinyin: "fáng zū", ko: "집세, 월세", pos: "명사", ex: { zh: "这个月的房租还没交。", pinyin: "Zhè ge yuè de fáng zū hái méi jiāo.", ko: "이번 달 집세를 아직 내지 않았다." } },
        { zh: "放到", pinyin: "fàng dào", ko: "~에 놓다, 두다", pos: "동사", ex: { zh: "请把书放到桌子上。", pinyin: "Qǐng bǎ shū fàng dào zhuō zi shàng.", ko: "책을 책상 위에 놓아주세요." } },
        { zh: "飞行", pinyin: "fēi xíng", ko: "비행하다", pos: "동사", ex: { zh: "飞机正在高空飞行。", pinyin: "Fēi jī zhèng zài gāo kōng fēi xíng.", ko: "비행기가 고공에서 비행하고 있다." } },
        { zh: "费", pinyin: "fèi", ko: "비용, 요금", pos: "명사", ex: { zh: "这次旅行的费用不便宜。", pinyin: "Zhè cì lǚ xíng de fèi yong bù pián yi.", ko: "이번 여행 비용은 저렴하지 않다." } },
        { zh: "分组", pinyin: "fēn zǔ", ko: "조를 나누다", pos: "동사", ex: { zh: "老师把学生分组进行讨论。", pinyin: "Lǎo shī bǎ xué sheng fēn zǔ jìn xíng tǎo lùn.", ko: "선생님은 학생들을 조로 나누어 토론을 진행했다." } },
        { zh: "福", pinyin: "fú", ko: "복, 행운", pos: "명사", ex: { zh: "春节的时候人们喜欢在门上贴福字。", pinyin: "Chūn jié de shí hou rén men xǐ huan zài mén shàng tiē fú zì.", ko: "설날에 사람들은 문에 '복(福)'자를 붙이는 것을 좋아한다." } },
        { zh: "父母", pinyin: "fù mǔ", ko: "부모", pos: "명사", ex: { zh: "我很爱我的父母。", pinyin: "Wǒ hěn ài wǒ de fù mǔ.", ko: "나는 부모님을 매우 사랑한다." } },
        { zh: "付", pinyin: "fù", ko: "지불하다", pos: "동사", ex: { zh: "谁来付钱?", pinyin: "Shéi lái fù qián?", ko: "누가 돈을 낼 거예요?" } },
        { zh: "改造", pinyin: "gǎi zào", ko: "개조하다, 개혁하다", pos: "동사", ex: { zh: "这座老房子被改造成了博物馆。", pinyin: "Zhè zuò lǎo fáng zi bèi gǎi zào chéng le bó wù guǎn.", ko: "이 오래된 집은 박물관으로 개조되었다." } },
        { zh: "赶", pinyin: "gǎn", ko: "서두르다, 쫓다, (차 등을) 잡다", pos: "동사", ex: { zh: "我们得赶时间了。", pinyin: "Wǒ men děi gǎn shí jiān le.", ko: "우리는 서둘러야 한다." } },
        { zh: "赶到", pinyin: "gǎn dào", ko: "서둘러 도착하다", pos: "동사", ex: { zh: "他及时赶到了机场。", pinyin: "Tā jí shí gǎn dào le jī chǎng.", ko: "그는 제때 공항에 도착했다." } },
        { zh: "干吗", pinyin: "gàn má", ko: "왜, 뭐하러", pos: "동사", ex: { zh: "你干吗不告诉我？", pinyin: "Nǐ gàn má bú gào su wǒ?", ko: "너는 왜 나에게 말하지 않았어?" } },
        { zh: "高速公路", pinyin: "gāo sù gōng lù", ko: "고속도로", pos: "명사", ex: { zh: "我们开车走高速公路。", pinyin: "Wǒ men kāi chē zǒu gāo sù gōng lù.", ko: "우리는 차를 타고 고속도로로 간다." } },
        { zh: "歌迷", pinyin: "gē mí", ko: "(가수의) 팬", pos: "명사", ex: { zh: "我是他的歌迷。", pinyin: "Wǒ shì tā de gē mí.", ko: "나는 그의 팬이다." } },
        { zh: "歌声", pinyin: "gē shēng", ko: "노랫소리", pos: "명사", ex: { zh: "远处传来歌声。", pinyin: "Yuǎn chù chuán lái gē shēng.", ko: "멀리서 노랫소리가 들려온다." } },
        { zh: "歌手", pinyin: "gē shǒu", ko: "가수", pos: "명사", ex: { zh: "她是有名的歌手。", pinyin: "Tā shì yǒu míng de gē shǒu.", ko: "그녀는 유명한 가수이다." } },
        { zh: "各地", pinyin: "gè dì", ko: "각지, 각처", pos: "대명사", ex: { zh: "游客来自各地。", pinyin: "Yóu kè lái zì gè dì.", ko: "관광객들이 각지에서 온다." } },
        { zh: "各位", pinyin: "gè wèi", ko: "여러분", pos: "대명사", ex: { zh: "各位请注意。", pinyin: "Gè wèi qǐng zhù yì.", ko: "여러분 주목해 주세요." } },
        { zh: "各种", pinyin: "gè zhǒng", ko: "각종, 여러 가지", pos: "대명사", ex: { zh: "商店里有各种商品。", pinyin: "Shāng diàn lǐ yǒu gè zhǒng shāng pǐn.", ko: "가게 안에는 각종 상품이 있다." } },
        { zh: "公共", pinyin: "gōng gòng", ko: "공공의", pos: "형용사", ex: { zh: "请爱护公共设施。", pinyin: "Qǐng ài hù gōng gòng shè shī.", ko: "공공시설을 아껴 주세요." } },
        { zh: "公民", pinyin: "gōng mín", ko: "시민, 공민", pos: "명사", ex: { zh: "每个公民都有责任。", pinyin: "Měi gè gōng mín dōu yǒu zé rèn.", ko: "모든 시민은 책임이 있다." } },
        { zh: "公务员", pinyin: "gōng wù yuán", ko: "공무원", pos: "명사", ex: { zh: "他考上了公务员。", pinyin: "Tā kǎo shàng le gōng wù yuán.", ko: "그는 공무원 시험에 합격했다." } },
        { zh: "功课", pinyin: "gōng kè", ko: "숙제, 공부", pos: "명사", ex: { zh: "我每天做功课。", pinyin: "Wǒ měi tiān zuò gōng kè.", ko: "나는 매일 숙제를 한다." } },
        { zh: "共有", pinyin: "gòng yǒu", ko: "합계 ~이다, 총 ~을 가지다", pos: "동사", ex: { zh: "我们班共有三十个学生。", pinyin: "Wǒ men bān gòng yǒu sān shí gè xué sheng.", ko: "우리 반은 총 30명의 학생이 있다." } },
        { zh: "古", pinyin: "gǔ", ko: "옛날의, 고대의", pos: "형용사", ex: { zh: "这是一座古城。", pinyin: "Zhè shì yí zuò gǔ chéng.", ko: "이곳은 고대 도시이다." } },
        { zh: "故乡", pinyin: "gù xiāng", ko: "고향", pos: "명사", ex: { zh: "我很想念故乡。", pinyin: "Wǒ hěn xiǎng niàn gù xiāng.", ko: "나는 고향이 매우 그립다." } },
        { zh: "关注", pinyin: "guān zhù", ko: "관심을 갖다, 주목하다", pos: "동사", ex: { zh: "大家都很关注这件事。", pinyin: "Dà jiā dōu hěn guān zhù zhè jiàn shì.", ko: "모두가 이 일에 관심을 갖고 있다." } },
        { zh: "观看", pinyin: "guān kàn", ko: "관람하다, 시청하다", pos: "동사", ex: { zh: "我们一起观看比赛。", pinyin: "Wǒ men yì qǐ guān kàn bǐ sài.", ko: "우리는 함께 경기를 관람한다." } },
        { zh: "管", pinyin: "guǎn", ko: "관리하다, 상관하다", pos: "동사", ex: { zh: "这件事不用你管。", pinyin: "Zhè jiàn shì bú yòng nǐ guǎn.", ko: "이 일은 네가 신경 쓸 필요 없다." } },
        { zh: "规范", pinyin: "guī fàn", ko: "규범, 기준", pos: "동사", ex: { zh: "请按照规范操作。", pinyin: "Qǐng àn zhào guī fàn cāo zuò.", ko: "규범에 따라 조작해 주세요." } },
        { zh: "国内", pinyin: "guó nèi", ko: "국내", pos: "", ex: { zh: "这是国内最大的城市。", pinyin: "Zhè shì guó nèi zuì dà de chéng shì.", ko: "이곳은 국내 최대 도시이다." } },
        { zh: "国庆", pinyin: "Guó qìng", ko: "국경절", pos: "명사", ex: { zh: "国庆节我们放假七天。", pinyin: "Guó qìng jié wǒ men fàng jià qī tiān.", ko: "국경절에 우리는 7일 동안 쉰다." } },
        { zh: "哈哈", pinyin: "hā hā", ko: "하하 (웃음소리)", pos: "", ex: { zh: "哈哈，这个笑话真好笑。", pinyin: "Hā hā, zhè ge xiào huà zhēn hǎo xiào.", ko: "하하, 이 농담 정말 재미있다." } },
        { zh: "好好", pinyin: "hǎo hǎo", ko: "잘, 충분히", pos: "부사", ex: { zh: "你要好好休息。", pinyin: "Nǐ yào hǎo hǎo xiū xi.", ko: "너는 잘 쉬어야 한다." } },
        { zh: "合", pinyin: "hé", ko: "합하다, 맞다", pos: "동사", ex: { zh: "这两部分正好合在一起。", pinyin: "Zhè liǎng bùfen zhènghǎo hé zài yìqǐ.", ko: "이 두 부분은 딱 맞게 합쳐진다." } },
        { zh: "红茶", pinyin: "hóng chá", ko: "홍차", pos: "명사", ex: { zh: "我喜欢喝红茶。", pinyin: "Wǒ xǐ huan hē hóng chá.", ko: "나는 홍차 마시는 것을 좋아한다." } },
        { zh: "红酒", pinyin: "hóng jiǔ", ko: "레드와인", pos: "", ex: { zh: "他点了一杯红酒。", pinyin: "Tā diǎn le yì bēi hóng jiǔ.", ko: "그는 레드와인 한 잔을 주문했다." } },
        { zh: "后年", pinyin: "hòu nián", ko: "내후년", pos: "명사", ex: { zh: "后年我就大学毕业了。", pinyin: "Hòu nián wǒ jiù dà xué bì yè le.", ko: "내후년이면 나는 대학을 졸업한다." } },
        { zh: "互联网", pinyin: "Hù lián wǎng", ko: "인터넷", pos: "명사", ex: { zh: "互联网改变了我们的生活。", pinyin: "Hù lián wǎng gǎi biàn le wǒ men de shēng huó.", ko: "인터넷은 우리의 생활을 바꾸었다." } },
        { zh: "华人", pinyin: "Huá rén", ko: "화교, 중국계 사람", pos: "명사", ex: { zh: "这里住着很多华人。", pinyin: "Zhè lǐ zhù zhe hěn duō Huá rén.", ko: "이곳에는 많은 화교가 살고 있다." } },
        { zh: "化", pinyin: "huà", ko: "~화하다, 변하다", pos: "동사", ex: { zh: "冰化成了水。", pinyin: "Bīng huà chéng le shuǐ.", ko: "얼음이 물로 변했다." } },
        { zh: "话剧", pinyin: "huà jù", ko: "연극", pos: "명사", ex: { zh: "我们去看话剧。", pinyin: "Wǒ men qù kàn huà jù.", ko: "우리는 연극을 보러 간다." } },
        { zh: "环", pinyin: "huán", ko: "고리", pos: "명사", ex: { zh: "她戴着一个玉环。", pinyin: "Tā dài zhe yí gè yù huán.", ko: "그녀는 옥고리를 하나 차고 있다." } },
        { zh: "欢乐", pinyin: "huān lè", ko: "즐거운, 유쾌한", pos: "형용사", ex: { zh: "大家度过了欢乐的周末。", pinyin: "Dà jiā dù guò le huān lè de zhōu mò.", ko: "모두 즐거운 주말을 보냈다." } },
        { zh: "会员", pinyin: "huì yuán", ko: "회원", pos: "명사", ex: { zh: "我是这家健身房的会员。", pinyin: "Wǒ shì zhè jiā jiàn shēn fáng de huì yuán.", ko: "나는 이 헬스장의 회원이다." } },
        { zh: "活", pinyin: "huó", ko: "살다", pos: "동사", ex: { zh: "他还活着。", pinyin: "Tā hái huó zhe.", ko: "그는 아직 살아 있다." } },
        { zh: "积极性", pinyin: "jī jí xìng", ko: "적극성, 열의", pos: "명사", ex: { zh: "老师提高了学生的积极性。", pinyin: "Lǎo shī tí gāo le xué sheng de jī jí xìng.", ko: "선생님은 학생들의 적극성을 높였다." } },
        { zh: "基本上", pinyin: "jī běn shang", ko: "기본적으로, 대체로", pos: "부사", ex: { zh: "这件事基本上完成了。", pinyin: "Zhè jiàn shì jī běn shang wán chéng le.", ko: "이 일은 대체로 완성되었다." } },
        { zh: "极了", pinyin: "jí le", ko: "극히, 매우", pos: "조사", ex: { zh: "这个电影好看极了。", pinyin: "Zhège diànyǐng hǎokàn jí le.", ko: "이 영화는 정말 재미있다." } },
        { zh: "加工", pinyin: "jiā gōng", ko: "가공하다", pos: "동사", ex: { zh: "这些原料需要加工。", pinyin: "Zhèxiē yuánliào xūyào jiāgōng.", ko: "이 원료들은 가공이 필요하다." } },
        { zh: "加快", pinyin: "jiā kuài", ko: "속도를 높이다, 가속화하다", pos: "동사", ex: { zh: "我们要加快工作进度。", pinyin: "Wǒmen yào jiākuài gōngzuò jìndù.", ko: "우리는 작업 진행을 가속화해야 한다." } },
        { zh: "加强", pinyin: "jiā qiáng", ko: "강화하다", pos: "동사", ex: { zh: "我们需要加强合作。", pinyin: "Wǒmen xūyào jiāqiáng hézuò.", ko: "우리는 협력을 강화할 필요가 있다." } },
        { zh: "家属", pinyin: "jiā shǔ", ko: "가족, 식솔", pos: "명사", ex: { zh: "病人的家属在外面等着。", pinyin: "Bìngrén de jiāshǔ zài wàimiàn děng zhe.", ko: "환자의 가족들이 밖에서 기다리고 있다." } },
        { zh: "价钱", pinyin: "jià qian", ko: "가격", pos: "명사", ex: { zh: "这件衣服的价钱不贵。", pinyin: "Zhè jiàn yīfu de jiàqian bú guì.", ko: "이 옷의 가격은 비싸지 않다." } },
        { zh: "架", pinyin: "jià", ko: "받치다, 세우다; 선반", pos: "동사", ex: { zh: "他把梯子架在墙上。", pinyin: "Tā bǎ tīzi jià zài qiáng shàng.", ko: "그는 사다리를 벽에 세워 놓았다." } },
        { zh: "建", pinyin: "jiàn", ko: "세우다, 건설하다", pos: "동사", ex: { zh: "这里要建一座大楼。", pinyin: "Zhèlǐ yào jiàn yí zuò dàlóu.", ko: "여기에 빌딩을 세울 것이다." } },
        { zh: "建成", pinyin: "jiàn chéng", ko: "완공하다, 건설을 마치다", pos: "동사", ex: { zh: "这座桥已经建成了。", pinyin: "Zhè zuò qiáo yǐjīng jiànchéng le.", ko: "이 다리는 이미 완공되었다." } },
        { zh: "将近", pinyin: "jiāng jìn", ko: "거의 ~에 가깝다", pos: "부사", ex: { zh: "这个项目将近完成了。", pinyin: "Zhège xiàngmù jiāng jìn wánchéng le.", ko: "이 프로젝트는 거의 완성되어 간다." } },
        { zh: "交费", pinyin: "jiāo fèi", ko: "비용을 납부하다", pos: "동사", ex: { zh: "请到窗口交费。", pinyin: "Qǐng dào chuāngkǒu jiāofèi.", ko: "창구로 가서 비용을 납부해 주세요." } },
        { zh: "交警", pinyin: "jiāo jǐng", ko: "교통경찰", pos: "명사", ex: { zh: "交警在路口指挥交通。", pinyin: "Jiāojǐng zài lùkǒu zhǐhuī jiāotōng.", ko: "교통경찰이 교차로에서 교통을 정리하고 있다." } },
        { zh: "交往", pinyin: "jiāo wǎng", ko: "사귀다, 왕래하다", pos: "동사", ex: { zh: "他们已经交往三年了。", pinyin: "Tāmen yǐjīng jiāowǎng sān nián le.", ko: "그들은 사귄 지 이미 3년이 되었다." } },
        { zh: "交易", pinyin: "jiāo yì", ko: "거래", pos: "명사", ex: { zh: "这笔交易很成功。", pinyin: "Zhè bǐ jiāoyì hěn chénggōng.", ko: "이 거래는 매우 성공적이었다." } },
        { zh: "较", pinyin: "jiào", ko: "비교적, ~보다", pos: "부사", ex: { zh: "今年的天气较去年热。", pinyin: "Jīnnián de tiānqì jiào qùnián rè.", ko: "올해 날씨는 작년보다 덥다." } },
        { zh: "解开", pinyin: "jiě kāi", ko: "풀다, 해결하다", pos: "동사", ex: { zh: "他解开了这个谜题。", pinyin: "Tā jiěkāi le zhège mítí.", ko: "그는 이 수수께끼를 풀었다." } },
        { zh: "金", pinyin: "jīn", ko: "금, 황금; 성씨(김/진)", pos: "명사", ex: { zh: "这条项链是金的。", pinyin: "Zhè tiáo xiàngliàn shì jīn de.", ko: "이 목걸이는 금으로 되어 있다." } },
        { zh: "金牌", pinyin: "jīn pái", ko: "금메달", pos: "명사", ex: { zh: "她获得了奥运金牌。", pinyin: "Tā huòdé le Àoyùn jīnpái.", ko: "그녀는 올림픽 금메달을 획득했다." } },
        { zh: "仅", pinyin: "jǐn", ko: "겨우, 단지", pos: "부사", ex: { zh: "这次比赛仅用了十分钟。", pinyin: "Zhè cì bǐsài jǐn yòng le shí fēnzhōng.", ko: "이번 경기는 겨우 10분밖에 걸리지 않았다." } },
        { zh: "仅仅", pinyin: "jǐn jǐn", ko: "겨우, 단지", pos: "부사", ex: { zh: "他仅仅是个孩子。", pinyin: "Tā jǐnjǐn shì gè háizi.", ko: "그는 단지 어린아이일 뿐이다." } },
        { zh: "近期", pinyin: "jìn qī", ko: "가까운 시일, 근일", pos: "명사", ex: { zh: "近期天气会变冷。", pinyin: "Jìnqī tiānqì huì biàn lěng.", ko: "근일 날씨가 추워질 것이다." } },
        { zh: "进一步", pinyin: "jìn yī bù", ko: "한 걸음 더 나아가, 더욱", pos: "부사", ex: { zh: "我们需要进一步了解情况。", pinyin: "Wǒmen xūyào jìn yī bù liǎojiě qíngkuàng.", ko: "우리는 상황을 한 걸음 더 나아가 이해할 필요가 있다." } },
        { zh: "进展", pinyin: "jìn zhǎn", ko: "진전하다, 진행되다", pos: "동사", ex: { zh: "工程进展得很顺利。", pinyin: "Gōngchéng jìnzhǎn de hěn shùnlì.", ko: "공사는 순조롭게 진행되고 있다." } },
        { zh: "静", pinyin: "jìng", ko: "조용하다, 고요하다", pos: "형용사", ex: { zh: "教室里非常静。", pinyin: "Jiàoshì lǐ fēicháng jìng.", ko: "교실 안이 매우 조용하다." } },
        { zh: "就是", pinyin: "jiù shì", ko: "바로 ~이다, 다름 아니라", pos: "동사", ex: { zh: "这就是我要找的书。", pinyin: "Zhè jiùshì wǒ yào zhǎo de shū.", ko: "이것이 바로 내가 찾던 책이다." } },
        { zh: "就业", pinyin: "jiù yè", ko: "취업하다", pos: "동사", ex: { zh: "大学生就业压力很大。", pinyin: "Dàxuéshēng jiùyè yālì hěn dà.", ko: "대학생들의 취업 압박이 크다." } },
        { zh: "具有", pinyin: "jù yǒu", ko: "가지다, 구비하다", pos: "동사", ex: { zh: "这个方法具有很大的优势。", pinyin: "Zhège fāngfǎ jùyǒu hěn dà de yōushì.", ko: "이 방법은 큰 장점을 가지고 있다." } },
        { zh: "剧场", pinyin: "jù chǎng", ko: "극장", pos: "명사", ex: { zh: "我们去剧场看话剧。", pinyin: "Wǒmen qù jùchǎng kàn huàjù.", ko: "우리는 극장에 연극을 보러 간다." } },
        { zh: "开业", pinyin: "kāi yè", ko: "개업하다", pos: "동사", ex: { zh: "这家餐厅刚开业。", pinyin: "Zhè jiā cāntīng gāng kāiyè.", ko: "이 식당은 막 개업했다." } },
        { zh: "开展", pinyin: "kāi zhǎn", ko: "전개하다, 펼치다", pos: "동사", ex: { zh: "学校开展了很多活动。", pinyin: "Xuéxiào kāizhǎn le hěn duō huódòng.", ko: "학교는 많은 활동을 전개했다." } },
        { zh: "看起来", pinyin: "kàn qǐ lai", ko: "보아하니, ~처럼 보이다", pos: "동사", ex: { zh: "他看起来很累。", pinyin: "Tā kàn qǐlai hěn lèi.", ko: "그는 피곤해 보인다." } },
        { zh: "看上去", pinyin: "kàn shang qu", ko: "보기에, ~인 것 같다", pos: "동사", ex: { zh: "这个苹果看上去很新鲜。", pinyin: "Zhège píngguǒ kàn shàng qù hěn xīnxiān.", ko: "이 사과는 신선해 보인다." } },
        { zh: "考验", pinyin: "kǎo yàn", ko: "시험하다, 시련", pos: "동사", ex: { zh: "这是对我们的一次考验。", pinyin: "Zhè shì duì wǒmen de yí cì kǎoyàn.", ko: "이것은 우리에 대한 하나의 시험이다." } },
        { zh: "可乐", pinyin: "kě lè", ko: "콜라", pos: "명사", ex: { zh: "我想喝一杯可乐。", pinyin: "Wǒ xiǎng hē yì bēi kělè.", ko: "나는 콜라 한 잔을 마시고 싶다." } },
        { zh: "空", pinyin: "kōng", ko: "비다, 텅 비다", pos: "형용사", ex: { zh: "房间里空无一人。", pinyin: "Fángjiān lǐ kōng wú yì rén.", ko: "방 안에는 아무도 없다." } },
        { zh: "空儿", pinyin: "kòngr", ko: "짬, 틈, 여가 시간", pos: "명사", ex: { zh: "你有空儿吗？", pinyin: "Nǐ yǒu kòngr ma?", ko: "너 시간 있어?" } },
        { zh: "快速", pinyin: "kuài sù", ko: "빠르게, 신속히", pos: "부사", ex: { zh: "他快速地跑向终点。", pinyin: "Tā kuàisù de pǎo xiàng zhōngdiǎn.", ko: "그는 빠르게 결승점을 향해 달렸다." } },
        { zh: "老太太", pinyin: "lǎo tài tai", ko: "할머니, 노부인", pos: "명사", ex: { zh: "那位老太太每天散步。", pinyin: "Nà wèi lǎotàitai měitiān sànbù.", ko: "그 할머니는 매일 산책을 한다." } },
        { zh: "老头儿", pinyin: "lǎo tóur", ko: "노인, 할아버지", pos: "명사", ex: { zh: "老头儿坐在公园的长椅上。", pinyin: "Lǎotóur zuò zài gōngyuán de chángyǐ shàng.", ko: "노인이 공원 벤치에 앉아 있다." } },
        { zh: "乐", pinyin: "lè", ko: "즐겁다, 기쁘다; 성씨(러)", pos: "형용사", ex: { zh: "他笑得很乐。", pinyin: "Tā xiào de hěn lè.", ko: "그는 매우 즐겁게 웃는다." } },
        { zh: "乐队", pinyin: "yuè duì", ko: "악단, 밴드", pos: "명사", ex: { zh: "这支乐队很有名。", pinyin: "Zhè zhī yuèduì hěn yǒumíng.", ko: "이 밴드는 매우 유명하다." } },
        { zh: "类似", pinyin: "lèi sì", ko: "유사하다, 비슷하다", pos: "형용사", ex: { zh: "他们俩的想法类似。", pinyin: "Tāmen liǎ de xiǎngfǎ lèisì.", ko: "그들 둘의 생각은 비슷하다." } },
        { zh: "里面", pinyin: "lǐ miàn", ko: "안, 내부", pos: "명사", ex: { zh: "箱子里面是什么?", pinyin: "Xiāngzi lǐmiàn shì shénme?", ko: "상자 안에는 무엇이 있나요?" } },
        { zh: "力", pinyin: "lì", ko: "힘, 역량", pos: "명사", ex: { zh: "他用力推门。", pinyin: "Tā yònglì tuī mén.", ko: "그는 힘을 써서 문을 밀었다." } },
        { zh: "连续", pinyin: "lián xù", ko: "연속하다, 계속되다", pos: "형용사", ex: { zh: "他连续三天没睡好。", pinyin: "Tā liánxù sān tiān méi shuì hǎo.", ko: "그는 사흘 연속 잠을 잘 못 잤다." } },
        { zh: "联合国", pinyin: "Lián hé guó", ko: "국제연합, 유엔(UN)", pos: "", ex: { zh: "联合国总部在纽约。", pinyin: "Liánhéguó zǒngbù zài Niǔyuē.", ko: "유엔 본부는 뉴욕에 있다." } },
        { zh: "凉水", pinyin: "liáng shuǐ", ko: "찬물, 냉수", pos: "명사", ex: { zh: "别喝凉水,对身体不好。", pinyin: "Bié hē liángshuǐ, duì shēntǐ bù hǎo.", ko: "찬물 마시지 마, 몸에 안 좋아." } },
        { zh: "领", pinyin: "lǐng", ko: "이끌다, 인솔하다; 옷깃", pos: "동사", ex: { zh: "老师领我们去图书馆。", pinyin: "Lǎoshī lǐng wǒmen qù túshūguǎn.", ko: "선생님이 우리를 도서관으로 인솔하셨다." } },
        { zh: "领先", pinyin: "lǐng xiān", ko: "앞서다, 선두에 서다", pos: "동사", ex: { zh: "我们队一直领先。", pinyin: "Wǒmen duì yìzhí lǐngxiān.", ko: "우리 팀이 계속 앞서고 있다." } },
        { zh: "另一方面", pinyin: "lìng yī fāng miàn", ko: "다른 한편으로는", pos: "접속사", ex: { zh: "另一方面,我们也要考虑成本。", pinyin: "Lìng yī fāngmiàn, wǒmen yě yào kǎolǜ chéngběn.", ko: "다른 한편으로는, 우리는 비용도 고려해야 한다." } },
        { zh: "录", pinyin: "lù", ko: "기록하다, (소리를) 녹음하다", pos: "동사", ex: { zh: "请把这段话录下来。", pinyin: "Qǐng bǎ zhè duàn huà lù xiàlái.", ko: "이 말을 녹음해 주세요." } },
        { zh: "路线", pinyin: "lù xiàn", ko: "노선, 경로", pos: "명사", ex: { zh: "这条路线很方便。", pinyin: "Zhè tiáo lùxiàn hěn fāngbiàn.", ko: "이 노선은 매우 편리하다." } },
        { zh: "旅馆", pinyin: "lǚ guǎn", ko: "여관, 호텔", pos: "명사", ex: { zh: "我们住在一家小旅馆。", pinyin: "Wǒmen zhù zài yì jiā xiǎo lǚguǎn.", ko: "우리는 작은 여관에 묵는다." } },
        { zh: "旅行社", pinyin: "lǚ xíng shè", ko: "여행사", pos: "명사", ex: { zh: "我在旅行社订了机票。", pinyin: "Wǒ zài lǚxíngshè dìngle jīpiào.", ko: "나는 여행사에서 비행기 표를 예약했다." } },
        { zh: "绿茶", pinyin: "lǜ chá", ko: "녹차", pos: "명사", ex: { zh: "我喜欢喝绿茶。", pinyin: "Wǒ xǐhuan hē lǜchá.", ko: "나는 녹차 마시는 것을 좋아한다." } },
        { zh: "慢慢", pinyin: "màn màn", ko: "천천히", pos: "부사", ex: { zh: "请你慢慢说。", pinyin: "Qǐng nǐ mànmàn shuō.", ko: "천천히 말씀해 주세요." } },
        { zh: "没用", pinyin: "méi yòng", ko: "쓸모없다, 소용없다", pos: "동사", ex: { zh: "哭也没用。", pinyin: "Kū yě méiyòng.", ko: "울어도 소용없다." } },
        { zh: "媒体", pinyin: "méi tǐ", ko: "매체, 언론", pos: "명사", ex: { zh: "这件事被很多媒体报道了。", pinyin: "Zhè jiàn shì bèi hěn duō méitǐ bàodào le.", ko: "이 일은 많은 언론에 보도되었다." } },
        { zh: "美", pinyin: "měi", ko: "아름답다; 미국(약칭)", pos: "형용사", ex: { zh: "这里的风景很美。", pinyin: "Zhèlǐ de fēngjǐng hěn měi.", ko: "이곳의 풍경은 매우 아름답다." } },
        { zh: "美好", pinyin: "měi hǎo", ko: "아름답다, 좋다", pos: "형용사", ex: { zh: "祝你有美好的一天。", pinyin: "Zhù nǐ yǒu měihǎo de yìtiān.", ko: "좋은 하루 보내시길 바랍니다." } },
        { zh: "美食", pinyin: "měi shí", ko: "맛있는 음식, 미식", pos: "명사", ex: { zh: "这座城市有很多美食。", pinyin: "Zhè zuò chéngshì yǒu hěn duō měishí.", ko: "이 도시에는 맛있는 음식이 많다." } },
        { zh: "美元", pinyin: "Měi yuán", ko: "미국 달러", pos: "양사", ex: { zh: "这本书要二十美元。", pinyin: "Zhè běn shū yào èrshí Měiyuán.", ko: "이 책은 20달러이다." } },
        { zh: "迷", pinyin: "mí", ko: "빠지다, 심취하다; 팬", pos: "동사", ex: { zh: "他是一个足球迷。", pinyin: "Tā shì yí gè zúqiú mí.", ko: "그는 축구 팬이다." } },
        { zh: "民间", pinyin: "mín jiān", ko: "민간(의)", pos: "명사", ex: { zh: "这是一个民间故事。", pinyin: "Zhè shì yí gè mínjiān gùshi.", ko: "이것은 민간 이야기(설화)이다." } },
        { zh: "奶茶", pinyin: "nǎi chá", ko: "밀크티", pos: "명사", ex: { zh: "我想喝一杯奶茶。", pinyin: "Wǒ xiǎng hē yì bēi nǎichá.", ko: "나는 밀크티 한 잔을 마시고 싶다." } },
        { zh: "男子", pinyin: "nán zǐ", ko: "남자", pos: "명사", ex: { zh: "那个男子是我哥哥。", pinyin: "Nàge nánzǐ shì wǒ gēge.", ko: "저 남자는 우리 형이다." } },
        { zh: "南部", pinyin: "nán bù", ko: "남부", pos: "명사", ex: { zh: "他住在城市南部。", pinyin: "Tā zhù zài chéngshì nánbù.", ko: "그는 도시 남부에 산다." } },
        { zh: "难度", pinyin: "nán dù", ko: "난이도", pos: "명사", ex: { zh: "这道题的难度很高。", pinyin: "Zhè dào tí de nándù hěn gāo.", ko: "이 문제의 난이도는 매우 높다." } },
        { zh: "内心", pinyin: "nèi xīn", ko: "내심, 마음속", pos: "명사", ex: { zh: "他内心很紧张。", pinyin: "Tā nèixīn hěn jǐnzhāng.", ko: "그는 마음속으로 매우 긴장했다." } },
        { zh: "能不能", pinyin: "néng bùnéng", ko: "~할 수 있나요?", pos: "", ex: { zh: "你能不能帮我一下?", pinyin: "Nǐ néng bù néng bāng wǒ yíxià?", ko: "저 좀 도와줄 수 있어요?" } },
        { zh: "年初", pinyin: "nián chū", ko: "연초", pos: "명사", ex: { zh: "我们年初制定了计划。", pinyin: "Wǒmen niánchū zhìdìngle jìhuà.", ko: "우리는 연초에 계획을 세웠다." } },
        { zh: "年底", pinyin: "nián dǐ", ko: "연말", pos: "명사", ex: { zh: "年底工作特别忙。", pinyin: "Niándǐ gōngzuò tèbié máng.", ko: "연말에는 일이 특히 바쁘다." } },
        { zh: "牛", pinyin: "niú", ko: "소", pos: "명사", ex: { zh: "农民在地里养了几头牛。", pinyin: "Nóngmín zài dì lǐ yǎngle jǐ tóu niú.", ko: "농부는 밭에서 소 몇 마리를 기른다." } },
        { zh: "女子", pinyin: "nǚ zǐ", ko: "여자", pos: "명사", ex: { zh: "那位女子很漂亮。", pinyin: "Nà wèi nǚzǐ hěn piàoliang.", ko: "저 여자분은 매우 예쁘다." } },
        { zh: "排名", pinyin: "pái míng", ko: "순위를 매기다, 순위", pos: "동사", ex: { zh: "他在班里排名第一。", pinyin: "Tā zài bān lǐ páimíng dì yī.", ko: "그는 반에서 1등을 한다." } },
        { zh: "牌子", pinyin: "pái zi", ko: "브랜드, 상표, 팻말", pos: "명사", ex: { zh: "这是一个有名的牌子。", pinyin: "Zhè shì yí gè yǒumíng de páizi.", ko: "이것은 유명한 브랜드이다." } },
        { zh: "配", pinyin: "pèi", ko: "배합하다, 어울리다, 짝짓다", pos: "동사", ex: { zh: "这件衣服配那条裤子很好看。", pinyin: "Zhè jiàn yīfu pèi nà tiáo kùzi hěn hǎokàn.", ko: "이 옷은 그 바지와 아주 잘 어울린다." } },
        { zh: "皮", pinyin: "pí", ko: "가죽, 껍질", pos: "명사", ex: { zh: "苹果皮不用削。", pinyin: "Píngguǒ pí bú yòng xiāo.", ko: "사과 껍질은 깎을 필요 없다." } },
        { zh: "皮包", pinyin: "pí bāo", ko: "가죽 가방, 핸드백", pos: "명사", ex: { zh: "她拿着一个皮包。", pinyin: "Tā názhe yí gè píbāo.", ko: "그녀는 가죽 가방을 들고 있다." } },
        { zh: "票价", pinyin: "piào jià", ko: "표 값, 요금", pos: "명사", ex: { zh: "电影票价涨了。", pinyin: "Diànyǐng piàojià zhǎng le.", ko: "영화표 값이 올랐다." } },
        { zh: "普及", pinyin: "pǔ jí", ko: "보급하다, 널리 퍼지다", pos: "동사", ex: { zh: "智能手机现在已经普及了。", pinyin: "Zhìnéng shǒujī xiànzài yǐjīng pǔjí le.", ko: "스마트폰은 이제 널리 보급되었다." } },
        { zh: "期", pinyin: "qī", ko: "기간, 시기", pos: "", ex: { zh: "这学期的课程很有意思。", pinyin: "Zhè xuéqī de kèchéng hěn yǒu yìsi.", ko: "이번 학기 수업은 매우 재미있다." } },
        { zh: "齐", pinyin: "qí", ko: "가지런하다, 다 모이다; (성씨) 치", pos: "형용사", ex: { zh: "大家到齐了,我们开始开会吧。", pinyin: "Dàjiā dào qí le, wǒmen kāishǐ kāihuì ba.", ko: "다들 모였으니, 회의를 시작합시다." } },
        { zh: "前后", pinyin: "qián hòu", ko: "전후, 앞뒤", pos: "명사", ex: { zh: "春节前后,火车票很难买。", pinyin: "Chūnjié qiánhòu, huǒchēpiào hěn nán mǎi.", ko: "설 전후에는 기차표를 구하기 어렵다." } },
        { zh: "前进", pinyin: "qián jìn", ko: "전진하다, 앞으로 나아가다", pos: "동사", ex: { zh: "士兵们勇敢地向前进。", pinyin: "Shìbīngmen yǒnggǎn de xiàng qián jìn.", ko: "병사들은 용감하게 앞으로 전진했다." } },
        { zh: "前往", pinyin: "qián wǎng", ko: "(~로) 향하다, 가다", pos: "동사", ex: { zh: "代表团即将前往北京。", pinyin: "Dàibiǎotuán jíjiāng qián wǎng Běijīng.", ko: "대표단이 곧 베이징으로 향한다." } },
        { zh: "强", pinyin: "qiáng", ko: "강하다; (성씨) 강", pos: "형용사", ex: { zh: "他的性格很强,从不轻易放弃。", pinyin: "Tā de xìnggé hěn qiáng, cóng bù qīngyì fàngqì.", ko: "그의 성격은 강해서 쉽게 포기하지 않는다." } },
        { zh: "强大", pinyin: "qiáng dà", ko: "강대하다, 막강하다", pos: "형용사", ex: { zh: "这个国家拥有强大的经济实力。", pinyin: "Zhège guójiā yōngyǒu qiángdà de jīngjì shílì.", ko: "이 나라는 강대한 경제력을 가지고 있다." } },
        { zh: "巧", pinyin: "qiǎo", ko: "공교롭다, 마침, 절묘하다", pos: "형용사", ex: { zh: "真巧,我也正要去找你。", pinyin: "Zhēn qiǎo, wǒ yě zhèng yào qù zhǎo nǐ.", ko: "정말 공교롭게도, 나도 마침 너를 찾아가려던 참이었어." } },
        { zh: "亲", pinyin: "qīn", ko: "입맞추다, 친하다", pos: "동사", ex: { zh: "妈妈亲了亲孩子的脸颊。", pinyin: "Māma qīn le qīn háizi de liǎnjiá.", ko: "엄마가 아이의 뺨에 입을 맞췄다." } },
        { zh: "亲人", pinyin: "qīn rén", ko: "가족, 친지", pos: "명사", ex: { zh: "春节的时候,我们都会和亲人团聚。", pinyin: "Chūnjié de shíhou, wǒmen dōu huì hé qīnrén tuánjù.", ko: "설날에는 우리 모두 가족과 함께 모인다." } },
        { zh: "情感", pinyin: "qíng gǎn", ko: "감정, 정서", pos: "명사", ex: { zh: "这首歌表达了作者复杂的情感。", pinyin: "Zhè shǒu gē biǎodá le zuòzhě fùzá de qínggǎn.", ko: "이 노래는 작가의 복잡한 감정을 표현했다." } },
        { zh: "请教", pinyin: "qǐng jiào", ko: "가르침을 청하다, 문의하다", pos: "동사", ex: { zh: "有个问题想请教您一下。", pinyin: "Yǒu ge wèntí xiǎng qǐngjiào nín yíxià.", ko: "여쭤보고 싶은 것이 있습니다." } },
        { zh: "区", pinyin: "qū", ko: "구역, 지역", pos: "명사", ex: { zh: "这个区有很多商店。", pinyin: "Zhège qū yǒu hěn duō shāngdiàn.", ko: "이 구역에는 상점이 많다." } },
        { zh: "全场", pinyin: "quán chǎng", ko: "전체 관중, 전장(全場)", pos: "명사", ex: { zh: "他的精彩表演赢得了全场的掌声。", pinyin: "Tā de jīngcǎi biǎoyǎn yíngdé le quánchǎng de zhǎngshēng.", ko: "그의 멋진 공연은 전체 관중의 박수를 받았다." } },
        { zh: "全球", pinyin: "quán qiú", ko: "전 세계, 글로벌", pos: "명사", ex: { zh: "这家公司在全球拥有上百家分店。", pinyin: "Zhè jiā gōngsī zài quánqiú yōngyǒu shàng bǎi jiā fēndiàn.", ko: "이 회사는 전 세계에 수백 개의 지점을 가지고 있다." } },
        { zh: "缺", pinyin: "quē", ko: "부족하다, 모자라다", pos: "동사", ex: { zh: "我们班还缺一名班长。", pinyin: "Wǒmen bān hái quē yì míng bānzhǎng.", ko: "우리 반은 아직 반장이 한 명 부족하다." } },
        { zh: "确保", pinyin: "què bǎo", ko: "확보하다, 보장하다", pos: "동사", ex: { zh: "我们必须确保产品的质量。", pinyin: "Wǒmen bìxū quèbǎo chǎnpǐn de zhìliàng.", ko: "우리는 반드시 제품의 품질을 보장해야 한다." } },
        { zh: "人工", pinyin: "rén gōng", ko: "인공의, 인력의", pos: "형용사", ex: { zh: "人工智能正在改变我们的生活。", pinyin: "Réngōng zhìnéng zhèngzài gǎibiàn wǒmen de shēnghuó.", ko: "인공지능이 우리의 삶을 바꾸고 있다." } },
        { zh: "人民", pinyin: "rén mín", ko: "인민, 국민", pos: "명사", ex: { zh: "这项政策深受人民的欢迎。", pinyin: "Zhè xiàng zhèngcè shēn shòu rénmín de huānyíng.", ko: "이 정책은 국민들에게 큰 환영을 받았다." } },
        { zh: "人群", pinyin: "rén qún", ko: "군중, 인파", pos: "명사", ex: { zh: "广场上挤满了人群。", pinyin: "Guǎngchǎng shàng jǐ mǎn le rénqún.", ko: "광장에는 사람들이 가득 모여 있었다." } },
        { zh: "认出", pinyin: "rèn chū", ko: "알아보다, 알아차리다", pos: "동사", ex: { zh: "我一眼就认出了他。", pinyin: "Wǒ yì yǎn jiù rèn chū le tā.", ko: "나는 한눈에 그를 알아봤다." } },
        { zh: "认得", pinyin: "rèn de", ko: "알다, 알아보다", pos: "동사", ex: { zh: "你还认得我吗?", pinyin: "Nǐ hái rèn de wǒ ma?", ko: "너 아직 나를 알아보겠니?" } },
        { zh: "认可", pinyin: "rèn kě", ko: "인정하다, 승인하다", pos: "동사", ex: { zh: "他的努力得到了大家的认可。", pinyin: "Tā de nǔlì dédào le dàjiā de rènkě.", ko: "그의 노력은 모두의 인정을 받았다." } },
        { zh: "任", pinyin: "rèn", ko: "맡다, 담당하다; (성씨) 런", pos: "동사", ex: { zh: "他任这个项目的负责人。", pinyin: "Tā rèn zhège xiàngmù de fùzérén.", ko: "그는 이 프로젝트의 책임자를 맡고 있다." } },
        { zh: "仍", pinyin: "réng", ko: "여전히, 아직도", pos: "부사", ex: { zh: "虽然很累,他仍坚持工作。", pinyin: "Suīrán hěn lèi, tā réng jiānchí gōngzuò.", ko: "비록 피곤했지만, 그는 여전히 일을 계속했다." } },
        { zh: "沙子", pinyin: "shā zi", ko: "모래", pos: "명사", ex: { zh: "孩子们在沙滩上玩沙子。", pinyin: "Háizimen zài shātān shàng wán shāzi.", ko: "아이들이 해변에서 모래를 가지고 놀고 있다." } },
        { zh: "伤", pinyin: "shāng", ko: "다치다, 상처(입다)", pos: "동사", ex: { zh: "他在比赛中不小心受了伤。", pinyin: "Tā zài bǐsài zhōng bù xiǎoxīn shòu le shāng.", ko: "그는 경기 중에 실수로 다쳤다." } },
        { zh: "上来", pinyin: "shàng lái", ko: "올라오다", pos: "동사", ex: { zh: "请你上来一下。", pinyin: "Qǐng nǐ shàng lái yíxià.", ko: "잠깐 올라와 주세요." } },
        { zh: "上面", pinyin: "shàng miàn", ko: "위, 위쪽", pos: "명사", ex: { zh: "桌子上面放着一本书。", pinyin: "Zhuōzi shàngmiàn fàng zhe yì běn shū.", ko: "책상 위에 책 한 권이 놓여 있다." } },
        { zh: "上去", pinyin: "shàng qù", ko: "올라가다", pos: "동사", ex: { zh: "电梯坏了,我们只能走上去。", pinyin: "Diàntī huài le, wǒmen zhǐ néng zǒu shàng qù.", ko: "엘리베이터가 고장 나서 우리는 걸어 올라갈 수밖에 없었다." } },
        { zh: "上升", pinyin: "shàng shēng", ko: "상승하다, 오르다", pos: "동사", ex: { zh: "最近气温不断上升。", pinyin: "Zuìjìn qìwēn bùduàn shàngshēng.", ko: "최근 기온이 계속 상승하고 있다." } },
        { zh: "上衣", pinyin: "shàng yī", ko: "상의, 웃옷", pos: "명사", ex: { zh: "她穿了一件红色的上衣。", pinyin: "Tā chuān le yí jiàn hóngsè de shàngyī.", ko: "그녀는 빨간색 상의를 입었다." } },
        { zh: "设立", pinyin: "shè lì", ko: "설립하다, 세우다", pos: "동사", ex: { zh: "学校设立了奖学金制度。", pinyin: "Xuéxiào shèlì le jiǎngxuéjīn zhìdù.", ko: "학교는 장학금 제도를 설립했다." } },
        { zh: "身份证", pinyin: "shēn fèn zhèng", ko: "신분증", pos: "명사", ex: { zh: "请出示您的身份证。", pinyin: "Qǐng chūshì nín de shēnfènzhèng.", ko: "신분증을 보여 주세요." } },
        { zh: "深入", pinyin: "shēn rù", ko: "깊이 파고들다, 심화하다", pos: "동사", ex: { zh: "我们需要深入了解这个问题。", pinyin: "Wǒmen xūyào shēnrù liǎojiě zhège wèntí.", ko: "우리는 이 문제를 깊이 이해할 필요가 있다." } },
        { zh: "生存", pinyin: "shēng cún", ko: "생존하다", pos: "동사", ex: { zh: "动物在恶劣环境中努力生存。", pinyin: "Dòngwù zài èliè huánjìng zhōng nǔlì shēngcún.", ko: "동물들은 열악한 환경 속에서 생존하려고 애쓴다." } },
        { zh: "生意", pinyin: "shēng yì", ko: "생기, 활력", pos: "명사", ex: { zh: "春天来了,树木充满了生意。", pinyin: "Chūntiān lái le, shùmù chōngmǎn le shēngyì.", ko: "봄이 오니, 나무들이 생기로 가득하다." } },
        { zh: "生长", pinyin: "shēng zhǎng", ko: "자라다, 성장하다", pos: "동사", ex: { zh: "这种植物适合在温暖的地方生长。", pinyin: "Zhè zhǒng zhíwù shìhé zài wēnnuǎn de dìfang shēngzhǎng.", ko: "이 식물은 따뜻한 곳에서 자라기에 적합하다." } },
        { zh: "声明", pinyin: "shēng míng", ko: "성명, 선언", pos: "명사", ex: { zh: "政府发表了一份正式声明。", pinyin: "Zhèngfǔ fābiǎo le yí fèn zhèngshì shēngmíng.", ko: "정부는 공식 성명을 발표했다." } },
        { zh: "胜", pinyin: "shèng", ko: "이기다, 승리하다", pos: "동사", ex: { zh: "我们队今天胜了对手。", pinyin: "Wǒmen duì jīntiān shèng le duìshǒu.", ko: "우리 팀은 오늘 상대를 이겼다." } },
        { zh: "石油", pinyin: "shí yóu", ko: "석유", pos: "명사", ex: { zh: "这个国家有丰富的石油资源。", pinyin: "Zhège guójiā yǒu fēngfù de shíyóu zīyuán.", ko: "이 나라는 풍부한 석유 자원을 가지고 있다." } },
        { zh: "时", pinyin: "shí", ko: "때, 시간", pos: "명사", ex: { zh: "到时我会通知你。", pinyin: "Dào shí wǒ huì tōngzhī nǐ.", ko: "때가 되면 내가 알려줄게." } },
        { zh: "实际上", pinyin: "shí jì shàng", ko: "사실은, 실제로", pos: "부사", ex: { zh: "实际上，他并不知道这件事。", pinyin: "Shíjìshàng, tā bìng bù zhīdào zhè jiàn shì.", ko: "사실은 그는 이 일을 전혀 모른다." } },
        { zh: "实力", pinyin: "shí lì", ko: "실력", pos: "명사", ex: { zh: "他的实力很强。", pinyin: "Tā de shílì hěn qiáng.", ko: "그의 실력은 매우 강하다." } },
        { zh: "实验室", pinyin: "shí yàn shì", ko: "실험실", pos: "명사", ex: { zh: "他每天都在实验室工作。", pinyin: "Tā měitiān dōu zài shíyànshì gōngzuò.", ko: "그는 매일 실험실에서 일한다." } },
        { zh: "世界杯", pinyin: "Shì jiè bēi", ko: "월드컵", pos: "명사", ex: { zh: "今年的世界杯非常精彩。", pinyin: "Jīnnián de Shìjièbēi fēicháng jīngcǎi.", ko: "올해 월드컵은 매우 흥미진진했다." } },
        { zh: "事故", pinyin: "shì gù", ko: "사고", pos: "명사", ex: { zh: "路上发生了一起交通事故。", pinyin: "Lùshang fāshēngle yì qǐ jiāotōng shìgù.", ko: "길에서 교통사고가 발생했다." } },
        { zh: "事件", pinyin: "shì jiàn", ko: "사건", pos: "명사", ex: { zh: "这是一起重大事件。", pinyin: "Zhè shì yì qǐ zhòngdà shìjiàn.", ko: "이것은 중대한 사건이다." } },
        { zh: "事实上", pinyin: "shì shí shàng", ko: "사실상, 실제로", pos: "", ex: { zh: "事实上，这个问题很简单。", pinyin: "Shìshíshàng, zhège wèntí hěn jiǎndān.", ko: "사실상 이 문제는 매우 간단하다." } },
        { zh: "事业", pinyin: "shì yè", ko: "사업, 일", pos: "명사", ex: { zh: "他把一生都献给了教育事业。", pinyin: "Tā bǎ yìshēng dōu xiàn gěile jiàoyù shìyè.", ko: "그는 평생을 교육 사업에 바쳤다." } },
        { zh: "试题", pinyin: "shì tí", ko: "시험 문제", pos: "명사", ex: { zh: "这次考试的试题很难。", pinyin: "Zhè cì kǎoshì de shìtí hěn nán.", ko: "이번 시험 문제는 매우 어려웠다." } },
        { zh: "试验", pinyin: "shì yàn", ko: "시험하다, 실험하다", pos: "동사", ex: { zh: "科学家正在做一个新试验。", pinyin: "Kēxuéjiā zhèngzài zuò yí gè xīn shìyàn.", ko: "과학자가 새로운 실험을 하고 있다." } },
        { zh: "室", pinyin: "shì", ko: "방, 실", pos: "명사", ex: { zh: "老师在办公室里。", pinyin: "Lǎoshī zài bàngōngshì lǐ.", ko: "선생님은 사무실에 계신다." } },
        { zh: "适用", pinyin: "shì yòng", ko: "적용되다, 적용하다", pos: "동사", ex: { zh: "这个规定适用于所有员工。", pinyin: "Zhège guīdìng shìyòng yú suǒyǒu yuángōng.", ko: "이 규정은 모든 직원에게 적용된다." } },
        { zh: "收费", pinyin: "shōu fèi", ko: "요금을 받다, 유료이다", pos: "동사", ex: { zh: "这个停车场收费吗？", pinyin: "Zhège tíngchēchǎng shōufèi ma?", ko: "이 주차장은 요금을 받나요?" } },
        { zh: "收看", pinyin: "shōu kàn", ko: "시청하다", pos: "동사", ex: { zh: "很多人喜欢收看这个节目。", pinyin: "Hěn duō rén xǐhuan shōukàn zhège jiémù.", ko: "많은 사람들이 이 프로그램을 시청하는 것을 좋아한다." } },
        { zh: "收听", pinyin: "shōu tīng", ko: "청취하다, 듣다", pos: "동사", ex: { zh: "我每天早上收听新闻广播。", pinyin: "Wǒ měitiān zǎoshang shōutīng xīnwén guǎngbō.", ko: "나는 매일 아침 뉴스 방송을 듣는다." } },
        { zh: "收音机", pinyin: "shōu yīn jī", ko: "라디오", pos: "명사", ex: { zh: "爷爷喜欢听收音机。", pinyin: "Yéye xǐhuan tīng shōuyīnjī.", ko: "할아버지는 라디오 듣는 것을 좋아하신다." } },
        { zh: "受", pinyin: "shòu", ko: "받다, 당하다", pos: "동사", ex: { zh: "他在比赛中受了伤。", pinyin: "Tā zài bǐsài zhōng shòule shāng.", ko: "그는 경기 중에 부상을 당했다." } },
        { zh: "熟人", pinyin: "shú rén", ko: "아는 사람, 지인", pos: "명사", ex: { zh: "在这个城市，我有很多熟人。", pinyin: "Zài zhège chéngshì, wǒ yǒu hěn duō shúrén.", ko: "이 도시에서 나는 아는 사람이 많다." } },
        { zh: "属", pinyin: "shǔ", ko: "속하다, ~띠이다", pos: "동사", ex: { zh: "我属狗，今年三十岁。", pinyin: "Wǒ shǔ gǒu, jīnnián sānshí suì.", ko: "나는 개띠이고, 올해 서른 살이다." } },
        { zh: "束", pinyin: "shù", ko: "다발, 묶음", pos: "양사", ex: { zh: "她买了一束花。", pinyin: "Tā mǎile yí shù huā.", ko: "그녀는 꽃 한 다발을 샀다." } },
        { zh: "随", pinyin: "suí", ko: "~에 따라, ~를 따라", pos: "전치사", ex: { zh: "随着天气变冷，穿的衣服也多了。", pinyin: "Suízhe tiānqì biàn lěng, chuān de yīfu yě duō le.", ko: "날씨가 추워짐에 따라 입는 옷도 많아졌다." } },
        { zh: "所长", pinyin: "suǒ cháng", ko: "장점, 특기", pos: "명사", ex: { zh: "每个人都有自己的所长。", pinyin: "Měi gè rén dōu yǒu zìjǐ de suǒcháng.", ko: "사람마다 자신만의 장점이 있다." } },
        { zh: "谈话", pinyin: "tán huà", ko: "대화하다, 이야기하다", pos: "동사", ex: { zh: "老师找他谈话了。", pinyin: "Lǎoshī zhǎo tā tánhuà le.", ko: "선생님이 그를 불러 이야기했다." } },
        { zh: "特色", pinyin: "tè sè", ko: "특색, 특징", pos: "명사", ex: { zh: "这家餐厅很有特色。", pinyin: "Zhè jiā cāntīng hěn yǒu tèsè.", ko: "이 식당은 매우 특색이 있다." } },
        { zh: "跳", pinyin: "tiào", ko: "뛰다, 점프하다", pos: "동사", ex: { zh: "孩子们在草地上跳来跳去。", pinyin: "Háizimen zài cǎodì shàng tiào lái tiào qù.", ko: "아이들이 잔디밭에서 이리저리 뛰어다닌다." } },
        { zh: "跳高", pinyin: "tiào gāo", ko: "높이뛰기", pos: "동사", ex: { zh: "他擅长跳高。", pinyin: "Tā shàncháng tiàogāo.", ko: "그는 높이뛰기를 잘한다." } },
        { zh: "跳远", pinyin: "tiào yuǎn", ko: "멀리뛰기", pos: "동사", ex: { zh: "她在跳远比赛中得了第一名。", pinyin: "Tā zài tiàoyuǎn bǐsài zhōng déle dì yī míng.", ko: "그녀는 멀리뛰기 시합에서 1등을 했다." } },
        { zh: "铁", pinyin: "tiě", ko: "철, 쇠", pos: "명사", ex: { zh: "这把刀是用铁做的。", pinyin: "Zhè bǎ dāo shì yòng tiě zuò de.", ko: "이 칼은 철로 만든 것이다." } },
        { zh: "铁路", pinyin: "tiě lù", ko: "철도", pos: "명사", ex: { zh: "这条铁路连接两座城市。", pinyin: "Zhè tiáo tiělù liánjiē liǎng zuò chéngshì.", ko: "이 철도는 두 도시를 연결한다." } },
        { zh: "听力", pinyin: "tīng lì", ko: "청력, 듣기 능력", pos: "명사", ex: { zh: "他的听力很好。", pinyin: "Tā de tīnglì hěn hǎo.", ko: "그는 청력이 매우 좋다." } },
        { zh: "听众", pinyin: "tīng zhòng", ko: "청중, 청취자", pos: "명사", ex: { zh: "台下的听众都很安静。", pinyin: "Tái xià de tīngzhòng dōu hěn ānjìng.", ko: "무대 아래의 청중은 모두 조용했다." } },
        { zh: "通信", pinyin: "tōng xìn", ko: "통신하다, 서신을 주고받다", pos: "동사", ex: { zh: "他们一直保持通信。", pinyin: "Tāmen yìzhí bǎochí tōngxìn.", ko: "그들은 계속 서신을 주고받고 있다." } },
        { zh: "痛", pinyin: "tòng", ko: "아프다", pos: "형용사", ex: { zh: "我的头很痛。", pinyin: "Wǒ de tóu hěn tòng.", ko: "나는 머리가 많이 아프다." } },
        { zh: "头脑", pinyin: "tóu nǎo", ko: "두뇌, 머리", pos: "명사", ex: { zh: "他头脑很聪明。", pinyin: "Tā tóunǎo hěn cōngming.", ko: "그는 머리가 매우 똑똑하다." } },
        { zh: "图", pinyin: "tú", ko: "그림, 도표", pos: "명사", ex: { zh: "这张图画得很漂亮。", pinyin: "Zhè zhāng tú huà de hěn piàoliang.", ko: "이 그림은 아주 예쁘게 그려졌다." } },
        { zh: "图画", pinyin: "tú huà", ko: "그림", pos: "명사", ex: { zh: "墙上挂着一幅图画。", pinyin: "Qiáng shàng guàzhe yì fú túhuà.", ko: "벽에 그림 한 폭이 걸려 있다." } },
        { zh: "土", pinyin: "tǔ", ko: "흙, 토양", pos: "명사", ex: { zh: "这里的土很肥沃。", pinyin: "Zhèlǐ de tǔ hěn féiwò.", ko: "이곳의 흙은 매우 비옥하다." } },
        { zh: "团结", pinyin: "tuán jié", ko: "단결하다, 단결", pos: "동사", ex: { zh: "大家要团结起来。", pinyin: "dà jiā yào tuán jié qǐ lái。", ko: "모두가 단결해야 한다." } },
        { zh: "团体", pinyin: "tuán tǐ", ko: "단체", pos: "명사", ex: { zh: "这是一个公益团体。", pinyin: "zhè shì yí gè gōng yì tuán tǐ。", ko: "이것은 공익 단체이다." } },
        { zh: "推进", pinyin: "tuī jìn", ko: "추진하다", pos: "동사", ex: { zh: "政府正在推进这项改革。", pinyin: "zhèng fǔ zhèng zài tuī jìn zhè xiàng gǎi gé。", ko: "정부는 이 개혁을 추진하고 있다." } },
        { zh: "推开", pinyin: "tuī kāi", ko: "밀어서 열다, 밀치다", pos: "동사", ex: { zh: "他用力推开了门。", pinyin: "tā yòng lì tuī kāi le mén。", ko: "그는 힘껏 문을 밀어서 열었다." } },
        { zh: "退出", pinyin: "tuì chū", ko: "탈퇴하다, 물러나다", pos: "동사", ex: { zh: "他决定退出比赛。", pinyin: "tā jué dìng tuì chū bǐ sài。", ko: "그는 경기에서 물러나기로 결정했다." } },
        { zh: "外面", pinyin: "wài miàn", ko: "밖, 바깥", pos: "명사", ex: { zh: "外面很冷，多穿点儿衣服。", pinyin: "wài miàn hěn lěng, duō chuān diǎnr yī fu。", ko: "밖이 추우니 옷을 좀 더 입어라." } },
        { zh: "外文", pinyin: "wài wén", ko: "외국어(문자)", pos: "명사", ex: { zh: "这本书是外文原版。", pinyin: "zhè běn shū shì wài wén yuán bǎn。", ko: "이 책은 외국어 원서이다." } },
        { zh: "围", pinyin: "wéi", ko: "둘러싸다(성씨: 웨이)", pos: "동사", ex: { zh: "孩子们把老师围了起来。", pinyin: "hái zi men bǎ lǎo shī wéi le qǐ lái。", ko: "아이들이 선생님을 둘러쌌다." } },
        { zh: "卫生", pinyin: "wèi shēng", ko: "위생", pos: "형용사", ex: { zh: "请注意个人卫生。", pinyin: "qǐng zhù yì gè rén wèi shēng。", ko: "개인 위생에 주의해 주세요." } },
        { zh: "文字", pinyin: "wén zì", ko: "문자, 글자", pos: "명사", ex: { zh: "汉字是一种古老的文字。", pinyin: "hàn zì shì yì zhǒng gǔ lǎo de wén zì。", ko: "한자는 오래된 문자이다." } },
        { zh: "舞台", pinyin: "wǔ tái", ko: "무대", pos: "명사", ex: { zh: "她第一次站在舞台上。", pinyin: "tā dì yī cì zhàn zài wǔ tái shàng。", ko: "그녀는 처음으로 무대 위에 섰다." } },
        { zh: "西部", pinyin: "xī bù", ko: "서부", pos: "명사", ex: { zh: "他在中国西部工作。", pinyin: "tā zài zhōng guó xī bù gōng zuò。", ko: "그는 중국 서부에서 일한다." } },
        { zh: "下来", pinyin: "xià lai", ko: "내려오다", pos: "동사", ex: { zh: "请你从楼上下来。", pinyin: "qǐng nǐ cóng lóu shàng xià lai。", ko: "위층에서 내려와 주세요." } },
        { zh: "下面", pinyin: "xià miàn", ko: "아래, 다음", pos: "명사", ex: { zh: "请看下面的例子。", pinyin: "qǐng kàn xià miàn de lì zi。", ko: "아래 예시를 보세요." } },
        { zh: "下去", pinyin: "xià qù", ko: "내려가다, 계속하다", pos: "동사", ex: { zh: "请继续说下去。", pinyin: "qǐng jì xù shuō xià qù。", ko: "계속 말해 주세요." } },
        { zh: "先进", pinyin: "xiān jìn", ko: "선진의, 앞선", pos: "형용사", ex: { zh: "这是一项先进技术。", pinyin: "zhè shì yí xiàng xiān jìn jì shù。", ko: "이것은 선진 기술이다." } },
        { zh: "现场", pinyin: "xiàn chǎng", ko: "현장", pos: "", ex: { zh: "警察赶到了事故现场。", pinyin: "jǐng chá gǎn dào le shì gù xiàn chǎng。", ko: "경찰이 사고 현장에 도착했다." } },
        { zh: "现代化", pinyin: "xiàn dài huà", ko: "현대화", pos: "동사", ex: { zh: "国家正在推进农业现代化。", pinyin: "guó jiā zhèng zài tuī jìn nóng yè xiàn dài huà。", ko: "국가는 농업 현대화를 추진하고 있다." } },
        { zh: "线", pinyin: "xiàn", ko: "실, 선", pos: "명사", ex: { zh: "这条线太长了。", pinyin: "zhè tiáo xiàn tài cháng le。", ko: "이 선은 너무 길다." } },
        { zh: "相比", pinyin: "xiāng bǐ", ko: "비교하다", pos: "동사", ex: { zh: "跟以前相比，情况好多了。", pinyin: "gēn yǐ qián xiāng bǐ, qíng kuàng hǎo duō le。", ko: "예전과 비교하면 상황이 많이 좋아졌다." } },
        { zh: "相互", pinyin: "xiāng hù", ko: "서로, 상호", pos: "부사", ex: { zh: "我们要相互帮助。", pinyin: "wǒ men yào xiāng hù bāng zhù。", ko: "우리는 서로 도와야 한다." } },
        { zh: "写作", pinyin: "xiě zuò", ko: "글쓰기, 창작하다", pos: "동사", ex: { zh: "她喜欢写作。", pinyin: "tā xǐ huan xiě zuò。", ko: "그녀는 글쓰기를 좋아한다." } },
        { zh: "心", pinyin: "xīn", ko: "마음, 심장", pos: "명사", ex: { zh: "他心里很难过。", pinyin: "tā xīn lǐ hěn nán guò。", ko: "그는 마음속으로 매우 슬프다." } },
        { zh: "性", pinyin: "xìng", ko: "성질, 성", pos: "명사", ex: { zh: "这种药有一定的危险性。", pinyin: "zhè zhǒng yào yǒu yí dìng de wēi xiǎn xìng。", ko: "이 약은 어느 정도 위험성이 있다." } },
        { zh: "需求", pinyin: "xū qiú", ko: "수요, 요구", pos: "명사", ex: { zh: "市场需求越来越大。", pinyin: "shì chǎng xū qiú yuè lái yuè dà。", ko: "시장 수요가 점점 커지고 있다." } },
        { zh: "选手", pinyin: "xuǎn shǒu", ko: "선수", pos: "명사", ex: { zh: "这位选手获得了金牌。", pinyin: "zhè wèi xuǎn shǒu huò dé le jīn pái。", ko: "이 선수는 금메달을 획득했다." } },
        { zh: "学费", pinyin: "xué fèi", ko: "학비", pos: "명사", ex: { zh: "大学学费越来越高。", pinyin: "dà xué xué fèi yuè lái yuè gāo。", ko: "대학 학비가 점점 비싸지고 있다." } },
        { zh: "压", pinyin: "yā", ko: "누르다, 압박하다", pos: "동사", ex: { zh: "别把箱子压坏了。", pinyin: "bié bǎ xiāng zi yā huài le。", ko: "상자를 눌러서 망가뜨리지 마라." } },
        { zh: "烟", pinyin: "yān", ko: "담배, 연기", pos: "명사", ex: { zh: "他戒烟了。", pinyin: "tā jiè yān le。", ko: "그는 담배를 끊었다." } },
        { zh: "眼前", pinyin: "yǎn qián", ko: "눈앞, 현재", pos: "명사", ex: { zh: "眼前的困难只是暂时的。", pinyin: "yǎn qián de kùn nan zhǐ shì zàn shí de。", ko: "눈앞의 어려움은 일시적인 것일 뿐이다." } },
        { zh: "演", pinyin: "yǎn", ko: "연기하다, 공연하다", pos: "동사", ex: { zh: "他演得非常好。", pinyin: "tā yǎn de fēi cháng hǎo。", ko: "그는 연기를 매우 잘한다." } },
        { zh: "演唱", pinyin: "yǎn chàng", ko: "노래를 부르다, 가창", pos: "동사", ex: { zh: "她在台上演唱了三首歌。", pinyin: "tā zài tái shàng yǎn chàng le sān shǒu gē。", ko: "그녀는 무대에서 노래 세 곡을 불렀다." } },
        { zh: "演唱会", pinyin: "yǎn chàng huì", ko: "콘서트", pos: "명사", ex: { zh: "我买了演唱会的门票。", pinyin: "wǒ mǎi le yǎn chàng huì de mén piào。", ko: "나는 콘서트 티켓을 샀다." } },
        { zh: "羊", pinyin: "yáng", ko: "양(성씨/동물)", pos: "명사", ex: { zh: "草原上有很多羊。", pinyin: "cǎo yuán shàng yǒu hěn duō yáng。", ko: "초원에는 양이 많이 있다." } },
        { zh: "一方面", pinyin: "yī fāng miàn", ko: "한편으로는", pos: "접속사", ex: { zh: "一方面要努力工作，一方面要照顾家庭。", pinyin: "yī fāng miàn yào nǔ lì gōng zuò, yī fāng miàn yào zhào gù jiā tíng。", ko: "한편으로는 열심히 일해야 하고, 한편으로는 가정을 돌봐야 한다." } },
        { zh: "衣架", pinyin: "yī jià", ko: "옷걸이", pos: "명사", ex: { zh: "把衣服挂在衣架上。", pinyin: "bǎ yī fu guà zài yī jià shàng。", ko: "옷을 옷걸이에 걸어라." } },
        { zh: "已", pinyin: "yǐ", ko: "이미, 벌써", pos: "부사", ex: { zh: "时间已不早了。", pinyin: "shí jiān yǐ bù zǎo le。", ko: "시간이 이미 늦었다." } },
        { zh: "银牌", pinyin: "yín pái", ko: "은메달", pos: "명사", ex: { zh: "他获得了银牌。", pinyin: "tā huò dé le yín pái。", ko: "그는 은메달을 획득했다." } },
        { zh: "应当", pinyin: "yīng dāng", ko: "마땅히 ~해야 한다", pos: "동사", ex: { zh: "我们应当尊重老师。", pinyin: "wǒ men yīng dāng zūn zhòng lǎo shī。", ko: "우리는 마땅히 선생님을 존중해야 한다." } },
        { zh: "影视", pinyin: "yǐng shì", ko: "영화와 텔레비전, 영상", pos: "형용사", ex: { zh: "他从事影视行业。", pinyin: "tā cóng shì yǐng shì háng yè。", ko: "그는 영상 업계에 종사한다." } },
        { zh: "邮件", pinyin: "yóu jiàn", ko: "우편물, 이메일", pos: "명사", ex: { zh: "我每天检查电子邮件。", pinyin: "Wǒ měi tiān jiǎn chá diàn zǐ yóu jiàn.", ko: "나는 매일 이메일을 확인한다." } },
        { zh: "邮票", pinyin: "yóu piào", ko: "우표", pos: "명사", ex: { zh: "他喜欢收集邮票。", pinyin: "Tā xǐ huan shōu jí yóu piào.", ko: "그는 우표 수집을 좋아한다." } },
        { zh: "邮箱", pinyin: "yóu xiāng", ko: "우편함, 이메일 주소", pos: "명사", ex: { zh: "请把文件发到我的邮箱。", pinyin: "Qǐng bǎ wén jiàn fā dào wǒ de yóu xiāng.", ko: "파일을 제 이메일로 보내 주세요." } },
        { zh: "游", pinyin: "yóu", ko: "헤엄치다; 성씨 유", pos: "동사", ex: { zh: "他每天去游泳池游泳。", pinyin: "Tā měi tiān qù yóu yǒng chí yóu yǒng.", ko: "그는 매일 수영장에 가서 수영한다." } },
        { zh: "有的是", pinyin: "yǒu de shì", ko: "얼마든지 있다", pos: "", ex: { zh: "这里有的是时间,别着急。", pinyin: "Zhè lǐ yǒu de shì shí jiān, bié zháo jí.", ko: "여기 시간은 얼마든지 있으니 서두르지 마세요." } },
        { zh: "有效", pinyin: "yǒu xiào", ko: "유효하다, 효과적이다", pos: "형용사", ex: { zh: "这个方法很有效。", pinyin: "Zhè ge fāng fǎ hěn yǒu xiào.", ko: "이 방법은 매우 효과적이다." } },
        { zh: "预计", pinyin: "yù jì", ko: "예측하다, 예상하다", pos: "동사", ex: { zh: "预计明天会下雨。", pinyin: "Yù jì míng tiān huì xià yǔ.", ko: "내일 비가 올 것으로 예상된다." } },
        { zh: "员", pinyin: "yuán", ko: "사람, 인원, 구성원", pos: "양사", ex: { zh: "公司新来了一名职员。", pinyin: "Gōng sī xīn lái le yì míng zhí yuán.", ko: "회사에 직원이 새로 왔다." } },
        { zh: "员工", pinyin: "yuán gōng", ko: "직원, 종업원", pos: "명사", ex: { zh: "公司有一百多名员工。", pinyin: "Gōng sī yǒu yì bǎi duō míng yuán gōng.", ko: "회사에는 100명이 넘는 직원이 있다." } },
        { zh: "约", pinyin: "yuē", ko: "약속하다; 대략", pos: "동사", ex: { zh: "我和朋友约好明天见面。", pinyin: "Wǒ hé péngyou yuē hǎo míngtiān jiànmiàn.", ko: "나는 친구와 내일 만나기로 약속했다." } },
        { zh: "早已", pinyin: "zǎo yǐ", ko: "이미, 벌써", pos: "부사", ex: { zh: "他早已离开了这座城市。", pinyin: "Tā zǎo yǐ lí kāi le zhè zuò chéng shì.", ko: "그는 이미 이 도시를 떠났다." } },
        { zh: "造", pinyin: "zào", ko: "만들다, 짓다", pos: "동사", ex: { zh: "这座桥是去年造的。", pinyin: "Zhè zuò qiáo shì qù nián zào de.", ko: "이 다리는 작년에 지어진 것이다." } },
        { zh: "长处", pinyin: "cháng chù", ko: "장점", pos: "명사", ex: { zh: "每个人都有自己的长处。", pinyin: "Měi gè rén dōu yǒu zì jǐ de cháng chù.", ko: "사람마다 자신만의 장점이 있다." } },
        { zh: "长期", pinyin: "cháng qī", ko: "장기의, 장기간의", pos: "형용사", ex: { zh: "这是一个长期计划。", pinyin: "Zhè shì yí gè cháng qī jì huà.", ko: "이것은 장기 계획이다." } },
        { zh: "照", pinyin: "zhào", ko: "비추다; ~에 따라", pos: "동사", ex: { zh: "阳光照在窗户上。", pinyin: "Yáng guāng zhào zài chuāng hu shàng.", ko: "햇빛이 창문을 비춘다." } },
        { zh: "者", pinyin: "zhě", ko: "~하는 사람, ~자", pos: "대명사", ex: { zh: "他是这个领域的开拓者。", pinyin: "Tā shì zhè ge lǐng yù de kāi tuò zhě.", ko: "그는 이 분야의 개척자이다." } },
        { zh: "争", pinyin: "zhēng", ko: "다투다, 쟁취하다", pos: "동사", ex: { zh: "他们在争一个名额。", pinyin: "Tā men zài zhēng yí gè míng é.", ko: "그들은 한 자리를 두고 경쟁하고 있다." } },
        { zh: "整", pinyin: "zhěng", ko: "온전한, 딱, 정확히", pos: "수사", ex: { zh: "现在整八点。", pinyin: "Xiàn zài zhěng bā diǎn.", ko: "지금 정확히 8시이다." } },
        { zh: "整天", pinyin: "zhěng tiān", ko: "하루 종일", pos: "부사", ex: { zh: "他整天在家看书。", pinyin: "Tā zhěng tiān zài jiā kàn shū.", ko: "그는 하루 종일 집에서 책을 본다." } },
        { zh: "整整", pinyin: "zhěng zhěng", ko: "꼬박, 꽉 채운", pos: "부사", ex: { zh: "他整整等了三个小时。", pinyin: "Tā zhěng zhěng děng le sān gè xiǎo shí.", ko: "그는 꼬박 세 시간을 기다렸다." } },
        { zh: "证", pinyin: "zhèng", ko: "증명서, 증거", pos: "명사", ex: { zh: "请出示您的身份证。", pinyin: "Qǐng chū shì nín de shēn fèn zhèng.", ko: "신분증을 제시해 주세요." } },
        { zh: "支付", pinyin: "zhī fù", ko: "지불하다", pos: "동사", ex: { zh: "你可以用手机支付。", pinyin: "Nǐ kě yǐ yòng shǒu jī zhī fù.", ko: "휴대폰으로 지불할 수 있다." } },
        { zh: "直播", pinyin: "zhí bō", ko: "생중계하다, 라이브 방송하다", pos: "동사", ex: { zh: "今晚有足球比赛直播。", pinyin: "Jīn wǎn yǒu zú qiú bǐ sài zhí bō.", ko: "오늘 밤 축구 경기 생중계가 있다." } },
        { zh: "直到", pinyin: "zhí dào", ko: "~까지", pos: "동사", ex: { zh: "他工作直到深夜。", pinyin: "Tā gōng zuò zhí dào shēn yè.", ko: "그는 밤늦게까지 일한다." } },
        { zh: "值", pinyin: "zhí", ko: "가치가 있다, ~할 만하다", pos: "동사", ex: { zh: "这本书很值得一读。", pinyin: "Zhè běn shū hěn zhí dé yì dú.", ko: "이 책은 읽을 만한 가치가 있다." } },
        { zh: "职工", pinyin: "zhí gōng", ko: "직원, 근로자", pos: "명사", ex: { zh: "工厂里有很多职工。", pinyin: "Gōng chǎng lǐ yǒu hěn duō zhí gōng.", ko: "공장에는 많은 직원이 있다." } },
        { zh: "只是", pinyin: "zhǐ shì", ko: "그저, 단지, 다만", pos: "부사", ex: { zh: "我只是随便说说。", pinyin: "Wǒ zhǐ shì suí biàn shuō shuo.", ko: "나는 그냥 아무렇게나 말한 것뿐이다." } },
        { zh: "只有", pinyin: "zhǐ yǒu", ko: "오직 ~해야만", pos: "접속사", ex: { zh: "只有努力才能成功。", pinyin: "Zhǐ yǒu nǔ lì cái néng chéng gōng.", ko: "노력해야만 성공할 수 있다." } },
        { zh: "指出", pinyin: "zhǐ chū", ko: "지적하다, 밝히다", pos: "동사", ex: { zh: "老师指出了我的错误。", pinyin: "Lǎo shī zhǐ chū le wǒ de cuò wù.", ko: "선생님은 내 잘못을 지적하셨다." } },
        { zh: "志愿", pinyin: "zhì yuàn", ko: "지원, 자원(하다)", pos: "명사", ex: { zh: "他志愿参加了这次活动。", pinyin: "Tā zhì yuàn cān jiā le zhè cì huó dòng.", ko: "그는 이번 활동에 자원해서 참가했다." } },
        { zh: "志愿者", pinyin: "zhì yuàn zhě", ko: "자원봉사자", pos: "명사", ex: { zh: "很多志愿者来帮助灾民。", pinyin: "Hěn duō zhì yuàn zhě lái bāng zhù zāi mín.", ko: "많은 자원봉사자들이 이재민을 도우러 왔다." } },
        { zh: "中部", pinyin: "zhōng bù", ko: "중부", pos: "명사", ex: { zh: "这条河流经中国中部。", pinyin: "Zhè tiáo hé liú jīng Zhōng guó zhōng bù.", ko: "이 강은 중국 중부를 지난다." } },
        { zh: "中华民族", pinyin: "Zhōng huá mín zú", ko: "중화민족", pos: "", ex: { zh: "中华民族有着悠久的历史。", pinyin: "Zhōng huá mín zú yǒu zhe yōu jiǔ de lì shǐ.", ko: "중화민족은 유구한 역사를 가지고 있다." } },
        { zh: "种子", pinyin: "zhǒng zi", ko: "씨앗", pos: "명사", ex: { zh: "农民在地里播种子。", pinyin: "Nóng mín zài dì lǐ bō zhǒng zi.", ko: "농부가 밭에 씨앗을 뿌린다." } },
        { zh: "重大", pinyin: "zhòng dà", ko: "중대하다", pos: "형용사", ex: { zh: "这是一个重大决定。", pinyin: "Zhè shì yí gè zhòng dà jué dìng.", ko: "이것은 중대한 결정이다." } },
        { zh: "主任", pinyin: "zhǔ rèn", ko: "주임, 책임자", pos: "명사", ex: { zh: "他是我们部门的主任。", pinyin: "Tā shì wǒ men bù mén de zhǔ rèn.", ko: "그는 우리 부서의 주임이다." } },
        { zh: "抓", pinyin: "zhuā", ko: "잡다, 붙잡다", pos: "동사", ex: { zh: "猫抓住了老鼠。", pinyin: "Māo zhuā zhù le lǎo shǔ.", ko: "고양이가 쥐를 잡았다." } },
        { zh: "抓住", pinyin: "zhuā zhù", ko: "붙잡다, 움켜쥐다", pos: "동사", ex: { zh: "他抓住了最后的机会。", pinyin: "Tā zhuā zhù le zuì hòu de jī huì.", ko: "그는 마지막 기회를 붙잡았다." } },
        { zh: "专题", pinyin: "zhuān tí", ko: "전문 주제, 특집", pos: "명사", ex: { zh: "这期杂志有个专题报道。", pinyin: "Zhè qī zá zhì yǒu ge zhuān tí bào dào.", ko: "이번 호 잡지에는 특집 기사가 있다." } },
        { zh: "转", pinyin: "zhuǎn", ko: "돌다, 회전하다", pos: "동사", ex: { zh: "请向右转。", pinyin: "Qǐng xiàng yòu zhuǎn.", ko: "오른쪽으로 도세요." } },
        { zh: "追", pinyin: "zhuī", ko: "쫓다, 추격하다", pos: "동사", ex: { zh: "警察在追那个小偷。", pinyin: "Jǐngchá zài zhuī nàge xiǎotōu.", ko: "경찰이 그 도둑을 쫓고 있다." } },
        { zh: "准", pinyin: "zhǔn", ko: "허락하다, 정확하다, 확실히", pos: "형용사", ex: { zh: "请准我一天假。", pinyin: "Qǐng zhǔn wǒ yī tiān jià.", ko: "하루 휴가를 허락해 주세요." } },
        { zh: "自身", pinyin: "zì shēn", ko: "자신, 스스로", pos: "대명사", ex: { zh: "你要相信自身的能力。", pinyin: "Nǐ yào xiāngxìn zìshēn de nénglì.", ko: "너는 스스로의 능력을 믿어야 한다." } },
        { zh: "自主", pinyin: "zì zhǔ", ko: "자주적이다, 스스로 결정하다", pos: "동사", ex: { zh: "学生应该学会自主学习。", pinyin: "Xuésheng yīnggāi xuéhuì zìzhǔ xuéxí.", ko: "학생은 자주적으로 학습하는 법을 배워야 한다." } },
        { zh: "子女", pinyin: "zǐ nǚ", ko: "자녀", pos: "명사", ex: { zh: "他有两个子女。", pinyin: "Tā yǒu liǎng gè zǐnǚ.", ko: "그는 자녀가 둘 있다." } },
        { zh: "总", pinyin: "zǒng", ko: "항상, 늘, 전체적으로", pos: "부사", ex: { zh: "他总是迟到。", pinyin: "Tā zǒngshì chídào.", ko: "그는 항상 지각한다." } },
        { zh: "足够", pinyin: "zú gòu", ko: "충분하다", pos: "동사", ex: { zh: "这些钱足够我们用一个月。", pinyin: "Zhèxiē qián zúgòu wǒmen yòng yī gè yuè.", ko: "이 돈은 우리가 한 달 동안 쓰기에 충분하다." } },
        { zh: "足球", pinyin: "zú qiú", ko: "축구", pos: "명사", ex: { zh: "他每天下午踢足球。", pinyin: "Tā měitiān xiàwǔ tī zúqiú.", ko: "그는 매일 오후 축구를 한다." } },
        { zh: "左右", pinyin: "zuǒ yòu", ko: "좌우, 대략, 쯤", pos: "수사", ex: { zh: "他大概三十岁左右。", pinyin: "Tā dàgài sānshí suì zuǒyòu.", ko: "그는 대략 서른 살쯤 된다." } },
        { zh: "做客", pinyin: "zuò kè", ko: "손님으로 방문하다, 놀러 가다", pos: "동사", ex: { zh: "周末我去朋友家做客。", pinyin: "Zhōumò wǒ qù péngyou jiā zuòkè.", ko: "주말에 나는 친구 집에 손님으로 갔다." } },
      ],
    },
  ],
}

export default themes;
