/**
 * 4급 어휘 — 의견·감정·사회로 넓어지는 단계
 * 일상 생존을 넘어 "생각과 상황을 설명하는" HSK4급 핵심어.
 */
const themes = {
  level: "H4",
  title: "H4 어휘",
  desc: "감정·성격·사회·직장까지 — 한자음으로 단숨에 외우는 HSK4급 핵심 어휘예요.",
  themes: [
    {
      name: "감정과 심리",
      words: [
        {
          zh: "感动",
          pinyin: "gǎndòng",
          ko: "감동하다, 감동시키다",
          pos: "동사",
          hanja: "감동(感動) — 한자 그대로예요.",
          ex: { zh: "这个故事让我很感动。", pinyin: "zhège gùshi ràng wǒ hěn gǎndòng", ko: "이 이야기는 저를 무척 감동시켰어요." },
        },
        {
          zh: "激动",
          pinyin: "jīdòng",
          ko: "흥분하다, 감격하다",
          pos: "동사",
          hanja: "격동(激動) — '격하게 움직이다'. 한국어 '격동'보다 '벅차오르다'에 가까워요.",
          ex: { zh: "听到这个消息，他非常激动。", pinyin: "tīngdào zhège xiāoxi, tā fēicháng jīdòng", ko: "그 소식을 듣고 그는 무척 감격했어요." },
        },
        {
          zh: "失望",
          pinyin: "shīwàng",
          ko: "실망하다",
          pos: "동사",
          hanja: "실망(失望) — '바람을 잃다'. 한자 그대로예요.",
          ex: { zh: "对不起，让你失望了。", pinyin: "duìbuqǐ, ràng nǐ shīwàng le", ko: "미안해요, 실망시켰네요." },
        },
        {
          zh: "羡慕",
          pinyin: "xiànmù",
          ko: "부러워하다",
          pos: "동사",
          hanja: "선모(羨慕) — 한국어엔 잘 안 쓰는 한자어지만 '羨(부러워할 선)'으로 기억해요.",
          ex: { zh: "我很羡慕你的生活。", pinyin: "wǒ hěn xiànmù nǐ de shēnghuó", ko: "저는 당신의 삶이 부러워요." },
        },
        {
          zh: "后悔",
          pinyin: "hòuhuǐ",
          ko: "후회하다",
          pos: "동사",
          hanja: "후회(後悔) — 한자 그대로예요.",
          ex: { zh: "我后悔没有早点儿告诉你。", pinyin: "wǒ hòuhuǐ méiyǒu zǎodiǎnr gàosu nǐ", ko: "더 일찍 말해주지 못한 게 후회돼요." },
        },
        {
          zh: "讨厌",
          pinyin: "tǎoyàn",
          ko: "싫어하다, 얄밉다",
          pos: "동사",
          ex: { zh: "我最讨厌排队。", pinyin: "wǒ zuì tǎoyàn páiduì", ko: "저는 줄 서는 게 제일 싫어요." },
        },
        {
          zh: "着急",
          pinyin: "zháojí",
          ko: "초조해하다, 조급하다",
          pos: "동사",
          hanja: "착급(著急) — '급함이 붙다'. 마음이 급한 상태예요.",
          ex: { zh: "别着急，时间还早。", pinyin: "bié zháojí, shíjiān hái zǎo", ko: "조급해하지 마세요, 아직 시간이 일러요." },
        },
        {
          zh: "紧张",
          pinyin: "jǐnzhāng",
          ko: "긴장되다, 긴박하다",
          pos: "형용사",
          hanja: "긴장(緊張) — 한자 그대로예요.",
          ex: { zh: "考试前我有点儿紧张。", pinyin: "kǎoshì qián wǒ yǒudiǎnr jǐnzhāng", ko: "시험 전에 저는 조금 긴장돼요." },
        },
        {
          zh: "幸福",
          pinyin: "xìngfú",
          ko: "행복하다, 행복",
          pos: "형용사",
          hanja: "행복(幸福) — 한자 그대로예요.",
          ex: { zh: "有家人在身边，我觉得很幸福。", pinyin: "yǒu jiārén zài shēnbiān, wǒ juéde hěn xìngfú", ko: "가족이 곁에 있어서 저는 행복해요." },
        },
        {
          zh: "孤单",
          pinyin: "gūdān",
          ko: "외롭다, 고독하다",
          pos: "형용사",
          hanja: "고단(孤單) — '孤(외로울 고)' 하나로도 의미가 와닿아요.",
          ex: { zh: "一个人在国外，他感到很孤单。", pinyin: "yí ge rén zài guówài, tā gǎndào hěn gūdān", ko: "혼자 외국에 있으니 그는 무척 외로워요." },
        },
      ],
    },
    {
      name: "성격과 태도",
      words: [
        {
          zh: "性格",
          pinyin: "xìnggé",
          ko: "성격",
          pos: "명사",
          hanja: "성격(性格) — 한자 그대로예요.",
          ex: { zh: "她的性格很开朗。", pinyin: "tā de xìnggé hěn kāilǎng", ko: "그녀의 성격은 무척 밝아요." },
        },
        {
          zh: "诚实",
          pinyin: "chéngshí",
          ko: "정직하다, 성실하다",
          pos: "형용사",
          hanja: "성실(誠實) — 한국어 '성실'보다 '정직하다'에 가까워요.",
          ex: { zh: "做人要诚实。", pinyin: "zuòrén yào chéngshí", ko: "사람은 정직해야 해요." },
        },
        {
          zh: "幽默",
          pinyin: "yōumò",
          ko: "유머러스하다",
          pos: "형용사",
          hanja: "유묵(幽默) — 영어 humor의 음역이에요. 소리로 외워요.",
          ex: { zh: "他是一个很幽默的人。", pinyin: "tā shì yí ge hěn yōumò de rén", ko: "그는 유머러스한 사람이에요." },
        },
        {
          zh: "骄傲",
          pinyin: "jiāo'ào",
          ko: "교만하다; 자랑스럽다",
          pos: "형용사",
          hanja: "교오(驕傲) — 한자는 '교만'이지만 '자랑스럽다'는 좋은 뜻으로도 써요.",
          ex: { zh: "我为你感到骄傲。", pinyin: "wǒ wèi nǐ gǎndào jiāo'ào", ko: "저는 당신이 자랑스러워요." },
        },
        {
          zh: "耐心",
          pinyin: "nàixīn",
          ko: "인내심",
          pos: "명사",
          hanja: "내심(耐心) — '耐(견딜 내)+心(마음)'. 참는 마음이에요.",
          ex: { zh: "教孩子需要很多耐心。", pinyin: "jiāo háizi xūyào hěn duō nàixīn", ko: "아이를 가르치려면 인내심이 많이 필요해요." },
        },
        {
          zh: "粗心",
          pinyin: "cūxīn",
          ko: "부주의하다, 덜렁대다",
          pos: "형용사",
          hanja: "조심(粗心) — 한국어 '조심'과 정반대! '거칠 조(粗)'라 '덤벙댄다'는 뜻이에요.",
          ex: { zh: "他很粗心，常常忘东西。", pinyin: "tā hěn cūxīn, chángcháng wàng dōngxi", ko: "그는 덜렁대서 자주 물건을 잊어버려요." },
        },
        {
          zh: "活泼",
          pinyin: "huópo",
          ko: "활발하다",
          pos: "형용사",
          hanja: "활발(活潑) — 한자 그대로예요.",
          ex: { zh: "这个孩子很活泼。", pinyin: "zhège háizi hěn huópo", ko: "이 아이는 무척 활발해요." },
        },
        {
          zh: "随便",
          pinyin: "suíbiàn",
          ko: "마음대로, 함부로; 아무거나",
          pos: "부사",
          ex: { zh: "你随便坐吧。", pinyin: "nǐ suíbiàn zuò ba", ko: "편한 대로 앉으세요." },
        },
        {
          zh: "认真",
          pinyin: "rènzhēn",
          ko: "진지하다, 성실하다",
          pos: "형용사",
          ex: { zh: "她学习很认真。", pinyin: "tā xuéxí hěn rènzhēn", ko: "그녀는 공부를 무척 열심히 해요." },
        },
        {
          zh: "好奇",
          pinyin: "hàoqí",
          ko: "호기심이 많다",
          pos: "형용사",
          hanja: "호기(好奇) — '호기심(好奇心)'의 그 호기예요.",
          ex: { zh: "孩子对什么都很好奇。", pinyin: "háizi duì shénme dōu hěn hàoqí", ko: "아이는 무엇에든 호기심이 많아요." },
        },
      ],
    },
    {
      name: "사회와 생활",
      words: [
        {
          zh: "环境",
          pinyin: "huánjìng",
          ko: "환경",
          pos: "명사",
          hanja: "환경(環境) — 한자 그대로예요.",
          ex: { zh: "我们要保护环境。", pinyin: "wǒmen yào bǎohù huánjìng", ko: "우리는 환경을 보호해야 해요." },
        },
        {
          zh: "污染",
          pinyin: "wūrǎn",
          ko: "오염, 오염시키다",
          pos: "동사",
          hanja: "오염(汚染) — 한자 그대로예요.",
          ex: { zh: "城市的空气污染很严重。", pinyin: "chéngshì de kōngqì wūrǎn hěn yánzhòng", ko: "도시의 공기 오염이 심각해요." },
        },
        {
          zh: "交通",
          pinyin: "jiāotōng",
          ko: "교통",
          pos: "명사",
          hanja: "교통(交通) — 한자 그대로예요.",
          ex: { zh: "这里的交通很方便。", pinyin: "zhèlǐ de jiāotōng hěn fāngbiàn", ko: "이곳은 교통이 편리해요." },
        },
        {
          zh: "人口",
          pinyin: "rénkǒu",
          ko: "인구",
          pos: "명사",
          hanja: "인구(人口) — 한자 그대로예요.",
          ex: { zh: "这个城市人口很多。", pinyin: "zhège chéngshì rénkǒu hěn duō", ko: "이 도시는 인구가 많아요." },
        },
        {
          zh: "法律",
          pinyin: "fǎlǜ",
          ko: "법률",
          pos: "명사",
          hanja: "법률(法律) — 한자 그대로예요.",
          ex: { zh: "每个人都要遵守法律。", pinyin: "měi ge rén dōu yào zūnshǒu fǎlǜ", ko: "누구나 법률을 지켜야 해요." },
        },
        {
          zh: "社会",
          pinyin: "shèhuì",
          ko: "사회",
          pos: "명사",
          hanja: "사회(社會) — 한자 그대로예요.",
          ex: { zh: "现代社会变化很快。", pinyin: "xiàndài shèhuì biànhuà hěn kuài", ko: "현대 사회는 변화가 빨라요." },
        },
        {
          zh: "民族",
          pinyin: "mínzú",
          ko: "민족",
          pos: "명사",
          hanja: "민족(民族) — 한자 그대로예요.",
          ex: { zh: "中国有五十六个民族。", pinyin: "zhōngguó yǒu wǔshíliù ge mínzú", ko: "중국에는 56개 민족이 있어요." },
        },
        {
          zh: "国际",
          pinyin: "guójì",
          ko: "국제",
          pos: "명사",
          hanja: "국제(國際) — 한자 그대로예요.",
          ex: { zh: "这是一次国际会议。", pinyin: "zhè shì yí cì guójì huìyì", ko: "이것은 국제 회의예요." },
        },
        {
          zh: "现代",
          pinyin: "xiàndài",
          ko: "현대",
          pos: "명사",
          hanja: "현대(現代) — 한자 그대로예요.",
          ex: { zh: "现代人的生活节奏很快。", pinyin: "xiàndài rén de shēnghuó jiézòu hěn kuài", ko: "현대인의 생활 리듬은 빨라요." },
        },
        {
          zh: "责任",
          pinyin: "zérèn",
          ko: "책임",
          pos: "명사",
          hanja: "책임(責任) — 한자 그대로예요.",
          ex: { zh: "保护环境是大家的责任。", pinyin: "bǎohù huánjìng shì dàjiā de zérèn", ko: "환경 보호는 모두의 책임이에요." },
        },
      ],
    },
    {
      name: "직장과 경제",
      words: [
        {
          zh: "经济",
          pinyin: "jīngjì",
          ko: "경제",
          pos: "명사",
          hanja: "경제(經濟) — 한자 그대로예요.",
          ex: { zh: "这个国家的经济发展很快。", pinyin: "zhège guójiā de jīngjì fāzhǎn hěn kuài", ko: "이 나라의 경제는 빠르게 발전해요." },
        },
        {
          zh: "工资",
          pinyin: "gōngzī",
          ko: "임금, 월급",
          pos: "명사",
          hanja: "공자(工資) — '工(일)+資(자본)'. '임금'으로 외워요.",
          ex: { zh: "他每个月的工资不高。", pinyin: "tā měi ge yuè de gōngzī bù gāo", ko: "그의 월급은 매달 높지 않아요." },
        },
        {
          zh: "收入",
          pinyin: "shōurù",
          ko: "수입, 소득",
          pos: "명사",
          hanja: "수입(收入) — 한자 그대로예요.",
          ex: { zh: "他的收入比以前高了。", pinyin: "tā de shōurù bǐ yǐqián gāo le", ko: "그의 수입은 예전보다 높아졌어요." },
        },
        {
          zh: "招聘",
          pinyin: "zhāopìn",
          ko: "채용하다, 모집하다",
          pos: "동사",
          hanja: "초빙(招聘) — '招(부를 초)+聘(부를 빙)'. 사람을 부른다는 뜻이에요.",
          ex: { zh: "公司正在招聘新员工。", pinyin: "gōngsī zhèngzài zhāopìn xīn yuángōng", ko: "회사는 신입 사원을 채용하고 있어요." },
        },
        {
          zh: "应聘",
          pinyin: "yìngpìn",
          ko: "지원하다 (일자리에)",
          pos: "동사",
          hanja: "응빙(應聘) — '응하여 부름을 받다'. 채용에 지원하는 거예요.",
          ex: { zh: "我想应聘这个职位。", pinyin: "wǒ xiǎng yìngpìn zhège zhíwèi", ko: "저는 이 자리에 지원하고 싶어요." },
        },
        {
          zh: "职业",
          pinyin: "zhíyè",
          ko: "직업",
          pos: "명사",
          hanja: "직업(職業) — 한자 그대로예요.",
          ex: { zh: "你的职业是什么？", pinyin: "nǐ de zhíyè shì shénme", ko: "당신의 직업은 무엇인가요?" },
        },
        {
          zh: "管理",
          pinyin: "guǎnlǐ",
          ko: "관리하다",
          pos: "동사",
          hanja: "관리(管理) — 한자 그대로예요.",
          ex: { zh: "她管理一个很大的团队。", pinyin: "tā guǎnlǐ yí ge hěn dà de tuánduì", ko: "그녀는 큰 팀을 관리해요." },
        },
        {
          zh: "竞争",
          pinyin: "jìngzhēng",
          ko: "경쟁, 경쟁하다",
          pos: "동사",
          hanja: "경쟁(競爭) — 한자 그대로예요.",
          ex: { zh: "市场竞争越来越激烈。", pinyin: "shìchǎng jìngzhēng yuèláiyuè jīliè", ko: "시장 경쟁이 점점 치열해져요." },
        },
        {
          zh: "实习",
          pinyin: "shíxí",
          ko: "실습하다, 인턴",
          pos: "동사",
          hanja: "실습(實習) — 한자 그대로예요.",
          ex: { zh: "她在一家公司实习。", pinyin: "tā zài yì jiā gōngsī shíxí", ko: "그녀는 한 회사에서 인턴을 해요." },
        },
        {
          zh: "顾客",
          pinyin: "gùkè",
          ko: "고객, 손님",
          pos: "명사",
          hanja: "고객(顧客) — 한자 그대로예요.",
          ex: { zh: "这家店的顾客很多。", pinyin: "zhè jiā diàn de gùkè hěn duō", ko: "이 가게는 손님이 많아요." },
        },
      ],
    },
    {
      name: "생각과 표현",
      words: [
        {
          zh: "意见",
          pinyin: "yìjiàn",
          ko: "의견",
          pos: "명사",
          hanja: "의견(意見) — 한자 그대로예요.",
          ex: { zh: "我同意你的意见。", pinyin: "wǒ tóngyì nǐ de yìjiàn", ko: "저는 당신의 의견에 동의해요." },
        },
        {
          zh: "判断",
          pinyin: "pànduàn",
          ko: "판단하다",
          pos: "동사",
          hanja: "판단(判斷) — 한자 그대로예요.",
          ex: { zh: "我们不能只看外表判断一个人。", pinyin: "wǒmen bù néng zhǐ kàn wàibiǎo pànduàn yí ge rén", ko: "겉모습만 보고 사람을 판단해선 안 돼요." },
        },
        {
          zh: "怀疑",
          pinyin: "huáiyí",
          ko: "의심하다",
          pos: "동사",
          hanja: "회의(懷疑) — '품을 회(懷)'. '의심을 품다'예요.",
          ex: { zh: "我怀疑他说的是不是真的。", pinyin: "wǒ huáiyí tā shuō de shì bu shì zhēn de", ko: "그의 말이 사실인지 의심스러워요." },
        },
        {
          zh: "解释",
          pinyin: "jiěshì",
          ko: "설명하다, 해명하다",
          pos: "동사",
          hanja: "해석(解釋) — 한국어 '해석'보다 '설명하다'에 가까워요.",
          ex: { zh: "请你解释一下原因。", pinyin: "qǐng nǐ jiěshì yíxià yuányīn", ko: "이유를 좀 설명해 주세요." },
        },
        {
          zh: "反对",
          pinyin: "fǎnduì",
          ko: "반대하다",
          pos: "동사",
          hanja: "반대(反對) — 한자 그대로예요.",
          ex: { zh: "大家都反对这个计划。", pinyin: "dàjiā dōu fǎnduì zhège jìhuà", ko: "모두가 이 계획에 반대해요." },
        },
        {
          zh: "支持",
          pinyin: "zhīchí",
          ko: "지지하다",
          pos: "동사",
          hanja: "지지(支持) — 한자 그대로예요.",
          ex: { zh: "谢谢大家的支持。", pinyin: "xièxie dàjiā de zhīchí", ko: "여러분의 지지에 감사해요." },
        },
        {
          zh: "考虑",
          pinyin: "kǎolǜ",
          ko: "고려하다, 생각하다",
          pos: "동사",
          hanja: "고려(考慮) — 한자 그대로예요.",
          ex: { zh: "请给我一点时间考虑。", pinyin: "qǐng gěi wǒ yìdiǎn shíjiān kǎolǜ", ko: "생각할 시간을 좀 주세요." },
        },
        {
          zh: "讨论",
          pinyin: "tǎolùn",
          ko: "토론하다, 논의하다",
          pos: "동사",
          hanja: "토론(討論) — 한자 그대로예요.",
          ex: { zh: "我们正在讨论这个问题。", pinyin: "wǒmen zhèngzài tǎolùn zhège wèntí", ko: "우리는 이 문제를 논의하고 있어요." },
        },
        {
          zh: "建议",
          pinyin: "jiànyì",
          ko: "제안하다, 건의",
          pos: "동사",
          hanja: "건의(建議) — 한자 그대로예요.",
          ex: { zh: "我建议你早点儿休息。", pinyin: "wǒ jiànyì nǐ zǎodiǎnr xiūxi", ko: "일찍 쉬는 게 좋겠어요." },
        },
        {
          zh: "估计",
          pinyin: "gūjì",
          ko: "추측하다, 어림하다",
          pos: "동사",
          hanja: "고계(估計) — '估(헤아릴 고)+計(셀 계)'. 어림짐작하는 거예요.",
          ex: { zh: "我估计他不会来了。", pinyin: "wǒ gūjì tā bú huì lái le", ko: "그는 안 올 것 같아요." },
        },
      ],
    },
    {
      name: "정도와 연결",
      words: [
        {
          zh: "其实",
          pinyin: "qíshí",
          ko: "사실은",
          pos: "부사",
          hanja: "기실(其實) — '그 실은'. 한국어 '기실(其實)'과 같아요.",
          ex: { zh: "其实我也不太清楚。", pinyin: "qíshí wǒ yě bú tài qīngchu", ko: "사실 저도 잘 몰라요." },
        },
        {
          zh: "当然",
          pinyin: "dāngrán",
          ko: "당연히, 물론",
          pos: "부사",
          hanja: "당연(當然) — '당연하다'의 그 당연이에요.",
          ex: { zh: "你愿意帮我吗？当然！", pinyin: "nǐ yuànyì bāng wǒ ma? dāngrán", ko: "저를 도와주실래요? 물론이죠!" },
        },
        {
          zh: "几乎",
          pinyin: "jīhū",
          ko: "거의",
          pos: "부사",
          ex: { zh: "他几乎每天都来。", pinyin: "tā jīhū měitiān dōu lái", ko: "그는 거의 매일 와요." },
        },
        {
          zh: "尤其",
          pinyin: "yóuqí",
          ko: "특히",
          pos: "부사",
          ex: { zh: "我喜欢水果，尤其是西瓜。", pinyin: "wǒ xǐhuan shuǐguǒ, yóuqí shì xīguā", ko: "저는 과일을 좋아해요, 특히 수박이요." },
        },
        {
          zh: "至少",
          pinyin: "zhìshǎo",
          ko: "적어도, 최소한",
          pos: "부사",
          hanja: "지소(至少) — '지극히 적게', 곧 '최소한'이에요.",
          ex: { zh: "这件事至少要三天。", pinyin: "zhè jiàn shì zhìshǎo yào sān tiān", ko: "이 일은 적어도 사흘은 걸려요." },
        },
        {
          zh: "竟然",
          pinyin: "jìngrán",
          ko: "뜻밖에도, 의외로",
          pos: "부사",
          ex: { zh: "他竟然忘了我的名字。", pinyin: "tā jìngrán wàng le wǒ de míngzi", ko: "그가 뜻밖에도 제 이름을 잊어버렸어요." },
        },
        {
          zh: "既然",
          pinyin: "jìrán",
          ko: "~한 이상, ~인 바에야",
          pos: "접속사",
          ex: { zh: "既然来了，就多坐一会儿吧。", pinyin: "jìrán lái le, jiù duō zuò yíhuìr ba", ko: "온 김에 좀 더 앉았다 가세요." },
        },
        {
          zh: "无论",
          pinyin: "wúlùn",
          ko: "~에 관계없이, ~든지",
          pos: "접속사",
          hanja: "무론(無論) — '논할 것 없이', 곧 '막론하고'예요.",
          ex: { zh: "无论多忙，他都会回家吃饭。", pinyin: "wúlùn duō máng, tā dōu huì huíjiā chīfàn", ko: "아무리 바빠도 그는 집에 와서 밥을 먹어요." },
        },
        {
          zh: "可是",
          pinyin: "kěshì",
          ko: "그러나, 그렇지만",
          pos: "접속사",
          ex: { zh: "我想去，可是没有时间。", pinyin: "wǒ xiǎng qù, kěshì méiyǒu shíjiān", ko: "가고 싶지만 시간이 없어요." },
        },
        {
          zh: "于是",
          pinyin: "yúshì",
          ko: "그래서, 그리하여",
          pos: "접속사",
          ex: { zh: "下雨了，于是我们回家了。", pinyin: "xiàyǔ le, yúshì wǒmen huíjiā le", ko: "비가 와서 우리는 집에 돌아갔어요." },
        },
      ],
    },
    {
      name: "학습과 능력",
      words: [
        {
          zh: "知识",
          pinyin: "zhīshi",
          ko: "지식",
          pos: "명사",
          hanja: "지식(知識) — 한자 그대로예요.",
          ex: { zh: "读书可以增加知识。", pinyin: "dúshū kěyǐ zēngjiā zhīshi", ko: "책을 읽으면 지식을 늘릴 수 있어요." },
        },
        {
          zh: "能力",
          pinyin: "nénglì",
          ko: "능력",
          pos: "명사",
          hanja: "능력(能力) — 한자 그대로예요.",
          ex: { zh: "他的工作能力很强。", pinyin: "tā de gōngzuò nénglì hěn qiáng", ko: "그는 업무 능력이 뛰어나요." },
        },
        {
          zh: "经验",
          pinyin: "jīngyàn",
          ko: "경험",
          pos: "명사",
          hanja: "경험(經驗) — 한자 그대로예요.",
          ex: { zh: "这次实习让我积累了经验。", pinyin: "zhè cì shíxí ràng wǒ jīlěi le jīngyàn", ko: "이번 인턴십으로 경험을 쌓았어요." },
        },
        {
          zh: "印象",
          pinyin: "yìnxiàng",
          ko: "인상",
          pos: "명사",
          hanja: "인상(印象) — 한자 그대로예요.",
          ex: { zh: "他给我的印象很好。", pinyin: "tā gěi wǒ de yìnxiàng hěn hǎo", ko: "그는 제게 좋은 인상을 줬어요." },
        },
        {
          zh: "重视",
          pinyin: "zhòngshì",
          ko: "중시하다",
          pos: "동사",
          hanja: "중시(重視) — 한자 그대로예요.",
          ex: { zh: "学校很重视学生的健康。", pinyin: "xuéxiào hěn zhòngshì xuésheng de jiànkāng", ko: "학교는 학생의 건강을 중시해요." },
        },
        {
          zh: "提高",
          pinyin: "tígāo",
          ko: "높이다, 향상시키다",
          pos: "동사",
          hanja: "제고(提高) — 한국어 '제고'와 같아요. '높이다'예요.",
          ex: { zh: "我想提高我的中文水平。", pinyin: "wǒ xiǎng tígāo wǒ de zhōngwén shuǐpíng", ko: "저는 중국어 실력을 높이고 싶어요." },
        },
        {
          zh: "鼓励",
          pinyin: "gǔlì",
          ko: "격려하다",
          pos: "동사",
          hanja: "고려(鼓勵) — '북을 쳐 힘을 돋우다'. '격려하다'예요.",
          ex: { zh: "老师鼓励我们多读书。", pinyin: "lǎoshī gǔlì wǒmen duō dúshū", ko: "선생님은 우리에게 책을 많이 읽으라고 격려해요." },
        },
        {
          zh: "掌握",
          pinyin: "zhǎngwò",
          ko: "숙달하다, 장악하다",
          pos: "동사",
          hanja: "장악(掌握) — '손바닥에 쥐다'. 기술·지식을 완전히 익히는 거예요.",
          ex: { zh: "他已经掌握了这门技术。", pinyin: "tā yǐjīng zhǎngwò le zhè mén jìshù", ko: "그는 이미 이 기술을 숙달했어요." },
        },
        {
          zh: "丰富",
          pinyin: "fēngfù",
          ko: "풍부하다",
          pos: "형용사",
          hanja: "풍부(豐富) — 한자 그대로예요.",
          ex: { zh: "他的经验很丰富。", pinyin: "tā de jīngyàn hěn fēngfù", ko: "그는 경험이 풍부해요." },
        },
        {
          zh: "成功",
          pinyin: "chénggōng",
          ko: "성공하다, 성공",
          pos: "동사",
          hanja: "성공(成功) — 한자 그대로예요.",
          ex: { zh: "经过努力，他终于成功了。", pinyin: "jīngguò nǔlì, tā zhōngyú chénggōng le", ko: "노력 끝에 그는 마침내 성공했어요." },
        },
        {
          zh: "失败",
          pinyin: "shībài",
          ko: "실패하다, 실패",
          pos: "동사",
          hanja: "실패(失敗) — 한자 그대로예요.",
          ex: { zh: "失败是成功之母。", pinyin: "shībài shì chénggōng zhī mǔ", ko: "실패는 성공의 어머니예요." },
        },
        {
          zh: "区别",
          pinyin: "qūbié",
          ko: "구별, 차이",
          pos: "명사",
          hanja: "구별(區別) — 한자 그대로예요.",
          ex: { zh: "这两个词有什么区别？", pinyin: "zhè liǎng ge cí yǒu shénme qūbié", ko: "이 두 단어는 어떤 차이가 있나요?" },
        },
      ],
    },
    {
      name: "교재 보충 어휘",
      words: [
        {
          zh: "流利",
          pinyin: "liúlì",
          ko: "유창하다",
          pos: "형용사",
          hanja: "유리(流利) — '물 흐르듯 매끄럽다'. 말이 막힘없는 거예요.",
          ex: { zh: "他汉语说得非常流利。", pinyin: "tā Hànyǔ shuō de fēicháng liúlì", ko: "그는 중국어를 아주 유창하게 해요." },
        },
        {
          zh: "汉字",
          pinyin: "Hànzì",
          ko: "한자",
          pos: "명사",
          hanja: "한자(漢字) — 한자 그대로예요.",
          ex: { zh: "这些汉字我都看得懂。", pinyin: "zhèxiē Hànzì wǒ dōu kàn de dǒng", ko: "이 한자들은 다 읽을 수 있어요." },
        },
        {
          zh: "休息",
          pinyin: "xiūxi",
          ko: "쉬다, 휴식하다",
          pos: "동사",
          hanja: "휴식(休息) — 한자 그대로예요.",
          ex: { zh: "要是你累了，就早点儿休息。", pinyin: "yàoshi nǐ lèi le, jiù zǎo diǎnr xiūxi", ko: "만약 피곤하면 일찍 쉬어요." },
        },
        {
          zh: "下班",
          pinyin: "xiàbān",
          ko: "퇴근하다",
          pos: "동사",
          hanja: "하반(下班) — '근무 조에서 내려오다'. '퇴근하다'예요.",
          ex: { zh: "他一下班就回家了。", pinyin: "tā yí xiàbān jiù huí jiā le", ko: "그는 퇴근하자마자 집에 갔어요." },
        },
        {
          zh: "回家",
          pinyin: "huí jiā",
          ko: "집에 돌아가다",
          pos: "동사",
          hanja: "회가(回家) — '집으로 돌아가다'예요.",
          ex: { zh: "无论多忙，他都会回家吃饭。", pinyin: "wúlùn duō máng, tā dōu huì huí jiā chīfàn", ko: "아무리 바빠도 그는 집에 와서 밥을 먹어요." },
        },
        {
          zh: "出生",
          pinyin: "chūshēng",
          ko: "태어나다, 출생하다",
          pos: "동사",
          hanja: "출생(出生) — 한자 그대로예요.",
          ex: { zh: "他是在北京出生的。", pinyin: "tā shì zài Běijīng chūshēng de", ko: "그는 베이징에서 태어났어요." },
        },
        {
          zh: "网上",
          pinyin: "wǎngshàng",
          ko: "인터넷(상), 온라인",
          pos: "명사",
          hanja: "망상(網上) — '그물(網) 위', 곧 인터넷이에요.",
          ex: { zh: "这件衣服是在网上买的。", pinyin: "zhè jiàn yīfu shì zài wǎngshàng mǎi de", ko: "이 옷은 인터넷에서 샀어요." },
        },
        {
          zh: "认识",
          pinyin: "rènshi",
          ko: "알다, 인식하다",
          pos: "동사",
          hanja: "인식(認識) — 한자 그대로예요. '(사람·글자를) 알다'로도 써요.",
          ex: { zh: "他连一个字都不认识。", pinyin: "tā lián yí ge zì dōu bú rènshi", ko: "그는 글자 하나조차 몰라요." },
        },
        {
          zh: "日语",
          pinyin: "Rìyǔ",
          ko: "일본어",
          pos: "명사",
          hanja: "일어(日語) — '일본어'예요.",
          ex: { zh: "除了汉语以外，他还会说日语。", pinyin: "chúle Hànyǔ yǐwài, tā hái huì shuō Rìyǔ", ko: "중국어 말고도 그는 일본어도 할 줄 알아요." },
        },
        {
          zh: "上班",
          pinyin: "shàngbān",
          ko: "출근하다",
          pos: "동사",
          hanja: "상반(上班) — '근무 조에 오르다'. '출근하다'예요.",
          ex: { zh: "除了周末以外，我每天都上班。", pinyin: "chúle zhōumò yǐwài, wǒ měitiān dōu shàngbān", ko: "주말 빼고 저는 매일 출근해요." },
        },
        {
          zh: "了解",
          pinyin: "liǎojiě",
          ko: "이해하다, 잘 알다",
          pos: "동사",
          hanja: "요해(了解) — '분명히 풀어 알다'. 속속들이 아는 거예요.",
          ex: { zh: "关于中国文化，我了解得不多。", pinyin: "guānyú Zhōngguó wénhuà, wǒ liǎojiě de bù duō", ko: "중국 문화에 관해서는 잘 알지 못해요." },
        },
        {
          zh: "好用",
          pinyin: "hǎoyòng",
          ko: "쓰기 좋다, 편리하다",
          pos: "형용사",
          hanja: "호용(好用) — '쓰기에 좋다'예요.",
          ex: { zh: "这个手机不但便宜，而且好用。", pinyin: "zhège shǒujī búdàn piányi, érqiě hǎoyòng", ko: "이 휴대폰은 쌀 뿐 아니라 게다가 쓰기 좋아요." },
        },
        {
          zh: "带来",
          pinyin: "dàilái",
          ko: "가져오다, 데려오다",
          pos: "동사",
          hanja: "대래(帶來) — '지녀서(帶) 오다(來)'예요.",
          ex: { zh: "他不但自己来了，而且还带来了朋友。", pinyin: "tā búdàn zìjǐ lái le, érqiě hái dàilái le péngyou", ko: "그는 자기가 왔을 뿐 아니라 친구까지 데려왔어요." },
        },
        {
          zh: "营业",
          pinyin: "yíngyè",
          ko: "영업하다",
          pos: "동사",
          hanja: "영업(營業) — 한자 그대로예요.",
          ex: { zh: "这家店除了周一，每天都营业。", pinyin: "zhè jiā diàn chúle zhōuyī, měitiān dōu yíngyè", ko: "이 가게는 월요일 빼고 매일 영업해요." },
        },
        {
          zh: "谈",
          pinyin: "tán",
          ko: "이야기하다, 논하다",
          pos: "동사",
          hanja: "담(談) — '담화(談話)'의 담. 이야기를 나누는 거예요.",
          ex: { zh: "关于这件事，我们明天再谈。", pinyin: "guānyú zhè jiàn shì, wǒmen míngtiān zài tán", ko: "이 일에 관해서는 내일 다시 얘기해요." },
        },
        {
          zh: "懂",
          pinyin: "dǒng",
          ko: "이해하다, 알다",
          pos: "동사",
          ex: { zh: "你怎么连这个都不懂？", pinyin: "nǐ zěnme lián zhège dōu bù dǒng", ko: "어떻게 이것조차 모를 수 있어요?" },
        },
        {
          zh: "忘",
          pinyin: "wàng",
          ko: "잊다",
          pos: "동사",
          hanja: "망(忘) — '망각(忘却)'의 망. 잊어버리는 거예요.",
          ex: { zh: "我连他的名字都忘了。", pinyin: "wǒ lián tā de míngzi dōu wàng le", ko: "저는 그의 이름조차 잊었어요." },
        },
      ],
    },
  ],
};

export default themes;
