/**
 * H4 (HSK 4급) 보강 어휘 — 청크 A.
 * 표준 HSK4 단어 목록 중 본편에 없던 어휘를 보충(163개).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되, 성씨·이체자·다음자 오독은
 * 실제 HSK 의미에 맞는 표준 병음으로 교정했어요. 가짜동족어는 ko·hanja에 명시.
 */
const themes = {
  themes: [
    {
      name: "HSK4 보강 — 동사",
      icon: "🔶",
      words: [
        { zh: "安排", pinyin: "ān pái", ko: "안배하다, 계획하다, 배정하다", pos: "동사", hanja: "안배(安排) — '安'은 편안할 안, '排'는 늘어놓을 배.", ex: { zh: "我来安排今天的工作。", pinyin: "wǒ lái ānpái jīntiān de gōngzuò", ko: "오늘 일은 제가 배정할게요." } },
        { zh: "包括", pinyin: "bāo kuò", ko: "포함하다, 포괄하다", pos: "동사", hanja: "포괄(包括) — '包'는 쌀 포, '括'는 묶을 괄.", ex: { zh: "这次旅行包括机票和饭店。", pinyin: "zhè cì lǚxíng bāokuò jīpiào hé fàndiàn", ko: "이번 여행은 항공권과 호텔을 포함해요." } },
        { zh: "保护", pinyin: "bǎo hù", ko: "보호하다, 지키다", pos: "동사", hanja: "보호(保護) — 한자 그대로.", ex: { zh: "我们要保护环境。", pinyin: "wǒmen yào bǎohù huánjìng", ko: "우리는 환경을 보호해야 해요." } },
        { zh: "保证", pinyin: "bǎo zhèng", ko: "보증하다, 보장하다, 장담하다", pos: "동사", hanja: "보증(保證) — 한자 그대로.", ex: { zh: "我保证准时到。", pinyin: "wǒ bǎozhèng zhǔnshí dào", ko: "제시간에 도착할 거라고 장담해요." } },
        { zh: "报道", pinyin: "bào dào", ko: "보도하다; 보도, 뉴스 기사", pos: "동사", hanja: "보도(報道) — 한자 그대로.", ex: { zh: "电视上报道了这件事。", pinyin: "diànshì shang bàodào le zhè jiàn shì", ko: "TV에서 이 일을 보도했어요." } },
        { zh: "报名", pinyin: "bào míng", ko: "신청하다, 등록하다, 접수하다", pos: "동사", hanja: "보명(報名) — '名(이름)을 報(알리다)' → 이름을 올려 신청하다.", ex: { zh: "我报名参加了比赛。", pinyin: "wǒ bàomíng cānjiā le bǐsài", ko: "저는 대회에 참가 신청을 했어요." } },
        { zh: "抱", pinyin: "bào", ko: "안다, 품다, 끌어안다", pos: "동사", hanja: "포(抱) — '안을 포'.", ex: { zh: "妈妈抱着孩子。", pinyin: "māma bàozhe háizi", ko: "엄마가 아이를 안고 있어요." } },
        { zh: "擦", pinyin: "cā", ko: "닦다, 문지르다, 바르다", pos: "동사", ex: { zh: "请把桌子擦干净。", pinyin: "qǐng bǎ zhuōzi cā gānjìng", ko: "탁자를 깨끗이 닦아 주세요." } },
        { zh: "猜", pinyin: "cāi", ko: "추측하다, 알아맞히다", pos: "동사", ex: { zh: "你猜我今年多大？", pinyin: "nǐ cāi wǒ jīnnián duō dà", ko: "제가 올해 몇 살인지 맞혀 볼래요?" } },
        { zh: "参观", pinyin: "cān guān", ko: "참관하다, 견학하다, 둘러보다", pos: "동사", hanja: "참관(參觀) — '參'은 참여할 참, '觀'은 볼 관.", ex: { zh: "我们去参观了博物馆。", pinyin: "wǒmen qù cānguān le bówùguǎn", ko: "우리는 박물관을 견학했어요." } },
        { zh: "尝", pinyin: "cháng", ko: "맛보다, 시식하다", pos: "동사", hanja: "상(嘗) — '맛볼 상'.", ex: { zh: "你尝一下这个菜。", pinyin: "nǐ cháng yíxià zhège cài", ko: "이 음식 한번 맛봐요." } },
        { zh: "超过", pinyin: "chāo guò", ko: "초과하다, 넘어서다, 앞지르다", pos: "동사", hanja: "초과(超過) — '超'는 넘을 초, '過'는 지날 과.", ex: { zh: "今天气温超过了三十度。", pinyin: "jīntiān qìwēn chāoguò le sānshí dù", ko: "오늘 기온이 30도를 넘었어요." } },
        { zh: "吵", pinyin: "chǎo", ko: "다투다, 말다툼하다; 시끄럽다", pos: "동사", ex: { zh: "他们俩又吵起来了。", pinyin: "tāmen liǎ yòu chǎo qǐlái le", ko: "그 둘이 또 다투기 시작했어요." } },
        { zh: "成为", pinyin: "chéng wéi", ko: "~이 되다, ~으로 되다", pos: "동사", hanja: "성위(成爲) — '成'은 이룰 성, '爲'는 될 위.", ex: { zh: "他成为了一名医生。", pinyin: "tā chéngwéi le yì míng yīshēng", ko: "그는 의사가 되었어요." } },
        { zh: "乘坐", pinyin: "chéng zuò", ko: "(교통수단을) 타다, 탑승하다", pos: "동사", hanja: "승좌(乘坐) — '乘'은 탈 승, '坐'는 앉을 좌.", ex: { zh: "我们乘坐地铁去机场。", pinyin: "wǒmen chéngzuò dìtiě qù jīchǎng", ko: "우리는 지하철을 타고 공항에 가요." } },
        { zh: "抽烟", pinyin: "chōu yān", ko: "담배를 피우다", pos: "동사", hanja: "추연(抽煙) — '煙'은 연기 연. '담배를 뽑아 피우다'.", ex: { zh: "这里不能抽烟。", pinyin: "zhèlǐ bù néng chōuyān", ko: "여기서는 담배를 피우면 안 돼요." } },
        { zh: "出差", pinyin: "chū chāi", ko: "출장 가다", pos: "동사", hanja: "출차(出差) — '差(chāi)'는 파견·임무. '差'를 chā로 읽지 않도록 주의.", ex: { zh: "他下周要去上海出差。", pinyin: "tā xià zhōu yào qù Shànghǎi chūchāi", ko: "그는 다음 주에 상하이로 출장 가요." } },
        { zh: "出发", pinyin: "chū fā", ko: "출발하다, 떠나다", pos: "동사", hanja: "출발(出發) — 한자 그대로.", ex: { zh: "我们明天早上出发。", pinyin: "wǒmen míngtiān zǎoshang chūfā", ko: "우리는 내일 아침에 출발해요." } },
        { zh: "打扮", pinyin: "dǎ ban", ko: "꾸미다, 단장하다, 차려입다", pos: "동사", ex: { zh: "她今天打扮得很漂亮。", pinyin: "tā jīntiān dǎban de hěn piàoliang", ko: "그녀는 오늘 예쁘게 꾸몄어요." } },
        { zh: "打扰", pinyin: "dǎ rǎo", ko: "방해하다, 폐를 끼치다", pos: "동사", hanja: "타요(打擾) — '擾'는 어지러울 요. '방해하다'.", ex: { zh: "对不起，打扰你了。", pinyin: "duìbuqǐ, dǎrǎo nǐ le", ko: "죄송해요, 방해했네요." } },
        { zh: "打印", pinyin: "dǎ yìn", ko: "출력하다, 인쇄하다, 프린트하다", pos: "동사", hanja: "타인(打印) — '印'은 도장·찍을 인.", ex: { zh: "请帮我打印这份文件。", pinyin: "qǐng bāng wǒ dǎyìn zhè fèn wénjiàn", ko: "이 문서 좀 출력해 주세요." } },
        { zh: "打折", pinyin: "dǎ zhé", ko: "할인하다, 세일하다", pos: "동사", hanja: "타절(打折) — '折'은 꺾을 절. '값을 깎다'.", ex: { zh: "这件衣服打八折。", pinyin: "zhè jiàn yīfu dǎ bā zhé", ko: "이 옷은 20% 할인해요.(80% 가격)" } },
        { zh: "打针", pinyin: "dǎ zhēn", ko: "주사를 맞다, 주사를 놓다", pos: "동사", hanja: "타침(打針) — '針'은 바늘 침.", ex: { zh: "医生给我打了一针。", pinyin: "yīshēng gěi wǒ dǎ le yì zhēn", ko: "의사가 저에게 주사를 한 대 놓았어요." } },
        { zh: "代替", pinyin: "dài tì", ko: "대신하다, 대체하다", pos: "동사", hanja: "대체(代替) — '代'는 대신할 대, '替'는 바꿀 체.", ex: { zh: "今天我代替他上课。", pinyin: "jīntiān wǒ dàitì tā shàngkè", ko: "오늘은 제가 그를 대신해 수업해요." } },
        { zh: "戴", pinyin: "dài", ko: "(모자·안경·장신구를) 쓰다, 착용하다", pos: "동사", hanja: "대(戴) — '일 대(머리에 얹다)'. 성씨가 아니라 '착용하다' 동사.", ex: { zh: "他戴着一副眼镜。", pinyin: "tā dàizhe yí fù yǎnjìng", ko: "그는 안경을 쓰고 있어요." } },
        { zh: "弹", pinyin: "tán", ko: "(악기를) 치다, 연주하다, 튕기다", pos: "동사", hanja: "탄(彈) — 악기 연주는 'tán'. (총알·탄환 뜻은 dàn)", ex: { zh: "她会弹钢琴。", pinyin: "tā huì tán gāngqín", ko: "그녀는 피아노를 칠 줄 알아요." } },
        { zh: "道歉", pinyin: "dào qiàn", ko: "사과하다, 사죄하다", pos: "동사", hanja: "도겸(道歉) — '道'는 말할 도, '歉'은 미안할 겸.", ex: { zh: "他向我道歉了。", pinyin: "tā xiàng wǒ dàoqiàn le", ko: "그가 저에게 사과했어요." } },
        { zh: "调查", pinyin: "diào chá", ko: "조사하다; 조사", pos: "동사", hanja: "조사(調查) — '調(diào)'는 조사·옮길 조. 가락 뜻일 땐 tiáo.", ex: { zh: "警察正在调查这件事。", pinyin: "jǐngchá zhèngzài diàochá zhè jiàn shì", ko: "경찰이 이 일을 조사하고 있어요." } },
        { zh: "掉", pinyin: "diào", ko: "떨어지다, 떨어뜨리다, 잃다", pos: "동사", ex: { zh: "我的手机掉地上了。", pinyin: "wǒ de shǒujī diào dìshang le", ko: "제 휴대폰이 바닥에 떨어졌어요." } },
        { zh: "丢", pinyin: "diū", ko: "잃어버리다, 버리다, 내던지다", pos: "동사", ex: { zh: "我把钱包丢了。", pinyin: "wǒ bǎ qiánbāo diū le", ko: "저는 지갑을 잃어버렸어요." } },
        { zh: "堵车", pinyin: "dǔ chē", ko: "차가 막히다, 교통 체증이 생기다", pos: "동사", hanja: "도차(堵車) — '堵'는 막을 도, '車'는 차 차.", ex: { zh: "上班的时候经常堵车。", pinyin: "shàngbān de shíhou jīngcháng dǔchē", ko: "출근할 때 자주 차가 막혀요." } },
        { zh: "断", pinyin: "duàn", ko: "끊다, 끊어지다, 부러지다", pos: "동사", hanja: "단(斷) — '끊을 단'.", ex: { zh: "电话突然断了。", pinyin: "diànhuà tūrán duàn le", ko: "전화가 갑자기 끊겼어요." } },
        { zh: "对话", pinyin: "duì huà", ko: "대화하다; 대화", pos: "동사", hanja: "대화(對話) — '對'는 마주할 대, '話'는 말 화.", ex: { zh: "我们用中文对话。", pinyin: "wǒmen yòng Zhōngwén duìhuà", ko: "우리는 중국어로 대화해요." } },
        { zh: "翻译", pinyin: "fān yì", ko: "번역하다, 통역하다; 번역가", pos: "동사", hanja: "번역(翻譯) — '翻'은 뒤집을 번, '譯'은 통역할 역.", ex: { zh: "请帮我翻译这句话。", pinyin: "qǐng bāng wǒ fānyì zhè jù huà", ko: "이 말 좀 번역해 주세요." } },
        { zh: "反映", pinyin: "fǎn yìng", ko: "반영하다, (의견을) 전달하다", pos: "동사", hanja: "반영(反映) — '反'은 돌이킬 반, '映'은 비칠 영.", ex: { zh: "这个问题反映了现实。", pinyin: "zhège wèntí fǎnyìng le xiànshí", ko: "이 문제는 현실을 반영해요." } },
        { zh: "访问", pinyin: "fǎng wèn", ko: "방문하다, 인터뷰하다", pos: "동사", hanja: "방문(訪問) — '訪'은 찾을 방, '問'은 물을 문.", ex: { zh: "总统访问了那个国家。", pinyin: "zǒngtǒng fǎngwèn le nàge guójiā", ko: "대통령이 그 나라를 방문했어요." } },
        { zh: "放暑假", pinyin: "fàng shǔ jià", ko: "여름방학을 하다", pos: "동사", hanja: "방서가(放暑假) — '暑'는 더울 서, '假'는 휴가·방학 가.", ex: { zh: "学校七月开始放暑假。", pinyin: "xuéxiào qī yuè kāishǐ fàng shǔjià", ko: "학교는 7월부터 여름방학을 해요." } },
        { zh: "符合", pinyin: "fú hé", ko: "부합하다, 들어맞다, 일치하다", pos: "동사", hanja: "부합(符合) — '符'는 부신 부, '合'은 합할 합.", ex: { zh: "这个结果符合我的想法。", pinyin: "zhège jiéguǒ fúhé wǒ de xiǎngfǎ", ko: "이 결과는 제 생각과 들어맞아요." } },
        { zh: "复印", pinyin: "fù yìn", ko: "복사하다", pos: "동사", hanja: "복인(複印) — '複'은 겹칠 복, '印'은 찍을 인.", ex: { zh: "我去复印几张纸。", pinyin: "wǒ qù fùyìn jǐ zhāng zhǐ", ko: "종이 몇 장 복사하러 갈게요." } },
        { zh: "改变", pinyin: "gǎi biàn", ko: "바꾸다, 변하다, 변화시키다", pos: "동사", hanja: "개변(改變) — '改'는 고칠 개, '變'은 변할 변.", ex: { zh: "他改变了主意。", pinyin: "tā gǎibiàn le zhǔyì", ko: "그는 생각을 바꿨어요." } },
        { zh: "感觉", pinyin: "gǎn jué", ko: "느끼다; 느낌, 감각", pos: "동사", hanja: "감각(感覺) — '感'은 느낄 감, '覺'은 깨달을 각.", ex: { zh: "我感觉有点累。", pinyin: "wǒ gǎnjué yǒudiǎn lèi", ko: "저는 좀 피곤한 느낌이에요." } },
        { zh: "感谢", pinyin: "gǎn xiè", ko: "감사하다, 고마워하다", pos: "동사", hanja: "감사(感謝) — '感'은 느낄 감, '謝'는 사례할 사.", ex: { zh: "非常感谢你的帮助。", pinyin: "fēicháng gǎnxiè nǐ de bāngzhù", ko: "도와주셔서 정말 감사해요." } },
        { zh: "干杯", pinyin: "gān bēi", ko: "건배하다, 잔을 비우다", pos: "동사", hanja: "건배(乾杯) — '乾'은 마를 건, '杯'는 잔 배. '잔을 비우다'.", ex: { zh: "为我们的友谊干杯！", pinyin: "wèi wǒmen de yǒuyì gānbēi", ko: "우리의 우정을 위해 건배!" } },
        { zh: "鼓掌", pinyin: "gǔ zhǎng", ko: "박수를 치다", pos: "동사", hanja: "고장(鼓掌) — '鼓'는 북·두드릴 고, '掌'은 손바닥 장.", ex: { zh: "大家都为他鼓掌。", pinyin: "dàjiā dōu wèi tā gǔzhǎng", ko: "모두가 그에게 박수를 쳤어요." } },
        { zh: "购物", pinyin: "gòu wù", ko: "쇼핑하다, 물건을 사다", pos: "동사", hanja: "구물(購物) — '購'는 살 구, '物'은 물건 물.", ex: { zh: "周末我喜欢去购物。", pinyin: "zhōumò wǒ xǐhuan qù gòuwù", ko: "주말에 저는 쇼핑하러 가는 걸 좋아해요." } },
        { zh: "逛", pinyin: "guàng", ko: "거닐다, 구경하며 다니다, 돌아다니다", pos: "동사", ex: { zh: "我们去逛街吧。", pinyin: "wǒmen qù guàngjiē ba", ko: "우리 거리 구경하러 가요." } },
        { zh: "广播", pinyin: "guǎng bō", ko: "방송하다; 방송, 라디오 방송", pos: "동사", hanja: "광파(廣播) — '廣'은 넓을 광, '播'는 뿌릴 파.", ex: { zh: "机场正在广播通知。", pinyin: "jīchǎng zhèngzài guǎngbō tōngzhī", ko: "공항에서 안내 방송을 하고 있어요." } },
        { zh: "规定", pinyin: "guī dìng", ko: "규정하다, 정하다; 규정, 규칙", pos: "동사", hanja: "규정(規定) — '規'는 법 규, '定'은 정할 정.", ex: { zh: "公司规定不能迟到。", pinyin: "gōngsī guīdìng bù néng chídào", ko: "회사는 지각하면 안 된다고 정해 놓았어요." } },
        { zh: "表达", pinyin: "biǎo dá", ko: "표현하다, (생각·감정을) 나타내다", pos: "동사", hanja: "표달(表達) — '表'는 겉·드러낼 표, '達'은 통할 달.", ex: { zh: "我不知道怎么表达。", pinyin: "wǒ bù zhīdào zěnme biǎodá", ko: "어떻게 표현해야 할지 모르겠어요." } },
        { zh: "干", pinyin: "gàn", ko: "하다, (일을) 하다, 종사하다", pos: "동사", hanja: "간(幹) — '줄기·일할 간'. '일하다' 뜻은 gàn으로 읽어요(gān 아님).", ex: { zh: "你在干什么？", pinyin: "nǐ zài gàn shénme", ko: "당신 뭐 하고 있어요?" } },
        { zh: "积累", pinyin: "jī lěi", ko: "쌓다, 축적하다, 누적되다", pos: "동사", hanja: "적루(積累) — '積'은 쌓을 적, '累'는 포갤 루.", ex: { zh: "学语言要慢慢积累。", pinyin: "xué yǔyán yào mànman jīlěi", ko: "언어를 배우려면 천천히 쌓아 가야 해요." } },
        { zh: "集合", pinyin: "jí hé", ko: "집합하다, 모이다, 집결하다", pos: "동사", hanja: "집합(集合) — '集'은 모을 집, '合'은 합할 합.", ex: { zh: "我们八点在门口集合。", pinyin: "wǒmen bā diǎn zài ménkǒu jíhé", ko: "우리는 8시에 입구에서 모여요." } },
        { zh: "计划", pinyin: "jì huà", ko: "계획하다; 계획", pos: "동사", hanja: "계획(計劃) — '計'는 셀 계, '劃'은 그을 획.", ex: { zh: "我计划明年去中国。", pinyin: "wǒ jìhuà míngnián qù Zhōngguó", ko: "저는 내년에 중국에 갈 계획이에요." } },
        { zh: "继续", pinyin: "jì xù", ko: "계속하다, 이어 가다", pos: "동사", hanja: "계속(繼續) — '繼'는 이을 계, '續'은 이을 속.", ex: { zh: "我们继续讨论吧。", pinyin: "wǒmen jìxù tǎolùn ba", ko: "우리 계속 논의해요." } },
        { zh: "寄", pinyin: "jì", ko: "(우편으로) 부치다, 보내다, 맡기다", pos: "동사", hanja: "기(寄) — '부칠 기'.", ex: { zh: "我想寄一封信。", pinyin: "wǒ xiǎng jì yì fēng xìn", ko: "저는 편지 한 통을 부치고 싶어요." } },
        { zh: "回忆", pinyin: "huí yì", ko: "회상하다, 떠올리다; 추억", pos: "동사", hanja: "회억(回憶) — '回'는 돌아올 회, '憶'은 생각할 억.", ex: { zh: "我常常回忆小时候。", pinyin: "wǒ chángcháng huíyì xiǎoshíhou", ko: "저는 종종 어린 시절을 회상해요." } },
        { zh: "合格", pinyin: "hé gé", ko: "합격하다, 기준에 맞다; 합격", pos: "동사", hanja: "합격(合格) — '合'은 합할 합, '格'은 격식 격.", ex: { zh: "这次考试他合格了。", pinyin: "zhè cì kǎoshì tā hégé le", ko: "이번 시험에 그는 합격했어요." } },
        { zh: "当", pinyin: "dāng", ko: "~이 되다, 맡다; ~할 때, ~에서", pos: "동사", hanja: "당(當) — '마땅할 당'. '~이 되다(当老师)' 또는 시점·장소를 이끌어요.", ex: { zh: "他想当医生。", pinyin: "tā xiǎng dāng yīshēng", ko: "그는 의사가 되고 싶어 해요." } },
        { zh: "过", pinyin: "guò", ko: "지나다, 보내다; (경험을 나타내는) ~한 적 있다", pos: "동사", hanja: "과(過) — '지날 과'. 성씨가 아니라 동사/경험 표지. 동사 뒤 过는 '~해 본 적 있다'.", ex: { zh: "我去过北京。", pinyin: "wǒ qùguo Běijīng", ko: "저는 베이징에 가 본 적이 있어요." } },
      ],
    },
    {
      name: "HSK4 보강 — 명사·사물",
      icon: "🔶",
      words: [
        { zh: "爱情", pinyin: "ài qíng", ko: "(남녀 간의) 사랑, 애정", pos: "명사", hanja: "애정(愛情) — '愛'는 사랑 애, '情'은 뜻 정. 주로 연애 감정.", ex: { zh: "这是一个爱情故事。", pinyin: "zhè shì yí ge àiqíng gùshi", ko: "이건 사랑 이야기예요." } },
        { zh: "标准", pinyin: "biāo zhǔn", ko: "기준, 표준; 표준적인", pos: "명사", hanja: "표준(標準) — '標'는 표할 표, '準'은 법도 준.", ex: { zh: "他的发音很标准。", pinyin: "tā de fāyīn hěn biāozhǔn", ko: "그의 발음은 아주 표준적이에요." } },
        { zh: "表格", pinyin: "biǎo gé", ko: "표, 양식, 서식", pos: "명사", hanja: "표격(表格) — '表'는 겉·표 표, '格'은 칸 격.", ex: { zh: "请填一下这张表格。", pinyin: "qǐng tián yíxià zhè zhāng biǎogé", ko: "이 양식을 좀 작성해 주세요." } },
        { zh: "饼干", pinyin: "bǐng gān", ko: "비스킷, 과자, 크래커", pos: "명사", hanja: "병건(餅乾) — '餅'은 떡 병, '乾'은 마를 건.", ex: { zh: "我买了一盒饼干。", pinyin: "wǒ mǎi le yì hé bǐnggān", ko: "저는 과자 한 통을 샀어요." } },
        { zh: "博士", pinyin: "bó shì", ko: "박사", pos: "명사", hanja: "박사(博士) — '博'은 넓을 박, '士'는 선비 사.", ex: { zh: "他是经济学博士。", pinyin: "tā shì jīngjìxué bóshì", ko: "그는 경제학 박사예요." } },
        { zh: "材料", pinyin: "cái liào", ko: "재료, 자료, 소재", pos: "명사", hanja: "재료(材料) — '材'는 재목 재, '料'는 헤아릴 료.", ex: { zh: "做这个菜需要很多材料。", pinyin: "zuò zhège cài xūyào hěn duō cáiliào", ko: "이 요리를 만들려면 재료가 많이 필요해요." } },
        { zh: "传真", pinyin: "chuán zhēn", ko: "팩스", pos: "명사", hanja: "전진(傳真) — '傳'은 전할 전, '眞'은 참 진.", ex: { zh: "请把文件发传真给我。", pinyin: "qǐng bǎ wénjiàn fā chuánzhēn gěi wǒ", ko: "문서를 팩스로 보내 주세요." } },
        { zh: "窗户", pinyin: "chuāng hu", ko: "창문", pos: "명사", hanja: "창호(窗戶) — '窗'은 창 창, '戶'는 지게문 호.", ex: { zh: "请把窗户打开。", pinyin: "qǐng bǎ chuānghu dǎkāi", ko: "창문 좀 열어 주세요." } },
        { zh: "词典", pinyin: "cí diǎn", ko: "사전", pos: "명사", hanja: "사전(詞典) — '詞'는 말 사, '典'은 책 전.", ex: { zh: "我用词典查生词。", pinyin: "wǒ yòng cídiǎn chá shēngcí", ko: "저는 사전으로 새 단어를 찾아요." } },
        { zh: "答案", pinyin: "dá àn", ko: "답, 정답, 해답", pos: "명사", hanja: "답안(答案) — '答'은 대답할 답, '案'은 책상·안 안.", ex: { zh: "这道题的答案是什么？", pinyin: "zhè dào tí de dá'àn shì shénme", ko: "이 문제의 답은 뭐예요?" } },
        { zh: "大概", pinyin: "dà gài", ko: "대략, 대강; 대강의 내용", pos: "부사", hanja: "대개(大概) — '大'는 큰 대, '概'는 대개 개.", ex: { zh: "他大概三十岁。", pinyin: "tā dàgài sānshí suì", ko: "그는 대략 서른 살이에요." } },
        { zh: "大使馆", pinyin: "dà shǐ guǎn", ko: "대사관", pos: "명사", hanja: "대사관(大使館) — '使'는 사신 사, '館'은 집 관.", ex: { zh: "我去大使馆办签证。", pinyin: "wǒ qù dàshǐguǎn bàn qiānzhèng", ko: "저는 비자를 만들러 대사관에 가요." } },
        { zh: "代表", pinyin: "dài biǎo", ko: "대표; 대표하다, 대신하다", pos: "명사", hanja: "대표(代表) — '代'는 대신할 대, '表'는 겉 표.", ex: { zh: "他是我们班的代表。", pinyin: "tā shì wǒmen bān de dàibiǎo", ko: "그는 우리 반 대표예요." } },
        { zh: "导游", pinyin: "dǎo yóu", ko: "가이드, 관광 안내원", pos: "명사", hanja: "도유(導遊) — '導'는 이끌 도, '遊'는 놀 유.", ex: { zh: "导游给我们介绍了这座城市。", pinyin: "dǎoyóu gěi wǒmen jièshào le zhè zuò chéngshì", ko: "가이드가 우리에게 이 도시를 소개해 줬어요." } },
        { zh: "地球", pinyin: "dì qiú", ko: "지구", pos: "명사", hanja: "지구(地球) — '地'는 땅 지, '球'는 공 구.", ex: { zh: "我们要保护地球。", pinyin: "wǒmen yào bǎohù dìqiú", ko: "우리는 지구를 보호해야 해요." } },
        { zh: "地址", pinyin: "dì zhǐ", ko: "주소", pos: "명사", hanja: "지지(地址) — '地'는 땅 지, '址'는 터 지.", ex: { zh: "请告诉我你的地址。", pinyin: "qǐng gàosu wǒ nǐ de dìzhǐ", ko: "당신 주소를 알려 주세요." } },
        { zh: "动作", pinyin: "dòng zuò", ko: "동작, 움직임", pos: "명사", hanja: "동작(動作) — '動'은 움직일 동, '作'은 지을 작.", ex: { zh: "这个动作有点难。", pinyin: "zhège dòngzuò yǒudiǎn nán", ko: "이 동작은 좀 어려워요." } },
        { zh: "肚子", pinyin: "dù zi", ko: "배, 복부", pos: "명사", hanja: "두자(肚子) — '肚'는 배 두.", ex: { zh: "我肚子有点疼。", pinyin: "wǒ dùzi yǒudiǎn téng", ko: "저는 배가 좀 아파요." } },
        { zh: "对面", pinyin: "duì miàn", ko: "맞은편, 건너편", pos: "명사", hanja: "대면(對面) — '對'는 마주할 대, '面'은 낯 면.", ex: { zh: "银行在书店对面。", pinyin: "yínháng zài shūdiàn duìmiàn", ko: "은행은 서점 맞은편에 있어요." } },
        { zh: "儿童", pinyin: "ér tóng", ko: "어린이, 아동", pos: "명사", hanja: "아동(兒童) — '兒'는 아이 아, '童'은 아이 동.", ex: { zh: "这本书是给儿童看的。", pinyin: "zhè běn shū shì gěi értóng kàn de", ko: "이 책은 어린이가 보는 거예요." } },
        { zh: "烦恼", pinyin: "fán nǎo", ko: "고민, 걱정; 괴롭다, 답답하다", pos: "명사", hanja: "번뇌(煩惱) — '煩'은 번거로울 번, '惱'는 괴로워할 뇌.", ex: { zh: "每个人都有烦恼。", pinyin: "měi ge rén dōu yǒu fánnǎo", ko: "누구나 고민이 있어요." } },
        { zh: "方法", pinyin: "fāng fǎ", ko: "방법, 방식", pos: "명사", hanja: "방법(方法) — '方'은 모 방, '法'은 법 법.", ex: { zh: "这个学习方法很有用。", pinyin: "zhège xuéxí fāngfǎ hěn yǒuyòng", ko: "이 공부 방법은 아주 유용해요." } },
        { zh: "方面", pinyin: "fāng miàn", ko: "방면, 측면, 분야", pos: "명사", hanja: "방면(方面) — '方'은 모 방, '面'은 낯·면 면.", ex: { zh: "他在很多方面都很优秀。", pinyin: "tā zài hěn duō fāngmiàn dōu hěn yōuxiù", ko: "그는 여러 방면에서 다 뛰어나요." } },
        { zh: "方向", pinyin: "fāng xiàng", ko: "방향", pos: "명사", hanja: "방향(方向) — '方'은 모 방, '向'은 향할 향.", ex: { zh: "我们走错方向了。", pinyin: "wǒmen zǒucuò fāngxiàng le", ko: "우리는 방향을 잘못 들었어요." } },
        { zh: "风景", pinyin: "fēng jǐng", ko: "풍경, 경치", pos: "명사", hanja: "풍경(風景) — '風'은 바람 풍, '景'은 볕 경.", ex: { zh: "这里的风景真美。", pinyin: "zhèlǐ de fēngjǐng zhēn měi", ko: "여기 경치가 정말 아름다워요." } },
        { zh: "父亲", pinyin: "fù qīn", ko: "아버지, 부친", pos: "명사", hanja: "부친(父親) — '父'는 아비 부, '親'은 친할 친.", ex: { zh: "他的父亲是老师。", pinyin: "tā de fùqīn shì lǎoshī", ko: "그의 아버지는 선생님이에요." } },
        { zh: "感情", pinyin: "gǎn qíng", ko: "감정, 정, 정서", pos: "명사", hanja: "감정(感情) — '感'은 느낄 감, '情'은 뜻 정.", ex: { zh: "他们的感情很好。", pinyin: "tāmen de gǎnqíng hěn hǎo", ko: "그들은 사이가(정이) 아주 좋아요." } },
        { zh: "个子", pinyin: "gè zi", ko: "키, 체격", pos: "명사", ex: { zh: "他的个子很高。", pinyin: "tā de gèzi hěn gāo", ko: "그는 키가 커요." } },
        { zh: "工具", pinyin: "gōng jù", ko: "도구, 공구, 수단", pos: "명사", hanja: "공구(工具) — '工'은 장인 공, '具'는 갖출 구.", ex: { zh: "电脑是很好的学习工具。", pinyin: "diànnǎo shì hěn hǎo de xuéxí gōngjù", ko: "컴퓨터는 아주 좋은 학습 도구예요." } },
        { zh: "广告", pinyin: "guǎng gào", ko: "광고", pos: "명사", hanja: "광고(廣告) — '廣'은 넓을 광, '告'은 알릴 고.", ex: { zh: "电视上有很多广告。", pinyin: "diànshì shang yǒu hěn duō guǎnggào", ko: "TV에는 광고가 많아요." } },
        { zh: "观众", pinyin: "guān zhòng", ko: "관중, 관객, 시청자", pos: "명사", hanja: "관중(觀衆) — '觀'은 볼 관, '衆'은 무리 중.", ex: { zh: "观众都很喜欢这部电影。", pinyin: "guānzhòng dōu hěn xǐhuan zhè bù diànyǐng", ko: "관객들은 모두 이 영화를 좋아해요." } },
        { zh: "过程", pinyin: "guò chéng", ko: "과정", pos: "명사", hanja: "과정(過程) — '過'는 지날 과, '程'은 한도·길 정.", ex: { zh: "学习是一个长期的过程。", pinyin: "xuéxí shì yí ge chángqī de guòchéng", ko: "공부는 오랜 과정이에요." } },
        { zh: "关键", pinyin: "guān jiàn", ko: "관건, 핵심; 결정적인", pos: "명사", hanja: "관건(關鍵) — '關'은 빗장 관, '鍵'은 열쇠 건.", ex: { zh: "这是问题的关键。", pinyin: "zhè shì wèntí de guānjiàn", ko: "이게 문제의 핵심이에요." } },
        { zh: "海洋", pinyin: "hǎi yáng", ko: "바다, 해양", pos: "명사", hanja: "해양(海洋) — '海'는 바다 해, '洋'은 큰바다 양.", ex: { zh: "海洋里有很多动物。", pinyin: "hǎiyáng lǐ yǒu hěn duō dòngwù", ko: "바다에는 동물이 많아요." } },
        { zh: "汗", pinyin: "hàn", ko: "땀", pos: "명사", hanja: "한(汗) — '땀 한'.", ex: { zh: "他跑得满头大汗。", pinyin: "tā pǎo de mǎn tóu dà hàn", ko: "그는 달려서 땀을 뻘뻘 흘렸어요." } },
        { zh: "好处", pinyin: "hǎo chù", ko: "좋은 점, 이점, 장점", pos: "명사", hanja: "호처(好處) — '好'는 좋을 호, '處'는 곳 처. '나쁜 점(坏处)'의 반대.", ex: { zh: "多运动有很多好处。", pinyin: "duō yùndòng yǒu hěn duō hǎochù", ko: "운동을 많이 하면 좋은 점이 많아요." } },
        { zh: "号码", pinyin: "hào mǎ", ko: "번호", pos: "명사", hanja: "호마(號碼) — '號'는 부르짖을·번호 호, '碼'는 마노·숫자 마.", ex: { zh: "请告诉我你的电话号码。", pinyin: "qǐng gàosu wǒ nǐ de diànhuà hàomǎ", ko: "당신 전화번호를 알려 주세요." } },
        { zh: "盒子", pinyin: "hé zi", ko: "상자, 곽, 케이스", pos: "명사", hanja: "합자(盒子) — '盒'은 합 합.", ex: { zh: "桌子上有一个盒子。", pinyin: "zhuōzi shang yǒu yí ge hézi", ko: "탁자 위에 상자가 하나 있어요." } },
        { zh: "猴子", pinyin: "hóu zi", ko: "원숭이", pos: "명사", hanja: "후자(猴子) — '猴'는 원숭이 후.", ex: { zh: "动物园里有很多猴子。", pinyin: "dòngwùyuán lǐ yǒu hěn duō hóuzi", ko: "동물원에 원숭이가 많아요." } },
        { zh: "护士", pinyin: "hù shi", ko: "간호사", pos: "명사", hanja: "호사(護士) — '護'는 보호할 호, '士'는 선비 사.", ex: { zh: "护士给病人打针。", pinyin: "hùshi gěi bìngrén dǎzhēn", ko: "간호사가 환자에게 주사를 놓아요." } },
        { zh: "活动", pinyin: "huó dòng", ko: "활동, 행사; 활동하다", pos: "명사", hanja: "활동(活動) — '活'은 살 활, '動'은 움직일 동.", ex: { zh: "学校组织了很多活动。", pinyin: "xuéxiào zǔzhī le hěn duō huódòng", ko: "학교는 여러 행사를 마련했어요." } },
        { zh: "基础", pinyin: "jī chǔ", ko: "기초, 토대, 바탕", pos: "명사", hanja: "기초(基礎) — '基'는 터 기, '礎'는 주춧돌 초.", ex: { zh: "学好基础很重要。", pinyin: "xuéhǎo jīchǔ hěn zhòngyào", ko: "기초를 잘 익히는 게 중요해요." } },
        { zh: "记者", pinyin: "jì zhě", ko: "기자", pos: "명사", hanja: "기자(記者) — '記'는 기록할 기, '者'는 사람 자.", ex: { zh: "他是一名记者。", pinyin: "tā shì yì míng jìzhě", ko: "그는 기자예요." } },
        { zh: "技术", pinyin: "jì shù", ko: "기술", pos: "명사", hanja: "기술(技術) — '技'는 재주 기, '術'은 꾀 술.", ex: { zh: "这家公司的技术很先进。", pinyin: "zhè jiā gōngsī de jìshù hěn xiānjìn", ko: "이 회사의 기술은 아주 앞서 있어요." } },
        { zh: "笔记本", pinyin: "bǐ jì běn", ko: "공책, 노트; 노트북(컴퓨터)", pos: "명사", hanja: "필기본(筆記本) — '筆'은 붓 필, '記'는 기록할 기, '本'은 책 본.", ex: { zh: "我买了一个新笔记本。", pinyin: "wǒ mǎi le yí ge xīn bǐjìběn", ko: "저는 새 공책을 하나 샀어요." } },
        { zh: "公里", pinyin: "gōng lǐ", ko: "킬로미터(km)", pos: "명사", hanja: "공리(公里) — '里'는 마을·거리 단위 리.", ex: { zh: "这里离学校有五公里。", pinyin: "zhèlǐ lí xuéxiào yǒu wǔ gōnglǐ", ko: "여기서 학교까지 5km 떨어져 있어요." } },
        { zh: "大夫", pinyin: "dài fu", ko: "의사 (구어체)", pos: "명사", hanja: "대부(大夫) — 한자는 옛 벼슬 이름이지만, 회화에서는 '의사'를 뜻해요. 'dà fū'가 아니라 'dài fu'로 읽어요.", ex: { zh: "你最好去看看大夫。", pinyin: "nǐ zuìhǎo qù kànkan dàifu", ko: "당신 의사한테 한번 가 보는 게 좋겠어요." } },
        { zh: "火", pinyin: "huǒ", ko: "불", pos: "명사", hanja: "화(火) — '불 화'. 성씨가 아니라 일반 명사 '불'.", ex: { zh: "厨房里着火了！", pinyin: "chúfáng lǐ zháohuǒ le", ko: "주방에 불이 났어요!" } },
        { zh: "底", pinyin: "dǐ", ko: "밑, 바닥; (월·연) 말", pos: "명사", hanja: "저(底) — '밑 저'. (조사 'de'가 아니라 명사 '밑·바닥'의 dǐ)", ex: { zh: "杯子底有点脏。", pinyin: "bēizi dǐ yǒudiǎn zāng", ko: "컵 바닥이 좀 더러워요." } },
        { zh: "富", pinyin: "fù", ko: "부유하다, 풍부하다", pos: "형용사", hanja: "부(富) — '부유할 부'. 성씨가 아니라 '부유하다' 형용사.", ex: { zh: "他家很富。", pinyin: "tā jiā hěn fù", ko: "그의 집은 아주 부유해요." } },
      ],
    },
    {
      name: "HSK4 보강 — 형용사·상태",
      icon: "🔶",
      words: [
        { zh: "安全", pinyin: "ān quán", ko: "안전하다; 안전", pos: "형용사", hanja: "안전(安全) — '安'은 편안할 안, '全'은 온전할 전.", ex: { zh: "晚上一个人走路不安全。", pinyin: "wǎnshang yí ge rén zǒulù bù ānquán", ko: "밤에 혼자 다니는 건 안전하지 않아요." } },
        { zh: "暗", pinyin: "àn", ko: "어둡다, 캄캄하다", pos: "형용사", hanja: "암(暗) — '어두울 암'.", ex: { zh: "房间里有点暗。", pinyin: "fángjiān lǐ yǒudiǎn àn", ko: "방 안이 좀 어두워요." } },
        { zh: "抱歉", pinyin: "bào qiàn", ko: "미안하다, 죄송하다", pos: "형용사", hanja: "포겸(抱歉) — '抱'는 안을 포, '歉'은 미안할 겸.", ex: { zh: "很抱歉，我来晚了。", pinyin: "hěn bàoqiàn, wǒ lái wǎn le", ko: "정말 죄송해요, 늦었네요." } },
        { zh: "笨", pinyin: "bèn", ko: "멍청하다, 어리석다, 둔하다", pos: "형용사", ex: { zh: "我太笨了，又做错了。", pinyin: "wǒ tài bèn le, yòu zuòcuò le", ko: "제가 너무 멍청해서 또 틀렸어요." } },
        { zh: "吃惊", pinyin: "chī jīng", ko: "놀라다, 깜짝 놀라다", pos: "형용사", hanja: "끽경(吃驚) — '驚'은 놀랄 경. '놀라움을 먹다' → 놀라다.", ex: { zh: "听到这个消息我很吃惊。", pinyin: "tīngdào zhège xiāoxi wǒ hěn chījīng", ko: "이 소식을 듣고 저는 깜짝 놀랐어요." } },
        { zh: "得意", pinyin: "dé yì", ko: "득의양양하다, 우쭐하다, 만족스러워하다", pos: "형용사", hanja: "득의(得意) — '得'은 얻을 득, '意'는 뜻 의.", ex: { zh: "他考了第一，很得意。", pinyin: "tā kǎo le dì-yī, hěn déyì", ko: "그는 1등을 해서 우쭐해해요." } },
        { zh: "干燥", pinyin: "gān zào", ko: "건조하다, 메마르다", pos: "형용사", hanja: "건조(乾燥) — '乾'은 마를 건, '燥'는 마를 조.", ex: { zh: "冬天空气很干燥。", pinyin: "dōngtiān kōngqì hěn gānzào", ko: "겨울에는 공기가 건조해요." } },
        { zh: "高级", pinyin: "gāo jí", ko: "고급의, 상급의, 수준 높은", pos: "형용사", hanja: "고급(高級) — '高'는 높을 고, '級'은 등급 급.", ex: { zh: "这是一家高级饭店。", pinyin: "zhè shì yì jiā gāojí fàndiàn", ko: "여기는 고급 호텔이에요." } },
        { zh: "害羞", pinyin: "hài xiū", ko: "수줍어하다, 부끄러워하다", pos: "형용사", hanja: "해수(害羞) — '害'는 해할 해, '羞'는 부끄러울 수.", ex: { zh: "她见到陌生人就害羞。", pinyin: "tā jiàndào mòshēngrén jiù hàixiū", ko: "그녀는 낯선 사람을 보면 수줍어해요." } },
        { zh: "合适", pinyin: "hé shì", ko: "알맞다, 적합하다, 어울리다", pos: "형용사", hanja: "합적(合適) — '合'은 합할 합, '適'은 맞을 적.", ex: { zh: "这件衣服很合适你。", pinyin: "zhè jiàn yīfu hěn héshì nǐ", ko: "이 옷은 당신한테 잘 어울려요." } },
        { zh: "厚", pinyin: "hòu", ko: "두껍다, 두텁다", pos: "형용사", hanja: "후(厚) — '두터울 후'.", ex: { zh: "这本书很厚。", pinyin: "zhè běn shū hěn hòu", ko: "이 책은 아주 두꺼워요." } },
        { zh: "积极", pinyin: "jī jí", ko: "적극적이다, 긍정적이다, 의욕적이다", pos: "형용사", hanja: "적극(積極) — '積'은 쌓을 적, '極'은 다할 극.", ex: { zh: "他学习很积极。", pinyin: "tā xuéxí hěn jījí", ko: "그는 공부를 아주 적극적으로 해요." } },
      ],
    },
    {
      name: "HSK4 보강 — 부사·기타",
      icon: "🔶",
      words: [
        { zh: "按时", pinyin: "àn shí", ko: "제때에, 정해진 시간에", pos: "부사", hanja: "안시(按時) — '按'은 누를·따를 안, '時'는 때 시.", ex: { zh: "请按时吃药。", pinyin: "qǐng ànshí chī yào", ko: "약을 제때에 드세요." } },
        { zh: "按照", pinyin: "àn zhào", ko: "~에 따라, ~대로", pos: "개사", hanja: "안조(按照) — '按'은 따를 안, '照'는 비출 조.", ex: { zh: "请按照说明书操作。", pinyin: "qǐng ànzhào shuōmíngshū cāozuò", ko: "설명서대로 조작해 주세요." } },
        { zh: "倍", pinyin: "bèi", ko: "배(倍), 곱절", pos: "양사", hanja: "배(倍) — '곱 배'.", ex: { zh: "今年的收入是去年的两倍。", pinyin: "jīnnián de shōurù shì qùnián de liǎng bèi", ko: "올해 수입은 작년의 두 배예요." } },
        { zh: "本来", pinyin: "běn lái", ko: "본래, 원래", pos: "부사", hanja: "본래(本來) — '本'은 근본 본, '來'는 올 래.", ex: { zh: "我本来想去，但是太忙了。", pinyin: "wǒ běnlái xiǎng qù, dànshì tài máng le", ko: "원래는 가려고 했는데 너무 바빴어요." } },
        { zh: "遍", pinyin: "biàn", ko: "번, 회(동작의 전 과정을 세는 양사)", pos: "양사", hanja: "편(遍) — '두루 편'. 처음부터 끝까지 한 차례.", ex: { zh: "这本书我看了三遍。", pinyin: "zhè běn shū wǒ kàn le sān biàn", ko: "이 책을 저는 세 번 읽었어요." } },
        { zh: "并且", pinyin: "bìng qiě", ko: "게다가, 또한, 그리고", pos: "접속사", hanja: "병차(並且) — '並'은 아우를 병, '且'는 또 차.", ex: { zh: "他聪明并且努力。", pinyin: "tā cōngmíng bìngqiě nǔlì", ko: "그는 똑똑하고 게다가 노력도 해요." } },
        { zh: "不但", pinyin: "bù dàn", ko: "~뿐만 아니라 (不但 A 而且 B)", pos: "접속사", hanja: "부단(不但) — '但'은 다만 단. 뒤에 而且와 호응.", ex: { zh: "他不但会说英语，而且会说法语。", pinyin: "tā búdàn huì shuō Yīngyǔ, érqiě huì shuō Fǎyǔ", ko: "그는 영어뿐만 아니라 프랑스어도 할 줄 알아요." } },
        { zh: "不得不", pinyin: "bù dé bù", ko: "어쩔 수 없이 ~하다, ~하지 않을 수 없다", pos: "부사", hanja: "부득불(不得不) — '얻지 못해 ~하지 않을 수 없다'.", ex: { zh: "下雨了，我们不得不回家。", pinyin: "xià yǔ le, wǒmen bùdébù huíjiā", ko: "비가 와서 우리는 어쩔 수 없이 집에 갔어요." } },
        { zh: "不管", pinyin: "bù guǎn", ko: "~에 관계없이, ~든지 간에", pos: "접속사", hanja: "불관(不管) — '管'은 맡을·상관할 관. '상관하지 않고'.", ex: { zh: "不管多忙，他都会锻炼。", pinyin: "bùguǎn duō máng, tā dōu huì duànliàn", ko: "아무리 바빠도 그는 운동을 해요." } },
        { zh: "不过", pinyin: "bù guò", ko: "그런데, 다만; ~에 불과하다", pos: "접속사", hanja: "불과(不過) — '過'는 지날 과. '지나치지 않다' → 다만.", ex: { zh: "这个不错，不过有点贵。", pinyin: "zhège búcuò, búguò yǒudiǎn guì", ko: "이거 괜찮은데, 다만 좀 비싸요." } },
        { zh: "部分", pinyin: "bù fen", ko: "부분, 일부", pos: "명사", hanja: "부분(部分) — '部'는 떼 부, '分'은 나눌 분.", ex: { zh: "这是考试的一部分。", pinyin: "zhè shì kǎoshì de yí bùfen", ko: "이건 시험의 일부예요." } },
        { zh: "差不多", pinyin: "chà bu duō", ko: "거의, 비슷하다, 큰 차이 없다", pos: "부사", hanja: "차부다(差不多) — '差(chà)'는 차이·모자랄 차. '差不多=거의'. chā로 읽지 않아요.", ex: { zh: "我们差不多到了。", pinyin: "wǒmen chàbuduō dào le", ko: "우리 거의 다 왔어요." } },
        { zh: "场", pinyin: "chǎng", ko: "번, 차례(공연·경기·일 등을 세는 양사)", pos: "양사", hanja: "장(場) — '마당 장'. 경기·공연 등을 세요. (장소 뜻일 땐 chǎng)", ex: { zh: "我们看了一场电影。", pinyin: "wǒmen kàn le yì chǎng diànyǐng", ko: "우리는 영화 한 편을 봤어요." } },
        { zh: "从来", pinyin: "cóng lái", ko: "지금까지, 여태껏(주로 부정문에)", pos: "부사", hanja: "종래(從來) — '從'은 좇을 종, '來'는 올 래.", ex: { zh: "我从来没去过中国。", pinyin: "wǒ cónglái méi qùguo Zhōngguó", ko: "저는 여태껏 중국에 가 본 적이 없어요." } },
        { zh: "当地", pinyin: "dāng dì", ko: "현지, 그 지방, 그 고장", pos: "명사", hanja: "당지(當地) — '當'은 마땅·그 당, '地'는 땅 지. '그 지역'.", ex: { zh: "我们尝了当地的美食。", pinyin: "wǒmen cháng le dāngdì de měishí", ko: "우리는 현지 음식을 맛봤어요." } },
        { zh: "当时", pinyin: "dāng shí", ko: "당시, 그때", pos: "명사", hanja: "당시(當時) — '當'은 그 당, '時'는 때 시.", ex: { zh: "当时我还很小。", pinyin: "dāngshí wǒ hái hěn xiǎo", ko: "당시 저는 아직 어렸어요." } },
        { zh: "刀", pinyin: "dāo", ko: "칼", pos: "명사", hanja: "도(刀) — '칼 도'. 성씨가 아니라 일반 명사 '칼'.", ex: { zh: "这把刀很快。", pinyin: "zhè bǎ dāo hěn kuài", ko: "이 칼은 아주 잘 들어요." } },
        { zh: "到处", pinyin: "dào chù", ko: "도처에, 곳곳에, 여기저기", pos: "부사", hanja: "도처(到處) — '到'는 이를 도, '處'는 곳 처.", ex: { zh: "公园里到处是花。", pinyin: "gōngyuán lǐ dàochù shì huā", ko: "공원 곳곳이 꽃이에요." } },
        { zh: "到底", pinyin: "dào dǐ", ko: "도대체; 끝까지", pos: "부사", hanja: "도저(到底) — '底'는 밑 저. '바닥까지 이르러' → 도대체.", ex: { zh: "你到底想说什么？", pinyin: "nǐ dàodǐ xiǎng shuō shénme", ko: "당신은 도대체 무슨 말이 하고 싶어요?" } },
        { zh: "而", pinyin: "ér", ko: "그리고, 그러나(앞뒤를 잇는 접속사)", pos: "접속사", hanja: "이(而) — '말 이을 이'.", ex: { zh: "这件事简单而重要。", pinyin: "zhè jiàn shì jiǎndān ér zhòngyào", ko: "이 일은 간단하면서도 중요해요." } },
        { zh: "否则", pinyin: "fǒu zé", ko: "그렇지 않으면", pos: "접속사", hanja: "부즉(否則) — '否'는 아닐 부, '則'은 곧 즉.", ex: { zh: "快点走，否则会迟到。", pinyin: "kuài diǎn zǒu, fǒuzé huì chídào", ko: "빨리 가요, 안 그러면 지각해요." } },
        { zh: "份", pinyin: "fèn", ko: "부, 인분, 몫(을 세는 양사)", pos: "양사", hanja: "분(份) — 신문·서류·세트 등을 세는 양사.", ex: { zh: "我点了两份饭。", pinyin: "wǒ diǎn le liǎng fèn fàn", ko: "저는 밥 2인분을 시켰어요." } },
        { zh: "顿", pinyin: "dùn", ko: "끼(니), 차례, 바탕(식사·꾸지람 등을 세는 양사)", pos: "양사", hanja: "돈(頓) — 식사·질책 등을 세요. 예: 一顿饭(한 끼).", ex: { zh: "我们一起吃了一顿饭。", pinyin: "wǒmen yìqǐ chī le yí dùn fàn", ko: "우리는 함께 밥 한 끼를 먹었어요." } },
        { zh: "朵", pinyin: "duǒ", ko: "송이(꽃·구름을 세는 양사)", pos: "양사", ex: { zh: "她买了一朵花。", pinyin: "tā mǎi le yì duǒ huā", ko: "그녀는 꽃 한 송이를 샀어요." } },
        { zh: "刚刚", pinyin: "gāng gāng", ko: "방금, 막, 이제 막", pos: "부사", hanja: "강강(剛剛) — '剛'은 굳셀·막 강.", ex: { zh: "他刚刚出去了。", pinyin: "tā gānggāng chūqù le", ko: "그는 방금 나갔어요." } },
        { zh: "各", pinyin: "gè", ko: "각각, 각자, 여러", pos: "대명사", hanja: "각(各) — '각각 각'.", ex: { zh: "各国的文化都不同。", pinyin: "gè guó de wénhuà dōu bù tóng", ko: "각 나라의 문화는 다 달라요." } },
        { zh: "共同", pinyin: "gòng tóng", ko: "공동의, 함께; 공통적인", pos: "부사", hanja: "공동(共同) — '共'은 함께 공, '同'은 같을 동.", ex: { zh: "这是我们共同的目标。", pinyin: "zhè shì wǒmen gòngtóng de mùbiāo", ko: "이건 우리 공동의 목표예요." } },
        { zh: "够", pinyin: "gòu", ko: "충분하다, 넉넉하다; 충분히", pos: "동사", ex: { zh: "这些钱够了吗？", pinyin: "zhèxiē qián gòu le ma", ko: "이 돈으로 충분한가요?" } },
        { zh: "故意", pinyin: "gù yì", ko: "고의로, 일부러", pos: "부사", hanja: "고의(故意) — '故'는 연고 고, '意'는 뜻 의.", ex: { zh: "他不是故意的。", pinyin: "tā bú shì gùyì de", ko: "그는 일부러 그런 게 아니에요." } },
        { zh: "光", pinyin: "guāng", ko: "빛; 오직, 단지; 다 써 버리다", pos: "명사", hanja: "광(光) — '빛 광'. 부사로는 '오직·~만'.", ex: { zh: "光说不做没有用。", pinyin: "guāng shuō bú zuò méiyǒu yòng", ko: "말만 하고 안 하면 소용없어요." } },
        { zh: "果然", pinyin: "guǒ rán", ko: "과연, 역시, 아니나 다를까", pos: "부사", hanja: "과연(果然) — '果'는 열매·과연 과, '然'은 그러할 연.", ex: { zh: "他果然来了。", pinyin: "tā guǒrán lái le", ko: "그가 과연 왔어요." } },
        { zh: "大约", pinyin: "dà yuē", ko: "대략, 대개, 아마", pos: "부사", hanja: "대약(大約) — '大'는 큰 대, '約'은 맺을·대략 약.", ex: { zh: "从这儿到学校大约十分钟。", pinyin: "cóng zhèr dào xuéxiào dàyuē shí fēnzhōng", ko: "여기서 학교까지 대략 10분이에요." } },
        { zh: "好像", pinyin: "hǎo xiàng", ko: "마치 ~인 것 같다, ~인 듯하다", pos: "부사", hanja: "호상(好像) — '像'은 닮을 상. '~인 것처럼'.", ex: { zh: "天好像要下雨了。", pinyin: "tiān hǎoxiàng yào xià yǔ le", ko: "비가 올 것 같아요." } },
        { zh: "后来", pinyin: "hòu lái", ko: "그 후, 나중에, 이후", pos: "명사", hanja: "후래(後來) — '後'는 뒤 후, '來'는 올 래. 과거 시점 이후.", ex: { zh: "后来我们成了好朋友。", pinyin: "hòulái wǒmen chéng le hǎo péngyou", ko: "그 후에 우리는 좋은 친구가 됐어요." } },
        { zh: "互相", pinyin: "hù xiāng", ko: "서로, 상호", pos: "부사", hanja: "호상(互相) — '互'는 서로 호, '相'은 서로 상.", ex: { zh: "我们应该互相帮助。", pinyin: "wǒmen yīnggāi hùxiāng bāngzhù", ko: "우리는 서로 도와야 해요." } },
        { zh: "极其", pinyin: "jí qí", ko: "지극히, 극히, 대단히", pos: "부사", hanja: "극기(極其) — '極'은 다할 극. '극도로'.", ex: { zh: "这件事极其重要。", pinyin: "zhè jiàn shì jíqí zhòngyào", ko: "이 일은 지극히 중요해요." } },
        { zh: "及时", pinyin: "jí shí", ko: "제때에, 적시에, 때맞춰", pos: "부사", hanja: "급시(及時) — '及'은 미칠 급, '時'는 때 시.", ex: { zh: "你来得很及时。", pinyin: "nǐ lái de hěn jíshí", ko: "당신 마침 딱 맞게 왔어요." } },
        { zh: "即使", pinyin: "jí shǐ", ko: "설령 ~일지라도, 비록 ~해도", pos: "접속사", hanja: "즉사(即使) — 뒤에 也와 호응해요.", ex: { zh: "即使下雨，我也要去。", pinyin: "jíshǐ xià yǔ, wǒ yě yào qù", ko: "설령 비가 와도 저는 갈 거예요." } },
        { zh: "分之", pinyin: "fēn zhī", ko: "분의(분수를 나타냄, 예: 三分之一=3분의 1)", pos: "조사", hanja: "분지(分之) — '몇 分之 몇' 꼴로 분수를 표현해요.", ex: { zh: "三分之一的人同意。", pinyin: "sān fēn zhī yī de rén tóngyì", ko: "3분의 1의 사람이 동의해요." } },
        { zh: "咳嗽", pinyin: "ké sou", ko: "기침하다; 기침", pos: "동사", hanja: "해수(咳嗽) — '咳'는 기침 해, '嗽'는 기침할 수.", ex: { zh: "我咳嗽得很厉害。", pinyin: "wǒ késou de hěn lìhai", ko: "저는 기침이 심해요." } },
        { zh: "寒假", pinyin: "hán jià", ko: "겨울방학", pos: "명사", hanja: "한가(寒假) — '寒'은 찰 한, '假'는 휴가·방학 가.", ex: { zh: "寒假我要回老家。", pinyin: "hánjià wǒ yào huí lǎojiā", ko: "겨울방학에 저는 고향에 갈 거예요." } },
        { zh: "毕业", pinyin: "bì yè", ko: "졸업하다; 졸업", pos: "동사", hanja: "필업(畢業) — '畢'은 마칠 필, '業'은 업 업.", ex: { zh: "他去年大学毕业了。", pinyin: "tā qùnián dàxué bìyè le", ko: "그는 작년에 대학을 졸업했어요." } },
      ],
    },
  ],
};

export default themes;
