/**
 * H4 (HSK 4급) 보강 어휘 — 청크 C.
 * 표준 HSK4 단어 목록 중 본편에 없던 161개를 품사·의미별 4개 테마로 보충.
 * pinyin은 원본 표기를 보존하되, 성씨·이체자·다음자 오독은 실제 HSK 의미의 표준 병음으로 교정했어요.
 */
const themes = {
  themes: [
    {
      name: "HSK4 보강 — 동사",
      icon: "🔶",
      words: [
        { zh: "死", pinyin: "sǐ", ko: "죽다; 죽을 듯이, 몹시", pos: "동사", hanja: "사(死) — '죽을 사'.", ex: { zh: "我累死了。", pinyin: "wǒ lèi sǐ le", ko: "저 피곤해 죽겠어요." } },
        { zh: "算", pinyin: "suàn", ko: "계산하다; ~인 셈이다, 치다", pos: "동사", hanja: "산(算) — '셈할 산'. '계산(計算)'의 산.", ex: { zh: "你算一下一共多少钱。", pinyin: "nǐ suàn yíxià yígòng duōshao qián", ko: "전부 얼마인지 계산해 보세요." } },
        { zh: "抬", pinyin: "tái", ko: "(들어) 올리다, 함께 들다", pos: "동사", hanja: "대(抬) — '들 대'.", ex: { zh: "我们一起抬这张桌子。", pinyin: "wǒmen yìqǐ tái zhè zhāng zhuōzi", ko: "우리 같이 이 탁자를 들어요." } },
        { zh: "躺", pinyin: "tǎng", ko: "눕다, 드러눕다", pos: "동사", ex: { zh: "他躺在床上看书。", pinyin: "tā tǎng zài chuáng shang kàn shū", ko: "그는 침대에 누워 책을 봐요." } },
        { zh: "提供", pinyin: "tígōng", ko: "제공하다", pos: "동사", hanja: "제공(提供) — 한자 그대로.", ex: { zh: "这家公司提供工作机会。", pinyin: "zhè jiā gōngsī tígōng gōngzuò jīhuì", ko: "이 회사는 일자리를 제공해요." } },
        { zh: "提前", pinyin: "tíqián", ko: "앞당기다, 미리 ~하다", pos: "동사", hanja: "제전(提前) — '미리·앞당김'을 뜻해요.", ex: { zh: "我们提前到了机场。", pinyin: "wǒmen tíqián dào le jīchǎng", ko: "우리는 공항에 미리 도착했어요." } },
        { zh: "提醒", pinyin: "tíxǐng", ko: "일깨우다, 상기시키다", pos: "동사", hanja: "제성(提醒) — '醒'은 깰 성. '주의를 환기하다'.", ex: { zh: "谢谢你提醒我。", pinyin: "xièxie nǐ tíxǐng wǒ", ko: "일깨워 줘서 고마워요." } },
        { zh: "填空", pinyin: "tiánkòng", ko: "빈칸을 채우다", pos: "동사", hanja: "전공(填空) — '填'은 채울 전, '空'은 빌 공.", ex: { zh: "请在这里填空。", pinyin: "qǐng zài zhèlǐ tiánkòng", ko: "여기 빈칸을 채워 주세요." } },
        { zh: "停止", pinyin: "tíngzhǐ", ko: "멈추다, 정지하다, 그치다", pos: "동사", hanja: "정지(停止) — 한자 그대로.", ex: { zh: "雨已经停止了。", pinyin: "yǔ yǐjīng tíngzhǐ le", ko: "비가 이미 그쳤어요." } },
        { zh: "通过", pinyin: "tōngguò", ko: "통과하다; ~를 통해", pos: "동사", hanja: "통과(通過) — 한자 그대로. '~을 거쳐서'의 뜻도 있어요.", ex: { zh: "他通过了考试。", pinyin: "tā tōngguò le kǎoshì", ko: "그는 시험에 통과했어요." } },
        { zh: "通知", pinyin: "tōngzhī", ko: "통지하다, 알리다; 통지", pos: "동사", hanja: "통지(通知) — 한자 그대로.", ex: { zh: "老师通知我们明天考试。", pinyin: "lǎoshī tōngzhī wǒmen míngtiān kǎoshì", ko: "선생님이 내일 시험이라고 알려 줬어요." } },
        { zh: "同情", pinyin: "tóngqíng", ko: "동정하다; 동정", pos: "동사", hanja: "동정(同情) — 한자 그대로.", ex: { zh: "大家都很同情他。", pinyin: "dàjiā dōu hěn tóngqíng tā", ko: "모두가 그를 안타까워해요." } },
        { zh: "推", pinyin: "tuī", ko: "밀다; 미루다, 거절하다", pos: "동사", hanja: "추(推) — '밀 추'.", ex: { zh: "请把门推开。", pinyin: "qǐng bǎ mén tuī kāi", ko: "문을 밀어서 열어 주세요." } },
        { zh: "推迟", pinyin: "tuīchí", ko: "미루다, 연기하다", pos: "동사", hanja: "추지(推遲) — '遲'는 늦을 지. '뒤로 미루다'.", ex: { zh: "会议推迟到下周了。", pinyin: "huìyì tuīchí dào xiàzhōu le", ko: "회의가 다음 주로 미뤄졌어요." } },
        { zh: "脱", pinyin: "tuō", ko: "벗다; 벗어나다", pos: "동사", hanja: "탈(脫) — '벗을 탈'. '탈출(脫出)'의 탈.", ex: { zh: "进门请脱鞋。", pinyin: "jìn mén qǐng tuō xié", ko: "들어올 때 신발을 벗어 주세요." } },
        { zh: "握手", pinyin: "wòshǒu", ko: "악수하다", pos: "동사", hanja: "악수(握手) — '握'는 쥘 악, '手'는 손 수.", ex: { zh: "他们握手问好。", pinyin: "tāmen wòshǒu wènhǎo", ko: "그들은 악수하며 인사했어요." } },
        { zh: "误会", pinyin: "wùhuì", ko: "오해하다; 오해", pos: "동사", hanja: "오회(誤會) — '誤'는 그릇될 오. '잘못 이해하다=오해'.", ex: { zh: "你误会我的意思了。", pinyin: "nǐ wùhuì wǒ de yìsi le", ko: "당신은 제 뜻을 오해했어요." } },
        { zh: "吸引", pinyin: "xīyǐn", ko: "끌어당기다, 매료하다", pos: "동사", hanja: "흡인(吸引) — '吸'은 마실 흡, '引'은 끌 인.", ex: { zh: "这个故事很吸引人。", pinyin: "zhège gùshi hěn xīyǐn rén", ko: "이 이야기는 사람을 끌어당겨요." } },
        { zh: "限制", pinyin: "xiànzhì", ko: "제한하다; 제한", pos: "동사", hanja: "한제(限制) — '제한(制限)'과 같은 뜻이에요.", ex: { zh: "这里限制车速。", pinyin: "zhèlǐ xiànzhì chēsù", ko: "여기는 차 속도를 제한해요." } },
        { zh: "相反", pinyin: "xiāngfǎn", ko: "상반되다, 정반대이다", pos: "형용사", hanja: "상반(相反) — 한자 그대로.", ex: { zh: "我们的看法正好相反。", pinyin: "wǒmen de kànfǎ zhènghǎo xiāngfǎn", ko: "우리 생각은 정반대예요." } },
        { zh: "醒", pinyin: "xǐng", ko: "깨다, 잠에서 깨다", pos: "동사", hanja: "성(醒) — '깰 성'.", ex: { zh: "我每天七点醒。", pinyin: "wǒ měi tiān qī diǎn xǐng", ko: "저는 매일 7시에 깨요." } },
        { zh: "引起", pinyin: "yǐnqǐ", ko: "일으키다, 야기하다", pos: "동사", hanja: "인기(引起) — '引'은 끌 인, '起'는 일어날 기.", ex: { zh: "这件事引起了大家的注意。", pinyin: "zhè jiàn shì yǐnqǐ le dàjiā de zhùyì", ko: "이 일은 모두의 주의를 끌었어요." } },
        { zh: "赢", pinyin: "yíng", ko: "이기다, 승리하다", pos: "동사", ex: { zh: "我们队赢了比赛。", pinyin: "wǒmen duì yíng le bǐsài", ko: "우리 팀이 경기에서 이겼어요." } },
        { zh: "养成", pinyin: "yǎngchéng", ko: "(습관을) 기르다, 들이다", pos: "동사", hanja: "양성(養成) — '養'은 기를 양, '成'은 이룰 성.", ex: { zh: "他养成了早起的习惯。", pinyin: "tā yǎngchéng le zǎoqǐ de xíguàn", ko: "그는 일찍 일어나는 습관을 들였어요." } },
        { zh: "邀请", pinyin: "yāoqǐng", ko: "초대하다, 초청하다; 초대", pos: "동사", hanja: "요청(邀請) — '邀'는 맞이할 요. 한국어 '요청'과 달리 '초대'에 가까워요.", ex: { zh: "他邀请我参加生日会。", pinyin: "tā yāoqǐng wǒ cānjiā shēngrì huì", ko: "그가 저를 생일 파티에 초대했어요." } },
        { zh: "原谅", pinyin: "yuánliàng", ko: "용서하다, 양해하다", pos: "동사", hanja: "원량(原諒) — '諒'은 살필 량. '잘못을 용서하다'.", ex: { zh: "请原谅我的错误。", pinyin: "qǐng yuánliàng wǒ de cuòwù", ko: "제 실수를 용서해 주세요." } },
        { zh: "阅读", pinyin: "yuèdú", ko: "읽다, 독해하다; 독서", pos: "동사", hanja: "열독(閱讀) — '閱'은 볼 열, '讀'은 읽을 독.", ex: { zh: "我喜欢阅读小说。", pinyin: "wǒ xǐhuan yuèdú xiǎoshuō", ko: "저는 소설 읽는 걸 좋아해요." } },
        { zh: "允许", pinyin: "yǔnxǔ", ko: "허락하다, 허용하다", pos: "동사", hanja: "윤허(允許) — '允'은 허락할 윤, '許'는 허락할 허.", ex: { zh: "妈妈允许我出去玩。", pinyin: "māma yǔnxǔ wǒ chūqù wán", ko: "엄마가 나가서 놀게 허락했어요." } },
        { zh: "增加", pinyin: "zēngjiā", ko: "증가하다, 늘리다", pos: "동사", hanja: "증가(增加) — 한자 그대로.", ex: { zh: "今年学生增加了。", pinyin: "jīnnián xuésheng zēngjiā le", ko: "올해 학생이 늘었어요." } },
        { zh: "增长", pinyin: "zēngzhǎng", ko: "증가하다, 늘어나다", pos: "동사", hanja: "증장(增長) — '長'은 길 장(자라다). '늘어나다'.", ex: { zh: "经济在快速增长。", pinyin: "jīngjì zài kuàisù zēngzhǎng", ko: "경제가 빠르게 성장하고 있어요." } },
        { zh: "整理", pinyin: "zhěnglǐ", ko: "정리하다, 정돈하다", pos: "동사", hanja: "정리(整理) — 한자 그대로.", ex: { zh: "我把房间整理好了。", pinyin: "wǒ bǎ fángjiān zhěnglǐ hǎo le", ko: "저는 방을 다 정리했어요." } },
        { zh: "指", pinyin: "zhǐ", ko: "가리키다; 손가락; 지적하다", pos: "동사", hanja: "지(指) — '가리킬 지'.", ex: { zh: "他指着地图说话。", pinyin: "tā zhǐ zhe dìtú shuōhuà", ko: "그는 지도를 가리키며 말했어요." } },
        { zh: "制造", pinyin: "zhìzào", ko: "제조하다, 만들다", pos: "동사", hanja: "제조(製造) — 한자 그대로.", ex: { zh: "这个工厂制造汽车。", pinyin: "zhège gōngchǎng zhìzào qìchē", ko: "이 공장은 자동차를 만들어요." } },
        { zh: "祝贺", pinyin: "zhùhè", ko: "축하하다; 축하", pos: "동사", hanja: "축하(祝賀) — '祝'은 빌 축, '賀'는 하례할 하.", ex: { zh: "祝贺你考上大学！", pinyin: "zhùhè nǐ kǎoshàng dàxué", ko: "대학 합격을 축하해요!" } },
        { zh: "赚", pinyin: "zhuàn", ko: "(돈을) 벌다", pos: "동사", ex: { zh: "他做生意赚了很多钱。", pinyin: "tā zuò shēngyì zhuàn le hěn duō qián", ko: "그는 장사로 돈을 많이 벌었어요." } },
        { zh: "撞", pinyin: "zhuàng", ko: "부딪치다, 충돌하다", pos: "동사", ex: { zh: "车撞到了墙上。", pinyin: "chē zhuàng dào le qiáng shang", ko: "차가 벽에 부딪쳤어요." } },
        { zh: "总结", pinyin: "zǒngjié", ko: "총정리하다, 요약하다; 총결산", pos: "동사", hanja: "총결(總結) — '總'은 다 총, '結'은 맺을 결. '정리·요약'.", ex: { zh: "我们来总结一下今天的内容。", pinyin: "wǒmen lái zǒngjié yíxià jīntiān de nèiróng", ko: "오늘 내용을 정리해 봐요." } },
        { zh: "租", pinyin: "zū", ko: "빌리다, 임대하다, 세놓다", pos: "동사", hanja: "조(租) — '조세 조'. '빌려 쓰다'.", ex: { zh: "我想租一套房子。", pinyin: "wǒ xiǎng zū yí tào fángzi", ko: "저는 집 한 채를 임대하고 싶어요." } },
        { zh: "组成", pinyin: "zǔchéng", ko: "구성하다, 이루다", pos: "동사", hanja: "조성(組成) — '組'은 짤 조, '成'은 이룰 성.", ex: { zh: "我们班由三十人组成。", pinyin: "wǒmen bān yóu sānshí rén zǔchéng", ko: "우리 반은 서른 명으로 구성돼요." } },
        { zh: "组织", pinyin: "zǔzhī", ko: "조직하다; 조직; (생물) 조직", pos: "동사", hanja: "조직(組織) — 한자 그대로.", ex: { zh: "学校组织了一次旅行。", pinyin: "xuéxiào zǔzhī le yí cì lǚxíng", ko: "학교가 여행을 한 번 조직했어요." } },
        { zh: "尊重", pinyin: "zūnzhòng", ko: "존중하다, 존경하다", pos: "동사", hanja: "존중(尊重) — 한자 그대로.", ex: { zh: "我们要尊重别人。", pinyin: "wǒmen yào zūnzhòng biéren", ko: "우리는 남을 존중해야 해요." } },
        { zh: "值得", pinyin: "zhíde", ko: "~할 만하다, 가치가 있다", pos: "동사", hanja: "치득(值得) — '값할 만하다'. '値=값 치'.", ex: { zh: "这本书值得一看。", pinyin: "zhè běn shū zhídé yí kàn", ko: "이 책은 한번 볼 만해요." } },
        { zh: "做生意", pinyin: "zuòshēngyì", ko: "장사하다, 사업하다", pos: "동사", hanja: "주의(做生意) — '生意'는 '장사·사업'을 뜻해요.", ex: { zh: "他在外国做生意。", pinyin: "tā zài wàiguó zuò shēngyì", ko: "그는 외국에서 사업을 해요." } },
        { zh: "信任", pinyin: "xìnrèn", ko: "신임하다, 믿다; 신뢰", pos: "동사", hanja: "신임(信任) — '信'은 믿을 신, '任'은 맡길 임.", ex: { zh: "大家都信任他。", pinyin: "dàjiā dōu xìnrèn tā", ko: "모두가 그를 신뢰해요." } },
        { zh: "响", pinyin: "xiǎng", ko: "(소리가) 울리다, 나다; 소리; (소리가) 크다", pos: "동사", hanja: "향(響) — '울릴 향'. '음향(音響)'의 향.", ex: { zh: "电话突然响了。", pinyin: "diànhuà tūrán xiǎng le", ko: "전화가 갑자기 울렸어요." } },
      ],
    },
    {
      name: "HSK4 보강 — 명사·사물",
      icon: "🔶",
      words: [
        { zh: "硕士", pinyin: "shuòshì", ko: "석사 (학위)", pos: "명사", hanja: "석사(碩士) — '碩'은 클 석, '士'는 선비 사.", ex: { zh: "他是硕士。", pinyin: "tā shì shuòshì", ko: "그는 석사예요." } },
        { zh: "速度", pinyin: "sùdù", ko: "속도", pos: "명사", hanja: "속도(速度) — 한자 그대로.", ex: { zh: "汽车的速度很快。", pinyin: "qìchē de sùdù hěn kuài", ko: "자동차의 속도가 빨라요." } },
        { zh: "塑料袋", pinyin: "sùliàodài", ko: "비닐봉지", pos: "명사", hanja: "소료대(塑料袋) — '塑料'는 플라스틱, '袋'는 자루 대.", ex: { zh: "请给我一个塑料袋。", pinyin: "qǐng gěi wǒ yí ge sùliàodài", ko: "비닐봉지 하나 주세요." } },
        { zh: "孙子", pinyin: "sūnzi", ko: "손자", pos: "명사", hanja: "손자(孫子) — '孫'은 손자 손. 인명 '손자(孫子)'가 아니라 '손주'예요.", ex: { zh: "爷爷很爱他的孙子。", pinyin: "yéye hěn ài tā de sūnzi", ko: "할아버지는 손자를 무척 사랑해요." } },
        { zh: "态度", pinyin: "tàidu", ko: "태도", pos: "명사", hanja: "태도(態度) — 한자 그대로.", ex: { zh: "他的态度很好。", pinyin: "tā de tàidu hěn hǎo", ko: "그의 태도가 좋아요." } },
        { zh: "汤", pinyin: "tāng", ko: "국, 탕, 수프", pos: "명사", hanja: "탕(湯) — '끓일 탕'. '탕국'의 탕.", ex: { zh: "这碗汤很好喝。", pinyin: "zhè wǎn tāng hěn hǎohē", ko: "이 국 맛있어요." } },
        { zh: "特点", pinyin: "tèdiǎn", ko: "특징, 특색", pos: "명사", hanja: "특점(特點) — '特'은 특별할 특, '點'은 점 점. '특징'을 뜻해요.", ex: { zh: "这个城市有很多特点。", pinyin: "zhège chéngshì yǒu hěn duō tèdiǎn", ko: "이 도시는 특징이 많아요." } },
        { zh: "袜子", pinyin: "wàzi", ko: "양말", pos: "명사", hanja: "말자(襪子) — '襪'은 버선 말.", ex: { zh: "我买了一双袜子。", pinyin: "wǒ mǎi le yì shuāng wàzi", ko: "저는 양말 한 켤레를 샀어요." } },
        { zh: "网球", pinyin: "wǎngqiú", ko: "테니스", pos: "명사", hanja: "망구(網球) — '網'은 그물 망, '球'는 공 구.", ex: { zh: "我每周打网球。", pinyin: "wǒ měi zhōu dǎ wǎngqiú", ko: "저는 매주 테니스를 쳐요." } },
        { zh: "网站", pinyin: "wǎngzhàn", ko: "웹사이트", pos: "명사", hanja: "망참(網站) — '網'은 그물 망(인터넷), '站'은 역 참.", ex: { zh: "这个网站很有用。", pinyin: "zhège wǎngzhàn hěn yǒuyòng", ko: "이 사이트는 유용해요." } },
        { zh: "味道", pinyin: "wèidao", ko: "맛, 냄새; 분위기", pos: "명사", hanja: "미도(味道) — '味'는 맛 미, '道'는 길 도. '맛'을 뜻해요.", ex: { zh: "这个菜的味道很好。", pinyin: "zhège cài de wèidao hěn hǎo", ko: "이 요리는 맛이 좋아요." } },
        { zh: "温度", pinyin: "wēndù", ko: "온도", pos: "명사", hanja: "온도(溫度) — 한자 그대로.", ex: { zh: "今天的温度很高。", pinyin: "jīntiān de wēndù hěn gāo", ko: "오늘 온도가 높아요." } },
        { zh: "洗衣机", pinyin: "xǐyījī", ko: "세탁기", pos: "명사", hanja: "세의기(洗衣機) — '洗衣'는 빨래, '機'는 기계 기.", ex: { zh: "洗衣机坏了。", pinyin: "xǐyījī huài le", ko: "세탁기가 고장 났어요." } },
        { zh: "西红柿", pinyin: "xīhóngshì", ko: "토마토", pos: "명사", hanja: "서홍시(西紅柿) — '西'는 서녘 서, '紅柿'는 붉은 감. '서양 붉은 감=토마토'.", ex: { zh: "我喜欢吃西红柿。", pinyin: "wǒ xǐhuan chī xīhóngshì", ko: "저는 토마토를 좋아해요." } },
        { zh: "小说", pinyin: "xiǎoshuō", ko: "소설", pos: "명사", hanja: "소설(小說) — 한자 그대로.", ex: { zh: "这本小说很有意思。", pinyin: "zhè běn xiǎoshuō hěn yǒu yìsi", ko: "이 소설은 재미있어요." } },
        { zh: "效果", pinyin: "xiàoguǒ", ko: "효과", pos: "명사", hanja: "효과(效果) — 한자 그대로.", ex: { zh: "这个药的效果很好。", pinyin: "zhège yào de xiàoguǒ hěn hǎo", ko: "이 약은 효과가 좋아요." } },
        { zh: "笑话", pinyin: "xiàohua", ko: "농담, 우스갯소리; 비웃다", pos: "명사", hanja: "소화(笑話) — '笑'는 웃을 소, '話'는 말 화. '웃긴 이야기'.", ex: { zh: "他讲了一个笑话。", pinyin: "tā jiǎng le yí ge xiàohua", ko: "그가 농담 하나를 했어요." } },
        { zh: "心情", pinyin: "xīnqíng", ko: "기분, 마음", pos: "명사", hanja: "심정(心情) — '心'은 마음 심, '情'은 뜻 정. '기분'을 뜻해요.", ex: { zh: "今天我的心情很好。", pinyin: "jīntiān wǒ de xīnqíng hěn hǎo", ko: "오늘 제 기분이 좋아요." } },
        { zh: "信心", pinyin: "xìnxīn", ko: "자신감, 확신", pos: "명사", hanja: "신심(信心) — '믿는 마음=자신감'을 뜻해요.", ex: { zh: "我对考试有信心。", pinyin: "wǒ duì kǎoshì yǒu xìnxīn", ko: "저는 시험에 자신이 있어요." } },
        { zh: "信用卡", pinyin: "xìnyòngkǎ", ko: "신용카드", pos: "명사", hanja: "신용(信用卡) — '信用'은 신용, '卡'는 카드.", ex: { zh: "我用信用卡付款。", pinyin: "wǒ yòng xìnyòngkǎ fùkuǎn", ko: "저는 신용카드로 결제해요." } },
        { zh: "性别", pinyin: "xìngbié", ko: "성별", pos: "명사", hanja: "성별(性別) — 한자 그대로.", ex: { zh: "请填写你的性别。", pinyin: "qǐng tiánxiě nǐ de xìngbié", ko: "성별을 적어 주세요." } },
        { zh: "血", pinyin: "xuè", ko: "피, 혈액", pos: "명사", hanja: "혈(血) — '피 혈'. 구어로는 [xiě]로도 읽어요.", ex: { zh: "他的手出血了。", pinyin: "tā de shǒu chū xiě le", ko: "그의 손에서 피가 났어요." } },
        { zh: "压力", pinyin: "yālì", ko: "압력, 스트레스", pos: "명사", hanja: "압력(壓力) — 한자 그대로. '정신적 부담=스트레스'로도 써요.", ex: { zh: "工作压力很大。", pinyin: "gōngzuò yālì hěn dà", ko: "일 스트레스가 커요." } },
        { zh: "牙膏", pinyin: "yágāo", ko: "치약", pos: "명사", hanja: "아고(牙膏) — '牙'는 어금니 아, '膏'는 기름 고. '치약'.", ex: { zh: "牙膏用完了。", pinyin: "yágāo yòng wán le", ko: "치약을 다 썼어요." } },
        { zh: "亚洲", pinyin: "Yàzhōu", ko: "아시아 (대륙)", pos: "명사", hanja: "아주(亞洲) — '亞'는 버금 아, '洲'는 물가 주.", ex: { zh: "中国在亚洲。", pinyin: "Zhōngguó zài Yàzhōu", ko: "중국은 아시아에 있어요." } },
        { zh: "研究生", pinyin: "yánjiūshēng", ko: "대학원생", pos: "명사", hanja: "연구생(研究生) — '研究'는 연구, '生'은 날 생(학생).", ex: { zh: "我是研究生。", pinyin: "wǒ shì yánjiūshēng", ko: "저는 대학원생이에요." } },
        { zh: "盐", pinyin: "yán", ko: "소금", pos: "명사", hanja: "염(鹽) — '소금 염'.", ex: { zh: "请放一点盐。", pinyin: "qǐng fàng yìdiǎn yán", ko: "소금을 조금 넣어 주세요." } },
        { zh: "演员", pinyin: "yǎnyuán", ko: "배우, 연기자", pos: "명사", hanja: "연원(演員) — '演'은 펼 연, '員'은 인원 원. '연기자'.", ex: { zh: "他是有名的演员。", pinyin: "tā shì yǒumíng de yǎnyuán", ko: "그는 유명한 배우예요." } },
        { zh: "样子", pinyin: "yàngzi", ko: "모양, 모습, 모양새", pos: "명사", hanja: "양자(樣子) — '樣'은 모양 양. '겉모습'.", ex: { zh: "这件衣服样子很好看。", pinyin: "zhè jiàn yīfu yàngzi hěn hǎokàn", ko: "이 옷은 모양이 예뻐요." } },
        { zh: "钥匙", pinyin: "yàoshi", ko: "열쇠", pos: "명사", ex: { zh: "我找不到钥匙了。", pinyin: "wǒ zhǎo bú dào yàoshi le", ko: "열쇠를 못 찾겠어요." } },
        { zh: "叶子", pinyin: "yèzi", ko: "잎, 나뭇잎", pos: "명사", hanja: "엽자(葉子) — '葉'은 잎 엽.", ex: { zh: "秋天叶子变黄了。", pinyin: "qiūtiān yèzi biàn huáng le", ko: "가을에 잎이 노랗게 변했어요." } },
        { zh: "页", pinyin: "yè", ko: "페이지, 쪽", pos: "양사", hanja: "엽(頁) — '책면 엽(쪽)'.", ex: { zh: "请看第十页。", pinyin: "qǐng kàn dì shí yè", ko: "10쪽을 보세요." } },
        { zh: "艺术", pinyin: "yìshù", ko: "예술", pos: "명사", hanja: "예술(藝術) — 한자 그대로.", ex: { zh: "他对艺术很感兴趣。", pinyin: "tā duì yìshù hěn gǎn xìngqù", ko: "그는 예술에 관심이 많아요." } },
        { zh: "饮料", pinyin: "yǐnliào", ko: "음료", pos: "명사", hanja: "음료(飲料) — '飲'은 마실 음, '料'는 헤아릴 료.", ex: { zh: "你要喝什么饮料？", pinyin: "nǐ yào hē shénme yǐnliào", ko: "어떤 음료를 마실래요?" } },
        { zh: "优点", pinyin: "yōudiǎn", ko: "장점, 강점", pos: "명사", hanja: "우점(優點) — '優'는 넉넉할 우, '點'은 점 점. '장점'을 뜻해요.", ex: { zh: "他有很多优点。", pinyin: "tā yǒu hěn duō yōudiǎn", ko: "그는 장점이 많아요." } },
        { zh: "友谊", pinyin: "yǒuyì", ko: "우정, 우의", pos: "명사", hanja: "우의(友誼) — '友'는 벗 우, '誼'는 정 의. '우정'.", ex: { zh: "我们的友谊很深。", pinyin: "wǒmen de yǒuyì hěn shēn", ko: "우리의 우정은 깊어요." } },
        { zh: "羽毛球", pinyin: "yǔmáoqiú", ko: "배드민턴; 셔틀콕", pos: "명사", hanja: "우모구(羽毛球) — '羽毛'는 깃털, '球'는 공 구.", ex: { zh: "我们去打羽毛球吧。", pinyin: "wǒmen qù dǎ yǔmáoqiú ba", ko: "우리 배드민턴 치러 가요." } },
        { zh: "语法", pinyin: "yǔfǎ", ko: "문법", pos: "명사", hanja: "어법(語法) — '語'는 말씀 어, '法'은 법 법.", ex: { zh: "这个语法很难。", pinyin: "zhège yǔfǎ hěn nán", ko: "이 문법은 어려워요." } },
        { zh: "语言", pinyin: "yǔyán", ko: "언어, 말", pos: "명사", hanja: "어언(語言) — '語'는 말씀 어, '言'은 말씀 언. '언어'.", ex: { zh: "汉语是很美的语言。", pinyin: "Hànyǔ shì hěn měi de yǔyán", ko: "중국어는 아름다운 언어예요." } },
        { zh: "杂志", pinyin: "zázhì", ko: "잡지", pos: "명사", hanja: "잡지(雜誌) — '雜'은 섞일 잡, '誌'는 기록할 지.", ex: { zh: "我喜欢看时尚杂志。", pinyin: "wǒ xǐhuan kàn shíshàng zázhì", ko: "저는 패션 잡지 보는 걸 좋아해요." } },
        { zh: "植物", pinyin: "zhíwù", ko: "식물", pos: "명사", hanja: "식물(植物) — 한자 그대로.", ex: { zh: "她喜欢种植物。", pinyin: "tā xǐhuan zhòng zhíwù", ko: "그녀는 식물 키우기를 좋아해요." } },
        { zh: "中文", pinyin: "Zhōngwén", ko: "중국어", pos: "명사", hanja: "중문(中文) — '中'은 가운데 중, '文'은 글월 문. '중국어'.", ex: { zh: "我在学中文。", pinyin: "wǒ zài xué Zhōngwén", ko: "저는 중국어를 배우고 있어요." } },
        { zh: "重点", pinyin: "zhòngdiǎn", ko: "중점, 요점, 핵심", pos: "명사", hanja: "중점(重點) — '重'은 무거울 중, '點'은 점 점. '핵심'.", ex: { zh: "这是考试的重点。", pinyin: "zhè shì kǎoshì de zhòngdiǎn", ko: "이건 시험의 핵심이에요." } },
        { zh: "周围", pinyin: "zhōuwéi", ko: "주위, 주변", pos: "명사", hanja: "주위(周圍) — '周'는 두루 주, '圍'는 둘레 위.", ex: { zh: "学校周围有很多商店。", pinyin: "xuéxiào zhōuwéi yǒu hěn duō shāngdiàn", ko: "학교 주변에 가게가 많아요." } },
        { zh: "猪", pinyin: "zhū", ko: "돼지", pos: "명사", hanja: "저(豬) — '돼지 저'.", ex: { zh: "农场里有很多猪。", pinyin: "nóngchǎng lǐ yǒu hěn duō zhū", ko: "농장에 돼지가 많아요." } },
        { zh: "主意", pinyin: "zhǔyi", ko: "생각, 아이디어, 방법", pos: "명사", hanja: "주의(主意) — '主'는 주인 주, '意'는 뜻 의. '생각·아이디어'.", ex: { zh: "这是个好主意。", pinyin: "zhè shì ge hǎo zhǔyi", ko: "이건 좋은 생각이에요." } },
        { zh: "专业", pinyin: "zhuānyè", ko: "전공; 전문적인", pos: "명사", hanja: "전업(專業) — '專'은 오로지 전, '業'은 업 업. 대학 '전공'을 뜻해요.", ex: { zh: "我的专业是经济。", pinyin: "wǒ de zhuānyè shì jīngjì", ko: "제 전공은 경제예요." } },
        { zh: "作者", pinyin: "zuòzhě", ko: "작가, 저자", pos: "명사", hanja: "작자(作者) — '作'은 지을 작, '者'는 놈 자. '지은이'.", ex: { zh: "这本书的作者很有名。", pinyin: "zhè běn shū de zuòzhě hěn yǒumíng", ko: "이 책의 저자는 유명해요." } },
        { zh: "座位", pinyin: "zuòwèi", ko: "좌석, 자리", pos: "명사", hanja: "좌위(座位) — '座'는 자리 좌, '位'는 자리 위. '좌석'.", ex: { zh: "这个座位有人吗？", pinyin: "zhège zuòwèi yǒu rén ma", ko: "이 자리에 사람 있어요?" } },
        { zh: "嘴", pinyin: "zuǐ", ko: "입; 주둥이, 부리", pos: "명사", hanja: "취(嘴) — '부리 취'. 사람·동물의 '입'.", ex: { zh: "她的嘴很小。", pinyin: "tā de zuǐ hěn xiǎo", ko: "그녀는 입이 작아요." } },
        { zh: "长城", pinyin: "Chángchéng", ko: "만리장성", pos: "명사", hanja: "장성(長城) — '長'은 길 장, '城'은 재 성. '만리장성'.", ex: { zh: "我去过长城。", pinyin: "wǒ qù guò Chángchéng", ko: "저는 만리장성에 가 봤어요." } },
        { zh: "长江", pinyin: "ChángJiāng", ko: "창장강, 양쯔강", pos: "명사", hanja: "장강(長江) — '長'은 길 장, '江'은 강 강. 중국 최대 강이에요.", ex: { zh: "长江是中国最长的河。", pinyin: "Chángjiāng shì Zhōngguó zuì cháng de hé", ko: "창장강은 중국에서 가장 긴 강이에요." } },
      ],
    },
    {
      name: "HSK4 보강 — 형용사·상태",
      icon: "🔶",
      words: [
        { zh: "酸", pinyin: "suān", ko: "(맛이) 시다; 시큰하다, 쑤시다", pos: "형용사", hanja: "산(酸) — '실 산'. '산성(酸性)'의 산.", ex: { zh: "这个橘子很酸。", pinyin: "zhège júzi hěn suān", ko: "이 귤은 시어요." } },
        { zh: "危险", pinyin: "wēixiǎn", ko: "위험하다; 위험", pos: "형용사", hanja: "위험(危險) — '危'는 위태할 위, '險'은 험할 험.", ex: { zh: "晚上一个人走很危险。", pinyin: "wǎnshang yí ge rén zǒu hěn wēixiǎn", ko: "밤에 혼자 다니면 위험해요." } },
        { zh: "无聊", pinyin: "wúliáo", ko: "지루하다, 무료하다, 따분하다", pos: "형용사", hanja: "무료(無聊) — '無'는 없을 무, '聊'는 애오라지 료. '심심하다'.", ex: { zh: "今天很无聊。", pinyin: "jīntiān hěn wúliáo", ko: "오늘은 너무 심심해요." } },
        { zh: "香", pinyin: "xiāng", ko: "향기롭다, 맛있다; 향", pos: "형용사", hanja: "향(香) — '향기 향'.", ex: { zh: "这个菜很香。", pinyin: "zhège cài hěn xiāng", ko: "이 요리는 향이 좋아요." } },
        { zh: "详细", pinyin: "xiángxì", ko: "상세하다, 자세하다", pos: "형용사", hanja: "상세(詳細) — '詳'은 자세할 상, '細'는 가늘 세.", ex: { zh: "请详细说明一下。", pinyin: "qǐng xiángxì shuōmíng yíxià", ko: "자세히 설명해 주세요." } },
        { zh: "咸", pinyin: "xián", ko: "(맛이) 짜다", pos: "형용사", hanja: "함(鹹) — '짤 함'. 성씨가 아니라 '짜다'예요.", ex: { zh: "这个汤有点咸。", pinyin: "zhège tāng yǒudiǎn xián", ko: "이 국은 좀 짜요." } },
        { zh: "严重", pinyin: "yánzhòng", ko: "심각하다, 위중하다", pos: "형용사", hanja: "엄중(嚴重) — '嚴'은 엄할 엄, '重'은 무거울 중. '심각하다'.", ex: { zh: "他的病很严重。", pinyin: "tā de bìng hěn yánzhòng", ko: "그의 병은 심각해요." } },
        { zh: "硬", pinyin: "yìng", ko: "단단하다, 딱딱하다; 억지로", pos: "형용사", hanja: "경(硬) — '굳을 경'.", ex: { zh: "这个面包很硬。", pinyin: "zhège miànbāo hěn yìng", ko: "이 빵은 딱딱해요." } },
        { zh: "勇敢", pinyin: "yǒnggǎn", ko: "용감하다", pos: "형용사", hanja: "용감(勇敢) — '勇'은 날랠 용, '敢'은 감히 감.", ex: { zh: "他是个勇敢的孩子。", pinyin: "tā shì ge yǒnggǎn de háizi", ko: "그는 용감한 아이예요." } },
        { zh: "有趣", pinyin: "yǒuqù", ko: "재미있다, 흥미롭다", pos: "형용사", hanja: "유취(有趣) — '有'는 있을 유, '趣'는 뜻 취. '재미있다'.", ex: { zh: "这本书很有趣。", pinyin: "zhè běn shū hěn yǒuqù", ko: "이 책은 재미있어요." } },
        { zh: "友好", pinyin: "yǒuhǎo", ko: "우호적이다, 다정하다", pos: "형용사", hanja: "우호(友好) — '友'는 벗 우, '好'는 좋을 호.", ex: { zh: "这里的人很友好。", pinyin: "zhèlǐ de rén hěn yǒuhǎo", ko: "이곳 사람들은 친절해요." } },
        { zh: "愉快", pinyin: "yúkuài", ko: "유쾌하다, 즐겁다, 기쁘다", pos: "형용사", hanja: "유쾌(愉快) — '愉'는 즐거울 유, '快'는 쾌할 쾌.", ex: { zh: "祝你旅行愉快！", pinyin: "zhù nǐ lǚxíng yúkuài", ko: "즐거운 여행 되세요!" } },
        { zh: "圆", pinyin: "yuán", ko: "둥글다; 원, 동그라미", pos: "형용사", hanja: "원(圓) — '둥글 원'. '원형(圓形)'의 원.", ex: { zh: "月亮又大又圆。", pinyin: "yuèliang yòu dà yòu yuán", ko: "달이 크고 둥글어요." } },
        { zh: "脏", pinyin: "zāng", ko: "더럽다, 지저분하다", pos: "형용사", hanja: "장(髒) — '더러울 장'. 신체 장기(臟)와 글자가 달라요.", ex: { zh: "你的手很脏。", pinyin: "nǐ de shǒu hěn zāng", ko: "네 손이 더러워요." } },
        { zh: "窄", pinyin: "zhǎi", ko: "좁다", pos: "형용사", hanja: "착(窄) — '좁을 착'.", ex: { zh: "这条路很窄。", pinyin: "zhè tiáo lù hěn zhǎi", ko: "이 길은 좁아요." } },
        { zh: "整齐", pinyin: "zhěngqí", ko: "가지런하다, 깔끔하다, 단정하다", pos: "형용사", hanja: "정제(整齊) — '整'은 가지런할 정, '齊'는 가지런할 제.", ex: { zh: "书放得很整齐。", pinyin: "shū fàng de hěn zhěngqí", ko: "책이 가지런히 놓여 있어요." } },
        { zh: "正常", pinyin: "zhèngcháng", ko: "정상이다, 정상적이다", pos: "형용사", hanja: "정상(正常) — '正'은 바를 정, '常'은 항상 상.", ex: { zh: "他的身体很正常。", pinyin: "tā de shēntǐ hěn zhèngcháng", ko: "그의 몸은 정상이에요." } },
        { zh: "正确", pinyin: "zhèngquè", ko: "정확하다, 올바르다, 맞다", pos: "형용사", hanja: "정확(正確) — '正'은 바를 정, '確'은 굳을 확.", ex: { zh: "你的答案是正确的。", pinyin: "nǐ de dáàn shì zhèngquè de", ko: "당신의 답이 맞아요." } },
        { zh: "正式", pinyin: "zhèngshì", ko: "정식이다, 공식적이다", pos: "형용사", hanja: "정식(正式) — '正'은 바를 정, '式'은 법 식.", ex: { zh: "这是一个正式的会议。", pinyin: "zhè shì yí ge zhèngshì de huìyì", ko: "이건 공식 회의예요." } },
        { zh: "准确", pinyin: "zhǔnquè", ko: "정확하다, 정밀하다", pos: "형용사", hanja: "준확(準確) — '準'은 법도 준, '確'은 굳을 확. '정확하다'.", ex: { zh: "他的发音很准确。", pinyin: "tā de fāyīn hěn zhǔnquè", ko: "그의 발음은 정확해요." } },
        { zh: "辛苦", pinyin: "xīnkǔ", ko: "고생스럽다, 수고롭다; 고생하다", pos: "형용사", hanja: "신고(辛苦) — '辛'은 매울 신, '苦'는 쓸 고. '고생하다'.", ex: { zh: "您辛苦了！", pinyin: "nín xīnkǔ le", ko: "수고하셨어요!" } },
        { zh: "兴奋", pinyin: "xīngfèn", ko: "흥분하다, 신나다, 들뜨다", pos: "형용사", hanja: "흥분(興奮) — '興'은 일 흥, '奮'은 떨칠 분.", ex: { zh: "听到这个消息我很兴奋。", pinyin: "tīng dào zhège xiāoxi wǒ hěn xīngfèn", ko: "이 소식을 듣고 정말 신났어요." } },
      ],
    },
    {
      name: "HSK4 보강 — 부사·기타",
      icon: "🔶",
      words: [
        { zh: "随着", pinyin: "suízhe", ko: "~에 따라, ~함에 따라", pos: "개사", hanja: "수착(隨著) — '隨'는 따를 수.", ex: { zh: "随着时间，他变好了。", pinyin: "suí zhe shíjiān, tā biàn hǎo le", ko: "시간이 지남에 따라 그는 나아졌어요." } },
        { zh: "所有", pinyin: "suǒyǒu", ko: "모든, 전부의", pos: "형용사", hanja: "소유(所有) — '所'는 바 소, '有'는 있을 유. 여기서는 '모든'이라는 뜻.", ex: { zh: "所有人都来了。", pinyin: "suǒyǒu rén dōu lái le", ko: "모든 사람이 다 왔어요." } },
        { zh: "台", pinyin: "tái", ko: "대 (기계·차량 등을 세는 양사); 무대", pos: "양사", hanja: "대(台) — '대 대'. 기계를 세는 양사로 써요.", ex: { zh: "我买了一台电脑。", pinyin: "wǒ mǎi le yì tái diànnǎo", ko: "저는 컴퓨터 한 대를 샀어요." } },
        { zh: "趟", pinyin: "tàng", ko: "번, 차례 (왕복·이동을 세는 양사)", pos: "양사", hanja: "당(趟) — 오고 가는 '횟수'를 세는 양사예요.", ex: { zh: "我去了一趟商店。", pinyin: "wǒ qù le yí tàng shāngdiàn", ko: "저는 가게에 한 번 다녀왔어요." } },
        { zh: "挺", pinyin: "tǐng", ko: "꽤, 제법, 상당히", pos: "부사", hanja: "정(挺) — '곧을 정'. 구어에서 '꽤·제법'으로 자주 써요.", ex: { zh: "这个菜挺好吃的。", pinyin: "zhège cài tǐng hǎochī de", ko: "이 요리 꽤 맛있어요." } },
        { zh: "往", pinyin: "wǎng", ko: "~쪽으로, ~를 향해; 가다", pos: "개사", hanja: "왕(往) — '갈 왕'. 방향을 나타내요.", ex: { zh: "往前走就到了。", pinyin: "wǎng qián zǒu jiù dào le", ko: "앞으로 가면 바로 도착해요." } },
        { zh: "往往", pinyin: "wǎngwǎng", ko: "흔히, 종종, 대개", pos: "부사", hanja: "왕왕(往往) — '往'은 갈 왕. '자주·흔히'를 뜻해요.", ex: { zh: "他往往很晚才睡。", pinyin: "tā wǎngwǎng hěn wǎn cái shuì", ko: "그는 흔히 아주 늦게 자요." } },
        { zh: "完全", pinyin: "wánquán", ko: "완전히, 전적으로; 완전하다", pos: "부사", hanja: "완전(完全) — '完'은 완전할 완, '全'은 온전할 전.", ex: { zh: "我完全同意你。", pinyin: "wǒ wánquán tóngyì nǐ", ko: "저는 전적으로 당신에게 동의해요." } },
        { zh: "无", pinyin: "wú", ko: "없다, ~이 아니다", pos: "동사", hanja: "무(無) — '없을 무'. 격식 있는 표현에 써요.", ex: { zh: "这件事和我无关。", pinyin: "zhè jiàn shì hé wǒ wúguān", ko: "이 일은 저와 무관해요." } },
        { zh: "行", pinyin: "háng", ko: "줄, 행; 업종, 직종", pos: "명사", hanja: "행(行) — '항렬 항'으로 읽으면 '줄·업종'을 뜻해요.", ex: { zh: "他在银行这一行工作。", pinyin: "tā zài yínháng zhè yì háng gōngzuò", ko: "그는 은행 쪽 업종에서 일해요." } },
        { zh: "许多", pinyin: "xǔduō", ko: "매우 많은, 수많은", pos: "수사", hanja: "허다(許多) — '許'는 허락할 허, '多'는 많을 다. '많다'.", ex: { zh: "公园里有许多人。", pinyin: "gōngyuán lǐ yǒu xǔduō rén", ko: "공원에 사람이 아주 많아요." } },
        { zh: "也许", pinyin: "yěxǔ", ko: "아마, 어쩌면", pos: "부사", hanja: "야허(也許) — '~일지도 모른다'는 추측을 나타내요.", ex: { zh: "他也许不来了。", pinyin: "tā yěxǔ bù lái le", ko: "그는 어쩌면 안 올지도 몰라요." } },
        { zh: "一切", pinyin: "yīqiè", ko: "모든 것, 일체, 전부", pos: "대명사", hanja: "일체(一切) — '一'은 한 일, '切'는 온통 체. '모든 것'.", ex: { zh: "一切都会好的。", pinyin: "yíqiè dōu huì hǎo de", ko: "모든 게 다 잘될 거예요." } },
        { zh: "以", pinyin: "yǐ", ko: "~로(써), ~을 가지고", pos: "개사", hanja: "이(以) — '써 이'. 수단·방식을 나타내요.", ex: { zh: "我们以茶代酒。", pinyin: "wǒmen yǐ chá dài jiǔ", ko: "우리는 술 대신 차로 해요." } },
        { zh: "亿", pinyin: "yì", ko: "억 (100,000,000)", pos: "수사", hanja: "억(億) — '억 억'.", ex: { zh: "中国有十几亿人。", pinyin: "Zhōngguó yǒu shí jǐ yì rén", ko: "중국에는 십몇 억 명이 살아요." } },
        { zh: "由", pinyin: "yóu", ko: "~로부터, ~에 의해; ~에서 (말미암다)", pos: "개사", hanja: "유(由) — '말미암을 유'. 주체·기점을 나타내요.", ex: { zh: "这件事由他负责。", pinyin: "zhè jiàn shì yóu tā fùzé", ko: "이 일은 그가 책임져요." } },
        { zh: "由于", pinyin: "yóuyú", ko: "~때문에, ~로 인하여", pos: "개사", hanja: "유어(由於) — '由'는 말미암을 유. 원인을 나타내요.", ex: { zh: "由于下雨，比赛取消了。", pinyin: "yóuyú xià yǔ, bǐsài qǔxiāo le", ko: "비 때문에 경기가 취소됐어요." } },
        { zh: "与", pinyin: "yǔ", ko: "~와/과, ~및", pos: "개사", hanja: "여(與) — '더불 여'. 격식 있는 '~와/과'예요.", ex: { zh: "这与我没有关系。", pinyin: "zhè yǔ wǒ méiyǒu guānxi", ko: "이건 저와 관계가 없어요." } },
        { zh: "预习", pinyin: "yùxí", ko: "예습하다", pos: "동사", hanja: "예습(預習) — '預'는 미리 예, '習'은 익힐 습.", ex: { zh: "上课前我会预习。", pinyin: "shàngkè qián wǒ huì yùxí", ko: "수업 전에 저는 예습을 해요." } },
        { zh: "原来", pinyin: "yuánlái", ko: "알고 보니; 원래, 본래", pos: "부사", hanja: "원래(原來) — '原'은 근원 원, '來'는 올 래. '알고 보니'.", ex: { zh: "原来你是老师啊。", pinyin: "yuánlái nǐ shì lǎoshī a", ko: "알고 보니 당신이 선생님이군요." } },
        { zh: "约会", pinyin: "yuēhuì", ko: "약속; 데이트; 만나기로 하다", pos: "명사", hanja: "약회(約會) — '約'은 맺을 약, '會'는 모일 회. '약속·데이트'.", ex: { zh: "我今晚有个约会。", pinyin: "wǒ jīnwǎn yǒu ge yuēhuì", ko: "저는 오늘 저녁에 약속이 있어요." } },
        { zh: "呀", pinyin: "ya", ko: "~구나, ~네 (감탄·놀람의 어기조사)", pos: "조사", ex: { zh: "你来了呀！", pinyin: "nǐ lái le ya", ko: "당신 왔군요!" } },
        { zh: "咱们", pinyin: "zánmen", ko: "우리 (듣는 사람 포함)", pos: "대명사", hanja: "잡문(咱們) — 말하는 이와 듣는 이를 모두 포함하는 '우리'예요.", ex: { zh: "咱们一起去吧。", pinyin: "zánmen yìqǐ qù ba", ko: "우리 같이 가요." } },
        { zh: "暂时", pinyin: "zànshí", ko: "잠시, 잠깐, 임시로", pos: "부사", hanja: "잠시(暫時) — '暫'은 잠깐 잠, '時'는 때 시.", ex: { zh: "我暂时住在朋友家。", pinyin: "wǒ zànshí zhù zài péngyou jiā", ko: "저는 잠시 친구 집에 살아요." } },
        { zh: "真正", pinyin: "zhēnzhèng", ko: "진정한, 진짜의; 정말로", pos: "형용사", hanja: "진정(真正) — '真'은 참 진, '正'은 바를 정.", ex: { zh: "这才是真正的朋友。", pinyin: "zhè cái shì zhēnzhèng de péngyou", ko: "이게 바로 진정한 친구예요." } },
        { zh: "正好", pinyin: "zhènghǎo", ko: "마침, 때마침; 딱 맞다", pos: "부사", hanja: "정호(正好) — '正'은 바를 정, '好'는 좋을 호. '딱·마침'.", ex: { zh: "你来得正好。", pinyin: "nǐ lái de zhènghǎo", ko: "마침 잘 왔어요." } },
        { zh: "之", pinyin: "zhī", ko: "~의 (소유·수식의 문어 조사); 그것", pos: "조사", hanja: "지(之) — '갈 지'. 문어에서 '~의' 또는 대명사로 써요.", ex: { zh: "这是我最爱之一。", pinyin: "zhè shì wǒ zuì ài zhī yī", ko: "이건 제가 가장 좋아하는 것 중 하나예요." } },
        { zh: "直接", pinyin: "zhíjiē", ko: "직접적인; 곧바로, 바로", pos: "형용사", hanja: "직접(直接) — '直'은 곧을 직, '接'은 이을 접. 반대말은 '간접(間接)'.", ex: { zh: "你直接告诉我吧。", pinyin: "nǐ zhíjiē gàosu wǒ ba", ko: "저한테 바로 말해 주세요." } },
        { zh: "只好", pinyin: "zhǐhǎo", ko: "어쩔 수 없이, ~할 수밖에 없다", pos: "부사", hanja: "지호(只好) — '只'는 다만 지, '好'는 좋을 호. '하는 수 없이'.", ex: { zh: "没有票，我们只好回家。", pinyin: "méiyǒu piào, wǒmen zhǐhǎo huí jiā", ko: "표가 없어서 우리는 어쩔 수 없이 집에 갔어요." } },
        { zh: "只要", pinyin: "zhǐyào", ko: "~하기만 하면, ~하는 한", pos: "접속사", hanja: "지요(只要) — '只'는 다만 지, '要'는 구할 요. 조건을 나타내요.", ex: { zh: "只要努力，就会成功。", pinyin: "zhǐyào nǔlì, jiù huì chénggōng", ko: "노력하기만 하면 성공할 거예요." } },
        { zh: "重新", pinyin: "chóngxīn", ko: "다시, 새로이, 재차", pos: "부사", hanja: "중신(重新) — '重'을 '거듭 중(chóng)'으로 읽어 '다시'를 뜻해요.", ex: { zh: "我们重新开始吧。", pinyin: "wǒmen chóngxīn kāishǐ ba", ko: "우리 다시 시작해요." } },
        { zh: "逐渐", pinyin: "zhújiàn", ko: "점차, 점점", pos: "부사", hanja: "축점(逐漸) — '逐'은 쫓을 축, '漸'은 점점 점. '서서히'.", ex: { zh: "天气逐渐变冷了。", pinyin: "tiānqì zhújiàn biàn lěng le", ko: "날씨가 점점 추워졌어요." } },
        { zh: "主动", pinyin: "zhǔdòng", ko: "주동적이다, 자발적이다, 능동적인", pos: "형용사", hanja: "주동(主動) — '主'는 주인 주, '動'은 움직일 동. '스스로 나서다'.", ex: { zh: "他主动帮助别人。", pinyin: "tā zhǔdòng bāngzhù biéren", ko: "그는 자발적으로 남을 도와요." } },
        { zh: "专门", pinyin: "zhuānmén", ko: "전문적으로; 일부러, 오로지", pos: "부사", hanja: "전문(專門) — '專'은 오로지 전, '門'은 문 문.", ex: { zh: "我专门来看你。", pinyin: "wǒ zhuānmén lái kàn nǐ", ko: "저는 일부러 당신을 보러 왔어요." } },
        { zh: "准时", pinyin: "zhǔnshí", ko: "정시에, 제때에; 시간을 잘 지키다", pos: "부사", hanja: "준시(準時) — '準'은 법도 준, '時'는 때 시. '제시간에'.", ex: { zh: "请准时到。", pinyin: "qǐng zhǔnshí dào", ko: "제시간에 와 주세요." } },
        { zh: "仔细", pinyin: "zǐxì", ko: "꼼꼼하다, 세심하다; 자세히", pos: "형용사", hanja: "자세(仔細) — '細'는 가늘 세. '세심하다'.", ex: { zh: "请仔细看说明书。", pinyin: "qǐng zǐxì kàn shuōmíngshū", ko: "설명서를 꼼꼼히 보세요." } },
        { zh: "最好", pinyin: "zuìhǎo", ko: "가장 좋다; ~하는 게 가장 좋다", pos: "부사", hanja: "최호(最好) — '最'는 가장 최, '好'는 좋을 호. 충고로 '~하는 게 낫다'.", ex: { zh: "你最好早点休息。", pinyin: "nǐ zuìhǎo zǎodiǎn xiūxi", ko: "당신은 좀 일찍 쉬는 게 좋아요." } },
        { zh: "最后", pinyin: "zuìhòu", ko: "마지막, 최후; 결국, 마침내", pos: "명사", hanja: "최후(最後) — '最'는 가장 최, '後'는 뒤 후.", ex: { zh: "最后他还是来了。", pinyin: "zuìhòu tā háishì lái le", ko: "결국 그는 왔어요." } },
        { zh: "座", pinyin: "zuò", ko: "동, 채 (산·건물 등을 세는 양사)", pos: "양사", hanja: "좌(座) — '자리 좌'. 큰 건물·산을 세는 양사예요.", ex: { zh: "那是一座很高的山。", pinyin: "nà shì yí zuò hěn gāo de shān", ko: "저건 아주 높은 산 한 채예요." } },
        { zh: "著名", pinyin: "zhùmíng", ko: "저명하다, 유명하다", pos: "형용사", hanja: "저명(著名) — '著'는 나타날 저, '名'은 이름 명. '유명하다'.", ex: { zh: "他是一位著名的作家。", pinyin: "tā shì yí wèi zhùmíng de zuòjiā", ko: "그는 저명한 작가예요." } },
        { zh: "修", pinyin: "xiū", ko: "고치다, 수리하다; 닦다", pos: "동사", hanja: "수(修) — '닦을 수'. '수리(修理)'의 수. 성씨가 아니에요.", ex: { zh: "我去修自行车。", pinyin: "wǒ qù xiū zìxíngchē", ko: "저는 자전거를 고치러 가요." } },
        { zh: "永远", pinyin: "yǒngyuǎn", ko: "영원히, 언제까지나", pos: "부사", hanja: "영원(永遠) — '永'은 길 영, '遠'은 멀 원.", ex: { zh: "我永远记得你。", pinyin: "wǒ yǒngyuǎn jìde nǐ", ko: "저는 당신을 영원히 기억할 거예요." } },
      ],
    },
  ],
};

export default themes;
