/**
 * H4 (HSK 4급) 보강 어휘 — 청크 B (표준 HSK4 단어 중 본편에 없던 163개).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되, 성씨·이체자·다음자 오독은
 * 실제 HSK 의미의 표준 병음으로 교정했어요(예: 那 Nā→nà). 가짜동족어는 ko·hanja에 명시.
 */
export default {
  themes: [
    {
      name: "HSK4 보강 — 동사",
      icon: "🔶",
      words: [
        { zh: "加班", pinyin: "jiā bān", ko: "야근하다, 초과 근무하다", pos: "동사", hanja: "가반(加班) — '班'은 근무 조 반. '근무를 더하다 = 야근'.", ex: { zh: "我今天要加班。", pinyin: "wǒ jīntiān yào jiābān", ko: "저 오늘 야근해야 해요." } },
        { zh: "减肥", pinyin: "jiǎn féi", ko: "살을 빼다, 다이어트하다", pos: "동사", hanja: "감비(減肥) — '減'은 덜 감, '肥'는 살찔 비.", ex: { zh: "她最近在减肥。", pinyin: "tā zuìjìn zài jiǎnféi", ko: "그녀는 요즘 다이어트 중이에요." } },
        { zh: "减少", pinyin: "jiǎn shǎo", ko: "줄이다, 감소하다", pos: "동사", hanja: "감소(減少) — 한자 그대로.", ex: { zh: "我们要减少花钱。", pinyin: "wǒmen yào jiǎnshǎo huā qián", ko: "우리는 지출을 줄여야 해요." } },
        { zh: "交", pinyin: "jiāo", ko: "건네다, 내다, 제출하다, (돈을) 내다", pos: "동사", hanja: "교(交) — '사귈 교'. '교부(交付)'의 교.", ex: { zh: "请把作业交给老师。", pinyin: "qǐng bǎ zuòyè jiāo gěi lǎoshī", ko: "숙제를 선생님께 제출하세요." } },
        { zh: "节约", pinyin: "jié yuē", ko: "절약하다, 아끼다", pos: "동사", hanja: "절약(節約) — 한자 그대로.", ex: { zh: "我们要节约用水。", pinyin: "wǒmen yào jiéyuē yòng shuǐ", ko: "우리는 물을 아껴 써야 해요." } },
        { zh: "进行", pinyin: "jìn xíng", ko: "진행하다, (어떤 활동을) 하다", pos: "동사", hanja: "진행(進行) — 한자 그대로.", ex: { zh: "比赛正在进行。", pinyin: "bǐsài zhèngzài jìnxíng", ko: "경기가 진행 중이에요." } },
        { zh: "禁止", pinyin: "jìn zhǐ", ko: "금지하다", pos: "동사", hanja: "금지(禁止) — 한자 그대로.", ex: { zh: "这里禁止吸烟。", pinyin: "zhèlǐ jìnzhǐ xīyān", ko: "여기는 흡연 금지예요." } },
        { zh: "经历", pinyin: "jīng lì", ko: "겪다, 경험하다; 경험", pos: "동사", hanja: "경력(經歷) — 한자는 '경력'이지만 '직접 겪다·체험'을 뜻해요.", ex: { zh: "我经历过很多事。", pinyin: "wǒ jīnglì guò hěn duō shì", ko: "저는 많은 일을 겪었어요." } },
        { zh: "举办", pinyin: "jǔ bàn", ko: "개최하다, 열다", pos: "동사", hanja: "거판(舉辦) — '舉'는 들 거, '辦'은 처리할 판.", ex: { zh: "学校举办了运动会。", pinyin: "xuéxiào jǔbàn le yùndònghuì", ko: "학교에서 운동회를 열었어요." } },
        { zh: "拒绝", pinyin: "jù jué", ko: "거절하다, 거부하다", pos: "동사", hanja: "거절(拒絕) — 한자 그대로.", ex: { zh: "他拒绝了我的帮助。", pinyin: "tā jùjué le wǒ de bāngzhù", ko: "그는 제 도움을 거절했어요." } },
        { zh: "开玩笑", pinyin: "kāi wán xiào", ko: "농담하다, 장난치다", pos: "동사", hanja: "개완소(開玩笑) — '玩'은 놀 완, '笑'는 웃을 소. '농담을 열다'.", ex: { zh: "别生气，我只是开玩笑。", pinyin: "bié shēngqì, wǒ zhǐshì kāi wánxiào", ko: "화내지 마요, 그냥 농담이에요." } },
        { zh: "拉", pinyin: "lā", ko: "당기다, 끌다; (악기를) 켜다", pos: "동사", hanja: "랍(拉) — '끌 랍'.", ex: { zh: "请帮我拉一下门。", pinyin: "qǐng bāng wǒ lā yíxià mén", ko: "문 좀 당겨 주세요." } },
        { zh: "来不及", pinyin: "lái bu jí", ko: "시간이 늦다, 미처 ~하지 못하다", pos: "동사", ex: { zh: "现在去已经来不及了。", pinyin: "xiànzài qù yǐjīng lái bu jí le", ko: "지금 가면 이미 늦었어요." } },
        { zh: "来得及", pinyin: "lái de jí", ko: "시간 안에 댈 수 있다, 늦지 않다", pos: "동사", ex: { zh: "现在出发还来得及。", pinyin: "xiànzài chūfā hái lái de jí", ko: "지금 출발하면 아직 늦지 않아요." } },
        { zh: "浪费", pinyin: "làng fèi", ko: "낭비하다", pos: "동사", hanja: "낭비(浪費) — 한자 그대로.", ex: { zh: "别浪费时间了。", pinyin: "bié làngfèi shíjiān le", ko: "시간 낭비하지 마세요." } },
        { zh: "理发", pinyin: "lǐ fà", ko: "이발하다, 머리를 자르다", pos: "동사", hanja: "이발(理髮) — '理'는 다스릴 리, '髮'은 터럭 발.", ex: { zh: "我下午去理发。", pinyin: "wǒ xiàwǔ qù lǐfà", ko: "저 오후에 머리 자르러 가요." } },
        { zh: "例如", pinyin: "lì rú", ko: "예를 들면, 예컨대", pos: "동사", hanja: "예여(例如) — '例'는 법식 례, '如'는 같을 여. '예를 들면'.", ex: { zh: "我喜欢水果，例如苹果。", pinyin: "wǒ xǐhuan shuǐguǒ, lìrú píngguǒ", ko: "저는 과일, 예를 들면 사과를 좋아해요." } },
        { zh: "联系", pinyin: "lián xì", ko: "연락하다, 연결하다; 연락", pos: "동사", hanja: "연계(聯繫) — 한자는 '연계'이지만 '연락·연결'을 뜻해요.", ex: { zh: "有事请跟我联系。", pinyin: "yǒu shì qǐng gēn wǒ liánxì", ko: "일이 있으면 저에게 연락하세요." } },
        { zh: "聊天", pinyin: "liáo tiān", ko: "잡담하다, 수다 떨다", pos: "동사", hanja: "료천(聊天) — '聊'는 애오라지 료, '天'은 하늘 천. '한담하다'.", ex: { zh: "我们一起聊天吧。", pinyin: "wǒmen yìqǐ liáotiān ba", ko: "우리 같이 수다 떨어요." } },
        { zh: "流泪", pinyin: "liú lèi", ko: "눈물을 흘리다", pos: "동사", hanja: "유루(流淚) — '流'는 흐를 류, '淚'는 눈물 루.", ex: { zh: "她感动得流泪了。", pinyin: "tā gǎndòng de liúlèi le", ko: "그녀는 감동해서 눈물을 흘렸어요." } },
        { zh: "流行", pinyin: "liú xíng", ko: "유행하다; 유행의", pos: "동사", hanja: "유행(流行) — 한자 그대로.", ex: { zh: "这首歌很流行。", pinyin: "zhè shǒu gē hěn liúxíng", ko: "이 노래는 아주 유행이에요." } },
        { zh: "留", pinyin: "liú", ko: "남기다, 머무르다, 남겨 두다", pos: "동사", hanja: "류(留) — '머무를 류'.", ex: { zh: "请给我留个座位。", pinyin: "qǐng gěi wǒ liú ge zuòwèi", ko: "자리 하나 남겨 주세요." } },
        { zh: "留学", pinyin: "liú xué", ko: "유학하다", pos: "동사", hanja: "유학(留學) — 한자 그대로.", ex: { zh: "他去美国留学了。", pinyin: "tā qù Měiguó liúxué le", ko: "그는 미국으로 유학 갔어요." } },
        { zh: "排列", pinyin: "pái liè", ko: "배열하다, 나열하다", pos: "동사", hanja: "배열(排列) — 한자 그대로.", ex: { zh: "请按顺序排列。", pinyin: "qǐng àn shùnxù páiliè", ko: "순서대로 배열해 주세요." } },
        { zh: "陪", pinyin: "péi", ko: "동반하다, 함께 있어 주다", pos: "동사", hanja: "배(陪) — '모실 배'.", ex: { zh: "我陪你去医院。", pinyin: "wǒ péi nǐ qù yīyuàn", ko: "제가 병원에 같이 가 줄게요." } },
        { zh: "骗", pinyin: "piàn", ko: "속이다, 사기 치다", pos: "동사", hanja: "편(騙) — '속일 편'.", ex: { zh: "他骗了我的钱。", pinyin: "tā piàn le wǒ de qián", ko: "그가 제 돈을 속여 가져갔어요." } },
        { zh: "起飞", pinyin: "qǐ fēi", ko: "(비행기가) 이륙하다", pos: "동사", hanja: "기비(起飛) — '起'는 일어날 기, '飛'는 날 비.", ex: { zh: "飞机十点起飞。", pinyin: "fēijī shí diǎn qǐfēi", ko: "비행기는 10시에 이륙해요." } },
        { zh: "起来", pinyin: "qǐ lai", ko: "일어나다, 일어서다", pos: "동사", hanja: "기래(起來) — '起'는 일어날 기.", ex: { zh: "我每天七点起来。", pinyin: "wǒ měi tiān qī diǎn qǐlái", ko: "저는 매일 7시에 일어나요." } },
        { zh: "请假", pinyin: "qǐng jià", ko: "휴가를 내다, 결근·결석을 신청하다", pos: "동사", hanja: "청가(請假) — '請'은 청할 청, '假'는 겨를 가(휴가).", ex: { zh: "我想请一天假。", pinyin: "wǒ xiǎng qǐng yì tiān jià", ko: "저 하루 휴가를 내고 싶어요." } },
        { zh: "请客", pinyin: "qǐng kè", ko: "한턱내다, 대접하다", pos: "동사", hanja: "청객(請客) — '請'은 청할 청, '客'은 손 객. '손님을 청하다'.", ex: { zh: "今天我请客。", pinyin: "jīntiān wǒ qǐngkè", ko: "오늘은 제가 살게요." } },
        { zh: "取", pinyin: "qǔ", ko: "찾다, 가지다, (돈을) 인출하다", pos: "동사", hanja: "취(取) — '가질 취'. '취득(取得)'의 취.", ex: { zh: "我去银行取钱。", pinyin: "wǒ qù yínháng qǔ qián", ko: "저는 은행에 돈을 찾으러 가요." } },
        { zh: "缺少", pinyin: "quē shǎo", ko: "부족하다, 모자라다", pos: "동사", hanja: "결소(缺少) — '缺'은 이지러질 결, '少'는 적을 소.", ex: { zh: "我们缺少时间。", pinyin: "wǒmen quēshǎo shíjiān", ko: "우리는 시간이 부족해요." } },
        { zh: "扔", pinyin: "rēng", ko: "던지다, 버리다", pos: "동사", ex: { zh: "请把垃圾扔了。", pinyin: "qǐng bǎ lājī rēng le", ko: "쓰레기 좀 버려 주세요." } },
        { zh: "散步", pinyin: "sàn bù", ko: "산책하다", pos: "동사", hanja: "산보(散步) — '散'은 흩을 산, '步'는 걸음 보.", ex: { zh: "晚饭后我们去散步。", pinyin: "wǎnfàn hòu wǒmen qù sànbù", ko: "저녁 먹고 우리 산책 가요." } },
        { zh: "商量", pinyin: "shāng liang", ko: "상의하다, 의논하다", pos: "동사", hanja: "상량(商量) — '商'은 헤아릴 상, '量'은 헤아릴 량.", ex: { zh: "这件事我们商量一下。", pinyin: "zhè jiàn shì wǒmen shāngliang yíxià", ko: "이 일은 우리 좀 의논해 봐요." } },
        { zh: "申请", pinyin: "shēn qǐng", ko: "신청하다; 신청", pos: "동사", hanja: "신청(申請) — 한자 그대로.", ex: { zh: "我申请了奖学金。", pinyin: "wǒ shēnqǐng le jiǎngxuéjīn", ko: "저는 장학금을 신청했어요." } },
        { zh: "省", pinyin: "shěng", ko: "아끼다, 절약하다, 생략하다; 성(행정구역)", pos: "동사", hanja: "성(省) — '살필 성·덜 생'. '절약·생략'을 뜻해요.", ex: { zh: "坐公交车能省钱。", pinyin: "zuò gōngjiāochē néng shěng qián", ko: "버스를 타면 돈을 아낄 수 있어요." } },
        { zh: "剩", pinyin: "shèng", ko: "남다, 남기다", pos: "동사", hanja: "잉(剩) — '남을 잉'.", ex: { zh: "桌上还剩一些菜。", pinyin: "zhuō shang hái shèng yìxiē cài", ko: "식탁에 음식이 좀 남아 있어요." } },
        { zh: "输", pinyin: "shū", ko: "지다, 패하다; 수송하다", pos: "동사", hanja: "수(輸) — '보낼 수'. '운수(運輸)'의 수. 경기에서는 '지다'.", ex: { zh: "我们队输了比赛。", pinyin: "wǒmen duì shū le bǐsài", ko: "우리 팀은 경기에서 졌어요." } },
        { zh: "熟悉", pinyin: "shú xī", ko: "익숙하다, 잘 알다", pos: "동사", hanja: "숙실(熟悉) — '熟'은 익을 숙, '悉'은 다 실.", ex: { zh: "我对这里很熟悉。", pinyin: "wǒ duì zhèlǐ hěn shúxī", ko: "저는 이곳을 아주 잘 알아요." } },
        { zh: "使用", pinyin: "shǐ yòng", ko: "사용하다", pos: "동사", hanja: "사용(使用) — 한자 그대로.", ex: { zh: "这个软件很容易使用。", pinyin: "zhège ruǎnjiàn hěn róngyì shǐyòng", ko: "이 소프트웨어는 사용하기 쉬워요." } },
        { zh: "试", pinyin: "shì", ko: "시도하다, 해 보다, 입어 보다", pos: "동사", hanja: "시(試) — '시험할 시'. '시도(試圖)'의 시.", ex: { zh: "我可以试一下吗？", pinyin: "wǒ kěyǐ shì yíxià ma", ko: "한번 해 봐도 될까요?" } },
        { zh: "适合", pinyin: "shì hé", ko: "알맞다, 적합하다, 어울리다", pos: "동사", hanja: "적합(適合) — 한자 그대로.", ex: { zh: "这件衣服很适合你。", pinyin: "zhè jiàn yīfu hěn shìhé nǐ", ko: "이 옷은 당신에게 잘 어울려요." } },
        { zh: "收", pinyin: "shōu", ko: "받다, 거두다, 받아들이다", pos: "동사", hanja: "수(收) — '거둘 수'. '수입(收入)'의 수.", ex: { zh: "我收到了你的礼物。", pinyin: "wǒ shōudào le nǐ de lǐwù", ko: "당신 선물을 받았어요." } },
        { zh: "收拾", pinyin: "shōu shi", ko: "정리하다, 치우다, (짐을) 챙기다", pos: "동사", hanja: "수습(收拾) — '收'는 거둘 수, '拾'은 주울 습.", ex: { zh: "我在收拾房间。", pinyin: "wǒ zài shōushi fángjiān", ko: "저는 방을 정리하고 있어요." } },
        { zh: "受不了", pinyin: "shòu bù liǎo", ko: "견딜 수 없다, 참을 수 없다", pos: "표현", ex: { zh: "天气太热，我受不了了。", pinyin: "tiānqì tài rè, wǒ shòu bu liǎo le", ko: "날씨가 너무 더워서 못 견디겠어요." } },
        { zh: "弄", pinyin: "nòng", ko: "하다, 만지다, 다루다", pos: "동사", ex: { zh: "你把它弄坏了。", pinyin: "nǐ bǎ tā nòng huài le", ko: "당신이 그걸 망가뜨렸어요." } },
        { zh: "说明", pinyin: "shuō míng", ko: "설명하다; 설명", pos: "동사", hanja: "설명(說明) — 한자 그대로.", ex: { zh: "请你说明一下原因。", pinyin: "qǐng nǐ shuōmíng yíxià yuányīn", ko: "이유를 좀 설명해 주세요." } },
      ],
    },
    {
      name: "HSK4 보강 — 명사·사물",
      icon: "🔶",
      words: [
        { zh: "加油站", pinyin: "jiā yóu zhàn", ko: "주유소", pos: "명사", hanja: "가유참(加油站) — '油'는 기름 유, '站'은 역·정거장 참.", ex: { zh: "前面有一个加油站。", pinyin: "qiánmiàn yǒu yí ge jiāyóuzhàn", ko: "앞쪽에 주유소가 하나 있어요." } },
        { zh: "家具", pinyin: "jiā jù", ko: "가구", pos: "명사", hanja: "가구(家具) — 한자 그대로.", ex: { zh: "这些家具很贵。", pinyin: "zhèxiē jiājù hěn guì", ko: "이 가구들은 비싸요." } },
        { zh: "奖金", pinyin: "jiǎng jīn", ko: "상금, 보너스", pos: "명사", hanja: "장금(獎金) — '獎'은 장려할 장, '金'은 쇠 금.", ex: { zh: "他拿到了奖金。", pinyin: "tā nádào le jiǎngjīn", ko: "그는 보너스를 받았어요." } },
        { zh: "饺子", pinyin: "jiǎo zi", ko: "교자, 만두", pos: "명사", hanja: "교자(餃子) — '餃'은 경단 교.", ex: { zh: "我们一起包饺子吧。", pinyin: "wǒmen yìqǐ bāo jiǎozi ba", ko: "우리 같이 만두 빚어요." } },
        { zh: "教授", pinyin: "jiào shòu", ko: "교수", pos: "명사", hanja: "교수(教授) — 한자 그대로.", ex: { zh: "他是大学教授。", pinyin: "tā shì dàxué jiàoshòu", ko: "그는 대학 교수예요." } },
        { zh: "京剧", pinyin: "jīng jù", ko: "경극(베이징 전통극)", pos: "명사", hanja: "경극(京劇) — '京'은 서울 경, '劇'은 연극 극.", ex: { zh: "我喜欢看京剧。", pinyin: "wǒ xǐhuan kàn jīngjù", ko: "저는 경극 보는 걸 좋아해요." } },
        { zh: "精神", pinyin: "jīng shén", ko: "정신, 활기, 기운", pos: "명사", hanja: "정신(精神) — 한자 그대로.", ex: { zh: "他今天精神很好。", pinyin: "tā jīntiān jīngshén hěn hǎo", ko: "그는 오늘 기운이 좋아요." } },
        { zh: "警察", pinyin: "jǐng chá", ko: "경찰", pos: "명사", hanja: "경찰(警察) — 한자 그대로.", ex: { zh: "警察来了。", pinyin: "jǐngchá lái le", ko: "경찰이 왔어요." } },
        { zh: "镜子", pinyin: "jìng zi", ko: "거울", pos: "명사", hanja: "경자(鏡子) — '鏡'은 거울 경.", ex: { zh: "她在照镜子。", pinyin: "tā zài zhào jìngzi", ko: "그녀는 거울을 보고 있어요." } },
        { zh: "看法", pinyin: "kàn fǎ", ko: "견해, 관점, 생각", pos: "명사", hanja: "간법(看法) — '看'은 볼 간, '法'은 법 법. '보는 방식 = 견해'.", ex: { zh: "我想听听你的看法。", pinyin: "wǒ xiǎng tīngting nǐ de kànfǎ", ko: "당신의 생각을 듣고 싶어요." } },
        { zh: "科学", pinyin: "kē xué", ko: "과학; 과학적이다", pos: "명사", hanja: "과학(科學) — 한자 그대로.", ex: { zh: "我对科学很感兴趣。", pinyin: "wǒ duì kēxué hěn gǎn xìngqù", ko: "저는 과학에 관심이 많아요." } },
        { zh: "空气", pinyin: "kōng qì", ko: "공기", pos: "명사", hanja: "공기(空氣) — 한자 그대로.", ex: { zh: "这里的空气很好。", pinyin: "zhèlǐ de kōngqì hěn hǎo", ko: "여기는 공기가 좋아요." } },
        { zh: "垃圾桶", pinyin: "lā jī tǒng", ko: "쓰레기통", pos: "명사", hanja: "납극통(垃圾桶) — '桶'은 통 통. '垃圾'는 쓰레기.", ex: { zh: "垃圾桶在门口。", pinyin: "lājītǒng zài ménkǒu", ko: "쓰레기통은 입구에 있어요." } },
        { zh: "老虎", pinyin: "lǎo hǔ", ko: "호랑이", pos: "명사", hanja: "노호(老虎) — '虎'는 범 호.", ex: { zh: "动物园里有老虎。", pinyin: "dòngwùyuán lǐ yǒu lǎohǔ", ko: "동물원에 호랑이가 있어요." } },
        { zh: "理想", pinyin: "lǐ xiǎng", ko: "이상, 꿈; 이상적이다", pos: "명사", hanja: "이상(理想) — 한자 그대로.", ex: { zh: "我的理想是当医生。", pinyin: "wǒ de lǐxiǎng shì dāng yīshēng", ko: "제 꿈은 의사가 되는 거예요." } },
        { zh: "力气", pinyin: "lì qi", ko: "힘, 기운", pos: "명사", hanja: "역기(力氣) — '力'은 힘 력, '氣'는 기운 기.", ex: { zh: "他力气很大。", pinyin: "tā lìqi hěn dà", ko: "그는 힘이 세요." } },
        { zh: "毛巾", pinyin: "máo jīn", ko: "수건, 타월", pos: "명사", hanja: "모건(毛巾) — '毛'는 털 모, '巾'은 수건 건.", ex: { zh: "请给我一条毛巾。", pinyin: "qǐng gěi wǒ yì tiáo máojīn", ko: "수건 한 장 주세요." } },
        { zh: "梦", pinyin: "mèng", ko: "꿈", pos: "명사", hanja: "몽(夢) — '꿈 몽'.", ex: { zh: "我昨晚做了一个梦。", pinyin: "wǒ zuówǎn zuò le yí ge mèng", ko: "저는 어젯밤 꿈을 꿨어요." } },
        { zh: "密码", pinyin: "mì mǎ", ko: "비밀번호, 암호", pos: "명사", hanja: "밀마(密碼) — '密'은 빽빽할 밀, '碼'는 부호 마.", ex: { zh: "我忘了密码。", pinyin: "wǒ wàng le mìmǎ", ko: "저 비밀번호를 잊어버렸어요." } },
        { zh: "母亲", pinyin: "mǔ qīn", ko: "어머니, 모친", pos: "명사", hanja: "모친(母親) — 한자 그대로.", ex: { zh: "她是三个孩子的母亲。", pinyin: "tā shì sān ge háizi de mǔqīn", ko: "그녀는 세 아이의 어머니예요." } },
        { zh: "目的", pinyin: "mù dì", ko: "목적", pos: "명사", hanja: "목적(目的) — 한자 그대로.", ex: { zh: "你来这里的目的是什么？", pinyin: "nǐ lái zhèlǐ de mùdì shì shénme", ko: "여기 온 목적이 뭐예요?" } },
        { zh: "年龄", pinyin: "nián líng", ko: "나이, 연령", pos: "명사", hanja: "연령(年齡) — 한자 그대로.", ex: { zh: "请问您的年龄？", pinyin: "qǐngwèn nín de niánlíng", ko: "실례지만 연세가 어떻게 되세요?" } },
        { zh: "农村", pinyin: "nóng cūn", ko: "농촌, 시골", pos: "명사", hanja: "농촌(農村) — 한자 그대로.", ex: { zh: "他在农村长大。", pinyin: "tā zài nóngcūn zhǎngdà", ko: "그는 시골에서 자랐어요." } },
        { zh: "皮肤", pinyin: "pí fū", ko: "피부", pos: "명사", hanja: "피부(皮膚) — 한자 그대로.", ex: { zh: "她的皮肤很白。", pinyin: "tā de pífū hěn bái", ko: "그녀는 피부가 하얘요." } },
        { zh: "脾气", pinyin: "pí qi", ko: "성격, 성질, 기질", pos: "명사", hanja: "비기(脾氣) — '脾'는 지라 비, '氣'는 기운 기. '성미·성깔'.", ex: { zh: "他的脾气很好。", pinyin: "tā de píqi hěn hǎo", ko: "그는 성격이 좋아요." } },
        { zh: "乒乓球", pinyin: "pīng pāng qiú", ko: "탁구", pos: "명사", hanja: "병방구(乒乓球) — '球'는 공 구. 소리를 본뜬 글자 + 공.", ex: { zh: "我们去打乒乓球吧。", pinyin: "wǒmen qù dǎ pīngpāngqiú ba", ko: "우리 탁구 치러 가요." } },
        { zh: "瓶子", pinyin: "píng zi", ko: "병", pos: "명사", hanja: "병자(瓶子) — '瓶'은 병 병.", ex: { zh: "桌上有一个瓶子。", pinyin: "zhuō shang yǒu yí ge píngzi", ko: "탁자 위에 병이 하나 있어요." } },
        { zh: "气候", pinyin: "qì hòu", ko: "기후", pos: "명사", hanja: "기후(氣候) — 한자 그대로.", ex: { zh: "这里的气候很好。", pinyin: "zhèlǐ de qìhòu hěn hǎo", ko: "이곳의 기후는 좋아요." } },
        { zh: "签证", pinyin: "qiān zhèng", ko: "비자, 사증", pos: "명사", hanja: "첨증(簽證) — '簽'은 서명할 첨, '證'은 증명할 증.", ex: { zh: "我在办签证。", pinyin: "wǒ zài bàn qiānzhèng", ko: "저는 비자를 발급받고 있어요." } },
        { zh: "桥", pinyin: "qiáo", ko: "다리, 교량", pos: "명사", hanja: "교(橋) — '다리 교'.", ex: { zh: "河上有一座桥。", pinyin: "hé shang yǒu yí zuò qiáo", ko: "강 위에 다리가 하나 있어요." } },
        { zh: "巧克力", pinyin: "qiǎo kè lì", ko: "초콜릿", pos: "명사", ex: { zh: "我送了她巧克力。", pinyin: "wǒ sòng le tā qiǎokèlì", ko: "저는 그녀에게 초콜릿을 선물했어요." } },
        { zh: "亲戚", pinyin: "qīn qi", ko: "친척", pos: "명사", hanja: "친척(親戚) — 한자 그대로.", ex: { zh: "过年我去看亲戚。", pinyin: "guònián wǒ qù kàn qīnqi", ko: "설에 저는 친척을 보러 가요." } },
        { zh: "情况", pinyin: "qíng kuàng", ko: "상황, 형편", pos: "명사", hanja: "정황(情況) — 한자 그대로.", ex: { zh: "请告诉我现在的情况。", pinyin: "qǐng gàosu wǒ xiànzài de qíngkuàng", ko: "지금 상황을 알려 주세요." } },
        { zh: "缺点", pinyin: "quē diǎn", ko: "단점, 결점", pos: "명사", hanja: "결점(缺點) — '缺'은 이지러질 결, '點'은 점 점.", ex: { zh: "每个人都有缺点。", pinyin: "měi ge rén dōu yǒu quēdiǎn", ko: "누구나 단점은 있어요." } },
        { zh: "群", pinyin: "qún", ko: "무리, 떼; (사람·동물을 세는) ~무리", pos: "명사", hanja: "군(群) — '무리 군'.", ex: { zh: "天上有一群鸟。", pinyin: "tiān shang yǒu yì qún niǎo", ko: "하늘에 새 떼가 있어요." } },
        { zh: "人民币", pinyin: "rén mín bì", ko: "인민폐, 위안화(중국 화폐)", pos: "명사", hanja: "인민폐(人民幣) — '幣'는 화폐 폐.", ex: { zh: "这里能用人民币吗？", pinyin: "zhèlǐ néng yòng rénmínbì ma", ko: "여기서 위안화를 쓸 수 있나요?" } },
        { zh: "日记", pinyin: "rì jì", ko: "일기", pos: "명사", hanja: "일기(日記) — 한자 그대로.", ex: { zh: "我每天写日记。", pinyin: "wǒ měi tiān xiě rìjì", ko: "저는 매일 일기를 써요." } },
        { zh: "入口", pinyin: "rù kǒu", ko: "입구", pos: "명사", hanja: "입구(入口) — 한자 그대로.", ex: { zh: "入口在那边。", pinyin: "rùkǒu zài nàbiān", ko: "입구는 저쪽이에요." } },
        { zh: "森林", pinyin: "sēn lín", ko: "숲, 삼림", pos: "명사", hanja: "삼림(森林) — '森'은 수풀 삼, '林'은 수풀 림.", ex: { zh: "森林里有很多动物。", pinyin: "sēnlín lǐ yǒu hěn duō dòngwù", ko: "숲속에는 동물이 많아요." } },
        { zh: "沙发", pinyin: "shā fā", ko: "소파", pos: "명사", ex: { zh: "他坐在沙发上。", pinyin: "tā zuò zài shāfā shang", ko: "그는 소파에 앉아 있어요." } },
        { zh: "师傅", pinyin: "shī fu", ko: "기사님, 사부(기술자에 대한 호칭)", pos: "명사", hanja: "사부(師傅) — '師'는 스승 사, '傅'는 스승 부.", ex: { zh: "师傅，请到机场。", pinyin: "shīfu, qǐng dào jīchǎng", ko: "기사님, 공항으로 가 주세요." } },
        { zh: "狮子", pinyin: "shī zi", ko: "사자", pos: "명사", hanja: "사자(獅子) — '獅'는 사자 사.", ex: { zh: "狮子是很危险的动物。", pinyin: "shīzi shì hěn wēixiǎn de dòngwù", ko: "사자는 위험한 동물이에요." } },
        { zh: "食品", pinyin: "shí pǐn", ko: "식품, 먹거리", pos: "명사", hanja: "식품(食品) — 한자 그대로.", ex: { zh: "这家店卖各种食品。", pinyin: "zhè jiā diàn mài gèzhǒng shípǐn", ko: "이 가게는 여러 식품을 팔아요." } },
        { zh: "世纪", pinyin: "shì jì", ko: "세기", pos: "명사", hanja: "세기(世紀) — 한자 그대로.", ex: { zh: "我们生活在二十一世纪。", pinyin: "wǒmen shēnghuó zài èrshíyī shìjì", ko: "우리는 21세기에 살고 있어요." } },
        { zh: "市场", pinyin: "shì chǎng", ko: "시장", pos: "명사", hanja: "시장(市場) — 한자 그대로.", ex: { zh: "我去市场买菜。", pinyin: "wǒ qù shìchǎng mǎi cài", ko: "저는 시장에 장 보러 가요." } },
        { zh: "首都", pinyin: "shǒu dū", ko: "수도", pos: "명사", hanja: "수도(首都) — 한자 그대로.", ex: { zh: "北京是中国的首都。", pinyin: "Běijīng shì Zhōngguó de shǒudū", ko: "베이징은 중국의 수도예요." } },
        { zh: "售货员", pinyin: "shòu huò yuán", ko: "판매원, 점원", pos: "명사", hanja: "수화원(售貨員) — '售'는 팔 수, '貨'는 재화 화, '員'은 인원 원.", ex: { zh: "售货员很热情。", pinyin: "shòuhuòyuán hěn rèqíng", ko: "점원이 친절해요." } },
        { zh: "数量", pinyin: "shù liàng", ko: "수량", pos: "명사", hanja: "수량(數量) — 한자 그대로.", ex: { zh: "请确认一下数量。", pinyin: "qǐng quèrèn yíxià shùliàng", ko: "수량을 확인해 주세요." } },
        { zh: "数字", pinyin: "shù zì", ko: "숫자", pos: "명사", hanja: "수자(數字) — '數'는 셈 수, '字'는 글자 자.", ex: { zh: "请写下这个数字。", pinyin: "qǐng xiě xià zhège shùzì", ko: "이 숫자를 적어 주세요." } },
        { zh: "顺序", pinyin: "shùn xù", ko: "순서, 차례", pos: "명사", hanja: "순서(順序) — 한자 그대로.", ex: { zh: "请按顺序进来。", pinyin: "qǐng àn shùnxù jìnlái", ko: "순서대로 들어오세요." } },
        { zh: "律师", pinyin: "lǜ shī", ko: "변호사", pos: "명사", hanja: "율사(律師) — '律'은 법 률, '師'는 스승 사.", ex: { zh: "他想当律师。", pinyin: "tā xiǎng dāng lǜshī", ko: "그는 변호사가 되고 싶어 해요." } },
        { zh: "实际", pinyin: "shí jì", ko: "실제; 실제적이다", pos: "명사", hanja: "실제(實際) — 한자 그대로.", ex: { zh: "实际情况比较复杂。", pinyin: "shíjì qíngkuàng bǐjiào fùzá", ko: "실제 상황은 좀 복잡해요." } },
      ],
    },
    {
      name: "HSK4 보강 — 형용사·상태",
      icon: "🔶",
      words: [
        { zh: "假", pinyin: "jiǎ", ko: "가짜의, 거짓의", pos: "형용사", hanja: "가(假) — '거짓 가'. 진짜(真)의 반대.", ex: { zh: "这是假的，不是真的。", pinyin: "zhè shì jiǎ de, bú shì zhēn de", ko: "이건 가짜예요, 진짜가 아니에요." } },
        { zh: "可怜", pinyin: "kě lián", ko: "불쌍하다, 가엾다; 불쌍히 여기다", pos: "형용사", hanja: "가련(可憐) — '可'는 옳을 가, '憐'은 불쌍히 여길 련.", ex: { zh: "那只小狗很可怜。", pinyin: "nà zhī xiǎo gǒu hěn kělián", ko: "저 강아지가 불쌍해요." } },
        { zh: "可惜", pinyin: "kě xī", ko: "아깝다, 아쉽다, 유감스럽다", pos: "형용사", hanja: "가석(可惜) — '惜'은 아낄 석. '아까워할 만하다'.", ex: { zh: "你不能来，太可惜了。", pinyin: "nǐ bù néng lái, tài kěxī le", ko: "당신이 못 온다니 너무 아쉬워요." } },
        { zh: "苦", pinyin: "kǔ", ko: "쓰다; 고생스럽다, 괴롭다", pos: "형용사", hanja: "고(苦) — '쓸 고'. 맛이 쓰고, 처지가 괴롭다.", ex: { zh: "这个药很苦。", pinyin: "zhège yào hěn kǔ", ko: "이 약은 써요." } },
        { zh: "宽", pinyin: "kuān", ko: "넓다, 폭이 넓다", pos: "형용사", hanja: "관(寬) — '너그러울 관·넓을 관'.", ex: { zh: "这条路很宽。", pinyin: "zhè tiáo lù hěn kuān", ko: "이 길은 넓어요." } },
        { zh: "困", pinyin: "kùn", ko: "졸리다; 곤란하다, 가두다", pos: "형용사", hanja: "곤(困) — '곤할 곤'. '곤란(困難)'의 곤.", ex: { zh: "我很困，想睡觉。", pinyin: "wǒ hěn kùn, xiǎng shuìjiào", ko: "저 졸려서 자고 싶어요." } },
        { zh: "辣", pinyin: "là", ko: "맵다", pos: "형용사", hanja: "랄(辣) — '매울 랄'.", ex: { zh: "这个菜太辣了。", pinyin: "zhège cài tài là le", ko: "이 음식은 너무 매워요." } },
        { zh: "懒", pinyin: "lǎn", ko: "게으르다, 나태하다", pos: "형용사", hanja: "라(懶) — '게으를 라'.", ex: { zh: "他太懒了，不想动。", pinyin: "tā tài lǎn le, bù xiǎng dòng", ko: "그는 너무 게을러서 움직이려 하지 않아요." } },
        { zh: "浪漫", pinyin: "làng màn", ko: "낭만적이다, 로맨틱하다", pos: "형용사", hanja: "낭만(浪漫) — 한자 그대로.", ex: { zh: "这个晚上很浪漫。", pinyin: "zhège wǎnshang hěn làngmàn", ko: "이 밤은 낭만적이에요." } },
        { zh: "冷静", pinyin: "lěng jìng", ko: "냉정하다, 침착하다", pos: "형용사", hanja: "냉정(冷靜) — '冷'은 찰 냉, '靜'은 고요할 정.", ex: { zh: "请你冷静一点。", pinyin: "qǐng nǐ lěngjìng yìdiǎn", ko: "좀 침착하세요." } },
        { zh: "礼貌", pinyin: "lǐ mào", ko: "예의 바르다; 예의, 예절", pos: "명사", hanja: "예모(禮貌) — '禮'는 예도 례, '貌'는 모양 모.", ex: { zh: "这个孩子很有礼貌。", pinyin: "zhège háizi hěn yǒu lǐmào", ko: "이 아이는 예의가 발라요." } },
        { zh: "厉害", pinyin: "lì hai", ko: "대단하다, 심하다, 엄청나다", pos: "형용사", hanja: "여해(厲害) — '厲'는 갈 려, '害'는 해할 해. 좋게도 나쁘게도 '대단하다'.", ex: { zh: "他打篮球很厉害。", pinyin: "tā dǎ lánqiú hěn lìhai", ko: "그는 농구를 엄청 잘해요." } },
        { zh: "凉快", pinyin: "liáng kuai", ko: "시원하다, 선선하다", pos: "형용사", hanja: "양쾌(涼快) — '涼'은 서늘할 량, '快'는 쾌할 쾌.", ex: { zh: "今天天气很凉快。", pinyin: "jīntiān tiānqì hěn liángkuai", ko: "오늘 날씨가 시원해요." } },
        { zh: "亮", pinyin: "liàng", ko: "밝다, 환하다", pos: "형용사", hanja: "량(亮) — '밝을 량'.", ex: { zh: "房间里很亮。", pinyin: "fángjiān lǐ hěn liàng", ko: "방 안이 밝아요." } },
        { zh: "乱", pinyin: "luàn", ko: "어지럽다, 무질서하다; 함부로", pos: "형용사", hanja: "란(亂) — '어지러울 란'. '혼란(混亂)'의 란.", ex: { zh: "房间太乱了。", pinyin: "fángjiān tài luàn le", ko: "방이 너무 어질러져 있어요." } },
        { zh: "麻烦", pinyin: "má fan", ko: "번거롭다, 귀찮다; 폐를 끼치다; 번거로움", pos: "형용사", hanja: "마번(麻煩) — '麻'는 삼 마, '煩'은 번거로울 번.", ex: { zh: "麻烦你帮我一下。", pinyin: "máfan nǐ bāng wǒ yíxià", ko: "번거롭지만 저 좀 도와주세요." } },
        { zh: "马虎", pinyin: "mǎ hu", ko: "덜렁대다, 대충대충 하다, 부주의하다", pos: "형용사", hanja: "마호(馬虎) — '馬'는 말 마, '虎'는 범 호. '대강 하다'.", ex: { zh: "做事不能太马虎。", pinyin: "zuò shì bù néng tài mǎhu", ko: "일을 너무 대충 하면 안 돼요." } },
        { zh: "满", pinyin: "mǎn", ko: "가득하다, 가득 차다", pos: "형용사", hanja: "만(滿) — '찰 만'. '만족(滿足)'의 만.", ex: { zh: "杯子里的水满了。", pinyin: "bēizi lǐ de shuǐ mǎn le", ko: "컵에 물이 가득 찼어요." } },
        { zh: "免费", pinyin: "miǎn fèi", ko: "무료이다, 무료의", pos: "형용사", hanja: "면비(免費) — '免'은 면할 면, '費'는 쓸 비. '비용을 면하다'.", ex: { zh: "这个软件是免费的。", pinyin: "zhège ruǎnjiàn shì miǎnfèi de", ko: "이 소프트웨어는 무료예요." } },
        { zh: "难受", pinyin: "nán shòu", ko: "(몸·마음이) 괴롭다, 견디기 힘들다", pos: "형용사", hanja: "난수(難受) — '難'은 어려울 난, '受'는 받을 수. '받아들이기 어렵다'.", ex: { zh: "我肚子很难受。", pinyin: "wǒ dùzi hěn nánshòu", ko: "저 배가 너무 아파요." } },
        { zh: "暖和", pinyin: "nuǎn huo", ko: "따뜻하다", pos: "형용사", hanja: "난화(暖和) — '暖'은 따뜻할 난, '和'는 화할 화.", ex: { zh: "春天到了，天气暖和了。", pinyin: "chūntiān dào le, tiānqì nuǎnhuo le", ko: "봄이 와서 날씨가 따뜻해졌어요." } },
        { zh: "破", pinyin: "pò", ko: "깨지다, 망가지다; 낡다", pos: "형용사", hanja: "파(破) — '깨뜨릴 파'. '파괴(破壞)'의 파.", ex: { zh: "我的鞋子破了。", pinyin: "wǒ de xiézi pò le", ko: "제 신발이 해졌어요." } },
        { zh: "普遍", pinyin: "pǔ biàn", ko: "보편적이다, 널리 퍼져 있다", pos: "형용사", hanja: "보편(普遍) — 한자 그대로.", ex: { zh: "这是很普遍的现象。", pinyin: "zhè shì hěn pǔbiàn de xiànxiàng", ko: "이건 아주 흔한 현상이에요." } },
        { zh: "穷", pinyin: "qióng", ko: "가난하다, 궁핍하다", pos: "형용사", hanja: "궁(窮) — '다할 궁·궁할 궁'. '빈궁(貧窮)'의 궁.", ex: { zh: "他小时候家里很穷。", pinyin: "tā xiǎoshíhou jiā lǐ hěn qióng", ko: "그는 어릴 때 집이 가난했어요." } },
        { zh: "轻", pinyin: "qīng", ko: "가볍다; 수월하다", pos: "형용사", hanja: "경(輕) — '가벼울 경'.", ex: { zh: "这个箱子很轻。", pinyin: "zhège xiāngzi hěn qīng", ko: "이 상자는 가벼워요." } },
        { zh: "轻松", pinyin: "qīng sōng", ko: "수월하다, 홀가분하다, 편안하다", pos: "형용사", hanja: "경송(輕鬆) — '輕'은 가벼울 경, '鬆'은 느슨할 송.", ex: { zh: "今天的工作很轻松。", pinyin: "jīntiān de gōngzuò hěn qīngsōng", ko: "오늘 일은 수월해요." } },
        { zh: "热闹", pinyin: "rè nao", ko: "북적이다, 떠들썩하다, 활기차다", pos: "형용사", hanja: "열뇨(熱鬧) — '熱'은 더울 열, '鬧'은 시끄러울 뇨.", ex: { zh: "这条街很热闹。", pinyin: "zhè tiáo jiē hěn rènao", ko: "이 거리는 북적여요." } },
        { zh: "软", pinyin: "ruǎn", ko: "부드럽다, 무르다, 푹신하다", pos: "형용사", hanja: "연(軟) — '연할 연'.", ex: { zh: "这张床很软。", pinyin: "zhè zhāng chuáng hěn ruǎn", ko: "이 침대는 푹신해요." } },
        { zh: "伤心", pinyin: "shāng xīn", ko: "슬프다, 마음 아프다", pos: "형용사", hanja: "상심(傷心) — '傷'은 다칠 상, '心'은 마음 심. '마음을 다치다'.", ex: { zh: "她哭得很伤心。", pinyin: "tā kū de hěn shāngxīn", ko: "그녀는 몹시 슬프게 울었어요." } },
        { zh: "深", pinyin: "shēn", ko: "깊다; (색이) 진하다", pos: "형용사", hanja: "심(深) — '깊을 심'. '심해(深海)'의 심.", ex: { zh: "这条河很深。", pinyin: "zhè tiáo hé hěn shēn", ko: "이 강은 깊어요." } },
        { zh: "湿润", pinyin: "shī rùn", ko: "축축하다, 촉촉하다", pos: "형용사", hanja: "습윤(濕潤) — '濕'은 젖을 습, '潤'은 불을 윤.", ex: { zh: "南方的空气很湿润。", pinyin: "nánfāng de kōngqì hěn shīrùn", ko: "남쪽 지방은 공기가 축축해요." } },
        { zh: "顺利", pinyin: "shùn lì", ko: "순조롭다", pos: "형용사", hanja: "순리(順利) — '順'은 순할 순, '利'는 이로울 리.", ex: { zh: "祝你工作顺利。", pinyin: "zhù nǐ gōngzuò shùnlì", ko: "일이 순조롭길 바라요." } },
        { zh: "帅", pinyin: "shuài", ko: "잘생기다, 멋지다", pos: "형용사", hanja: "수(帥) — '장수 수'. 구어로 '멋지다'를 뜻해요.", ex: { zh: "这个男生很帅。", pinyin: "zhège nánshēng hěn shuài", ko: "이 남학생은 잘생겼어요." } },
        { zh: "确实", pinyin: "què shí", ko: "확실하다; 확실히, 정말로", pos: "형용사", hanja: "확실(確實) — 한자 그대로.", ex: { zh: "这件事确实很难。", pinyin: "zhè jiàn shì quèshí hěn nán", ko: "이 일은 확실히 어려워요." } },
      ],
    },
    {
      name: "HSK4 보강 — 부사·기타",
      icon: "🔶",
      words: [
        { zh: "将来", pinyin: "jiāng lái", ko: "장래, 미래, 앞으로", pos: "명사", hanja: "장래(將來) — '將'은 장차 장, '來'는 올 래.", ex: { zh: "将来你想做什么？", pinyin: "jiānglái nǐ xiǎng zuò shénme", ko: "앞으로 뭘 하고 싶어요?" } },
        { zh: "尽管", pinyin: "jǐn guǎn", ko: "비록 ~일지라도; 얼마든지, 마음껏", pos: "접속사", hanja: "진관(儘管) — '비록 ~에도 불구하고'. 양보를 나타내요.", ex: { zh: "尽管很累，他还是来了。", pinyin: "jǐnguǎn hěn lèi, tā háishi lái le", ko: "비록 피곤해도 그는 왔어요." } },
        { zh: "究竟", pinyin: "jiū jìng", ko: "도대체; 결국, 자초지종", pos: "부사", hanja: "구경(究竟) — '究'는 궁구할 구, '竟'은 마침내 경. '도대체'.", ex: { zh: "你究竟想说什么？", pinyin: "nǐ jiūjìng xiǎng shuō shénme", ko: "도대체 무슨 말을 하고 싶은 거예요?" } },
        { zh: "棵", pinyin: "kē", ko: "그루, 포기 (식물을 세는 양사)", pos: "양사", hanja: "과(棵) — 나무·풀을 세는 양사.", ex: { zh: "院子里有两棵树。", pinyin: "yuànzi lǐ yǒu liǎng kē shù", ko: "마당에 나무 두 그루가 있어요." } },
        { zh: "肯定", pinyin: "kěn dìng", ko: "틀림없이, 확실히; 긍정하다, 인정하다", pos: "부사", hanja: "긍정(肯定) — '肯'은 즐길 긍, '定'은 정할 정.", ex: { zh: "他肯定会来。", pinyin: "tā kěndìng huì lái", ko: "그는 틀림없이 올 거예요." } },
        { zh: "恐怕", pinyin: "kǒng pà", ko: "아마 ~일 것이다, ~일까 걱정이다", pos: "부사", hanja: "공파(恐怕) — '恐'은 두려울 공, '怕'는 두려울 파. '아마 ~할까 봐'.", ex: { zh: "恐怕今天来不及了。", pinyin: "kǒngpà jīntiān lái bu jí le", ko: "아마 오늘은 시간이 안 될 것 같아요." } },
        { zh: "另外", pinyin: "lìng wài", ko: "그 밖에, 따로, 다른", pos: "접속사", hanja: "령외(另外) — '另'은 따로 령, '外'는 바깥 외.", ex: { zh: "另外，我还有一个问题。", pinyin: "lìngwài, wǒ hái yǒu yí ge wèntí", ko: "그 밖에, 저 질문이 하나 더 있어요." } },
        { zh: "俩", pinyin: "liǎ", ko: "두 사람, 둘 (两个의 구어)", pos: "수사", hanja: "량(倆) — '두 사람'을 한 단어로 줄인 구어 표현이에요.", ex: { zh: "我们俩是好朋友。", pinyin: "wǒmen liǎ shì hǎo péngyou", ko: "우리 둘은 친한 친구예요." } },
        { zh: "连", pinyin: "lián", ko: "~조차, ~까지도; 잇다, 연결하다", pos: "개사", hanja: "련(連) — '잇닿을 련'. '连…都/也…' 형태로 '~조차도'.", ex: { zh: "他连饭都没吃。", pinyin: "tā lián fàn dōu méi chī", ko: "그는 밥조차 안 먹었어요." } },
        { zh: "内", pinyin: "nèi", ko: "안, 내부, 이내", pos: "명사", hanja: "내(內) — '안 내'. 外(밖)의 반대.", ex: { zh: "请在一周内回复。", pinyin: "qǐng zài yì zhōu nèi huífù", ko: "일주일 내로 답해 주세요." } },
        { zh: "难道", pinyin: "nán dào", ko: "설마 ~란 말인가, 그래 ~란 말이야?", pos: "부사", hanja: "난도(難道) — 반문을 강조하는 부사예요. '설마'.", ex: { zh: "难道你不知道吗？", pinyin: "nándào nǐ bù zhīdào ma", ko: "설마 모르는 거예요?" } },
        { zh: "偶尔", pinyin: "ǒu ěr", ko: "이따금, 가끔, 어쩌다", pos: "부사", hanja: "우이(偶爾) — '偶'는 짝 우(우연), '爾'는 너 이.", ex: { zh: "我偶尔会去看电影。", pinyin: "wǒ ǒu'ěr huì qù kàn diànyǐng", ko: "저는 가끔 영화를 보러 가요." } },
        { zh: "篇", pinyin: "piān", ko: "편 (글·문장을 세는 양사)", pos: "양사", hanja: "편(篇) — '책 편'. 문장·글을 세요.", ex: { zh: "我写了一篇文章。", pinyin: "wǒ xiě le yì piān wénzhāng", ko: "저는 글 한 편을 썼어요." } },
        { zh: "平时", pinyin: "píng shí", ko: "평소, 평상시", pos: "명사", hanja: "평시(平時) — '平'은 평평할 평, '時'는 때 시.", ex: { zh: "我平时很少喝酒。", pinyin: "wǒ píngshí hěn shǎo hē jiǔ", ko: "저는 평소 술을 거의 안 마셔요." } },
        { zh: "其次", pinyin: "qí cì", ko: "그다음, 둘째로", pos: "접속사", hanja: "기차(其次) — '其'는 그 기, '次'는 버금 차. '그다음'.", ex: { zh: "首先要努力，其次要坚持。", pinyin: "shǒuxiān yào nǔlì, qícì yào jiānchí", ko: "우선 노력해야 하고, 그다음은 꾸준해야 해요." } },
        { zh: "其中", pinyin: "qí zhōng", ko: "그중, 그 가운데", pos: "대명사", hanja: "기중(其中) — '其'는 그 기, '中'은 가운데 중.", ex: { zh: "其中一个是我的。", pinyin: "qízhōng yí ge shì wǒ de", ko: "그중 하나는 제 거예요." } },
        { zh: "千万", pinyin: "qiān wàn", ko: "제발, 부디, 절대 (당부); 천만(1,000만)", pos: "부사", hanja: "천만(千萬) — 한자는 '천만'이지만 당부에서 '부디·절대'를 뜻해요.", ex: { zh: "你千万别迟到。", pinyin: "nǐ qiānwàn bié chídào", ko: "절대 늦지 마세요." } },
        { zh: "敲", pinyin: "qiāo", ko: "두드리다, (문을) 노크하다", pos: "동사", hanja: "고(敲) — '두드릴 고'.", ex: { zh: "有人在敲门。", pinyin: "yǒu rén zài qiāo mén", ko: "누가 문을 두드려요." } },
        { zh: "全部", pinyin: "quán bù", ko: "전부, 모두", pos: "명사", hanja: "전부(全部) — 한자 그대로.", ex: { zh: "这些书全部都是我的。", pinyin: "zhèxiē shū quánbù dōu shì wǒ de", ko: "이 책들은 전부 제 거예요." } },
        { zh: "却", pinyin: "què", ko: "오히려, 도리어, 그러나", pos: "부사", hanja: "각(卻) — '물리칠 각'. 예상과 다른 결과를 이어줘요.", ex: { zh: "他很累，却没有休息。", pinyin: "tā hěn lèi, què méiyǒu xiūxi", ko: "그는 피곤한데도 쉬지 않았어요." } },
        { zh: "仍然", pinyin: "réng rán", ko: "여전히, 변함없이", pos: "부사", hanja: "잉연(仍然) — '仍'은 인할 잉. '여전히'.", ex: { zh: "他仍然在等你。", pinyin: "tā réngrán zài děng nǐ", ko: "그는 여전히 당신을 기다리고 있어요." } },
        { zh: "任何", pinyin: "rèn hé", ko: "어떠한, 무슨 ~든지", pos: "대명사", hanja: "임하(任何) — '任'은 맡길 임, '何'는 어찌 하. '어떤 ~라도'.", ex: { zh: "任何人都可以参加。", pinyin: "rènhé rén dōu kěyǐ cānjiā", ko: "누구든지 참가할 수 있어요." } },
        { zh: "稍微", pinyin: "shāo wēi", ko: "조금, 약간", pos: "부사", hanja: "초미(稍微) — '稍'는 점점 초, '微'는 작을 미. '조금'.", ex: { zh: "请稍微等一下。", pinyin: "qǐng shāowēi děng yíxià", ko: "잠깐만 기다려 주세요." } },
        { zh: "甚至", pinyin: "shèn zhì", ko: "심지어, ~조차도", pos: "부사", hanja: "심지(甚至) — '甚'은 심할 심, '至'는 이를 지. '심지어'.", ex: { zh: "他忙得甚至忘了吃饭。", pinyin: "tā máng de shènzhì wàng le chī fàn", ko: "그는 바빠서 밥 먹는 것조차 잊었어요." } },
        { zh: "十分", pinyin: "shí fēn", ko: "매우, 충분히, 십분", pos: "부사", hanja: "십분(十分) — '10할 = 100%'에서 '매우'를 뜻해요.", ex: { zh: "我十分感谢你。", pinyin: "wǒ shífēn gǎnxiè nǐ", ko: "정말 감사드려요." } },
        { zh: "实在", pinyin: "shí zài", ko: "정말, 참으로; 착실하다, 진실하다", pos: "부사", hanja: "실재(實在) — '實'은 열매 실, '在'는 있을 재. '정말로'.", ex: { zh: "这件事我实在不知道。", pinyin: "zhè jiàn shì wǒ shízài bù zhīdào", ko: "이 일은 저도 정말 몰라요." } },
        { zh: "首先", pinyin: "shǒu xiān", ko: "우선, 먼저, 첫째로", pos: "접속사", hanja: "수선(首先) — '首'는 머리 수, '先'은 먼저 선.", ex: { zh: "首先，谢谢大家。", pinyin: "shǒuxiān, xièxie dàjiā", ko: "우선, 여러분께 감사드려요." } },
        { zh: "顺便", pinyin: "shùn biàn", ko: "~하는 김에, 겸사겸사", pos: "부사", hanja: "순편(順便) — '順'은 순할 순, '便'은 편할 편. '하는 김에'.", ex: { zh: "你出去顺便买点东西。", pinyin: "nǐ chūqù shùnbiàn mǎi diǎn dōngxi", ko: "나가는 김에 뭐 좀 사 와요." } },
        { zh: "距离", pinyin: "jù lí", ko: "거리, 간격; ~에서 떨어져 있다", pos: "명사", hanja: "거리(距離) — '距'는 떨어질 거, '離'는 떠날 리.", ex: { zh: "学校距离我家很近。", pinyin: "xuéxiào jùlí wǒ jiā hěn jìn", ko: "학교는 우리 집에서 가까워요." } },
      ],
    },
  ],
};
