/**
 * H4 (HSK 4급) HSK 3.0 표준 보강 어휘 — 공식 어휘표(drkameleon/complete-hsk-vocabulary, MIT)에서
 * 기존에 없던 454개를 채웠어요. 한자·병음·품사는 표준 데이터, 뜻·예문은 학습용으로 작성.
 */
const themes = {
  themes: [
    {
      name: "HSK4 3.0 보강",
      icon: "🟩",
      words: [
        { zh: "矮小", pinyin: "ǎixiǎo", ko: "작고 왜소하다", pos: "형용사", ex: { zh: "他身材矮小。", pinyin: "Tā shēn cái ǎi xiǎo.", ko: "그는 체격이 작고 왜소해요." } },
        { zh: "爱国", pinyin: "àiguó", ko: "애국의, 애국하다", pos: "형용사", ex: { zh: "他是一个爱国的人。", pinyin: "Tā shì yí gè ài guó de rén.", ko: "그는 애국하는 사람이에요." } },
        { zh: "安", pinyin: "ān", ko: "편안하게 하다, 설치하다", pos: "동사", ex: { zh: "他把心安了下来。", pinyin: "Tā bǎ xīn ān le xià lai.", ko: "그는 마음을 편안하게 가라앉혔어요." } },
        { zh: "安置", pinyin: "ānzhì", ko: "안치하다, 배치하다", pos: "동사", ex: { zh: "政府帮助他们安置新家。", pinyin: "Zhèng fǔ bāng zhù tā men ān zhì xīn jiā.", ko: "정부는 그들이 새 집에 정착하도록 도왔어요." } },
        { zh: "暗示", pinyin: "ànshì", ko: "암시하다", pos: "동사", ex: { zh: "他的话暗示了一些问题。", pinyin: "Tā de huà àn shì le yì xiē wèn tí.", ko: "그의 말은 몇 가지 문제를 암시했어요." } },
        { zh: "巴士", pinyin: "bāshì", ko: "버스", pos: "명사", ex: { zh: "我们坐巴士去机场。", pinyin: "Wǒ men zuò bā shì qù jī chǎng.", ko: "우리는 버스를 타고 공항에 가요." } },
        { zh: "百货", pinyin: "bǎihuò", ko: "잡화, 백화(상품)", pos: "명사", ex: { zh: "这家百货商店很大。", pinyin: "Zhè jiā bǎi huò shāng diàn hěn dà.", ko: "이 백화점은 매우 커요." } },
        { zh: "摆动", pinyin: "bǎidòng", ko: "흔들다, 흔들리다", pos: "동사", ex: { zh: "树枝在风中摆动。", pinyin: "Shù zhī zài fēng zhōng bǎi dòng.", ko: "나뭇가지가 바람에 흔들려요." } },
        { zh: "摆脱", pinyin: "bǎituō", ko: "벗어나다, 떨쳐버리다", pos: "동사", ex: { zh: "他终于摆脱了困境。", pinyin: "Tā zhōng yú bǎi tuō le kùn jìng.", ko: "그는 마침내 곤경에서 벗어났어요." } },
        { zh: "败", pinyin: "bài", ko: "지다, 패하다", pos: "동사", ex: { zh: "我们队败给了对手。", pinyin: "Wǒ men duì bài gěi le duì shǒu.", ko: "우리 팀은 상대에게 패했어요." } },
        { zh: "办事", pinyin: "bànshì", ko: "일을 처리하다", pos: "동사", ex: { zh: "他去银行办事了。", pinyin: "Tā qù yín háng bàn shì le.", ko: "그는 은행에 가서 일을 처리했어요." } },
        { zh: "宝", pinyin: "bǎo", ko: "보물", pos: "명사", ex: { zh: "这件文物是国家的宝。", pinyin: "Zhè jiàn wén wù shì guó jiā de bǎo.", ko: "이 문물은 국가의 보물이에요." } },
        { zh: "宝宝", pinyin: "bǎobao", ko: "아기, 애기", pos: "명사", ex: { zh: "她的宝宝很可爱。", pinyin: "Tā de bǎo bao hěn kě ài.", ko: "그녀의 아기는 매우 귀여워요." } },
        { zh: "宝石", pinyin: "bǎoshí", ko: "보석", pos: "명사", ex: { zh: "这枚戒指上镶着宝石。", pinyin: "Zhè méi jiè zhi shàng xiāng zhe bǎo shí.", ko: "이 반지에는 보석이 박혀 있어요." } },
        { zh: "保密", pinyin: "bǎomì", ko: "비밀을 지키다, 기밀로 하다", pos: "동사", ex: { zh: "这件事请你帮我保密。", pinyin: "Zhè jiàn shì qǐng nǐ bāng wǒ bǎo mì.", ko: "이 일은 비밀로 해주세요." } },
        { zh: "保守", pinyin: "bǎoshǒu", ko: "보수적이다", pos: "형용사", ex: { zh: "他的想法比较保守。", pinyin: "Tā de xiǎng fǎ bǐ jiào bǎo shǒu.", ko: "그의 생각은 비교적 보수적이에요." } },
        { zh: "被迫", pinyin: "bèipò", ko: "강요당하여, 어쩔 수 없이", pos: "부사", ex: { zh: "他被迫辞去了工作。", pinyin: "Tā bèi pò cí qù le gōng zuò.", ko: "그는 어쩔 수 없이 일을 그만두었어요." } },
        { zh: "比分", pinyin: "bǐfēn", ko: "점수(경기)", pos: "명사", ex: { zh: "现在的比分是二比一。", pinyin: "Xiàn zài de bǐ fēn shì èr bǐ yī.", ko: "현재 점수는 2대1예요." } },
        { zh: "毕业生", pinyin: "bìyèshēng", ko: "졸업생", pos: "명사", ex: { zh: "今年的毕业生找工作不容易。", pinyin: "Jīn nián de bì yè shēng zhǎo gōng zuò bù róng yì.", ko: "올해 졸업생들은 일자리 구하기가 쉽지 않아요." } },
        { zh: "避", pinyin: "bì", ko: "피하다", pos: "동사", ex: { zh: "他躲避着记者的提问。", pinyin: "Tā duǒ bì zhe jì zhě de tí wèn.", ko: "그는 기자의 질문을 피하고 있어요." } },
        { zh: "编", pinyin: "biān", ko: "짜다, 엮다, 편집하다", pos: "동사", ex: { zh: "她会编毛衣。", pinyin: "Tā huì biān máo yī.", ko: "그녀는 스웨터를 짤 줄 알아요." } },
        { zh: "冰", pinyin: "bīng", ko: "얼음", pos: "명사", ex: { zh: "湖面上结了一层冰。", pinyin: "Hú miàn shàng jié le yì céng bīng.", ko: "호수 표면에 얼음이 얼었어요." } },
        { zh: "冰雪", pinyin: "bīngxuě", ko: "얼음과 눈", pos: "명사", ex: { zh: "山顶上覆盖着冰雪。", pinyin: "Shān dǐng shàng fù gài zhe bīng xuě.", ko: "산꼭대기는 얼음과 눈으로 덮여 있어요." } },
        { zh: "兵", pinyin: "bīng", ko: "병사, 군인", pos: "명사", ex: { zh: "他年轻时当过兵。", pinyin: "Tā nián qīng shí dāng guo bīng.", ko: "그는 젊었을 때 군인이었어요." } },
        { zh: "不在乎", pinyin: "bùzàihu", ko: "개의치 않다, 신경 쓰지 않다", pos: "동사", ex: { zh: "他对别人的看法毫不在乎。", pinyin: "Tā duì bié rén de kàn fǎ háo bú zài hu.", ko: "그는 다른 사람의 시선에 전혀 개의치 않아요." } },
        { zh: "布置", pinyin: "bùzhì", ko: "배치하다, 꾸미다", pos: "동사", ex: { zh: "他们把房间布置得很漂亮。", pinyin: "Tā men bǎ fáng jiān bù zhì de hěn piào liang.", ko: "그들은 방을 예쁘게 꾸몄어요." } },
        { zh: "步行", pinyin: "bùxíng", ko: "걷다, 도보로 가다", pos: "동사", ex: { zh: "我每天步行上班。", pinyin: "Wǒ měi tiān bù xíng shàng bān.", ko: "나는 매일 걸어서 출근해요." } },
        { zh: "财富", pinyin: "cáifù", ko: "재산, 부", pos: "명사", ex: { zh: "健康是最大的财富。", pinyin: "Jiàn kāng shì zuì dà de cái fù.", ko: "건강이 가장 큰 재산이에요." } },
        { zh: "操作", pinyin: "cāozuò", ko: "조작하다, 운용하다", pos: "동사", ex: { zh: "这台机器很容易操作。", pinyin: "Zhè tái jī qì hěn róng yì cāo zuò.", ko: "이 기계는 조작하기 쉬워요." } },
        { zh: "测", pinyin: "cè", ko: "측정하다, 재다", pos: "동사", ex: { zh: "医生给他测了体温。", pinyin: "Yī shēng gěi tā cè le tǐ wēn.", ko: "의사가 그의 체온을 측정했어요." } },
        { zh: "测量", pinyin: "cèliáng", ko: "측량하다, 측정하다", pos: "동사", ex: { zh: "工人正在测量这块地的面积。", pinyin: "Gōng rén zhèng zài cè liáng zhè kuài dì de miàn jī.", ko: "인부들이 이 땅의 면적을 측량하고 있어요." } },
        { zh: "测试", pinyin: "cèshì", ko: "테스트하다, 시험하다", pos: "동사", ex: { zh: "这个软件还在测试阶段。", pinyin: "Zhè ge ruǎn jiàn hái zài cè shì jiē duàn.", ko: "이 소프트웨어는 아직 테스트 단계예요." } },
        { zh: "曾", pinyin: "céng", ko: "일찍이, ~한 적 있다", pos: "부사", ex: { zh: "我曾去过北京。", pinyin: "Wǒ céng qù guo Běijīng.", ko: "나는 일찍이 베이징에 가 본 적이 있어요." } },
        { zh: "茶叶", pinyin: "cháyè", ko: "찻잎, 차", pos: "명사", ex: { zh: "这种茶叶很香。", pinyin: "Zhè zhǒng chá yè hěn xiāng.", ko: "이 찻잎은 향이 좋아요." } },
        { zh: "唱片", pinyin: "chàngpiàn", ko: "음반, 레코드", pos: "명사", ex: { zh: "他收藏了很多老唱片。", pinyin: "Tā shōu cáng le hěn duō lǎo chàng piàn.", ko: "그는 많은 옛날 음반을 수집했어요." } },
        { zh: "抄写", pinyin: "chāoxiě", ko: "베끼다, 필사하다", pos: "동사", ex: { zh: "老师让我们抄写课文。", pinyin: "Lǎo shī ràng wǒ men chāo xiě kè wén.", ko: "선생님은 우리에게 본문을 베껴 쓰라고 하셨어요." } },
        { zh: "潮", pinyin: "cháo", ko: "조수, 파도, 유행", pos: "명사", ex: { zh: "海边涨潮了。", pinyin: "Hǎi biān zhǎng cháo le.", ko: "바닷가에 조수가 밀려왔어요." } },
        { zh: "潮流", pinyin: "cháoliú", ko: "조류, 트렌드, 유행", pos: "명사", ex: { zh: "这种穿衣风格很符合潮流。", pinyin: "Zhè zhǒng chuān yī fēng gé hěn fú hé cháo liú.", ko: "이런 옷차림 스타일은 유행에 잘 맞아요." } },
        { zh: "潮湿", pinyin: "cháoshī", ko: "습하다, 축축하다", pos: "형용사", ex: { zh: "南方的气候比较潮湿。", pinyin: "Nán fāng de qì hòu bǐ jiào cháo shī.", ko: "남방 지역의 기후는 비교적 습해요." } },
        { zh: "沉", pinyin: "chén", ko: "가라앉다, 침몰하다", pos: "동사", ex: { zh: "船慢慢沉入了海底。", pinyin: "Chuán màn màn chén rù le hǎi dǐ.", ko: "배가 천천히 바다 밑으로 가라앉았어요." } },
        { zh: "沉重", pinyin: "chénzhòng", ko: "무거운, 심각한", pos: "형용사", ex: { zh: "他的心情很沉重。", pinyin: "Tā de xīn qíng hěn chén zhòng.", ko: "그의 마음이 무거워요." } },
        { zh: "成人", pinyin: "chéngrén", ko: "성인, 어른", pos: "명사", ex: { zh: "这部电影只适合成人观看。", pinyin: "Zhè bù diàn yǐng zhǐ shì hé chéng rén guān kàn.", ko: "이 영화는 성인만 볼 수 있어요." } },
        { zh: "诚信", pinyin: "chéngxìn", ko: "성실, 신용", pos: "형용사", ex: { zh: "做生意要讲诚信。", pinyin: "Zuò shēng yì yào jiǎng chéng xìn.", ko: "사업을 할 때는 신용을 중시해야 해요." } },
        { zh: "尺", pinyin: "chǐ", ko: "자(길이 단위)", pos: "양사", ex: { zh: "这块布有三尺长。", pinyin: "Zhè kuài bù yǒu sān chǐ cháng.", ko: "이 천은 세 자 길이예요." } },
        { zh: "尺寸", pinyin: "chǐcun", ko: "사이즈, 치수", pos: "명사", ex: { zh: "这件衣服的尺寸正合适。", pinyin: "Zhè jiàn yī fu de chǐ cun zhèng hé shì.", ko: "이 옷의 사이즈가 딱 맞아요." } },
        { zh: "充电", pinyin: "chōngdiàn", ko: "충전하다", pos: "동사", ex: { zh: "我的手机需要充电。", pinyin: "Wǒ de shǒu jī xū yào chōng diàn.", ko: "내 휴대폰은 충전이 필요해요." } },
        { zh: "虫子", pinyin: "chóngzi", ko: "벌레", pos: "명사", ex: { zh: "花园里有很多虫子。", pinyin: "Huā yuán lǐ yǒu hěn duō chóng zi.", ko: "정원에 벌레가 많아요." } },
        { zh: "抽", pinyin: "chōu", ko: "뽑다, 빼내다", pos: "동사", ex: { zh: "他从口袋里抽出一张纸。", pinyin: "Tā cóng kǒu dai lǐ chōu chū yì zhāng zhǐ.", ko: "그는 주머니에서 종이 한 장을 꺼냈어요." } },
        { zh: "抽奖", pinyin: "chōujiǎng", ko: "추첨하다", pos: "동사", ex: { zh: "商场今天举行抽奖活动。", pinyin: "Shāng chǎng jīn tiān jǔ xíng chōu jiǎng huó dòng.", ko: "백화점에서 오늘 추첨 행사를 진행해요." } },
        { zh: "出售", pinyin: "chūshòu", ko: "판매하다", pos: "동사", ex: { zh: "这套房子正在出售。", pinyin: "Zhè tào fáng zi zhèng zài chū shòu.", ko: "이 집은 판매 중이에요." } },
        { zh: "处", pinyin: "chǔ", ko: "거주하다, 지내다", pos: "명사", ex: { zh: "我们相处得很好。", pinyin: "Wǒ men xiāng chǔ de hěn hǎo.", ko: "우리는 사이좋게 지내요." } },
        { zh: "处于", pinyin: "chǔyú", ko: "~에 처하다, ~한 상태에 있다", pos: "동사", ex: { zh: "公司目前处于困难时期。", pinyin: "Gōng sī mù qián chǔ yú kùn nan shí qī.", ko: "회사는 현재 어려운 시기에 처해 있어요." } },
        { zh: "穿上", pinyin: "chuānshang", ko: "(옷을) 입다", pos: "동사", ex: { zh: "快穿上外套，外面很冷。", pinyin: "Kuài chuān shang wài tào, wài miàn hěn lěng.", ko: "빨리 외투를 입어, 밖이 추워요." } },
        { zh: "窗台", pinyin: "chuāngtái", ko: "창턱", pos: "명사", ex: { zh: "花瓶放在窗台上。", pinyin: "Huā píng fàng zài chuāng tái shàng.", ko: "꽃병이 창턱 위에 놓여 있어요." } },
        { zh: "窗子", pinyin: "chuāngzi", ko: "창문", pos: "명사", ex: { zh: "请把窗子关上。", pinyin: "Qǐng bǎ chuāng zi guān shàng.", ko: "창문을 닫아 주세요." } },
        { zh: "春季", pinyin: "chūnjì", ko: "봄철", pos: "명사", ex: { zh: "春季气候温暖。", pinyin: "Chūn jì qì hòu wēn nuǎn.", ko: "봄철 기후는 따뜻해요." } },
        { zh: "纯", pinyin: "chún", ko: "순수한", pos: "형용사", ex: { zh: "这是纯棉的衣服。", pinyin: "Zhè shì chún mián de yī fu.", ko: "이것은 순면 옷이에요." } },
        { zh: "纯净水", pinyin: "chúnjìngshuǐ", ko: "정수, 생수", pos: "명사", ex: { zh: "请喝一瓶纯净水。", pinyin: "Qǐng hē yì píng chún jìng shuǐ.", ko: "생수 한 병 마셔 주세요." } },
        { zh: "词汇", pinyin: "cíhuì", ko: "어휘", pos: "명사", ex: { zh: "他的词汇量很大。", pinyin: "Tā de cí huì liàng hěn dà.", ko: "그의 어휘량은 매우 많아요." } },
        { zh: "此", pinyin: "cǐ", ko: "이, 이것", pos: "대명사", ex: { zh: "由此可见他很努力。", pinyin: "Yóu cǐ kě jiàn tā hěn nǔ lì.", ko: "이로써 그가 노력한다는 것을 알 수 있어요." } },
        { zh: "刺", pinyin: "cī", ko: "(의성어) 찍, 휙", pos: "동사", ex: { zh: "布被刺的一声撕开了。", pinyin: "Bù bèi \"cī\" de yì shēng sī kāi le.", ko: "천이 '찍' 소리를 내며 찢어졌어요." } },
        { zh: "粗", pinyin: "cū", ko: "굵은, 거친", pos: "형용사", ex: { zh: "这根绳子很粗。", pinyin: "Zhè gēn shéng zi hěn cū.", ko: "이 밧줄은 매우 굵어요." } },
        { zh: "促销", pinyin: "cùxiāo", ko: "판촉하다, 세일하다", pos: "동사", ex: { zh: "商店正在促销打折。", pinyin: "Shāng diàn zhèng zài cù xiāo dǎ zhé.", ko: "상점에서 판촉 할인을 하고 있어요." } },
        { zh: "打败", pinyin: "dǎbài", ko: "물리치다, 이기다", pos: "동사", ex: { zh: "我们打败了对手。", pinyin: "Wǒ men dǎ bài le duì shǒu.", ko: "우리는 상대를 물리쳤어요." } },
        { zh: "打雷", pinyin: "dǎléi", ko: "천둥이 치다", pos: "동사", ex: { zh: "外面正在打雷。", pinyin: "Wài miàn zhèng zài dǎ léi.", ko: "밖에서 천둥이 치고 있어요." } },
        { zh: "大巴", pinyin: "dàbā", ko: "대형 버스", pos: "명사", ex: { zh: "我们坐大巴去旅行。", pinyin: "Wǒ men zuò dà bā qù lǚ xíng.", ko: "우리는 대형 버스를 타고 여행 가요." } },
        { zh: "大多", pinyin: "dàduō", ko: "대부분", pos: "부사", ex: { zh: "学生大多喜欢体育课。", pinyin: "Xué sheng dà duō xǐ huan tǐ yù kè.", ko: "학생들은 대부분 체육 수업을 좋아해요." } },
        { zh: "大哥", pinyin: "dàgē", ko: "큰형", pos: "명사", ex: { zh: "我大哥比我大五岁。", pinyin: "Wǒ dà gē bǐ wǒ dà wǔ suì.", ko: "우리 큰형은 나보다 다섯 살 많아요." } },
        { zh: "大规模", pinyin: "dàguīmó", ko: "대규모의", pos: "형용사", ex: { zh: "政府进行了大规模改革。", pinyin: "Zhèng fǔ jìn xíng le dà guī mó gǎi gé.", ko: "정부는 대규모 개혁을 진행했어요." } },
        { zh: "大会", pinyin: "dàhuì", ko: "대회, 총회", pos: "명사", ex: { zh: "明天召开股东大会。", pinyin: "Míng tiān zhào kāi gǔ dōng dà huì.", ko: "내일 주주 총회가 열려요." } },
        { zh: "大姐", pinyin: "dàjiě", ko: "큰누나, 맏언니", pos: "명사", ex: { zh: "大姐对我很好。", pinyin: "Dà jiě duì wǒ hěn hǎo.", ko: "큰언니는 나에게 잘해줘요." } },
        { zh: "大楼", pinyin: "dàlóu", ko: "빌딩, 건물", pos: "명사", ex: { zh: "这座大楼有三十层。", pinyin: "Zhè zuò dà lóu yǒu sān shí céng.", ko: "이 빌딩은 30층이에요." } },
        { zh: "大陆", pinyin: "dàlù", ko: "대륙", pos: "명사", ex: { zh: "欧洲大陆的气候很多样。", pinyin: "Ōuzhōu dàlù de qìhòu hěn duōyàng.", ko: "유럽 대륙의 기후는 다양해요." } },
        { zh: "大妈", pinyin: "dàmā", ko: "아주머니, 큰어머니", pos: "명사", ex: { zh: "楼下的大妈很热情。", pinyin: "Lóu xià de dà mā hěn rè qíng.", ko: "아래층 아주머니는 매우 친절해요." } },
        { zh: "大爷", pinyin: "dàyé", ko: "거만한 사람, 어르신", pos: "명사", ex: { zh: "他像个大爷一样指挥别人。", pinyin: "Tā xiàng gè dà yé yí yàng zhǐ huī bié rén.", ko: "그는 마치 거만한 사람처럼 다른 사람을 부려요." } },
        { zh: "袋", pinyin: "dài", ko: "자루, 봉지, 포대", pos: "양사", ex: { zh: "我买了一袋米。", pinyin: "Wǒ mǎi le yí dài mǐ.", ko: "나는 쌀 한 포대를 샀어요." } },
        { zh: "单", pinyin: "dān", ko: "단일한, 홑", pos: "형용사", ex: { zh: "他单独完成了这个任务。", pinyin: "Tā dāndú wánchéng le zhège rènwù.", ko: "그는 혼자서 이 임무를 완성했어요." } },
        { zh: "担保", pinyin: "dānbǎo", ko: "보증하다", pos: "동사", ex: { zh: "他为朋友担保贷款。", pinyin: "Tā wèi péng you dān bǎo dài kuǎn.", ko: "그는 친구를 위해 대출을 보증했어요." } },
        { zh: "倒闭", pinyin: "dǎobì", ko: "도산하다, 파산하다", pos: "동사", ex: { zh: "那家公司去年倒闭了。", pinyin: "Nà jiā gōng sī qù nián dǎo bì le.", ko: "그 회사는 작년에 도산했어요." } },
        { zh: "倒车", pinyin: "dǎochē", ko: "(버스, 기차 등을) 갈아타다, 후진하다", pos: "동사", ex: { zh: "我们需要在北京倒车。", pinyin: "Wǒ men xū yào zài Běi jīng dǎo chē.", ko: "우리는 베이징에서 갈아타야 해요." } },
        { zh: "地面", pinyin: "dìmiàn", ko: "지면, 바닥", pos: "명사", ex: { zh: "地面上有很多落叶。", pinyin: "Dìmiàn shàng yǒu hěn duō luòyè.", ko: "지면에 낙엽이 많이 있어요." } },
        { zh: "地下", pinyin: "dìxià", ko: "지하의, 지하", pos: "명사", ex: { zh: "停车场在地下。", pinyin: "Tíngchēchǎng zài dìxià.", ko: "주차장은 지하에 있어요." } },
        { zh: "灯光", pinyin: "dēngguāng", ko: "조명, 불빛", pos: "명사", ex: { zh: "舞台上的灯光很漂亮。", pinyin: "Wǔtái shàng de dēngguāng hěn piàoliang.", ko: "무대 위의 조명이 매우 아름다워요." } },
        { zh: "登", pinyin: "dēng", ko: "오르다, 등반하다", pos: "동사", ex: { zh: "他们决定登山顶。", pinyin: "Tāmen juédìng dēng shāndǐng.", ko: "그들은 산 정상에 오르기로 결정했어요." } },
        { zh: "登录", pinyin: "dēnglù", ko: "로그인하다, 등록하다", pos: "동사", ex: { zh: "请输入密码登录账号。", pinyin: "Qǐng shūrù mìmǎ dēnglù zhànghào.", ko: "비밀번호를 입력하여 계정에 로그인해 주세요." } },
        { zh: "登山", pinyin: "dēngshān", ko: "등산하다", pos: "동사", ex: { zh: "周末我们一起去登山。", pinyin: "Zhōumò wǒmen yìqǐ qù dēngshān.", ko: "주말에 우리는 함께 등산하러 가요." } },
        { zh: "典型", pinyin: "diǎnxíng", ko: "전형, 모범", pos: "명사", ex: { zh: "他是一个典型的例子。", pinyin: "Tā shì yí gè diǎnxíng de lìzi.", ko: "그는 하나의 전형적인 사례예요." } },
        { zh: "点名", pinyin: "diǎnmíng", ko: "출석을 부르다, 이름을 지목하다", pos: "동사", ex: { zh: "老师正在点名。", pinyin: "Lǎoshī zhèngzài diǎnmíng.", ko: "선생님이 출석을 부르고 있어요." } },
        { zh: "电灯", pinyin: "diàndēng", ko: "전등", pos: "명사", ex: { zh: "请打开电灯。", pinyin: "Qǐng dǎkāi diàndēng.", ko: "전등을 켜 주세요." } },
        { zh: "电动车", pinyin: "diàndòngchē", ko: "전동차, 전기 자전거", pos: "명사", ex: { zh: "他每天骑电动车上班。", pinyin: "Tā měitiān qí diàndòngchē shàngbān.", ko: "그는 매일 전동차를 타고 출근해요." } },
        { zh: "电源", pinyin: "diànyuán", ko: "전원", pos: "명사", ex: { zh: "请关掉电脑的电源。", pinyin: "Qǐng guān diào diànnǎo de diànyuán.", ko: "컴퓨터 전원을 꺼 주세요." } },
        { zh: "定", pinyin: "dìng", ko: "정하다, 결정하다", pos: "동사", ex: { zh: "我们已经定好了计划。", pinyin: "Wǒmen yǐjīng dìng hǎo le jìhuà.", ko: "우리는 이미 계획을 정했어요." } },
        { zh: "冬季", pinyin: "dōngjì", ko: "겨울철", pos: "명사", ex: { zh: "冬季这里经常下雪。", pinyin: "Dōngjì zhèlǐ jīngcháng xià xuě.", ko: "겨울철에는 이곳에 자주 눈이 내려요." } },
        { zh: "动摇", pinyin: "dòngyáo", ko: "흔들리다, 동요하다", pos: "동사", ex: { zh: "他的决心没有动摇。", pinyin: "Tā de juéxīn méiyǒu dòngyáo.", ko: "그의 결심은 흔들리지 않았어요." } },
        { zh: "独自", pinyin: "dúzì", ko: "홀로, 혼자서", pos: "부사", ex: { zh: "她独自一人去了旅行。", pinyin: "Tā dúzì yì rén qù le lǚxíng.", ko: "그녀는 홀로 여행을 떠났어요." } },
        { zh: "堵", pinyin: "dǔ", ko: "막다, 막히다", pos: "동사", ex: { zh: "路上堵车堵得很厉害。", pinyin: "Lù shàng dǔchē dǔ de hěn lìhài.", ko: "길에서 차가 심하게 막혔어요." } },
        { zh: "对付", pinyin: "duìfu", ko: "대처하다, 대응하다", pos: "동사", ex: { zh: "我们要想办法对付这个问题。", pinyin: "Wǒmen yào xiǎng bànfǎ duìfu zhège wèntí.", ko: "우리는 이 문제에 대처할 방법을 생각해야 해요." } },
        { zh: "多次", pinyin: "duōcì", ko: "여러 번", pos: "부사", ex: { zh: "他多次提醒我要注意安全。", pinyin: "Tā duō cì tíxǐng wǒ yào zhùyì ānquán.", ko: "그는 여러 번 나에게 안전에 유의하라고 알려주었어요." } },
        { zh: "多年", pinyin: "duōnián", ko: "여러 해, 다년간", pos: "명사", ex: { zh: "他们已经认识多年了。", pinyin: "Tāmen yǐjīng rènshi duō nián le.", ko: "그들은 이미 여러 해 동안 알고 지냈어요." } },
        { zh: "多样", pinyin: "duōyàng", ko: "다양하다", pos: "수사", ex: { zh: "这里的商品种类多样。", pinyin: "Zhèlǐ de shāngpǐn zhǒnglèi duōyàng.", ko: "이곳의 상품 종류는 다양해요." } },
        { zh: "多种", pinyin: "duōzhǒng", ko: "여러 종류의, 다양한", pos: "수사", ex: { zh: "这家超市有多种水果。", pinyin: "Zhè jiā chāoshì yǒu duō zhǒng shuǐguǒ.", ko: "이 마트에는 여러 종류의 과일이 있어요." } },
        { zh: "恶心", pinyin: "ěxīn", ko: "메스껍다, 역겹다", pos: "형용사", ex: { zh: "我坐船的时候觉得恶心。", pinyin: "Wǒ zuò chuán de shíhou juéde ě xīn.", ko: "나는 배를 탈 때 메스꺼움을 느꼈어요." } },
        { zh: "而是", pinyin: "érshì", ko: "~이 아니라 (오히려)", pos: "접속사", ex: { zh: "他不是老师，而是学生。", pinyin: "Tā bú shì lǎoshī, ér shì xuésheng.", ko: "그는 선생님이 아니라 학생이에요." } },
        { zh: "耳机", pinyin: "ěrjī", ko: "이어폰, 헤드폰", pos: "명사", ex: { zh: "他戴着耳机听音乐。", pinyin: "Tā dài zhe ěrjī tīng yīnyuè.", ko: "그는 이어폰을 끼고 음악을 들어요." } },
        { zh: "二手", pinyin: "èrshǒu", ko: "중고의", pos: "형용사", ex: { zh: "他买了一辆二手车。", pinyin: "Tā mǎi le yí liàng èrshǒu chē.", ko: "그는 중고차 한 대를 샀어요." } },
        { zh: "法", pinyin: "fǎ", ko: "법, 방법", pos: "명사", ex: { zh: "这是解决问题的好办法。", pinyin: "Zhè shì jiějué wèntí de hǎo fǎ.", ko: "이것은 문제를 해결하는 좋은 방법이에요." } },
        { zh: "法官", pinyin: "fǎguān", ko: "법관, 판사", pos: "명사", ex: { zh: "法官宣布了判决结果。", pinyin: "Fǎguān xuānbù le pànjué jiéguǒ.", ko: "판사가 판결 결과를 선고했어요." } },
        { zh: "烦", pinyin: "fán", ko: "귀찮다, 성가시다, 번거롭다", pos: "동사", ex: { zh: "这件事让我很烦。", pinyin: "Zhè jiàn shì ràng wǒ hěn fán.", ko: "이 일은 나를 매우 귀찮게 해요." } },
        { zh: "反", pinyin: "fǎn", ko: "반대하다, 뒤집다", pos: "동사", ex: { zh: "他反对这个计划。", pinyin: "Tā fǎnduì zhège jìhuà.", ko: "그는 이 계획에 반대해요." } },
        { zh: "方针", pinyin: "fāngzhēn", ko: "방침", pos: "명사", ex: { zh: "公司制定了新的方针。", pinyin: "Gōngsī zhìdìng le xīn de fāngzhēn.", ko: "회사는 새로운 방침을 제정했어요." } },
        { zh: "肥", pinyin: "féi", ko: "살찌다, 기름지다, 비료", pos: "명사", ex: { zh: "这块地很肥。", pinyin: "Zhè kuài dì hěn féi.", ko: "이 땅은 매우 기름져요." } },
        { zh: "分散", pinyin: "fēnsàn", ko: "분산하다, 흩어지다", pos: "동사", ex: { zh: "大家的注意力分散了。", pinyin: "Dàjiā de zhùyìlì fēnsàn le.", ko: "모두의 주의력이 분산되었어요." } },
        { zh: "分手", pinyin: "fēnshǒu", ko: "헤어지다", pos: "동사", ex: { zh: "他们上个月分手了。", pinyin: "Tāmen shàng gè yuè fēnshǒu le.", ko: "그들은 지난달에 헤어졌어요." } },
        { zh: "分为", pinyin: "fēnwéi", ko: "~로 나뉘다", pos: "동사", ex: { zh: "这本书分为三个部分。", pinyin: "Zhè běn shū fēn wéi sān gè bùfen.", ko: "이 책은 세 부분으로 나뉘어요." } },
        { zh: "封闭", pinyin: "fēngbì", ko: "폐쇄하다, 봉쇄하다", pos: "동사", ex: { zh: "这条路已经封闭了。", pinyin: "Zhè tiáo lù yǐjīng fēngbì le.", ko: "이 길은 이미 폐쇄되었어요." } },
        { zh: "符号", pinyin: "fúhào", ko: "부호, 기호", pos: "명사", ex: { zh: "请写出正确的数学符号。", pinyin: "Qǐng xiě chū zhèngquè de shùxué fúhào.", ko: "정확한 수학 기호를 써 주세요." } },
        { zh: "付出", pinyin: "fùchū", ko: "지불하다, (노력을) 들이다", pos: "동사", ex: { zh: "他为这个项目付出了很多努力。", pinyin: "Tā wèi zhège xiàngmù fùchū le hěn duō nǔlì.", ko: "그는 이 프로젝트를 위해 많은 노력을 들였어요." } },
        { zh: "负担", pinyin: "fùdān", ko: "부담", pos: "명사", ex: { zh: "学费给家庭带来了负担。", pinyin: "Xuéfèi gěi jiātíng dàilái le fùdān.", ko: "학비는 가정에 부담을 가져다주었어요." } },
        { zh: "夫妇", pinyin: "fūfù", ko: "부부", pos: "명사", ex: { zh: "这对夫妇结婚十年了。", pinyin: "Zhè duì fūfù jiéhūn shí nián le.", ko: "이 부부는 결혼한 지 10년이 되었어요." } },
        { zh: "夫妻", pinyin: "fūqī", ko: "부부", pos: "명사", ex: { zh: "他们是一对幸福的夫妻。", pinyin: "Tāmen shì yí duì xìngfú de fūqī.", ko: "그들은 행복한 부부예요." } },
        { zh: "夫人", pinyin: "fūren", ko: "부인", pos: "명사", ex: { zh: "校长和他的夫人来了。", pinyin: "Xiàozhǎng hé tā de fūren lái le.", ko: "교장 선생님과 그의 부인이 오셨어요." } },
        { zh: "感兴趣", pinyin: "gǎnxìngqù", ko: "관심이 있다, 흥미를 느끼다", pos: "형용사", ex: { zh: "我对音乐很感兴趣。", pinyin: "Wǒ duì yīnyuè hěn gǎn xìngqù.", ko: "나는 음악에 관심이 많아요." } },
        { zh: "高潮", pinyin: "gāocháo", ko: "절정, 고조, 클라이맥스", pos: "명사", ex: { zh: "比赛进入了高潮。", pinyin: "Bǐsài jìnrùle gāocháo.", ko: "경기가 절정에 이르렀어요." } },
        { zh: "高价", pinyin: "gāojià", ko: "고가, 비싼 값", pos: "명사", ex: { zh: "他以高价卖出了房子。", pinyin: "Tā yǐ gāojià màichūle fángzi.", ko: "그는 비싼 값에 집을 팔았어요." } },
        { zh: "高尚", pinyin: "gāoshàng", ko: "고상하다, 고귀하다", pos: "형용사", ex: { zh: "他品德高尚。", pinyin: "Tā pǐndé gāoshàng.", ko: "그는 인품이 고상해요." } },
        { zh: "高铁", pinyin: "gāotiě", ko: "고속철도", pos: "명사", ex: { zh: "我坐高铁去上海。", pinyin: "Wǒ zuò gāotiě qù Shànghǎi.", ko: "나는 고속철도를 타고 상하이에 가요." } },
        { zh: "隔", pinyin: "gé", ko: "사이를 두다, 떨어지다, 간격을 두다", pos: "동사", ex: { zh: "他们家隔一条街。", pinyin: "Tāmen jiā gé yì tiáo jiē.", ko: "그들의 집은 길 하나를 사이에 두고 있어요." } },
        { zh: "隔开", pinyin: "gékāi", ko: "떼어 놓다, 분리하다", pos: "동사", ex: { zh: "把两张桌子隔开。", pinyin: "Bǎ liǎng zhāng zhuōzi gékāi.", ko: "두 책상을 떼어 놓아라." } },
        { zh: "个体", pinyin: "gètǐ", ko: "개체, 개인", pos: "명사", ex: { zh: "每个个体都不一样。", pinyin: "Měi gè gètǐ dōu bù yíyàng.", ko: "모든 개체는 다 달라요." } },
        { zh: "各个", pinyin: "gègè", ko: "각각, 여러", pos: "대명사", ex: { zh: "各个国家的文化都不同。", pinyin: "Gège guójiā de wénhuà dōu bùtóng.", ko: "각 나라의 문화는 모두 달라요." } },
        { zh: "工程", pinyin: "gōngchéng", ko: "공정, 프로젝트, 공학", pos: "명사", ex: { zh: "这项工程很大。", pinyin: "Zhè xiàng gōngchéng hěn dà.", ko: "이 프로젝트는 규모가 커요." } },
        { zh: "供应", pinyin: "gōngyìng", ko: "공급하다", pos: "동사", ex: { zh: "工厂供应原材料。", pinyin: "Gōngchǎng gōngyìng yuáncáiliào.", ko: "공장이 원자재를 공급해요." } },
        { zh: "共", pinyin: "gòng", ko: "모두, 다 함께, 합계", pos: "부사", ex: { zh: "我们共花了一百元。", pinyin: "Wǒmen gòng huāle yìbǎi yuán.", ko: "우리는 합계 100위안을 썼어요." } },
        { zh: "构造", pinyin: "gòuzào", ko: "구조", pos: "명사", ex: { zh: "这台机器构造复杂。", pinyin: "Zhè tái jīqì gòuzào fùzá.", ko: "이 기계는 구조가 복잡해요." } },
        { zh: "购买", pinyin: "gòumǎi", ko: "구매하다", pos: "동사", ex: { zh: "顾客可以在网上购买商品。", pinyin: "Gùkè kěyǐ zài wǎngshàng gòumǎi shāngpǐn.", ko: "고객은 온라인에서 상품을 구매할 수 있어요." } },
        { zh: "瓜", pinyin: "guā", ko: "오이, 참외류(외 종류의 총칭)", pos: "명사", ex: { zh: "夏天吃西瓜很爽快。", pinyin: "Xiàtiān chī xīguā hěn shuǎngkuai.", ko: "여름에 수박을 먹으면 정말 시원해요." } },
        { zh: "怪", pinyin: "guài", ko: "이상하다, 탓하다", pos: "동사", ex: { zh: "这件事很怪。", pinyin: "Zhè jiàn shì hěn guài.", ko: "이 일은 참 이상해요." } },
        { zh: "官方", pinyin: "guānfāng", ko: "관방, 공식(정부측)", pos: "명사", ex: { zh: "这是官方的消息。", pinyin: "Zhè shì guānfāng de xiāoxi.", ko: "이것은 공식적인 소식이에요." } },
        { zh: "归", pinyin: "guī", ko: "돌아가다, ~에 속하다", pos: "동사", ex: { zh: "这本书归图书馆所有。", pinyin: "Zhè běn shū guī túshūguǎn suǒyǒu.", ko: "이 책은 도서관 소유예요." } },
        { zh: "海水", pinyin: "hǎishuǐ", ko: "바닷물", pos: "명사", ex: { zh: "海水是咸的。", pinyin: "Hǎishuǐ shì xián de.", ko: "바닷물은 짜요." } },
        { zh: "含", pinyin: "hán", ko: "포함하다, 머금다", pos: "동사", ex: { zh: "这种饮料含糖量很高。", pinyin: "Zhè zhǒng yǐnliào hán táng liàng hěn gāo.", ko: "이 음료는 당 함유량이 매우 높아요." } },
        { zh: "含量", pinyin: "hánliàng", ko: "함량", pos: "명사", ex: { zh: "这个水果的维生素含量很高。", pinyin: "Zhège shuǐguǒ de wéishēngsù hánliàng hěn gāo.", ko: "이 과일은 비타민 함량이 높아요." } },
        { zh: "含义", pinyin: "hányì", ko: "함의, 내포된 뜻", pos: "명사", ex: { zh: "这句话的含义很深。", pinyin: "Zhè jù huà de hányì hěn shēn.", ko: "이 말의 함의는 매우 깊어요." } },
        { zh: "含有", pinyin: "hányǒu", ko: "함유하다, 포함하다", pos: "동사", ex: { zh: "牛奶含有丰富的蛋白质。", pinyin: "Niúnǎi hányǒu fēngfù de dànbáizhì.", ko: "우유는 풍부한 단백질을 함유하고 있어요." } },
        { zh: "寒冷", pinyin: "hánlěng", ko: "한랭하다, 몹시 춥다", pos: "형용사", ex: { zh: "北方的冬天非常寒冷。", pinyin: "Běifāng de dōngtiān fēicháng hánlěng.", ko: "북방의 겨울은 매우 추워요." } },
        { zh: "航空", pinyin: "hángkōng", ko: "항공", pos: "명사", ex: { zh: "他在航空公司工作。", pinyin: "Tā zài hángkōng gōngsī gōngzuò.", ko: "그는 항공사에서 일해요." } },
        { zh: "毫米", pinyin: "háomǐ", ko: "밀리미터(mm)", pos: "양사", ex: { zh: "这张纸厚零点一毫米。", pinyin: "Zhè zhāng zhǐ hòu líng diǎn yī háomǐ.", ko: "이 종이는 두께가 0.1밀리미터예요." } },
        { zh: "毫升", pinyin: "háoshēng", ko: "밀리리터(mL)", pos: "양사", ex: { zh: "这瓶水是五百毫升。", pinyin: "Zhè píng shuǐ shì wǔbǎi háoshēng.", ko: "이 물병은 500밀리리터예요." } },
        { zh: "好友", pinyin: "hǎoyǒu", ko: "친한 친구", pos: "명사", ex: { zh: "她是我的好友。", pinyin: "Tā shì wǒ de hǎoyǒu.", ko: "그녀는 나의 친한 친구예요." } },
        { zh: "黑暗", pinyin: "hēiàn", ko: "어둡다, 암흑", pos: "형용사", ex: { zh: "房间里一片黑暗。", pinyin: "Fángjiān lǐ yí piàn hēi'àn.", ko: "방 안은 온통 어둠뿐이에요." } },
        { zh: "红包", pinyin: "hóngbāo", ko: "세뱃돈, 홍바오(축의금 봉투)", pos: "명사", ex: { zh: "过年的时候长辈会给红包。", pinyin: "Guònián de shíhou zhǎngbèi huì gěi hóngbāo.", ko: "설날에는 어른들이 세뱃돈을 주세요." } },
        { zh: "后头", pinyin: "hòutou", ko: "뒤, 뒤쪽", pos: "명사", ex: { zh: "他站在我后头。", pinyin: "Tā zhàn zài wǒ hòutou.", ko: "그는 내 뒤에 서 있어요." } },
        { zh: "户", pinyin: "hù", ko: "가구, 세대", pos: "양사", ex: { zh: "这个小区有三百户。", pinyin: "Zhège xiǎoqū yǒu sānbǎi hù.", ko: "이 단지에는 300세대가 있어요." } },
        { zh: "划", pinyin: "huá", ko: "(배를) 젓다", pos: "동사", ex: { zh: "他们在湖上划船。", pinyin: "Tāmen zài hú shàng huá chuán.", ko: "그들은 호수에서 배를 저어요." } },
        { zh: "回复", pinyin: "huífù", ko: "회신하다, 답장하다", pos: "동사", ex: { zh: "请尽快回复我的邮件。", pinyin: "Qǐng jǐnkuài huífù wǒ de yóujiàn.", ko: "제 메일에 빨리 답장해 주세요." } },
        { zh: "汇", pinyin: "huì", ko: "송금하다, 모이다", pos: "동사", ex: { zh: "我给他汇了一笔钱。", pinyin: "Wǒ gěi tā huìle yì bǐ qián.", ko: "나는 그에게 돈을 좀 송금했어요." } },
        { zh: "汇报", pinyin: "huìbào", ko: "보고하다", pos: "동사", ex: { zh: "他向经理汇报了工作情况。", pinyin: "Tā xiàng jīnglǐ huìbàole gōngzuò qíngkuàng.", ko: "그는 매니저에게 업무 상황을 보고했어요." } },
        { zh: "伙", pinyin: "huǒ", ko: "패거리, 무리(양사)", pos: "양사", ex: { zh: "一伙人在门口等着。", pinyin: "Yì huǒ rén zài ménkǒu děngzhe.", ko: "한 무리의 사람들이 입구에서 기다리고 있어요." } },
        { zh: "或许", pinyin: "huòxǔ", ko: "아마도, 어쩌면", pos: "부사", ex: { zh: "他或许已经知道了。", pinyin: "Tā huòxǔ yǐjīng zhīdào le.", ko: "그는 어쩌면 이미 알고 있을지도 몰라요." } },
        { zh: "货", pinyin: "huò", ko: "물품, 상품", pos: "명사", ex: { zh: "这批货已经到了。", pinyin: "Zhè pī huò yǐjīng dào le.", ko: "이 물품은 이미 도착했어요." } },
        { zh: "获", pinyin: "huò", ko: "얻다, 획득하다", pos: "동사", ex: { zh: "今年农民喜获丰收。", pinyin: "jīn nián nóng mín xǐ huò fēng shōu.", ko: "올해 농민들은 기쁘게도 풍작을 거두었어요." } },
        { zh: "获奖", pinyin: "huòjiǎng", ko: "상을 받다, 수상하다", pos: "동사", ex: { zh: "这部电影获奖无数。", pinyin: "zhè bù diàn yǐng huò jiǎng wú shù.", ko: "이 영화는 수많은 상을 받았어요." } },
        { zh: "获取", pinyin: "huòqǔ", ko: "얻다, 획득하다", pos: "동사", ex: { zh: "我们可以通过网络获取信息。", pinyin: "wǒ men kě yǐ tōng guò wǎng luò huò qǔ xìn xī.", ko: "우리는 인터넷을 통해 정보를 얻을 수 있어요." } },
        { zh: "机构", pinyin: "jīgòu", ko: "기구, 기관", pos: "명사", ex: { zh: "这家机构专门帮助失业人员。", pinyin: "zhè jiā jī gòu zhuān mén bāng zhù shī yè rén yuán.", ko: "이 기관은 실업자를 돕는 것을 전문으로 해요." } },
        { zh: "机遇", pinyin: "jīyù", ko: "기회, 호기", pos: "명사", ex: { zh: "这是一个难得的机遇。", pinyin: "zhè shì yí gè nán dé de jī yù.", ko: "이것은 흔치 않은 좋은 기회예요." } },
        { zh: "即将", pinyin: "jíjiāng", ko: "곧, 머지않아", pos: "부사", ex: { zh: "比赛即将开始。", pinyin: "bǐ sài jí jiāng kāi shǐ.", ko: "경기가 곧 시작돼요." } },
        { zh: "记载", pinyin: "jìzǎi", ko: "기재하다, 기록하다", pos: "동사", ex: { zh: "史书记载了这段历史。", pinyin: "shǐ shū jì zǎi le zhè duàn lì shǐ.", ko: "역사책에 이 역사가 기록되어 있어요." } },
        { zh: "技巧", pinyin: "jìqiǎo", ko: "기교, 테크닉", pos: "명사", ex: { zh: "他掌握了很多写作技巧。", pinyin: "tā zhǎng wò le hěn duō xiě zuò jì qiǎo.", ko: "그는 많은 글쓰기 기교를 익혔어요." } },
        { zh: "季", pinyin: "jì", ko: "계절", pos: "명사", ex: { zh: "一年有四个季节。", pinyin: "Yì nián yǒu sì gè jìjié.", ko: "일 년에는 네 계절이 있어요." } },
        { zh: "季度", pinyin: "jìdù", ko: "분기", pos: "명사", ex: { zh: "公司每个季度都要开总结会。", pinyin: "gōng sī měi gè jì dù dōu yào kāi zǒng jié huì.", ko: "회사는 매 분기마다 결산 회의를 열어요." } },
        { zh: "既", pinyin: "jì", ko: "이미; ~이자 ~이다(既...又...)", pos: "접속사", ex: { zh: "他既聪明又努力。", pinyin: "tā jì cōng míng yòu nǔ lì.", ko: "그는 똑똑할 뿐만 아니라 노력하기도 해요." } },
        { zh: "加入", pinyin: "jiārù", ko: "가입하다, 참가하다", pos: "동사", ex: { zh: "他决定加入这个团队。", pinyin: "tā jué dìng jiā rù zhè ge tuán duì.", ko: "그는 이 팀에 가입하기로 결정했어요." } },
        { zh: "坚固", pinyin: "jiāngù", ko: "견고하다, 튼튼하다", pos: "형용사", ex: { zh: "这座桥非常坚固。", pinyin: "zhè zuò qiáo fēi cháng jiān gù.", ko: "이 다리는 매우 견고해요." } },
        { zh: "减", pinyin: "jiǎn", ko: "줄이다, 빼다, 감소하다", pos: "동사", ex: { zh: "十减三等于七。", pinyin: "shí jiǎn sān děng yú qī.", ko: "10 빼기 3은 7예요." } },
        { zh: "检测", pinyin: "jiǎncè", ko: "검사하다, 검측하다", pos: "동사", ex: { zh: "工人正在检测设备的性能。", pinyin: "gōng rén zhèng zài jiǎn cè shè bèi de xìng néng.", ko: "작업자가 설비의 성능을 검사하고 있어요." } },
        { zh: "健身", pinyin: "jiànshēn", ko: "헬스하다, 몸을 단련하다", pos: "동사", ex: { zh: "我每天早上去健身房健身。", pinyin: "wǒ měi tiān zǎo shang qù jiàn shēn fáng jiàn shēn.", ko: "나는 매일 아침 헬스장에 가서 운동해요." } },
        { zh: "渐渐", pinyin: "jiànjiàn", ko: "점점, 점차", pos: "부사", ex: { zh: "天渐渐黑了。", pinyin: "tiān jiàn jiàn hēi le.", ko: "날이 점점 어두워졌어요." } },
        { zh: "江", pinyin: "jiāng", ko: "강; 성씨(장)", pos: "명사", ex: { zh: "长江是中国最长的河流。", pinyin: "cháng jiāng shì zhōng guó zuì cháng de hé liú.", ko: "장강(창장)은 중국에서 가장 긴 강이에요." } },
        { zh: "奖", pinyin: "jiǎng", ko: "상, 상금", pos: "명사", ex: { zh: "他获得了一等奖。", pinyin: "tā huò dé le yì děng jiǎng.", ko: "그는 1등상을 받았어요." } },
        { zh: "奖学金", pinyin: "jiǎngxuéjīn", ko: "장학금", pos: "명사", ex: { zh: "她申请到了奖学金。", pinyin: "tā shēn qǐng dào le jiǎng xué jīn.", ko: "그녀는 장학금을 신청해서 받았어요." } },
        { zh: "降", pinyin: "jiàng", ko: "내리다, 떨어지다", pos: "동사", ex: { zh: "气温明显下降了。", pinyin: "qì wēn míng xiǎn xià jiàng le.", ko: "기온이 뚜렷하게 내려갔어요." } },
        { zh: "降价", pinyin: "jiàngjià", ko: "가격을 내리다, 할인하다", pos: "동사", ex: { zh: "这款手机最近降价了。", pinyin: "zhè kuǎn shǒu jī zuì jìn jiàng jià le.", ko: "이 휴대폰은 최근 가격이 내렸어요." } },
        { zh: "降温", pinyin: "jiàngwēn", ko: "온도가 내려가다, 식다", pos: "동사", ex: { zh: "明天开始降温。", pinyin: "míng tiān kāi shǐ jiàng wēn.", ko: "내일부터 기온이 내려가요." } },
        { zh: "结", pinyin: "jiē", ko: "(열매를) 맺다", pos: "동사", ex: { zh: "这棵苹果树今年结了很多果子。", pinyin: "zhè kē píng guǒ shù jīn nián jiē le hěn duō guǒ zi.", ko: "이 사과나무는 올해 열매를 많이 맺었어요." } },
        { zh: "姐妹", pinyin: "jiěmèi", ko: "자매", pos: "명사", ex: { zh: "我们是好姐妹。", pinyin: "wǒ men shì hǎo jiě mèi.", ko: "우리는 친한 자매예요." } },
        { zh: "尽快", pinyin: "jǐnkuài", ko: "되도록 빨리, 최대한 빨리", pos: "부사", ex: { zh: "请尽快回复我。", pinyin: "qǐng jǐn kuài huí fù wǒ.", ko: "가능한 한 빨리 답장해 주세요." } },
        { zh: "紧密", pinyin: "jǐnmì", ko: "긴밀하다, 밀접하다", pos: "형용사", ex: { zh: "两国关系日益紧密。", pinyin: "liǎng guó guān xì rì yì jǐn mì.", ko: "양국 관계가 날로 긴밀해지고 있어요." } },
        { zh: "镜头", pinyin: "jìngtóu", ko: "카메라 렌즈, 장면", pos: "명사", ex: { zh: "这个镜头拍得很美。", pinyin: "zhè ge jìng tóu pāi de hěn měi.", ko: "이 장면은 아주 아름답게 촬영되었어요." } },
        { zh: "居民", pinyin: "jūmín", ko: "주민", pos: "명사", ex: { zh: "小区居民都很热情。", pinyin: "xiǎo qū jū mín dōu hěn rè qíng.", ko: "단지 주민들은 모두 매우 친절해요." } },
        { zh: "居住", pinyin: "jūzhù", ko: "거주하다, 살다", pos: "동사", ex: { zh: "他们一家居住在上海。", pinyin: "tā men yì jiā jū zhù zài shàng hǎi.", ko: "그들 가족은 상하이에 거주해요." } },
        { zh: "局", pinyin: "jú", ko: "좁다, 옹졸하다", pos: "명사", ex: { zh: "他性格局促,不太合群。", pinyin: "tā xìng gé jú cù, bú tài hé qún.", ko: "그는 성격이 옹졸하여 잘 어울리지 못해요." } },
        { zh: "聚", pinyin: "jù", ko: "모이다, 모으다", pos: "동사", ex: { zh: "老朋友们聚在一起聊天。", pinyin: "lǎo péng you men jù zài yì qǐ liáo tiān.", ko: "오랜 친구들이 함께 모여 이야기를 나눠요." } },
        { zh: "开花", pinyin: "kāihuā", ko: "꽃이 피다, 개화하다", pos: "동사", ex: { zh: "春天到了,樱花都开花了。", pinyin: "chūn tiān dào le, yīng huā dōu kāi huā le.", ko: "봄이 되어 벚꽃이 활짝 피었어요." } },
        { zh: "开水", pinyin: "kāishuǐ", ko: "끓인 물", pos: "명사", ex: { zh: "请给我一杯开水。", pinyin: "qǐng gěi wǒ yì bēi kāi shuǐ.", ko: "끓인 물 한 잔 주세요." } },
        { zh: "看望", pinyin: "kànwàng", ko: "문안하다, 찾아뵙다", pos: "동사", ex: { zh: "周末我要去看望奶奶。", pinyin: "zhōu mò wǒ yào qù kàn wàng nǎi nai.", ko: "주말에 나는 할머니를 뵈러 갈 거예요." } },
        { zh: "考察", pinyin: "kǎochá", ko: "고찰하다, 시찰하다", pos: "동사", ex: { zh: "专家们去当地进行实地考察。", pinyin: "zhuān jiā men qù dāng dì jìn xíng shí dì kǎo chá.", ko: "전문가들이 현지에 가서 현장 시찰을 진행했어요." } },
        { zh: "口袋", pinyin: "kǒudài", ko: "주머니, 자루", pos: "명사", ex: { zh: "他把钥匙放进口袋里。", pinyin: "tā bǎ yào shi fàng jìn kǒu dài lǐ.", ko: "그는 열쇠를 주머니에 넣었어요." } },
        { zh: "口语", pinyin: "kǒuyǔ", ko: "구어, 회화", pos: "명사", ex: { zh: "他的口语水平提高很快。", pinyin: "tā de kǒu yǔ shuǐ píng tí gāo hěn kuài.", ko: "그의 회화 실력이 빠르게 늘었어요." } },
        { zh: "快递", pinyin: "kuàidì", ko: "택배, 특급 배송", pos: "동사", ex: { zh: "我昨天寄了一个快递。", pinyin: "wǒ zuó tiān jì le yí gè kuài dì.", ko: "나는 어제 택배를 하나 부쳤어요." } },
        { zh: "宽广", pinyin: "kuānguǎng", ko: "넓다, 광활하다", pos: "형용사", ex: { zh: "这片草原十分宽广。", pinyin: "zhè piàn cǎo yuán shí fēn kuān guǎng.", ko: "이 초원은 매우 넓어요." } },
        { zh: "扩展", pinyin: "kuòzhǎn", ko: "확장하다, 넓히다", pos: "동사", ex: { zh: "公司计划扩展海外市场。", pinyin: "Gōngsī jìhuà kuòzhǎn hǎiwài shìchǎng.", ko: "회사는 해외 시장을 확장할 계획이에요." } },
        { zh: "括号", pinyin: "kuòhào", ko: "괄호", pos: "명사", ex: { zh: "请把答案写在括号里。", pinyin: "Qǐng bǎ dá'àn xiě zài kuòhào lǐ.", ko: "답을 괄호 안에 써 주세요." } },
        { zh: "垃圾", pinyin: "lājī", ko: "쓰레기", pos: "명사", ex: { zh: "请把垃圾扔进垃圾桶。", pinyin: "Qǐng bǎ lājī rēng jìn lājītǒng.", ko: "쓰레기를 쓰레기통에 버려 주세요." } },
        { zh: "拉开", pinyin: "lākāi", ko: "잡아당겨 열다, 벌리다", pos: "동사", ex: { zh: "他拉开窗帘,让阳光照进来。", pinyin: "Tā lākāi chuānglián, ràng yángguāng zhào jìnlái.", ko: "그는 커튼을 열어 햇빛이 들어오게 했어요." } },
        { zh: "来源", pinyin: "láiyuán", ko: "원천, 출처, 근원", pos: "명사", ex: { zh: "这个消息的来源不清楚。", pinyin: "Zhège xiāoxi de láiyuán bù qīngchu.", ko: "이 소식의 출처가 불분명해요." } },
        { zh: "老公", pinyin: "lǎogōng", ko: "남편", pos: "명사", ex: { zh: "我老公每天做饭。", pinyin: "Wǒ lǎogōng měitiān zuò fàn.", ko: "내 남편은 매일 요리를 해요." } },
        { zh: "老家", pinyin: "lǎojiā", ko: "고향", pos: "명사", ex: { zh: "我老家在四川。", pinyin: "Wǒ lǎojiā zài Sìchuān.", ko: "내 고향은 쓰촨이에요." } },
        { zh: "乐趣", pinyin: "lèqù", ko: "즐거움, 재미", pos: "명사", ex: { zh: "做饭给我带来很多乐趣。", pinyin: "Zuò fàn gěi wǒ dàilái hěn duō lèqù.", ko: "요리는 나에게 많은 즐거움을 줘요." } },
        { zh: "泪", pinyin: "lèi", ko: "눈물", pos: "명사", ex: { zh: "她的眼里流下了泪。", pinyin: "Tā de yǎn lǐ liú xiàle lèi.", ko: "그녀의 눈에서 눈물이 흘렀어요." } },
        { zh: "泪水", pinyin: "lèishuǐ", ko: "눈물", pos: "명사", ex: { zh: "泪水从她脸上流下来。", pinyin: "Lèishuǐ cóng tā liǎn shàng liú xiàlái.", ko: "눈물이 그녀의 얼굴을 타고 흘러내렸어요." } },
        { zh: "类型", pinyin: "lèixíng", ko: "유형, 종류", pos: "명사", ex: { zh: "这两种类型有什么区别?", pinyin: "Zhè liǎng zhǒng lèixíng yǒu shénme qūbié?", ko: "이 두 유형은 어떤 차이가 있나요?" } },
        { zh: "离不开", pinyin: "líbukāi", ko: "떼려야 뗄 수 없다, 없어서는 안 되다", pos: "동사", ex: { zh: "生活离不开水和空气。", pinyin: "Shēnghuó líbukāi shuǐ hé kōngqì.", ko: "생활은 물과 공기 없이는 안 돼요." } },
        { zh: "两边", pinyin: "liǎngbian", ko: "양쪽, 양편", pos: "명사", ex: { zh: "路的两边种满了树。", pinyin: "Lù de liǎngbian zhòng mǎnle shù.", ko: "길 양쪽에 나무가 가득 심어져 있어요." } },
        { zh: "量", pinyin: "liáng", ko: "재다, 측정하다", pos: "명사", ex: { zh: "医生给他量了体温。", pinyin: "Yīshēng gěi tā liángle tǐwēn.", ko: "의사가 그의 체온을 재었어요." } },
        { zh: "疗养", pinyin: "liáoyǎng", ko: "요양하다", pos: "동사", ex: { zh: "他去海边疗养身体。", pinyin: "Tā qù hǎibiān liáoyǎng shēntǐ.", ko: "그는 몸을 요양하러 바닷가에 갔어요." } },
        { zh: "列", pinyin: "liè", ko: "줄지어 세우다, 배열하다", pos: "동사", ex: { zh: "请把名字按顺序列出来。", pinyin: "Qǐng bǎ míngzi àn shùnxù liè chūlái.", ko: "이름을 순서대로 나열해 주세요." } },
        { zh: "列车", pinyin: "lièchē", ko: "열차, 기차", pos: "명사", ex: { zh: "这趟列车马上就要出发了。", pinyin: "Zhè tàng lièchē mǎshàng jiù yào chūfāle.", ko: "이 열차는 곧 출발해요." } },
        { zh: "列入", pinyin: "lièrù", ko: "포함시키다, 명단에 넣다", pos: "동사", ex: { zh: "这本书已经被列入推荐名单。", pinyin: "Zhè běn shū yǐjīng bèi lièrù tuījiàn míngdān.", ko: "이 책은 이미 추천 목록에 포함되었어요." } },
        { zh: "列为", pinyin: "lièwéi", ko: "~로 분류되다, ~로 꼽히다", pos: "동사", ex: { zh: "这个城市被列为重点保护对象。", pinyin: "Zhège chéngshì bèi lièwéi zhòngdiǎn bǎohù duìxiàng.", ko: "이 도시는 중점 보호 대상으로 분류되었어요." } },
        { zh: "楼梯", pinyin: "lóutī", ko: "계단", pos: "명사", ex: { zh: "请走楼梯上楼。", pinyin: "Qǐng zǒu lóutī shàng lóu.", ko: "계단으로 올라가 주세요." } },
        { zh: "率先", pinyin: "shuàixiān", ko: "앞장서서, 솔선하여", pos: "부사", ex: { zh: "他率先举手回答问题。", pinyin: "Tā shuàixiān jǔshǒu huídá wèntí.", ko: "그는 앞장서서 손을 들고 질문에 답했어요." } },
        { zh: "轮", pinyin: "lún", ko: "돌아가면서 하다, 차례가 되다", pos: "동사", ex: { zh: "今天轮到我打扫教室。", pinyin: "Jīntiān lún dào wǒ dǎsǎo jiàoshì.", ko: "오늘은 내가 교실을 청소할 차례예요." } },
        { zh: "轮船", pinyin: "lúnchuán", ko: "기선, 증기선", pos: "명사", ex: { zh: "我们坐轮船去了海南岛。", pinyin: "Wǒmen zuò lúnchuán qùle Hǎinán Dǎo.", ko: "우리는 기선을 타고 하이난섬에 갔어요." } },
        { zh: "轮椅", pinyin: "lúnyǐ", ko: "휠체어", pos: "명사", ex: { zh: "奶奶坐轮椅出门散步。", pinyin: "Nǎinai zuò lúnyǐ chūmén sànbù.", ko: "할머니는 휠체어를 타고 산책하러 나가세요." } },
        { zh: "轮子", pinyin: "lúnzi", ko: "바퀴", pos: "명사", ex: { zh: "这辆自行车的轮子坏了。", pinyin: "Zhè liàng zìxíngchē de lúnzi huàile.", ko: "이 자전거의 바퀴가 고장 났어요." } },
        { zh: "落", pinyin: "là", ko: "빠뜨리다, 놓고 오다", pos: "동사", ex: { zh: "我把伞落在公交车上了。", pinyin: "Wǒ bǎ sǎn là zài gōngjiāochē shàng le.", ko: "나는 우산을 버스에 두고 내렸어요." } },
        { zh: "毛衣", pinyin: "máoyī", ko: "스웨터, 털옷", pos: "명사", ex: { zh: "天冷了,该穿毛衣了。", pinyin: "Tiān lěng le, gāi chuān máoyī le.", ko: "날씨가 추워져서 스웨터를 입어야 해요." } },
        { zh: "没错", pinyin: "méicuò", ko: "맞다, 틀림없다", pos: "동사", ex: { zh: "没错,就是这个地方。", pinyin: "Méi cuò, jiùshì zhège dìfang.", ko: "맞아요, 바로 이곳이에요." } },
        { zh: "没法儿", pinyin: "méifǎr", ko: "방법이 없다, 어쩔 수 없다", pos: "명사", ex: { zh: "下这么大的雨,没法儿出门。", pinyin: "Xià zhème dà de yǔ, méifǎr chūmén.", ko: "비가 이렇게 많이 오니 나갈 방법이 없어요." } },
        { zh: "没想到", pinyin: "méixiǎngdào", ko: "생각지도 못했다, 뜻밖이다", pos: "동사", ex: { zh: "没想到今天会遇见你。", pinyin: "Méi xiǎngdào jīntiān huì yùjiàn nǐ.", ko: "오늘 너를 만날 줄은 생각지도 못했어요." } },
        { zh: "美金", pinyin: "Měijīn", ko: "미국 달러", pos: "양사", ex: { zh: "这件衣服要一百美金。", pinyin: "Zhè jiàn yīfu yào yìbǎi Měijīn.", ko: "이 옷은 100달러예요." } },
        { zh: "美女", pinyin: "měinǚ", ko: "미녀", pos: "명사", ex: { zh: "她是公司里出了名的美女。", pinyin: "Tā shì gōngsī lǐ chūle míng de měinǚ.", ko: "그녀는 회사에서 유명한 미녀예요." } },
        { zh: "梦见", pinyin: "mèngjiàn", ko: "꿈에서 보다, 꿈꾸다", pos: "동사", ex: { zh: "我昨晚梦见了你。", pinyin: "Wǒ zuówǎn mèngjiànle nǐ.", ko: "나는 어젯밤 꿈에서 너를 봤어요." } },
        { zh: "梦想", pinyin: "mèngxiǎng", ko: "꿈, 이상", pos: "명사", ex: { zh: "我的梦想是成为一名医生。", pinyin: "Wǒ de mèngxiǎng shì chéngwéi yì míng yīshēng.", ko: "내 꿈은 의사가 되는 거예요." } },
        { zh: "密", pinyin: "mì", ko: "촘촘하다, 은밀하다", pos: "형용사", ex: { zh: "森林里的树很密。", pinyin: "Sēnlín lǐ de shù hěn mì.", ko: "숲속의 나무가 매우 촘촘해요." } },
        { zh: "面试", pinyin: "miànshì", ko: "면접(하다)", pos: "동사", ex: { zh: "明天我要去公司面试。", pinyin: "Míngtiān wǒ yào qù gōngsī miànshì.", ko: "내일 나는 회사 면접을 보러 가요." } },
        { zh: "描述", pinyin: "miáoshù", ko: "묘사하다, 서술하다", pos: "동사", ex: { zh: "请你描述一下当时的情况。", pinyin: "Qǐng nǐ miáoshù yíxià dāngshí de qíngkuàng.", ko: "그때 상황을 묘사해 주세요." } },
        { zh: "名牌儿", pinyin: "míngpáir", ko: "유명 브랜드, 명품", pos: "명사", ex: { zh: "她喜欢穿名牌儿衣服。", pinyin: "Tā xǐhuan chuān míngpáir yīfu.", ko: "그녀는 명품 옷을 즐겨 입어요." } },
        { zh: "名人", pinyin: "míngrén", ko: "유명인, 명사", pos: "명사", ex: { zh: "这条街上住着很多名人。", pinyin: "Zhè tiáo jiē shàng zhùzhe hěn duō míngrén.", ko: "이 거리에는 많은 유명인이 살고 있어요." } },
        { zh: "模特儿", pinyin: "mó tèr", ko: "모델", pos: "명사", ex: { zh: "她是一名时装模特儿。", pinyin: "Tā shì yì míng shízhuāng mótèr.", ko: "그녀는 패션모델이에요." } },
        { zh: "模型", pinyin: "móxíng", ko: "모형, 모델", pos: "명사", ex: { zh: "他做了一个飞机模型。", pinyin: "tā zuò le yí gè fēi jī mó xíng。", ko: "그는 비행기 모형을 만들었어요." } },
        { zh: "末", pinyin: "mò", ko: "끝, 말", pos: "명사", ex: { zh: "这是本世纪末的事情。", pinyin: "zhè shì běn shì jì mò de shì qing。", ko: "이것은 이번 세기 말의 일이에요." } },
        { zh: "默默", pinyin: "mòmò", ko: "묵묵히, 조용히", pos: "부사", ex: { zh: "他默默地流下了眼泪。", pinyin: "tā mò mò de liú xià le yǎn lèi。", ko: "그는 묵묵히 눈물을 흘렸어요." } },
        { zh: "男女", pinyin: "nánnǚ", ko: "남녀", pos: "명사", ex: { zh: "这里男女都可以参加。", pinyin: "zhè lǐ nán nǚ dōu kě yǐ cān jiā。", ko: "이곳은 남녀 모두 참가할 수 있어요." } },
        { zh: "男士", pinyin: "nánshì", ko: "신사, 남성", pos: "명사", ex: { zh: "这位男士很有礼貌。", pinyin: "zhè wèi nán shì hěn yǒu lǐ mào。", ko: "이 신사는 매우 예의 발라요." } },
        { zh: "闹", pinyin: "nào", ko: "소란 피우다, 시끄럽게 하다", pos: "동사", ex: { zh: "孩子们在楼下闹得很厉害。", pinyin: "hái zi men zài lóu xià nào de hěn lì hai。", ko: "아이들이 아래층에서 심하게 소란을 피워요." } },
        { zh: "闹钟", pinyin: "nàozhōng", ko: "자명종, 알람시계", pos: "명사", ex: { zh: "我每天用闹钟叫醒自己。", pinyin: "wǒ měi tiān yòng nào zhōng jiào xǐng zì jǐ。", ko: "나는 매일 알람시계로 스스로를 깨워요." } },
        { zh: "内部", pinyin: "nèibù", ko: "내부", pos: "명사", ex: { zh: "这是公司内部的消息。", pinyin: "zhè shì gōng sī nèi bù de xiāo xi。", ko: "이것은 회사 내부 소식이에요." } },
        { zh: "宁静", pinyin: "níngjìng", ko: "고요하다, 평온하다", pos: "형용사", ex: { zh: "夜晚的村庄非常宁静。", pinyin: "yè wǎn de cūn zhuāng fēi cháng níng jìng。", ko: "밤의 마을은 매우 고요해요." } },
        { zh: "暖气", pinyin: "nuǎnqì", ko: "난방, 온기", pos: "명사", ex: { zh: "冬天家里有暖气很舒服。", pinyin: "dōng tiān jiā lǐ yǒu nuǎn qì hěn shū fu。", ko: "겨울에 집에 난방이 있으면 편안해요." } },
        { zh: "拍照", pinyin: "pāizhào", ko: "사진을 찍다", pos: "동사", ex: { zh: "我们在这里拍照吧。", pinyin: "wǒ men zài zhè lǐ pāi zhào ba。", ko: "우리 여기서 사진 찍자." } },
        { zh: "牌", pinyin: "pái", ko: "패, 카드", pos: "명사", ex: { zh: "他们在打牌。", pinyin: "tā men zài dǎ pái。", ko: "그들은 카드놀이를 하고 있어요." } },
        { zh: "盘", pinyin: "pán", ko: "쟁반, 접시", pos: "동사", ex: { zh: "桌上放着一盘水果。", pinyin: "zhuō shàng fàng zhe yì pán shuǐ guǒ。", ko: "탁자 위에 과일 한 접시가 놓여 있어요." } },
        { zh: "胖子", pinyin: "pàngzi", ko: "뚱보", pos: "명사", ex: { zh: "他从小就是个胖子。", pinyin: "tā cóng xiǎo jiù shì gè pàng zi。", ko: "그는 어릴 때부터 뚱보였어요." } },
        { zh: "培训", pinyin: "péixùn", ko: "훈련하다, 연수하다", pos: "동사", ex: { zh: "公司为员工提供培训。", pinyin: "gōng sī wèi yuán gōng tí gōng péi xùn。", ko: "회사는 직원들에게 연수를 제공해요." } },
        { zh: "培训班", pinyin: "péixùnbān", ko: "연수반, 학원", pos: "명사", ex: { zh: "她报了一个英语培训班。", pinyin: "tā bào le yí gè yīng yǔ péi xùn bān。", ko: "그녀는 영어 학원 하나를 등록했어요." } },
        { zh: "培育", pinyin: "péiyù", ko: "육성하다, 재배하다", pos: "동사", ex: { zh: "农民培育了新品种。", pinyin: "nóng mín péi yù le xīn pǐn zhǒng。", ko: "농민은 새로운 품종을 육성했어요." } },
        { zh: "品质", pinyin: "pǐnzhì", ko: "품질, 인품", pos: "명사", ex: { zh: "这个产品品质很好。", pinyin: "zhè ge chǎn pǐn pǐn zhì hěn hǎo。", ko: "이 제품은 품질이 좋아요." } },
        { zh: "平稳", pinyin: "píngwěn", ko: "안정적이다, 순조롭다", pos: "형용사", ex: { zh: "飞机平稳地降落了。", pinyin: "fēi jī píng wěn de jiàng luò le。", ko: "비행기가 안정적으로 착륙했어요." } },
        { zh: "期末", pinyin: "qīmò", ko: "기말", pos: "명사", ex: { zh: "期末考试快到了。", pinyin: "qī mò kǎo shì kuài dào le。", ko: "기말고사가 다가와요." } },
        { zh: "期限", pinyin: "qīxiàn", ko: "기한", pos: "명사", ex: { zh: "交作业的期限是明天。", pinyin: "jiāo zuò yè de qī xiàn shì míng tiān。", ko: "숙제 제출 기한은 내일이에요." } },
        { zh: "期中", pinyin: "qīzhōng", ko: "중간(고사)", pos: "명사", ex: { zh: "下周有期中考试。", pinyin: "xià zhōu yǒu qī zhōng kǎo shì。", ko: "다음 주에 중간고사가 있어요." } },
        { zh: "气球", pinyin: "qìqiú", ko: "풍선", pos: "명사", ex: { zh: "孩子拿着一个气球。", pinyin: "hái zi ná zhe yí gè qì qiú。", ko: "아이는 풍선 하나를 들고 있어요." } },
        { zh: "汽水", pinyin: "qìshuǐ", ko: "사이다, 탄산음료", pos: "명사", ex: { zh: "他喜欢喝汽水。", pinyin: "tā xǐ huan hē qì shuǐ。", ko: "그는 탄산음료 마시는 것을 좋아해요." } },
        { zh: "器官", pinyin: "qìguān", ko: "기관(신체)", pos: "명사", ex: { zh: "心脏是重要的器官。", pinyin: "xīn zàng shì zhòng yào de qì guān。", ko: "심장은 중요한 기관이에요." } },
        { zh: "前头", pinyin: "qiántou", ko: "앞, 앞쪽", pos: "명사", ex: { zh: "他走在前头。", pinyin: "tā zǒu zài qián tou。", ko: "그는 앞쪽에서 걸어요." } },
        { zh: "亲密", pinyin: "qīnmì", ko: "친밀하다", pos: "형용사", ex: { zh: "他们关系很亲密。", pinyin: "tā men guān xi hěn qīn mì。", ko: "그들의 관계는 매우 친밀해요." } },
        { zh: "轻易", pinyin: "qīngyì", ko: "쉽사리, 함부로", pos: "부사", ex: { zh: "不要轻易放弃。", pinyin: "bú yào qīng yì fàng qì。", ko: "함부로 포기하지 마라." } },
        { zh: "穷人", pinyin: "qióngrén", ko: "가난한 사람", pos: "명사", ex: { zh: "政府帮助穷人。", pinyin: "zhèng fǔ bāng zhù qióng rén。", ko: "정부는 가난한 사람들을 도와요." } },
        { zh: "秋季", pinyin: "qiūjì", ko: "가을", pos: "명사", ex: { zh: "秋季的天气很凉爽。", pinyin: "qiū jì de tiān qì hěn liáng shuǎng。", ko: "가을 날씨는 매우 시원해요." } },
        { zh: "燃料", pinyin: "ránliào", ko: "연료", pos: "명사", ex: { zh: "汽车需要燃料。", pinyin: "qì chē xū yào rán liào。", ko: "자동차는 연료가 필요해요." } },
        { zh: "人家", pinyin: "rénjiā", ko: "남, 다른 사람, 집", pos: "대명사", ex: { zh: "人家都在等你呢。", pinyin: "rén jiā dōu zài děng nǐ ne。", ko: "다들 너를 기다리고 있어." } },
        { zh: "散", pinyin: "sàn", ko: "흩어지다, 헤어지다", pos: "동사", ex: { zh: "会议结束后大家就散了。", pinyin: "huì yì jié shù hòu dà jiā jiù sàn le。", ko: "회의가 끝난 후 사람들은 흩어졌어요." } },
        { zh: "扫", pinyin: "sǎo", ko: "쓸다, 청소하다", pos: "동사", ex: { zh: "她在扫地。", pinyin: "tā zài sǎo dì。", ko: "그녀는 바닥을 쓸고 있어요." } },
        { zh: "色", pinyin: "sè", ko: "색, 색깔", pos: "명사", ex: { zh: "这件衣服是什么颜色？", pinyin: "zhè jiàn yī fu shì shén me yán sè?", ko: "이 옷은 무슨 색이에요?" } },
        { zh: "色彩", pinyin: "sècǎi", ko: "색채", pos: "명사", ex: { zh: "这幅画色彩很丰富。", pinyin: "zhè fú huà sè cǎi hěn fēng fù。", ko: "이 그림은 색채가 풍부해요." } },
        { zh: "闪", pinyin: "shǎn", ko: "번쩍이다(성씨: 산)", pos: "동사", ex: { zh: "闪电划过天空。", pinyin: "shǎn diàn huà guò tiān kōng。", ko: "번개가 하늘을 가로질렀어요." } },
        { zh: "伤害", pinyin: "shānghài", ko: "상처를 주다, 해치다", pos: "동사", ex: { zh: "他的话伤害了我的感情。", pinyin: "tā de huà shāng hài le wǒ de gǎn qíng。", ko: "그의 말은 내 감정을 상하게 했어요." } },
        { zh: "商务", pinyin: "shāngwù", ko: "상무, 비즈니스", pos: "명사", ex: { zh: "他经常出差处理商务。", pinyin: "tā jīng cháng chū chāi chǔ lǐ shāng wù。", ko: "그는 자주 출장을 가서 비즈니스를 처리해요." } },
        { zh: "赏", pinyin: "shǎng", ko: "상을 주다, 하사하다", pos: "동사", ex: { zh: "老板赏了他一笔钱。", pinyin: "lǎo bǎn shǎng le tā yì bǐ qián。", ko: "사장은 그에게 돈을 상으로 주었어요." } },
        { zh: "上个月", pinyin: "shànggèyuè", ko: "지난달", pos: "명사", ex: { zh: "我上个月去了北京。", pinyin: "Wǒ shàng gè yuè qù le Běi jīng.", ko: "나는 지난달 베이징에 갔어요." } },
        { zh: "上楼", pinyin: "shànglóu", ko: "위층으로 올라가다", pos: "동사", ex: { zh: "他上楼去拿东西了。", pinyin: "Tā shàng lóu qù ná dōng xi le.", ko: "그는 물건을 가지러 위층으로 올라갔어요." } },
        { zh: "上门", pinyin: "shàngmén", ko: "방문하다, 찾아가다", pos: "동사", ex: { zh: "医生上门给老人看病。", pinyin: "Yī shēng shàng mén gěi lǎo rén kàn bìng.", ko: "의사가 노인을 진찰하러 방문했어요." } },
        { zh: "烧", pinyin: "shāo", ko: "타다, 태우다; 열이 나다", pos: "동사", ex: { zh: "孩子发烧了,需要吃药。", pinyin: "Hái zi fā shāo le, xū yào chī yào.", ko: "아이가 열이 나서 약을 먹어야 해요." } },
        { zh: "设置", pinyin: "shèzhì", ko: "설치하다, 설정하다", pos: "동사", ex: { zh: "请设置一下手机密码。", pinyin: "Qǐng shè zhì yí xià shǒu jī mì mǎ.", ko: "휴대폰 비밀번호를 설정해 주세요." } },
        { zh: "身高", pinyin: "shēngāo", ko: "신장, 키", pos: "명사", ex: { zh: "他的身高是一米八。", pinyin: "Tā de shēn gāo shì yì mǐ bā.", ko: "그의 키는 180cm예요." } },
        { zh: "深厚", pinyin: "shēnhòu", ko: "깊다, 두텁다", pos: "형용사", ex: { zh: "他们有深厚的友谊。", pinyin: "Tā men yǒu shēn hòu de yǒu yì.", ko: "그들은 깊은 우정을 가지고 있어요." } },
        { zh: "诗人", pinyin: "shīrén", ko: "시인", pos: "명사", ex: { zh: "李白是著名的诗人。", pinyin: "Lǐ Bái shì zhù míng de shī rén.", ko: "이백은 유명한 시인이에요." } },
        { zh: "湿", pinyin: "shī", ko: "축축하다, 젖다", pos: "형용사", ex: { zh: "外面下雨,地上很湿。", pinyin: "Wài miàn xià yǔ, dì shang hěn shī.", ko: "밖에 비가 와서 땅이 축축해요." } },
        { zh: "实施", pinyin: "shíshī", ko: "실시하다, 시행하다", pos: "동사", ex: { zh: "新政策已经开始实施。", pinyin: "Xīn zhèng cè yǐ jīng kāi shǐ shí shī.", ko: "새 정책이 이미 시행되기 시작했어요." } },
        { zh: "食堂", pinyin: "shítáng", ko: "식당(구내식당)", pos: "명사", ex: { zh: "我们中午在食堂吃饭。", pinyin: "Wǒ men zhōng wǔ zài shí táng chī fàn.", ko: "우리는 점심에 구내식당에서 밥을 먹어요." } },
        { zh: "使劲", pinyin: "shǐjìn", ko: "힘을 쓰다", pos: "동사", ex: { zh: "大家一起使劲把车推出去。", pinyin: "Dà jiā yì qǐ shǐ jìn bǎ chē tuī chū qù.", ko: "모두 함께 힘을 써서 차를 밀어냈어요." } },
        { zh: "市区", pinyin: "shìqū", ko: "시내, 도심 지역", pos: "명사", ex: { zh: "他住在市区附近。", pinyin: "Tā zhù zài shì qū fù jìn.", ko: "그는 시내 근처에 살아요." } },
        { zh: "收回", pinyin: "shōuhuí", ko: "회수하다, 되찾다", pos: "동사", ex: { zh: "公司收回了那笔投资。", pinyin: "Gōng sī shōu huí le nà bǐ tóu zī.", ko: "회사는 그 투자금을 회수했어요." } },
        { zh: "收益", pinyin: "shōuyì", ko: "수익", pos: "명사", ex: { zh: "这个项目带来了不少收益。", pinyin: "Zhè ge xiàng mù dài lái le bù shǎo shōu yì.", ko: "이 프로젝트는 적지 않은 수익을 가져왔어요." } },
        { zh: "手里", pinyin: "shǒulǐ", ko: "손안에, 수중에", pos: "명사", ex: { zh: "他手里拿着一本书。", pinyin: "Tā shǒu lǐ ná zhe yì běn shū.", ko: "그는 손에 책 한 권을 들고 있어요." } },
        { zh: "守", pinyin: "shǒu", ko: "지키다, 수비하다", pos: "동사", ex: { zh: "士兵们守着边境。", pinyin: "Shì bīng men shǒu zhe biān jìng.", ko: "병사들이 국경을 지키고 있어요." } },
        { zh: "首", pinyin: "shǒu", ko: "머리, 최초의; (노래를 세는 단위) 곡", pos: "수사", ex: { zh: "她唱了一首好听的歌。", pinyin: "Tā chàng le yì shǒu hǎo tīng de gē.", ko: "그녀는 아름다운 노래 한 곡을 불렀어요." } },
        { zh: "暑假", pinyin: "shǔjià", ko: "여름 방학", pos: "명사", ex: { zh: "暑假我打算去旅游。", pinyin: "Shǔ jià wǒ dǎ suàn qù lǚ yóu.", ko: "여름 방학에 나는 여행을 갈 계획이에요." } },
        { zh: "树林", pinyin: "Shùlín", ko: "숲, 나무숲", pos: "명사", ex: { zh: "孩子们在树林里玩捉迷藏。", pinyin: "Hái zi men zài shù lín lǐ wán zhuō mí cáng.", ko: "아이들이 숲에서 숨바꼭질을 해요." } },
        { zh: "树叶", pinyin: "shùyè", ko: "나뭇잎", pos: "명사", ex: { zh: "秋天树叶都变黄了。", pinyin: "Qiū tiān shù yè dōu biàn huáng le.", ko: "가을이 되자 나뭇잎이 모두 노랗게 변했어요." } },
        { zh: "刷牙", pinyin: "shuāyá", ko: "이를 닦다, 양치질하다", pos: "동사", ex: { zh: "每天早晚都要刷牙。", pinyin: "Měi tiān zǎo wǎn dōu yào shuā yá.", ko: "매일 아침저녁으로 이를 닦아야 해요." } },
        { zh: "刷子", pinyin: "shuāzi", ko: "솔, 브러시", pos: "명사", ex: { zh: "他用刷子清理鞋子。", pinyin: "Tā yòng shuā zi qīng lǐ xié zi.", ko: "그는 솔로 신발을 청소해요." } },
        { zh: "帅哥", pinyin: "shuàigē", ko: "미남, 잘생긴 남자", pos: "명사", ex: { zh: "那个帅哥是新来的老师。", pinyin: "Nà ge shuài gē shì xīn lái de lǎo shī.", ko: "저 미남은 새로 온 선생님이에요." } },
        { zh: "睡着", pinyin: "shuìzháo", ko: "잠들다", pos: "동사", ex: { zh: "他一躺下就睡着了。", pinyin: "Tā yì tǎng xià jiù shuì zháo le.", ko: "그는 눕자마자 잠들었어요." } },
        { zh: "松", pinyin: "sōng", ko: "느슨하다, 풀다; 소나무", pos: "동사", ex: { zh: "请把绳子松一松。", pinyin: "Qǐng bǎ shéng zi sōng yi sōng.", ko: "밧줄을 좀 느슨하게 풀어주세요." } },
        { zh: "松树", pinyin: "sōngshù", ko: "소나무", pos: "명사", ex: { zh: "山上长满了松树。", pinyin: "Shān shàng zhǎng mǎn le sōng shù.", ko: "산 위에는 소나무가 가득 자라 있어요." } },
        { zh: "塑料", pinyin: "sùliào", ko: "플라스틱", pos: "명사", ex: { zh: "这个杯子是塑料做的。", pinyin: "Zhè ge bēi zi shì sù liào zuò de.", ko: "이 컵은 플라스틱으로 만들어졌어요." } },
        { zh: "酸奶", pinyin: "suānnǎi", ko: "요구르트", pos: "명사", ex: { zh: "我早餐喜欢喝酸奶。", pinyin: "Wǒ zǎo cān xǐ huan hē suān nǎi.", ko: "나는 아침에 요구르트 마시는 것을 좋아해요." } },
        { zh: "随手", pinyin: "suíshǒu", ko: "~하는 김에, 손 가는 대로", pos: "부사", ex: { zh: "请随手关门。", pinyin: "Qǐng suí shǒu guān mén.", ko: "나가는 김에 문 좀 닫아 주세요." } },
        { zh: "孙女", pinyin: "sūnnǚ", ko: "손녀", pos: "명사", ex: { zh: "奶奶很疼爱她的孙女。", pinyin: "Nǎi nai hěn téng ài tā de sūn nǚ.", ko: "할머니는 손녀를 매우 아끼세요." } },
        { zh: "台上", pinyin: "táishàng", ko: "무대 위", pos: "명사", ex: { zh: "演员们站在台上表演。", pinyin: "Yǎn yuán men zhàn zài tái shàng biǎo yǎn.", ko: "배우들이 무대 위에 서서 공연해요." } },
        { zh: "套餐", pinyin: "tàocān", ko: "세트 메뉴", pos: "명사", ex: { zh: "我点了一份午餐套餐。", pinyin: "Wǒ diǎn le yí fèn wǔ cān tào cān.", ko: "나는 점심 세트 메뉴를 하나 주문했어요." } },
        { zh: "特价", pinyin: "tèjià", ko: "특가", pos: "명사", ex: { zh: "这件衣服正在特价销售。", pinyin: "Zhè jiàn yī fu zhèng zài tè jià xiāo shòu.", ko: "이 옷은 지금 특가로 판매 중이에요." } },
        { zh: "体操", pinyin: "tǐcāo", ko: "체조", pos: "명사", ex: { zh: "她从小练习体操。", pinyin: "Tā cóng xiǎo liàn xí tǐ cāo.", ko: "그녀는 어릴 때부터 체조를 연습했어요." } },
        { zh: "体检", pinyin: "tǐjiǎn", ko: "건강검진(하다)", pos: "동사", ex: { zh: "公司每年组织员工体检。", pinyin: "Gōng sī měi nián zǔ zhī yuán gōng tǐ jiǎn.", ko: "회사는 매년 직원 건강검진을 실시해요." } },
        { zh: "体重", pinyin: "tǐzhòng", ko: "체중", pos: "명사", ex: { zh: "他最近体重增加了。", pinyin: "Tā zuì jìn tǐ zhòng zēng jiā le.", ko: "그는 최근 체중이 늘었어요." } },
        { zh: "替", pinyin: "tì", ko: "대신하다, ~을 위해", pos: "전치사", ex: { zh: "今天他替我上课。", pinyin: "Jīn tiān tā tì wǒ shàng kè.", ko: "오늘 그가 나 대신 수업을 해요." } },
        { zh: "替代", pinyin: "tìdài", ko: "대체하다", pos: "동사", ex: { zh: "机器无法完全替代人工。", pinyin: "Jī qì wú fǎ wán quán tì dài rén gōng.", ko: "기계는 사람의 노동을 완전히 대체할 수 없어요." } },
        { zh: "填", pinyin: "tián", ko: "채우다, 기입하다", pos: "동사", ex: { zh: "请填写这张表格。", pinyin: "Qǐng tián xiě zhè zhāng biǎo gé.", ko: "이 서식을 작성해 주세요." } },
        { zh: "挑", pinyin: "tiāo", ko: "고르다, 선택하다, 메다", pos: "동사", ex: { zh: "她仔细挑了一件礼物。", pinyin: "Tā zǐxì tiāo le yī jiàn lǐwù.", ko: "그녀는 신중하게 선물을 하나 골랐어요." } },
        { zh: "挑选", pinyin: "tiāoxuǎn", ko: "고르다, 선정하다", pos: "동사", ex: { zh: "请帮我挑选一件合适的衣服。", pinyin: "Qǐng bāng wǒ tiāoxuǎn yī jiàn héshì de yīfu.", ko: "저에게 맞는 옷 한 벌을 골라주세요." } },
        { zh: "贴", pinyin: "tiē", ko: "붙이다", pos: "동사", ex: { zh: "他在墙上贴了一张海报。", pinyin: "Tā zài qiáng shàng tiē le yī zhāng hǎibào.", ko: "그는 벽에 포스터를 한 장 붙였어요." } },
        { zh: "停下", pinyin: "tíngxià", ko: "멈추다, 정지하다", pos: "동사", ex: { zh: "汽车突然停下了。", pinyin: "Qìchē tūrán tíngxià le.", ko: "자동차가 갑자기 멈췄어요." } },
        { zh: "通知书", pinyin: "tōngzhīshū", ko: "통지서", pos: "명사", ex: { zh: "他收到了大学的录取通知书。", pinyin: "Tā shōudào le dàxué de lùqǔ tōngzhīshū.", ko: "그는 대학 합격 통지서를 받았어요." } },
        { zh: "童话", pinyin: "tónghuà", ko: "동화", pos: "명사", ex: { zh: "妈妈给孩子讲童话故事。", pinyin: "Māma gěi háizi jiǎng tónghuà gùshi.", ko: "엄마가 아이에게 동화 이야기를 들려줘요." } },
        { zh: "童年", pinyin: "tóngnián", ko: "어린 시절, 유년 시절", pos: "명사", ex: { zh: "他的童年过得很幸福。", pinyin: "Tā de tóngnián guò de hěn xìngfú.", ko: "그의 어린 시절은 매우 행복했어요." } },
        { zh: "统计", pinyin: "tǒngjì", ko: "통계(하다), 집계하다", pos: "동사", ex: { zh: "老师统计了班里的人数。", pinyin: "Lǎoshī tǒngjì le bān lǐ de rénshù.", ko: "선생님이 반의 인원수를 집계했어요." } },
        { zh: "投", pinyin: "tóu", ko: "던지다, 투입하다", pos: "동사", ex: { zh: "他把球投进篮筐。", pinyin: "Tā bǎ qiú tóu jìn lánkuāng.", ko: "그는 공을 바구니 안으로 던져 넣었어요." } },
        { zh: "投入", pinyin: "tóurù", ko: "투입하다, 몰두하다", pos: "동사", ex: { zh: "公司投入了大量资金。", pinyin: "Gōngsī tóurù le dàliàng zījīn.", ko: "회사는 대량의 자금을 투입했어요." } },
        { zh: "投诉", pinyin: "tóusù", ko: "항의하다, 신고하다", pos: "동사", ex: { zh: "顾客向经理投诉服务态度。", pinyin: "Gùkè xiàng jīnglǐ tóusù fúwù tàidu.", ko: "고객이 매니저에게 서비스 태도를 항의했어요." } },
        { zh: "透", pinyin: "tòu", ko: "꿰뚫다, 스며들다, 충분히", pos: "형용사", ex: { zh: "阳光透过窗户照进屋里。", pinyin: "Yángguāng tòuguò chuānghu zhào jìn wū lǐ.", ko: "햇빛이 창문을 통과해 방 안으로 비쳐요." } },
        { zh: "图案", pinyin: "túàn", ko: "도안, 무늬", pos: "명사", ex: { zh: "这块布上的图案很漂亮。", pinyin: "Zhè kuài bù shàng de tú'àn hěn piàoliang.", ko: "이 천의 무늬가 매우 예뻐요." } },
        { zh: "途中", pinyin: "túzhōng", ko: "도중, 가는 길에", pos: "명사", ex: { zh: "我们在途中遇到了大雨。", pinyin: "Wǒmen zài túzhōng yùdào le dàyǔ.", ko: "우리는 가는 도중에 폭우를 만났어요." } },
        { zh: "推销", pinyin: "tuīxiāo", ko: "판촉하다, 판매하다", pos: "동사", ex: { zh: "他在超市推销新产品。", pinyin: "Tā zài chāoshì tuīxiāo xīn chǎnpǐn.", ko: "그는 마트에서 신제품을 판촉해요." } },
        { zh: "外汇", pinyin: "wàihuì", ko: "외환", pos: "명사", ex: { zh: "他在银行兑换外汇。", pinyin: "Tā zài yínháng duìhuàn wàihuì.", ko: "그는 은행에서 외환을 환전해요." } },
        { zh: "外交官", pinyin: "wàijiāoguān", ko: "외교관", pos: "명사", ex: { zh: "他的父亲是一名外交官。", pinyin: "Tā de fùqin shì yī míng wàijiāoguān.", ko: "그의 아버지는 외교관이에요." } },
        { zh: "外套", pinyin: "wàitào", ko: "외투, 코트", pos: "명사", ex: { zh: "天冷了,记得穿外套。", pinyin: "Tiān lěng le, jìde chuān wàitào.", ko: "날씨가 추워졌으니 외투를 입는 것을 잊지 마라." } },
        { zh: "晚点", pinyin: "wǎndiǎn", ko: "연착하다, 늦어지다", pos: "동사", ex: { zh: "火车晚点了半个小时。", pinyin: "Huǒchē wǎndiǎn le bàn gè xiǎoshí.", ko: "기차가 30분 연착했어요." } },
        { zh: "王", pinyin: "wáng", ko: "왕, 임금; 성씨(왕)", pos: "명사", ex: { zh: "国王住在城堡里。", pinyin: "Guówáng zhù zài chéngbǎo lǐ.", ko: "왕은 성에 살고 있어요." } },
        { zh: "网络", pinyin: "Wǎngluò", ko: "인터넷, 네트워크", pos: "명사", ex: { zh: "现在的生活离不开网络。", pinyin: "Xiànzài de shēnghuó lí bu kāi wǎngluò.", ko: "요즘 생활은 인터넷과 떼려야 뗄 수 없어요." } },
        { zh: "网址", pinyin: "wǎngzhǐ", ko: "웹사이트 주소, URL", pos: "명사", ex: { zh: "请把网址发给我。", pinyin: "Qǐng bǎ wǎngzhǐ fā gěi wǒ.", ko: "웹사이트 주소를 저에게 보내주세요." } },
        { zh: "微信", pinyin: "Wēixìn", ko: "위챗(중국 국민 메신저)", pos: "명사", ex: { zh: "我们可以用微信联系。", pinyin: "Wǒmen kěyǐ yòng Wēixìn liánxì.", ko: "우리는 위챗으로 연락할 수 있어요." } },
        { zh: "维修", pinyin: "wéixiū", ko: "수리하다, 보수하다", pos: "동사", ex: { zh: "师傅正在维修空调。", pinyin: "Shīfu zhèngzài wéixiū kōngtiáo.", ko: "기사님이 에어컨을 수리하고 있어요." } },
        { zh: "位于", pinyin: "wèiyú", ko: "~에 위치하다", pos: "동사", ex: { zh: "学校位于市中心。", pinyin: "Xuéxiào wèiyú shì zhōngxīn.", ko: "학교는 시내 중심에 위치해 있어요." } },
        { zh: "味儿", pinyin: "wèir", ko: "맛, 냄새", pos: "명사", ex: { zh: "这道菜味儿真好。", pinyin: "Zhè dào cài wèir zhēn hǎo.", ko: "이 요리는 맛이 정말 좋아요." } },
        { zh: "稳", pinyin: "wěn", ko: "안정적이다, 흔들림 없다", pos: "형용사", ex: { zh: "这张桌子放得很稳。", pinyin: "Zhè zhāng zhuōzi fàng de hěn wěn.", ko: "이 테이블은 매우 안정적으로 놓여 있어요." } },
        { zh: "无法", pinyin: "wúfǎ", ko: "~할 수 없다, 불가능하다", pos: "동사", ex: { zh: "我无法接受这个结果。", pinyin: "Wǒ wúfǎ jiēshòu zhège jiéguǒ.", ko: "나는 이 결과를 받아들일 수 없어요." } },
        { zh: "无所谓", pinyin: "wúsuǒwèi", ko: "상관없다, 개의치 않다", pos: "동사", ex: { zh: "去哪儿吃饭我都无所谓。", pinyin: "Qù nǎr chīfàn wǒ dōu wúsuǒwèi.", ko: "어디서 밥을 먹든 나는 상관없어요." } },
        { zh: "无限", pinyin: "wúxiàn", ko: "무한하다, 끝없다", pos: "동사", ex: { zh: "网络给了我们无限的可能。", pinyin: "Wǎngluò gěi le wǒmen wúxiàn de kěnéng.", ko: "인터넷은 우리에게 무한한 가능성을 주었어요." } },
        { zh: "五颜六色", pinyin: "wǔyán liùsè", ko: "형형색색, 알록달록", pos: "성어", ex: { zh: "花园里开满了五颜六色的花。", pinyin: "Huāyuán lǐ kāimǎn le wǔyánliùsè de huā.", ko: "정원에는 형형색색의 꽃이 만발했어요." } },
        { zh: "吸", pinyin: "xī", ko: "흡수하다, 들이마시다", pos: "동사", ex: { zh: "他深深地吸了一口气。", pinyin: "Tā shēnshēn de xī le yī kǒu qì.", ko: "그는 깊게 숨을 들이마셨어요." } },
        { zh: "吸管", pinyin: "xīguǎn", ko: "빨대", pos: "명사", ex: { zh: "请给我一根吸管。", pinyin: "Qǐng gěi wǒ yī gēn xīguǎn.", ko: "빨대 하나 주세요." } },
        { zh: "吸烟", pinyin: "xīyān", ko: "흡연하다, 담배를 피우다", pos: "동사", ex: { zh: "这里禁止吸烟。", pinyin: "Zhèlǐ jìnzhǐ xīyān.", ko: "여기는 흡연이 금지되어 있어요." } },
        { zh: "喜爱", pinyin: "xǐài", ko: "좋아하다, 사랑하다", pos: "동사", ex: { zh: "很多人喜爱这部小说。", pinyin: "Hěn duō rén xǐ'ài zhè bù xiǎoshuō.", ko: "많은 사람들이 이 소설을 좋아해요." } },
        { zh: "系列", pinyin: "xìliè", ko: "시리즈, 계열", pos: "양사", ex: { zh: "这是一系列关于历史的书。", pinyin: "Zhè shì yī xìliè guānyú lìshǐ de shū.", ko: "이것은 역사에 관한 시리즈 책이에요." } },
        { zh: "细", pinyin: "xì", ko: "가늘다, 세밀하다", pos: "형용사", ex: { zh: "这根线很细。", pinyin: "Zhè gēn xiàn hěn xì.", ko: "이 실은 매우 가늘어요." } },
        { zh: "细致", pinyin: "xìzhì", ko: "세밀하다, 꼼꼼하다", pos: "형용사", ex: { zh: "他工作非常细致。", pinyin: "Tā gōngzuò fēicháng xìzhì.", ko: "그는 일을 매우 꼼꼼하게 해요." } },
        { zh: "下个月", pinyin: "xiàgèyuè", ko: "다음 달", pos: "명사", ex: { zh: "我下个月要去北京出差。", pinyin: "Wǒ xià gè yuè yào qù Běijīng chūchāi.", ko: "나는 다음 달에 베이징으로 출장을 가요." } },
        { zh: "下降", pinyin: "xiàjiàng", ko: "하락하다, 떨어지다", pos: "동사", ex: { zh: "最近气温明显下降。", pinyin: "Zuìjìn qìwēn míngxiǎn xiàjiàng.", ko: "최근 기온이 눈에 띄게 떨어졌어요." } },
        { zh: "下楼", pinyin: "xiàlóu", ko: "아래층으로 내려가다", pos: "동사", ex: { zh: "我马上下楼。", pinyin: "Wǒ mǎ shàng xià lóu.", ko: "나 곧 아래층으로 내려갈게." } },
        { zh: "夏季", pinyin: "xiàjì", ko: "여름철, 하계", pos: "명사", ex: { zh: "夏季气温很高。", pinyin: "Xià jì qì wēn hěn gāo.", ko: "여름철 기온이 매우 높아요." } },
        { zh: "鲜", pinyin: "xiǎn", ko: "드물다, 적다", pos: "형용사", ex: { zh: "这种情况鲜为人知。", pinyin: "Zhè zhǒng qíng kuàng xiǎn wéi rén zhī.", ko: "이런 상황은 아는 사람이 드물어요." } },
        { zh: "鲜花", pinyin: "xiānhuā", ko: "생화, 꽃", pos: "명사", ex: { zh: "她收到了一束鲜花。", pinyin: "Tā shōu dào le yí shù xiān huā.", ko: "그녀는 꽃 한 다발을 받았어요." } },
        { zh: "鲜明", pinyin: "xiānmíng", ko: "선명하다, 뚜렷하다", pos: "형용사", ex: { zh: "这幅画的颜色很鲜明。", pinyin: "Zhè fú huà de yán sè hěn xiān míng.", ko: "이 그림의 색깔은 매우 선명해요." } },
        { zh: "显著", pinyin: "xiǎnzhù", ko: "현저하다, 뚜렷하다", pos: "형용사", ex: { zh: "这项政策取得了显著的效果。", pinyin: "Zhè xiàng zhèng cè qǔ dé le xiǎn zhù de xiào guǒ.", ko: "이 정책은 현저한 효과를 거두었어요." } },
        { zh: "相片", pinyin: "xiàngpiàn", ko: "사진", pos: "명사", ex: { zh: "墙上挂着一张相片。", pinyin: "Qiáng shàng guà zhe yì zhāng xiàng piàn.", ko: "벽에 사진 한 장이 걸려 있어요." } },
        { zh: "箱", pinyin: "xiāng", ko: "상자, 궤짝(단위)", pos: "양사", ex: { zh: "他买了一箱苹果。", pinyin: "Tā mǎi le yì xiāng píng guǒ.", ko: "그는 사과 한 상자를 샀어요." } },
        { zh: "箱子", pinyin: "xiāngzi", ko: "상자, 트렁크", pos: "명사", ex: { zh: "这个箱子很重。", pinyin: "Zhè ge xiāng zi hěn zhòng.", ko: "이 상자는 매우 무거워요." } },
        { zh: "小型", pinyin: "xiǎoxíng", ko: "소형의", pos: "형용사", ex: { zh: "他买了一台小型冰箱。", pinyin: "Tā mǎi le yì tái xiǎo xíng bīng xiāng.", ko: "그는 소형 냉장고를 샀어요." } },
        { zh: "新郎", pinyin: "xīnláng", ko: "신랑", pos: "명사", ex: { zh: "新郎穿着黑色西装。", pinyin: "Xīn láng chuān zhe hēi sè xī zhuāng.", ko: "신랑은 검은색 양복을 입고 있어요." } },
        { zh: "新娘", pinyin: "xīnniáng", ko: "신부", pos: "명사", ex: { zh: "新娘穿着白色婚纱。", pinyin: "Xīn niáng chuān zhe bái sè hūn shā.", ko: "신부는 하얀 웨딩드레스를 입고 있어요." } },
        { zh: "新型", pinyin: "xīnxíng", ko: "신형의, 새로운 유형의", pos: "형용사", ex: { zh: "这是一款新型手机。", pinyin: "Zhè shì yì kuǎn xīn xíng shǒu jī.", ko: "이것은 신형 휴대폰이에요." } },
        { zh: "型", pinyin: "xíng", ko: "형, 유형, 틀", pos: "명사", ex: { zh: "这款车的外型很时尚。", pinyin: "Zhè kuǎn chē de wài xíng hěn shí shàng.", ko: "이 자동차의 외형은 매우 세련되었어요." } },
        { zh: "型号", pinyin: "xínghào", ko: "모델, 규격", pos: "명사", ex: { zh: "这两款手机的型号不同。", pinyin: "Zhè liǎng kuǎn shǒu jī de xíng hào bù tóng.", ko: "이 두 휴대폰의 모델은 달라요." } },
        { zh: "胸部", pinyin: "xiōngbù", ko: "가슴, 흉부", pos: "명사", ex: { zh: "他胸部有点疼。", pinyin: "Tā xiōng bù yǒu diǎn téng.", ko: "그는 가슴이 좀 아파요." } },
        { zh: "修理", pinyin: "xiūlǐ", ko: "수리하다, 고치다", pos: "동사", ex: { zh: "师傅正在修理自行车。", pinyin: "Shī fu zhèng zài xiū lǐ zì xíng chē.", ko: "기사님이 자전거를 수리하고 있어요." } },
        { zh: "学分", pinyin: "xuéfēn", ko: "학점", pos: "명사", ex: { zh: "这门课有三个学分。", pinyin: "Zhè mén kè yǒu sān gè xué fēn.", ko: "이 과목은 3학점이에요." } },
        { zh: "学年", pinyin: "xuénián", ko: "학년(도)", pos: "명사", ex: { zh: "新学年就要开始了。", pinyin: "Xīn xué nián jiù yào kāi shǐ le.", ko: "새 학년(도)이 곧 시작돼요." } },
        { zh: "学时", pinyin: "xuéshí", ko: "수업 시간(단위)", pos: "명사", ex: { zh: "这门课一共有六十个学时。", pinyin: "Zhè mén kè yí gòng yǒu liù shí gè xué shí.", ko: "이 과목은 총 60학시(수업시간)예요." } },
        { zh: "牙", pinyin: "yá", ko: "이, 치아", pos: "명사", ex: { zh: "他的牙很白。", pinyin: "Tā de yá hěn bái.", ko: "그의 치아는 매우 하얘요." } },
        { zh: "牙刷", pinyin: "yáshuā", ko: "칫솔", pos: "명사", ex: { zh: "请给我拿一把新牙刷。", pinyin: "Qǐng gěi wǒ ná yì bǎ xīn yá shuā.", ko: "새 칫솔 하나 가져다 주세요." } },
        { zh: "亚运会", pinyin: "Yàyùnhuì", ko: "아시안게임", pos: "명사", ex: { zh: "亚运会将在这个城市举行。", pinyin: "Yà yùn huì jiāng zài zhè ge chéng shì jǔ xíng.", ko: "아시안게임이 이 도시에서 개최될 예정이에요." } },
        { zh: "延期", pinyin: "yánqī", ko: "연기하다", pos: "동사", ex: { zh: "会议因故延期了。", pinyin: "Huì yì yīn gù yán qī le.", ko: "회의가 사정으로 연기되었어요." } },
        { zh: "延续", pinyin: "yánxù", ko: "지속하다, 계속되다", pos: "동사", ex: { zh: "这个传统延续了几百年。", pinyin: "Zhè ge chuán tǒng yán xù le jǐ bǎi nián.", ko: "이 전통은 수백 년 동안 지속되었어요." } },
        { zh: "严", pinyin: "yán", ko: "엄격하다", pos: "형용사", ex: { zh: "老师对学生要求很严。", pinyin: "Lǎo shī duì xué sheng yāo qiú hěn yán.", ko: "선생님은 학생들에게 매우 엄격하게 요구해요." } },
        { zh: "研制", pinyin: "yánzhì", ko: "연구 제작하다, 개발하다", pos: "동사", ex: { zh: "科学家们正在研制新药。", pinyin: "Kē xué jiā men zhèng zài yán zhì xīn yào.", ko: "과학자들이 신약을 연구 개발하고 있어요." } },
        { zh: "眼泪", pinyin: "yǎnlèi", ko: "눈물", pos: "명사", ex: { zh: "她感动得流下了眼泪。", pinyin: "Tā gǎn dòng de liú xià le yǎn lèi.", ko: "그녀는 감동하여 눈물을 흘렸어요." } },
        { zh: "眼里", pinyin: "yǎnli", ko: "눈에는, 눈 속에", pos: "명사", ex: { zh: "在他眼里,家人最重要。", pinyin: "Zài tā yǎn li, jiā rén zuì zhòng yào.", ko: "그의 눈에는 가족이 가장 중요해요." } },
        { zh: "演讲", pinyin: "yǎnjiǎng", ko: "강연하다, 연설하다", pos: "동사", ex: { zh: "他在大会上做了演讲。", pinyin: "Tā zài dà huì shàng zuò le yǎn jiǎng.", ko: "그는 대회에서 연설을 했어요." } },
        { zh: "药物", pinyin: "yàowù", ko: "약물, 약품", pos: "명사", ex: { zh: "这种药物有副作用。", pinyin: "Zhè zhǒng yào wù yǒu fù zuò yòng.", ko: "이 약물은 부작용이 있어요." } },
        { zh: "一般来说", pinyin: "yībān láishuō", ko: "일반적으로 말하면", pos: "동사", ex: { zh: "一般来说,这里夏天很热。", pinyin: "Yī bān lái shuō, zhè lǐ xià tiān hěn rè.", ko: "일반적으로 말하면, 이곳은 여름이 매우 더워요." } },
        { zh: "一律", pinyin: "yīlǜ", ko: "일률적으로, 모두", pos: "부사", ex: { zh: "迟到者一律扣分。", pinyin: "Chí dào zhě yī lǜ kòu fēn.", ko: "지각자는 일률적으로 감점해요." } },
        { zh: "一再", pinyin: "yīzài", ko: "거듭, 여러 차례", pos: "부사", ex: { zh: "他一再强调这个问题的重要性。", pinyin: "Tā yī zài qiáng diào zhè ge wèn tí de zhòng yào xìng.", ko: "그는 이 문제의 중요성을 거듭 강조했어요." } },
        { zh: "依靠", pinyin: "yīkào", ko: "의지하다, 의존하다", pos: "동사", ex: { zh: "孩子不能一直依靠父母。", pinyin: "Hái zi bù néng yì zhí yī kào fù mǔ.", ko: "아이는 계속 부모에게 의지할 수 없어요." } },
        { zh: "移", pinyin: "yí", ko: "옮기다, 이동하다", pos: "동사", ex: { zh: "请把桌子移到那边。", pinyin: "Qǐng bǎ zhuō zi yí dào nà biān.", ko: "책상을 저쪽으로 옮겨주세요." } },
        { zh: "遗产", pinyin: "yíchǎn", ko: "유산", pos: "명사", ex: { zh: "这座古城是世界文化遗产。", pinyin: "Zhè zuò gǔ chéng shì shì jiè wén huà yí chǎn.", ko: "이 고도는 세계 문화유산이에요." } },
        { zh: "遗传", pinyin: "yíchuán", ko: "유전하다, 유전되다", pos: "동사", ex: { zh: "这种病会遗传给下一代。", pinyin: "Zhè zhǒng bìng huì yí chuán gěi xià yí dài.", ko: "이 병은 다음 세대에게 유전될 수 있어요." } },
        { zh: "以内", pinyin: "yǐnèi", ko: "이내, 이내에", pos: "명사", ex: { zh: "请在三天以内回复。", pinyin: "Qǐng zài sān tiān yǐ nèi huí fù.", ko: "3일 이내에 답장해 주세요." } },
        { zh: "引", pinyin: "yǐn", ko: "끌다, 당기다, 이끌다", pos: "동사", ex: { zh: "他引起了大家的注意。", pinyin: "Tā yǐn qǐ le dà jiā de zhù yì.", ko: "그는 모두의 주의를 끌었어요." } },
        { zh: "引导", pinyin: "yǐndǎo", ko: "인도하다, 안내하다", pos: "동사", ex: { zh: "老师引导学生思考问题。", pinyin: "Lǎo shī yǐn dǎo xué sheng sī kǎo wèn tí.", ko: "선생님은 학생들이 문제를 생각하도록 인도해요." } },
        { zh: "引进", pinyin: "yǐnjìn", ko: "도입하다", pos: "동사", ex: { zh: "公司引进了新技术。", pinyin: "Gōng sī yǐn jìn le xīn jì shù.", ko: "회사는 새로운 기술을 도입했어요." } },
        { zh: "应", pinyin: "yīng", ko: "응답하다; 응당", pos: "동사", ex: { zh: "我们应该努力学习。", pinyin: "Wǒmen yīnggāi nǔlì xuéxí.", ko: "우리는 응당 열심히 공부해야 해요." } },
        { zh: "英勇", pinyin: "yīngyǒng", ko: "용감한, 영웅적인", pos: "형용사", ex: { zh: "消防员英勇地救出了孩子。", pinyin: "Xiāo fáng yuán yīng yǒng de jiù chū le hái zi.", ko: "소방관은 용감하게 아이를 구해냈어요." } },
        { zh: "赢得", pinyin: "yíngdé", ko: "획득하다, 얻다", pos: "동사", ex: { zh: "他赢得了大家的尊重。", pinyin: "Tā yíng dé le dà jiā de zūn zhòng.", ko: "그는 모두의 존경을 얻었어요." } },
        { zh: "优良", pinyin: "yōuliáng", ko: "우수한, 양호한", pos: "형용사", ex: { zh: "这种产品质量优良。", pinyin: "Zhè zhǒng chǎn pǐn zhì liàng yōu liáng.", ko: "이 제품은 품질이 우수해요." } },
        { zh: "有劲儿", pinyin: "yǒujìnr", ko: "힘이 나다, 힘차다", pos: "형용사", ex: { zh: "喝了咖啡我更有劲儿了。", pinyin: "Hē le kā fēi wǒ gèng yǒu jìnr le.", ko: "커피를 마시니 힘이 더 나요." } },
        { zh: "有限", pinyin: "yǒuxiàn", ko: "유한한, 제한적인", pos: "형용사", ex: { zh: "我们的时间有限。", pinyin: "Wǒ men de shí jiān yǒu xiàn.", ko: "우리의 시간은 제한적이에요." } },
        { zh: "语音", pinyin: "yǔyīn", ko: "음성, 발음", pos: "명사", ex: { zh: "请发一条语音消息。", pinyin: "Qǐng fā yì tiáo yǔ yīn xiāo xi.", ko: "음성 메시지를 하나 보내 주세요." } },
        { zh: "玉", pinyin: "yù", ko: "옥", pos: "명사", ex: { zh: "她戴着一块玉。", pinyin: "Tā dài zhe yí kuài yù.", ko: "그녀는 옥 하나를 착용하고 있어요." } },
        { zh: "预测", pinyin: "yùcè", ko: "예측하다", pos: "동사", ex: { zh: "专家预测明天会下雨。", pinyin: "Zhuān jiā yù cè míng tiān huì xià yǔ.", ko: "전문가는 내일 비가 올 것이라고 예측했어요." } },
        { zh: "遇", pinyin: "yù", ko: "만나다, 마주치다; (성씨) 위", pos: "동사", ex: { zh: "我在路上遇到了老朋友。", pinyin: "Wǒ zài lù shàng yùdào le lǎo péngyou.", ko: "나는 길에서 옛 친구를 마주쳤어요." } },
        { zh: "遇见", pinyin: "yùjiàn", ko: "우연히 만나다", pos: "동사", ex: { zh: "我在路上遇见了老朋友。", pinyin: "Wǒ zài lù shang yù jiàn le lǎo péng you.", ko: "나는 길에서 옛 친구를 우연히 만났어요." } },
        { zh: "圆满", pinyin: "yuánmǎn", ko: "원만한, 완벽한", pos: "형용사", ex: { zh: "会议圆满结束了。", pinyin: "Huì yì yuán mǎn jié shù le.", ko: "회의가 원만하게 끝났어요." } },
        { zh: "月底", pinyin: "yuèdǐ", ko: "월말", pos: "명사", ex: { zh: "我月底发工资。", pinyin: "Wǒ yuè dǐ fā gōng zī.", ko: "나는 월말에 월급을 받아요." } },
        { zh: "运动会", pinyin: "yùndònghuì", ko: "운동회", pos: "명사", ex: { zh: "学校下周举行运动会。", pinyin: "Xué xiào xià zhōu jǔ xíng yùn dòng huì.", ko: "학교에서 다음 주 운동회를 열어요." } },
        { zh: "运动员", pinyin: "yùndòngyuán", ko: "운동선수", pos: "명사", ex: { zh: "他是一名优秀的运动员。", pinyin: "Tā shì yì míng yōu xiù de yùn dòng yuán.", ko: "그는 우수한 운동선수예요." } },
        { zh: "在乎", pinyin: "zàihu", ko: "신경 쓰다, 개의하다", pos: "동사", ex: { zh: "我不在乎别人怎么想。", pinyin: "Wǒ bú zài hu bié rén zěn me xiǎng.", ko: "나는 남들이 어떻게 생각하든 신경 쓰지 않아요." } },
        { zh: "在于", pinyin: "zàiyú", ko: "~에 있다, ~에 달려 있다", pos: "동사", ex: { zh: "成功在于坚持。", pinyin: "Chéng gōng zài yú jiān chí.", ko: "성공은 꾸준함에 달려 있어요." } },
        { zh: "赞赏", pinyin: "zànshǎng", ko: "칭찬하다, 높이 평가하다", pos: "동사", ex: { zh: "老师赞赏他的努力。", pinyin: "Lǎo shī zàn shǎng tā de nǔ lì.", ko: "선생님은 그의 노력을 높이 평가했어요." } },
        { zh: "赞助", pinyin: "zànzhù", ko: "후원하다, 협찬하다", pos: "동사", ex: { zh: "这家公司赞助了比赛。", pinyin: "Zhè jiā gōng sī zàn zhù le bǐ sài.", ko: "이 회사는 경기를 후원했어요." } },
        { zh: "造型", pinyin: "zàoxíng", ko: "조형, 스타일", pos: "명사", ex: { zh: "这个雕塑的造型很独特。", pinyin: "Zhè ge diāo sù de zào xíng hěn dú tè.", ko: "이 조각상의 조형은 매우 독특해요." } },
        { zh: "战斗", pinyin: "zhàndòu", ko: "전투하다, 싸우다", pos: "동사", ex: { zh: "士兵们勇敢地战斗。", pinyin: "Shì bīng men yǒng gǎn de zhàn dòu.", ko: "병사들은 용감하게 싸워요." } },
        { zh: "战胜", pinyin: "zhànshèng", ko: "이기다, 극복하다", pos: "동사", ex: { zh: "我们要战胜困难。", pinyin: "Wǒ men yào zhàn shèng kùn nan.", ko: "우리는 어려움을 극복해야 해요." } },
        { zh: "战士", pinyin: "zhànshì", ko: "전사, 군인", pos: "명사", ex: { zh: "战士们保卫祖国。", pinyin: "Zhàn shì men bǎo wèi zǔ guó.", ko: "전사들은 조국을 수호해요." } },
        { zh: "招呼", pinyin: "zhāohu", ko: "인사하다, 부르다", pos: "동사", ex: { zh: "他向我打招呼。", pinyin: "Tā xiàng wǒ dǎ zhāo hu.", ko: "그는 나에게 인사를 했어요." } },
        { zh: "折", pinyin: "shé", ko: "부러지다, 꺾이다", pos: "동사", ex: { zh: "树枝被风吹折了。", pinyin: "Shù zhī bèi fēng chuī shé le.", ko: "나뭇가지가 바람에 부러졌어요." } },
        { zh: "着火", pinyin: "zháohuǒ", ko: "불이 나다", pos: "동사", ex: { zh: "厨房着火了！", pinyin: "Chú fáng zháo huǒ le!", ko: "주방에 불이 났다!" } },
        { zh: "著作", pinyin: "zhùzuò", ko: "저작, 저서", pos: "명사", ex: { zh: "这本书是他的重要著作。", pinyin: "Zhè běn shū shì tā de zhòng yào zhù zuò.", ko: "이 책은 그의 중요한 저서예요." } },
        { zh: "针", pinyin: "zhēn", ko: "바늘, 침, 주사", pos: "명사", ex: { zh: "护士给他打了一针。", pinyin: "Hù shi gěi tā dǎ le yì zhēn.", ko: "간호사가 그에게 주사 한 대를 놓았어요." } },
        { zh: "征服", pinyin: "zhēngfú", ko: "정복하다", pos: "동사", ex: { zh: "他征服了这座高山。", pinyin: "Tā zhēng fú le zhè zuò gāo shān.", ko: "그는 이 높은 산을 정복했어요." } },
        { zh: "之后", pinyin: "zhīhòu", ko: "~후에, 이후", pos: "명사", ex: { zh: "下课之后我们去吃饭。", pinyin: "Xià kè zhī hòu wǒ men qù chī fàn.", ko: "수업이 끝난 후에 우리는 밥 먹으러 가요." } },
        { zh: "之间", pinyin: "zhījiān", ko: "~사이, ~간", pos: "명사", ex: { zh: "他们之间的关系很好。", pinyin: "Tā men zhī jiān de guān xì hěn hǎo.", ko: "그들 사이의 관계는 좋아요." } },
        { zh: "之前", pinyin: "zhīqián", ko: "~전에, 이전", pos: "명사", ex: { zh: "睡觉之前要刷牙。", pinyin: "Shuì jiào zhī qián yào shuā yá.", ko: "자기 전에 양치질을 해야 해요." } },
        { zh: "之一", pinyin: "zhīyī", ko: "~중 하나", pos: "대명사", ex: { zh: "他是我最好的朋友之一。", pinyin: "Tā shì wǒ zuì hǎo de péng you zhī yī.", ko: "그는 나의 가장 친한 친구 중 하나예요." } },
        { zh: "制订", pinyin: "zhìdìng", ko: "제정하다, 세우다", pos: "동사", ex: { zh: "我们要制订一个计划。", pinyin: "Wǒ men yào zhì dìng yí gè jì huà.", ko: "우리는 계획을 하나 세워야 해요." } },
        { zh: "治", pinyin: "zhì", ko: "다스리다, 통치하다", pos: "동사", ex: { zh: "古人以德治国。", pinyin: "Gǔ rén yǐ dé zhì guó.", ko: "옛사람들은 덕으로 나라를 다스렸어요." } },
        { zh: "智力", pinyin: "zhìlì", ko: "지력, 지능", pos: "명사", ex: { zh: "这个游戏能锻炼智力。", pinyin: "Zhè ge yóu xì néng duàn liàn zhì lì.", ko: "이 게임은 지능을 단련시킬 수 있어요." } },
        { zh: "智能", pinyin: "zhìnéng", ko: "지능, 스마트한", pos: "명사", ex: { zh: "这是一部智能手机。", pinyin: "Zhè shì yí bù zhì néng shǒu jī.", ko: "이것은 스마트폰이에요." } },
        { zh: "中奖", pinyin: "zhòngjiǎng", ko: "당첨되다", pos: "동사", ex: { zh: "他买彩票中奖了。", pinyin: "Tā mǎi cǎi piào zhòng jiǎng le.", ko: "그는 복권을 사서 당첨되었어요." } },
        { zh: "种类", pinyin: "zhǒnglèi", ko: "종류", pos: "명사", ex: { zh: "商店里的商品种类很多。", pinyin: "Shāngdiàn lǐ de shāngpǐn zhǒnglèi hěn duō.", ko: "상점에는 상품 종류가 매우 많아요." } },
        { zh: "种植", pinyin: "zhòngzhí", ko: "심다, 재배하다", pos: "동사", ex: { zh: "农民在地里种植水稻。", pinyin: "Nóngmín zài dì lǐ zhòngzhí shuǐdào.", ko: "농부들이 밭에 벼를 심어요." } },
        { zh: "主题", pinyin: "zhǔtí", ko: "주제", pos: "명사", ex: { zh: "这次会议的主题是环保。", pinyin: "Zhè cì huìyì de zhǔtí shì huánbǎo.", ko: "이번 회의의 주제는 환경보호예요." } },
        { zh: "转动", pinyin: "zhuǎndòng", ko: "돌리다, 회전하다", pos: "동사", ex: { zh: "他转动了门把手。", pinyin: "Tā zhuǎndòng le mén bǎshǒu.", ko: "그는 문 손잡이를 돌렸어요." } },
        { zh: "转身", pinyin: "zhuǎnshēn", ko: "몸을 돌리다", pos: "동사", ex: { zh: "她转身离开了。", pinyin: "Tā zhuǎnshēn líkāi le.", ko: "그녀는 몸을 돌려 떠났어요." } },
        { zh: "转弯", pinyin: "zhuǎnwān", ko: "커브를 돌다, 방향을 바꾸다", pos: "동사", ex: { zh: "前面路口请转弯。", pinyin: "Qiánmiàn lùkǒu qǐng zhuǎnwān.", ko: "앞의 교차로에서 방향을 바꿔 주세요." } },
        { zh: "转移", pinyin: "zhuǎnyí", ko: "이전하다, 옮기다", pos: "동사", ex: { zh: "医生把病人转移到了另一间病房。", pinyin: "Yīshēng bǎ bìngrén zhuǎnyí dào le lìng yì jiān bìngfáng.", ko: "의사는 환자를 다른 병실로 옮겼어요." } },
        { zh: "装修", pinyin: "zhuāngxiū", ko: "인테리어 공사를 하다, 실내장식하다", pos: "동사", ex: { zh: "他们家正在装修。", pinyin: "Tāmen jiā zhèngzài zhuāngxiū.", ko: "그들의 집은 지금 인테리어 공사 중이에요." } },
        { zh: "装置", pinyin: "zhuāngzhì", ko: "장치, 설비", pos: "명사", ex: { zh: "这台机器有安全装置。", pinyin: "Zhè tái jīqì yǒu ānquán zhuāngzhì.", ko: "이 기계에는 안전 장치가 있어요." } },
        { zh: "字母", pinyin: "zìmǔ", ko: "알파벳, 글자", pos: "명사", ex: { zh: "英语有二十六个字母。", pinyin: "Yīngyǔ yǒu èrshíliù gè zìmǔ.", ko: "영어에는 26개의 알파벳이 있어요." } },
        { zh: "自", pinyin: "zì", ko: "~로부터, ~에서", pos: "전치사", ex: { zh: "他来自北京。", pinyin: "Tā lái zì Běijīng.", ko: "그는 베이징에서 왔어요." } },
        { zh: "嘴巴", pinyin: "zuǐba", ko: "입", pos: "명사", ex: { zh: "他张开嘴巴笑了。", pinyin: "Tā zhāngkāi zuǐba xiào le.", ko: "그는 입을 벌리고 웃었어요." } },
        { zh: "作出", pinyin: "zuòchū", ko: "(결정 등을) 내리다, 하다", pos: "동사", ex: { zh: "我们要作出正确的选择。", pinyin: "Wǒmen yào zuòchū zhèngquè de xuǎnzé.", ko: "우리는 올바른 선택을 해야 해요." } },
        { zh: "做梦", pinyin: "zuòmèng", ko: "꿈을 꾸다", pos: "동사", ex: { zh: "我昨晚做梦了。", pinyin: "Wǒ zuówǎn zuòmèng le.", ko: "나는 어젯밤 꿈을 꾸었어요." } },
      ],
    },
  ],
}

export default themes;
