/**
 * 5급 어휘 — 추상·논리·전문 영역으로
 * 신문과 토론, 직장 실무를 읽고 말하기 위한 HSK5급 핵심어.
 */
export default {
  level: "H5",
  title: "5급 어휘",
  desc: "추상 개념·경제·심리·논리 연결어까지 — 한자음의 힘이 가장 빛나는 HSK5급 어휘예요.",
  themes: [
    {
      name: "추상 명사",
      words: [
        {
          zh: "概念",
          pinyin: "gàiniàn",
          ko: "개념",
          pos: "명사",
          hanja: "개념(概念) — 한자 그대로예요.",
          ex: { zh: "这个概念有点儿抽象。", pinyin: "zhège gàiniàn yǒudiǎnr chōuxiàng", ko: "이 개념은 조금 추상적이에요." },
        },
        {
          zh: "本质",
          pinyin: "běnzhì",
          ko: "본질",
          pos: "명사",
          hanja: "본질(本質) — 한자 그대로예요.",
          ex: { zh: "我们要看清问题的本质。", pinyin: "wǒmen yào kànqīng wèntí de běnzhì", ko: "우리는 문제의 본질을 똑바로 봐야 해요." },
        },
        {
          zh: "现象",
          pinyin: "xiànxiàng",
          ko: "현상",
          pos: "명사",
          hanja: "현상(現象) — 한자 그대로예요.",
          ex: { zh: "这是一种很常见的社会现象。", pinyin: "zhè shì yì zhǒng hěn chángjiàn de shèhuì xiànxiàng", ko: "이것은 흔한 사회 현상이에요." },
        },
        {
          zh: "因素",
          pinyin: "yīnsù",
          ko: "요인, 요소",
          pos: "명사",
          hanja: "인소(因素) — '因(원인)+素(요소)'. '요인'으로 외워요.",
          ex: { zh: "成功有很多因素。", pinyin: "chénggōng yǒu hěn duō yīnsù", ko: "성공에는 여러 요인이 있어요." },
        },
        {
          zh: "趋势",
          pinyin: "qūshì",
          ko: "추세, 경향",
          pos: "명사",
          hanja: "추세(趨勢) — 한자 그대로예요.",
          ex: { zh: "这是未来发展的趋势。", pinyin: "zhè shì wèilái fāzhǎn de qūshì", ko: "이것은 미래 발전의 추세예요." },
        },
        {
          zh: "规律",
          pinyin: "guīlǜ",
          ko: "규칙, 법칙",
          pos: "명사",
          hanja: "규율(規律) — 한국어 '규율'과 달리 '법칙·규칙성'을 가리켜요.",
          ex: { zh: "生活要有规律。", pinyin: "shēnghuó yào yǒu guīlǜ", ko: "생활은 규칙적이어야 해요." },
        },
        {
          zh: "范围",
          pinyin: "fànwéi",
          ko: "범위",
          pos: "명사",
          hanja: "범위(範圍) — 한자 그대로예요.",
          ex: { zh: "这超出了我的工作范围。", pinyin: "zhè chāochū le wǒ de gōngzuò fànwéi", ko: "이건 제 업무 범위를 벗어났어요." },
        },
        {
          zh: "价值",
          pinyin: "jiàzhí",
          ko: "가치",
          pos: "명사",
          hanja: "가치(價値) — 한자 그대로예요.",
          ex: { zh: "这本书很有价值。", pinyin: "zhè běn shū hěn yǒu jiàzhí", ko: "이 책은 가치가 높아요." },
        },
        {
          zh: "意义",
          pinyin: "yìyì",
          ko: "의의, 의미",
          pos: "명사",
          hanja: "의의(意義) — 한자 그대로예요.",
          ex: { zh: "这件事很有意义。", pinyin: "zhè jiàn shì hěn yǒu yìyì", ko: "이 일은 무척 의미가 있어요." },
        },
        {
          zh: "前途",
          pinyin: "qiántú",
          ko: "장래, 전도",
          pos: "명사",
          hanja: "전도(前途) — '前(앞)+途(길)'. '앞길', 곧 장래예요.",
          ex: { zh: "这个行业很有前途。", pinyin: "zhège hángyè hěn yǒu qiántú", ko: "이 업종은 장래가 밝아요." },
        },
      ],
    },
    {
      name: "심리 동사",
      words: [
        {
          zh: "意识",
          pinyin: "yìshí",
          ko: "의식하다, 깨닫다",
          pos: "동사",
          hanja: "의식(意識) — 한자 그대로지만 '意识到'로 '깨닫다'로 자주 써요.",
          ex: { zh: "他突然意识到自己错了。", pinyin: "tā tūrán yìshídào zìjǐ cuò le", ko: "그는 자기가 틀렸음을 문득 깨달았어요." },
        },
        {
          zh: "体会",
          pinyin: "tǐhuì",
          ko: "체득하다, 실감하다",
          pos: "동사",
          hanja: "체회(體會) — '몸으로 깨닫다'. 직접 느껴 아는 거예요.",
          ex: { zh: "只有经历过才能体会到。", pinyin: "zhǐyǒu jīnglì guo cáinéng tǐhuì dào", ko: "겪어봐야만 비로소 실감할 수 있어요." },
        },
        {
          zh: "佩服",
          pinyin: "pèifú",
          ko: "탄복하다, 존경하다",
          pos: "동사",
          hanja: "패복(佩服) — '차고 따른다'. 마음으로 존경하는 거예요.",
          ex: { zh: "我很佩服他的勇气。", pinyin: "wǒ hěn pèifú tā de yǒngqì", ko: "저는 그의 용기에 탄복해요." },
        },
        {
          zh: "忽视",
          pinyin: "hūshì",
          ko: "소홀히 하다, 무시하다",
          pos: "동사",
          hanja: "홀시(忽視) — '소홀히 보다'. 가볍게 여기는 거예요.",
          ex: { zh: "我们不能忽视这个问题。", pinyin: "wǒmen bù néng hūshì zhège wèntí", ko: "우리는 이 문제를 소홀히 해선 안 돼요." },
        },
        {
          zh: "克服",
          pinyin: "kèfú",
          ko: "극복하다",
          pos: "동사",
          hanja: "극복(克服) — 한자 그대로예요.",
          ex: { zh: "他克服了很多困难。", pinyin: "tā kèfú le hěn duō kùnnan", ko: "그는 많은 어려움을 극복했어요." },
        },
        {
          zh: "适应",
          pinyin: "shìyìng",
          ko: "적응하다",
          pos: "동사",
          hanja: "적응(適應) — 한자 그대로예요.",
          ex: { zh: "她很快适应了新环境。", pinyin: "tā hěn kuài shìyìng le xīn huánjìng", ko: "그녀는 새 환경에 빠르게 적응했어요." },
        },
        {
          zh: "犹豫",
          pinyin: "yóuyù",
          ko: "망설이다, 주저하다",
          pos: "동사",
          hanja: "유예(猶豫) — 한국어 '유예'와 어원은 같지만 뜻은 '머뭇거리다'예요.",
          ex: { zh: "别犹豫了，快做决定吧。", pinyin: "bié yóuyù le, kuài zuò juédìng ba", ko: "망설이지 말고 어서 결정하세요." },
        },
        {
          zh: "盼望",
          pinyin: "pànwàng",
          ko: "간절히 바라다",
          pos: "동사",
          hanja: "반망(盼望) — '盼(바랄 반)+望(바랄 망)'. 손꼽아 기다리는 거예요.",
          ex: { zh: "我们都盼望着春天的到来。", pinyin: "wǒmen dōu pànwàng zhe chūntiān de dàolái", ko: "우리는 모두 봄이 오기를 간절히 바라요." },
        },
        {
          zh: "珍惜",
          pinyin: "zhēnxī",
          ko: "소중히 여기다",
          pos: "동사",
          hanja: "진석(珍惜) — '珍(보배 진)+惜(아낄 석)'. 보배처럼 아끼는 거예요.",
          ex: { zh: "我们要珍惜时间。", pinyin: "wǒmen yào zhēnxī shíjiān", ko: "우리는 시간을 소중히 해야 해요." },
        },
        {
          zh: "感激",
          pinyin: "gǎnjī",
          ko: "감격하다, 깊이 감사하다",
          pos: "동사",
          hanja: "감격(感激) — 한국어 '감격'과 어원은 같으나 '깊이 감사하다'로 많이 써요.",
          ex: { zh: "我非常感激你的帮助。", pinyin: "wǒ fēicháng gǎnjī nǐ de bāngzhù", ko: "당신의 도움에 깊이 감사해요." },
        },
      ],
    },
    {
      name: "경제와 사회",
      words: [
        {
          zh: "投资",
          pinyin: "tóuzī",
          ko: "투자, 투자하다",
          pos: "동사",
          hanja: "투자(投資) — 한자 그대로예요.",
          ex: { zh: "他把钱投资到房地产上。", pinyin: "tā bǎ qián tóuzī dào fángdìchǎn shàng", ko: "그는 돈을 부동산에 투자했어요." },
        },
        {
          zh: "利润",
          pinyin: "lìrùn",
          ko: "이윤",
          pos: "명사",
          hanja: "이윤(利潤) — 한자 그대로예요.",
          ex: { zh: "公司今年的利润增加了。", pinyin: "gōngsī jīnnián de lìrùn zēngjiā le", ko: "회사의 올해 이윤이 늘었어요." },
        },
        {
          zh: "成本",
          pinyin: "chéngběn",
          ko: "원가, 비용",
          pos: "명사",
          hanja: "성본(成本) — '이루는 데 드는 밑천'. '원가'로 외워요.",
          ex: { zh: "我们要降低生产成本。", pinyin: "wǒmen yào jiàngdī shēngchǎn chéngběn", ko: "우리는 생산 원가를 낮춰야 해요." },
        },
        {
          zh: "财产",
          pinyin: "cáichǎn",
          ko: "재산",
          pos: "명사",
          hanja: "재산(財産) — 한자 그대로예요.",
          ex: { zh: "保护个人财产很重要。", pinyin: "bǎohù gèrén cáichǎn hěn zhòngyào", ko: "개인 재산을 보호하는 건 중요해요." },
        },
        {
          zh: "贷款",
          pinyin: "dàikuǎn",
          ko: "대출, 대출하다",
          pos: "동사",
          hanja: "대관(貸款) — '貸(빌릴 대)+款(돈)'. '대출'로 외워요.",
          ex: { zh: "他向银行贷款买房。", pinyin: "tā xiàng yínháng dàikuǎn mǎifáng", ko: "그는 집을 사려고 은행에서 대출받았어요." },
        },
        {
          zh: "效率",
          pinyin: "xiàolǜ",
          ko: "효율",
          pos: "명사",
          hanja: "효율(效率) — 한자 그대로예요.",
          ex: { zh: "这样做可以提高效率。", pinyin: "zhèyàng zuò kěyǐ tígāo xiàolǜ", ko: "이렇게 하면 효율을 높일 수 있어요." },
        },
        {
          zh: "制度",
          pinyin: "zhìdù",
          ko: "제도",
          pos: "명사",
          hanja: "제도(制度) — 한자 그대로예요.",
          ex: { zh: "公司有严格的管理制度。", pinyin: "gōngsī yǒu yángé de guǎnlǐ zhìdù", ko: "회사에는 엄격한 관리 제도가 있어요." },
        },
        {
          zh: "政策",
          pinyin: "zhèngcè",
          ko: "정책",
          pos: "명사",
          hanja: "정책(政策) — 한자 그대로예요.",
          ex: { zh: "政府出台了新政策。", pinyin: "zhèngfǔ chūtái le xīn zhèngcè", ko: "정부가 새 정책을 내놓았어요." },
        },
        {
          zh: "资源",
          pinyin: "zīyuán",
          ko: "자원",
          pos: "명사",
          hanja: "자원(資源) — 한자 그대로예요.",
          ex: { zh: "我们要节约资源。", pinyin: "wǒmen yào jiéyuē zīyuán", ko: "우리는 자원을 절약해야 해요." },
        },
        {
          zh: "规模",
          pinyin: "guīmó",
          ko: "규모",
          pos: "명사",
          hanja: "규모(規模) — 한자 그대로예요.",
          ex: { zh: "这家公司的规模很大。", pinyin: "zhè jiā gōngsī de guīmó hěn dà", ko: "이 회사는 규모가 커요." },
        },
      ],
    },
    {
      name: "고급 형용사",
      words: [
        {
          zh: "抽象",
          pinyin: "chōuxiàng",
          ko: "추상적이다",
          pos: "형용사",
          hanja: "추상(抽象) — 한자 그대로예요.",
          ex: { zh: "他讲的内容太抽象了。", pinyin: "tā jiǎng de nèiróng tài chōuxiàng le", ko: "그가 말한 내용은 너무 추상적이었어요." },
        },
        {
          zh: "具体",
          pinyin: "jùtǐ",
          ko: "구체적이다",
          pos: "형용사",
          hanja: "구체(具體) — 한자 그대로예요.",
          ex: { zh: "请你说得具体一点儿。", pinyin: "qǐng nǐ shuō de jùtǐ yìdiǎnr", ko: "좀 더 구체적으로 말씀해 주세요." },
        },
        {
          zh: "明显",
          pinyin: "míngxiǎn",
          ko: "뚜렷하다, 분명하다",
          pos: "형용사",
          hanja: "명현(明顯) — '밝게 드러나다'. '뚜렷하다'예요.",
          ex: { zh: "他的进步很明显。", pinyin: "tā de jìnbù hěn míngxiǎn", ko: "그의 발전은 뚜렷해요." },
        },
        {
          zh: "严格",
          pinyin: "yángé",
          ko: "엄격하다",
          pos: "형용사",
          hanja: "엄격(嚴格) — 한자 그대로예요.",
          ex: { zh: "这位老师对学生很严格。", pinyin: "zhè wèi lǎoshī duì xuésheng hěn yángé", ko: "이 선생님은 학생에게 엄격해요." },
        },
        {
          zh: "复杂",
          pinyin: "fùzá",
          ko: "복잡하다",
          pos: "형용사",
          hanja: "복잡(複雜) — 한자 그대로예요.",
          ex: { zh: "这个问题很复杂。", pinyin: "zhège wèntí hěn fùzá", ko: "이 문제는 복잡해요." },
        },
        {
          zh: "优秀",
          pinyin: "yōuxiù",
          ko: "우수하다",
          pos: "형용사",
          hanja: "우수(優秀) — 한자 그대로예요.",
          ex: { zh: "她是一名优秀的医生。", pinyin: "tā shì yì míng yōuxiù de yīshēng", ko: "그녀는 우수한 의사예요." },
        },
        {
          zh: "宝贵",
          pinyin: "bǎoguì",
          ko: "귀중하다",
          pos: "형용사",
          hanja: "보귀(寶貴) — '寶(보배)+貴(귀할)'. '귀중하다'예요.",
          ex: { zh: "时间是宝贵的。", pinyin: "shíjiān shì bǎoguì de", ko: "시간은 귀중해요." },
        },
        {
          zh: "巨大",
          pinyin: "jùdà",
          ko: "거대하다, 막대하다",
          pos: "형용사",
          hanja: "거대(巨大) — 한자 그대로예요.",
          ex: { zh: "这件事产生了巨大的影响。", pinyin: "zhè jiàn shì chǎnshēng le jùdà de yǐngxiǎng", ko: "이 일은 막대한 영향을 낳았어요." },
        },
        {
          zh: "成熟",
          pinyin: "chéngshú",
          ko: "성숙하다; 익다",
          pos: "형용사",
          hanja: "성숙(成熟) — 한자 그대로예요.",
          ex: { zh: "他比同龄人成熟得多。", pinyin: "tā bǐ tónglíng rén chéngshú de duō", ko: "그는 또래보다 훨씬 성숙해요." },
        },
        {
          zh: "谨慎",
          pinyin: "jǐnshèn",
          ko: "신중하다",
          pos: "형용사",
          hanja: "근신(謹愼) — 한국어 '근신'과 달리 '신중하다'는 뜻이에요.",
          ex: { zh: "做决定要谨慎。", pinyin: "zuò juédìng yào jǐnshèn", ko: "결정을 내릴 때는 신중해야 해요." },
        },
      ],
    },
    {
      name: "논리와 연결",
      words: [
        {
          zh: "因此",
          pinyin: "yīncǐ",
          ko: "그러므로, 따라서",
          pos: "접속사",
          hanja: "인차(因此) — '이로 인하여'. '따라서'예요.",
          ex: { zh: "他病了，因此没来上课。", pinyin: "tā bìng le, yīncǐ méi lái shàngkè", ko: "그는 아파서, 그래서 수업에 오지 않았어요." },
        },
        {
          zh: "然而",
          pinyin: "rán'ér",
          ko: "그러나, 그렇지만",
          pos: "접속사",
          ex: { zh: "他很努力，然而结果并不理想。", pinyin: "tā hěn nǔlì, rán'ér jiéguǒ bìng bù lǐxiǎng", ko: "그는 열심히 했지만, 결과는 그리 좋지 않았어요." },
        },
        {
          zh: "不仅",
          pinyin: "bùjǐn",
          ko: "~뿐만 아니라",
          pos: "접속사",
          hanja: "불근(不僅) — '~에 그치지 않고'. 뒤에 而且가 자주 와요.",
          ex: { zh: "他不仅聪明，而且很努力。", pinyin: "tā bùjǐn cōngming, érqiě hěn nǔlì", ko: "그는 똑똑할 뿐 아니라 노력도 해요." },
        },
        {
          zh: "从而",
          pinyin: "cóng'ér",
          ko: "그리하여, 그럼으로써",
          pos: "접속사",
          ex: { zh: "他改进了方法，从而提高了效率。", pinyin: "tā gǎijìn le fāngfǎ, cóng'ér tígāo le xiàolǜ", ko: "그는 방법을 개선했고, 그럼으로써 효율을 높였어요." },
        },
        {
          zh: "总之",
          pinyin: "zǒngzhī",
          ko: "요컨대, 한마디로",
          pos: "접속사",
          hanja: "총지(總之) — '통틀어 말하면'. '요컨대'예요.",
          ex: { zh: "总之，这是一个好机会。", pinyin: "zǒngzhī, zhè shì yí ge hǎo jīhuì", ko: "요컨대, 이건 좋은 기회예요." },
        },
        {
          zh: "何况",
          pinyin: "hékuàng",
          ko: "하물며, 더구나",
          pos: "접속사",
          ex: { zh: "大人都做不到，何况孩子。", pinyin: "dàrén dōu zuòbudào, hékuàng háizi", ko: "어른도 못 하는데, 하물며 아이는요." },
        },
        {
          zh: "宁可",
          pinyin: "nìngkě",
          ko: "차라리 ~할지언정",
          pos: "부사",
          hanja: "영가(寧可) — '차라리 ~함이 낫다'. 뒤에 也不가 자주 와요.",
          ex: { zh: "我宁可走路，也不坐他的车。", pinyin: "wǒ nìngkě zǒulù, yě bù zuò tā de chē", ko: "저는 차라리 걸을지언정 그의 차는 안 타요." },
        },
        {
          zh: "毕竟",
          pinyin: "bìjìng",
          ko: "결국, 어쨌든",
          pos: "부사",
          hanja: "필경(畢竟) — 한국어 '필경'과 같아요. '어쨌든'이에요.",
          ex: { zh: "他毕竟还是个孩子。", pinyin: "tā bìjìng háishi ge háizi", ko: "그는 어쨌든 아직 아이예요." },
        },
        {
          zh: "难免",
          pinyin: "nánmiǎn",
          ko: "면하기 어렵다, 으레 ~하기 마련",
          pos: "부사",
          hanja: "난면(難免) — '면하기 어렵다'. 피할 수 없다는 뜻이에요.",
          ex: { zh: "第一次难免会紧张。", pinyin: "dì-yī cì nánmiǎn huì jǐnzhāng", ko: "처음에는 으레 긴장하기 마련이에요." },
        },
        {
          zh: "的确",
          pinyin: "díquè",
          ko: "확실히, 정말로",
          pos: "부사",
          hanja: "적확(的確) — 한국어 '적확'과 어원이 같아요. '확실히'예요.",
          ex: { zh: "这件事的确很难办。", pinyin: "zhè jiàn shì díquè hěn nán bàn", ko: "이 일은 확실히 처리하기 어려워요." },
        },
      ],
    },
    {
      name: "과학과 문화",
      words: [
        {
          zh: "科技",
          pinyin: "kējì",
          ko: "과학 기술",
          pos: "명사",
          hanja: "과기(科技) — '과학(科學)+기술(技術)'의 줄임말이에요.",
          ex: { zh: "现代科技改变了我们的生活。", pinyin: "xiàndài kējì gǎibiàn le wǒmen de shēnghuó", ko: "현대 과학 기술이 우리 삶을 바꿨어요." },
        },
        {
          zh: "理论",
          pinyin: "lǐlùn",
          ko: "이론",
          pos: "명사",
          hanja: "이론(理論) — 한자 그대로예요.",
          ex: { zh: "理论要和实践结合。", pinyin: "lǐlùn yào hé shíjiàn jiéhé", ko: "이론은 실천과 결합해야 해요." },
        },
        {
          zh: "实践",
          pinyin: "shíjiàn",
          ko: "실천, 실천하다",
          pos: "동사",
          hanja: "실천(實踐) — 한자 그대로예요.",
          ex: { zh: "把学到的知识用到实践中。", pinyin: "bǎ xuédào de zhīshi yòngdào shíjiàn zhōng", ko: "배운 지식을 실천에 활용해요." },
        },
        {
          zh: "实验",
          pinyin: "shíyàn",
          ko: "실험",
          pos: "명사",
          hanja: "실험(實驗) — 한자 그대로예요.",
          ex: { zh: "这个实验很成功。", pinyin: "zhège shíyàn hěn chénggōng", ko: "이 실험은 성공적이었어요." },
        },
        {
          zh: "证明",
          pinyin: "zhèngmíng",
          ko: "증명하다",
          pos: "동사",
          hanja: "증명(證明) — 한자 그대로예요.",
          ex: { zh: "事实证明他是对的。", pinyin: "shìshí zhèngmíng tā shì duì de", ko: "사실이 그가 옳았음을 증명했어요." },
        },
        {
          zh: "传统",
          pinyin: "chuántǒng",
          ko: "전통",
          pos: "명사",
          hanja: "전통(傳統) — 한자 그대로예요.",
          ex: { zh: "我们要保护传统文化。", pinyin: "wǒmen yào bǎohù chuántǒng wénhuà", ko: "우리는 전통 문화를 지켜야 해요." },
        },
        {
          zh: "创造",
          pinyin: "chuàngzào",
          ko: "창조하다, 만들어내다",
          pos: "동사",
          hanja: "창조(創造) — 한자 그대로예요.",
          ex: { zh: "他们创造了一个新纪录。", pinyin: "tāmen chuàngzào le yí ge xīn jìlù", ko: "그들은 새 기록을 만들어냈어요." },
        },
        {
          zh: "象征",
          pinyin: "xiàngzhēng",
          ko: "상징, 상징하다",
          pos: "동사",
          hanja: "상징(象徵) — 한자 그대로예요.",
          ex: { zh: "鸽子象征着和平。", pinyin: "gēzi xiàngzhēng zhe hépíng", ko: "비둘기는 평화를 상징해요." },
        },
        {
          zh: "成果",
          pinyin: "chéngguǒ",
          ko: "성과, 결실",
          pos: "명사",
          hanja: "성과(成果) — 한자 그대로예요.",
          ex: { zh: "这是大家共同努力的成果。", pinyin: "zhè shì dàjiā gòngtóng nǔlì de chéngguǒ", ko: "이건 모두가 함께 노력한 성과예요." },
        },
        {
          zh: "促进",
          pinyin: "cùjìn",
          ko: "촉진하다",
          pos: "동사",
          hanja: "촉진(促進) — 한자 그대로예요.",
          ex: { zh: "贸易促进了两国的合作。", pinyin: "màoyì cùjìn le liǎng guó de hézuò", ko: "무역이 두 나라의 협력을 촉진했어요." },
        },
      ],
    },
    {
      name: "상태와 변화 동사",
      words: [
        {
          zh: "改善",
          pinyin: "gǎishàn",
          ko: "개선하다",
          pos: "동사",
          hanja: "개선(改善) — 한자 그대로예요.",
          ex: { zh: "政府努力改善人民的生活。", pinyin: "zhèngfǔ nǔlì gǎishàn rénmín de shēnghuó", ko: "정부는 국민의 삶을 개선하고자 애써요." },
        },
        {
          zh: "维持",
          pinyin: "wéichí",
          ko: "유지하다",
          pos: "동사",
          hanja: "유지(維持) — 한자 그대로예요.",
          ex: { zh: "他努力维持着家庭的平衡。", pinyin: "tā nǔlì wéichí zhe jiātíng de pínghéng", ko: "그는 가정의 균형을 유지하려 애써요." },
        },
        {
          zh: "扩大",
          pinyin: "kuòdà",
          ko: "확대하다",
          pos: "동사",
          hanja: "확대(擴大) — 한자 그대로예요.",
          ex: { zh: "公司打算扩大生产规模。", pinyin: "gōngsī dǎsuàn kuòdà shēngchǎn guīmó", ko: "회사는 생산 규모를 확대할 계획이에요." },
        },
        {
          zh: "缩小",
          pinyin: "suōxiǎo",
          ko: "축소하다, 줄이다",
          pos: "동사",
          hanja: "축소(縮小) — 한자 그대로예요.",
          ex: { zh: "两地的差距正在缩小。", pinyin: "liǎng dì de chājù zhèngzài suōxiǎo", ko: "두 지역의 격차가 줄어들고 있어요." },
        },
        {
          zh: "调整",
          pinyin: "tiáozhěng",
          ko: "조정하다",
          pos: "동사",
          hanja: "조정(調整) — 한자 그대로예요.",
          ex: { zh: "我需要调整一下计划。", pinyin: "wǒ xūyào tiáozhěng yíxià jìhuà", ko: "저는 계획을 좀 조정해야 해요." },
        },
        {
          zh: "保持",
          pinyin: "bǎochí",
          ko: "유지하다, 지키다",
          pos: "동사",
          hanja: "보지(保持) — '지녀 지키다'. 상태를 그대로 '유지하다'예요.",
          ex: { zh: "请保持安静。", pinyin: "qǐng bǎochí ānjìng", ko: "조용히 해 주세요." },
        },
        {
          zh: "实现",
          pinyin: "shíxiàn",
          ko: "실현하다, 이루다",
          pos: "동사",
          hanja: "실현(實現) — 한자 그대로예요.",
          ex: { zh: "他终于实现了自己的梦想。", pinyin: "tā zhōngyú shíxiàn le zìjǐ de mèngxiǎng", ko: "그는 마침내 자신의 꿈을 이뤘어요." },
        },
        {
          zh: "形成",
          pinyin: "xíngchéng",
          ko: "형성하다, 이루어지다",
          pos: "동사",
          hanja: "형성(形成) — 한자 그대로예요.",
          ex: { zh: "这种习惯是慢慢形成的。", pinyin: "zhè zhǒng xíguàn shì mànmàn xíngchéng de", ko: "이런 습관은 서서히 형성된 거예요." },
        },
        {
          zh: "确认",
          pinyin: "quèrèn",
          ko: "확인하다",
          pos: "동사",
          hanja: "확인(確認) — 한자 그대로예요.",
          ex: { zh: "请再确认一下时间。", pinyin: "qǐng zài quèrèn yíxià shíjiān", ko: "시간을 다시 한번 확인해 주세요." },
        },
        {
          zh: "承担",
          pinyin: "chéngdān",
          ko: "떠맡다, 부담하다",
          pos: "동사",
          hanja: "승담(承擔) — '받아 짊어지다'. 책임을 떠맡는 거예요.",
          ex: { zh: "他愿意承担这个责任。", pinyin: "tā yuànyì chéngdān zhège zérèn", ko: "그는 이 책임을 기꺼이 떠맡으려 해요." },
        },
      ],
    },
    {
      name: "교재 보충 어휘",
      words: [
        {
          zh: "教育",
          pinyin: "jiàoyù",
          ko: "교육, 교육하다",
          pos: "명사",
          hanja: "교육(敎育) — 한자 그대로예요.",
          ex: { zh: "本次会议讨论了教育、医疗以及环保等问题。", pinyin: "běn cì huìyì tǎolùn le jiàoyù yīliáo yǐjí huánbǎo děng wèntí", ko: "이번 회의는 교육, 의료 및 환경보호 등의 문제를 논의했어요." },
        },
        {
          zh: "医疗",
          pinyin: "yīliáo",
          ko: "의료",
          pos: "명사",
          hanja: "의료(醫療) — 한자 그대로예요.",
          ex: { zh: "农村的医疗条件改善了很多。", pinyin: "nóngcūn de yīliáo tiáojiàn gǎishàn le hěn duō", ko: "농촌의 의료 여건이 많이 개선됐어요." },
        },
        {
          zh: "环保",
          pinyin: "huánbǎo",
          ko: "환경 보호",
          pos: "명사",
          hanja: "환보(環保) — '환경보호(環境保護)'의 줄임말이에요.",
          ex: { zh: "政府制定了新的环保政策。", pinyin: "zhèngfǔ zhìdìng le xīn de huánbǎo zhèngcè", ko: "정부는 새로운 환경보호 정책을 제정했어요." },
        },
        {
          zh: "以及",
          pinyin: "yǐjí",
          ko: "및, 그리고",
          pos: "접속사",
          hanja: "이급(以及) — 한국어 '및(及)'의 격식 표현이에요. 和보다 글말에 어울려요.",
          ex: { zh: "本次会议讨论了教育、医疗以及环保等问题。", pinyin: "běn cì huìyì tǎolùn le jiàoyù yīliáo yǐjí huánbǎo děng wèntí", ko: "이번 회의는 교육, 의료 및 환경보호 등의 문제를 논의했어요." },
        },
        {
          zh: "原因",
          pinyin: "yuányīn",
          ko: "원인, 까닭",
          pos: "명사",
          hanja: "원인(原因) — 한자 그대로예요.",
          ex: { zh: "由于天气原因，航班被取消了。", pinyin: "yóuyú tiānqì yuányīn, hángbān bèi qǔxiāo le", ko: "날씨 때문에 항공편이 취소됐어요." },
        },
        {
          zh: "航班",
          pinyin: "hángbān",
          ko: "항공편",
          pos: "명사",
          hanja: "항반(航班) — '항공편'을 가리켜요.",
          ex: { zh: "由于天气原因，航班被取消了。", pinyin: "yóuyú tiānqì yuányīn, hángbān bèi qǔxiāo le", ko: "날씨 때문에 항공편이 취소됐어요." },
        },
        {
          zh: "取消",
          pinyin: "qǔxiāo",
          ko: "취소하다",
          pos: "동사",
          hanja: "취소(取消) — 한자 그대로예요.",
          ex: { zh: "由于天气不好，比赛取消了。", pinyin: "yóuyú tiānqì bù hǎo, bǐsài qǔxiāo le", ko: "날씨가 안 좋아서 경기가 취소됐어요." },
        },
        {
          zh: "推出",
          pinyin: "tuīchū",
          ko: "내놓다, 출시하다",
          pos: "동사",
          hanja: "추출(推出) — '밀어 내놓다'. 새로 선보이는 거예요.",
          ex: { zh: "本公司将于下月推出新产品。", pinyin: "běn gōngsī jiāng yú xià yuè tuīchū xīn chǎnpǐn", ko: "본사는 다음 달에 신제품을 출시할 예정이에요." },
        },
        {
          zh: "产品",
          pinyin: "chǎnpǐn",
          ko: "제품, 상품",
          pos: "명사",
          hanja: "산품(産品) — '생산된 물품', 곧 제품이에요.",
          ex: { zh: "本公司将于下月推出新产品。", pinyin: "běn gōngsī jiāng yú xià yuè tuīchū xīn chǎnpǐn", ko: "본사는 다음 달에 신제품을 출시할 예정이에요." },
        },
        {
          zh: "方案",
          pinyin: "fāng'àn",
          ko: "방안, 계획",
          pos: "명사",
          hanja: "방안(方案) — 한자 그대로예요.",
          ex: { zh: "该方案已获得批准。", pinyin: "gāi fāng'àn yǐ huòdé pīzhǔn", ko: "해당 방안은 이미 승인을 받았어요." },
        },
        {
          zh: "获得",
          pinyin: "huòdé",
          ko: "획득하다, 얻다",
          pos: "동사",
          hanja: "획득(獲得) — 한자 그대로예요.",
          ex: { zh: "该方案已获得批准。", pinyin: "gāi fāng'àn yǐ huòdé pīzhǔn", ko: "해당 방안은 이미 승인을 받았어요." },
        },
        {
          zh: "批准",
          pinyin: "pīzhǔn",
          ko: "비준하다, 승인하다",
          pos: "동사",
          hanja: "비준(批准) — 한자 그대로예요.",
          ex: { zh: "该方案已获得批准。", pinyin: "gāi fāng'àn yǐ huòdé pīzhǔn", ko: "해당 방안은 이미 승인을 받았어요." },
        },
        {
          zh: "气馁",
          pinyin: "qìněi",
          ko: "낙담하다, 기가 죽다",
          pos: "동사",
          hanja: "기뇌(氣餒) — '기운(氣)이 꺾이다'. 의기소침해지는 거예요.",
          ex: { zh: "实验失败了，然而我们并不气馁。", pinyin: "shíyàn shībài le, rán'ér wǒmen bìng bù qìněi", ko: "실험은 실패했지만, 우리는 결코 낙담하지 않았어요." },
        },
        {
          zh: "受到",
          pinyin: "shòudào",
          ko: "받다, 입다",
          pos: "동사",
          hanja: "수도(受到) — '受(받을 수)+到'. 어떤 작용을 받는 거예요.",
          ex: { zh: "他的作品受到了广泛的欢迎。", pinyin: "tā de zuòpǐn shòudào le guǎngfàn de huānyíng", ko: "그의 작품은 폭넓은 환영을 받았어요." },
        },
        {
          zh: "坚持",
          pinyin: "jiānchí",
          ko: "꾸준히 하다, 견지하다",
          pos: "동사",
          hanja: "견지(堅持) — '굳게 지키다'. 끝까지 밀고 나가는 거예요.",
          ex: { zh: "他坚持锻炼，从而改善了身体状况。", pinyin: "tā jiānchí duànliàn, cóng'ér gǎishàn le shēntǐ zhuàngkuàng", ko: "그는 꾸준히 운동했고, 그리하여 몸 상태를 개선했어요." },
        },
        {
          zh: "身体",
          pinyin: "shēntǐ",
          ko: "몸, 신체",
          pos: "명사",
          hanja: "신체(身體) — 한자 그대로예요.",
          ex: { zh: "他坚持锻炼，从而改善了身体状况。", pinyin: "tā jiānchí duànliàn, cóng'ér gǎishàn le shēntǐ zhuàngkuàng", ko: "그는 꾸준히 운동했고, 그리하여 몸 상태를 개선했어요." },
        },
        {
          zh: "状况",
          pinyin: "zhuàngkuàng",
          ko: "상황, 상태",
          pos: "명사",
          hanja: "상황(狀況) — 한자 그대로예요.",
          ex: { zh: "他坚持锻炼，从而改善了身体状况。", pinyin: "tā jiānchí duànliàn, cóng'ér gǎishàn le shēntǐ zhuàngkuàng", ko: "그는 꾸준히 운동했고, 그리하여 몸 상태를 개선했어요." },
        },
        {
          zh: "降低",
          pinyin: "jiàngdī",
          ko: "낮추다, 내리다",
          pos: "동사",
          hanja: "강저(降低) — '내려 낮추다'예요.",
          ex: { zh: "降低成本，从而提高竞争力。", pinyin: "jiàngdī chéngběn, cóng'ér tígāo jìngzhēnglì", ko: "원가를 낮춰서 그로써 경쟁력을 높여요." },
        },
        {
          zh: "竞争力",
          pinyin: "jìngzhēnglì",
          ko: "경쟁력",
          pos: "명사",
          hanja: "경쟁력(競爭力) — 한자 그대로예요.",
          ex: { zh: "降低成本，从而提高竞争力。", pinyin: "jiàngdī chéngběn, cóng'ér tígāo jìngzhēnglì", ko: "원가를 낮춰서 그로써 경쟁력을 높여요." },
        },
        {
          zh: "研究",
          pinyin: "yánjiū",
          ko: "연구, 연구하다",
          pos: "동사",
          hanja: "연구(硏究) — 한자 그대로예요.",
          ex: { zh: "这项研究有助于理解大脑，进而推动医学发展。", pinyin: "zhè xiàng yánjiū yǒuzhù yú lǐjiě dànǎo, jìn'ér tuīdòng yīxué fāzhǎn", ko: "이 연구는 뇌 이해에 도움이 되고, 나아가 의학 발전을 추동해요." },
        },
        {
          zh: "理解",
          pinyin: "lǐjiě",
          ko: "이해하다",
          pos: "동사",
          hanja: "이해(理解) — 한자 그대로예요.",
          ex: { zh: "我们要先了解问题，进而解决问题。", pinyin: "wǒmen yào xiān liǎojiě wèntí, jìn'ér jiějué wèntí", ko: "우리는 먼저 문제를 이해하고, 더 나아가 문제를 해결해야 해요." },
        },
        {
          zh: "大脑",
          pinyin: "dànǎo",
          ko: "대뇌, 뇌",
          pos: "명사",
          hanja: "대뇌(大腦) — 한자 그대로예요.",
          ex: { zh: "这项研究有助于理解大脑，进而推动医学发展。", pinyin: "zhè xiàng yánjiū yǒuzhù yú lǐjiě dànǎo, jìn'ér tuīdòng yīxué fāzhǎn", ko: "이 연구는 뇌 이해에 도움이 되고, 나아가 의학 발전을 추동해요." },
        },
        {
          zh: "推动",
          pinyin: "tuīdòng",
          ko: "추동하다, 밀고 나가다",
          pos: "동사",
          hanja: "추동(推動) — '밀어 움직이다'. 일을 진전시키는 거예요.",
          ex: { zh: "这项研究有助于理解大脑，进而推动医学发展。", pinyin: "zhè xiàng yánjiū yǒuzhù yú lǐjiě dànǎo, jìn'ér tuīdòng yīxué fāzhǎn", ko: "이 연구는 뇌 이해에 도움이 되고, 나아가 의학 발전을 추동해요." },
        },
        {
          zh: "医学",
          pinyin: "yīxué",
          ko: "의학",
          pos: "명사",
          hanja: "의학(醫學) — 한자 그대로예요.",
          ex: { zh: "这项研究有助于理解大脑，进而推动医学发展。", pinyin: "zhè xiàng yánjiū yǒuzhù yú lǐjiě dànǎo, jìn'ér tuīdòng yīxué fāzhǎn", ko: "이 연구는 뇌 이해에 도움이 되고, 나아가 의학 발전을 추동해요." },
        },
        {
          zh: "发展",
          pinyin: "fāzhǎn",
          ko: "발전, 발전하다",
          pos: "동사",
          hanja: "발전(發展) — 한자 그대로예요.",
          ex: { zh: "这项研究有助于理解大脑，进而推动医学发展。", pinyin: "zhè xiàng yánjiū yǒuzhù yú lǐjiě dànǎo, jìn'ér tuīdòng yīxué fāzhǎn", ko: "이 연구는 뇌 이해에 도움이 되고, 나아가 의학 발전을 추동해요." },
        },
        {
          zh: "饮食",
          pinyin: "yǐnshí",
          ko: "음식, 식사",
          pos: "명사",
          hanja: "음식(飮食) — 한자 그대로예요.",
          ex: { zh: "饮食、运动、睡眠，总之，健康需要全面的努力。", pinyin: "yǐnshí yùndòng shuìmián, zǒngzhī, jiànkāng xūyào quánmiàn de nǔlì", ko: "식사, 운동, 수면 — 요컨대 건강은 전면적인 노력이 필요해요." },
        },
        {
          zh: "睡眠",
          pinyin: "shuìmián",
          ko: "수면, 잠",
          pos: "명사",
          hanja: "수면(睡眠) — 한자 그대로예요.",
          ex: { zh: "饮食、运动、睡眠，总之，健康需要全面的努力。", pinyin: "yǐnshí yùndòng shuìmián, zǒngzhī, jiànkāng xūyào quánmiàn de nǔlì", ko: "식사, 운동, 수면 — 요컨대 건강은 전면적인 노력이 필요해요." },
        },
        {
          zh: "全面",
          pinyin: "quánmiàn",
          ko: "전면적이다, 전반적이다",
          pos: "형용사",
          hanja: "전면(全面) — '모든 면', 곧 빠짐없이 전반적인 거예요.",
          ex: { zh: "饮食、运动、睡眠，总之，健康需要全面的努力。", pinyin: "yǐnshí yùndòng shuìmián, zǒngzhī, jiànkāng xūyào quánmiàn de nǔlì", ko: "식사, 운동, 수면 — 요컨대 건강은 전면적인 노력이 필요해요." },
        },
        {
          zh: "尝试",
          pinyin: "chángshì",
          ko: "시도, 시도하다",
          pos: "동사",
          hanja: "상시(嘗試) — '맛보아 시험하다'. 한번 해 보는 거예요.",
          ex: { zh: "总而言之，这是一次成功的尝试。", pinyin: "zǒng'éryánzhī, zhè shì yí cì chénggōng de chángshì", ko: "총괄하자면, 이것은 성공적인 시도였어요." },
        },
        {
          zh: "赞叹",
          pinyin: "zàntàn",
          ko: "감탄하다, 찬탄하다",
          pos: "동사",
          hanja: "찬탄(讚歎) — 한자 그대로예요.",
          ex: { zh: "他的画栩栩如生，令人赞叹。", pinyin: "tā de huà xǔxǔ-rúshēng, lìng rén zàntàn", ko: "그의 그림은 살아 있는 듯 생생해서 감탄하게 해요." },
        },
        {
          zh: "做事",
          pinyin: "zuòshì",
          ko: "일을 하다, 처신하다",
          pos: "동사",
          hanja: "주사(做事) — '일(事)을 하다(做)'예요.",
          ex: { zh: "做事不能半途而废。", pinyin: "zuò shì bù néng bàntú'érfèi", ko: "일은 중도에 그만두면 안 돼요." },
        },
        {
          zh: "面对",
          pinyin: "miànduì",
          ko: "마주하다, 직면하다",
          pos: "동사",
          hanja: "면대(面對) — '얼굴을 마주하다'. 맞닥뜨리는 거예요.",
          ex: { zh: "面对困难，我们要坚持不懈。", pinyin: "miànduì kùnnan, wǒmen yào jiānchí-búxiè", ko: "어려움 앞에서 우리는 끈기 있게 버텨야 해요." },
        },
        {
          zh: "困难",
          pinyin: "kùnnan",
          ko: "어려움, 곤란하다",
          pos: "명사",
          hanja: "곤란(困難) — 한자 그대로예요.",
          ex: { zh: "面对困难，我们要坚持不懈。", pinyin: "miànduì kùnnan, wǒmen yào jiānchí-búxiè", ko: "어려움 앞에서 우리는 끈기 있게 버텨야 해요." },
        },
        {
          zh: "消息",
          pinyin: "xiāoxi",
          ko: "소식",
          pos: "명사",
          hanja: "소식(消息) — 한자 그대로예요.",
          ex: { zh: "这个消息使大家很激动。", pinyin: "zhège xiāoxi shǐ dàjiā hěn jīdòng", ko: "이 소식은 모두를 매우 들뜨게 했어요." },
        },
        {
          zh: "演出",
          pinyin: "yǎnchū",
          ko: "공연, 공연하다",
          pos: "명사",
          hanja: "연출(演出) — 한국어 '연출'과 글자는 같지만 '공연·상연'을 뜻해요.",
          ex: { zh: "那场演出令人难忘。", pinyin: "nà chǎng yǎnchū lìng rén nánwàng", ko: "그 공연은 잊을 수 없게 만들었어요." },
        },
        {
          zh: "难忘",
          pinyin: "nánwàng",
          ko: "잊기 어렵다, 잊을 수 없다",
          pos: "형용사",
          hanja: "난망(難忘) — '잊기(忘) 어렵다(難)'예요.",
          ex: { zh: "那场演出令人难忘。", pinyin: "nà chǎng yǎnchū lìng rén nánwàng", ko: "그 공연은 잊을 수 없게 만들었어요." },
        },
        {
          zh: "比赛",
          pinyin: "bǐsài",
          ko: "경기, 시합",
          pos: "명사",
          hanja: "비새(比賽) — '겨루다(賽)'. 경기·시합이에요.",
          ex: { zh: "比赛结果令人失望。", pinyin: "bǐsài jiéguǒ lìng rén shīwàng", ko: "경기 결과는 실망스러웠어요." },
        },
        {
          zh: "结果",
          pinyin: "jiéguǒ",
          ko: "결과",
          pos: "명사",
          hanja: "결과(結果) — 한자 그대로예요.",
          ex: { zh: "比赛结果令人失望。", pinyin: "bǐsài jiéguǒ lìng rén shīwàng", ko: "경기 결과는 실망스러웠어요." },
        },
        {
          zh: "生活",
          pinyin: "shēnghuó",
          ko: "생활, 삶, 생활하다",
          pos: "명사",
          hanja: "생활(生活) — 한자 그대로예요.",
          ex: { zh: "科技的发展使生活更加便利。", pinyin: "kējì de fāzhǎn shǐ shēnghuó gèngjiā biànlì", ko: "과학기술의 발전은 생활을 더욱 편리하게 만들어요." },
        },
        {
          zh: "便利",
          pinyin: "biànlì",
          ko: "편리하다",
          pos: "형용사",
          hanja: "편리(便利) — 한자 그대로예요. 여기서 便은 biàn으로 읽어요.",
          ex: { zh: "科技的发展使生活更加便利。", pinyin: "kējì de fāzhǎn shǐ shēnghuó gèngjiā biànlì", ko: "과학기술의 발전은 생활을 더욱 편리하게 만들어요." },
        },
        {
          zh: "自行车",
          pinyin: "zìxíngchē",
          ko: "자전거",
          pos: "명사",
          hanja: "자행거(自行車) — '스스로 굴러가는 수레', 곧 자전거예요.",
          ex: { zh: "我的自行车被偷了。", pinyin: "wǒ de zìxíngchē bèi tōu le", ko: "제 자전거를 도둑맞았어요." },
        },
        {
          zh: "项目",
          pinyin: "xiàngmù",
          ko: "프로젝트, 항목",
          pos: "명사",
          hanja: "항목(項目) — 한자 그대로지만 '프로젝트·종목'으로도 써요.",
          ex: { zh: "这个项目由王经理负责。", pinyin: "zhège xiàngmù yóu Wáng jīnglǐ fùzé", ko: "이 프로젝트는 왕 매니저가 맡아요." },
        },
        {
          zh: "负责",
          pinyin: "fùzé",
          ko: "책임지다, 담당하다",
          pos: "동사",
          hanja: "부책(負責) — '책임(責)을 지다(負)'예요.",
          ex: { zh: "这个项目由王经理负责。", pinyin: "zhège xiàngmù yóu Wáng jīnglǐ fùzé", ko: "이 프로젝트는 왕 매니저가 맡아요." },
        },
        {
          zh: "作品",
          pinyin: "zuòpǐn",
          ko: "작품",
          pos: "명사",
          hanja: "작품(作品) — 한자 그대로예요.",
          ex: { zh: "他的作品受到了广泛的欢迎。", pinyin: "tā de zuòpǐn shòudào le guǎngfàn de huānyíng", ko: "그의 작품은 폭넓은 환영을 받았어요." },
        },
        {
          zh: "广泛",
          pinyin: "guǎngfàn",
          ko: "광범위하다, 폭넓다",
          pos: "형용사",
          hanja: "광범(廣泛) — '넓게 퍼지다'. 범위가 넓은 거예요.",
          ex: { zh: "他的作品受到了广泛的欢迎。", pinyin: "tā de zuòpǐn shòudào le guǎngfàn de huānyíng", ko: "그의 작품은 폭넓은 환영을 받았어요." },
        },
        {
          zh: "科学家",
          pinyin: "kēxuéjiā",
          ko: "과학자",
          pos: "명사",
          hanja: "과학가(科學家) — '과학(科學)+가(家)'. 과학자예요.",
          ex: { zh: "这位科学家的成就为世人所敬仰。", pinyin: "zhè wèi kēxuéjiā de chéngjiù wéi shìrén suǒ jìngyǎng", ko: "이 과학자의 업적은 세상 사람들에게 존경받아요." },
        },
        {
          zh: "成就",
          pinyin: "chéngjiù",
          ko: "성취, 업적",
          pos: "명사",
          hanja: "성취(成就) — 한자 그대로예요.",
          ex: { zh: "这位科学家的成就为世人所敬仰。", pinyin: "zhè wèi kēxuéjiā de chéngjiù wéi shìrén suǒ jìngyǎng", ko: "이 과학자의 업적은 세상 사람들에게 존경받아요." },
        },
        {
          zh: "敬仰",
          pinyin: "jìngyǎng",
          ko: "존경하다, 우러러보다",
          pos: "동사",
          hanja: "경앙(敬仰) — '공경하여 우러르다'. 존경하는 거예요.",
          ex: { zh: "这位科学家的成就为世人所敬仰。", pinyin: "zhè wèi kēxuéjiā de chéngjiù wéi shìrén suǒ jìngyǎng", ko: "이 과학자의 업적은 세상 사람들에게 존경받아요." },
        },
        {
          zh: "做法",
          pinyin: "zuòfǎ",
          ko: "방식, 방법",
          pos: "명사",
          hanja: "주법(做法) — '하는(做) 방법(法)'. 처리 방식이에요.",
          ex: { zh: "这种做法不为大众所接受。", pinyin: "zhè zhǒng zuòfǎ bù wéi dàzhòng suǒ jiēshòu", ko: "이런 방식은 대중에게 받아들여지지 않아요." },
        },
        {
          zh: "大众",
          pinyin: "dàzhòng",
          ko: "대중",
          pos: "명사",
          hanja: "대중(大衆) — 한자 그대로예요.",
          ex: { zh: "这种做法不为大众所接受。", pinyin: "zhè zhǒng zuòfǎ bù wéi dàzhòng suǒ jiēshòu", ko: "이런 방식은 대중에게 받아들여지지 않아요." },
        },
        {
          zh: "接受",
          pinyin: "jiēshòu",
          ko: "받아들이다, 수용하다",
          pos: "동사",
          hanja: "접수(接受) — '받아들이다'예요. 한국어 '접수'보다 폭이 넓어요.",
          ex: { zh: "这种做法不为大众所接受。", pinyin: "zhè zhǒng zuòfǎ bù wéi dàzhòng suǒ jiēshòu", ko: "이런 방식은 대중에게 받아들여지지 않아요." },
        },
        {
          zh: "内容",
          pinyin: "nèiróng",
          ko: "내용",
          pos: "명사",
          hanja: "내용(內容) — 한자 그대로예요.",
          ex: { zh: "这本书内容丰富，其中第三章最精彩。", pinyin: "zhè běn shū nèiróng fēngfù, qízhōng dì-sān zhāng zuì jīngcǎi", ko: "이 책은 내용이 풍부한데, 그중 3장이 가장 흥미로워요." },
        },
        {
          zh: "精彩",
          pinyin: "jīngcǎi",
          ko: "훌륭하다, 멋지다",
          pos: "형용사",
          hanja: "정채(精彩) — '빛나는 광채'. 빼어나고 흥미진진한 거예요.",
          ex: { zh: "这本书内容丰富，其中第三章最精彩。", pinyin: "zhè běn shū nèiróng fēngfù, qízhōng dì-sān zhāng zuì jīngcǎi", ko: "이 책은 내용이 풍부한데, 그중 3장이 가장 흥미로워요." },
        },
        {
          zh: "篮球",
          pinyin: "lánqiú",
          ko: "농구",
          pos: "명사",
          hanja: "남구(籃球) — '바구니(籃) 공(球)', 곧 농구예요.",
          ex: { zh: "他喜欢运动，尤其是篮球。", pinyin: "tā xǐhuan yùndòng, yóuqí shì lánqiú", ko: "그는 운동을 좋아하는데, 특히 농구를 좋아해요." },
        },
        {
          zh: "放弃",
          pinyin: "fàngqì",
          ko: "포기하다",
          pos: "동사",
          hanja: "방기(放棄) — '놓아 버리다'. 포기하는 거예요.",
          ex: { zh: "他之所以成功，是因为他从不放弃。", pinyin: "tā zhīsuǒyǐ chénggōng, shì yīnwèi tā cóng bù fàngqì", ko: "그가 성공한 까닭은 결코 포기하지 않았기 때문이에요." },
        },
        {
          zh: "道理",
          pinyin: "dàoli",
          ko: "도리, 이치",
          pos: "명사",
          hanja: "도리(道理) — 한자 그대로예요.",
          ex: { zh: "这个道理连小孩子也明白。", pinyin: "zhège dàoli lián xiǎoháizi yě míngbai", ko: "이 이치는 어린아이조차도 알아요." },
        },
        {
          zh: "明白",
          pinyin: "míngbai",
          ko: "알다, 이해하다; 분명하다",
          pos: "동사",
          hanja: "명백(明白) — '밝고 분명하다'에서 '분명히 알다'로 써요.",
          ex: { zh: "这个道理连小孩子也明白。", pinyin: "zhège dàoli lián xiǎoháizi yě míngbai", ko: "이 이치는 어린아이조차도 알아요." },
        },
        {
          zh: "惊讶",
          pinyin: "jīngyà",
          ko: "놀라다, 의아해하다",
          pos: "형용사",
          hanja: "경아(驚訝) — '놀라 의아해하다'예요.",
          ex: { zh: "听到这个消息，我不能不感到惊讶。", pinyin: "tīngdào zhège xiāoxi, wǒ bùnéngbù gǎndào jīngyà", ko: "이 소식을 듣고 놀라지 않을 수 없었어요." },
        },
        {
          zh: "美丽",
          pinyin: "měilì",
          ko: "아름답다",
          pos: "형용사",
          hanja: "미려(美麗) — 한자 그대로예요.",
          ex: { zh: "她有一双美丽的眼睛。", pinyin: "tā yǒu yì shuāng měilì de yǎnjing", ko: "그녀는 아름다운 눈을 가졌어요." },
        },
        {
          zh: "眼睛",
          pinyin: "yǎnjing",
          ko: "눈",
          pos: "명사",
          hanja: "안정(眼睛) — '眼(눈 안)+睛(눈동자 정)'. 눈이에요.",
          ex: { zh: "她有一双美丽的眼睛。", pinyin: "tā yǒu yì shuāng měilì de yǎnjing", ko: "그녀는 아름다운 눈을 가졌어요." },
        },
        {
          zh: "发生",
          pinyin: "fāshēng",
          ko: "발생하다, 일어나다",
          pos: "동사",
          hanja: "발생(發生) — 한자 그대로예요.",
          ex: { zh: "今天发生了一件高兴的事。", pinyin: "jīntiān fāshēng le yí jiàn gāoxìng de shì", ko: "오늘 기쁜 일이 하나 생겼어요." },
        },
        {
          zh: "坚持不懈",
          pinyin: "jiānchí-búxiè",
          ko: "꾸준히 노력하다, 끈기 있게 버티다",
          pos: "성어",
          hanja: "견지불해(堅持不懈) — '굳게 지켜 게을리하지 않다'. 끝까지 밀고 가는 거예요.",
          ex: { zh: "面对困难，我们要坚持不懈。", pinyin: "miànduì kùnnan, wǒmen yào jiānchí-búxiè", ko: "어려움 앞에서 우리는 끈기 있게 버텨야 해요." },
        },
      ],
    },
  ],
};
