/**
 * 5급 어휘 — 추상·논리·전문 영역으로
 * 신문과 토론, 직장 실무를 읽고 말하기 위한 HSK5급 핵심어.
 */
export default {
  level: "H5",
  title: "5급 어휘",
  desc: "추상 개념·경제·심리·논리 연결어까지 — 한자음의 힘이 가장 빛나는 HSK5급 어휘예요.",
  themes: [
    {
      name: "추상 명사",
      words: [
        {
          zh: "概念",
          pinyin: "gàiniàn",
          ko: "개념",
          pos: "명사",
          hanja: "개념(概念) — 한자 그대로예요.",
          ex: { zh: "这个概念有点儿抽象。", pinyin: "zhège gàiniàn yǒudiǎnr chōuxiàng", ko: "이 개념은 조금 추상적이에요." },
        },
        {
          zh: "本质",
          pinyin: "běnzhì",
          ko: "본질",
          pos: "명사",
          hanja: "본질(本質) — 한자 그대로예요.",
          ex: { zh: "我们要看清问题的本质。", pinyin: "wǒmen yào kànqīng wèntí de běnzhì", ko: "우리는 문제의 본질을 똑바로 봐야 해요." },
        },
        {
          zh: "现象",
          pinyin: "xiànxiàng",
          ko: "현상",
          pos: "명사",
          hanja: "현상(現象) — 한자 그대로예요.",
          ex: { zh: "这是一种很常见的社会现象。", pinyin: "zhè shì yì zhǒng hěn chángjiàn de shèhuì xiànxiàng", ko: "이것은 흔한 사회 현상이에요." },
        },
        {
          zh: "因素",
          pinyin: "yīnsù",
          ko: "요인, 요소",
          pos: "명사",
          hanja: "인소(因素) — '因(원인)+素(요소)'. '요인'으로 외워요.",
          ex: { zh: "成功有很多因素。", pinyin: "chénggōng yǒu hěn duō yīnsù", ko: "성공에는 여러 요인이 있어요." },
        },
        {
          zh: "趋势",
          pinyin: "qūshì",
          ko: "추세, 경향",
          pos: "명사",
          hanja: "추세(趨勢) — 한자 그대로예요.",
          ex: { zh: "这是未来发展的趋势。", pinyin: "zhè shì wèilái fāzhǎn de qūshì", ko: "이것은 미래 발전의 추세예요." },
        },
        {
          zh: "规律",
          pinyin: "guīlǜ",
          ko: "규칙, 법칙",
          pos: "명사",
          hanja: "규율(規律) — 한국어 '규율'과 달리 '법칙·규칙성'을 가리켜요.",
          ex: { zh: "生活要有规律。", pinyin: "shēnghuó yào yǒu guīlǜ", ko: "생활은 규칙적이어야 해요." },
        },
        {
          zh: "范围",
          pinyin: "fànwéi",
          ko: "범위",
          pos: "명사",
          hanja: "범위(範圍) — 한자 그대로예요.",
          ex: { zh: "这超出了我的工作范围。", pinyin: "zhè chāochū le wǒ de gōngzuò fànwéi", ko: "이건 제 업무 범위를 벗어났어요." },
        },
        {
          zh: "价值",
          pinyin: "jiàzhí",
          ko: "가치",
          pos: "명사",
          hanja: "가치(價値) — 한자 그대로예요.",
          ex: { zh: "这本书很有价值。", pinyin: "zhè běn shū hěn yǒu jiàzhí", ko: "이 책은 가치가 높아요." },
        },
        {
          zh: "意义",
          pinyin: "yìyì",
          ko: "의의, 의미",
          pos: "명사",
          hanja: "의의(意義) — 한자 그대로예요.",
          ex: { zh: "这件事很有意义。", pinyin: "zhè jiàn shì hěn yǒu yìyì", ko: "이 일은 무척 의미가 있어요." },
        },
        {
          zh: "前途",
          pinyin: "qiántú",
          ko: "장래, 전도",
          pos: "명사",
          hanja: "전도(前途) — '前(앞)+途(길)'. '앞길', 곧 장래예요.",
          ex: { zh: "这个行业很有前途。", pinyin: "zhège hángyè hěn yǒu qiántú", ko: "이 업종은 장래가 밝아요." },
        },
      ],
    },
    {
      name: "심리 동사",
      words: [
        {
          zh: "意识",
          pinyin: "yìshí",
          ko: "의식하다, 깨닫다",
          pos: "동사",
          hanja: "의식(意識) — 한자 그대로지만 '意识到'로 '깨닫다'로 자주 써요.",
          ex: { zh: "他突然意识到自己错了。", pinyin: "tā tūrán yìshídào zìjǐ cuò le", ko: "그는 자기가 틀렸음을 문득 깨달았어요." },
        },
        {
          zh: "体会",
          pinyin: "tǐhuì",
          ko: "체득하다, 실감하다",
          pos: "동사",
          hanja: "체회(體會) — '몸으로 깨닫다'. 직접 느껴 아는 거예요.",
          ex: { zh: "只有经历过才能体会到。", pinyin: "zhǐyǒu jīnglì guo cáinéng tǐhuì dào", ko: "겪어봐야만 비로소 실감할 수 있어요." },
        },
        {
          zh: "佩服",
          pinyin: "pèifú",
          ko: "탄복하다, 존경하다",
          pos: "동사",
          hanja: "패복(佩服) — '차고 따른다'. 마음으로 존경하는 거예요.",
          ex: { zh: "我很佩服他的勇气。", pinyin: "wǒ hěn pèifú tā de yǒngqì", ko: "저는 그의 용기에 탄복해요." },
        },
        {
          zh: "忽视",
          pinyin: "hūshì",
          ko: "소홀히 하다, 무시하다",
          pos: "동사",
          hanja: "홀시(忽視) — '소홀히 보다'. 가볍게 여기는 거예요.",
          ex: { zh: "我们不能忽视这个问题。", pinyin: "wǒmen bù néng hūshì zhège wèntí", ko: "우리는 이 문제를 소홀히 해선 안 돼요." },
        },
        {
          zh: "克服",
          pinyin: "kèfú",
          ko: "극복하다",
          pos: "동사",
          hanja: "극복(克服) — 한자 그대로예요.",
          ex: { zh: "他克服了很多困难。", pinyin: "tā kèfú le hěn duō kùnnan", ko: "그는 많은 어려움을 극복했어요." },
        },
        {
          zh: "适应",
          pinyin: "shìyìng",
          ko: "적응하다",
          pos: "동사",
          hanja: "적응(適應) — 한자 그대로예요.",
          ex: { zh: "她很快适应了新环境。", pinyin: "tā hěn kuài shìyìng le xīn huánjìng", ko: "그녀는 새 환경에 빠르게 적응했어요." },
        },
        {
          zh: "犹豫",
          pinyin: "yóuyù",
          ko: "망설이다, 주저하다",
          pos: "동사",
          hanja: "유예(猶豫) — 한국어 '유예'와 어원은 같지만 뜻은 '머뭇거리다'예요.",
          ex: { zh: "别犹豫了，快做决定吧。", pinyin: "bié yóuyù le, kuài zuò juédìng ba", ko: "망설이지 말고 어서 결정하세요." },
        },
        {
          zh: "盼望",
          pinyin: "pànwàng",
          ko: "간절히 바라다",
          pos: "동사",
          hanja: "반망(盼望) — '盼(바랄 반)+望(바랄 망)'. 손꼽아 기다리는 거예요.",
          ex: { zh: "我们都盼望着春天的到来。", pinyin: "wǒmen dōu pànwàng zhe chūntiān de dàolái", ko: "우리는 모두 봄이 오기를 간절히 바라요." },
        },
        {
          zh: "珍惜",
          pinyin: "zhēnxī",
          ko: "소중히 여기다",
          pos: "동사",
          hanja: "진석(珍惜) — '珍(보배 진)+惜(아낄 석)'. 보배처럼 아끼는 거예요.",
          ex: { zh: "我们要珍惜时间。", pinyin: "wǒmen yào zhēnxī shíjiān", ko: "우리는 시간을 소중히 해야 해요." },
        },
        {
          zh: "感激",
          pinyin: "gǎnjī",
          ko: "감격하다, 깊이 감사하다",
          pos: "동사",
          hanja: "감격(感激) — 한국어 '감격'과 어원은 같으나 '깊이 감사하다'로 많이 써요.",
          ex: { zh: "我非常感激你的帮助。", pinyin: "wǒ fēicháng gǎnjī nǐ de bāngzhù", ko: "당신의 도움에 깊이 감사해요." },
        },
      ],
    },
    {
      name: "경제와 사회",
      words: [
        {
          zh: "投资",
          pinyin: "tóuzī",
          ko: "투자, 투자하다",
          pos: "동사",
          hanja: "투자(投資) — 한자 그대로예요.",
          ex: { zh: "他把钱投资到房地产上。", pinyin: "tā bǎ qián tóuzī dào fángdìchǎn shàng", ko: "그는 돈을 부동산에 투자했어요." },
        },
        {
          zh: "利润",
          pinyin: "lìrùn",
          ko: "이윤",
          pos: "명사",
          hanja: "이윤(利潤) — 한자 그대로예요.",
          ex: { zh: "公司今年的利润增加了。", pinyin: "gōngsī jīnnián de lìrùn zēngjiā le", ko: "회사의 올해 이윤이 늘었어요." },
        },
        {
          zh: "成本",
          pinyin: "chéngběn",
          ko: "원가, 비용",
          pos: "명사",
          hanja: "성본(成本) — '이루는 데 드는 밑천'. '원가'로 외워요.",
          ex: { zh: "我们要降低生产成本。", pinyin: "wǒmen yào jiàngdī shēngchǎn chéngběn", ko: "우리는 생산 원가를 낮춰야 해요." },
        },
        {
          zh: "财产",
          pinyin: "cáichǎn",
          ko: "재산",
          pos: "명사",
          hanja: "재산(財産) — 한자 그대로예요.",
          ex: { zh: "保护个人财产很重要。", pinyin: "bǎohù gèrén cáichǎn hěn zhòngyào", ko: "개인 재산을 보호하는 건 중요해요." },
        },
        {
          zh: "贷款",
          pinyin: "dàikuǎn",
          ko: "대출, 대출하다",
          pos: "동사",
          hanja: "대관(貸款) — '貸(빌릴 대)+款(돈)'. '대출'로 외워요.",
          ex: { zh: "他向银行贷款买房。", pinyin: "tā xiàng yínháng dàikuǎn mǎifáng", ko: "그는 집을 사려고 은행에서 대출받았어요." },
        },
        {
          zh: "效率",
          pinyin: "xiàolǜ",
          ko: "효율",
          pos: "명사",
          hanja: "효율(效率) — 한자 그대로예요.",
          ex: { zh: "这样做可以提高效率。", pinyin: "zhèyàng zuò kěyǐ tígāo xiàolǜ", ko: "이렇게 하면 효율을 높일 수 있어요." },
        },
        {
          zh: "制度",
          pinyin: "zhìdù",
          ko: "제도",
          pos: "명사",
          hanja: "제도(制度) — 한자 그대로예요.",
          ex: { zh: "公司有严格的管理制度。", pinyin: "gōngsī yǒu yángé de guǎnlǐ zhìdù", ko: "회사에는 엄격한 관리 제도가 있어요." },
        },
        {
          zh: "政策",
          pinyin: "zhèngcè",
          ko: "정책",
          pos: "명사",
          hanja: "정책(政策) — 한자 그대로예요.",
          ex: { zh: "政府出台了新政策。", pinyin: "zhèngfǔ chūtái le xīn zhèngcè", ko: "정부가 새 정책을 내놓았어요." },
        },
        {
          zh: "资源",
          pinyin: "zīyuán",
          ko: "자원",
          pos: "명사",
          hanja: "자원(資源) — 한자 그대로예요.",
          ex: { zh: "我们要节约资源。", pinyin: "wǒmen yào jiéyuē zīyuán", ko: "우리는 자원을 절약해야 해요." },
        },
        {
          zh: "规模",
          pinyin: "guīmó",
          ko: "규모",
          pos: "명사",
          hanja: "규모(規模) — 한자 그대로예요.",
          ex: { zh: "这家公司的规模很大。", pinyin: "zhè jiā gōngsī de guīmó hěn dà", ko: "이 회사는 규모가 커요." },
        },
      ],
    },
    {
      name: "고급 형용사",
      words: [
        {
          zh: "抽象",
          pinyin: "chōuxiàng",
          ko: "추상적이다",
          pos: "형용사",
          hanja: "추상(抽象) — 한자 그대로예요.",
          ex: { zh: "他讲的内容太抽象了。", pinyin: "tā jiǎng de nèiróng tài chōuxiàng le", ko: "그가 말한 내용은 너무 추상적이었어요." },
        },
        {
          zh: "具体",
          pinyin: "jùtǐ",
          ko: "구체적이다",
          pos: "형용사",
          hanja: "구체(具體) — 한자 그대로예요.",
          ex: { zh: "请你说得具体一点儿。", pinyin: "qǐng nǐ shuō de jùtǐ yìdiǎnr", ko: "좀 더 구체적으로 말씀해 주세요." },
        },
        {
          zh: "明显",
          pinyin: "míngxiǎn",
          ko: "뚜렷하다, 분명하다",
          pos: "형용사",
          hanja: "명현(明顯) — '밝게 드러나다'. '뚜렷하다'예요.",
          ex: { zh: "他的进步很明显。", pinyin: "tā de jìnbù hěn míngxiǎn", ko: "그의 발전은 뚜렷해요." },
        },
        {
          zh: "严格",
          pinyin: "yángé",
          ko: "엄격하다",
          pos: "형용사",
          hanja: "엄격(嚴格) — 한자 그대로예요.",
          ex: { zh: "这位老师对学生很严格。", pinyin: "zhè wèi lǎoshī duì xuésheng hěn yángé", ko: "이 선생님은 학생에게 엄격해요." },
        },
        {
          zh: "复杂",
          pinyin: "fùzá",
          ko: "복잡하다",
          pos: "형용사",
          hanja: "복잡(複雜) — 한자 그대로예요.",
          ex: { zh: "这个问题很复杂。", pinyin: "zhège wèntí hěn fùzá", ko: "이 문제는 복잡해요." },
        },
        {
          zh: "优秀",
          pinyin: "yōuxiù",
          ko: "우수하다",
          pos: "형용사",
          hanja: "우수(優秀) — 한자 그대로예요.",
          ex: { zh: "她是一名优秀的医生。", pinyin: "tā shì yì míng yōuxiù de yīshēng", ko: "그녀는 우수한 의사예요." },
        },
        {
          zh: "宝贵",
          pinyin: "bǎoguì",
          ko: "귀중하다",
          pos: "형용사",
          hanja: "보귀(寶貴) — '寶(보배)+貴(귀할)'. '귀중하다'예요.",
          ex: { zh: "时间是宝贵的。", pinyin: "shíjiān shì bǎoguì de", ko: "시간은 귀중해요." },
        },
        {
          zh: "巨大",
          pinyin: "jùdà",
          ko: "거대하다, 막대하다",
          pos: "형용사",
          hanja: "거대(巨大) — 한자 그대로예요.",
          ex: { zh: "这件事产生了巨大的影响。", pinyin: "zhè jiàn shì chǎnshēng le jùdà de yǐngxiǎng", ko: "이 일은 막대한 영향을 낳았어요." },
        },
        {
          zh: "成熟",
          pinyin: "chéngshú",
          ko: "성숙하다; 익다",
          pos: "형용사",
          hanja: "성숙(成熟) — 한자 그대로예요.",
          ex: { zh: "他比同龄人成熟得多。", pinyin: "tā bǐ tónglíng rén chéngshú de duō", ko: "그는 또래보다 훨씬 성숙해요." },
        },
        {
          zh: "谨慎",
          pinyin: "jǐnshèn",
          ko: "신중하다",
          pos: "형용사",
          hanja: "근신(謹愼) — 한국어 '근신'과 달리 '신중하다'는 뜻이에요.",
          ex: { zh: "做决定要谨慎。", pinyin: "zuò juédìng yào jǐnshèn", ko: "결정을 내릴 때는 신중해야 해요." },
        },
      ],
    },
    {
      name: "논리와 연결",
      words: [
        {
          zh: "因此",
          pinyin: "yīncǐ",
          ko: "그러므로, 따라서",
          pos: "접속사",
          hanja: "인차(因此) — '이로 인하여'. '따라서'예요.",
          ex: { zh: "他病了，因此没来上课。", pinyin: "tā bìng le, yīncǐ méi lái shàngkè", ko: "그는 아파서, 그래서 수업에 오지 않았어요." },
        },
        {
          zh: "然而",
          pinyin: "rán'ér",
          ko: "그러나, 그렇지만",
          pos: "접속사",
          ex: { zh: "他很努力，然而结果并不理想。", pinyin: "tā hěn nǔlì, rán'ér jiéguǒ bìng bù lǐxiǎng", ko: "그는 열심히 했지만, 결과는 그리 좋지 않았어요." },
        },
        {
          zh: "不仅",
          pinyin: "bùjǐn",
          ko: "~뿐만 아니라",
          pos: "접속사",
          hanja: "불근(不僅) — '~에 그치지 않고'. 뒤에 而且가 자주 와요.",
          ex: { zh: "他不仅聪明，而且很努力。", pinyin: "tā bùjǐn cōngming, érqiě hěn nǔlì", ko: "그는 똑똑할 뿐 아니라 노력도 해요." },
        },
        {
          zh: "从而",
          pinyin: "cóng'ér",
          ko: "그리하여, 그럼으로써",
          pos: "접속사",
          ex: { zh: "他改进了方法，从而提高了效率。", pinyin: "tā gǎijìn le fāngfǎ, cóng'ér tígāo le xiàolǜ", ko: "그는 방법을 개선했고, 그럼으로써 효율을 높였어요." },
        },
        {
          zh: "总之",
          pinyin: "zǒngzhī",
          ko: "요컨대, 한마디로",
          pos: "접속사",
          hanja: "총지(總之) — '통틀어 말하면'. '요컨대'예요.",
          ex: { zh: "总之，这是一个好机会。", pinyin: "zǒngzhī, zhè shì yí ge hǎo jīhuì", ko: "요컨대, 이건 좋은 기회예요." },
        },
        {
          zh: "何况",
          pinyin: "hékuàng",
          ko: "하물며, 더구나",
          pos: "접속사",
          ex: { zh: "大人都做不到，何况孩子。", pinyin: "dàrén dōu zuòbudào, hékuàng háizi", ko: "어른도 못 하는데, 하물며 아이는요." },
        },
        {
          zh: "宁可",
          pinyin: "nìngkě",
          ko: "차라리 ~할지언정",
          pos: "부사",
          hanja: "영가(寧可) — '차라리 ~함이 낫다'. 뒤에 也不가 자주 와요.",
          ex: { zh: "我宁可走路，也不坐他的车。", pinyin: "wǒ nìngkě zǒulù, yě bù zuò tā de chē", ko: "저는 차라리 걸을지언정 그의 차는 안 타요." },
        },
        {
          zh: "毕竟",
          pinyin: "bìjìng",
          ko: "결국, 어쨌든",
          pos: "부사",
          hanja: "필경(畢竟) — 한국어 '필경'과 같아요. '어쨌든'이에요.",
          ex: { zh: "他毕竟还是个孩子。", pinyin: "tā bìjìng háishi ge háizi", ko: "그는 어쨌든 아직 아이예요." },
        },
        {
          zh: "难免",
          pinyin: "nánmiǎn",
          ko: "면하기 어렵다, 으레 ~하기 마련",
          pos: "부사",
          hanja: "난면(難免) — '면하기 어렵다'. 피할 수 없다는 뜻이에요.",
          ex: { zh: "第一次难免会紧张。", pinyin: "dì-yī cì nánmiǎn huì jǐnzhāng", ko: "처음에는 으레 긴장하기 마련이에요." },
        },
        {
          zh: "的确",
          pinyin: "díquè",
          ko: "확실히, 정말로",
          pos: "부사",
          hanja: "적확(的確) — 한국어 '적확'과 어원이 같아요. '확실히'예요.",
          ex: { zh: "这件事的确很难办。", pinyin: "zhè jiàn shì díquè hěn nán bàn", ko: "이 일은 확실히 처리하기 어려워요." },
        },
      ],
    },
  ],
};
