/**
 * H5 (HSK 5급) 보강 어휘 — 표준 HSK5 단어 목록 중 본편(h5.js)에 없던 어휘를 보충 (청크 D).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되, 성씨·이체자·다음자 오독은 표준 병음으로 교정했어요.
 */
const themes = {
  themes: [
    {
      name: "HSK5 보강 — 동사",
      icon: "🔴",
      words: [
        { zh: "冒险", pinyin: "màoxiǎn", ko: "모험하다, 위험을 무릅쓰다", pos: "동사", hanja: "모험(冒險) — '冒'는 무릅쓸 모, '險'은 험할 험.", ex: { zh: "他喜欢冒险。", pinyin: "tā xǐhuan màoxiǎn", ko: "그는 모험을 좋아해요." } },
        { zh: "迷路", pinyin: "mílù", ko: "길을 잃다", pos: "동사", hanja: "미로(迷路) — 한자는 '미로'지만 '길을 잃다'를 뜻해요. 가짜동족어 주의!", ex: { zh: "我在山里迷路了。", pinyin: "wǒ zài shān lǐ mílù le", ko: "저는 산속에서 길을 잃었어요." } },
        { zh: "面临", pinyin: "miànlín", ko: "(문제·상황에) 직면하다", pos: "동사", hanja: "면림(面臨) — '面'은 낯 면, '臨'은 임할 림.", ex: { zh: "我们面临很多困难。", pinyin: "wǒmen miànlín hěn duō kùnnan", ko: "우리는 많은 어려움에 직면했어요." } },
        { zh: "描写", pinyin: "miáoxiě", ko: "묘사하다, 그려내다", pos: "동사", hanja: "묘사(描寫) — '描'는 그릴 묘, '寫'는 베낄 사.", ex: { zh: "这本书描写了战争。", pinyin: "zhè běn shū miáoxiě le zhànzhēng", ko: "이 책은 전쟁을 묘사했어요." } },
        { zh: "命令", pinyin: "mìnglìng", ko: "명령하다; 명령", pos: "동사", hanja: "명령(命令) — 한자 그대로.", ex: { zh: "他命令士兵前进。", pinyin: "tā mìnglìng shìbīng qiánjìn", ko: "그는 병사들에게 전진하라고 명령했어요." } },
        { zh: "摸", pinyin: "mō", ko: "(손으로) 만지다, 더듬다", pos: "동사", ex: { zh: "别摸那只狗。", pinyin: "bié mō nà zhī gǒu", ko: "그 개를 만지지 마세요." } },
        { zh: "模仿", pinyin: "mófǎng", ko: "모방하다, 흉내 내다", pos: "동사", hanja: "모방(模倣) — '模'는 본뜰 모, '倣'은 본뜰 방.", ex: { zh: "孩子喜欢模仿大人。", pinyin: "háizi xǐhuan mófǎng dàrén", ko: "아이는 어른을 흉내 내기 좋아해요." } },
        { zh: "念", pinyin: "niàn", ko: "(소리 내어) 읽다; 그리워하다", pos: "동사", hanja: "념(念) — '생각할 념'. '그리워하다·읽다'.", ex: { zh: "请你念一下这句话。", pinyin: "qǐng nǐ niàn yíxià zhè jù huà", ko: "이 문장을 한번 읽어 주세요." } },
        { zh: "拍", pinyin: "pāi", ko: "(손으로) 치다, (사진을) 찍다", pos: "동사", ex: { zh: "我们一起拍张照吧。", pinyin: "wǒmen yìqǐ pāi zhāng zhào ba", ko: "우리 같이 사진 한 장 찍어요." } },
        { zh: "排队", pinyin: "páiduì", ko: "줄을 서다", pos: "동사", hanja: "배대(排隊) — '排'는 늘어설 배, '隊'는 무리 대.", ex: { zh: "请大家排队上车。", pinyin: "qǐng dàjiā páiduì shàng chē", ko: "모두 줄 서서 차에 타세요." } },
        { zh: "派", pinyin: "pài", ko: "파견하다, 보내다; 파, 유파", pos: "동사", hanja: "파(派) — '갈래 파'. '파견(派遣)'의 파.", ex: { zh: "公司派他去上海。", pinyin: "gōngsī pài tā qù Shànghǎi", ko: "회사가 그를 상하이로 파견했어요." } },
        { zh: "培养", pinyin: "péiyǎng", ko: "양성하다, 키우다", pos: "동사", hanja: "배양(培養) — '培'는 북돋울 배, '養'은 기를 양.", ex: { zh: "学校培养了很多人才。", pinyin: "xuéxiào péiyǎng le hěn duō réncái", ko: "학교는 많은 인재를 길러냈어요." } },
        { zh: "赔偿", pinyin: "péicháng", ko: "배상하다, 변상하다", pos: "동사", hanja: "배상(賠償) — '賠'는 물어줄 배, '償'은 갚을 상.", ex: { zh: "他必须赔偿损失。", pinyin: "tā bìxū péicháng sǔnshī", ko: "그는 손해를 배상해야 해요." } },
        { zh: "配合", pinyin: "pèihé", ko: "협력하다, 손발을 맞추다", pos: "동사", hanja: "배합(配合) — '配'는 짝 배, '合'은 합할 합.", ex: { zh: "谢谢你的配合。", pinyin: "xièxie nǐ de pèihé", ko: "협조해 주셔서 감사해요." } },
        { zh: "碰见", pinyin: "pèngjiàn", ko: "우연히 마주치다", pos: "동사", hanja: "팽견(碰見) — '碰'은 부딪칠 팽, '見'은 볼 견.", ex: { zh: "我在路上碰见了老同学。", pinyin: "wǒ zài lùshang pèngjiàn le lǎo tóngxué", ko: "저는 길에서 옛 동창을 우연히 만났어요." } },
        { zh: "披", pinyin: "pī", ko: "(어깨에) 걸치다, 두르다", pos: "동사", ex: { zh: "她披着一件外套。", pinyin: "tā pī zhe yí jiàn wàitào", ko: "그녀는 외투를 걸치고 있어요." } },
        { zh: "飘", pinyin: "piāo", ko: "(바람에) 흩날리다, 펄럭이다", pos: "동사", hanja: "표(飄) — '나부낄 표'.", ex: { zh: "雪花在空中飘。", pinyin: "xuěhuā zài kōngzhōng piāo", ko: "눈송이가 공중에서 흩날려요." } },
        { zh: "评价", pinyin: "píngjià", ko: "평가하다; 평가", pos: "동사", hanja: "평가(評價) — '評'은 평할 평, '價'는 값 가.", ex: { zh: "大家对他评价很高。", pinyin: "dàjiā duì tā píngjià hěn gāo", ko: "모두 그를 높이 평가해요." } },
        { zh: "凭", pinyin: "píng", ko: "~에 근거하다, ~에 기대다", pos: "개사", hanja: "빙(憑) — '기댈 빙'.", ex: { zh: "凭这张票就能进去。", pinyin: "píng zhè zhāng piào jiù néng jìnqù", ko: "이 표만 있으면 들어갈 수 있어요." } },
        { zh: "破产", pinyin: "pòchǎn", ko: "파산하다", pos: "동사", hanja: "파산(破産) — '破'는 깨질 파, '産'은 낳을 산.", ex: { zh: "那家公司破产了。", pinyin: "nà jiā gōngsī pòchǎn le", ko: "그 회사는 파산했어요." } },
        { zh: "破坏", pinyin: "pòhuài", ko: "파괴하다, 훼손하다", pos: "동사", hanja: "파괴(破壞) — '破'는 깨질 파, '壞'는 무너질 괴.", ex: { zh: "我们不能破坏环境。", pinyin: "wǒmen bù néng pòhuài huánjìng", ko: "우리는 환경을 파괴하면 안 돼요." } },
        { zh: "期待", pinyin: "qīdài", ko: "기대하다, 고대하다", pos: "동사", hanja: "기대(期待) — '期'는 기약할 기, '待'는 기다릴 대.", ex: { zh: "我很期待这次旅行。", pinyin: "wǒ hěn qīdài zhè cì lǚxíng", ko: "저는 이번 여행을 무척 기대해요." } },
        { zh: "企图", pinyin: "qǐtú", ko: "기도하다, 꾀하다 (부정적); 시도", pos: "동사", hanja: "기도(企圖) — '企'는 꾀할 기, '圖'는 그림 도. 주로 나쁜 의도에 써요.", ex: { zh: "他企图逃跑。", pinyin: "tā qǐtú táopǎo", ko: "그는 도망치려고 했어요." } },
        { zh: "启发", pinyin: "qǐfā", ko: "일깨우다, 깨우치다; 깨달음", pos: "동사", hanja: "계발(啓發) — '啓'는 열 계, '發'은 필 발.", ex: { zh: "老师的话给了我很大启发。", pinyin: "lǎoshī de huà gěi le wǒ hěn dà qǐfā", ko: "선생님의 말씀이 제게 큰 깨우침을 줬어요." } },
        { zh: "牵", pinyin: "qiān", ko: "(끈을) 끌다, 손을 잡다; 연루되다", pos: "동사", hanja: "견(牽) — '이끌 견'.", ex: { zh: "妈妈牵着孩子的手。", pinyin: "māma qiān zhe háizi de shǒu", ko: "엄마가 아이의 손을 잡고 있어요." } },
        { zh: "签字", pinyin: "qiānzì", ko: "서명하다, 사인하다", pos: "동사", hanja: "첨자(簽字) — '簽'은 서명할 첨, '字'는 글자 자.", ex: { zh: "请在这里签字。", pinyin: "qǐng zài zhèlǐ qiānzì", ko: "여기에 서명해 주세요." } },
        { zh: "欠", pinyin: "qiàn", ko: "(빚을) 지다, 빚지다; 모자라다", pos: "동사", hanja: "흠(欠) — '하품 흠, 모자랄 흠'.", ex: { zh: "我还欠你一百块。", pinyin: "wǒ hái qiàn nǐ yìbǎi kuài", ko: "저는 아직 당신에게 백 위안을 빚졌어요." } },
        { zh: "强调", pinyin: "qiángdiào", ko: "강조하다", pos: "동사", hanja: "강조(強調) — '強'은 강할 강, '調'는 고를 조.", ex: { zh: "老师强调了这个问题。", pinyin: "lǎoshī qiángdiào le zhège wèntí", ko: "선생님은 이 문제를 강조했어요." } },
        { zh: "抢", pinyin: "qiǎng", ko: "빼앗다, 강탈하다; 앞다투다", pos: "동사", hanja: "창(搶) — '빼앗을 창'. 입력 병음(qiāng)은 오독, 표준은 qiǎng이에요.", ex: { zh: "有人抢了她的包。", pinyin: "yǒu rén qiǎng le tā de bāo", ko: "누군가 그녀의 가방을 빼앗았어요." } },
        { zh: "瞧", pinyin: "qiáo", ko: "보다, 쳐다보다 (구어)", pos: "동사", hanja: "초(瞧) — '볼 초'. 看의 구어 표현이에요.", ex: { zh: "你瞧，那是什么？", pinyin: "nǐ qiáo, nà shì shénme", ko: "봐요, 저게 뭐예요?" } },
        { zh: "切", pinyin: "qiē", ko: "(칼로) 자르다, 썰다", pos: "동사", hanja: "절(切) — '끊을 절'.", ex: { zh: "请把苹果切成块。", pinyin: "qǐng bǎ píngguǒ qiē chéng kuài", ko: "사과를 조각으로 잘라 주세요." } },
        { zh: "侵略", pinyin: "qīnlüè", ko: "침략하다; 침략", pos: "동사", hanja: "침략(侵略) — '侵'은 침노할 침, '略'은 다스릴 략.", ex: { zh: "侵略战争是不义的。", pinyin: "qīnlüè zhànzhēng shì búyì de", ko: "침략 전쟁은 정의롭지 못해요." } },
        { zh: "轻视", pinyin: "qīngshì", ko: "경시하다, 깔보다", pos: "동사", hanja: "경시(輕視) — '輕'은 가벼울 경, '視'는 볼 시.", ex: { zh: "不要轻视任何对手。", pinyin: "búyào qīngshì rènhé duìshǒu", ko: "어떤 상대도 깔보지 마세요." } },
        { zh: "请求", pinyin: "qǐngqiú", ko: "요청하다, 부탁하다; 요청", pos: "동사", hanja: "청구(請求) — '請'은 청할 청, '求'는 구할 구.", ex: { zh: "他请求我帮忙。", pinyin: "tā qǐngqiú wǒ bāngmáng", ko: "그는 제게 도움을 청했어요." } },
        { zh: "庆祝", pinyin: "qìngzhù", ko: "경축하다, 축하하다", pos: "동사", hanja: "경축(慶祝) — '慶'은 경사 경, '祝'은 빌 축.", ex: { zh: "我们一起庆祝节日。", pinyin: "wǒmen yìqǐ qìngzhù jiérì", ko: "우리 함께 명절을 축하해요." } },
        { zh: "娶", pinyin: "qǔ", ko: "(아내를) 맞이하다, 장가들다", pos: "동사", hanja: "취(娶) — '장가들 취'. (남자가) 아내를 맞이하는 것이에요.", ex: { zh: "他去年娶了妻子。", pinyin: "tā qùnián qǔ le qīzi", ko: "그는 작년에 아내를 맞이했어요." } },
        { zh: "去世", pinyin: "qùshì", ko: "세상을 떠나다, 별세하다", pos: "동사", hanja: "거세(去世) — '去'는 갈 거, '世'는 세상 세.", ex: { zh: "他的爷爷去年去世了。", pinyin: "tā de yéye qùnián qùshì le", ko: "그의 할아버지는 작년에 돌아가셨어요." } },
        { zh: "劝", pinyin: "quàn", ko: "권하다, 타이르다, 설득하다", pos: "동사", hanja: "권(勸) — '권할 권'.", ex: { zh: "我劝他别喝酒。", pinyin: "wǒ quàn tā bié hē jiǔ", ko: "저는 그에게 술을 마시지 말라고 권했어요." } },
        { zh: "缺乏", pinyin: "quēfá", ko: "결핍되다, 부족하다", pos: "동사", hanja: "결핍(缺乏) — '缺'은 모자랄 결, '乏'은 모자랄 핍.", ex: { zh: "他缺乏经验。", pinyin: "tā quēfá jīngyàn", ko: "그는 경험이 부족해요." } },
        { zh: "确定", pinyin: "quèdìng", ko: "확정하다; 확실하다, 분명하다", pos: "동사", hanja: "확정(確定) — '確'은 굳을 확, '定'은 정할 정.", ex: { zh: "时间还没确定。", pinyin: "shíjiān hái méi quèdìng", ko: "시간은 아직 정해지지 않았어요." } },
        { zh: "燃烧", pinyin: "ránshāo", ko: "연소하다, 타다", pos: "동사", hanja: "연소(燃燒) — '燃'은 탈 연, '燒'는 사를 소.", ex: { zh: "木头在火里燃烧。", pinyin: "mùtou zài huǒ lǐ ránshāo", ko: "나무가 불 속에서 타고 있어요." } },
        { zh: "嚷", pinyin: "rǎng", ko: "고함치다, 떠들어대다", pos: "동사", ex: { zh: "别在这儿大声嚷。", pinyin: "bié zài zhèr dàshēng rǎng", ko: "여기서 큰 소리로 떠들지 마세요." } },
        { zh: "绕", pinyin: "rào", ko: "감다, 둘러싸다; 돌아가다", pos: "동사", ex: { zh: "我们绕了一圈才到。", pinyin: "wǒmen rào le yì quān cái dào", ko: "우리는 한 바퀴 빙 돌아서야 도착했어요." } },
        { zh: "热爱", pinyin: "rèài", ko: "열렬히 사랑하다, 애착을 갖다", pos: "동사", hanja: "열애(熱愛) — 한자는 '열애'지만 '간절히 사랑하다(일·조국 등)'를 뜻해요.", ex: { zh: "他热爱自己的工作。", pinyin: "tā rè'ài zìjǐ de gōngzuò", ko: "그는 자기 일을 무척 사랑해요." } },
        { zh: "忍不住", pinyin: "rěnbuzhù", ko: "참지 못하다, 견디지 못하다", pos: "동사", hanja: "인부주(忍不住) — '忍'은 참을 인. '참아 낼 수 없다'.", ex: { zh: "她忍不住笑了。", pinyin: "tā rěnbuzhù xiào le", ko: "그녀는 참지 못하고 웃었어요." } },
        { zh: "融化", pinyin: "rónghuà", ko: "녹다, 용해되다", pos: "동사", hanja: "융화(融化) — '融'은 녹을 융, '化'는 될 화.", ex: { zh: "春天到了，雪开始融化。", pinyin: "chūntiān dào le, xuě kāishǐ rónghuà", ko: "봄이 와서 눈이 녹기 시작해요." } },
        { zh: "洒", pinyin: "sǎ", ko: "뿌리다, 흩뿌리다; 엎지르다", pos: "동사", ex: { zh: "他不小心把水洒了。", pinyin: "tā bù xiǎoxīn bǎ shuǐ sǎ le", ko: "그는 실수로 물을 엎질렀어요." } },
        { zh: "杀", pinyin: "shā", ko: "죽이다, 살해하다", pos: "동사", hanja: "살(殺) — '죽일 살'.", ex: { zh: "他杀了一只鸡。", pinyin: "tā shā le yì zhī jī", ko: "그는 닭 한 마리를 잡았어요." } },
        { zh: "晒", pinyin: "shài", ko: "햇볕에 말리다, 햇볕을 쬐다", pos: "동사", hanja: "쇄(曬) — '쬘 쇄'.", ex: { zh: "妈妈在阳台上晒衣服。", pinyin: "māma zài yángtái shang shài yīfu", ko: "엄마가 베란다에서 빨래를 말려요." } },
        { zh: "删除", pinyin: "shānchú", ko: "삭제하다, 지우다", pos: "동사", hanja: "산제(刪除) — '刪'은 깎을 산, '除'는 덜 제.", ex: { zh: "请删除这个文件。", pinyin: "qǐng shānchú zhège wénjiàn", ko: "이 파일을 삭제해 주세요." } },
        { zh: "上当", pinyin: "shàngdàng", ko: "속다, 사기당하다", pos: "동사", hanja: "상당(上當) — '上'은 위 상, '當'은 마땅 당. '함정에 빠지다'.", ex: { zh: "小心别上当。", pinyin: "xiǎoxīn bié shàngdàng", ko: "속지 않게 조심하세요." } },
        { zh: "舍不得", pinyin: "shěbude", ko: "(아까워서) ~하기 아쉽다, 차마 ~못하다", pos: "동사", hanja: "사부득(捨不得) — '捨'는 버릴 사. '버리기 아깝다'.", ex: { zh: "我舍不得离开这里。", pinyin: "wǒ shěbude líkāi zhèlǐ", ko: "저는 이곳을 떠나기가 아쉬워요." } },
        { zh: "设计", pinyin: "shèjì", ko: "설계하다, 디자인하다; 설계", pos: "동사", hanja: "설계(設計) — '設'은 베풀 설, '計'는 셀 계.", ex: { zh: "他设计了这座大楼。", pinyin: "tā shèjì le zhè zuò dàlóu", ko: "그가 이 건물을 설계했어요." } },
        { zh: "射击", pinyin: "shèjī", ko: "사격하다, 쏘다; 사격", pos: "동사", hanja: "사격(射擊) — '射'는 쏠 사, '擊'은 칠 격.", ex: { zh: "他练习射击。", pinyin: "tā liànxí shèjī", ko: "그는 사격을 연습해요." } },
        { zh: "摄影", pinyin: "shèyǐng", ko: "촬영하다, 사진을 찍다; 촬영", pos: "동사", hanja: "섭영(攝影) — '攝'은 당길 섭, '影'은 그림자 영.", ex: { zh: "他喜欢摄影。", pinyin: "tā xǐhuan shèyǐng", ko: "그는 사진 찍기를 좋아해요." } },
        { zh: "伸", pinyin: "shēn", ko: "(손·몸을) 뻗다, 펴다", pos: "동사", hanja: "신(伸) — '펼 신'.", ex: { zh: "他伸手拿杯子。", pinyin: "tā shēn shǒu ná bēizi", ko: "그는 손을 뻗어 컵을 잡았어요." } },
        { zh: "生产", pinyin: "shēngchǎn", ko: "생산하다; 출산하다", pos: "동사", hanja: "생산(生産) — '生'은 날 생, '産'은 낳을 산.", ex: { zh: "这家工厂生产汽车。", pinyin: "zhè jiā gōngchǎng shēngchǎn qìchē", ko: "이 공장은 자동차를 생산해요." } },
        { zh: "省略", pinyin: "shěnglüè", ko: "생략하다", pos: "동사", hanja: "생략(省略) — '省'은 덜 생, '略'은 줄일 략.", ex: { zh: "这部分可以省略。", pinyin: "zhè bùfen kěyǐ shěnglüè", ko: "이 부분은 생략해도 돼요." } },
        { zh: "胜利", pinyin: "shènglì", ko: "승리하다; 승리", pos: "동사", hanja: "승리(勝利) — '勝'은 이길 승, '利'는 이로울 리.", ex: { zh: "我们队取得了胜利。", pinyin: "wǒmen duì qǔdé le shènglì", ko: "우리 팀이 승리를 거뒀어요." } },
        { zh: "失眠", pinyin: "shīmián", ko: "불면증에 걸리다, 잠을 못 자다", pos: "동사", hanja: "실면(失眠) — '失'은 잃을 실, '眠'은 잠잘 면.", ex: { zh: "我昨晚失眠了。", pinyin: "wǒ zuówǎn shīmián le", ko: "저는 어젯밤 잠을 못 잤어요." } },
        { zh: "失去", pinyin: "shīqù", ko: "잃다, 상실하다", pos: "동사", hanja: "실거(失去) — '失'은 잃을 실, '去'는 갈 거.", ex: { zh: "他失去了工作。", pinyin: "tā shīqù le gōngzuò", ko: "그는 일자리를 잃었어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 명사·추상",
      icon: "🔴",
      words: [
        { zh: "矛盾", pinyin: "máodùn", ko: "모순; 갈등, 대립", pos: "명사", hanja: "모순(矛盾) — '矛'는 창 모, '盾'은 방패 순. 창과 방패의 고사.", ex: { zh: "他们之间有矛盾。", pinyin: "tāmen zhījiān yǒu máodùn", ko: "그들 사이에는 갈등이 있어요." } },
        { zh: "贸易", pinyin: "màoyì", ko: "무역, 교역", pos: "명사", hanja: "무역(貿易) — '貿'는 바꿀 무, '易'는 바꿀 역.", ex: { zh: "两国的贸易往来很多。", pinyin: "liǎng guó de màoyì wǎnglái hěn duō", ko: "두 나라의 무역 거래가 활발해요." } },
        { zh: "眉毛", pinyin: "méimao", ko: "눈썹", pos: "명사", hanja: "미모(眉毛) — '眉'는 눈썹 미, '毛'는 털 모.", ex: { zh: "她的眉毛很细。", pinyin: "tā de méimao hěn xì", ko: "그녀의 눈썹은 가늘어요." } },
        { zh: "煤炭", pinyin: "méitàn", ko: "석탄", pos: "명사", hanja: "매탄(煤炭) — '煤'는 그을음 매(석탄), '炭'은 숯 탄.", ex: { zh: "这里出产煤炭。", pinyin: "zhèlǐ chūchǎn méitàn", ko: "이곳에서는 석탄이 나요." } },
        { zh: "美术", pinyin: "měishù", ko: "미술", pos: "명사", hanja: "미술(美術) — '美'는 아름다울 미, '術'은 재주 술.", ex: { zh: "他在学美术。", pinyin: "tā zài xué měishù", ko: "그는 미술을 배우고 있어요." } },
        { zh: "魅力", pinyin: "mèilì", ko: "매력", pos: "명사", hanja: "매력(魅力) — '魅'는 도깨비 매, '力'은 힘 력.", ex: { zh: "这座城市很有魅力。", pinyin: "zhè zuò chéngshì hěn yǒu mèilì", ko: "이 도시는 매력이 넘쳐요." } },
        { zh: "谜语", pinyin: "míyǔ", ko: "수수께끼", pos: "명사", hanja: "미어(謎語) — '謎'는 수수께끼 미, '語'는 말씀 어.", ex: { zh: "我来猜这个谜语。", pinyin: "wǒ lái cāi zhège míyǔ", ko: "제가 이 수수께끼를 맞혀 볼게요." } },
        { zh: "秘密", pinyin: "mìmì", ko: "비밀", pos: "명사", hanja: "비밀(秘密) — '秘'는 숨길 비, '密'은 빽빽할 밀.", ex: { zh: "这是我们之间的秘密。", pinyin: "zhè shì wǒmen zhījiān de mìmì", ko: "이건 우리만의 비밀이에요." } },
        { zh: "秘书", pinyin: "mìshū", ko: "비서", pos: "명사", hanja: "비서(秘書) — '秘'는 숨길 비, '書'는 글 서.", ex: { zh: "她是经理的秘书。", pinyin: "tā shì jīnglǐ de mìshū", ko: "그녀는 사장의 비서예요." } },
        { zh: "蜜蜂", pinyin: "mìfēng", ko: "꿀벌", pos: "명사", hanja: "밀봉(蜜蜂) — '蜜'은 꿀 밀, '蜂'은 벌 봉.", ex: { zh: "花上有很多蜜蜂。", pinyin: "huā shang yǒu hěn duō mìfēng", ko: "꽃에 꿀벌이 많이 있어요." } },
        { zh: "棉花", pinyin: "miánhua", ko: "목화, 솜", pos: "명사", hanja: "면화(棉花) — '棉'은 솜 면, '花'는 꽃 화.", ex: { zh: "这件衣服是棉花做的。", pinyin: "zhè jiàn yīfu shì miánhua zuò de", ko: "이 옷은 목화로 만든 거예요." } },
        { zh: "面积", pinyin: "miànjī", ko: "면적, 넓이", pos: "명사", hanja: "면적(面積) — '面'은 낯 면, '積'은 쌓을 적.", ex: { zh: "这个房间面积很大。", pinyin: "zhège fángjiān miànjī hěn dà", ko: "이 방은 면적이 넓어요." } },
        { zh: "民主", pinyin: "mínzhǔ", ko: "민주, 민주주의", pos: "명사", hanja: "민주(民主) — '民'은 백성 민, '主'는 주인 주.", ex: { zh: "我们追求民主和自由。", pinyin: "wǒmen zhuīqiú mínzhǔ hé zìyóu", ko: "우리는 민주와 자유를 추구해요." } },
        { zh: "名牌", pinyin: "míngpái", ko: "명품, 유명 브랜드; 명패", pos: "명사", hanja: "명패(名牌) — '名'은 이름 명, '牌'는 패 패.", ex: { zh: "她喜欢买名牌。", pinyin: "tā xǐhuan mǎi míngpái", ko: "그녀는 명품 사는 걸 좋아해요." } },
        { zh: "名片", pinyin: "míngpiàn", ko: "명함", pos: "명사", hanja: "명편(名片) — '名'은 이름 명, '片'은 조각 편.", ex: { zh: "这是我的名片。", pinyin: "zhè shì wǒ de míngpiàn", ko: "이건 제 명함이에요." } },
        { zh: "名胜", pinyin: "míngshèng", ko: "명승지, 명소", pos: "명사", hanja: "명승(名勝) — '名'은 이름 명, '勝'은 경치 좋을 승.", ex: { zh: "这里有很多名胜古迹。", pinyin: "zhèlǐ yǒu hěn duō míngshèng gǔjì", ko: "이곳에는 명승고적이 많아요." } },
        { zh: "明信片", pinyin: "míngxìnpiàn", ko: "엽서", pos: "명사", hanja: "명신편(明信片) — '明'은 밝을 명, '信'은 편지 신, '片'은 조각 편.", ex: { zh: "我给你寄一张明信片。", pinyin: "wǒ gěi nǐ jì yì zhāng míngxìnpiàn", ko: "제가 엽서 한 장 보내 드릴게요." } },
        { zh: "明星", pinyin: "míngxīng", ko: "스타, 인기 연예인", pos: "명사", hanja: "명성(明星) — '明'은 밝을 명, '星'은 별 성.", ex: { zh: "他是个电影明星。", pinyin: "tā shì ge diànyǐng míngxīng", ko: "그는 영화 스타예요." } },
        { zh: "命运", pinyin: "mìngyùn", ko: "운명", pos: "명사", hanja: "명운(命運) — '命'은 목숨 명, '運'은 옮길 운.", ex: { zh: "他相信命运。", pinyin: "tā xiāngxìn mìngyùn", ko: "그는 운명을 믿어요." } },
        { zh: "摩托车", pinyin: "mótuōchē", ko: "오토바이", pos: "명사", hanja: "마탁차(摩托車) — '摩托'는 motor의 음역, '車'는 수레 차.", ex: { zh: "他骑摩托车上班。", pinyin: "tā qí mótuōchē shàngbān", ko: "그는 오토바이를 타고 출근해요." } },
        { zh: "木头", pinyin: "mùtou", ko: "나무, 목재", pos: "명사", hanja: "목두(木頭) — '木'은 나무 목, '頭'는 머리 두.", ex: { zh: "这张桌子是木头做的。", pinyin: "zhè zhāng zhuōzi shì mùtou zuò de", ko: "이 책상은 나무로 만든 거예요." } },
        { zh: "目标", pinyin: "mùbiāo", ko: "목표, 타깃", pos: "명사", hanja: "목표(目標) — '目'은 눈 목, '標'는 표할 표.", ex: { zh: "我的目标是考上大学。", pinyin: "wǒ de mùbiāo shì kǎoshàng dàxué", ko: "제 목표는 대학에 합격하는 거예요." } },
        { zh: "目录", pinyin: "mùlù", ko: "목록, 목차, 카탈로그", pos: "명사", hanja: "목록(目錄) — '目'은 눈 목, '錄'은 기록할 록.", ex: { zh: "请看书的目录。", pinyin: "qǐng kàn shū de mùlù", ko: "책의 목차를 봐 주세요." } },
        { zh: "内科", pinyin: "nèikē", ko: "내과", pos: "명사", hanja: "내과(內科) — '內'는 안 내, '科'는 과목 과.", ex: { zh: "他在医院的内科工作。", pinyin: "tā zài yīyuàn de nèikē gōngzuò", ko: "그는 병원 내과에서 일해요." } },
        { zh: "能源", pinyin: "néngyuán", ko: "에너지, 에너지원", pos: "명사", hanja: "능원(能源) — '能'은 능할 능, '源'은 근원 원.", ex: { zh: "我们要节约能源。", pinyin: "wǒmen yào jiéyuē néngyuán", ko: "우리는 에너지를 절약해야 해요." } },
        { zh: "年代", pinyin: "niándài", ko: "연대, 시대; (몇십) 년대", pos: "명사", hanja: "연대(年代) — '年'은 해 년, '代'는 대신할 대.", ex: { zh: "这是八十年代的歌。", pinyin: "zhè shì bāshí niándài de gē", ko: "이건 80년대 노래예요." } },
        { zh: "年纪", pinyin: "niánjì", ko: "나이, 연세", pos: "명사", hanja: "연기(年紀) — '年'은 해 년, '紀'는 벼리 기.", ex: { zh: "您年纪多大了？", pinyin: "nín niánjì duō dà le", ko: "연세가 어떻게 되세요?" } },
        { zh: "牛仔裤", pinyin: "niúzǎikù", ko: "청바지", pos: "명사", hanja: "우자고(牛仔褲) — '牛仔'는 카우보이, '褲'는 바지 고.", ex: { zh: "他喜欢穿牛仔裤。", pinyin: "tā xǐhuan chuān niúzǎikù", ko: "그는 청바지 입는 걸 좋아해요." } },
        { zh: "农民", pinyin: "nóngmín", ko: "농민, 농부", pos: "명사", hanja: "농민(農民) — '農'은 농사 농, '民'은 백성 민.", ex: { zh: "农民在田里工作。", pinyin: "nóngmín zài tián lǐ gōngzuò", ko: "농민들이 밭에서 일해요." } },
        { zh: "农业", pinyin: "nóngyè", ko: "농업", pos: "명사", hanja: "농업(農業) — '農'은 농사 농, '業'은 업 업.", ex: { zh: "这个国家农业很发达。", pinyin: "zhège guójiā nóngyè hěn fādá", ko: "이 나라는 농업이 발달했어요." } },
        { zh: "女士", pinyin: "nǚshì", ko: "여사, 숙녀 (여성 존칭)", pos: "명사", hanja: "여사(女士) — '女'는 여자 여, '士'는 선비 사.", ex: { zh: "女士们，先生们，晚上好！", pinyin: "nǚshìmen, xiānshengmen, wǎnshang hǎo", ko: "신사 숙녀 여러분, 안녕하세요!" } },
        { zh: "皮鞋", pinyin: "píxié", ko: "가죽 구두", pos: "명사", hanja: "피혜(皮鞋) — '皮'는 가죽 피, '鞋'는 신 혜.", ex: { zh: "他穿了一双皮鞋。", pinyin: "tā chuān le yì shuāng píxié", ko: "그는 가죽 구두를 신었어요." } },
        { zh: "频道", pinyin: "píndào", ko: "(TV·라디오) 채널", pos: "명사", hanja: "빈도(頻道) — '頻'은 자주 빈, '道'는 길 도.", ex: { zh: "请换一个频道。", pinyin: "qǐng huàn yí ge píndào", ko: "채널 좀 바꿔 주세요." } },
        { zh: "品种", pinyin: "pǐnzhǒng", ko: "품종, 종류", pos: "명사", hanja: "품종(品種) — '品'은 물건 품, '種'은 씨 종.", ex: { zh: "这种水果品种很多。", pinyin: "zhè zhǒng shuǐguǒ pǐnzhǒng hěn duō", ko: "이 과일은 품종이 다양해요." } },
        { zh: "排球", pinyin: "páiqiú", ko: "배구", pos: "명사", hanja: "배구(排球) — '排'는 늘어설 배, '球'는 공 구.", ex: { zh: "我们下午打排球。", pinyin: "wǒmen xiàwǔ dǎ páiqiú", ko: "우리 오후에 배구 해요." } },
        { zh: "权力", pinyin: "quánlì", ko: "권력", pos: "명사", hanja: "권력(權力) — '權'은 권세 권, '力'은 힘 력.", ex: { zh: "他有很大的权力。", pinyin: "tā yǒu hěn dà de quánlì", ko: "그는 큰 권력을 가지고 있어요." } },
        { zh: "权利", pinyin: "quánlì", ko: "권리", pos: "명사", hanja: "권리(權利) — '權'은 권세 권, '利'는 이로울 리. 발음은 权力와 같지만 '권리'예요.", ex: { zh: "每个人都有受教育的权利。", pinyin: "měi ge rén dōu yǒu shòu jiàoyù de quánlì", ko: "누구나 교육받을 권리가 있어요." } },
        { zh: "奇迹", pinyin: "qíjì", ko: "기적", pos: "명사", hanja: "기적(奇跡) — '奇'는 기이할 기, '跡'은 자취 적.", ex: { zh: "这真是个奇迹。", pinyin: "zhè zhēn shì ge qíjì", ko: "이건 정말 기적이에요." } },
        { zh: "企业", pinyin: "qǐyè", ko: "기업", pos: "명사", hanja: "기업(企業) — '企'는 꾀할 기, '業'은 업 업.", ex: { zh: "他在一家大企业工作。", pinyin: "tā zài yì jiā dà qǐyè gōngzuò", ko: "그는 대기업에서 일해요." } },
        { zh: "气氛", pinyin: "qìfēn", ko: "분위기", pos: "명사", hanja: "기분(氣氛) — 한자는 '기분'이지만 '분위기(공간의 무드)'를 뜻해요. 가짜동족어 주의!", ex: { zh: "今天的气氛很好。", pinyin: "jīntiān de qìfēn hěn hǎo", ko: "오늘 분위기가 좋아요." } },
        { zh: "汽油", pinyin: "qìyóu", ko: "휘발유, 가솔린", pos: "명사", hanja: "기유(汽油) — '汽'는 김 기, '油'는 기름 유.", ex: { zh: "汽油又涨价了。", pinyin: "qìyóu yòu zhǎngjià le", ko: "휘발유 값이 또 올랐어요." } },
        { zh: "青春", pinyin: "qīngchūn", ko: "청춘", pos: "명사", hanja: "청춘(靑春) — '靑'은 푸를 청, '春'은 봄 춘.", ex: { zh: "青春是美好的。", pinyin: "qīngchūn shì měihǎo de", ko: "청춘은 아름다워요." } },
        { zh: "青少年", pinyin: "qīngshàonián", ko: "청소년", pos: "명사", hanja: "청소년(靑少年) — '靑'은 푸를 청, '少年'은 소년.", ex: { zh: "这部电影适合青少年看。", pinyin: "zhè bù diànyǐng shìhé qīngshàonián kàn", ko: "이 영화는 청소년이 보기에 좋아요." } },
        { zh: "情景", pinyin: "qíngjǐng", ko: "정경, 광경, 장면", pos: "명사", hanja: "정경(情景) — '情'은 뜻 정, '景'은 볕 경.", ex: { zh: "我还记得当时的情景。", pinyin: "wǒ hái jìde dāngshí de qíngjǐng", ko: "저는 그때의 광경을 아직 기억해요." } },
        { zh: "情绪", pinyin: "qíngxù", ko: "정서, 기분, 감정 상태", pos: "명사", hanja: "정서(情緒) — '情'은 뜻 정, '緒'는 실마리 서.", ex: { zh: "他今天情绪不太好。", pinyin: "tā jīntiān qíngxù bú tài hǎo", ko: "그는 오늘 기분이 별로 안 좋아요." } },
        { zh: "球迷", pinyin: "qiúmí", ko: "(구기 종목) 팬, 마니아", pos: "명사", hanja: "구미(球迷) — '球'는 공 구, '迷'는 미혹할 미(팬).", ex: { zh: "他是个足球球迷。", pinyin: "tā shì ge zúqiú qiúmí", ko: "그는 축구 팬이에요." } },
        { zh: "人才", pinyin: "réncái", ko: "인재", pos: "명사", hanja: "인재(人才) — '人'은 사람 인, '才'는 재주 재.", ex: { zh: "公司需要更多人才。", pinyin: "gōngsī xūyào gèng duō réncái", ko: "회사는 더 많은 인재가 필요해요." } },
        { zh: "人生", pinyin: "rénshēng", ko: "인생", pos: "명사", hanja: "인생(人生) — '人'은 사람 인, '生'은 날 생.", ex: { zh: "人生很短暂。", pinyin: "rénshēng hěn duǎnzàn", ko: "인생은 짧아요." } },
        { zh: "人事", pinyin: "rénshì", ko: "인사 (업무·관리)", pos: "명사", hanja: "인사(人事) — '人'은 사람 인, '事'는 일 사. 인력 관리 업무를 뜻해요.", ex: { zh: "她在人事部门工作。", pinyin: "tā zài rénshì bùmén gōngzuò", ko: "그녀는 인사 부서에서 일해요." } },
        { zh: "人物", pinyin: "rénwù", ko: "인물 (사람·등장인물)", pos: "명사", hanja: "인물(人物) — '人'은 사람 인, '物'은 물건 물.", ex: { zh: "这本小说的人物很多。", pinyin: "zhè běn xiǎoshuō de rénwù hěn duō", ko: "이 소설은 등장인물이 많아요." } },
        { zh: "人员", pinyin: "rényuán", ko: "인원, 요원, 직원", pos: "명사", hanja: "인원(人員) — '人'은 사람 인, '員'은 인원 원.", ex: { zh: "工作人员正在准备。", pinyin: "gōngzuò rényuán zhèngzài zhǔnbèi", ko: "직원들이 준비하고 있어요." } },
        { zh: "日程", pinyin: "rìchéng", ko: "일정, 스케줄", pos: "명사", hanja: "일정(日程) — '日'은 날 일, '程'은 길 정.", ex: { zh: "我的日程很满。", pinyin: "wǒ de rìchéng hěn mǎn", ko: "제 일정이 꽉 찼어요." } },
        { zh: "日历", pinyin: "rìlì", ko: "달력", pos: "명사", hanja: "일력(日曆) — '日'은 날 일, '曆'은 책력 력.", ex: { zh: "墙上挂着一本日历。", pinyin: "qiáng shang guà zhe yì běn rìlì", ko: "벽에 달력이 한 권 걸려 있어요." } },
        { zh: "日期", pinyin: "rìqī", ko: "날짜, 일자", pos: "명사", hanja: "일기(日期) — '日'은 날 일, '期'는 기약할 기.", ex: { zh: "请填上出生日期。", pinyin: "qǐng tián shang chūshēng rìqī", ko: "생년월일을 적어 주세요." } },
        { zh: "日用品", pinyin: "rìyòngpǐn", ko: "일용품, 생활용품", pos: "명사", hanja: "일용품(日用品) — '日用'은 일상에서 쓰는, '品'은 물건 품.", ex: { zh: "超市里有各种日用品。", pinyin: "chāoshì lǐ yǒu gè zhǒng rìyòngpǐn", ko: "마트에는 온갖 생활용품이 있어요." } },
        { zh: "荣誉", pinyin: "róngyù", ko: "명예, 영예", pos: "명사", hanja: "영예(榮譽) — '榮'은 영화 영, '譽'는 기릴 예.", ex: { zh: "这是我们的荣誉。", pinyin: "zhè shì wǒmen de róngyù", ko: "이건 우리의 영예예요." } },
        { zh: "软件", pinyin: "ruǎnjiàn", ko: "소프트웨어", pos: "명사", hanja: "연건(軟件) — '軟'은 부드러울 연, '件'은 물건 건.", ex: { zh: "这个软件很好用。", pinyin: "zhège ruǎnjiàn hěn hǎoyòng", ko: "이 소프트웨어는 쓰기 편해요." } },
        { zh: "嗓子", pinyin: "sǎngzi", ko: "목, 목구멍; 목소리", pos: "명사", ex: { zh: "我的嗓子有点疼。", pinyin: "wǒ de sǎngzi yǒudiǎn téng", ko: "목이 좀 아파요." } },
        { zh: "沙漠", pinyin: "shāmò", ko: "사막", pos: "명사", hanja: "사막(沙漠) — '沙'는 모래 사, '漠'은 사막 막.", ex: { zh: "骆驼生活在沙漠里。", pinyin: "luòtuo shēnghuó zài shāmò lǐ", ko: "낙타는 사막에서 살아요." } },
        { zh: "沙滩", pinyin: "shātān", ko: "모래사장, 백사장", pos: "명사", hanja: "사탄(沙灘) — '沙'는 모래 사, '灘'은 여울 탄.", ex: { zh: "孩子们在沙滩上玩。", pinyin: "háizimen zài shātān shang wán", ko: "아이들이 모래사장에서 놀아요." } },
        { zh: "勺子", pinyin: "sháozi", ko: "숟가락, 국자", pos: "명사", ex: { zh: "请给我一个勺子。", pinyin: "qǐng gěi wǒ yí ge sháozi", ko: "숟가락 하나 주세요." } },
        { zh: "舌头", pinyin: "shétou", ko: "혀", pos: "명사", hanja: "설두(舌頭) — '舌'은 혀 설, '頭'는 머리 두.", ex: { zh: "他咬到了舌头。", pinyin: "tā yǎo dào le shétou", ko: "그는 혀를 깨물었어요." } },
        { zh: "蛇", pinyin: "shé", ko: "뱀", pos: "명사", hanja: "사(蛇) — '뱀 사'.", ex: { zh: "草丛里有一条蛇。", pinyin: "cǎocóng lǐ yǒu yì tiáo shé", ko: "풀숲에 뱀 한 마리가 있어요." } },
        { zh: "设备", pinyin: "shèbèi", ko: "설비, 장비", pos: "명사", hanja: "설비(設備) — '設'은 베풀 설, '備'는 갖출 비.", ex: { zh: "这家工厂的设备很先进。", pinyin: "zhè jiā gōngchǎng de shèbèi hěn xiānjìn", ko: "이 공장의 설비는 첨단이에요." } },
        { zh: "设施", pinyin: "shèshī", ko: "시설", pos: "명사", hanja: "설시(設施) — '設'은 베풀 설, '施'는 베풀 시.", ex: { zh: "这里的体育设施很全。", pinyin: "zhèlǐ de tǐyù shèshī hěn quán", ko: "이곳의 체육 시설은 잘 갖춰져 있어요." } },
        { zh: "身材", pinyin: "shēncái", ko: "몸매, 체격", pos: "명사", hanja: "신재(身材) — '身'은 몸 신, '材'는 재목 재.", ex: { zh: "她的身材很好。", pinyin: "tā de shēncái hěn hǎo", ko: "그녀는 몸매가 좋아요." } },
        { zh: "身份", pinyin: "shēnfèn", ko: "신분, 신원", pos: "명사", hanja: "신분(身份) — '身'은 몸 신, '份'은 나눌 분.", ex: { zh: "请出示你的身份证。", pinyin: "qǐng chūshì nǐ de shēnfènzhèng", ko: "신분증을 보여 주세요." } },
        { zh: "神话", pinyin: "shénhuà", ko: "신화", pos: "명사", hanja: "신화(神話) — '神'은 귀신 신, '話'는 말씀 화.", ex: { zh: "他喜欢读希腊神话。", pinyin: "tā xǐhuan dú Xīlà shénhuà", ko: "그는 그리스 신화 읽기를 좋아해요." } },
        { zh: "神经", pinyin: "shénjīng", ko: "신경", pos: "명사", hanja: "신경(神經) — '神'은 귀신 신, '經'은 날 경.", ex: { zh: "他的神经很紧张。", pinyin: "tā de shénjīng hěn jǐnzhāng", ko: "그는 신경이 매우 곤두서 있어요." } },
        { zh: "枪", pinyin: "qiāng", ko: "총; 창", pos: "명사", hanja: "창(槍) — '창 창'. 입력 병음(Qiāng, 성씨)은 오독, 표준은 qiāng이에요.", ex: { zh: "警察拿着枪。", pinyin: "jǐngchá ná zhe qiāng", ko: "경찰이 총을 들고 있어요." } },
        { zh: "声调", pinyin: "shēngdiào", ko: "성조; 어조", pos: "명사", hanja: "성조(聲調) — '聲'은 소리 성, '調'는 고를 조.", ex: { zh: "汉语有四个声调。", pinyin: "Hànyǔ yǒu sì ge shēngdiào", ko: "중국어에는 네 개의 성조가 있어요." } },
        { zh: "绳子", pinyin: "shéngzi", ko: "끈, 밧줄, 노끈", pos: "명사", hanja: "승자(繩子) — '繩'은 노끈 승, '子'는 접미사.", ex: { zh: "用绳子把箱子捆好。", pinyin: "yòng shéngzi bǎ xiāngzi kǔn hǎo", ko: "끈으로 상자를 잘 묶으세요." } },
        { zh: "诗", pinyin: "shī", ko: "시", pos: "명사", hanja: "시(詩) — '시 시'.", ex: { zh: "他写了一首诗。", pinyin: "tā xiě le yì shǒu shī", ko: "그는 시 한 수를 썼어요." } },
        { zh: "石头", pinyin: "shítou", ko: "돌, 돌멩이", pos: "명사", hanja: "석두(石頭) — '石'은 돌 석, '頭'는 머리 두.", ex: { zh: "他扔了一块石头。", pinyin: "tā rēng le yí kuài shítou", ko: "그는 돌멩이 하나를 던졌어요." } },
        { zh: "时代", pinyin: "shídài", ko: "시대, 시기", pos: "명사", hanja: "시대(時代) — '時'는 때 시, '代'는 대신할 대.", ex: { zh: "我们生活在信息时代。", pinyin: "wǒmen shēnghuó zài xìnxī shídài", ko: "우리는 정보화 시대에 살고 있어요." } },
        { zh: "时刻", pinyin: "shíkè", ko: "시각, 때, 순간; 늘, 언제나", pos: "명사", hanja: "시각(時刻) — '時'는 때 시, '刻'은 새길 각.", ex: { zh: "这是个重要的时刻。", pinyin: "zhè shì ge zhòngyào de shíkè", ko: "이건 중요한 순간이에요." } },
        { zh: "时期", pinyin: "shíqī", ko: "시기, 기간", pos: "명사", hanja: "시기(時期) — '時'는 때 시, '期'는 기약할 기.", ex: { zh: "那是一段困难的时期。", pinyin: "nà shì yí duàn kùnnan de shíqī", ko: "그건 힘든 시기였어요." } },
        { zh: "时尚", pinyin: "shíshàng", ko: "패션, 유행; 트렌디함", pos: "명사", hanja: "시상(時尙) — '時'는 때 시, '尙'은 숭상할 상.", ex: { zh: "她很关注时尚。", pinyin: "tā hěn guānzhù shíshàng", ko: "그녀는 패션에 관심이 많아요." } },
        { zh: "盆", pinyin: "pén", ko: "대야, 화분; (양사) 한 대야", pos: "명사", hanja: "분(盆) — '동이 분'. '花盆(화분)'의 분.", ex: { zh: "她在阳台上种了一盆花。", pinyin: "tā zài yángtái shang zhòng le yì pén huā", ko: "그녀는 베란다에 꽃 화분 하나를 키워요." } },
        { zh: "扇子", pinyin: "shànzi", ko: "부채", pos: "명사", hanja: "선자(扇子) — '扇'은 부채 선, '子'는 접미사.", ex: { zh: "天气太热，她用扇子扇风。", pinyin: "tiānqì tài rè, tā yòng shànzi shān fēng", ko: "날이 너무 더워서 그녀는 부채로 부채질해요." } },
        { zh: "闪电", pinyin: "shǎndiàn", ko: "번개", pos: "명사", hanja: "섬전(閃電) — '閃'은 번쩍일 섬, '電'은 번개 전.", ex: { zh: "天上出现了闪电。", pinyin: "tiānshàng chūxiàn le shǎndiàn", ko: "하늘에 번개가 쳤어요." } },
        { zh: "商品", pinyin: "shāngpǐn", ko: "상품, 제품", pos: "명사", hanja: "상품(商品) — '商'은 장사 상, '品'은 물건 품.", ex: { zh: "这种商品卖得很好。", pinyin: "zhè zhǒng shāngpǐn mài de hěn hǎo", ko: "이 상품은 잘 팔려요." } },
        { zh: "商业", pinyin: "shāngyè", ko: "상업, 비즈니스", pos: "명사", hanja: "상업(商業) — '商'은 장사 상, '業'은 업 업.", ex: { zh: "这是一条商业街。", pinyin: "zhè shì yì tiáo shāngyè jiē", ko: "여기는 상업 거리예요." } },
        { zh: "其余", pinyin: "qíyú", ko: "나머지, 그 밖의 것", pos: "대명사", hanja: "기여(其餘) — '其'는 그 기, '餘'는 남을 여.", ex: { zh: "其余的事明天再说。", pinyin: "qíyú de shì míngtiān zài shuō", ko: "나머지 일은 내일 다시 얘기해요." } },
        { zh: "期间", pinyin: "qījiān", ko: "기간, 동안", pos: "명사", hanja: "기간(期間) — '期'는 기약할 기, '間'은 사이 간.", ex: { zh: "假期期间我去了旅行。", pinyin: "jiàqī qījiān wǒ qù le lǚxíng", ko: "휴가 기간에 저는 여행을 갔어요." } },
        { zh: "目前", pinyin: "mùqián", ko: "현재, 지금", pos: "명사", hanja: "목전(目前) — '目'은 눈 목, '前'은 앞 전. '눈앞=현재'.", ex: { zh: "目前还没有结果。", pinyin: "mùqián hái méiyǒu jiéguǒ", ko: "현재로서는 아직 결과가 없어요." } },
        { zh: "如今", pinyin: "rújīn", ko: "오늘날, 지금", pos: "명사", hanja: "여금(如今) — '如'는 같을 여, '今'은 이제 금.", ex: { zh: "如今的生活越来越好。", pinyin: "rújīn de shēnghuó yuèláiyuè hǎo", ko: "오늘날의 삶은 점점 나아지고 있어요." } },
        { zh: "圈", pinyin: "quān", ko: "동그라미, 원; 바퀴; (사람들의) 권, 모임", pos: "명사", hanja: "권(圈) — '우리·테두리 권'. 입력 병음(juān)은 다른 뜻의 다음자라 표준 quān으로 교정했어요.", ex: { zh: "请画一个圈。", pinyin: "qǐng huà yí ge quān", ko: "동그라미 하나를 그려 주세요." } },
        { zh: "秒", pinyin: "miǎo", ko: "초 (시간 단위)", pos: "명사", hanja: "묘(秒) — '초 묘'. 시간의 '초'를 뜻해요.", ex: { zh: "请等我十秒。", pinyin: "qǐng děng wǒ shí miǎo", ko: "10초만 기다려 주세요." } },
      ],
    },
    {
      name: "HSK5 보강 — 형용사·상태",
      icon: "🔴",
      words: [
        { zh: "明确", pinyin: "míngquè", ko: "명확하다, 분명하다; 명확히 하다", pos: "형용사", hanja: "명확(明確) — '明'은 밝을 명, '確'은 굳을 확.", ex: { zh: "他的态度很明确。", pinyin: "tā de tàidu hěn míngquè", ko: "그의 태도는 분명해요." } },
        { zh: "苗条", pinyin: "miáotiao", ko: "(몸매가) 날씬하다", pos: "형용사", ex: { zh: "她的身材很苗条。", pinyin: "tā de shēncái hěn miáotiao", ko: "그녀는 몸매가 날씬해요." } },
        { zh: "模糊", pinyin: "móhu", ko: "흐릿하다, 모호하다", pos: "형용사", hanja: "모호(模糊) — '模'는 본뜰 모, '糊'는 풀 호.", ex: { zh: "照片有点模糊。", pinyin: "zhàopiàn yǒudiǎn móhu", ko: "사진이 좀 흐릿해요." } },
        { zh: "陌生", pinyin: "mòshēng", ko: "낯설다, 생소하다", pos: "형용사", hanja: "맥생(陌生) — '陌'은 길 맥, '生'은 날 생.", ex: { zh: "这个地方对我很陌生。", pinyin: "zhège dìfang duì wǒ hěn mòshēng", ko: "이곳은 제게 낯설어요." } },
        { zh: "难看", pinyin: "nánkàn", ko: "보기 흉하다, 못생기다", pos: "형용사", hanja: "난간(難看) — '難'은 어려울 난, '看'은 볼 간. '보기 어렵다=흉하다'.", ex: { zh: "这件衣服颜色很难看。", pinyin: "zhè jiàn yīfu yánsè hěn nánkàn", ko: "이 옷은 색깔이 보기 안 좋아요." } },
        { zh: "嫩", pinyin: "nèn", ko: "(음식이) 연하다, 부드럽다; (색이) 연하다", pos: "형용사", ex: { zh: "这块肉很嫩。", pinyin: "zhè kuài ròu hěn nèn", ko: "이 고기는 아주 연해요." } },
        { zh: "能干", pinyin: "nénggàn", ko: "유능하다, 일을 잘하다", pos: "형용사", hanja: "능간(能幹) — '能'은 능할 능, '幹'은 줄기 간(능력).", ex: { zh: "她是个能干的人。", pinyin: "tā shì ge nénggàn de rén", ko: "그녀는 유능한 사람이에요." } },
        { zh: "浓", pinyin: "nóng", ko: "(농도가) 진하다, 짙다", pos: "형용사", hanja: "농(濃) — '짙을 농'.", ex: { zh: "这杯咖啡太浓了。", pinyin: "zhè bēi kāfēi tài nóng le", ko: "이 커피는 너무 진해요." } },
        { zh: "偶然", pinyin: "ǒurán", ko: "우연하다; 우연히", pos: "형용사", hanja: "우연(偶然) — '偶'는 짝 우, '然'은 그럴 연.", ex: { zh: "这只是偶然的事。", pinyin: "zhè zhǐ shì ǒurán de shì", ko: "이건 그저 우연한 일이에요." } },
        { zh: "疲劳", pinyin: "píláo", ko: "피로하다, 지치다; 피로", pos: "형용사", hanja: "피로(疲勞) — '疲'는 피곤할 피, '勞'는 일할 로.", ex: { zh: "工作了一天，我很疲劳。", pinyin: "gōngzuò le yì tiān, wǒ hěn píláo", ko: "하루 종일 일해서 무척 피곤해요." } },
        { zh: "平", pinyin: "píng", ko: "평평하다, 평탄하다; 무승부", pos: "형용사", hanja: "평(平) — '평평할 평'. 입력 병음(Píng, 성씨)은 오독, 표준은 píng이에요.", ex: { zh: "这条路很平。", pinyin: "zhè tiáo lù hěn píng", ko: "이 길은 평평해요." } },
        { zh: "平常", pinyin: "píngcháng", ko: "평소; 평범하다, 보통이다", pos: "형용사", hanja: "평상(平常) — '平'은 평평할 평, '常'은 항상 상.", ex: { zh: "我平常七点起床。", pinyin: "wǒ píngcháng qī diǎn qǐchuáng", ko: "저는 평소에 7시에 일어나요." } },
        { zh: "平等", pinyin: "píngděng", ko: "평등하다; 평등", pos: "형용사", hanja: "평등(平等) — '平'은 평평할 평, '等'은 무리 등.", ex: { zh: "人人都是平等的。", pinyin: "rénrén dōu shì píngděng de", ko: "사람은 누구나 평등해요." } },
        { zh: "平衡", pinyin: "pínghéng", ko: "균형이 잡히다; 균형", pos: "형용사", hanja: "평형(平衡) — '平'은 평평할 평, '衡'은 저울대 형.", ex: { zh: "要注意营养平衡。", pinyin: "yào zhùyì yíngyǎng pínghéng", ko: "영양 균형에 신경 써야 해요." } },
        { zh: "平静", pinyin: "píngjìng", ko: "평온하다, 차분하다", pos: "형용사", hanja: "평정(平靜) — '平'은 평평할 평, '靜'은 고요할 정.", ex: { zh: "她的心情很平静。", pinyin: "tā de xīnqíng hěn píngjìng", ko: "그녀의 마음은 평온해요." } },
        { zh: "平均", pinyin: "píngjūn", ko: "평균적이다, 고르다; 평균", pos: "형용사", hanja: "평균(平均) — '平'은 평평할 평, '均'은 고를 균.", ex: { zh: "平均气温是二十度。", pinyin: "píngjūn qìwēn shì èrshí dù", ko: "평균 기온은 20도예요." } },
        { zh: "迫切", pinyin: "pòqiè", ko: "절박하다, 절실하다", pos: "형용사", hanja: "박절(迫切) — '迫'은 닥칠 박, '切'은 간절할 절.", ex: { zh: "我们迫切需要帮助。", pinyin: "wǒmen pòqiè xūyào bāngzhù", ko: "우리는 도움이 절실히 필요해요." } },
        { zh: "朴素", pinyin: "pǔsù", ko: "소박하다, 검소하다", pos: "형용사", hanja: "박소(樸素) — '樸'은 순박할 박, '素'는 본디 소.", ex: { zh: "她穿得很朴素。", pinyin: "tā chuān de hěn pǔsù", ko: "그녀는 옷차림이 소박해요." } },
        { zh: "谦虚", pinyin: "qiānxū", ko: "겸손하다", pos: "형용사", hanja: "겸허(謙虛) — '謙'은 겸손할 겸, '虛'는 빌 허.", ex: { zh: "他为人很谦虚。", pinyin: "tā wéirén hěn qiānxū", ko: "그는 사람됨이 겸손해요." } },
        { zh: "浅", pinyin: "qiǎn", ko: "(깊이가) 얕다; (색이) 연하다", pos: "형용사", hanja: "천(淺) — '얕을 천'. 입력 병음(jiān)은 오독, 표준은 qiǎn이에요.", ex: { zh: "这条河很浅。", pinyin: "zhè tiáo hé hěn qiǎn", ko: "이 강은 얕아요." } },
        { zh: "强烈", pinyin: "qiángliè", ko: "강렬하다, 격렬하다", pos: "형용사", hanja: "강렬(強烈) — '強'은 강할 강, '烈'은 매울 렬.", ex: { zh: "阳光很强烈。", pinyin: "yángguāng hěn qiángliè", ko: "햇빛이 강렬해요." } },
        { zh: "巧妙", pinyin: "qiǎomiào", ko: "교묘하다, 절묘하다", pos: "형용사", hanja: "교묘(巧妙) — '巧'는 공교할 교, '妙'는 묘할 묘.", ex: { zh: "他用了一个巧妙的办法。", pinyin: "tā yòng le yí ge qiǎomiào de bànfǎ", ko: "그는 절묘한 방법을 썼어요." } },
        { zh: "亲爱", pinyin: "qīnài", ko: "친애하는, 사랑하는", pos: "형용사", hanja: "친애(親愛) — '親'은 친할 친, '愛'는 사랑 애.", ex: { zh: "亲爱的妈妈，节日快乐！", pinyin: "qīn'ài de māma, jiérì kuàilè", ko: "사랑하는 엄마, 명절 잘 보내세요!" } },
        { zh: "亲切", pinyin: "qīnqiè", ko: "친근하다, 다정하다", pos: "형용사", hanja: "친절(親切) — '親'은 친할 친, '切'은 간절할 절.", ex: { zh: "她对人很亲切。", pinyin: "tā duì rén hěn qīnqiè", ko: "그녀는 사람을 다정하게 대해요." } },
        { zh: "勤劳", pinyin: "qínláo", ko: "부지런하다, 근면하다", pos: "형용사", hanja: "근로(勤勞) — '勤'은 부지런할 근, '勞'는 일할 로.", ex: { zh: "他是个勤劳的人。", pinyin: "tā shì ge qínláo de rén", ko: "그는 부지런한 사람이에요." } },
        { zh: "青", pinyin: "qīng", ko: "푸르다, 파랗다; (식물이) 푸르다", pos: "형용사", hanja: "청(靑) — '푸를 청'. 입력 병음(Qīng, 약칭)은 오독, 표준은 qīng이에요.", ex: { zh: "山上的草很青。", pinyin: "shān shang de cǎo hěn qīng", ko: "산 위의 풀이 푸르러요." } },
        { zh: "清淡", pinyin: "qīngdàn", ko: "(맛이) 담백하다, 싱겁다; 한산하다", pos: "형용사", hanja: "청담(淸淡) — '淸'은 맑을 청, '淡'은 묽을 담.", ex: { zh: "我喜欢吃清淡的菜。", pinyin: "wǒ xǐhuan chī qīngdàn de cài", ko: "저는 담백한 음식을 좋아해요." } },
        { zh: "热烈", pinyin: "rèliè", ko: "열렬하다, 뜨겁다", pos: "형용사", hanja: "열렬(熱烈) — '熱'은 더울 열, '烈'은 매울 렬.", ex: { zh: "大家热烈鼓掌。", pinyin: "dàjiā rèliè gǔzhǎng", ko: "모두 열렬히 박수를 쳤어요." } },
        { zh: "热心", pinyin: "rèxīn", ko: "열성적이다, 친절하다", pos: "형용사", hanja: "열심(熱心) — '熱'은 더울 열, '心'은 마음 심.", ex: { zh: "他很热心，常常帮助别人。", pinyin: "tā hěn rèxīn, chángcháng bāngzhù biéren", ko: "그는 열성적이라 자주 남을 도와요." } },
        { zh: "日常", pinyin: "rìcháng", ko: "일상의, 평소의", pos: "형용사", hanja: "일상(日常) — '日'은 날 일, '常'은 항상 상.", ex: { zh: "这是日常生活用品。", pinyin: "zhè shì rìcháng shēnghuó yòngpǐn", ko: "이건 일상생활 용품이에요." } },
        { zh: "荣幸", pinyin: "róngxìng", ko: "영광스럽다, 영광이다", pos: "형용사", hanja: "영행(榮幸) — '榮'은 영화 영, '幸'은 다행 행.", ex: { zh: "认识你很荣幸。", pinyin: "rènshi nǐ hěn róngxìng", ko: "당신을 알게 되어 영광이에요." } },
        { zh: "弱", pinyin: "ruò", ko: "약하다, 허약하다", pos: "형용사", hanja: "약(弱) — '약할 약'.", ex: { zh: "他身体比较弱。", pinyin: "tā shēntǐ bǐjiào ruò", ko: "그는 몸이 비교적 약해요." } },
        { zh: "傻", pinyin: "shǎ", ko: "어리석다, 멍청하다", pos: "형용사", ex: { zh: "你别做傻事。", pinyin: "nǐ bié zuò shǎ shì", ko: "바보 같은 짓 하지 마세요." } },
        { zh: "善良", pinyin: "shànliáng", ko: "선량하다, 착하다", pos: "형용사", hanja: "선량(善良) — '善'은 착할 선, '良'은 어질 량.", ex: { zh: "她是个善良的人。", pinyin: "tā shì ge shànliáng de rén", ko: "그녀는 선량한 사람이에요." } },
        { zh: "善于", pinyin: "shànyú", ko: "~을 잘하다, ~에 능하다", pos: "동사", hanja: "선어(善於) — '善'은 잘할 선, '於'는 어조사 어.", ex: { zh: "他善于交朋友。", pinyin: "tā shànyú jiāo péngyou", ko: "그는 친구 사귀는 데 능해요." } },
        { zh: "生动", pinyin: "shēngdòng", ko: "생동감 있다, 생생하다", pos: "형용사", hanja: "생동(生動) — '生'은 날 생, '動'은 움직일 동.", ex: { zh: "这个故事讲得很生动。", pinyin: "zhège gùshi jiǎng de hěn shēngdòng", ko: "이 이야기는 아주 생생하게 들려줬어요." } },
        { zh: "神秘", pinyin: "shénmì", ko: "신비하다, 신비롭다", pos: "형용사", hanja: "신비(神秘) — '神'은 귀신 신, '秘'는 숨길 비.", ex: { zh: "这个地方很神秘。", pinyin: "zhège dìfang hěn shénmì", ko: "이곳은 신비로워요." } },
        { zh: "时髦", pinyin: "shímáo", ko: "유행에 맞다, 세련되다", pos: "형용사", hanja: "시모(時髦) — '時'는 때 시, '髦'는 다팔머리 모.", ex: { zh: "她穿得很时髦。", pinyin: "tā chuān de hěn shímáo", ko: "그녀는 옷차림이 세련됐어요." } },
        { zh: "密切", pinyin: "mìqiè", ko: "밀접하다, 긴밀하다", pos: "형용사", hanja: "밀절(密切) — '密'은 빽빽할 밀, '切'은 간절할 절.", ex: { zh: "他们关系很密切。", pinyin: "tāmen guānxì hěn mìqiè", ko: "그들은 관계가 아주 밀접해요." } },
        { zh: "批", pinyin: "pī", ko: "(양사) 무더기, 묶음, 떼; 결재하다", pos: "양사", ex: { zh: "这批货已经到了。", pinyin: "zhè pī huò yǐjīng dào le", ko: "이번 물량은 이미 도착했어요." } },
        { zh: "片", pinyin: "piàn", ko: "(양사) 조각, 편; 한 면 (얇은 것)", pos: "양사", hanja: "편(片) — '조각 편'.", ex: { zh: "我吃了一片药。", pinyin: "wǒ chī le yí piàn yào", ko: "저는 약 한 알을 먹었어요." } },
        { zh: "匹", pinyin: "pǐ", ko: "(양사) 필, 마리 (말·천)", pos: "양사", hanja: "필(匹) — '짝 필'. 말이나 천을 세는 양사예요.", ex: { zh: "他买了一匹马。", pinyin: "tā mǎi le yì pǐ mǎ", ko: "그는 말 한 마리를 샀어요." } },
        { zh: "升", pinyin: "shēng", ko: "오르다, 상승하다; (양사) 리터(L)", pos: "동사", hanja: "승(升) — '되 승, 오를 승'. 부피 단위로도 써요.", ex: { zh: "太阳升起来了。", pinyin: "tàiyáng shēng qǐlái le", ko: "해가 떠올랐어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 부사·기타",
      icon: "🔴",
      words: [
        { zh: "某", pinyin: "mǒu", ko: "어느, 모, 아무 (불특정)", pos: "대명사", hanja: "모(某) — '아무 모'.", ex: { zh: "某天我会告诉你的。", pinyin: "mǒu tiān wǒ huì gàosu nǐ de", ko: "언젠가 당신에게 말해 줄게요." } },
        { zh: "哪怕", pinyin: "nǎpà", ko: "설령 ~할지라도, 비록 ~하더라도", pos: "접속사", ex: { zh: "哪怕下雨，我也要去。", pinyin: "nǎpà xià yǔ, wǒ yě yào qù", ko: "비가 와도 저는 갈 거예요." } },
        { zh: "难怪", pinyin: "nánguài", ko: "어쩐지, 과연 (그래서 그렇구나)", pos: "부사", hanja: "난괴(難怪) — '難'은 어려울 난, '怪'는 괴이할 괴. '탓하기 어렵다=어쩐지'.", ex: { zh: "难怪他不高兴，原来你骗了他。", pinyin: "nánguài tā bù gāoxìng, yuánlái nǐ piàn le tā", ko: "어쩐지 그가 기분 나빠하더라니, 알고 보니 당신이 속였군요." } },
        { zh: "悄悄", pinyin: "qiāoqiāo", ko: "조용히, 살그머니, 몰래", pos: "부사", ex: { zh: "他悄悄地走了。", pinyin: "tā qiāoqiāo de zǒu le", ko: "그는 살그머니 떠났어요." } },
        { zh: "亲自", pinyin: "qīnzì", ko: "직접, 친히, 몸소", pos: "부사", hanja: "친자(親自) — '親'은 친할 친, '自'는 스스로 자.", ex: { zh: "经理亲自来了。", pinyin: "jīnglǐ qīnzì lái le", ko: "사장님이 직접 오셨어요." } },
        { zh: "如何", pinyin: "rúhé", ko: "어떻게, 어떠하다", pos: "대명사", hanja: "여하(如何) — '如'는 같을 여, '何'는 어찌 하.", ex: { zh: "你打算如何解决？", pinyin: "nǐ dǎsuàn rúhé jiějué", ko: "당신은 어떻게 해결할 생각이에요?" } },
        { zh: "平方", pinyin: "píngfāng", ko: "제곱; 평방, 제곱미터", pos: "명사", hanja: "평방(平方) — '平'은 평평할 평, '方'은 모 방.", ex: { zh: "这个房间有二十平方米。", pinyin: "zhège fángjiān yǒu èrshí píngfāngmǐ", ko: "이 방은 20제곱미터예요." } },
      ],
    },
  ],
};

export default themes;
