/**
 * H5 (HSK 5급) 보강 어휘 — 청크 c (200개).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되,
 * 성씨·이체자·다음자(多音字) 오독은 표준 병음으로 교정했어요.
 */
export default {
  themes: [
    {
      name: "HSK5 보강 — 동사",
      icon: "🔴",
      words: [
        { zh: "恢复", pinyin: "huī fù", ko: "회복하다, 되찾다; 재개하다", pos: "동사", hanja: "회복(恢復) — '恢'는 넓을 회, '復'는 회복할 복.", ex: { zh: "他的身体慢慢恢复了。", pinyin: "tā de shēntǐ mànmàn huīfù le", ko: "그의 몸이 천천히 회복됐어요." } },
        { zh: "挥", pinyin: "huī", ko: "휘두르다, (손을) 흔들다; 지휘하다", pos: "동사", hanja: "휘(揮) — '휘두를 휘'. '指挥(지휘)'의 휘.", ex: { zh: "他向我挥了挥手。", pinyin: "tā xiàng wǒ huī le huī shǒu", ko: "그는 저를 향해 손을 흔들었어요." } },
        { zh: "活跃", pinyin: "huó yuè", ko: "활기차다, 활발하다; 활기를 띠게 하다", pos: "형용사", hanja: "활약(活躍) — '躍'은 뛸 약. 분위기를 띄울 때도 써요.", ex: { zh: "课堂气氛很活跃。", pinyin: "kètáng qìfēn hěn huóyuè", ko: "교실 분위기가 활기차요." } },
        { zh: "及格", pinyin: "jí gé", ko: "합격하다, 통과하다", pos: "동사", hanja: "급격(及格) — '及'은 미칠 급, '格'은 격식 격. '기준에 미치다'.", ex: { zh: "这次考试我及格了。", pinyin: "zhè cì kǎoshì wǒ jígé le", ko: "이번 시험은 합격했어요." } },
        { zh: "集中", pinyin: "jí zhōng", ko: "집중하다, 모으다", pos: "동사", hanja: "집중(集中) — 한자 그대로.", ex: { zh: "请集中注意力。", pinyin: "qǐng jízhōng zhùyìlì", ko: "주의력을 집중하세요." } },
        { zh: "计算", pinyin: "jì suàn", ko: "계산하다", pos: "동사", hanja: "계산(計算) — '計'는 셀 계, '算'은 셈할 산.", ex: { zh: "请帮我计算一下总数。", pinyin: "qǐng bāng wǒ jìsuàn yíxià zǒngshù", ko: "총액을 좀 계산해 주세요." } },
        { zh: "记录", pinyin: "jì lù", ko: "기록하다; 기록", pos: "동사", hanja: "기록(記錄) — 한자 그대로.", ex: { zh: "请记录会议内容。", pinyin: "qǐng jìlù huìyì nèiróng", ko: "회의 내용을 기록하세요." } },
        { zh: "记忆", pinyin: "jì yì", ko: "기억하다; 기억", pos: "동사", hanja: "기억(記憶) — '憶'은 생각할 억.", ex: { zh: "我对那天的记忆很深。", pinyin: "wǒ duì nà tiān de jìyì hěn shēn", ko: "저는 그날의 기억이 깊어요." } },
        { zh: "纪念", pinyin: "jì niàn", ko: "기념하다; 기념", pos: "동사", hanja: "기념(紀念) — '紀'는 벼리 기, '念'은 생각할 념.", ex: { zh: "我们一起拍照纪念。", pinyin: "wǒmen yìqǐ pāizhào jìniàn", ko: "우리 같이 사진 찍어 기념해요." } },
        { zh: "假装", pinyin: "jiǎ zhuāng", ko: "~인 척하다, 가장하다", pos: "동사", hanja: "가장(假裝) — '假'는 거짓 가, '裝'은 꾸밀 장.", ex: { zh: "他假装没听见。", pinyin: "tā jiǎzhuāng méi tīngjiàn", ko: "그는 못 들은 척했어요." } },
        { zh: "驾驶", pinyin: "jià shǐ", ko: "운전하다, 조종하다", pos: "동사", hanja: "가사(駕駛) — '駕'는 멍에 가, '駛'는 달릴 사.", ex: { zh: "他正在学习驾驶。", pinyin: "tā zhèngzài xuéxí jiàshǐ", ko: "그는 운전을 배우고 있어요." } },
        { zh: "嫁", pinyin: "jià", ko: "(여자가) 시집가다, 출가하다", pos: "동사", hanja: "가(嫁) — '시집갈 가'. 여자가 결혼하는 쪽이에요.", ex: { zh: "她去年嫁给了一个医生。", pinyin: "tā qùnián jià gěi le yí ge yīshēng", ko: "그녀는 작년에 의사에게 시집갔어요." } },
        { zh: "煎", pinyin: "jiān", ko: "(기름에) 부치다, 지지다", pos: "동사", hanja: "전(煎) — '달일 전'. 적은 기름에 부쳐요.", ex: { zh: "妈妈在煎鸡蛋。", pinyin: "māma zài jiān jīdàn", ko: "엄마가 달걀을 부치고 있어요." } },
        { zh: "捡", pinyin: "jiǎn", ko: "줍다, 집다", pos: "동사", hanja: "검(撿) — '주울 검'.", ex: { zh: "我在路上捡到一支笔。", pinyin: "wǒ zài lùshang jiǎn dào yì zhī bǐ", ko: "길에서 펜 하나를 주웠어요." } },
        { zh: "建立", pinyin: "jiàn lì", ko: "건립하다, 세우다, 맺다", pos: "동사", hanja: "건립(建立) — '建'은 세울 건, '立'은 설 립.", ex: { zh: "他们建立了良好的关系。", pinyin: "tāmen jiànlì le liánghǎo de guānxì", ko: "그들은 좋은 관계를 맺었어요." } },
        { zh: "建设", pinyin: "jiàn shè", ko: "건설하다", pos: "동사", hanja: "건설(建設) — '設'은 베풀 설.", ex: { zh: "国家正在建设高铁。", pinyin: "guójiā zhèngzài jiànshè gāotiě", ko: "나라가 고속철도를 건설하고 있어요." } },
        { zh: "降落", pinyin: "jiàng luò", ko: "착륙하다, 내려앉다", pos: "동사", hanja: "강락(降落) — '降'은 내릴 강, '落'은 떨어질 락.", ex: { zh: "飞机准时降落了。", pinyin: "fēijī zhǔnshí jiàngluò le", ko: "비행기가 제시간에 착륙했어요." } },
        { zh: "交换", pinyin: "jiāo huàn", ko: "교환하다, 맞바꾸다", pos: "동사", hanja: "교환(交換) — 한자 그대로.", ex: { zh: "我们交换了联系方式。", pinyin: "wǒmen jiāohuàn le liánxì fāngshì", ko: "우리는 연락처를 교환했어요." } },
        { zh: "交际", pinyin: "jiāo jì", ko: "교제하다, 사교하다; 교제", pos: "동사", hanja: "교제(交際) — '際'는 즈음 제.", ex: { zh: "他很善于交际。", pinyin: "tā hěn shànyú jiāojì", ko: "그는 사교에 능해요." } },
        { zh: "浇", pinyin: "jiāo", ko: "(물을) 주다, 끼얹다, 뿌리다", pos: "동사", hanja: "요(澆) — '물댈 요'.", ex: { zh: "我每天给花浇水。", pinyin: "wǒ měi tiān gěi huā jiāo shuǐ", ko: "저는 매일 꽃에 물을 줘요." } },
        { zh: "结合", pinyin: "jié hé", ko: "결합하다, 결부하다", pos: "동사", hanja: "결합(結合) — '結'은 맺을 결, '合'은 합할 합.", ex: { zh: "理论要和实践结合。", pinyin: "lǐlùn yào hé shíjiàn jiéhé", ko: "이론은 실천과 결합해야 해요." } },
        { zh: "结账", pinyin: "jié zhàng", ko: "계산하다, 결제하다", pos: "동사", hanja: "결장(結賬) — '賬'은 장부 장. 식당에서 '계산하다'.", ex: { zh: "服务员，结账！", pinyin: "fúwùyuán, jiézhàng", ko: "저기요, 계산할게요!" } },
        { zh: "解放", pinyin: "jiě fàng", ko: "해방하다, 풀어주다", pos: "동사", hanja: "해방(解放) — '解'는 풀 해, '放'은 놓을 방.", ex: { zh: "新技术解放了人力。", pinyin: "xīn jìshù jiěfàng le rénlì", ko: "신기술이 인력을 해방시켰어요." } },
        { zh: "戒烟", pinyin: "jiè yān", ko: "금연하다, 담배를 끊다", pos: "동사", hanja: "계연(戒煙) — '戒'는 경계할 계, '煙'은 연기 연.", ex: { zh: "为了健康，他决定戒烟。", pinyin: "wèile jiànkāng, tā juédìng jièyān", ko: "건강을 위해 그는 금연하기로 했어요." } },
        { zh: "进口", pinyin: "jìn kǒu", ko: "수입하다; 입구", pos: "동사", hanja: "진구(進口) — '進'은 나아갈 진, '口'는 입 구. '수입·진입구'.", ex: { zh: "这种水果是从国外进口的。", pinyin: "zhè zhǒng shuǐguǒ shì cóng guówài jìnkǒu de", ko: "이 과일은 외국에서 수입한 거예요." } },
        { zh: "经营", pinyin: "jīng yíng", ko: "경영하다, 운영하다", pos: "동사", hanja: "경영(經營) — '經'은 지날 경, '營'은 경영할 영.", ex: { zh: "他经营着一家饭店。", pinyin: "tā jīngyíng zhe yì jiā fàndiàn", ko: "그는 식당 한 곳을 운영하고 있어요." } },
        { zh: "敬爱", pinyin: "jìng ài", ko: "존경하고 사랑하다, 경애하다", pos: "동사", hanja: "경애(敬愛) — '敬'은 공경 경, '愛'는 사랑 애.", ex: { zh: "我们都很敬爱这位老师。", pinyin: "wǒmen dōu hěn jìng'ài zhè wèi lǎoshī", ko: "우리 모두 이 선생님을 존경해요." } },
        { zh: "救", pinyin: "jiù", ko: "구하다, 구조하다, 살리다", pos: "동사", hanja: "구(救) — '구원할 구'. '救命(구명)'의 구.", ex: { zh: "医生救了他的命。", pinyin: "yīshēng jiù le tā de mìng", ko: "의사가 그의 목숨을 구했어요." } },
        { zh: "据说", pinyin: "jù shuō", ko: "~라고 한다, 듣자 하니", pos: "동사", hanja: "거설(據說) — '據'는 근거 거, '說'은 말씀 설.", ex: { zh: "据说明天会下雪。", pinyin: "jùshuō míngtiān huì xià xuě", ko: "듣자 하니 내일 눈이 온대요." } },
        { zh: "聚会", pinyin: "jù huì", ko: "모이다; 모임", pos: "동사", hanja: "취회(聚會) — '聚'는 모일 취, '會'는 모일 회.", ex: { zh: "我们周末一起聚会吧。", pinyin: "wǒmen zhōumò yìqǐ jùhuì ba", ko: "우리 주말에 같이 모여요." } },
        { zh: "捐", pinyin: "juān", ko: "기부하다, 헌납하다", pos: "동사", hanja: "연(捐) — '버릴 연'. '捐款(기부금)'의 연.", ex: { zh: "他给灾区捐了很多钱。", pinyin: "tā gěi zāiqū juān le hěn duō qián", ko: "그는 재해 지역에 돈을 많이 기부했어요." } },
        { zh: "具备", pinyin: "jù bèi", ko: "갖추다, 구비하다", pos: "동사", hanja: "구비(具備) — '具'는 갖출 구, '備'는 갖출 비.", ex: { zh: "这份工作需要具备相关经验。", pinyin: "zhè fèn gōngzuò xūyào jùbèi xiāngguān jīngyàn", ko: "이 일은 관련 경험을 갖춰야 해요." } },
        { zh: "举", pinyin: "jǔ", ko: "들다, 들어 올리다; (예를) 들다", pos: "동사", hanja: "거(舉) — '들 거'. '举手(거수)'의 거.", ex: { zh: "请举手回答问题。", pinyin: "qǐng jǔshǒu huídá wèntí", ko: "손을 들고 질문에 답하세요." } },
        { zh: "开发", pinyin: "kāi fā", ko: "개발하다, 개척하다", pos: "동사", hanja: "개발(開發) — '開'는 열 개, '發'은 필 발.", ex: { zh: "公司在开发新产品。", pinyin: "gōngsī zài kāifā xīn chǎnpǐn", ko: "회사가 신제품을 개발하고 있어요." } },
        { zh: "开放", pinyin: "kāi fàng", ko: "개방하다; 꽃이 피다", pos: "동사", hanja: "개방(開放) — '放'은 놓을 방.", ex: { zh: "这个公园对游客开放。", pinyin: "zhège gōngyuán duì yóukè kāifàng", ko: "이 공원은 관광객에게 개방돼 있어요." } },
        { zh: "砍", pinyin: "kǎn", ko: "(도끼로) 찍다, 베다, 자르다", pos: "동사", hanja: "감(砍) — '벨 감'.", ex: { zh: "他用斧头砍柴。", pinyin: "tā yòng fǔtóu kǎn chái", ko: "그는 도끼로 장작을 패요." } },
        { zh: "看不起", pinyin: "kàn bu qǐ", ko: "깔보다, 무시하다, 업신여기다", pos: "동사", ex: { zh: "不要看不起别人。", pinyin: "búyào kànbuqǐ biéren", ko: "남을 무시하지 마세요." } },
        { zh: "抗议", pinyin: "kàng yì", ko: "항의하다; 항의", pos: "동사", hanja: "항의(抗議) — '抗'은 막을 항, '議'는 의논할 의.", ex: { zh: "群众上街抗议。", pinyin: "qúnzhòng shàng jiē kàngyì", ko: "군중이 거리로 나와 항의했어요." } },
        { zh: "控制", pinyin: "kòng zhì", ko: "통제하다, 제어하다", pos: "동사", hanja: "공제(控制) — '控'은 당길 공, '制'는 마를 제.", ex: { zh: "他无法控制自己的情绪。", pinyin: "tā wúfǎ kòngzhì zìjǐ de qíngxù", ko: "그는 자기 감정을 통제할 수 없어요." } },
        { zh: "夸", pinyin: "kuā", ko: "칭찬하다; 과장하다", pos: "동사", hanja: "과(夸) — '자랑할 과'. '夸奖(칭찬)'의 과.", ex: { zh: "老师夸他很聪明。", pinyin: "lǎoshī kuā tā hěn cōngming", ko: "선생님이 그가 똑똑하다고 칭찬했어요." } },
        { zh: "来自", pinyin: "lái zì", ko: "~로부터 오다, ~에서 비롯되다", pos: "동사", hanja: "내자(來自) — '來'는 올 래, '自'는 스스로 자.", ex: { zh: "他来自一个小城市。", pinyin: "tā láizì yí ge xiǎo chéngshì", ko: "그는 작은 도시 출신이에요." } },
        { zh: "拦", pinyin: "lán", ko: "막다, 가로막다, (택시를) 잡다", pos: "동사", hanja: "란(攔) — '막을 란'.", ex: { zh: "他在路边拦了一辆出租车。", pinyin: "tā zài lùbiān lán le yí liàng chūzūchē", ko: "그는 길가에서 택시를 잡았어요." } },
        { zh: "离婚", pinyin: "lí hūn", ko: "이혼하다", pos: "동사", hanja: "이혼(離婚) — '離'는 떠날 리, '婚'은 혼인할 혼.", ex: { zh: "他们去年离婚了。", pinyin: "tāmen qùnián líhūn le", ko: "그들은 작년에 이혼했어요." } },
        { zh: "联合", pinyin: "lián hé", ko: "연합하다, 결합하다", pos: "동사", hanja: "연합(聯合) — '聯'은 잇닿을 련, '合'은 합할 합.", ex: { zh: "几家公司联合起来开发产品。", pinyin: "jǐ jiā gōngsī liánhé qǐlái kāifā chǎnpǐn", ko: "몇몇 회사가 연합해 제품을 개발해요." } },
        { zh: "恋爱", pinyin: "liàn ài", ko: "연애하다; 연애", pos: "동사", hanja: "연애(戀愛) — '戀'은 그리워할 련, '愛'는 사랑 애.", ex: { zh: "他们正在谈恋爱。", pinyin: "tāmen zhèngzài tán liàn'ài", ko: "그들은 지금 연애 중이에요." } },
        { zh: "浏览", pinyin: "liú lǎn", ko: "훑어보다, 둘러보다, 브라우징하다", pos: "동사", hanja: "유람(瀏覽) — '瀏'는 맑을 류, '覽'은 볼 람.", ex: { zh: "我喜欢浏览各种网站。", pinyin: "wǒ xǐhuan liúlǎn gè zhǒng wǎngzhàn", ko: "저는 여러 사이트를 둘러보는 걸 좋아해요." } },
        { zh: "流传", pinyin: "liú chuán", ko: "전해 내려오다, 퍼지다", pos: "동사", hanja: "유전(流傳) — '流'는 흐를 류, '傳'은 전할 전.", ex: { zh: "这个故事流传了很多年。", pinyin: "zhège gùshi liúchuán le hěn duō nián", ko: "이 이야기는 오랜 세월 전해져 왔어요." } },
        { zh: "漏", pinyin: "lòu", ko: "새다; 빠뜨리다, 누락하다", pos: "동사", hanja: "루(漏) — '샐 루'.", ex: { zh: "屋顶漏水了。", pinyin: "wūdǐng lòu shuǐ le", ko: "지붕에서 물이 새요." } },
        { zh: "录取", pinyin: "lù qǔ", ko: "(시험 등에) 합격시키다, 뽑다", pos: "동사", hanja: "녹취(錄取) — '錄'은 기록할 록, '取'는 가질 취.", ex: { zh: "他被那所大学录取了。", pinyin: "tā bèi nà suǒ dàxué lùqǔ le", ko: "그는 그 대학에 합격했어요." } },
        { zh: "录音", pinyin: "lù yīn", ko: "녹음하다; 녹음", pos: "동사", hanja: "녹음(錄音) — '錄'은 기록할 록, '音'은 소리 음.", ex: { zh: "我把课录音了下来。", pinyin: "wǒ bǎ kè lùyīn le xiàlái", ko: "저는 수업을 녹음해 뒀어요." } },
        { zh: "露", pinyin: "lù", ko: "드러내다, 노출하다; 이슬", pos: "동사", hanja: "로(露) — '이슬 로'. '드러나다'는 露出(노출).", ex: { zh: "他脸上露出了笑容。", pinyin: "tā liǎn shang lùchū le xiàoróng", ko: "그의 얼굴에 미소가 드러났어요." } },
        { zh: "轮流", pinyin: "lún liú", ko: "교대로 하다, 돌아가며 하다", pos: "동사", hanja: "윤류(輪流) — '輪'은 바퀴 륜, '流'는 흐를 류.", ex: { zh: "我们轮流照顾病人。", pinyin: "wǒmen lúnliú zhàogu bìngrén", ko: "우리는 돌아가며 환자를 돌봐요." } },
        { zh: "骂", pinyin: "mà", ko: "욕하다, 꾸짖다", pos: "동사", hanja: "매(罵) — '꾸짖을 매'.", ex: { zh: "妈妈骂了他一顿。", pinyin: "māma mà le tā yí dùn", ko: "엄마가 그를 한바탕 꾸짖었어요." } },
        { zh: "满足", pinyin: "mǎn zú", ko: "만족하다; 만족시키다, 충족하다", pos: "동사", hanja: "만족(滿足) — '滿'은 찰 만, '足'은 발 족.", ex: { zh: "他对现状很满足。", pinyin: "tā duì xiànzhuàng hěn mǎnzú", ko: "그는 현재 상황에 만족해요." } },
        { zh: "接触", pinyin: "jiē chù", ko: "접촉하다, 닿다, 만나다", pos: "동사", hanja: "접촉(接觸) — '接'은 이을 접, '觸'은 닿을 촉.", ex: { zh: "我第一次接触这个领域。", pinyin: "wǒ dì yī cì jiēchù zhège lǐngyù", ko: "저는 이 분야를 처음 접해요." } },
        { zh: "接待", pinyin: "jiē dài", ko: "접대하다, 응접하다, 맞이하다", pos: "동사", hanja: "접대(接待) — '接'은 이을 접, '待'는 기다릴 대.", ex: { zh: "她负责接待客人。", pinyin: "tā fùzé jiēdài kèrén", ko: "그녀가 손님 접대를 맡아요." } },
        { zh: "接近", pinyin: "jiē jìn", ko: "접근하다, 가까이 가다", pos: "동사", hanja: "접근(接近) — '近'은 가까울 근.", ex: { zh: "时间已经接近中午了。", pinyin: "shíjiān yǐjīng jiējìn zhōngwǔ le", ko: "시간이 벌써 정오에 가까워졌어요." } },
        { zh: "节省", pinyin: "jié shěng", ko: "절약하다, 아끼다", pos: "동사", hanja: "절성(節省) — '節'은 마디 절, '省'은 덜 생.", ex: { zh: "我们要节省用水。", pinyin: "wǒmen yào jiéshěng yòng shuǐ", ko: "우리는 물을 아껴 써야 해요." } },
        { zh: "借口", pinyin: "jiè kǒu", ko: "핑계 대다; 핑계, 구실", pos: "명사", hanja: "차구(借口) — '借'는 빌릴 차, '口'는 입 구.", ex: { zh: "这只是一个借口。", pinyin: "zhè zhǐshì yí ge jièkǒu", ko: "이건 그냥 핑계일 뿐이에요." } },
        { zh: "尽力", pinyin: "jìn lì", ko: "힘을 다하다, 최선을 다하다", pos: "동사", hanja: "진력(盡力) — '盡'은 다할 진, '力'은 힘 력.", ex: { zh: "我会尽力帮你。", pinyin: "wǒ huì jìnlì bāng nǐ", ko: "최선을 다해 도울게요." } },
        { zh: "讲究", pinyin: "jiǎng jiu", ko: "중시하다, 신경 쓰다; 정교하다", pos: "동사", hanja: "강구(講究) — '講'은 외울 강, '究'는 궁구할 구. '따지다·중시하다'.", ex: { zh: "他做事很讲究。", pinyin: "tā zuòshì hěn jiǎngjiu", ko: "그는 일을 꼼꼼히 따져서 해요." } },
        { zh: "教训", pinyin: "jiào xun", ko: "훈계하다, 혼내다; 교훈", pos: "동사", hanja: "교훈(教訓) — '教'는 가르칠 교, '訓'은 가르칠 훈.", ex: { zh: "这件事给了我一个教训。", pinyin: "zhè jiàn shì gěi le wǒ yí ge jiàoxun", ko: "이 일이 저에게 교훈을 줬어요." } },
        { zh: "接着", pinyin: "jiē zhe", ko: "이어서, 잇따라; 받다", pos: "동사", hanja: "접착(接著) — '接'은 이을 접. '뒤이어'라는 접속 표현으로도 써요.", ex: { zh: "他说完，接着大家鼓掌。", pinyin: "tā shuōwán, jiēzhe dàjiā gǔzhǎng", ko: "그가 말을 마치자 이어서 모두 박수쳤어요." } },
        { zh: "可见", pinyin: "kě jiàn", ko: "~을 알 수 있다; ~인 셈이다", pos: "동사", hanja: "가견(可見) — '可'는 옳을 가, '見'은 볼 견. '이로써 ~을 알 수 있다'.", ex: { zh: "由此可见，努力很重要。", pinyin: "yóu cǐ kějiàn, nǔlì hěn zhòngyào", ko: "이로써 노력이 중요함을 알 수 있어요." } },
        { zh: "卷", pinyin: "juǎn", ko: "말다, 감다; 두루마리, 권(양사)", pos: "동사", hanja: "권(卷) — '책 권'. 동사로는 '둥글게 말다'.", ex: { zh: "她把画卷了起来。", pinyin: "tā bǎ huà juǎn le qǐlái", ko: "그녀는 그림을 둥글게 말았어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 명사·추상",
      icon: "🔴",
      words: [
        { zh: "汇率", pinyin: "huì lǜ", ko: "환율", pos: "명사", hanja: "회율(匯率) — '匯'는 모일 회, '率'은 비율 률.", ex: { zh: "最近人民币汇率上升了。", pinyin: "zuìjìn rénmínbì huìlǜ shàngshēng le", ko: "최근 위안화 환율이 올랐어요." } },
        { zh: "会计", pinyin: "kuài jì", ko: "회계; 회계사", pos: "명사", hanja: "회계(會計) — '會'는 여기서 'kuài'로 읽어요. '計'는 셀 계.", ex: { zh: "她在公司当会计。", pinyin: "tā zài gōngsī dāng kuàijì", ko: "그녀는 회사에서 회계 일을 해요." } },
        { zh: "婚礼", pinyin: "hūn lǐ", ko: "결혼식, 혼례", pos: "명사", hanja: "혼례(婚禮) — '婚'은 혼인 혼, '禮'는 예도 례.", ex: { zh: "他们的婚礼很热闹。", pinyin: "tāmen de hūnlǐ hěn rènao", ko: "그들의 결혼식은 떠들썩했어요." } },
        { zh: "婚姻", pinyin: "hūn yīn", ko: "혼인, 결혼 생활", pos: "명사", hanja: "혼인(婚姻) — '婚'은 혼인 혼, '姻'은 혼인 인.", ex: { zh: "他们的婚姻很幸福。", pinyin: "tāmen de hūnyīn hěn xìngfú", ko: "그들의 결혼 생활은 행복해요." } },
        { zh: "火柴", pinyin: "huǒ chái", ko: "성냥", pos: "명사", hanja: "화시(火柴) — '火'는 불 화, '柴'는 섶 시.", ex: { zh: "他用火柴点了蜡烛。", pinyin: "tā yòng huǒchái diǎn le làzhú", ko: "그는 성냥으로 초에 불을 붙였어요." } },
        { zh: "伙伴", pinyin: "huǒ bàn", ko: "동반자, 파트너, 동료", pos: "명사", hanja: "화반(伙伴) — '伙'는 동무 화, '伴'은 짝 반.", ex: { zh: "他是我最好的伙伴。", pinyin: "tā shì wǒ zuì hǎo de huǒbàn", ko: "그는 제 가장 좋은 동료예요." } },
        { zh: "机器", pinyin: "jī qì", ko: "기계", pos: "명사", hanja: "기기(機器) — '機'는 틀 기, '器'는 그릇 기.", ex: { zh: "这台机器坏了。", pinyin: "zhè tái jīqì huài le", ko: "이 기계가 고장 났어요." } },
        { zh: "肌肉", pinyin: "jī ròu", ko: "근육", pos: "명사", hanja: "기육(肌肉) — '肌'는 살 기, '肉'은 고기 육.", ex: { zh: "运动可以锻炼肌肉。", pinyin: "yùndòng kěyǐ duànliàn jīròu", ko: "운동은 근육을 단련할 수 있어요." } },
        { zh: "集体", pinyin: "jí tǐ", ko: "집단, 단체", pos: "명사", hanja: "집체(集體) — '集'은 모을 집, '體'는 몸 체.", ex: { zh: "我们要爱护集体。", pinyin: "wǒmen yào àihù jítǐ", ko: "우리는 단체를 아껴야 해요." } },
        { zh: "纪录", pinyin: "jì lù", ko: "(스포츠 등의) 기록", pos: "명사", hanja: "기록(紀錄) — '紀'는 벼리 기, '錄'은 기록할 록. 주로 '최고 기록'을 뜻해요.", ex: { zh: "他打破了世界纪录。", pinyin: "tā dǎpò le shìjiè jìlù", ko: "그는 세계 기록을 깼어요." } },
        { zh: "纪律", pinyin: "jì lǜ", ko: "규율, 기율", pos: "명사", hanja: "기율(紀律) — '紀'는 벼리 기, '律'은 법칙 률.", ex: { zh: "学生要遵守纪律。", pinyin: "xuésheng yào zūnshǒu jìlǜ", ko: "학생은 규율을 지켜야 해요." } },
        { zh: "夹子", pinyin: "jiā zi", ko: "집게, 클립", pos: "명사", hanja: "협자(夾子) — '夾'은 낄 협, '子'는 접미사.", ex: { zh: "用夹子把纸夹好。", pinyin: "yòng jiāzi bǎ zhǐ jiā hǎo", ko: "집게로 종이를 잘 집어요." } },
        { zh: "家庭", pinyin: "jiā tíng", ko: "가정", pos: "명사", hanja: "가정(家庭) — '家'는 집 가, '庭'은 뜰 정.", ex: { zh: "他来自一个幸福的家庭。", pinyin: "tā láizì yí ge xìngfú de jiātíng", ko: "그는 행복한 가정에서 자랐어요." } },
        { zh: "家务", pinyin: "jiā wù", ko: "집안일, 가사", pos: "명사", hanja: "가무(家務) — '家'는 집 가, '務'는 힘쓸 무.", ex: { zh: "我们一起分担家务。", pinyin: "wǒmen yìqǐ fēndān jiāwù", ko: "우리는 집안일을 함께 분담해요." } },
        { zh: "家乡", pinyin: "jiā xiāng", ko: "고향", pos: "명사", hanja: "가향(家鄉) — '家'는 집 가, '鄉'은 시골 향.", ex: { zh: "我很想念家乡。", pinyin: "wǒ hěn xiǎngniàn jiāxiāng", ko: "저는 고향이 많이 그리워요." } },
        { zh: "嘉宾", pinyin: "jiā bīn", ko: "귀빈, (방송) 게스트", pos: "명사", hanja: "가빈(嘉賓) — '嘉'는 아름다울 가, '賓'은 손 빈.", ex: { zh: "今天的嘉宾是一位作家。", pinyin: "jīntiān de jiābīn shì yí wèi zuòjiā", ko: "오늘의 게스트는 작가 한 분이에요." } },
        { zh: "剪刀", pinyin: "jiǎn dāo", ko: "가위", pos: "명사", hanja: "전도(剪刀) — '剪'은 자를 전, '刀'는 칼 도.", ex: { zh: "请把剪刀递给我。", pinyin: "qǐng bǎ jiǎndāo dì gěi wǒ", ko: "가위 좀 건네주세요." } },
        { zh: "简历", pinyin: "jiǎn lì", ko: "이력서", pos: "명사", hanja: "간력(簡歷) — '簡'은 간략할 간, '歷'은 지날 력.", ex: { zh: "请发一份简历给我。", pinyin: "qǐng fā yí fèn jiǎnlì gěi wǒ", ko: "이력서를 한 부 보내 주세요." } },
        { zh: "讲座", pinyin: "jiǎng zuò", ko: "강좌, 강연", pos: "명사", hanja: "강좌(講座) — '講'은 외울 강, '座'는 자리 좌.", ex: { zh: "今天有一场免费讲座。", pinyin: "jīntiān yǒu yì chǎng miǎnfèi jiǎngzuò", ko: "오늘 무료 강연이 하나 있어요." } },
        { zh: "酱油", pinyin: "jiàng yóu", ko: "간장", pos: "명사", hanja: "장유(醬油) — '醬'은 장 장, '油'는 기름 유.", ex: { zh: "炒菜时加点酱油。", pinyin: "chǎocài shí jiā diǎn jiàngyóu", ko: "볶음 요리에 간장을 좀 넣어요." } },
        { zh: "郊区", pinyin: "jiāo qū", ko: "교외, 변두리", pos: "명사", hanja: "교구(郊區) — '郊'는 들 교, '區'는 구역 구.", ex: { zh: "他住在城市的郊区。", pinyin: "tā zhù zài chéngshì de jiāoqū", ko: "그는 도시 교외에 살아요." } },
        { zh: "胶水", pinyin: "jiāo shuǐ", ko: "(액체) 풀, 접착제", pos: "명사", hanja: "교수(膠水) — '膠'는 아교 교, '水'는 물 수.", ex: { zh: "用胶水把照片贴上。", pinyin: "yòng jiāoshuǐ bǎ zhàopiàn tiē shàng", ko: "풀로 사진을 붙여요." } },
        { zh: "角度", pinyin: "jiǎo dù", ko: "각도; 관점", pos: "명사", hanja: "각도(角度) — '角'은 뿔 각, '度'는 법도 도.", ex: { zh: "换个角度看问题。", pinyin: "huàn ge jiǎodù kàn wèntí", ko: "관점을 바꿔서 문제를 봐요." } },
        { zh: "角色", pinyin: "jué sè", ko: "배역, 역할; 등장인물", pos: "명사", hanja: "각색(角色) — '角'은 여기서 'jué'로 읽어요. '배역·역할'.", ex: { zh: "他在电影里演主要角色。", pinyin: "tā zài diànyǐng lǐ yǎn zhǔyào juésè", ko: "그는 영화에서 주연을 맡아요." } },
        { zh: "教材", pinyin: "jiào cái", ko: "교재", pos: "명사", hanja: "교재(教材) — '教'는 가르칠 교, '材'는 재목 재.", ex: { zh: "这本教材很实用。", pinyin: "zhè běn jiàocái hěn shíyòng", ko: "이 교재는 아주 실용적이에요." } },
        { zh: "教练", pinyin: "jiào liàn", ko: "코치, 감독, 트레이너", pos: "명사", hanja: "교련(教練) — '教'는 가르칠 교, '練'은 익힐 련.", ex: { zh: "他是足球队的教练。", pinyin: "tā shì zúqiú duì de jiàoliàn", ko: "그는 축구팀 감독이에요." } },
        { zh: "阶段", pinyin: "jiē duàn", ko: "단계, 시기", pos: "명사", hanja: "계단(階段) — '階'는 섬돌 계, '段'은 구분 단. '단계'를 뜻해요.", ex: { zh: "项目进入了新阶段。", pinyin: "xiàngmù jìnrù le xīn jiēduàn", ko: "프로젝트가 새 단계에 들어섰어요." } },
        { zh: "结构", pinyin: "jié gòu", ko: "구조, 구성", pos: "명사", hanja: "결구(結構) — '結'은 맺을 결, '構'는 얽을 구.", ex: { zh: "这篇文章结构清晰。", pinyin: "zhè piān wénzhāng jiégòu qīngxī", ko: "이 글은 구조가 명확해요." } },
        { zh: "结论", pinyin: "jié lùn", ko: "결론", pos: "명사", hanja: "결론(結論) — '結'은 맺을 결, '論'은 논할 론.", ex: { zh: "我们还没得出结论。", pinyin: "wǒmen hái méi déchū jiélùn", ko: "우리는 아직 결론을 못 냈어요." } },
        { zh: "解说员", pinyin: "jiě shuō yuán", ko: "해설자, 캐스터", pos: "명사", hanja: "해설원(解說員) — '解'는 풀 해, '說'은 말씀 설, '員'은 인원 원.", ex: { zh: "比赛解说员很专业。", pinyin: "bǐsài jiěshuōyuán hěn zhuānyè", ko: "경기 해설자가 아주 전문적이에요." } },
        { zh: "戒指", pinyin: "jiè zhi", ko: "반지", pos: "명사", hanja: "계지(戒指) — '戒'는 경계할 계, '指'는 손가락 지.", ex: { zh: "他送了女朋友一枚戒指。", pinyin: "tā sòng le nǚpéngyou yì méi jièzhi", ko: "그는 여자친구에게 반지를 선물했어요." } },
        { zh: "金属", pinyin: "jīn shǔ", ko: "금속", pos: "명사", hanja: "금속(金屬) — '金'은 쇠 금, '屬'은 무리 속.", ex: { zh: "这个零件是金属做的。", pinyin: "zhège língjiàn shì jīnshǔ zuò de", ko: "이 부품은 금속으로 만들어졌어요." } },
        { zh: "经典", pinyin: "jīng diǎn", ko: "고전; 고전적인, 클래식한", pos: "명사", hanja: "경전(經典) — '經'은 지날 경, '典'은 법 전.", ex: { zh: "这是一部经典电影。", pinyin: "zhè shì yí bù jīngdiǎn diànyǐng", ko: "이건 고전 명작 영화예요." } },
        { zh: "精力", pinyin: "jīng lì", ko: "정력, 기력, 에너지", pos: "명사", hanja: "정력(精力) — '精'은 정할 정, '力'은 힘 력.", ex: { zh: "他工作时精力充沛。", pinyin: "tā gōngzuò shí jīnglì chōngpèi", ko: "그는 일할 때 기력이 넘쳐요." } },
        { zh: "景色", pinyin: "jǐng sè", ko: "경치, 풍경", pos: "명사", hanja: "경색(景色) — '景'은 볕 경, '色'은 빛 색.", ex: { zh: "山上的景色很美。", pinyin: "shān shang de jǐngsè hěn měi", ko: "산 위 경치가 아름다워요." } },
        { zh: "酒吧", pinyin: "jiǔ bā", ko: "술집, 바, 펍", pos: "명사", hanja: "주(酒) + 吧(바). '酒'는 술 주, '吧'는 음역자예요.", ex: { zh: "晚上我们去酒吧坐坐。", pinyin: "wǎnshang wǒmen qù jiǔbā zuòzuo", ko: "저녁에 우리 바에 가서 좀 앉아요." } },
        { zh: "救护车", pinyin: "jiù hù chē", ko: "구급차, 앰뷸런스", pos: "명사", hanja: "구호차(救護車) — '救'는 구원할 구, '護'는 도울 호, '車'는 수레 차.", ex: { zh: "快叫救护车！", pinyin: "kuài jiào jiùhùchē", ko: "빨리 구급차를 불러요!" } },
        { zh: "舅舅", pinyin: "jiù jiu", ko: "외삼촌", pos: "명사", hanja: "구구(舅舅) — '舅'는 외삼촌 구. 어머니의 남자 형제예요.", ex: { zh: "这是我舅舅。", pinyin: "zhè shì wǒ jiùjiu", ko: "이쪽은 제 외삼촌이에요." } },
        { zh: "俱乐部", pinyin: "jù lè bù", ko: "클럽, 동호회", pos: "명사", hanja: "구락부(俱樂部) — 'club'의 음역어예요.", ex: { zh: "他加入了一个读书俱乐部。", pinyin: "tā jiārù le yí ge dúshū jùlèbù", ko: "그는 독서 동호회에 가입했어요." } },
        { zh: "决赛", pinyin: "jué sài", ko: "결승전", pos: "명사", hanja: "결새(決賽) — '決'은 결단할 결, '賽'는 겨룰 새.", ex: { zh: "他进入了决赛。", pinyin: "tā jìnrù le juésài", ko: "그는 결승에 진출했어요." } },
        { zh: "决心", pinyin: "jué xīn", ko: "결심, 결의", pos: "명사", hanja: "결심(決心) — '決'은 결단할 결, '心'은 마음 심.", ex: { zh: "他下定决心要成功。", pinyin: "tā xiàdìng juéxīn yào chénggōng", ko: "그는 성공하겠다고 결심했어요." } },
        { zh: "军事", pinyin: "jūn shì", ko: "군사", pos: "명사", hanja: "군사(軍事) — '軍'은 군사 군, '事'는 일 사.", ex: { zh: "他对军事很感兴趣。", pinyin: "tā duì jūnshì hěn gǎn xìngqù", ko: "그는 군사에 관심이 많아요." } },
        { zh: "卡车", pinyin: "kǎ chē", ko: "트럭, 화물차", pos: "명사", hanja: "卡(카) + 车(차). '卡'는 'truck'의 음역, '車'는 수레 차.", ex: { zh: "卡车装满了货物。", pinyin: "kǎchē zhuāng mǎn le huòwù", ko: "트럭에 화물이 가득 실렸어요." } },
        { zh: "开幕式", pinyin: "kāi mù shì", ko: "개막식", pos: "명사", hanja: "개막식(開幕式) — '開'는 열 개, '幕'은 장막 막, '式'은 법 식.", ex: { zh: "运动会的开幕式很精彩。", pinyin: "yùndònghuì de kāimùshì hěn jīngcǎi", ko: "운동회 개막식이 멋졌어요." } },
        { zh: "客厅", pinyin: "kè tīng", ko: "거실, 응접실", pos: "명사", hanja: "객청(客廳) — '客'은 손 객, '廳'은 관청 청.", ex: { zh: "客厅里有一台电视。", pinyin: "kètīng lǐ yǒu yì tái diànshì", ko: "거실에 텔레비전 한 대가 있어요." } },
        { zh: "课程", pinyin: "kè chéng", ko: "교과 과정, 커리큘럼", pos: "명사", hanja: "과정(課程) — '課'는 공부할 과, '程'은 길 정.", ex: { zh: "这门课程很有意思。", pinyin: "zhè mén kèchéng hěn yǒu yìsi", ko: "이 과목은 정말 재미있어요." } },
        { zh: "空间", pinyin: "kōng jiān", ko: "공간; 여지", pos: "명사", hanja: "공간(空間) — '空'은 빌 공, '間'은 사이 간.", ex: { zh: "这个房间空间很大。", pinyin: "zhège fángjiān kōngjiān hěn dà", ko: "이 방은 공간이 넓어요." } },
        { zh: "口味", pinyin: "kǒu wèi", ko: "입맛, 기호; 맛", pos: "명사", hanja: "구미(口味) — '口'는 입 구, '味'는 맛 미.", ex: { zh: "这道菜很合我的口味。", pinyin: "zhè dào cài hěn hé wǒ de kǒuwèi", ko: "이 요리는 제 입맛에 잘 맞아요." } },
        { zh: "矿泉水", pinyin: "kuàng quán shuǐ", ko: "생수, 미네랄워터", pos: "명사", hanja: "광천수(礦泉水) — '礦'은 쇳돌 광, '泉'은 샘 천, '水'는 물 수.", ex: { zh: "请给我一瓶矿泉水。", pinyin: "qǐng gěi wǒ yì píng kuàngquánshuǐ", ko: "생수 한 병 주세요." } },
        { zh: "蜡烛", pinyin: "là zhú", ko: "초, 양초", pos: "명사", hanja: "납촉(蠟燭) — '蠟'은 밀 랍, '燭'은 촛불 촉.", ex: { zh: "生日蛋糕上插着蜡烛。", pinyin: "shēngrì dàngāo shang chā zhe làzhú", ko: "생일 케이크에 초가 꽂혀 있어요." } },
        { zh: "辣椒", pinyin: "là jiāo", ko: "고추", pos: "명사", hanja: "랄초(辣椒) — '辣'는 매울 랄, '椒'는 산초 초.", ex: { zh: "这道菜放了很多辣椒。", pinyin: "zhè dào cài fàng le hěn duō làjiāo", ko: "이 요리에 고추를 많이 넣었어요." } },
        { zh: "狼", pinyin: "láng", ko: "늑대", pos: "명사", hanja: "랑(狼) — '이리 랑'.", ex: { zh: "森林里有狼。", pinyin: "sēnlín lǐ yǒu láng", ko: "숲속에 늑대가 있어요." } },
        { zh: "劳动", pinyin: "láo dòng", ko: "노동, 일하다", pos: "명사", hanja: "노동(勞動) — '勞'는 일할 로, '動'은 움직일 동.", ex: { zh: "劳动是光荣的。", pinyin: "láodòng shì guāngróng de", ko: "노동은 영예로운 거예요." } },
        { zh: "老百姓", pinyin: "lǎo bǎi xìng", ko: "백성, 서민, 일반 국민", pos: "명사", hanja: "노백성(老百姓) — '百姓'은 백성. '老'는 친근한 접두사예요.", ex: { zh: "政策要为老百姓服务。", pinyin: "zhèngcè yào wèi lǎobǎixìng fúwù", ko: "정책은 서민을 위해야 해요." } },
        { zh: "老板", pinyin: "lǎo bǎn", ko: "사장, 주인", pos: "명사", hanja: "노판(老闆) — '老'는 늙을 로, '板/闆'은 사장. '가게 주인·사장'.", ex: { zh: "他是这家店的老板。", pinyin: "tā shì zhè jiā diàn de lǎobǎn", ko: "그가 이 가게 사장이에요." } },
        { zh: "老鼠", pinyin: "lǎo shǔ", ko: "쥐", pos: "명사", hanja: "노서(老鼠) — '鼠'는 쥐 서. '老'는 접두사예요.", ex: { zh: "家里有一只老鼠。", pinyin: "jiā lǐ yǒu yì zhī lǎoshǔ", ko: "집에 쥐 한 마리가 있어요." } },
        { zh: "姥姥", pinyin: "lǎo lao", ko: "외할머니", pos: "명사", hanja: "노노(姥姥) — 회화체로 어머니의 어머니예요.", ex: { zh: "我小时候和姥姥一起住。", pinyin: "wǒ xiǎoshíhou hé lǎolao yìqǐ zhù", ko: "저는 어릴 때 외할머니와 함께 살았어요." } },
        { zh: "雷", pinyin: "léi", ko: "천둥; 지뢰", pos: "명사", hanja: "뢰(雷) — '우레 뢰'. 사람 성씨가 아니라 '천둥'이에요.", ex: { zh: "外面打雷了。", pinyin: "wàimiàn dǎ léi le", ko: "밖에 천둥이 쳐요." } },
        { zh: "厘米", pinyin: "lí mǐ", ko: "센티미터(cm)", pos: "양사", hanja: "리미(釐米) — '釐'는 다스릴 리, '米'는 쌀 미(미터).", ex: { zh: "这条线有十厘米长。", pinyin: "zhè tiáo xiàn yǒu shí límǐ cháng", ko: "이 선은 10센티미터 길이예요." } },
        { zh: "梨", pinyin: "lí", ko: "배(과일)", pos: "명사", hanja: "리(梨) — '배나무 리'.", ex: { zh: "这个梨很甜。", pinyin: "zhège lí hěn tián", ko: "이 배는 정말 달아요." } },
        { zh: "理由", pinyin: "lǐ yóu", ko: "이유, 까닭", pos: "명사", hanja: "이유(理由) — '理'는 다스릴 리, '由'는 말미암을 유.", ex: { zh: "你没有理由生气。", pinyin: "nǐ méiyǒu lǐyóu shēngqì", ko: "당신이 화낼 이유는 없어요." } },
        { zh: "力量", pinyin: "lì liang", ko: "힘, 역량, 세력", pos: "명사", hanja: "역량(力量) — '力'은 힘 력, '量'은 헤아릴 량.", ex: { zh: "团结就是力量。", pinyin: "tuánjié jiùshì lìliang", ko: "단결이 곧 힘이에요." } },
        { zh: "利息", pinyin: "lì xī", ko: "이자, 이식", pos: "명사", hanja: "이식(利息) — '利'는 이로울 리, '息'은 쉴 식.", ex: { zh: "这笔贷款利息很高。", pinyin: "zhè bǐ dàikuǎn lìxī hěn gāo", ko: "이 대출은 이자가 높아요." } },
        { zh: "利益", pinyin: "lì yì", ko: "이익, 이득", pos: "명사", hanja: "이익(利益) — '利'는 이로울 리, '益'은 더할 익.", ex: { zh: "我们要保护国家利益。", pinyin: "wǒmen yào bǎohù guójiā lìyì", ko: "우리는 국가의 이익을 지켜야 해요." } },
        { zh: "连续剧", pinyin: "lián xù jù", ko: "연속극, 드라마 시리즈", pos: "명사", hanja: "연속극(連續劇) — '連續'은 연속, '劇'은 연극 극.", ex: { zh: "她每天晚上看连续剧。", pinyin: "tā měi tiān wǎnshang kàn liánxùjù", ko: "그녀는 매일 저녁 드라마를 봐요." } },
        { zh: "粮食", pinyin: "liáng shi", ko: "양식, 식량, 곡물", pos: "명사", hanja: "양식(糧食) — '糧'은 양식 량, '食'은 밥 식.", ex: { zh: "我们要节约粮食。", pinyin: "wǒmen yào jiéyuē liángshi", ko: "우리는 식량을 아껴야 해요." } },
        { zh: "铃", pinyin: "líng", ko: "방울, 종, 벨", pos: "명사", hanja: "령(鈴) — '방울 령'.", ex: { zh: "下课铃响了。", pinyin: "xiàkè líng xiǎng le", ko: "수업 종이 울렸어요." } },
        { zh: "零件", pinyin: "líng jiàn", ko: "부품, 부속품", pos: "명사", hanja: "영건(零件) — '零'은 떨어질 령, '件'은 물건 건.", ex: { zh: "这台机器缺一个零件。", pinyin: "zhè tái jīqì quē yí ge língjiàn", ko: "이 기계는 부품 하나가 빠졌어요." } },
        { zh: "零钱", pinyin: "líng qián", ko: "잔돈, 푼돈", pos: "명사", hanja: "영전(零錢) — '零'은 떨어질 령, '錢'은 돈 전.", ex: { zh: "我身上没有零钱。", pinyin: "wǒ shēnshang méiyǒu língqián", ko: "저 잔돈이 없어요." } },
        { zh: "零食", pinyin: "líng shí", ko: "간식, 군것질거리", pos: "명사", hanja: "영식(零食) — '零'은 떨어질 령, '食'은 밥 식.", ex: { zh: "孩子喜欢吃零食。", pinyin: "háizi xǐhuan chī língshí", ko: "아이는 간식 먹는 걸 좋아해요." } },
        { zh: "领域", pinyin: "lǐng yù", ko: "영역, 분야", pos: "명사", hanja: "영역(領域) — '領'은 거느릴 령, '域'은 지경 역.", ex: { zh: "他是这个领域的专家。", pinyin: "tā shì zhège lǐngyù de zhuānjiā", ko: "그는 이 분야의 전문가예요." } },
        { zh: "龙", pinyin: "lóng", ko: "용", pos: "명사", hanja: "룡(龍) — '용 룡'. 성씨가 아니라 전설 속 '용'이에요.", ex: { zh: "中国人认为龙是吉祥的。", pinyin: "Zhōngguó rén rènwéi lóng shì jíxiáng de", ko: "중국인은 용을 상서롭게 여겨요." } },
        { zh: "陆地", pinyin: "lù dì", ko: "육지, 뭍", pos: "명사", hanja: "육지(陸地) — '陸'은 뭍 륙, '地'는 땅 지.", ex: { zh: "船终于靠近了陆地。", pinyin: "chuán zhōngyú kàojìn le lùdì", ko: "배가 마침내 육지에 가까워졌어요." } },
        { zh: "论文", pinyin: "lùn wén", ko: "논문", pos: "명사", hanja: "논문(論文) — '論'은 논할 론, '文'은 글월 문.", ex: { zh: "他正在写毕业论文。", pinyin: "tā zhèngzài xiě bìyè lùnwén", ko: "그는 졸업 논문을 쓰고 있어요." } },
        { zh: "逻辑", pinyin: "luó ji", ko: "논리, 로직", pos: "명사", hanja: "라집(邏輯) — 'logic'의 음역어예요.", ex: { zh: "他说话很有逻辑。", pinyin: "tā shuōhuà hěn yǒu luóji", ko: "그는 말에 논리가 있어요." } },
        { zh: "麦克风", pinyin: "mài kè fēng", ko: "마이크", pos: "명사", hanja: "麦克风 — 'microphone'의 음역어예요.", ex: { zh: "请对着麦克风说话。", pinyin: "qǐng duì zhe màikèfēng shuōhuà", ko: "마이크에 대고 말씀하세요." } },
        { zh: "馒头", pinyin: "mán tou", ko: "찐빵, 만터우", pos: "명사", hanja: "만두(饅頭) — '饅'은 만두 만, '頭'는 머리 두. 소가 없는 찐빵이에요. 한국 '만두'와 달라요!", ex: { zh: "早餐我吃了两个馒头。", pinyin: "zǎocān wǒ chī le liǎng ge mántou", ko: "아침으로 찐빵 두 개를 먹었어요." } },
        { zh: "毛", pinyin: "máo", ko: "털, 깃털; 마오(화폐 단위)", pos: "명사", hanja: "모(毛) — '터럭 모'. 성씨가 아니라 '털'이에요.", ex: { zh: "这件衣服掉毛了。", pinyin: "zhè jiàn yīfu diào máo le", ko: "이 옷에서 털이 빠져요." } },
        { zh: "毛病", pinyin: "máo bìng", ko: "결점, 흠; 고장; 나쁜 버릇", pos: "명사", hanja: "모병(毛病) — '毛'는 터럭 모, '病'은 병 병. '결함·고장'.", ex: { zh: "这台电脑老出毛病。", pinyin: "zhè tái diànnǎo lǎo chū máobìng", ko: "이 컴퓨터는 자꾸 고장이 나요." } },
        { zh: "甲", pinyin: "jiǎ", ko: "첫째, 갑(순서의 첫째); 갑옷", pos: "명사", hanja: "갑(甲) — '갑옷 갑'. 십간(十干)의 첫째라 '갑·1번'을 뜻해요.", ex: { zh: "甲方负责提供材料。", pinyin: "jiǎfāng fùzé tígōng cáiliào", ko: "갑(甲) 측이 자재 제공을 맡아요." } },
        { zh: "桔子", pinyin: "jú zi", ko: "귤", pos: "명사", hanja: "귤자(桔子) — '橘子'로도 써요. '桔/橘'은 귤 귤.", ex: { zh: "桌上有几个桔子。", pinyin: "zhuō shang yǒu jǐ ge júzi", ko: "탁자 위에 귤 몇 개가 있어요." } },
        { zh: "肩膀", pinyin: "jiān bǎng", ko: "어깨", pos: "명사", hanja: "견방(肩膀) — '肩'은 어깨 견, '膀'은 어깨 방.", ex: { zh: "他的肩膀很宽。", pinyin: "tā de jiānbǎng hěn kuān", ko: "그는 어깨가 넓어요." } },
        { zh: "健身房", pinyin: "jiàn shēn fáng", ko: "헬스장, 체육관", pos: "명사", hanja: "건신방(健身房) — '健身'은 헬스, '房'은 방 방.", ex: { zh: "我每周去三次健身房。", pinyin: "wǒ měi zhōu qù sān cì jiànshēnfáng", ko: "저는 매주 세 번 헬스장에 가요." } },
        { zh: "键盘", pinyin: "jiàn pán", ko: "키보드, 건반", pos: "명사", hanja: "건반(鍵盤) — '鍵'은 자물쇠 건, '盤'은 소반 반.", ex: { zh: "这个键盘手感很好。", pinyin: "zhège jiànpán shǒugǎn hěn hǎo", ko: "이 키보드는 타건감이 좋아요." } },
        { zh: "烤鸭", pinyin: "kǎo yā", ko: "오리구이, 카오야", pos: "명사", hanja: "고압(烤鴨) — '烤'는 구울 고, '鴨'은 오리 압.", ex: { zh: "北京烤鸭很有名。", pinyin: "Běijīng kǎoyā hěn yǒumíng", ko: "베이징 오리구이가 유명해요." } },
        { zh: "立方", pinyin: "lì fāng", ko: "세제곱; 입방(立方)", pos: "명사", hanja: "입방(立方) — '立'은 설 립, '方'은 모 방. 수학의 '세제곱'.", ex: { zh: "这个水箱有两立方米。", pinyin: "zhège shuǐxiāng yǒu liǎng lìfāng mǐ", ko: "이 물탱크는 2세제곱미터예요." } },
        { zh: "克", pinyin: "kè", ko: "그램(g); 극복하다", pos: "명사", hanja: "극(克) — '이길 극'. 무게 단위 '그램'으로 자주 써요.", ex: { zh: "这块肉有五百克。", pinyin: "zhè kuài ròu yǒu wǔbǎi kè", ko: "이 고기는 500그램이에요." } },
        { zh: "颗", pinyin: "kē", ko: "알, 개 (작고 둥근 것을 세는 양사)", pos: "양사", hanja: "과(顆) — '낟알 과'. 별·구슬·심장 등에 써요.", ex: { zh: "天上有一颗星星。", pinyin: "tiān shang yǒu yì kē xīngxing", ko: "하늘에 별 하나가 떠 있어요." } },
        { zh: "粒", pinyin: "lì", ko: "알, 톨 (작고 둥근 것을 세는 양사)", pos: "양사", hanja: "립(粒) — '낟알 립'. 쌀·약·콩 등에 써요.", ex: { zh: "他吃了一粒药。", pinyin: "tā chī le yí lì yào", ko: "그는 약 한 알을 먹었어요." } },
        { zh: "类", pinyin: "lèi", ko: "종류, 부류 (양사)", pos: "양사", hanja: "류(類) — '무리 류'.", ex: { zh: "这类问题很常见。", pinyin: "zhè lèi wèntí hěn chángjiàn", ko: "이런 종류의 문제는 흔해요." } },
        { zh: "届", pinyin: "jiè", ko: "회, 기, 차 (정기 행사·졸업 기수를 세는 양사)", pos: "양사", hanja: "계(屆) — '이를 계'. '제○회·○기'를 셀 때 써요.", ex: { zh: "他是这届毕业生。", pinyin: "tā shì zhè jiè bìyèshēng", ko: "그는 이번 기수 졸업생이에요." } },
        { zh: "礼拜天", pinyin: "lǐ bài tiān", ko: "일요일", pos: "명사", hanja: "예배천(禮拜天) — '禮拜'는 예배, '天'은 날 천. 회화체 '일요일'.", ex: { zh: "礼拜天我们去爬山。", pinyin: "lǐbàitiān wǒmen qù páshān", ko: "일요일에 우리 등산 가요." } },
        { zh: "近代", pinyin: "jìn dài", ko: "근대", pos: "명사", hanja: "근대(近代) — '近'은 가까울 근, '代'는 대신할 대.", ex: { zh: "这是近代历史上的大事。", pinyin: "zhè shì jìndài lìshǐ shang de dàshì", ko: "이건 근대사의 큰 사건이에요." } },
        { zh: "尖锐", pinyin: "jiān ruì", ko: "날카롭다, 첨예하다", pos: "형용사", hanja: "첨예(尖銳) — '尖'은 뾰족할 첨, '銳'는 날카로울 예.", ex: { zh: "他提出了尖锐的批评。", pinyin: "tā tíchū le jiānruì de pīpíng", ko: "그는 날카로운 비판을 제기했어요." } },
        { zh: "空闲", pinyin: "kòng xián", ko: "한가하다; 여가, 짬", pos: "명사", hanja: "공한(空閒) — '空'은 빌 공, '閒'은 한가할 한.", ex: { zh: "有空闲的时候我喜欢看书。", pinyin: "yǒu kòngxián de shíhou wǒ xǐhuan kàn shū", ko: "한가할 때 저는 책 읽는 걸 좋아해요." } },
      ],
    },
    {
      name: "HSK5 보강 — 형용사·상태",
      icon: "🔴",
      words: [
        { zh: "基本", pinyin: "jī běn", ko: "기본적인; 기본; 대체로", pos: "형용사", hanja: "기본(基本) — '基'는 터 기, '本'은 근본 본.", ex: { zh: "这是最基本的要求。", pinyin: "zhè shì zuì jīběn de yāoqiú", ko: "이건 가장 기본적인 요구예요." } },
        { zh: "激烈", pinyin: "jī liè", ko: "격렬하다, 치열하다", pos: "형용사", hanja: "격렬(激烈) — '激'은 격할 격, '烈'은 매울 렬.", ex: { zh: "比赛非常激烈。", pinyin: "bǐsài fēicháng jīliè", ko: "경기가 무척 치열해요." } },
        { zh: "寂寞", pinyin: "jì mò", ko: "외롭다, 쓸쓸하다", pos: "형용사", hanja: "적막(寂寞) — '寂'은 고요할 적, '寞'은 쓸쓸할 막.", ex: { zh: "一个人在家很寂寞。", pinyin: "yí ge rén zài jiā hěn jìmò", ko: "혼자 집에 있으면 외로워요." } },
        { zh: "坚决", pinyin: "jiān jué", ko: "단호하다, 결연하다", pos: "형용사", hanja: "견결(堅決) — '堅'은 굳을 견, '決'은 결단할 결.", ex: { zh: "他坚决反对这个计划。", pinyin: "tā jiānjué fǎnduì zhège jìhuà", ko: "그는 이 계획에 단호히 반대해요." } },
        { zh: "坚强", pinyin: "jiān qiáng", ko: "굳세다, 강인하다", pos: "형용사", hanja: "견강(堅強) — '堅'은 굳을 견, '強'은 강할 강.", ex: { zh: "她是个坚强的女人。", pinyin: "tā shì ge jiānqiáng de nǚrén", ko: "그녀는 강인한 여성이에요." } },
        { zh: "艰巨", pinyin: "jiān jù", ko: "어렵고 막중하다, 험난하다", pos: "형용사", hanja: "간거(艱巨) — '艱'은 어려울 간, '巨'는 클 거. '아주 어렵고 큰'.", ex: { zh: "这是一项艰巨的任务。", pinyin: "zhè shì yí xiàng jiānjù de rènwu", ko: "이건 막중한 임무예요." } },
        { zh: "狡猾", pinyin: "jiǎo huá", ko: "교활하다, 간사하다", pos: "형용사", hanja: "교활(狡猾) — '狡'는 교활할 교, '猾'은 교활할 활.", ex: { zh: "那个商人很狡猾。", pinyin: "nàge shāngrén hěn jiǎohuá", ko: "그 상인은 아주 교활해요." } },
        { zh: "结实", pinyin: "jiē shi", ko: "튼튼하다, 견고하다; (몸이) 다부지다", pos: "형용사", hanja: "결실(結實) — 한자는 '결실'이지만 '튼튼하다·단단하다'를 뜻해요. 가짜동족어 주의!", ex: { zh: "这张桌子很结实。", pinyin: "zhè zhāng zhuōzi hěn jiēshi", ko: "이 탁자는 아주 튼튼해요." } },
        { zh: "紧", pinyin: "jǐn", ko: "팽팽하다, 꽉 끼다; 빠듯하다; 긴박하다", pos: "형용사", hanja: "긴(緊) — '긴할 긴'. '紧张(긴장)'의 긴.", ex: { zh: "这条裤子有点紧。", pinyin: "zhè tiáo kùzi yǒudiǎn jǐn", ko: "이 바지가 좀 꽉 껴요." } },
        { zh: "紧急", pinyin: "jǐn jí", ko: "긴급하다, 위급하다", pos: "형용사", hanja: "긴급(緊急) — '緊'은 긴할 긴, '急'은 급할 급.", ex: { zh: "这是紧急情况。", pinyin: "zhè shì jǐnjí qíngkuàng", ko: "이건 긴급 상황이에요." } },
        { zh: "可靠", pinyin: "kě kào", ko: "믿을 만하다, 신뢰할 수 있다", pos: "형용사", hanja: "가고(可靠) — '可'는 옳을 가, '靠'는 기댈 고.", ex: { zh: "他是个可靠的人。", pinyin: "tā shì ge kěkào de rén", ko: "그는 믿을 만한 사람이에요." } },
        { zh: "可怕", pinyin: "kě pà", ko: "무섭다, 두렵다", pos: "형용사", hanja: "가파(可怕) — '可'는 옳을 가, '怕'는 두려울 파.", ex: { zh: "这个故事太可怕了。", pinyin: "zhège gùshi tài kěpà le", ko: "이 이야기는 너무 무서워요." } },
        { zh: "刻苦", pinyin: "kè kǔ", ko: "고생을 참고 애쓰다, 각고하다", pos: "형용사", hanja: "각고(刻苦) — '刻'은 새길 각, '苦'는 쓸 고. '고생을 무릅쓰고 노력하다'.", ex: { zh: "他学习很刻苦。", pinyin: "tā xuéxí hěn kèkǔ", ko: "그는 무척 열심히 공부해요." } },
        { zh: "客观", pinyin: "kè guān", ko: "객관적이다; 객관", pos: "형용사", hanja: "객관(客觀) — '客'은 손 객, '觀'은 볼 관.", ex: { zh: "我们要客观地看问题。", pinyin: "wǒmen yào kèguān de kàn wèntí", ko: "우리는 문제를 객관적으로 봐야 해요." } },
        { zh: "恐怖", pinyin: "kǒng bù", ko: "무섭다, 끔찍하다; 공포", pos: "형용사", hanja: "공포(恐怖) — '恐'은 두려울 공, '怖'는 두려울 포.", ex: { zh: "他喜欢看恐怖电影。", pinyin: "tā xǐhuan kàn kǒngbù diànyǐng", ko: "그는 공포 영화 보는 걸 좋아해요." } },
        { zh: "烂", pinyin: "làn", ko: "물러지다, 썩다; (푹 익어) 무르다; 형편없다", pos: "형용사", hanja: "란(爛) — '문드러질 란'.", ex: { zh: "这些水果已经烂了。", pinyin: "zhèxiē shuǐguǒ yǐjīng làn le", ko: "이 과일들은 이미 썩었어요." } },
        { zh: "良好", pinyin: "liáng hǎo", ko: "양호하다, 좋다", pos: "형용사", hanja: "양호(良好) — '良'은 어질 량, '好'는 좋을 호.", ex: { zh: "他的成绩一直良好。", pinyin: "tā de chéngjì yìzhí liánghǎo", ko: "그의 성적은 줄곧 양호해요." } },
        { zh: "灵活", pinyin: "líng huó", ko: "민첩하다, 융통성 있다, 유연하다", pos: "형용사", hanja: "영활(靈活) — '靈'은 신령 령, '活'은 살 활.", ex: { zh: "他的脑子很灵活。", pinyin: "tā de nǎozi hěn línghuó", ko: "그는 머리가 잘 돌아가요." } },
        { zh: "乐观", pinyin: "lè guān", ko: "낙관적이다, 긍정적이다", pos: "형용사", hanja: "낙관(樂觀) — '樂'은 즐거울 락, '觀'은 볼 관.", ex: { zh: "他对未来很乐观。", pinyin: "tā duì wèilái hěn lèguān", ko: "그는 미래에 대해 낙관적이에요." } },
        { zh: "了不起", pinyin: "liǎo bu qǐ", ko: "대단하다, 굉장하다", pos: "형용사", hanja: "료불기(了不起) — '대단하다·뛰어나다'를 뜻하는 회화 표현이에요.", ex: { zh: "他真了不起！", pinyin: "tā zhēn liǎobuqǐ", ko: "그는 정말 대단해요!" } },
        { zh: "老实", pinyin: "lǎo shi", ko: "성실하다, 정직하다; 얌전하다", pos: "형용사", hanja: "노실(老實) — '老'는 늙을 로, '實'은 열매 실. '정직하다·고지식하다'.", ex: { zh: "他是个老实人。", pinyin: "tā shì ge lǎoshi rén", ko: "그는 정직한 사람이에요." } },
        { zh: "均匀", pinyin: "jūn yún", ko: "고르다, 균등하다", pos: "형용사", hanja: "균균(均勻) — '均'은 고를 균, '勻'은 고를 균.", ex: { zh: "请把颜料涂均匀。", pinyin: "qǐng bǎ yánliào tú jūnyún", ko: "물감을 고르게 칠하세요." } },
        { zh: "尽量", pinyin: "jǐn liàng", ko: "되도록, 가능한 한", pos: "부사", hanja: "진량(儘量) — '儘'은 다할 진, '量'은 헤아릴 량.", ex: { zh: "请尽量早点来。", pinyin: "qǐng jǐnliàng zǎo diǎn lái", ko: "되도록 일찍 와 주세요." } },
        { zh: "开心", pinyin: "kāi xīn", ko: "기쁘다, 즐겁다", pos: "형용사", hanja: "개심(開心) — '開'는 열 개, '心'은 마음 심. '마음이 열려 즐겁다'.", ex: { zh: "今天玩得很开心。", pinyin: "jīntiān wán de hěn kāixīn", ko: "오늘 정말 즐겁게 놀았어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 부사·기타",
      icon: "🔴",
      words: [
        { zh: "急忙", pinyin: "jí máng", ko: "급히, 황급히, 서둘러", pos: "부사", hanja: "급망(急忙) — '急'은 급할 급, '忙'은 바쁠 망.", ex: { zh: "他急忙跑了出去。", pinyin: "tā jímáng pǎo le chūqù", ko: "그는 황급히 뛰쳐나갔어요." } },
        { zh: "简直", pinyin: "jiǎn zhí", ko: "그야말로, 정말로, 완전히", pos: "부사", hanja: "간직(簡直) — '簡'은 간략할 간, '直'은 곧을 직. 과장·강조에 써요.", ex: { zh: "这简直太神奇了。", pinyin: "zhè jiǎnzhí tài shénqí le", ko: "이건 그야말로 너무 신기해요." } },
        { zh: "假如", pinyin: "jiǎ rú", ko: "만약 ~라면", pos: "접속사", hanja: "가여(假如) — '假'는 거짓 가, '如'는 같을 여. '만일'.", ex: { zh: "假如明天下雨，我们就不去了。", pinyin: "jiǎrú míngtiān xià yǔ, wǒmen jiù bú qù le", ko: "만약 내일 비가 오면 우리는 안 가요." } },
        { zh: "居然", pinyin: "jū rán", ko: "뜻밖에, 의외로, 놀랍게도", pos: "부사", hanja: "거연(居然) — '뜻밖에·의외로'. 예상 밖일 때 써요.", ex: { zh: "他居然忘了我的名字。", pinyin: "tā jūrán wàng le wǒ de míngzi", ko: "그가 뜻밖에도 제 이름을 잊었어요." } },
        { zh: "绝对", pinyin: "jué duì", ko: "절대로; 절대적인", pos: "부사", hanja: "절대(絕對) — '絕'은 끊을 절, '對'는 대답할 대.", ex: { zh: "我绝对不会骗你。", pinyin: "wǒ juéduì bú huì piàn nǐ", ko: "저는 절대 당신을 속이지 않아요." } },
        { zh: "看来", pinyin: "kàn lái", ko: "보아하니, ~인 것 같다", pos: "동사", hanja: "간래(看來) — '看'은 볼 간, '來'는 올 래.", ex: { zh: "看来今天要下雨了。", pinyin: "kànlái jīntiān yào xià yǔ le", ko: "보아하니 오늘 비가 오겠어요." } },
        { zh: "立即", pinyin: "lì jí", ko: "즉시, 당장, 곧바로", pos: "부사", hanja: "입즉(立即) — '立'은 설 립, '即'은 곧 즉.", ex: { zh: "他立即作出了反应。", pinyin: "tā lìjí zuòchū le fǎnyìng", ko: "그는 즉시 반응을 보였어요." } },
        { zh: "立刻", pinyin: "lì kè", ko: "즉각, 당장, 곧", pos: "부사", hanja: "입각(立刻) — '立'은 설 립, '刻'은 새길 각.", ex: { zh: "请你立刻过来。", pinyin: "qǐng nǐ lìkè guòlái", ko: "당장 이쪽으로 와 주세요." } },
        { zh: "连忙", pinyin: "lián máng", ko: "얼른, 재빨리, 서둘러", pos: "부사", hanja: "연망(連忙) — '連'은 잇닿을 련, '忙'은 바쁠 망.", ex: { zh: "他连忙道歉。", pinyin: "tā liánmáng dàoqiàn", ko: "그는 얼른 사과했어요." } },
        { zh: "临时", pinyin: "lín shí", ko: "임시의, 잠시의; 그때그때, 즉석에서", pos: "부사", hanja: "임시(臨時) — '臨'은 임할 림, '時'는 때 시.", ex: { zh: "这只是临时安排。", pinyin: "zhè zhǐshì línshí ānpái", ko: "이건 그냥 임시 조치예요." } },
        { zh: "陆续", pinyin: "lù xù", ko: "잇따라, 끊임없이, 계속해서", pos: "부사", hanja: "육속(陸續) — '陸'은 뭍 륙, '續'은 이을 속.", ex: { zh: "客人陆续到了。", pinyin: "kèrén lùxù dào le", ko: "손님들이 잇따라 도착했어요." } },
        { zh: "利用", pinyin: "lì yòng", ko: "이용하다, 활용하다", pos: "동사", hanja: "이용(利用) — '利'는 이로울 리, '用'은 쓸 용.", ex: { zh: "我们要充分利用时间。", pinyin: "wǒmen yào chōngfèn lìyòng shíjiān", ko: "우리는 시간을 충분히 활용해야 해요." } },
        { zh: "领导", pinyin: "lǐng dǎo", ko: "지도하다; 지도자, 상사", pos: "명사", hanja: "영도(領導) — '領'은 거느릴 령, '導'는 인도할 도. '상사·지도자'.", ex: { zh: "他是我们的领导。", pinyin: "tā shì wǒmen de lǐngdǎo", ko: "그는 우리 상사예요." } },
        { zh: "建筑", pinyin: "jiàn zhù", ko: "건축물, 건물; 건축하다", pos: "명사", hanja: "건축(建築) — '建'은 세울 건, '築'은 쌓을 축.", ex: { zh: "这座建筑很古老。", pinyin: "zhè zuò jiànzhù hěn gǔlǎo", ko: "이 건물은 아주 오래됐어요." } },
        { zh: "节", pinyin: "jié", ko: "마디, 절기; 명절; 교시(수업 양사)", pos: "양사", hanja: "절(節) — '마디 절'. 명절·교시·마디를 두루 뜻해요.", ex: { zh: "今天上午有三节课。", pinyin: "jīntiān shàngwǔ yǒu sān jié kè", ko: "오늘 오전에 수업이 세 교시 있어요." } },
        { zh: "劳驾", pinyin: "láo jià", ko: "실례합니다, 죄송하지만 (부탁할 때)", pos: "표현", hanja: "노가(勞駕) — '勞'는 일할 로, '駕'는 멍에 가. 부탁·양해를 구하는 인사말.", ex: { zh: "劳驾，让我过一下。", pinyin: "láojià, ràng wǒ guò yíxià", ko: "실례지만 좀 지나갈게요." } },
      ],
    },
  ],
};
