/**
 * H5 (HSK 5급) 보강 어휘 — 청크 e (200개).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되,
 * 성씨·이체자·다음자 오독은 표준 병음으로 교정했어요.
 */
const themes = {
  themes: [
    {
      name: "HSK5 보강 — 동사",
      icon: "🔴",
      words: [
        { zh: "实行", pinyin: "shí xíng", ko: "실행하다, 시행하다", pos: "동사", hanja: "실행(實行) — 한자 그대로.", ex: { zh: "新政策已经开始实行。", pinyin: "xīn zhèngcè yǐjīng kāishǐ shíxíng", ko: "새 정책이 이미 시행되기 시작했어요." } },
        { zh: "使劲儿", pinyin: "shǐ jìnr", ko: "힘을 쓰다, 힘껏 하다", pos: "동사", hanja: "사경(使勁) — '使'는 부릴 사, '勁'은 힘 경. 儿화 형태예요.", ex: { zh: "大家一起使劲儿推。", pinyin: "dàjiā yìqǐ shǐjìnr tuī", ko: "다 같이 힘껏 밀어요." } },
        { zh: "是否", pinyin: "shì fǒu", ko: "~인지 아닌지, ~여부", pos: "동사", hanja: "시부(是否) — '是'는 옳을 시, '否'는 아닐 부. '~인지 아닌지'.", ex: { zh: "请告诉我你是否能来。", pinyin: "qǐng gàosu wǒ nǐ shìfǒu néng lái", ko: "올 수 있는지 알려 주세요." } },
        { zh: "受伤", pinyin: "shòu shāng", ko: "다치다, 부상을 입다", pos: "동사", hanja: "수상(受傷) — '受'는 받을 수, '傷'은 다칠 상.", ex: { zh: "他在比赛中受伤了。", pinyin: "tā zài bǐsài zhōng shòushāng le", ko: "그는 경기 중에 다쳤어요." } },
        { zh: "输入", pinyin: "shū rù", ko: "입력하다, 들여오다", pos: "동사", hanja: "수입(輸入) — '輸'는 보낼 수, '入'은 들 입. '입력·수입'.", ex: { zh: "请输入你的密码。", pinyin: "qǐng shūrù nǐ de mìmǎ", ko: "비밀번호를 입력하세요." } },
        { zh: "属于", pinyin: "shǔ yú", ko: "~에 속하다", pos: "동사", hanja: "속어(屬於) — '屬'은 무리 속, '於'는 어조사 어.", ex: { zh: "这个问题属于历史。", pinyin: "zhège wèntí shǔyú lìshǐ", ko: "이 문제는 역사에 속해요." } },
        { zh: "摔", pinyin: "shuāi", ko: "넘어지다, 내던지다, 떨어뜨려 깨다", pos: "동사", ex: { zh: "他不小心摔了一跤。", pinyin: "tā bù xiǎoxīn shuāi le yì jiāo", ko: "그는 실수로 한 번 넘어졌어요." } },
        { zh: "甩", pinyin: "shuǎi", ko: "(휙) 흔들다, 내던지다, 떼어 내다", pos: "동사", ex: { zh: "她甩了甩头发。", pinyin: "tā shuǎi le shuǎi tóufa", ko: "그녀는 머리카락을 휙 흔들었어요." } },
        { zh: "说不定", pinyin: "shuō bu dìng", ko: "어쩌면, 아마도 (단정할 수 없다)", pos: "동사", hanja: "설불정(說不定) — '딱 잘라 말할 수 없다 → 어쩌면'.", ex: { zh: "说不定他明天就来了。", pinyin: "shuō bu dìng tā míngtiān jiù lái le", ko: "어쩌면 그가 내일 올지도 몰라요." } },
        { zh: "说服", pinyin: "shuō fú", ko: "설득하다", pos: "동사", hanja: "설복(說服) — '說'은 말씀 설, '服'은 따를 복.", ex: { zh: "我终于说服了他。", pinyin: "wǒ zhōngyú shuōfú le tā", ko: "저는 마침내 그를 설득했어요." } },
        { zh: "撕", pinyin: "sī", ko: "찢다, 뜯다", pos: "동사", ex: { zh: "他把信撕成了两半。", pinyin: "tā bǎ xìn sī chéng le liǎng bàn", ko: "그는 편지를 둘로 찢었어요." } },
        { zh: "损失", pinyin: "sǔn shī", ko: "손실되다; 손실", pos: "동사", hanja: "손실(損失) — 한자 그대로.", ex: { zh: "这次事故损失很大。", pinyin: "zhè cì shìgù sǔnshī hěn dà", ko: "이번 사고로 손실이 커요." } },
        { zh: "缩短", pinyin: "suō duǎn", ko: "단축하다, 줄이다", pos: "동사", hanja: "축단(縮短) — '縮'은 줄일 축, '短'은 짧을 단.", ex: { zh: "我们缩短了会议时间。", pinyin: "wǒmen suōduǎn le huìyì shíjiān", ko: "우리는 회의 시간을 줄였어요." } },
        { zh: "锁", pinyin: "suǒ", ko: "잠그다; 자물쇠", pos: "동사", hanja: "쇄(鎖) — '자물쇠 쇄'.", ex: { zh: "出门别忘了锁门。", pinyin: "chūmén bié wàng le suǒ mén", ko: "나갈 때 문 잠그는 거 잊지 마세요." } },
        { zh: "谈判", pinyin: "tán pàn", ko: "협상하다; 협상, 담판", pos: "동사", hanja: "담판(談判) — '談'은 말씀 담, '判'은 판단할 판.", ex: { zh: "双方正在谈判。", pinyin: "shuāngfāng zhèngzài tánpàn", ko: "양측이 협상 중이에요." } },
        { zh: "烫", pinyin: "tàng", ko: "데다, 데우다; 뜨겁다", pos: "동사", hanja: "탕(燙) — '데울 탕'.", ex: { zh: "小心，汤很烫。", pinyin: "xiǎoxīn, tāng hěn tàng", ko: "조심하세요, 국이 아주 뜨거워요." } },
        { zh: "逃", pinyin: "táo", ko: "도망치다, 달아나다", pos: "동사", hanja: "도(逃) — '도망할 도'.", ex: { zh: "小偷逃走了。", pinyin: "xiǎotōu táozǒu le", ko: "도둑이 도망갔어요." } },
        { zh: "逃避", pinyin: "táo bì", ko: "도피하다, 회피하다", pos: "동사", hanja: "도피(逃避) — '逃'는 도망할 도, '避'는 피할 피.", ex: { zh: "你不能逃避责任。", pinyin: "nǐ bù néng táobì zérèn", ko: "당신은 책임을 피할 수 없어요." } },
        { zh: "提", pinyin: "tí", ko: "들다, 언급하다, 제기하다", pos: "동사", hanja: "제(提) — '끌 제'. '提案(제안)'의 제.", ex: { zh: "他提了一个好建议。", pinyin: "tā tí le yí ge hǎo jiànyì", ko: "그는 좋은 제안을 하나 했어요." } },
        { zh: "提倡", pinyin: "tí chàng", ko: "제창하다, 장려하다", pos: "동사", hanja: "제창(提倡) — '提'는 끌 제, '倡'은 부를 창.", ex: { zh: "学校提倡节约用水。", pinyin: "xuéxiào tíchàng jiéyuē yòng shuǐ", ko: "학교는 물 절약을 권장해요." } },
        { zh: "提问", pinyin: "tí wèn", ko: "질문하다", pos: "동사", hanja: "제문(提問) — '提'는 끌 제, '問'은 물을 문.", ex: { zh: "学生们积极提问。", pinyin: "xuéshēngmen jījí tíwèn", ko: "학생들이 적극적으로 질문해요." } },
        { zh: "体现", pinyin: "tǐ xiàn", ko: "구현하다, 드러내다, 반영하다", pos: "동사", hanja: "체현(體現) — '體'는 몸 체, '現'은 나타날 현.", ex: { zh: "这部作品体现了爱。", pinyin: "zhè bù zuòpǐn tǐxiàn le ài", ko: "이 작품은 사랑을 드러내요." } },
        { zh: "体验", pinyin: "tǐ yàn", ko: "체험하다; 체험", pos: "동사", hanja: "체험(體驗) — '體'는 몸 체, '驗'은 시험할 험.", ex: { zh: "我想体验一下当地生活。", pinyin: "wǒ xiǎng tǐyàn yíxià dāngdì shēnghuó", ko: "현지 생활을 체험해 보고 싶어요." } },
        { zh: "挑战", pinyin: "tiǎo zhàn", ko: "도전하다; 도전", pos: "동사", hanja: "도전(挑戰) — '挑'는 돋울 도, '戰'은 싸울 전.", ex: { zh: "我喜欢挑战自己。", pinyin: "wǒ xǐhuan tiǎozhàn zìjǐ", ko: "저는 저 자신에게 도전하는 걸 좋아해요." } },
        { zh: "统一", pinyin: "tǒng yī", ko: "통일하다; 통일된", pos: "동사", hanja: "통일(統一) — 한자 그대로.", ex: { zh: "我们要统一意见。", pinyin: "wǒmen yào tǒngyī yìjiàn", ko: "우리는 의견을 통일해야 해요." } },
        { zh: "统治", pinyin: "tǒng zhì", ko: "통치하다; 통치", pos: "동사", hanja: "통치(統治) — '統'은 거느릴 통, '治'는 다스릴 치.", ex: { zh: "国王统治这个国家。", pinyin: "guówáng tǒngzhì zhège guójiā", ko: "왕이 이 나라를 통치해요." } },
        { zh: "推辞", pinyin: "tuī cí", ko: "사양하다, 거절하다", pos: "동사", hanja: "추사(推辭) — '推'는 밀 추, '辭'는 말씀 사. '맡지 않으려 사양하다'.", ex: { zh: "他推辞了这个职位。", pinyin: "tā tuīcí le zhège zhíwèi", ko: "그는 이 자리를 고사했어요." } },
        { zh: "推广", pinyin: "tuī guǎng", ko: "널리 보급하다, 확산시키다", pos: "동사", hanja: "추광(推廣) — '推'는 밀 추, '廣'은 넓을 광.", ex: { zh: "公司正在推广新产品。", pinyin: "gōngsī zhèngzài tuīguǎng xīn chǎnpǐn", ko: "회사는 신제품을 보급하고 있어요." } },
        { zh: "推荐", pinyin: "tuī jiàn", ko: "추천하다; 추천", pos: "동사", hanja: "추천(推薦) — '推'는 밀 추, '薦'은 천거할 천.", ex: { zh: "我推荐这家餐厅。", pinyin: "wǒ tuījiàn zhè jiā cāntīng", ko: "저는 이 식당을 추천해요." } },
        { zh: "退", pinyin: "tuì", ko: "물러나다, 후퇴하다, 환불하다", pos: "동사", hanja: "퇴(退) — '물러날 퇴'.", ex: { zh: "这件衣服可以退吗？", pinyin: "zhè jiàn yīfu kěyǐ tuì ma", ko: "이 옷 환불할 수 있나요?" } },
        { zh: "退步", pinyin: "tuì bù", ko: "퇴보하다; 양보, 후퇴", pos: "동사", hanja: "퇴보(退步) — '退'는 물러날 퇴, '步'는 걸음 보.", ex: { zh: "他的成绩退步了。", pinyin: "tā de chéngjì tuìbù le", ko: "그의 성적이 떨어졌어요." } },
        { zh: "退休", pinyin: "tuì xiū", ko: "퇴직하다, 은퇴하다", pos: "동사", hanja: "퇴휴(退休) — '退'는 물러날 퇴, '休'는 쉴 휴.", ex: { zh: "我爸爸去年退休了。", pinyin: "wǒ bàba qùnián tuìxiū le", ko: "우리 아빠는 작년에 은퇴하셨어요." } },
        { zh: "围绕", pinyin: "wéi rào", ko: "둘러싸다, 중심으로 하다", pos: "동사", hanja: "위요(圍繞) — '圍'는 둘러쌀 위, '繞'는 두를 요.", ex: { zh: "讨论围绕这个主题展开。", pinyin: "tǎolùn wéirào zhège zhǔtí zhǎnkāi", ko: "토론이 이 주제를 중심으로 펼쳐져요." } },
        { zh: "违反", pinyin: "wéi fǎn", ko: "위반하다, 어기다", pos: "동사", hanja: "위반(違反) — '違'는 어길 위, '反'은 돌이킬 반.", ex: { zh: "他违反了规定。", pinyin: "tā wéifǎn le guīdìng", ko: "그는 규정을 위반했어요." } },
        { zh: "维护", pinyin: "wéi hù", ko: "지키다, 보호하다, 유지·관리하다", pos: "동사", hanja: "유호(維護) — '維'는 벼리 유, '護'는 보호할 호.", ex: { zh: "我们要维护和平。", pinyin: "wǒmen yào wéihù hépíng", ko: "우리는 평화를 지켜야 해요." } },
        { zh: "委托", pinyin: "wěi tuō", ko: "위탁하다, 맡기다", pos: "동사", hanja: "위탁(委託) — '委'는 맡길 위, '託'은 부탁할 탁.", ex: { zh: "他委托律师处理这件事。", pinyin: "tā wěituō lǜshī chǔlǐ zhè jiàn shì", ko: "그는 변호사에게 이 일을 맡겼어요." } },
        { zh: "闻", pinyin: "wén", ko: "냄새를 맡다; 듣다", pos: "동사", hanja: "문(聞) — '들을 문'. '見聞(견문)'의 문. (성씨 아님)", ex: { zh: "我闻到了花香。", pinyin: "wǒ wén dào le huāxiāng", ko: "저는 꽃향기를 맡았어요." } },
        { zh: "吻", pinyin: "wěn", ko: "입맞춤하다; 입맞춤, 키스", pos: "동사", hanja: "문(吻) — '입술 문'.", ex: { zh: "妈妈吻了吻孩子。", pinyin: "māma wěn le wěn háizi", ko: "엄마가 아이에게 입을 맞췄어요." } },
        { zh: "吸收", pinyin: "xī shōu", ko: "흡수하다, 받아들이다", pos: "동사", hanja: "흡수(吸收) — '吸'은 마실 흡, '收'는 거둘 수.", ex: { zh: "植物吸收阳光。", pinyin: "zhíwù xīshōu yángguāng", ko: "식물은 햇빛을 흡수해요." } },
        { zh: "系", pinyin: "xì", ko: "매다, 묶다; 관계되다", pos: "동사", hanja: "계(係) — '맬 계'. '관계(關係)'의 계.", ex: { zh: "他系上了安全带。", pinyin: "tā jì shàng le ānquándài", ko: "그는 안전벨트를 맸어요." } },
        { zh: "显得", pinyin: "xiǎn de", ko: "~해 보이다, ~한 듯하다", pos: "동사", hanja: "현득(顯得) — '顯'은 나타날 현. '~하게 드러나다'.", ex: { zh: "她今天显得很高兴。", pinyin: "tā jīntiān xiǎnde hěn gāoxìng", ko: "그녀는 오늘 무척 기뻐 보여요." } },
        { zh: "显示", pinyin: "xiǎn shì", ko: "보여 주다, 표시하다, 나타내다", pos: "동사", hanja: "현시(顯示) — '顯'은 나타날 현, '示'는 보일 시.", ex: { zh: "数据显示销量上升了。", pinyin: "shùjù xiǎnshì xiāoliàng shàngshēng le", ko: "데이터는 판매량이 올랐음을 보여 줘요." } },
        { zh: "相处", pinyin: "xiāng chǔ", ko: "함께 지내다, 어울리다", pos: "동사", hanja: "상처(相處) — '相'은 서로 상, '處'는 곳 처(지내다).", ex: { zh: "我们相处得很好。", pinyin: "wǒmen xiāngchǔ de hěn hǎo", ko: "우리는 사이좋게 잘 지내요." } },
        { zh: "享受", pinyin: "xiǎng shòu", ko: "누리다, 즐기다; 향유", pos: "동사", hanja: "향수(享受) — '享'은 누릴 향, '受'는 받을 수.", ex: { zh: "我们在海边享受阳光。", pinyin: "wǒmen zài hǎibiān xiǎngshòu yángguāng", ko: "우리는 바닷가에서 햇볕을 즐겨요." } },
        { zh: "想念", pinyin: "xiǎng niàn", ko: "그리워하다, 보고 싶어 하다", pos: "동사", hanja: "상념(想念) — '想'은 생각 상, '念'은 생각할 념.", ex: { zh: "我很想念家乡。", pinyin: "wǒ hěn xiǎngniàn jiāxiāng", ko: "저는 고향이 무척 그리워요." } },
        { zh: "想象", pinyin: "xiǎng xiàng", ko: "상상하다; 상상", pos: "동사", hanja: "상상(想象) — '想'은 생각 상, '象'은 코끼리·모양 상.", ex: { zh: "我无法想象那个场面。", pinyin: "wǒ wúfǎ xiǎngxiàng nàge chǎngmiàn", ko: "저는 그 장면을 상상할 수 없어요." } },
        { zh: "消费", pinyin: "xiāo fèi", ko: "소비하다; 소비", pos: "동사", hanja: "소비(消費) — '消'는 사라질 소, '費'는 쓸 비.", ex: { zh: "年轻人喜欢消费。", pinyin: "niánqīng rén xǐhuan xiāofèi", ko: "젊은이들은 소비를 즐겨요." } },
        { zh: "消化", pinyin: "xiāo huà", ko: "소화하다; 소화", pos: "동사", hanja: "소화(消化) — '消'는 사라질 소, '化'는 될 화.", ex: { zh: "这些食物很难消化。", pinyin: "zhèxiē shíwù hěn nán xiāohuà", ko: "이 음식들은 소화가 잘 안 돼요." } },
        { zh: "消灭", pinyin: "xiāo miè", ko: "없애다, 소멸시키다, 박멸하다", pos: "동사", hanja: "소멸(消滅) — '消'는 사라질 소, '滅'은 멸할 멸.", ex: { zh: "我们要消灭害虫。", pinyin: "wǒmen yào xiāomiè hàichóng", ko: "우리는 해충을 박멸해야 해요." } },
        { zh: "消失", pinyin: "xiāo shī", ko: "사라지다, 없어지다", pos: "동사", hanja: "소실(消失) — '消'는 사라질 소, '失'은 잃을 실.", ex: { zh: "飞机在云中消失了。", pinyin: "fēijī zài yún zhōng xiāoshī le", ko: "비행기가 구름 속으로 사라졌어요." } },
        { zh: "销售", pinyin: "xiāo shòu", ko: "판매하다; 판매, 영업", pos: "동사", hanja: "소수(銷售) — '銷'은 녹일·팔 소, '售'는 팔 수.", ex: { zh: "这款手机销售得很好。", pinyin: "zhè kuǎn shǒujī xiāoshòu de hěn hǎo", ko: "이 휴대폰은 판매가 잘돼요." } },
        { zh: "歇", pinyin: "xiē", ko: "쉬다, 휴식하다", pos: "동사", hanja: "헐(歇) — '쉴 헐'.", ex: { zh: "我们歇一会儿吧。", pinyin: "wǒmen xiē yíhuìr ba", ko: "우리 잠깐 쉬어요." } },
        { zh: "协调", pinyin: "xié tiáo", ko: "조율하다, 조정하다; 조화롭다", pos: "동사", hanja: "협조(協調) — '協'은 화합할 협, '調'는 고를 조.", ex: { zh: "他负责协调各方意见。", pinyin: "tā fùzé xiétiáo gè fāng yìjiàn", ko: "그는 각측 의견을 조율하는 일을 맡아요." } },
        { zh: "欣赏", pinyin: "xīn shǎng", ko: "감상하다, 마음에 들어 하다", pos: "동사", hanja: "흔상(欣賞) — '欣'은 기쁠 흔, '賞'은 상줄 상. '즐겨 감상하다'.", ex: { zh: "我很欣赏她的才能。", pinyin: "wǒ hěn xīnshǎng tā de cáinéng", ko: "저는 그녀의 재능을 높이 사요." } },
        { zh: "形容", pinyin: "xíng róng", ko: "형용하다, 묘사하다", pos: "동사", hanja: "형용(形容) — '形'은 모양 형, '容'은 얼굴·모습 용.", ex: { zh: "美得无法形容。", pinyin: "měi de wúfǎ xíngróng", ko: "말로 형용할 수 없을 만큼 아름다워요." } },
        { zh: "吓", pinyin: "xià", ko: "놀라게 하다, 겁주다", pos: "동사", hanja: "하(嚇) — '놀랄 하'. (표준 독음 xià)", ex: { zh: "你别吓我。", pinyin: "nǐ bié xià wǒ", ko: "저 놀라게 하지 마세요." } },
        { zh: "下载", pinyin: "xià zǎi", ko: "다운로드하다, 내려받다", pos: "동사", hanja: "하재(下載) — '下'는 아래 하, '載'는 실을 재.", ex: { zh: "我下载了一个应用。", pinyin: "wǒ xiàzǎi le yí ge yìngyòng", ko: "저는 앱을 하나 다운로드했어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 명사·추상",
      icon: "🔴",
      words: [
        { zh: "实话", pinyin: "shí huà", ko: "참말, 솔직한 말", pos: "명사", hanja: "실화(實話) — '實'은 열매 실, '話'는 말씀 화. '실제의 말 → 참말'.", ex: { zh: "说实话，我很累。", pinyin: "shuō shíhuà, wǒ hěn lèi", ko: "솔직히 말하면 저 너무 피곤해요." } },
        { zh: "食物", pinyin: "shí wù", ko: "음식, 식품", pos: "명사", hanja: "식물(食物) — '食'은 밥 식, '物'은 물건 물. '먹을 것'. (식물 plant 아님!)", ex: { zh: "冰箱里有很多食物。", pinyin: "bīngxiāng lǐ yǒu hěn duō shíwù", ko: "냉장고에 음식이 많아요." } },
        { zh: "士兵", pinyin: "shì bīng", ko: "병사, 군인", pos: "명사", hanja: "사병(士兵) — '士'는 선비·군사 사, '兵'은 병사 병.", ex: { zh: "士兵们在训练。", pinyin: "shìbīngmen zài xùnliàn", ko: "병사들이 훈련하고 있어요." } },
        { zh: "事实", pinyin: "shì shí", ko: "사실", pos: "명사", hanja: "사실(事實) — '事'는 일 사, '實'은 열매 실.", ex: { zh: "这是不可否认的事实。", pinyin: "zhè shì bùkě fǒurèn de shìshí", ko: "이건 부정할 수 없는 사실이에요." } },
        { zh: "事物", pinyin: "shì wù", ko: "사물, 것", pos: "명사", hanja: "사물(事物) — '事'는 일 사, '物'은 물건 물.", ex: { zh: "新事物总是吸引人。", pinyin: "xīn shìwù zǒngshì xīyǐn rén", ko: "새로운 것은 늘 사람을 끌어요." } },
        { zh: "试卷", pinyin: "shì juàn", ko: "시험지", pos: "명사", hanja: "시권(試卷) — '試'는 시험할 시, '卷'은 두루마리 권.", ex: { zh: "老师在改试卷。", pinyin: "lǎoshī zài gǎi shìjuàn", ko: "선생님이 시험지를 채점하고 있어요." } },
        { zh: "收据", pinyin: "shōu jù", ko: "영수증", pos: "명사", hanja: "수거(收據) — '收'는 거둘 수, '據'는 근거 거.", ex: { zh: "请把收据给我。", pinyin: "qǐng bǎ shōujù gěi wǒ", ko: "영수증 좀 주세요." } },
        { zh: "收获", pinyin: "shōu huò", ko: "수확; 성과, 소득", pos: "명사", hanja: "수확(收獲) — '收'는 거둘 수, '獲'은 얻을 획. 추상적 '성과'도 돼요.", ex: { zh: "这次旅行收获很大。", pinyin: "zhè cì lǚxíng shōuhuò hěn dà", ko: "이번 여행은 얻은 게 많았어요." } },
        { zh: "手工", pinyin: "shǒu gōng", ko: "수공, 손작업; 수제의", pos: "명사", hanja: "수공(手工) — '手'는 손 수, '工'은 장인 공.", ex: { zh: "这是手工做的。", pinyin: "zhè shì shǒugōng zuò de", ko: "이건 손으로 만든 거예요." } },
        { zh: "手术", pinyin: "shǒu shù", ko: "수술", pos: "명사", hanja: "수술(手術) — '手'는 손 수, '術'은 재주 술.", ex: { zh: "他做了一个手术。", pinyin: "tā zuò le yí ge shǒushù", ko: "그는 수술을 한 번 받았어요." } },
        { zh: "手套", pinyin: "shǒu tào", ko: "장갑", pos: "명사", hanja: "수투(手套) — '手'는 손 수, '套'는 씌울 투.", ex: { zh: "天冷了，戴上手套吧。", pinyin: "tiān lěng le, dàishang shǒutào ba", ko: "날이 추워졌으니 장갑을 끼세요." } },
        { zh: "手续", pinyin: "shǒu xù", ko: "수속, 절차", pos: "명사", hanja: "수속(手續) — '手'는 손 수, '續'은 이을 속.", ex: { zh: "办手续需要半个小时。", pinyin: "bàn shǒuxù xūyào bàn ge xiǎoshí", ko: "수속하는 데 30분이 걸려요." } },
        { zh: "手指", pinyin: "shǒu zhǐ", ko: "손가락", pos: "명사", hanja: "수지(手指) — '手'는 손 수, '指'는 가리킬 지.", ex: { zh: "她的手指又细又长。", pinyin: "tā de shǒuzhǐ yòu xì yòu cháng", ko: "그녀의 손가락은 가늘고 길어요." } },
        { zh: "寿命", pinyin: "shòu mìng", ko: "수명", pos: "명사", hanja: "수명(壽命) — '壽'는 목숨 수, '命'은 목숨 명.", ex: { zh: "这种电池寿命很长。", pinyin: "zhè zhǒng diànchí shòumìng hěn cháng", ko: "이 배터리는 수명이 길어요." } },
        { zh: "书架", pinyin: "shū jià", ko: "책꽂이, 책장", pos: "명사", hanja: "서가(書架) — '書'는 글 서, '架'는 시렁 가.", ex: { zh: "书架上有很多书。", pinyin: "shūjià shang yǒu hěn duō shū", ko: "책장에 책이 많아요." } },
        { zh: "梳子", pinyin: "shū zi", ko: "빗", pos: "명사", hanja: "소자(梳子) — '梳'는 얼레빗 소.", ex: { zh: "我找不到我的梳子。", pinyin: "wǒ zhǎo bu dào wǒ de shūzi", ko: "제 빗을 못 찾겠어요." } },
        { zh: "蔬菜", pinyin: "shū cài", ko: "채소, 야채", pos: "명사", hanja: "소채(蔬菜) — '蔬'는 나물 소, '菜'는 나물 채.", ex: { zh: "多吃蔬菜对身体好。", pinyin: "duō chī shūcài duì shēntǐ hǎo", ko: "채소를 많이 먹으면 몸에 좋아요." } },
        { zh: "鼠标", pinyin: "shǔ biāo", ko: "(컴퓨터) 마우스", pos: "명사", hanja: "서표(鼠標) — '鼠'는 쥐 서, '標'는 표할 표. '쥐 모양 포인터'.", ex: { zh: "我的鼠标坏了。", pinyin: "wǒ de shǔbiāo huài le", ko: "제 마우스가 고장 났어요." } },
        { zh: "数据", pinyin: "shù jù", ko: "데이터, 자료", pos: "명사", hanja: "수거(數據) — '數'는 셀 수, '據'는 근거 거.", ex: { zh: "这些数据很重要。", pinyin: "zhèxiē shùjù hěn zhòngyào", ko: "이 데이터들은 중요해요." } },
        { zh: "数码", pinyin: "shù mǎ", ko: "디지털; 숫자", pos: "명사", hanja: "수마(數碼) — '數'는 셀 수, '碼'는 부호 마.", ex: { zh: "我买了一台数码相机。", pinyin: "wǒ mǎi le yì tái shùmǎ xiàngjī", ko: "저는 디지털 카메라를 한 대 샀어요." } },
        { zh: "双方", pinyin: "shuāng fāng", ko: "쌍방, 양측", pos: "명사", hanja: "쌍방(雙方) — '雙'은 쌍 쌍, '方'은 모 방.", ex: { zh: "双方都很满意。", pinyin: "shuāngfāng dōu hěn mǎnyì", ko: "양측 모두 만족해요." } },
        { zh: "税", pinyin: "shuì", ko: "세금", pos: "명사", hanja: "세(稅) — '구실 세'. '稅金(세금)'의 세.", ex: { zh: "我们每年都要交税。", pinyin: "wǒmen měi nián dōu yào jiāo shuì", ko: "우리는 매년 세금을 내야 해요." } },
        { zh: "丝绸", pinyin: "sī chóu", ko: "비단, 실크", pos: "명사", hanja: "사주(絲綢) — '絲'는 실 사, '綢'는 비단 주.", ex: { zh: "这条丝绸围巾很贵。", pinyin: "zhè tiáo sīchóu wéijīn hěn guì", ko: "이 실크 스카프는 비싸요." } },
        { zh: "私人", pinyin: "sī rén", ko: "개인, 사적인", pos: "명사", hanja: "사인(私人) — '私'는 사사로울 사, '人'은 사람 인.", ex: { zh: "这是我的私人物品。", pinyin: "zhè shì wǒ de sīrén wùpǐn", ko: "이건 제 개인 물품이에요." } },
        { zh: "思想", pinyin: "sī xiǎng", ko: "사상, 생각", pos: "명사", hanja: "사상(思想) — '思'는 생각 사, '想'은 생각 상.", ex: { zh: "他的思想很开放。", pinyin: "tā de sīxiǎng hěn kāifàng", ko: "그의 생각은 매우 열려 있어요." } },
        { zh: "寺庙", pinyin: "sì miào", ko: "절, 사찰", pos: "명사", hanja: "사묘(寺廟) — '寺'는 절 사, '廟'는 사당 묘.", ex: { zh: "山上有一座古老的寺庙。", pinyin: "shān shang yǒu yí zuò gǔlǎo de sìmiào", ko: "산 위에 오래된 절이 하나 있어요." } },
        { zh: "宿舍", pinyin: "sù shè", ko: "기숙사", pos: "명사", hanja: "숙사(宿舍) — '宿'은 잘 숙, '舍'는 집 사.", ex: { zh: "我住在学校宿舍。", pinyin: "wǒ zhù zài xuéxiào sùshè", ko: "저는 학교 기숙사에 살아요." } },
        { zh: "塔", pinyin: "tǎ", ko: "탑", pos: "명사", hanja: "탑(塔) — '탑 탑'.", ex: { zh: "这座塔有一千年历史。", pinyin: "zhè zuò tǎ yǒu yìqiān nián lìshǐ", ko: "이 탑은 천 년 역사를 지녔어요." } },
        { zh: "台阶", pinyin: "tái jiē", ko: "계단, 층계", pos: "명사", hanja: "대계(臺階) — '臺'는 대 대, '階'는 섬돌 계.", ex: { zh: "门前有几级台阶。", pinyin: "mén qián yǒu jǐ jí táijiē", ko: "문 앞에 계단이 몇 단 있어요." } },
        { zh: "太极拳", pinyin: "tài jí quán", ko: "태극권", pos: "명사", hanja: "태극권(太極拳) — '太極'은 태극, '拳'은 주먹 권.", ex: { zh: "爷爷每天打太极拳。", pinyin: "yéye měi tiān dǎ tàijíquán", ko: "할아버지는 매일 태극권을 하세요." } },
        { zh: "太太", pinyin: "tài tai", ko: "부인, 아내; ~여사", pos: "명사", hanja: "태태(太太) — 기혼 여성에 대한 존칭이에요.", ex: { zh: "他太太是医生。", pinyin: "tā tàitai shì yīshēng", ko: "그의 아내는 의사예요." } },
        { zh: "特征", pinyin: "tè zhēng", ko: "특징", pos: "명사", hanja: "특징(特徵) — '特'은 특별할 특, '徵'은 부를·조짐 징.", ex: { zh: "这是它最大的特征。", pinyin: "zhè shì tā zuì dà de tèzhēng", ko: "이게 그것의 가장 큰 특징이에요." } },
        { zh: "提纲", pinyin: "tí gāng", ko: "개요, 요강, 골자", pos: "명사", hanja: "제강(提綱) — '提'는 끌 제, '綱'은 벼리 강. '핵심을 끌어낸 골자'.", ex: { zh: "我先写一个提纲。", pinyin: "wǒ xiān xiě yí ge tígāng", ko: "저는 먼저 개요를 써요." } },
        { zh: "题目", pinyin: "tí mù", ko: "제목, 문제, 주제", pos: "명사", hanja: "제목(題目) — '題'는 제목 제, '目'은 눈 목.", ex: { zh: "这道题目很难。", pinyin: "zhè dào tímù hěn nán", ko: "이 문제는 어려워요." } },
        { zh: "体积", pinyin: "tǐ jī", ko: "부피, 체적", pos: "명사", hanja: "체적(體積) — '體'는 몸 체, '積'은 쌓을 적.", ex: { zh: "这个箱子体积很大。", pinyin: "zhège xiāngzi tǐjī hěn dà", ko: "이 상자는 부피가 커요." } },
        { zh: "天空", pinyin: "tiān kōng", ko: "하늘", pos: "명사", hanja: "천공(天空) — '天'은 하늘 천, '空'은 빌 공.", ex: { zh: "天空中有很多星星。", pinyin: "tiānkōng zhōng yǒu hěn duō xīngxing", ko: "하늘에 별이 많아요." } },
        { zh: "田野", pinyin: "tián yě", ko: "들판, 들녘", pos: "명사", hanja: "전야(田野) — '田'은 밭 전, '野'는 들 야.", ex: { zh: "田野里开满了花。", pinyin: "tiányě lǐ kāimǎn le huā", ko: "들판에 꽃이 가득 피었어요." } },
        { zh: "通讯", pinyin: "tōng xùn", ko: "통신; 통신문", pos: "명사", hanja: "통신(通訊) — '通'은 통할 통, '訊'은 물을 신.", ex: { zh: "现在通讯很方便。", pinyin: "xiànzài tōngxùn hěn fāngbiàn", ko: "요즘은 통신이 아주 편리해요." } },
        { zh: "铜", pinyin: "tóng", ko: "구리, 동", pos: "명사", hanja: "동(銅) — '구리 동'.", ex: { zh: "这个雕像是铜做的。", pinyin: "zhège diāoxiàng shì tóng zuò de", ko: "이 조각상은 구리로 만들었어요." } },
        { zh: "土地", pinyin: "tǔ dì", ko: "토지, 땅", pos: "명사", hanja: "토지(土地) — '土'는 흙 토, '地'는 땅 지.", ex: { zh: "这片土地很肥沃。", pinyin: "zhè piàn tǔdì hěn féiwò", ko: "이 땅은 비옥해요." } },
        { zh: "土豆", pinyin: "tǔ dòu", ko: "감자", pos: "명사", hanja: "토두(土豆) — '土'는 흙 토, '豆'는 콩 두. (대만에서는 땅콩)", ex: { zh: "我喜欢吃土豆。", pinyin: "wǒ xǐhuan chī tǔdòu", ko: "저는 감자 먹는 걸 좋아해요." } },
        { zh: "兔子", pinyin: "tù zi", ko: "토끼", pos: "명사", hanja: "토자(兔子) — '兔'는 토끼 토.", ex: { zh: "兔子跑得很快。", pinyin: "tùzi pǎo de hěn kuài", ko: "토끼는 빨리 달려요." } },
        { zh: "外交", pinyin: "wài jiāo", ko: "외교", pos: "명사", hanja: "외교(外交) — '外'는 바깥 외, '交'는 사귈 교.", ex: { zh: "他在外交部工作。", pinyin: "tā zài wàijiāobù gōngzuò", ko: "그는 외교부에서 일해요." } },
        { zh: "玩具", pinyin: "wán jù", ko: "장난감, 완구", pos: "명사", hanja: "완구(玩具) — '玩'은 희롱할 완, '具'는 갖출 구.", ex: { zh: "孩子有很多玩具。", pinyin: "háizi yǒu hěn duō wánjù", ko: "아이는 장난감이 많아요." } },
        { zh: "王子", pinyin: "wáng zǐ", ko: "왕자", pos: "명사", hanja: "왕자(王子) — '王'은 임금 왕, '子'는 아들 자.", ex: { zh: "童话里有一位王子。", pinyin: "tónghuà lǐ yǒu yí wèi wángzǐ", ko: "동화 속에 왕자가 한 명 있어요." } },
        { zh: "围巾", pinyin: "wéi jīn", ko: "목도리, 스카프", pos: "명사", hanja: "위건(圍巾) — '圍'는 둘러쌀 위, '巾'은 수건 건.", ex: { zh: "她戴着一条红围巾。", pinyin: "tā dài zhe yì tiáo hóng wéijīn", ko: "그녀는 빨간 목도리를 두르고 있어요." } },
        { zh: "卫生间", pinyin: "wèi shēng jiān", ko: "화장실", pos: "명사", hanja: "위생간(衛生間) — '衛生'은 위생, '間'은 사이 간(방).", ex: { zh: "请问卫生间在哪儿？", pinyin: "qǐngwèn wèishēngjiān zài nǎr", ko: "화장실이 어디인지요?" } },
        { zh: "未来", pinyin: "wèi lái", ko: "미래, 장래", pos: "명사", hanja: "미래(未來) — '未'는 아닐 미, '來'는 올 래.", ex: { zh: "我对未来充满希望。", pinyin: "wǒ duì wèilái chōngmǎn xīwàng", ko: "저는 미래에 대해 희망으로 가득해요." } },
        { zh: "位置", pinyin: "wèi zhi", ko: "위치, 자리", pos: "명사", hanja: "위치(位置) — '位'는 자리 위, '置'는 둘 치.", ex: { zh: "请确认你的座位位置。", pinyin: "qǐng quèrèn nǐ de zuòwèi wèizhi", ko: "당신 좌석 위치를 확인하세요." } },
        { zh: "胃", pinyin: "wèi", ko: "위(소화기관)", pos: "명사", hanja: "위(胃) — '밥통 위'.", ex: { zh: "我的胃不太舒服。", pinyin: "wǒ de wèi bú tài shūfu", ko: "제 위가 좀 불편해요." } },
        { zh: "文件", pinyin: "wén jiàn", ko: "문서, 서류, 파일", pos: "명사", hanja: "문건(文件) — '文'은 글월 문, '件'은 물건 건.", ex: { zh: "请把文件发给我。", pinyin: "qǐng bǎ wénjiàn fā gěi wǒ", ko: "그 파일 좀 보내 주세요." } },
        { zh: "文具", pinyin: "wén jù", ko: "문구, 문구류", pos: "명사", hanja: "문구(文具) — '文'은 글월 문, '具'는 갖출 구.", ex: { zh: "我去买一些文具。", pinyin: "wǒ qù mǎi yìxiē wénjù", ko: "저는 문구를 좀 사러 가요." } },
        { zh: "文学", pinyin: "wén xué", ko: "문학", pos: "명사", hanja: "문학(文學) — '文'은 글월 문, '學'은 배울 학.", ex: { zh: "她喜欢中国文学。", pinyin: "tā xǐhuan Zhōngguó wénxué", ko: "그녀는 중국 문학을 좋아해요." } },
        { zh: "卧室", pinyin: "wò shì", ko: "침실", pos: "명사", hanja: "와실(臥室) — '臥'는 누울 와, '室'은 집 실.", ex: { zh: "我的卧室很安静。", pinyin: "wǒ de wòshì hěn ānjìng", ko: "제 침실은 조용해요." } },
        { zh: "屋子", pinyin: "wū zi", ko: "방, 집", pos: "명사", hanja: "옥자(屋子) — '屋'은 집 옥.", ex: { zh: "这间屋子很干净。", pinyin: "zhè jiān wūzi hěn gānjìng", ko: "이 방은 깨끗해요." } },
        { zh: "武器", pinyin: "wǔ qì", ko: "무기", pos: "명사", hanja: "무기(武器) — '武'는 굳셀 무, '器'는 그릇 기.", ex: { zh: "这是一种新武器。", pinyin: "zhè shì yì zhǒng xīn wǔqì", ko: "이건 새로운 무기예요." } },
        { zh: "武术", pinyin: "wǔ shù", ko: "무술", pos: "명사", hanja: "무술(武術) — '武'는 굳셀 무, '術'은 재주 술.", ex: { zh: "他从小学武术。", pinyin: "tā cóngxiǎo xué wǔshù", ko: "그는 어릴 때부터 무술을 배웠어요." } },
        { zh: "物理", pinyin: "wù lǐ", ko: "물리, 물리학", pos: "명사", hanja: "물리(物理) — '物'은 물건 물, '理'는 다스릴 리.", ex: { zh: "物理是我最喜欢的科目。", pinyin: "wùlǐ shì wǒ zuì xǐhuan de kēmù", ko: "물리는 제가 가장 좋아하는 과목이에요." } },
        { zh: "雾", pinyin: "wù", ko: "안개", pos: "명사", hanja: "무(霧) — '안개 무'.", ex: { zh: "今天早上有雾。", pinyin: "jīntiān zǎoshang yǒu wù", ko: "오늘 아침에 안개가 꼈어요." } },
        { zh: "戏剧", pinyin: "xì jù", ko: "연극, 희곡", pos: "명사", hanja: "희극(戲劇) — '戲'는 놀이 희, '劇'은 심할·연극 극. (코미디 아님, '연극·드라마')", ex: { zh: "她喜欢看戏剧。", pinyin: "tā xǐhuan kàn xìjù", ko: "그녀는 연극 보는 걸 좋아해요." } },
        { zh: "系统", pinyin: "xì tǒng", ko: "시스템, 체계", pos: "명사", hanja: "계통(系統) — '系'는 맬 계, '統'은 거느릴 통.", ex: { zh: "这个系统很稳定。", pinyin: "zhège xìtǒng hěn wěndìng", ko: "이 시스템은 안정적이에요." } },
        { zh: "细节", pinyin: "xì jié", ko: "세부 사항, 디테일", pos: "명사", hanja: "세절(細節) — '細'는 가늘 세, '節'은 마디 절.", ex: { zh: "请注意细节。", pinyin: "qǐng zhùyì xìjié", ko: "세부 사항에 주의하세요." } },
        { zh: "项链", pinyin: "xiàng liàn", ko: "목걸이", pos: "명사", hanja: "항련(項鏈) — '項'은 목·항목 항, '鏈'은 쇠사슬 련.", ex: { zh: "她戴着一条金项链。", pinyin: "tā dài zhe yì tiáo jīn xiàngliàn", ko: "그녀는 금목걸이를 하고 있어요." } },
        { zh: "象棋", pinyin: "xiàng qí", ko: "장기 (중국 장기)", pos: "명사", hanja: "상기(象棋) — '象'은 코끼리 상, '棋'는 바둑 기.", ex: { zh: "我和爷爷下象棋。", pinyin: "wǒ hé yéye xià xiàngqí", ko: "저는 할아버지와 장기를 둬요." } },
        { zh: "橡皮", pinyin: "xiàng pí", ko: "지우개; 고무", pos: "명사", hanja: "상피(橡皮) — '橡'은 상수리나무 상, '皮'는 가죽 피.", ex: { zh: "请借我一块橡皮。", pinyin: "qǐng jiè wǒ yí kuài xiàngpí", ko: "지우개 하나 빌려주세요." } },
        { zh: "小吃", pinyin: "xiǎo chī", ko: "간식, 분식, 가벼운 먹거리", pos: "명사", hanja: "소흘(小吃) — '小'는 작을 소, '吃'은 먹을 흘.", ex: { zh: "这条街有很多小吃。", pinyin: "zhè tiáo jiē yǒu hěn duō xiǎochī", ko: "이 거리에는 먹거리가 많아요." } },
        { zh: "小伙子", pinyin: "xiǎo huǒ zi", ko: "젊은이, 총각", pos: "명사", hanja: "소화자(小伙子) — '小伙'는 젊은 남자를 뜻해요.", ex: { zh: "那个小伙子很热情。", pinyin: "nàge xiǎohuǒzi hěn rèqíng", ko: "저 젊은이는 아주 친절해요." } },
        { zh: "小麦", pinyin: "xiǎo mài", ko: "밀", pos: "명사", hanja: "소맥(小麥) — '小'는 작을 소, '麥'은 보리 맥.", ex: { zh: "这片地种着小麦。", pinyin: "zhè piàn dì zhòng zhe xiǎomài", ko: "이 밭에는 밀을 심어 놨어요." } },
        { zh: "小偷", pinyin: "xiǎo tōu", ko: "도둑, 좀도둑", pos: "명사", hanja: "소투(小偷) — '小'는 작을 소, '偷'는 훔칠 투.", ex: { zh: "小偷被警察抓住了。", pinyin: "xiǎotōu bèi jǐngchá zhuāzhù le", ko: "도둑이 경찰에게 잡혔어요." } },
        { zh: "心理", pinyin: "xīn lǐ", ko: "심리", pos: "명사", hanja: "심리(心理) — '心'은 마음 심, '理'는 다스릴 리.", ex: { zh: "她在研究儿童心理。", pinyin: "tā zài yánjiū értóng xīnlǐ", ko: "그녀는 아동 심리를 연구하고 있어요." } },
        { zh: "心脏", pinyin: "xīn zàng", ko: "심장", pos: "명사", hanja: "심장(心臟) — '心'은 마음 심, '臟'은 오장 장.", ex: { zh: "运动对心脏有好处。", pinyin: "yùndòng duì xīnzàng yǒu hǎochù", ko: "운동은 심장에 좋아요." } },
        { zh: "信封", pinyin: "xìn fēng", ko: "봉투, 편지 봉투", pos: "명사", hanja: "신봉(信封) — '信'은 믿을·편지 신, '封'은 봉할 봉.", ex: { zh: "请把信放进信封里。", pinyin: "qǐng bǎ xìn fàngjìn xìnfēng lǐ", ko: "편지를 봉투에 넣으세요." } },
        { zh: "信号", pinyin: "xìn hào", ko: "신호", pos: "명사", hanja: "신호(信號) — '信'은 믿을 신, '號'는 부호 호.", ex: { zh: "这里手机信号不好。", pinyin: "zhèlǐ shǒujī xìnhào bù hǎo", ko: "여기는 휴대폰 신호가 안 좋아요." } },
        { zh: "信息", pinyin: "xìn xī", ko: "정보, 소식, 메시지", pos: "명사", hanja: "신식(信息) — '信'은 믿을 신, '息'은 쉴·소식 식.", ex: { zh: "我收到一条信息。", pinyin: "wǒ shōudào yì tiáo xìnxī", ko: "저는 메시지를 하나 받았어요." } },
        { zh: "行人", pinyin: "xíng rén", ko: "행인, 보행자", pos: "명사", hanja: "행인(行人) — '行'은 다닐 행, '人'은 사람 인.", ex: { zh: "马路上行人很多。", pinyin: "mǎlù shang xíngrén hěn duō", ko: "길에 행인이 많아요." } },
        { zh: "行为", pinyin: "xíng wéi", ko: "행위, 행동", pos: "명사", hanja: "행위(行爲) — '行'은 다닐 행, '爲'는 할 위.", ex: { zh: "这种行为是不对的。", pinyin: "zhè zhǒng xíngwéi shì bú duì de", ko: "이런 행동은 옳지 않아요." } },
        { zh: "行业", pinyin: "háng yè", ko: "업종, 업계, 직종", pos: "명사", hanja: "행업(行業) — '行'은 항렬 항(여기선 háng), '業'은 업 업.", ex: { zh: "他在金融行业工作。", pinyin: "tā zài jīnróng hángyè gōngzuò", ko: "그는 금융 업계에서 일해요." } },
        { zh: "形式", pinyin: "xíng shì", ko: "형식, 형태", pos: "명사", hanja: "형식(形式) — '形'은 모양 형, '式'은 법 식.", ex: { zh: "考试有很多形式。", pinyin: "kǎoshì yǒu hěn duō xíngshì", ko: "시험에는 여러 형식이 있어요." } },
        { zh: "形象", pinyin: "xíng xiàng", ko: "이미지, 형상", pos: "명사", hanja: "형상(形象) — '形'은 모양 형, '象'은 코끼리·모양 상.", ex: { zh: "他很注意自己的形象。", pinyin: "tā hěn zhùyì zìjǐ de xíngxiàng", ko: "그는 자기 이미지에 무척 신경 써요." } },
        { zh: "事先", pinyin: "shì xiān", ko: "사전, 미리", pos: "명사", hanja: "사선(事先) — '일에 앞서 → 사전·미리'.", ex: { zh: "请事先通知我。", pinyin: "qǐng shìxiān tōngzhī wǒ", ko: "미리 알려 주세요." } },
        { zh: "微笑", pinyin: "wēi xiào", ko: "미소; 미소 짓다", pos: "명사", hanja: "미소(微笑) — '微'는 작을 미, '笑'는 웃을 소.", ex: { zh: "她脸上带着微笑。", pinyin: "tā liǎn shang dài zhe wēixiào", ko: "그녀는 얼굴에 미소를 띠고 있어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 형용사·상태",
      icon: "🔴",
      words: [
        { zh: "实用", pinyin: "shí yòng", ko: "실용적이다", pos: "형용사", hanja: "실용(實用) — '實'은 열매 실, '用'은 쓸 용.", ex: { zh: "这个工具很实用。", pinyin: "zhège gōngjù hěn shíyòng", ko: "이 도구는 아주 실용적이에요." } },
        { zh: "舒适", pinyin: "shū shì", ko: "쾌적하다, 편안하다", pos: "형용사", hanja: "서적(舒適) — '舒'는 펼 서, '適'은 맞을 적.", ex: { zh: "这家酒店很舒适。", pinyin: "zhè jiā jiǔdiàn hěn shūshì", ko: "이 호텔은 아주 쾌적해요." } },
        { zh: "熟练", pinyin: "shú liàn", ko: "능숙하다, 숙련되다", pos: "형용사", hanja: "숙련(熟練) — '熟'은 익을 숙, '練'은 익힐 련.", ex: { zh: "她的技术很熟练。", pinyin: "tā de jìshù hěn shúliàn", ko: "그녀의 기술은 아주 능숙해요." } },
        { zh: "碎", pinyin: "suì", ko: "부서지다, 깨지다; 자잘하다", pos: "형용사", hanja: "쇄(碎) — '부술 쇄'.", ex: { zh: "杯子碎了。", pinyin: "bēizi suì le", ko: "컵이 깨졌어요." } },
        { zh: "坦率", pinyin: "tǎn shuài", ko: "솔직하다, 거리낌 없다", pos: "형용사", hanja: "탄솔(坦率) — '坦'은 평탄할 탄, '率'은 거느릴·솔직할 솔.", ex: { zh: "他是个坦率的人。", pinyin: "tā shì ge tǎnshuài de rén", ko: "그는 솔직한 사람이에요." } },
        { zh: "特殊", pinyin: "tè shū", ko: "특수하다, 특별하다", pos: "형용사", hanja: "특수(特殊) — '特'은 특별할 특, '殊'는 다를 수.", ex: { zh: "这是一个特殊的情况。", pinyin: "zhè shì yí ge tèshū de qíngkuàng", ko: "이건 특수한 상황이에요." } },
        { zh: "痛苦", pinyin: "tòng kǔ", ko: "고통스럽다; 고통", pos: "형용사", hanja: "통고(痛苦) — '痛'은 아플 통, '苦'는 쓸 고.", ex: { zh: "失败让他很痛苦。", pinyin: "shībài ràng tā hěn tòngkǔ", ko: "실패는 그를 무척 괴롭게 했어요." } },
        { zh: "痛快", pinyin: "tòng kuài", ko: "통쾌하다, 후련하다, 시원시원하다", pos: "형용사", hanja: "통쾌(痛快) — '痛'은 아플 통, '快'는 빠를·즐거울 쾌.", ex: { zh: "我们玩得很痛快。", pinyin: "wǒmen wán de hěn tòngkuài", ko: "우리는 아주 신나게 놀았어요." } },
        { zh: "透明", pinyin: "tòu míng", ko: "투명하다", pos: "형용사", hanja: "투명(透明) — '透'는 통할 투, '明'은 밝을 명.", ex: { zh: "这块玻璃很透明。", pinyin: "zhè kuài bōli hěn tòumíng", ko: "이 유리는 투명해요." } },
        { zh: "突出", pinyin: "tū chū", ko: "두드러지다, 뛰어나다; 부각시키다", pos: "형용사", hanja: "돌출(突出) — '突'은 갑자기 돌, '出'은 날 출.", ex: { zh: "他的表现很突出。", pinyin: "tā de biǎoxiàn hěn tūchū", ko: "그의 활약은 두드러져요." } },
        { zh: "歪", pinyin: "wāi", ko: "비뚤다, 기울다", pos: "형용사", hanja: "왜(歪) — '비뚤 왜'. ('不正'이 합쳐진 글자)", ex: { zh: "这幅画挂歪了。", pinyin: "zhè fú huà guà wāi le", ko: "이 그림이 비뚤게 걸렸어요." } },
        { zh: "弯", pinyin: "wān", ko: "구부러지다; 굽다; 굽이", pos: "형용사", hanja: "만(彎) — '굽을 만'.", ex: { zh: "前面有个弯。", pinyin: "qiánmiàn yǒu ge wān", ko: "앞에 굽은 길이 있어요." } },
        { zh: "完美", pinyin: "wán měi", ko: "완벽하다", pos: "형용사", hanja: "완미(完美) — '完'은 완전할 완, '美'는 아름다울 미.", ex: { zh: "没有完美的人。", pinyin: "méiyǒu wánměi de rén", ko: "완벽한 사람은 없어요." } },
        { zh: "完善", pinyin: "wán shàn", ko: "완비되다, 잘 갖춰지다; 완비하다", pos: "형용사", hanja: "완선(完善) — '完'은 완전할 완, '善'은 착할 선.", ex: { zh: "这个制度还不够完善。", pinyin: "zhège zhìdù hái búgòu wánshàn", ko: "이 제도는 아직 충분히 정비되지 않았어요." } },
        { zh: "完整", pinyin: "wán zhěng", ko: "완전하다, 온전하다", pos: "형용사", hanja: "완정(完整) — '完'은 완전할 완, '整'은 가지런할 정.", ex: { zh: "这套书很完整。", pinyin: "zhè tào shū hěn wánzhěng", ko: "이 책 세트는 온전히 다 있어요." } },
        { zh: "危害", pinyin: "wēi hài", ko: "해치다, 위해하다; 해악", pos: "동사", hanja: "위해(危害) — '危'는 위태할 위, '害'는 해할 해.", ex: { zh: "吸烟危害健康。", pinyin: "xīyān wēihài jiànkāng", ko: "흡연은 건강을 해쳐요." } },
        { zh: "威胁", pinyin: "wēi xié", ko: "위협하다; 위협", pos: "동사", hanja: "위협(威脅) — '威'는 위엄 위, '脅'은 위협할 협.", ex: { zh: "污染威胁着环境。", pinyin: "wūrǎn wēixié zhe huánjìng", ko: "오염이 환경을 위협하고 있어요." } },
        { zh: "伟大", pinyin: "wěi dà", ko: "위대하다", pos: "형용사", hanja: "위대(偉大) — '偉'는 클 위, '大'는 큰 대.", ex: { zh: "她是一位伟大的科学家。", pinyin: "tā shì yí wèi wěidà de kēxuéjiā", ko: "그녀는 위대한 과학자예요." } },
        { zh: "委屈", pinyin: "wěi qu", ko: "억울하다, 서럽다; 억울하게 하다", pos: "형용사", hanja: "위굴(委屈) — '委'는 맡길 위, '屈'은 굽힐 굴. '부당하게 굽혀져 억울하다'.", ex: { zh: "她觉得很委屈。", pinyin: "tā juéde hěn wěiqu", ko: "그녀는 무척 억울해해요." } },
        { zh: "稳定", pinyin: "wěn dìng", ko: "안정되다; 안정", pos: "형용사", hanja: "온정(穩定) — '穩'은 평온할 온, '定'은 정할 정.", ex: { zh: "他有一份稳定的工作。", pinyin: "tā yǒu yí fèn wěndìng de gōngzuò", ko: "그는 안정적인 직업을 가지고 있어요." } },
        { zh: "无奈", pinyin: "wú nài", ko: "어쩔 수 없다, 부득이하다", pos: "형용사", hanja: "무내(無奈) — '無'는 없을 무, '奈'는 어찌 내. '어찌할 도리가 없다'.", ex: { zh: "我感到很无奈。", pinyin: "wǒ gǎndào hěn wúnài", ko: "저는 어쩔 수 없다고 느껴요." } },
        { zh: "无数", pinyin: "wú shù", ko: "무수하다, 수없이 많다", pos: "형용사", hanja: "무수(無數) — '無'는 없을 무, '數'는 셀 수.", ex: { zh: "天上有无数颗星星。", pinyin: "tiān shàng yǒu wúshù kē xīngxing", ko: "하늘에 무수한 별이 있어요." } },
        { zh: "鲜艳", pinyin: "xiān yàn", ko: "(색이) 산뜻하고 화려하다, 선명하다", pos: "형용사", hanja: "선염(鮮艷) — '鮮'은 고울 선, '艷'은 고울 염.", ex: { zh: "花的颜色很鲜艳。", pinyin: "huā de yánsè hěn xiānyàn", ko: "꽃 색깔이 아주 선명해요." } },
        { zh: "显然", pinyin: "xiǎn rán", ko: "분명하다, 명백하다", pos: "형용사", hanja: "현연(顯然) — '顯'은 나타날 현, '然'은 그럴 연.", ex: { zh: "他显然没听懂。", pinyin: "tā xiǎnrán méi tīngdǒng", ko: "그는 분명히 못 알아들었어요." } },
        { zh: "现实", pinyin: "xiàn shí", ko: "현실; 현실적이다", pos: "명사", hanja: "현실(現實) — '現'은 나타날 현, '實'은 열매 실.", ex: { zh: "我们要面对现实。", pinyin: "wǒmen yào miànduì xiànshí", ko: "우리는 현실을 직시해야 해요." } },
        { zh: "相似", pinyin: "xiāng sì", ko: "비슷하다, 닮다", pos: "형용사", hanja: "상사(相似) — '相'은 서로 상, '似'는 닮을 사.", ex: { zh: "他们俩长得很相似。", pinyin: "tāmen liǎ zhǎng de hěn xiāngsì", ko: "그 둘은 생김새가 비슷해요." } },
        { zh: "相关", pinyin: "xiāng guān", ko: "관련되다, 상관있다", pos: "동사", hanja: "상관(相關) — '相'은 서로 상, '關'은 빗장 관.", ex: { zh: "这两件事相关。", pinyin: "zhè liǎng jiàn shì xiāngguān", ko: "이 두 일은 서로 관련돼 있어요." } },
        { zh: "瞎", pinyin: "xiā", ko: "눈멀다; 함부로, 마구", pos: "형용사", hanja: "할(瞎) — '눈멀 할'. 부사로 '함부로'.", ex: { zh: "别瞎说。", pinyin: "bié xiā shuō", ko: "함부로 말하지 마세요." } },
        { zh: "天真", pinyin: "tiān zhēn", ko: "천진하다, 순진하다", pos: "형용사", hanja: "천진(天眞) — '天'은 하늘 천, '眞'은 참 진.", ex: { zh: "孩子很天真。", pinyin: "háizi hěn tiānzhēn", ko: "아이는 아주 천진해요." } },
        { zh: "疼爱", pinyin: "téng ài", ko: "끔찍이 사랑하다, 애지중지하다", pos: "동사", hanja: "동애(疼愛) — '疼'은 아플·애틋할 동, '愛'는 사랑 애.", ex: { zh: "奶奶很疼爱孙子。", pinyin: "nǎinai hěn téng'ài sūnzi", ko: "할머니는 손자를 끔찍이 아껴요." } },
        { zh: "体贴", pinyin: "tǐ tiē", ko: "자상하다, 살뜰히 챙기다", pos: "형용사", hanja: "체첩(體貼) — '體'는 몸 체, '貼'은 붙을 첩. '남의 마음을 헤아려 살피다'.", ex: { zh: "他对人很体贴。", pinyin: "tā duì rén hěn tǐtiē", ko: "그는 사람을 자상하게 챙겨요." } },
        { zh: "温柔", pinyin: "wēn róu", ko: "부드럽다, 다정하다, 온화하다", pos: "형용사", hanja: "온유(溫柔) — '溫'은 따뜻할 온, '柔'는 부드러울 유.", ex: { zh: "她说话很温柔。", pinyin: "tā shuōhuà hěn wēnróu", ko: "그녀는 말투가 부드러워요." } },
        { zh: "文明", pinyin: "wén míng", ko: "문명; 교양 있다, 예의 바르다", pos: "명사", hanja: "문명(文明) — '文'은 글월 문, '明'은 밝을 명.", ex: { zh: "我们要做文明的人。", pinyin: "wǒmen yào zuò wénmíng de rén", ko: "우리는 교양 있는 사람이 되어야 해요." } },
        { zh: "斜", pinyin: "xié", ko: "비스듬하다, 기울다", pos: "형용사", hanja: "사(斜) — '비낄 사'.", ex: { zh: "他斜着身子坐着。", pinyin: "tā xié zhe shēnzi zuò zhe", ko: "그는 몸을 비스듬히 하고 앉아 있어요." } },
        { zh: "孝顺", pinyin: "xiào shùn", ko: "효도하다; 효성스럽다", pos: "동사", hanja: "효순(孝順) — '孝'는 효도 효, '順'은 순할 순.", ex: { zh: "他很孝顺父母。", pinyin: "tā hěn xiàoshùn fùmǔ", ko: "그는 부모님께 효성스러워요." } },
        { zh: "似的", pinyin: "shì de", ko: "~인 것 같다, ~처럼 (비유)", pos: "조사", hanja: "사적(似的) — '似'는 닮을 사. 비유의 어조사예요.", ex: { zh: "他像孩子似的笑了。", pinyin: "tā xiàng háizi shì de xiào le", ko: "그는 아이처럼 웃었어요." } },
        { zh: "小气", pinyin: "xiǎo qì", ko: "인색하다, 쩨쩨하다, 옹졸하다", pos: "형용사", hanja: "소기(小氣) — '小'는 작을 소, '氣'는 기운 기. '그릇이 작다 → 인색하다'.", ex: { zh: "他这个人很小气。", pinyin: "tā zhège rén hěn xiǎoqì", ko: "그는 무척 인색한 사람이에요." } },
        { zh: "丝毫", pinyin: "sī háo", ko: "조금도, 추호도", pos: "형용사", hanja: "사호(絲毫) — '絲'는 실 사, '毫'는 터럭 호. '실오라기·터럭만큼'.", ex: { zh: "我丝毫不担心。", pinyin: "wǒ sīháo bù dānxīn", ko: "저는 조금도 걱정하지 않아요." } },
      ],
    },
    {
      name: "HSK5 보강 — 부사·기타",
      icon: "🔴",
      words: [
        { zh: "始终", pinyin: "shǐ zhōng", ko: "시종, 줄곧, 처음부터 끝까지", pos: "부사", hanja: "시종(始終) — '始'는 비로소 시, '終'은 마칠 종.", ex: { zh: "他始终没有放弃。", pinyin: "tā shǐzhōng méiyǒu fàngqì", ko: "그는 끝까지 포기하지 않았어요." } },
        { zh: "似乎", pinyin: "sì hū", ko: "마치 ~인 듯하다, ~인 것 같다", pos: "부사", hanja: "사호(似乎) — '似'는 닮을 사, '乎'는 어조사 호.", ex: { zh: "他似乎不太高兴。", pinyin: "tā sìhū bú tài gāoxìng", ko: "그는 별로 기쁘지 않은 것 같아요." } },
        { zh: "随时", pinyin: "suí shí", ko: "수시로, 언제든지", pos: "부사", hanja: "수시(隨時) — '隨'는 따를 수, '時'는 때 시.", ex: { zh: "有问题随时找我。", pinyin: "yǒu wèntí suíshí zhǎo wǒ", ko: "문제가 있으면 언제든 저를 찾으세요." } },
        { zh: "所", pinyin: "suǒ", ko: "(所+동사) ~하는 바; ~곳, ~군데(양사)", pos: "조사", hanja: "소(所) — '바 소'.", ex: { zh: "这是我所知道的。", pinyin: "zhè shì wǒ suǒ zhīdào de", ko: "이게 제가 아는 바예요." } },
        { zh: "所谓", pinyin: "suǒ wèi", ko: "이른바, 소위", pos: "형용사", hanja: "소위(所謂) — '所'는 바 소, '謂'는 이를 위.", ex: { zh: "所谓的成功，因人而异。", pinyin: "suǒwèi de chénggōng, yīn rén ér yì", ko: "이른바 성공이란 사람마다 달라요." } },
        { zh: "特意", pinyin: "tè yì", ko: "일부러, 특별히", pos: "부사", hanja: "특의(特意) — '特'은 특별할 특, '意'는 뜻 의.", ex: { zh: "我特意来看你。", pinyin: "wǒ tèyì lái kàn nǐ", ko: "저는 일부러 당신을 보러 왔어요." } },
        { zh: "通常", pinyin: "tōng cháng", ko: "통상, 보통, 일반적으로", pos: "부사", hanja: "통상(通常) — '通'은 통할 통, '常'은 항상 상.", ex: { zh: "我通常六点起床。", pinyin: "wǒ tōngcháng liù diǎn qǐchuáng", ko: "저는 보통 6시에 일어나요." } },
        { zh: "同时", pinyin: "tóng shí", ko: "동시에; 게다가", pos: "부사", hanja: "동시(同時) — '同'은 같을 동, '時'는 때 시.", ex: { zh: "他们同时到达了。", pinyin: "tāmen tóngshí dàodá le", ko: "그들은 동시에 도착했어요." } },
        { zh: "团", pinyin: "tuán", ko: "단체, 집단; 덩어리; ~덩이(양사)", pos: "명사", hanja: "단(團) — '둥글 단'. '집단(集團)'의 단.", ex: { zh: "我们是一个旅游团。", pinyin: "wǒmen shì yí ge lǚyóu tuán", ko: "우리는 한 여행단이에요." } },
        { zh: "往返", pinyin: "wǎng fǎn", ko: "왕복하다; 왕복", pos: "동사", hanja: "왕반(往返) — '往'은 갈 왕, '返'은 돌이킬 반.", ex: { zh: "我每天往返于公司和家。", pinyin: "wǒ měi tiān wǎngfǎn yú gōngsī hé jiā", ko: "저는 매일 회사와 집을 오가요." } },
        { zh: "未必", pinyin: "wèi bì", ko: "반드시 ~한 것은 아니다", pos: "부사", hanja: "미필(未必) — '未'는 아닐 미, '必'은 반드시 필.", ex: { zh: "贵的未必是好的。", pinyin: "guì de wèibì shì hǎo de", ko: "비싸다고 꼭 좋은 건 아니에요." } },
        { zh: "万一", pinyin: "wàn yī", ko: "만일, 만약; 만일의 경우", pos: "부사", hanja: "만일(萬一) — '萬'은 일만 만, '一'은 한 일.", ex: { zh: "万一下雨怎么办？", pinyin: "wànyī xià yǔ zěnme bàn", ko: "만일 비가 오면 어떡하죠?" } },
        { zh: "问候", pinyin: "wèn hòu", ko: "안부를 묻다, 문안하다", pos: "동사", hanja: "문후(問候) — '問'은 물을 문, '候'는 기후·물을 후.", ex: { zh: "请代我问候你父母。", pinyin: "qǐng dài wǒ wènhòu nǐ fùmǔ", ko: "부모님께 안부 전해 주세요." } },
        { zh: "唯一", pinyin: "wéi yī", ko: "유일하다, 단 하나의", pos: "형용사", hanja: "유일(唯一) — '唯'는 오직 유, '一'은 한 일.", ex: { zh: "这是唯一的办法。", pinyin: "zhè shì wéiyī de bànfǎ", ko: "이게 유일한 방법이에요." } },
        { zh: "尾巴", pinyin: "wěi ba", ko: "꼬리", pos: "명사", hanja: "미파(尾巴) — '尾'는 꼬리 미.", ex: { zh: "小狗摇着尾巴。", pinyin: "xiǎo gǒu yáo zhe wěiba", ko: "강아지가 꼬리를 흔들어요." } },
        { zh: "相当", pinyin: "xiāng dāng", ko: "상당히, 꽤; 상응하다", pos: "부사", hanja: "상당(相當) — '相'은 서로 상, '當'은 마땅 당.", ex: { zh: "今天相当冷。", pinyin: "jīntiān xiāngdāng lěng", ko: "오늘은 꽤 추워요." } },
        { zh: "相对", pinyin: "xiāng duì", ko: "상대적으로; 마주하다", pos: "부사", hanja: "상대(相對) — '相'은 서로 상, '對'는 대할 대.", ex: { zh: "这里相对安静。", pinyin: "zhèlǐ xiāngduì ānjìng", ko: "여기는 상대적으로 조용해요." } },
        { zh: "项", pinyin: "xiàng", ko: "항목; ~가지, ~항(양사)", pos: "양사", hanja: "항(項) — '항목 항'. (성씨 아닌 일반 양사)", ex: { zh: "这项工作很重要。", pinyin: "zhè xiàng gōngzuò hěn zhòngyào", ko: "이 일은 아주 중요해요." } },
        { zh: "县", pinyin: "xiàn", ko: "현 (행정 구역)", pos: "명사", hanja: "현(縣) — '고을 현'.", ex: { zh: "他住在一个小县。", pinyin: "tā zhù zài yí ge xiǎo xiàn", ko: "그는 작은 현에 살아요." } },
        { zh: "现金", pinyin: "xiàn jīn", ko: "현금", pos: "명사", hanja: "현금(現金) — '現'은 나타날 현, '金'은 쇠 금.", ex: { zh: "我身上没带现金。", pinyin: "wǒ shēnshang méi dài xiànjīn", ko: "저는 현금을 안 가지고 있어요." } },
        { zh: "桃", pinyin: "táo", ko: "복숭아", pos: "명사", hanja: "도(桃) — '복숭아 도'. '桃花(도화)'의 도.", ex: { zh: "这个桃很甜。", pinyin: "zhège táo hěn tián", ko: "이 복숭아는 달아요." } },
        { zh: "套", pinyin: "tào", ko: "씌우다; 세트, 벌(양사); 틀, 수법", pos: "양사", hanja: "투(套) — '덮개 투'. '한 세트'를 셀 때 써요.", ex: { zh: "我买了一套衣服。", pinyin: "wǒ mǎi le yí tào yīfu", ko: "저는 옷 한 벌을 샀어요." } },
        { zh: "吐", pinyin: "tǔ", ko: "뱉다, 토하다, 내뱉다", pos: "동사", hanja: "토(吐) — '토할 토'.", ex: { zh: "他难受得想吐。", pinyin: "tā nánshòu de xiǎng tǔ", ko: "그는 토할 만큼 괴로워해요." } },
        { zh: "系领带", pinyin: "xì lǐng dài", ko: "넥타이를 매다", pos: "표현", hanja: "계영대(繫領帶) — '繫'는 맬 계, '領帶'는 넥타이.", ex: { zh: "他正在系领带。", pinyin: "tā zhèngzài jì lǐngdài", ko: "그는 넥타이를 매고 있어요." } },
      ],
    },
  ],
};

export default themes;
