/**
 * H5 (HSK 5급) 보강 어휘 — 청크 A (200개).
 * 표준 HSK5 단어 목록 보강분. 품사·의미별 4개 테마.
 * pinyin은 표준 표기로 교정(성씨·이체자·다음자 오독 정정), ko는 실제 HSK 의미 기준.
 */
const themes = {
  themes: [
    {
      name: "HSK5 보강 — 동사",
      icon: "🔴",
      words: [
        { zh: "爱护", pinyin: "ài hù", ko: "아끼고 보호하다, 소중히 여기다", pos: "동사", hanja: "애호(愛護) — '愛'는 사랑 애, '護'는 도울 호.", ex: { zh: "我们要爱护环境。", pinyin: "wǒmen yào àihù huánjìng", ko: "우리는 환경을 아끼고 보호해야 해요." } },
        { zh: "爱惜", pinyin: "ài xī", ko: "아끼다, 소중히 여기다", pos: "동사", hanja: "애석(愛惜) — '惜'은 아낄 석.", ex: { zh: "我们要爱惜粮食。", pinyin: "wǒmen yào àixī liángshi", ko: "우리는 음식을 아껴야 해요." } },
        { zh: "安慰", pinyin: "ān wèi", ko: "위로하다; 위안", pos: "동사", hanja: "안위(安慰) — '安'은 편안할 안, '慰'는 위로할 위.", ex: { zh: "他安慰了哭泣的孩子。", pinyin: "tā ānwèi le kūqì de háizi", ko: "그는 우는 아이를 위로했어요." } },
        { zh: "安装", pinyin: "ān zhuāng", ko: "설치하다, 장착하다", pos: "동사", hanja: "안장(安裝) — '裝'은 꾸밀 장.", ex: { zh: "工人正在安装空调。", pinyin: "gōngrén zhèngzài ānzhuāng kōngtiáo", ko: "인부가 에어컨을 설치하고 있어요." } },
        { zh: "把握", pinyin: "bǎ wò", ko: "(기회를) 잡다, 파악하다; 확신", pos: "동사", hanja: "파악(把握) — '把'는 잡을 파, '握'는 쥘 악.", ex: { zh: "你要把握机会。", pinyin: "nǐ yào bǎwò jīhuì", ko: "당신은 기회를 잡아야 해요." } },
        { zh: "摆", pinyin: "bǎi", ko: "놓다, 진열하다, 흔들다", pos: "동사", hanja: "파(擺) — '열 파'.", ex: { zh: "桌子上摆着很多书。", pinyin: "zhuōzi shang bǎi zhe hěn duō shū", ko: "탁자 위에 책이 많이 놓여 있어요." } },
        { zh: "办理", pinyin: "bàn lǐ", ko: "처리하다, (수속을) 밟다", pos: "동사", hanja: "판리(辦理) — '辦'은 힘쓸 판, '理'는 다스릴 리.", ex: { zh: "我去银行办理手续。", pinyin: "wǒ qù yínháng bànlǐ shǒuxù", ko: "저는 은행에 가서 수속을 밟아요." } },
        { zh: "包含", pinyin: "bāo hán", ko: "포함하다, 내포하다", pos: "동사", hanja: "포함(包含) — '包'는 쌀 포, '含'은 머금을 함.", ex: { zh: "价格包含服务费。", pinyin: "jiàgé bāohán fúwùfèi", ko: "가격에는 봉사료가 포함돼 있어요." } },
        { zh: "保存", pinyin: "bǎo cún", ko: "보존하다, 저장하다", pos: "동사", hanja: "보존(保存) — '保'는 지킬 보, '存'은 있을 존.", ex: { zh: "请把文件保存好。", pinyin: "qǐng bǎ wénjiàn bǎocún hǎo", ko: "파일을 잘 저장해 두세요." } },
        { zh: "保留", pinyin: "bǎo liú", ko: "보류하다, 남겨 두다, 유지하다", pos: "동사", hanja: "보류(保留) — '留'는 머무를 류.", ex: { zh: "我保留自己的意见。", pinyin: "wǒ bǎoliú zìjǐ de yìjiàn", ko: "저는 제 의견을 보류하겠어요." } },
        { zh: "比如", pinyin: "bǐ rú", ko: "예를 들면, 예컨대", pos: "동사", hanja: "비여(比如) — '比'는 견줄 비, '如'는 같을 여.", ex: { zh: "我喜欢运动，比如跑步。", pinyin: "wǒ xǐhuan yùndòng, bǐrú pǎobù", ko: "저는 운동을 좋아해요, 예를 들면 달리기요." } },
        { zh: "必需", pinyin: "bì xū", ko: "꼭 필요로 하다, 없어서는 안 되다", pos: "동사", hanja: "필수(必需) — '必'은 반드시 필, '需'는 쓰일 수.", ex: { zh: "水是生活必需的。", pinyin: "shuǐ shì shēnghuó bìxū de", ko: "물은 생활에 꼭 필요한 거예요." } },
        { zh: "避免", pinyin: "bì miǎn", ko: "피하다, 모면하다", pos: "동사", hanja: "피면(避免) — '避'는 피할 피, '免'은 면할 면.", ex: { zh: "我们要避免犯同样的错误。", pinyin: "wǒmen yào bìmiǎn fàn tóngyàng de cuòwù", ko: "우리는 같은 실수를 피해야 해요." } },
        { zh: "编辑", pinyin: "biān jí", ko: "편집하다; 편집자", pos: "동사", hanja: "편집(編輯) — '編'은 엮을 편, '輯'은 모을 집.", ex: { zh: "她在编辑这篇文章。", pinyin: "tā zài biānjí zhè piān wénzhāng", ko: "그녀는 이 글을 편집하고 있어요." } },
        { zh: "辩论", pinyin: "biàn lùn", ko: "논쟁하다, 토론하다; 논쟁", pos: "동사", hanja: "변론(辯論) — '辯'은 말 잘할 변, '論'은 논할 론.", ex: { zh: "他们在辩论这个问题。", pinyin: "tāmen zài biànlùn zhège wèntí", ko: "그들은 이 문제를 두고 논쟁하고 있어요." } },
        { zh: "表面", pinyin: "biǎo miàn", ko: "표면; 겉, 외면", pos: "명사", hanja: "표면(表面) — '表'는 겉 표, '面'은 낯 면.", ex: { zh: "表面看起来很平静。", pinyin: "biǎomiàn kàn qǐlái hěn píngjìng", ko: "겉보기에는 평온해 보여요." } },
        { zh: "表明", pinyin: "biǎo míng", ko: "분명히 밝히다, 표명하다", pos: "동사", hanja: "표명(表明) — '明'은 밝을 명.", ex: { zh: "他表明了自己的立场。", pinyin: "tā biǎomíng le zìjǐ de lìchǎng", ko: "그는 자신의 입장을 분명히 밝혔어요." } },
        { zh: "补充", pinyin: "bǔ chōng", ko: "보충하다, 추가하다", pos: "동사", hanja: "보충(補充) — '補'는 기울 보, '充'은 채울 충.", ex: { zh: "我再补充几句。", pinyin: "wǒ zài bǔchōng jǐ jù", ko: "제가 몇 마디 덧붙일게요." } },
        { zh: "采访", pinyin: "cǎi fǎng", ko: "취재하다, 인터뷰하다", pos: "동사", hanja: "채방(採訪) — '採'는 캘 채, '訪'은 찾을 방.", ex: { zh: "记者采访了那位明星。", pinyin: "jìzhě cǎifǎng le nà wèi míngxīng", ko: "기자가 그 스타를 인터뷰했어요." } },
        { zh: "采取", pinyin: "cǎi qǔ", ko: "(조치·방법을) 취하다, 채택하다", pos: "동사", hanja: "채취(採取) — '取'는 가질 취.", ex: { zh: "政府采取了新措施。", pinyin: "zhèngfǔ cǎiqǔ le xīn cuòshī", ko: "정부는 새 조치를 취했어요." } },
        { zh: "踩", pinyin: "cǎi", ko: "(발로) 밟다", pos: "동사", ex: { zh: "别踩草地。", pinyin: "bié cǎi cǎodì", ko: "잔디를 밟지 마세요." } },
        { zh: "参考", pinyin: "cān kǎo", ko: "참고하다; 참고", pos: "동사", hanja: "참고(參考) — '參'은 참여할 참, '考'는 상고할 고.", ex: { zh: "这本书值得参考。", pinyin: "zhè běn shū zhídé cānkǎo", ko: "이 책은 참고할 만해요." } },
        { zh: "参与", pinyin: "cān yù", ko: "참여하다, 가담하다", pos: "동사", hanja: "참여(參與) — '與'는 더불 여.", ex: { zh: "很多人参与了这次活动。", pinyin: "hěn duō rén cānyù le zhè cì huódòng", ko: "많은 사람이 이번 행사에 참여했어요." } },
        { zh: "插", pinyin: "chā", ko: "꽂다, 끼우다, 삽입하다", pos: "동사", hanja: "삽(插) — '꽂을 삽'.", ex: { zh: "她把花插在瓶子里。", pinyin: "tā bǎ huā chā zài píngzi lǐ", ko: "그녀는 꽃을 병에 꽂았어요." } },
        { zh: "拆", pinyin: "chāi", ko: "뜯다, 해체하다, 철거하다", pos: "동사", ex: { zh: "他拆开了包裹。", pinyin: "tā chāikāi le bāoguǒ", ko: "그는 소포를 뜯었어요." } },
        { zh: "产生", pinyin: "chǎn shēng", ko: "생기다, 발생하다, 일으키다", pos: "동사", hanja: "산생(産生) — '産'은 낳을 산, '生'은 날 생.", ex: { zh: "这件事产生了很大影响。", pinyin: "zhè jiàn shì chǎnshēng le hěn dà yǐngxiǎng", ko: "이 일은 큰 영향을 미쳤어요." } },
        { zh: "抄", pinyin: "chāo", ko: "베끼다, 베껴 쓰다, 표절하다", pos: "동사", hanja: "초(抄) — '베낄 초'.", ex: { zh: "请把生词抄一遍。", pinyin: "qǐng bǎ shēngcí chāo yí biàn", ko: "새 단어를 한 번 베껴 쓰세요." } },
        { zh: "成立", pinyin: "chéng lì", ko: "(조직을) 설립하다; (논리가) 성립하다", pos: "동사", hanja: "성립(成立) — '成'은 이룰 성, '立'은 설 립.", ex: { zh: "公司是去年成立的。", pinyin: "gōngsī shì qùnián chénglì de", ko: "회사는 작년에 설립됐어요." } },
        { zh: "成长", pinyin: "chéng zhǎng", ko: "성장하다, 자라다", pos: "동사", hanja: "성장(成長) — '長'은 길/자랄 장.", ex: { zh: "孩子们健康地成长。", pinyin: "háizimen jiànkāng de chéngzhǎng", ko: "아이들이 건강하게 자라요." } },
        { zh: "承认", pinyin: "chéng rèn", ko: "인정하다, 시인하다", pos: "동사", hanja: "승인(承認) — '承'은 이을 승, '認'은 알 인.", ex: { zh: "他承认了自己的错误。", pinyin: "tā chéngrèn le zìjǐ de cuòwù", ko: "그는 자신의 잘못을 인정했어요." } },
        { zh: "承受", pinyin: "chéng shòu", ko: "감당하다, 견디다, 받아들이다", pos: "동사", hanja: "승수(承受) — '受'는 받을 수.", ex: { zh: "他承受了很大的压力。", pinyin: "tā chéngshòu le hěn dà de yālì", ko: "그는 큰 스트레스를 견뎠어요." } },
        { zh: "充满", pinyin: "chōng mǎn", ko: "가득 차다, 충만하다", pos: "동사", hanja: "충만(充滿) — '充'은 채울 충, '滿'은 찰 만.", ex: { zh: "他对未来充满信心。", pinyin: "tā duì wèilái chōngmǎn xìnxīn", ko: "그는 미래에 대한 자신감으로 가득 차 있어요." } },
        { zh: "出版", pinyin: "chū bǎn", ko: "출판하다, 펴내다", pos: "동사", hanja: "출판(出版) — '出'은 날 출, '版'은 판목 판.", ex: { zh: "他的新书已经出版了。", pinyin: "tā de xīn shū yǐjīng chūbǎn le", ko: "그의 새 책이 이미 출판됐어요." } },
        { zh: "出席", pinyin: "chū xí", ko: "출석하다, 참석하다", pos: "동사", hanja: "출석(出席) — '席'은 자리 석.", ex: { zh: "他出席了今天的会议。", pinyin: "tā chūxí le jīntiān de huìyì", ko: "그는 오늘 회의에 참석했어요." } },
        { zh: "除", pinyin: "chú", ko: "없애다, 제거하다; 나누다", pos: "동사", hanja: "제(除) — '덜 제'.", ex: { zh: "六除以二等于三。", pinyin: "liù chú yǐ èr děngyú sān", ko: "6 나누기 2는 3이에요." } },
        { zh: "传播", pinyin: "chuán bō", ko: "퍼뜨리다, 전파하다", pos: "동사", hanja: "전파(傳播) — '傳'은 전할 전, '播'는 뿌릴 파.", ex: { zh: "网络传播信息很快。", pinyin: "wǎngluò chuánbō xìnxī hěn kuài", ko: "인터넷은 정보를 빠르게 퍼뜨려요." } },
        { zh: "传递", pinyin: "chuán dì", ko: "전달하다, 전하다", pos: "동사", hanja: "전체(傳遞) — '遞'는 갈마들 체.", ex: { zh: "请把这个消息传递给大家。", pinyin: "qǐng bǎ zhège xiāoxi chuándì gěi dàjiā", ko: "이 소식을 모두에게 전해 주세요." } },
        { zh: "传染", pinyin: "chuán rǎn", ko: "전염되다, 옮기다", pos: "동사", hanja: "전염(傳染) — '染'은 물들 염.", ex: { zh: "这种病会传染。", pinyin: "zhè zhǒng bìng huì chuánrǎn", ko: "이 병은 전염될 수 있어요." } },
        { zh: "闯", pinyin: "chuǎng", ko: "뛰어들다, 돌진하다, 부딪쳐 나아가다", pos: "동사", ex: { zh: "他闯红灯了。", pinyin: "tā chuǎng hóngdēng le", ko: "그는 빨간 신호를 무시하고 지나갔어요." } },
        { zh: "吹", pinyin: "chuī", ko: "(바람·입으로) 불다; 허풍 떨다", pos: "동사", ex: { zh: "风把帽子吹走了。", pinyin: "fēng bǎ màozi chuī zǒu le", ko: "바람이 모자를 날려 버렸어요." } },
        { zh: "辞职", pinyin: "cí zhí", ko: "사직하다, 일을 그만두다", pos: "동사", hanja: "사직(辭職) — '辭'는 말씀/사퇴할 사, '職'은 직분 직.", ex: { zh: "他上个月辞职了。", pinyin: "tā shàng ge yuè cízhí le", ko: "그는 지난달에 사직했어요." } },
        { zh: "促使", pinyin: "cù shǐ", ko: "~하도록 촉진하다, 부추기다", pos: "동사", hanja: "촉사(促使) — '促'은 재촉할 촉, '使'는 하여금 사.", ex: { zh: "这件事促使我改变想法。", pinyin: "zhè jiàn shì cùshǐ wǒ gǎibiàn xiǎngfǎ", ko: "이 일은 제가 생각을 바꾸게 만들었어요." } },
        { zh: "催", pinyin: "cuī", ko: "재촉하다, 독촉하다", pos: "동사", hanja: "최(催) — '재촉할 최'.", ex: { zh: "妈妈催我快点出门。", pinyin: "māma cuī wǒ kuài diǎn chūmén", ko: "엄마가 빨리 나가라고 재촉해요." } },
        { zh: "存", pinyin: "cún", ko: "저장하다, 보관하다, 예금하다", pos: "동사", hanja: "존(存) — '있을 존'.", ex: { zh: "我每个月存一点钱。", pinyin: "wǒ měi ge yuè cún yìdiǎn qián", ko: "저는 매달 돈을 조금씩 저축해요." } },
        { zh: "存在", pinyin: "cún zài", ko: "존재하다; 존재", pos: "동사", hanja: "존재(存在) — '在'는 있을 재.", ex: { zh: "这个问题确实存在。", pinyin: "zhège wèntí quèshí cúnzài", ko: "이 문제는 확실히 존재해요." } },
        { zh: "达到", pinyin: "dá dào", ko: "달성하다, 도달하다, 이르다", pos: "동사", hanja: "달도(達到) — '達'은 통달할 달, '到'는 이를 도.", ex: { zh: "我们达到了目标。", pinyin: "wǒmen dádào le mùbiāo", ko: "우리는 목표를 달성했어요." } },
        { zh: "打工", pinyin: "dǎ gōng", ko: "아르바이트하다, 일하다", pos: "동사", hanja: "타공(打工) — '工'은 장인 공.", ex: { zh: "他周末在咖啡店打工。", pinyin: "tā zhōumò zài kāfēidiàn dǎgōng", ko: "그는 주말에 카페에서 아르바이트해요." } },
        { zh: "打交道", pinyin: "dǎ jiāo dào", ko: "교제하다, 거래하다, 왕래하다", pos: "동사", hanja: "타교도(打交道) — '交道'는 교류·왕래.", ex: { zh: "我常和外国人打交道。", pinyin: "wǒ cháng hé wàiguórén dǎ jiāodào", ko: "저는 외국인과 자주 왕래해요." } },
        { zh: "打听", pinyin: "dǎ ting", ko: "물어보다, 알아보다, 수소문하다", pos: "동사", ex: { zh: "我打听一下去车站的路。", pinyin: "wǒ dǎting yíxià qù chēzhàn de lù", ko: "역으로 가는 길을 좀 알아볼게요." } },
        { zh: "担任", pinyin: "dān rèn", ko: "(직책을) 맡다, 담임하다", pos: "동사", hanja: "담임(擔任) — '擔'은 멜 담, '任'은 맡길 임.", ex: { zh: "他担任经理。", pinyin: "tā dānrèn jīnglǐ", ko: "그는 매니저를 맡고 있어요." } },
        { zh: "耽误", pinyin: "dān wu", ko: "(시간을) 지체시키다, 그르치다", pos: "동사", hanja: "탐오(耽誤) — '耽'은 즐길/지체할 탐, '誤'는 그르칠 오.", ex: { zh: "堵车耽误了我半个小时。", pinyin: "dǔchē dānwù le wǒ bàn ge xiǎoshí", ko: "차가 막혀 30분을 허비했어요." } },
        { zh: "挡", pinyin: "dǎng", ko: "막다, 가리다, 차단하다", pos: "동사", ex: { zh: "大树挡住了阳光。", pinyin: "dà shù dǎng zhù le yángguāng", ko: "큰 나무가 햇빛을 가렸어요." } },
        { zh: "导演", pinyin: "dǎo yǎn", ko: "감독하다; (영화) 감독", pos: "동사", hanja: "도연(導演) — '導'는 인도할 도, '演'은 펼 연.", ex: { zh: "这部电影是他导演的。", pinyin: "zhè bù diànyǐng shì tā dǎoyǎn de", ko: "이 영화는 그가 감독한 거예요." } },
        { zh: "导致", pinyin: "dǎo zhì", ko: "(나쁜 결과를) 초래하다, 야기하다", pos: "동사", hanja: "도치(導致) — '致'는 이를 치.", ex: { zh: "粗心导致了这次失败。", pinyin: "cūxīn dǎozhì le zhè cì shībài", ko: "부주의가 이번 실패를 초래했어요." } },
        { zh: "到达", pinyin: "dào dá", ko: "도착하다, 도달하다", pos: "동사", hanja: "도달(到達) — '到'는 이를 도, '達'은 통달할 달.", ex: { zh: "火车准时到达了。", pinyin: "huǒchē zhǔnshí dàodá le", ko: "기차가 정시에 도착했어요." } },
        { zh: "登记", pinyin: "dēng jì", ko: "등록하다, 등기하다", pos: "동사", hanja: "등기(登記) — '登'은 오를 등, '記'는 기록할 기.", ex: { zh: "请在前台登记。", pinyin: "qǐng zài qiántái dēngjì", ko: "프런트에서 등록해 주세요." } },
        { zh: "等待", pinyin: "děng dài", ko: "기다리다 (서면어)", pos: "동사", hanja: "등대(等待) — '等'은 무리/기다릴 등, '待'는 기다릴 대.", ex: { zh: "我们在等待结果。", pinyin: "wǒmen zài děngdài jiéguǒ", ko: "우리는 결과를 기다리고 있어요." } },
        { zh: "等候", pinyin: "děng hòu", ko: "기다리다 (정중·서면어)", pos: "동사", hanja: "등후(等候) — '候'는 기다릴 후.", ex: { zh: "请在外面等候。", pinyin: "qǐng zài wàimiàn děnghòu", ko: "밖에서 기다려 주세요." } },
        { zh: "等于", pinyin: "děng yú", ko: "~과 같다, ~인 셈이다", pos: "동사", hanja: "등어(等於) — '於'는 어조사 어.", ex: { zh: "二加三等于五。", pinyin: "èr jiā sān děngyú wǔ", ko: "2 더하기 3은 5예요." } },
        { zh: "递", pinyin: "dì", ko: "건네다, 전하다", pos: "동사", hanja: "체(遞) — '갈마들 체'.", ex: { zh: "请把书递给我。", pinyin: "qǐng bǎ shū dì gěi wǒ", ko: "책을 저에게 건네주세요." } },
        { zh: "点头", pinyin: "diǎn tóu", ko: "고개를 끄덕이다", pos: "동사", hanja: "점두(點頭) — '點'은 점 점, '頭'는 머리 두.", ex: { zh: "他点头表示同意。", pinyin: "tā diǎntóu biǎoshì tóngyì", ko: "그는 고개를 끄덕여 동의했어요." } },
        { zh: "包裹", pinyin: "bāo guǒ", ko: "소포; 싸다, 감싸다", pos: "명사", hanja: "포과(包裹) — '包'는 쌀 포, '裹'는 쌀 과.", ex: { zh: "我收到了一个包裹。", pinyin: "wǒ shōudào le yí ge bāoguǒ", ko: "저는 소포 하나를 받았어요." } },
        { zh: "持续", pinyin: "chí xù", ko: "지속하다, 계속되다", pos: "동사", hanja: "지속(持續) — '持'는 가질 지, '續'은 이을 속.", ex: { zh: "高温天气持续了一周。", pinyin: "gāowēn tiānqì chíxù le yì zhōu", ko: "폭염이 일주일 동안 계속됐어요." } },
        { zh: "处理", pinyin: "chǔ lǐ", ko: "처리하다, 다루다", pos: "동사", hanja: "처리(處理) — '處'는 곳/처리할 처, '理'는 다스릴 리.", ex: { zh: "这件事我会处理好。", pinyin: "zhè jiàn shì wǒ huì chǔlǐ hǎo", ko: "이 일은 제가 잘 처리할게요." } },
        { zh: "从事", pinyin: "cóng shì", ko: "종사하다, (일에) 몸담다", pos: "동사", hanja: "종사(從事) — '從'은 좇을 종, '事'는 일 사.", ex: { zh: "他从事教育工作。", pinyin: "tā cóngshì jiàoyù gōngzuò", ko: "그는 교육 일에 종사해요." } },
        { zh: "刺激", pinyin: "cì jī", ko: "자극하다; 자극, 스릴", pos: "동사", hanja: "자격(刺激) — '刺'는 찌를 자, '激'는 격할 격.", ex: { zh: "这个消息刺激了他。", pinyin: "zhège xiāoxi cìjī le tā", ko: "이 소식이 그를 자극했어요." } },
        { zh: "保险", pinyin: "bǎo xiǎn", ko: "보험; 안전하다", pos: "명사", hanja: "보험(保險) — '保'는 지킬 보, '險'은 험할 험.", ex: { zh: "我买了一份保险。", pinyin: "wǒ mǎi le yí fèn bǎoxiǎn", ko: "저는 보험을 하나 들었어요." } },
        { zh: "称呼", pinyin: "chēng hu", ko: "부르다, 호칭하다; 호칭", pos: "동사", hanja: "칭호(稱呼) — '稱'은 일컬을 칭, '呼'는 부를 호.", ex: { zh: "我该怎么称呼您？", pinyin: "wǒ gāi zěnme chēnghu nín", ko: "당신을 어떻게 불러야 할까요?" } },
        { zh: "称赞", pinyin: "chēng zàn", ko: "칭찬하다, 찬양하다", pos: "동사", hanja: "칭찬(稱讚) — '讚'은 기릴 찬.", ex: { zh: "老师称赞了他的努力。", pinyin: "lǎoshī chēngzàn le tā de nǔlì", ko: "선생님이 그의 노력을 칭찬했어요." } },
        { zh: "操心", pinyin: "cāo xīn", ko: "신경 쓰다, 마음 쓰다, 걱정하다", pos: "동사", hanja: "조심(操心) — 한자는 '조심'이지만 '마음을 쓰다·애태우다'를 뜻해요. 가짜동족어 주의!", ex: { zh: "妈妈为我们操了不少心。", pinyin: "māma wèi wǒmen cāo le bùshǎo xīn", ko: "엄마는 우리 때문에 마음을 많이 쓰셨어요." } },
        { zh: "传说", pinyin: "chuán shuō", ko: "전설; 전해 내려오다", pos: "명사", hanja: "전설(傳說) — '傳'은 전할 전, '說'은 말씀 설.", ex: { zh: "这是一个古老的传说。", pinyin: "zhè shì yí ge gǔlǎo de chuánshuō", ko: "이것은 오래된 전설이에요." } },
      ],
    },
    {
      name: "HSK5 보강 — 명사·추상",
      icon: "🔴",
      words: [
        { zh: "爱心", pinyin: "ài xīn", ko: "사랑하는 마음, 따뜻한 정성", pos: "명사", hanja: "애심(愛心) — '愛'는 사랑 애, '心'은 마음 심.", ex: { zh: "他是一个很有爱心的人。", pinyin: "tā shì yí ge hěn yǒu àixīn de rén", ko: "그는 따뜻한 마음을 가진 사람이에요." } },
        { zh: "班主任", pinyin: "bān zhǔ rèn", ko: "담임 선생님", pos: "명사", hanja: "반주임(班主任) — '班'은 반 반, '主任'은 주임.", ex: { zh: "我们的班主任很严格。", pinyin: "wǒmen de bānzhǔrèn hěn yángé", ko: "우리 담임 선생님은 엄격해요." } },
        { zh: "包子", pinyin: "bāo zi", ko: "(소가 든) 찐빵, 만두", pos: "명사", hanja: "포자(包子) — '包'는 쌀 포.", ex: { zh: "早上我吃了两个包子。", pinyin: "zǎoshang wǒ chī le liǎng ge bāozi", ko: "아침에 만두 두 개를 먹었어요." } },
        { zh: "宝贝", pinyin: "bǎo bèi", ko: "보물, 소중한 것; (애칭) 자기, 아가", pos: "명사", hanja: "보패(寶貝) — '寶'는 보배 보, '貝'는 조개 패.", ex: { zh: "这本书是我的宝贝。", pinyin: "zhè běn shū shì wǒ de bǎobèi", ko: "이 책은 제 보물이에요." } },
        { zh: "背景", pinyin: "bèi jǐng", ko: "배경; 뒷받침, 연줄", pos: "명사", hanja: "배경(背景) — '背'는 등 배, '景'은 볕 경.", ex: { zh: "这张照片的背景很美。", pinyin: "zhè zhāng zhàopiàn de bèijǐng hěn měi", ko: "이 사진의 배경이 아름다워요." } },
        { zh: "被子", pinyin: "bèi zi", ko: "이불", pos: "명사", hanja: "피자(被子) — '被'는 이불 피.", ex: { zh: "天冷了，多盖一床被子。", pinyin: "tiān lěng le, duō gài yì chuáng bèizi", ko: "날이 추우니 이불을 하나 더 덮으세요." } },
        { zh: "本科", pinyin: "běn kē", ko: "학부, 대학 본과", pos: "명사", hanja: "본과(本科) — '本'은 근본 본, '科'는 과목 과.", ex: { zh: "他是本科毕业。", pinyin: "tā shì běnkē bìyè", ko: "그는 학부를 졸업했어요." } },
        { zh: "本领", pinyin: "běn lǐng", ko: "능력, 재주, 솜씨", pos: "명사", hanja: "본령(本領) — '領'은 거느릴 령.", ex: { zh: "他有真本领。", pinyin: "tā yǒu zhēn běnlǐng", ko: "그는 진짜 실력이 있어요." } },
        { zh: "比例", pinyin: "bǐ lì", ko: "비례, 비율", pos: "명사", hanja: "비례(比例) — '比'는 견줄 비, '例'는 법식 례.", ex: { zh: "男女学生的比例差不多。", pinyin: "nán nǚ xuésheng de bǐlì chàbuduō", ko: "남녀 학생의 비율이 비슷해요." } },
        { zh: "标志", pinyin: "biāo zhì", ko: "표지, 상징, 마크; 상징하다", pos: "명사", hanja: "표지(標誌) — '標'는 표할 표, '誌'는 기록할 지.", ex: { zh: "这是和平的标志。", pinyin: "zhè shì hépíng de biāozhì", ko: "이것은 평화의 상징이에요." } },
        { zh: "表情", pinyin: "biǎo qíng", ko: "표정", pos: "명사", hanja: "표정(表情) — '表'는 겉 표, '情'은 뜻 정.", ex: { zh: "她脸上的表情很奇怪。", pinyin: "tā liǎn shang de biǎoqíng hěn qíguài", ko: "그녀의 표정이 이상해요." } },
        { zh: "病毒", pinyin: "bìng dú", ko: "바이러스", pos: "명사", hanja: "병독(病毒) — '病'은 병 병, '毒'은 독 독.", ex: { zh: "电脑感染了病毒。", pinyin: "diànnǎo gǎnrǎn le bìngdú", ko: "컴퓨터가 바이러스에 감염됐어요." } },
        { zh: "玻璃", pinyin: "bō li", ko: "유리", pos: "명사", hanja: "파리(玻璃) — '玻'는 유리 파, '璃'는 유리 리.", ex: { zh: "窗户的玻璃碎了。", pinyin: "chuānghu de bōli suì le", ko: "창문 유리가 깨졌어요." } },
        { zh: "脖子", pinyin: "bó zi", ko: "목", pos: "명사", ex: { zh: "我的脖子有点酸。", pinyin: "wǒ de bózi yǒudiǎn suān", ko: "제 목이 좀 뻐근해요." } },
        { zh: "博物馆", pinyin: "bó wù guǎn", ko: "박물관", pos: "명사", hanja: "박물관(博物館) — '博'은 넓을 박, '物'은 물건 물, '館'은 집 관.", ex: { zh: "周末我们去博物馆吧。", pinyin: "zhōumò wǒmen qù bówùguǎn ba", ko: "주말에 박물관에 가요." } },
        { zh: "步骤", pinyin: "bù zhòu", ko: "(일의) 절차, 단계, 순서", pos: "명사", hanja: "보취(步驟) — '步'는 걸음 보, '驟'는 달릴 취.", ex: { zh: "请按步骤操作。", pinyin: "qǐng àn bùzhòu cāozuò", ko: "절차에 따라 조작하세요." } },
        { zh: "部门", pinyin: "bù mén", ko: "부서, 부문", pos: "명사", hanja: "부문(部門) — '部'는 떼 부, '門'은 문 문.", ex: { zh: "他在销售部门工作。", pinyin: "tā zài xiāoshòu bùmén gōngzuò", ko: "그는 영업 부서에서 일해요." } },
        { zh: "餐厅", pinyin: "cān tīng", ko: "식당, 레스토랑", pos: "명사", hanja: "찬청(餐廳) — '餐'은 밥 찬, '廳'은 관청/홀 청.", ex: { zh: "这家餐厅的菜很好吃。", pinyin: "zhè jiā cāntīng de cài hěn hǎochī", ko: "이 식당 음식은 맛있어요." } },
        { zh: "残疾", pinyin: "cán jí", ko: "장애 (신체적)", pos: "명사", hanja: "잔질(殘疾) — '殘'은 잔인할/남을 잔, '疾'은 병 질.", ex: { zh: "他身体有残疾，但很坚强。", pinyin: "tā shēntǐ yǒu cánjí, dàn hěn jiānqiáng", ko: "그는 몸에 장애가 있지만 강인해요." } },
        { zh: "操场", pinyin: "cāo chǎng", ko: "운동장, 연병장", pos: "명사", hanja: "조장(操場) — '操'는 잡을 조, '場'은 마당 장.", ex: { zh: "学生们在操场上跑步。", pinyin: "xuéshengmen zài cāochǎng shang pǎobù", ko: "학생들이 운동장에서 달려요." } },
        { zh: "厕所", pinyin: "cè suǒ", ko: "화장실, 변소", pos: "명사", hanja: "측소(廁所) — '廁'은 뒷간 측, '所'는 바 소.", ex: { zh: "请问厕所在哪里？", pinyin: "qǐngwèn cèsuǒ zài nǎlǐ", ko: "실례지만 화장실이 어디예요?" } },
        { zh: "差别", pinyin: "chā bié", ko: "차이, 차별, 구별", pos: "명사", hanja: "차별(差別) — '差'는 어긋날 차, '別'은 다를 별.", ex: { zh: "这两个词有什么差别？", pinyin: "zhè liǎng ge cí yǒu shénme chābié", ko: "이 두 단어는 무슨 차이가 있어요?" } },
        { zh: "常识", pinyin: "cháng shí", ko: "상식, 일반 지식", pos: "명사", hanja: "상식(常識) — '常'은 떳떳할 상, '識'은 알 식.", ex: { zh: "这是基本的生活常识。", pinyin: "zhè shì jīběn de shēnghuó chángshí", ko: "이것은 기본적인 생활 상식이에요." } },
        { zh: "朝代", pinyin: "cháo dài", ko: "(왕조의) 시대, 왕조", pos: "명사", hanja: "조대(朝代) — '朝'는 아침/조정 조, '代'는 대신할 대.", ex: { zh: "中国有很多朝代。", pinyin: "Zhōngguó yǒu hěn duō cháodài", ko: "중국에는 많은 왕조가 있었어요." } },
        { zh: "车库", pinyin: "chē kù", ko: "차고, 주차장", pos: "명사", hanja: "차고(車庫) — '車'는 수레 차, '庫'는 곳집 고.", ex: { zh: "车停在车库里。", pinyin: "chē tíng zài chēkù lǐ", ko: "차는 차고에 세워 두었어요." } },
        { zh: "车厢", pinyin: "chē xiāng", ko: "(기차·전철) 객차, 칸", pos: "명사", hanja: "차상(車廂) — '廂'은 곁채/객차 상.", ex: { zh: "这节车厢很挤。", pinyin: "zhè jié chēxiāng hěn jǐ", ko: "이 객차 칸은 붐벼요." } },
        { zh: "成分", pinyin: "chéng fèn", ko: "성분, 요소", pos: "명사", hanja: "성분(成分) — '成'은 이룰 성, '分'은 나눌 분.", ex: { zh: "这种药的成分很安全。", pinyin: "zhè zhǒng yào de chéngfèn hěn ānquán", ko: "이 약의 성분은 안전해요." } },
        { zh: "成语", pinyin: "chéng yǔ", ko: "성어, 사자성어", pos: "명사", hanja: "성어(成語) — '語'는 말씀 어.", ex: { zh: "我学了一个新成语。", pinyin: "wǒ xué le yí ge xīn chéngyǔ", ko: "저는 새 성어 하나를 배웠어요." } },
        { zh: "程度", pinyin: "chéng dù", ko: "정도, 수준", pos: "명사", hanja: "정도(程度) — '程'은 한도 정, '度'는 법도 도.", ex: { zh: "他的汉语达到了高级程度。", pinyin: "tā de Hànyǔ dádào le gāojí chéngdù", ko: "그의 중국어는 고급 수준에 도달했어요." } },
        { zh: "程序", pinyin: "chéng xù", ko: "절차, 순서; (컴퓨터) 프로그램", pos: "명사", hanja: "정서(程序) — '序'는 차례 서.", ex: { zh: "请按程序办事。", pinyin: "qǐng àn chéngxù bànshì", ko: "절차에 따라 일을 처리하세요." } },
        { zh: "翅膀", pinyin: "chì bǎng", ko: "날개", pos: "명사", hanja: "시방(翅膀) — '翅'는 날개 시.", ex: { zh: "鸟用翅膀飞。", pinyin: "niǎo yòng chìbǎng fēi", ko: "새는 날개로 날아요." } },
        { zh: "充电器", pinyin: "chōng diàn qì", ko: "충전기", pos: "명사", hanja: "충전기(充電器) — '充'은 채울 충, '電'은 번개 전, '器'는 그릇 기.", ex: { zh: "我忘了带充电器。", pinyin: "wǒ wàng le dài chōngdiànqì", ko: "충전기 챙기는 걸 잊었어요." } },
        { zh: "宠物", pinyin: "chǒng wù", ko: "반려동물, 애완동물", pos: "명사", hanja: "총물(寵物) — '寵'은 사랑할 총, '物'은 물건 물.", ex: { zh: "我家养了一只宠物猫。", pinyin: "wǒ jiā yǎng le yì zhī chǒngwù māo", ko: "우리 집은 반려묘 한 마리를 키워요." } },
        { zh: "抽屉", pinyin: "chōu ti", ko: "서랍", pos: "명사", hanja: "추체(抽屜) — '抽'는 뽑을 추, '屜'는 서랍 체.", ex: { zh: "钥匙在抽屉里。", pinyin: "yàoshi zài chōuti lǐ", ko: "열쇠는 서랍 안에 있어요." } },
        { zh: "窗帘", pinyin: "chuāng lián", ko: "커튼", pos: "명사", hanja: "창렴(窗簾) — '窗'은 창 창, '簾'은 발 렴.", ex: { zh: "请拉上窗帘。", pinyin: "qǐng lā shang chuānglián", ko: "커튼을 쳐 주세요." } },
        { zh: "磁带", pinyin: "cí dài", ko: "(녹음) 테이프, 카세트", pos: "명사", hanja: "자대(磁帶) — '磁'는 자석 자, '帶'는 띠 대.", ex: { zh: "现在很少有人用磁带了。", pinyin: "xiànzài hěn shǎo yǒu rén yòng cídài le", ko: "지금은 테이프를 쓰는 사람이 거의 없어요." } },
        { zh: "措施", pinyin: "cuò shī", ko: "조치, 대책", pos: "명사", hanja: "조시(措施) — '措'는 둘 조, '施'는 베풀 시.", ex: { zh: "学校采取了安全措施。", pinyin: "xuéxiào cǎiqǔ le ānquán cuòshī", ko: "학교는 안전 조치를 취했어요." } },
        { zh: "错误", pinyin: "cuò wù", ko: "잘못, 오류; 잘못되다", pos: "명사", hanja: "착오(錯誤) — '錯'은 어긋날 착, '誤'는 그르칠 오.", ex: { zh: "这是一个严重的错误。", pinyin: "zhè shì yí ge yánzhòng de cuòwù", ko: "이것은 심각한 잘못이에요." } },
        { zh: "待遇", pinyin: "dài yù", ko: "대우, 처우, 보수", pos: "명사", hanja: "대우(待遇) — '待'는 기다릴 대, '遇'는 만날 우.", ex: { zh: "这份工作待遇不错。", pinyin: "zhè fèn gōngzuò dàiyù búcuò", ko: "이 일은 대우가 괜찮아요." } },
        { zh: "单位", pinyin: "dān wèi", ko: "(소속) 직장, 기관; 단위", pos: "명사", hanja: "단위(單位) — '單'은 홑 단, '位'는 자리 위.", ex: { zh: "我们单位有食堂。", pinyin: "wǒmen dānwèi yǒu shítáng", ko: "우리 직장에는 식당이 있어요." } },
        { zh: "单元", pinyin: "dān yuán", ko: "단원; (건물의) 동, 입구", pos: "명사", hanja: "단원(單元) — '元'은 으뜸 원.", ex: { zh: "我们学到第三单元了。", pinyin: "wǒmen xuédào dì sān dānyuán le", ko: "우리는 3단원까지 배웠어요." } },
        { zh: "胆小鬼", pinyin: "dǎn xiǎo guǐ", ko: "겁쟁이", pos: "명사", hanja: "담소귀(膽小鬼) — '膽'은 쓸개 담, '小'는 작을 소, '鬼'는 귀신 귀.", ex: { zh: "别当胆小鬼，勇敢一点。", pinyin: "bié dāng dǎnxiǎoguǐ, yǒnggǎn yìdiǎn", ko: "겁쟁이 되지 말고 좀 용감해지세요." } },
        { zh: "道德", pinyin: "dào dé", ko: "도덕, 윤리", pos: "명사", hanja: "도덕(道德) — '道'는 길 도, '德'은 큰 덕.", ex: { zh: "我们要讲道德。", pinyin: "wǒmen yào jiǎng dàodé", ko: "우리는 도덕을 지켜야 해요." } },
        { zh: "地理", pinyin: "dì lǐ", ko: "지리", pos: "명사", hanja: "지리(地理) — '地'는 땅 지, '理'는 다스릴 리.", ex: { zh: "我对中国地理很感兴趣。", pinyin: "wǒ duì Zhōngguó dìlǐ hěn gǎn xìngqù", ko: "저는 중국 지리에 관심이 많아요." } },
        { zh: "地区", pinyin: "dì qū", ko: "지역, 지구", pos: "명사", hanja: "지구(地區) — '區'는 구역 구.", ex: { zh: "这个地区雨水很多。", pinyin: "zhège dìqū yǔshuǐ hěn duō", ko: "이 지역은 비가 많이 와요." } },
        { zh: "地毯", pinyin: "dì tǎn", ko: "카펫, 양탄자", pos: "명사", hanja: "지담(地毯) — '毯'은 담요 담.", ex: { zh: "客厅铺了一块地毯。", pinyin: "kètīng pū le yí kuài dìtǎn", ko: "거실에 카펫을 깔았어요." } },
        { zh: "地位", pinyin: "dì wèi", ko: "지위, 위치, 신분", pos: "명사", hanja: "지위(地位) — '位'는 자리 위.", ex: { zh: "他在公司地位很高。", pinyin: "tā zài gōngsī dìwèi hěn gāo", ko: "그는 회사에서 지위가 높아요." } },
        { zh: "地震", pinyin: "dì zhèn", ko: "지진", pos: "명사", hanja: "지진(地震) — '震'은 우레 진.", ex: { zh: "昨晚发生了地震。", pinyin: "zuówǎn fāshēng le dìzhèn", ko: "어젯밤 지진이 발생했어요." } },
        { zh: "登机牌", pinyin: "dēng jī pái", ko: "탑승권, 보딩 패스", pos: "명사", hanja: "등기패(登機牌) — '登機'는 비행기 탑승, '牌'는 패 패.", ex: { zh: "请出示您的登机牌。", pinyin: "qǐng chūshì nín de dēngjīpái", ko: "탑승권을 보여 주세요." } },
        { zh: "敌人", pinyin: "dí rén", ko: "적", pos: "명사", hanja: "적인(敵人) — '敵'은 대적할 적, '人'은 사람 인.", ex: { zh: "他们曾经是敌人。", pinyin: "tāmen céngjīng shì dírén", ko: "그들은 한때 적이었어요." } },
        { zh: "点心", pinyin: "diǎn xin", ko: "간식, 다과, 딤섬", pos: "명사", hanja: "점심(點心) — 한자는 '점심'이지만 '간식·과자'를 뜻해요. 식사 점심은 午饭!", ex: { zh: "下午我们吃点点心吧。", pinyin: "xiàwǔ wǒmen chī diǎn diǎnxin ba", ko: "오후에 간식 좀 먹어요." } },
        { zh: "出口", pinyin: "chū kǒu", ko: "출구; 수출하다; 말을 꺼내다", pos: "명사", hanja: "출구(出口) — '出'은 날 출, '口'는 입 구.", ex: { zh: "出口在那边。", pinyin: "chūkǒu zài nàbiān", ko: "출구는 저쪽이에요." } },
        { zh: "彩虹", pinyin: "cǎi hóng", ko: "무지개", pos: "명사", hanja: "채홍(彩虹) — '彩'는 채색 채, '虹'은 무지개 홍.", ex: { zh: "雨后出现了彩虹。", pinyin: "yǔ hòu chūxiàn le cǎihóng", ko: "비 온 뒤 무지개가 떴어요." } },
        { zh: "叉子", pinyin: "chā zi", ko: "포크", pos: "명사", hanja: "차자(叉子) — '叉'는 깍지 낄/갈래 차.", ex: { zh: "吃西餐要用叉子。", pinyin: "chī xīcān yào yòng chāzi", ko: "양식을 먹을 때는 포크를 써요." } },
        { zh: "尺子", pinyin: "chǐ zi", ko: "자(측정 도구)", pos: "명사", hanja: "척자(尺子) — '尺'은 자 척.", ex: { zh: "请借我一把尺子。", pinyin: "qǐng jiè wǒ yì bǎ chǐzi", ko: "자 하나 빌려주세요." } },
        { zh: "池子", pinyin: "chí zi", ko: "못, (수영장 등) 물이 담긴 곳", pos: "명사", hanja: "지자(池子) — '池'는 못 지.", ex: { zh: "公园里有一个大池子。", pinyin: "gōngyuán lǐ yǒu yí ge dà chízi", ko: "공원에 큰 연못이 있어요." } },
        { zh: "鞭炮", pinyin: "biān pào", ko: "폭죽", pos: "명사", hanja: "편포(鞭炮) — '鞭'은 채찍 편, '炮'는 대포 포.", ex: { zh: "过年时大家放鞭炮。", pinyin: "guònián shí dàjiā fàng biānpào", ko: "설에는 모두 폭죽을 터뜨려요." } },
        { zh: "标点", pinyin: "biāo diǎn", ko: "구두점, 문장 부호", pos: "명사", hanja: "표점(標點) — '標'는 표할 표, '點'은 점 점.", ex: { zh: "这句话少了一个标点。", pinyin: "zhè jù huà shǎo le yí ge biāodiǎn", ko: "이 문장에 구두점이 하나 빠졌어요." } },
        { zh: "册", pinyin: "cè", ko: "책, 권(책을 세는 양사)", pos: "양사", hanja: "책(冊) — '책 책'.", ex: { zh: "这套书一共十册。", pinyin: "zhè tào shū yígòng shí cè", ko: "이 책 세트는 모두 열 권이에요." } },
        { zh: "测验", pinyin: "cè yàn", ko: "테스트, 시험", pos: "명사", hanja: "측험(測驗) — '測'은 헤아릴 측, '驗'은 시험할 험.", ex: { zh: "明天有一个小测验。", pinyin: "míngtiān yǒu yí ge xiǎo cèyàn", ko: "내일 작은 시험이 있어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 형용사·상태",
      icon: "🔴",
      words: [
        { zh: "悲观", pinyin: "bēi guān", ko: "비관적이다", pos: "형용사", hanja: "비관(悲觀) — '悲'는 슬플 비, '觀'은 볼 관.", ex: { zh: "他对未来很悲观。", pinyin: "tā duì wèilái hěn bēiguān", ko: "그는 미래에 대해 비관적이에요." } },
        { zh: "必然", pinyin: "bì rán", ko: "필연적이다, 반드시 그러하다", pos: "형용사", hanja: "필연(必然) — '必'은 반드시 필, '然'은 그럴 연.", ex: { zh: "这是必然的结果。", pinyin: "zhè shì bìrán de jiéguǒ", ko: "이것은 필연적인 결과예요." } },
        { zh: "必要", pinyin: "bì yào", ko: "필요하다, 필수적이다; 필요성", pos: "형용사", hanja: "필요(必要) — '要'는 요긴할 요.", ex: { zh: "没有必要担心。", pinyin: "méiyǒu bìyào dānxīn", ko: "걱정할 필요 없어요." } },
        { zh: "不安", pinyin: "bù ān", ko: "불안하다, 마음이 편치 않다", pos: "형용사", hanja: "불안(不安) — '不'은 아닐 불, '安'은 편안할 안.", ex: { zh: "他心里感到不安。", pinyin: "tā xīnlǐ gǎndào bù'ān", ko: "그는 마음속으로 불안해했어요." } },
        { zh: "不耐烦", pinyin: "bù nài fán", ko: "귀찮다, 참을성이 없다, 짜증스럽다", pos: "형용사", hanja: "불내번(不耐煩) — '耐'는 견딜 내, '煩'은 번거로울 번.", ex: { zh: "他等得有点不耐烦了。", pinyin: "tā děng de yǒudiǎn bú nàifán le", ko: "그는 기다리다가 좀 짜증이 났어요." } },
        { zh: "不足", pinyin: "bù zú", ko: "부족하다, 모자라다; 미흡함", pos: "형용사", hanja: "부족(不足) — '足'은 발/족할 족.", ex: { zh: "时间不足，我们快点。", pinyin: "shíjiān bùzú, wǒmen kuài diǎn", ko: "시간이 부족하니 서두릅시다." } },
        { zh: "岛", pinyin: "dǎo", ko: "섬", pos: "명사", hanja: "도(島) — '섬 도'. (입력 trad 㠀는 이체자)", ex: { zh: "这座岛非常美丽。", pinyin: "zhè zuò dǎo fēicháng měilì", ko: "이 섬은 정말 아름다워요." } },
        { zh: "惭愧", pinyin: "cán kuì", ko: "부끄럽다, 창피하다", pos: "형용사", hanja: "참괴(慚愧) — '慚'은 부끄러울 참, '愧'는 부끄러울 괴.", ex: { zh: "做错了事，我很惭愧。", pinyin: "zuòcuò le shì, wǒ hěn cánkuì", ko: "일을 잘못해서 부끄러워요." } },
        { zh: "彻底", pinyin: "chè dǐ", ko: "철저하다, 완전하다; 철저히", pos: "형용사", hanja: "철저(徹底) — '徹'은 통할 철, '底'는 밑 저.", ex: { zh: "请把房间彻底打扫一下。", pinyin: "qǐng bǎ fángjiān chèdǐ dǎsǎo yíxià", ko: "방을 철저히 청소해 주세요." } },
        { zh: "沉默", pinyin: "chén mò", ko: "침묵하다, 말이 없다; 침묵", pos: "형용사", hanja: "침묵(沈默) — '沈'은 잠길 침, '默'은 잠잠할 묵.", ex: { zh: "他一直保持沉默。", pinyin: "tā yìzhí bǎochí chénmò", ko: "그는 줄곧 침묵을 지켰어요." } },
        { zh: "诚恳", pinyin: "chéng kěn", ko: "진실하다, 간절하다, 정성스럽다", pos: "형용사", hanja: "성간(誠懇) — '誠'은 정성 성, '懇'은 간절할 간.", ex: { zh: "他的态度很诚恳。", pinyin: "tā de tàidu hěn chéngkěn", ko: "그의 태도는 진실해요." } },
        { zh: "充分", pinyin: "chōng fèn", ko: "충분하다; 충분히", pos: "형용사", hanja: "충분(充分) — '充'은 채울 충, '分'은 나눌 분.", ex: { zh: "我们做了充分的准备。", pinyin: "wǒmen zuò le chōngfèn de zhǔnbèi", ko: "우리는 충분한 준비를 했어요." } },
        { zh: "臭", pinyin: "chòu", ko: "(냄새가) 구리다, 역겹다", pos: "형용사", hanja: "취(臭) — '냄새 취'.", ex: { zh: "这个垃圾桶很臭。", pinyin: "zhège lājītǒng hěn chòu", ko: "이 쓰레기통은 냄새가 고약해요." } },
        { zh: "出色", pinyin: "chū sè", ko: "뛰어나다, 훌륭하다", pos: "형용사", hanja: "출색(出色) — '出'은 날 출, '色'은 빛 색.", ex: { zh: "她的表现非常出色。", pinyin: "tā de biǎoxiàn fēicháng chūsè", ko: "그녀의 활약은 아주 뛰어났어요." } },
        { zh: "次要", pinyin: "cì yào", ko: "부차적이다, 중요하지 않다", pos: "형용사", hanja: "차요(次要) — '次'는 버금 차, '要'는 요긴할 요.", ex: { zh: "这些都是次要问题。", pinyin: "zhèxiē dōu shì cìyào wèntí", ko: "이것들은 모두 부차적인 문제예요." } },
        { zh: "匆忙", pinyin: "cōng máng", ko: "분주하다, 급하다, 황급하다", pos: "형용사", hanja: "총망(匆忙) — '匆'은 바쁠 총, '忙'은 바쁠 망.", ex: { zh: "他匆忙地走了。", pinyin: "tā cōngmáng de zǒu le", ko: "그는 황급히 떠났어요." } },
        { zh: "单纯", pinyin: "dān chún", ko: "단순하다, 순수하다", pos: "형용사", hanja: "단순(單純) — '單'은 홑 단, '純'은 순수할 순.", ex: { zh: "他想得太单纯了。", pinyin: "tā xiǎng de tài dānchún le", ko: "그는 생각이 너무 단순해요." } },
        { zh: "单调", pinyin: "dān diào", ko: "단조롭다, 변화가 없다", pos: "형용사", hanja: "단조(單調) — '調'는 고를 조.", ex: { zh: "这里的生活很单调。", pinyin: "zhèlǐ de shēnghuó hěn dāndiào", ko: "이곳의 생활은 단조로워요." } },
        { zh: "单独", pinyin: "dān dú", ko: "단독으로, 혼자서", pos: "부사", hanja: "단독(單獨) — '獨'은 홀로 독.", ex: { zh: "我想单独和你谈谈。", pinyin: "wǒ xiǎng dāndú hé nǐ tántan", ko: "당신과 따로 이야기하고 싶어요." } },
        { zh: "倒霉", pinyin: "dǎo méi", ko: "재수 없다, 운이 나쁘다", pos: "형용사", hanja: "도매(倒霉) — '倒'는 넘어질 도, '霉'는 곰팡이 매.", ex: { zh: "今天真倒霉，丢了钱包。", pinyin: "jīntiān zhēn dǎoméi, diū le qiánbāo", ko: "오늘은 정말 재수 없게 지갑을 잃어버렸어요." } },
        { zh: "淡", pinyin: "dàn", ko: "(맛이) 싱겁다, (색이) 연하다, 묽다", pos: "형용사", hanja: "담(淡) — '맑을 담'.", ex: { zh: "这个汤味道有点淡。", pinyin: "zhège tāng wèidao yǒudiǎn dàn", ko: "이 국은 맛이 좀 싱거워요." } },
        { zh: "呆", pinyin: "dāi", ko: "멍하다, 미련하다; 멍하니 있다", pos: "형용사", ex: { zh: "他听到消息后呆住了。", pinyin: "tā tīngdào xiāoxi hòu dāi zhù le", ko: "그는 소식을 듣고 멍해졌어요." } },
        { zh: "唉", pinyin: "āi", ko: "에이, 휴 (탄식·대답)", pos: "감탄사", ex: { zh: "唉，真没办法。", pinyin: "āi, zhēn méi bànfǎ", ko: "휴, 정말 방법이 없네요." } },
        { zh: "薄", pinyin: "báo", ko: "(두께가) 얇다", pos: "형용사", hanja: "박(薄) — '엷을 박'. (입력 'Bó'는 성씨 오독, HSK 의미는 '얇다' báo)", ex: { zh: "这件衣服太薄了。", pinyin: "zhè jiàn yīfu tài báo le", ko: "이 옷은 너무 얇아요." } },
        { zh: "棒", pinyin: "bàng", ko: "(구어) 대단하다, 훌륭하다; 막대기", pos: "형용사", hanja: "봉(棒) — '몽둥이 봉'. 구어로 '훌륭하다'.", ex: { zh: "你做得真棒！", pinyin: "nǐ zuò de zhēn bàng", ko: "정말 잘했어요!" } },
        { zh: "便", pinyin: "biàn", ko: "곧, 바로 (=就); 편리하다", pos: "부사", hanja: "편(便) — '편할 편/똥오줌 변'. 부사로 '就'와 같이 '곧·바로'.", ex: { zh: "他说完便走了。", pinyin: "tā shuō wán biàn zǒu le", ko: "그는 말을 마치자 바로 떠났어요." } },
        { zh: "丑", pinyin: "chǒu", ko: "못생기다, 추하다", pos: "형용사", hanja: "추(醜) — '추할 추'. (입력 'Chǒu'는 성씨 오독, HSK 의미는 '못생기다')", ex: { zh: "这幅画一点也不丑。", pinyin: "zhè fú huà yìdiǎn yě bù chǒu", ko: "이 그림은 조금도 못나지 않았어요." } },
        { zh: "初级", pinyin: "chū jí", ko: "초급의, 초보의", pos: "형용사", hanja: "초급(初級) — '初'는 처음 초, '級'은 등급 급.", ex: { zh: "我在上初级汉语班。", pinyin: "wǒ zài shàng chūjí Hànyǔ bān", ko: "저는 초급 중국어 반을 듣고 있어요." } },
        { zh: "大方", pinyin: "dà fāng", ko: "(돈에) 후하다, 시원시원하다, (태도가) 점잖다", pos: "형용사", hanja: "대방(大方) — '大'는 큰 대, '方'은 모 방.", ex: { zh: "他花钱很大方。", pinyin: "tā huā qián hěn dàfang", ko: "그는 돈을 시원시원하게 써요." } },
        { zh: "大型", pinyin: "dà xíng", ko: "대형의, 대규모의", pos: "형용사", hanja: "대형(大型) — '型'은 모형 형.", ex: { zh: "这是一场大型演出。", pinyin: "zhè shì yì chǎng dàxíng yǎnchū", ko: "이것은 대형 공연이에요." } },
        { zh: "当代", pinyin: "dāng dài", ko: "당대의, 현시대의", pos: "형용사", hanja: "당대(當代) — '當'은 마땅 당, '代'는 대신할 대.", ex: { zh: "他是当代著名作家。", pinyin: "tā shì dāngdài zhùmíng zuòjiā", ko: "그는 당대의 유명한 작가예요." } },
        { zh: "地道", pinyin: "dì dao", ko: "정통의, 본고장의, 제대로 된", pos: "형용사", hanja: "지도(地道) — '地'는 땅 지, '道'는 길 도. 발음 'dìdao'면 '정통의'.", ex: { zh: "他说一口地道的北京话。", pinyin: "tā shuō yì kǒu dìdao de Běijīng huà", ko: "그는 정통 베이징 말을 해요." } },
        { zh: "吃亏", pinyin: "chī kuī", ko: "손해를 보다, 손해 보다", pos: "동사", hanja: "끽휴(吃虧) — '吃'는 먹을 끽, '虧'는 이지러질 휴.", ex: { zh: "诚实的人不会吃亏。", pinyin: "chéngshí de rén bú huì chīkuī", ko: "정직한 사람은 손해 보지 않아요." } },
        { zh: "表现", pinyin: "biǎo xiàn", ko: "(태도·능력을) 드러내다, 표현하다; 활약, 태도", pos: "동사", hanja: "표현(表現) — '表'는 겉 표, '現'은 나타날 현.", ex: { zh: "他在工作中表现得很好。", pinyin: "tā zài gōngzuò zhōng biǎoxiàn de hěn hǎo", ko: "그는 일에서 좋은 모습을 보였어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 부사·기타",
      icon: "🔴",
      words: [
        { zh: "彼此", pinyin: "bǐ cǐ", ko: "서로, 피차, 상호", pos: "대명사", hanja: "피차(彼此) — '彼'는 저 피, '此'는 이 차.", ex: { zh: "我们彼此都很了解。", pinyin: "wǒmen bǐcǐ dōu hěn liǎojiě", ko: "우리는 서로를 잘 알아요." } },
        { zh: "不必", pinyin: "bù bì", ko: "~할 필요 없다", pos: "부사", hanja: "불필(不必) — '必'은 반드시 필.", ex: { zh: "你不必担心。", pinyin: "nǐ búbì dānxīn", ko: "당신은 걱정할 필요 없어요." } },
        { zh: "不得了", pinyin: "bù dé liǎo", ko: "큰일이다; (정도가) 대단하다", pos: "형용사", hanja: "부득료(不得了) — '得'은 얻을 득, '了'는 마칠 료.", ex: { zh: "他高兴得不得了。", pinyin: "tā gāoxìng de bùdéliǎo", ko: "그는 엄청나게 기뻐했어요." } },
        { zh: "不断", pinyin: "bù duàn", ko: "끊임없이, 부단히", pos: "부사", hanja: "부단(不斷) — '斷'은 끊을 단.", ex: { zh: "科技在不断发展。", pinyin: "kējì zài búduàn fāzhǎn", ko: "과학 기술은 끊임없이 발전하고 있어요." } },
        { zh: "不好意思", pinyin: "bù hǎo yì si", ko: "쑥스럽다, 미안하다", pos: "관용구", hanja: "—", ex: { zh: "不好意思，我来晚了。", pinyin: "bù hǎo yìsi, wǒ lái wǎn le", ko: "미안해요, 제가 늦었어요." } },
        { zh: "不见得", pinyin: "bù jiàn de", ko: "반드시 ~한 것은 아니다", pos: "부사", hanja: "부견득(不見得) — '見'은 볼 견, '得'은 얻을 득.", ex: { zh: "贵的不见得就好。", pinyin: "guì de bújiànde jiù hǎo", ko: "비싸다고 꼭 좋은 건 아니에요." } },
        { zh: "不免", pinyin: "bù miǎn", ko: "면할 수 없이, 자연히", pos: "부사", hanja: "불면(不免) — '免'은 면할 면.", ex: { zh: "第一次上台，不免有点紧张。", pinyin: "dì yī cì shàngtái, bùmiǎn yǒudiǎn jǐnzhāng", ko: "처음 무대에 서면 자연히 좀 긴장돼요." } },
        { zh: "不然", pinyin: "bù rán", ko: "그렇지 않으면, 아니면", pos: "접속사", hanja: "불연(不然) — '然'은 그럴 연.", ex: { zh: "快走吧，不然就迟到了。", pinyin: "kuài zǒu ba, bùrán jiù chídào le", ko: "빨리 가요, 안 그러면 지각해요." } },
        { zh: "不如", pinyin: "bù rú", ko: "~만 못하다, ~하는 편이 낫다", pos: "동사", hanja: "불여(不如) — '如'는 같을 여.", ex: { zh: "坐车不如走路快。", pinyin: "zuò chē bùrú zǒulù kuài", ko: "차를 타는 것보다 걷는 게 빨라요." } },
        { zh: "不要紧", pinyin: "bù yào jǐn", ko: "괜찮다, 대수롭지 않다", pos: "관용구", hanja: "불요긴(不要緊) — '緊'은 긴할 긴.", ex: { zh: "没关系，不要紧。", pinyin: "méi guānxi, búyàojǐn", ko: "괜찮아요, 별일 아니에요." } },
        { zh: "曾经", pinyin: "céng jīng", ko: "일찍이, 예전에 (~한 적이 있다)", pos: "부사", hanja: "증경(曾經) — '曾'은 일찍 증, '經'은 지날 경.", ex: { zh: "我曾经去过北京。", pinyin: "wǒ céngjīng qù guò Běijīng", ko: "저는 예전에 베이징에 가 본 적이 있어요." } },
        { zh: "趁", pinyin: "chèn", ko: "~을 틈타, ~을 이용하여", pos: "개사", hanja: "츤(趁) — '쫓을 츤'.", ex: { zh: "趁热吃吧。", pinyin: "chèn rè chī ba", ko: "따뜻할 때 드세요." } },
        { zh: "朝", pinyin: "cháo", ko: "~을 향하여; 왕조", pos: "개사", hanja: "조(朝) — '아침/조정 조'. 개사로 '~을 향해'. (입력 'Cháo'는 국명 약칭 오독)", ex: { zh: "请朝前走。", pinyin: "qǐng cháo qián zǒu", ko: "앞쪽으로 가세요." } },
        { zh: "乘", pinyin: "chéng", ko: "타다, 탑승하다; 곱하다", pos: "동사", hanja: "승(乘) — '탈 승'. (입력 'Chéng'은 성씨 오독, HSK 의미는 '타다')", ex: { zh: "我们乘飞机去上海。", pinyin: "wǒmen chéng fēijī qù Shànghǎi", ko: "우리는 비행기를 타고 상하이에 가요." } },
        { zh: "此外", pinyin: "cǐ wài", ko: "이 외에, 그 밖에", pos: "접속사", hanja: "차외(此外) — '此'는 이 차, '外'는 바깥 외.", ex: { zh: "此外，还有一个问题。", pinyin: "cǐwài, hái yǒu yí ge wèntí", ko: "이 외에 또 한 가지 문제가 있어요." } },
        { zh: "从此", pinyin: "cóng cǐ", ko: "이로부터, 그때부터", pos: "부사", hanja: "종차(從此) — '從'은 좇을 종, '此'는 이 차.", ex: { zh: "从此他再也没来过。", pinyin: "cóngcǐ tā zài yě méi lái guò", ko: "그때부터 그는 다시는 오지 않았어요." } },
        { zh: "从前", pinyin: "cóng qián", ko: "예전, 옛날에", pos: "명사", hanja: "종전(從前) — '前'은 앞 전.", ex: { zh: "从前这里是一片森林。", pinyin: "cóngqián zhèlǐ shì yí piàn sēnlín", ko: "예전에 이곳은 숲이었어요." } },
        { zh: "除非", pinyin: "chú fēi", ko: "오직 ~해야만, ~하지 않는 한", pos: "접속사", hanja: "제비(除非) — '除'는 덜 제, '非'는 아닐 비.", ex: { zh: "除非你去，我才去。", pinyin: "chúfēi nǐ qù, wǒ cái qù", ko: "당신이 가야만 저도 갈게요." } },
        { zh: "除夕", pinyin: "chú xī", ko: "섣달그믐, 음력 12월 31일 밤", pos: "명사", hanja: "제석(除夕) — '除'는 덜 제, '夕'은 저녁 석.", ex: { zh: "除夕全家在一起吃饭。", pinyin: "chúxī quánjiā zài yìqǐ chī fàn", ko: "섣달그믐에는 온 가족이 함께 밥을 먹어요." } },
        { zh: "傍晚", pinyin: "bàng wǎn", ko: "해 질 무렵, 저녁 무렵", pos: "명사", hanja: "방만(傍晚) — '傍'은 곁 방, '晚'은 늦을 만.", ex: { zh: "傍晚我们去散步。", pinyin: "bàngwǎn wǒmen qù sànbù", ko: "해 질 무렵 우리는 산책하러 가요." } },
        { zh: "丙", pinyin: "bǐng", ko: "병(천간의 셋째), 세 번째, C 등급", pos: "명사", hanja: "병(丙) — '남녘 병'. 갑을병의 '병'.", ex: { zh: "他的成绩是丙等。", pinyin: "tā de chéngjì shì bǐng děng", ko: "그의 성적은 병(C)등급이에요." } },
        { zh: "吵架", pinyin: "chǎo jià", ko: "말다툼하다, 다투다", pos: "동사", hanja: "초가(吵架) — '吵'는 시끄러울 초, '架'는 시렁 가.", ex: { zh: "他们昨天吵架了。", pinyin: "tāmen zuótiān chǎojià le", ko: "그들은 어제 다퉜어요." } },
        { zh: "炒", pinyin: "chǎo", ko: "볶다", pos: "동사", hanja: "초(炒) — '볶을 초'.", ex: { zh: "妈妈在炒菜。", pinyin: "māma zài chǎocài", ko: "엄마가 요리를 볶고 있어요." } },
        { zh: "答应", pinyin: "dā ying", ko: "대답하다; 응하다, 승낙하다", pos: "동사", hanja: "답응(答應) — '答'은 대답할 답, '應'은 응할 응.", ex: { zh: "他答应帮我搬家。", pinyin: "tā dāying bāng wǒ bānjiā", ko: "그는 이사를 도와주기로 했어요." } },
        { zh: "打喷嚏", pinyin: "dǎ pēn tì", ko: "재채기하다", pos: "동사", hanja: "타분체(打噴嚏) — '噴'은 뿜을 분, '嚏'는 재채기 체.", ex: { zh: "他感冒了，一直打喷嚏。", pinyin: "tā gǎnmào le, yìzhí dǎ pēntì", ko: "그는 감기에 걸려 계속 재채기해요." } },
        { zh: "打招呼", pinyin: "dǎ zhāo hu", ko: "인사하다; (미리) 알리다", pos: "동사", hanja: "타초호(打招呼) — '招'는 부를 초, '呼'는 부를 호.", ex: { zh: "见到老师要打招呼。", pinyin: "jiàndào lǎoshī yào dǎ zhāohu", ko: "선생님을 만나면 인사해야 해요." } },
        { zh: "大象", pinyin: "dà xiàng", ko: "코끼리", pos: "명사", hanja: "대상(大象) — '大'는 큰 대, '象'은 코끼리 상.", ex: { zh: "动物园里有大象。", pinyin: "dòngwùyuán lǐ yǒu dàxiàng", ko: "동물원에 코끼리가 있어요." } },
        { zh: "滴", pinyin: "dī", ko: "방울; (액체가) 떨어지다", pos: "양사", hanja: "적(滴) — '물방울 적'.", ex: { zh: "天上掉下几滴雨。", pinyin: "tiān shàng diào xià jǐ dī yǔ", ko: "하늘에서 빗방울 몇 개가 떨어졌어요." } },
        { zh: "醋", pinyin: "cù", ko: "식초; (연애의) 질투", pos: "명사", hanja: "초(醋) — '식초 초'. '吃醋'는 질투하다.", ex: { zh: "做菜时放一点醋。", pinyin: "zuòcài shí fàng yìdiǎn cù", ko: "요리할 때 식초를 조금 넣어요." } },
        { zh: "岸", pinyin: "àn", ko: "물가, 기슭, 강가", pos: "명사", hanja: "안(岸) — '언덕 안'. (입력 trad 㟁는 이체자)", ex: { zh: "船靠岸了。", pinyin: "chuán kào àn le", ko: "배가 기슭에 닿았어요." } },
        { zh: "背", pinyin: "bēi", ko: "(등에) 지다, 업다", pos: "동사", hanja: "배(背) — '등 배'. 'bēi'로 읽으면 '등에 지다'.", ex: { zh: "他背着一个大包。", pinyin: "tā bēi zhe yí ge dà bāo", ko: "그는 큰 가방을 메고 있어요." } },
        { zh: "布", pinyin: "bù", ko: "천, 직물; 펴다, 배치하다", pos: "명사", hanja: "포(布) — '베 포'.", ex: { zh: "她买了一块布。", pinyin: "tā mǎi le yí kuài bù", ko: "그녀는 천 한 조각을 샀어요." } },
        { zh: "冲", pinyin: "chōng", ko: "(물로) 헹구다, 끼얹다; 돌진하다", pos: "동사", hanja: "충(沖) — '빌/물댈 충'.", ex: { zh: "他用热水冲了一杯咖啡。", pinyin: "tā yòng rèshuǐ chōng le yì bēi kāfēi", ko: "그는 뜨거운 물로 커피 한 잔을 탔어요." } },
        { zh: "倒", pinyin: "dào", ko: "따르다, 붓다; 오히려, 도리어", pos: "동사", hanja: "도(倒) — '넘어질 도'. 'dào'로 읽으면 '따르다', 부사로는 '오히려'.", ex: { zh: "请给我倒一杯水。", pinyin: "qǐng gěi wǒ dào yì bēi shuǐ", ko: "물 한 잔 따라 주세요." } },
        { zh: "报告", pinyin: "bào gào", ko: "보고하다; 보고(서), 리포트", pos: "명사", hanja: "보고(報告) — '報'는 갚을/알릴 보, '告'는 고할 고.", ex: { zh: "他写了一份报告。", pinyin: "tā xiě le yí fèn bàogào", ko: "그는 보고서 한 부를 작성했어요." } },
      ],
    },
  ],
};

export default themes;
