/**
 * H5 (HSK 5급) 보강 어휘 — 청크 f (200개).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되, 성씨·이체자·다음자 오독은 표준 병음으로 교정했어요.
 */
const themes = {
  themes: [
    {
      name: "HSK5 보강 — 동사",
      icon: "🔴",
      words: [
        { zh: "休闲", pinyin: "xiūxián", ko: "휴식을 취하다, 한가롭게 보내다; 레저", pos: "동사", hanja: "휴한(休閒) — '休'는 쉴 휴, '閒'은 한가할 한.", ex: { zh: "周末他喜欢在家休闲。", pinyin: "zhōumò tā xǐhuan zài jiā xiūxián", ko: "주말에 그는 집에서 한가롭게 쉬는 걸 좋아해요." } },
        { zh: "修改", pinyin: "xiūgǎi", ko: "수정하다, 고치다", pos: "동사", hanja: "수개(修改) — '修'는 닦을 수, '改'는 고칠 개.", ex: { zh: "请帮我修改这篇文章。", pinyin: "qǐng bāng wǒ xiūgǎi zhè piān wénzhāng", ko: "이 글을 좀 수정해 주세요." } },
        { zh: "叙述", pinyin: "xùshù", ko: "서술하다, 이야기하다", pos: "동사", hanja: "서술(敘述) — 한자 그대로.", ex: { zh: "他详细叙述了事情的经过。", pinyin: "tā xiángxì xùshù le shìqing de jīngguò", ko: "그는 일의 경과를 자세히 서술했어요." } },
        { zh: "宣布", pinyin: "xuānbù", ko: "선포하다, 발표하다", pos: "동사", hanja: "선포(宣布) — 한자 그대로.", ex: { zh: "公司宣布了新的政策。", pinyin: "gōngsī xuānbù le xīn de zhèngcè", ko: "회사는 새 정책을 발표했어요." } },
        { zh: "宣传", pinyin: "xuānchuán", ko: "선전하다, 홍보하다; 선전", pos: "동사", hanja: "선전(宣傳) — 한자 그대로.", ex: { zh: "他们在街上宣传环保。", pinyin: "tāmen zài jiē shang xuānchuán huánbǎo", ko: "그들은 거리에서 환경 보호를 홍보해요." } },
        { zh: "选举", pinyin: "xuǎnjǔ", ko: "선거하다, 뽑다; 선거", pos: "동사", hanja: "선거(選舉) — '選'은 가릴 선, '舉'는 들 거.", ex: { zh: "大家投票选举班长。", pinyin: "dàjiā tóupiào xuǎnjǔ bānzhǎng", ko: "모두 투표로 반장을 뽑아요." } },
        { zh: "寻找", pinyin: "xúnzhǎo", ko: "찾다, 구하다", pos: "동사", hanja: "심조(尋找) — '尋'은 찾을 심, '找'는 찾을 조.", ex: { zh: "他到处寻找丢失的钱包。", pinyin: "tā dàochù xúnzhǎo diūshī de qiánbāo", ko: "그는 잃어버린 지갑을 여기저기 찾았어요." } },
        { zh: "询问", pinyin: "xúnwèn", ko: "문의하다, 물어보다", pos: "동사", hanja: "순문(詢問) — '詢'은 물을 순, '問'은 물을 문.", ex: { zh: "我向他询问了价格。", pinyin: "wǒ xiàng tā xúnwèn le jiàgé", ko: "저는 그에게 가격을 문의했어요." } },
        { zh: "训练", pinyin: "xùnliàn", ko: "훈련하다; 훈련", pos: "동사", hanja: "훈련(訓練) — 한자 그대로.", ex: { zh: "运动员每天都要训练。", pinyin: "yùndòngyuán měi tiān dōu yào xùnliàn", ko: "운동선수는 매일 훈련해야 해요." } },
        { zh: "延长", pinyin: "yáncháng", ko: "연장하다, 늘이다", pos: "동사", hanja: "연장(延長) — '延'은 늘일 연, '長'은 길 장.", ex: { zh: "会议时间延长了一个小时。", pinyin: "huìyì shíjiān yáncháng le yí ge xiǎoshí", ko: "회의 시간이 한 시간 연장됐어요." } },
        { zh: "移动", pinyin: "yídòng", ko: "이동하다, 옮기다; 이동", pos: "동사", hanja: "이동(移動) — 한자 그대로.", ex: { zh: "请把桌子移动一下。", pinyin: "qǐng bǎ zhuōzi yídòng yíxià", ko: "책상을 좀 옮겨 주세요." } },
        { zh: "移民", pinyin: "yímín", ko: "이민하다; 이민자", pos: "동사", hanja: "이민(移民) — 한자 그대로.", ex: { zh: "他们一家移民到了加拿大。", pinyin: "tāmen yì jiā yímín dào le Jiānádà", ko: "그들 가족은 캐나다로 이민 갔어요." } },
        { zh: "议论", pinyin: "yìlùn", ko: "왈가왈부하다, 논하다; 의론", pos: "동사", hanja: "의론(議論) — '議'는 의논할 의, '論'은 논할 론.", ex: { zh: "大家议论着这件事。", pinyin: "dàjiā yìlùn zhe zhè jiàn shì", ko: "모두 이 일에 대해 이러쿵저러쿵해요." } },
        { zh: "应付", pinyin: "yìngfu", ko: "대응하다, 대처하다; 대충 때우다", pos: "동사", hanja: "응부(應付) — '應'은 응할 응, '付'는 줄 부.", ex: { zh: "他能应付各种问题。", pinyin: "tā néng yìngfu gè zhǒng wèntí", ko: "그는 온갖 문제에 잘 대처해요." } },
        { zh: "应用", pinyin: "yìngyòng", ko: "응용하다, 활용하다", pos: "동사", hanja: "응용(應用) — 한자 그대로.", ex: { zh: "把知识应用到工作中。", pinyin: "bǎ zhīshi yìngyòng dào gōngzuò zhōng", ko: "지식을 업무에 활용해요." } },
        { zh: "迎接", pinyin: "yíngjiē", ko: "맞이하다, 영접하다", pos: "동사", hanja: "영접(迎接) — '迎'은 맞을 영, '接'은 접할 접.", ex: { zh: "我们到机场迎接客人。", pinyin: "wǒmen dào jīchǎng yíngjiē kèren", ko: "우리는 공항에 손님을 마중 나가요." } },
        { zh: "拥抱", pinyin: "yōngbào", ko: "포옹하다, 껴안다", pos: "동사", hanja: "옹포(擁抱) — '擁'은 안을 옹, '抱'는 안을 포.", ex: { zh: "母亲紧紧拥抱着孩子。", pinyin: "mǔqīn jǐnjǐn yōngbào zhe háizi", ko: "어머니가 아이를 꼭 껴안고 있어요." } },
        { zh: "游览", pinyin: "yóulǎn", ko: "유람하다, 관광하다", pos: "동사", hanja: "유람(遊覽) — '遊'는 놀 유, '覽'은 볼 람.", ex: { zh: "我们游览了整个古城。", pinyin: "wǒmen yóulǎn le zhěnggè gǔchéng", ko: "우리는 옛 도시 전체를 둘러봤어요." } },
        { zh: "娱乐", pinyin: "yúlè", ko: "오락하다, 즐기다; 오락", pos: "동사", hanja: "오락(娛樂) — '娛'는 즐길 오, '樂'은 즐길 락.", ex: { zh: "看电影是一种娱乐。", pinyin: "kàn diànyǐng shì yì zhǒng yúlè", ko: "영화 보기는 일종의 오락이에요." } },
        { zh: "预报", pinyin: "yùbào", ko: "예보하다; 예보", pos: "동사", hanja: "예보(預報) — '預'는 미리 예, '報'는 알릴 보.", ex: { zh: "天气预报说明天有雨。", pinyin: "tiānqì yùbào shuō míngtiān yǒu yǔ", ko: "일기예보에서 내일 비가 온대요." } },
        { zh: "预订", pinyin: "yùdìng", ko: "예약하다, 미리 주문하다", pos: "동사", hanja: "예정(預訂) — '訂'은 정할 정. '미리 정하다=예약'.", ex: { zh: "我已经预订了房间。", pinyin: "wǒ yǐjīng yùdìng le fángjiān", ko: "저는 이미 방을 예약했어요." } },
        { zh: "预防", pinyin: "yùfáng", ko: "예방하다, 미리 막다", pos: "동사", hanja: "예방(預防) — 한자 그대로.", ex: { zh: "运动可以预防疾病。", pinyin: "yùndòng kěyǐ yùfáng jíbìng", ko: "운동은 질병을 예방할 수 있어요." } },
        { zh: "运输", pinyin: "yùnshū", ko: "운송하다, 수송하다; 운수", pos: "동사", hanja: "운수(運輸) — '運'은 옮길 운, '輸'는 보낼 수.", ex: { zh: "这些货物用火车运输。", pinyin: "zhèxiē huòwù yòng huǒchē yùnshū", ko: "이 화물들은 기차로 운송해요." } },
        { zh: "运用", pinyin: "yùnyòng", ko: "운용하다, 활용하다", pos: "동사", hanja: "운용(運用) — 한자 그대로.", ex: { zh: "他善于运用各种方法。", pinyin: "tā shànyú yùnyòng gè zhǒng fāngfǎ", ko: "그는 여러 방법을 잘 활용해요." } },
        { zh: "赞成", pinyin: "zànchéng", ko: "찬성하다, 동의하다", pos: "동사", hanja: "찬성(贊成) — 한자 그대로.", ex: { zh: "我赞成你的意见。", pinyin: "wǒ zànchéng nǐ de yìjiàn", ko: "저는 당신 의견에 찬성해요." } },
        { zh: "赞美", pinyin: "zànměi", ko: "찬미하다, 칭찬하다", pos: "동사", hanja: "찬미(贊美) — 한자 그대로.", ex: { zh: "大家都赞美她的勇敢。", pinyin: "dàjiā dōu zànměi tā de yǒnggǎn", ko: "모두 그녀의 용감함을 칭찬해요." } },
        { zh: "造成", pinyin: "zàochéng", ko: "초래하다, 야기하다", pos: "동사", hanja: "조성(造成) — '造'는 지을 조, '成'은 이룰 성.", ex: { zh: "粗心造成了这次错误。", pinyin: "cūxīn zàochéng le zhè cì cuòwù", ko: "부주의가 이번 실수를 초래했어요." } },
        { zh: "责备", pinyin: "zébèi", ko: "책망하다, 나무라다", pos: "동사", hanja: "책비(責備) — '責'은 꾸짖을 책, '備'는 갖출 비.", ex: { zh: "妈妈责备了他的粗心。", pinyin: "māma zébèi le tā de cūxīn", ko: "엄마는 그의 부주의를 나무랐어요." } },
        { zh: "摘", pinyin: "zhāi", ko: "따다, 떼다, 발췌하다", pos: "동사", hanja: "적(摘) — '딸 적'.", ex: { zh: "她在花园里摘花。", pinyin: "tā zài huāyuán lǐ zhāi huā", ko: "그녀는 정원에서 꽃을 따요." } },
        { zh: "粘贴", pinyin: "zhāntiē", ko: "붙이다, 부착하다", pos: "동사", hanja: "점첩(粘貼) — '粘'은 붙을 점, '貼'은 붙일 첩.", ex: { zh: "把照片粘贴在本子上。", pinyin: "bǎ zhàopiàn zhāntiē zài běnzi shang", ko: "사진을 공책에 붙여요." } },
        { zh: "展开", pinyin: "zhǎnkāi", ko: "펼치다, 전개하다", pos: "동사", hanja: "전개(展開) — '展'은 펼 전, '開'는 열 개.", ex: { zh: "他们展开了热烈的讨论。", pinyin: "tāmen zhǎnkāi le rèliè de tǎolùn", ko: "그들은 열띤 토론을 펼쳤어요." } },
        { zh: "展览", pinyin: "zhǎnlǎn", ko: "전시하다; 전람, 전시회", pos: "동사", hanja: "전람(展覽) — '展'은 펼 전, '覽'은 볼 람.", ex: { zh: "美术馆正在展览名画。", pinyin: "měishùguǎn zhèngzài zhǎnlǎn mínghuà", ko: "미술관에서 명화를 전시하고 있어요." } },
        { zh: "涨", pinyin: "zhǎng", ko: "오르다, 불어나다", pos: "동사", hanja: "창(漲) — '물 불을 창'. 물가가 오르다.", ex: { zh: "最近物价涨得很快。", pinyin: "zuìjìn wùjià zhǎng de hěn kuài", ko: "요즘 물가가 빠르게 올라요." } },
        { zh: "招待", pinyin: "zhāodài", ko: "접대하다, 대접하다", pos: "동사", hanja: "초대(招待) — '招'는 부를 초, '待'는 기다릴 대.", ex: { zh: "他热情地招待了客人。", pinyin: "tā rèqíng de zhāodài le kèren", ko: "그는 손님을 따뜻하게 대접했어요." } },
        { zh: "召开", pinyin: "zhàokāi", ko: "소집하다, 개최하다", pos: "동사", hanja: "소개(召開) — '召'는 부를 소, '開'는 열 개. '회의를 열다'.", ex: { zh: "公司召开了紧急会议。", pinyin: "gōngsī zhàokāi le jǐnjí huìyì", ko: "회사는 긴급 회의를 소집했어요." } },
        { zh: "着凉", pinyin: "zháoliáng", ko: "감기에 걸리다, 한기가 들다", pos: "동사", hanja: "착량(著涼) — '凉'은 서늘할 량. '찬 기운이 들다'.", ex: { zh: "小心别着凉了。", pinyin: "xiǎoxīn bié zháoliáng le", ko: "감기 걸리지 않게 조심하세요." } },
        { zh: "针对", pinyin: "zhēnduì", ko: "겨냥하다, 초점을 맞추다, ~에 대하여", pos: "동사", hanja: "침대(針對) — '針'은 바늘 침, '對'는 대할 대.", ex: { zh: "这个建议针对你的问题。", pinyin: "zhège jiànyì zhēnduì nǐ de wèntí", ko: "이 제안은 당신 문제를 겨냥한 거예요." } },
        { zh: "诊断", pinyin: "zhěnduàn", ko: "진단하다; 진단", pos: "동사", hanja: "진단(診斷) — 한자 그대로.", ex: { zh: "医生诊断他得了感冒。", pinyin: "yīshēng zhěnduàn tā dé le gǎnmào", ko: "의사는 그가 감기에 걸렸다고 진단했어요." } },
        { zh: "振动", pinyin: "zhèndòng", ko: "진동하다; 진동", pos: "동사", hanja: "진동(振動) — '振'은 떨칠 진, '動'은 움직일 동.", ex: { zh: "手机在桌上振动。", pinyin: "shǒujī zài zhuō shang zhèndòng", ko: "휴대폰이 책상 위에서 진동해요." } },
        { zh: "争论", pinyin: "zhēnglùn", ko: "논쟁하다, 다투다; 논쟁", pos: "동사", hanja: "쟁론(爭論) — '爭'은 다툴 쟁, '論'은 논할 론.", ex: { zh: "他们为这件事争论不休。", pinyin: "tāmen wèi zhè jiàn shì zhēnglùn bù xiū", ko: "그들은 이 일로 끝없이 논쟁해요." } },
        { zh: "征求", pinyin: "zhēngqiú", ko: "구하다, 묻다, 요청하다", pos: "동사", hanja: "징구(徵求) — '徵'은 부를 징, '求'는 구할 구. '의견을 구하다'.", ex: { zh: "我想征求你的意见。", pinyin: "wǒ xiǎng zhēngqiú nǐ de yìjiàn", ko: "당신의 의견을 구하고 싶어요." } },
        { zh: "挣钱", pinyin: "zhèngqián", ko: "돈을 벌다", pos: "동사", hanja: "쟁전(掙錢) — '掙'은 힘쓸 쟁, '錢'은 돈 전.", ex: { zh: "他努力工作挣钱。", pinyin: "tā nǔlì gōngzuò zhèng qián", ko: "그는 열심히 일해 돈을 벌어요." } },
        { zh: "睁", pinyin: "zhēng", ko: "(눈을) 뜨다", pos: "동사", hanja: "쟁(睜) — '눈 부릅뜰 쟁'.", ex: { zh: "他睁开眼睛看着我。", pinyin: "tā zhēng kāi yǎnjing kàn zhe wǒ", ko: "그는 눈을 떠 저를 바라봤어요." } },
        { zh: "执行", pinyin: "zhíxíng", ko: "집행하다, 실행하다", pos: "동사", hanja: "집행(執行) — '執'은 잡을 집, '行'은 행할 행.", ex: { zh: "我们必须执行这个计划。", pinyin: "wǒmen bìxū zhíxíng zhège jìhuà", ko: "우리는 이 계획을 반드시 실행해야 해요." } },
        { zh: "指导", pinyin: "zhǐdǎo", ko: "지도하다, 이끌다; 지도", pos: "동사", hanja: "지도(指導) — 한자 그대로.", ex: { zh: "老师耐心地指导学生。", pinyin: "lǎoshī nàixīn de zhǐdǎo xuésheng", ko: "선생님은 학생을 끈기 있게 지도해요." } },
        { zh: "指挥", pinyin: "zhǐhuī", ko: "지휘하다; 지휘(자)", pos: "동사", hanja: "지휘(指揮) — 한자 그대로.", ex: { zh: "他指挥乐队演奏。", pinyin: "tā zhǐhuī yuèduì yǎnzòu", ko: "그는 악단의 연주를 지휘해요." } },
        { zh: "制作", pinyin: "zhìzuò", ko: "제작하다, 만들다", pos: "동사", hanja: "제작(制作) — 한자 그대로.", ex: { zh: "这部电影制作得很精美。", pinyin: "zhè bù diànyǐng zhìzuò de hěn jīngměi", ko: "이 영화는 아주 정교하게 제작됐어요." } },
        { zh: "治疗", pinyin: "zhìliáo", ko: "치료하다; 치료", pos: "동사", hanja: "치료(治療) — 한자 그대로.", ex: { zh: "这种病很难治疗。", pinyin: "zhè zhǒng bìng hěn nán zhìliáo", ko: "이 병은 치료하기 어려워요." } },
        { zh: "主持", pinyin: "zhǔchí", ko: "주관하다, 사회를 보다", pos: "동사", hanja: "주지(主持) — '主'는 주인 주, '持'는 가질 지.", ex: { zh: "她主持了今天的会议。", pinyin: "tā zhǔchí le jīntiān de huìyì", ko: "그녀가 오늘 회의를 진행했어요." } },
        { zh: "主张", pinyin: "zhǔzhāng", ko: "주장하다; 주장", pos: "동사", hanja: "주장(主張) — 한자 그대로.", ex: { zh: "我主张多听别人的意见。", pinyin: "wǒ zhǔzhāng duō tīng biéren de yìjiàn", ko: "저는 남의 의견을 많이 들어야 한다고 봐요." } },
        { zh: "煮", pinyin: "zhǔ", ko: "삶다, 끓이다, 익히다", pos: "동사", hanja: "자(煮) — '삶을 자'.", ex: { zh: "妈妈在厨房煮饺子。", pinyin: "māma zài chúfáng zhǔ jiǎozi", ko: "엄마가 부엌에서 만두를 삶아요." } },
        { zh: "嘱咐", pinyin: "zhǔfù", ko: "당부하다, 분부하다", pos: "동사", hanja: "촉부(囑咐) — '囑'은 부탁할 촉, '咐'는 분부할 부.", ex: { zh: "妈妈嘱咐我路上小心。", pinyin: "māma zhǔfù wǒ lùshang xiǎoxīn", ko: "엄마는 길 조심하라고 당부했어요." } },
        { zh: "注册", pinyin: "zhùcè", ko: "등록하다, 가입하다", pos: "동사", hanja: "주책(註冊) — '註'는 주낼 주, '冊'은 책 책. '명부에 올리다=등록'.", ex: { zh: "我注册了一个新账号。", pinyin: "wǒ zhùcè le yí ge xīn zhànghào", ko: "저는 새 계정을 등록했어요." } },
        { zh: "祝福", pinyin: "zhùfú", ko: "축복하다; 축복", pos: "동사", hanja: "축복(祝福) — 한자 그대로.", ex: { zh: "我们祝福你前程似锦。", pinyin: "wǒmen zhùfú nǐ qiánchéng sì jǐn", ko: "우리는 당신의 밝은 앞날을 빌어요." } },
        { zh: "抓紧", pinyin: "zhuājǐn", ko: "꽉 잡다, 서두르다, 박차를 가하다", pos: "동사", hanja: "조긴(抓緊) — '抓'는 긁을 조, '緊'은 긴할 긴.", ex: { zh: "时间不多，要抓紧。", pinyin: "shíjiān bù duō, yào zhuājǐn", ko: "시간이 별로 없으니 서둘러야 해요." } },
        { zh: "转变", pinyin: "zhuǎnbiàn", ko: "전환하다, 바뀌다; 전환", pos: "동사", hanja: "전변(轉變) — '轉'은 구를 전, '變'은 변할 변.", ex: { zh: "他的态度转变了很多。", pinyin: "tā de tàidu zhuǎnbiàn le hěn duō", ko: "그의 태도가 많이 바뀌었어요." } },
        { zh: "转告", pinyin: "zhuǎngào", ko: "전하다, 전달하다", pos: "동사", hanja: "전고(轉告) — '轉'은 구를 전, '告'는 알릴 고.", ex: { zh: "请转告他明天开会。", pinyin: "qǐng zhuǎngào tā míngtiān kāihuì", ko: "내일 회의한다고 그에게 전해 주세요." } },
        { zh: "装", pinyin: "zhuāng", ko: "담다, 설치하다, ~인 척하다, 꾸미다", pos: "동사", hanja: "장(裝) — '꾸밀 장'.", ex: { zh: "他把书装进包里。", pinyin: "tā bǎ shū zhuāng jìn bāo lǐ", ko: "그는 책을 가방에 담았어요." } },
        { zh: "装饰", pinyin: "zhuāngshì", ko: "장식하다; 장식", pos: "동사", hanja: "장식(裝飾) — 한자 그대로.", ex: { zh: "他们用花装饰房间。", pinyin: "tāmen yòng huā zhuāngshì fángjiān", ko: "그들은 꽃으로 방을 장식해요." } },
        { zh: "追求", pinyin: "zhuīqiú", ko: "추구하다, 쫓다, 구애하다", pos: "동사", hanja: "추구(追求) — 한자 그대로.", ex: { zh: "他一直追求自己的梦想。", pinyin: "tā yìzhí zhuīqiú zìjǐ de mèngxiǎng", ko: "그는 줄곧 자신의 꿈을 좇아요." } },
        { zh: "咨询", pinyin: "zīxún", ko: "자문하다, 상담하다; 자문", pos: "동사", hanja: "자순(諮詢) — '諮'는 물을 자, '詢'은 물을 순.", ex: { zh: "你可以向医生咨询。", pinyin: "nǐ kěyǐ xiàng yīshēng zīxún", ko: "의사에게 상담을 받아 보세요." } },
        { zh: "阻止", pinyin: "zǔzhǐ", ko: "저지하다, 막다", pos: "동사", hanja: "조지(阻止) — '阻'는 막을 조, '止'는 그칠 지.", ex: { zh: "没人能阻止他离开。", pinyin: "méi rén néng zǔzhǐ tā líkāi", ko: "아무도 그가 떠나는 걸 막을 수 없어요." } },
        { zh: "组合", pinyin: "zǔhé", ko: "조합하다, 짜 맞추다; 조합", pos: "동사", hanja: "조합(組合) — 한자 그대로.", ex: { zh: "把这些零件组合起来。", pinyin: "bǎ zhèxiē língjiàn zǔhé qǐlái", ko: "이 부품들을 조합해 보세요." } },
        { zh: "尊敬", pinyin: "zūnjìng", ko: "존경하다", pos: "동사", hanja: "존경(尊敬) — 한자 그대로.", ex: { zh: "我们都很尊敬这位老师。", pinyin: "wǒmen dōu hěn zūnjìng zhè wèi lǎoshī", ko: "우리는 이 선생님을 무척 존경해요." } },
        { zh: "遵守", pinyin: "zūnshǒu", ko: "준수하다, 지키다", pos: "동사", hanja: "준수(遵守) — 한자 그대로.", ex: { zh: "每个人都要遵守规则。", pinyin: "měi ge rén dōu yào zūnshǒu guīzé", ko: "모두가 규칙을 지켜야 해요." } },
        { zh: "晕", pinyin: "yūn", ko: "어지럽다, 기절하다", pos: "동사", hanja: "운(暈) — '어지러울 운'.", ex: { zh: "她突然晕倒了。", pinyin: "tā tūrán yūndǎo le", ko: "그녀가 갑자기 쓰러졌어요." } },
        { zh: "占线", pinyin: "zhànxiàn", ko: "통화 중이다", pos: "동사", hanja: "점선(占線) — '占'은 차지할 점, '線'은 줄 선. '전화선이 차다'.", ex: { zh: "他的电话一直占线。", pinyin: "tā de diànhuà yìzhí zhànxiàn", ko: "그의 전화가 계속 통화 중이에요." } },
        { zh: "醉", pinyin: "zuì", ko: "취하다", pos: "동사", hanja: "취(醉) — '취할 취'.", ex: { zh: "他喝多了，有点醉。", pinyin: "tā hē duō le, yǒudiǎn zuì", ko: "그는 많이 마셔서 좀 취했어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 명사·추상",
      icon: "🔴",
      words: [
        { zh: "形状", pinyin: "xíngzhuàng", ko: "형상, 모양", pos: "명사", hanja: "형상(形狀) — '形'은 모양 형, '狀'은 형상 상.", ex: { zh: "这块石头的形状很奇怪。", pinyin: "zhè kuài shítou de xíngzhuàng hěn qíguài", ko: "이 돌의 모양은 아주 이상해요." } },
        { zh: "性质", pinyin: "xìngzhì", ko: "성질, 본질", pos: "명사", hanja: "성질(性質) — 한자 그대로.", ex: { zh: "这两件事性质完全不同。", pinyin: "zhè liǎng jiàn shì xìngzhì wánquán bùtóng", ko: "이 두 일은 성질이 완전히 달라요." } },
        { zh: "兄弟", pinyin: "xiōngdì", ko: "형제, 동생", pos: "명사", hanja: "형제(兄弟) — '兄'은 형 형, '弟'는 아우 제.", ex: { zh: "他们是亲兄弟。", pinyin: "tāmen shì qīn xiōngdì", ko: "그들은 친형제예요." } },
        { zh: "胸", pinyin: "xiōng", ko: "가슴", pos: "명사", hanja: "흉(胸) — '가슴 흉'.", ex: { zh: "他用手捂住胸口。", pinyin: "tā yòng shǒu wǔ zhù xiōngkǒu", ko: "그는 손으로 가슴을 감쌌어요." } },
        { zh: "学期", pinyin: "xuéqī", ko: "학기", pos: "명사", hanja: "학기(學期) — 한자 그대로.", ex: { zh: "这个学期我选了五门课。", pinyin: "zhège xuéqī wǒ xuǎn le wǔ mén kè", ko: "이번 학기에 저는 다섯 과목을 신청했어요." } },
        { zh: "学术", pinyin: "xuéshù", ko: "학술", pos: "명사", hanja: "학술(學術) — 한자 그대로.", ex: { zh: "他参加了一个学术会议。", pinyin: "tā cānjiā le yí ge xuéshù huìyì", ko: "그는 학술 회의에 참석했어요." } },
        { zh: "学问", pinyin: "xuéwèn", ko: "학문, 지식", pos: "명사", hanja: "학문(學問) — 한자 그대로.", ex: { zh: "这位老人很有学问。", pinyin: "zhè wèi lǎorén hěn yǒu xuéwen", ko: "이 노인은 학식이 깊어요." } },
        { zh: "宴会", pinyin: "yànhuì", ko: "연회, 잔치", pos: "명사", hanja: "연회(宴會) — '宴'은 잔치 연, '會'는 모일 회.", ex: { zh: "今晚有一场盛大的宴会。", pinyin: "jīnwǎn yǒu yì chǎng shèngdà de yànhuì", ko: "오늘 밤 성대한 연회가 있어요." } },
        { zh: "阳台", pinyin: "yángtái", ko: "발코니, 베란다", pos: "명사", hanja: "양대(陽臺) — '陽'은 볕 양, '臺'는 대 대.", ex: { zh: "她在阳台上晒衣服。", pinyin: "tā zài yángtái shang shài yīfu", ko: "그녀는 발코니에서 빨래를 말려요." } },
        { zh: "样式", pinyin: "yàngshì", ko: "양식, 스타일", pos: "명사", hanja: "양식(樣式) — '樣'은 모양 양, '式'은 법 식.", ex: { zh: "这件衣服的样式很流行。", pinyin: "zhè jiàn yīfu de yàngshì hěn liúxíng", ko: "이 옷의 스타일은 아주 유행이에요." } },
        { zh: "腰", pinyin: "yāo", ko: "허리", pos: "명사", hanja: "요(腰) — '허리 요'.", ex: { zh: "他的腰受伤了。", pinyin: "tā de yāo shòushāng le", ko: "그는 허리를 다쳤어요." } },
        { zh: "业务", pinyin: "yèwù", ko: "업무, 비즈니스", pos: "명사", hanja: "업무(業務) — 한자 그대로.", ex: { zh: "他对业务很熟悉。", pinyin: "tā duì yèwù hěn shúxī", ko: "그는 업무에 아주 익숙해요." } },
        { zh: "夜", pinyin: "yè", ko: "밤", pos: "명사", hanja: "야(夜) — '밤 야'.", ex: { zh: "夜深了，快睡吧。", pinyin: "yè shēn le, kuài shuì ba", ko: "밤이 깊었으니 어서 자요." } },
        { zh: "液体", pinyin: "yètǐ", ko: "액체", pos: "명사", hanja: "액체(液體) — 한자 그대로.", ex: { zh: "水是一种液体。", pinyin: "shuǐ shì yì zhǒng yètǐ", ko: "물은 일종의 액체예요." } },
        { zh: "一辈子", pinyin: "yībèizi", ko: "한평생, 일생", pos: "명사", hanja: "일배자(一輩子) — '輩'는 무리 배. '한 세대 분량의 평생'.", ex: { zh: "他们一辈子都住在这里。", pinyin: "tāmen yíbèizi dōu zhù zài zhèlǐ", ko: "그들은 평생 여기서 살았어요." } },
        { zh: "疑问", pinyin: "yíwèn", ko: "의문, 의혹", pos: "명사", hanja: "의문(疑問) — 한자 그대로.", ex: { zh: "我对这件事有疑问。", pinyin: "wǒ duì zhè jiàn shì yǒu yíwèn", ko: "저는 이 일에 의문이 있어요." } },
        { zh: "义务", pinyin: "yìwù", ko: "의무", pos: "명사", hanja: "의무(義務) — 한자 그대로.", ex: { zh: "纳税是公民的义务。", pinyin: "nàshuì shì gōngmín de yìwù", ko: "납세는 국민의 의무예요." } },
        { zh: "银", pinyin: "yín", ko: "은(銀)", pos: "명사", hanja: "은(銀) — '은 은'.", ex: { zh: "她戴着一条银项链。", pinyin: "tā dài zhe yì tiáo yín xiàngliàn", ko: "그녀는 은 목걸이를 하고 있어요." } },
        { zh: "英雄", pinyin: "yīngxióng", ko: "영웅", pos: "명사", hanja: "영웅(英雄) — 한자 그대로.", ex: { zh: "他是大家心中的英雄。", pinyin: "tā shì dàjiā xīnzhōng de yīngxióng", ko: "그는 모두의 마음속 영웅이에요." } },
        { zh: "营养", pinyin: "yíngyǎng", ko: "영양", pos: "명사", hanja: "영양(營養) — 한자 그대로.", ex: { zh: "蔬菜里有丰富的营养。", pinyin: "shūcài lǐ yǒu fēngfù de yíngyǎng", ko: "채소에는 풍부한 영양이 있어요." } },
        { zh: "影子", pinyin: "yǐngzi", ko: "그림자", pos: "명사", hanja: "영자(影子) — '影'은 그림자 영.", ex: { zh: "墙上有一个长长的影子。", pinyin: "qiáng shang yǒu yí ge cháng cháng de yǐngzi", ko: "벽에 긴 그림자가 있어요." } },
        { zh: "硬币", pinyin: "yìngbì", ko: "동전", pos: "명사", hanja: "경폐(硬幣) — '硬'은 굳을 경, '幣'는 화폐 폐.", ex: { zh: "他口袋里有几枚硬币。", pinyin: "tā kǒudài lǐ yǒu jǐ méi yìngbì", ko: "그의 주머니에 동전 몇 개가 있어요." } },
        { zh: "硬件", pinyin: "yìngjiàn", ko: "하드웨어", pos: "명사", hanja: "경건(硬件) — '硬'은 굳을 경, '件'은 물건 건.", ex: { zh: "这台电脑的硬件很好。", pinyin: "zhè tái diànnǎo de yìngjiàn hěn hǎo", ko: "이 컴퓨터의 하드웨어는 아주 좋아요." } },
        { zh: "用途", pinyin: "yòngtú", ko: "용도, 쓰임새", pos: "명사", hanja: "용도(用途) — '用'은 쓸 용, '途'는 길 도.", ex: { zh: "这种工具用途很广。", pinyin: "zhè zhǒng gōngjù yòngtú hěn guǎng", ko: "이 도구는 용도가 넓어요." } },
        { zh: "优势", pinyin: "yōushì", ko: "우세, 우위, 강점", pos: "명사", hanja: "우세(優勢) — '優'는 넉넉할 우, '勢'는 형세 세.", ex: { zh: "我们队有明显的优势。", pinyin: "wǒmen duì yǒu míngxiǎn de yōushì", ko: "우리 팀은 뚜렷한 우위가 있어요." } },
        { zh: "邮局", pinyin: "yóujú", ko: "우체국", pos: "명사", hanja: "우국(郵局) — '郵'은 우편 우, '局'은 판 국.", ex: { zh: "我去邮局寄包裹。", pinyin: "wǒ qù yóujú jì bāoguǒ", ko: "저는 우체국에 소포를 부치러 가요." } },
        { zh: "幼儿园", pinyin: "yòuéryuán", ko: "유치원", pos: "명사", hanja: "유아원(幼兒園) — '幼'는 어릴 유, '兒'는 아이 아.", ex: { zh: "妹妹在上幼儿园。", pinyin: "mèimei zài shàng yòu'éryuán", ko: "여동생은 유치원에 다녀요." } },
        { zh: "宇宙", pinyin: "yǔzhòu", ko: "우주", pos: "명사", hanja: "우주(宇宙) — 한자 그대로.", ex: { zh: "宇宙非常广阔。", pinyin: "yǔzhòu fēicháng guǎngkuò", ko: "우주는 매우 광활해요." } },
        { zh: "语气", pinyin: "yǔqì", ko: "어조, 말투", pos: "명사", hanja: "어기(語氣) — '語'는 말씀 어, '氣'는 기운 기.", ex: { zh: "他说话的语气很温和。", pinyin: "tā shuōhuà de yǔqì hěn wēnhé", ko: "그의 말투는 아주 부드러워요." } },
        { zh: "玉米", pinyin: "yùmǐ", ko: "옥수수", pos: "명사", hanja: "옥미(玉米) — '玉'은 구슬 옥, '米'는 쌀 미.", ex: { zh: "农民在田里种玉米。", pinyin: "nóngmín zài tián lǐ zhòng yùmǐ", ko: "농부가 밭에 옥수수를 심어요." } },
        { zh: "原料", pinyin: "yuánliào", ko: "원료", pos: "명사", hanja: "원료(原料) — 한자 그대로.", ex: { zh: "这是制作面包的原料。", pinyin: "zhè shì zhìzuò miànbāo de yuánliào", ko: "이것은 빵을 만드는 원료예요." } },
        { zh: "原则", pinyin: "yuánzé", ko: "원칙", pos: "명사", hanja: "원칙(原則) — 한자 그대로.", ex: { zh: "做事要有原则。", pinyin: "zuòshì yào yǒu yuánzé", ko: "일을 할 때는 원칙이 있어야 해요." } },
        { zh: "缘故", pinyin: "yuángù", ko: "까닭, 이유", pos: "명사", hanja: "연고(緣故) — '緣'은 인연 연, '故'는 연고 고.", ex: { zh: "不知什么缘故，他没来。", pinyin: "bù zhī shénme yuángù, tā méi lái", ko: "무슨 까닭인지 그는 오지 않았어요." } },
        { zh: "愿望", pinyin: "yuànwàng", ko: "소원, 바람", pos: "명사", hanja: "원망(願望) — '願'은 원할 원, '望'은 바랄 망. '바람·소원'(원망怨望과 무관). 가짜동족어 주의!", ex: { zh: "他终于实现了愿望。", pinyin: "tā zhōngyú shíxiàn le yuànwàng", ko: "그는 마침내 소원을 이뤘어요." } },
        { zh: "运气", pinyin: "yùnqi", ko: "운, 운수", pos: "명사", hanja: "운기(運氣) — '運'은 옮길 운, '氣'는 기운 기.", ex: { zh: "今天我的运气真好。", pinyin: "jīntiān wǒ de yùnqi zhēn hǎo", ko: "오늘 제 운이 정말 좋아요." } },
        { zh: "灾害", pinyin: "zāihài", ko: "재해, 재난", pos: "명사", hanja: "재해(災害) — '災'는 재앙 재, '害'는 해할 해.", ex: { zh: "这次地震是严重的自然灾害。", pinyin: "zhè cì dìzhèn shì yánzhòng de zìrán zāihài", ko: "이번 지진은 심각한 자연재해예요." } },
        { zh: "战争", pinyin: "zhànzhēng", ko: "전쟁", pos: "명사", hanja: "전쟁(戰爭) — '戰'은 싸울 전, '爭'은 다툴 쟁.", ex: { zh: "战争给人们带来痛苦。", pinyin: "zhànzhēng gěi rénmen dàilái tòngkǔ", ko: "전쟁은 사람들에게 고통을 줘요." } },
        { zh: "账户", pinyin: "zhànghù", ko: "계좌, 계정", pos: "명사", hanja: "장호(賬戶) — '賬'은 장부 장, '戶'는 지게 호.", ex: { zh: "请输入你的账户密码。", pinyin: "qǐng shūrù nǐ de zhànghù mìmǎ", ko: "계정 비밀번호를 입력하세요." } },
        { zh: "哲学", pinyin: "zhéxué", ko: "철학", pos: "명사", hanja: "철학(哲學) — 한자 그대로.", ex: { zh: "他对哲学很感兴趣。", pinyin: "tā duì zhéxué hěn gǎn xìngqù", ko: "그는 철학에 관심이 많아요." } },
        { zh: "真理", pinyin: "zhēnlǐ", ko: "진리", pos: "명사", hanja: "진리(真理) — 한자 그대로.", ex: { zh: "科学家追求真理。", pinyin: "kēxuéjiā zhuīqiú zhēnlǐ", ko: "과학자는 진리를 추구해요." } },
        { zh: "枕头", pinyin: "zhěntou", ko: "베개", pos: "명사", hanja: "침두(枕頭) — '枕'은 베개 침, '頭'는 머리 두.", ex: { zh: "这个枕头很软。", pinyin: "zhège zhěntou hěn ruǎn", ko: "이 베개는 아주 푹신해요." } },
        { zh: "证件", pinyin: "zhèngjiàn", ko: "증명서, 신분증", pos: "명사", hanja: "증건(證件) — '證'은 증거 증, '件'은 물건 건.", ex: { zh: "请出示你的证件。", pinyin: "qǐng chūshì nǐ de zhèngjiàn", ko: "신분증을 제시해 주세요." } },
        { zh: "证据", pinyin: "zhèngjù", ko: "증거", pos: "명사", hanja: "증거(證據) — 한자 그대로.", ex: { zh: "警察找到了重要证据。", pinyin: "jǐngchá zhǎodào le zhòngyào zhèngjù", ko: "경찰이 중요한 증거를 찾았어요." } },
        { zh: "政治", pinyin: "zhèngzhì", ko: "정치", pos: "명사", hanja: "정치(政治) — 한자 그대로.", ex: { zh: "他对政治不太关心。", pinyin: "tā duì zhèngzhì bú tài guānxīn", ko: "그는 정치에 별로 관심이 없어요." } },
        { zh: "支票", pinyin: "zhīpiào", ko: "수표", pos: "명사", hanja: "지표(支票) — '支'는 지탱할 지, '票'는 표 표.", ex: { zh: "他用支票付了款。", pinyin: "tā yòng zhīpiào fù le kuǎn", ko: "그는 수표로 돈을 냈어요." } },
        { zh: "执照", pinyin: "zhízhào", ko: "면허증, 허가증", pos: "명사", hanja: "집조(執照) — '執'은 잡을 집, '照'는 비칠 조.", ex: { zh: "开车要有驾驶执照。", pinyin: "kāichē yào yǒu jiàshǐ zhízhào", ko: "운전하려면 운전면허증이 있어야 해요." } },
        { zh: "秩序", pinyin: "zhìxù", ko: "질서", pos: "명사", hanja: "질서(秩序) — 한자 그대로.", ex: { zh: "请大家保持秩序。", pinyin: "qǐng dàjiā bǎochí zhìxù", ko: "모두 질서를 지켜 주세요." } },
        { zh: "中介", pinyin: "zhōngjiè", ko: "중개(인), 매개", pos: "명사", hanja: "중개(中介) — '中'은 가운데 중, '介'는 끼일 개.", ex: { zh: "我们通过中介租了房子。", pinyin: "wǒmen tōngguò zhōngjiè zū le fángzi", ko: "우리는 중개를 통해 집을 빌렸어요." } },
        { zh: "中心", pinyin: "zhōngxīn", ko: "중심, 센터", pos: "명사", hanja: "중심(中心) — 한자 그대로.", ex: { zh: "市中心很热闹。", pinyin: "shì zhōngxīn hěn rènao", ko: "시내 중심은 아주 번화해요." } },
        { zh: "重量", pinyin: "zhòngliàng", ko: "중량, 무게", pos: "명사", hanja: "중량(重量) — 한자 그대로.", ex: { zh: "这个包裹的重量超标了。", pinyin: "zhège bāoguǒ de zhòngliàng chāobiāo le", ko: "이 소포는 중량이 기준을 초과했어요." } },
        { zh: "竹子", pinyin: "zhúzi", ko: "대나무", pos: "명사", hanja: "죽자(竹子) — '竹'은 대 죽.", ex: { zh: "熊猫喜欢吃竹子。", pinyin: "xióngmāo xǐhuan chī zhúzi", ko: "판다는 대나무 먹는 걸 좋아해요." } },
        { zh: "主观", pinyin: "zhǔguān", ko: "주관(적인)", pos: "명사", hanja: "주관(主觀) — 한자 그대로.", ex: { zh: "你的看法太主观了。", pinyin: "nǐ de kànfǎ tài zhǔguān le", ko: "당신의 견해는 너무 주관적이에요." } },
        { zh: "主人", pinyin: "zhǔrén", ko: "주인, 집주인", pos: "명사", hanja: "주인(主人) — 한자 그대로.", ex: { zh: "狗一直跟着它的主人。", pinyin: "gǒu yìzhí gēn zhe tā de zhǔrén", ko: "개는 줄곧 주인을 따라다녀요." } },
        { zh: "主席", pinyin: "zhǔxí", ko: "주석, 의장", pos: "명사", hanja: "주석(主席) — '主'는 주인 주, '席'은 자리 석.", ex: { zh: "他被选为大会主席。", pinyin: "tā bèi xuǎn wéi dàhuì zhǔxí", ko: "그는 대회 의장으로 선출됐어요." } },
        { zh: "专家", pinyin: "zhuānjiā", ko: "전문가", pos: "명사", hanja: "전가(專家) — '專'은 오로지 전, '家'는 집 가.", ex: { zh: "他是这方面的专家。", pinyin: "tā shì zhè fāngmiàn de zhuānjiā", ko: "그는 이 분야의 전문가예요." } },
        { zh: "状态", pinyin: "zhuàngtài", ko: "상태", pos: "명사", hanja: "상태(狀態) — 한자 그대로.", ex: { zh: "他今天的状态不错。", pinyin: "tā jīntiān de zhuàngtài búcuò", ko: "그는 오늘 컨디션이 좋아요." } },
        { zh: "姿势", pinyin: "zīshì", ko: "자세, 포즈", pos: "명사", hanja: "자세(姿勢) — '姿'는 모양 자, '勢'는 형세 세.", ex: { zh: "她的坐姿势很端正。", pinyin: "tā de zuò zīshì hěn duānzhèng", ko: "그녀의 앉은 자세는 아주 반듯해요." } },
        { zh: "资格", pinyin: "zīgé", ko: "자격", pos: "명사", hanja: "자격(資格) — 한자 그대로.", ex: { zh: "他有参赛的资格。", pinyin: "tā yǒu cānsài de zīgé", ko: "그는 시합에 참가할 자격이 있어요." } },
        { zh: "资金", pinyin: "zījīn", ko: "자금", pos: "명사", hanja: "자금(資金) — 한자 그대로.", ex: { zh: "公司缺少资金。", pinyin: "gōngsī quēshǎo zījīn", ko: "회사는 자금이 부족해요." } },
        { zh: "资料", pinyin: "zīliào", ko: "자료", pos: "명사", hanja: "자료(資料) — 한자 그대로.", ex: { zh: "我收集了很多资料。", pinyin: "wǒ shōují le hěn duō zīliào", ko: "저는 많은 자료를 모았어요." } },
        { zh: "字幕", pinyin: "zìmù", ko: "자막", pos: "명사", hanja: "자막(字幕) — '字'는 글자 자, '幕'은 장막 막.", ex: { zh: "这部电影有中文字幕。", pinyin: "zhè bù diànyǐng yǒu Zhōngwén zìmù", ko: "이 영화는 중국어 자막이 있어요." } },
        { zh: "宗教", pinyin: "zōngjiào", ko: "종교", pos: "명사", hanja: "종교(宗教) — 한자 그대로.", ex: { zh: "世界上有许多宗教。", pinyin: "shìjiè shang yǒu xǔduō zōngjiào", ko: "세계에는 많은 종교가 있어요." } },
        { zh: "总裁", pinyin: "zǒngcái", ko: "총재, 회장, CEO", pos: "명사", hanja: "총재(總裁) — '總'은 거느릴 총, '裁'는 마를 재.", ex: { zh: "他是这家公司的总裁。", pinyin: "tā shì zhè jiā gōngsī de zǒngcái", ko: "그는 이 회사의 회장이에요." } },
        { zh: "总理", pinyin: "zǒnglǐ", ko: "총리", pos: "명사", hanja: "총리(總理) — 한자 그대로.", ex: { zh: "总理发表了重要讲话。", pinyin: "zǒnglǐ fābiǎo le zhòngyào jiǎnghuà", ko: "총리가 중요한 연설을 했어요." } },
        { zh: "总统", pinyin: "zǒngtǒng", ko: "대통령", pos: "명사", hanja: "총통(總統) — '統'은 거느릴 통. 한국어로는 '대통령'. 가짜동족어 주의!", ex: { zh: "总统访问了这个国家。", pinyin: "zǒngtǒng fǎngwèn le zhège guójiā", ko: "대통령이 이 나라를 방문했어요." } },
        { zh: "祖国", pinyin: "zǔguó", ko: "조국", pos: "명사", hanja: "조국(祖國) — '祖'는 조상 조, '國'은 나라 국.", ex: { zh: "我热爱我的祖国。", pinyin: "wǒ rè'ài wǒ de zǔguó", ko: "저는 제 조국을 사랑해요." } },
        { zh: "祖先", pinyin: "zǔxiān", ko: "조상, 선조", pos: "명사", hanja: "조선(祖先) — '祖'는 조상 조, '先'은 먼저 선.", ex: { zh: "我们要记住祖先的智慧。", pinyin: "wǒmen yào jìzhù zǔxiān de zhìhuì", ko: "우리는 조상의 지혜를 기억해야 해요." } },
        { zh: "罪犯", pinyin: "zuìfàn", ko: "범죄자, 죄인", pos: "명사", hanja: "죄범(罪犯) — '罪'는 허물 죄, '犯'은 범할 범.", ex: { zh: "警察抓住了罪犯。", pinyin: "jǐngchá zhuāzhù le zuìfàn", ko: "경찰이 범죄자를 붙잡았어요." } },
        { zh: "作文", pinyin: "zuòwén", ko: "작문, 글짓기", pos: "명사", hanja: "작문(作文) — 한자 그대로.", ex: { zh: "老师让我们写一篇作文。", pinyin: "lǎoshī ràng wǒmen xiě yì piān zuòwén", ko: "선생님이 우리에게 작문을 쓰게 했어요." } },
        { zh: "整体", pinyin: "zhěngtǐ", ko: "전체, 총체", pos: "명사", hanja: "정체(整體) — '整'은 가지런할 정, '體'는 몸 체.", ex: { zh: "要从整体上考虑问题。", pinyin: "yào cóng zhěngtǐ shang kǎolǜ wèntí", ko: "문제를 전체적으로 고려해야 해요." } },
        { zh: "中旬", pinyin: "zhōngxún", ko: "중순", pos: "명사", hanja: "중순(中旬) — '旬'은 열흘 순.", ex: { zh: "他打算这个月中旬出发。", pinyin: "tā dǎsuàn zhège yuè zhōngxún chūfā", ko: "그는 이달 중순에 출발할 계획이에요." } },
      ],
    },
    {
      name: "HSK5 보강 — 형용사·상태",
      icon: "🔴",
      words: [
        { zh: "幸运", pinyin: "xìngyùn", ko: "운이 좋다, 행운의; 행운", pos: "형용사", hanja: "행운(幸運) — '幸'은 다행 행, '運'은 옮길 운.", ex: { zh: "我很幸运地通过了考试。", pinyin: "wǒ hěn xìngyùn de tōngguò le kǎoshì", ko: "저는 운 좋게 시험에 합격했어요." } },
        { zh: "雄伟", pinyin: "xióngwěi", ko: "웅장하다, 위풍당당하다", pos: "형용사", hanja: "웅위(雄偉) — '雄'은 수컷 웅, '偉'는 클 위.", ex: { zh: "长城非常雄伟。", pinyin: "Chángchéng fēicháng xióngwěi", ko: "만리장성은 매우 웅장해요." } },
        { zh: "虚心", pinyin: "xūxīn", ko: "겸손하다, 마음을 비우다", pos: "형용사", hanja: "허심(虛心) — '虛'는 빌 허, '心'은 마음 심. '마음을 비워 겸손하다'.", ex: { zh: "他虚心向别人学习。", pinyin: "tā xūxīn xiàng biéren xuéxí", ko: "그는 겸손하게 남에게 배워요." } },
        { zh: "迅速", pinyin: "xùnsù", ko: "신속하다, 빠르다", pos: "형용사", hanja: "신속(迅速) — '迅'은 빠를 신, '速'은 빠를 속.", ex: { zh: "他迅速地做出了反应。", pinyin: "tā xùnsù de zuò chū le fǎnyìng", ko: "그는 신속하게 반응했어요." } },
        { zh: "严肃", pinyin: "yánsù", ko: "엄숙하다, 진지하다", pos: "형용사", hanja: "엄숙(嚴肅) — '嚴'은 엄할 엄, '肅'은 엄숙할 숙.", ex: { zh: "他表情很严肃。", pinyin: "tā biǎoqíng hěn yánsù", ko: "그의 표정은 매우 진지해요." } },
        { zh: "痒", pinyin: "yǎng", ko: "가렵다, 간지럽다", pos: "형용사", hanja: "양(癢) — '가려울 양'.", ex: { zh: "我的胳膊有点痒。", pinyin: "wǒ de gēbo yǒudiǎn yǎng", ko: "제 팔이 좀 가려워요." } },
        { zh: "意外", pinyin: "yìwài", ko: "뜻밖이다; 의외; 사고", pos: "형용사", hanja: "의외(意外) — 한자 그대로.", ex: { zh: "这个结果让人很意外。", pinyin: "zhège jiéguǒ ràng rén hěn yìwài", ko: "이 결과는 정말 뜻밖이에요." } },
        { zh: "一致", pinyin: "yīzhì", ko: "일치하다, 한결같다", pos: "형용사", hanja: "일치(一致) — 한자 그대로.", ex: { zh: "大家的意见很一致。", pinyin: "dàjiā de yìjiàn hěn yízhì", ko: "모두의 의견이 일치해요." } },
        { zh: "遗憾", pinyin: "yíhàn", ko: "유감스럽다; 유감", pos: "형용사", hanja: "유감(遺憾) — '遺'는 남길 유, '憾'은 섭섭할 감.", ex: { zh: "没能见到你很遗憾。", pinyin: "méi néng jiàndào nǐ hěn yíhàn", ko: "당신을 못 만나서 아쉬워요." } },
        { zh: "英俊", pinyin: "yīngjùn", ko: "잘생기다, 영준하다", pos: "형용사", hanja: "영준(英俊) — '英'은 꽃부리 영, '俊'은 준걸 준.", ex: { zh: "这位演员长得很英俊。", pinyin: "zhè wèi yǎnyuán zhǎng de hěn yīngjùn", ko: "이 배우는 아주 잘생겼어요." } },
        { zh: "拥挤", pinyin: "yōngjǐ", ko: "붐비다, 혼잡하다", pos: "형용사", hanja: "옹제(擁擠) — '擁'은 안을 옹, '擠'는 밀칠 제.", ex: { zh: "上班时地铁很拥挤。", pinyin: "shàngbān shí dìtiě hěn yōngjǐ", ko: "출근할 때 지하철은 아주 붐벼요." } },
        { zh: "优惠", pinyin: "yōuhuì", ko: "혜택을 주다, 우대의; 우대", pos: "형용사", hanja: "우혜(優惠) — '優'는 넉넉할 우, '惠'는 은혜 혜.", ex: { zh: "现在购买有优惠价格。", pinyin: "xiànzài gòumǎi yǒu yōuhuì jiàgé", ko: "지금 사면 할인가가 적용돼요." } },
        { zh: "优美", pinyin: "yōuměi", ko: "우아하다, 아름답다", pos: "형용사", hanja: "우미(優美) — '優'는 넉넉할 우, '美'는 아름다울 미.", ex: { zh: "这里的风景很优美。", pinyin: "zhèlǐ de fēngjǐng hěn yōuměi", ko: "이곳 풍경은 아주 아름다워요." } },
        { zh: "悠久", pinyin: "yōujiǔ", ko: "유구하다, 오래되다", pos: "형용사", hanja: "유구(悠久) — '悠'는 멀 유, '久'는 오랠 구.", ex: { zh: "中国有悠久的历史。", pinyin: "Zhōngguó yǒu yōujiǔ de lìshǐ", ko: "중국은 유구한 역사를 가지고 있어요." } },
        { zh: "有利", pinyin: "yǒulì", ko: "유리하다, 이롭다", pos: "형용사", hanja: "유리(有利) — '有'는 있을 유, '利'는 이로울 리.", ex: { zh: "这对我们很有利。", pinyin: "zhè duì wǒmen hěn yǒulì", ko: "이것은 우리에게 아주 유리해요." } },
        { zh: "糟糕", pinyin: "zāogāo", ko: "엉망이다, 큰일이다", pos: "형용사", hanja: "조고(糟糕) — '糟'는 지게미 조, '糕'는 떡 고. '일이 엉망이다'.", ex: { zh: "糟糕，我忘带钥匙了。", pinyin: "zāogāo, wǒ wàng dài yàoshi le", ko: "큰일이다, 열쇠 챙기는 걸 깜빡했어요." } },
        { zh: "真实", pinyin: "zhēnshí", ko: "진실하다, 실제의", pos: "형용사", hanja: "진실(真實) — 한자 그대로.", ex: { zh: "这是一个真实的故事。", pinyin: "zhè shì yí ge zhēnshí de gùshi", ko: "이것은 실화예요." } },
        { zh: "周到", pinyin: "zhōudào", ko: "세심하다, 빈틈없다", pos: "형용사", hanja: "주도(周到) — '周'는 두루 주, '到'는 이를 도. '두루 미치다'.", ex: { zh: "服务员的服务很周到。", pinyin: "fúwùyuán de fúwù hěn zhōudào", ko: "종업원의 서비스가 아주 세심해요." } },
        { zh: "自豪", pinyin: "zìháo", ko: "자랑스럽다, 자부심을 느끼다", pos: "형용사", hanja: "자호(自豪) — '自'는 스스로 자, '豪'는 호걸 호.", ex: { zh: "我为你感到自豪。", pinyin: "wǒ wèi nǐ gǎndào zìháo", ko: "저는 당신이 자랑스러워요." } },
        { zh: "自觉", pinyin: "zìjué", ko: "자각하다, 자발적이다", pos: "형용사", hanja: "자각(自覺) — '自'는 스스로 자, '覺'은 깨달을 각.", ex: { zh: "他学习很自觉。", pinyin: "tā xuéxí hěn zìjué", ko: "그는 알아서 공부를 잘해요." } },
        { zh: "自私", pinyin: "zìsī", ko: "이기적이다", pos: "형용사", hanja: "자사(自私) — '自'는 스스로 자, '私'는 사사 사.", ex: { zh: "他是一个自私的人。", pinyin: "tā shì yí ge zìsī de rén", ko: "그는 이기적인 사람이에요." } },
        { zh: "自信", pinyin: "zìxìn", ko: "자신감 있다; 자신(감)", pos: "형용사", hanja: "자신(自信) — '自'는 스스로 자, '信'은 믿을 신.", ex: { zh: "她对自己很自信。", pinyin: "tā duì zìjǐ hěn zìxìn", ko: "그녀는 자신에 대한 자신감이 강해요." } },
        { zh: "自由", pinyin: "zìyóu", ko: "자유롭다; 자유", pos: "형용사", hanja: "자유(自由) — 한자 그대로.", ex: { zh: "每个人都向往自由。", pinyin: "měi ge rén dōu xiàngwǎng zìyóu", ko: "모든 사람은 자유를 동경해요." } },
        { zh: "自愿", pinyin: "zìyuàn", ko: "자원하다, 자발적이다", pos: "형용사", hanja: "자원(自願) — '自'는 스스로 자, '願'은 원할 원.", ex: { zh: "他自愿参加了这个活动。", pinyin: "tā zìyuàn cānjiā le zhège huódòng", ko: "그는 자발적으로 이 행사에 참가했어요." } },
        { zh: "紫", pinyin: "zǐ", ko: "자줏빛의, 보라색의", pos: "형용사", hanja: "자(紫) — '자줏빛 자'.", ex: { zh: "她穿着一件紫色的裙子。", pinyin: "tā chuān zhe yí jiàn zǐsè de qúnzi", ko: "그녀는 보라색 치마를 입고 있어요." } },
        { zh: "重复", pinyin: "chóngfù", ko: "중복되다, 반복하다", pos: "형용사", hanja: "중복(重複) — '重'은 거듭 중, '複'은 겹칠 복.", ex: { zh: "请不要重复同样的错误。", pinyin: "qǐng búyào chóngfù tóngyàng de cuòwù", ko: "같은 실수를 반복하지 마세요." } },
        { zh: "整个", pinyin: "zhěnggè", ko: "전체의, 온", pos: "형용사", hanja: "정개(整個) — '整'은 가지런할 정, '個'는 낱 개.", ex: { zh: "整个城市都下雪了。", pinyin: "zhěnggè chéngshì dōu xià xuě le", ko: "도시 전체에 눈이 내렸어요." } },
        { zh: "正", pinyin: "zhèng", ko: "바르다, 똑바르다, 마침 ~하다", pos: "형용사", hanja: "정(正) — '바를 정'.", ex: { zh: "请把画挂正。", pinyin: "qǐng bǎ huà guà zhèng", ko: "그림을 똑바로 걸어 주세요." } },
      ],
    },
    {
      name: "HSK5 보강 — 부사·기타",
      icon: "🔴",
      words: [
        { zh: "幸亏", pinyin: "xìngkuī", ko: "다행히, 운 좋게", pos: "부사", hanja: "행휴(幸虧) — '幸'은 다행 행, '虧'는 이지러질 휴.", ex: { zh: "幸亏你提醒我，不然就忘了。", pinyin: "xìngkuī nǐ tíxǐng wǒ, bùrán jiù wàng le", ko: "다행히 알려 줘서 망정이지, 안 그랬으면 잊을 뻔했어요." } },
        { zh: "要不", pinyin: "yàobù", ko: "그렇지 않으면; ~하는 게 어때", pos: "접속사", hanja: "요부(要不) — '要'는 요긴할 요, '不'은 아닐 불.", ex: { zh: "快走吧，要不就迟到了。", pinyin: "kuài zǒu ba, yàobù jiù chídào le", ko: "어서 가요, 안 그러면 늦어요." } },
        { zh: "要是", pinyin: "yàoshi", ko: "만약 ~라면", pos: "접속사", hanja: "요시(要是) — '要'는 요긴할 요, '是'는 옳을 시.", ex: { zh: "要是下雨，我们就不去了。", pinyin: "yàoshi xià yǔ, wǒmen jiù bú qù le", ko: "만약 비가 오면 우리는 안 갈 거예요." } },
        { zh: "业余", pinyin: "yèyú", ko: "여가의, 아마추어의", pos: "구별사", hanja: "업여(業餘) — '業'은 일 업, '餘'는 남을 여. '업무 외의 여가'.", ex: { zh: "他业余时间喜欢画画。", pinyin: "tā yèyú shíjiān xǐhuan huà huà", ko: "그는 여가 시간에 그림 그리기를 좋아해요." } },
        { zh: "一旦", pinyin: "yīdàn", ko: "일단 ~하면, 만일", pos: "부사", hanja: "일단(一旦) — '一'은 한 일, '旦'은 아침 단.", ex: { zh: "一旦决定了就别后悔。", pinyin: "yídàn juédìng le jiù bié hòuhuǐ", ko: "일단 결정했으면 후회하지 마세요." } },
        { zh: "一路", pinyin: "yīlù", ko: "도중 내내, 가는 길 내내", pos: "부사", hanja: "일로(一路) — '一'은 한 일, '路'는 길 로.", ex: { zh: "一路上我们聊得很开心。", pinyin: "yí lù shang wǒmen liáo de hěn kāixīn", ko: "가는 길 내내 우리는 즐겁게 얘기했어요." } },
        { zh: "以来", pinyin: "yǐlái", ko: "~이래, ~이후로", pos: "조사", hanja: "이래(以來) — '以'는 써 이, '來'는 올 래.", ex: { zh: "入冬以来，天气越来越冷。", pinyin: "rùdōng yǐlái, tiānqì yuè lái yuè lěng", ko: "겨울 들어 날씨가 갈수록 추워져요." } },
        { zh: "因而", pinyin: "yīnér", ko: "따라서, 그러므로", pos: "접속사", hanja: "인이(因而) — '因'은 인할 인, '而'는 말이을 이.", ex: { zh: "他生病了，因而没来上课。", pinyin: "tā shēngbìng le, yīn'ér méi lái shàngkè", ko: "그는 아파서, 따라서 수업에 오지 않았어요." } },
        { zh: "与其", pinyin: "yǔqí", ko: "~하느니 (차라리)", pos: "접속사", hanja: "여기(與其) — '與'는 줄 여, '其'는 그 기. '与其 A 不如 B' 형태로 써요.", ex: { zh: "与其等待，不如行动。", pinyin: "yǔqí děngdài, bùrú xíngdòng", ko: "기다리느니 차라리 행동하는 게 나아요." } },
        { zh: "再三", pinyin: "zàisān", ko: "거듭, 재삼", pos: "부사", hanja: "재삼(再三) — '再'는 두 재, '三'은 석 삼.", ex: { zh: "他再三向我道谢。", pinyin: "tā zàisān xiàng wǒ dàoxiè", ko: "그는 거듭 제게 감사를 표했어요." } },
        { zh: "则", pinyin: "zé", ko: "(그러면) 곧, 오히려; 규칙", pos: "접속사", hanja: "칙(則) — '곧 즉/법칙 칙'.", ex: { zh: "欲速则不达。", pinyin: "yù sù zé bù dá", ko: "서두르면 오히려 이루지 못해요." } },
        { zh: "至今", pinyin: "zhìjīn", ko: "지금까지, 여태", pos: "부사", hanja: "지금(至今) — '至'는 이를 지, '今'은 이제 금.", ex: { zh: "这个问题至今没有答案。", pinyin: "zhège wèntí zhìjīn méiyǒu dá'àn", ko: "이 문제는 지금까지 답이 없어요." } },
        { zh: "至于", pinyin: "zhìyú", ko: "~로 말하자면, ~에 관해서는", pos: "개사", hanja: "지어(至於) — '至'는 이를 지, '於'는 어조사 어.", ex: { zh: "至于结果，谁也不知道。", pinyin: "zhìyú jiéguǒ, shéi yě bù zhīdào", ko: "결과로 말하자면 아무도 몰라요." } },
        { zh: "逐步", pinyin: "zhúbù", ko: "점차, 차츰차츰", pos: "부사", hanja: "축보(逐步) — '逐'은 쫓을 축, '步'는 걸음 보. '한 걸음씩'.", ex: { zh: "情况正在逐步好转。", pinyin: "qíngkuàng zhèngzài zhúbù hǎozhuǎn", ko: "상황이 점차 나아지고 있어요." } },
        { zh: "专心", pinyin: "zhuānxīn", ko: "전념하다, 몰두하다", pos: "부사", hanja: "전심(專心) — '專'은 오로지 전, '心'은 마음 심.", ex: { zh: "他专心听老师讲课。", pinyin: "tā zhuānxīn tīng lǎoshī jiǎngkè", ko: "그는 선생님 강의를 집중해서 들어요." } },
        { zh: "自从", pinyin: "zìcóng", ko: "~로부터, ~이래", pos: "개사", hanja: "자종(自從) — '自'는 스스로 자, '從'은 좇을 종.", ex: { zh: "自从搬家以后，我们很少见面。", pinyin: "zìcóng bānjiā yǐhòu, wǒmen hěn shǎo jiànmiàn", ko: "이사한 뒤로 우리는 거의 못 만나요." } },
        { zh: "自动", pinyin: "zìdòng", ko: "자동으로, 자발적으로", pos: "부사", hanja: "자동(自動) — 한자 그대로.", ex: { zh: "这扇门会自动打开。", pinyin: "zhè shàn mén huì zìdòng dǎkāi", ko: "이 문은 자동으로 열려요." } },
        { zh: "总共", pinyin: "zǒnggòng", ko: "전부, 모두 합쳐", pos: "부사", hanja: "총공(總共) — '總'은 거느릴 총, '共'은 함께 공.", ex: { zh: "我们总共花了三百块。", pinyin: "wǒmen zǒnggòng huā le sānbǎi kuài", ko: "우리는 모두 합쳐 300위안을 썼어요." } },
        { zh: "总算", pinyin: "zǒngsuàn", ko: "마침내, 겨우, 어쨌든", pos: "부사", hanja: "총산(總算) — '總'은 거느릴 총, '算'은 셈할 산.", ex: { zh: "等了很久，他总算来了。", pinyin: "děng le hěn jiǔ, tā zǒngsuàn lái le", ko: "한참 기다린 끝에 그가 드디어 왔어요." } },
        { zh: "最初", pinyin: "zuìchū", ko: "최초의, 처음", pos: "부사", hanja: "최초(最初) — 한자 그대로.", ex: { zh: "最初我并不喜欢这里。", pinyin: "zuìchū wǒ bìng bù xǐhuan zhèlǐ", ko: "처음에 저는 이곳을 좋아하지 않았어요." } },
        { zh: "作为", pinyin: "zuòwéi", ko: "~로서, ~로 삼다", pos: "개사", hanja: "작위(作爲) — '作'은 지을 작, '爲'는 할 위.", ex: { zh: "作为学生，应该努力学习。", pinyin: "zuòwéi xuésheng, yīnggāi nǔlì xuéxí", ko: "학생으로서 열심히 공부해야 해요." } },
        { zh: "支", pinyin: "zhī", ko: "지탱하다; 자루(가늘고 긴 물건 양사)", pos: "양사", hanja: "지(支) — '지탱할 지'. 펜·담배 등을 세는 양사.", ex: { zh: "我买了一支笔。", pinyin: "wǒ mǎi le yì zhī bǐ", ko: "저는 펜 한 자루를 샀어요." } },
        { zh: "直", pinyin: "zhí", ko: "곧다, 곧장, 줄곧", pos: "형용사", hanja: "직(直) — '곧을 직'.", ex: { zh: "这条路一直往前走。", pinyin: "zhè tiáo lù yìzhí wǎng qián zǒu", ko: "이 길로 곧장 앞으로 가세요." } },
        { zh: "钟", pinyin: "zhōng", ko: "시계, 종", pos: "명사", hanja: "종(鐘) — '쇠북 종'. 시계·괘종을 가리켜요.", ex: { zh: "墙上挂着一个钟。", pinyin: "qiáng shang guà zhe yí ge zhōng", ko: "벽에 시계가 하나 걸려 있어요." } },
        { zh: "重", pinyin: "chóng", ko: "다시, 거듭; 중복되다", pos: "부사", hanja: "중(重) — '거듭 중'(chóng일 때). 무거울 중(zhòng)과 다른 뜻이에요.", ex: { zh: "这道题请重做一遍。", pinyin: "zhè dào tí qǐng chóng zuò yí biàn", ko: "이 문제를 다시 한번 풀어 주세요." } },
        { zh: "摇", pinyin: "yáo", ko: "흔들다, 흔들리다", pos: "동사", hanja: "요(搖) — '흔들 요'.", ex: { zh: "他摇了摇头表示不同意。", pinyin: "tā yáo le yáo tóu biǎoshì bù tóngyì", ko: "그는 고개를 저어 반대를 나타냈어요." } },
        { zh: "咬", pinyin: "yǎo", ko: "물다, 깨물다", pos: "동사", hanja: "교(咬) — '깨물 교'.", ex: { zh: "小狗咬住了他的裤子。", pinyin: "xiǎo gǒu yǎozhù le tā de kùzi", ko: "강아지가 그의 바지를 물었어요." } },
        { zh: "油炸", pinyin: "yóuzhá", ko: "기름에 튀기다", pos: "동사", hanja: "유작(油炸) — '油'는 기름 유, '炸'는 터질 작(튀기다).", ex: { zh: "这些食物是油炸的。", pinyin: "zhèxiē shíwù shì yóuzhá de", ko: "이 음식들은 기름에 튀긴 거예요." } },
        { zh: "乙", pinyin: "yǐ", ko: "을(둘째 천간), 두 번째", pos: "명사", hanja: "을(乙) — '새 을'. 천간(天干)의 둘째, 순서상 '을'.", ex: { zh: "甲方和乙方签了合同。", pinyin: "jiǎ fāng hé yǐ fāng qiān le hétong", ko: "갑과 을이 계약을 맺었어요." } },
        { zh: "元旦", pinyin: "yuándàn", ko: "원단, 설날(양력 1월 1일)", pos: "명사", hanja: "원단(元旦) — '元'은 으뜸 원, '旦'은 아침 단.", ex: { zh: "元旦我们放假一天。", pinyin: "yuándàn wǒmen fàngjià yì tiān", ko: "신정에 우리는 하루 쉬어요." } },
        { zh: "阵", pinyin: "zhèn", ko: "바탕, 차례(잠깐 지속되는 동작·현상 양사)", pos: "양사", hanja: "진(陣) — '진칠 진'. '一阵风(한바탕 바람)'처럼 써요.", ex: { zh: "刮过一阵大风。", pinyin: "guā guò yí zhèn dà fēng", ko: "한바탕 큰바람이 불고 지나갔어요." } },
        { zh: "长途", pinyin: "chángtú", ko: "장거리의", pos: "구별사", hanja: "장도(長途) — '長'은 길 장, '途'는 길 도.", ex: { zh: "他坐长途汽车回家。", pinyin: "tā zuò chángtú qìchē huí jiā", ko: "그는 장거리 버스를 타고 집에 가요." } },
        { zh: "照常", pinyin: "zhàocháng", ko: "평소대로, 여느 때와 같이", pos: "부사", hanja: "조상(照常) — '照'는 비칠 조, '常'은 항상 상.", ex: { zh: "节日期间商店照常营业。", pinyin: "jiérì qījiān shāngdiàn zhàocháng yíngyè", ko: "명절 기간에도 상점은 평소대로 영업해요." } },
      ],
    },
  ],
};

export default themes;
