/**
 * H5 (HSK 5급) 보강 어휘 — 청크 B (200개).
 * 품사·의미별 4개 테마. pinyin은 원본 표기를 보존하되, 성씨·이체자·다음자 오독은 표준 병음으로 교정했어요.
 */
const themes = {
  themes: [
    {
      name: "HSK5 보강 — 동사",
      icon: "🔴",
      words: [
        { zh: "钓", pinyin: "diào", ko: "낚다, 낚시하다", pos: "동사", hanja: "조(釣) — '낚을 조'.", ex: { zh: "他在河边钓鱼。", pinyin: "tā zài hé biān diào yú", ko: "그는 강가에서 낚시를 해요." } },
        { zh: "顶", pinyin: "dǐng", ko: "(머리로) 떠받치다, 버티다; 꼭대기", pos: "동사", hanja: "정(頂) — '정수리 정'.", ex: { zh: "他用头顶着球。", pinyin: "tā yòng tóu dǐng zhe qiú", ko: "그는 머리로 공을 받쳐요." } },
        { zh: "冻", pinyin: "dòng", ko: "얼다, 얼리다, 얼어붙다", pos: "동사", hanja: "동(凍) — '얼 동'. '동결(凍結)'의 동.", ex: { zh: "水冻成了冰。", pinyin: "shuǐ dòng chéng le bīng", ko: "물이 얼어서 얼음이 됐어요." } },
        { zh: "逗", pinyin: "dòu", ko: "놀리다, 어르다; 웃기다", pos: "동사", ex: { zh: "他爱逗孩子玩。", pinyin: "tā ài dòu háizi wán", ko: "그는 아이를 어르며 놀아 주길 좋아해요." } },
        { zh: "度过", pinyin: "dùguò", ko: "(시간을) 보내다, 지내다", pos: "동사", hanja: "도과(度過) — '度'는 지낼 도, '過'는 지날 과.", ex: { zh: "我们一起度过了假期。", pinyin: "wǒmen yìqǐ dùguò le jiàqī", ko: "우리는 함께 휴가를 보냈어요." } },
        { zh: "堆", pinyin: "duī", ko: "쌓다, 쌓이다; 무더기", pos: "동사", hanja: "퇴(堆) — '쌓을 퇴'.", ex: { zh: "桌上堆着很多书。", pinyin: "zhuō shang duī zhe hěn duō shū", ko: "책상에 책이 잔뜩 쌓여 있어요." } },
        { zh: "对比", pinyin: "duìbǐ", ko: "대비하다, 비교하다; 대비", pos: "동사", hanja: "대비(對比) — 한자 그대로.", ex: { zh: "把两个方案对比一下。", pinyin: "bǎ liǎng ge fāng'àn duìbǐ yíxià", ko: "두 방안을 한번 비교해 보세요." } },
        { zh: "对待", pinyin: "duìdài", ko: "대하다, 대우하다", pos: "동사", hanja: "대대(對待) — '對'는 대할 대, '待'는 기다릴·대접할 대.", ex: { zh: "我们要认真对待问题。", pinyin: "wǒmen yào rènzhēn duìdài wèntí", ko: "우리는 문제를 진지하게 대해야 해요." } },
        { zh: "蹲", pinyin: "dūn", ko: "쪼그려 앉다, 웅크리다", pos: "동사", ex: { zh: "他蹲在地上看蚂蚁。", pinyin: "tā dūn zài dì shang kàn mǎyǐ", ko: "그는 땅에 쪼그려 앉아 개미를 봐요." } },
        { zh: "多亏", pinyin: "duōkuī", ko: "덕분이다, 다행히 ~덕에", pos: "동사", hanja: "다휴(多虧) — '虧'는 이지러질 휴. '~덕을 많이 보다'.", ex: { zh: "多亏你帮忙，我才能完成。", pinyin: "duōkuī nǐ bāngmáng, wǒ cái néng wánchéng", ko: "당신 덕분에 끝낼 수 있었어요." } },
        { zh: "躲藏", pinyin: "duǒcáng", ko: "숨다, 몸을 감추다", pos: "동사", hanja: "타장(躲藏) — '藏'은 감출 장.", ex: { zh: "孩子躲藏在门后。", pinyin: "háizi duǒcáng zài mén hòu", ko: "아이가 문 뒤에 숨어 있어요." } },
        { zh: "发表", pinyin: "fābiǎo", ko: "발표하다, 게재하다", pos: "동사", hanja: "발표(發表) — 한자 그대로.", ex: { zh: "他在杂志上发表了文章。", pinyin: "tā zài zázhì shang fābiǎo le wénzhāng", ko: "그는 잡지에 글을 발표했어요." } },
        { zh: "发愁", pinyin: "fāchóu", ko: "근심하다, 걱정하다", pos: "동사", hanja: "발수(發愁) — '愁'는 근심 수.", ex: { zh: "他为找工作发愁。", pinyin: "tā wèi zhǎo gōngzuò fāchóu", ko: "그는 일자리 구하는 일로 걱정해요." } },
        { zh: "发抖", pinyin: "fādǒu", ko: "떨다, 부들부들 떨다", pos: "동사", hanja: "발두(發抖) — '抖'는 떨 두.", ex: { zh: "他冷得发抖。", pinyin: "tā lěng de fādǒu", ko: "그는 추워서 덜덜 떨어요." } },
        { zh: "发挥", pinyin: "fāhuī", ko: "발휘하다, 발휘되다", pos: "동사", hanja: "발휘(發揮) — 한자 그대로.", ex: { zh: "他发挥了自己的才能。", pinyin: "tā fāhuī le zìjǐ de cáinéng", ko: "그는 자기 재능을 발휘했어요." } },
        { zh: "发明", pinyin: "fāmíng", ko: "발명하다; 발명", pos: "동사", hanja: "발명(發明) — 한자 그대로.", ex: { zh: "他发明了一种新机器。", pinyin: "tā fāmíng le yì zhǒng xīn jīqì", ko: "그는 새로운 기계를 발명했어요." } },
        { zh: "发言", pinyin: "fāyán", ko: "발언하다; 발언", pos: "동사", hanja: "발언(發言) — 한자 그대로.", ex: { zh: "请大家自由发言。", pinyin: "qǐng dàjiā zìyóu fāyán", ko: "여러분 자유롭게 발언해 주세요." } },
        { zh: "罚款", pinyin: "fákuǎn", ko: "벌금을 물리다; 벌금", pos: "동사", hanja: "벌관(罰款) — '罰'은 벌할 벌, '款'은 돈·항목 관.", ex: { zh: "乱停车会被罚款。", pinyin: "luàn tíngchē huì bèi fákuǎn", ko: "함부로 주차하면 벌금을 물어요." } },
        { zh: "翻", pinyin: "fān", ko: "뒤집다, 넘기다; 번역하다", pos: "동사", hanja: "번(翻) — '뒤칠 번'. '번역(翻譯)'의 번.", ex: { zh: "他翻开书看了起来。", pinyin: "tā fān kāi shū kàn le qǐlái", ko: "그는 책을 펼쳐 읽기 시작했어요." } },
        { zh: "妨碍", pinyin: "fángài", ko: "방해하다, 지장을 주다", pos: "동사", hanja: "방애(妨礙) — '妨'은 방해할 방, '礙'는 거리낄 애.", ex: { zh: "别妨碍他工作。", pinyin: "bié fáng'ài tā gōngzuò", ko: "그가 일하는 걸 방해하지 마세요." } },
        { zh: "放松", pinyin: "fàngsōng", ko: "긴장을 풀다, 느슨하게 하다", pos: "동사", hanja: "방송(放鬆) — '放'은 놓을 방, '鬆'은 느슨할 송.", ex: { zh: "周末好好放松一下。", pinyin: "zhōumò hǎohǎo fàngsōng yíxià", ko: "주말에 푹 쉬며 긴장을 풀어요." } },
        { zh: "奋斗", pinyin: "fèndòu", ko: "분투하다, 힘써 싸우다", pos: "동사", hanja: "분투(奮鬥) — '奮'은 떨칠 분, '鬥'는 싸울 투.", ex: { zh: "为理想而奋斗。", pinyin: "wèi lǐxiǎng ér fèndòu", ko: "이상을 위해 분투해요." } },
        { zh: "讽刺", pinyin: "fěngcì", ko: "풍자하다, 비꼬다; 풍자", pos: "동사", hanja: "풍자(諷刺) — '諷'은 풍자할 풍, '刺'는 찌를 자.", ex: { zh: "他喜欢讽刺别人。", pinyin: "tā xǐhuan fěngcì biéren", ko: "그는 남을 비꼬길 좋아해요." } },
        { zh: "否定", pinyin: "fǒudìng", ko: "부정하다; 부정적인", pos: "동사", hanja: "부정(否定) — '否'는 아닐 부, '定'은 정할 정.", ex: { zh: "他否定了这个计划。", pinyin: "tā fǒudìng le zhège jìhuà", ko: "그는 이 계획을 부정했어요." } },
        { zh: "否认", pinyin: "fǒurèn", ko: "부인하다, 인정하지 않다", pos: "동사", hanja: "부인(否認) — '認'은 알·인정할 인.", ex: { zh: "他否认做过这件事。", pinyin: "tā fǒurèn zuò guò zhè jiàn shì", ko: "그는 이 일을 한 적이 없다고 부인했어요." } },
        { zh: "扶", pinyin: "fú", ko: "부축하다, (손으로) 받치다", pos: "동사", hanja: "부(扶) — '도울 부'. '부조(扶助)'의 부.", ex: { zh: "他扶老人过马路。", pinyin: "tā fú lǎorén guò mǎlù", ko: "그는 노인을 부축해 길을 건너요." } },
        { zh: "服从", pinyin: "fúcóng", ko: "복종하다, 따르다", pos: "동사", hanja: "복종(服從) — '服'은 따를 복, '從'은 좇을 종.", ex: { zh: "军人要服从命令。", pinyin: "jūnrén yào fúcóng mìnglìng", ko: "군인은 명령에 복종해야 해요." } },
        { zh: "辅导", pinyin: "fǔdǎo", ko: "지도하다, 과외하다; 지도", pos: "동사", hanja: "보도(輔導) — '輔'는 도울 보, '導'는 이끌 도.", ex: { zh: "老师辅导我做作业。", pinyin: "lǎoshī fǔdǎo wǒ zuò zuòyè", ko: "선생님이 제 숙제를 지도해 줘요." } },
        { zh: "付款", pinyin: "fùkuǎn", ko: "돈을 지불하다", pos: "동사", hanja: "부관(付款) — '付'는 줄 부, '款'은 돈 관.", ex: { zh: "请在这里付款。", pinyin: "qǐng zài zhèlǐ fùkuǎn", ko: "여기서 결제해 주세요." } },
        { zh: "复制", pinyin: "fùzhì", ko: "복제하다, 복사하다", pos: "동사", hanja: "복제(複製) — '複'은 겹칠 복, '製'는 지을 제.", ex: { zh: "请复制一份文件。", pinyin: "qǐng fùzhì yí fèn wénjiàn", ko: "문서를 한 부 복사해 주세요." } },
        { zh: "改进", pinyin: "gǎijìn", ko: "개선하다, 개량하다; 개선", pos: "동사", hanja: "개진(改進) — '改'는 고칠 개, '進'은 나아갈 진.", ex: { zh: "我们要改进工作方法。", pinyin: "wǒmen yào gǎijìn gōngzuò fāngfǎ", ko: "우리는 일하는 방법을 개선해야 해요." } },
        { zh: "改正", pinyin: "gǎizhèng", ko: "바로잡다, 고치다", pos: "동사", hanja: "개정(改正) — '改'는 고칠 개, '正'은 바를 정.", ex: { zh: "请改正你的错误。", pinyin: "qǐng gǎizhèng nǐ de cuòwù", ko: "당신의 잘못을 바로잡으세요." } },
        { zh: "盖", pinyin: "gài", ko: "덮다; (집을) 짓다; 뚜껑", pos: "동사", hanja: "개(蓋) — '덮을 개'. (입력의 '성씨 Gě'는 무시했어요.)", ex: { zh: "请把锅盖好。", pinyin: "qǐng bǎ guō gài hǎo", ko: "냄비 뚜껑을 잘 덮어 주세요." } },
        { zh: "概括", pinyin: "gàikuò", ko: "개괄하다, 요약하다", pos: "동사", hanja: "개괄(概括) — '概'는 대개 개, '括'는 묶을 괄.", ex: { zh: "请概括一下文章内容。", pinyin: "qǐng gàikuò yíxià wénzhāng nèiróng", ko: "글의 내용을 한번 요약해 주세요." } },
        { zh: "感受", pinyin: "gǎnshòu", ko: "느끼다; 느낌, 감회", pos: "동사", hanja: "감수(感受) — '感'은 느낄 감, '受'는 받을 수.", ex: { zh: "我感受到了大家的关心。", pinyin: "wǒ gǎnshòu dào le dàjiā de guānxīn", ko: "저는 모두의 관심을 느꼈어요." } },
        { zh: "告别", pinyin: "gàobié", ko: "작별하다, 이별을 고하다", pos: "동사", hanja: "고별(告別) — '告'는 고할 고, '別'은 다를·헤어질 별.", ex: { zh: "他向朋友告别。", pinyin: "tā xiàng péngyou gàobié", ko: "그는 친구에게 작별을 고해요." } },
        { zh: "革命", pinyin: "gémìng", ko: "혁명하다; 혁명", pos: "동사", hanja: "혁명(革命) — '革'은 가죽·고칠 혁, '命'은 목숨·명할 명.", ex: { zh: "这是一场技术革命。", pinyin: "zhè shì yì chǎng jìshù gémìng", ko: "이것은 하나의 기술 혁명이에요." } },
        { zh: "公布", pinyin: "gōngbù", ko: "공표하다, 발표하다", pos: "동사", hanja: "공포(公佈) — '公'은 공평할 공, '佈'는 펼 포.", ex: { zh: "结果已经公布了。", pinyin: "jiéguǒ yǐjīng gōngbù le", ko: "결과는 이미 공표됐어요." } },
        { zh: "公开", pinyin: "gōngkāi", ko: "공개하다; 공개적인", pos: "동사", hanja: "공개(公開) — 한자 그대로.", ex: { zh: "他公开了这个秘密。", pinyin: "tā gōngkāi le zhège mìmì", ko: "그는 이 비밀을 공개했어요." } },
        { zh: "沟通", pinyin: "gōutōng", ko: "소통하다, 통하게 하다", pos: "동사", hanja: "구통(溝通) — '溝'는 도랑 구, '通'은 통할 통.", ex: { zh: "我们要多沟通。", pinyin: "wǒmen yào duō gōutōng", ko: "우리는 소통을 많이 해야 해요." } },
        { zh: "构成", pinyin: "gòuchéng", ko: "구성하다, 이루다; 구성", pos: "동사", hanja: "구성(構成) — '構'는 얽을 구, '成'은 이룰 성.", ex: { zh: "水由氢和氧构成。", pinyin: "shuǐ yóu qīng hé yǎng gòuchéng", ko: "물은 수소와 산소로 구성돼요." } },
        { zh: "鼓舞", pinyin: "gǔwǔ", ko: "고무하다, 북돋우다; 고무", pos: "동사", hanja: "고무(鼓舞) — '鼓'는 북 고, '舞'는 춤출 무. 사기를 북돋워요.", ex: { zh: "他的话鼓舞了大家。", pinyin: "tā de huà gǔwǔ le dàjiā", ko: "그의 말이 모두를 북돋웠어요." } },
        { zh: "固定", pinyin: "gùdìng", ko: "고정하다; 고정된", pos: "동사", hanja: "고정(固定) — '固'는 굳을 고, '定'은 정할 정.", ex: { zh: "把架子固定在墙上。", pinyin: "bǎ jiàzi gùdìng zài qiáng shang", ko: "선반을 벽에 고정하세요." } },
        { zh: "雇佣", pinyin: "gùyōng", ko: "고용하다", pos: "동사", hanja: "고용(雇傭) — '雇'는 품팔 고, '傭'은 품팔 용.", ex: { zh: "公司雇佣了新员工。", pinyin: "gōngsī gùyōng le xīn yuángōng", ko: "회사가 새 직원을 고용했어요." } },
        { zh: "挂号", pinyin: "guàhào", ko: "(병원) 접수하다; 등기로 부치다", pos: "동사", hanja: "괘호(掛號) — '掛'는 걸 괘, '號'는 번호 호.", ex: { zh: "看病要先挂号。", pinyin: "kànbìng yào xiān guàhào", ko: "진료받으려면 먼저 접수해야 해요." } },
        { zh: "关闭", pinyin: "guānbì", ko: "닫다, 폐쇄하다, (전원을) 끄다", pos: "동사", hanja: "관폐(關閉) — '關'은 빗장 관, '閉'는 닫을 폐.", ex: { zh: "请关闭手机。", pinyin: "qǐng guānbì shǒujī", ko: "휴대폰을 꺼 주세요." } },
        { zh: "关怀", pinyin: "guānhuái", ko: "관심을 가지고 보살피다; 배려", pos: "동사", hanja: "관회(關懷) — '關'은 관계할 관, '懷'는 품을 회.", ex: { zh: "感谢您的关怀。", pinyin: "gǎnxiè nín de guānhuái", ko: "보살펴 주셔서 감사해요." } },
        { zh: "缓解", pinyin: "huǎnjiě", ko: "완화하다, 누그러뜨리다", pos: "동사", hanja: "완해(緩解) — '緩'은 느릴·늦출 완, '解'는 풀 해.", ex: { zh: "这药能缓解疼痛。", pinyin: "zhè yào néng huǎnjiě téngtòng", ko: "이 약은 통증을 완화해 줘요." } },
        { zh: "怀念", pinyin: "huáiniàn", ko: "그리워하다, 추억하다", pos: "동사", hanja: "회념(懷念) — '懷'는 품을 회, '念'은 생각할 념.", ex: { zh: "我很怀念那段时光。", pinyin: "wǒ hěn huáiniàn nà duàn shíguāng", ko: "저는 그 시절이 무척 그리워요." } },
        { zh: "呼吸", pinyin: "hūxī", ko: "호흡하다, 숨쉬다", pos: "동사", hanja: "호흡(呼吸) — '呼'는 부를·내쉴 호, '吸'는 마실·들이쉴 흡.", ex: { zh: "深呼吸一下。", pinyin: "shēn hūxī yíxià", ko: "심호흡을 한번 하세요." } },
        { zh: "胡说", pinyin: "húshuō", ko: "헛소리하다, 함부로 지껄이다", pos: "동사", hanja: "호설(胡說) — '胡'는 오랑캐·함부로 호, '說'은 말씀 설.", ex: { zh: "别胡说，这不是真的。", pinyin: "bié húshuō, zhè bú shì zhēn de", ko: "헛소리 마세요, 이건 사실이 아니에요." } },
        { zh: "滑冰", pinyin: "huábīng", ko: "스케이트를 타다; 빙상", pos: "동사", hanja: "활빙(滑冰) — '滑'은 미끄러울 활, '冰'은 얼음 빙.", ex: { zh: "冬天我们去滑冰。", pinyin: "dōngtiān wǒmen qù huábīng", ko: "겨울에 우리는 스케이트를 타러 가요." } },
        { zh: "划船", pinyin: "huáchuán", ko: "배를 젓다, 노를 젓다", pos: "동사", hanja: "획선(划船) — '划'는 그을·저을 획, '船'은 배 선.", ex: { zh: "我们在湖上划船。", pinyin: "wǒmen zài hú shang huáchuán", ko: "우리는 호수에서 배를 저어요." } },
        { zh: "喊", pinyin: "hǎn", ko: "외치다, 소리치다, 부르다", pos: "동사", ex: { zh: "他大声喊我的名字。", pinyin: "tā dàshēng hǎn wǒ de míngzì", ko: "그가 큰 소리로 제 이름을 불러요." } },
        { zh: "恨", pinyin: "hèn", ko: "미워하다, 한스러워하다", pos: "동사", hanja: "한(恨) — '한 한'. 미움·원망을 뜻해요.", ex: { zh: "我不恨任何人。", pinyin: "wǒ bú hèn rènhé rén", ko: "저는 누구도 미워하지 않아요." } },
        { zh: "合作", pinyin: "hézuò", ko: "협력하다, 합작하다; 협력", pos: "동사", hanja: "합작(合作) — '合'은 합할 합, '作'은 지을 작. 한국어 '합작·협력'에 해당해요.", ex: { zh: "我们愉快地合作。", pinyin: "wǒmen yúkuài de hézuò", ko: "우리는 즐겁게 협력해요." } },
      ],
    },
    {
      name: "HSK5 보강 — 명사·추상",
      icon: "🔴",
      words: [
        { zh: "电池", pinyin: "diànchí", ko: "배터리, 전지", pos: "명사", hanja: "전지(電池) — '電'은 번개 전, '池'는 못 지.", ex: { zh: "我的手机没电池了。", pinyin: "wǒ de shǒujī méi diànchí le", ko: "제 휴대폰 배터리가 다 됐어요." } },
        { zh: "电台", pinyin: "diàntái", ko: "라디오 방송국, 무선국", pos: "명사", hanja: "전대(電臺) — '電'은 번개 전, '臺'는 대 대.", ex: { zh: "我喜欢听这个电台。", pinyin: "wǒ xǐhuan tīng zhège diàntái", ko: "저는 이 라디오 방송국을 즐겨 들어요." } },
        { zh: "动画片", pinyin: "dònghuàpiàn", ko: "애니메이션, 만화 영화", pos: "명사", hanja: "동화편(動畫片) — '動'은 움직일 동, '畫'는 그림 화, '片'은 조각·필름 편.", ex: { zh: "孩子爱看动画片。", pinyin: "háizi ài kàn dònghuàpiàn", ko: "아이는 애니메이션 보는 걸 좋아해요." } },
        { zh: "洞", pinyin: "dòng", ko: "구멍, 동굴", pos: "명사", hanja: "동(洞) — '골 동'. '동굴(洞窟)'의 동.", ex: { zh: "墙上有一个洞。", pinyin: "qiáng shang yǒu yí ge dòng", ko: "벽에 구멍이 하나 있어요." } },
        { zh: "豆腐", pinyin: "dòufu", ko: "두부", pos: "명사", hanja: "두부(豆腐) — '豆'는 콩 두, '腐'는 썩을 부.", ex: { zh: "我喜欢吃豆腐。", pinyin: "wǒ xǐhuan chī dòufu", ko: "저는 두부 먹는 걸 좋아해요." } },
        { zh: "对方", pinyin: "duìfāng", ko: "상대방, 상대편", pos: "명사", hanja: "대방(對方) — '對'는 대할 대, '方'은 모 방.", ex: { zh: "要考虑对方的感受。", pinyin: "yào kǎolǜ duìfāng de gǎnshòu", ko: "상대방의 기분을 고려해야 해요." } },
        { zh: "对手", pinyin: "duìshǒu", ko: "상대, 적수, 라이벌", pos: "명사", hanja: "대수(對手) — '對'는 대할 대, '手'는 손 수.", ex: { zh: "他是我的强大对手。", pinyin: "tā shì wǒ de qiángdà duìshǒu", ko: "그는 저의 강력한 라이벌이에요." } },
        { zh: "对象", pinyin: "duìxiàng", ko: "대상; 사귀는 상대(애인)", pos: "명사", hanja: "대상(對象) — '對'는 대할 대, '象'은 코끼리·모양 상. 구어로 '결혼 상대·애인'도 뜻해요.", ex: { zh: "你有对象了吗？", pinyin: "nǐ yǒu duìxiàng le ma", ko: "사귀는 사람 있어요?" } },
        { zh: "法院", pinyin: "fǎyuàn", ko: "법원", pos: "명사", hanja: "법원(法院) — 한자 그대로.", ex: { zh: "他被告上了法院。", pinyin: "tā bèi gào shàng le fǎyuàn", ko: "그는 법원에 고소당했어요." } },
        { zh: "肥皂", pinyin: "féizào", ko: "비누", pos: "명사", hanja: "비조(肥皂) — '肥'는 살찔 비, '皂'는 검을·비누 조.", ex: { zh: "用肥皂洗手。", pinyin: "yòng féizào xǐ shǒu", ko: "비누로 손을 씻어요." } },
        { zh: "废话", pinyin: "fèihuà", ko: "쓸데없는 말, 군말", pos: "명사", hanja: "폐화(廢話) — '廢'는 폐할 폐, '話'는 말씀 화.", ex: { zh: "别说废话了。", pinyin: "bié shuō fèihuà le", ko: "쓸데없는 말 그만하세요." } },
        { zh: "肺", pinyin: "fèi", ko: "폐, 허파", pos: "명사", hanja: "폐(肺) — '허파 폐'. '폐렴(肺炎)'의 폐.", ex: { zh: "吸烟对肺不好。", pinyin: "xīyān duì fèi bù hǎo", ko: "흡연은 폐에 안 좋아요." } },
        { zh: "费用", pinyin: "fèiyòng", ko: "비용, 경비", pos: "명사", hanja: "비용(費用) — '費'는 쓸 비, '用'은 쓸 용.", ex: { zh: "这次旅行费用不高。", pinyin: "zhè cì lǚxíng fèiyòng bù gāo", ko: "이번 여행 비용은 높지 않아요." } },
        { zh: "风格", pinyin: "fēnggé", ko: "스타일, 풍격, 작풍", pos: "명사", hanja: "풍격(風格) — '風'은 바람 풍, '格'은 격식 격.", ex: { zh: "他的画很有风格。", pinyin: "tā de huà hěn yǒu fēnggé", ko: "그의 그림은 개성이 뚜렷해요." } },
        { zh: "风俗", pinyin: "fēngsú", ko: "풍속, 풍습", pos: "명사", hanja: "풍속(風俗) — '風'은 바람 풍, '俗'은 풍속 속.", ex: { zh: "各地风俗不同。", pinyin: "gèdì fēngsú bùtóng", ko: "지역마다 풍속이 달라요." } },
        { zh: "风险", pinyin: "fēngxiǎn", ko: "위험, 리스크", pos: "명사", hanja: "풍험(風險) — '風'은 바람 풍, '險'은 험할 험.", ex: { zh: "投资有一定的风险。", pinyin: "tóuzī yǒu yídìng de fēngxiǎn", ko: "투자에는 일정한 위험이 있어요." } },
        { zh: "房东", pinyin: "fángdōng", ko: "집주인, 임대인", pos: "명사", hanja: "방동(房東) — '房'은 방 방, '東'은 동녘 동. '주인'을 '东(동가)'이라 불러요.", ex: { zh: "房东今天来收房租。", pinyin: "fángdōng jīntiān lái shōu fángzū", ko: "집주인이 오늘 월세를 받으러 와요." } },
        { zh: "妇女", pinyin: "fùnǚ", ko: "여성, 부녀자", pos: "명사", hanja: "부녀(婦女) — '婦'는 며느리·여자 부, '女'는 여자 녀.", ex: { zh: "三月八日是妇女节。", pinyin: "sān yuè bā rì shì fùnǚ jié", ko: "3월 8일은 여성의 날이에요." } },
        { zh: "钢铁", pinyin: "gāngtiě", ko: "강철", pos: "명사", hanja: "강철(鋼鐵) — '鋼'은 강철 강, '鐵'은 쇠 철.", ex: { zh: "这座桥用钢铁建成。", pinyin: "zhè zuò qiáo yòng gāngtiě jiànchéng", ko: "이 다리는 강철로 지어졌어요." } },
        { zh: "胳膊", pinyin: "gēbo", ko: "팔", pos: "명사", ex: { zh: "他的胳膊很有力。", pinyin: "tā de gēbo hěn yǒulì", ko: "그는 팔에 힘이 있어요." } },
        { zh: "鸽子", pinyin: "gēzi", ko: "비둘기", pos: "명사", hanja: "합자(鴿子) — '鴿'은 비둘기 합.", ex: { zh: "广场上有很多鸽子。", pinyin: "guǎngchǎng shang yǒu hěn duō gēzi", ko: "광장에 비둘기가 많아요." } },
        { zh: "工厂", pinyin: "gōngchǎng", ko: "공장", pos: "명사", hanja: "공창(工廠) — '工'은 장인 공, '廠'은 헛간·공장 창.", ex: { zh: "他在工厂工作。", pinyin: "tā zài gōngchǎng gōngzuò", ko: "그는 공장에서 일해요." } },
        { zh: "工程师", pinyin: "gōngchéngshī", ko: "엔지니어, 기사", pos: "명사", hanja: "공정사(工程師) — '工程'은 공정, '師'는 스승·전문가 사.", ex: { zh: "他是一名工程师。", pinyin: "tā shì yì míng gōngchéngshī", ko: "그는 엔지니어예요." } },
        { zh: "工人", pinyin: "gōngrén", ko: "노동자, 근로자", pos: "명사", hanja: "공인(工人) — '工'은 장인 공, '人'은 사람 인.", ex: { zh: "工人们正在修路。", pinyin: "gōngrénmen zhèngzài xiū lù", ko: "노동자들이 도로를 보수하고 있어요." } },
        { zh: "工业", pinyin: "gōngyè", ko: "공업, 산업", pos: "명사", hanja: "공업(工業) — '工'은 장인 공, '業'은 업 업.", ex: { zh: "这个城市工业很发达。", pinyin: "zhège chéngshì gōngyè hěn fādá", ko: "이 도시는 공업이 발달했어요." } },
        { zh: "公寓", pinyin: "gōngyù", ko: "아파트, 공동 주택", pos: "명사", hanja: "공우(公寓) — '公'은 공평할 공, '寓'는 부칠·거처 우.", ex: { zh: "他住在一套公寓里。", pinyin: "tā zhù zài yí tào gōngyù lǐ", ko: "그는 아파트에 살아요." } },
        { zh: "公元", pinyin: "gōngyuán", ko: "서기, 기원", pos: "명사", hanja: "공원(公元) — '公'은 공평할 공, '元'은 으뜸 원. 서력 연도를 가리켜요.", ex: { zh: "他生于公元前一百年。", pinyin: "tā shēng yú gōngyuán qián yìbǎi nián", ko: "그는 기원전 100년에 태어났어요." } },
        { zh: "公主", pinyin: "gōngzhǔ", ko: "공주", pos: "명사", hanja: "공주(公主) — '公'은 공평할 공, '主'는 주인 주.", ex: { zh: "她像公主一样漂亮。", pinyin: "tā xiàng gōngzhǔ yíyàng piàoliang", ko: "그녀는 공주처럼 예뻐요." } },
        { zh: "功夫", pinyin: "gōngfu", ko: "(들인) 노력·시간; 무술, 쿵후", pos: "명사", hanja: "공부(功夫) — '功'은 공 공, '夫'는 지아비 부. '들인 공력·무술'을 뜻해요. 한국어 '공부'와 다른 가짜동족어예요.", ex: { zh: "他练了很多年功夫。", pinyin: "tā liàn le hěn duō nián gōngfu", ko: "그는 여러 해 동안 무술을 연마했어요." } },
        { zh: "功能", pinyin: "gōngnéng", ko: "기능", pos: "명사", hanja: "공능(功能) — '功'은 공 공, '能'은 능할 능. 한국어 '기능'에 해당해요.", ex: { zh: "这个手机功能很多。", pinyin: "zhège shǒujī gōngnéng hěn duō", ko: "이 휴대폰은 기능이 많아요." } },
        { zh: "姑姑", pinyin: "gūgu", ko: "고모", pos: "명사", hanja: "고고(姑姑) — '姑'는 시어머니·고모 고. 아버지의 누이를 가리켜요.", ex: { zh: "我姑姑住在上海。", pinyin: "wǒ gūgu zhù zài Shànghǎi", ko: "제 고모는 상하이에 살아요." } },
        { zh: "姑娘", pinyin: "gūniang", ko: "처녀, 아가씨, 소녀", pos: "명사", hanja: "고낭(姑娘) — '姑'는 고모·여자 고, '娘'은 아가씨 낭.", ex: { zh: "那个姑娘很漂亮。", pinyin: "nàge gūniang hěn piàoliang", ko: "저 아가씨는 예뻐요." } },
        { zh: "股票", pinyin: "gǔpiào", ko: "주식, 주권", pos: "명사", hanja: "고표(股票) — '股'는 넓적다리·몫 고, '票'는 표 표.", ex: { zh: "他在炒股票。", pinyin: "tā zài chǎo gǔpiào", ko: "그는 주식 투자를 하고 있어요." } },
        { zh: "骨头", pinyin: "gǔtou", ko: "뼈", pos: "명사", hanja: "골두(骨頭) — '骨'은 뼈 골, '頭'는 머리 두.", ex: { zh: "狗在啃骨头。", pinyin: "gǒu zài kěn gǔtou", ko: "개가 뼈를 갉아 먹고 있어요." } },
        { zh: "固体", pinyin: "gùtǐ", ko: "고체", pos: "명사", hanja: "고체(固體) — '固'는 굳을 고, '體'는 몸 체.", ex: { zh: "冰是固体。", pinyin: "bīng shì gùtǐ", ko: "얼음은 고체예요." } },
        { zh: "海关", pinyin: "hǎiguān", ko: "세관", pos: "명사", hanja: "해관(海關) — '海'는 바다 해, '關'은 빗장·관문 관. 한국 '세관'에 해당해요.", ex: { zh: "过海关时要检查行李。", pinyin: "guò hǎiguān shí yào jiǎnchá xíngli", ko: "세관을 지날 때 짐을 검사해요." } },
        { zh: "海鲜", pinyin: "hǎixiān", ko: "해산물", pos: "명사", hanja: "해선(海鮮) — '海'는 바다 해, '鮮'은 고울·생선 선.", ex: { zh: "这家店的海鲜很新鲜。", pinyin: "zhè jiā diàn de hǎixiān hěn xīnxiān", ko: "이 가게 해산물은 신선해요." } },
        { zh: "合同", pinyin: "hétong", ko: "계약, 계약서", pos: "명사", hanja: "합동(合同) — '合'은 합할 합, '同'은 같을 동. 한국어 '합동'과 달리 '계약'을 뜻하는 가짜동족어예요.", ex: { zh: "我们签了合同。", pinyin: "wǒmen qiān le hétong", ko: "우리는 계약서에 서명했어요." } },
        { zh: "合影", pinyin: "héyǐng", ko: "단체 사진; 함께 사진 찍다", pos: "명사", hanja: "합영(合影) — '合'은 합할 합, '影'은 그림자·사진 영.", ex: { zh: "我们一起拍张合影吧。", pinyin: "wǒmen yìqǐ pāi zhāng héyǐng ba", ko: "우리 같이 사진 한 장 찍어요." } },
        { zh: "核心", pinyin: "héxīn", ko: "핵심, 중심", pos: "명사", hanja: "핵심(核心) — '核'은 씨 핵, '心'은 마음 심.", ex: { zh: "这是问题的核心。", pinyin: "zhè shì wèntí de héxīn", ko: "이것이 문제의 핵심이에요." } },
        { zh: "后果", pinyin: "hòuguǒ", ko: "(나쁜) 결과, 뒤탈", pos: "명사", hanja: "후과(後果) — '後'는 뒤 후, '果'는 열매·결과 과. 주로 부정적 결과예요.", ex: { zh: "你要考虑后果。", pinyin: "nǐ yào kǎolǜ hòuguǒ", ko: "당신은 결과를 고려해야 해요." } },
        { zh: "胡同", pinyin: "hútòng", ko: "골목, 후퉁", pos: "명사", ex: { zh: "他家在一条小胡同里。", pinyin: "tā jiā zài yì tiáo xiǎo hútòng lǐ", ko: "그의 집은 작은 골목 안에 있어요." } },
        { zh: "胡须", pinyin: "húxū", ko: "수염, 턱수염", pos: "명사", hanja: "호수(鬍鬚) — '鬍'는 수염 호, '鬚'는 수염 수.", ex: { zh: "爷爷留着白胡须。", pinyin: "yéye liú zhe bái húxū", ko: "할아버지는 흰 수염을 기르고 있어요." } },
        { zh: "蝴蝶", pinyin: "húdié", ko: "나비", pos: "명사", hanja: "호접(蝴蝶) — '蝴'는 나비 호, '蝶'은 나비 접.", ex: { zh: "花上有一只蝴蝶。", pinyin: "huā shang yǒu yì zhī húdié", ko: "꽃 위에 나비 한 마리가 있어요." } },
        { zh: "花生", pinyin: "huāshēng", ko: "땅콩", pos: "명사", hanja: "화생(花生) — '花'는 꽃 화, '生'은 날 생.", ex: { zh: "我喜欢吃花生。", pinyin: "wǒ xǐhuan chī huāshēng", ko: "저는 땅콩 먹는 걸 좋아해요." } },
        { zh: "化学", pinyin: "huàxué", ko: "화학", pos: "명사", hanja: "화학(化學) — '化'는 될 화, '學'은 배울 학.", ex: { zh: "他的化学成绩很好。", pinyin: "tā de huàxué chéngjì hěn hǎo", ko: "그는 화학 성적이 좋아요." } },
        { zh: "话题", pinyin: "huàtí", ko: "화제, 이야깃거리", pos: "명사", hanja: "화제(話題) — '話'는 말씀 화, '題'는 제목 제.", ex: { zh: "我们换个话题吧。", pinyin: "wǒmen huàn ge huàtí ba", ko: "우리 화제를 바꿔요." } },
        { zh: "幻想", pinyin: "huànxiǎng", ko: "환상; 공상하다", pos: "명사", hanja: "환상(幻想) — '幻'은 헛보일 환, '想'은 생각 상.", ex: { zh: "别再幻想了。", pinyin: "bié zài huànxiǎng le", ko: "더는 헛된 공상 마세요." } },
        { zh: "皇帝", pinyin: "huángdì", ko: "황제", pos: "명사", hanja: "황제(皇帝) — '皇'은 임금 황, '帝'는 임금 제.", ex: { zh: "他是古代的皇帝。", pinyin: "tā shì gǔdài de huángdì", ko: "그는 고대의 황제예요." } },
        { zh: "皇后", pinyin: "huánghòu", ko: "황후", pos: "명사", hanja: "황후(皇后) — '皇'은 임금 황, '后'는 왕후 후.", ex: { zh: "皇后住在宫里。", pinyin: "huánghòu zhù zài gōng lǐ", ko: "황후는 궁궐에 살아요." } },
        { zh: "黄瓜", pinyin: "huángguā", ko: "오이", pos: "명사", hanja: "황과(黃瓜) — '黃'은 누를 황, '瓜'는 오이 과.", ex: { zh: "我买了两根黄瓜。", pinyin: "wǒ mǎi le liǎng gēn huángguā", ko: "저는 오이 두 개를 샀어요." } },
        { zh: "黄金", pinyin: "huángjīn", ko: "황금, 금", pos: "명사", hanja: "황금(黃金) — '黃'은 누를 황, '金'은 쇠·금 금.", ex: { zh: "黄金的价格涨了。", pinyin: "huángjīn de jiàgé zhǎng le", ko: "금값이 올랐어요." } },
        { zh: "灰尘", pinyin: "huīchén", ko: "먼지", pos: "명사", hanja: "회진(灰塵) — '灰'는 재 회, '塵'은 티끌 진.", ex: { zh: "桌子上有很多灰尘。", pinyin: "zhuōzi shang yǒu hěn duō huīchén", ko: "책상에 먼지가 많아요." } },
        { zh: "服装", pinyin: "fúzhuāng", ko: "복장, 의류, 의상", pos: "명사", hanja: "복장(服裝) — '服'은 옷 복, '裝'은 꾸밀 장.", ex: { zh: "这家店卖运动服装。", pinyin: "zhè jiā diàn mài yùndòng fúzhuāng", ko: "이 가게는 운동복을 팔아요." } },
        { zh: "锅", pinyin: "guō", ko: "냄비, 솥, 가마", pos: "명사", hanja: "과(鍋) — '노구솥 과'.", ex: { zh: "锅里在煮汤。", pinyin: "guō lǐ zài zhǔ tāng", ko: "냄비에 국을 끓이고 있어요." } },
        { zh: "国籍", pinyin: "guójí", ko: "국적", pos: "명사", hanja: "국적(國籍) — '國'은 나라 국, '籍'은 문서·호적 적.", ex: { zh: "请问您的国籍是？", pinyin: "qǐngwèn nín de guójí shì", ko: "실례지만 국적이 어떻게 되세요?" } },
        { zh: "果实", pinyin: "guǒshí", ko: "열매, (노력의) 결실", pos: "명사", hanja: "과실(果實) — '果'는 열매 과, '實'은 열매 실.", ex: { zh: "秋天是收获果实的季节。", pinyin: "qiūtiān shì shōuhuò guǒshí de jìjié", ko: "가을은 열매를 거두는 계절이에요." } },
        { zh: "罐头", pinyin: "guàntou", ko: "통조림, 캔", pos: "명사", hanja: "관두(罐頭) — '罐'은 두레박·통 관, '頭'는 머리 두.", ex: { zh: "我买了一个鱼罐头。", pinyin: "wǒ mǎi le yí ge yú guàntou", ko: "저는 생선 통조림 하나를 샀어요." } },
        { zh: "广场", pinyin: "guǎngchǎng", ko: "광장", pos: "명사", hanja: "광장(廣場) — '廣'은 넓을 광, '場'은 마당 장.", ex: { zh: "广场上有很多人。", pinyin: "guǎngchǎng shang yǒu hěn duō rén", ko: "광장에 사람이 많아요." } },
        { zh: "规矩", pinyin: "guīju", ko: "규칙, 법도; 단정하다", pos: "명사", hanja: "규구(規矩) — '規'는 그림쇠·규칙 규, '矩'는 곱자·법도 구.", ex: { zh: "你要懂规矩。", pinyin: "nǐ yào dǒng guīju", ko: "당신은 규칙을 알아야 해요." } },
        { zh: "规则", pinyin: "guīzé", ko: "규칙, 규정", pos: "명사", hanja: "규칙(規則) — '規'는 규칙 규, '則'은 법칙 칙.", ex: { zh: "请遵守游戏规则。", pinyin: "qǐng zūnshǒu yóuxì guīzé", ko: "게임 규칙을 지켜 주세요." } },
        { zh: "柜台", pinyin: "guìtái", ko: "카운터, 판매대, 계산대", pos: "명사", hanja: "궤대(櫃臺) — '櫃'는 궤·장 궤, '臺'는 대 대.", ex: { zh: "请到柜台付款。", pinyin: "qǐng dào guìtái fùkuǎn", ko: "계산대에서 결제해 주세요." } },
        { zh: "管子", pinyin: "guǎnzi", ko: "관, 파이프, 대롱", pos: "명사", hanja: "관자(管子) — '管'은 대롱 관. (입력의 인명 '관자(管仲)'는 무시하고 일반 명사 '관·파이프'로 처리했어요.)", ex: { zh: "水从管子里流出来。", pinyin: "shuǐ cóng guǎnzi lǐ liú chūlái", ko: "물이 관에서 흘러나와요." } },
        { zh: "短信", pinyin: "duǎnxìn", ko: "문자 메시지, 단문 메시지", pos: "명사", hanja: "단신(短信) — '短'은 짧을 단, '信'은 믿을·편지 신.", ex: { zh: "我给你发个短信。", pinyin: "wǒ gěi nǐ fā ge duǎnxìn", ko: "제가 문자 하나 보낼게요." } },
        { zh: "光盘", pinyin: "guāngpán", ko: "CD, DVD, 광디스크", pos: "명사", hanja: "광반(光盤) — '光'은 빛 광, '盤'은 소반·쟁반 반.", ex: { zh: "这张光盘里有电影。", pinyin: "zhè zhāng guāngpán lǐ yǒu diànyǐng", ko: "이 CD에 영화가 들어 있어요." } },
        { zh: "光明", pinyin: "guāngmíng", ko: "광명, 밝음; (전망이) 밝다", pos: "명사", hanja: "광명(光明) — '光'은 빛 광, '明'은 밝을 명.", ex: { zh: "未来一片光明。", pinyin: "wèilái yí piàn guāngmíng", ko: "미래가 온통 밝아요." } },
        { zh: "古代", pinyin: "gǔdài", ko: "고대, 옛날", pos: "명사", hanja: "고대(古代) — '古'는 예 고, '代'는 대 대.", ex: { zh: "这是古代的故事。", pinyin: "zhè shì gǔdài de gùshi", ko: "이것은 고대의 이야기예요." } },
        { zh: "个人", pinyin: "gèrén", ko: "개인, 본인", pos: "명사", hanja: "개인(個人) — '個'는 낱 개, '人'은 사람 인.", ex: { zh: "这是我个人的看法。", pinyin: "zhè shì wǒ gèrén de kànfǎ", ko: "이건 제 개인적인 견해예요." } },
        { zh: "个性", pinyin: "gèxìng", ko: "개성, 성격", pos: "명사", hanja: "개성(個性) — '個'는 낱 개, '性'은 성품 성.", ex: { zh: "她很有个性。", pinyin: "tā hěn yǒu gèxìng", ko: "그녀는 개성이 강해요." } },
        { zh: "观点", pinyin: "guāndiǎn", ko: "관점, 견해", pos: "명사", hanja: "관점(觀點) — '觀'은 볼 관, '點'은 점 점.", ex: { zh: "我同意你的观点。", pinyin: "wǒ tóngyì nǐ de guāndiǎn", ko: "저는 당신의 관점에 동의해요." } },
        { zh: "观念", pinyin: "guānniàn", ko: "관념, 사고방식", pos: "명사", hanja: "관념(觀念) — '觀'은 볼 관, '念'은 생각 념.", ex: { zh: "他的观念很传统。", pinyin: "tā de guānniàn hěn chuántǒng", ko: "그의 관념은 매우 전통적이에요." } },
        { zh: "冠军", pinyin: "guànjūn", ko: "우승, 챔피언", pos: "명사", hanja: "관군(冠軍) — '冠'은 갓 관, '軍'은 군사 군. '으뜸'을 뜻해요.", ex: { zh: "他得了冠军。", pinyin: "tā dé le guànjūn", ko: "그가 우승을 차지했어요." } },
        { zh: "方式", pinyin: "fāngshì", ko: "방식, 방법", pos: "명사", hanja: "방식(方式) — '方'은 모 방, '式'은 법 식.", ex: { zh: "每个人的生活方式不同。", pinyin: "měi ge rén de shēnghuó fāngshì bùtóng", ko: "사람마다 생활 방식이 달라요." } },
        { zh: "繁荣", pinyin: "fánróng", ko: "번영; 번영하다", pos: "명사", hanja: "번영(繁榮) — '繁'은 번성할 번, '榮'은 영화 영.", ex: { zh: "经济越来越繁荣。", pinyin: "jīngjì yuèláiyuè fánróng", ko: "경제가 갈수록 번영해요." } },
        { zh: "反应", pinyin: "fǎnyìng", ko: "반응; 반응하다", pos: "명사", hanja: "반응(反應) — '反'은 돌이킬 반, '應'은 응할 응.", ex: { zh: "他的反应很快。", pinyin: "tā de fǎnyìng hěn kuài", ko: "그는 반응이 빨라요." } },
        { zh: "发票", pinyin: "fāpiào", ko: "영수증, 인보이스", pos: "명사", hanja: "발표(發票) — '發'은 필 발, '票'는 표 표. 한국어 '발표'와 다른 가짜동족어로, '영수증'이에요.", ex: { zh: "请给我开发票。", pinyin: "qǐng gěi wǒ kāi fāpiào", ko: "영수증을 발행해 주세요." } },
        { zh: "分配", pinyin: "fēnpèi", ko: "분배하다, 배정하다", pos: "동사", hanja: "분배(分配) — '分'은 나눌 분, '配'는 짝·나눌 배.", ex: { zh: "把工作合理分配。", pinyin: "bǎ gōngzuò hélǐ fēnpèi", ko: "일을 합리적으로 분배해요." } },
        { zh: "分析", pinyin: "fēnxī", ko: "분석하다; 분석", pos: "동사", hanja: "분석(分析) — '分'은 나눌 분, '析'은 쪼갤 석.", ex: { zh: "请分析一下原因。", pinyin: "qǐng fēnxī yíxià yuányīn", ko: "원인을 한번 분석해 주세요." } },
        { zh: "分布", pinyin: "fēnbù", ko: "분포하다; 분포", pos: "동사", hanja: "분포(分佈) — '分'은 나눌 분, '佈'는 펼 포.", ex: { zh: "人口分布很不均匀。", pinyin: "rénkǒu fēnbù hěn bù jūnyún", ko: "인구 분포가 매우 고르지 않아요." } },
      ],
    },
    {
      name: "HSK5 보강 — 형용사·상태",
      icon: "🔴",
      words: [
        { zh: "调皮", pinyin: "tiáopí", ko: "장난스럽다, 짓궂다, 까불다", pos: "형용사", hanja: "조피(調皮) — '調'는 고를 조, '皮'는 가죽 피.", ex: { zh: "这孩子很调皮。", pinyin: "zhè háizi hěn tiáopí", ko: "이 아이는 장난기가 많아요." } },
        { zh: "独立", pinyin: "dúlì", ko: "독립적이다; 독립하다", pos: "형용사", hanja: "독립(獨立) — '獨'은 홀로 독, '立'은 설 립.", ex: { zh: "她经济上很独立。", pinyin: "tā jīngjì shang hěn dúlì", ko: "그녀는 경제적으로 독립적이에요." } },
        { zh: "独特", pinyin: "dútè", ko: "독특하다, 특별하다", pos: "형용사", hanja: "독특(獨特) — '獨'은 홀로 독, '特'은 특별할 특.", ex: { zh: "他的风格很独特。", pinyin: "tā de fēnggé hěn dútè", ko: "그의 스타일은 독특해요." } },
        { zh: "多余", pinyin: "duōyú", ko: "쓸데없다, 불필요하다, 여분의", pos: "형용사", hanja: "다여(多餘) — '多'는 많을 다, '餘'는 남을 여.", ex: { zh: "这句话是多余的。", pinyin: "zhè jù huà shì duōyú de", ko: "이 말은 군더더기예요." } },
        { zh: "恶劣", pinyin: "èliè", ko: "열악하다, 악랄하다, 험하다", pos: "형용사", hanja: "악렬(惡劣) — '惡'은 악할 악, '劣'은 못할 렬.", ex: { zh: "天气非常恶劣。", pinyin: "tiānqì fēicháng èliè", ko: "날씨가 매우 험악해요." } },
        { zh: "发达", pinyin: "fādá", ko: "발달하다, 번창하다; 발달한", pos: "형용사", hanja: "발달(發達) — '發'은 필 발, '達'은 통달할 달.", ex: { zh: "这里交通很发达。", pinyin: "zhèlǐ jiāotōng hěn fādá", ko: "이곳은 교통이 발달했어요." } },
        { zh: "愤怒", pinyin: "fènnù", ko: "분노하다, 화나다; 분노", pos: "형용사", hanja: "분노(憤怒) — '憤'은 성낼 분, '怒'는 성낼 노.", ex: { zh: "他感到非常愤怒。", pinyin: "tā gǎndào fēicháng fènnù", ko: "그는 몹시 분노를 느꼈어요." } },
        { zh: "疯狂", pinyin: "fēngkuáng", ko: "미친 듯하다, 광적이다", pos: "형용사", hanja: "풍광(瘋狂) — '瘋'은 미칠 풍, '狂'은 미칠 광.", ex: { zh: "他们疯狂地购物。", pinyin: "tāmen fēngkuáng de gòuwù", ko: "그들은 미친 듯이 쇼핑해요." } },
        { zh: "乖", pinyin: "guāi", ko: "(아이가) 얌전하다, 말을 잘 듣다", pos: "형용사", ex: { zh: "这个孩子很乖。", pinyin: "zhège háizi hěn guāi", ko: "이 아이는 참 착해요." } },
        { zh: "光滑", pinyin: "guānghuá", ko: "매끄럽다, 반들반들하다", pos: "형용사", hanja: "광활(光滑) — '光'은 빛 광, '滑'은 미끄러울 활.", ex: { zh: "这块石头很光滑。", pinyin: "zhè kuài shítou hěn guānghuá", ko: "이 돌은 매끄러워요." } },
        { zh: "光荣", pinyin: "guāngróng", ko: "영광스럽다, 영예롭다; 영광", pos: "형용사", hanja: "광영(光榮) — '光'은 빛 광, '榮'은 영화 영. 한국어 '영광'과 어순이 반대예요.", ex: { zh: "这是一件光荣的事。", pinyin: "zhè shì yí jiàn guāngróng de shì", ko: "이것은 영광스러운 일이에요." } },
        { zh: "豪华", pinyin: "háohuá", ko: "호화롭다, 화려하다", pos: "형용사", hanja: "호화(豪華) — '豪'는 호걸 호, '華'는 빛날 화.", ex: { zh: "这是一家豪华酒店。", pinyin: "zhè shì yì jiā háohuá jiǔdiàn", ko: "이곳은 호화 호텔이에요." } },
        { zh: "合法", pinyin: "héfǎ", ko: "합법적이다", pos: "형용사", hanja: "합법(合法) — '合'은 합할 합, '法'은 법 법.", ex: { zh: "这种行为是合法的。", pinyin: "zhè zhǒng xíngwéi shì héfǎ de", ko: "이런 행위는 합법적이에요." } },
        { zh: "合理", pinyin: "hélǐ", ko: "합리적이다, 타당하다", pos: "형용사", hanja: "합리(合理) — '合'은 합할 합, '理'는 이치 리.", ex: { zh: "这个价格很合理。", pinyin: "zhège jiàgé hěn hélǐ", ko: "이 가격은 합리적이에요." } },
        { zh: "糊涂", pinyin: "hútu", ko: "어리둥절하다, 멍청하다, 어수룩하다", pos: "형용사", hanja: "호도(糊塗) — '糊'는 풀 호, '塗'는 칠할 도. '머리가 흐리멍덩하다'.", ex: { zh: "我越想越糊涂。", pinyin: "wǒ yuè xiǎng yuè hútu", ko: "생각할수록 더 헷갈려요." } },
        { zh: "慌张", pinyin: "huāngzhāng", ko: "허둥대다, 당황하다", pos: "형용사", hanja: "황장(慌張) — '慌'은 어리둥절할 황, '張'은 베풀 장.", ex: { zh: "他显得有点慌张。", pinyin: "tā xiǎnde yǒudiǎn huāngzhāng", ko: "그는 좀 당황한 듯해요." } },
        { zh: "灰心", pinyin: "huīxīn", ko: "낙담하다, 의기소침하다", pos: "형용사", hanja: "회심(灰心) — '灰'는 재 회, '心'은 마음 심. '마음이 재처럼 식다'.", ex: { zh: "失败了也别灰心。", pinyin: "shībài le yě bié huīxīn", ko: "실패해도 낙담하지 마세요." } },
        { zh: "过分", pinyin: "guòfèn", ko: "지나치다, 과하다", pos: "형용사", hanja: "과분(過分) — '過'는 지날 과, '分'은 나눌·분수 분.", ex: { zh: "他的要求太过分了。", pinyin: "tā de yāoqiú tài guòfèn le", ko: "그의 요구는 너무 지나쳐요." } },
        { zh: "古典", pinyin: "gǔdiǎn", ko: "고전적이다, 클래식한", pos: "형용사", hanja: "고전(古典) — '古'는 예 고, '典'은 법·책 전.", ex: { zh: "我喜欢古典音乐。", pinyin: "wǒ xǐhuan gǔdiǎn yīnyuè", ko: "저는 클래식 음악을 좋아해요." } },
        { zh: "古老", pinyin: "gǔlǎo", ko: "오래되다, 유서 깊다", pos: "형용사", hanja: "고로(古老) — '古'는 예 고, '老'는 늙을 로.", ex: { zh: "这是一座古老的城市。", pinyin: "zhè shì yí zuò gǔlǎo de chéngshì", ko: "이곳은 유서 깊은 도시예요." } },
        { zh: "公平", pinyin: "gōngpíng", ko: "공평하다, 공정하다", pos: "형용사", hanja: "공평(公平) — '公'은 공평할 공, '平'은 평평할 평.", ex: { zh: "这样做不公平。", pinyin: "zhèyàng zuò bù gōngpíng", ko: "이렇게 하는 건 불공평해요." } },
        { zh: "高档", pinyin: "gāodàng", ko: "고급이다, 상급의", pos: "형용사", hanja: "고당(高檔) — '高'는 높을 고, '檔'은 칸·등급 당.", ex: { zh: "这是高档商品。", pinyin: "zhè shì gāodàng shāngpǐn", ko: "이것은 고급 상품이에요." } },
        { zh: "广大", pinyin: "guǎngdà", ko: "광대하다, 광범위하다, 폭넓다", pos: "형용사", hanja: "광대(廣大) — '廣'은 넓을 광, '大'는 큰 대.", ex: { zh: "得到广大群众的支持。", pinyin: "dédào guǎngdà qúnzhòng de zhīchí", ko: "폭넓은 대중의 지지를 얻어요." } },
        { zh: "和平", pinyin: "hépíng", ko: "평화; 평화롭다", pos: "명사", hanja: "화평(和平) — '和'는 화할 화, '平'은 평평할 평. (입력의 지명은 무시하고 일반 의미 '평화'로 처리했어요.)", ex: { zh: "我们都希望和平。", pinyin: "wǒmen dōu xīwàng hépíng", ko: "우리는 모두 평화를 바라요." } },
        { zh: "干脆", pinyin: "gāncuì", ko: "시원시원하다, 명쾌하다; 차라리", pos: "형용사", hanja: "건취(乾脆) — '乾'은 마를 건, '脆'는 연할·바삭할 취.", ex: { zh: "他做事很干脆。", pinyin: "tā zuòshì hěn gāncuì", ko: "그는 일을 시원시원하게 처리해요." } },
        { zh: "灰", pinyin: "huī", ko: "회색의; 재, 먼지", pos: "형용사", hanja: "회(灰) — '재 회'. 색으로는 '회색'이에요.", ex: { zh: "天空灰蒙蒙的。", pinyin: "tiānkōng huīméngméng de", ko: "하늘이 잿빛으로 흐려요." } },
        { zh: "横", pinyin: "héng", ko: "가로의, 가로지른; 가로획", pos: "형용사", hanja: "횡(橫) — '가로 횡'. '횡단(橫斷)'의 횡.", ex: { zh: "在纸上画一条横线。", pinyin: "zài zhǐ shang huà yì tiáo héng xiàn", ko: "종이에 가로줄을 하나 그어요." } },
        { zh: "高速", pinyin: "gāosù", ko: "고속의, 빠른", pos: "형용사", hanja: "고속(高速) — '高'는 높을 고, '速'은 빠를 속.", ex: { zh: "高速公路上车很多。", pinyin: "gāosù gōnglù shang chē hěn duō", ko: "고속도로에 차가 많아요." } },
        { zh: "过敏", pinyin: "guòmǐn", ko: "알레르기가 있다, 과민하다; 알레르기", pos: "형용사", hanja: "과민(過敏) — '過'는 지날 과, '敏'은 민첩할 민.", ex: { zh: "我对花粉过敏。", pinyin: "wǒ duì huāfěn guòmǐn", ko: "저는 꽃가루 알레르기가 있어요." } },
        { zh: "过期", pinyin: "guòqī", ko: "기한이 지나다, 만료되다", pos: "동사", hanja: "과기(過期) — '過'는 지날 과, '期'는 기약할 기.", ex: { zh: "这盒牛奶过期了。", pinyin: "zhè hé niúnǎi guòqī le", ko: "이 우유는 유통기한이 지났어요." } },
      ],
    },
    {
      name: "HSK5 보강 — 부사·기타",
      icon: "🔴",
      words: [
        { zh: "丁", pinyin: "dīng", ko: "장정, 인원; (천간) 정", pos: "명사", hanja: "정(丁) — '고무래·장정 정'. (입력의 '성씨 Dīng'은 무시하고 일반 의미로 처리했어요.)", ex: { zh: "他是家里的壮丁。", pinyin: "tā shì jiā lǐ de zhuàngdīng", ko: "그는 집안의 장정이에요." } },
        { zh: "对于", pinyin: "duìyú", ko: "~에 대하여, ~에 관해서", pos: "개사", hanja: "대어(對於) — '對'는 대할 대, '於'는 어조사 어.", ex: { zh: "对于这件事，我没意见。", pinyin: "duìyú zhè jiàn shì, wǒ méi yìjiàn", ko: "이 일에 대해 저는 이견이 없어요." } },
        { zh: "吨", pinyin: "dūn", ko: "톤(t, 무게 단위)", pos: "양사", ex: { zh: "这辆车能装五吨货。", pinyin: "zhè liàng chē néng zhuāng wǔ dūn huò", ko: "이 차는 화물 5톤을 실을 수 있어요." } },
        { zh: "凡是", pinyin: "fánshì", ko: "무릇, 대체로 ~한 것은 모두", pos: "부사", hanja: "범시(凡是) — '凡'은 무릇 범, '是'는 이·옳을 시.", ex: { zh: "凡是去过的人都说好。", pinyin: "fánshì qù guò de rén dōu shuō hǎo", ko: "가 본 사람은 모두 좋다고 해요." } },
        { zh: "反而", pinyin: "fǎnér", ko: "오히려, 도리어", pos: "부사", hanja: "반이(反而) — '反'은 돌이킬 반, '而'는 말이을 이.", ex: { zh: "他不但不累，反而很高兴。", pinyin: "tā búdàn bú lèi, fǎn'ér hěn gāoxìng", ko: "그는 피곤하기는커녕 오히려 기뻐해요." } },
        { zh: "反复", pinyin: "fǎnfù", ko: "반복하여, 거듭; 반복하다", pos: "부사", hanja: "반복(反復) — '反'은 돌이킬 반, '復'은 돌아올 복.", ex: { zh: "他反复练习这首歌。", pinyin: "tā fǎnfù liànxí zhè shǒu gē", ko: "그는 이 노래를 반복해 연습해요." } },
        { zh: "反正", pinyin: "fǎnzhèng", ko: "어차피, 어쨌든", pos: "부사", hanja: "반정(反正) — '反'은 돌이킬 반, '正'은 바를 정.", ex: { zh: "反正我都要去。", pinyin: "fǎnzhèng wǒ dōu yào qù", ko: "어차피 저는 갈 거예요." } },
        { zh: "纷纷", pinyin: "fēnfēn", ko: "잇달아, 너도나도, 분분히", pos: "부사", hanja: "분분(紛紛) — '紛'은 어지러울 분.", ex: { zh: "大家纷纷表示同意。", pinyin: "dàjiā fēnfēn biǎoshì tóngyì", ko: "모두가 너도나도 동의를 표했어요." } },
        { zh: "非", pinyin: "fēi", ko: "아니다, ~이 아니다; (접두) 비-", pos: "부사", hanja: "비(非) — '아닐 비'. (입력의 '아프리카 약칭'은 무시하고 일반 의미로 처리했어요.)", ex: { zh: "这非他不可。", pinyin: "zhè fēi tā bùkě", ko: "이건 그가 아니면 안 돼요." } },
        { zh: "更加", pinyin: "gèngjiā", ko: "더욱, 한층 더", pos: "부사", hanja: "갱가(更加) — '更'은 다시 갱, '加'는 더할 가.", ex: { zh: "她比以前更加漂亮了。", pinyin: "tā bǐ yǐqián gèngjiā piàoliang le", ko: "그녀는 예전보다 더 예뻐졌어요." } },
        { zh: "各自", pinyin: "gèzì", ko: "각자, 제각기", pos: "대명사", hanja: "각자(各自) — '各'은 각각 각, '自'는 스스로 자.", ex: { zh: "大家各自回家吧。", pinyin: "dàjiā gèzì huí jiā ba", ko: "모두 각자 집으로 가요." } },
        { zh: "个别", pinyin: "gèbié", ko: "개별적인, 일부의, 극소수의", pos: "형용사", hanja: "개별(個別) — '個'는 낱 개, '別'은 다를 별.", ex: { zh: "只有个别人反对。", pinyin: "zhǐyǒu gèbié rén fǎnduì", ko: "극소수 사람만 반대해요." } },
        { zh: "根本", pinyin: "gēnběn", ko: "전혀, 도무지; 근본", pos: "부사", hanja: "근본(根本) — '根'은 뿌리 근, '本'은 근본 본.", ex: { zh: "我根本不知道这件事。", pinyin: "wǒ gēnběn bù zhīdào zhè jiàn shì", ko: "저는 이 일을 전혀 몰랐어요." } },
        { zh: "赶紧", pinyin: "gǎnjǐn", ko: "서둘러, 얼른, 급히", pos: "부사", hanja: "간긴(趕緊) — '趕'은 쫓을 간, '緊'은 긴할 긴.", ex: { zh: "快下雨了，赶紧回家吧。", pinyin: "kuài xià yǔ le, gǎnjǐn huí jiā ba", ko: "곧 비가 오니 얼른 집에 가요." } },
        { zh: "赶快", pinyin: "gǎnkuài", ko: "빨리, 어서, 서둘러", pos: "부사", hanja: "간쾌(趕快) — '趕'은 쫓을 간, '快'는 빠를 쾌.", ex: { zh: "你赶快去吧。", pinyin: "nǐ gǎnkuài qù ba", ko: "당신 어서 가세요." } },
        { zh: "感想", pinyin: "gǎnxiǎng", ko: "감상, 소감, 느낀 점", pos: "명사", hanja: "감상(感想) — '感'은 느낄 감, '想'은 생각 상.", ex: { zh: "说说你的感想吧。", pinyin: "shuōshuo nǐ de gǎnxiǎng ba", ko: "당신의 소감을 말해 보세요." } },
        { zh: "干活儿", pinyin: "gàn huór", ko: "일을 하다, 노동하다", pos: "동사", hanja: "간활아(幹活兒) — '幹'은 줄기·할 간, '活'은 살·일 활.", ex: { zh: "他在工地干活儿。", pinyin: "tā zài gōngdì gànhuór", ko: "그는 공사장에서 일해요." } },
        { zh: "搞", pinyin: "gǎo", ko: "하다, 만들다, 처리하다", pos: "동사", ex: { zh: "这件事被他搞砸了。", pinyin: "zhè jiàn shì bèi tā gǎozá le", ko: "이 일은 그가 망쳐 버렸어요." } },
        { zh: "滚", pinyin: "gǔn", ko: "구르다; (물이) 끓다; 꺼지다", pos: "동사", hanja: "곤(滾) — '흐를·구를 곤'.", ex: { zh: "球滚到了地上。", pinyin: "qiú gǔn dào le dì shang", ko: "공이 바닥으로 굴러갔어요." } },
        { zh: "幅", pinyin: "fú", ko: "폭(그림·천을 세는 양사)", pos: "양사", hanja: "폭(幅) — '폭 폭'. 그림·천 등을 세요.", ex: { zh: "墙上挂着一幅画。", pinyin: "qiáng shang guà zhe yì fú huà", ko: "벽에 그림 한 폭이 걸려 있어요." } },
        { zh: "根", pinyin: "gēn", ko: "뿌리; (가늘고 긴 것을 세는) ~개", pos: "양사", hanja: "근(根) — '뿌리 근'. 끈·막대 등을 세는 양사로도 써요.", ex: { zh: "给我一根香蕉。", pinyin: "gěi wǒ yì gēn xiāngjiāo", ko: "바나나 한 개 주세요." } },
        { zh: "方", pinyin: "fāng", ko: "네모; 쪽, 측; 방법", pos: "명사", hanja: "방(方) — '모 방'. (입력의 '성씨 Fāng'은 무시하고 일반 의미로 처리했어요.)", ex: { zh: "双方都同意了。", pinyin: "shuāngfāng dōu tóngyì le", ko: "양측 모두 동의했어요." } },
        { zh: "仿佛", pinyin: "fǎngfú", ko: "마치 ~인 듯하다, 흡사", pos: "부사", hanja: "방불(仿佛) — '仿'은 본뜰 방, '佛'은 비슷할 불. 한국어 '방불하다'와 통해요.", ex: { zh: "他仿佛睡着了。", pinyin: "tā fǎngfú shuìzháo le", ko: "그는 마치 잠든 것 같아요." } },
        { zh: "分别", pinyin: "fēnbié", ko: "각각, 따로; 헤어지다", pos: "부사", hanja: "분별(分別) — '分'은 나눌 분, '別'은 다를 별.", ex: { zh: "他们分别住在两个城市。", pinyin: "tāmen fēnbié zhù zài liǎng ge chéngshì", ko: "그들은 각각 두 도시에 살아요." } },
        { zh: "隔壁", pinyin: "gébì", ko: "옆집, 이웃, 바로 옆방", pos: "명사", hanja: "격벽(隔壁) — '隔'은 사이뜰 격, '壁'은 벽 벽. '벽 하나 사이'.", ex: { zh: "隔壁住着一对老夫妻。", pinyin: "gébì zhù zhe yí duì lǎo fūqī", ko: "옆집에 노부부가 살아요." } },
        { zh: "怪不得", pinyin: "guàibude", ko: "어쩐지, 그래서 ~구나", pos: "부사", hanja: "괴부득(怪不得) — '怪'는 괴이할 괴. '탓할 게 없다'에서 온 표현이에요.", ex: { zh: "怪不得他没来，原来生病了。", pinyin: "guàibude tā méi lái, yuánlái shēngbìng le", ko: "어쩐지 그가 안 왔더니, 알고 보니 아팠군요." } },
        { zh: "何必", pinyin: "hébì", ko: "구태여 ~할 필요가 있나, 굳이", pos: "부사", hanja: "하필(何必) — '何'는 어찌 하, '必'은 반드시 필.", ex: { zh: "你何必这么着急？", pinyin: "nǐ hébì zhème zháojí", ko: "굳이 그렇게 서두를 필요가 있나요?" } },
        { zh: "哈", pinyin: "hā", ko: "하하(웃음소리); (입김을) 후 불다", pos: "감탄사", ex: { zh: "哈，原来是你呀！", pinyin: "hā, yuánlái shì nǐ ya", ko: "하, 알고 보니 너였구나!" } },
        { zh: "官", pinyin: "guān", ko: "관리, 관원; 기관", pos: "명사", hanja: "관(官) — '벼슬 관'. (입력의 '성씨 Guān'은 무시하고 일반 의미 '관리'로 처리했어요.)", ex: { zh: "他是个清廉的官。", pinyin: "tā shì ge qīnglián de guān", ko: "그는 청렴한 관리예요." } },
        { zh: "华裔", pinyin: "huáyì", ko: "화교 후손, 중국계(외국 국적)", pos: "명사", hanja: "화예(華裔) — '華'는 빛날·중국 화, '裔'는 후손 예.", ex: { zh: "他是美国华裔。", pinyin: "tā shì Měiguó huáyì", ko: "그는 미국 국적의 중국계예요." } },
        { zh: "国庆节", pinyin: "guóqìngjié", ko: "국경절(중국 건국 기념일, 10월 1일)", pos: "명사", hanja: "국경절(國慶節) — '國'은 나라 국, '慶'은 경사 경, '節'은 마디·명절 절.", ex: { zh: "国庆节我们放假七天。", pinyin: "guóqìngjié wǒmen fàngjià qī tiān", ko: "국경절에 우리는 7일 쉬어요." } },
        { zh: "拐弯", pinyin: "guǎiwān", ko: "방향을 틀다, 모퉁이를 돌다", pos: "동사", hanja: "괴만(拐彎) — '拐'는 후릴·꺾을 괴, '彎'은 굽을 만.", ex: { zh: "前面拐弯就到了。", pinyin: "qiánmiàn guǎiwān jiù dào le", ko: "앞에서 돌면 바로 도착해요." } },
        { zh: "光临", pinyin: "guānglín", ko: "왕림하다, 찾아 주시다", pos: "동사", hanja: "광림(光臨) — '光'은 빛 광, '臨'은 임할 림. 손님을 높이는 표현이에요.", ex: { zh: "欢迎光临！", pinyin: "huānyíng guānglín", ko: "어서 오세요!" } },
        { zh: "观察", pinyin: "guānchá", ko: "관찰하다; 관찰", pos: "동사", hanja: "관찰(觀察) — '觀'은 볼 관, '察'은 살필 찰.", ex: { zh: "请仔细观察这张图。", pinyin: "qǐng zǐxì guānchá zhè zhāng tú", ko: "이 그림을 자세히 관찰해 주세요." } },
        { zh: "壶", pinyin: "hú", ko: "주전자, 병; (병에 든 것을 세는) 병", pos: "양사", hanja: "호(壺) — '병·단지 호'.", ex: { zh: "请给我一壶茶。", pinyin: "qǐng gěi wǒ yì hú chá", ko: "차 한 주전자 주세요." } },
      ],
    },
  ],
};

export default themes;
