/**
 * 6급 어휘 — 고급 추상어와 성어의 세계
 * 격식 있는 글과 깊이 있는 토론을 위한 HSK6급 핵심어 · 사자성어.
 */
export default {
  level: "H6",
  title: "6급 어휘",
  desc: "고급 추상어·정치사회·심리, 그리고 사자성어까지 — 한국 한자음과 그대로 통하는 HSK6급 어휘예요.",
  themes: [
    {
      name: "고급 추상 명사",
      words: [
        {
          zh: "范畴",
          pinyin: "fànchóu",
          ko: "범주",
          pos: "명사",
          hanja: "범주(範疇) — 한자 그대로예요.",
          ex: { zh: "这个问题属于哲学的范畴。", pinyin: "zhège wèntí shǔyú zhéxué de fànchóu", ko: "이 문제는 철학의 범주에 속해요." },
        },
        {
          zh: "宗旨",
          pinyin: "zōngzhǐ",
          ko: "취지, 근본 목적",
          pos: "명사",
          hanja: "종지(宗旨) — '으뜸 되는 뜻'. '취지'로 외워요.",
          ex: { zh: "服务社会是这个组织的宗旨。", pinyin: "fúwù shèhuì shì zhège zǔzhī de zōngzhǐ", ko: "사회에 봉사하는 것이 이 단체의 취지예요." },
        },
        {
          zh: "前提",
          pinyin: "qiántí",
          ko: "전제",
          pos: "명사",
          hanja: "전제(前提) — 한자 그대로예요.",
          ex: { zh: "互相信任是合作的前提。", pinyin: "hùxiāng xìnrèn shì hézuò de qiántí", ko: "상호 신뢰가 협력의 전제예요." },
        },
        {
          zh: "本能",
          pinyin: "běnnéng",
          ko: "본능",
          pos: "명사",
          hanja: "본능(本能) — 한자 그대로예요.",
          ex: { zh: "求生是动物的本能。", pinyin: "qiúshēng shì dòngwù de běnnéng", ko: "살고자 하는 것은 동물의 본능이에요." },
        },
        {
          zh: "潜力",
          pinyin: "qiánlì",
          ko: "잠재력",
          pos: "명사",
          hanja: "잠력(潛力) — '潛(잠길 잠)+力(힘)'. '잠재력'이에요.",
          ex: { zh: "这个孩子很有潜力。", pinyin: "zhège háizi hěn yǒu qiánlì", ko: "이 아이는 잠재력이 커요." },
        },
        {
          zh: "舆论",
          pinyin: "yúlùn",
          ko: "여론",
          pos: "명사",
          hanja: "여론(輿論) — 한자 그대로예요.",
          ex: { zh: "这件事引起了社会舆论的关注。", pinyin: "zhè jiàn shì yǐnqǐ le shèhuì yúlùn de guānzhù", ko: "이 일은 사회 여론의 주목을 받았어요." },
        },
        {
          zh: "意识形态",
          pinyin: "yìshí xíngtài",
          ko: "이데올로기, 의식 형태",
          pos: "명사",
          hanja: "의식형태(意識形態) — 한자 그대로 '이데올로기'를 옮긴 말이에요.",
          ex: { zh: "不同的意识形态导致了冲突。", pinyin: "bùtóng de yìshí xíngtài dǎozhì le chōngtū", ko: "서로 다른 이데올로기가 갈등을 불러왔어요." },
        },
        {
          zh: "底线",
          pinyin: "dǐxiàn",
          ko: "마지노선, 최저선",
          pos: "명사",
          hanja: "저선(底線) — '밑바닥 선'. 양보할 수 없는 한계예요.",
          ex: { zh: "诚实是我做人的底线。", pinyin: "chéngshí shì wǒ zuòrén de dǐxiàn", ko: "정직함은 제 삶의 마지노선이에요." },
        },
        {
          zh: "格局",
          pinyin: "géjú",
          ko: "구도, 판세",
          pos: "명사",
          ex: { zh: "世界经济格局正在发生变化。", pinyin: "shìjiè jīngjì géjú zhèngzài fāshēng biànhuà", ko: "세계 경제의 판세가 변하고 있어요." },
        },
        {
          zh: "渊源",
          pinyin: "yuānyuán",
          ko: "연원, 근원",
          pos: "명사",
          hanja: "연원(淵源) — '깊은 못의 근원'. 일의 뿌리예요.",
          ex: { zh: "两国的文化渊源很深。", pinyin: "liǎng guó de wénhuà yuānyuán hěn shēn", ko: "두 나라의 문화적 연원은 깊어요." },
        },
      ],
    },
    {
      name: "정치와 사회",
      words: [
        {
          zh: "体制",
          pinyin: "tǐzhì",
          ko: "체제",
          pos: "명사",
          hanja: "체제(體制) — 한자 그대로예요.",
          ex: { zh: "经济体制改革取得了成果。", pinyin: "jīngjì tǐzhì gǎigé qǔdé le chéngguǒ", ko: "경제 체제 개혁이 성과를 거뒀어요." },
        },
        {
          zh: "改革",
          pinyin: "gǎigé",
          ko: "개혁",
          pos: "명사",
          hanja: "개혁(改革) — 한자 그대로예요.",
          ex: { zh: "政府推行了一系列改革。", pinyin: "zhèngfǔ tuīxíng le yíxìliè gǎigé", ko: "정부는 일련의 개혁을 추진했어요." },
        },
        {
          zh: "主权",
          pinyin: "zhǔquán",
          ko: "주권",
          pos: "명사",
          hanja: "주권(主權) — 한자 그대로예요.",
          ex: { zh: "国家主权不容侵犯。", pinyin: "guójiā zhǔquán bùróng qīnfàn", ko: "국가 주권은 침해될 수 없어요." },
        },
        {
          zh: "舆情",
          pinyin: "yúqíng",
          ko: "여론 동향, 민심",
          pos: "명사",
          hanja: "여정(輿情) — '여러 사람의 마음', 곧 민심이에요.",
          ex: { zh: "政府密切关注网络舆情。", pinyin: "zhèngfǔ mìqiè guānzhù wǎngluò yúqíng", ko: "정부는 인터넷 여론 동향을 면밀히 주시해요." },
        },
        {
          zh: "歧视",
          pinyin: "qíshì",
          ko: "차별, 차별하다",
          pos: "동사",
          hanja: "기시(歧視) — '다르게 보다', 곧 차별이에요.",
          ex: { zh: "我们应该反对一切歧视。", pinyin: "wǒmen yīnggāi fǎnduì yíqiè qíshì", ko: "우리는 모든 차별에 반대해야 해요." },
        },
        {
          zh: "福利",
          pinyin: "fúlì",
          ko: "복지",
          pos: "명사",
          hanja: "복리(福利) — 한국어 '복리·복지'와 같아요.",
          ex: { zh: "这家公司的福利很好。", pinyin: "zhè jiā gōngsī de fúlì hěn hǎo", ko: "이 회사는 복지가 좋아요." },
        },
        {
          zh: "腐败",
          pinyin: "fǔbài",
          ko: "부패하다, 타락하다",
          pos: "형용사",
          hanja: "부패(腐敗) — 한자 그대로예요.",
          ex: { zh: "反对腐败是长期的任务。", pinyin: "fǎnduì fǔbài shì chángqī de rènwù", ko: "부패에 맞서는 일은 장기적 과제예요." },
        },
        {
          zh: "贫困",
          pinyin: "pínkùn",
          ko: "빈곤하다",
          pos: "형용사",
          hanja: "빈곤(貧困) — 한자 그대로예요.",
          ex: { zh: "政府努力帮助贫困地区。", pinyin: "zhèngfǔ nǔlì bāngzhù pínkùn dìqū", ko: "정부는 빈곤 지역을 돕고자 애써요." },
        },
        {
          zh: "趋于",
          pinyin: "qūyú",
          ko: "~로 기울다, ~해지는 추세다",
          pos: "동사",
          hanja: "추어(趨於) — '~로 향하여 가다'. 어떤 방향으로 기우는 거예요.",
          ex: { zh: "局势逐渐趋于稳定。", pinyin: "júshì zhújiàn qūyú wěndìng", ko: "정세가 점차 안정되는 추세예요." },
        },
        {
          zh: "倡导",
          pinyin: "chàngdǎo",
          ko: "제창하다, 앞장서 주장하다",
          pos: "동사",
          hanja: "창도(倡導) — '앞장서 이끌다'. 주의·운동을 제창하는 거예요.",
          ex: { zh: "我们倡导绿色出行。", pinyin: "wǒmen chàngdǎo lǜsè chūxíng", ko: "우리는 친환경 이동을 제창해요." },
        },
      ],
    },
    {
      name: "심리·태도 동사",
      words: [
        {
          zh: "领悟",
          pinyin: "lǐngwù",
          ko: "깨닫다, 터득하다",
          pos: "동사",
          hanja: "영오(領悟) — '거느려 깨닫다'. 이치를 터득하는 거예요.",
          ex: { zh: "他终于领悟了其中的道理。", pinyin: "tā zhōngyú lǐngwù le qízhōng de dàoli", ko: "그는 마침내 그 안의 이치를 깨달았어요." },
        },
        {
          zh: "陶醉",
          pinyin: "táozuì",
          ko: "도취하다, 심취하다",
          pos: "동사",
          hanja: "도취(陶醉) — 한자 그대로예요.",
          ex: { zh: "他陶醉在音乐里。", pinyin: "tā táozuì zài yīnyuè lǐ", ko: "그는 음악에 도취해 있어요." },
        },
        {
          zh: "畏惧",
          pinyin: "wèijù",
          ko: "두려워하다, 위축되다",
          pos: "동사",
          hanja: "외구(畏懼) — '畏(두려울 외)+懼(두려울 구)'. 두려워하는 거예요.",
          ex: { zh: "他面对困难毫不畏惧。", pinyin: "tā miànduì kùnnan háobù wèijù", ko: "그는 어려움 앞에서 조금도 두려워하지 않아요." },
        },
        {
          zh: "厌倦",
          pinyin: "yànjuàn",
          ko: "싫증나다, 권태를 느끼다",
          pos: "동사",
          hanja: "염권(厭倦) — '厭(싫을 염)+倦(게으를 권)'. 물려서 지치는 거예요.",
          ex: { zh: "他渐渐厌倦了这种生活。", pinyin: "tā jiànjiàn yànjuàn le zhè zhǒng shēnghuó", ko: "그는 점점 이런 생활에 싫증이 났어요." },
        },
        {
          zh: "执着",
          pinyin: "zhízhuó",
          ko: "집착하다, 끈질기다",
          pos: "형용사",
          hanja: "집착(執着) — 한자 그대로지만 '끈기 있다'는 긍정적 뜻으로도 써요.",
          ex: { zh: "他对梦想很执着。", pinyin: "tā duì mèngxiǎng hěn zhízhuó", ko: "그는 꿈을 향해 끈질겨요." },
        },
        {
          zh: "依赖",
          pinyin: "yīlài",
          ko: "의존하다, 기대다",
          pos: "동사",
          hanja: "의뢰(依賴) — 한국어 '의뢰'와 달리 '의존하다'는 뜻이에요.",
          ex: { zh: "孩子不应该过度依赖父母。", pinyin: "háizi bù yīnggāi guòdù yīlài fùmǔ", ko: "아이는 부모에게 지나치게 의존해선 안 돼요." },
        },
        {
          zh: "包容",
          pinyin: "bāoróng",
          ko: "포용하다, 너그러이 받아들이다",
          pos: "동사",
          hanja: "포용(包容) — 한자 그대로예요.",
          ex: { zh: "他是一个很包容的人。", pinyin: "tā shì yí ge hěn bāoróng de rén", ko: "그는 무척 포용력 있는 사람이에요." },
        },
        {
          zh: "妥协",
          pinyin: "tuǒxié",
          ko: "타협하다",
          pos: "동사",
          hanja: "타협(妥協) — 한자 그대로예요.",
          ex: { zh: "在原则问题上不能妥协。", pinyin: "zài yuánzé wèntí shàng bù néng tuǒxié", ko: "원칙 문제에서는 타협할 수 없어요." },
        },
        {
          zh: "衡量",
          pinyin: "héngliáng",
          ko: "가늠하다, 따지다",
          pos: "동사",
          hanja: "형량(衡量) — '저울로 달다'. 무게를 재듯 따지는 거예요.",
          ex: { zh: "我们要衡量利弊再做决定。", pinyin: "wǒmen yào héngliáng lìbì zài zuò juédìng", ko: "득실을 따져본 뒤 결정해야 해요." },
        },
        {
          zh: "贯彻",
          pinyin: "guànchè",
          ko: "관철하다, 철저히 실행하다",
          pos: "동사",
          hanja: "관철(貫徹) — 한자 그대로예요.",
          ex: { zh: "我们要把这个方针贯彻到底。", pinyin: "wǒmen yào bǎ zhège fāngzhēn guànchè dàodǐ", ko: "이 방침을 끝까지 관철해야 해요." },
        },
      ],
    },
    {
      name: "고급 형용사·부사",
      words: [
        {
          zh: "卓越",
          pinyin: "zhuóyuè",
          ko: "탁월하다",
          pos: "형용사",
          hanja: "탁월(卓越) — 한자 그대로예요.",
          ex: { zh: "她在科研方面有卓越的贡献。", pinyin: "tā zài kēyán fāngmiàn yǒu zhuóyuè de gòngxiàn", ko: "그녀는 연구 분야에서 탁월한 기여를 했어요." },
        },
        {
          zh: "微妙",
          pinyin: "wēimiào",
          ko: "미묘하다",
          pos: "형용사",
          hanja: "미묘(微妙) — 한자 그대로예요.",
          ex: { zh: "两人的关系很微妙。", pinyin: "liǎng rén de guānxì hěn wēimiào", ko: "두 사람의 관계는 미묘해요." },
        },
        {
          zh: "严峻",
          pinyin: "yánjùn",
          ko: "엄준하다, 험난하다",
          pos: "형용사",
          hanja: "엄준(嚴峻) — '엄하고 험하다'. 상황이 심각한 거예요.",
          ex: { zh: "我们面临着严峻的挑战。", pinyin: "wǒmen miànlín zhe yánjùn de tiǎozhàn", ko: "우리는 험난한 도전에 직면해 있어요." },
        },
        {
          zh: "崇高",
          pinyin: "chónggāo",
          ko: "숭고하다",
          pos: "형용사",
          hanja: "숭고(崇高) — 한자 그대로예요.",
          ex: { zh: "这是一种崇高的精神。", pinyin: "zhè shì yì zhǒng chónggāo de jīngshén", ko: "이것은 숭고한 정신이에요." },
        },
        {
          zh: "顽强",
          pinyin: "wánqiáng",
          ko: "완강하다, 굳세다",
          pos: "형용사",
          hanja: "완강(頑强) — 한자 그대로예요.",
          ex: { zh: "他以顽强的意志战胜了病魔。", pinyin: "tā yǐ wánqiáng de yìzhì zhànshèng le bìngmó", ko: "그는 굳센 의지로 병마를 이겨냈어요." },
        },
        {
          zh: "片面",
          pinyin: "piànmiàn",
          ko: "일면적이다, 단편적이다",
          pos: "형용사",
          hanja: "편면(片面) — '한쪽 면'. 치우친 시각이에요.",
          ex: { zh: "这种看法太片面了。", pinyin: "zhè zhǒng kànfǎ tài piànmiàn le", ko: "이런 견해는 너무 일면적이에요." },
        },
        {
          zh: "格外",
          pinyin: "géwài",
          ko: "유달리, 각별히",
          pos: "부사",
          hanja: "격외(格外) — '격을 벗어나', 곧 유달리예요.",
          ex: { zh: "今天她显得格外高兴。", pinyin: "jīntiān tā xiǎnde géwài gāoxìng", ko: "오늘 그녀는 유달리 기뻐 보여요." },
        },
        {
          zh: "依然",
          pinyin: "yīrán",
          ko: "여전히",
          pos: "부사",
          hanja: "의연(依然) — 한국어 '의연히'와 같아요. '여전히'예요.",
          ex: { zh: "多年过去，他依然记得那句话。", pinyin: "duōnián guòqù, tā yīrán jìde nà jù huà", ko: "여러 해가 지나도 그는 여전히 그 말을 기억해요." },
        },
        {
          zh: "势必",
          pinyin: "shìbì",
          ko: "필연적으로, 반드시",
          pos: "부사",
          hanja: "세필(勢必) — '형세상 반드시'. 그렇게 될 수밖에 없는 거예요.",
          ex: { zh: "这样下去势必会出问题。", pinyin: "zhèyàng xiàqù shìbì huì chū wèntí", ko: "이대로 가면 필연적으로 문제가 생길 거예요." },
        },
        {
          zh: "未免",
          pinyin: "wèimiǎn",
          ko: "아무래도 좀 ~한 감이 있다",
          pos: "부사",
          hanja: "미면(未免) — '면하지 못하다'. 지나친 감이 든다는 어감이에요.",
          ex: { zh: "你这样说未免太过分了。", pinyin: "nǐ zhèyàng shuō wèimiǎn tài guòfèn le", ko: "그렇게 말하는 건 아무래도 좀 지나쳐요." },
        },
      ],
    },
    {
      name: "사자성어",
      words: [
        {
          zh: "一举两得",
          pinyin: "yìjǔ-liǎngdé",
          ko: "일거양득, 일석이조",
          pos: "성어",
          hanja: "일거양득(一擧兩得) — 한국어 '일거양득'과 글자까지 똑같아요.",
          ex: { zh: "骑车上班既省钱又锻炼身体，真是一举两得。", pinyin: "qíchē shàngbān jì shěngqián yòu duànliàn shēntǐ, zhēnshì yìjǔ-liǎngdé", ko: "자전거 출근은 돈도 아끼고 운동도 되니 그야말로 일거양득이에요." },
        },
        {
          zh: "实事求是",
          pinyin: "shíshì-qiúshì",
          ko: "실사구시, 사실에 입각하다",
          pos: "성어",
          hanja: "실사구시(實事求是) — 한국어 '실사구시'와 같아요.",
          ex: { zh: "做研究要实事求是。", pinyin: "zuò yánjiū yào shíshì-qiúshì", ko: "연구는 사실에 입각해서 해야 해요." },
        },
        {
          zh: "全力以赴",
          pinyin: "quánlì-yǐfù",
          ko: "전력을 다하다",
          pos: "성어",
          hanja: "전력이부(全力以赴) — '온 힘으로 달려들다'. 최선을 다하는 거예요.",
          ex: { zh: "为了这个目标，他全力以赴。", pinyin: "wèile zhège mùbiāo, tā quánlì-yǐfù", ko: "이 목표를 위해 그는 전력을 다했어요." },
        },
        {
          zh: "理所当然",
          pinyin: "lǐsuǒdāngrán",
          ko: "당연하다, 너무도 마땅하다",
          pos: "성어",
          hanja: "이소당연(理所當然) — '이치상 마땅히 그러하다'. '당연하다'예요.",
          ex: { zh: "父母照顾孩子是理所当然的。", pinyin: "fùmǔ zhàogù háizi shì lǐsuǒdāngrán de", ko: "부모가 아이를 돌보는 건 너무도 당연한 일이에요." },
        },
        {
          zh: "全心全意",
          pinyin: "quánxīn-quányì",
          ko: "전심전력으로, 온 마음을 다해",
          pos: "성어",
          hanja: "전심전의(全心全意) — '온 마음과 온 뜻으로'. 진심을 다하는 거예요.",
          ex: { zh: "她全心全意地为大家服务。", pinyin: "tā quánxīn-quányì de wèi dàjiā fúwù", ko: "그녀는 온 마음을 다해 모두를 위해 봉사해요." },
        },
        {
          zh: "千方百计",
          pinyin: "qiānfāng-bǎijì",
          ko: "온갖 방법을 다 동원하다",
          pos: "성어",
          hanja: "천방백계(千方百計) — '천 가지 방법 백 가지 꾀'. 갖은 수를 쓰는 거예요.",
          ex: { zh: "他千方百计地想解决这个问题。", pinyin: "tā qiānfāng-bǎijì de xiǎng jiějué zhège wèntí", ko: "그는 온갖 방법을 다 써서 이 문제를 풀려 했어요." },
        },
        {
          zh: "名副其实",
          pinyin: "míngfùqíshí",
          ko: "명실상부하다",
          pos: "성어",
          hanja: "명부기실(名副其實) — '이름이 그 실질에 들어맞다'. 명실상부예요.",
          ex: { zh: "他是名副其实的专家。", pinyin: "tā shì míngfùqíshí de zhuānjiā", ko: "그는 명실상부한 전문가예요." },
        },
        {
          zh: "脚踏实地",
          pinyin: "jiǎotà-shídì",
          ko: "착실하다, 발을 땅에 딛다",
          pos: "성어",
          hanja: "각답실지(脚踏實地) — '발로 단단한 땅을 밟다'. 착실히 해 나가는 거예요.",
          ex: { zh: "成功需要脚踏实地的努力。", pinyin: "chénggōng xūyào jiǎotà-shídì de nǔlì", ko: "성공에는 착실한 노력이 필요해요." },
        },
        {
          zh: "举世闻名",
          pinyin: "jǔshì-wénmíng",
          ko: "온 세상에 이름이 알려지다",
          pos: "성어",
          hanja: "거세문명(擧世聞名) — '온 세상이 이름을 듣다'. 세계적으로 유명한 거예요.",
          ex: { zh: "长城是举世闻名的建筑。", pinyin: "chángchéng shì jǔshì-wénmíng de jiànzhù", ko: "만리장성은 세계적으로 유명한 건축물이에요." },
        },
        {
          zh: "迫不及待",
          pinyin: "pòbùjídài",
          ko: "한시도 못 기다리다, 안달하다",
          pos: "성어",
          hanja: "박불급대(迫不及待) — '급박해 기다릴 겨를이 없다'. 몹시 서두르는 거예요.",
          ex: { zh: "他迫不及待地打开了礼物。", pinyin: "tā pòbùjídài de dǎkāi le lǐwù", ko: "그는 한시도 못 기다리고 선물을 뜯었어요." },
        },
      ],
    },
  ],
};
