/**
 * 6급 어휘 — 고급 추상어와 성어의 세계
 * 격식 있는 글과 깊이 있는 토론을 위한 HSK6급 핵심어 · 사자성어.
 */
export default {
  level: "H6",
  title: "6급 어휘",
  desc: "고급 추상어·정치사회·심리, 그리고 사자성어까지 — 한국 한자음과 그대로 통하는 HSK6급 어휘예요.",
  themes: [
    {
      name: "고급 추상 명사",
      words: [
        {
          zh: "范畴",
          pinyin: "fànchóu",
          ko: "범주",
          pos: "명사",
          hanja: "범주(範疇) — 한자 그대로예요.",
          ex: { zh: "这个问题属于哲学的范畴。", pinyin: "zhège wèntí shǔyú zhéxué de fànchóu", ko: "이 문제는 철학의 범주에 속해요." },
        },
        {
          zh: "宗旨",
          pinyin: "zōngzhǐ",
          ko: "취지, 근본 목적",
          pos: "명사",
          hanja: "종지(宗旨) — '으뜸 되는 뜻'. '취지'로 외워요.",
          ex: { zh: "服务社会是这个组织的宗旨。", pinyin: "fúwù shèhuì shì zhège zǔzhī de zōngzhǐ", ko: "사회에 봉사하는 것이 이 단체의 취지예요." },
        },
        {
          zh: "前提",
          pinyin: "qiántí",
          ko: "전제",
          pos: "명사",
          hanja: "전제(前提) — 한자 그대로예요.",
          ex: { zh: "互相信任是合作的前提。", pinyin: "hùxiāng xìnrèn shì hézuò de qiántí", ko: "상호 신뢰가 협력의 전제예요." },
        },
        {
          zh: "本能",
          pinyin: "běnnéng",
          ko: "본능",
          pos: "명사",
          hanja: "본능(本能) — 한자 그대로예요.",
          ex: { zh: "求生是动物的本能。", pinyin: "qiúshēng shì dòngwù de běnnéng", ko: "살고자 하는 것은 동물의 본능이에요." },
        },
        {
          zh: "潜力",
          pinyin: "qiánlì",
          ko: "잠재력",
          pos: "명사",
          hanja: "잠력(潛力) — '潛(잠길 잠)+力(힘)'. '잠재력'이에요.",
          ex: { zh: "这个孩子很有潜力。", pinyin: "zhège háizi hěn yǒu qiánlì", ko: "이 아이는 잠재력이 커요." },
        },
        {
          zh: "舆论",
          pinyin: "yúlùn",
          ko: "여론",
          pos: "명사",
          hanja: "여론(輿論) — 한자 그대로예요.",
          ex: { zh: "这件事引起了社会舆论的关注。", pinyin: "zhè jiàn shì yǐnqǐ le shèhuì yúlùn de guānzhù", ko: "이 일은 사회 여론의 주목을 받았어요." },
        },
        {
          zh: "意识形态",
          pinyin: "yìshí xíngtài",
          ko: "이데올로기, 의식 형태",
          pos: "명사",
          hanja: "의식형태(意識形態) — 한자 그대로 '이데올로기'를 옮긴 말이에요.",
          ex: { zh: "不同的意识形态导致了冲突。", pinyin: "bùtóng de yìshí xíngtài dǎozhì le chōngtū", ko: "서로 다른 이데올로기가 갈등을 불러왔어요." },
        },
        {
          zh: "底线",
          pinyin: "dǐxiàn",
          ko: "마지노선, 최저선",
          pos: "명사",
          hanja: "저선(底線) — '밑바닥 선'. 양보할 수 없는 한계예요.",
          ex: { zh: "诚实是我做人的底线。", pinyin: "chéngshí shì wǒ zuòrén de dǐxiàn", ko: "정직함은 제 삶의 마지노선이에요." },
        },
        {
          zh: "格局",
          pinyin: "géjú",
          ko: "구도, 판세",
          pos: "명사",
          ex: { zh: "世界经济格局正在发生变化。", pinyin: "shìjiè jīngjì géjú zhèngzài fāshēng biànhuà", ko: "세계 경제의 판세가 변하고 있어요." },
        },
        {
          zh: "渊源",
          pinyin: "yuānyuán",
          ko: "연원, 근원",
          pos: "명사",
          hanja: "연원(淵源) — '깊은 못의 근원'. 일의 뿌리예요.",
          ex: { zh: "两国的文化渊源很深。", pinyin: "liǎng guó de wénhuà yuānyuán hěn shēn", ko: "두 나라의 문화적 연원은 깊어요." },
        },
      ],
    },
    {
      name: "정치와 사회",
      words: [
        {
          zh: "体制",
          pinyin: "tǐzhì",
          ko: "체제",
          pos: "명사",
          hanja: "체제(體制) — 한자 그대로예요.",
          ex: { zh: "经济体制改革取得了成果。", pinyin: "jīngjì tǐzhì gǎigé qǔdé le chéngguǒ", ko: "경제 체제 개혁이 성과를 거뒀어요." },
        },
        {
          zh: "改革",
          pinyin: "gǎigé",
          ko: "개혁",
          pos: "명사",
          hanja: "개혁(改革) — 한자 그대로예요.",
          ex: { zh: "政府推行了一系列改革。", pinyin: "zhèngfǔ tuīxíng le yíxìliè gǎigé", ko: "정부는 일련의 개혁을 추진했어요." },
        },
        {
          zh: "主权",
          pinyin: "zhǔquán",
          ko: "주권",
          pos: "명사",
          hanja: "주권(主權) — 한자 그대로예요.",
          ex: { zh: "国家主权不容侵犯。", pinyin: "guójiā zhǔquán bùróng qīnfàn", ko: "국가 주권은 침해될 수 없어요." },
        },
        {
          zh: "舆情",
          pinyin: "yúqíng",
          ko: "여론 동향, 민심",
          pos: "명사",
          hanja: "여정(輿情) — '여러 사람의 마음', 곧 민심이에요.",
          ex: { zh: "政府密切关注网络舆情。", pinyin: "zhèngfǔ mìqiè guānzhù wǎngluò yúqíng", ko: "정부는 인터넷 여론 동향을 면밀히 주시해요." },
        },
        {
          zh: "歧视",
          pinyin: "qíshì",
          ko: "차별, 차별하다",
          pos: "동사",
          hanja: "기시(歧視) — '다르게 보다', 곧 차별이에요.",
          ex: { zh: "我们应该反对一切歧视。", pinyin: "wǒmen yīnggāi fǎnduì yíqiè qíshì", ko: "우리는 모든 차별에 반대해야 해요." },
        },
        {
          zh: "福利",
          pinyin: "fúlì",
          ko: "복지",
          pos: "명사",
          hanja: "복리(福利) — 한국어 '복리·복지'와 같아요.",
          ex: { zh: "这家公司的福利很好。", pinyin: "zhè jiā gōngsī de fúlì hěn hǎo", ko: "이 회사는 복지가 좋아요." },
        },
        {
          zh: "腐败",
          pinyin: "fǔbài",
          ko: "부패하다, 타락하다",
          pos: "형용사",
          hanja: "부패(腐敗) — 한자 그대로예요.",
          ex: { zh: "反对腐败是长期的任务。", pinyin: "fǎnduì fǔbài shì chángqī de rènwù", ko: "부패에 맞서는 일은 장기적 과제예요." },
        },
        {
          zh: "贫困",
          pinyin: "pínkùn",
          ko: "빈곤하다",
          pos: "형용사",
          hanja: "빈곤(貧困) — 한자 그대로예요.",
          ex: { zh: "政府努力帮助贫困地区。", pinyin: "zhèngfǔ nǔlì bāngzhù pínkùn dìqū", ko: "정부는 빈곤 지역을 돕고자 애써요." },
        },
        {
          zh: "趋于",
          pinyin: "qūyú",
          ko: "~로 기울다, ~해지는 추세다",
          pos: "동사",
          hanja: "추어(趨於) — '~로 향하여 가다'. 어떤 방향으로 기우는 거예요.",
          ex: { zh: "局势逐渐趋于稳定。", pinyin: "júshì zhújiàn qūyú wěndìng", ko: "정세가 점차 안정되는 추세예요." },
        },
        {
          zh: "倡导",
          pinyin: "chàngdǎo",
          ko: "제창하다, 앞장서 주장하다",
          pos: "동사",
          hanja: "창도(倡導) — '앞장서 이끌다'. 주의·운동을 제창하는 거예요.",
          ex: { zh: "我们倡导绿色出行。", pinyin: "wǒmen chàngdǎo lǜsè chūxíng", ko: "우리는 친환경 이동을 제창해요." },
        },
      ],
    },
    {
      name: "심리·태도 동사",
      words: [
        {
          zh: "领悟",
          pinyin: "lǐngwù",
          ko: "깨닫다, 터득하다",
          pos: "동사",
          hanja: "영오(領悟) — '거느려 깨닫다'. 이치를 터득하는 거예요.",
          ex: { zh: "他终于领悟了其中的道理。", pinyin: "tā zhōngyú lǐngwù le qízhōng de dàoli", ko: "그는 마침내 그 안의 이치를 깨달았어요." },
        },
        {
          zh: "陶醉",
          pinyin: "táozuì",
          ko: "도취하다, 심취하다",
          pos: "동사",
          hanja: "도취(陶醉) — 한자 그대로예요.",
          ex: { zh: "他陶醉在音乐里。", pinyin: "tā táozuì zài yīnyuè lǐ", ko: "그는 음악에 도취해 있어요." },
        },
        {
          zh: "畏惧",
          pinyin: "wèijù",
          ko: "두려워하다, 위축되다",
          pos: "동사",
          hanja: "외구(畏懼) — '畏(두려울 외)+懼(두려울 구)'. 두려워하는 거예요.",
          ex: { zh: "他面对困难毫不畏惧。", pinyin: "tā miànduì kùnnan háobù wèijù", ko: "그는 어려움 앞에서 조금도 두려워하지 않아요." },
        },
        {
          zh: "厌倦",
          pinyin: "yànjuàn",
          ko: "싫증나다, 권태를 느끼다",
          pos: "동사",
          hanja: "염권(厭倦) — '厭(싫을 염)+倦(게으를 권)'. 물려서 지치는 거예요.",
          ex: { zh: "他渐渐厌倦了这种生活。", pinyin: "tā jiànjiàn yànjuàn le zhè zhǒng shēnghuó", ko: "그는 점점 이런 생활에 싫증이 났어요." },
        },
        {
          zh: "执着",
          pinyin: "zhízhuó",
          ko: "집착하다, 끈질기다",
          pos: "형용사",
          hanja: "집착(執着) — 한자 그대로지만 '끈기 있다'는 긍정적 뜻으로도 써요.",
          ex: { zh: "他对梦想很执着。", pinyin: "tā duì mèngxiǎng hěn zhízhuó", ko: "그는 꿈을 향해 끈질겨요." },
        },
        {
          zh: "依赖",
          pinyin: "yīlài",
          ko: "의존하다, 기대다",
          pos: "동사",
          hanja: "의뢰(依賴) — 한국어 '의뢰'와 달리 '의존하다'는 뜻이에요.",
          ex: { zh: "孩子不应该过度依赖父母。", pinyin: "háizi bù yīnggāi guòdù yīlài fùmǔ", ko: "아이는 부모에게 지나치게 의존해선 안 돼요." },
        },
        {
          zh: "包容",
          pinyin: "bāoróng",
          ko: "포용하다, 너그러이 받아들이다",
          pos: "동사",
          hanja: "포용(包容) — 한자 그대로예요.",
          ex: { zh: "他是一个很包容的人。", pinyin: "tā shì yí ge hěn bāoróng de rén", ko: "그는 무척 포용력 있는 사람이에요." },
        },
        {
          zh: "妥协",
          pinyin: "tuǒxié",
          ko: "타협하다",
          pos: "동사",
          hanja: "타협(妥協) — 한자 그대로예요.",
          ex: { zh: "在原则问题上不能妥协。", pinyin: "zài yuánzé wèntí shàng bù néng tuǒxié", ko: "원칙 문제에서는 타협할 수 없어요." },
        },
        {
          zh: "衡量",
          pinyin: "héngliáng",
          ko: "가늠하다, 따지다",
          pos: "동사",
          hanja: "형량(衡量) — '저울로 달다'. 무게를 재듯 따지는 거예요.",
          ex: { zh: "我们要衡量利弊再做决定。", pinyin: "wǒmen yào héngliáng lìbì zài zuò juédìng", ko: "득실을 따져본 뒤 결정해야 해요." },
        },
        {
          zh: "贯彻",
          pinyin: "guànchè",
          ko: "관철하다, 철저히 실행하다",
          pos: "동사",
          hanja: "관철(貫徹) — 한자 그대로예요.",
          ex: { zh: "我们要把这个方针贯彻到底。", pinyin: "wǒmen yào bǎ zhège fāngzhēn guànchè dàodǐ", ko: "이 방침을 끝까지 관철해야 해요." },
        },
      ],
    },
    {
      name: "고급 형용사·부사",
      words: [
        {
          zh: "卓越",
          pinyin: "zhuóyuè",
          ko: "탁월하다",
          pos: "형용사",
          hanja: "탁월(卓越) — 한자 그대로예요.",
          ex: { zh: "她在科研方面有卓越的贡献。", pinyin: "tā zài kēyán fāngmiàn yǒu zhuóyuè de gòngxiàn", ko: "그녀는 연구 분야에서 탁월한 기여를 했어요." },
        },
        {
          zh: "微妙",
          pinyin: "wēimiào",
          ko: "미묘하다",
          pos: "형용사",
          hanja: "미묘(微妙) — 한자 그대로예요.",
          ex: { zh: "两人的关系很微妙。", pinyin: "liǎng rén de guānxì hěn wēimiào", ko: "두 사람의 관계는 미묘해요." },
        },
        {
          zh: "严峻",
          pinyin: "yánjùn",
          ko: "엄준하다, 험난하다",
          pos: "형용사",
          hanja: "엄준(嚴峻) — '엄하고 험하다'. 상황이 심각한 거예요.",
          ex: { zh: "我们面临着严峻的挑战。", pinyin: "wǒmen miànlín zhe yánjùn de tiǎozhàn", ko: "우리는 험난한 도전에 직면해 있어요." },
        },
        {
          zh: "崇高",
          pinyin: "chónggāo",
          ko: "숭고하다",
          pos: "형용사",
          hanja: "숭고(崇高) — 한자 그대로예요.",
          ex: { zh: "这是一种崇高的精神。", pinyin: "zhè shì yì zhǒng chónggāo de jīngshén", ko: "이것은 숭고한 정신이에요." },
        },
        {
          zh: "顽强",
          pinyin: "wánqiáng",
          ko: "완강하다, 굳세다",
          pos: "형용사",
          hanja: "완강(頑强) — 한자 그대로예요.",
          ex: { zh: "他以顽强的意志战胜了病魔。", pinyin: "tā yǐ wánqiáng de yìzhì zhànshèng le bìngmó", ko: "그는 굳센 의지로 병마를 이겨냈어요." },
        },
        {
          zh: "片面",
          pinyin: "piànmiàn",
          ko: "일면적이다, 단편적이다",
          pos: "형용사",
          hanja: "편면(片面) — '한쪽 면'. 치우친 시각이에요.",
          ex: { zh: "这种看法太片面了。", pinyin: "zhè zhǒng kànfǎ tài piànmiàn le", ko: "이런 견해는 너무 일면적이에요." },
        },
        {
          zh: "格外",
          pinyin: "géwài",
          ko: "유달리, 각별히",
          pos: "부사",
          hanja: "격외(格外) — '격을 벗어나', 곧 유달리예요.",
          ex: { zh: "今天她显得格外高兴。", pinyin: "jīntiān tā xiǎnde géwài gāoxìng", ko: "오늘 그녀는 유달리 기뻐 보여요." },
        },
        {
          zh: "依然",
          pinyin: "yīrán",
          ko: "여전히",
          pos: "부사",
          hanja: "의연(依然) — 한국어 '의연히'와 같아요. '여전히'예요.",
          ex: { zh: "多年过去，他依然记得那句话。", pinyin: "duōnián guòqù, tā yīrán jìde nà jù huà", ko: "여러 해가 지나도 그는 여전히 그 말을 기억해요." },
        },
        {
          zh: "势必",
          pinyin: "shìbì",
          ko: "필연적으로, 반드시",
          pos: "부사",
          hanja: "세필(勢必) — '형세상 반드시'. 그렇게 될 수밖에 없는 거예요.",
          ex: { zh: "这样下去势必会出问题。", pinyin: "zhèyàng xiàqù shìbì huì chū wèntí", ko: "이대로 가면 필연적으로 문제가 생길 거예요." },
        },
        {
          zh: "未免",
          pinyin: "wèimiǎn",
          ko: "아무래도 좀 ~한 감이 있다",
          pos: "부사",
          hanja: "미면(未免) — '면하지 못하다'. 지나친 감이 든다는 어감이에요.",
          ex: { zh: "你这样说未免太过分了。", pinyin: "nǐ zhèyàng shuō wèimiǎn tài guòfèn le", ko: "그렇게 말하는 건 아무래도 좀 지나쳐요." },
        },
      ],
    },
    {
      name: "사자성어",
      words: [
        {
          zh: "一举两得",
          pinyin: "yìjǔ-liǎngdé",
          ko: "일거양득, 일석이조",
          pos: "성어",
          hanja: "일거양득(一擧兩得) — 한국어 '일거양득'과 글자까지 똑같아요.",
          ex: { zh: "骑车上班既省钱又锻炼身体，真是一举两得。", pinyin: "qíchē shàngbān jì shěngqián yòu duànliàn shēntǐ, zhēnshì yìjǔ-liǎngdé", ko: "자전거 출근은 돈도 아끼고 운동도 되니 그야말로 일거양득이에요." },
        },
        {
          zh: "实事求是",
          pinyin: "shíshì-qiúshì",
          ko: "실사구시, 사실에 입각하다",
          pos: "성어",
          hanja: "실사구시(實事求是) — 한국어 '실사구시'와 같아요.",
          ex: { zh: "做研究要实事求是。", pinyin: "zuò yánjiū yào shíshì-qiúshì", ko: "연구는 사실에 입각해서 해야 해요." },
        },
        {
          zh: "全力以赴",
          pinyin: "quánlì-yǐfù",
          ko: "전력을 다하다",
          pos: "성어",
          hanja: "전력이부(全力以赴) — '온 힘으로 달려들다'. 최선을 다하는 거예요.",
          ex: { zh: "为了这个目标，他全力以赴。", pinyin: "wèile zhège mùbiāo, tā quánlì-yǐfù", ko: "이 목표를 위해 그는 전력을 다했어요." },
        },
        {
          zh: "理所当然",
          pinyin: "lǐsuǒdāngrán",
          ko: "당연하다, 너무도 마땅하다",
          pos: "성어",
          hanja: "이소당연(理所當然) — '이치상 마땅히 그러하다'. '당연하다'예요.",
          ex: { zh: "父母照顾孩子是理所当然的。", pinyin: "fùmǔ zhàogù háizi shì lǐsuǒdāngrán de", ko: "부모가 아이를 돌보는 건 너무도 당연한 일이에요." },
        },
        {
          zh: "全心全意",
          pinyin: "quánxīn-quányì",
          ko: "전심전력으로, 온 마음을 다해",
          pos: "성어",
          hanja: "전심전의(全心全意) — '온 마음과 온 뜻으로'. 진심을 다하는 거예요.",
          ex: { zh: "她全心全意地为大家服务。", pinyin: "tā quánxīn-quányì de wèi dàjiā fúwù", ko: "그녀는 온 마음을 다해 모두를 위해 봉사해요." },
        },
        {
          zh: "千方百计",
          pinyin: "qiānfāng-bǎijì",
          ko: "온갖 방법을 다 동원하다",
          pos: "성어",
          hanja: "천방백계(千方百計) — '천 가지 방법 백 가지 꾀'. 갖은 수를 쓰는 거예요.",
          ex: { zh: "他千方百计地想解决这个问题。", pinyin: "tā qiānfāng-bǎijì de xiǎng jiějué zhège wèntí", ko: "그는 온갖 방법을 다 써서 이 문제를 풀려 했어요." },
        },
        {
          zh: "名副其实",
          pinyin: "míngfùqíshí",
          ko: "명실상부하다",
          pos: "성어",
          hanja: "명부기실(名副其實) — '이름이 그 실질에 들어맞다'. 명실상부예요.",
          ex: { zh: "他是名副其实的专家。", pinyin: "tā shì míngfùqíshí de zhuānjiā", ko: "그는 명실상부한 전문가예요." },
        },
        {
          zh: "脚踏实地",
          pinyin: "jiǎotà-shídì",
          ko: "착실하다, 발을 땅에 딛다",
          pos: "성어",
          hanja: "각답실지(脚踏實地) — '발로 단단한 땅을 밟다'. 착실히 해 나가는 거예요.",
          ex: { zh: "成功需要脚踏实地的努力。", pinyin: "chénggōng xūyào jiǎotà-shídì de nǔlì", ko: "성공에는 착실한 노력이 필요해요." },
        },
        {
          zh: "举世闻名",
          pinyin: "jǔshì-wénmíng",
          ko: "온 세상에 이름이 알려지다",
          pos: "성어",
          hanja: "거세문명(擧世聞名) — '온 세상이 이름을 듣다'. 세계적으로 유명한 거예요.",
          ex: { zh: "长城是举世闻名的建筑。", pinyin: "chángchéng shì jǔshì-wénmíng de jiànzhù", ko: "만리장성은 세계적으로 유명한 건축물이에요." },
        },
        {
          zh: "迫不及待",
          pinyin: "pòbùjídài",
          ko: "한시도 못 기다리다, 안달하다",
          pos: "성어",
          hanja: "박불급대(迫不及待) — '급박해 기다릴 겨를이 없다'. 몹시 서두르는 거예요.",
          ex: { zh: "他迫不及待地打开了礼物。", pinyin: "tā pòbùjídài de dǎkāi le lǐwù", ko: "그는 한시도 못 기다리고 선물을 뜯었어요." },
        },
      ],
    },
    {
      name: "학술·논리 표현",
      words: [
        {
          zh: "归纳",
          pinyin: "guīnà",
          ko: "귀납하다, 간추리다",
          pos: "동사",
          hanja: "귀납(歸納) — 한자 그대로예요.",
          ex: { zh: "请把这些观点归纳一下。", pinyin: "qǐng bǎ zhèxiē guāndiǎn guīnà yíxià", ko: "이 견해들을 좀 간추려 주세요." },
        },
        {
          zh: "阐述",
          pinyin: "chǎnshù",
          ko: "상세히 논술하다",
          pos: "동사",
          hanja: "천술(闡述) — '밝혀 서술하다'. 자세히 설명하는 거예요.",
          ex: { zh: "他详细阐述了自己的观点。", pinyin: "tā xiángxì chǎnshù le zìjǐ de guāndiǎn", ko: "그는 자신의 관점을 자세히 논술했어요." },
        },
        {
          zh: "论证",
          pinyin: "lùnzhèng",
          ko: "논증하다",
          pos: "동사",
          hanja: "논증(論證) — 한자 그대로예요.",
          ex: { zh: "这篇文章论证得很严密。", pinyin: "zhè piān wénzhāng lùnzhèng de hěn yánmì", ko: "이 글은 논증이 매우 치밀해요." },
        },
        {
          zh: "依据",
          pinyin: "yījù",
          ko: "근거, 근거로 하다",
          pos: "명사",
          hanja: "의거(依據) — '의거하다'의 그 의거예요. '근거'로 외워요.",
          ex: { zh: "你这样说有什么依据？", pinyin: "nǐ zhèyàng shuō yǒu shénme yījù", ko: "그렇게 말하는 근거가 뭐예요?" },
        },
        {
          zh: "侧重",
          pinyin: "cèzhòng",
          ko: "치중하다, 무게를 두다",
          pos: "동사",
          hanja: "측중(側重) — '한쪽에 무게를 싣다'. 어느 쪽을 더 중시하는 거예요.",
          ex: { zh: "这门课侧重于实践。", pinyin: "zhè mén kè cèzhòng yú shíjiàn", ko: "이 수업은 실천에 치중해요." },
        },
        {
          zh: "鉴于",
          pinyin: "jiànyú",
          ko: "~을 고려하여, ~에 비추어",
          pos: "개사",
          hanja: "감어(鑒於) — '거울에 비추어 보아'. ~을 감안하여라는 격식 표현이에요.",
          ex: { zh: "鉴于天气原因，活动延期了。", pinyin: "jiànyú tiānqì yuányīn, huódòng yánqī le", ko: "날씨 사정을 고려해 행사가 연기됐어요." },
        },
        {
          zh: "凭借",
          pinyin: "píngjiè",
          ko: "~에 의지하여, ~을 발판으로",
          pos: "개사",
          hanja: "빙차(憑藉) — '기대어 빌리다'. ~에 의존해 무언가를 이루는 거예요.",
          ex: { zh: "他凭借努力取得了成功。", pinyin: "tā píngjiè nǔlì qǔdé le chénggōng", ko: "그는 노력에 힘입어 성공을 거뒀어요." },
        },
        {
          zh: "综合",
          pinyin: "zōnghé",
          ko: "종합하다, 종합적인",
          pos: "동사",
          hanja: "종합(綜合) — 한자 그대로예요.",
          ex: { zh: "综合各方面来看，这个方案最好。", pinyin: "zōnghé gè fāngmiàn lái kàn, zhège fāng'àn zuì hǎo", ko: "여러 면을 종합해 보면 이 방안이 가장 좋아요." },
        },
        {
          zh: "界定",
          pinyin: "jièdìng",
          ko: "한계를 정하다, 규정하다",
          pos: "동사",
          hanja: "계정(界定) — '경계를 정하다'. 범위를 명확히 규정하는 거예요.",
          ex: { zh: "这个概念很难界定。", pinyin: "zhège gàiniàn hěn nán jièdìng", ko: "이 개념은 규정하기가 어려워요." },
        },
        {
          zh: "诠释",
          pinyin: "quánshì",
          ko: "해석하다, 풀이하다",
          pos: "동사",
          hanja: "전석(詮釋) — '갖춰 풀이하다'. 의미를 해석해 보여주는 거예요.",
          ex: { zh: "她用行动诠释了什么是责任。", pinyin: "tā yòng xíngdòng quánshì le shénme shì zérèn", ko: "그녀는 행동으로 책임이 무엇인지 보여줬어요." },
        },
      ],
    },
    {
      name: "교재 보충 어휘",
      words: [
        {
          zh: "机会",
          pinyin: "jīhuì",
          ko: "기회",
          pos: "명사",
          hanja: "기회(機會) — 한자 그대로예요.",
          ex: { zh: "光等机会不努力，简直是守株待兔。", pinyin: "guāng děng jīhuì bù nǔlì, jiǎnzhí shì shǒuzhū-dàitù", ko: "기회만 기다리고 노력 안 하는 건 그야말로 요행 바라기예요." },
        },
        {
          zh: "补救",
          pinyin: "bǔjiù",
          ko: "바로잡다, 만회하다",
          pos: "동사",
          hanja: "보구(補救) — '모자란 것을 메워 구하다'. 잘못을 만회하는 거예요.",
          ex: { zh: "现在补救还不晚，亡羊补牢嘛。", pinyin: "xiànzài bǔjiù hái bù wǎn, wángyáng-bǔláo ma", ko: "지금 바로잡아도 늦지 않아요, 소 잃고 외양간 고치기죠." },
        },
        {
          zh: "失业",
          pinyin: "shīyè",
          ko: "실업, 실직하다",
          pos: "동사",
          hanja: "실업(失業) — '직업(業)을 잃다(失)'예요.",
          ex: { zh: "失业未必是坏事，塞翁失马，焉知非福。", pinyin: "shīyè wèibì shì huàishì, sàiwēng-shīmǎ, yānzhī-fēifú", ko: "실직이 꼭 나쁜 일은 아니에요, 새옹지마, 화가 복이 될지 누가 알겠어요." },
        },
        {
          zh: "坏事",
          pinyin: "huàishì",
          ko: "나쁜 일, 궂은일",
          pos: "명사",
          hanja: "괴사(壞事) — '나쁜(壞) 일(事)'이에요.",
          ex: { zh: "失业未必是坏事，塞翁失马，焉知非福。", pinyin: "shīyè wèibì shì huàishì, sàiwēng-shīmǎ, yānzhī-fēifú", ko: "실직이 꼭 나쁜 일은 아니에요, 새옹지마, 화가 복이 될지 누가 알겠어요." },
        },
        {
          zh: "文章",
          pinyin: "wénzhāng",
          ko: "글, 문장",
          pos: "명사",
          hanja: "문장(文章) — 한자 그대로예요. 한 편의 '글'을 가리켜요.",
          ex: { zh: "这篇文章华而不实。", pinyin: "zhè piān wénzhāng huá ér bù shí", ko: "이 글은 화려하지만 알맹이가 없어요." },
        },
        {
          zh: "遇到",
          pinyin: "yùdào",
          ko: "마주치다, 부딪치다",
          pos: "동사",
          hanja: "우도(遇到) — '만나게(遇) 되다'예요.",
          ex: { zh: "他遇到困难而毫不退缩。", pinyin: "tā yùdào kùnnan ér háobù tuìsuō", ko: "그는 어려움을 만나도 조금도 물러서지 않아요." },
        },
        {
          zh: "退缩",
          pinyin: "tuìsuō",
          ko: "위축되다, 움츠러들다",
          pos: "동사",
          hanja: "퇴축(退縮) — '물러나 움츠리다'예요.",
          ex: { zh: "他遇到困难而毫不退缩。", pinyin: "tā yùdào kùnnan ér háobù tuìsuō", ko: "그는 어려움을 만나도 조금도 물러서지 않아요." },
        },
        {
          zh: "勤奋",
          pinyin: "qínfèn",
          ko: "부지런하다, 근면하다",
          pos: "형용사",
          hanja: "근분(勤奮) — '부지런히(勤) 힘쓰다(奮)'예요.",
          ex: { zh: "他不仅聪明，而且勤奋。", pinyin: "tā bùjǐn cōngming, érqiě qínfèn", ko: "그는 똑똑할 뿐 아니라 부지런하기까지 해요." },
        },
        {
          zh: "抱怨",
          pinyin: "bàoyuàn",
          ko: "원망하다, 불평하다",
          pos: "동사",
          hanja: "포원(抱怨) — '원망(怨)을 품다(抱)'예요.",
          ex: { zh: "与其抱怨，不如行动。", pinyin: "yǔqí bàoyuàn, bùrú xíngdòng", ko: "불평하느니 차라리 행동하는 게 나아요." },
        },
        {
          zh: "行动",
          pinyin: "xíngdòng",
          ko: "행동, 행동하다",
          pos: "동사",
          hanja: "행동(行動) — 한자 그대로예요.",
          ex: { zh: "与其抱怨，不如行动。", pinyin: "yǔqí bàoyuàn, bùrú xíngdòng", ko: "불평하느니 차라리 행동하는 게 나아요." },
        },
        {
          zh: "笑容",
          pinyin: "xiàoróng",
          ko: "웃는 얼굴, 미소",
          pos: "명사",
          hanja: "소용(笑容) — '웃는(笑) 모습(容)'이에요.",
          ex: { zh: "她的笑容像阳光一样温暖。", pinyin: "tā de xiàoróng xiàng yángguāng yíyàng wēnnuǎn", ko: "그녀의 미소는 햇살처럼 따뜻해요." },
        },
        {
          zh: "阳光",
          pinyin: "yángguāng",
          ko: "햇빛, 햇살",
          pos: "명사",
          hanja: "양광(陽光) — '볕(陽) 빛(光)', 곧 햇살이에요.",
          ex: { zh: "她的笑容像阳光一样温暖。", pinyin: "tā de xiàoróng xiàng yángguāng yíyàng wēnnuǎn", ko: "그녀의 미소는 햇살처럼 따뜻해요." },
        },
        {
          zh: "温暖",
          pinyin: "wēnnuǎn",
          ko: "따뜻하다",
          pos: "형용사",
          hanja: "온난(溫暖) — 한자 그대로예요.",
          ex: { zh: "她的笑容像阳光一样温暖。", pinyin: "tā de xiàoróng xiàng yángguāng yíyàng wēnnuǎn", ko: "그녀의 미소는 햇살처럼 따뜻해요." },
        },
        {
          zh: "书籍",
          pinyin: "shūjí",
          ko: "서적, 책",
          pos: "명사",
          hanja: "서적(書籍) — 한자 그대로예요.",
          ex: { zh: "书籍是人类进步的阶梯。", pinyin: "shūjí shì rénlèi jìnbù de jiētī", ko: "책은 인류 진보의 사다리예요." },
        },
        {
          zh: "人类",
          pinyin: "rénlèi",
          ko: "인류",
          pos: "명사",
          hanja: "인류(人類) — 한자 그대로예요.",
          ex: { zh: "书籍是人类进步的阶梯。", pinyin: "shūjí shì rénlèi jìnbù de jiētī", ko: "책은 인류 진보의 사다리예요." },
        },
        {
          zh: "进步",
          pinyin: "jìnbù",
          ko: "진보, 향상되다",
          pos: "동사",
          hanja: "진보(進步) — 한자 그대로예요.",
          ex: { zh: "虚心使人进步，骄傲使人落后。", pinyin: "xūxīn shǐ rén jìnbù, jiāo'ào shǐ rén luòhòu", ko: "겸손은 사람을 발전시키고, 교만은 사람을 뒤처지게 해요." },
        },
        {
          zh: "落后",
          pinyin: "luòhòu",
          ko: "뒤떨어지다, 낙후되다",
          pos: "동사",
          hanja: "낙후(落後) — '뒤(後)로 처지다(落)'예요.",
          ex: { zh: "虚心使人进步，骄傲使人落后。", pinyin: "xūxīn shǐ rén jìnbù, jiāo'ào shǐ rén luòhòu", ko: "겸손은 사람을 발전시키고, 교만은 사람을 뒤처지게 해요." },
        },
        {
          zh: "知己",
          pinyin: "zhījǐ",
          ko: "지기, 마음을 알아주는 벗",
          pos: "명사",
          hanja: "지기(知己) — '나(己)를 알아주는(知)' 벗이에요.",
          ex: { zh: "海内存知己，天涯若比邻。", pinyin: "hǎinèi cún zhījǐ, tiānyá ruò bǐlín", ko: "세상에 나를 알아주는 벗이 있으면, 하늘 끝도 이웃 같아요." },
        },
        {
          zh: "勇气",
          pinyin: "yǒngqì",
          ko: "용기",
          pos: "명사",
          hanja: "용기(勇氣) — 한자 그대로예요.",
          ex: { zh: "我们需要勇气，需要智慧，需要坚持。", pinyin: "wǒmen xūyào yǒngqì, xūyào zhìhuì, xūyào jiānchí", ko: "우리에겐 용기가, 지혜가, 끈기가 필요해요." },
        },
        {
          zh: "智慧",
          pinyin: "zhìhuì",
          ko: "지혜",
          pos: "명사",
          hanja: "지혜(智慧) — 한자 그대로예요.",
          ex: { zh: "我们需要勇气，需要智慧，需要坚持。", pinyin: "wǒmen xūyào yǒngqì, xūyào zhìhuì, xūyào jiānchí", ko: "우리에겐 용기가, 지혜가, 끈기가 필요해요." },
        },
        {
          zh: "读书",
          pinyin: "dúshū",
          ko: "독서하다, 책을 읽다",
          pos: "동사",
          hanja: "독서(讀書) — 한자 그대로예요.",
          ex: { zh: "读书使人充实，思考使人深刻，交流使人清醒。", pinyin: "dúshū shǐ rén chōngshí, sīkǎo shǐ rén shēnkè, jiāoliú shǐ rén qīngxǐng", ko: "독서는 충실하게, 사고는 깊이 있게, 교류는 또렷하게 만들어요." },
        },
        {
          zh: "充实",
          pinyin: "chōngshí",
          ko: "충실하다, 알차다",
          pos: "형용사",
          hanja: "충실(充實) — 한자 그대로예요.",
          ex: { zh: "读书使人充实，思考使人深刻，交流使人清醒。", pinyin: "dúshū shǐ rén chōngshí, sīkǎo shǐ rén shēnkè, jiāoliú shǐ rén qīngxǐng", ko: "독서는 충실하게, 사고는 깊이 있게, 교류는 또렷하게 만들어요." },
        },
        {
          zh: "思考",
          pinyin: "sīkǎo",
          ko: "사고하다, 깊이 생각하다",
          pos: "동사",
          hanja: "사고(思考) — 한자 그대로예요.",
          ex: { zh: "读书使人充实，思考使人深刻，交流使人清醒。", pinyin: "dúshū shǐ rén chōngshí, sīkǎo shǐ rén shēnkè, jiāoliú shǐ rén qīngxǐng", ko: "독서는 충실하게, 사고는 깊이 있게, 교류는 또렷하게 만들어요." },
        },
        {
          zh: "深刻",
          pinyin: "shēnkè",
          ko: "깊다, 깊이 있다",
          pos: "형용사",
          hanja: "심각(深刻) — 한국어 '심각'과 달리 '깊이 있다'는 뜻으로 자주 써요.",
          ex: { zh: "读书使人充实，思考使人深刻，交流使人清醒。", pinyin: "dúshū shǐ rén chōngshí, sīkǎo shǐ rén shēnkè, jiāoliú shǐ rén qīngxǐng", ko: "독서는 충실하게, 사고는 깊이 있게, 교류는 또렷하게 만들어요." },
        },
        {
          zh: "交流",
          pinyin: "jiāoliú",
          ko: "교류하다, 소통하다",
          pos: "동사",
          hanja: "교류(交流) — 한자 그대로예요.",
          ex: { zh: "读书使人充实，思考使人深刻，交流使人清醒。", pinyin: "dúshū shǐ rén chōngshí, sīkǎo shǐ rén shēnkè, jiāoliú shǐ rén qīngxǐng", ko: "독서는 충실하게, 사고는 깊이 있게, 교류는 또렷하게 만들어요." },
        },
        {
          zh: "清醒",
          pinyin: "qīngxǐng",
          ko: "또렷하다, 정신이 맑다",
          pos: "형용사",
          hanja: "청성(淸醒) — '맑게 깨어 있다'. 정신이 또렷한 거예요.",
          ex: { zh: "读书使人充实，思考使人深刻，交流使人清醒。", pinyin: "dúshū shǐ rén chōngshí, sīkǎo shǐ rén shēnkè, jiāoliú shǐ rén qīngxǐng", ko: "독서는 충실하게, 사고는 깊이 있게, 교류는 또렷하게 만들어요." },
        },
        {
          zh: "患者",
          pinyin: "huànzhě",
          ko: "환자",
          pos: "명사",
          hanja: "환자(患者) — 한자 그대로예요.",
          ex: { zh: "经检查，患者头部并无损伤。", pinyin: "jīng jiǎnchá, huànzhě tóubù bìng wú sǔnshāng", ko: "검사 결과, 환자의 머리에는 손상이 없었어요." },
        },
        {
          zh: "头部",
          pinyin: "tóubù",
          ko: "머리, 두부",
          pos: "명사",
          hanja: "두부(頭部) — '머리(頭) 부위(部)'. 脑袋의 글말 표현이에요.",
          ex: { zh: "经检查，患者头部并无损伤。", pinyin: "jīng jiǎnchá, huànzhě tóubù bìng wú sǔnshāng", ko: "검사 결과, 환자의 머리에는 손상이 없었어요." },
        },
        {
          zh: "损伤",
          pinyin: "sǔnshāng",
          ko: "손상, 다치다",
          pos: "명사",
          hanja: "손상(損傷) — 한자 그대로예요.",
          ex: { zh: "经检查，患者头部并无损伤。", pinyin: "jīng jiǎnchá, huànzhě tóubù bìng wú sǔnshāng", ko: "검사 결과, 환자의 머리에는 손상이 없었어요." },
        },
        {
          zh: "脑袋",
          pinyin: "nǎodai",
          ko: "머리 (구어)",
          pos: "명사",
          hanja: "뇌대(腦袋) — '머리'의 구어 표현이에요. 头部의 회화형이에요.",
          ex: { zh: "你脑袋撞到哪儿了？", pinyin: "nǐ nǎodai zhuàngdào nǎr le", ko: "너 머리 어디 부딪쳤어?" },
        },
        {
          zh: "上述",
          pinyin: "shàngshù",
          ko: "위에서 말한, 상술한",
          pos: "형용사",
          hanja: "상술(上述) — '위(上)에서 서술한(述)'. 앞서 언급한 것을 가리켜요.",
          ex: { zh: "鉴于上述原因，本方案予以驳回。", pinyin: "jiànyú shàngshù yuányīn, běn fāng'àn yǔyǐ bóhuí", ko: "위 사유에 비추어, 본 방안을 기각합니다." },
        },
        {
          zh: "驳回",
          pinyin: "bóhuí",
          ko: "기각하다, 물리치다",
          pos: "동사",
          hanja: "박회(駁回) — '반박하여 돌려보내다'. 받아들이지 않고 물리치는 거예요.",
          ex: { zh: "鉴于上述原因，本方案予以驳回。", pinyin: "jiànyú shàngshù yuányīn, běn fāng'àn yǔyǐ bóhuí", ko: "위 사유에 비추어, 본 방안을 기각합니다." },
        },
        {
          zh: "形势",
          pinyin: "xíngshì",
          ko: "형세, 정세",
          pos: "명사",
          hanja: "형세(形勢) — 한자 그대로예요.",
          ex: { zh: "鉴于目前的经济形势，公司决定暂缓招聘。", pinyin: "jiànyú mùqián de jīngjì xíngshì, gōngsī juédìng zànhuǎn zhāopìn", ko: "현재의 경제 상황을 고려하여, 회사는 채용을 잠시 미루기로 했어요." },
        },
        {
          zh: "贡献",
          pinyin: "gòngxiàn",
          ko: "공헌, 기여하다",
          pos: "동사",
          hanja: "공헌(貢獻) — 한자 그대로예요.",
          ex: { zh: "鉴于他的突出贡献，特授予此奖。", pinyin: "jiànyú tā de tūchū gòngxiàn, tè shòuyǔ cǐ jiǎng", ko: "그의 두드러진 공헌을 감안하여, 특별히 이 상을 수여합니다." },
        },
        {
          zh: "条件",
          pinyin: "tiáojiàn",
          ko: "조건",
          pos: "명사",
          hanja: "조건(條件) — 한자 그대로예요.",
          ex: { zh: "即便条件再艰苦，他也从未放弃。", pinyin: "jíbiàn tiáojiàn zài jiānkǔ, tā yě cóngwèi fàngqì", ko: "설령 조건이 아무리 힘들어도, 그는 결코 포기하지 않았어요." },
        },
        {
          zh: "艰苦",
          pinyin: "jiānkǔ",
          ko: "고되다, 어렵고 힘들다",
          pos: "형용사",
          hanja: "간고(艱苦) — '어렵고(艱) 괴롭다(苦)'예요.",
          ex: { zh: "即便条件再艰苦，他也从未放弃。", pinyin: "jíbiàn tiáojiàn zài jiānkǔ, tā yě cóngwèi fàngqì", ko: "설령 조건이 아무리 힘들어도, 그는 결코 포기하지 않았어요." },
        },
        {
          zh: "争取",
          pinyin: "zhēngqǔ",
          ko: "쟁취하다, 얻으려 애쓰다",
          pos: "동사",
          hanja: "쟁취(爭取) — '다투어(爭) 얻다(取)'예요.",
          ex: { zh: "哪怕只有一线希望，我们也要争取。", pinyin: "nǎpà zhǐyǒu yíxiàn xīwàng, wǒmen yě yào zhēngqǔ", ko: "설령 한 가닥 희망뿐이라도, 우리는 쟁취해야 해요." },
        },
        {
          zh: "质量",
          pinyin: "zhìliàng",
          ko: "질, 품질",
          pos: "명사",
          hanja: "질량(質量) — 한국어 '질량'과 글자는 같지만 보통 '품질'을 뜻해요.",
          ex: { zh: "质量姑且不论，价格就已经太高了。", pinyin: "zhìliàng gūqiě bùlùn, jiàgé jiù yǐjīng tài gāo le", ko: "품질은 일단 논외로 해도, 가격이 이미 너무 비싸요." },
        },
        {
          zh: "价格",
          pinyin: "jiàgé",
          ko: "가격",
          pos: "명사",
          hanja: "가격(價格) — 한자 그대로예요.",
          ex: { zh: "质量姑且不论，价格就已经太高了。", pinyin: "zhìliàng gūqiě bùlùn, jiàgé jiù yǐjīng tài gāo le", ko: "품질은 일단 논외로 해도, 가격이 이미 너무 비싸요." },
        },
        {
          zh: "忽然",
          pinyin: "hūrán",
          ko: "갑자기, 홀연히",
          pos: "부사",
          hanja: "홀연(忽然) — 한국어 '홀연히'와 같아요. 부사로만 써요.",
          ex: { zh: "他忽然想起了一件事。", pinyin: "tā hūrán xiǎngqǐ le yí jiàn shì", ko: "그는 갑자기 한 가지 일이 떠올랐어요." },
        },
        {
          zh: "想起",
          pinyin: "xiǎngqǐ",
          ko: "떠올리다, 생각나다",
          pos: "동사",
          hanja: "상기(想起) — '생각(想)이 일어나다(起)'. 문득 떠오르는 거예요.",
          ex: { zh: "他忽然想起了一件事。", pinyin: "tā hūrán xiǎngqǐ le yí jiàn shì", ko: "그는 갑자기 한 가지 일이 떠올랐어요." },
        },
        {
          zh: "必须",
          pinyin: "bìxū",
          ko: "반드시 ~해야 한다",
          pos: "부사",
          hanja: "필수(必須) — '모름지기(須) 반드시'. 행위의 당위를 나타내요.",
          ex: { zh: "你必须按时完成任务。", pinyin: "nǐ bìxū ànshí wánchéng rènwù", ko: "당신은 제때 임무를 완수해야 해요." },
        },
        {
          zh: "任务",
          pinyin: "rènwù",
          ko: "임무, 과제",
          pos: "명사",
          hanja: "임무(任務) — 한자 그대로예요.",
          ex: { zh: "你必须按时完成任务。", pinyin: "nǐ bìxū ànshí wánchéng rènwù", ko: "당신은 제때 임무를 완수해야 해요." },
        },
        {
          zh: "生命",
          pinyin: "shēngmìng",
          ko: "생명",
          pos: "명사",
          hanja: "생명(生命) — 한자 그대로예요.",
          ex: { zh: "水是生命必需的物质。", pinyin: "shuǐ shì shēngmìng bìxū de wùzhì", ko: "물은 생명에 반드시 필요한 물질이에요." },
        },
        {
          zh: "物质",
          pinyin: "wùzhì",
          ko: "물질",
          pos: "명사",
          hanja: "물질(物質) — 한자 그대로예요.",
          ex: { zh: "水是生命必需的物质。", pinyin: "shuǐ shì shēngmìng bìxū de wùzhì", ko: "물은 생명에 반드시 필요한 물질이에요." },
        },
        {
          zh: "政府",
          pinyin: "zhèngfǔ",
          ko: "정부",
          pos: "명사",
          hanja: "정부(政府) — 한자 그대로예요.",
          ex: { zh: "政府制定了新的环保政策。", pinyin: "zhèngfǔ zhìdìng le xīn de huánbǎo zhèngcè", ko: "정부는 새로운 환경보호 정책을 제정했어요." },
        },
        {
          zh: "制定",
          pinyin: "zhìdìng",
          ko: "제정하다, 정하다",
          pos: "동사",
          hanja: "제정(制定) — '정책·법을 확정해 공포하다'. 制订보다 완결적이에요.",
          ex: { zh: "政府制定了新的环保政策。", pinyin: "zhèngfǔ zhìdìng le xīn de huánbǎo zhèngcè", ko: "정부는 새로운 환경보호 정책을 제정했어요." },
        },
        {
          zh: "正事",
          pinyin: "zhèngshì",
          ko: "본론, 중요한 일",
          pos: "명사",
          hanja: "정사(正事) — '바른(正) 일(事)', 곧 본론·정작 할 일이에요.",
          ex: { zh: "别拍马屁了，说正事吧。", pinyin: "bié pāi mǎpì le, shuō zhèngshì ba", ko: "아첨 그만하고 본론을 말해요." },
        },
        {
          zh: "自然",
          pinyin: "zìrán",
          ko: "자연히, 저절로",
          pos: "부사",
          hanja: "자연(自然) — '스스로(自) 그러하다(然)'. '자연히·저절로'예요.",
          ex: { zh: "正所谓“熟能生巧”，多练习自然就会了。", pinyin: "zhèng suǒwèi shú néng shēng qiǎo, duō liànxí zìrán jiù huì le", ko: "이른바 '익숙해지면 능숙해진다'고, 많이 연습하면 자연히 돼요." },
        },
      ],
    },
  ],
};
