/**
 * H6 (HSK 6급) 보강 어휘 — 청크 E (200개).
 * HSK 2.0 6급 표준 목록 순증분(빈도순, 전 급 교차 중복 배제) — drkameleon/complete-hsk-vocabulary(MIT) 골격.
 * zh·pinyin·pos는 소스 그대로(다음자 단일 한자는 상용 독음으로 교정), ko·예문만 생성 후 결정적 전수 검증.
 */
export default {
  themes: [
    {
      name: "HSK6 보강 E",
      icon: "🟥",
      words: [
        { zh: "轮廓", pinyin: "lún kuò", ko: "윤곽, 실루엣", pos: "명사", ex: { zh: "山的轮廓渐渐清晰起来。", pinyin: "Shān de lún kuò jiàn jiàn qīng xī qǐ lái.", ko: "산의 윤곽이 점점 뚜렷해졌다." } },
        { zh: "起源", pinyin: "qǐ yuán", ko: "기원, 근원", pos: "명사", ex: { zh: "人类的起源一直是个谜。", pinyin: "Rén lèi de qǐ yuán yī zhí shì gè mí.", ko: "인류의 기원은 늘 수수께끼다." } },
        { zh: "妥善", pinyin: "tuǒ shàn", ko: "적절하다, 알맞다", pos: "", ex: { zh: "请妥善保管好你的证件。", pinyin: "Qǐng tuǒ shàn bǎo guǎn hǎo nǐ de zhèng jiàn.", ko: "네 증명서를 적절히 잘 보관해라." } },
        { zh: "耳环", pinyin: "ěr huán", ko: "귀걸이", pos: "명사", ex: { zh: "她戴着一副漂亮的耳环。", pinyin: "Tā dài zhe yī fù piào liang de ěr huán.", ko: "그녀는 예쁜 귀걸이를 하고 있다." } },
        { zh: "颁布", pinyin: "bān bù", ko: "공포하다, 반포하다", pos: "동사", ex: { zh: "政府颁布了新的法律。", pinyin: "Zhèng fǔ bān bù le xīn de fǎ lǜ.", ko: "정부가 새로운 법률을 공포했다." } },
        { zh: "钩子", pinyin: "gōu zi", ko: "갈고리, 후크", pos: "명사", ex: { zh: "墙上挂着一个钩子。", pinyin: "Qiáng shàng guà zhe yī gè gōu zi.", ko: "벽에 갈고리 하나가 걸려 있다." } },
        { zh: "饲养", pinyin: "sì yǎng", ko: "사육하다, 기르다", pos: "동사", ex: { zh: "他在农场饲养鸡鸭。", pinyin: "Tā zài nóng chǎng sì yǎng jī yā.", ko: "그는 농장에서 닭과 오리를 기른다." } },
        { zh: "凝聚", pinyin: "níng jù", ko: "응집하다, 결집하다", pos: "동사", ex: { zh: "团队的力量凝聚在一起。", pinyin: "Tuán duì de lì liàng níng jù zài yī qǐ.", ko: "팀의 힘이 하나로 응집되었다." } },
        { zh: "宽敞", pinyin: "kuān chang", ko: "널찍하다, 넓다", pos: "형용사", ex: { zh: "这间客厅非常宽敞明亮。", pinyin: "Zhè jiān kè tīng fēi cháng kuān chang míng liàng.", ko: "이 거실은 매우 넓고 밝다." } },
        { zh: "恩怨", pinyin: "ēn yuàn", ko: "은원, 은혜와 원한", pos: "명사", ex: { zh: "他们之间的恩怨很复杂。", pinyin: "Tā men zhī jiān de ēn yuàn hěn fù zá.", ko: "그들 사이의 은원 관계는 매우 복잡하다." } },
        { zh: "专程", pinyin: "zhuān chéng", ko: "일부러, 특별히", pos: "부사", ex: { zh: "我专程从北京来看望你。", pinyin: "Wǒ zhuān chéng cóng Běi jīng lái kàn wàng nǐ.", ko: "나는 일부러 베이징에서 너를 보러 왔다." } },
        { zh: "分红", pinyin: "fēn hóng", ko: "배당하다, 배당금", pos: "동사", ex: { zh: "公司年底给员工分红。", pinyin: "Gōng sī nián dǐ gěi yuán gōng fēn hóng.", ko: "회사는 연말에 직원들에게 배당금을 준다." } },
        { zh: "奔波", pinyin: "bēn bō", ko: "분주히 뛰어다니다, 바쁘게 뛰다", pos: "동사", ex: { zh: "他为了生活四处奔波。", pinyin: "Tā wèi le shēng huó sì chù bēn bō.", ko: "그는 생계를 위해 사방으로 분주히 뛰어다닌다." } },
        { zh: "备份", pinyin: "bèi fèn", ko: "백업", pos: "명사", ex: { zh: "记得给文件做备份。", pinyin: "Jì de gěi wén jiàn zuò bèi fèn.", ko: "파일을 백업해 두는 것을 잊지 마라." } },
        { zh: "偏僻", pinyin: "piān pì", ko: "외지다, 궁벽하다", pos: "형용사", ex: { zh: "他住在一个偏僻的山村。", pinyin: "Tā zhù zài yī gè piān pì de shān cūn.", ko: "그는 외진 산골 마을에 산다." } },
        { zh: "亲身", pinyin: "qīn shēn", ko: "몸소, 직접", pos: "부사", ex: { zh: "我亲身经历了这件事。", pinyin: "Wǒ qīn shēn jīng lì le zhè jiàn shì.", ko: "나는 이 일을 직접 경험했다." } },
        { zh: "废除", pinyin: "fèi chú", ko: "폐지하다", pos: "동사", ex: { zh: "这项制度已被废除。", pinyin: "Zhè xiàng zhì dù yǐ bèi fèi chú.", ko: "이 제도는 이미 폐지되었다." } },
        { zh: "镇压", pinyin: "zhèn yā", ko: "진압하다", pos: "동사", ex: { zh: "军队出动镇压叛乱。", pinyin: "Jūn duì chū dòng zhèn yā pàn luàn.", ko: "군대가 출동하여 반란을 진압했다." } },
        { zh: "伺候", pinyin: "cì hou", ko: "시중들다, 모시다", pos: "동사", ex: { zh: "她每天伺候年迈的婆婆。", pinyin: "Tā měi tiān cì hou nián mài de pó po.", ko: "그녀는 매일 연로한 시어머니를 시중든다." } },
        { zh: "鼻涕", pinyin: "bí tì", ko: "콧물", pos: "명사", ex: { zh: "孩子感冒流鼻涕了。", pinyin: "Hái zi gǎn mào liú bí tì le.", ko: "아이가 감기에 걸려 콧물을 흘린다." } },
        { zh: "融洽", pinyin: "róng qià", ko: "화목하다, 사이좋다", pos: "형용사", ex: { zh: "他们相处得非常融洽。", pinyin: "Tā men xiāng chǔ de fēi cháng róng qià.", ko: "그들은 매우 화목하게 지낸다." } },
        { zh: "拼搏", pinyin: "pīn bó", ko: "분투하다, 힘써 싸우다", pos: "동사", ex: { zh: "运动员们奋力拼搏。", pinyin: "Yùn dòng yuán men fèn lì pīn bó.", ko: "선수들이 힘껏 분투했다." } },
        { zh: "功效", pinyin: "gōng xiào", ko: "효능, 효과", pos: "명사", ex: { zh: "这种药有很好的功效。", pinyin: "Zhè zhǒng yào yǒu hěn hǎo de gōng xiào.", ko: "이 약은 효능이 매우 좋다." } },
        { zh: "美满", pinyin: "měi mǎn", ko: "원만하다, 행복하다", pos: "형용사", ex: { zh: "祝你们婚姻美满幸福。", pinyin: "Zhù nǐ men hūn yīn měi mǎn xìng fú.", ko: "당신들의 결혼 생활이 원만하고 행복하길 바랍니다." } },
        { zh: "口头", pinyin: "kǒu tóu", ko: "구두, 말로 하는", pos: "명사", ex: { zh: "这只是口头协议而已。", pinyin: "Zhè zhǐ shì kǒu tóu xié yì ér yǐ.", ko: "이것은 그저 구두 합의일 뿐이다." } },
        { zh: "埋葬", pinyin: "mái zàng", ko: "매장하다", pos: "동사", ex: { zh: "他们把英雄埋葬在山上。", pinyin: "Tā men bǎ yīng xióng mái zàng zài shān shàng.", ko: "그들은 영웅을 산에 매장했다." } },
        { zh: "配偶", pinyin: "pèi ǒu", ko: "배우자", pos: "명사", ex: { zh: "请填写配偶的姓名。", pinyin: "Qǐng tián xiě pèi ǒu de xìng míng.", ko: "배우자의 성명을 기입해 주세요." } },
        { zh: "中立", pinyin: "zhōng lì", ko: "중립적이다, 중립", pos: "동사", ex: { zh: "这个国家一直保持中立。", pinyin: "Zhè gè guó jiā yī zhí bǎo chí zhōng lì.", ko: "이 나라는 줄곧 중립을 유지해 왔다." } },
        { zh: "容纳", pinyin: "róng nà", ko: "수용하다, 받아들이다", pos: "동사", ex: { zh: "这个礼堂能容纳千人。", pinyin: "Zhè gè lǐ táng néng róng nà qiān rén.", ko: "이 강당은 천 명을 수용할 수 있다." } },
        { zh: "公然", pinyin: "gōng rán", ko: "공공연히, 대놓고", pos: "부사", ex: { zh: "他公然违反了规定。", pinyin: "Tā gōng rán wéi fǎn le guī dìng.", ko: "그는 공공연히 규정을 위반했다." } },
        { zh: "勇于", pinyin: "yǒng yú", ko: "용감하게 ~하다, 과감히 ~하다", pos: "동사", ex: { zh: "我们要勇于面对困难。", pinyin: "Wǒ men yào yǒng yú miàn duì kùn nan.", ko: "우리는 용감하게 어려움에 맞서야 한다." } },
        { zh: "反思", pinyin: "fǎn sī", ko: "반성하다, 되돌아보다", pos: "동사", ex: { zh: "他认真反思了自己的错误。", pinyin: "Tā rèn zhēn fǎn sī le zì jǐ de cuò wù.", ko: "그는 자신의 잘못을 진지하게 반성했다." } },
        { zh: "洞穴", pinyin: "dòng xué", ko: "동굴", pos: "명사", ex: { zh: "探险队发现了一个洞穴。", pinyin: "Tàn xiǎn duì fā xiàn le yī gè dòng xué.", ko: "탐험대가 동굴 하나를 발견했다." } },
        { zh: "坚实", pinyin: "jiān shí", ko: "견실하다, 튼튼하다", pos: "형용사", ex: { zh: "他打下了坚实的基础。", pinyin: "Tā dǎ xià le jiān shí de jī chǔ.", ko: "그는 견실한 기초를 다졌다." } },
        { zh: "向来", pinyin: "xiàng lái", ko: "줄곧, 원래부터", pos: "부사", ex: { zh: "他向来做事非常认真。", pinyin: "Tā xiàng lái zuò shì fēi cháng rèn zhēn.", ko: "그는 줄곧 일을 매우 성실하게 한다." } },
        { zh: "投机", pinyin: "tóu jī", ko: "투기하다, 기회를 노리다", pos: "동사", ex: { zh: "他靠投机赚了不少钱。", pinyin: "Tā kào tóu jī zhuàn le bù shǎo qián.", ko: "그는 투기로 적지 않은 돈을 벌었다." } },
        { zh: "黄昏", pinyin: "huáng hūn", ko: "황혼, 해질녘", pos: "명사", ex: { zh: "我们在黄昏时分散步。", pinyin: "Wǒ men zài huáng hūn shí fēn sàn bù.", ko: "우리는 황혼 무렵에 산책을 한다." } },
        { zh: "展望", pinyin: "zhǎn wàng", ko: "전망하다, 내다보다", pos: "동사", ex: { zh: "让我们展望美好的未来。", pinyin: "Ràng wǒ men zhǎn wàng měi hǎo de wèi lái.", ko: "우리 함께 아름다운 미래를 전망해 보자." } },
        { zh: "庄严", pinyin: "zhuāng yán", ko: "장엄하다, 엄숙하다", pos: "형용사", ex: { zh: "会场气氛庄严肃穆。", pinyin: "Huì chǎng qì fēn zhuāng yán sù mù.", ko: "회의장 분위기가 장엄하고 엄숙하다." } },
        { zh: "蹬", pinyin: "dēng", ko: "밟다, 딛다", pos: "동사", ex: { zh: "他用力蹬了一下自行车。", pinyin: "Tā yòng lì dēng le yī xià zì xíng chē.", ko: "그는 힘껏 자전거 페달을 밟았다." } },
        { zh: "冷淡", pinyin: "lěng dàn", ko: "냉담하다, 무관심하다", pos: "형용사", ex: { zh: "他对我态度很冷淡。", pinyin: "Tā duì wǒ tài dù hěn lěng dàn.", ko: "그는 나에게 태도가 매우 냉담하다." } },
        { zh: "草案", pinyin: "cǎo àn", ko: "초안", pos: "명사", ex: { zh: "委员会通过了这份草案。", pinyin: "Wěi yuán huì tōng guò le zhè fèn cǎo àn.", ko: "위원회가 이 초안을 통과시켰다." } },
        { zh: "流露", pinyin: "liú lù", ko: "무심코 드러내다, 나타내다", pos: "동사", ex: { zh: "她脸上流露出喜悦之情。", pinyin: "Tā liǎn shàng liú lù chū xǐ yuè zhī qíng.", ko: "그녀의 얼굴에 기쁜 감정이 드러났다." } },
        { zh: "冤枉", pinyin: "yuān wang", ko: "억울하게 하다, 누명을 씌우다", pos: "동사", ex: { zh: "他被冤枉偷了东西。", pinyin: "Tā bèi yuān wang tōu le dōng xi.", ko: "그는 억울하게 물건을 훔쳤다는 누명을 썼다." } },
        { zh: "生机", pinyin: "shēng jī", ko: "생기, 삶의 활력", pos: "명사", ex: { zh: "春天的田野充满生机。", pinyin: "Chūn tiān de tián yě chōng mǎn shēng jī.", ko: "봄날의 들판은 생기로 가득하다." } },
        { zh: "陷害", pinyin: "xiàn hài", ko: "모함하다, 함정에 빠뜨리다", pos: "동사", ex: { zh: "公司里有人蓄意陷害他。", pinyin: "Gōng sī lǐ yǒu rén xù yì xiàn hài tā.", ko: "회사에서 누군가 고의로 그를 모함했다." } },
        { zh: "体谅", pinyin: "tǐ liàng", ko: "이해하다, 헤아리다", pos: "동사", ex: { zh: "请你多体谅我的难处。", pinyin: "Qǐng nǐ duō tǐ liàng wǒ de nán chù.", ko: "제 어려움을 좀 더 헤아려 주세요." } },
        { zh: "起义", pinyin: "qǐ yì", ko: "봉기하다, 반란을 일으키다", pos: "동사", ex: { zh: "农民纷纷起义反抗。", pinyin: "Nóng mín fēn fēn qǐ yì fǎn kàng.", ko: "농민들이 잇달아 봉기하여 반항했다." } },
        { zh: "缓和", pinyin: "huǎn hé", ko: "완화하다, 누그러뜨리다", pos: "동사", ex: { zh: "双方关系逐渐缓和。", pinyin: "Shuāng fāng guān xì zhú jiàn huǎn hé.", ko: "양측 관계가 점차 완화되었다." } },
        { zh: "戒备", pinyin: "jiè bèi", ko: "경계하다, 대비하다", pos: "동사", ex: { zh: "警方已经加强了戒备。", pinyin: "Jǐng fāng yǐ jīng jiā qiáng le jiè bèi.", ko: "경찰은 이미 경계를 강화했다." } },
        { zh: "报销", pinyin: "bào xiāo", ko: "정산하다, 청구하다", pos: "동사", ex: { zh: "出差费用可以报销。", pinyin: "Chū chāi fèi yòng kě yǐ bào xiāo.", ko: "출장비는 청구하여 정산할 수 있다." } },
        { zh: "严禁", pinyin: "yán jìn", ko: "엄금하다, 엄격히 금지하다", pos: "동사", ex: { zh: "车间内严禁吸烟喝酒。", pinyin: "Chē jiān nèi yán jìn xī yān hē jiǔ.", ko: "작업장 내에서는 흡연과 음주를 엄금한다." } },
        { zh: "结晶", pinyin: "jié jīng", ko: "결정체, 결정", pos: "명사", ex: { zh: "这是他多年努力的结晶。", pinyin: "Zhè shì tā duō nián nǔ lì de jié jīng.", ko: "이것은 그가 여러 해 노력한 결정체이다." } },
        { zh: "想方设法", pinyin: "xiǎng fāng shè fǎ", ko: "온갖 방법을 다 강구하다, 갖은 수를 다 쓰다", pos: "관용구", ex: { zh: "他想方设法解决问题。", pinyin: "Tā xiǎng fāng shè fǎ jiě jué wèn tí.", ko: "그는 온갖 방법을 다 강구해서 문제를 해결했다." } },
        { zh: "索赔", pinyin: "suǒ péi", ko: "배상을 청구하다, 손해배상을 요구하다", pos: "동사", ex: { zh: "消费者向厂家索赔。", pinyin: "Xiāo fèi zhě xiàng chǎng jiā suǒ péi.", ko: "소비자가 제조사에 손해배상을 청구했다." } },
        { zh: "手艺", pinyin: "shǒu yì", ko: "손재주, 솜씨", pos: "명사", ex: { zh: "他的木工手艺很好。", pinyin: "Tā de mù gōng shǒu yì hěn hǎo.", ko: "그의 목공 솜씨는 매우 훌륭하다." } },
        { zh: "领会", pinyin: "lǐng huì", ko: "이해하다, 파악하다", pos: "동사", ex: { zh: "我终于领会了他的意思。", pinyin: "Wǒ zhōng yú lǐng huì le tā de yì si.", ko: "나는 마침내 그의 뜻을 이해했다." } },
        { zh: "参照", pinyin: "cān zhào", ko: "참조하다, 참고하다", pos: "동사", ex: { zh: "请参照说明书操作。", pinyin: "Qǐng cān zhào shuō míng shū cāo zuò.", ko: "설명서를 참조하여 조작해 주세요." } },
        { zh: "摇摆", pinyin: "yáo bǎi", ko: "흔들리다, 동요하다", pos: "동사", ex: { zh: "树枝在风中不断摇摆。", pinyin: "Shù zhī zài fēng zhōng bù duàn yáo bǎi.", ko: "나뭇가지가 바람에 끊임없이 흔들린다." } },
        { zh: "优越", pinyin: "yōu yuè", ko: "우월하다, 우수하다", pos: "형용사", ex: { zh: "他家条件十分优越。", pinyin: "Tā jiā tiáo jiàn shí fēn yōu yuè.", ko: "그의 집안 형편은 매우 우월하다." } },
        { zh: "开朗", pinyin: "kāi lǎng", ko: "명랑하다, 쾌활하다", pos: "형용사", ex: { zh: "她的性格开朗又活泼。", pinyin: "Tā de xìng gé kāi lǎng yòu huó pō.", ko: "그녀의 성격은 명랑하고 또 활발하다." } },
        { zh: "哨", pinyin: "shào", ko: "호루라기, 초소", pos: "", ex: { zh: "老师吹哨集合队伍。", pinyin: "Lǎo shī chuī shào jí hé duì wǔ.", ko: "선생님이 호루라기를 불어 대열을 집합시켰다." } },
        { zh: "着迷", pinyin: "zháo mí", ko: "빠지다, 매료되다", pos: "동사", ex: { zh: "他对绘画非常着迷。", pinyin: "Tā duì huì huà fēi cháng zháo mí.", ko: "그는 그림에 매우 매료되어 있다." } },
        { zh: "随即", pinyin: "suí jí", ko: "즉시, 곧바로", pos: "부사", ex: { zh: "他说完随即离开了。", pinyin: "Tā shuō wán suí jí lí kāi le.", ko: "그는 말을 마치고 곧바로 떠났다." } },
        { zh: "做主", pinyin: "zuò zhǔ", ko: "결정하다, 주관하다", pos: "동사", ex: { zh: "这件事情由你做主。", pinyin: "Zhè jiàn shì qing yóu nǐ zuò zhǔ.", ko: "이 일은 네가 결정해라." } },
        { zh: "文凭", pinyin: "wén píng", ko: "졸업장, 학위증", pos: "명사", ex: { zh: "他终于拿到了文凭。", pinyin: "Tā zhōng yú ná dào le wén píng.", ko: "그는 마침내 졸업장을 받았다." } },
        { zh: "捎", pinyin: "shāo", ko: "가져다주다, 전달하다", pos: "동사", ex: { zh: "麻烦你给他捎个口信。", pinyin: "Má fan nǐ gěi tā shāo gè kǒu xìn.", ko: "번거롭겠지만 그에게 메시지 좀 전해 주세요." } },
        { zh: "无非", pinyin: "wú fēi", ko: "단지 ~에 지나지 않다, ~에 불과하다", pos: "부사", ex: { zh: "他的目的无非是赚钱。", pinyin: "Tā de mù dì wú fēi shì zhuàn qián.", ko: "그의 목적은 단지 돈을 버는 것에 불과하다." } },
        { zh: "启程", pinyin: "qǐ chéng", ko: "출발하다, 떠나다", pos: "동사", ex: { zh: "我们明天早上启程。", pinyin: "Wǒ men míng tiān zǎo shang qǐ chéng.", ko: "우리는 내일 아침에 출발한다." } },
        { zh: "提拔", pinyin: "tí bá", ko: "발탁하다, 등용하다", pos: "동사", ex: { zh: "老板决定提拔他了。", pinyin: "Lǎo bǎn jué dìng tí bá tā le.", ko: "사장은 그를 발탁하기로 결정했다." } },
        { zh: "皮革", pinyin: "pí gé", ko: "가죽", pos: "명사", ex: { zh: "这个包是真皮革做的。", pinyin: "Zhè ge bāo shì zhēn pí gé zuò de.", ko: "이 가방은 진짜 가죽으로 만든 것이다." } },
        { zh: "告诫", pinyin: "gào jiè", ko: "타이르다, 훈계하다", pos: "동사", ex: { zh: "老师告诫我们要认真学习。", pinyin: "Lǎo shī gào jiè wǒ men yào rèn zhēn xué xí.", ko: "선생님이 우리에게 열심히 공부하라고 타일렀다." } },
        { zh: "踪迹", pinyin: "zōng jì", ko: "종적, 자취", pos: "명사", ex: { zh: "警察在追查他的踪迹。", pinyin: "Jǐng chá zài zhuī chá tā de zōng jì.", ko: "경찰이 그의 종적을 뒤쫓고 있다." } },
        { zh: "沉思", pinyin: "chén sī", ko: "심사숙고하다, 깊이 생각하다", pos: "동사", ex: { zh: "他独自坐在窗前沉思。", pinyin: "Tā dú zì zuò zài chuāng qián chén sī.", ko: "그는 홀로 창가에 앉아 깊이 생각에 잠겼다." } },
        { zh: "精密", pinyin: "jīng mì", ko: "정밀하다, 정교하다", pos: "형용사", ex: { zh: "这是一台精密仪器。", pinyin: "Zhè shì yī tái jīng mì yí qì.", ko: "이것은 정밀한 기계이다." } },
        { zh: "掠夺", pinyin: "lu:è duó", ko: "약탈하다", pos: "동사", ex: { zh: "侵略者掠夺了大量财物。", pinyin: "Qīn lüè zhě lüè duó le dà liàng cái wù.", ko: "침략자들이 대량의 재물을 약탈했다." } },
        { zh: "剥削", pinyin: "bō xuē", ko: "착취하다", pos: "동사", ex: { zh: "资本家残酷剥削工人。", pinyin: "Zī běn jiā cán kù bō xuē gōng rén.", ko: "자본가가 노동자를 잔혹하게 착취한다." } },
        { zh: "话筒", pinyin: "huà tǒng", ko: "마이크, 수화기", pos: "명사", ex: { zh: "他拿起话筒开始讲话。", pinyin: "Tā ná qǐ huà tǒng kāi shǐ jiǎng huà.", ko: "그는 마이크를 들고 말하기 시작했다." } },
        { zh: "晋升", pinyin: "jìn shēng", ko: "승진하다", pos: "동사", ex: { zh: "她今年晋升为经理。", pinyin: "Tā jīn nián jìn shēng wéi jīng lǐ.", ko: "그녀는 올해 매니저로 승진했다." } },
        { zh: "溶解", pinyin: "róng jiě", ko: "용해되다, 녹다", pos: "동사", ex: { zh: "盐在水中容易溶解。", pinyin: "Yán zài shuǐ zhōng róng yì róng jiě.", ko: "소금은 물에 쉽게 용해된다." } },
        { zh: "疏忽", pinyin: "shū hu", ko: "소홀히 하다, 부주의로 놓치다", pos: "동사", ex: { zh: "他因疏忽而忘记关窗户。", pinyin: "Tā yīn shūhu ér wàngjì guān chuānghu.", ko: "그는 부주의로 창문 닫는 것을 잊었다." } },
        { zh: "粉末", pinyin: "fěn mò", ko: "가루, 분말", pos: "명사", ex: { zh: "这种药是白色的粉末。", pinyin: "Zhè zhǒng yào shì báisè de fěnmò.", ko: "이 약은 하얀 가루다." } },
        { zh: "衰退", pinyin: "shuāi tuì", ko: "쇠퇴하다, 쇠약해지다", pos: "동사", ex: { zh: "经济衰退给企业带来很大压力。", pinyin: "Jīngjì shuāituì gěi qǐyè dàilái hěn dà yālì.", ko: "경기 침체는 기업에 큰 부담을 준다." } },
        { zh: "呻吟", pinyin: "shēn yín", ko: "신음하다", pos: "동사", ex: { zh: "病人痛苦地呻吟着。", pinyin: "Bìngrén tòngkǔ de shēnyínzhe.", ko: "환자가 고통스럽게 신음하고 있다." } },
        { zh: "讨价还价", pinyin: "tǎo jià huán jià", ko: "흥정하다", pos: "동사", ex: { zh: "买东西时她喜欢讨价还价。", pinyin: "Mǎi dōngxi shí tā xǐhuan tǎojiàhuánjià.", ko: "그녀는 물건을 살 때 흥정하는 것을 좋아한다." } },
        { zh: "雕刻", pinyin: "diāo kè", ko: "조각, 조각하다", pos: "명사", ex: { zh: "这座雕刻非常精美。", pinyin: "Zhè zuò diāokè fēicháng jīngměi.", ko: "이 조각은 매우 정교하고 아름답다." } },
        { zh: "挥霍", pinyin: "huī huò", ko: "낭비하다, 흥청망청 쓰다", pos: "동사", ex: { zh: "他把钱都挥霍光了。", pinyin: "Tā bǎ qián dōu huīhuò guāng le.", ko: "그는 돈을 다 탕진해 버렸다." } },
        { zh: "恼火", pinyin: "nǎo huǒ", ko: "화나다, 언짢다", pos: "형용사", ex: { zh: "这件事让他非常恼火。", pinyin: "Zhè jiàn shì ràng tā fēicháng nǎohuǒ.", ko: "이 일은 그를 매우 화나게 했다." } },
        { zh: "趣味", pinyin: "qù wèi", ko: "재미, 흥미", pos: "명사", ex: { zh: "这部电影很有趣味。", pinyin: "Zhè bù diànyǐng hěn yǒu qùwèi.", ko: "이 영화는 매우 재미있다." } },
        { zh: "枯燥", pinyin: "kū zào", ko: "무미건조하다, 지루하다", pos: "형용사", ex: { zh: "这门课的内容很枯燥。", pinyin: "Zhè mén kè de nèiróng hěn kūzào.", ko: "이 수업 내용은 매우 지루하다." } },
        { zh: "争端", pinyin: "zhēng duān", ko: "분쟁, 다툼", pos: "명사", ex: { zh: "双方应和平解决争端。", pinyin: "Shuāngfāng yīng hépíng jiějué zhēngduān.", ko: "양측은 평화적으로 분쟁을 해결해야 한다." } },
        { zh: "人道", pinyin: "rén dào", ko: "인도주의, 인도적인", pos: "명사", ex: { zh: "我们应该给予人道救援。", pinyin: "Wǒmen yīnggāi jǐyǔ réndào jiùyuán.", ko: "우리는 인도적 지원을 제공해야 한다." } },
        { zh: "方言", pinyin: "Fāng yán", ko: "사투리, 방언", pos: "명사", ex: { zh: "他讲话带着浓重的方言。", pinyin: "Tā jiǎnghuà dàizhe nóngzhòng de fāngyán.", ko: "그는 진한 사투리로 말한다." } },
        { zh: "丰盛", pinyin: "fēng shèng", ko: "풍성하다, 푸짐하다", pos: "형용사", ex: { zh: "妈妈准备了丰盛的晚餐。", pinyin: "Māma zhǔnbèi le fēngshèng de wǎncān.", ko: "엄마는 푸짐한 저녁 식사를 준비했다." } },
        { zh: "后勤", pinyin: "hòu qín", ko: "병참, 후방 지원", pos: "명사", ex: { zh: "他负责部队的后勤工作。", pinyin: "Tā fùzé bùduì de hòuqín gōngzuò.", ko: "그는 부대의 병참 업무를 담당한다." } },
        { zh: "捣乱", pinyin: "dǎo luàn", ko: "소란을 피우다, 훼방 놓다", pos: "동사", ex: { zh: "你别在教室里捣乱。", pinyin: "Nǐ bié zài jiàoshì lǐ dǎoluàn.", ko: "너 교실에서 소란 피우지 마." } },
        { zh: "优异", pinyin: "yōu yì", ko: "우수하다, 뛰어나다", pos: "형용사", ex: { zh: "他取得了优异的成绩。", pinyin: "Tā qǔdé le yōuyì de chéngjì.", ko: "그는 우수한 성적을 거두었다." } },
        { zh: "媳妇", pinyin: "xí fù", ko: "며느리, 아내", pos: "명사", ex: { zh: "她是我们家的媳妇。", pinyin: "Tā shì wǒmen jiā de xífù.", ko: "그녀는 우리 집 며느리다." } },
        { zh: "腹泻", pinyin: "fù xiè", ko: "설사하다", pos: "동사", ex: { zh: "他吃坏肚子腹泻了。", pinyin: "Tā chī huài dùzi fùxiè le.", ko: "그는 배탈이 나서 설사를 했다." } },
        { zh: "逼迫", pinyin: "bī pò", ko: "강요하다, 핍박하다", pos: "동사", ex: { zh: "他被逼迫签下合同。", pinyin: "Tā bèi bīpò qiānxià hétong.", ko: "그는 계약서에 서명하도록 강요받았다." } },
        { zh: "不得已", pinyin: "bù dé yǐ", ko: "부득이하다, 어쩔 수 없다", pos: "형용사", ex: { zh: "我不得已才这样做。", pinyin: "Wǒ bùdéyǐ cái zhèyàng zuò.", ko: "나는 어쩔 수 없이 이렇게 했다." } },
        { zh: "框架", pinyin: "kuàng jià", ko: "틀, 프레임", pos: "명사", ex: { zh: "这本书有明确的框架。", pinyin: "Zhè běn shū yǒu míngquè de kuàngjià.", ko: "이 책은 명확한 틀을 갖추고 있다." } },
        { zh: "断定", pinyin: "duàn dìng", ko: "단정하다, 단언하다", pos: "동사", ex: { zh: "警方断定他就是凶手。", pinyin: "Jǐngfāng duàndìng tā jiùshì xiōngshǒu.", ko: "경찰은 그가 바로 범인이라고 단정했다." } },
        { zh: "复兴", pinyin: "Fù xīng", ko: "부흥하다, 재건하다", pos: "동사", ex: { zh: "民族复兴是我们的目标。", pinyin: "Mínzú fùxīng shì wǒmen de mùbiāo.", ko: "민족 부흥은 우리의 목표다." } },
        { zh: "风趣", pinyin: "fēng qù", ko: "재치 있다, 유머러스하다", pos: "형용사", ex: { zh: "他说话总是很风趣。", pinyin: "Tā shuōhuà zǒngshì hěn fēngqù.", ko: "그는 말할 때 늘 재치가 넘친다." } },
        { zh: "曲折", pinyin: "qū zhé", ko: "구불구불하다, 우여곡절이 많다", pos: "형용사", ex: { zh: "他的经历十分曲折。", pinyin: "Tā de jīnglì shífēn qūzhé.", ko: "그의 경험은 매우 우여곡절이 많다." } },
        { zh: "变质", pinyin: "biàn zhì", ko: "변질되다, 상하다", pos: "동사", ex: { zh: "天热食物容易变质。", pinyin: "Tiān rè shíwù róngyì biànzhì.", ko: "날씨가 더우면 음식이 쉽게 상한다." } },
        { zh: "混淆", pinyin: "hùn xiáo", ko: "혼동하다, 뒤섞다", pos: "동사", ex: { zh: "不要混淆这两个概念。", pinyin: "Bùyào hùnxiáo zhè liǎng ge gàiniàn.", ko: "이 두 개념을 혼동하지 마라." } },
        { zh: "捆绑", pinyin: "kǔn bǎng", ko: "묶다, 결박하다", pos: "동사", ex: { zh: "他把行李捆绑在车上。", pinyin: "Tā bǎ xíngli kǔnbǎng zài chē shang.", ko: "그는 짐을 차에 묶었다." } },
        { zh: "急剧", pinyin: "jí jù", ko: "급격히, 급격하다", pos: "부사", ex: { zh: "最近气温急剧下降。", pinyin: "Zuìjìn qìwēn jíjù xiàjiàng.", ko: "요즘 기온이 급격히 내려갔다." } },
        { zh: "交涉", pinyin: "jiāo shè", ko: "교섭하다, 협상하다", pos: "동사", ex: { zh: "双方正在交涉此事。", pinyin: "Shuāngfāng zhèngzài jiāoshè cǐ shì.", ko: "양측은 이 일에 대해 교섭 중이다." } },
        { zh: "锋利", pinyin: "fēng lì", ko: "날카롭다, 예리하다", pos: "형용사", ex: { zh: "这把刀看起来非常锋利。", pinyin: "Zhè bǎ dāo kànqǐlái fēicháng fēnglì.", ko: "이 칼은 매우 날카로워 보인다." } },
        { zh: "思索", pinyin: "sī suǒ", ko: "깊이 생각하다, 사색하다", pos: "동사", ex: { zh: "他静静地思索着问题。", pinyin: "Tā jìngjìng de sīsuǒzhe wèntí.", ko: "그는 조용히 문제를 깊이 생각하고 있다." } },
        { zh: "二氧化碳", pinyin: "èr yǎng huà tàn", ko: "이산화탄소", pos: "명사", ex: { zh: "植物能吸收二氧化碳。", pinyin: "Zhíwù néng xīshōu èryǎnghuàtàn.", ko: "식물은 이산화탄소를 흡수할 수 있다." } },
        { zh: "编织", pinyin: "biān zhī", ko: "짜다, 엮다", pos: "동사", ex: { zh: "奶奶正在编织毛衣。", pinyin: "Nǎinai zhèngzài biānzhī máoyī.", ko: "할머니는 스웨터를 뜨고 계신다." } },
        { zh: "改良", pinyin: "gǎi liáng", ko: "개량하다, 개선하다", pos: "동사", ex: { zh: "农民改良了种植技术。", pinyin: "Nóngmín gǎiliáng le zhòngzhí jìshù.", ko: "농민들은 재배 기술을 개량했다." } },
        { zh: "驻扎", pinyin: "zhù zhā", ko: "주둔하다", pos: "동사", ex: { zh: "部队驻扎在边境地区。", pinyin: "Bùduì zhùzhā zài biānjìng dìqū.", ko: "부대는 국경 지역에 주둔하고 있다." } },
        { zh: "急切", pinyin: "jí qiè", ko: "다급하다, 간절하다", pos: "형용사", ex: { zh: "他急切地想知道结果。", pinyin: "Tā jíqiè de xiǎng zhīdào jiéguǒ.", ko: "그는 결과를 간절히 알고 싶어 했다." } },
        { zh: "施加", pinyin: "shī jiā", ko: "가하다, 행사하다", pos: "동사", ex: { zh: "他们对我施加压力。", pinyin: "Tāmen duì wǒ shījiā yālì.", ko: "그들은 나에게 압력을 가했다." } },
        { zh: "私自", pinyin: "sī zì", ko: "몰래, 무단으로", pos: "부사", ex: { zh: "他私自拿走了文件。", pinyin: "Tā sīzì názǒu le wénjiàn.", ko: "그는 무단으로 서류를 가져갔다." } },
        { zh: "宏伟", pinyin: "hóng wěi", ko: "웅장하다, 장엄하다", pos: "형용사", ex: { zh: "这座建筑非常宏伟。", pinyin: "Zhè zuò jiànzhù fēicháng hóngwěi.", ko: "이 건물은 매우 웅장하다." } },
        { zh: "惦记", pinyin: "diàn jì", ko: "마음에 두다, 그리워하다", pos: "동사", ex: { zh: "妈妈总是惦记着我。", pinyin: "Māma zǒngshì diànjìzhe wǒ.", ko: "엄마는 항상 나를 걱정하신다." } },
        { zh: "岛屿", pinyin: "dǎo yǔ", ko: "섬", pos: "명사", ex: { zh: "这里有许多美丽的岛屿。", pinyin: "Zhèlǐ yǒu xǔduō měilì de dǎoyǔ.", ko: "이곳에는 아름다운 섬이 많다." } },
        { zh: "茫茫", pinyin: "máng máng", ko: "아득하다, 망망하다", pos: "형용사", ex: { zh: "大海茫茫望不到边。", pinyin: "Dàhǎi mángmáng wàng bú dào biān.", ko: "바다는 아득하여 끝이 보이지 않는다." } },
        { zh: "敏捷", pinyin: "mǐn jié", ko: "민첩하다, 재빠르다", pos: "형용사", ex: { zh: "他的动作十分敏捷。", pinyin: "Tā de dòngzuò shífēn mǐnjié.", ko: "그의 동작은 매우 민첩하다." } },
        { zh: "进而", pinyin: "jìn ér", ko: "더 나아가, 진일보하여", pos: "접속사", ex: { zh: "先了解情况,进而制定计划。", pinyin: "Xiān liǎojiě qíngkuàng, jìn'ér zhìdìng jìhuà.", ko: "먼저 상황을 파악하고, 더 나아가 계획을 세운다." } },
        { zh: "简化", pinyin: "jiǎn huà", ko: "간소화하다", pos: "동사", ex: { zh: "我们需要简化流程。", pinyin: "Wǒmen xūyào jiǎnhuà liúchéng.", ko: "우리는 절차를 간소화할 필요가 있다." } },
        { zh: "懒惰", pinyin: "lǎn duò", ko: "게으르다, 나태하다", pos: "형용사", ex: { zh: "他因为懒惰被批评了。", pinyin: "Tā yīnwèi lǎnduò bèi pīpíng le.", ko: "그는 게을러서 비판받았다." } },
        { zh: "柴油", pinyin: "chái yóu", ko: "디젤유, 경유", pos: "명사", ex: { zh: "这辆卡车用柴油发动。", pinyin: "Zhè liàng kǎchē yòng cháiyóu fādòng.", ko: "이 트럭은 경유로 시동을 건다." } },
        { zh: "可口", pinyin: "kě kǒu", ko: "맛있다, 입에 맞다", pos: "형용사", ex: { zh: "这道菜味道非常可口。", pinyin: "Zhè dào cài wèidào fēicháng kěkǒu.", ko: "이 요리는 맛이 매우 좋다." } },
        { zh: "殖民地", pinyin: "zhí mín dì", ko: "식민지", pos: "명사", ex: { zh: "这里曾经是英国的殖民地。", pinyin: "Zhèlǐ céngjīng shì Yīngguó de zhímíndì.", ko: "이곳은 예전에 영국의 식민지였다." } },
        { zh: "酗酒", pinyin: "xù jiǔ", ko: "폭음하다, 술을 지나치게 마시다", pos: "동사", ex: { zh: "长期酗酒对身体有害。", pinyin: "Chángqī xùjiǔ duì shēntǐ yǒuhài.", ko: "장기간 폭음은 몸에 해롭다." } },
        { zh: "池塘", pinyin: "chí táng", ko: "연못", pos: "명사", ex: { zh: "院子里有一个池塘。", pinyin: "Yuànzi lǐ yǒu yí ge chítáng.", ko: "마당에는 연못이 하나 있다." } },
        { zh: "示意", pinyin: "shì yì", ko: "신호를 보내다, 의사를 나타내다", pos: "동사", ex: { zh: "他向我示意快点走。", pinyin: "Tā xiàng wǒ shìyì kuài diǎn zǒu.", ko: "그는 나에게 빨리 가라고 신호를 보냈다." } },
        { zh: "熄灭", pinyin: "xī miè", ko: "꺼지다, 소멸하다", pos: "동사", ex: { zh: "火焰终于慢慢熄灭了。", pinyin: "Huǒyàn zhōngyú mànmàn xīmiè le.", ko: "불꽃이 마침내 서서히 꺼졌다." } },
        { zh: "开辟", pinyin: "kāi pì", ko: "개척하다, 열다", pos: "동사", ex: { zh: "他们开辟了一条新路。", pinyin: "Tāmen kāipì le yì tiáo xīn lù.", ko: "그들은 새로운 길을 개척했다." } },
        { zh: "漂浮", pinyin: "piāo fú", ko: "떠다니다, 부유하다", pos: "동사", ex: { zh: "树叶在水面漂浮着。", pinyin: "Shùyè zài shuǐmiàn piāofúzhe.", ko: "나뭇잎이 수면 위에 떠 있다." } },
        { zh: "空洞", pinyin: "kōng dòng", ko: "공허하다, 내용이 없다", pos: "형용사", ex: { zh: "他的发言内容很空洞。", pinyin: "Tā de fāyán nèiróng hěn kōngdòng.", ko: "그의 발언 내용은 매우 공허하다." } },
        { zh: "打量", pinyin: "dǎ liang", ko: "훑어보다, 관찰하다", pos: "동사", ex: { zh: "她仔细打量着来客。", pinyin: "Tā zǐxì dǎliangzhe láikè.", ko: "그녀는 손님을 자세히 훑어보았다." } },
        { zh: "反常", pinyin: "fǎn cháng", ko: "이상하다, 비정상적이다", pos: "형용사", ex: { zh: "今天他的行为很反常。", pinyin: "Jīntiān tā de xíngwéi hěn fǎncháng.", ko: "오늘 그의 행동은 매우 이상하다." } },
        { zh: "泛滥", pinyin: "fàn làn", ko: "범람하다, 넘쳐나다", pos: "동사", ex: { zh: "洪水泛滥淹没了农田。", pinyin: "Hóngshuǐ fànlàn yānmò le nóngtián.", ko: "홍수가 범람하여 농경지를 침수시켰다." } },
        { zh: "大意", pinyin: "dà yì", ko: "요지, 대강의 뜻", pos: "명사", ex: { zh: "请概括这段话的大意。", pinyin: "Qǐng gàikuò zhè duàn huà de dàyì.", ko: "이 단락의 요지를 요약해 주세요." } },
        { zh: "会晤", pinyin: "huì wù", ko: "회담하다, 만나다", pos: "동사", ex: { zh: "两国领导人举行会晤。", pinyin: "Liǎng guó lǐngdǎorén jǔxíng huìwù.", ko: "양국 정상이 회담을 가졌다." } },
        { zh: "焦急", pinyin: "jiāo jí", ko: "초조하다, 애타다", pos: "형용사", ex: { zh: "妈妈焦急地等着他回家。", pinyin: "Māma jiāojí de děngzhe tā huí jiā.", ko: "엄마는 초조하게 그가 집에 돌아오기를 기다렸다." } },
        { zh: "体面", pinyin: "tǐ miàn", ko: "품위 있다, 체면이 서다", pos: "형용사", ex: { zh: "他今天穿得非常体面。", pinyin: "Tā jīntiān chuān de fēicháng tǐmiàn.", ko: "그는 오늘 매우 품위 있게 옷을 입었다." } },
        { zh: "胡乱", pinyin: "hú luàn", ko: "함부로, 마구잡이로", pos: "부사", ex: { zh: "他胡乱回答了几句。", pinyin: "Tā húluàn huídá le jǐ jù.", ko: "그는 되는대로 몇 마디 대답했다." } },
        { zh: "凝固", pinyin: "níng gù", ko: "응고하다, 굳다", pos: "동사", ex: { zh: "蜡烛油冷却后凝固了。", pinyin: "Làzhú yóu lěngquè hòu nínggù le.", ko: "촛농이 식은 후 굳었다." } },
        { zh: "意向", pinyin: "yì xiàng", ko: "의향, 의도", pos: "명사", ex: { zh: "公司表达了合作意向。", pinyin: "Gōngsī biǎodá le hézuò yìxiàng.", ko: "회사는 협력할 의향을 나타냈다." } },
        { zh: "源泉", pinyin: "yuán quán", ko: "원천, 근원", pos: "명사", ex: { zh: "知识是力量的源泉。", pinyin: "Zhīshi shì lìliàng de yuánquán.", ko: "지식은 힘의 원천이다." } },
        { zh: "夕阳", pinyin: "xī yáng", ko: "석양, 노을", pos: "명사", ex: { zh: "夕阳西下,景色很美。", pinyin: "Xīyáng xī xià, jǐngsè hěn měi.", ko: "석양이 서쪽으로 지니 풍경이 매우 아름답다." } },
        { zh: "海拔", pinyin: "hǎi bá", ko: "해발", pos: "명사", ex: { zh: "这座山的海拔非常高。", pinyin: "Zhè zuò shān de hǎibá fēicháng gāo.", ko: "이 산의 해발은 매우 높다." } },
        { zh: "摇晃", pinyin: "yáo huàng", ko: "흔들리다, 흔들다", pos: "동사", ex: { zh: "船在海上摇晃不停。", pinyin: "Chuán zài hǎishàng yáohuàng bùtíng.", ko: "배가 바다 위에서 계속 흔들린다." } },
        { zh: "发呆", pinyin: "fā dāi", ko: "멍하니 있다, 넋을 놓다", pos: "동사", ex: { zh: "她一个人坐着发呆。", pinyin: "Tā yí ge rén zuòzhe fādāi.", ko: "그녀는 혼자 앉아 멍하니 있다." } },
        { zh: "连同", pinyin: "lián tóng", ko: "~와 함께, ~와 더불어", pos: "개사", ex: { zh: "他连同家人一起搬走了。", pinyin: "Tā liántóng jiārén yìqǐ bānzǒu le.", ko: "그는 가족과 함께 이사를 갔다." } },
        { zh: "自卑", pinyin: "zì bēi", ko: "열등감을 느끼다", pos: "형용사", ex: { zh: "他因外貌感到自卑。", pinyin: "Tā yīn wàimào gǎndào zìbēi.", ko: "그는 외모 때문에 열등감을 느낀다." } },
        { zh: "夏令营", pinyin: "xià lìng yíng", ko: "여름 캠프", pos: "명사", ex: { zh: "孩子们参加了夏令营。", pinyin: "Háizimen cānjiā le xiàlìngyíng.", ko: "아이들은 여름 캠프에 참가했다." } },
        { zh: "圈套", pinyin: "quān tào", ko: "함정, 올가미", pos: "명사", ex: { zh: "他掉进了别人的圈套。", pinyin: "Tā diàojìn le biéren de quāntào.", ko: "그는 다른 사람의 함정에 빠졌다." } },
        { zh: "触犯", pinyin: "chù fàn", ko: "저촉되다, 위반하다", pos: "동사", ex: { zh: "他触犯了公司规定。", pinyin: "Tā chùfàn le gōngsī guīdìng.", ko: "그는 회사 규정을 위반했다." } },
        { zh: "干旱", pinyin: "gān hàn", ko: "가물다, 건조하다", pos: "형용사", ex: { zh: "今年这里非常干旱。", pinyin: "Jīnnián zhèlǐ fēicháng gānhàn.", ko: "올해 이곳은 매우 가물었다." } },
        { zh: "茫然", pinyin: "máng rán", ko: "망연하다, 막막하다", pos: "형용사", ex: { zh: "听到消息他一脸茫然。", pinyin: "Tīngdào xiāoxi tā yì liǎn mángrán.", ko: "소식을 듣고 그는 어리둥절한 표정을 지었다." } },
        { zh: "留恋", pinyin: "liú liàn", ko: "미련을 두다, 아쉬워하다, 그리워하다", pos: "동사", ex: { zh: "他对故乡的一草一木都充满留恋。", pinyin: "Tā duì gùxiāng de yī cǎo yī mù dōu chōngmǎn liúliàn.", ko: "그는 고향의 풀 한 포기 나무 한 그루에도 미련이 가득하다." } },
        { zh: "阻挠", pinyin: "zǔ náo", ko: "저지하다, 방해하다", pos: "동사", ex: { zh: "他们想尽办法阻挠这项计划的实施。", pinyin: "Tāmen xiǎngjìn bànfǎ zǔnáo zhè xiàng jìhuà de shíshī.", ko: "그들은 온갖 방법을 다해 이 계획의 실행을 저지하려 했다." } },
        { zh: "凝视", pinyin: "níng shì", ko: "응시하다, 주시하다", pos: "동사", ex: { zh: "她静静地凝视着远方的天空。", pinyin: "Tā jìngjìng de níngshìzhe yuǎnfāng de tiānkōng.", ko: "그녀는 조용히 먼 하늘을 응시하고 있었다." } },
        { zh: "无赖", pinyin: "wú lài", ko: "무뢰한, 건달, 불량배", pos: "명사", ex: { zh: "那个无赖经常在街上欺负别人。", pinyin: "Nàge wúlài jīngcháng zài jiē shàng qīfù biérén.", ko: "그 무뢰한은 자주 길거리에서 남을 괴롭힌다." } },
        { zh: "轻而易举", pinyin: "qīng ér yì jǔ", ko: "아주 쉽다, 식은 죽 먹기", pos: "관용구", ex: { zh: "这道题对他来说轻而易举。", pinyin: "Zhè dào tí duì tā lái shuō qīng ér yì jǔ.", ko: "이 문제는 그에게 식은 죽 먹기이다." } },
        { zh: "哦", pinyin: "ò", ko: "아, 오(깨달음을 나타내는 감탄)", pos: "감탄사", ex: { zh: "哦，原来你早就知道了。", pinyin: "Ò, yuánlái nǐ zǎo jiù zhīdào le.", ko: "아, 알고 보니 너 진작 알고 있었구나." } },
        { zh: "嗯", pinyin: "èn", ko: "응, 그래(동의·수긍)", pos: "감탄사", ex: { zh: "嗯，这个方法确实不错。", pinyin: "Èn, zhège fāngfǎ quèshí búcuò.", ko: "응, 이 방법 확실히 괜찮네." } },
        { zh: "枚", pinyin: "méi", ko: "개, 매(작은 물건을 세는 양사)", pos: "양사", ex: { zh: "他收藏了几枚珍贵的邮票。", pinyin: "Tā shōucáng le jǐ méi zhēnguì de yóupiào.", ko: "그는 진귀한 우표 몇 매를 소장하고 있다." } },
        { zh: "耍", pinyin: "shuǎ", ko: "놀다, 가지고 놀다", pos: "동사", ex: { zh: "孩子们在公园里尽情玩耍。", pinyin: "Háizimen zài gōngyuán lǐ jìnqíng wánshuǎ.", ko: "아이들이 공원에서 마음껏 놀고 있다." } },
        { zh: "坑", pinyin: "kēng", ko: "구덩이, 웅덩이", pos: "명사", ex: { zh: "路上有个大坑，小心别摔倒。", pinyin: "Lùshàng yǒu gè dà kēng, xiǎoxīn bié shuāidǎo.", ko: "길에 큰 구덩이가 있으니 넘어지지 않게 조심해." } },
        { zh: "咋", pinyin: "zǎ", ko: "어째서, 어떻게", pos: "대명사", ex: { zh: "你咋不早点告诉我这件事？", pinyin: "Nǐ zǎ bù zǎodiǎn gàosù wǒ zhè jiàn shì?", ko: "너 왜 이 일을 좀 더 일찍 말해주지 않았어?" } },
        { zh: "熬", pinyin: "áo", ko: "오래 끓이다, 밤새우다, 견디다", pos: "동사", ex: { zh: "他经常熬夜工作，身体很差。", pinyin: "Tā jīngcháng áoyè gōngzuò, shēntǐ hěn chà.", ko: "그는 자주 밤새워 일해서 건강이 아주 나쁘다." } },
        { zh: "捏", pinyin: "niē", ko: "집다, 꼬집다, 빚다", pos: "동사", ex: { zh: "她用手轻轻捏了捏那个面团。", pinyin: "Tā yòng shǒu qīngqīng niē le niē nàge miàntuán.", ko: "그녀는 손으로 그 밀가루 반죽을 살짝 주물렀다." } },
        { zh: "罐", pinyin: "guàn", ko: "항아리, 단지, 통", pos: "", ex: { zh: "桌上放着一个装满糖果的罐子。", pinyin: "Zhuō shàng fàngzhe yī gè zhuāngmǎn tángguǒ de guànzi.", ko: "탁자 위에 사탕이 가득 담긴 단지가 놓여 있다." } },
        { zh: "呵", pinyin: "hē", ko: "입김을 불다, 보살피다", pos: "조사", ex: { zh: "母亲无微不至地呵护着孩子。", pinyin: "Mǔqīn wúwēibùzhì de hēhù zhe háizi.", ko: "어머니는 세심하게 아이를 보살핀다." } },
        { zh: "幢", pinyin: "zhuàng", ko: "채, 동(건물을 세는 양사)", pos: "양사", ex: { zh: "那幢高楼是这座城市的地标。", pinyin: "Nà zhuàng gāolóu shì zhè zuò chéngshì de dìbiāo.", ko: "저 고층 건물은 이 도시의 랜드마크이다." } },
        { zh: "翘", pinyin: "qiào", ko: "위로 들리다, 치켜들다", pos: "동사", ex: { zh: "他得意地翘起了二郎腿。", pinyin: "Tā déyì de qiào qǐ le èrlángtuǐ.", ko: "그는 의기양양하게 다리를 꼬아 올렸다." } },
        { zh: "孔", pinyin: "kǒng", ko: "구멍", pos: "명사", ex: { zh: "这块木板上有一个小孔。", pinyin: "Zhè kuài mùbǎn shàng yǒu yī gè xiǎo kǒng.", ko: "이 나무판에는 작은 구멍이 하나 있다." } },
        { zh: "颇", pinyin: "pō", ko: "자못, 꽤, 상당히", pos: "부사", ex: { zh: "他对这个领域颇有研究。", pinyin: "Tā duì zhège lǐngyù pō yǒu yánjiū.", ko: "그는 이 분야에 대해 상당히 조예가 깊다." } },
        { zh: "溜", pinyin: "liū", ko: "미끄러지다, 몰래 빠져나가다", pos: "동사", ex: { zh: "他趁人不注意悄悄溜走了。", pinyin: "Tā chèn rén bù zhùyì qiāoqiāo liū zǒu le.", ko: "그는 남이 주의하지 않는 틈을 타 몰래 빠져나갔다." } },
        { zh: "拽", pinyin: "zhuài", ko: "잡아당기다, 끌다", pos: "동사", ex: { zh: "他用力拽住绳子往上爬。", pinyin: "Tā yònglì zhuài zhù shéngzi wǎng shàng pá.", ko: "그는 힘껏 밧줄을 잡아당기며 위로 기어올랐다." } },
        { zh: "兜", pinyin: "dōu", ko: "주머니, 한 바퀴 돌다", pos: "동사", ex: { zh: "周末他开车带我们去兜风。", pinyin: "Zhōumò tā kāichē dài wǒmen qù dōufēng.", ko: "주말에 그는 차를 몰아 우리를 데리고 드라이브를 갔다." } },
        { zh: "哄", pinyin: "hǒng", ko: "달래다, 어르다, 속이다", pos: "동사", ex: { zh: "妈妈耐心地哄孩子入睡。", pinyin: "Māma nàixīn de hǒng háizi rùshuì.", ko: "엄마가 참을성 있게 아이를 달래어 재운다." } },
        { zh: "愈", pinyin: "yù", ko: "더욱더 ~하다, 낫다", pos: "부사", ex: { zh: "天气愈来愈冷，要多穿衣服。", pinyin: "Tiānqì yù lái yù lěng, yào duō chuān yīfú.", ko: "날씨가 점점 더 추워지니 옷을 많이 입어야 한다." } },
        { zh: "翼", pinyin: "yì", ko: "날개", pos: "", ex: { zh: "飞机的机翼在阳光下闪闪发光。", pinyin: "Fēijī de jīyì zài yángguāng xià shǎnshǎn fāguāng.", ko: "비행기의 날개가 햇빛 아래 반짝반짝 빛난다." } },
        { zh: "盛", pinyin: "shèng", ko: "활짝 피다, 무성하다, 성대하다", pos: "동사", ex: { zh: "公园里的花朵盛开得格外美丽。", pinyin: "Gōngyuán lǐ de huāduǒ shèngkāi de géwài měilì.", ko: "공원의 꽃들이 유난히 아름답게 활짝 피었다." } },
        { zh: "淋", pinyin: "lín", ko: "끼얹다, (비에) 젖다", pos: "동사", ex: { zh: "昨天回家路上淋了一场大雨。", pinyin: "Zuótiān huíjiā lùshàng lín le yī chǎng dàyǔ.", ko: "어제 집에 오는 길에 소나기를 흠뻑 맞았다." } },
        { zh: "拧", pinyin: "nǐng", ko: "비틀다, 돌리다", pos: "동사", ex: { zh: "他费了很大劲才拧开瓶盖。", pinyin: "Tā fèi le hěn dà jìn cái nǐng kāi pínggài.", ko: "그는 큰 힘을 들여서야 병뚜껑을 비틀어 열었다." } },
        { zh: "溪", pinyin: "xī", ko: "시내, 개울", pos: "", ex: { zh: "清澈的溪水从山间缓缓流过。", pinyin: "Qīngchè de xīshuǐ cóng shānjiān huǎnhuǎn liúguò.", ko: "맑은 시냇물이 산골짜기를 천천히 흘러간다." } },
        { zh: "扛", pinyin: "káng", ko: "어깨에 메다, 짊어지다", pos: "동사", ex: { zh: "他一个人扛起了整个家的重担。", pinyin: "Tā yī gè rén káng qǐ le zhěnggè jiā de zhòngdàn.", ko: "그는 혼자서 온 집안의 무거운 짐을 짊어졌다." } },
        { zh: "劈", pinyin: "pī", ko: "쪼개다, 패다, 가르다", pos: "동사", ex: { zh: "他抡起斧头把木柴劈成两半。", pinyin: "Tā lūn qǐ fǔtóu bǎ mùchái pī chéng liǎng bàn.", ko: "그는 도끼를 휘둘러 장작을 반으로 쪼갰다." } },
        { zh: "扒", pinyin: "bā", ko: "헤치다, 벗기다, 붙잡다", pos: "동사", ex: { zh: "他扒开草丛寻找丢失的钥匙。", pinyin: "Tā bā kāi cǎocóng xúnzhǎo diūshī de yàoshi.", ko: "그는 풀숲을 헤치며 잃어버린 열쇠를 찾았다." } },
        { zh: "竖", pinyin: "shù", ko: "세우다, 곧추세우다, 세로의", pos: "동사", ex: { zh: "请把这块木板竖起来靠墙放。", pinyin: "Qǐng bǎ zhè kuài mùbǎn shù qǐlái kào qiáng fàng.", ko: "이 나무판을 세워서 벽에 기대어 놓아 주세요." } },
        { zh: "搂", pinyin: "lǒu", ko: "껴안다, 끌어안다", pos: "동사", ex: { zh: "母亲紧紧搂着熟睡的孩子。", pinyin: "Mǔqīn jǐnjǐn lǒu zhe shúshuì de háizi.", ko: "어머니가 곤히 잠든 아이를 꼭 끌어안고 있다." } },
        { zh: "磕", pinyin: "kē", ko: "부딪치다, (딱딱한 것에) 찧다", pos: "동사", ex: { zh: "他不小心磕破了膝盖。", pinyin: "Tā bù xiǎoxīn kē pò le xīgài.", ko: "그는 부주의하여 무릎을 부딪쳐 까졌다." } },
        { zh: "锤", pinyin: "chuí", ko: "망치, 쇠망치", pos: "", ex: { zh: "工人用锤子把钉子敲进木板。", pinyin: "Gōngrén yòng chuízi bǎ dīngzi qiāo jìn mùbǎn.", ko: "일꾼이 망치로 못을 나무판에 박아 넣었다." } },
        { zh: "攒", pinyin: "zǎn", ko: "모으다, 저축하다", pos: "동사", ex: { zh: "他省吃俭用攒下了一笔钱。", pinyin: "Tā shěngchī jiǎnyòng zǎn xià le yī bǐ qián.", ko: "그는 아끼고 아껴 목돈을 모았다." } },
        { zh: "秤", pinyin: "chèng", ko: "저울", pos: "명사", ex: { zh: "商贩用秤称了称水果的重量。", pinyin: "Shāngfàn yòng chèng chēng le chēng shuǐguǒ de zhòngliàng.", ko: "상인이 저울로 과일의 무게를 달아 보았다." } },
        { zh: "绣", pinyin: "xiù", ko: "수놓다, 자수", pos: "동사", ex: { zh: "奶奶在手绢上绣了一朵花。", pinyin: "Nǎinai zài shǒujuàn shàng xiù le yī duǒ huā.", ko: "할머니가 손수건에 꽃 한 송이를 수놓았다." } },
        { zh: "搁", pinyin: "gē", ko: "놓다, 두다, 방치하다", pos: "동사", ex: { zh: "他把书随手搁在了桌子上。", pinyin: "Tā bǎ shū suíshǒu gē zài le zhuōzi shàng.", ko: "그는 책을 아무렇게나 탁자 위에 놓아 두었다." } },
      ],
    },
  ],
};
