/**
 * H6 (HSK 6급) 보강 어휘 — 청크 C (200개).
 * HSK 2.0 6급 표준 목록 순증분(빈도순, 전 급 교차 중복 배제) — drkameleon/complete-hsk-vocabulary(MIT) 골격.
 * zh·pinyin·pos는 소스 그대로(다음자 단일 한자는 상용 독음으로 교정), ko·예문만 생성 후 결정적 전수 검증.
 */
const themes = {
  themes: [
    {
      name: "HSK6 보강 C",
      icon: "🟥",
      words: [
        { zh: "国防", pinyin: "guófáng", ko: "국방", pos: "명사", ex: { zh: "国防是国家安全的重要保障。", pinyin: "Guó fáng shì guójiā ānquán de zhòngyào bǎozhàng.", ko: "국방은 국가 안보의 중요한 보장이다." } },
        { zh: "着想", pinyin: "zhuóxiǎng", ko: "배려하다, 고려하다", pos: "동사", ex: { zh: "他做事总是为别人着想。", pinyin: "Tā zuòshì zǒngshì wèi biérén zhuóxiǎng.", ko: "그는 일을 할 때 늘 남을 배려한다." } },
        { zh: "颁发", pinyin: "bānfā", ko: "발급하다, 수여하다", pos: "동사", ex: { zh: "学校将向优秀学生颁发奖学金。", pinyin: "Xuéxiào jiāng xiàng yōuxiù xuésheng bānfā jiǎngxuéjīn.", ko: "학교는 우수한 학생에게 장학금을 수여할 것이다." } },
        { zh: "呼吁", pinyin: "hūyù", ko: "호소하다, 촉구하다", pos: "동사", ex: { zh: "政府呼吁市民节约用水。", pinyin: "Zhèngfǔ hūyù shìmín jiéyuē yòngshuǐ.", ko: "정부는 시민들에게 절수를 호소했다." } },
        { zh: "堕落", pinyin: "duòluò", ko: "타락하다", pos: "동사", ex: { zh: "他因交友不慎而逐渐堕落。", pinyin: "Tā yīn jiāoyǒu bùshèn ér zhújiàn duòluò.", ko: "그는 친구를 잘못 사귀어 점점 타락했다." } },
        { zh: "歹徒", pinyin: "dǎitú", ko: "악당, 범인", pos: "명사", ex: { zh: "警察终于抓住了那个歹徒。", pinyin: "Jǐngchá zhōngyú zhuāzhùle nàge dǎitú.", ko: "경찰이 마침내 그 악당을 붙잡았다." } },
        { zh: "野蛮", pinyin: "yěmán", ko: "야만적이다, 미개하다", pos: "형용사", ex: { zh: "这种野蛮的行为令人愤怒。", pinyin: "Zhè zhǒng yěmán de xíngwéi lìng rén fènnù.", ko: "이런 야만적인 행동은 사람을 분노하게 한다." } },
        { zh: "敞开", pinyin: "chǎngkāi", ko: "활짝 열다", pos: "동사", ex: { zh: "她把窗户敞开让空气流通。", pinyin: "Tā bǎ chuānghu chǎngkāi ràng kōngqì liútōng.", ko: "그녀는 창문을 활짝 열어 공기가 통하게 했다." } },
        { zh: "挪", pinyin: "nuó", ko: "옮기다, 이동하다", pos: "동사", ex: { zh: "请把桌子挪到旁边去。", pinyin: "Qǐng bǎ zhuōzi nuó dào pángbiān qù.", ko: "탁자를 옆으로 옮겨 주세요." } },
        { zh: "公关", pinyin: "gōngguān", ko: "홍보, 공공관계", pos: "명사", ex: { zh: "她在公司负责公关工作。", pinyin: "Tā zài gōngsī fùzé gōngguān gōngzuò.", ko: "그녀는 회사에서 홍보 업무를 담당한다." } },
        { zh: "信赖", pinyin: "xìnlài", ko: "신뢰하다", pos: "동사", ex: { zh: "员工们都很信赖这位经理。", pinyin: "Yuángōngmen dōu hěn xìnlài zhè wèi jīnglǐ.", ko: "직원들은 모두 이 매니저를 신뢰한다." } },
        { zh: "澄清", pinyin: "chéngqīng", ko: "명확히 하다, 해명하다", pos: "동사", ex: { zh: "他及时澄清了这个误会。", pinyin: "Tā jíshí chéngqīngle zhège wùhuì.", ko: "그는 즉시 이 오해를 해명했다." } },
        { zh: "大不了", pinyin: "dàbùliǎo", ko: "기껏해야, 대단한 것 아니다", pos: "동사", ex: { zh: "大不了从头再来一次。", pinyin: "Dàbuliǎo cóngtóu zài lái yīcì.", ko: "기껏해야 처음부터 다시 하면 된다." } },
        { zh: "境界", pinyin: "jìngjiè", ko: "경지, 영역", pos: "명사", ex: { zh: "他的书法已经达到了很高的境界。", pinyin: "Tā de shūfǎ yǐjīng dádàole hěn gāo de jìngjiè.", ko: "그의 서예는 이미 매우 높은 경지에 이르렀다." } },
        { zh: "生育", pinyin: "shēngyù", ko: "출산하다", pos: "동사", ex: { zh: "她计划明年生育第一个孩子。", pinyin: "Tā jìhuà míngnián shēngyù dì-yī gè háizi.", ko: "그녀는 내년에 첫 아이를 낳을 계획이다." } },
        { zh: "撤退", pinyin: "chètuì", ko: "철수하다, 후퇴하다", pos: "동사", ex: { zh: "军队接到命令后立即撤退。", pinyin: "Jūnduì jiēdào mìnglìng hòu lìjí chètuì.", ko: "군대는 명령을 받은 후 즉시 철수했다." } },
        { zh: "品尝", pinyin: "pǐncháng", ko: "맛보다, 시식하다", pos: "동사", ex: { zh: "游客们品尝了当地的特色小吃。", pinyin: "Yóukèmen pǐncháng le dāngdì de tèsè xiǎochī.", ko: "관광객들은 현지의 특색 있는 간식을 맛보았다." } },
        { zh: "粉碎", pinyin: "fěnsuì", ko: "분쇄하다, 산산이 부수다", pos: "동사", ex: { zh: "敌人的阴谋被彻底粉碎了。", pinyin: "Dírén de yīnmóu bèi chèdǐ fěnsuìle.", ko: "적의 음모는 철저히 분쇄되었다." } },
        { zh: "撒谎", pinyin: "sāhuǎng", ko: "거짓말하다", pos: "동사", ex: { zh: "小孩子不应该学会撒谎。", pinyin: "Xiǎoháizi bù yīnggāi xuéhuì sāhuǎng.", ko: "아이는 거짓말하는 법을 배워서는 안 된다." } },
        { zh: "忧郁", pinyin: "yōuyù", ko: "우울하다", pos: "형용사", ex: { zh: "她最近情绪十分忧郁。", pinyin: "Tā zuìjìn qíngxù shífēn yōuyù.", ko: "그녀는 요즘 기분이 매우 우울하다." } },
        { zh: "掀起", pinyin: "xiānqǐ", ko: "일으키다, 불러일으키다", pos: "동사", ex: { zh: "这部电影掀起了观影热潮。", pinyin: "Zhè bù diànyǐng xiānqǐle guānyǐng rècháo.", ko: "이 영화는 관람 열풍을 일으켰다." } },
        { zh: "界限", pinyin: "jièxiàn", ko: "경계, 한계", pos: "명사", ex: { zh: "两国之间的界限十分清楚。", pinyin: "Liǎng guó zhī jiān de jièxiàn shífēn qīngchu.", ko: "두 나라 사이의 경계는 매우 명확하다." } },
        { zh: "旋律", pinyin: "xuánlǜ", ko: "선율, 멜로디", pos: "명사", ex: { zh: "这首歌的旋律非常优美。", pinyin: "Zhè shǒu gē de xuánlǜ fēicháng yōuměi.", ko: "이 노래의 선율은 매우 아름답다." } },
        { zh: "固执", pinyin: "gùzhí", ko: "고집스럽다, 완고하다", pos: "형용사", ex: { zh: "老人的想法一向很固执。", pinyin: "Lǎorén de xiǎngfǎ yīxiàng hěn gùzhí.", ko: "노인의 생각은 늘 고집스럽다." } },
        { zh: "借助", pinyin: "jièzhù", ko: "힘을 빌리다, 도움을 받다", pos: "동사", ex: { zh: "他借助字典学习生词。", pinyin: "Tā jièzhù zìdiǎn xuéxí shēngcí.", ko: "그는 사전의 도움을 받아 새 단어를 공부한다." } },
        { zh: "一度", pinyin: "yīdù", ko: "한때, 한동안", pos: "부사", ex: { zh: "这里一度是繁华的商业区。", pinyin: "Zhèlǐ yīdù shì fánhuá de shāngyèqū.", ko: "이곳은 한때 번화한 상업지구였다." } },
        { zh: "侧面", pinyin: "cèmiàn", ko: "측면", pos: "명사", ex: { zh: "从侧面看这座建筑更漂亮。", pinyin: "Cóng cèmiàn kàn zhè zuò jiànzhù gèng piàoliang.", ko: "측면에서 보면 이 건물은 더 아름답다." } },
        { zh: "局部", pinyin: "júbù", ko: "국부, 일부분", pos: "명사", ex: { zh: "手术只需要局部麻醉。", pinyin: "Shǒushù zhǐ xūyào júbù mázuì.", ko: "수술은 국부 마취만 하면 된다." } },
        { zh: "渗透", pinyin: "shèntòu", ko: "침투하다, 스며들다", pos: "동사", ex: { zh: "雨水慢慢渗透到土壤里。", pinyin: "Yǔshuǐ mànmàn shèntòu dào tǔrǎng lǐ.", ko: "빗물이 서서히 토양 속으로 스며든다." } },
        { zh: "塌", pinyin: "tā", ko: "무너지다, 꺼지다", pos: "동사", ex: { zh: "老房子的屋顶突然塌了。", pinyin: "Lǎo fángzi de wūdǐng tūrán tāle.", ko: "낡은 집의 지붕이 갑자기 무너졌다." } },
        { zh: "打仗", pinyin: "dǎzhàng", ko: "전쟁하다, 싸우다", pos: "동사", ex: { zh: "士兵们在前线打仗。", pinyin: "Shìbīngmen zài qiánxiàn dǎzhàng.", ko: "병사들은 전선에서 전쟁을 치른다." } },
        { zh: "把手", pinyin: "bǎshǒu", ko: "손잡이", pos: "명사", ex: { zh: "这个门的把手已经坏了。", pinyin: "Zhège mén de bǎshou yǐjīng huàile.", ko: "이 문의 손잡이는 이미 고장 났다." } },
        { zh: "和解", pinyin: "héjiě", ko: "화해하다, 합의하다", pos: "동사", ex: { zh: "双方最终达成了和解。", pinyin: "Shuāngfāng zuìzhōng dáchéngle héjiě.", ko: "양측은 결국 화해에 이르렀다." } },
        { zh: "报社", pinyin: "bàoshè", ko: "신문사", pos: "명사", ex: { zh: "他大学毕业后进了报社工作。", pinyin: "Tā dàxué bìyè hòu jìnle bàoshè gōngzuò.", ko: "그는 대학 졸업 후 신문사에 들어가 일했다." } },
        { zh: "解散", pinyin: "jiěsàn", ko: "해산하다", pos: "동사", ex: { zh: "会议结束后队伍就解散了。", pinyin: "Huìyì jiéshù hòu duìwu jiù jiěsànle.", ko: "회의가 끝난 후 대오는 해산했다." } },
        { zh: "筹备", pinyin: "chóubèi", ko: "준비하다, 마련하다", pos: "동사", ex: { zh: "他们正在筹备结婚典礼。", pinyin: "Tāmen zhèngzài chóubèi jiéhūn diǎnlǐ.", ko: "그들은 결혼식을 준비하고 있다." } },
        { zh: "严密", pinyin: "yánmì", ko: "치밀하다, 엄밀하다", pos: "형용사", ex: { zh: "这套方案设计得非常严密。", pinyin: "Zhè tào fāng'àn shèjì de fēicháng yánmì.", ko: "이 방안은 매우 치밀하게 설계되었다." } },
        { zh: "排斥", pinyin: "páichì", ko: "배척하다, 배제하다", pos: "동사", ex: { zh: "大家都排斥这种落后的观念。", pinyin: "Dàjiā dōu páichì zhè zhǒng luòhòu de guānniàn.", ko: "모두가 이런 낙후된 관념을 배척한다." } },
        { zh: "报仇", pinyin: "bàochóu", ko: "복수하다", pos: "동사", ex: { zh: "他发誓要为父亲报仇。", pinyin: "Tā fāshì yào wèi fùqin bàochóu.", ko: "그는 아버지의 복수를 하겠다고 맹세했다." } },
        { zh: "收缩", pinyin: "shōusuō", ko: "수축하다, 축소하다", pos: "동사", ex: { zh: "天冷时金属会收缩。", pinyin: "Tiān lěng shí jīnshǔ huì shōusuō.", ko: "날씨가 추우면 금속은 수축한다." } },
        { zh: "抚养", pinyin: "fǔyǎng", ko: "부양하다, 양육하다", pos: "동사", ex: { zh: "她独自抚养两个孩子长大。", pinyin: "Tā dúzì fǔyǎng liǎng gè háizi zhǎngdà.", ko: "그녀는 혼자서 두 아이를 키웠다." } },
        { zh: "兼职", pinyin: "jiānzhí", ko: "겸직하다, 아르바이트하다", pos: "동사", ex: { zh: "他周末在餐厅兼职打工。", pinyin: "Tā zhōumò zài cāntīng jiānzhí dǎgōng.", ko: "그는 주말에 식당에서 아르바이트를 한다." } },
        { zh: "较量", pinyin: "jiàoliàng", ko: "겨루다, 승부를 겨루다", pos: "동사", ex: { zh: "两支球队将在决赛中较量。", pinyin: "Liǎng zhī qiúduì jiāng zài juésài zhōng jiàoliàng.", ko: "두 팀은 결승전에서 승부를 겨룰 것이다." } },
        { zh: "谣言", pinyin: "yáoyán", ko: "소문, 유언비어", pos: "명사", ex: { zh: "网上到处流传着谣言。", pinyin: "Wǎngshàng dàochù liúchuánzhe yáoyán.", ko: "인터넷에 곳곳에 소문이 퍼지고 있다." } },
        { zh: "探测", pinyin: "tàncè", ko: "탐지하다, 측정하다", pos: "동사", ex: { zh: "卫星可以探测地球的地形。", pinyin: "Wèixīng kěyǐ tàncè dìqiú de dìxíng.", ko: "위성은 지구의 지형을 탐지할 수 있다." } },
        { zh: "瘫痪", pinyin: "tānhuàn", ko: "마비되다", pos: "동사", ex: { zh: "交通因大雪几乎瘫痪。", pinyin: "Jiāotōng yīn dàxuě jīhū tānhuàn.", ko: "교통이 폭설로 거의 마비되었다." } },
        { zh: "大臣", pinyin: "dàchén", ko: "대신, 장관", pos: "명사", ex: { zh: "国王召见了几位大臣。", pinyin: "Guówáng zhàojiànle jǐ wèi dàchén.", ko: "국왕은 몇몇 대신을 불러들였다." } },
        { zh: "放射", pinyin: "fàngshè", ko: "방사하다, 방출하다", pos: "동사", ex: { zh: "太阳不断放射出光和热。", pinyin: "Tàiyáng bùduàn fàngshè chū guāng hé rè.", ko: "태양은 끊임없이 빛과 열을 방출한다." } },
        { zh: "容器", pinyin: "róngqì", ko: "용기, 그릇", pos: "명사", ex: { zh: "把液体倒进这个容器里。", pinyin: "Bǎ yètǐ dào jìn zhège róngqì lǐ.", ko: "액체를 이 용기 안에 부어라." } },
        { zh: "欣慰", pinyin: "xīnwèi", ko: "기쁘고 안심되다, 흐뭇하다", pos: "형용사", ex: { zh: "看到孩子成长他感到欣慰。", pinyin: "Kàndào háizi chéngzhǎng tā gǎndào xīnwèi.", ko: "아이가 성장하는 것을 보고 그는 흐뭇함을 느꼈다." } },
        { zh: "元首", pinyin: "yuánshǒu", ko: "원수, 국가 지도자", pos: "명사", ex: { zh: "两国元首举行了会谈。", pinyin: "Liǎng guó yuánshǒu jǔxíngle huìtán.", ko: "양국 원수가 회담을 진행했다." } },
        { zh: "苍白", pinyin: "cāngbái", ko: "창백하다", pos: "형용사", ex: { zh: "他的脸色显得十分苍白。", pinyin: "Tā de liǎnsè xiǎnde shífēn cāngbái.", ko: "그의 안색이 매우 창백해 보인다." } },
        { zh: "残留", pinyin: "cánliú", ko: "잔류하다, 남아 있다", pos: "동사", ex: { zh: "蔬菜上可能残留农药。", pinyin: "Shūcài shàng kěnéng cánliú nóngyào.", ko: "채소에는 농약이 잔류할 수 있다." } },
        { zh: "密度", pinyin: "mìdù", ko: "밀도", pos: "명사", ex: { zh: "这个城市的人口密度很高。", pinyin: "Zhège chéngshì de rénkǒu mìdù hěn gāo.", ko: "이 도시의 인구 밀도는 매우 높다." } },
        { zh: "向往", pinyin: "xiàngwǎng", ko: "동경하다, 갈망하다", pos: "동사", ex: { zh: "她一直向往自由的生活。", pinyin: "Tā yīzhí xiàngwǎng zìyóu de shēnghuó.", ko: "그녀는 늘 자유로운 삶을 동경했다." } },
        { zh: "音响", pinyin: "yīnxiǎng", ko: "음향, 오디오", pos: "명사", ex: { zh: "客厅里摆放着一套音响。", pinyin: "Kètīng lǐ bǎifàngzhe yī tào yīnxiǎng.", ko: "거실에는 오디오 세트가 놓여 있다." } },
        { zh: "钞票", pinyin: "chāopiào", ko: "지폐", pos: "명사", ex: { zh: "他从钱包里掏出一张钞票。", pinyin: "Tā cóng qiánbāo lǐ tāochū yī zhāng chāopiào.", ko: "그는 지갑에서 지폐 한 장을 꺼냈다." } },
        { zh: "徘徊", pinyin: "páihuái", ko: "배회하다, 망설이다", pos: "동사", ex: { zh: "他在街头徘徊了很久。", pinyin: "Tā zài jiētóu páihuáile hěn jiǔ.", ko: "그는 거리에서 오랫동안 배회했다." } },
        { zh: "迷惑", pinyin: "míhuo", ko: "헷갈리게 하다, 미혹시키다", pos: "동사", ex: { zh: "这些数据让人十分迷惑。", pinyin: "Zhèxiē shùjù ràng rén shífēn míhuo.", ko: "이 데이터들은 사람을 매우 헷갈리게 한다." } },
        { zh: "黎明", pinyin: "límíng", ko: "새벽, 여명", pos: "명사", ex: { zh: "我们黎明时分出发上路。", pinyin: "Wǒmen límíng shífēn chūfā shànglù.", ko: "우리는 새벽녘에 길을 떠났다." } },
        { zh: "琢磨", pinyin: "zhuómó", ko: "다듬다, 조탁하다", pos: "동사", ex: { zh: "匠人正在细心琢磨这块玉。", pinyin: "Jiàngrén zhèngzài xìxīn zhuómó zhè kuài yù.", ko: "장인이 이 옥을 정성껏 다듬고 있다." } },
        { zh: "表态", pinyin: "biǎotài", ko: "입장을 밝히다, 태도를 표명하다", pos: "동사", ex: { zh: "领导还没有对此事表态。", pinyin: "Lǐngdǎo hái méiyǒu duì cǐ shì biǎotài.", ko: "지도자는 아직 이 일에 대해 입장을 밝히지 않았다." } },
        { zh: "双胞胎", pinyin: "shuāngbāotāi", ko: "쌍둥이", pos: "명사", ex: { zh: "她生了一对双胞胎。", pinyin: "Tā shēngle yī duì shuāngbāotāi.", ko: "그녀는 쌍둥이를 낳았다." } },
        { zh: "殴打", pinyin: "ōudǎ", ko: "구타하다, 때리다", pos: "동사", ex: { zh: "他因殴打他人被逮捕。", pinyin: "Tā yīn ōudǎ tārén bèi dàibǔ.", ko: "그는 타인을 구타해 체포되었다." } },
        { zh: "领土", pinyin: "lǐngtǔ", ko: "영토", pos: "명사", ex: { zh: "这片土地是我国的领土。", pinyin: "Zhè piàn tǔdì shì wǒguó de lǐngtǔ.", ko: "이 땅은 우리나라의 영토이다." } },
        { zh: "反馈", pinyin: "fǎnkuì", ko: "피드백하다, 반응을 보이다", pos: "동사", ex: { zh: "请及时反馈使用意见。", pinyin: "Qǐng jíshí fǎnkuì shǐyòng yìjiàn.", ko: "사용 의견을 즉시 피드백해 주세요." } },
        { zh: "无能为力", pinyin: "wúnéng wéilì", ko: "무기력하다, 어찌할 도리가 없다", pos: "동사", ex: { zh: "面对这种情况他无能为力。", pinyin: "Miànduì zhè zhǒng qíngkuàng tā wúnéngwéilì.", ko: "이런 상황에 직면해 그는 어찌할 도리가 없었다." } },
        { zh: "比喻", pinyin: "bǐyù", ko: "비유", pos: "명사", ex: { zh: "老师用比喻解释这个概念。", pinyin: "Lǎoshī yòng bǐyù jiěshì zhège gàiniàn.", ko: "선생님은 비유를 사용해 이 개념을 설명했다." } },
        { zh: "跳跃", pinyin: "tiàoyuè", ko: "도약하다, 뛰어오르다", pos: "동사", ex: { zh: "运动员在场上不断跳跃。", pinyin: "Yùndòngyuán zài chǎng shàng bùduàn tiàoyuè.", ko: "선수는 경기장에서 계속 뛰어오른다." } },
        { zh: "挫折", pinyin: "cuòzhé", ko: "좌절, 시련", pos: "명사", ex: { zh: "人生难免会遇到挫折。", pinyin: "Rénshēng nánmiǎn huì yùdào cuòzhé.", ko: "인생에는 좌절을 겪는 것을 피하기 어렵다." } },
        { zh: "惯例", pinyin: "guànlì", ko: "관례, 관행", pos: "명사", ex: { zh: "按照惯例大家轮流发言。", pinyin: "Ànzhào guànlì dàjiā lúnliú fāyán.", ko: "관례에 따라 모두가 돌아가며 발언한다." } },
        { zh: "荒唐", pinyin: "huāngtáng", ko: "황당하다, 터무니없다", pos: "형용사", ex: { zh: "这个借口实在太荒唐了。", pinyin: "Zhège jièkǒu shízài tài huāngtángle.", ko: "이 핑계는 정말 너무 황당하다." } },
        { zh: "储蓄", pinyin: "chǔxù", ko: "저축하다", pos: "동사", ex: { zh: "他每月都储蓄一部分工资。", pinyin: "Tā měi yuè dōu chǔxù yī bùfen gōngzī.", ko: "그는 매달 월급의 일부를 저축한다." } },
        { zh: "必定", pinyin: "bìdìng", ko: "반드시, 틀림없이", pos: "부사", ex: { zh: "努力学习必定会有收获。", pinyin: "Nǔlì xuéxí bìdìng huì yǒu shōuhuò.", ko: "열심히 공부하면 반드시 성과가 있을 것이다." } },
        { zh: "弦", pinyin: "xián", ko: "현, 줄", pos: "명사", ex: { zh: "他轻轻拨动了吉他的弦。", pinyin: "Tā qīngqīng bōdòngle jítā de xián.", ko: "그는 가볍게 기타 줄을 튕겼다." } },
        { zh: "虚伪", pinyin: "xūwěi", ko: "위선적이다, 가식적이다", pos: "형용사", ex: { zh: "大家都讨厌他虚伪的态度。", pinyin: "Dàjiā dōu tǎoyàn tā xūwěi de tàidu.", ko: "모두가 그의 위선적인 태도를 싫어한다." } },
        { zh: "分泌", pinyin: "fēnmì", ko: "분비하다", pos: "동사", ex: { zh: "这种腺体能分泌激素。", pinyin: "Zhè zhǒng xiàntǐ néng fēnmì jīsù.", ko: "이 분비샘은 호르몬을 분비할 수 있다." } },
        { zh: "予以", pinyin: "yǔyǐ", ko: "주다, 부여하다", pos: "동사", ex: { zh: "对违规者将予以处罚。", pinyin: "Duì wéiguīzhě jiāng yǔyǐ chǔfá.", ko: "규정을 위반한 자에게는 처벌을 가할 것이다." } },
        { zh: "后代", pinyin: "hòudài", ko: "후대, 자손", pos: "명사", ex: { zh: "这片森林留给了后代。", pinyin: "Zhè piàn sēnlín liú gěile hòudài.", ko: "이 숲은 후대에게 남겨졌다." } },
        { zh: "扭转", pinyin: "niǔzhuǎn", ko: "뒤바꾸다, 전환시키다", pos: "동사", ex: { zh: "他们努力扭转了不利局面。", pinyin: "Tāmen nǔlì niǔzhuǎnle bùlì júmiàn.", ko: "그들은 노력하여 불리한 국면을 전환시켰다." } },
        { zh: "压制", pinyin: "yāzhì", ko: "억압하다, 억제하다", pos: "", ex: { zh: "政府不应压制民众的言论自由。", pinyin: "Zhèng fǔ bù yīng yā zhì mín zhòng de yán lùn zì yóu.", ko: "정부는 민중의 언론 자유를 억압해서는 안 된다." } },
        { zh: "窜", pinyin: "cuàn", ko: "달아나다, 도망치다", pos: "동사", ex: { zh: "歹徒作案后仓皇逃窜。", pinyin: "Dǎi tú zuò àn hòu cāng huáng táo cuàn.", ko: "범인은 범행 후 황급히 달아났다." } },
        { zh: "内涵", pinyin: "nèihán", ko: "내포된 의미, 함의", pos: "명사", ex: { zh: "这首诗蕴含着丰富的内涵。", pinyin: "Zhè shǒu shī yùn hán zhe fēng fù de nèi hán.", ko: "이 시는 풍부한 함의를 담고 있다." } },
        { zh: "起初", pinyin: "qǐchū", ko: "처음에는, 애초에", pos: "부사", ex: { zh: "起初我并不相信这个消息。", pinyin: "Qǐ chū wǒ bìng bù xiāng xìn zhè ge xiāo xi.", ko: "처음에 나는 이 소식을 믿지 않았다." } },
        { zh: "推翻", pinyin: "tuīfān", ko: "뒤엎다, 전복시키다", pos: "동사", ex: { zh: "起义军最终推翻了旧政权。", pinyin: "Qǐ yì jūn zuì zhōng tuī fān le jiù zhèng quán.", ko: "봉기군은 결국 낡은 정권을 전복시켰다." } },
        { zh: "弹性", pinyin: "tánxìng", ko: "탄력성, 유연성", pos: "명사", ex: { zh: "这种材料具有很好的弹性。", pinyin: "Zhè zhǒng cái liào jù yǒu hěn hǎo de tán xìng.", ko: "이 재료는 탄력성이 매우 좋다." } },
        { zh: "富裕", pinyin: "Fùyù", ko: "부유하다, 풍족하다", pos: "형용사", ex: { zh: "如今这个村子变得越来越富裕。", pinyin: "Rú jīn zhè ge cūn zi biàn de yuè lái yuè fù yù.", ko: "오늘날 이 마을은 점점 더 부유해지고 있다." } },
        { zh: "日益", pinyin: "rìyì", ko: "날로, 나날이", pos: "부사", ex: { zh: "城市的环境日益改善。", pinyin: "Chéng shì de huán jìng rì yì gǎi shàn.", ko: "도시의 환경이 날로 개선되고 있다." } },
        { zh: "光彩", pinyin: "guāngcǎi", ko: "빛나다, 영광스럽다", pos: "형용사", ex: { zh: "他觉得这样做很不光彩。", pinyin: "Tā jué de zhè yàng zuò hěn bù guāng cǎi.", ko: "그는 이렇게 하는 것이 매우 떳떳하지 못하다고 생각했다." } },
        { zh: "株", pinyin: "zhū", ko: "그루(나무를 세는 단위)", pos: "양사", ex: { zh: "院子里种着一株老槐树。", pinyin: "Yuàn zi lǐ zhòng zhe yī zhū lǎo huái shù.", ko: "마당에는 오래된 회화나무 한 그루가 심어져 있다." } },
        { zh: "冻结", pinyin: "dòngjié", ko: "얼다, 동결하다", pos: "동사", ex: { zh: "银行冻结了他的账户。", pinyin: "Yín háng dòng jié le tā de zhàng hù.", ko: "은행은 그의 계좌를 동결했다." } },
        { zh: "侦探", pinyin: "zhēntàn", ko: "탐정, 형사", pos: "명사", ex: { zh: "这部电影讲述了一个侦探破案的故事。", pinyin: "Zhè bù diàn yǐng jiǎng shù le yī gè zhēn tàn pò àn de gù shi.", ko: "이 영화는 한 탐정이 사건을 해결하는 이야기를 그린다." } },
        { zh: "丢人", pinyin: "diūrén", ko: "창피하다, 체면이 깎이다", pos: "형용사", ex: { zh: "考试作弊太丢人了。", pinyin: "Kǎo shì zuò bì tài diū rén le.", ko: "시험에서 부정행위를 하는 것은 너무 창피하다." } },
        { zh: "公务", pinyin: "gōngwù", ko: "공무, 공적인 업무", pos: "명사", ex: { zh: "他因公务出差去了北京。", pinyin: "Tā yīn gōng wù chū chāi qù le Běi jīng.", ko: "그는 공무로 출장을 가서 베이징에 갔다." } },
        { zh: "口音", pinyin: "kǒuyīn", ko: "말투, 사투리, 억양", pos: "명사", ex: { zh: "他说话带着浓重的口音。", pinyin: "Tā shuō huà dài zhe nóng zhòng de kǒu yīn.", ko: "그는 말할 때 억양이 강하다." } },
        { zh: "行列", pinyin: "hángliè", ko: "행렬, 대열", pos: "명사", ex: { zh: "他加入了志愿者的行列。", pinyin: "Tā jiā rù le zhì yuàn zhě de háng liè.", ko: "그는 자원봉사자 대열에 합류했다." } },
        { zh: "持久", pinyin: "chíjiǔ", ko: "지속적이다, 오래 지속되다", pos: "형용사", ex: { zh: "这种药效并不持久。", pinyin: "Zhè zhǒng yào xiào bìng bù chí jiǔ.", ko: "이 약의 효과는 오래 지속되지 않는다." } },
        { zh: "麻痹", pinyin: "mábì", ko: "마비되다, 무감각해지다", pos: "형용사", ex: { zh: "长期不动导致双腿麻痹。", pinyin: "Cháng qī bù dòng dǎo zhì shuāng tuǐ má bì.", ko: "오랫동안 움직이지 않아 두 다리가 마비되었다." } },
        { zh: "制裁", pinyin: "zhìcái", ko: "제재하다, 처벌하다", pos: "동사", ex: { zh: "国际社会对该国实行制裁。", pinyin: "Guó jì shè huì duì gāi guó shí xíng zhì cái.", ko: "국제 사회는 그 나라에 제재를 가했다." } },
        { zh: "绅士", pinyin: "shēnshì", ko: "신사", pos: "명사", ex: { zh: "他举止得体,像个绅士。", pinyin: "Tā jǔ zhǐ dé tǐ, xiàng gè shēn shì.", ko: "그는 행동이 예의 바르며 신사 같다." } },
        { zh: "不堪", pinyin: "bùkān", ko: "견딜 수 없다, ~하기 짝이 없다", pos: "동사", ex: { zh: "长途旅行让他疲惫不堪。", pinyin: "Cháng tú lǚ xíng ràng tā pí bèi bù kān.", ko: "장거리 여행으로 그는 몹시 피곤해졌다." } },
        { zh: "别扭", pinyin: "bièniu", ko: "어색하다, 거북하다", pos: "형용사", ex: { zh: "这句话听起来有点别扭。", pinyin: "Zhè jù huà tīng qǐ lái yǒu diǎn biè niu.", ko: "이 말은 좀 어색하게 들린다." } },
        { zh: "款式", pinyin: "kuǎnshì", ko: "스타일, 디자인", pos: "명사", ex: { zh: "这家店的衣服款式很新颖。", pinyin: "Zhè jiā diàn de yī fu kuǎn shì hěn xīn yǐng.", ko: "이 가게의 옷 디자인은 매우 참신하다." } },
        { zh: "揉", pinyin: "róu", ko: "주무르다, 비비다", pos: "동사", ex: { zh: "她轻轻揉着酸痛的肩膀。", pinyin: "Tā qīng qīng róu zhe suān tòng de jiān bǎng.", ko: "그녀는 아픈 어깨를 살살 주물렀다." } },
        { zh: "正经", pinyin: "zhèngjīng", ko: "정직하다, 반듯하다, 진지하다", pos: "형용사", ex: { zh: "他为人一向十分正经。", pinyin: "Tā wéi rén yī xiàng shí fēn zhèng jīng.", ko: "그는 사람됨이 항상 매우 진지하다." } },
        { zh: "盈利", pinyin: "yínglì", ko: "이윤을 내다, 수익을 얻다", pos: "동사", ex: { zh: "公司今年终于开始盈利。", pinyin: "Gōng sī jīn nián zhōng yú kāi shǐ yíng lì.", ko: "회사는 올해 마침내 이윤을 내기 시작했다." } },
        { zh: "确信", pinyin: "quèxìn", ko: "확신하다", pos: "동사", ex: { zh: "我确信他不会说谎。", pinyin: "Wǒ què xìn tā bù huì shuō huǎng.", ko: "나는 그가 거짓말을 하지 않을 것이라고 확신한다." } },
        { zh: "销毁", pinyin: "xiāohuǐ", ko: "소각하다, 폐기하다", pos: "동사", ex: { zh: "这些文件必须彻底销毁。", pinyin: "Zhè xiē wén jiàn bì xū chè dǐ xiāo huǐ.", ko: "이 서류들은 반드시 완전히 폐기해야 한다." } },
        { zh: "况且", pinyin: "kuàngqiě", ko: "게다가, 하물며", pos: "접속사", ex: { zh: "天已经晚了,况且外面还下着雨。", pinyin: "Tiān yǐ jīng wǎn le, kuàng qiě wài miàn hái xià zhe yǔ.", ko: "날도 이미 늦었고, 게다가 밖에는 비까지 내리고 있다." } },
        { zh: "忍耐", pinyin: "rěnnài", ko: "참다, 인내하다", pos: "동사", ex: { zh: "面对挑衅他一直在忍耐。", pinyin: "Miàn duì tiǎo xìn tā yī zhí zài rěn nài.", ko: "도발에 직면해서도 그는 계속 참고 있었다." } },
        { zh: "土壤", pinyin: "tǔrǎng", ko: "토양", pos: "명사", ex: { zh: "这里的土壤非常肥沃。", pinyin: "Zhè lǐ de tǔ rǎng fēi cháng féi wò.", ko: "이곳의 토양은 매우 비옥하다." } },
        { zh: "抵制", pinyin: "dǐzhì", ko: "저지하다, 배척하다, 보이콧하다", pos: "동사", ex: { zh: "消费者纷纷抵制假冒产品。", pinyin: "Xiāo fèi zhě fēn fēn dǐ zhì jiǎ mào chǎn pǐn.", ko: "소비자들은 앞다투어 가짜 제품을 배척했다." } },
        { zh: "贪婪", pinyin: "tānlán", ko: "탐욕스럽다, 욕심 많다", pos: "형용사", ex: { zh: "他对金钱十分贪婪。", pinyin: "Tā duì jīn qián shí fēn tān lán.", ko: "그는 돈에 매우 탐욕스럽다." } },
        { zh: "学历", pinyin: "xuélì", ko: "학력", pos: "명사", ex: { zh: "这份工作对学历要求很高。", pinyin: "Zhè fèn gōng zuò duì xué lì yāo qiú hěn gāo.", ko: "이 일자리는 학력 요구 수준이 매우 높다." } },
        { zh: "得罪", pinyin: "dézuì", ko: "죄를 짓다, 법을 어기다, 실례합니다", pos: "동사", ex: { zh: "得罪了,请让我先过去。", pinyin: "Dé zuì le, qǐng ràng wǒ xiān guò qù.", ko: "실례합니다, 제가 먼저 지나가겠습니다." } },
        { zh: "保重", pinyin: "bǎozhòng", ko: "몸조심하다, 건강을 돌보다", pos: "동사", ex: { zh: "天冷了,请多保重身体。", pinyin: "Tiān lěng le, qǐng duō bǎo zhòng shēn tǐ.", ko: "날씨가 추워졌으니 건강 잘 챙기세요." } },
        { zh: "奢侈", pinyin: "shēchǐ", ko: "사치스럽다, 호화롭다", pos: "형용사", ex: { zh: "他过着极其奢侈的生活。", pinyin: "Tā guò zhe jí qí shē chǐ de shēng huó.", ko: "그는 매우 사치스러운 생활을 하고 있다." } },
        { zh: "巷", pinyin: "xiàng", ko: "골목, 좁은 길", pos: "", ex: { zh: "他住在一条小巷里。", pinyin: "Tā zhù zài yī tiáo xiǎo xiàng lǐ.", ko: "그는 작은 골목에 살고 있다." } },
        { zh: "当面", pinyin: "dāngmiàn", ko: "직접 얼굴을 보고, 면전에서", pos: "부사", ex: { zh: "有意见你应该当面提出来。", pinyin: "Yǒu yì jiàn nǐ yīng gāi dāng miàn tí chū lái.", ko: "의견이 있으면 직접 얼굴을 보고 말해야 한다." } },
        { zh: "倾斜", pinyin: "qīngxié", ko: "기울다, 경사지다", pos: "동사", ex: { zh: "这座塔身微微倾斜。", pinyin: "Zhè zuò tǎ shēn wēi wēi qīng xié.", ko: "이 탑은 몸체가 약간 기울어져 있다." } },
        { zh: "事迹", pinyin: "shìjì", ko: "행적, 업적, 사적", pos: "명사", ex: { zh: "他的英雄事迹广为流传。", pinyin: "Tā de yīng xióng shì jì guǎng wéi liú chuán.", ko: "그의 영웅적인 업적은 널리 전해졌다." } },
        { zh: "物资", pinyin: "wùzī", ko: "물자", pos: "명사", ex: { zh: "救灾物资已经送到灾区。", pinyin: "Jiù zāi wù zī yǐ jīng sòng dào zāi qū.", ko: "구호 물자가 이미 재해 지역에 도착했다." } },
        { zh: "犹如", pinyin: "yóurú", ko: "마치 ~와 같다", pos: "동사", ex: { zh: "夜空中的星星犹如钻石。", pinyin: "Yè kōng zhōng de xīng xing yóu rú zuàn shí.", ko: "밤하늘의 별들은 마치 다이아몬드 같다." } },
        { zh: "迄今为止", pinyin: "qìjīn wéizhǐ", ko: "지금까지, 오늘날까지", pos: "관용구", ex: { zh: "迄今为止还没有人解开这个谜。", pinyin: "Qì jīn wéi zhǐ hái méi yǒu rén jiě kāi zhè ge mí.", ko: "지금까지 아무도 이 수수께끼를 풀지 못했다." } },
        { zh: "支柱", pinyin: "zhīzhù", ko: "지주, 기둥, 버팀목", pos: "명사", ex: { zh: "旅游业是当地经济的支柱。", pinyin: "Lǚ yóu yè shì dāng dì jīng jì de zhī zhù.", ko: "관광업은 이 지역 경제의 버팀목이다." } },
        { zh: "饥饿", pinyin: "jīè", ko: "굶주림, 배고픔", pos: "명사", ex: { zh: "很多难民正忍受着饥饿。", pinyin: "Hěn duō nàn mín zhèng rěn shòu zhe jī è.", ko: "많은 난민들이 굶주림을 견디고 있다." } },
        { zh: "空虚", pinyin: "kōngxū", ko: "공허하다, 허전하다", pos: "형용사", ex: { zh: "他退休后感到内心空虚。", pinyin: "Tā tuì xiū hòu gǎn dào nèi xīn kōng xū.", ko: "그는 은퇴 후 마음이 공허함을 느꼈다." } },
        { zh: "喇叭", pinyin: "lǎba", ko: "나팔, 스피커, 확성기", pos: "명사", ex: { zh: "汽车喇叭突然响了起来。", pinyin: "Qì chē lǎ ba tū rán xiǎng le qǐ lai.", ko: "자동차 경적이 갑자기 울리기 시작했다." } },
        { zh: "实质", pinyin: "shízhì", ko: "실질, 본질", pos: "명사", ex: { zh: "我们要看清问题的实质。", pinyin: "Wǒ men yào kàn qīng wèn tí de shí zhì.", ko: "우리는 문제의 본질을 명확히 봐야 한다." } },
        { zh: "人为", pinyin: "rénwéi", ko: "인위적이다, 인공적이다", pos: "형용사", ex: { zh: "这场事故是人为造成的。", pinyin: "Zhè chǎng shì gù shì rén wéi zào chéng de.", ko: "이 사고는 인위적으로 초래된 것이다." } },
        { zh: "计较", pinyin: "jìjiào", ko: "따지다, 계산하다, 시비를 가리다", pos: "동사", ex: { zh: "他从不计较个人得失。", pinyin: "Tā cóng bù jì jiào gè rén dé shī.", ko: "그는 개인적인 득실을 따지지 않는다." } },
        { zh: "贩卖", pinyin: "fànmài", ko: "판매하다, 팔다", pos: "동사", ex: { zh: "严禁贩卖假冒伪劣商品。", pinyin: "Yán jìn fàn mài jiǎ mào wěi liè shāng pǐn.", ko: "가짜 불량 상품 판매를 엄격히 금지한다." } },
        { zh: "耀眼", pinyin: "yàoyǎn", ko: "눈부시다, 찬란하다", pos: "형용사", ex: { zh: "阳光照在雪地上十分耀眼。", pinyin: "Yáng guāng zhào zài xuě dì shàng shí fēn yào yǎn.", ko: "햇빛이 눈 쌓인 땅에 비쳐 매우 눈부시다." } },
        { zh: "慢性", pinyin: "mànxìng", ko: "만성적인", pos: "형용사", ex: { zh: "他常年患有慢性胃病。", pinyin: "Tā cháng nián huàn yǒu màn xìng wèi bìng.", ko: "그는 오랫동안 만성 위장병을 앓고 있다." } },
        { zh: "平面", pinyin: "píngmiàn", ko: "평면", pos: "명사", ex: { zh: "这幅画运用了平面设计。", pinyin: "Zhè fú huà yùn yòng le píng miàn shè jì.", ko: "이 그림은 평면 디자인을 활용했다." } },
        { zh: "包袱", pinyin: "bāofu", ko: "보따리, 부담", pos: "명사", ex: { zh: "别把这件事当成包袱。", pinyin: "Bié bǎ zhè jiàn shì dāng chéng bāo fu.", ko: "이 일을 부담으로 여기지 마세요." } },
        { zh: "要点", pinyin: "yàodiǎn", ko: "요점, 핵심", pos: "명사", ex: { zh: "请你概括一下报告的要点。", pinyin: "Qǐng nǐ gài kuò yī xià bào gào de yào diǎn.", ko: "보고서의 요점을 간략히 정리해 주세요." } },
        { zh: "发财", pinyin: "fācái", ko: "부자가 되다, 돈을 벌다", pos: "동사", ex: { zh: "他做生意后发财了。", pinyin: "Tā zuò shēng yi hòu fā cái le.", ko: "그는 사업을 시작한 후 부자가 되었다." } },
        { zh: "往常", pinyin: "wǎngcháng", ko: "평소, 예전", pos: "명사", ex: { zh: "今天他比往常来得早。", pinyin: "Jīn tiān tā bǐ wǎng cháng lái de zǎo.", ko: "오늘 그는 평소보다 일찍 왔다." } },
        { zh: "隐蔽", pinyin: "yǐnbì", ko: "은폐하다, 가려지다, 은밀하다", pos: "형용사", ex: { zh: "敌人躲在隐蔽的角落里。", pinyin: "Dí rén duǒ zài yǐn bì de jiǎo luò lǐ.", ko: "적은 은밀한 구석에 숨어 있었다." } },
        { zh: "救济", pinyin: "jiùjì", ko: "구제, 구호", pos: "명사", ex: { zh: "政府向灾民发放救济金。", pinyin: "Zhèng fǔ xiàng zāi mín fā fàng jiù jì jīn.", ko: "정부는 이재민에게 구호금을 지급했다." } },
        { zh: "分辨", pinyin: "fēnbiàn", ko: "분별하다, 구별하다", pos: "동사", ex: { zh: "我很难分辨这对双胞胎。", pinyin: "Wǒ hěn nán fēn biàn zhè duì shuāng bāo tāi.", ko: "나는 이 쌍둥이를 구별하기 어렵다." } },
        { zh: "描绘", pinyin: "miáohuì", ko: "묘사하다, 그려내다", pos: "동사", ex: { zh: "作者生动地描绘了春天的景色。", pinyin: "Zuò zhě shēng dòng de miáo huì le chūn tiān de jǐng sè.", ko: "작가는 봄의 풍경을 생생하게 묘사했다." } },
        { zh: "赞扬", pinyin: "zànyáng", ko: "칭찬하다, 찬양하다", pos: "동사", ex: { zh: "老师赞扬了他的勇敢行为。", pinyin: "Lǎo shī zàn yáng le tā de yǒng gǎn xíng wéi.", ko: "선생님은 그의 용감한 행동을 칭찬했다." } },
        { zh: "派遣", pinyin: "pàiqiǎn", ko: "파견하다", pos: "동사", ex: { zh: "公司派遣他去国外工作。", pinyin: "Gōng sī pài qiǎn tā qù guó wài gōng zuò.", ko: "회사는 그를 해외로 파견하여 일하게 했다." } },
        { zh: "一如既往", pinyin: "yīrú jìwǎng", ko: "변함없이, 예전과 다름없이", pos: "동사", ex: { zh: "他对工作一如既往地认真。", pinyin: "Tā duì gōng zuò yī rú jì wǎng de rèn zhēn.", ko: "그는 일에 대해 변함없이 성실하다." } },
        { zh: "安宁", pinyin: "Ānníng", ko: "평온하다, 안녕하다", pos: "형용사", ex: { zh: "这里的生活十分安宁。", pinyin: "Zhè lǐ de shēng huó shí fēn ān níng.", ko: "이곳의 생활은 매우 평온하다." } },
        { zh: "归还", pinyin: "guīhuán", ko: "돌려주다, 반환하다", pos: "동사", ex: { zh: "请按时归还借来的书。", pinyin: "Qǐng àn shí guī huán jiè lái de shū.", ko: "빌린 책은 제때 반납해 주세요." } },
        { zh: "捕捉", pinyin: "bǔzhuō", ko: "포착하다, 잡다", pos: "동사", ex: { zh: "摄影师捕捉到了精彩瞬间。", pinyin: "Shè yǐng shī bǔ zhuō dào le jīng cǎi shùn jiān.", ko: "사진작가는 멋진 순간을 포착했다." } },
        { zh: "气势", pinyin: "qìshì", ko: "기세, 위세", pos: "명사", ex: { zh: "这支球队气势如虹。", pinyin: "Zhè zhī qiú duì qì shì rú hóng.", ko: "이 팀은 기세가 대단하다." } },
        { zh: "事项", pinyin: "shìxiàng", ko: "사항", pos: "명사", ex: { zh: "请仔细阅读注意事项。", pinyin: "Qǐng zǐ xì yuè dú zhù yì shì xiàng.", ko: "주의 사항을 자세히 읽어 주세요." } },
        { zh: "慎重", pinyin: "shènzhòng", ko: "신중하다", pos: "형용사", ex: { zh: "这个决定要慎重考虑。", pinyin: "Zhè ge jué dìng yào shèn zhòng kǎo lǜ.", ko: "이 결정은 신중하게 고려해야 한다." } },
        { zh: "航天", pinyin: "hángtiān", ko: "우주 비행, 항공 우주", pos: "명사", ex: { zh: "中国的航天技术发展迅速。", pinyin: "Zhōng guó de háng tiān jì shù fā zhǎn xùn sù.", ko: "중국의 우주 항공 기술은 빠르게 발전하고 있다." } },
        { zh: "棕色", pinyin: "zōngsè", ko: "갈색", pos: "명사", ex: { zh: "她穿了一件棕色的外套。", pinyin: "Tā chuān le yī jiàn zōng sè de wài tào.", ko: "그녀는 갈색 외투를 입었다." } },
        { zh: "孤立", pinyin: "gūlì", ko: "고립되다, 고립시키다", pos: "동사", ex: { zh: "他在班里被同学孤立了。", pinyin: "Tā zài bān lǐ bèi tóng xué gū lì le.", ko: "그는 반에서 친구들에게 고립당했다." } },
        { zh: "器材", pinyin: "qìcái", ko: "기자재, 장비", pos: "명사", ex: { zh: "学校添置了新的体育器材。", pinyin: "Xué xiào tiān zhì le xīn de tǐ yù qì cái.", ko: "학교는 새로운 체육 기자재를 구입했다." } },
        { zh: "航行", pinyin: "hángxíng", ko: "항해하다, 운항하다", pos: "동사", ex: { zh: "这艘船正在大海上航行。", pinyin: "Zhè sōu chuán zhèng zài dà hǎi shàng háng xíng.", ko: "이 배는 지금 바다 위를 항해하고 있다." } },
        { zh: "起草", pinyin: "qǐcǎo", ko: "초안을 작성하다, 기초하다", pos: "동사", ex: { zh: "律师负责起草这份合同。", pinyin: "Lǜ shī fù zé qǐ cǎo zhè fèn hé tong.", ko: "변호사는 이 계약서의 초안 작성을 맡았다." } },
        { zh: "麻木", pinyin: "mámù", ko: "마비되다, 무감각하다", pos: "형용사", ex: { zh: "长时间坐着让他的腿麻木了。", pinyin: "Cháng shí jiān zuò zhe ràng tā de tuǐ má mù le.", ko: "오랫동안 앉아 있어서 그의 다리가 마비되었다." } },
        { zh: "反感", pinyin: "fǎngǎn", ko: "반감을 가지다, 거부감을 느끼다", pos: "동사", ex: { zh: "他的态度让人很反感。", pinyin: "Tā de tài du ràng rén hěn fǎn gǎn.", ko: "그의 태도는 사람들에게 반감을 준다." } },
        { zh: "方位", pinyin: "fāngwèi", ko: "방위, 방향", pos: "명사", ex: { zh: "他仔细辨认了周围的方位。", pinyin: "Tā zǐxì biànrèn le zhōuwéi de fāngwèi.", ko: "그는 주위의 방위를 신중하게 확인했다." } },
        { zh: "当心", pinyin: "dāngxīn", ko: "조심하다, 주의하다", pos: "동사", ex: { zh: "过马路时一定要当心车辆。", pinyin: "Guò mǎlù shí yídìng yào dāngxīn chēliàng.", ko: "길을 건널 때는 반드시 차량을 조심해야 한다." } },
        { zh: "衰老", pinyin: "shuāilǎo", ko: "노쇠하다, 늙다", pos: "형용사", ex: { zh: "随着年龄增长，身体逐渐衰老。", pinyin: "Suízhe niánlíng zēngzhǎng, shēntǐ zhújiàn shuāilǎo.", ko: "나이가 들면서 몸이 점점 노쇠해진다." } },
        { zh: "轰动", pinyin: "hōngdòng", ko: "센세이션을 일으키다, 큰 반향을 일으키다", pos: "동사", ex: { zh: "这条消息轰动了整个城市。", pinyin: "Zhè tiáo xiāoxi hōngdòng le zhěnggè chéngshì.", ko: "이 소식은 도시 전체에 큰 반향을 일으켰다." } },
        { zh: "筛选", pinyin: "shāixuǎn", ko: "선별하다, 걸러내다", pos: "동사", ex: { zh: "公司从简历中筛选出优秀人才。", pinyin: "Gōngsī cóng jiǎnlì zhōng shāixuǎn chū yōuxiù réncái.", ko: "회사는 이력서 중에서 우수한 인재를 선별해냈다." } },
        { zh: "猛烈", pinyin: "měngliè", ko: "맹렬하다, 격렬하다", pos: "형용사", ex: { zh: "台风带来了猛烈的暴雨。", pinyin: "Táifēng dàilái le měngliè de bàoyǔ.", ko: "태풍이 맹렬한 폭우를 몰고 왔다." } },
        { zh: "手势", pinyin: "shǒushì", ko: "손짓, 제스처", pos: "명사", ex: { zh: "他打了个手势示意我过去。", pinyin: "Tā dǎ le gè shǒushì shìyì wǒ guòqù.", ko: "그는 손짓으로 나에게 오라는 신호를 보냈다." } },
        { zh: "示威", pinyin: "shìwēi", ko: "시위하다, 데모하다", pos: "동사", ex: { zh: "大批市民走上街头示威。", pinyin: "Dàpī shìmín zǒushàng jiētóu shìwēi.", ko: "많은 시민들이 거리로 나와 시위했다." } },
        { zh: "重心", pinyin: "zhòngxīn", ko: "중심, 무게중심", pos: "명사", ex: { zh: "公司把工作重心转移到海外市场。", pinyin: "Gōngsī bǎ gōngzuò zhòngxīn zhuǎnyí dào hǎiwài shìchǎng.", ko: "회사는 업무의 중심을 해외 시장으로 옮겼다." } },
        { zh: "慷慨", pinyin: "kāngkǎi", ko: "관대하다, 후하다", pos: "형용사", ex: { zh: "他慷慨地捐出了全部积蓄。", pinyin: "Tā kāngkǎi de juān chū le quánbù jīxù.", ko: "그는 아낌없이 전 재산을 기부했다." } },
        { zh: "逢", pinyin: "féng", ko: "만나다, 마주치다", pos: "동사", ex: { zh: "每逢周末，公园里都挤满了人。", pinyin: "Měi féng zhōumò, gōngyuán lǐ dōu jǐmǎn le rén.", ko: "주말마다 공원은 사람들로 가득 찬다." } },
        { zh: "对策", pinyin: "duìcè", ko: "대책, 대응책", pos: "명사", ex: { zh: "政府正在研究应对通货膨胀的对策。", pinyin: "Zhèngfǔ zhèngzài yánjiū yìngduì tōnghuò péngzhàng de duìcè.", ko: "정부는 인플레이션에 대응할 대책을 연구하고 있다." } },
        { zh: "扰乱", pinyin: "rǎoluàn", ko: "어지럽히다, 교란하다", pos: "동사", ex: { zh: "噪音扰乱了居民的正常生活。", pinyin: "Zàoyīn rǎoluàn le jūmín de zhèngcháng shēnghuó.", ko: "소음이 주민들의 정상적인 생활을 어지럽혔다." } },
        { zh: "启示", pinyin: "qǐshì", ko: "깨우침, 시사점", pos: "동사", ex: { zh: "这个故事给了我们深刻的启示。", pinyin: "Zhège gùshi gěi le wǒmen shēnkè de qǐshì.", ko: "이 이야기는 우리에게 깊은 깨우침을 주었다." } },
        { zh: "阵地", pinyin: "zhèndì", ko: "진지, 거점", pos: "명사", ex: { zh: "士兵们坚守着自己的阵地。", pinyin: "Shìbīngmen jiānshǒu zhe zìjǐ de zhèndì.", ko: "병사들은 자신의 진지를 굳게 지켰다." } },
        { zh: "溅", pinyin: "jiàn", ko: "튀다, 튀기다", pos: "동사", ex: { zh: "汽车驶过水坑，溅了他一身水。", pinyin: "Qìchē shǐguò shuǐkēng, jiàn le tā yìshēn shuǐ.", ko: "자동차가 물웅덩이를 지나가며 그에게 물을 튀겼다." } },
        { zh: "资深", pinyin: "zīshēn", ko: "경력이 많은, 베테랑의", pos: "형용사", ex: { zh: "他是这家公司的资深工程师。", pinyin: "Tā shì zhè jiā gōngsī de zīshēn gōngchéngshī.", ko: "그는 이 회사의 베테랑 엔지니어이다." } },
        { zh: "密封", pinyin: "mìfēng", ko: "밀봉하다, 밀폐하다", pos: "동사", ex: { zh: "请把这些文件密封好再寄出。", pinyin: "Qǐng bǎ zhèxiē wénjiàn mìfēng hǎo zài jìchū.", ko: "이 서류들을 밀봉한 후 발송해 주세요." } },
        { zh: "高明", pinyin: "Gāomíng", ko: "뛰어나다, 훌륭하다", pos: "형용사", ex: { zh: "老师的解题方法十分高明。", pinyin: "Lǎoshī de jiětí fāngfǎ shífēn gāomíng.", ko: "선생님의 문제 풀이 방법이 매우 뛰어나다." } },
        { zh: "疤", pinyin: "bā", ko: "흉터, 상처 자국", pos: "명사", ex: { zh: "他手臂上留下了一道疤。", pinyin: "Tā shǒubì shàng liú xià le yí dào bā.", ko: "그의 팔에는 흉터가 하나 남아 있다." } },
        { zh: "叼", pinyin: "diāo", ko: "입에 물다", pos: "동사", ex: { zh: "小狗叼着一根骨头跑开了。", pinyin: "Xiǎogǒu diāo zhe yì gēn gǔtou pǎo kāi le.", ko: "강아지가 뼈다귀를 입에 물고 뛰어갔다." } },
        { zh: "堵塞", pinyin: "dǔsè", ko: "막히다, 정체되다", pos: "동사", ex: { zh: "交通堵塞让他迟到了半小时。", pinyin: "Jiāotōng dǔsè ràng tā chídào le bàn xiǎoshí.", ko: "교통 정체로 그는 30분 늦었다." } },
        { zh: "分明", pinyin: "fēnmíng", ko: "분명하다, 뚜렷하다", pos: "형용사", ex: { zh: "这张照片黑白分明，非常清晰。", pinyin: "Zhè zhāng zhàopiàn hēibái fēnmíng, fēicháng qīngxī.", ko: "이 사진은 흑백이 분명해서 매우 선명하다." } },
        { zh: "剧烈", pinyin: "jùliè", ko: "격렬하다, 극심하다", pos: "형용사", ex: { zh: "剧烈运动后要注意补充水分。", pinyin: "Jùliè yùndòng hòu yào zhùyì bǔchōng shuǐfèn.", ko: "격렬한 운동 후에는 수분 보충에 신경 써야 한다." } },
        { zh: "起伏", pinyin: "qǐfú", ko: "기복, 오르내리다", pos: "동사", ex: { zh: "他的情绪总是起伏不定。", pinyin: "Tā de qíngxù zǒngshì qǐfú búdìng.", ko: "그의 감정은 항상 기복이 심하다." } },
        { zh: "否决", pinyin: "fǒujué", ko: "부결하다, 거부하다", pos: "동사", ex: { zh: "这项提案被大会否决了。", pinyin: "Zhè xiàng tí'àn bèi dàhuì fǒujué le.", ko: "이 제안은 총회에서 부결되었다." } },
        { zh: "挑衅", pinyin: "tiǎoxìn", ko: "도발하다, 시비를 걸다", pos: "동사", ex: { zh: "他故意挑衅，想引起冲突。", pinyin: "Tā gùyì tiǎoxìn, xiǎng yǐnqǐ chōngtū.", ko: "그는 일부러 도발해서 충돌을 일으키려 했다." } },
        { zh: "功劳", pinyin: "gōngláo", ko: "공로, 공적", pos: "명사", ex: { zh: "这次成功离不开大家的功劳。", pinyin: "Zhè cì chénggōng líbukāi dàjiā de gōngláo.", ko: "이번 성공은 모두의 공로 덕분이다." } },
        { zh: "演变", pinyin: "yǎnbiàn", ko: "변화하다, 변천하다", pos: "동사", ex: { zh: "语言在长期使用中不断演变。", pinyin: "Yǔyán zài chángqī shǐyòng zhōng búduàn yǎnbiàn.", ko: "언어는 오랜 사용 속에서 끊임없이 변천한다." } },
        { zh: "精华", pinyin: "jīnghuá", ko: "정수, 알짜", pos: "명사", ex: { zh: "这本书汇集了作者一生的精华。", pinyin: "Zhè běn shū huìjí le zuòzhě yìshēng de jīnghuá.", ko: "이 책은 작가 일생의 정수를 모은 것이다." } },
        { zh: "反射", pinyin: "fǎnshè", ko: "반사하다, 반사", pos: "동사", ex: { zh: "湖面反射着夕阳的余晖。", pinyin: "Húmiàn fǎnshè zhe xīyáng de yúhuī.", ko: "호수 수면이 석양의 빛을 반사하고 있다." } },
        { zh: "缺席", pinyin: "quēxí", ko: "결석하다, 불참하다", pos: "동사", ex: { zh: "他因病缺席了今天的会议。", pinyin: "Tā yīn bìng quēxí le jīntiān de huìyì.", ko: "그는 병으로 오늘 회의에 결석했다." } },
        { zh: "标本", pinyin: "biāoběn", ko: "표본, 견본", pos: "명사", ex: { zh: "实验室里摆放着各种动物标本。", pinyin: "Shíyànshì lǐ bǎifàng zhe gèzhǒng dòngwù biāoběn.", ko: "실험실에는 다양한 동물 표본이 진열되어 있다." } },
        { zh: "皱纹", pinyin: "zhòuwén", ko: "주름", pos: "명사", ex: { zh: "岁月在她脸上留下了皱纹。", pinyin: "Suìyuè zài tā liǎn shàng liú xià le zhòuwén.", ko: "세월이 그녀의 얼굴에 주름을 남겼다." } },
        { zh: "机动", pinyin: "jīdòng", ko: "기동성 있는, 융통성 있는", pos: "형용사", ex: { zh: "我们需要制定一个机动方案。", pinyin: "Wǒmen xūyào zhìdìng yí gè jīdòng fāng'àn.", ko: "우리는 융통성 있는 방안을 마련해야 한다." } },
        { zh: "过滤", pinyin: "guòlǜ", ko: "여과하다, 걸러내다", pos: "동사", ex: { zh: "这台机器可以过滤水中的杂质。", pinyin: "Zhè tái jīqì kěyǐ guòlǜ shuǐ zhōng de zázhì.", ko: "이 기계는 물속의 불순물을 여과할 수 있다." } },
        { zh: "偏见", pinyin: "piānjiàn", ko: "편견", pos: "명사", ex: { zh: "我们应该消除对外来者的偏见。", pinyin: "Wǒmen yīnggāi xiāochú duì wàiláizhě de piānjiàn.", ko: "우리는 외지인에 대한 편견을 없애야 한다." } },
        { zh: "阶层", pinyin: "jiēcéng", ko: "계층", pos: "명사", ex: { zh: "这项政策惠及不同社会阶层。", pinyin: "Zhè xiàng zhèngcè huìjí bùtóng shèhuì jiēcéng.", ko: "이 정책은 다양한 사회 계층에 혜택을 준다." } },
        { zh: "知觉", pinyin: "zhījué", ko: "지각, 의식", pos: "명사", ex: { zh: "他摔倒后失去了知觉。", pinyin: "Tā shuāidǎo hòu shīqù le zhījué.", ko: "그는 넘어진 후 의식을 잃었다." } },
        { zh: "飞翔", pinyin: "fēixiáng", ko: "비상하다, 날다", pos: "동사", ex: { zh: "老鹰在蓝天中自由飞翔。", pinyin: "Lǎoyīng zài lántiān zhōng zìyóu fēixiáng.", ko: "독수리가 푸른 하늘에서 자유롭게 날고 있다." } },
      ],
    },
  ],
};

export default themes;
