/**
 * H6 (HSK 6급) 보강 어휘 — 청크 D (200개).
 * HSK 2.0 6급 표준 목록 순증분(빈도순, 전 급 교차 중복 배제) — drkameleon/complete-hsk-vocabulary(MIT) 골격.
 * zh·pinyin·pos는 소스 그대로(다음자 단일 한자는 상용 독음으로 교정), ko·예문만 생성 후 결정적 전수 검증.
 */
const themes = {
  themes: [
    {
      name: "HSK6 보강 D",
      icon: "🟥",
      words: [
        { zh: "敏锐", pinyin: "mǐnruì", ko: "예리하다, 날카롭다", pos: "형용사", ex: { zh: "她有着敏锐的观察力。", pinyin: "Tā yǒu zhe mǐnruì de guānchálì.", ko: "그녀는 예리한 관찰력을 가지고 있다." } },
        { zh: "冷却", pinyin: "lěngquè", ko: "냉각하다, 식히다", pos: "동사", ex: { zh: "发动机需要时间冷却下来。", pinyin: "Fādòngjī xūyào shíjiān lěngquè xiàlai.", ko: "엔진은 식는 데 시간이 필요하다." } },
        { zh: "化验", pinyin: "huàyàn", ko: "검사하다, 화학 검사하다", pos: "동사", ex: { zh: "医生让他去化验血液。", pinyin: "Yīshēng ràng tā qù huàyàn xuèyè.", ko: "의사는 그에게 혈액 검사를 받으라고 했다." } },
        { zh: "平行", pinyin: "píngxíng", ko: "평행하다, 병행하다", pos: "동사", ex: { zh: "这两条线永远平行，不会相交。", pinyin: "Zhè liǎng tiáo xiàn yǒngyuǎn píngxíng, bú huì xiāngjiāo.", ko: "이 두 선은 영원히 평행하며 교차하지 않는다." } },
        { zh: "声誉", pinyin: "shēngyù", ko: "명성, 평판", pos: "명사", ex: { zh: "这家公司在业内享有很高的声誉。", pinyin: "Zhè jiā gōngsī zài yènèi xiǎngyǒu hěn gāo de shēngyù.", ko: "이 회사는 업계에서 높은 명성을 누리고 있다." } },
        { zh: "众所周知", pinyin: "zhòngsuǒ zhōuzhī", ko: "모두가 알다시피, 주지하다시피", pos: "동사", ex: { zh: "众所周知，运动有益健康。", pinyin: "Zhòngsuǒzhōuzhī, yùndòng yǒuyì jiànkāng.", ko: "모두가 알다시피 운동은 건강에 이롭다." } },
        { zh: "根源", pinyin: "gēnyuán", ko: "근원, 원인", pos: "명사", ex: { zh: "找到问题的根源才能彻底解决。", pinyin: "Zhǎodào wèntí de gēnyuán cáinéng chèdǐ jiějué.", ko: "문제의 근원을 찾아야 완전히 해결할 수 있다." } },
        { zh: "妄想", pinyin: "wàngxiǎng", ko: "망상하다, 헛된 생각을 하다", pos: "동사", ex: { zh: "他妄想一夜之间发财致富。", pinyin: "Tā wàngxiǎng yíyè zhījiān fācái zhìfù.", ko: "그는 하룻밤 사이에 부자가 될 헛된 생각을 했다." } },
        { zh: "笼罩", pinyin: "lǒngzhào", ko: "뒤덮다, 자욱하게 덮다", pos: "동사", ex: { zh: "浓雾笼罩着整个城市。", pinyin: "Nóngwù lǒngzhào zhe zhěnggè chéngshì.", ko: "짙은 안개가 도시 전체를 뒤덮고 있다." } },
        { zh: "全局", pinyin: "quánjú", ko: "전체 국면, 대세", pos: "명사", ex: { zh: "领导要从全局出发考虑问题。", pinyin: "Lǐngdǎo yào cóng quánjú chūfā kǎolǜ wèntí.", ko: "리더는 전체 국면을 고려해서 문제를 생각해야 한다." } },
        { zh: "响应", pinyin: "xiǎngyìng", ko: "호응하다, 응답하다", pos: "동사", ex: { zh: "大家积极响应了他的号召。", pinyin: "Dàjiā jījí xiǎngyìng le tā de hàozhào.", ko: "모두가 그의 호소에 적극적으로 호응했다." } },
        { zh: "瀑布", pinyin: "pùbù", ko: "폭포", pos: "명사", ex: { zh: "我们去山里看了一个瀑布。", pinyin: "Wǒmen qù shān lǐ kàn le yí gè pùbù.", ko: "우리는 산에 가서 폭포를 구경했다." } },
        { zh: "顾虑", pinyin: "gùlǜ", ko: "우려, 걱정", pos: "명사", ex: { zh: "请不要有顾虑，尽管说出你的想法。", pinyin: "Qǐng búyào yǒu gùlǜ, jǐnguǎn shuō chū nǐ de xiǎngfǎ.", ko: "우려하지 말고 당신의 생각을 마음껏 말해 주세요." } },
        { zh: "恐吓", pinyin: "kǒnghè", ko: "협박하다, 위협하다", pos: "동사", ex: { zh: "有人打电话恐吓他，要他交钱。", pinyin: "Yǒurén dǎ diànhuà kǒnghè tā, yào tā jiāo qián.", ko: "누군가 전화로 그를 협박하며 돈을 요구했다." } },
        { zh: "数额", pinyin: "shùé", ko: "액수, 수량", pos: "명사", ex: { zh: "这笔贷款的数额相当大。", pinyin: "Zhè bǐ dàikuǎn de shù'é xiāngdāng dà.", ko: "이 대출금의 액수가 상당히 크다." } },
        { zh: "淹没", pinyin: "yānmò", ko: "침수시키다, 잠기게 하다", pos: "동사", ex: { zh: "洪水淹没了整片农田。", pinyin: "Hóngshuǐ yānmò le zhěng piàn nóngtián.", ko: "홍수가 논밭 전체를 잠기게 했다." } },
        { zh: "闪烁", pinyin: "shǎnshuò", ko: "반짝이다, 깜빡이다", pos: "동사", ex: { zh: "夜空中星星在闪烁。", pinyin: "Yèkōng zhōng xīngxing zài shǎnshuò.", ko: "밤하늘에서 별들이 반짝이고 있다." } },
        { zh: "眨", pinyin: "zhǎ", ko: "눈을 깜빡이다", pos: "동사", ex: { zh: "她惊讶得连眼睛都没眨一下。", pinyin: "Tā jīngyà de lián yǎnjīng dōu méi zhǎ yíxià.", ko: "그녀는 너무 놀라서 눈도 깜빡이지 못했다." } },
        { zh: "挑剔", pinyin: "tiāoti", ko: "까다롭다, 트집을 잡다", pos: "동사", ex: { zh: "他对食物一向很挑剔。", pinyin: "Tā duì shíwù yíxiàng hěn tiāoti.", ko: "그는 음식에 대해 늘 까다롭다." } },
        { zh: "内幕", pinyin: "nèimù", ko: "내막, 이면", pos: "명사", ex: { zh: "记者揭露了事件的内幕。", pinyin: "Jìzhě jiēlù le shìjiàn de nèimù.", ko: "기자가 사건의 내막을 폭로했다." } },
        { zh: "俘虏", pinyin: "fúlǔ", ko: "포로", pos: "명사", ex: { zh: "战争结束后俘虏被释放了。", pinyin: "Zhànzhēng jiéshù hòu fúlǔ bèi shìfàng le.", ko: "전쟁이 끝난 후 포로들이 석방되었다." } },
        { zh: "信誉", pinyin: "xìnyù", ko: "신용, 명성", pos: "명사", ex: { zh: "诚信经营才能建立良好信誉。", pinyin: "Chéngxìn jīngyíng cáinéng jiànlì liánghǎo xìnyù.", ko: "정직하게 경영해야 좋은 신용을 쌓을 수 있다." } },
        { zh: "镇定", pinyin: "zhèndìng", ko: "침착하다, 차분하다", pos: "형용사", ex: { zh: "面对危险，他表现得十分镇定。", pinyin: "Miànduì wēixiǎn, tā biǎoxiàn de shífēn zhèndìng.", ko: "위험에 직면해서도 그는 매우 침착했다." } },
        { zh: "租赁", pinyin: "zūlìn", ko: "임대하다, 세내다", pos: "동사", ex: { zh: "公司租赁了一间新办公室。", pinyin: "Gōngsī zūlìn le yì jiān xīn bàngōngshì.", ko: "회사는 새 사무실을 임대했다." } },
        { zh: "规章", pinyin: "guīzhāng", ko: "규정, 규칙", pos: "명사", ex: { zh: "员工必须遵守公司的规章制度。", pinyin: "Yuángōng bìxū zūnshǒu gōngsī de guīzhāng zhìdù.", ko: "직원은 반드시 회사의 규정 제도를 지켜야 한다." } },
        { zh: "施展", pinyin: "shīzhǎn", ko: "발휘하다, 펼치다", pos: "동사", ex: { zh: "这个舞台让她充分施展才华。", pinyin: "Zhège wǔtái ràng tā chōngfèn shīzhǎn cáihuá.", ko: "이 무대는 그녀가 재능을 충분히 발휘하게 했다." } },
        { zh: "屑", pinyin: "xiè", ko: "부스러기, 조각", pos: "", ex: { zh: "桌子上撒满了面包屑。", pinyin: "Zhuōzi shàng sǎ mǎn le miànbāo xiè.", ko: "탁자 위에 빵 부스러기가 가득 흩어져 있다." } },
        { zh: "曲子", pinyin: "qǔzi", ko: "곡, 노래", pos: "명사", ex: { zh: "她哼着一首熟悉的曲子。", pinyin: "Tā hēng zhe yì shǒu shúxī de qǔzi.", ko: "그녀는 익숙한 곡을 흥얼거리고 있다." } },
        { zh: "推理", pinyin: "tuīlǐ", ko: "추리하다, 추론하다", pos: "동사", ex: { zh: "侦探根据线索进行推理。", pinyin: "Zhēntàn gēnjù xiànsuǒ jìnxíng tuīlǐ.", ko: "탐정은 단서를 근거로 추리했다." } },
        { zh: "潜水", pinyin: "qiánshuǐ", ko: "잠수하다", pos: "동사", ex: { zh: "他喜欢在海边潜水看鱼。", pinyin: "Tā xǐhuan zài hǎibiān qiánshuǐ kàn yú.", ko: "그는 바닷가에서 잠수하며 물고기를 구경하는 것을 좋아한다." } },
        { zh: "唠叨", pinyin: "láodao", ko: "잔소리하다, 수다떨다", pos: "동사", ex: { zh: "妈妈总是唠叨个不停。", pinyin: "Māma zǒngshì láodao ge bùtíng.", ko: "엄마는 항상 끊임없이 잔소리를 하신다." } },
        { zh: "管辖", pinyin: "guǎnxiá", ko: "관할하다", pos: "동사", ex: { zh: "这个案件由地方法院管辖。", pinyin: "Zhège ànjiàn yóu dìfāng fǎyuàn guǎnxiá.", ko: "이 사건은 지방 법원이 관할한다." } },
        { zh: "坟墓", pinyin: "fénmù", ko: "무덤, 묘", pos: "명사", ex: { zh: "他们去祖先的坟墓前扫墓。", pinyin: "Tāmen qù zǔxiān de fénmù qián sǎomù.", ko: "그들은 조상의 무덤 앞에 성묘하러 갔다." } },
        { zh: "充当", pinyin: "chōngdāng", ko: "담당하다, ~역할을 하다", pos: "동사", ex: { zh: "他在会议上充当翻译的角色。", pinyin: "Tā zài huìyì shàng chōngdāng fānyì de juésè.", ko: "그는 회의에서 통역 역할을 담당했다." } },
        { zh: "遍布", pinyin: "biànbù", ko: "널리 퍼지다, 두루 분포하다", pos: "동사", ex: { zh: "这种植物遍布全国各地。", pinyin: "Zhè zhǒng zhíwù biànbù quánguó gèdì.", ko: "이 식물은 전국 각지에 널리 분포되어 있다." } },
        { zh: "衷心", pinyin: "zhōngxīn", ko: "진심으로, 충심으로", pos: "부사", ex: { zh: "我衷心祝愿你们幸福美满。", pinyin: "Wǒ zhōngxīn zhùyuàn nǐmen xìngfú měimǎn.", ko: "저는 여러분의 행복을 진심으로 기원합니다." } },
        { zh: "司令", pinyin: "sīlìng", ko: "사령관", pos: "명사", ex: { zh: "他被任命为部队的司令。", pinyin: "Tā bèi rènmìng wéi bùduì de sīlìng.", ko: "그는 부대의 사령관으로 임명되었다." } },
        { zh: "若干", pinyin: "ruògān", ko: "약간, 다소, 몇몇", pos: "수사", ex: { zh: "会议提出了若干改进意见。", pinyin: "Huìyì tíchū le ruògān gǎijìn yìjiàn.", ko: "회의에서 몇 가지 개선 의견을 제시했다." } },
        { zh: "批判", pinyin: "pīpàn", ko: "비판하다", pos: "동사", ex: { zh: "老师批判了他的错误观点。", pinyin: "Lǎoshī pīpàn le tā de cuòwù guāndiǎn.", ko: "선생님은 그의 잘못된 견해를 비판했다." } },
        { zh: "难堪", pinyin: "nánkān", ko: "난처하다, 곤란하다", pos: "형용사", ex: { zh: "他的问题让我感到十分难堪。", pinyin: "Tā de wèntí ràng wǒ gǎndào shífēn nánkān.", ko: "그의 질문에 나는 매우 난처했다." } },
        { zh: "野心", pinyin: "yěxīn", ko: "야심, 야망", pos: "명사", ex: { zh: "他从小就有很大的野心。", pinyin: "Tā cóng xiǎo jiù yǒu hěn dà de yěxīn.", ko: "그는 어릴 때부터 큰 야심을 가지고 있었다." } },
        { zh: "关照", pinyin: "guānzhào", ko: "돌보다, 보살피다", pos: "동사", ex: { zh: "谢谢你一直关照我。", pinyin: "Xièxie nǐ yīzhí guānzhào wǒ.", ko: "항상 저를 돌봐주셔서 감사합니다." } },
        { zh: "油漆", pinyin: "yóuqī", ko: "페인트, 도료", pos: "명사", ex: { zh: "墙上的油漆还没干。", pinyin: "Qiáng shang de yóuqī hái méi gān.", ko: "벽의 페인트가 아직 마르지 않았다." } },
        { zh: "古董", pinyin: "gǔdǒng", ko: "골동품", pos: "명사", ex: { zh: "他喜欢收藏古董家具。", pinyin: "Tā xǐhuan shōucáng gǔdǒng jiājù.", ko: "그는 골동품 가구 수집을 좋아한다." } },
        { zh: "鉴别", pinyin: "jiànbié", ko: "감별하다, 식별하다", pos: "동사", ex: { zh: "专家鉴别出这是假画。", pinyin: "Zhuānjiā jiànbié chū zhè shì jiǎ huà.", ko: "전문가는 이것이 가짜 그림임을 감별해 냈다." } },
        { zh: "心血", pinyin: "xīnxuè", ko: "심혈, 애쓴 노력", pos: "명사", ex: { zh: "这本书是他多年心血的结晶。", pinyin: "Zhè běn shū shì tā duō nián xīnxuè de jiéjīng.", ko: "이 책은 그가 다년간 쏟은 심혈의 결정체이다." } },
        { zh: "预先", pinyin: "yùxiān", ko: "미리, 사전에", pos: "부사", ex: { zh: "请预先通知我们时间。", pinyin: "Qǐng yùxiān tōngzhī wǒmen shíjiān.", ko: "시간을 미리 저희에게 알려주세요." } },
        { zh: "遗失", pinyin: "yíshī", ko: "분실하다, 잃어버리다", pos: "동사", ex: { zh: "他不小心遗失了护照。", pinyin: "Tā bù xiǎoxīn yíshī le hùzhào.", ko: "그는 실수로 여권을 분실했다." } },
        { zh: "四肢", pinyin: "sìzhī", ko: "사지, 팔다리", pos: "명사", ex: { zh: "运动能锻炼四肢肌肉。", pinyin: "Yùndòng néng duànliàn sìzhī jīròu.", ko: "운동은 사지 근육을 단련시킬 수 있다." } },
        { zh: "还原", pinyin: "huányuán", ko: "원상복구하다, 복원하다", pos: "동사", ex: { zh: "警方还原了案发经过。", pinyin: "Jǐngfāng huányuán le àn fā jīngguò.", ko: "경찰은 사건 발생 경위를 재구성했다." } },
        { zh: "烹饪", pinyin: "pēngrèn", ko: "요리하다, 조리하다", pos: "동사", ex: { zh: "她对烹饪很有兴趣。", pinyin: "Tā duì pēngrèn hěn yǒu xìngqù.", ko: "그녀는 요리에 관심이 많다." } },
        { zh: "陶瓷", pinyin: "táocí", ko: "도자기", pos: "명사", ex: { zh: "这家店专卖陶瓷制品。", pinyin: "Zhè jiā diàn zhuān mài táocí zhìpǐn.", ko: "이 가게는 도자기 제품만 판매한다." } },
        { zh: "发火", pinyin: "fāhuǒ", ko: "발화하다, 점화하다", pos: "동사", ex: { zh: "这堆干柴很容易发火。", pinyin: "Zhè duī gān chái hěn róngyì fāhuǒ.", ko: "이 마른 장작 더미는 쉽게 발화한다." } },
        { zh: "丰满", pinyin: "Fēngmǎn", ko: "풍만하다, 충만하다", pos: "형용사", ex: { zh: "理想很丰满，现实很骨感。", pinyin: "Lǐxiǎng hěn fēngmǎn, xiànshí hěn gǔgǎn.", ko: "이상은 풍만하지만 현실은 냉혹하다." } },
        { zh: "垂直", pinyin: "chuízhí", ko: "수직이다, 수직의", pos: "동사", ex: { zh: "这条线与地面垂直。", pinyin: "Zhè tiáo xiàn yǔ dìmiàn chuízhí.", ko: "이 선은 지면과 수직이다." } },
        { zh: "任性", pinyin: "rènxìng", ko: "제멋대로이다, 방종하다", pos: "형용사", ex: { zh: "小孩子有时很任性。", pinyin: "Xiǎo háizi yǒushí hěn rènxìng.", ko: "어린아이는 가끔 매우 제멋대로이다." } },
        { zh: "以致", pinyin: "yǐzhì", ko: "그리하여 ~하게 되다, 그 결과", pos: "접속사", ex: { zh: "他太紧张，以致说错了话。", pinyin: "Tā tài jǐnzhāng, yǐzhì shuō cuò le huà.", ko: "그는 너무 긴장한 나머지 말을 잘못했다." } },
        { zh: "蒸发", pinyin: "zhēngfā", ko: "증발하다", pos: "동사", ex: { zh: "水在阳光下逐渐蒸发。", pinyin: "Shuǐ zài yángguāng xià zhújiàn zhēngfā.", ko: "물은 햇빛 아래에서 점차 증발한다." } },
        { zh: "立体", pinyin: "lìtǐ", ko: "입체적이다, 입체의", pos: "형용사", ex: { zh: "这幅画很有立体感。", pinyin: "Zhè fú huà hěn yǒu lìtǐ gǎn.", ko: "이 그림은 입체감이 강하다." } },
        { zh: "高涨", pinyin: "gāozhǎng", ko: "고조되다, 앙양되다", pos: "형용사", ex: { zh: "大家的热情越来越高涨。", pinyin: "Dàjiā de rèqíng yuè lái yuè gāozhǎng.", ko: "모두의 열정이 점점 고조되고 있다." } },
        { zh: "上游", pinyin: "shàngyóu", ko: "상류", pos: "명사", ex: { zh: "这条河的上游水很清。", pinyin: "Zhè tiáo hé de shàngyóu shuǐ hěn qīng.", ko: "이 강의 상류는 물이 맑다." } },
        { zh: "上任", pinyin: "shàngrèn", ko: "부임하다, 취임하다", pos: "동사", ex: { zh: "新经理下周正式上任。", pinyin: "Xīn jīnglǐ xià zhōu zhèngshì shàngrèn.", ko: "새 매니저는 다음 주에 정식으로 부임한다." } },
        { zh: "探望", pinyin: "tànwàng", ko: "방문하다, 문안하다", pos: "동사", ex: { zh: "周末我要去医院探望他。", pinyin: "Zhōumò wǒ yào qù yīyuàn tànwàng tā.", ko: "주말에 나는 병원에 가서 그를 문안할 것이다." } },
        { zh: "荒谬", pinyin: "huāngmiù", ko: "황당하다, 터무니없다", pos: "형용사", ex: { zh: "这个理由听起来很荒谬。", pinyin: "Zhège lǐyóu tīng qǐlai hěn huāngmiù.", ko: "이 이유는 매우 황당하게 들린다." } },
        { zh: "特长", pinyin: "tècháng", ko: "특기, 장기", pos: "명사", ex: { zh: "画画一直是她的特长。", pinyin: "Huà huà yīzhí shì tā de tècháng.", ko: "그림 그리기는 줄곧 그녀의 특기였다." } },
        { zh: "果断", pinyin: "guǒduàn", ko: "과단성 있다, 결단력 있다", pos: "형용사", ex: { zh: "关键时刻他做出果断决定。", pinyin: "Guānjiàn shíkè tā zuò chū guǒduàn juédìng.", ko: "결정적인 순간에 그는 과감한 결정을 내렸다." } },
        { zh: "振奋", pinyin: "zhènfèn", ko: "분발시키다, 진작시키다", pos: "동사", ex: { zh: "这个消息让大家很振奋。", pinyin: "Zhège xiāoxi ràng dàjiā hěn zhènfèn.", ko: "이 소식은 모두를 분발시켰다." } },
        { zh: "卑鄙", pinyin: "bēibǐ", ko: "비열하다, 야비하다", pos: "형용사", ex: { zh: "他用卑鄙的手段骗人。", pinyin: "Tā yòng bēibǐ de shǒuduàn piàn rén.", ko: "그는 비열한 수단으로 사람을 속인다." } },
        { zh: "务必", pinyin: "wùbì", ko: "반드시, 꼭", pos: "부사", ex: { zh: "明天务必准时到场。", pinyin: "Míngtiān wùbì zhǔnshí dàochǎng.", ko: "내일은 반드시 제시간에 도착해야 한다." } },
        { zh: "拥护", pinyin: "yōnghù", ko: "옹호하다, 지지하다", pos: "동사", ex: { zh: "大家都拥护这项改革。", pinyin: "Dàjiā dōu yōnghù zhè xiàng gǎigé.", ko: "모두가 이 개혁을 지지한다." } },
        { zh: "意料", pinyin: "yìliào", ko: "예상하다, 예상", pos: "동사", ex: { zh: "结果出乎大家的意料。", pinyin: "Jiéguǒ chūhū dàjiā de yìliào.", ko: "결과는 모두의 예상을 벗어났다." } },
        { zh: "僵硬", pinyin: "jiāngyìng", ko: "뻣뻣하다, 경직되다", pos: "형용사", ex: { zh: "他的表情变得僵硬。", pinyin: "Tā de biǎoqíng biàn de jiāngyìng.", ko: "그의 표정이 굳어졌다." } },
        { zh: "董事长", pinyin: "dǒngshìzhǎng", ko: "이사장, 회장", pos: "명사", ex: { zh: "他被任命为董事长。", pinyin: "Tā bèi rènmìng wéi dǒngshìzhǎng.", ko: "그는 이사장으로 임명되었다." } },
        { zh: "风味", pinyin: "fēngwèi", ko: "풍미, 독특한 맛", pos: "명사", ex: { zh: "这道菜很有地方风味。", pinyin: "Zhè dào cài hěn yǒu dìfāng fēngwèi.", ko: "이 요리는 향토의 풍미가 강하다." } },
        { zh: "档次", pinyin: "dàngcì", ko: "등급, 수준", pos: "명사", ex: { zh: "这家酒店档次很高。", pinyin: "Zhè jiā jiǔdiàn dàngcì hěn gāo.", ko: "이 호텔은 등급이 매우 높다." } },
        { zh: "让步", pinyin: "ràngbù", ko: "양보하다", pos: "동사", ex: { zh: "双方最终都做出让步。", pinyin: "Shuāngfāng zuìzhōng dōu zuò chū ràngbù.", ko: "양측은 결국 모두 양보했다." } },
        { zh: "繁忙", pinyin: "fánmáng", ko: "바쁘다, 분주하다", pos: "형용사", ex: { zh: "他最近工作十分繁忙。", pinyin: "Tā zuìjìn gōngzuò shífēn fánmáng.", ko: "그는 요즘 업무가 매우 바쁘다." } },
        { zh: "习俗", pinyin: "xísú", ko: "풍습, 관습", pos: "명사", ex: { zh: "各地过节的习俗不同。", pinyin: "Gè dì guò jié de xísú bùtóng.", ko: "각 지역의 명절 풍습은 서로 다르다." } },
        { zh: "狭窄", pinyin: "xiázhǎi", ko: "좁다, 협소하다", pos: "형용사", ex: { zh: "这条巷子非常狭窄。", pinyin: "Zhè tiáo xiàngzi fēicháng xiázhǎi.", ko: "이 골목은 매우 좁다." } },
        { zh: "布局", pinyin: "bùjú", ko: "배치, 구성", pos: "명사", ex: { zh: "整个房间布局合理。", pinyin: "Zhěnggè fángjiān bùjú hélǐ.", ko: "방 전체의 배치가 합리적이다." } },
        { zh: "贪污", pinyin: "tānwū", ko: "부패하다, 횡령하다", pos: "동사", ex: { zh: "这名官员因贪污被捕。", pinyin: "Zhè míng guānyuán yīn tānwū bèi bǔ.", ko: "이 관리는 횡령으로 체포되었다." } },
        { zh: "峡谷", pinyin: "xiágǔ", ko: "협곡", pos: "명사", ex: { zh: "他们徒步穿越峡谷。", pinyin: "Tāmen túbù chuānyuè xiágǔ.", ko: "그들은 도보로 협곡을 가로질렀다." } },
        { zh: "沐浴", pinyin: "mùyù", ko: "목욕하다, 몸을 담그다", pos: "동사", ex: { zh: "每天早上她都会沐浴。", pinyin: "Měitiān zǎoshang tā dōu huì mùyù.", ko: "그녀는 매일 아침 목욕을 한다." } },
        { zh: "口腔", pinyin: "kǒuqiāng", ko: "구강", pos: "명사", ex: { zh: "医生检查了他的口腔。", pinyin: "Yīshēng jiǎnchá le tā de kǒuqiāng.", ko: "의사는 그의 구강을 검사했다." } },
        { zh: "废墟", pinyin: "fèixū", ko: "폐허", pos: "명사", ex: { zh: "地震后城市变成废墟。", pinyin: "Dìzhèn hòu chéngshì biàn chéng fèixū.", ko: "지진 후 도시는 폐허로 변했다." } },
        { zh: "反驳", pinyin: "fǎnbó", ko: "반박하다", pos: "동사", ex: { zh: "他立刻反驳了对方的观点。", pinyin: "Tā lìkè fǎnbó le duìfāng de guāndiǎn.", ko: "그는 즉시 상대방의 견해를 반박했다." } },
        { zh: "驱逐", pinyin: "qūzhú", ko: "추방하다, 쫓아내다", pos: "동사", ex: { zh: "他因违法被驱逐出境。", pinyin: "Tā yīn wéifǎ bèi qūzhú chūjìng.", ko: "그는 법을 어겨 국외로 추방되었다." } },
        { zh: "责怪", pinyin: "zéguài", ko: "나무라다, 탓하다", pos: "동사", ex: { zh: "你别再责怪自己了。", pinyin: "Nǐ bié zài zéguài zìjǐ le.", ko: "너 더 이상 자신을 탓하지 마." } },
        { zh: "对照", pinyin: "duìzhào", ko: "대조하다, 비교하다", pos: "동사", ex: { zh: "请对照原文检查译文。", pinyin: "Qǐng duìzhào yuánwén jiǎnchá yìwén.", ko: "원문과 대조하여 번역문을 확인하세요." } },
        { zh: "辨认", pinyin: "biànrèn", ko: "식별하다, 분간하다", pos: "동사", ex: { zh: "他很难辨认她的字迹。", pinyin: "Tā hěn nán biànrèn tā de zìjì.", ko: "그는 그녀의 필체를 알아보기 어려웠다." } },
        { zh: "备忘录", pinyin: "bèiwànglù", ko: "메모, 비망록", pos: "명사", ex: { zh: "秘书写了一份备忘录。", pinyin: "Mìshū xiě le yī fèn bèiwànglù.", ko: "비서는 메모 한 장을 작성했다." } },
        { zh: "埋怨", pinyin: "mányuàn", ko: "원망하다, 투덜거리다", pos: "동사", ex: { zh: "她总是埋怨天气不好。", pinyin: "Tā zǒngshì mányuàn tiānqì bù hǎo.", ko: "그녀는 항상 날씨가 나쁘다고 투덜댄다." } },
        { zh: "过失", pinyin: "guòshī", ko: "과실, 실수", pos: "명사", ex: { zh: "这是他工作中的过失。", pinyin: "Zhè shì tā gōngzuò zhōng de guòshī.", ko: "이것은 그의 업무상 과실이다." } },
        { zh: "搅拌", pinyin: "jiǎobàn", ko: "휘젓다, 뒤섞다", pos: "동사", ex: { zh: "把鸡蛋和面粉搅拌均匀。", pinyin: "Bǎ jīdàn hé miànfěn jiǎobàn jūnyún.", ko: "계란과 밀가루를 골고루 섞으세요." } },
        { zh: "宣誓", pinyin: "xuānshì", ko: "선서하다", pos: "동사", ex: { zh: "新总统正式宣誓就职。", pinyin: "Xīn zǒngtǒng zhèngshì xuānshì jiùzhí.", ko: "새 대통령이 정식으로 취임 선서를 했다." } },
        { zh: "床单", pinyin: "chuángdān", ko: "침대 시트", pos: "명사", ex: { zh: "妈妈换了新的床单。", pinyin: "Māma huàn le xīn de chuángdān.", ko: "엄마는 새 침대 시트로 바꾸셨다." } },
        { zh: "精通", pinyin: "jīngtōng", ko: "정통하다, 능통하다", pos: "동사", ex: { zh: "他精通好几种外语。", pinyin: "Tā jīngtōng hǎo jǐ zhǒng wàiyǔ.", ko: "그는 여러 외국어에 능통하다." } },
        { zh: "海滨", pinyin: "hǎibīn", ko: "해변, 바닷가", pos: "명사", ex: { zh: "他们在海滨散步聊天。", pinyin: "Tāmen zài hǎibīn sànbù liáotiān.", ko: "그들은 해변에서 산책하며 이야기했다." } },
        { zh: "利率", pinyin: "lìlǜ", ko: "이율, 금리", pos: "명사", ex: { zh: "银行下调了贷款利率。", pinyin: "Yínháng xiàtiáo le dàikuǎn lìlǜ.", ko: "은행은 대출 금리를 인하했다." } },
        { zh: "腐蚀", pinyin: "fǔshí", ko: "부식하다, 부식시키다", pos: "동사", ex: { zh: "海水很容易腐蚀金属。", pinyin: "Hǎishuǐ hěn róngyì fǔshí jīnshǔ.", ko: "바닷물은 금속을 쉽게 부식시킨다." } },
        { zh: "公道", pinyin: "gōngdào", ko: "공정하다, 정당하다", pos: "형용사", ex: { zh: "老板处理事情很公道。", pinyin: "Lǎobǎn chǔlǐ shìqing hěn gōngdào.", ko: "사장님은 일 처리가 매우 공정하다." } },
        { zh: "辜负", pinyin: "gūfù", ko: "저버리다, 실망시키다", pos: "동사", ex: { zh: "他没有辜负父母的期望。", pinyin: "Tā méiyǒu gūfù fùmǔ de qīwàng.", ko: "그는 부모님의 기대를 저버리지 않았다." } },
        { zh: "活该", pinyin: "huógāi", ko: "자업자득이다, 당연하다", pos: "부사", ex: { zh: "你活该被骂了一顿。", pinyin: "Nǐ huógāi bèi mà le yī dùn.", ko: "너는 혼나도 싸다." } },
        { zh: "上瘾", pinyin: "shàngyǐn", ko: "중독되다, 습관이 되다", pos: "동사", ex: { zh: "他对手机游戏上瘾了。", pinyin: "Tā duì shǒujī yóuxì shàngyǐn le.", ko: "그는 휴대폰 게임에 중독되었다." } },
        { zh: "不愧", pinyin: "bùkuì", ko: "과연 ~답다, 손색없다", pos: "부사", ex: { zh: "他不愧是最优秀的学生。", pinyin: "Tā bùkuì shì zuì yōuxiù de xuésheng.", ko: "그는 과연 최고의 학생답다." } },
        { zh: "垄断", pinyin: "lǒngduàn", ko: "독점하다", pos: "동사", ex: { zh: "这家公司垄断了市场。", pinyin: "Zhè jiā gōngsī lǒngduàn le shìchǎng.", ko: "이 회사는 시장을 독점했다." } },
        { zh: "玩弄", pinyin: "wánnòng", ko: "희롱하다, 가지고 놀다", pos: "동사", ex: { zh: "他喜欢玩弄别人的感情。", pinyin: "Tā xǐhuan wánnòng biérén de gǎnqíng.", ko: "그는 다른 사람의 감정을 가지고 노는 것을 좋아한다." } },
        { zh: "开采", pinyin: "kāicǎi", ko: "채굴하다, 개발하다", pos: "동사", ex: { zh: "这里正在开采石油。", pinyin: "Zhèlǐ zhèngzài kāicǎi shíyóu.", ko: "이곳에서는 석유를 채굴하고 있다." } },
        { zh: "见解", pinyin: "jiànjiě", ko: "견해, 의견", pos: "명사", ex: { zh: "他对这个问题有独特见解。", pinyin: "Tā duì zhège wèntí yǒu dútè jiànjiě.", ko: "그는 이 문제에 대해 독특한 견해를 가지고 있다." } },
        { zh: "氢", pinyin: "qīng", ko: "수소", pos: "명사", ex: { zh: "氢是宇宙中最轻的元素。", pinyin: "Qīng shì yǔzhòu zhōng zuì qīng de yuánsù.", ko: "수소는 우주에서 가장 가벼운 원소이다." } },
        { zh: "酝酿", pinyin: "yùnniàng", ko: "무르익다, 구상하다", pos: "동사", ex: { zh: "这项政策正在酝酿之中。", pinyin: "Zhè xiàng zhèngcè zhèngzài yùnniàng zhī zhōng.", ko: "이 정책은 현재 구상 중이다." } },
        { zh: "揭发", pinyin: "jiēfā", ko: "폭로하다, 고발하다", pos: "동사", ex: { zh: "记者揭发了这起丑闻。", pinyin: "Jìzhě jiēfā le zhè qǐ chǒuwén.", ko: "기자가 이 스캔들을 폭로했다." } },
        { zh: "阵容", pinyin: "zhènróng", ko: "진용, 라인업", pos: "명사", ex: { zh: "这支球队阵容强大。", pinyin: "Zhè zhī qiúduì zhènróng qiángdà.", ko: "이 팀은 라인업이 강력하다." } },
        { zh: "畅销", pinyin: "chàngxiāo", ko: "잘 팔리다, 베스트셀러이다", pos: "동사", ex: { zh: "这本小说非常畅销。", pinyin: "Zhè běn xiǎoshuō fēicháng chàngxiāo.", ko: "이 소설은 매우 잘 팔린다." } },
        { zh: "拣", pinyin: "jiǎn", ko: "고르다, 선택하다", pos: "동사", ex: { zh: "她仔细地拣出坏的水果。", pinyin: "Tā zǐxì de jiǎn chū huài de shuǐguǒ.", ko: "그녀는 상한 과일을 꼼꼼히 골라냈다." } },
        { zh: "附属", pinyin: "fùshǔ", ko: "부속되다, 딸려 있다", pos: "동사", ex: { zh: "这所医院附属于大学。", pinyin: "Zhè suǒ yīyuàn fùshǔ yú dàxué.", ko: "이 병원은 대학에 부속되어 있다." } },
        { zh: "适宜", pinyin: "shìyí", ko: "적합하다, 알맞다", pos: "동사", ex: { zh: "这里的气候很适宜居住。", pinyin: "Zhèlǐ de qìhòu hěn shìyí jūzhù.", ko: "이곳의 기후는 거주하기에 매우 적합하다." } },
        { zh: "屈服", pinyin: "qūfú", ko: "굴복하다", pos: "동사", ex: { zh: "他绝不会向困难屈服。", pinyin: "Tā jué bù huì xiàng kùnnán qūfú.", ko: "그는 절대 어려움에 굴복하지 않을 것이다." } },
        { zh: "捍卫", pinyin: "hànwèi", ko: "수호하다, 지키다", pos: "", ex: { zh: "士兵们誓死捍卫祖国。", pinyin: "Shìbīngmen shì sǐ hànwèi zǔguó.", ko: "병사들은 목숨을 걸고 조국을 수호하기로 맹세했다." } },
        { zh: "沸腾", pinyin: "fèiténg", ko: "끓다, 들끓다", pos: "동사", ex: { zh: "锅里的水已经沸腾了。", pinyin: "Guō lǐ de shuǐ yǐjīng fèiténg le.", ko: "냄비 속 물이 이미 끓었다." } },
        { zh: "小心翼翼", pinyin: "xiǎoxīn yìyì", ko: "매우 조심스럽다, 조심조심", pos: "관용구", ex: { zh: "他小心翼翼地把花瓶放在桌子上。", pinyin: "Tā xiǎoxīnyìyì de bǎ huāpíng fàng zài zhuōzi shang.", ko: "그는 매우 조심스럽게 꽃병을 탁자 위에 놓았다." } },
        { zh: "合伙", pinyin: "héhuǒ", ko: "동업하다, 합작하다", pos: "동사", ex: { zh: "他们打算合伙开一家咖啡店。", pinyin: "Tāmen dǎsuàn héhuǒ kāi yì jiā kāfēidiàn.", ko: "그들은 동업하여 카페를 열 계획이다." } },
        { zh: "共鸣", pinyin: "gòngmíng", ko: "공명하다, 공감하다", pos: "동사", ex: { zh: "这部小说引起了读者的强烈共鸣。", pinyin: "Zhè bù xiǎoshuō yǐnqǐle dúzhě de qiángliè gòngmíng.", ko: "이 소설은 독자들의 강한 공감을 불러일으켰다." } },
        { zh: "乞丐", pinyin: "qǐgài", ko: "거지", pos: "명사", ex: { zh: "街头坐着一个衣衫褴褛的乞丐。", pinyin: "Jiētóu zuòzhe yí gè yīshān lánlǚ de qǐgài.", ko: "거리에 남루한 옷을 입은 거지가 앉아 있다." } },
        { zh: "申报", pinyin: "shēnbào", ko: "신고하다", pos: "동사", ex: { zh: "入境时必须如实申报携带的物品。", pinyin: "Rùjìng shí bìxū rúshí shēnbào xiédài de wùpǐn.", ko: "입국할 때 반드시 소지한 물품을 사실대로 신고해야 한다." } },
        { zh: "冒充", pinyin: "màochōng", ko: "사칭하다, 가장하다", pos: "동사", ex: { zh: "他冒充警察骗取了老人的信任。", pinyin: "Tā màochōng jǐngchá piànqǔle lǎorén de xìnrèn.", ko: "그는 경찰을 사칭하여 노인의 신뢰를 속여 얻었다." } },
        { zh: "事态", pinyin: "shìtài", ko: "사태, 상황", pos: "명사", ex: { zh: "事态的发展远远超出了我们的预料。", pinyin: "Shìtài de fāzhǎn yuǎnyuǎn chāochūle wǒmen de yùliào.", ko: "사태의 진전은 우리의 예상을 훨씬 뛰어넘었다." } },
        { zh: "橙", pinyin: "chéng", ko: "오렌지색, 등자나무", pos: "", ex: { zh: "夕阳把天空染成了一片橙色。", pinyin: "Xīyáng bǎ tiānkōng rǎnchéngle yí piàn chéngsè.", ko: "석양이 하늘을 온통 오렌지색으로 물들였다." } },
        { zh: "局限", pinyin: "júxiàn", ko: "국한되다, 제한하다", pos: "동사", ex: { zh: "他的知识局限于书本，缺乏实践经验。", pinyin: "Tā de zhīshi júxiàn yú shūběn, quēfá shíjiàn jīngyàn.", ko: "그의 지식은 책에만 국한되어 실무 경험이 부족하다." } },
        { zh: "削弱", pinyin: "xuēruò", ko: "약화시키다", pos: "동사", ex: { zh: "长期的压力削弱了他的免疫力。", pinyin: "Chángqī de yālì xuēruòle tā de miǎnyìlì.", ko: "장기간의 스트레스가 그의 면역력을 약화시켰다." } },
        { zh: "牢固", pinyin: "láogù", ko: "견고하다, 튼튼하다", pos: "형용사", ex: { zh: "这座桥梁建造得非常牢固。", pinyin: "Zhè zuò qiáoliáng jiànzào de fēicháng láogù.", ko: "이 다리는 매우 튼튼하게 지어졌다." } },
        { zh: "恨不得", pinyin: "hènbude", ko: "간절히 ~하고 싶다", pos: "부사", ex: { zh: "她恨不得马上飞回家看孩子。", pinyin: "Tā hènbude mǎshàng fēihuí jiā kàn háizi.", ko: "그녀는 당장이라도 집에 날아가 아이를 보고 싶었다." } },
        { zh: "亲热", pinyin: "qīnrè", ko: "다정하다, 친밀하다", pos: "형용사", ex: { zh: "两个孩子见面就亲热地拥抱在一起。", pinyin: "Liǎng gè háizi jiànmiàn jiù qīnrè de yōngbào zài yìqǐ.", ko: "두 아이는 만나자마자 다정하게 서로 껴안았다." } },
        { zh: "分量", pinyin: "fēnliàng", ko: "분력, 성분(벡터의)", pos: "명사", ex: { zh: "这个力可以分解成两个分量。", pinyin: "Zhège lì kěyǐ fēnjiě chéng liǎng gè fēnliàng.", ko: "이 힘은 두 개의 분력(성분)으로 분해될 수 있다." } },
        { zh: "兑换", pinyin: "duìhuàn", ko: "환전하다, 교환하다", pos: "동사", ex: { zh: "我想把美元兑换成人民币。", pinyin: "Wǒ xiǎng bǎ měiyuán duìhuàn chéng rénmínbì.", ko: "저는 달러를 인민폐로 환전하고 싶습니다." } },
        { zh: "遗留", pinyin: "yíliú", ko: "남기다, 물려주다", pos: "동사", ex: { zh: "这些问题是历史遗留下来的。", pinyin: "Zhèxiē wèntí shì lìshǐ yíliú xiàlai de.", ko: "이 문제들은 역사가 남긴 것이다." } },
        { zh: "大肆", pinyin: "dàsì", ko: "제멋대로, 대대적으로", pos: "부사", ex: { zh: "商店在节日期间大肆宣传促销活动。", pinyin: "Shāngdiàn zài jiérì qījiān dàsì xuānchuán cùxiāo huódòng.", ko: "상점은 명절 기간에 대대적으로 판촉 행사를 홍보했다." } },
        { zh: "悬念", pinyin: "xuánniàn", ko: "긴장감, 서스펜스", pos: "명사", ex: { zh: "这部电影的结局充满了悬念。", pinyin: "Zhè bù diànyǐng de jiéjú chōngmǎnle xuánniàn.", ko: "이 영화의 결말은 긴장감으로 가득 차 있다." } },
        { zh: "寂静", pinyin: "jìjìng", ko: "고요하다, 적막하다", pos: "형용사", ex: { zh: "深夜的森林一片寂静。", pinyin: "Shēnyè de sēnlín yí piàn jìjìng.", ko: "깊은 밤의 숲은 온통 고요했다." } },
        { zh: "压缩", pinyin: "yāsuō", ko: "압축하다", pos: "동사", ex: { zh: "请把这个文件压缩后再发送。", pinyin: "Qǐng bǎ zhège wénjiàn yāsuō hòu zài fāsòng.", ko: "이 파일을 압축한 후 보내 주세요." } },
        { zh: "宫殿", pinyin: "gōngdiàn", ko: "궁전", pos: "명사", ex: { zh: "这座宫殿有着几百年的历史。", pinyin: "Zhè zuò gōngdiàn yǒuzhe jǐ bǎi nián de lìshǐ.", ko: "이 궁전은 수백 년의 역사를 지니고 있다." } },
        { zh: "缺口", pinyin: "quēkǒu", ko: "틈, 부족분", pos: "명사", ex: { zh: "墙上出现了一个大缺口。", pinyin: "Qiáng shang chūxiànle yí gè dà quēkǒu.", ko: "벽에 큰 틈이 생겼다." } },
        { zh: "疲倦", pinyin: "píjuàn", ko: "피곤하다, 지치다", pos: "형용사", ex: { zh: "加班到深夜让他感到十分疲倦。", pinyin: "Jiābān dào shēnyè ràng tā gǎndào shífēn píjuàn.", ko: "밤늦게까지 야근하여 그는 매우 피곤함을 느꼈다." } },
        { zh: "考古", pinyin: "kǎogǔ", ko: "고고학", pos: "명사", ex: { zh: "他大学毕业后从事考古工作。", pinyin: "Tā dàxué bìyè hòu cóngshì kǎogǔ gōngzuò.", ko: "그는 대학 졸업 후 고고학 일에 종사했다." } },
        { zh: "镇静", pinyin: "zhènjìng", ko: "침착하다, 냉정하다", pos: "형용사", ex: { zh: "面对危险，她始终保持镇静。", pinyin: "Miànduì wēixiǎn, tā shǐzhōng bǎochí zhènjìng.", ko: "위험에 직면해서도 그녀는 시종일관 침착함을 유지했다." } },
        { zh: "遥控", pinyin: "yáokòng", ko: "원격 조종하다", pos: "동사", ex: { zh: "这架无人机可以用手机遥控。", pinyin: "Zhè jià wúrénjī kěyǐ yòng shǒujī yáokòng.", ko: "이 드론은 휴대폰으로 원격 조종할 수 있다." } },
        { zh: "排放", pinyin: "páifàng", ko: "배출하다", pos: "동사", ex: { zh: "工厂必须减少废气排放。", pinyin: "Gōngchǎng bìxū jiǎnshǎo fèiqì páifàng.", ko: "공장은 반드시 배기가스 배출을 줄여야 한다." } },
        { zh: "顽固", pinyin: "wángù", ko: "완고하다, 고집스럽다", pos: "형용사", ex: { zh: "爷爷的脾气十分顽固。", pinyin: "Yéye de píqi shífēn wángù.", ko: "할아버지의 성격은 매우 완고하다." } },
        { zh: "散布", pinyin: "sànbù", ko: "퍼뜨리다, 유포하다", pos: "동사", ex: { zh: "有人故意散布谣言扰乱人心。", pinyin: "Yǒurén gùyì sànbù yáoyán rǎoluàn rénxīn.", ko: "어떤 사람이 고의로 소문을 퍼뜨려 민심을 어지럽혔다." } },
        { zh: "搓", pinyin: "cuō", ko: "비비다, 문지르다", pos: "동사", ex: { zh: "他冷得不停地搓手。", pinyin: "Tā lěng de bùtíng de cuō shǒu.", ko: "그는 추워서 계속 손을 비볐다." } },
        { zh: "愣", pinyin: "lèng", ko: "멍해지다, 어리둥절하다", pos: "동사", ex: { zh: "听到这个消息，他愣住了。", pinyin: "Tīngdào zhège xiāoxi, tā lèngzhùle.", ko: "이 소식을 듣고 그는 멍해졌다." } },
        { zh: "颗粒", pinyin: "kēlì", ko: "낟알, 알갱이", pos: "명사", ex: { zh: "这种药是颗粒状的，需要用水冲服。", pinyin: "Zhè zhǒng yào shì kēlì zhuàng de, xūyào yòng shuǐ chōngfú.", ko: "이 약은 알갱이 형태로, 물에 타서 복용해야 한다." } },
        { zh: "构思", pinyin: "gòusī", ko: "구상하다", pos: "동사", ex: { zh: "作家花了半年时间构思这部小说。", pinyin: "Zuòjiā huāle bàn nián shíjiān gòusī zhè bù xiǎoshuō.", ko: "작가는 반년의 시간을 들여 이 소설을 구상했다." } },
        { zh: "增添", pinyin: "zēngtiān", ko: "더하다, 늘리다", pos: "동사", ex: { zh: "新家具为客厅增添了不少色彩。", pinyin: "Xīn jiājù wèi kètīng zēngtiānle bùshǎo sècǎi.", ko: "새 가구가 거실에 많은 색채를 더했다." } },
        { zh: "暧昧", pinyin: "àimèi", ko: "애매하다, 모호하다", pos: "형용사", ex: { zh: "他的态度一直很暧昧，让人捉摸不透。", pinyin: "Tā de tàidu yìzhí hěn àimèi, ràng rén zhuōmō bú tòu.", ko: "그의 태도는 줄곧 애매해서 종잡을 수가 없다." } },
        { zh: "灭亡", pinyin: "mièwáng", ko: "멸망하다", pos: "동사", ex: { zh: "这个古老的王朝最终走向灭亡。", pinyin: "Zhège gǔlǎo de wángcháo zuìzhōng zǒuxiàng mièwáng.", ko: "이 오래된 왕조는 결국 멸망으로 향했다." } },
        { zh: "弥漫", pinyin: "mímàn", ko: "자욱하다, 가득 퍼지다", pos: "동사", ex: { zh: "清晨的山谷里弥漫着薄雾。", pinyin: "Qīngchén de shāngǔ lǐ mímànzhe bó wù.", ko: "이른 아침 계곡에는 옅은 안개가 자욱하게 퍼져 있었다." } },
        { zh: "辩解", pinyin: "biànjiě", ko: "변명하다, 해명하다", pos: "동사", ex: { zh: "他不停地为自己的错误辩解。", pinyin: "Tā bùtíng de wèi zìjǐ de cuòwù biànjiě.", ko: "그는 자신의 잘못에 대해 계속 변명했다." } },
        { zh: "紧迫", pinyin: "jǐnpò", ko: "긴박하다, 절박하다", pos: "형용사", ex: { zh: "时间十分紧迫，我们必须马上行动。", pinyin: "Shíjiān shífēn jǐnpò, wǒmen bìxū mǎshàng xíngdòng.", ko: "시간이 매우 촉박하여 우리는 즉시 행동해야 한다." } },
        { zh: "规格", pinyin: "guīgé", ko: "규격, 사양", pos: "명사", ex: { zh: "这批产品必须符合国际规格。", pinyin: "Zhè pī chǎnpǐn bìxū fúhé guójì guīgé.", ko: "이 제품들은 반드시 국제 규격에 부합해야 한다." } },
        { zh: "思绪", pinyin: "sīxù", ko: "생각의 갈피, 사고의 실마리", pos: "명사", ex: { zh: "窗外的雨声打乱了她的思绪。", pinyin: "Chuāngwài de yǔshēng dǎluànle tā de sīxù.", ko: "창밖의 빗소리가 그녀의 생각을 흐트러뜨렸다." } },
        { zh: "宣扬", pinyin: "xuānyáng", ko: "선전하다, 널리 알리다", pos: "동사", ex: { zh: "媒体大力宣扬环保理念。", pinyin: "Méitǐ dàlì xuānyáng huánbǎo lǐniàn.", ko: "언론은 환경 보호 이념을 대대적으로 선전했다." } },
        { zh: "牵扯", pinyin: "qiānchě", ko: "연루되다, 연관되다", pos: "동사", ex: { zh: "这起案件牵扯到多名官员。", pinyin: "Zhè qǐ ànjiàn qiānchě dào duō míng guānyuán.", ko: "이 사건은 여러 명의 공무원과 연루되어 있다." } },
        { zh: "致使", pinyin: "zhìshǐ", ko: "초래하다, ~하게 하다", pos: "동사", ex: { zh: "操作失误致使系统瘫痪。", pinyin: "Cāozuò shīwù zhìshǐ xìtǒng tānhuàn.", ko: "조작 실수가 시스템 마비를 초래했다." } },
        { zh: "埋伏", pinyin: "máifú", ko: "매복하다", pos: "동사", ex: { zh: "士兵们在山谷两侧埋伏起来。", pinyin: "Shìbīngmen zài shāngǔ liǎng cè máifú qǐlai.", ko: "병사들은 계곡 양쪽에 매복했다." } },
        { zh: "结算", pinyin: "jiésuàn", ko: "결산하다, 정산하다", pos: "동사", ex: { zh: "月底公司要进行财务结算。", pinyin: "Yuèdǐ gōngsī yào jìnxíng cáiwù jiésuàn.", ko: "월말에 회사는 재무 결산을 진행해야 한다." } },
        { zh: "格式", pinyin: "géshì", ko: "형식, 포맷", pos: "명사", ex: { zh: "请按照统一的格式填写表格。", pinyin: "Qǐng ànzhào tǒngyī de géshì tiánxiě biǎogé.", ko: "통일된 형식에 따라 표를 작성해 주세요." } },
        { zh: "间隔", pinyin: "jiàngé", ko: "간격", pos: "명사", ex: { zh: "两趟公交车的间隔是十分钟。", pinyin: "Liǎng tàng gōngjiāochē de jiàngé shì shí fēnzhōng.", ko: "두 버스 간의 간격은 십 분이다." } },
        { zh: "表彰", pinyin: "biǎozhāng", ko: "표창하다", pos: "동사", ex: { zh: "学校表彰了成绩优秀的学生。", pinyin: "Xuéxiào biǎozhāngle chéngjì yōuxiù de xuésheng.", ko: "학교는 성적이 우수한 학생들을 표창했다." } },
        { zh: "过瘾", pinyin: "guòyǐn", ko: "만족스럽다, 짜릿하다", pos: "형용사", ex: { zh: "这场球赛看得真过瘾。", pinyin: "Zhè chǎng qiúsài kàn de zhēn guòyǐn.", ko: "이 경기는 정말 짜릿하게 봤다." } },
        { zh: "地质", pinyin: "dìzhì", ko: "지질", pos: "명사", ex: { zh: "这一地区的地质结构十分复杂。", pinyin: "Zhè yí dìqū de dìzhì jiégòu shífēn fùzá.", ko: "이 지역의 지질 구조는 매우 복잡하다." } },
        { zh: "相差", pinyin: "xiāngchà", ko: "차이가 나다", pos: "동사", ex: { zh: "两个人的年龄相差十岁。", pinyin: "Liǎng gè rén de niánlíng xiāngchà shí suì.", ko: "두 사람의 나이는 열 살 차이가 난다." } },
        { zh: "师范", pinyin: "shīfàn", ko: "사범, 교원 양성", pos: "", ex: { zh: "她毕业于一所著名的师范大学。", pinyin: "Tā bìyè yú yì suǒ zhùmíng de shīfàn dàxué.", ko: "그녀는 유명한 사범대학을 졸업했다." } },
        { zh: "寄托", pinyin: "jìtuō", ko: "의탁하다, (희망 등을) 걸다", pos: "동사", ex: { zh: "父母把所有希望都寄托在孩子身上。", pinyin: "Fùmǔ bǎ suǒyǒu xīwàng dōu jìtuō zài háizi shēnshang.", ko: "부모는 모든 희망을 아이에게 걸었다." } },
        { zh: "可观", pinyin: "kěguān", ko: "상당하다, 대단하다", pos: "형용사", ex: { zh: "公司今年的利润相当可观。", pinyin: "Gōngsī jīnnián de lìrùn xiāngdāng kěguān.", ko: "회사의 올해 이윤은 상당히 크다." } },
        { zh: "拿手", pinyin: "náshǒu", ko: "자신 있다, 특기이다", pos: "형용사", ex: { zh: "做红烧肉是他最拿手的菜。", pinyin: "Zuò hóngshāoròu shì tā zuì náshǒu de cài.", ko: "홍샤오러우를 만드는 것은 그가 가장 자신 있는 요리이다." } },
        { zh: "开阔", pinyin: "kāikuò", ko: "넓다, 트이다", pos: "동사", ex: { zh: "旅行可以开阔我们的视野。", pinyin: "Lǚxíng kěyǐ kāikuò wǒmen de shìyě.", ko: "여행은 우리의 시야를 넓혀 줄 수 있다." } },
        { zh: "脉搏", pinyin: "màibó", ko: "맥박", pos: "명사", ex: { zh: "医生仔细检查了病人的脉搏。", pinyin: "Yīshēng zǐxì jiǎnchále bìngrén de màibó.", ko: "의사는 환자의 맥박을 세심하게 검사했다." } },
        { zh: "文献", pinyin: "wénxiàn", ko: "문헌", pos: "명사", ex: { zh: "撰写论文需要查阅大量文献。", pinyin: "Zhuànxiě lùnwén xūyào cháyuè dàliàng wénxiàn.", ko: "논문을 작성하려면 대량의 문헌을 열람해야 한다." } },
        { zh: "掰", pinyin: "bāi", ko: "쪼개다, 뜯다", pos: "동사", ex: { zh: "他把面包掰成两半分给朋友。", pinyin: "Tā bǎ miànbāo bāichéng liǎng bàn fēn gěi péngyou.", ko: "그는 빵을 두 조각으로 쪼개어 친구에게 나눠 주었다." } },
        { zh: "搏斗", pinyin: "bódòu", ko: "격투하다, 싸우다", pos: "동사", ex: { zh: "他和病魔搏斗了整整三年。", pinyin: "Tā hé bìngmó bódòule zhěngzhěng sān nián.", ko: "그는 꼬박 삼 년 동안 병마와 싸웠다." } },
        { zh: "腐烂", pinyin: "fǔlàn", ko: "썩다, 부패하다", pos: "동사", ex: { zh: "天气炎热，水果很快就腐烂了。", pinyin: "Tiānqì yánrè, shuǐguǒ hěn kuài jiù fǔlàn le.", ko: "날씨가 무더워서 과일이 금세 썩어 버렸다." } },
        { zh: "照料", pinyin: "zhàoliào", ko: "돌보다, 보살피다", pos: "동사", ex: { zh: "她一直悉心照料生病的母亲。", pinyin: "Tā yìzhí xīxīn zhàoliào shēngbìng de mǔqīn.", ko: "그녀는 줄곧 정성껏 병든 어머니를 돌봤다." } },
        { zh: "飞跃", pinyin: "fēiyuè", ko: "비약하다, 도약하다", pos: "동사", ex: { zh: "这项技术实现了质的飞跃。", pinyin: "Zhè xiàng jìshù shíxiànle zhì de fēiyuè.", ko: "이 기술은 질적인 도약을 이루었다." } },
        { zh: "冷酷", pinyin: "lěngkù", ko: "냉혹하다, 무정하다", pos: "형용사", ex: { zh: "现实往往是冷酷无情的。", pinyin: "Xiànshí wǎngwǎng shì lěngkù wúqíng de.", ko: "현실은 종종 냉혹하고 무정하다." } },
        { zh: "开拓", pinyin: "kāituò", ko: "개척하다", pos: "동사", ex: { zh: "公司正在积极开拓海外市场。", pinyin: "Gōngsī zhèngzài jījí kāituò hǎiwài shìchǎng.", ko: "회사는 해외 시장을 적극적으로 개척하고 있다." } },
        { zh: "神仙", pinyin: "shénxiān", ko: "신선", pos: "명사", ex: { zh: "传说中神仙可以长生不老。", pinyin: "Chuánshuō zhōng shénxiān kěyǐ chángshēng bùlǎo.", ko: "전설에 따르면 신선은 늙지 않고 오래 살 수 있다." } },
        { zh: "柔和", pinyin: "róuhé", ko: "부드럽다, 온화하다", pos: "형용사", ex: { zh: "傍晚的阳光十分柔和。", pinyin: "Bàngwǎn de yángguāng shífēn róuhé.", ko: "저녁 무렵의 햇살은 매우 부드럽다." } },
        { zh: "昆虫", pinyin: "kūnchóng", ko: "곤충", pos: "명사", ex: { zh: "孩子们对昆虫的世界充满好奇。", pinyin: "Háizimen duì kūnchóng de shìjiè chōngmǎn hàoqí.", ko: "아이들은 곤충의 세계에 대해 호기심으로 가득 차 있다." } },
        { zh: "迫害", pinyin: "pòhài", ko: "박해하다", pos: "동사", ex: { zh: "他因为信仰而遭到迫害。", pinyin: "Tā yīnwèi xìnyǎng ér zāodào pòhài.", ko: "그는 신앙 때문에 박해를 당했다." } },
        { zh: "谅解", pinyin: "liàngjiě", ko: "양해하다, 이해하다", pos: "동사", ex: { zh: "希望大家能够谅解我的难处。", pinyin: "Xīwàng dàjiā nénggòu liàngjiě wǒ de nánchu.", ko: "여러분이 저의 어려움을 양해해 주시길 바랍니다." } },
        { zh: "颠倒", pinyin: "diāndǎo", ko: "뒤바뀌다, 전도되다", pos: "동사", ex: { zh: "他把事情的顺序完全颠倒了。", pinyin: "Tā bǎ shìqing de shùnxù wánquán diāndǎo le.", ko: "그는 일의 순서를 완전히 뒤바꿔 버렸다." } },
        { zh: "无从", pinyin: "wúcóng", ko: "~할 방법이 없다, 어찌할 수 없다", pos: "부사", ex: { zh: "事情太复杂，他无从下手。", pinyin: "Shìqing tài fùzá, tā wúcóng xiàshǒu.", ko: "일이 너무 복잡해서 그는 손을 댈 방법이 없었다." } },
        { zh: "辛勤", pinyin: "xīnqín", ko: "부지런하다, 근면하다", pos: "형용사", ex: { zh: "农民们辛勤地在田间劳作。", pinyin: "Nóngmínmen xīnqín de zài tiánjiān láozuò.", ko: "농민들은 부지런히 밭에서 일했다." } },
        { zh: "传授", pinyin: "chuánshòu", ko: "전수하다, 가르치다", pos: "동사", ex: { zh: "老师傅把手艺传授给了徒弟。", pinyin: "Lǎo shīfu bǎ shǒuyì chuánshòu gěile túdì.", ko: "늙은 스승은 기술을 제자에게 전수했다." } },
        { zh: "成天", pinyin: "chéngtiān", ko: "온종일, 하루 종일", pos: "부사", ex: { zh: "他成天坐在电脑前打游戏。", pinyin: "Tā chéngtiān zuò zài diànnǎo qián dǎ yóuxì.", ko: "그는 온종일 컴퓨터 앞에 앉아 게임을 한다." } },
        { zh: "苏醒", pinyin: "sūxǐng", ko: "소생하다, 깨어나다", pos: "동사", ex: { zh: "手术后他慢慢苏醒过来。", pinyin: "Shǒushù hòu tā mànmàn sūxǐng guòlai.", ko: "수술 후 그는 서서히 의식을 되찾았다." } },
        { zh: "解雇", pinyin: "jiěgù", ko: "해고하다", pos: "동사", ex: { zh: "公司因业绩不佳解雇了他。", pinyin: "Gōngsī yīn yèjì bùjiā jiěgùle tā.", ko: "회사는 실적이 좋지 않아 그를 해고했다." } },
        { zh: "隐患", pinyin: "yǐnhuàn", ko: "잠재적 위험, 숨은 화근", pos: "명사", ex: { zh: "老旧电线是一大安全隐患。", pinyin: "Lǎojiù diànxiàn shì yí dà ānquán yǐnhuàn.", ko: "낡은 전선은 큰 안전상의 잠재적 위험이다." } },
        { zh: "郑重", pinyin: "zhèngzhòng", ko: "정중하다, 엄숙하다", pos: "", ex: { zh: "他郑重地向大家道歉。", pinyin: "Tā zhèngzhòng de xiàng dàjiā dàoqiàn.", ko: "그는 정중하게 모두에게 사과했다." } },
      ],
    },
  ],
};

export default themes;
