/**
 * H6 (HSK 6급) 보강 어휘 — 청크 B (200개).
 * HSK 2.0 6급 표준 목록 순증분(빈도순, 전 급 교차 중복 배제) — drkameleon/complete-hsk-vocabulary(MIT) 골격.
 * zh·pinyin·pos는 소스 그대로(다음자 단일 한자는 상용 독음으로 교정), ko·예문만 생성 후 결정적 전수 검증.
 */
export default {
  themes: [
    {
      name: "HSK6 보강 B",
      icon: "🟥",
      words: [
        { zh: "空白", pinyin: "kòng bái", ko: "공백, 여백", pos: "명사", ex: { zh: "请在空白处写上你的名字。", pinyin: "Qǐng zài kòngbái chù xiěshàng nǐ de míngzi.", ko: "빈 공간에 당신의 이름을 써 주세요." } },
        { zh: "地步", pinyin: "dì bù", ko: "지경, 정도", pos: "명사", ex: { zh: "事情已经发展到严重的地步。", pinyin: "Shìqing yǐjīng fāzhǎn dào yánzhòng de dìbù.", ko: "일이 이미 심각한 지경까지 이르렀다." } },
        { zh: "伴随", pinyin: "bàn suí", ko: "동반하다, 따르다", pos: "동사", ex: { zh: "成功往往伴随着艰辛的努力。", pinyin: "Chénggōng wǎngwǎng bànsuízhe jiānxīn de nǔlì.", ko: "성공은 흔히 힘든 노력을 동반한다." } },
        { zh: "悲哀", pinyin: "bēi āi", ko: "슬프다, 비통하다", pos: "형용사", ex: { zh: "他的遭遇让人感到悲哀。", pinyin: "Tā de zāoyù ràng rén gǎndào bēi'āi.", ko: "그의 처지는 사람을 슬프게 만든다." } },
        { zh: "嘲笑", pinyin: "cháo xiào", ko: "비웃다, 조롱하다", pos: "동사", ex: { zh: "同学们不该嘲笑他的口音。", pinyin: "Tóngxuémen bù gāi cháoxiào tā de kǒuyīn.", ko: "학생들은 그의 억양을 비웃으면 안 된다." } },
        { zh: "遥远", pinyin: "yáo yuǎn", ko: "아득하다, 멀다", pos: "형용사", ex: { zh: "他来自一个遥远的国家。", pinyin: "Tā láizì yí gè yáoyuǎn de guójiā.", ko: "그는 아주 먼 나라에서 왔다." } },
        { zh: "神圣", pinyin: "shén shèng", ko: "신성하다", pos: "형용사", ex: { zh: "婚姻是一件神圣的事情。", pinyin: "Hūnyīn shì yí jiàn shénshèng de shìqing.", ko: "결혼은 신성한 일이다." } },
        { zh: "恶化", pinyin: "è huà", ko: "악화되다", pos: "동사", ex: { zh: "他的病情突然恶化了。", pinyin: "Tā de bìngqíng tūrán èhuà le.", ko: "그의 병세가 갑자기 악화되었다." } },
        { zh: "口气", pinyin: "kǒu qì", ko: "말투, 어조", pos: "명사", ex: { zh: "他用严厉的口气批评我。", pinyin: "Tā yòng yánlì de kǒuqì pīpíng wǒ.", ko: "그는 엄한 말투로 나를 비판했다." } },
        { zh: "捧", pinyin: "pěng", ko: "받쳐 들다, 받들다", pos: "동사", ex: { zh: "她双手捧着一束鲜花。", pinyin: "Tā shuāngshǒu pěngzhe yí shù xiānhuā.", ko: "그녀는 두 손으로 꽃다발을 받쳐 들었다." } },
        { zh: "指令", pinyin: "zhǐ lìng", ko: "지령, 명령", pos: "명사", ex: { zh: "士兵们服从上级的指令。", pinyin: "Shìbīngmen fúcóng shàngjí de zhǐlìng.", ko: "병사들은 상관의 명령에 복종한다." } },
        { zh: "贵族", pinyin: "guì zú", ko: "귀족", pos: "명사", ex: { zh: "他出身于一个贵族家庭。", pinyin: "Tā chūshēn yú yí gè guìzú jiātíng.", ko: "그는 귀족 가문 출신이다." } },
        { zh: "制服", pinyin: "zhì fú", ko: "제압하다, 굴복시키다", pos: "명사", ex: { zh: "警察迅速制服了嫌疑人。", pinyin: "Jǐngchá xùnsù zhìfúle xiányírén.", ko: "경찰이 신속하게 용의자를 제압했다." } },
        { zh: "勉强", pinyin: "miǎn qiǎng", ko: "억지로 하다, 마지못해", pos: "", ex: { zh: "他勉强答应了我的请求。", pinyin: "Tā miǎnqiǎng dāyingle wǒ de qǐngqiú.", ko: "그는 마지못해 나의 부탁을 들어주었다." } },
        { zh: "案例", pinyin: "àn lì", ko: "사례, 케이스", pos: "명사", ex: { zh: "这是一个典型的案例。", pinyin: "Zhè shì yí gè diǎnxíng de ànlì.", ko: "이것은 전형적인 사례이다." } },
        { zh: "毁灭", pinyin: "huǐ miè", ko: "파멸시키다, 훼멸하다", pos: "동사", ex: { zh: "战争几乎毁灭了整座城市。", pinyin: "Zhànzhēng jīhū huǐmièle zhěng zuò chéngshì.", ko: "전쟁은 도시 전체를 거의 파괴했다." } },
        { zh: "乐意", pinyin: "lè yì", ko: "기꺼이 하다, 즐거이 하다", pos: "동사", ex: { zh: "我很乐意帮助你。", pinyin: "Wǒ hěn lèyì bāngzhù nǐ.", ko: "나는 기꺼이 너를 도와주겠다." } },
        { zh: "掩饰", pinyin: "yǎn shì", ko: "감추다, 위장하다", pos: "동사", ex: { zh: "她努力掩饰内心的紧张。", pinyin: "Tā nǔlì yǎnshì nèixīn de jǐnzhāng.", ko: "그녀는 내면의 긴장을 감추려 애썼다." } },
        { zh: "掩盖", pinyin: "yǎn gài", ko: "숨기다, 덮다", pos: "동사", ex: { zh: "白雪掩盖了整片田野。", pinyin: "Báixuě yǎngàile zhěng piàn tiányě.", ko: "흰 눈이 들판 전체를 뒤덮었다." } },
        { zh: "演习", pinyin: "yǎn xí", ko: "훈련, 연습", pos: "동사", ex: { zh: "军队正在举行军事演习。", pinyin: "Jūnduì zhèngzài jǔxíng jūnshì yǎnxí.", ko: "군대가 군사 훈련을 실시하고 있다." } },
        { zh: "制止", pinyin: "zhì zhǐ", ko: "제지하다, 저지하다", pos: "동사", ex: { zh: "老师及时制止了争吵。", pinyin: "Lǎoshī jíshí zhìzhǐle zhēngchǎo.", ko: "선생님이 제때 다툼을 제지했다." } },
        { zh: "货币", pinyin: "huò bì", ko: "화폐, 통화", pos: "명사", ex: { zh: "各国的货币价值不同。", pinyin: "Gè guó de huòbì jiàzhí bùtóng.", ko: "각 나라의 화폐 가치는 다르다." } },
        { zh: "华丽", pinyin: "huá lì", ko: "화려하다", pos: "형용사", ex: { zh: "她穿着一身华丽的礼服。", pinyin: "Tā chuānzhe yì shēn huálì de lǐfú.", ko: "그녀는 화려한 예복을 입고 있다." } },
        { zh: "激发", pinyin: "jī fā", ko: "불러일으키다, 자극하다", pos: "동사", ex: { zh: "老师激发了学生的兴趣。", pinyin: "Lǎoshī jīfāle xuésheng de xìngqù.", ko: "선생님은 학생들의 흥미를 불러일으켰다." } },
        { zh: "准则", pinyin: "zhǔn zé", ko: "준칙, 기준", pos: "명사", ex: { zh: "我们应该遵守道德准则。", pinyin: "Wǒmen yīnggāi zūnshǒu dàodé zhǔnzé.", ko: "우리는 도덕적 준칙을 지켜야 한다." } },
        { zh: "报酬", pinyin: "bào chou", ko: "보수, 대가", pos: "명사", ex: { zh: "他努力工作获得了丰厚的报酬。", pinyin: "Tā nǔlì gōngzuò huòdéle fēnghòu de bàochou.", ko: "그는 열심히 일해서 후한 보수를 받았다." } },
        { zh: "极限", pinyin: "jí xiàn", ko: "극한, 한계", pos: "명사", ex: { zh: "运动员挑战了自己的极限。", pinyin: "Yùndòngyuán tiǎozhànle zìjǐ de jíxiàn.", ko: "운동선수는 자신의 한계에 도전했다." } },
        { zh: "违背", pinyin: "wéi bèi", ko: "위배하다, 어기다", pos: "동사", ex: { zh: "他的行为违背了公司规定。", pinyin: "Tā de xíngwéi wéibèile gōngsī guīdìng.", ko: "그의 행동은 회사 규정을 위배했다." } },
        { zh: "呕吐", pinyin: "ǒu tù", ko: "구토하다, 토하다", pos: "동사", ex: { zh: "他因为晕车而呕吐了。", pinyin: "Tā yīnwèi yùnchē ér ǒutù le.", ko: "그는 차멀미 때문에 토했다." } },
        { zh: "周边", pinyin: "zhōu biān", ko: "주변", pos: "명사", ex: { zh: "学校周边有很多商店。", pinyin: "Xuéxiào zhōubiān yǒu hěn duō shāngdiàn.", ko: "학교 주변에는 상점이 많다." } },
        { zh: "揍", pinyin: "zòu", ko: "때리다, 패다", pos: "동사", ex: { zh: "他被哥哥揍了一顿。", pinyin: "Tā bèi gēge zòule yí dùn.", ko: "그는 형에게 한바탕 얻어맞았다." } },
        { zh: "性命", pinyin: "xìng mìng", ko: "생명, 목숨", pos: "명사", ex: { zh: "医生救了他的性命。", pinyin: "Yīshēng jiùle tā de xìngmìng.", ko: "의사가 그의 목숨을 구했다." } },
        { zh: "预料", pinyin: "yù liào", ko: "예상하다, 예측하다", pos: "동사", ex: { zh: "事情的结果出乎预料。", pinyin: "Shìqing de jiéguǒ chūhū yùliào.", ko: "일의 결과가 예상을 벗어났다." } },
        { zh: "麻醉", pinyin: "má zuì", ko: "마취하다, 마취시키다", pos: "동사", ex: { zh: "手术前医生给病人麻醉。", pinyin: "Shǒushù qián yīshēng gěi bìngrén mázuì.", ko: "수술 전 의사는 환자를 마취시켰다." } },
        { zh: "审理", pinyin: "shěn lǐ", ko: "심리하다, 심의하다", pos: "동사", ex: { zh: "法院正在审理这起案件。", pinyin: "Fǎyuàn zhèngzài shěnlǐ zhè qǐ ànjiàn.", ko: "법원은 이 사건을 심리하고 있다." } },
        { zh: "粉色", pinyin: "fěn sè", ko: "분홍색", pos: "명사", ex: { zh: "她喜欢穿粉色的衣服。", pinyin: "Tā xǐhuan chuān fěnsè de yīfu.", ko: "그녀는 분홍색 옷 입는 것을 좋아한다." } },
        { zh: "首要", pinyin: "shǒu yào", ko: "가장 중요하다, 최우선의", pos: "형용사", ex: { zh: "安全是首要的考虑因素。", pinyin: "Ānquán shì shǒuyào de kǎolǜ yīnsù.", ko: "안전은 가장 중요한 고려 요소이다." } },
        { zh: "任意", pinyin: "rèn yì", ko: "임의로, 마음대로", pos: "부사", ex: { zh: "你可以任意选择颜色。", pinyin: "Nǐ kěyǐ rènyì xuǎnzé yánsè.", ko: "당신은 마음대로 색을 선택할 수 있다." } },
        { zh: "开除", pinyin: "kāi chú", ko: "해고하다, 제명하다", pos: "동사", ex: { zh: "公司因违规开除了他。", pinyin: "Gōngsī yīn wéiguī kāichúle tā.", ko: "회사는 규정 위반으로 그를 해고했다." } },
        { zh: "忙碌", pinyin: "máng lù", ko: "바쁘다, 분주하다", pos: "형용사", ex: { zh: "她每天都过得很忙碌。", pinyin: "Tā měitiān dōu guò de hěn mánglù.", ko: "그녀는 매일 매우 바쁘게 지낸다." } },
        { zh: "国务院", pinyin: "Guó wù yuàn", ko: "국무원", pos: "", ex: { zh: "国务院发布了新的经济政策。", pinyin: "Guó wù yuàn fā bù le xīn de jīng jì zhèng cè.", ko: "국무원은 새로운 경제 정책을 발표했다." } },
        { zh: "是非", pinyin: "shì fēi", ko: "시비, 옳고 그름", pos: "명사", ex: { zh: "他从不参与是非之争。", pinyin: "Tā cóng bù cān yù shì fēi zhī zhēng.", ko: "그는 시비에 결코 끼어들지 않는다." } },
        { zh: "言论", pinyin: "yán lùn", ko: "언론, 발언", pos: "명사", ex: { zh: "每个人都有言论自由的权利。", pinyin: "Měi gè rén dōu yǒu yán lùn zì yóu de quán lì.", ko: "모든 사람은 언론의 자유를 가질 권리가 있다." } },
        { zh: "罕见", pinyin: "hǎn jiàn", ko: "드물다, 희귀하다", pos: "형용사", ex: { zh: "这种珍稀动物十分罕见。", pinyin: "Zhè zhǒng zhēn xī dòng wù shí fēn hǎn jiàn.", ko: "이 희귀한 동물은 매우 드물다." } },
        { zh: "昏迷", pinyin: "hūn mí", ko: "혼수상태에 빠지다, 의식을 잃다", pos: "동사", ex: { zh: "他因车祸昏迷了三天。", pinyin: "Tā yīn chē huò hūn mí le sān tiān.", ko: "그는 교통사고로 사흘 동안 혼수상태에 빠졌다." } },
        { zh: "辉煌", pinyin: "huī huáng", ko: "눈부시다, 찬란하다", pos: "형용사", ex: { zh: "这座城市夜景十分辉煌。", pinyin: "Zhè zuò chéng shì yè jǐng shí fēn huī huáng.", ko: "이 도시의 야경은 매우 눈부시다." } },
        { zh: "流浪", pinyin: "liú làng", ko: "방랑하다, 떠돌다", pos: "동사", ex: { zh: "那只流浪狗一直跟着我。", pinyin: "Nà zhī liú làng gǒu yī zhí gēn zhe wǒ.", ko: "그 떠돌이 개는 계속 나를 따라왔다." } },
        { zh: "良心", pinyin: "liáng xīn", ko: "양심", pos: "명사", ex: { zh: "他做这件事完全没有良心。", pinyin: "Tā zuò zhè jiàn shì wán quán méi yǒu liáng xīn.", ko: "그는 이 일을 하면서 전혀 양심의 가책을 느끼지 않았다." } },
        { zh: "出卖", pinyin: "chū mài", ko: "팔다, 배신하다", pos: "동사", ex: { zh: "他为了钱出卖了朋友。", pinyin: "Tā wèi le qián chū mài le péng you.", ko: "그는 돈 때문에 친구를 배신했다." } },
        { zh: "魔术", pinyin: "mó shù", ko: "마술", pos: "명사", ex: { zh: "那位魔术师表演得非常精彩。", pinyin: "Nà wèi mó shù shī biǎo yǎn de fēi cháng jīng cǎi.", ko: "그 마술사는 매우 훌륭하게 공연했다." } },
        { zh: "发育", pinyin: "fā yù", ko: "발육하다, 성장하다", pos: "동사", ex: { zh: "孩子正处于发育阶段。", pinyin: "Hái zi zhèng chǔ yú fā yù jiē duàn.", ko: "아이는 지금 발육 단계에 있다." } },
        { zh: "光芒", pinyin: "guāng máng", ko: "빛, 광채", pos: "명사", ex: { zh: "太阳散发出耀眼的光芒。", pinyin: "Tài yáng sàn fā chū yào yǎn de guāng máng.", ko: "태양은 눈부신 빛을 발산한다." } },
        { zh: "额外", pinyin: "é wài", ko: "별도의, 추가의", pos: "형용사", ex: { zh: "这次任务需要额外的努力。", pinyin: "Zhè cì rèn wù xū yào é wài de nǔ lì.", ko: "이번 임무는 추가적인 노력이 필요하다." } },
        { zh: "精确", pinyin: "jīng què", ko: "정확하다", pos: "형용사", ex: { zh: "这个数据非常精确可靠。", pinyin: "Zhè ge shù jù fēi cháng jīng què kě kào.", ko: "이 데이터는 매우 정확하고 신뢰할 수 있다." } },
        { zh: "压抑", pinyin: "yā yì", ko: "억압하다, 답답하다", pos: "동사", ex: { zh: "长期压抑情绪对健康不好。", pinyin: "Cháng qī yā yì qíng xù duì jiàn kāng bù hǎo.", ko: "오랫동안 감정을 억압하는 것은 건강에 좋지 않다." } },
        { zh: "伪造", pinyin: "wěi zào", ko: "위조하다", pos: "동사", ex: { zh: "他因伪造文件被逮捕了。", pinyin: "Tā yīn wěi zào wén jiàn bèi dài bǔ le.", ko: "그는 문서를 위조해서 체포되었다." } },
        { zh: "憋", pinyin: "biē", ko: "참다, 억누르다", pos: "동사", ex: { zh: "他憋了很久终于说出真相。", pinyin: "Tā biē le hěn jiǔ zhōng yú shuō chū zhēn xiàng.", ko: "그는 오랫동안 참다가 마침내 진실을 말했다." } },
        { zh: "任命", pinyin: "rèn mìng", ko: "임명하다", pos: "동사", ex: { zh: "公司任命他为新经理。", pinyin: "Gōng sī rèn mìng tā wéi xīn jīng lǐ.", ko: "회사는 그를 새 매니저로 임명했다." } },
        { zh: "容忍", pinyin: "róng rěn", ko: "참다, 용인하다", pos: "동사", ex: { zh: "我无法容忍这种行为。", pinyin: "Wǒ wú fǎ róng rěn zhè zhǒng xíng wéi.", ko: "나는 이런 행동을 용납할 수 없다." } },
        { zh: "权益", pinyin: "quán yì", ko: "권익", pos: "명사", ex: { zh: "我们要维护消费者的权益。", pinyin: "Wǒ men yào wéi hù xiāo fèi zhě de quán yì.", ko: "우리는 소비자의 권익을 보호해야 한다." } },
        { zh: "散发", pinyin: "sàn fā", ko: "발산하다, 배포하다", pos: "동사", ex: { zh: "花朵散发出阵阵香气。", pinyin: "Huā duǒ sàn fā chū zhèn zhèn xiāng qì.", ko: "꽃이 은은한 향기를 발산한다." } },
        { zh: "丸", pinyin: "wán", ko: "알, 환약", pos: "", ex: { zh: "医生给他开了几丸药。", pinyin: "Yī shēng gěi tā kāi le jǐ wán yào.", ko: "의사는 그에게 알약 몇 알을 처방해 주었다." } },
        { zh: "折腾", pinyin: "zhē teng", ko: "뒤척이다, 들볶다, 고생시키다", pos: "동사", ex: { zh: "这件事把他折腾得筋疲力尽。", pinyin: "Zhè jiàn shì bǎ tā zhē teng de jīn pí lì jìn.", ko: "이 일은 그를 지치게 만들었다." } },
        { zh: "侮辱", pinyin: "wǔ rǔ", ko: "모욕하다", pos: "동사", ex: { zh: "你不能公开侮辱别人。", pinyin: "Nǐ bù néng gōng kāi wǔ rǔ bié rén.", ko: "당신은 공개적으로 남을 모욕해서는 안 된다." } },
        { zh: "致力于", pinyin: "zhìlìyú", ko: "~에 힘쓰다, 전념하다", pos: "", ex: { zh: "他一生致力于科学研究。", pinyin: "Tā yī shēng zhì lì yú kē xué yán jiū.", ko: "그는 평생 과학 연구에 힘썼다." } },
        { zh: "树立", pinyin: "shù lì", ko: "세우다, 수립하다", pos: "동사", ex: { zh: "老师为学生树立了榜样。", pinyin: "Lǎo shī wèi xué sheng shù lì le bǎng yàng.", ko: "선생님은 학생들에게 모범을 세워 주었다." } },
        { zh: "意图", pinyin: "yì tú", ko: "의도", pos: "명사", ex: { zh: "我不明白他的真实意图。", pinyin: "Wǒ bù míng bai tā de zhēn shí yì tú.", ko: "나는 그의 진짜 의도를 이해할 수 없다." } },
        { zh: "火焰", pinyin: "huǒ yàn", ko: "불꽃, 화염", pos: "명사", ex: { zh: "熊熊火焰照亮了夜空。", pinyin: "Xióng xióng huǒ yàn zhào liàng le yè kōng.", ko: "활활 타오르는 불꽃이 밤하늘을 밝혔다." } },
        { zh: "以免", pinyin: "yǐ miǎn", ko: "~하지 않도록", pos: "접속사", ex: { zh: "请早点出发，以免迟到。", pinyin: "Qǐng zǎo diǎn chū fā, yǐ miǎn chí dào.", ko: "늦지 않도록 일찍 출발하세요." } },
        { zh: "处境", pinyin: "chǔ jìng", ko: "처지, 상황", pos: "명사", ex: { zh: "他现在的处境十分艰难。", pinyin: "Tā xiàn zài de chǔ jìng shí fēn jiān nán.", ko: "그의 현재 처지는 매우 어렵다." } },
        { zh: "片刻", pinyin: "piàn kè", ko: "잠깐, 잠시", pos: "수사", ex: { zh: "请稍等片刻，马上就好。", pinyin: "Qǐng shāo děng piàn kè, mǎ shàng jiù hǎo.", ko: "잠시만 기다려 주세요, 곧 됩니다." } },
        { zh: "沮丧", pinyin: "jǔ sàng", ko: "낙담하다, 풀이 죽다", pos: "형용사", ex: { zh: "考试失败让他非常沮丧。", pinyin: "Kǎo shì shī bài ràng tā fēi cháng jǔ sàng.", ko: "시험에 떨어져서 그는 매우 낙담했다." } },
        { zh: "庞大", pinyin: "páng dà", ko: "거대하다, 방대하다", pos: "형용사", ex: { zh: "这个项目规模十分庞大。", pinyin: "Zhè ge xiàng mù guī mó shí fēn páng dà.", ko: "이 프로젝트의 규모는 매우 거대하다." } },
        { zh: "储备", pinyin: "chǔ bèi", ko: "비축하다, 저장하다", pos: "동사", ex: { zh: "国家储备了大量粮食。", pinyin: "Guó jiā chǔ bèi le dà liàng liáng shi.", ko: "국가는 대량의 식량을 비축했다." } },
        { zh: "盲目", pinyin: "máng mù", ko: "맹목적인, 무작정", pos: "형용사", ex: { zh: "不要盲目跟从别人的意见。", pinyin: "Bú yào máng mù gēn cóng bié rén de yì jiàn.", ko: "다른 사람의 의견을 맹목적으로 따르지 마라." } },
        { zh: "伴侣", pinyin: "bàn lǚ", ko: "반려자, 동반자", pos: "명사", ex: { zh: "他们是相伴一生的伴侣。", pinyin: "Tā men shì xiāng bàn yī shēng de bàn lǚ.", ko: "그들은 평생을 함께한 반려자이다." } },
        { zh: "书面", pinyin: "shū miàn", ko: "서면의, 문서상의", pos: "형용사", ex: { zh: "请提交书面申请材料。", pinyin: "Qǐng tí jiāo shū miàn shēn qǐng cái liào.", ko: "서면 신청 자료를 제출해 주세요." } },
        { zh: "步伐", pinyin: "bù fá", ko: "발걸음, 보조", pos: "명사", ex: { zh: "我们要加快改革的步伐。", pinyin: "Wǒ men yào jiā kuài gǎi gé de bù fá.", ko: "우리는 개혁의 걸음을 재촉해야 한다." } },
        { zh: "姿态", pinyin: "zī tài", ko: "자세, 태도", pos: "명사", ex: { zh: "他以谦虚的姿态接受批评。", pinyin: "Tā yǐ qiān xū de zī tài jiē shòu pī píng.", ko: "그는 겸손한 태도로 비판을 받아들였다." } },
        { zh: "榜样", pinyin: "bǎng yàng", ko: "본보기, 모범", pos: "명사", ex: { zh: "父母是孩子最好的榜样。", pinyin: "Fù mǔ shì hái zi zuì hǎo de bǎng yàng.", ko: "부모는 아이의 가장 좋은 본보기다." } },
        { zh: "随身", pinyin: "suí shēn", ko: "몸에 지니다, 휴대하다", pos: "부사", ex: { zh: "请随身携带身份证。", pinyin: "Qǐng suí shēn xié dài shēn fèn zhèng.", ko: "신분증을 항상 몸에 지니고 다니세요." } },
        { zh: "幼稚", pinyin: "yòu zhì", ko: "유치하다, 미숙하다", pos: "형용사", ex: { zh: "他的想法有点幼稚。", pinyin: "Tā de xiǎng fǎ yǒu diǎn yòu zhì.", ko: "그의 생각은 조금 유치하다." } },
        { zh: "诈骗", pinyin: "zhà piàn", ko: "사기치다, 속이다", pos: "동사", ex: { zh: "他因诈骗罪被起诉了。", pinyin: "Tā yīn zhà piàn zuì bèi qǐ sù le.", ko: "그는 사기죄로 기소되었다." } },
        { zh: "挽救", pinyin: "wǎn jiù", ko: "구하다, 만회하다", pos: "동사", ex: { zh: "医生全力挽救病人的生命。", pinyin: "Yī shēng quán lì wǎn jiù bìng rén de shēng mìng.", ko: "의사는 온 힘을 다해 환자의 생명을 구했다." } },
        { zh: "扩张", pinyin: "kuò zhāng", ko: "확장하다, 팽창하다", pos: "동사", ex: { zh: "公司正在扩张海外市场。", pinyin: "Gōng sī zhèng zài kuò zhāng hǎi wài shì chǎng.", ko: "회사는 해외 시장을 확장하고 있다." } },
        { zh: "眼下", pinyin: "yǎn xià", ko: "지금, 현재", pos: "명사", ex: { zh: "眼下最重要的是安全。", pinyin: "Yǎn xià zuì zhòng yào de shì ān quán.", ko: "지금 가장 중요한 것은 안전이다." } },
        { zh: "气味", pinyin: "qì wèi", ko: "냄새, 향", pos: "명사", ex: { zh: "厨房里飘出诱人的气味。", pinyin: "Chú fáng lǐ piāo chū yòu rén de qì wèi.", ko: "부엌에서 유혹적인 냄새가 풍겨 나왔다." } },
        { zh: "推测", pinyin: "tuī cè", ko: "추측하다", pos: "동사", ex: { zh: "大家都在推测事情的原因。", pinyin: "Dà jiā dōu zài tuī cè shì qing de yuán yīn.", ko: "모두들 사건의 원인을 추측하고 있다." } },
        { zh: "思念", pinyin: "sī niàn", ko: "그리워하다", pos: "동사", ex: { zh: "她时常思念远方的家人。", pinyin: "Tā shí cháng sī niàn yuǎn fāng de jiā rén.", ko: "그녀는 멀리 있는 가족을 자주 그리워한다." } },
        { zh: "刹车", pinyin: "shā chē", ko: "브레이크, 제동을 걸다", pos: "명사", ex: { zh: "司机紧急刹车避免了事故。", pinyin: "Sī jī jǐn jí shā chē bì miǎn le shì gù.", ko: "운전기사는 급브레이크를 밟아 사고를 피했다." } },
        { zh: "威力", pinyin: "wēi lì", ko: "위력", pos: "명사", ex: { zh: "台风的威力非常惊人。", pinyin: "Tái fēng de wēi lì fēi cháng jīng rén.", ko: "태풍의 위력은 매우 놀랍다." } },
        { zh: "勿", pinyin: "wù", ko: "~하지 마라", pos: "부사", ex: { zh: "公共场所请勿吸烟。", pinyin: "Gōng gòng chǎng suǒ qǐng wù xī yān.", ko: "공공장소에서는 흡연하지 마세요." } },
        { zh: "隆重", pinyin: "lóng zhòng", ko: "성대하다, 장중하다", pos: "형용사", ex: { zh: "开幕式举行得非常隆重。", pinyin: "Kāi mù shì jǔ xíng de fēi cháng lóng zhòng.", ko: "개막식은 매우 성대하게 열렸다." } },
        { zh: "迷失", pinyin: "mí shī", ko: "길을 잃다, 방향을 잃다", pos: "동사", ex: { zh: "他在森林里迷失了方向。", pinyin: "Tā zài sēn lín lǐ mí shī le fāng xiàng.", ko: "그는 숲 속에서 방향을 잃었다." } },
        { zh: "守护", pinyin: "shǒu hù", ko: "지키다, 수호하다", pos: "동사", ex: { zh: "军人守护着祖国的边疆。", pinyin: "Jūn rén shǒu hù zhe zǔ guó de biān jiāng.", ko: "군인들은 조국의 국경을 지키고 있다." } },
        { zh: "视野", pinyin: "shì yě", ko: "시야", pos: "명사", ex: { zh: "旅行开阔了他的视野。", pinyin: "Lǚ xíng kāi kuò le tā de shì yě.", ko: "여행은 그의 시야를 넓혀 주었다." } },
        { zh: "委员", pinyin: "wěi yuán", ko: "위원", pos: "명사", ex: { zh: "他被选为班级委员。", pinyin: "Tā bèi xuǎn wéi bān jí wěi yuán.", ko: "그는 학급 위원으로 선출되었다." } },
        { zh: "蹦", pinyin: "bèng", ko: "뛰다, 튀다", pos: "동사", ex: { zh: "孩子们高兴地蹦来蹦去。", pinyin: "Hái zi men gāo xìng de bèng lái bèng qù.", ko: "아이들은 신이 나서 이리저리 뛰어다녔다." } },
        { zh: "雷达", pinyin: "léi dá", ko: "레이더", pos: "명사", ex: { zh: "雷达可以探测飞机的位置。", pinyin: "Léi dá kě yǐ tàn cè fēi jī de wèi zhì.", ko: "레이더는 비행기의 위치를 탐지할 수 있다." } },
        { zh: "样品", pinyin: "yàng pǐn", ko: "견본, 샘플", pos: "명사", ex: { zh: "请先寄一份样品给我们。", pinyin: "Qǐng xiān jì yī fèn yàng pǐn gěi wǒ men.", ko: "먼저 저희에게 샘플 하나를 보내 주세요." } },
        { zh: "边界", pinyin: "biān jiè", ko: "경계, 국경", pos: "명사", ex: { zh: "两国边界发生了冲突。", pinyin: "Liǎng guó biān jiè fā shēng le chōng tū.", ko: "두 나라의 국경에서 충돌이 발생했다." } },
        { zh: "嫌疑", pinyin: "xián yí", ko: "혐의", pos: "명사", ex: { zh: "警方怀疑他有作案嫌疑。", pinyin: "Jǐng fāng huái yí tā yǒu zuò àn xián yí.", ko: "경찰은 그가 범행 혐의가 있다고 의심한다." } },
        { zh: "哎哟", pinyin: "āi yō", ko: "아이고, 어이쿠", pos: "감탄사", ex: { zh: "哎哟，我的脚被扭伤了！", pinyin: "Āi yō, wǒ de jiǎo bèi niǔ shāng le!", ko: "아이고, 내 발목을 삐었어!" } },
        { zh: "往事", pinyin: "wǎng shì", ko: "지난 일, 옛일", pos: "명사", ex: { zh: "他常常回忆童年的往事。", pinyin: "Tā cháng cháng huí yì tóng nián de wǎng shì.", ko: "그는 자주 어린 시절의 지난 일을 회상한다." } },
        { zh: "倾听", pinyin: "qīng tīng", ko: "경청하다", pos: "동사", ex: { zh: "老师认真倾听学生的意见。", pinyin: "Lǎo shī rèn zhēn qīng tīng xué sheng de yì jiàn.", ko: "선생님은 학생들의 의견을 진지하게 경청한다." } },
        { zh: "预言", pinyin: "yù yán", ko: "예언하다", pos: "동사", ex: { zh: "他的预言最终成真了。", pinyin: "Tā de yù yán zuì zhōng chéng zhēn le.", ko: "그의 예언은 결국 현실이 되었다." } },
        { zh: "噪音", pinyin: "zào yīn", ko: "소음", pos: "명사", ex: { zh: "工地的噪音影响了居民休息。", pinyin: "Gōng dì de zào yīn yǐng xiǎng le jū mín xiū xi.", ko: "공사장의 소음이 주민들의 휴식에 영향을 주었다." } },
        { zh: "瞪", pinyin: "dèng", ko: "노려보다, 눈을 크게 뜨다", pos: "동사", ex: { zh: "他生气地瞪了我一眼。", pinyin: "Tā shēng qì de dèng le wǒ yī yǎn.", ko: "그는 화가 나서 나를 노려보았다." } },
        { zh: "可恶", pinyin: "kě wù", ko: "밉살스럽다, 얄밉다", pos: "형용사", ex: { zh: "这种行为真是太可恶了。", pinyin: "Zhè zhǒng xíng wéi zhēn shi tài kě wù le.", ko: "이런 행동은 정말 너무 얄밉다." } },
        { zh: "泡沫", pinyin: "pào mò", ko: "거품", pos: "명사", ex: { zh: "经济泡沫最终会破裂。", pinyin: "Jīng jì pào mò zuì zhōng huì pò liè.", ko: "경제 거품은 결국 터지게 된다." } },
        { zh: "谴责", pinyin: "qiǎn zé", ko: "비난하다, 규탄하다", pos: "동사", ex: { zh: "国际社会强烈谴责这一行为。", pinyin: "Guó jì shè huì qiáng liè qiǎn zé zhè yī xíng wéi.", ko: "국제 사회는 이 행위를 강력히 비난했다." } },
        { zh: "论坛", pinyin: "lùn tán", ko: "포럼, 토론장", pos: "명사", ex: { zh: "我们在论坛上讨论了这个问题。", pinyin: "Wǒ men zài lùn tán shàng tǎo lùn le zhè ge wèn tí.", ko: "우리는 포럼에서 이 문제를 토론했다." } },
        { zh: "分歧", pinyin: "fēn qí", ko: "이견, 의견차이", pos: "명사", ex: { zh: "双方在价格上存在分歧。", pinyin: "Shuāng fāng zài jià gé shàng cún zài fēn qí.", ko: "양측은 가격 문제에서 이견이 있다." } },
        { zh: "城堡", pinyin: "chéng bǎo", ko: "성, 성곽", pos: "명사", ex: { zh: "那座古老的城堡吸引了很多游客。", pinyin: "Nà zuò gǔ lǎo de chéng bǎo xī yǐn le hěn duō yóu kè.", ko: "그 오래된 성은 많은 관광객을 끌어들였다." } },
        { zh: "机密", pinyin: "jī mì", ko: "기밀", pos: "명사", ex: { zh: "这份文件属于国家机密。", pinyin: "Zhè fèn wén jiàn shǔ yú guó jiā jī mì.", ko: "이 문서는 국가 기밀에 속한다." } },
        { zh: "弱点", pinyin: "ruò diǎn", ko: "약점", pos: "명사", ex: { zh: "每个人都有自己的弱点。", pinyin: "Měi gè rén dōu yǒu zì jǐ de ruò diǎn.", ko: "모든 사람은 자신만의 약점이 있다." } },
        { zh: "灿烂", pinyin: "càn làn", ko: "찬란하다, 눈부시다", pos: "형용사", ex: { zh: "星空显得格外灿烂。", pinyin: "Xīng kōng xiǎn de gé wài càn làn.", ko: "별이 빛나는 하늘이 유난히 찬란하다." } },
        { zh: "损坏", pinyin: "sǔn huài", ko: "손상시키다, 파손하다", pos: "동사", ex: { zh: "台风损坏了很多房屋。", pinyin: "Tái fēng sǔn huài le hěn duō fáng wū.", ko: "태풍이 많은 집을 파손했다." } },
        { zh: "验证", pinyin: "yàn zhèng", ko: "검증하다", pos: "동사", ex: { zh: "科学家需要验证这个假设。", pinyin: "Kē xué jiā xū yào yàn zhèng zhè ge jiǎ shè.", ko: "과학자들은 이 가설을 검증해야 한다." } },
        { zh: "拘留", pinyin: "jū liú", ko: "구류하다, 구금하다", pos: "동사", ex: { zh: "警方将嫌疑人拘留审查。", pinyin: "Jǐng fāng jiāng xián yí rén jū liú shěn chá.", ko: "경찰은 용의자를 구류하여 조사했다." } },
        { zh: "蛋白质", pinyin: "dàn bái zhì", ko: "단백질", pos: "명사", ex: { zh: "鸡蛋含有丰富的蛋白质。", pinyin: "Jī dàn hán yǒu fēng fù de dàn bái zhì.", ko: "계란에는 단백질이 풍부하게 들어 있다." } },
        { zh: "古怪", pinyin: "gǔ guài", ko: "이상하다, 괴상하다", pos: "형용사", ex: { zh: "他的想法非常古怪。", pinyin: "Tā de xiǎng fǎ fēi cháng gǔ guài.", ko: "그의 생각은 매우 괴상하다." } },
        { zh: "岩石", pinyin: "yán shí", ko: "암석, 바위", pos: "명사", ex: { zh: "这座山上有很多岩石。", pinyin: "Zhè zuò shān shang yǒu hěn duō yán shí.", ko: "이 산에는 바위가 많다." } },
        { zh: "精致", pinyin: "jīng zhì", ko: "정교하다, 섬세하다", pos: "형용사", ex: { zh: "这件工艺品做得非常精致。", pinyin: "Zhè jiàn gōng yì pǐn zuò de fēi cháng jīng zhì.", ko: "이 공예품은 매우 정교하게 만들어졌다." } },
        { zh: "出身", pinyin: "chū shēn", ko: "출신이다, 태생이다", pos: "동사", ex: { zh: "他出身于一个贫穷的家庭。", pinyin: "Tā chū shēn yú yí gè pín qióng de jiā tíng.", ko: "그는 가난한 집안 출신이다." } },
        { zh: "动静", pinyin: "dòng jìng", ko: "동정, 낌새, 인기척", pos: "명사", ex: { zh: "屋里一点动静都没有。", pinyin: "Wū li yì diǎn dòng jìng dōu méi yǒu.", ko: "방 안에는 아무 인기척도 없었다." } },
        { zh: "授予", pinyin: "shòu yǔ", ko: "수여하다", pos: "동사", ex: { zh: "学校授予他博士学位。", pinyin: "Xué xiào shòu yǔ tā bó shì xué wèi.", ko: "학교는 그에게 박사 학위를 수여했다." } },
        { zh: "臂", pinyin: "bì", ko: "팔", pos: "", ex: { zh: "他伸出手臂拥抱了我。", pinyin: "Tā shēn chū shǒu bì yōng bào le wǒ.", ko: "그는 팔을 뻗어 나를 안아 주었다." } },
        { zh: "掐", pinyin: "qiā", ko: "꼬집다, 따다", pos: "동사", ex: { zh: "她轻轻掐了我一下。", pinyin: "Tā qīng qīng qiā le wǒ yí xià.", ko: "그녀는 나를 살짝 꼬집었다." } },
        { zh: "忠实", pinyin: "zhōng shí", ko: "충실하다", pos: "형용사", ex: { zh: "他是一位忠实的朋友。", pinyin: "Tā shì yí wèi zhōng shí de péng you.", ko: "그는 충실한 친구이다." } },
        { zh: "保管", pinyin: "bǎo guǎn", ko: "보관하다", pos: "동사", ex: { zh: "请把贵重物品保管好。", pinyin: "Qǐng bǎ guì zhòng wù pǐn bǎo guǎn hǎo.", ko: "귀중품을 잘 보관해 주세요." } },
        { zh: "视力", pinyin: "shì lì", ko: "시력", pos: "명사", ex: { zh: "他的视力越来越差了。", pinyin: "Tā de shì lì yuè lái yuè chà le.", ko: "그의 시력은 점점 나빠지고 있다." } },
        { zh: "战役", pinyin: "zhàn yì", ko: "전투, 전역", pos: "명사", ex: { zh: "这是一场重要的战役。", pinyin: "Zhè shì yì chǎng zhòng yào de zhàn yì.", ko: "이것은 중요한 전투이다." } },
        { zh: "坦白", pinyin: "tǎn bái", ko: "솔직하다, 자백하다", pos: "동사", ex: { zh: "他向警察坦白了一切。", pinyin: "Tā xiàng jǐng chá tǎn bái le yí qiè.", ko: "그는 경찰에게 모든 것을 자백했다." } },
        { zh: "掩护", pinyin: "yǎn hù", ko: "엄호하다, 보호하다", pos: "동사", ex: { zh: "士兵们互相掩护前进。", pinyin: "Shì bīng men hù xiāng yǎn hù qián jìn.", ko: "병사들은 서로 엄호하며 전진했다." } },
        { zh: "虐待", pinyin: "nu:è dài", ko: "학대하다", pos: "동사", ex: { zh: "我们坚决反对虐待动物。", pinyin: "Wǒ men jiān jué fǎn duì nüè dài dòng wù.", ko: "우리는 동물 학대에 단호히 반대한다." } },
        { zh: "胃口", pinyin: "wèi kǒu", ko: "식욕, 구미", pos: "명사", ex: { zh: "今天他一点胃口都没有。", pinyin: "Jīn tiān tā yì diǎn wèi kǒu dōu méi yǒu.", ko: "오늘 그는 식욕이 전혀 없다." } },
        { zh: "虚假", pinyin: "xū jiǎ", ko: "허위의, 거짓의", pos: "형용사", ex: { zh: "这条新闻完全是虚假的。", pinyin: "Zhè tiáo xīn wén wán quán shì xū jiǎ de.", ko: "이 뉴스는 완전히 거짓이다." } },
        { zh: "采集", pinyin: "cǎi jí", ko: "채집하다, 수집하다", pos: "동사", ex: { zh: "学生们去山上采集标本。", pinyin: "Xué sheng men qù shān shang cǎi jí biāo běn.", ko: "학생들은 산에 가서 표본을 채집했다." } },
        { zh: "种族", pinyin: "zhǒng zú", ko: "종족, 인종", pos: "명사", ex: { zh: "我们反对种族歧视。", pinyin: "Wǒ men fǎn duì zhǒng zú qí shì.", ko: "우리는 인종 차별에 반대한다." } },
        { zh: "生态", pinyin: "shēng tài", ko: "생태", pos: "명사", ex: { zh: "保护生态环境十分重要。", pinyin: "Bǎo hù shēng tài huán jìng shí fēn zhòng yào.", ko: "생태 환경 보호는 매우 중요하다." } },
        { zh: "舔", pinyin: "tiǎn", ko: "핥다", pos: "동사", ex: { zh: "小狗舔了舔主人的手。", pinyin: "Xiǎo gǒu tiǎn le tiǎn zhǔ rén de shǒu.", ko: "강아지는 주인의 손을 핥았다." } },
        { zh: "崭新", pinyin: "zhǎn xīn", ko: "참신한, 새로운", pos: "형용사", ex: { zh: "他买了一辆崭新的汽车。", pinyin: "Tā mǎi le yí liàng zhǎn xīn de qì chē.", ko: "그는 완전히 새 자동차를 샀다." } },
        { zh: "智商", pinyin: "zhì shāng", ko: "지능지수, 아이큐", pos: "명사", ex: { zh: "这个孩子智商很高。", pinyin: "Zhè ge hái zi zhì shāng hěn gāo.", ko: "이 아이는 아이큐가 매우 높다." } },
        { zh: "副作用", pinyin: "fù zuò yòng", ko: "부작용", pos: "명사", ex: { zh: "这种药有一定的副作用。", pinyin: "Zhè zhǒng yào yǒu yí dìng de fù zuò yòng.", ko: "이 약은 어느 정도 부작용이 있다." } },
        { zh: "奴隶", pinyin: "nú lì", ko: "노예", pos: "명사", ex: { zh: "古代社会有很多奴隶。", pinyin: "Gǔ dài shè huì yǒu hěn duō nú lì.", ko: "고대 사회에는 노예가 많았다." } },
        { zh: "无知", pinyin: "wú zhī", ko: "무지하다", pos: "형용사", ex: { zh: "他的话暴露了他的无知。", pinyin: "Tā de huà bào lù le tā de wú zhī.", ko: "그의 말은 그의 무지를 드러냈다." } },
        { zh: "万分", pinyin: "wàn fēn", ko: "극히, 대단히", pos: "부사", ex: { zh: "我万分感谢你的帮助。", pinyin: "Wǒ wàn fēn gǎn xiè nǐ de bāng zhù.", ko: "당신의 도움에 대단히 감사드립니다." } },
        { zh: "旗帜", pinyin: "qí zhì", ko: "깃발, 기치", pos: "명사", ex: { zh: "广场上飘扬着旗帜。", pinyin: "Guǎng chǎng shang piāo yáng zhe qí zhì.", ko: "광장에 깃발이 휘날리고 있다." } },
        { zh: "纯洁", pinyin: "chún jié", ko: "순결하다, 깨끗하다", pos: "형용사", ex: { zh: "她有一颗纯洁的心。", pinyin: "Tā yǒu yì kē chún jié de xīn.", ko: "그녀는 순결한 마음을 가지고 있다." } },
        { zh: "揭露", pinyin: "jiē lù", ko: "폭로하다, 드러내다", pos: "동사", ex: { zh: "记者揭露了这个骗局。", pinyin: "Jì zhě jiē lù le zhè ge piàn jú.", ko: "기자는 이 사기극을 폭로했다." } },
        { zh: "吩咐", pinyin: "fēn fù", ko: "분부하다, 지시하다", pos: "동사", ex: { zh: "妈妈吩咐我早点回家。", pinyin: "Mā ma fēn fù wǒ zǎo diǎn huí jiā.", ko: "엄마는 나에게 일찍 집에 오라고 분부했다." } },
        { zh: "导航", pinyin: "dǎo háng", ko: "내비게이션, 항해 안내하다", pos: "동사", ex: { zh: "手机可以帮我们导航。", pinyin: "Shǒu jī kě yǐ bāng wǒ men dǎo háng.", ko: "휴대폰이 우리에게 길 안내를 해 줄 수 있다." } },
        { zh: "挽回", pinyin: "wǎn huí", ko: "만회하다, 되돌리다", pos: "동사", ex: { zh: "他努力挽回了损失。", pinyin: "Tā nǔ lì wǎn huí le sǔn shī.", ko: "그는 노력해서 손실을 만회했다." } },
        { zh: "三角", pinyin: "sān jiǎo", ko: "삼각, 세모", pos: "명사", ex: { zh: "黑板上画着一个三角。", pinyin: "Hēi bǎn shang huà zhe yí gè sān jiǎo.", ko: "칠판에 삼각형이 그려져 있다." } },
        { zh: "条约", pinyin: "tiáo yuē", ko: "조약", pos: "명사", ex: { zh: "两国签订了和平条约。", pinyin: "Liǎng guó qiān dìng le hé píng tiáo yuē.", ko: "두 나라는 평화 조약을 체결했다." } },
        { zh: "塑造", pinyin: "sù zào", ko: "형상화하다, 만들어내다", pos: "동사", ex: { zh: "电影塑造了一个英雄形象。", pinyin: "Diàn yǐng sù zào le yí gè yīng xióng xíng xiàng.", ko: "영화는 영웅적인 이미지를 형상화했다." } },
        { zh: "连锁", pinyin: "lián suǒ", ko: "연쇄적인, 체인의", pos: "동사", ex: { zh: "这是一家连锁餐厅。", pinyin: "Zhè shì yì jiā lián suǒ cān tīng.", ko: "이곳은 체인 레스토랑이다." } },
        { zh: "疲惫", pinyin: "pí bèi", ko: "지치다, 피로하다", pos: "형용사", ex: { zh: "他工作一整天感到十分疲惫。", pinyin: "Tā gōng zuò yì zhěng tiān gǎn dào shí fēn pí bèi.", ko: "그는 하루 종일 일해서 매우 지쳤다." } },
        { zh: "莫名其妙", pinyin: "mò míng qí miào", ko: "영문을 모르다, 이상야릇하다", pos: "관용구", ex: { zh: "他的举动让人莫名其妙。", pinyin: "Tā de jǔ dòng ràng rén mò míng qí miào.", ko: "그의 행동은 영문을 알 수 없었다." } },
        { zh: "束缚", pinyin: "shù fù", ko: "속박하다, 구속하다", pos: "동사", ex: { zh: "传统观念束缚着她。", pinyin: "Chuán tǒng guān niàn shù fù zhe tā.", ko: "전통적인 관념이 그녀를 속박하고 있다." } },
        { zh: "债券", pinyin: "zhài quàn", ko: "채권", pos: "명사", ex: { zh: "他买了一些政府债券。", pinyin: "Tā mǎi le yì xiē zhèng fǔ zhài quàn.", ko: "그는 정부 채권을 좀 샀다." } },
        { zh: "复活", pinyin: "fù huó", ko: "부활하다, 되살아나다", pos: "동사", ex: { zh: "春天万物开始复活。", pinyin: "Chūn tiān wàn wù kāi shǐ fù huó.", ko: "봄이 되면 만물이 되살아나기 시작한다." } },
        { zh: "蔓延", pinyin: "màn yán", ko: "만연하다, 퍼지다", pos: "동사", ex: { zh: "火势迅速向四周蔓延。", pinyin: "Huǒ shì xùn sù xiàng sì zhōu màn yán.", ko: "불길이 사방으로 빠르게 번졌다." } },
        { zh: "不妨", pinyin: "bù fáng", ko: "무방하다, ~하는 것도 좋다", pos: "부사", ex: { zh: "你不妨试试这个方法。", pinyin: "Nǐ bù fáng shì shi zhè ge fāng fǎ.", ko: "이 방법을 한번 시도해 보는 것도 좋겠다." } },
        { zh: "终究", pinyin: "zhōng jiū", ko: "결국, 끝내", pos: "부사", ex: { zh: "谎言终究会被揭穿。", pinyin: "Huǎng yán zhōng jiū huì bèi jiē chuān.", ko: "거짓말은 결국 들통나게 된다." } },
        { zh: "表决", pinyin: "biǎo jué", ko: "표결하다", pos: "동사", ex: { zh: "大家举手表决这个提案。", pinyin: "Dà jiā jǔ shǒu biǎo jué zhè ge tí àn.", ko: "모두가 손을 들어 이 안건을 표결했다." } },
        { zh: "疑惑", pinyin: "yí huò", ko: "의혹을 품다, 의심하다", pos: "동사", ex: { zh: "他的解释让人疑惑。", pinyin: "Tā de jiě shì ràng rén yí huò.", ko: "그의 설명은 사람을 의심하게 만들었다." } },
        { zh: "开支", pinyin: "kāi zhī", ko: "지출, 경비", pos: "명사", ex: { zh: "家庭开支越来越大。", pinyin: "Jiā tíng kāi zhī yuè lái yuè dà.", ko: "가정 지출이 점점 커지고 있다." } },
        { zh: "擅自", pinyin: "shàn zì", ko: "제멋대로, 함부로", pos: "부사", ex: { zh: "请勿擅自离开岗位。", pinyin: "Qǐng wù shàn zì lí kāi gǎng wèi.", ko: "함부로 자리를 이탈하지 마세요." } },
        { zh: "目睹", pinyin: "mù dǔ", ko: "목격하다", pos: "동사", ex: { zh: "我亲眼目睹了这场事故。", pinyin: "Wǒ qīn yǎn mù dǔ le zhè chǎng shì gù.", ko: "나는 이 사고를 직접 목격했다." } },
        { zh: "刊登", pinyin: "kān dēng", ko: "게재하다, 싣다", pos: "동사", ex: { zh: "这篇文章刊登在报纸上。", pinyin: "Zhè piān wén zhāng kān dēng zài bào zhǐ shang.", ko: "이 글은 신문에 게재되었다." } },
        { zh: "泄露", pinyin: "xiè lù", ko: "누설하다, 유출하다", pos: "동사", ex: { zh: "他不小心泄露了秘密。", pinyin: "Tā bù xiǎo xīn xiè lù le mì mì.", ko: "그는 실수로 비밀을 누설했다." } },
        { zh: "拖延", pinyin: "tuō yán", ko: "지연시키다, 미루다", pos: "동사", ex: { zh: "别再拖延这件事情了。", pinyin: "Bié zài tuō yán zhè jiàn shì qing le.", ko: "이 일을 더 이상 미루지 마라." } },
        { zh: "无耻", pinyin: "wú chǐ", ko: "파렴치하다, 뻔뻔하다", pos: "형용사", ex: { zh: "他的行为真是无耻。", pinyin: "Tā de xíng wéi zhēn shì wú chǐ.", ko: "그의 행동은 정말 파렴치하다." } },
        { zh: "文物", pinyin: "wén wù", ko: "문물, 문화재", pos: "명사", ex: { zh: "博物馆收藏了很多文物。", pinyin: "Bó wù guǎn shōu cáng le hěn duō wén wù.", ko: "박물관은 많은 문화재를 소장하고 있다." } },
        { zh: "昂贵", pinyin: "áng guì", ko: "비싸다, 값비싸다", pos: "형용사", ex: { zh: "这件首饰非常昂贵。", pinyin: "Zhè jiàn shǒu shì fēi cháng áng guì.", ko: "이 장신구는 매우 비싸다." } },
        { zh: "卡通", pinyin: "kǎ tōng", ko: "카툰, 만화", pos: "명사", ex: { zh: "孩子们喜欢看卡通片。", pinyin: "Hái zi men xǐ huan kàn kǎ tōng piàn.", ko: "아이들은 만화 영화를 즐겨 본다." } },
        { zh: "奔驰", pinyin: "Bēn chí", ko: "벤츠(자동차 브랜드)", pos: "명사", ex: { zh: "他开着一辆奔驰去上班。", pinyin: "Tā kāi zhe yí liàng Bēn chí qù shàng bān.", ko: "그는 벤츠를 몰고 출근한다." } },
        { zh: "生效", pinyin: "shēng xiào", ko: "효력을 발생하다, 발효되다", pos: "동사", ex: { zh: "这项法律明天生效。", pinyin: "Zhè xiàng fǎ lǜ míng tiān shēng xiào.", ko: "이 법률은 내일 발효된다." } },
        { zh: "兑现", pinyin: "duì xiàn", ko: "현금으로 바꾸다, 이행하다", pos: "동사", ex: { zh: "他终于兑现了自己的承诺。", pinyin: "Tā zhōng yú duì xiàn le zì jǐ de chéng nuò.", ko: "그는 마침내 자신의 약속을 이행했다." } },
        { zh: "拳头", pinyin: "quán tou", ko: "주먹", pos: "명사", ex: { zh: "他生气地握紧拳头。", pinyin: "Tā shēng qì de wò jǐn quán tou.", ko: "그는 화가 나서 주먹을 꽉 쥐었다." } },
        { zh: "遵循", pinyin: "zūn xún", ko: "준수하다, 따르다", pos: "동사", ex: { zh: "大家都要遵循交通规则。", pinyin: "Dà jiā dōu yào zūn xún jiāo tōng guī zé.", ko: "모두 교통 규칙을 준수해야 한다." } },
        { zh: "下属", pinyin: "xià shǔ", ko: "부하, 하급자", pos: "동사", ex: { zh: "他对下属非常严格。", pinyin: "Tā duì xià shǔ fēi cháng yán gé.", ko: "그는 부하 직원에게 매우 엄격하다." } },
        { zh: "可行", pinyin: "kě xíng", ko: "가능하다, 실행할 수 있다", pos: "형용사", ex: { zh: "这个方案完全可行。", pinyin: "Zhè ge fāng àn wán quán kě xíng.", ko: "이 방안은 완전히 실현 가능하다." } },
        { zh: "喜悦", pinyin: "xǐ yuè", ko: "기쁘다, 즐겁다", pos: "형용사", ex: { zh: "她脸上充满了喜悦。", pinyin: "Tā liǎn shàng chōng mǎn le xǐ yuè.", ko: "그녀의 얼굴에는 기쁨이 가득했다." } },
        { zh: "引用", pinyin: "yǐn yòng", ko: "인용하다", pos: "동사", ex: { zh: "他在文章中引用了名言。", pinyin: "Tā zài wén zhāng zhōng yǐn yòng le míng yán.", ko: "그는 글에서 명언을 인용했다." } },
        { zh: "作弊", pinyin: "zuò bì", ko: "부정행위를 하다, 커닝하다", pos: "동사", ex: { zh: "考试作弊是不诚实的。", pinyin: "Kǎo shì zuò bì shì bù chéng shí de.", ko: "시험에서 부정행위를 하는 것은 부정직한 일이다." } },
        { zh: "惊奇", pinyin: "jīng qí", ko: "놀랍다, 경이롭다", pos: "형용사", ex: { zh: "大家都对结果感到惊奇。", pinyin: "Dà jiā dōu duì jié guǒ gǎn dào jīng qí.", ko: "모두가 결과에 놀랐다." } },
        { zh: "厌恶", pinyin: "yàn wù", ko: "혐오하다, 싫어하다", pos: "동사", ex: { zh: "她厌恶那种虚伪的人。", pinyin: "Tā yàn wù nà zhǒng xū wěi de rén.", ko: "그녀는 그런 위선적인 사람을 혐오한다." } },
        { zh: "偿还", pinyin: "cháng huán", ko: "상환하다, 갚다", pos: "동사", ex: { zh: "他按时偿还了贷款。", pinyin: "Tā àn shí cháng huán le dài kuǎn.", ko: "그는 제때 대출금을 상환했다." } },
        { zh: "啃", pinyin: "kěn", ko: "갉아먹다, 물어뜯다", pos: "동사", ex: { zh: "小狗在啃一根骨头。", pinyin: "Xiǎo gǒu zài kěn yì gēn gǔ tou.", ko: "강아지가 뼈다귀를 물어뜯고 있다." } },
        { zh: "吸取", pinyin: "xī qǔ", ko: "흡수하다, 받아들이다", pos: "동사", ex: { zh: "我们应该吸取这次教训。", pinyin: "Wǒ men yīng gāi xī qǔ zhè cì jiào xun.", ko: "우리는 이번 교훈을 받아들여야 한다." } },
        { zh: "帐篷", pinyin: "zhàng peng", ko: "텐트, 천막", pos: "명사", ex: { zh: "我们在山上搭了帐篷。", pinyin: "Wǒ men zài shān shang dā le zhàng peng.", ko: "우리는 산에서 텐트를 쳤다." } },
        { zh: "偏偏", pinyin: "piān piān", ko: "하필, 공교롭게도", pos: "부사", ex: { zh: "偏偏这时候下起雨来。", pinyin: "Piān piān zhè shí hou xià qǐ yǔ lái.", ko: "하필 이때 비가 내리기 시작했다." } },
        { zh: "统统", pinyin: "tǒng tǒng", ko: "모두, 전부", pos: "부사", ex: { zh: "他把东西统统卖掉了。", pinyin: "Tā bǎ dōng xi tǒng tǒng mài diào le.", ko: "그는 물건을 모두 팔아 버렸다." } },
        { zh: "要命", pinyin: "yào mìng", ko: "목숨을 앗아가다, 지독하다, 죽을 지경이다", pos: "동사", ex: { zh: "今天天气热得要命。", pinyin: "Jīn tiān tiān qì rè de yào mìng.", ko: "오늘 날씨가 지독하게 덥다." } },
        { zh: "颤抖", pinyin: "chàn dǒu", ko: "떨다, 전율하다", pos: "동사", ex: { zh: "他冷得浑身不停颤抖。", pinyin: "Tā lěng de hún shēn bù tíng chàn dǒu.", ko: "그는 추워서 온몸을 계속 떨었다." } },
        { zh: "解剖", pinyin: "jiě pōu", ko: "해부하다, 분석하다", pos: "동사", ex: { zh: "学生们在课上解剖青蛙。", pinyin: "Xué sheng men zài kè shàng jiě pōu qīng wā.", ko: "학생들은 수업 시간에 개구리를 해부했다." } },
        { zh: "雕塑", pinyin: "diāo sù", ko: "조각상, 조소", pos: "명사", ex: { zh: "广场中央有一座雕塑。", pinyin: "Guǎng chǎng zhōng yāng yǒu yí zuò diāo sù.", ko: "광장 중앙에는 조각상이 하나 있다." } },
      ],
    },
  ],
};
