/**
 * H6 (HSK 6급) 보강 어휘 — 청크 A (200개).
 * HSK 2.0 6급 표준 목록 순증분(빈도순, 전 급 교차 중복 배제) — drkameleon/complete-hsk-vocabulary(MIT) 골격.
 * zh·pinyin·pos는 소스 그대로(다음자 단일 한자는 상용 독음으로 교정), ko·예문만 생성 후 결정적 전수 검증.
 */
const themes = {
  themes: [
    {
      name: "HSK6 보강 A",
      icon: "🟥",
      words: [
        { zh: "啥", pinyin: "shá", ko: "무엇, 뭐", pos: "대명사", ex: { zh: "你心里到底在想啥,快说。", pinyin: "Nǐ xīnli dàodǐ zài xiǎng shá, kuài shuō.", ko: "너 속으로 도대체 뭘 생각하는 거야, 빨리 말해." } },
        { zh: "同志", pinyin: "tóngzhì", ko: "동지, (속어) 동성애자", pos: "명사", ex: { zh: "他是我多年的老同志。", pinyin: "Tā shì wǒ duōnián de lǎo tóngzhì.", ko: "그는 나의 오랜 동지이다." } },
        { zh: "而已", pinyin: "éryǐ", ko: "~일 뿐이다, ~에 지나지 않다", pos: "조사", ex: { zh: "这只是个开始而已。", pinyin: "Zhè zhǐshì gè kāishǐ éryǐ.", ko: "이것은 그저 시작일 뿐이다." } },
        { zh: "案件", pinyin: "ànjiàn", ko: "사건", pos: "명사", ex: { zh: "警方正在调查这起案件。", pinyin: "Jǐngfāng zhèngzài diàochá zhè qǐ ànjiàn.", ko: "경찰이 이 사건을 조사하고 있다." } },
        { zh: "家伙", pinyin: "jiāhuo", ko: "녀석, 놈; 도구", pos: "명사", ex: { zh: "这个家伙真是讨厌极了。", pinyin: "Zhège jiāhuo zhēnshi tǎoyàn jíle.", ko: "이 녀석 정말 짜증나 죽겠다." } },
        { zh: "欧洲", pinyin: "Oūzhōu", ko: "유럽", pos: "명사", ex: { zh: "他计划明年去欧洲旅行。", pinyin: "Tā jìhuà míngnián qù Ōuzhōu lǚxíng.", ko: "그는 내년에 유럽으로 여행 갈 계획이다." } },
        { zh: "州", pinyin: "zhōu", ko: "주(행정구역), (옛) 지방", pos: "명사", ex: { zh: "这是美国的一个州。", pinyin: "Zhè shì Měiguó de yī gè zhōu.", ko: "이곳은 미국의 한 주이다." } },
        { zh: "袭击", pinyin: "xíjī", ko: "습격하다, 공격하다", pos: "동사", ex: { zh: "敌军突然袭击了村庄。", pinyin: "Díjūn tūrán xíjī le cūnzhuāng.", ko: "적군이 갑자기 마을을 습격했다." } },
        { zh: "感染", pinyin: "gǎnrǎn", ko: "감염되다, (감정 등에) 감화되다", pos: "동사", ex: { zh: "伤口不小心感染了。", pinyin: "Shāngkǒu bù xiǎoxīn gǎnrǎn le.", ko: "상처가 실수로 감염되었다." } },
        { zh: "砸", pinyin: "zá", ko: "부수다, 깨뜨리다; 실패하다", pos: "동사", ex: { zh: "他一拳砸碎了玻璃。", pinyin: "Tā yī quán zásuì le bōli.", ko: "그는 주먹 한 방으로 유리를 부쉈다." } },
        { zh: "生物", pinyin: "shēngwù", ko: "생물", pos: "명사", ex: { zh: "海洋里有很多奇特的生物。", pinyin: "Hǎiyáng lǐ yǒu hěnduō qítè de shēngwù.", ko: "바다에는 신기한 생물이 많다." } },
        { zh: "性感", pinyin: "xìnggǎn", ko: "섹시하다, 관능적이다", pos: "형용사", ex: { zh: "她今天穿得非常性感。", pinyin: "Tā jīntiān chuān de fēicháng xìnggǎn.", ko: "그녀는 오늘 매우 섹시하게 입었다." } },
        { zh: "毫无", pinyin: "háowú", ko: "전혀 없다, 조금도 ~않다", pos: "동사", ex: { zh: "他对此事毫无兴趣。", pinyin: "Tā duì cǐ shì háowú xìngqù.", ko: "그는 이 일에 전혀 흥미가 없다." } },
        { zh: "并非", pinyin: "bìngfēi", ko: "결코 ~이 아니다", pos: "동사", ex: { zh: "事实并非如此简单。", pinyin: "Shìshí bìngfēi rúcǐ jiǎndān.", ko: "사실은 결코 이렇게 간단하지 않다." } },
        { zh: "非法", pinyin: "fēifǎ", ko: "불법의", pos: "형용사", ex: { zh: "非法交易将受到严惩。", pinyin: "Fēifǎ jiāoyì jiāng shòudào yánchéng.", ko: "불법 거래는 엄중한 처벌을 받을 것이다." } },
        { zh: "盯", pinyin: "dīng", ko: "응시하다, 뚫어지게 보다", pos: "동사", ex: { zh: "他一直盯着屏幕看。", pinyin: "Tā yīzhí dīngzhe píngmù kàn.", ko: "그는 계속 화면을 뚫어지게 쳐다봤다." } },
        { zh: "尸体", pinyin: "shītǐ", ko: "시체", pos: "명사", ex: { zh: "警察在河边发现了尸体。", pinyin: "Jǐngchá zài hébiān fāxiàn le shītǐ.", ko: "경찰이 강가에서 시체를 발견했다." } },
        { zh: "艘", pinyin: "sōu", ko: "척(배를 세는 양사)", pos: "양사", ex: { zh: "港口停着几艘渔船。", pinyin: "Gǎngkǒu tíngzhe jǐ sōu yúchuán.", ko: "항구에 어선 몇 척이 정박해 있다." } },
        { zh: "灵魂", pinyin: "línghún", ko: "영혼", pos: "명사", ex: { zh: "音乐能触动人的灵魂。", pinyin: "Yīnyuè néng chùdòng rén de línghún.", ko: "음악은 사람의 영혼을 감동시킬 수 있다." } },
        { zh: "凌晨", pinyin: "língchén", ko: "새벽녘, 이른 새벽", pos: "명사", ex: { zh: "他凌晨三点才睡觉。", pinyin: "Tā língchén sān diǎn cái shuìjiào.", ko: "그는 새벽 세 시가 되어서야 잠들었다." } },
        { zh: "淘汰", pinyin: "táotài", ko: "도태되다, 도태시키다", pos: "동사", ex: { zh: "落后的技术终将被淘汰。", pinyin: "Luòhòu de jìshù zhōng jiāng bèi táotài.", ko: "낙후된 기술은 결국 도태될 것이다." } },
        { zh: "释放", pinyin: "shìfàng", ko: "석방하다, 방출하다", pos: "동사", ex: { zh: "他终于被无罪释放了。", pinyin: "Tā zhōngyú bèi wúzuì shìfàng le.", ko: "그는 마침내 무죄로 석방되었다." } },
        { zh: "嗨", pinyin: "hāi", ko: "안녕, 이봐, 어이", pos: "감탄사", ex: { zh: "嗨,你终于来了,好久不见!", pinyin: "Hāi, nǐ zhōngyú lái le, hǎojiǔ bùjiàn!", ko: "이봐, 드디어 왔구나, 오랜만이야!" } },
        { zh: "嘿", pinyin: "hēi", ko: "이봐, 어이", pos: "감탄사", ex: { zh: "嘿,你在这儿干什么呢?", pinyin: "Hēi, nǐ zài zhèr gàn shénme ne?", ko: "이봐, 너 여기서 뭐 하는 거야?" } },
        { zh: "哼", pinyin: "hēng", ko: "흥(콧방귀), 신음하다", pos: "감탄사", ex: { zh: "他不满地哼了一声。", pinyin: "Tā bùmǎn de hēng le yī shēng.", ko: "그는 불만스럽게 흥 하고 콧방귀를 뀌었다." } },
        { zh: "情报", pinyin: "qíngbào", ko: "정보, 첩보", pos: "명사", ex: { zh: "他专门负责收集情报。", pinyin: "Tā zhuānmén fùzé shōují qíngbào.", ko: "그는 정보 수집을 전담하고 있다." } },
        { zh: "眼神", pinyin: "yǎnshén", ko: "눈빛, 눈매", pos: "명사", ex: { zh: "她的眼神充满了悲伤。", pinyin: "Tā de yǎnshén chōngmǎn le bēishāng.", ko: "그녀의 눈빛에는 슬픔이 가득했다." } },
        { zh: "基因", pinyin: "jīyīn", ko: "유전자", pos: "명사", ex: { zh: "这种疾病与基因有关。", pinyin: "Zhè zhǒng jíbìng yǔ jīyīn yǒuguān.", ko: "이 질병은 유전자와 관련이 있다." } },
        { zh: "尴尬", pinyin: "gāngà", ko: "어색하다, 난처하다", pos: "형용사", ex: { zh: "气氛一下子变得尴尬。", pinyin: "Qìfēn yīxiàzi biàn de gāngà.", ko: "분위기가 갑자기 어색해졌다." } },
        { zh: "婴儿", pinyin: "yīngér", ko: "영아, 갓난아기", pos: "명사", ex: { zh: "这个婴儿刚出生不久。", pinyin: "Zhège yīng'ér gāng chūshēng bùjiǔ.", ko: "이 아기는 태어난 지 얼마 안 되었다." } },
        { zh: "武装", pinyin: "wǔzhuāng", ko: "무장, 군장비", pos: "명사", ex: { zh: "士兵们全副武装出发了。", pinyin: "Shìbīngmen quánfù wǔzhuāng chūfā le.", ko: "병사들은 완전 무장을 하고 출발했다." } },
        { zh: "跟踪", pinyin: "gēnzōng", ko: "미행하다, 추적하다", pos: "동사", ex: { zh: "有人一直在跟踪他。", pinyin: "Yǒurén yīzhí zài gēnzōng tā.", ko: "누군가 계속 그를 미행하고 있다." } },
        { zh: "屁股", pinyin: "pìgu", ko: "엉덩이", pos: "명사", ex: { zh: "他坐着的时候屁股疼。", pinyin: "Tā zuòzhe de shíhou pìgu téng.", ko: "그는 앉아 있을 때 엉덩이가 아팠다." } },
        { zh: "肿瘤", pinyin: "zhǒngliú", ko: "종양", pos: "명사", ex: { zh: "医生发现他体内有肿瘤。", pinyin: "Yīshēng fāxiàn tā tǐnèi yǒu zhǒngliú.", ko: "의사는 그의 몸속에 종양이 있음을 발견했다." } },
        { zh: "结局", pinyin: "jiéjú", ko: "결말, 결과", pos: "명사", ex: { zh: "这部电影的结局很感人。", pinyin: "Zhè bù diànyǐng de jiéjú hěn gǎnrén.", ko: "이 영화의 결말은 매우 감동적이다." } },
        { zh: "怀孕", pinyin: "huáiyùn", ko: "임신하다", pos: "동사", ex: { zh: "她已经怀孕三个月了。", pinyin: "Tā yǐjīng huáiyùn sān gè yuè le.", ko: "그녀는 임신한 지 3개월이 되었다." } },
        { zh: "即便", pinyin: "jíbiàn", ko: "설령 ~일지라도, 비록 ~하더라도", pos: "접속사", ex: { zh: "即便下雨,我们也要去。", pinyin: "Jíbiàn xiàyǔ, wǒmen yě yào qù.", ko: "설령 비가 오더라도 우리는 갈 것이다." } },
        { zh: "失踪", pinyin: "shīzōng", ko: "실종되다, 종적을 감추다", pos: "동사", ex: { zh: "那个孩子已经失踪三天了。", pinyin: "Nàge háizi yǐjīng shīzōng sān tiān le.", ko: "그 아이는 실종된 지 사흘이 되었다." } },
        { zh: "抢劫", pinyin: "qiǎngjié", ko: "강탈하다, 약탈하다", pos: "동사", ex: { zh: "银行昨晚遭到抢劫。", pinyin: "Yínháng zuówǎn zāodào qiǎngjié.", ko: "은행이 어젯밤 강도를 당했다." } },
        { zh: "栋", pinyin: "dòng", ko: "동(건물을 세는 양사)", pos: "양사", ex: { zh: "那栋楼有二十层高。", pinyin: "Nà dòng lóu yǒu èrshí céng gāo.", ko: "저 건물은 20층 높이이다." } },
        { zh: "恐惧", pinyin: "kǒngjù", ko: "공포, 두려움; 두려워하다", pos: "형용사", ex: { zh: "他对黑暗充满恐惧。", pinyin: "Tā duì hēi'àn chōngmǎn kǒngjù.", ko: "그는 어둠에 대한 공포로 가득 차 있다." } },
        { zh: "完毕", pinyin: "wánbì", ko: "끝나다, 완료되다", pos: "동사", ex: { zh: "会议已经全部完毕。", pinyin: "Huìyì yǐjīng quánbù wánbì.", ko: "회의가 이미 모두 끝났다." } },
        { zh: "监狱", pinyin: "jiānyù", ko: "감옥, 교도소", pos: "명사", ex: { zh: "他因抢劫被关进监狱。", pinyin: "Tā yīn qiǎngjié bèi guānjìn jiānyù.", ko: "그는 강도죄로 감옥에 갇혔다." } },
        { zh: "保障", pinyin: "bǎozhàng", ko: "보장하다, 보장", pos: "동사", ex: { zh: "政府努力保障公民权利。", pinyin: "Zhèngfǔ nǔlì bǎozhàng gōngmín quánlì.", ko: "정부는 국민의 권리를 보장하기 위해 노력한다." } },
        { zh: "吼", pinyin: "hǒu", ko: "포효하다, 고함치다", pos: "동사", ex: { zh: "老虎在笼子里大声吼。", pinyin: "Lǎohǔ zài lóngzi lǐ dàshēng hǒu.", ko: "호랑이가 우리 안에서 크게 포효했다." } },
        { zh: "皆", pinyin: "jiē", ko: "모두, 다", pos: "부사", ex: { zh: "在场的人皆表示赞同。", pinyin: "Zàichǎng de rén jiē biǎoshì zàntóng.", ko: "현장에 있던 사람들 모두 찬성을 표했다." } },
        { zh: "当事人", pinyin: "dāngshìrén", ko: "당사자", pos: "명사", ex: { zh: "法官询问了当事人的意见。", pinyin: "Fǎguān xúnwèn le dāngshìrén de yìjiàn.", ko: "판사는 당사자의 의견을 물었다." } },
        { zh: "诉讼", pinyin: "sùsòng", ko: "소송", pos: "동사", ex: { zh: "这起诉讼持续了三年。", pinyin: "Zhè qǐ sùsòng chíxù le sān nián.", ko: "이 소송은 3년 동안 계속되었다." } },
        { zh: "判决", pinyin: "pànjué", ko: "판결하다, 판결", pos: "동사", ex: { zh: "法院对此案作出判决。", pinyin: "Fǎyuàn duì cǐ àn zuòchū pànjué.", ko: "법원은 이 사건에 대해 판결을 내렸다." } },
        { zh: "逮捕", pinyin: "dàibǔ", ko: "체포하다", pos: "동사", ex: { zh: "警方当场逮捕了嫌疑人。", pinyin: "Jǐngfāng dāngchǎng dàibǔ le xiányírén.", ko: "경찰은 현장에서 용의자를 체포했다." } },
        { zh: "审判", pinyin: "shěnpàn", ko: "심판하다, 재판하다", pos: "동사", ex: { zh: "法庭正在审判这个案子。", pinyin: "Fǎtíng zhèngzài shěnpàn zhège ànzi.", ko: "법정에서 이 사건을 심리하고 있다." } },
        { zh: "财务", pinyin: "cáiwù", ko: "재무, 재정", pos: "명사", ex: { zh: "公司财务出现了问题。", pinyin: "Gōngsī cáiwù chūxiàn le wèntí.", ko: "회사 재무에 문제가 생겼다." } },
        { zh: "折磨", pinyin: "zhémó", ko: "괴롭히다, 시달리게 하다", pos: "동사", ex: { zh: "病痛长期折磨着他。", pinyin: "Bìngtòng chángqī zhémózhe tā.", ko: "병으로 인한 고통이 그를 오랫동안 괴롭혔다." } },
        { zh: "贼", pinyin: "zéi", ko: "도둑; 교활한", pos: "명사", ex: { zh: "小区里最近来了个贼。", pinyin: "Xiǎoqū lǐ zuìjìn lái le gè zéi.", ko: "요즘 아파트 단지에 도둑이 들었다." } },
        { zh: "预算", pinyin: "yùsuàn", ko: "예산", pos: "명사", ex: { zh: "这次装修超出了预算。", pinyin: "Zhè cì zhuāngxiū chāochū le yùsuàn.", ko: "이번 인테리어는 예산을 초과했다." } },
        { zh: "行政", pinyin: "xíngzhèng", ko: "행정", pos: "명사", ex: { zh: "他负责公司的行政工作。", pinyin: "Tā fùzé gōngsī de xíngzhèng gōngzuò.", ko: "그는 회사의 행정 업무를 담당한다." } },
        { zh: "司法", pinyin: "sīfǎ", ko: "사법", pos: "명사", ex: { zh: "司法独立是法治的基础。", pinyin: "Sīfǎ dúlì shì fǎzhì de jīchǔ.", ko: "사법 독립은 법치의 기초이다." } },
        { zh: "呈现", pinyin: "chéngxiàn", ko: "드러내다, 나타나다", pos: "동사", ex: { zh: "数据呈现出上升趋势。", pinyin: "Shùjù chéngxiàn chū shàngshēng qūshì.", ko: "데이터가 상승 추세를 나타내고 있다." } },
        { zh: "无比", pinyin: "wúbǐ", ko: "비할 데 없다, 더없이", pos: "형용사", ex: { zh: "看到成绩他无比高兴。", pinyin: "Kàndào chéngjì tā wúbǐ gāoxìng.", ko: "성적을 보고 그는 더없이 기뻐했다." } },
        { zh: "导弹", pinyin: "dǎodàn", ko: "미사일, 유도탄", pos: "명사", ex: { zh: "这枚导弹射程很远。", pinyin: "Zhè méi dǎodàn shèchéng hěn yuǎn.", ko: "이 미사일은 사거리가 매우 길다." } },
        { zh: "亦", pinyin: "yì", ko: "또한, 역시", pos: "부사", ex: { zh: "此言亦有一定道理。", pinyin: "Cǐ yán yì yǒu yīdìng dàolǐ.", ko: "이 말도 어느 정도 일리가 있다." } },
        { zh: "绑架", pinyin: "bǎngjià", ko: "납치하다, 유괴하다", pos: "동사", ex: { zh: "歹徒绑架了一名儿童。", pinyin: "Dǎitú bǎngjià le yī míng értóng.", ko: "범인이 한 아이를 납치했다." } },
        { zh: "诱惑", pinyin: "yòuhuò", ko: "유혹하다, 매혹하다", pos: "동사", ex: { zh: "美食的诱惑让人难以抵挡。", pinyin: "Měishí de yòuhuò ràng rén nányǐ dǐdǎng.", ko: "맛있는 음식의 유혹은 사람이 뿌리치기 어렵다." } },
        { zh: "嫉妒", pinyin: "jídù", ko: "질투하다, 시기하다", pos: "동사", ex: { zh: "她嫉妒同事的成功。", pinyin: "Tā jídù tóngshì de chénggōng.", ko: "그녀는 동료의 성공을 질투한다." } },
        { zh: "财政", pinyin: "cáizhèng", ko: "재정", pos: "명사", ex: { zh: "国家财政状况正在好转。", pinyin: "Guójiā cáizhèng zhuàngkuàng zhèngzài hǎozhuǎn.", ko: "국가 재정 상황이 호전되고 있다." } },
        { zh: "迹象", pinyin: "jìxiàng", ko: "조짐, 징후", pos: "명사", ex: { zh: "天空出现了下雨的迹象。", pinyin: "Tiānkōng chūxiàn le xiàyǔ de jìxiàng.", ko: "하늘에 비가 올 조짐이 나타났다." } },
        { zh: "签署", pinyin: "qiānshǔ", ko: "서명하다, 조인하다", pos: "동사", ex: { zh: "两国正式签署了协议。", pinyin: "Liǎng guó zhèngshì qiānshǔ le xiéyì.", ko: "양국은 정식으로 협정에 서명했다." } },
        { zh: "犬", pinyin: "quǎn", ko: "개(견)", pos: "", ex: { zh: "这只犬非常聪明伶俐。", pinyin: "Zhè zhī quǎn fēicháng cōngmíng línglì.", ko: "이 개는 매우 영리하다." } },
        { zh: "欺骗", pinyin: "qīpiàn", ko: "속이다, 기만하다", pos: "동사", ex: { zh: "他欺骗了所有的朋友。", pinyin: "Tā qīpiàn le suǒyǒu de péngyou.", ko: "그는 모든 친구들을 속였다." } },
        { zh: "痕迹", pinyin: "hénjì", ko: "흔적, 자국", pos: "명사", ex: { zh: "墙上留下了火烧的痕迹。", pinyin: "Qiáng shàng liú xià le huǒshāo de hénjì.", ko: "벽에 불에 탄 흔적이 남아 있다." } },
        { zh: "清晰", pinyin: "qīngxī", ko: "뚜렷하다, 분명하다", pos: "형용사", ex: { zh: "照片拍得十分清晰。", pinyin: "Zhàopiàn pāi de shífēn qīngxī.", ko: "사진이 매우 선명하게 찍혔다." } },
        { zh: "崩溃", pinyin: "bēngkuì", ko: "붕괴하다, 무너지다", pos: "동사", ex: { zh: "公司资金链几乎崩溃。", pinyin: "Gōngsī zījīnliàn jīhū bēngkuì.", ko: "회사의 자금줄이 거의 붕괴 직전이다." } },
        { zh: "穿越", pinyin: "chuānyuè", ko: "관통하다, 통과하다", pos: "동사", ex: { zh: "火车正穿越一片森林。", pinyin: "Huǒchē zhèng chuānyuè yī piàn sēnlín.", ko: "기차가 숲을 지나가고 있다." } },
        { zh: "抛弃", pinyin: "pāoqì", ko: "버리다, 포기하다", pos: "동사", ex: { zh: "他从未抛弃自己的理想。", pinyin: "Tā cóngwèi pāoqì zìjǐ de lǐxiǎng.", ko: "그는 자신의 꿈을 버린 적이 없다." } },
        { zh: "临床", pinyin: "línchuáng", ko: "임상의", pos: "동사", ex: { zh: "这种药物正在临床试验。", pinyin: "Zhè zhǒng yàowù zhèngzài línchuáng shìyàn.", ko: "이 약물은 임상 시험 중이다." } },
        { zh: "欲望", pinyin: "yùwàng", ko: "욕망, 욕구", pos: "명사", ex: { zh: "他对权力充满欲望。", pinyin: "Tā duì quánlì chōngmǎn yùwàng.", ko: "그는 권력에 대한 욕망으로 가득하다." } },
        { zh: "放手", pinyin: "fàngshǒu", ko: "손을 놓다, 포기하다", pos: "동사", ex: { zh: "他终于放手让孩子去闯。", pinyin: "Tā zhōngyú fàngshǒu ràng háizi qù chuǎng.", ko: "그는 마침내 손을 놓고 아이가 스스로 부딪히게 했다." } },
        { zh: "惩罚", pinyin: "chéngfá", ko: "처벌하다, 징벌", pos: "동사", ex: { zh: "老师惩罚了迟到的学生。", pinyin: "Lǎoshī chéngfá le chídào de xuésheng.", ko: "선생님은 지각한 학생을 벌주었다." } },
        { zh: "事务", pinyin: "shìwù", ko: "사무, 업무", pos: "명사", ex: { zh: "他每天处理很多事务。", pinyin: "Tā měitiān chǔlǐ hěn duō shìwù.", ko: "그는 매일 많은 사무를 처리한다." } },
        { zh: "在意", pinyin: "zàiyì", ko: "마음에 두다, 신경 쓰다", pos: "동사", ex: { zh: "他从不在意别人的看法。", pinyin: "Tā cóngbù zàiyì biérén de kànfǎ.", ko: "그는 다른 사람의 시선을 전혀 신경 쓰지 않는다." } },
        { zh: "化妆", pinyin: "huàzhuāng", ko: "화장하다", pos: "동사", ex: { zh: "她每天早上都要化妆才出门。", pinyin: "Tā měitiān zǎoshang dōu yào huàzhuāng cái chūmén.", ko: "그녀는 매일 아침 화장을 해야만 외출한다." } },
        { zh: "角落", pinyin: "jiǎoluò", ko: "구석, 모퉁이", pos: "명사", ex: { zh: "房间的角落里堆满了旧书。", pinyin: "Fángjiān de jiǎoluò lǐ duīmǎnle jiù shū.", ko: "방 구석에는 오래된 책이 가득 쌓여 있다." } },
        { zh: "版本", pinyin: "bǎnběn", ko: "버전, 판본", pos: "명사", ex: { zh: "这个软件的最新版本修复了很多漏洞。", pinyin: "Zhège ruǎnjiàn de zuìxīn bǎnběn xiūfùle hěn duō lòudòng.", ko: "이 소프트웨어의 최신 버전은 많은 버그를 수정했다." } },
        { zh: "体系", pinyin: "tǐxì", ko: "체계, 시스템", pos: "명사", ex: { zh: "学校建立了完整的教育体系。", pinyin: "Xuéxiào jiànlìle wánzhěng de jiàoyù tǐxì.", ko: "학교는 완전한 교육 체계를 구축했다." } },
        { zh: "脆弱", pinyin: "cuìruò", ko: "연약하다, 취약하다", pos: "형용사", ex: { zh: "老人的身体非常脆弱，需要精心照顾。", pinyin: "Lǎorén de shēntǐ fēicháng cuìruò, xūyào jīngxīn zhàogù.", ko: "노인의 몸은 매우 연약해서 정성껏 돌봐야 한다." } },
        { zh: "引擎", pinyin: "yǐnqíng", ko: "엔진", pos: "명사", ex: { zh: "这辆车的引擎发出了奇怪的声音。", pinyin: "Zhè liàng chē de yǐnqíng fāchūle qíguài de shēngyīn.", ko: "이 차의 엔진에서 이상한 소리가 났다." } },
        { zh: "窝", pinyin: "wō", ko: "둥지, 보금자리", pos: "명사", ex: { zh: "小鸟在树上筑了一个窝。", pinyin: "Xiǎo niǎo zài shù shàng zhùle yí ge wō.", ko: "작은 새가 나무 위에 둥지를 지었다." } },
        { zh: "弥补", pinyin: "míbǔ", ko: "보완하다, 메우다", pos: "동사", ex: { zh: "他努力工作以弥补之前的损失。", pinyin: "Tā nǔlì gōngzuò yǐ míbǔ zhīqián de sǔnshī.", ko: "그는 이전의 손실을 메우기 위해 열심히 일했다." } },
        { zh: "天生", pinyin: "tiānshēng", ko: "타고난, 천성적으로", pos: "부사", ex: { zh: "她天生就有一副好嗓子。", pinyin: "Tā tiānshēng jiù yǒu yí fù hǎo sǎngzi.", ko: "그녀는 타고난 좋은 목소리를 가지고 있다." } },
        { zh: "登陆", pinyin: "dēnglù", ko: "상륙하다, 착륙하다", pos: "동사", ex: { zh: "台风将于今晚登陆沿海城市。", pinyin: "Táifēng jiāng yú jīnwǎn dēnglù yánhǎi chéngshì.", ko: "태풍이 오늘 밤 연해 도시에 상륙할 예정이다." } },
        { zh: "灵感", pinyin: "línggǎn", ko: "영감", pos: "명사", ex: { zh: "这幅画给了他很多创作灵感。", pinyin: "Zhè fú huà gěile tā hěn duō chuàngzuò línggǎn.", ko: "이 그림은 그에게 많은 창작 영감을 주었다." } },
        { zh: "别墅", pinyin: "biéshù", ko: "별장", pos: "명사", ex: { zh: "他们在海边买了一栋别墅。", pinyin: "Tāmen zài hǎibiān mǎile yí dòng biéshù.", ko: "그들은 바닷가에 별장 한 채를 샀다." } },
        { zh: "钻石", pinyin: "zuànshí", ko: "다이아몬드", pos: "명사", ex: { zh: "她收到了一枚闪闪发光的钻石戒指。", pinyin: "Tā shōudàole yì méi shǎnshǎn fāguāng de zuànshí jièzhi.", ko: "그녀는 반짝반짝 빛나는 다이아몬드 반지를 받았다." } },
        { zh: "不可思议", pinyin: "bùkě sīyì", ko: "불가사의하다, 상상할 수 없다", pos: "관용구", ex: { zh: "这个结果简直不可思议。", pinyin: "Zhège jiéguǒ jiǎnzhí bùkěsīyì.", ko: "이 결과는 정말 불가사의하다." } },
        { zh: "宁愿", pinyin: "nìngyuàn", ko: "차라리 ~하겠다", pos: "부사", ex: { zh: "我宁愿加班也不想让工作落后。", pinyin: "Wǒ nìngyuàn jiābān yě bù xiǎng ràng gōngzuò luòhòu.", ko: "나는 차라리 야근을 할지언정 일이 뒤처지게 하고 싶지 않다." } },
        { zh: "拼命", pinyin: "pīnmìng", ko: "필사적으로, 죽을힘을 다해", pos: "부사", ex: { zh: "他拼命奔跑去追赶公交车。", pinyin: "Tā pīnmìng bēnpǎo qù zhuīgǎn gōngjiāochē.", ko: "그는 버스를 따라잡기 위해 필사적으로 뛰었다." } },
        { zh: "免疫", pinyin: "miǎnyì", ko: "면역되다, 면역력을 가지다", pos: "동사", ex: { zh: "接种疫苗可以让身体对病毒免疫。", pinyin: "Jiēzhòng yìmiáo kěyǐ ràng shēntǐ duì bìngdú miǎnyì.", ko: "백신을 접종하면 몸이 바이러스에 면역될 수 있다." } },
        { zh: "割", pinyin: "gē", ko: "자르다, 베다", pos: "동사", ex: { zh: "他不小心用刀割伤了手指。", pinyin: "Tā bù xiǎoxīn yòng dāo gē shāngle shǒuzhǐ.", ko: "그는 실수로 칼에 손가락을 베였다." } },
        { zh: "渣", pinyin: "zhā", ko: "찌꺼기, 부스러기", pos: "", ex: { zh: "锅底剩下了一些油渣。", pinyin: "Guō dǐ shèngxiàle yìxiē yóuzhā.", ko: "냄비 바닥에 기름 찌꺼기가 남아 있었다." } },
        { zh: "假设", pinyin: "jiǎshè", ko: "가정하다, 추정하다", pos: "동사", ex: { zh: "我们先假设这个理论是正确的。", pinyin: "Wǒmen xiān jiǎshè zhège lǐlùn shì zhèngquè de.", ko: "우리는 먼저 이 이론이 옳다고 가정해 보자." } },
        { zh: "级别", pinyin: "jíbié", ko: "등급, 급수", pos: "명사", ex: { zh: "这个考试分为不同的级别。", pinyin: "Zhège kǎoshì fēnwéi bùtóng de jíbié.", ko: "이 시험은 서로 다른 등급으로 나뉜다." } },
        { zh: "携带", pinyin: "xiédài", ko: "휴대하다, 지니다", pos: "동사", ex: { zh: "乘客不得携带危险物品上飞机。", pinyin: "Chéngkè bùdé xiédài wēixiǎn wùpǐn shàng fēijī.", ko: "승객은 위험 물품을 휴대하고 비행기에 탑승할 수 없다." } },
        { zh: "癌症", pinyin: "áizhèng", ko: "암", pos: "명사", ex: { zh: "早期发现癌症有助于治疗。", pinyin: "Zǎoqī fāxiàn áizhèng yǒuzhù yú zhìliáo.", ko: "암을 조기에 발견하면 치료에 도움이 된다." } },
        { zh: "激励", pinyin: "jīlì", ko: "격려하다, 고무하다", pos: "동사", ex: { zh: "老师的话激励了每一位学生。", pinyin: "Lǎoshī de huà jīlìle měi yí wèi xuésheng.", ko: "선생님의 말씀은 모든 학생을 격려했다." } },
        { zh: "定义", pinyin: "dìngyì", ko: "정의", pos: "명사", ex: { zh: "请给这个词下一个准确的定义。", pinyin: "Qǐng gěi zhège cí xià yí ge zhǔnquè de dìngyì.", ko: "이 단어에 대해 정확한 정의를 내려 주세요." } },
        { zh: "清除", pinyin: "qīngchú", ko: "제거하다, 없애다", pos: "동사", ex: { zh: "工作人员正在清除路面上的积雪。", pinyin: "Gōngzuò rényuán zhèngzài qīngchú lùmiàn shàng de jīxuě.", ko: "작업자들이 도로 위의 쌓인 눈을 제거하고 있다." } },
        { zh: "挣扎", pinyin: "zhēngzhá", ko: "발버둥치다, 몸부림치다", pos: "동사", ex: { zh: "他在痛苦中挣扎了很久。", pinyin: "Tā zài tòngkǔ zhōng zhēngzhále hěn jiǔ.", ko: "그는 고통 속에서 오랫동안 몸부림쳤다." } },
        { zh: "履行", pinyin: "lǚxíng", ko: "이행하다, 실행하다", pos: "동사", ex: { zh: "双方都必须履行合同规定的义务。", pinyin: "Shuāngfāng dōu bìxū lǚxíng hétong guīdìng de yìwù.", ko: "양측 모두 계약에 규정된 의무를 이행해야 한다." } },
        { zh: "频率", pinyin: "pínlǜ", ko: "빈도, 주파수", pos: "명사", ex: { zh: "他锻炼的频率越来越高。", pinyin: "Tā duànliàn de pínlǜ yuè lái yuè gāo.", ko: "그의 운동 빈도가 점점 더 높아지고 있다." } },
        { zh: "报复", pinyin: "bàofù", ko: "보복하다, 앙갚음하다", pos: "동사", ex: { zh: "他发誓一定要报复曾经欺负他的人。", pinyin: "Tā fāshì yídìng yào bàofù céngjīng qīfù tā de rén.", ko: "그는 자신을 괴롭혔던 사람에게 반드시 보복하겠다고 맹세했다." } },
        { zh: "纤维", pinyin: "xiānwéi", ko: "섬유", pos: "명사", ex: { zh: "这种布料含有天然纤维。", pinyin: "Zhè zhǒng bùliào hányǒu tiānrán xiānwéi.", ko: "이 원단에는 천연 섬유가 함유되어 있다." } },
        { zh: "提议", pinyin: "tíyì", ko: "제안, 건의", pos: "명사", ex: { zh: "他在会议上提出了一个新提议。", pinyin: "Tā zài huìyì shàng tíchūle yí ge xīn tíyì.", ko: "그는 회의에서 새로운 제안을 내놓았다." } },
        { zh: "轮胎", pinyin: "lúntāi", ko: "타이어", pos: "명사", ex: { zh: "这辆车的轮胎需要更换了。", pinyin: "Zhè liàng chē de lúntāi xūyào gēnghuànle.", ko: "이 차의 타이어는 교체가 필요하다." } },
        { zh: "监视", pinyin: "jiānshì", ko: "감시하다", pos: "동사", ex: { zh: "警方一直在监视这栋可疑的建筑。", pinyin: "Jǐngfāng yìzhí zài jiānshì zhè dòng kěyí de jiànzhù.", ko: "경찰은 이 의심스러운 건물을 계속 감시하고 있다." } },
        { zh: "擅长", pinyin: "shàncháng", ko: "능하다, 뛰어나다", pos: "동사", ex: { zh: "她擅长画油画。", pinyin: "Tā shàncháng huà yóuhuà.", ko: "그녀는 유화를 그리는 데 능하다." } },
        { zh: "磅", pinyin: "bàng", ko: "파운드, 저울", pos: "양사", ex: { zh: "这块肉重五磅。", pinyin: "Zhè kuài ròu zhòng wǔ bàng.", ko: "이 고깃덩어리는 무게가 5파운드이다." } },
        { zh: "背叛", pinyin: "bèipàn", ko: "배신하다", pos: "동사", ex: { zh: "他从未想过朋友会背叛自己。", pinyin: "Tā cóng wèi xiǎngguò péngyou huì bèipàn zìjǐ.", ko: "그는 친구가 자신을 배신하리라고는 전혀 생각하지 못했다." } },
        { zh: "股份", pinyin: "gǔfèn", ko: "주식, 지분", pos: "명사", ex: { zh: "他持有这家公司的部分股份。", pinyin: "Tā chíyǒu zhè jiā gōngsī de bùfen gǔfèn.", ko: "그는 이 회사의 일부 지분을 보유하고 있다." } },
        { zh: "辐射", pinyin: "fúshè", ko: "방사하다, 방사선", pos: "동사", ex: { zh: "太阳不断向地球辐射能量。", pinyin: "Tàiyáng búduàn xiàng dìqiú fúshè néngliàng.", ko: "태양은 끊임없이 지구에 에너지를 방사한다." } },
        { zh: "趴", pinyin: "pā", ko: "엎드리다", pos: "동사", ex: { zh: "他趴在桌子上睡着了。", pinyin: "Tā pā zài zhuōzi shàng shuìzháole.", ko: "그는 책상에 엎드려 잠들었다." } },
        { zh: "曝光", pinyin: "bàoguāng", ko: "노출되다, 폭로되다", pos: "동사", ex: { zh: "这起丑闻终于被媒体曝光了。", pinyin: "Zhè qǐ chǒuwén zhōngyú bèi méitǐ bàoguāngle.", ko: "이 스캔들이 마침내 언론에 의해 폭로되었다." } },
        { zh: "浑身", pinyin: "húnshēn", ko: "온몸", pos: "명사", ex: { zh: "他跑完步后浑身都是汗。", pinyin: "Tā pǎo wán bù hòu húnshēn dōu shì hàn.", ko: "그는 달리기를 마친 후 온몸이 땀투성이였다." } },
        { zh: "宪法", pinyin: "xiànfǎ", ko: "헌법", pos: "명사", ex: { zh: "宪法保障公民的基本权利。", pinyin: "Xiànfǎ bǎozhàng gōngmín de jīběn quánlì.", ko: "헌법은 국민의 기본 권리를 보장한다." } },
        { zh: "防御", pinyin: "fángyù", ko: "방어하다", pos: "동사", ex: { zh: "球队加强了防御能力。", pinyin: "Qiú duì jiāqiángle fángyù nénglì.", ko: "팀은 방어 능력을 강화했다." } },
        { zh: "外表", pinyin: "wàibiǎo", ko: "외모, 겉모습", pos: "명사", ex: { zh: "不要只看一个人的外表。", pinyin: "Bú yào zhǐ kàn yí ge rén de wàibiǎo.", ko: "사람을 겉모습만 보고 판단하지 마라." } },
        { zh: "人格", pinyin: "réngé", ko: "인격", pos: "명사", ex: { zh: "他是一个具有高尚人格的人。", pinyin: "Tā shì yí ge jùyǒu gāoshàng réngé de rén.", ko: "그는 고상한 인격을 지닌 사람이다." } },
        { zh: "忠诚", pinyin: "zhōngchéng", ko: "충성스럽다", pos: "형용사", ex: { zh: "这只狗对主人非常忠诚。", pinyin: "Zhè zhī gǒu duì zhǔrén fēicháng zhōngchéng.", ko: "이 개는 주인에게 매우 충성스럽다." } },
        { zh: "局势", pinyin: "júshì", ko: "정세, 국면", pos: "명사", ex: { zh: "国际局势正在发生变化。", pinyin: "Guójì júshì zhèngzài fāshēng biànhuà.", ko: "국제 정세가 변화하고 있다." } },
        { zh: "大厦", pinyin: "dàshà", ko: "빌딩, 대형 건물", pos: "명사", ex: { zh: "这座大厦有五十层高。", pinyin: "Zhè zuò dàshà yǒu wǔshí céng gāo.", ko: "이 빌딩은 오십 층 높이이다." } },
        { zh: "隧道", pinyin: "suìdào", ko: "터널", pos: "명사", ex: { zh: "汽车穿过了一条长长的隧道。", pinyin: "Qìchē chuānguòle yì tiáo chángcháng de suìdào.", ko: "자동차가 길고 긴 터널을 통과했다." } },
        { zh: "抑制", pinyin: "yìzhì", ko: "억제하다", pos: "동사", ex: { zh: "他努力抑制住内心的愤怒。", pinyin: "Tā nǔlì yìzhì zhù nèixīn de fènnù.", ko: "그는 마음속의 분노를 억제하려고 애썼다." } },
        { zh: "精心", pinyin: "jīngxīn", ko: "정성을 들이다, 세심하다", pos: "", ex: { zh: "妈妈精心准备了一桌晚餐。", pinyin: "Māma jīngxīn zhǔnbèile yì zhuō wǎncān.", ko: "엄마는 정성을 들여 한 상 가득 저녁을 준비했다." } },
        { zh: "流氓", pinyin: "liúmáng", ko: "건달, 불량배", pos: "명사", ex: { zh: "那个流氓总是欺负弱小。", pinyin: "Nàge liúmáng zǒngshì qīfù ruòxiǎo.", ko: "저 건달은 항상 약자를 괴롭힌다." } },
        { zh: "竞选", pinyin: "jìngxuǎn", ko: "선거에 출마하다", pos: "동사", ex: { zh: "他决定竞选下一届市长。", pinyin: "Tā juédìng jìngxuǎn xià yí jiè shìzhǎng.", ko: "그는 다음 시장 선거에 출마하기로 결정했다." } },
        { zh: "着手", pinyin: "zhuóshǒu", ko: "착수하다", pos: "동사", ex: { zh: "我们应该立刻着手解决这个问题。", pinyin: "Wǒmen yīnggāi lìkè zhuóshǒu jiějué zhège wèntí.", ko: "우리는 즉시 이 문제 해결에 착수해야 한다." } },
        { zh: "指望", pinyin: "zhǐwàng", ko: "기대하다, 바라다", pos: "동사", ex: { zh: "别指望别人替你解决问题。", pinyin: "Bié zhǐwàng biérén tì nǐ jiějué wèntí.", ko: "다른 사람이 대신 문제를 해결해 줄 거라고 기대하지 마라." } },
        { zh: "使命", pinyin: "shǐmìng", ko: "사명", pos: "명사", ex: { zh: "保护环境是我们共同的使命。", pinyin: "Bǎohù huánjìng shì wǒmen gòngtóng de shǐmìng.", ko: "환경 보호는 우리 모두의 공통된 사명이다." } },
        { zh: "残忍", pinyin: "cánrěn", ko: "잔인하다", pos: "형용사", ex: { zh: "这种残忍的行为令人愤怒。", pinyin: "Zhè zhǒng cánrěn de xíngwéi lìng rén fènnù.", ko: "이런 잔인한 행동은 사람을 분노하게 한다." } },
        { zh: "隔离", pinyin: "gélí", ko: "격리하다", pos: "동사", ex: { zh: "医院将病人隔离起来治疗。", pinyin: "Yīyuàn jiāng bìngrén gélí qǐlái zhìliáo.", ko: "병원은 환자를 격리시켜 치료했다." } },
        { zh: "人性", pinyin: "rénxìng", ko: "인성, 인간성", pos: "명사", ex: { zh: "这部电影深刻揭示了人性的复杂。", pinyin: "Zhè bù diànyǐng shēnkè jiēshìle rénxìng de fùzá.", ko: "이 영화는 인간성의 복잡함을 깊이 있게 드러냈다." } },
        { zh: "美妙", pinyin: "měimiào", ko: "아름답다, 미묘하다", pos: "형용사", ex: { zh: "音乐厅里传来美妙的旋律。", pinyin: "Yīnyuè tīng lǐ chuánlái měimiào de xuánlǜ.", ko: "음악당에서 아름다운 선율이 흘러나왔다." } },
        { zh: "作风", pinyin: "zuòfēng", ko: "태도, 기풍", pos: "명사", ex: { zh: "他的工作作风一向严谨。", pinyin: "Tā de gōngzuò zuòfēng yíxiàng yánjǐn.", ko: "그의 업무 태도는 늘 신중하다." } },
        { zh: "纯粹", pinyin: "chúncuì", ko: "순전히, 순수하게", pos: "부사", ex: { zh: "这纯粹是一场误会。", pinyin: "Zhè chúncuì shì yì chǎng wùhuì.", ko: "이것은 순전히 오해일 뿐이다." } },
        { zh: "保姆", pinyin: "bǎomǔ", ko: "보모, 가정부", pos: "명사", ex: { zh: "他们请了一位保姆照顾孩子。", pinyin: "Tāmen qǐngle yí wèi bǎomǔ zhàogù háizi.", ko: "그들은 아이를 돌볼 보모를 한 명 고용했다." } },
        { zh: "刑事", pinyin: "xíngshì", ko: "형사의", pos: "형용사", ex: { zh: "这是一起严重的刑事案件。", pinyin: "Zhè shì yì qǐ yánzhòng de xíngshì ànjiàn.", ko: "이것은 중대한 형사 사건이다." } },
        { zh: "演绎", pinyin: "yǎnyì", ko: "연출하다, 전개하다", pos: "동사", ex: { zh: "演员们精彩地演绎了这个故事。", pinyin: "Yǎnyuánmen jīngcǎi de yǎnyìle zhège gùshi.", ko: "배우들은 이 이야기를 멋지게 연기해 냈다." } },
        { zh: "生理", pinyin: "shēnglǐ", ko: "생리", pos: "명사", ex: { zh: "医生解释了人体的生理结构。", pinyin: "Yīshēng jiěshìle réntǐ de shēnglǐ jiégòu.", ko: "의사는 인체의 생리 구조를 설명했다." } },
        { zh: "拜托", pinyin: "bàituō", ko: "부탁하다", pos: "동사", ex: { zh: "拜托你帮我照看一下行李。", pinyin: "Bàituō nǐ bāng wǒ zhàokàn yíxià xíngli.", ko: "제 짐 좀 봐 주시길 부탁드립니다." } },
        { zh: "滋味", pinyin: "zīwèi", ko: "맛, 기분", pos: "명사", ex: { zh: "这道菜的滋味非常独特。", pinyin: "Zhè dào cài de zīwèi fēicháng dútè.", ko: "이 요리의 맛은 매우 독특하다." } },
        { zh: "脂肪", pinyin: "zhīfáng", ko: "지방", pos: "명사", ex: { zh: "运动可以帮助燃烧体内脂肪。", pinyin: "Yùndòng kěyǐ bāngzhù ránshāo tǐnèi zhīfáng.", ko: "운동은 체내 지방을 태우는 데 도움이 된다." } },
        { zh: "挖掘", pinyin: "wājué", ko: "발굴하다, 파내다", pos: "동사", ex: { zh: "考古学家在这里挖掘出许多文物。", pinyin: "Kǎogǔ xuéjiā zài zhèlǐ wājué chū xǔduō wénwù.", ko: "고고학자들이 이곳에서 많은 문물을 발굴해 냈다." } },
        { zh: "权威", pinyin: "quánwēi", ko: "권위", pos: "명사", ex: { zh: "他是这个领域的权威专家。", pinyin: "Tā shì zhège lǐngyù de quánwēi zhuānjiā.", ko: "그는 이 분야의 권위 있는 전문가이다." } },
        { zh: "覆盖", pinyin: "fùgài", ko: "덮다, 뒤덮다", pos: "동사", ex: { zh: "大雪覆盖了整个城市。", pinyin: "Dàxuě fùgàile zhěnggè chéngshì.", ko: "폭설이 도시 전체를 뒤덮었다." } },
        { zh: "永恒", pinyin: "yǒnghéng", ko: "영원하다", pos: "형용사", ex: { zh: "他们相信爱情是永恒的。", pinyin: "Tāmen xiāngxìn àiqíng shì yǒnghéng de.", ko: "그들은 사랑이 영원하다고 믿는다." } },
        { zh: "尊严", pinyin: "zūnyán", ko: "존엄, 위엄", pos: "명사", ex: { zh: "每个人都应该受到尊严的对待。", pinyin: "Měi ge rén dōu yīnggāi shòudào zūnyán de duìdài.", ko: "모든 사람은 존엄하게 대우받아야 한다." } },
        { zh: "宰", pinyin: "zǎi", ko: "도살하다, 바가지 씌우다", pos: "동사", ex: { zh: "那家餐厅经常宰游客。", pinyin: "Nà jiā cāntīng jīngcháng zǎi yóukè.", ko: "그 식당은 관광객에게 자주 바가지를 씌운다." } },
        { zh: "交叉", pinyin: "jiāochā", ko: "교차하다", pos: "동사", ex: { zh: "两条道路在这里交叉。", pinyin: "Liǎng tiáo dàolù zài zhèlǐ jiāochā.", ko: "두 도로가 이곳에서 교차한다." } },
        { zh: "酒精", pinyin: "jiǔjīng", ko: "알코올, 주정", pos: "명사", ex: { zh: "医生用酒精给伤口消毒。", pinyin: "Yīshēng yòng jiǔjīng gěi shāngkǒu xiāodú.", ko: "의사는 알코올로 상처를 소독했다." } },
        { zh: "可笑", pinyin: "kěxiào", ko: "우습다, 가소롭다", pos: "형용사", ex: { zh: "他的借口听起来十分可笑。", pinyin: "Tā de jièkǒu tīng qǐlái shífēn kěxiào.", ko: "그의 변명은 매우 우습게 들렸다." } },
        { zh: "捞", pinyin: "lāo", ko: "건지다, 부당하게 취득하다", pos: "동사", ex: { zh: "渔民从河里捞起了不少鱼。", pinyin: "Yúmín cóng hé lǐ lāo qǐle bù shǎo yú.", ko: "어부들이 강에서 많은 물고기를 건져 올렸다." } },
        { zh: "动脉", pinyin: "dòngmài", ko: "동맥", pos: "명사", ex: { zh: "医生检查了病人的动脉血管。", pinyin: "Yīshēng jiǎnchále bìngrén de dòngmài xuèguǎn.", ko: "의사가 환자의 동맥 혈관을 검사했다." } },
        { zh: "扩散", pinyin: "kuòsàn", ko: "확산되다, 퍼지다", pos: "동사", ex: { zh: "病毒在城市里迅速扩散。", pinyin: "Bìngdú zài chéngshì lǐ xùnsù kuòsàn.", ko: "바이러스가 도시에서 빠르게 확산되었다." } },
        { zh: "条款", pinyin: "tiáokuǎn", ko: "조항, 조목", pos: "명사", ex: { zh: "合同里有一条重要的条款。", pinyin: "Hétong lǐ yǒu yì tiáo zhòngyào de tiáokuǎn.", ko: "계약서에는 중요한 조항이 하나 있다." } },
        { zh: "贿赂", pinyin: "huìlù", ko: "뇌물을 주다, 매수하다", pos: "동사", ex: { zh: "他试图贿赂政府官员。", pinyin: "Tā shìtú huìlù zhèngfǔ guānyuán.", ko: "그는 정부 관리를 매수하려 했다." } },
        { zh: "封锁", pinyin: "fēngsuǒ", ko: "봉쇄하다, 차단하다", pos: "동사", ex: { zh: "军队封锁了整个边境地区。", pinyin: "Jūnduì fēngsuǒle zhěnggè biānjìng dìqū.", ko: "군대가 국경 지역 전체를 봉쇄했다." } },
        { zh: "命名", pinyin: "mìngmíng", ko: "명명하다, 이름을 짓다", pos: "동사", ex: { zh: "这座桥以他的名字命名。", pinyin: "Zhè zuò qiáo yǐ tā de míngzi mìngmíng.", ko: "이 다리는 그의 이름을 따서 명명되었다." } },
        { zh: "部署", pinyin: "bùshǔ", ko: "배치하다, 배치", pos: "동사", ex: { zh: "政府部署了新的安全措施。", pinyin: "Zhèngfǔ bùshǔle xīn de ānquán cuòshī.", ko: "정부는 새로운 안전 조치를 배치했다." } },
        { zh: "赋予", pinyin: "fùyǔ", ko: "부여하다", pos: "동사", ex: { zh: "法律赋予公民选举权利。", pinyin: "Fǎlǜ fùyǔ gōngmín xuǎnjǔ quánlì.", ko: "법률은 시민에게 선거 권리를 부여한다." } },
        { zh: "血压", pinyin: "xuèyā", ko: "혈압", pos: "명사", ex: { zh: "医生每天都测量他的血压。", pinyin: "Yīshēng měitiān dōu cèliáng tā de xuèyā.", ko: "의사는 매일 그의 혈압을 측정한다." } },
        { zh: "识别", pinyin: "shíbié", ko: "식별하다, 인식하다", pos: "동사", ex: { zh: "这个系统可以识别人脸。", pinyin: "Zhège xìtǒng kěyǐ shíbié rénliǎn.", ko: "이 시스템은 얼굴을 식별할 수 있다." } },
        { zh: "摇滚", pinyin: "yáogǔn", ko: "로큰롤, 록 음악", pos: "명사", ex: { zh: "他很喜欢听摇滚音乐。", pinyin: "Tā hěn xǐhuan tīng yáogǔn yīnyuè.", ko: "그는 록 음악 듣는 것을 아주 좋아한다." } },
        { zh: "魔鬼", pinyin: "móguǐ", ko: "악마, 마귀", pos: "명사", ex: { zh: "电影里的魔鬼形象很吓人。", pinyin: "Diànyǐng lǐ de móguǐ xíngxiàng hěn xiàrén.", ko: "영화 속 악마의 모습은 매우 무섭다." } },
        { zh: "标记", pinyin: "biāojì", ko: "표기, 표시", pos: "명사", ex: { zh: "他在地图上做了标记。", pinyin: "Tā zài dìtú shàng zuòle biāojì.", ko: "그는 지도에 표시를 했다." } },
        { zh: "辩护", pinyin: "biànhù", ko: "변호하다", pos: "동사", ex: { zh: "律师为被告进行辩护。", pinyin: "Lǜshī wèi bèigào jìnxíng biànhù.", ko: "변호사가 피고를 위해 변호했다." } },
        { zh: "幸好", pinyin: "xìnghǎo", ko: "다행히", pos: "부사", ex: { zh: "幸好我们及时赶到了机场。", pinyin: "Xìnghǎo wǒmen jíshí gǎndàole jīchǎng.", ko: "다행히 우리는 제시간에 공항에 도착했다." } },
        { zh: "走廊", pinyin: "zǒuláng", ko: "복도", pos: "명사", ex: { zh: "学生们在走廊里聊天。", pinyin: "Xuéshengmen zài zǒuláng lǐ liáotiān.", ko: "학생들이 복도에서 이야기하고 있다." } },
        { zh: "人质", pinyin: "rénzhì", ko: "인질", pos: "명사", ex: { zh: "劫匪劫持了几名人质。", pinyin: "Jiéfěi jiéchíle jǐ míng rénzhì.", ko: "강도가 인질 몇 명을 붙잡았다." } },
        { zh: "嘴唇", pinyin: "zuǐchún", ko: "입술", pos: "명사", ex: { zh: "她的嘴唇因寒冷而干裂。", pinyin: "Tā de zuǐchún yīn hánlěng ér gānliè.", ko: "그녀의 입술이 추위 때문에 갈라졌다." } },
        { zh: "强制", pinyin: "qiángzhì", ko: "강제하다, 강제적인", pos: "동사", ex: { zh: "政府强制居民接种疫苗。", pinyin: "Zhèngfǔ qiángzhì jūmín jiēzhòng yìmiáo.", ko: "정부는 주민들에게 백신 접종을 강제했다." } },
        { zh: "愚蠢", pinyin: "yúchǔn", ko: "어리석다, 멍청하다", pos: "형용사", ex: { zh: "这真是一个愚蠢的决定。", pinyin: "Zhè zhēn shi yí gè yúchǔn de juédìng.", ko: "이것은 정말 어리석은 결정이다." } },
        { zh: "盗窃", pinyin: "dàoqiè", ko: "절도하다, 훔치다", pos: "동사", ex: { zh: "他因盗窃财物被逮捕。", pinyin: "Tā yīn dàoqiè cáiwù bèi dàibǔ.", ko: "그는 재물을 훔쳐서 체포되었다." } },
        { zh: "警惕", pinyin: "jǐngtì", ko: "경계하다, 경계심을 갖다", pos: "동사", ex: { zh: "我们要警惕网络诈骗。", pinyin: "Wǒmen yào jǐngtì wǎngluò zhàpiàn.", ko: "우리는 인터넷 사기를 경계해야 한다." } },
        { zh: "降临", pinyin: "jiànglín", ko: "도래하다, 강림하다", pos: "동사", ex: { zh: "夜幕降临后街灯亮了起来。", pinyin: "Yèmù jiànglín hòu jiēdēng liàngle qǐlái.", ko: "밤이 찾아오자 가로등이 켜졌다." } },
        { zh: "膝盖", pinyin: "xīgài", ko: "무릎", pos: "명사", ex: { zh: "他不小心摔伤了膝盖。", pinyin: "Tā bù xiǎoxīn shuāishāngle xīgài.", ko: "그는 실수로 넘어져서 무릎을 다쳤다." } },
        { zh: "舱", pinyin: "cāng", ko: "선실, 객실", pos: "명사", ex: { zh: "乘客们进入了飞机的机舱。", pinyin: "Chéngkèmen jìnrùle fēijī de jīcāng.", ko: "승객들이 비행기 객실로 들어갔다." } },
        { zh: "处置", pinyin: "chǔzhì", ko: "처리하다, 처분하다", pos: "동사", ex: { zh: "医生迅速处置了伤口。", pinyin: "Yīshēng xùnsù chǔzhìle shāngkǒu.", ko: "의사가 신속하게 상처를 처치했다." } },
        { zh: "视线", pinyin: "shìxiàn", ko: "시선", pos: "명사", ex: { zh: "高楼挡住了我们的视线。", pinyin: "Gāolóu dǎngzhùle wǒmen de shìxiàn.", ko: "높은 건물이 우리의 시선을 가로막았다." } },
        { zh: "间谍", pinyin: "jiàndié", ko: "간첩, 스파이", pos: "명사", ex: { zh: "他被怀疑是外国间谍。", pinyin: "Tā bèi huáiyí shì wàiguó jiàndié.", ko: "그는 외국 간첩으로 의심받고 있다." } },
        { zh: "投降", pinyin: "tóuxiáng", ko: "투항하다, 항복하다", pos: "동사", ex: { zh: "敌军最终选择了投降。", pinyin: "Díjūn zuìzhōng xuǎnzéle tóuxiáng.", ko: "적군은 결국 항복을 선택했다." } },
        { zh: "巡逻", pinyin: "xúnluó", ko: "순찰하다", pos: "동사", ex: { zh: "警察在街头巡逻。", pinyin: "Jǐngchá zài jiētóu xúnluó.", ko: "경찰이 거리에서 순찰하고 있다." } },
        { zh: "喉咙", pinyin: "hóulóng", ko: "목구멍", pos: "명사", ex: { zh: "他感冒后喉咙很痛。", pinyin: "Tā gǎnmào hòu hóulóng hěn tòng.", ko: "그는 감기에 걸려서 목이 매우 아프다." } },
        { zh: "隐瞒", pinyin: "yǐnmán", ko: "숨기다, 은폐하다", pos: "동사", ex: { zh: "他向警方隐瞒了真相。", pinyin: "Tā xiàng jǐngfāng yǐnmánle zhēnxiàng.", ko: "그는 경찰에게 진실을 숨겼다." } },
        { zh: "陈述", pinyin: "chénshù", ko: "진술하다, 서술하다", pos: "동사", ex: { zh: "证人向法庭陈述了事实。", pinyin: "Zhèngrén xiàng fǎtíng chénshùle shìshí.", ko: "증인이 법정에서 사실을 진술했다." } },
        { zh: "迈", pinyin: "mài", ko: "내딛다, 나아가다", pos: "동사", ex: { zh: "他迈着大步走向前方。", pinyin: "Tā màizhe dà bù zǒuxiàng qiánfāng.", ko: "그는 큰 걸음으로 앞으로 나아갔다." } },
        { zh: "垫", pinyin: "diàn", ko: "깔다, 받치다", pos: "동사", ex: { zh: "她在椅子上垫了一个软垫。", pinyin: "Tā zài yǐzi shàng diànle yí gè ruǎndiàn.", ko: "그녀는 의자 위에 부드러운 방석을 깔았다." } },
        { zh: "赞同", pinyin: "zàntóng", ko: "찬성하다, 동의하다", pos: "동사", ex: { zh: "大家都赞同他的意见。", pinyin: "Dàjiā dōu zàntóng tā de yìjiàn.", ko: "모두가 그의 의견에 찬성했다." } },
        { zh: "确切", pinyin: "quèqiè", ko: "확실하다, 정확하다", pos: "형용사", ex: { zh: "他没给出确切的答复。", pinyin: "Tā méi gěichū quèqiè de dáfù.", ko: "그는 확실한 답변을 주지 않았다." } },
        { zh: "不惜", pinyin: "bùxī", ko: "아끼지 않다, 서슴지 않다", pos: "동사", ex: { zh: "他不惜一切代价帮助朋友。", pinyin: "Tā bùxī yíqiè dàijià bāngzhù péngyou.", ko: "그는 어떤 대가도 아끼지 않고 친구를 도왔다." } },
        { zh: "发誓", pinyin: "fāshì", ko: "맹세하다", pos: "동사", ex: { zh: "他发誓再也不撒谎了。", pinyin: "Tā fāshì zài yě bù sāhuǎng le.", ko: "그는 다시는 거짓말하지 않겠다고 맹세했다." } },
        { zh: "共和国", pinyin: "gònghéguó", ko: "공화국", pos: "명사", ex: { zh: "这个国家是一个共和国。", pinyin: "Zhège guójiā shì yí gè gònghéguó.", ko: "이 나라는 공화국이다." } },
      ],
    },
  ],
};

export default themes;
