// Executes the real migration in isolated Postgres. No remote data or credentials.
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const modules=process.env.COMPOSER_TEST_MODULES;
if(!modules)throw new Error('COMPOSER_TEST_MODULES required');
const {PGlite}=await import(pathToFileURL(resolve(modules,'@electric-sql/pglite/dist/index.js')).href);
const db=new PGlite();
const owner='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
try{
 await db.exec(`create role authenticated;create role anon;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table reading_materials(id bigserial primary key,owner_id uuid,visibility text,title text,raw_text text,processed_json jsonb,created_at timestamptz default now());
 alter table reading_materials enable row level security;
 create policy owned on reading_materials for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
 grant usage on schema public,auth to authenticated,anon;grant all on reading_materials to authenticated;grant select on reading_materials to anon;grant usage on all sequences in schema public to authenticated;
 create unique index import_once on reading_materials(owner_id,(processed_json->'metadata'->>'importAttempt'));
 `);
 for(const file of ['20260907221311_material_document_editing.sql','20260908060607_source_passage_study.sql'])await db.exec(await readFile(new URL(`../../supabase/migrations/${file}`,import.meta.url),'utf8'));
 await db.exec(`set role authenticated;set test.uid='${owner}';`);
 const meta={status:'saved',metadata:{language:'French',composer:{version:1,assets:[{kind:'pdf',hash:'a'.repeat(64)},{kind:'epub',hash:'b'.repeat(64)}],links:[]}},sequence:[],dictionary:{}};
 const body='😀 Un café.\nUn café.\n次の文。';
 const parent=(await db.query('insert into reading_materials(owner_id,visibility,title,raw_text,processed_json) values($1,$2,$3,$4,$5) returning *',[owner,'private','Source title',body,meta])).rows[0];
 const source={version:1,kind:'body',textVersion:'plain-v1',quote:{exact:'Un café.',prefix:'😀 ',suffix:'\nUn café.\n次の文。',start:2,end:10}};
 const open=async(s=source,text='Un café.',lang='French',id=parent.id)=>(await db.query('select open_source_passage($1,$2,$3,$4) data',[id,s,text,lang])).rows[0].data;
 const child=await open();assert.equal(child.raw_text,'Un café.');assert.equal(child.visibility,'private');assert.equal(child.processed_json.metadata.composer.parentId,String(parent.id));
 assert.equal((await open()).id,child.id);
 const pdf={version:1,kind:'pdf',textVersion:'pdf-layer-v1',assetHash:'a'.repeat(64),page:2,quote:{exact:'Same words.',prefix:'',suffix:'',start:0,end:11}};
 const firstPdf=await open(pdf,'Same words.','English');const otherPage=await open({...pdf,page:3},'Same words.','English');assert.notEqual(firstPdf.id,otherPage.id);
 for(const invalid of [{...source,kind:null},{...source,textVersion:null},{...source,textVersion:'pdf-layer-v1'},{...source,quote:{}},{...pdf,assetHash:'c'.repeat(64)},{...pdf,page:0},{...pdf,page:null}])await assert.rejects(open(invalid),/PASSAGE_/);
 await assert.rejects(open(source,'x'.repeat(1501)),/PASSAGE_LENGTH/);await assert.rejects(open(source,'hello','German'),/PASSAGE_LANGUAGE/);
 await assert.rejects(db.query("update reading_materials set visibility='public' where id=$1",[child.id]),/source_passage_stays_private/);
 await assert.rejects(db.query("update reading_materials set processed_json=jsonb_set(processed_json,'{status}','\"completed\"') where id=$1",[child.id]),/PASSAGE_USE_ANALYSIS_RPC/);
 const attempt='00000000-0000-4000-8000-000000000010',attempt2='00000000-0000-4000-8000-000000000011';
 const analyze=async(id,run,json=null)=>(await db.query('select source_passage_analysis($1,$2,$3) data',[id,run,json])).rows[0].data;
 const claim=await analyze(child.id,attempt);assert.equal(claim.acquired,true);
 assert.equal((await analyze(child.id,attempt2)).acquired,false);
 const progress={...claim.material.processed_json,sequence:['id_0_0'],dictionary:{id_0_0:{text:'Un',pos:'冠詞'}},last_idx:0,status:'analyzing'};
 await assert.rejects(analyze(child.id,attempt2,progress),/PASSAGE_ANALYSIS_EXPIRED/);
 const final=await analyze(child.id,attempt,{...progress,status:'completed',metadata:{composer:{wrong:true},language:'Chinese'}});
 assert.deepEqual(final.material.processed_json.metadata.composer,child.processed_json.metadata.composer);assert.equal(final.material.processed_json.metadata.language,'French');
 assert.equal((await open()).processed_json.status,'completed');assert.equal((await analyze(child.id,attempt2)).acquired,false);
 await assert.rejects(analyze(child.id,attempt,{...progress,status:'analyzing'}),/PASSAGE_ANALYSIS_EXPIRED/);
 const doc={version:1,revision:'00000000-0000-4000-8000-000000000012',body:'Changed text',assets:[],retainedAssets:meta.metadata.composer.assets,links:[]};
 await db.query('update reading_materials set document_json=$1 where id=$2',[doc,parent.id]);
 await assert.rejects(open(),/PASSAGE_SOURCE_CHANGED/);
 await assert.rejects(open({...source,quote:{...source.quote,exact:'Un café',end:9}},'Un café'),/PASSAGE_SOURCE_CHANGED/);
 assert.equal((await open(pdf,'Same words.','English')).id,firstPdf.id);
 const preserved=(await db.query('select * from reading_materials where id=$1',[parent.id])).rows[0];assert.equal(preserved.raw_text,body);assert.deepEqual(preserved.processed_json,meta);
 await db.exec(`set test.uid='${other}';`);assert.equal((await db.query('select * from reading_materials')).rows.length,0);await assert.rejects(open(),/PASSAGE_ACCESS/);await assert.rejects(analyze(child.id,attempt),/PASSAGE_ACCESS/);
 await db.exec('reset role;set role anon;');await assert.rejects(open(),/permission denied/);assert.equal((await db.query('select * from reading_materials')).rows.length,0);
 console.log('PASS: real SQL, private source snapshots, Unicode positions, same-source idempotency, distinct-page identity, invalid-source rejection, immutable raw/metadata, retained source, run lease, stale write guard, non-owner/anon isolation.');
}finally{await db.close();}
