import {describe,it,expect,vi} from 'vitest';
import {quoteRange,findPassageQuote,samePassageSource,passageBlocks,sourcePassageHref,openSourcePassage} from '../sourcePassage';
import {runPassageAnalysis,requestPassageAnalysis,takePassageAnalysis} from '../passageAnalysis';
const source={version:1,kind:'body',textVersion:'plain-v1',revision:'r1'};
const material={id:22,owner_id:'owner',raw_text:'First.\nSecond.',processed_json:{status:'pending',sequence:[],dictionary:{},metadata:{language:'English',composer:{version:1,role:'study',parentId:'12',passage:source}}}};
describe('source passage provenance',()=>{
 it('uses code points without changing accents or Japanese source',()=>{const text='😀 Café e\u0301\n次の文。';const q=quoteRange(text,2,9);expect(q.exact).toBe('Café e\u0301');expect(findPassageQuote(text,q)).toEqual({start:2,end:9});expect(quoteRange(text,0,500)).toBeNull();});
 it('disambiguates repeated text, never guesses between ambiguous matches',()=>{const text='same / same / same';expect(findPassageQuote(text,{exact:'same'})).toBeNull();expect(findPassageQuote(text,quoteRange(text,7,11))).toEqual({start:7,end:11});expect(findPassageQuote('ああああ',quoteRange('ああああ',1,3))).toEqual({start:1,end:3});});
 it('does not return a previous body revision or another file/page',()=>{expect(samePassageSource(source,{...source,revision:'r2'})).toBe(false);expect(samePassageSource({...source,kind:'pdf',assetHash:'a',page:2},{...source,kind:'pdf',assetHash:'a',page:3})).toBe(false);});
 it('preserves real block offsets and builds a safe origin route',()=>{expect(passageBlocks('😀\n\nBonjour.')).toEqual([{text:'😀',start:0,end:1},{text:'Bonjour.',start:3,end:11}]);expect(sourcePassageHref(material,'https://evil.example')).toBe('/viewer/12?passage=22&returnTo=%2Fmaterials');});
 it('bounds the actual study text before calling the server',async()=>{const client={rpc:vi.fn()};await expect(openSourcePassage(client,material,source,'a'.repeat(1501),'English')).rejects.toThrow('PASSAGE_LENGTH');await expect(openSourcePassage(client,material,source,'hello','German')).rejects.toThrow('PASSAGE_LANGUAGE');expect(client.rpc).not.toHaveBeenCalled();});
});
describe('analysis intent and run',()=>{
 it('consumes an explicit action once, scoped to the account',()=>{requestPassageAnalysis('one',22);expect(takePassageAnalysis('two',22)).toBe(false);expect(takePassageAnalysis('one',22)).toBe(true);expect(takePassageAnalysis('one',22)).toBe(false);});
 it('reuses completed or concurrently leased data without an analysis request',async()=>{const analyze=vi.fn(),client={rpc:vi.fn().mockResolvedValue({data:{acquired:false,material:{...material,processed_json:{...material.processed_json,status:'completed'}}}})};const result=await runPassageAnalysis(client,material,new AbortController().signal,analyze);expect(result.status).toBe('completed');expect(analyze).not.toHaveBeenCalled();});
 it('persists batches and final status on the same run, never inserts another material',async()=>{const calls=[];const client={rpc:vi.fn(async(name,p)=>{calls.push(p);return {data:{acquired:true,material:{...material,processed_json:p.p_json||{...material.processed_json,status:'analyzing'}}}};})};const analyze=vi.fn(async(text,signal,{onBatch,metadata})=>{const j={sequence:['id_0_0'],dictionary:{id_0_0:{text:'First'}},metadata,status:'completed'};await onBatch({currentJson:j});return j;});await runPassageAnalysis(client,material,new AbortController().signal,analyze);expect(calls).toHaveLength(3);expect(calls[1].p_json.status).toBe('analyzing');expect(calls[2].p_json.status).toBe('completed');expect(new Set(calls.map(p=>p.p_attempt)).size).toBe(1);});
 it('releases an aborted preparation without replacing the selected source',async()=>{const controller=new AbortController();controller.abort();const calls=[];const client={rpc:vi.fn(async(name,p)=>{calls.push(p);return {data:{acquired:true,material:{...material,processed_json:p.p_json||material.processed_json}}};})};await expect(runPassageAnalysis(client,material,controller.signal,vi.fn())).rejects.toThrow('Aborted');expect(calls.at(-1).p_json.status).toBe('pending');expect(calls.at(-1).p_json.metadata.composer.passage).toEqual(source);});
});
