import {beforeEach,it,expect,vi} from 'vitest';
const {auth}=vi.hoisted(()=>({auth:vi.fn()}));vi.mock('@/lib/supabaseServer',()=>({requireUser:auth}));
import {GET,POST,PUT} from '../../app/api/classroom/boards/route';
import {packBoard,BOARD_BUCKET} from '../teachingBoardCloud';
import {emptyBoard} from '../teachingBoard';
const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',op='33333333-3333-4333-8333-333333333333';
const root={id:1,owner_id:owner,processed_json:{metadata:{team:{key:'fixture',root:true,lang:'Chinese'}}}};
const req=(body,method='POST')=>new Request('http://localhost/api/classroom/boards?rootId=1&day=2026-09-16',{method,body:method==='GET'?undefined:JSON.stringify(body)});
function db(results){const calls=[];return {calls,rpc:vi.fn(async()=>({data:{id,revision:op}})),storage:{from:vi.fn(()=>({download:vi.fn(async()=>({data:new Blob(['bad'])}))}))},from(table){const c={table,filters:[]};calls.push(c);const q={select(v){c.select=v;return q;},eq(...v){c.filters.push(v);return q;},not(){return q;},order(){return q;},limit(){return q;},maybeSingle(){return Promise.resolve(results.shift());},then(resolve,reject){return Promise.resolve(results.shift()).then(resolve,reject);}};return q;}};}
beforeEach(()=>auth.mockReset());
it('requires auth on all API operations',async()=>{auth.mockResolvedValue({error:'로그인 필요',status:401});for(const [fn,method]of [[GET,'GET'],[POST,'POST'],[PUT,'PUT']])expect((await fn(req({},method))).status).toBe(401);});
it('rejects students or another owner even if a loose database returned the root',async()=>{for(const candidate of [null,{...root,owner_id:'other'},{...root,processed_json:{}}]){const client=db([{data:candidate}]);auth.mockResolvedValue({user:{id:owner},supabase:client});expect((await GET(req({},'GET'))).status).toBe(403);expect(client.rpc).not.toHaveBeenCalled();}});
it('keeps board queries in the private table scoped to the teacher and team',async()=>{const client=db([{data:root},{data:null}]);auth.mockResolvedValue({user:{id:owner},supabase:client});const response=await GET(req({},'GET'));expect(response.status).toBe(200);expect(await response.json()).toEqual({board:null});expect(client.calls[1]).toMatchObject({table:'class_teaching_boards',filters:[['owner_id',owner],['root_id','1'],['day','2026-09-16']]});});
it('does not hide missing migrations as an empty account board',async()=>{const client=db([{data:root},{error:{code:'42P01'}}]);auth.mockResolvedValue({user:{id:owner},supabase:client});expect((await GET(req({},'GET'))).status).toBe(503);});
it('does not upload or commit against a stale revision',async()=>{const client=db([{data:root},{data:{id,owner_id:owner,revision:op}}]);auth.mockResolvedValue({user:{id:owner},supabase:client});const {manifest}=await packBoard(emptyBoard('p'));expect((await PUT(req({rootId:1,day:'2026-09-16',revision:null,operation:id,manifest},'PUT'))).status).toBe(409);expect(client.rpc).not.toHaveBeenCalled();expect(client.storage.from).not.toHaveBeenCalled();});
it('verifies uploaded bytes and hash before CAS and never trusts a path in the request',async()=>{
 const client=db([{data:root},{data:{id,owner_id:owner,revision:null}}]);auth.mockResolvedValue({user:{id:owner},supabase:client});const {manifest,files}=await packBoard(emptyBoard('p'));const download=vi.fn(async()=>({data:new Blob([files[0].text])}));client.storage.from.mockReturnValue({download});
 const response=await PUT(req({rootId:1,day:'2026-09-16',revision:null,operation:op,manifest:{...manifest,path:'other-user'}},'PUT'));
 expect(response.status).toBe(200);expect(client.storage.from).toHaveBeenCalledWith(BOARD_BUCKET);expect(download).toHaveBeenCalledWith(`${owner}/${id}/${files[0].hash}.json`);expect(client.rpc).toHaveBeenCalledWith('teaching_board_commit',expect.objectContaining({p_expected:null,p_operation:op,p_manifest:manifest}));
});
it('rejects corrupt uploaded pages without changing the head',async()=>{const client=db([{data:root},{data:{id,owner_id:owner,revision:null}}]);auth.mockResolvedValue({user:{id:owner},supabase:client});const {manifest}=await packBoard(emptyBoard('p'));expect((await PUT(req({rootId:1,day:'2026-09-16',revision:null,operation:op,manifest},'PUT'))).status).toBe(400);expect(client.rpc).not.toHaveBeenCalled();});
it('rejects invalid days and caps request metadata before database writes',async()=>{const client=db([{data:root}]);auth.mockResolvedValue({user:{id:owner},supabase:client});expect((await POST(req({rootId:1,day:'2026-02-30'}))).status).toBe(400);expect((await PUT(req({rootId:1,day:'x'.repeat(20001)},'PUT'))).status).toBe(413);expect(client.rpc).not.toHaveBeenCalled();});
