import {beforeEach,describe,it,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({user:null,scoped:null,mapping:null,source:null,canClass:false,rows:[],rpc:vi.fn(),replay:null}));
const query=result=>{const q={select:()=>q,eq:()=>q,order:()=>Promise.resolve({data:result}),in:()=>q,limit:()=>Promise.resolve({data:result}),maybeSingle:()=>Promise.resolve({data:result})};return q;};
vi.mock('@supabase/supabase-js',()=>({createClient:()=>({from:()=>query(m.scoped)})}));
vi.mock('@/lib/server/auth',()=>({requireUser:async()=>m.user?{user:m.user}:{error:'login',status:401}}));
vi.mock('@/lib/server/classIndex',()=>({serviceClient:()=>({from:table=>query(table==='reading_materials'?m.source:table==='class_material_copies'?m.mapping:table==='textbook_annotations'?m.rows:m.replay),rpc:m.rpc}),materialBelongsToTeam:row=>row?.owner_id==='teacher'&&row?.processed_json?.metadata?.book?.key==='book'}));
vi.mock('@/app/api/class/[team]/route',()=>({authorizeTeamRequest:async()=>m.canClass?{root:{owner_id:'teacher'},team:{bookKey:'book'}}:{error:Response.json({error:'locked'},{status:401})}}));
import {GET,POST} from '@/app/api/materials/[id]/annotations/route';
import {makeTextbookAnchor} from '../textbookAnnotations';
const material=()=>({id:2,owner_id:'teacher',processed_json:{sequence:['a'],dictionary:{a:{text:'图书馆'}},metadata:{book:{key:'book'}}}});
const call=(method='GET',body,team='')=>{const req=new Request(`https://manabi.invalid/api/materials/2/annotations${team?'?team='+team:''}`,{method,headers:{...(m.user?{Authorization:'Bearer fixture'}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return (method==='POST'?POST:GET)(req,{params:Promise.resolve({id:'2'})});};
const body=()=>({operation:crypto.randomUUID(),annotation:{id:crypto.randomUUID(),revision:0,archived:false,anchor:makeTextbookAnchor(material().processed_json,'a'),body:'주의점'}});
beforeEach(()=>{Object.assign(m,{user:{id:'teacher'},scoped:material(),source:material(),mapping:null,rows:[],replay:null,canClass:false});m.rpc.mockReset().mockResolvedValue({data:{id:'saved'}});});
describe('textbook annotations permissions',()=>{
 it('allows existing material owner to add',async()=>{expect((await call('POST',body())).status).toBe(200);expect(m.rpc.mock.calls[0][1].p_actor).toBe('teacher');});
 it('rejects a student write even if their profile is client-labelled admin',async()=>{m.user={id:'student',user_metadata:{role:'admin'}};expect((await call('POST',body())).status).toBe(403);expect(m.rpc).not.toHaveBeenCalled();});
 it('does not treat mutable source_ref as authority',async()=>{m.user={id:'student'};m.scoped=null;m.source.processed_json.metadata.book.key='other';m.canClass=true;expect((await call('GET',null,'class')).status).toBe(403);});
 it('canonical copy requires a current capability to read private source notes',async()=>{m.user={id:'student'};m.scoped={...material(),owner_id:'student'};m.mapping={source_material_id:20};expect((await call()).status).toBe(403);expect((await call('GET',null,'class')).status).toBe(401);m.canClass=true;const response=await call('GET',null,'class');expect(response.status).toBe(200);expect((await response.json()).canEdit).toBe(false);});
 it('canonical copy can read its publicly accessible source without a team token',async()=>{m.user={id:'student'};m.scoped={...material(),owner_id:'student'};m.mapping={source_material_id:2};const r=await call();expect(r.status).toBe(200);expect((await r.json()).canEdit).toBe(false);});
 it('canonical copy never edits the common source',async()=>{m.user={id:'student'};m.scoped={...material(),owner_id:'student'};m.mapping={source_material_id:20};m.canClass=true;expect((await call('POST',body(),'class')).status).toBe(403);});
 it('allows unlocked guest read but no guest write',async()=>{m.user=null;m.scoped=null;m.canClass=true;expect((await call('GET',null,'class')).status).toBe(200);expect((await call('POST',body(),'class')).status).toBe(403);});
 it('rejects forged location before calling the mutation',async()=>{const b=body();b.annotation.anchor.exact='其他';expect((await call('POST',b)).status).toBe(409);expect(m.rpc).not.toHaveBeenCalled();});
 it('marks revision conflicts distinctly for safe editing',async()=>{m.rpc.mockResolvedValue({error:{code:'40001'}});const r=await call('POST',body());expect(r.status).toBe(409);expect((await r.json()).conflict).toBe(true);});
 it('invalid UUID and oversized note never enter SQL',async()=>{const b=body();b.operation='bad';expect((await call('POST',b)).status).toBe(400);b.operation=crypto.randomUUID();b.annotation.body='x'.repeat(2001);expect((await call('POST',b)).status).toBe(400);expect(m.rpc).not.toHaveBeenCalled();});
});
